### ISSUE TITLE
Crash on using existing DB or creating new

### ISSUE THREAD

**Issue by mrjavum** [moneymanagerex/moneymanagerex#1001]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.1
  - [ ] 1.2.x
  - [ ] 1.1 or older
On trying to use my existing DB, which works fine on Windows 1.3.0 version, or on creating new DB I have a crash:
[mmex.xml.zip](https://github.com/moneymanagerex/moneymanagerex/files/692230/mmex.xml.zip)

**Comment by vomikan** [comment]
What is OS name?

**Comment by mrjavum** [comment]
Arch Linux:
`Linux archie 4.9.1-1-ARCH #1 SMP PREEMPT Fri Jan 6 20:42:57 CET 2017 x86_64 GNU/Linux`

**Comment by ni1son** [comment]
I have the same problem. When I'm trying to open existing db this error appear:
15:54:41: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]: no such column: STATEMENTLOCKED
15:54:41: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]: no such column: STATEMENTLOCKED

And after creating new db, more precisely after pressing "Ok" button in "Edit account" window, the program crush too.

My OS:
Linux kvado 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

[mmex.xml.txt](https://github.com/moneymanagerex/moneymanagerex/files/693494/mmex.xml.txt)

**Comment by gabriele-v** [comment]
https://sourceforge.net/p/moneymanagerex/bugs/927/?limit=25

**Comment by blueyestar** [comment]
I have same issue on Windows 7 x64.
It crashed when set currency.
