### ISSUE TITLE
'Duplicate' status of a transaction

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1012]
Related issue is #1008 
After import QIF file it may be several duplicate transactions. In fact it the same but has affect to an account balance. 

I think it has sense to fix it and made the 'Duplicate' transactions balance equal zero.

**Comment by Spoker** [comment]
I have alwasy wondered why a duplicate transaction had influence on the balance. In my opinion, it should not. I agree that duplicate transactions should not have an effect on the balance.

**Comment by vomikan** [comment]
@Spoker thank you for feedback

**Comment by vomikan** [comment]
@MisterY what do you think about it?

**Comment by MisterY** [comment]
Hm, I'm not sure what makes a transaction"duplicate". Should having a same date, payee, amount, and a category automatically be considered a duplicate?
Should a transfer automatically be ruled out as a duplicate if there is a transfer between the same accounts on the same date?
I would not make those assumptions.

Some sort of duplicate matching would be useful as a separate tool, perhaps? That way the user has the last word on what really is a duplicate and what is not. The importing should not make such an assumption, I believe. Quicken also suggests the matching and I find it extremely annoying as in 99.9% of the cases I have no duplicate transactions.
