### ISSUE TITLE
PPA repository is down

### ISSUE THREAD

**Issue by ryhaberecht** [moneymanagerex/moneymanagerex#1013]
https://launchpad.net/~dwrj87/+archive/ubuntu/mmex-test/ is down.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [x] 1.2.x
  - [x] 1.1 or older

**Comment by stef145g** [comment]
The user who created this was on GitHub but has left and deleted his account.
It appears that he has also deleted the account on Launchpad.net

**Comment by vomikan** [comment]
http://forum.moneymanagerex.org/viewtopic.php?f=25&t=6856

**Comment by akovalyov** [comment]
For those who miss the app on Linux - I have created https://github.com/akovalyov/subuser-mmex. It is highly experimental and there are a couple of bugs still (mostly with lang files), but at least it works - https://github.com/akovalyov/subuser-mmex

**Comment by vomikan** [comment]
Join us in slack

**Comment by vomikan** [comment]
@akovalyov  join us in Slack

**Comment by efDidymos** [comment]
Hello all, take a look at https://github.com/moneymanagerex/moneymanagerex/issues/950#issuecomment-284143691

**Comment by vomikan** [comment]
I am owner of  https://launchpad.net/mmex but can't build PPA

**Comment by akovalyov** [comment]
@vomikan maybe https://packagecloud.io/ can be an option? It has a plan for open source projects, but you need to contact support.

**Comment by ryhaberecht** [comment]
Maybe the OpenSUSE Build Service can be of use, too: [https://build.opensuse.org/](url)

**Comment by vomikan** [comment]
I've created the moneymanager account in packagecloud.io
I don't undestand what kind of package should be uploaded.
I any volunteers please be free to try. Ask the password by e-mail vomikan @ mail . ru

**Comment by vomikan** [comment]
Also
Developers and users chat at moneymanagerex.slack.com.
Leave your email in comment or email us for the slack invitation!

**Comment by MartinX3** [comment]
> https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu  xenial Release
Still down

> The repository 'https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu xenial Release' does not have a Release file.Data from such a repository can't be authenticated and is therefore potentially dangerous to use.See apt-secure(8) manpage for repository creation and user configuration details.Fehlschlag beim Holen von https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu/dists/xenial/main/source/Sources  404  Not FoundEinige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

**Comment by vomikan** [comment]
https://packagecloud.io/moneymanagerex/moneymanagerex
