### ISSUE TITLE
Right click one transaction issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1016]
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x

[If I right click one transaction](http://forum.moneymanagerex.org/posting.php?mode=quote&f=23&p=14628) (and get the right-click contect menu), then choose nothing from that menu and right-click another transaction instead, the first transaction seems to stay selected. Is this expected?

**Comment by vomikan** [comment]
I can't reproduce this.

**Comment by Spoker** [comment]
I could reproduce this on v1.3.1 but not on 1.2.7.

**Comment by vomikan** [comment]
In mmex v1.3.0 multiselect is on. If you select another line as result selected both.
