### ISSUE TITLE
Mac Downloads are not available!!

### ISSUE THREAD

**Issue by vinodraut** [moneymanagerex/moneymanagerex#1017]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by omalleypat** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.3.1
