### ISSUE TITLE
Null Pointer Crash

### ISSUE THREAD

**Issue by BentleyJOakes** [moneymanagerex/moneymanagerex#1019]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Issue:
Thread 1 "mmex" received signal SIGSEGV, Segmentation fault.
0x000000000074e2a0 in mmDateRange::destroy() ()
(gdb) bt
#0  0x000000000074e2a0 in mmDateRange::destroy() ()
#1  0x0000000000639220 in mmHomePagePanel::getData() (this=0x1128a10) at ../src/mmhomepagepanel.cpp:559
#2  0x0000000000638878 in mmHomePagePanel::createHTML() (this=0x1128a10) at ../src/mmhomepagepanel.cpp:519

Problem Location:
src/mmhomepagepanel.cpp Line 559
date_range_->destroy();

Suggestion:
Add if (date_range_) before this line. This prevents the crash.

Note:
The crash may require having accounts from a previous version of MoneyManagerEx.

**Comment by stef145g** [comment]
Thanks for the patch.
This has also been added to the v1.3.x branch
