### ISSUE TITLE
Auto linking of transactions continuation of #560

### ISSUE THREAD

**Issue by chris3081** [moneymanagerex/moneymanagerex#1025]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

This was mentioned in #560 but that one has been closed down. 

It would be good to have a function to identify and link together transactions based on criteria. In my case when I import my bank statements the transfers I have made between 2 accounts show up as a withdraw in one and a deposit in the other, both have a matching receipt number in the notes field. It would be good if these could be identified and converted to transfers automatically.

**Comment by vomikan** [comment]
[GRM](https://sourceforge.net/p/moneymanagerex/wiki/General%20Report%20Manager/)
Can halp in that case.

**Comment by vomikan** [comment]
I have already made somthing like this in case #1008 but for 'Transfer' transactions type.

**Comment by Spoker** [comment]
If manual correction is necessary, this might help also:
https://github.com/moneymanagerex/moneymanagerex/issues/909

**Comment by vomikan** [comment]
@chris3081 Could you tru this report?

[Duplicates_v1.grm.txt](https://github.com/moneymanagerex/moneymanagerex/files/709135/Duplicates_v1.grm.txt)

**Comment by vomikan** [comment]
http://forum.moneymanagerex.org/viewtopic.php?f=16&t=6922

**Comment by chris3081** [comment]
Hi @vomikan that one picks up entries but not the ones that are transfers

**Comment by vomikan** [comment]
It's by design, the report shows deposit+withdrawal pair.

**Comment by chris3081** [comment]
Oh Ok, What I'm trying to do is to match the withdrawal transaction in account A with the matching Deposit transaction in Account B. The notes field in both transactions has the description of 'Internal Transfer - Receipt xxxxxxx' where xxxxx is a receipt number.

**Comment by vomikan** [comment]
The report l've provided should do that.
Run, click first link and change deposit transaction status to void.
Then click second link in the same line and change withdraval transaction type to transfer.

**Comment by chris3081** [comment]
Thanks @vomikan I've managed to adjust the SQL to pick up the withdrawals I need, however it looks like sqlite doesn't support updates to table aliases. Would you recommend using the java script in the template or lua to make the report iterate through each of the transactions making the changes?

from what I can see I need to set d.status='d' and w.toaccountid = d.accountid

**Comment by vomikan** [comment]
SQL can't update rhe data (it has been blocked).
But from the report you can open transaction edit dialogue. It's working?

**Comment by chris3081** [comment]
Yes its definitely working, but with so many in the report is it possible to automate the task of converting each of these?

**Comment by vomikan** [comment]
@chris3081 I've added functionality that are you looking for.
How to use:
Select several (>=2) transactions in some account then change a type to 'Transfer'
![screenshot 57](https://cloud.githubusercontent.com/assets/6836805/23099990/a8262d4a-f685-11e6-969b-b0791c3a28be.jpg)
