### ISSUE TITLE
Frequest crashes when editing category list

### ISSUE THREAD

**Issue by kennydrobnack** [moneymanagerex/moneymanagerex#1026]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ X] Windows
  - [ X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I've used MMEX before and decided to give the newest version a try. Attempting to set up a fresh MMEX database, I reorganized the categories to my liking. While editing the categories, I am getting frequent crashes of the application. This is on both Windows 10 and MacOS 10.12.2 using MMEX 1.3.0 from a fresh installation.

So far I have not found any specific way to reproduce the crash, but it seems to happen most often if I'm trying to create a new category while I'm creating or editing a transaction.

I have not tested to see if I get the same behavior on Linux.

**Comment by kennydrobnack** [comment]
Good news: it seems like I missed the memo that 1.3.1 was out and fixed this particular bug. Bad news is it looks like poking around the budgets and reports make it crash.

I'm going to close this issue and will open a new one if/when I can confirm exactly what is making it crash.

**Comment by stef145g** [comment]
Fix mentioned not related to this issue
