### ISSUE TITLE
Build errors using VS Community 2017 RC

### ISSUE THREAD

**Issue by stef145g** [moneymanagerex/moneymanagerex#1038]
- Checked OS  - Windows
- Checked MMEX version - 1.3.x

Testing builds using new version of MS VS

**Comment by stef145g** [comment]
Build configurations also added for mmex_tests for msvc_2015 and msvc_2017

**Comment by slodki** [comment]
It cannot be retested at appveyor after migration to cmake due to appveyor problem with VS2107 image
