### ISSUE TITLE
cant open db

### ISSUE THREAD

**Issue by Edvinaz** [moneymanagerex/moneymanagerex#1057]
When opening old db from 1.2.7 i'm getting error:
ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]: no such column: STATEMENTLOCKED

When i trying to create new db mmex crashes.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by guanlisheng** [comment]
@stef145g please have a look here

**Comment by stef145g** [comment]
Please refer Sourceforge.net for answer: https://sourceforge.net/p/moneymanagerex/bugs/927/
