### ISSUE TITLE
Exception SQL logic error or missing database

### ISSUE THREAD

**Issue by junpet** [moneymanagerex/moneymanagerex#1066]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
![screenshot 2017-02-23 20 15 20](https://cloud.githubusercontent.com/assets/3465278/23276348/3bb4bd38-fa0a-11e6-8c5f-a7b56768b2f1.png)
[log.txt](https://github.com/moneymanagerex/moneymanagerex/files/797560/log.txt)
![screenshot 2017-02-23 19 34 56](https://cloud.githubusercontent.com/assets/3465278/23276363/4686f47e-fa0a-11e6-98dc-557b0e586584.png)

**Comment by vomikan** [comment]
Please take a look at https://sourceforge.net/p/moneymanagerex/bugs/927/

**Comment by junpet** [comment]
Thanks. I found it.
