### ISSUE TITLE
Issues reading from a pre-existing database with 1.3.1

### ISSUE THREAD

**Issue by Dreamspectre** [moneymanagerex/moneymanagerex#1078]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I updated from 1.3.0 release to version 1.3.1 tonight, and upon opening the database I have been using for a few months now, was met with the errors listed in the attached log.

[MMEX Error log.txt](https://github.com/moneymanagerex/moneymanagerex/files/810382/MMEX.Error.log.txt)

**Comment by Dreamspectre** [comment]
To provide some additional information, this is happening with both 1.3.1 64bit for Windows, as well as the Android app (v. 2017.1.19.949). I was utilizing the database without issue (on Windows), closed the program, updated it, and was met with the errors in the log.

**Comment by vomikan** [comment]
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6969

https://sourceforge.net/p/moneymanagerex/bugs/927/
