### ISSUE TITLE
Custom Dates for GRM

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1085]
I suggest to add date ranges for GRM. 

![screenshot 75](https://cloud.githubusercontent.com/assets/6836805/23610025/f8c83844-0281-11e7-9325-ae5c351a6f0d.jpg)

This dates may be used in SQL script like &begin_date     &end_date
-  Check MMEX version
  - [x] 1.4.x

**Comment by vomikan** [comment]
@siena123 James, I need help with transfer parameters to SQL script.

Here may be code to replace placeholders to real data:
https://github.com/moneymanagerex/moneymanagerex/compare/master...vomikan:%231085?expand=1#diff-f8a5929a16cdeff021409c02a03484f3R169

I've attached test DB to see how parameters looks in GRM reports
[test7.zip](https://github.com/moneymanagerex/moneymanagerex/files/823788/test7.zip)

**Comment by vomikan** [comment]
I've attached test DB to see how parameters looks in GRM reports
[test7.zip](https://github.com/moneymanagerex/moneymanagerex/files/824783/test7.zip)

**Comment by siena123** [comment]
I see the direction you are going. I will look at the parameter transfer in more detail this weekend.

**Comment by vomikan** [comment]
@siena123 Please investigate the changes regarding this issue.
I think this way we can add more options for payees, categories etc.

**Comment by vomikan** [comment]
Help file update needed and samples

**Comment by vomikan** [comment]
There are four options available for sql script:
```&single_date
&begin_date
&end_date
&budget_years```

**Comment by vomikan** [comment]
For example for sql:
```select  '&budget_years' as year```
The report header will contain budget years choice:
![image](https://user-images.githubusercontent.com/6836805/38904242-f2c9d9a4-42b1-11e8-8b83-b2c78c71c59a.png)

**Comment by vomikan** [comment]
[test7.zip](https://github.com/moneymanagerex/moneymanagerex/files/1921958/test7.zip)

**Comment by gabriele-v** [comment]
@vomikan we can close this? Documentation seems good, or you have to add something else?
