### ISSUE TITLE
Update 1.27->1.32, deleted transactions came back

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#1090]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 
-  Check MMEX version
  - [X] 1.3.2
  - [ ] 1.2.x
  - [ ] 1.1 or older

As I updated to version 1.3.2 I noticed several void transactions, found out they were deleted transactions somehow resurrected. Should I keep them in order to keep the ID database field without holes or can I safely delete them and have IDs like 1,2,3,5,8,12,etc:?

**Comment by vomikan** [comment]
It was an option by right mouse click like 'hide void transactions'. May be all transactions was void not deleted?
