### ISSUE TITLE
Navigation tree disappears when editing an account

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#1091]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 
- Check MMEX version
  - [X] 1.3.2
  - [ ] 1.2.x
  - [ ] 1.1 or older

Items become invisible, I have to click them or collapse and then expand the tree to make them reappear (homepage doesn't disappear)

**Comment by vomikan** [comment]
Is that issue the same?
https://github.com/moneymanagerex/moneymanagerex/issues/658

**Comment by J316** [comment]
So it seems, and #773 seems to be related as well.
