### ISSUE TITLE
Change type to transfer for multiple transactions

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1097]
It's continue of #909 
Related forum link:
http://forum.moneymanagerex.org/viewtopic.php?f=10&t=6999

**Comment by slodki** [comment]
@vomikan This should have status "won't fix" or "on hold" or something? The milestone 1.4.x is still valid?

**Comment by jaiminim** [comment]
Is this feature available now?

**Comment by vomikan** [comment]
This feature is not available.
