### ISSUE TITLE
Calendar's weeks start 

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1105]
http://forum.moneymanagerex.org/viewtopic.php?f=10&t=7015&p=15026#p15026
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [x] 1.2.x

![screenshot 104](https://cloud.githubusercontent.com/assets/6836805/24005036/f5ec4ec2-0a78-11e7-8b66-e18c1773890a.jpg)

**Comment by vomikan** [comment]
http://docs.wxwidgets.org/trunk/classwx_calendar_ctrl.html

This class supports the following styles:

wxCAL_SUNDAY_FIRST:
Show Sunday as the first day in the week (not in wxGTK)
wxCAL_MONDAY_FIRST:
Show Monday as the first day in the week (not in wxGTK)

**Comment by slodki** [comment]
> If neither the wxCAL_SUNDAY_FIRST or wxCAL_MONDAY_FIRST style is given, the first day of the week is determined from operating system's settings, if possible. The native wxGTK calendar chooses the first weekday based on locale, and these styles have no effect on it.

**Comment by lonemadmax** [comment]
There's no wxCalendarCtrl anymore, just date pickers, so maybe this should be closed?

**Comment by whalley** [comment]
Agreed, we should close.
