### ISSUE TITLE
1.3.3 mac builds not available

### ISSUE THREAD

**Issue by vinodraut** [moneymanagerex/moneymanagerex#1106]
mac builds not available
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by bingalls** [comment]
Existing DMGs extract, but fail to install on El Capitain, with error message "Damaged or Incomplete"
It is also challenging, to build source, even with Homebrew installed.

**Comment by tomasfrtala** [comment]
Fixed with #1123
