### ISSUE TITLE
Can't build under Ubuntu 16.10

### ISSUE THREAD

**Issue by alitor** [moneymanagerex/moneymanagerex#1107]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by ferdiga** [comment]
did you do  
 `git submodule update --init` ?

**Comment by vomikan** [comment]
Please more details
