### ISSUE TITLE
[1.3.3] Crash on Arch Linux when adding stock transaction

### ISSUE THREAD

**Issue by mek-x** [moneymanagerex/moneymanagerex#1111]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I have crashes when trying to `Add Stock Transactions` to a stock in stock portfolio. `View Stock Transactions` works without crashes. I'm using version 1.3.3 on Arch Linux. Windows stable version [1.3.1] works fine using Wine. Attaching crash report:
[mmex.zip](https://github.com/moneymanagerex/moneymanagerex/files/878661/mmex.zip)

**Comment by stef145g** [comment]
Thanks for providing a fix for this.

**Comment by mek-x** [comment]
No prob :)
