### ISSUE TITLE
Mmex requires (the default) case insensitive file system for Mac OS X.

### ISSUE THREAD

**Issue by bingalls** [moneymanagerex/moneymanagerex#1113]
OS
  - [x] Mac OSX    10.11 El Capitain
 Check MMEX version
  - [x] 1.3.x  and all versions.
All Existing DMGs extract, but fail to install. Run time returns error message _Damaged or Incomplete_
mmex can run from its DMG image, but not from my HFS+ filesystem.
I believe that my *case-sensitive* file system causes these errors.

Documentation to build mmex from source is stale; I finally found it, and updating it at http://forum.moneymanagerex.org/viewtopic.php?f=24&t=6378&start=10

FWIW, OSX docker itself, & the Xenial Ubuntu build on VirtualBox have been challenging...

**Comment by tomasfrtala** [comment]
Fixed with #1123 you can also take look at newly created [doc](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.macOS.md). To the future the (github releases](https://github.com/moneymanagerex/moneymanagerex/releases) will hold also macOS installable package
