### ISSUE TITLE
Wrong language folder on Linux

### ISSUE THREAD

**Issue by mrjavum** [moneymanagerex/moneymanagerex#1114]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [*] Linux 
-  Check MMEX version
  - [*] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
Linux xxx 4.10.8-1-ARCH #1 SMP PREEMPT Fri Mar 31 16:50:19 CEST 2017 x86_64 GNU/Linux

The program searches .mo files in /usr/share/mmex/po/en directory, but language files are in /usr/share/mmex/po directory.

**Comment by tomasfrtala** [comment]
Fixed with #1123
