### ISSUE TITLE
Broken dropdown keyboard control

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#1116]
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

On New Transaction window `Account` and `From` dropdown control with keyboard is broken.
On `Status` or `Type` dropdowns, first down/up arrow hit opens dropdown list, consecutive arrow hits let me navigate on the list. On `Account` and `From`, first arrow hit opens dropdown and second hit closes it again.

It is especially disappointing when user is one step from appreciating the great benefit of filtering Payees by typing. When there  is one option left it is very tempting to just hit down arrow + space, but it does not work.

<img width="316" alt="new_transaction" src="https://cloud.githubusercontent.com/assets/2995498/24727777/9ca8db8e-1a57-11e7-903b-67fea5c86a17.png">

**Comment by michalkoza** [comment]
the comparison of New Transaction and Relocate Payee Dialog is the following:

- New Transaction - filtering works, keyboard navigation does not work
![new_transaction_and_money_manager_ex_-__users_mkoza_downloads_backup_2017-02-24_mmb](https://cloud.githubusercontent.com/assets/2995498/25216166/ab859fe8-25a1-11e7-844d-09491171e0e3.png)

- Relocate Payee - filtering and arrow navigation do not work. 
![relocate_payee_dialog_and_money_manager_ex_-__users_mkoza_downloads_backup_2017-02-24_mmb](https://cloud.githubusercontent.com/assets/2995498/25216155/9e414e90-25a1-11e7-8d46-d965e9708d61.png)

**Comment by vomikan** [comment]
I mean the left side field. It should autocomplete as well as the right field but dropdown menu is hiden.

**Comment by michalkoza** [comment]
Ok, then it works completely as plain text field for me.
It does not even "recognize" Payee once I type entire name.
By recognize I mean that in the New Transaction dialog when I type "apteka" it get automatically changed to "Apteka" with capital A. It does not occur on the relocate left widget.

Also note that on the right side field the dropdown menu does not appear as I type. I have to press the down arrow to see it.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/1117

**Comment by omalleypat** [comment]
I think this is a wxWidgets issue with autocomplete. I hacked together a custom autocomplete for Payee field in the transaction dialog a few years ago. A similar approach could be taken in the other fields.
