### ISSUE TITLE
Account dropdown filtering not working

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#1117]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

In New Transaction window in "Account" dropdown (same for "To" in case of Transfer transaction type), when I start typing an Account name it does not filter the list as it is for Payee dropdown. Navigation with keyboard is also not possible.

<img width="334" alt="new_transaction" src="https://cloud.githubusercontent.com/assets/2995498/24726600/49c494f2-1a53-11e7-836e-70e5b18f3e3b.png">

**Comment by vomikan** [comment]
@michalkoza could you compare the functionality of both widgets in 
Tools  - Relocation of ... - Payees ...
![screenshot 146](https://cloud.githubusercontent.com/assets/6836805/25169000/26fc1f8a-24ee-11e7-9a11-dc75218669a2.jpg)

**Comment by michalkoza** [comment]
Hey Nikolay,
I'm sorry I'm not sure what you would like me to compare...
If you mean "Relocate:" and "to:" from above screenshot, then "Relocate:" seems to be simple textfield. While "to:" is a dropdown with not working filtering and not working keyboard navigation.
![relocate_payee_dialog_and_money_manager_ex_-__users_mkoza_downloads_backup_2017-02-24_mmb](https://cloud.githubusercontent.com/assets/2995498/25216025/e3abd104-25a0-11e7-8bcf-a04ebbd6fb63.png)

Also I just noticed some confusion in the issue Summary and description. This issue was supposed to relate to Account dropdown and not Payee, sorry for that.

But since we are at Payees for the moment: the comparison of New Transaction and Relocate Payee Dialog is the following:

- New Transaction - filtering works, keyboard navigation does not work
- Relocate Payee - filtering and arrow navigation do not work. 
![new_transaction_and_money_manager_ex_-__users_mkoza_downloads_backup_2017-02-24_mmb](https://cloud.githubusercontent.com/assets/2995498/25216166/ab859fe8-25a1-11e7-844d-09491171e0e3.png)

![relocate_payee_dialog_and_money_manager_ex_-__users_mkoza_downloads_backup_2017-02-24_mmb](https://cloud.githubusercontent.com/assets/2995498/25216155/9e414e90-25a1-11e7-8d46-d965e9708d61.png)

**Comment by vomikan** [comment]
One #1117 issue enought.
