### ISSUE TITLE
Not ergonomic focus on Category browsing window

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#1118]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

On New Transaction in category selection window initial focus is on Expand checkbox.
<img width="307" alt="organize_categories_and_new_transaction" src="https://cloud.githubusercontent.com/assets/2995498/24726926/54fa67ba-1a54-11e7-93f9-ae9a5ce2f811.png">
As the best way to navigate there is to start typing a category name it would make much more sense to have initial focus on the categories list window
<img width="296" alt="organize_categories_and_new_transaction" src="https://cloud.githubusercontent.com/assets/2995498/24726948/6bbaa186-1a54-11e7-98a7-16fd5003b853.png">
Saving two additional tab hits for each category selection would be a lot.

**Comment by vomikan** [comment]
Here is nothing to fix becouse SetFocus already there:
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/categdialog.cpp#L121
It working fine in WIndows.

**Comment by michalkoza** [comment]
But it seems not to be working on a MAC :(
https://www.dropbox.com/s/xqecj52g02lzi6u/focus%20on%20a%20MAC.mov?dl=0

**Comment by vomikan** [comment]
From here:
https://forums.wxwidgets.org/viewtopic.php?t=18961
buttons and other non-text components getting focus is disabled by default on mac!
I will search a solution....

**Comment by vomikan** [comment]
We should try SetFocusIgnoringChildren()

**Comment by whalley** [comment]
Just tested on 1.3.6 MacOs build and this works as expected. On opening focus is on the category list and you can start typing straight away. Suggest we close.
