### ISSUE TITLE
Doing OK click from keyboard

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#1119]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

It would be very helpful to have a combination like Shift+Enter or cmd+Enter to work like clicking OK. For example but not only on New Transaction window.

Not only it seems there is no such shortcut but also OK button is not reachable with navigating using TAB key.

**Comment by vomikan** [comment]
For Windows it's Alt+O shortcut.

**Comment by michalkoza** [comment]
Ok thank you! On MAC cmd+o works. Very strange shortcut though... :)

**Comment by vomikan** [comment]
It's usual way for menu and buttons. In case if a label of the button is E&xit the shotcut is x.
For Windowd if Alt pressed all active buttons and menu items has underline marker.

**Comment by michalkoza** [comment]
Indeed it makes sense. Thanks. I just had in mind sth like alt+Enter or ctrl+Enter
