### ISSUE TITLE
Minor consequences of CMake update

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1126]
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Thought I would have a play with CMake on Windows just to try and gain some insights and keep the old grey cells ticking over.
After the CMake update to master branch, folder src no longer contains constants.h so mmex.sln in build/msw-vc-2017 no longer compiles with a simple download of the source.
I managed to get VS2017 Workbench to compile from the CMakelists.txt which generated constants.h so the old way now works.
I added ADD_DEFINITIONS(-D/MP) to CMakelists.txt as single thread compile was taking ages on an I7 processor.
In VS2017 when trying to run a Debug session after a Cmake compile it goes looking in Appdata for the mmex binary when it was put in CMAKE_SOURCE_DIR/bin.
I guess that this may have something to do with my lack of knowledge or VS2017's changes to CMake config or may be a bug. No big deal as mmex.sln works fine.

**Comment by tomasfrtala** [comment]
The idea behind generated files (_constants.h; .travis.yml and appveyor.yml_) is that the version of application is written only once at one place (in https://github.com/moneymanagerex/moneymanagerex/blob/master/CMakeLists.txt#L10). Then the CMake repleace the pattern name of variable in their templated version with correct values (see example in section _Adding a Version Number and Configured Header File_ https://cmake.org/cmake-tutorial/).

Have looked at https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.Windows.md#compile ?

Also @stef145g script can help you https://github.com/moneymanagerex/moneymanagerex/pull/1124#issuecomment-295259409

**Comment by grumpy235** [comment]
Tomas,
I understand the idea for version numbers, it was just a surprise when I updated my repository to the latest commit that I could no longer compile using mmex.sln from the build folder. I found INSTALL.Windows.md which has one very minor error in that "git checkout cmake" is no longer required. I am very new to working with Visual Studio (40years on IBM mainframes!) and could not find the VS2017 command prompt (I have since found it) so ran everything from an ordinary command prompt in CMAKE_SOURCE_DIR and that worked well from the instructions although I did have to download CMake and I went directly to generating mmex.sln rather than Makefiles. I guess had I worked from the VS2017 command prompt I would have found the CMake version bundled with VS2017 ?
Well done on getting CMake working from my limited reading it is not as straightforward as one might hope and for me getting used to a non-mainframe environment has been a challenge.

**Comment by tomasfrtala** [comment]
I think you will get into it very quick. It is not that hard as it looks like :) Starting from [Visual Studio 2017 the CMake is bundled](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/) and you can find it for example here `Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin`. But as was mentioned in the [installation instruction](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.Windows.md#compile) you need to run commands inside the VS2017 command prompt because it already has the CMake linked whereas the regular cmd.exe do not. Personally I do not work through Visual Studio I use [CLion](https://www.jetbrains.com/clion/) that allows me multi-platform work.

**Comment by grumpy235** [comment]
After your recent changes to cmake process, thought I would have another go at following doc/INSTALL.Windows.md.
Downloaded and compiled wxWidgets by using the relevant VS project file rather than nmake as that is the way I have always done it.
Downloaded mmex git repository and then ran the following

cd moneymanagerex\build - success
mkdir release - success
cd release - success
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ../../ - failed

Get the following message
D:\Projects\moneymanagerex\build\release>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ../../
'cmake' is not recognized as an internal or external command,operable program or batch file._

Which I guess is to be expected as I do not have cmake installed and there are no instructions to download cmake, the version bundled with VS2017 is not available.

**Comment by tomasfrtala** [comment]
If cmake is not present, please try to download install it [from official cmake](https://cmake.org/download/) site.

**Comment by tomasfrtala** [comment]
Or you can take a look at [readme for windows msvc 2015](https://github.com/moneymanagerex/moneymanagerex/tree/master/build/msw-vc-2015) or for [windows msvc 2017](https://github.com/moneymanagerex/moneymanagerex/tree/master/build/msw-vc-2017) in the build dir. Hope it helps you

**Comment by grumpy235** [comment]
The point I was trying to make was that the Windows.md document tells you to download Gettext and where to get it as a pre-req. but not cmake perhaps it should ?

**Comment by slodki** [comment]
Instructions from PR #1312 should allow close this issue IMHO

**Comment by grumpy235** [comment]
Looks like it, I'll give it a go later this week.
Thanks for all the hard work
