### ISSUE TITLE
Sourceforge abandoned by devs?

### ISSUE THREAD

**Issue by thomasboehm** [moneymanagerex/moneymanagerex#1131]
Are the devs still reading the tickets on sourceforge.net? One open ticket concerns me the most

**#962 Security flaws in Android app**
https://sourceforge.net/p/moneymanagerex/bugs/962/

In there someone from a security company found a security flaw in the Android app and asked who to contact. This ticket was **opened on 2016-12-03** and there is no reply and it is **still OPEN**. This doesn't fill me with confidence to use the app on Android.

But since updating to Android 7.1 it stopped working anyway
https://sourceforge.net/p/moneymanagerex/bugs/937/

**Comment by vomikan** [comment]
It's a good place to report any issues.

**Comment by thomasboehm** [comment]
Firstly, I'm not Erez and secondly I guess he didn't want to disclose the vulnerability publicly. You should reply on SF and let him know how he can contact the devs directly. I still can't believe that there was no reaction for more than 4 month to a possible vulnerability in a software which should handle my finances securely.

I was just looking for a solution why I can't run mmex on Android 7.1 anymore.

**Comment by vomikan** [comment]
Sorry, I thought that you are the one who reported the error.

To contact dev directly there are several options:
e-mail to developers @ moneymanagerex . org
Slack https://moneymanagerex.slack.com
