### ISSUE TITLE
Tooltips unreadable

### ISSUE THREAD

**Issue by OvermindDL1** [moneymanagerex/moneymanagerex#1142]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 
- Check MMEX version
  - [X] 1.4.0
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Tooltips when hovering over icons on the toolbar are unreadable, I've tried themeing GTK with light themes, dark themes, a variety of others and the tooltip never changes, which means the program is overriding the color from the OS, it is always light-gray background with white text.  Here it is with a dark GTK theme:
![image](https://cloud.githubusercontent.com/assets/401605/25626044/7c371c20-2f1b-11e7-9b34-7d3627b3a1a5.png)

Here it is with a light GTK theme:
![image](https://cloud.githubusercontent.com/assets/401605/25626097/a881175e-2f1b-11e7-82ac-64f58002633e.png)

Also tried changing the primary KDE theme (I'm using KDE 5.11 I think it was) to no avail, always displays the same unreadable text.

Simple fix likely, if the colors are being overridden as they are then the text color should probably be overridden to be black.  This build is from about 21 hours ago.

**Comment by OvermindDL1** [comment]
For note, this could be ignored and closed if you wish.  If colors are explicitly set it will be fixed, but this happens when, say, one is set (background/foreground color) but not the other, so it defaults to the system for the other.  It should just be a simple setting in the GTK theme file for the application, if you remove any reference to any line that toolbar it would probably fix it, though not tested.

**Comment by slodki** [comment]
Not only tool tips for icons are affected - but popups describing errors too:

![unreadable pop-up](https://cloud.githubusercontent.com/assets/3155552/25771758/b8c0fcf0-325a-11e7-9b23-2268581ee902.png)

Clean Kubuntu zesty install with default system/plasma/mmex color settings.

**Comment by slodki** [comment]
This is not MMEX but GTK style problem.

Adding this code at the end of the `~/.gtkrc-2.0`
```
style "my-tooltips"
{
  bg[NORMAL] = "#FFFFAF"
  fg[NORMAL] = "#000000"
}
widget "*tooltip*" style "my-tooltips"
```
fixes this issue. BTW not all colors combinations work for me - the example above gives:
![mmex-tooltip](https://user-images.githubusercontent.com/3155552/29272537-c4834d32-8100-11e7-9ac4-3c7dc8bf56f9.png)

**Comment by slodki** [comment]
Next workaround is to change GTK style to *Raleigh* using KDE *System Settings* applet:
![mmex-gtk-style](https://user-images.githubusercontent.com/3155552/29272751-b6e89d8e-8101-11e7-9c74-b1f8fd32f971.png)

*Raleigh* style should be default empty GTK style as defined in `/usr/share/themes/Raleigh/gtk-2.0/gtkrc`:
```
#
# This theme is the default theme if no other theme is selected.
#
```

But it gives ugly old style for all Gnome/GTK apps:
![mmex-tooltip-ugly](https://user-images.githubusercontent.com/3155552/29273225-c9d5f0fc-8103-11e7-8472-99f83f649c79.png)

**Comment by slodki** [comment]
You can always select GTK style at run-time for selected application starting it with `GTK2_RC_FILES` variable:
```shell
GTK2_RC_FILES=/usr/share/themes/Raleigh/gtk-2.0/gtkrc mmex
```
or
```shell
GTK2_RC_FILES=$HOME/my-super-buper-gtkrc-for-mmex mmex
```

All details available at [GTK+ 2 Reference Manual](https://developer.gnome.org/gtk2/stable/gtk2-Resource-Files.html#gtk2-Resource-Files.description).

**Comment by OvermindDL1** [comment]
Still, specifying a tooltip foreground color (black text) without specifying a background color is not a good default.  ^.^;

**Comment by slodki** [comment]
My default style on Kubuntu has both set:

in `/usr/share/themes/Breeze/gtk-2.0/widgets/styles`:
```
widget "gtk-tooltip*" style "tooltips"
```

in `/usr/share/themes/Breeze/gtk-2.0/widgets/misc`:
```
style "tooltips"
{
    xthickness  = 8
    ythickness  = 4
    
    bg[NORMAL]    = @tooltip_bg_color
    fg[NORMAL]    = @tooltip_fg_color
    bg[SELECTED]    = @tooltip_bg_color
}
```

in `/usr/share/themes/Breeze/gtk-2.0/gtkrc`:
```
gtk-color-scheme = "tooltip_fg_color:#eff0f1"
gtk-color-scheme = "tooltip_bg_color:#31363b"
```

but not working. Maybe different style selector overwrites one of the settings?

**Comment by OvermindDL1** [comment]
> My default style on Kubuntu has both set:

Not 'your' style, but the style definition in the program itself is overriding the theme only partially instead of entirely.

**Comment by slodki** [comment]
Could you point this at source? I cannot find this.
