### ISSUE TITLE
Navigation pane sometimes clears

### ISSUE THREAD

**Issue by OvermindDL1** [moneymanagerex/moneymanagerex#1143]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux - KDE, Ubuntu 16.10
-  Check MMEX version
  - [X] 1.4.x
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

While doing things like adding an account (or seemingly anything that changes the treeview in the Navigation pane) then the treeview in the Navigation pane completely clears except for the root node of "Home Page" (this happened while adding an account):
![image](https://cloud.githubusercontent.com/assets/401605/25626474/e025bfd8-2f1c-11e7-86ef-d1f1fc2dc3e0.png)

Sometimes it partially clears like (this happened while deleting the above test account):
![image](https://cloud.githubusercontent.com/assets/401605/25626491/ed0a8152-2f1c-11e7-954a-48efebf558df.png)

And it can be fixed by collapsing and expanding the root node of "Home Page" again in all cases, it is probably just missing a render message for the full pane after the treeview is modified (as the credit card account section was where the new account was in the treeview vertically, so it seems it is only re-rendering just that rectangle).

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/658
