### ISSUE TITLE
mmexini.db3 size

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1144]
mmexini.db3 file constantly grows.
~~~~~~
select count(*) from usage_v1 
~~~~~~
returns more than 1k records and the file size is 3Mb

This brings some troubles like:
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6990&hilit=mmexini.db3

**Comment by stef145g** [comment]
The incorporated fix will solve this problem
