### ISSUE TITLE
Does not work on Fedora 25

### ISSUE THREAD

**Issue by jjd24** [moneymanagerex/moneymanagerex#1149]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [ ] 1.4.x
  - [x] 1.3.x

**Comment by vomikan** [comment]
Is there any output?

**Comment by jjd24** [comment]
Following instructions for Fedora the installation of the rpm fails with
     wxWidgets-3_0-devel is needed by mmex-1.3.3-1.x86_64
Have reported this on MMEX forum, but no response. So took it up with the support team at Korora - the distro based on Fedora 25. They advise that this package is not valid for Fedora.and that line 355 in the build is being used in the Fedora build even though it relates to openSUSE.  They also say that CPACK_RPM_PACKAGE_REQUIRES isn't used for build requires - it used for adding binary rpm requires.

Please advise and help thiis work on Fedora 25. Thank you.

jjd24

**Comment by jjd24** [comment]
Please see the GitHub thread.

**Comment by tomasfrtala** [comment]
@jjd24 please check if you have all needed packages installed:
```
sudo yum -y update && sudo yum -y install \
cmake gcc-c++ gettext git gtk3-devel make rpm-build webkitgtk3-devel wxGTK3-devel
```
Also, have you take a look at our newly created test [repository](https://packagecloud.io/moneymanagerex/moneymanagerex/packages/fedora/25/mmex-1.4.0-1.x86_64.rpm)?

**Comment by jjd24** [comment]
Thank you for the swift response. I copied and pasted from the instructions to install the required packages but will re-run to double-check.
Is the test repository an alternative way of installing MMEX?

**Comment by tomasfrtala** [comment]
Installing MMEX can be done in two way:
- comfortably for user (from repository)
- manually for advanced users and developers (from sources)

**Comment by jjd24** [comment]
Thanks. Will try from the repository.

**Comment by jjd24** [comment]
No joy with repository.  "curl  etc" returns
bash : -s:  command not found
How do I overcome this?

**Comment by tomasfrtala** [comment]
have you installed curl?
```
sudo yum install curl
```

**Comment by jjd24** [comment]
Yes, curl is installed.

**Comment by leigh123linux** [comment]
@tomasfrtala  Your fedora repo isn't usable because you have used cpack wrong

gcc-c++ and wxWidgets-3_0-devel are build requirements not runtime, also wxWidgets-3_0-devel is a suse package name


https://github.com/moneymanagerex/moneymanagerex/blob/master/CMakeLists.txt#L355

mmex-1.4.0-1.x86_64.rpm was downloaded from your repository!

```
$ rpm -qp --info --requires '/home/leigh/Downloads/mmex-1.4.0-1.x86_64.rpm' 
Name        : mmex
Version     : 1.4.0
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : unknown
Size        : 25152596
License     : GPL-2+
Signature   : (none)
Source RPM  : mmex-1.4.0-1.src.rpm
Build Date  : Mon 01 May 2017 19:18:21 BST
Build Host  : 8a6f0bfd0b45
Relocations : /usr 
Vendor      : Humanity
Summary     : Simple to use financial management software
Description :
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.
/bin/sh
/bin/sh
/bin/sh
/bin/sh
gcc-c++
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.5)(64bit)
libstdc++.so.6(CXXABI_1.3.8)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libwx_baseu-3.0.so.0()(64bit)
libwx_baseu-3.0.so.0(WXU_3.0)(64bit)
libwx_baseu_net-3.0.so.0()(64bit)
libwx_baseu_net-3.0.so.0(WXU_3.0)(64bit)
libwx_baseu_xml-3.0.so.0()(64bit)
libwx_baseu_xml-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_adv-3.0.so.0()(64bit)
libwx_gtk3u_adv-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_aui-3.0.so.0()(64bit)
libwx_gtk3u_aui-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_core-3.0.so.0()(64bit)
libwx_gtk3u_core-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_html-3.0.so.0()(64bit)
libwx_gtk3u_html-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_qa-3.0.so.0()(64bit)
libwx_gtk3u_qa-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_stc-3.0.so.0()(64bit)
libwx_gtk3u_stc-3.0.so.0(WXU_3.0)(64bit)
libwx_gtk3u_webview-3.0.so.0()(64bit)
libwx_gtk3u_webview-3.0.so.0(WXU_3.0)(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
wxWidgets-3_0-devel
```


In my opinion this whole section is broken, you have misused  CPACK_RPM_PACKAGE_REQUIRES (it's use for runtime package requirements).

```
# Linux
# Set package dependencies
IF(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    IF(EXISTS "/etc/debian_version")
        SET(CPACK_GENERATOR "DEB")
        # Ubuntu
        SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.15), libgcc1 (>=1:4.1.1), libstdc++6 (>= 4.6), libwxgtk3.0-0v5 (>= 3.0.0) | libwxgtk3.0-0 (>=3.0.0), libwxgtk-webview3.0-0v5 (>= 3.0.0) | libwxgtk-webview3.0-0 (>= 3.0.0)")
    ELSEIF(EXISTS "/etc/redhat-release" OR LINUX_DISTRO MATCHES "openSUSE")
        SET(CPACK_GENERATOR "RPM")
        SET(CPACK_RPM_PACKAGE_LICENSE "GPL-2+")
        # Fedora
        IF("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" AND LINUX_DISTRO MATCHES "Fedora")
            SET(CPACK_RPM_PACKAGE_REQUIRES "clang, wxGTK3-devel")
        ELSE()
            SET(CPACK_RPM_PACKAGE_REQUIRES "gcc-c++, wxGTK3-devel")
        ENDIF()
        # openSUSE
        IF("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" AND LINUX_DISTRO MATCHES "openSUSE")
            SET(CPACK_RPM_PACKAGE_REQUIRES "llvm-clang, wxWidgets-3_0-devel")
        ELSE()
            SET(CPACK_RPM_PACKAGE_REQUIRES "gcc-c++, wxWidgets-3_0-devel")
        ENDIF()
    ELSE()
        #TODO: tar.gz
    ENDIF()
ENDIF()
```

And you O/S detection is broken as the resulting rpm has suse requires, gcc-c++ and wxWidgets-3_0-devel are suse packages only needed for building the binary rpm.


```
$ cmake ../..
-- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build Type = 
-- Building Tests = OFF
-- OS = Linux
-- Distro = Fedora
-- Compiler = GNU
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found wxWidgets: -pthread;;;-lwx_gtk3u_core-3.0;-lwx_gtk3u_qa-3.0;-lwx_baseu_net-3.0;-lwx_gtk3u_html-3.0;-lwx_baseu_xml-3.0;-lwx_gtk3u_aui-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_stc-3.0;-lwx_gtk3u_webview-3.0;-lwx_baseu-3.0 (found version "3.0.3") 
-- Base Directory =  /home/leigh/.local/share/Trash/files/moneymanagerex
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leigh/.local/share/Trash/files/moneymanagerex/build/release
```

**Comment by tomasfrtala** [comment]
Found the source of the problem. I will fix it right away!

**Comment by tomasfrtala** [comment]
You can try newly created packages from repository

**Comment by leigh123linux** [comment]
@tomasfrtala  After your fix it installs and runs on fedora, thank you.

**Comment by jjd24** [comment]
I have to ask that you re-open this. Although I can now install MMEX via the repository (many thanks to the Korora Project Team) MMEX fails to open my existing database - created in Ubuntu. Neither will it import a csv file. Both fail with

"Unexpected character in NUIMBER token"

Can you please advise. 
Thanks

**Comment by tomasfrtala** [comment]
@jjd24 please open a new issue because this problem does not related to installation. I found similar issue that https://sourceforge.net/p/moneymanagerex/bugs/635/

**Comment by vomikan** [comment]
@jjd24  try to delete ~/.mmex/mmexini.db3

**Comment by jjd24** [comment]
I have come back to this after a day away, having - I think - overcome the "Unexpected character" problem. That seemed to be in the way the date was formatted. But now I cannot even load MMEX. It crashes with 
"Segmentation Fault (core dumped)". Any thoughts?

**Comment by jjd24** [comment]
Further to previous post please see attached screenshots of debug.

![screenshot at 2017-05-10 16-11-08](https://cloud.githubusercontent.com/assets/28481269/25903225/1ca01294-359c-11e7-967d-a24242bce92d.png)
![screenshot at 2017-05-10 16-13-31](https://cloud.githubusercontent.com/assets/28481269/25903226/1ca1015e-359c-11e7-9b02-6729379b9833.png)
