### ISSUE TITLE
mmex ignoring locale currency settings - input fields truncate entered values without warning

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1150]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [x] git master
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

How to reproduce:
Open dialog for new transaction, enter "123,45" as an amount, press Tab to change focus to next field.

Result:
Amount value is silently changed to "123.00"
It's impossible to enter values as in configured system locale, use numeric keypad etc.

configured locale:
```
$ locale -ck LC_MONETARY
LC_MONETARY
int_curr_symbol="PLN "
currency_symbol="zł"
mon_decimal_point=","   <--- here
mon_thousands_sep="."   <--- and here
mon_grouping=3;3
positive_sign=""
negative_sign="-"
int_frac_digits=2
frac_digits=2
p_cs_precedes=0
p_sep_by_space=1
n_cs_precedes=0
n_sep_by_space=1
p_sign_posn=1
n_sign_posn=1
crncystr="+zł"
int_p_cs_precedes=0
int_p_sep_by_space=1
int_n_cs_precedes=0
int_n_sep_by_space=1
int_p_sign_posn=1
int_n_sign_posn=1
[...]
```

mmex should respect system settings for entering monetary amounts.

Next problem: it possible to enter amount value as "123,456.789" or "123,456,789" which are truncated to "123.00", but it's impossible to enter "123.456,789" or "123.456.789" - input field is ignoring dot or comma after first dot entered. So it seems mmex supports thousands separator char but converts it to decimal point what is wrong.

Entering monetary amounts should be rewritten to correctly support thousands separator and decimal point settings in system-wide or user configured locale.

Input field should display some kind of warning (icon, changed background colour, pop-up?) if user entered value is wrong and is corrected by mmex logic.

**Comment by vomikan** [comment]
Jast change the account currency settings in the Currency Manager.
It's feature not bug.

**Comment by slodki** [comment]
Ignoring user configured settings is a feature?
Default settings in mmex are: grouping char is space, decimal point is dot.

Results:
"123 456 789,246" -> "123 456 789.00
"123.456.789,246" -> cannot be entered (enters as "123.456789246" -> "123.46")
"123,456,789,246" -> "123.00"

"123 456 789.246" -> "123 456 789.25"
"123.456.789.246" -> cannot be entered (enters as "123.456789246" -> "123.46")
"123,456,789.246" -> "123.00"

"123 456 789 246" -> "123 456 789 246.00"
"123.456.789 246" -> cannot be entered (enters as "123.456789246" -> "123.46")
"123,456,789 246" -> "123.00"

So comma is accepted, but then treated as illegal char. This is wrong and should be fixed. I don't know why comma can be entered and semicolon not if both are illegal?

When user enter a wrong value (not a number) it's truncated at first illegal char without warning the user. This is wrong and should be fixed. Field should be marked as invalid and wait for user correction. Or apply some automatic corrections displaying warning about them. 

Default currency settings for separator chars are the same (even if local rules for currencies differ) and are not respecting system/user settings (locale), making default input method unusable (see above). This is wrong and can be fixed: initialize currency separators from system/user settings, allowing change them per currency later. Or ask user during setup wizard to ignore user/system settings and use application specific (impacting numeric keypad usage, copy-paste from other apps etc.).

**Comment by MartinX3** [comment]
I can confirm this issue with a self build package with 28.03.2018 20:34 commit date.

**Comment by MartinX3** [comment]
when we can expect an "alpha 4" build?
