### ISSUE TITLE
Currency Manager window should be more ergonimic

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1158]
CM windows should be updated reflecting latest code changes 855f0f30b71b1b499b25271637a2ec561a88ded5.

- User have no idea which values are accepted for delimiters. Available options should be displayed as radio buttons
- `Currency Symbol` label should be changed to `Currency Code` as it's [ISO 4217 code](https://en.wikipedia.org/wiki/ISO_4217) not symbol (compare EUR vs. €)
- Defining both prefix and suffix should be disabled - label should be changed to `Currency Symbol` with options to use it as prefix or suffix

Below is new GUI proposal:
![currency manager gui](https://cloud.githubusercontent.com/assets/3155552/25782191/09d74e96-3346-11e7-89cb-f83442e9e50b.png)

**Comment by vomikan** [comment]
How it looks:
![default](https://cloud.githubusercontent.com/assets/6836805/25785531/c0c656ac-338b-11e7-8432-adf1236ddc2a.PNG)
I'll prefer wxChoice*

**Comment by vomikan** [comment]
![2](https://cloud.githubusercontent.com/assets/6836805/25785645/e262e5ca-338e-11e7-84a1-e4128a510342.PNG)

**Comment by slodki** [comment]
I think tooltip in last example is not enough - the use of both fields should be clearly described in labels (always visible). Mayby set label to `Prefix or suffix symbol`?

Or maybe `Prefix / suffix symbol` and separate the input fields with ` / ` between them?

**Comment by whalley** [comment]
![CleanShot 2022-10-14 at 16 25 13](https://user-images.githubusercontent.com/487345/195883680-b58e039b-41fc-496d-9c41-ca49c98f09b6.png)

**Comment by reddyshyam** [comment]
> ![CleanShot 2022-10-14 at 16 25 13](https://user-images.githubusercontent.com/487345/195883680-b58e039b-41fc-496d-9c41-ca49c98f09b6.png)

Grouping char is space and yet we see comma?

**Comment by whalley** [comment]
> Grouping char is space and yet we see comma?

Indeed. That is because the defined Locale is being used, as indicted in the Sample. My MMEX options have:

![CleanShot 2022-10-14 at 18 48 03](https://user-images.githubusercontent.com/487345/195909551-c1b3da56-d654-44c0-b675-02e62fef4162.png)

**Comment by reddyshyam** [comment]
> > Grouping char is space and yet we see comma?
> 
> Indeed. That is because the defined Locale is being used, as indicted in the Sample. My MMEX options have:
> 
> ![CleanShot 2022-10-14 at 18 48 03](https://user-images.githubusercontent.com/487345/195909551-c1b3da56-d654-44c0-b675-02e62fef4162.png)

Got you. Thanks for the clarification. 👍

**Comment by whalley** [comment]
One thought is that we could disable the Decimal Char and Grouping Char if the Locale is being used.. .Would avoid confusion I guess.

**Comment by reddyshyam** [comment]
> One thought is that we could disable the Decimal Char and Grouping Char if the Locale is being used.. .Would avoid confusion I guess.

That's a great idea! Once locale is set, I guess it will be redundant here. It definitely did confuse me, I vote for disabling here.
