### ISSUE TITLE
Cannot open money manager ex, always get the following message when open: The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.   i am using windows 7

### ISSUE THREAD

**Issue by tzuhsun** [moneymanagerex/moneymanagerex#1161]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Patch for OS needed. Please ask google what kind of patch. 
This already discussed on forun.

**Comment by vomikan** [comment]
It looks like a C++ redistributable issue. It can be corrected and checked for in the installer. 

https://social.msdn.microsoft.com/Forums/en-US/96a1451b-ae6a-4c81-8029-dc00ab6a8d4a/the-program-cant-start-because-apimswincrtruntimel110dll-is-missing-from-your-computer?forum=vcgeneral

**Comment by slodki** [comment]
Solution recommended by Microsoft from #1228:

>[Update for Universal C Runtime in Windows](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) is required: 

>> Microsoft Visual Studio 2015 creates a dependency on the Universal CRT when applications are built by using the Windows 10 Software Development Kit (SDK). You can install this update on earlier Windows operating systems to enable these applications to run correctly.
