### ISSUE TITLE
All my data is gone after updating from 1.2.7 to 1.3.1

### ISSUE THREAD

**Issue by hisyam** [moneymanagerex/moneymanagerex#1162]
When I first open MMEX 1.3.1 after updating the app, it gives me the error

![mmex wut](https://cloud.githubusercontent.com/assets/1519780/26095786/7707ff6c-3a51-11e7-94e7-fc982998f0c7.png)

All my data is gone.

- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/bugs/927/

**Comment by hisyam** [comment]
I recovered my file using Dropbox version history and went back to 1.2.7 instead.
