### ISSUE TITLE
Compile warning after commit 1ae8416

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1166]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
Downloaded fix for#1147 compiled with VS2017 and got
d:\projects\moneymanagerex\src\dbupgrade.cpp(33): warning C4706: assignment within conditional expression
Did you have a slip of the finger as I think line 33 needs to be "if (version == 7)"
What is there would work for most of the old stuff I am familiar with like Algol and PL/1 as assignments were not allowed in conditional expressions but not for C++ ?

**Comment by vomikan** [comment]
@stef145g please fix asap
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/dbupgrade.cpp#L33

**Comment by stef145g** [comment]
@grumpy235 Thanks for picking this up. Just shows we all make mistakes even though my tests worked before I committed it.
