### ISSUE TITLE
The installation on Ubuntu 16.04 TLS as described on the Download page still does not work.

### ISSUE THREAD

**Issue by marjolin** [moneymanagerex/moneymanagerex#1169]
The installation on Ubuntu 16.04 TLS as described on the [Download page](http://www.moneymanagerex.org/download) still does not work.
After several month still a non-existing repository is referenced.

**Comment by tomasfrtala** [comment]
Hi @marjolin thank you for pointing to problem. Please take a look at the end of issue [1013](https://github.com/moneymanagerex/moneymanagerex/issues/1013#issuecomment-298400501). The download page will be soon altered.

**Comment by marjolin** [comment]
Hello Tomás,

thank you for your quick response. I installed this package twice but after
that MMEX does not start anymore. It terminates with an error message
saying something like "the column STATEMENT_LOCKED is not existent".
Currently I am not able to recall the exact wording because I re-installed
v1.2.7 in order to use MMEX at all.

Kind regards

Marco

**Comment by tomasfrtala** [comment]
I found similar problem was discussed here in issue [927](https://sourceforge.net/p/moneymanagerex/bugs/927/) and [1017](https://sourceforge.net/p/moneymanagerex/bugs/1017/) and also in [forum](http://forum.moneymanagerex.org/viewtopic.php?t=6879).
Actually this problem was [fixed](https://github.com/moneymanagerex/moneymanagerex/pull/1165) so the updates will arrive shortly.

**Comment by slodki** [comment]
Download page still doesn't point to https://packagecloud.io/moneymanagerex/moneymanagerex - should be updated

**Comment by slodki** [comment]
Binaries at packagecloud were built May 8 and have critical error #1147 as reported in #1210.
They are unusable for previous version users.

There are problems with packagecloud with reuploads the same versions of the packages (see travis-ci/dpl#618). The workaround it to manually delete packages from packagecloud and rebild them with temporary tag at travis (or manually upload packages to packagecloud).

**Comment by slodki** [comment]
Updated BUILD.md and INSTALL.md files are avaiable in PR #1312

**Comment by slodki** [comment]
Link at webpage should be changed from BUILD to INSTALL instructions.

**Comment by slodki** [comment]
@vomikan How can I help with this issue?
