### ISSUE TITLE
MMEX upgrade files 

### ISSUE THREAD

**Issue by patchaume** [moneymanagerex/moneymanagerex#1170]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by patchaume** [comment]
What are the upgrade files  automatically generated by the application ? How to suppress these files ?

**Comment by vomikan** [comment]
It should start once in case if upgrade from 1.2.3 to 1.3.0

**Comment by patchaume** [comment]
Thank you for your quick answer. And after some time can I delete it ? I suppose .

**Comment by stef145g** [comment]
When a database is upgraded, because of a new release, upgrade files will be generated as a backup in case you wish to return to the previous version.

If the upgrade is successful and you continue using the updated program, the update files can be deleted as these backups become unnecessary.

**Comment by patchaume** [comment]
Thank you very much. Now upgrade files have no secret  for me !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Stefano<mailto:notifications@github.com>
Envoyé le :mercredi 24 mai 2017 12:55
À : moneymanagerex/moneymanagerex<mailto:moneymanagerex@noreply.github.com>
Cc : patchaume<mailto:patrick.chaumeret@outlook.com>; State change<mailto:state_change@noreply.github.com>
Objet :Re: [moneymanagerex/moneymanagerex] MMEX upgrade files (#1170)


When a database is upgraded, because of a new release, upgrade files will be generated as a backup in case you wish to return to the previous version.

If the upgrade is successful and you continue using the updated program, the update files can be deleted as these backups become unnecessary.
