### ISSUE TITLE
Cannot load MMEX on Fedora 25

### ISSUE THREAD

**Issue by jjd24** [moneymanagerex/moneymanagerex#1172]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by jjd24** [comment]
After a struggle to install on Fedora I am unable to run the program as it crashes. From the menu it flashes the first dialogue box - then ends. Running from terminal it shows a segmentation fault. See attached screenshots of debug. Please assist.
![image](https://cloud.githubusercontent.com/assets/28481269/26491581/83250508-4210-11e7-9303-64969acb3349.png)
![image](https://cloud.githubusercontent.com/assets/28481269/26491601/990f61ec-4210-11e7-8ddd-75d2b44e2601.png)

**Comment by jjd24** [comment]
Sorry - must have closed this in error. To confirm, this issue is still present.

**Comment by stef145g** [comment]
This may be silly questions to ask, but have you tried selecting English as the language., Are the english.mo and persian.mo file installed. Also have you cancelled the language question to allow default start-up.

**Comment by jjd24** [comment]
I am unable to select any language. As I said the program crashes after I click on the "MMEX" icon. That is what I meant by running it "From the menu". Sorry if that was ambiguous. Where should I look for the .mo files?

**Comment by tomasfrtala** [comment]
I am unable to reproduce the problem. Clean installation of Fedora 25 in virtualised environment everything runs as expected. How you installed the mmex? Here is the standard way:
1. From [repository](https://packagecloud.io/moneymanagerex/moneymanagerex/install) choose `installation -> rpm -> quick install` and copy the script for adding repository
```
curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.rpm.sh | sudo bash
```
and paste it to terminal
2. After adding repository, run `yum install mmex`
3. Finally, `mmex` command is ready to be used to start Money Manager EX

**Comment by jjd24** [comment]
Dear Tomas
Have tried a new install as your instructions. I can add the repository but the install fails with the following:
******************************************************************************************************************

[MIRROR] mmex-1.4.0-1.x86_64.rpm: Curl error (35): SSL connect error for https://packagecloud-oss.global.ssl.fastly.net/4236/4524/fedora/25/package_files/209389.rpm?t=1497346148_91065f745a3df83ab3cdfcb34600ea923ec2d684 [TCP connection reset by peer]
[FAILED] mmex-1.4.0-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success 
***********************************************************************************************************************
I have tried five times but get the same message each time. Any suggestion, please.

**Comment by jjd24** [comment]
Hi Tomas
Just tried again and it installed! So forget last post. Will try using it now and update later today.

**Comment by jjd24** [comment]
Dear Tomas

OK I can confirm Mmex does run after the clean install. The previous problems with segmentation fault were probably due to the previous unsuccessful installation. 
However, there are one or two problems when in use:

1. Cannot open last used database. Selecting this option from the Mmex dialogue box crashes the 
 program. One has to select "Open existing Database" to proceed. That successfully loads the program but .......

2. Then the "Unexpected character in NUMBER token:" message appears. One has to ignore this and click on "Show Account List" to display the database items.

3. The ACCOUNT VIEW: Bank account name" does not display correctly. It seems to go down a line and overwrites the other details.

I appreciate this is an Alpha version and you may have these items in hand, but thought you should know. Thank you for all your efforts. It is easy for users to forget all your work on the packages.
Regards
jjd

**Comment by slodki** [comment]
The original problem with installing and starting MMEX is solved.
Please open new separate issues for problems mentioned in last post if they still exist.
