### ISSUE TITLE
Unexpected character in NUMBER token:

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#1175]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I am getting this error: "Unexpected character in NUMBER token: " when opening an empty mmex database.
On arch linux, latest mmex built from the master branch.

**Comment by stef145g** [comment]
Could you attach your empty database please. (I am assuming that the database in question has no confidential or personal data included)

**Comment by Dialga** [comment]
Heres the empty db
[mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/1048821/mmb.zip)

**Comment by stef145g** [comment]
I have examined the database and all looks good. Tested using Windows, as I don't have a Linux OS to test on.

**Comment by slodki** [comment]
Attached file tested with my build from git master gives only this on load:
```
mmex ./tmp.mmb 
(mmex:17574): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
(mmex:17574): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
```
on kubuntu zesty

**Comment by slodki** [comment]
Is this error displayed when you click on My Usage report? I can see this error only here, as described in #773

**Comment by avma** [comment]
Unfortunately that did not work for me, removed and made a fresh install from master c8e77b4  some 20 hours ago but same error pops up.
On the log file i found this line:
![image](https://user-images.githubusercontent.com/7680483/34643101-2a656f2a-f327-11e7-9b24-2e3d11836f77.png)

**Comment by Dialga** [comment]
Using a debug build I run `mmex tmp.mmb` and get a popup dialog with `cannot load translation from selected language` then an assertion fault appears which I press continue and then a dialog with `Unexpected character in NUMBER token` appears.
The following appears on the command line:
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
09:19:04: Debug: 2017-01-07 - 2017-10-20
09:19:04: Debug: 2017-01-07 - 2017-10-07
09:19:04: Debug: 2017-01-07 - 2017-09-13
09:19:04: Debug: 2017-01-07 - 2017-09-04
09:19:04: Debug: 2017-01-07 - 2017-08-22
09:19:04: Debug: 2017-01-07 - 2017-08-13
09:19:04: Debug: 2017-01-07 - 2017-08-08
09:19:04: Debug: 2017-01-07 - 2017-06-07
09:19:04: Debug: 2017-01-07 - 2017-05-30
09:19:04: Debug: 2017-01-07 - 2017-05-01
09:19:05: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
./src/common/wincmn.cpp(478): assert "GetEventHandler() == this" failed in ~wxWindowBase(): any pushed event handlers must have been removed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(mmex:6887): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by pl6025** [comment]
Hello, (sorry for my english)
I've compiled mmex 1.4.0 alpha3 for Linux Jessie_amd64.deb the 8 of january.
I've open my database and I was working fine. To I try to reopen my database and I've the "Unexpected character in NUMBER token" error.
With windows10 (mmex 1.3.0) my database is open without problem.
On my Linux I can just open an old database (may 2016)...

When I open mmex on my Linux computer I've a message:
Gtk-Message: Failed to load module "canberra-gtk-module"
Perhaps it has no link. I'm not used to compile.

I can't give you my database (too much personal information). And I can say that with a windows mmex it open correctly.

**Comment by vomikan** [comment]
I think that something is wrong with online news.

**Comment by MartinX3** [comment]
There is something wrong with the text parser of the news.
This bug gets activated by a special code letter.

Am 20. Februar 2018 09:07:06 MEZ schrieb Nikolay <notifications@github.com>:
>I think that something is wrong with online news.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/moneymanagerex/moneymanagerex/issues/1175#issuecomment-366896548

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by slodki** [comment]
All JSON streams (from web - as news feed, from usage statistic file etc.) can raise this error. JSON library used so far has errors and @stef145g is working on it trying replace with new RapidJSON lib.

**Comment by MartinX3** [comment]
Thank you very much!

**Comment by Dialga** [comment]
I can say this issue is related to #1323 and only occurs in release builds for some reason.
Problem still exists though.

**Comment by slodki** [comment]
@Dialga @pl6025 Please test [fixed build](https://github.com/slodki/moneymanagerex/releases/tag/test2)

**Comment by Dialga** [comment]
Hi I can confirm this error no longer occurs.
Thanks
