### ISSUE TITLE
Open file window is below main window

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#1176]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

latest mmex built from the master branch on arch linux, when startup dialog shows up and I select "open existing database", the main window opens with the file selector window underneath it.

**Comment by stef145g** [comment]
Is it possible to include some screen shots please.

**Comment by Dialga** [comment]
not really, the file select dialog is underneath the main gui as I said

**Comment by stef145g** [comment]
Unfortunately I cannot test it under Linux as I don't have a Linux OS. In Windows, the file select dialog follows the point where the top left hand side of the main window resides, and is OS based.

Have you tried to maximise the main screen, then open the file select dialog? This may reset the OS settings.

Does anyone else using Linux have the same problem?

**Comment by slodki** [comment]
@Dialga: mmex build from git master opens dialog over main window with kubuntu zesty (plasma desktop). It must be related to your window manager settings. Could you test clean system install in virtual machine?
