### ISSUE TITLE
MME 1.3.3: Crash when using double calculate sign

### ISSUE THREAD

**Issue by ffoknissom** [moneymanagerex/moneymanagerex#1179]
- Check OS
  - [x] Windows 10 64bit
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.3
  - [ ] 1.2.x
  - [ ] 1.1 or older

When making a new transaction and using double calculate signs (like --, ++, ::, xx) in the Amount box (e.g. 100--50) the program crashes after clicking OK

![mme_crash_01](https://cloud.githubusercontent.com/assets/25381170/26782164/7b4e4800-49f2-11e7-8bd7-0e3190db3d5c.png)

**Comment by stef145g** [comment]
I have tried this in Win 10 and Win 7 and could not reproduce problem.
Putting an amount 100--50 produced a warning message that this was invalid.

**Comment by ffoknissom** [comment]
Good morning Stefano,
It only occurs in 64 bits, i just tested in 32 bits and a warning message appears. Hope that helps!

**Comment by stef145g** [comment]
Both machines tested on are 64bit.
Win 10 Home version 1607 build 14393.693 (Having update problems) 
Win7 Home Premium editions.

**Comment by ffoknissom** [comment]
Tested just now on my work on a Windows 8.1 Enterprise machine (64 bits). Fresh download from Sourceforge, both 32 bits and 64 bits MMEX 1.3.3 portable packages, same packages i use at home. 

Same thing happens, the 32 bits version works fine and generates a notification, the 64 bits version crashes immediately after hitting the ENTER key or click on OK button.

**Comment by stef145g** [comment]
I have now downloaded the 65Kbit package from Sourceforge.net and I get the same result as you. I had been testing the versions I had built at that version and beyond. This is the reason I could not find the problem initially. This mean that something went wrong in that specific build.

**Comment by ffoknissom** [comment]
Ah oke, that makes sense. Now i know i'm not seeing ghosts :)
