### ISSUE TITLE
Reconciliation of transfer between accounts should be done separately in the accounts

### ISSUE THREAD

**Issue by corse63** [moneymanagerex/moneymanagerex#1180]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [ x] Mac OSX
  - [ x] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by corse63** [comment]
In the current version, reconciliation of a transfer between accounts is somehow painful:
When you do reconciliation of an operation, you do it either in the source or destination account, however at the end, it appears as reconciliated in both accounts. 

In fact, when you do a reconciliation, you do it based on an account statement and you do it for a given account (say the source one). When you receive the statement for the other account (say the destination one), it is then possible to make the reconciliation, and only then.

For this reason, I would suggest to make reconciliation only in the concerned account where you are working.

**Comment by stef145g** [comment]
This has been a long standing issue reported many times before. I think I have a way of solving this problem using the current database schema. I will investigate this further.

**Comment by stef145g** [comment]
PR #1208 has been created that will address this issue.
