### ISSUE TITLE
Reconciliation, could we have a dedicated screen to do it

### ISSUE THREAD

**Issue by corse63** [moneymanagerex/moneymanagerex#1181]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ x] Windows
  - [ x] Mac OSX
  - [ x] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by corse63** [comment]
Reconciliation can be difficult if you have many operations (typically I can have a 4 to 5 pages statement).

In order to make things easier and allow to restart the reconciliation process from scratch or look for potential errors, I would strongly suggest to create a specific screen to perform reconciliation:

This screen would show the non reconciliated transactions (all but non reconciliated). In this screen you could:
1) select the transaction you would like to reconciliate. Those transactions would be set in an intermediate state (say proposed). 
2) This screen would propose you a button, confirm, that would turn all the intermediate state (proposed) into reconciliated. This would allow you to track the potential errors, and revert the proposed state to un reconciliated if needed, if you want to restart the operation
3) you should be able in this screen to toggle the status line by line between proposed and non reconciliated
4) if you leave the screen, the status of each line should not be changed (either non reconciliated of proposed), as they are when you leave the screen
5) in the screen you should be given the possibility to add transactions if needed (say if you find a transaction in your statement that has not been key in)

**Comment by stef145g** [comment]
Within the Account view, have you used the Transaction filter?
Also have you used the options on the popup menu: Mark all being viewed as ...
Reconciliation can then be done noting the Reconciled Balance at the top of the list.

The Transaction filter used to remember the settings on successive openings to allow quick changes but now it does not unless the settings are saved. This would produce a similar screen as you propose, as most if not all the functionality exists.

**Comment by corse63** [comment]
I uinderstand your point, but it does not bring the functionality to put in
a temporary state: the way I do it is a three  state process (cumbersome
but works):

Step 1: using the filter (not reconciliated) I put in the intermediate
state To be Checked the transaction I intend to re-conciliate.
Step 2: using the filter (to be checked) I verify balance is OK
Step 3: using the filter (to be checked) I mark everything as re-conciliate

So it can be done, I do it, but having dedicated screen would allow to it
in one step

2017-06-10 8:05 GMT+02:00 Stefano <notifications@github.com>:

**Comment by corse63** [comment]
BTW I still owe you a description on stock accounts, I have not so much
time. But I will do it as I think here the application could be improved

2017-06-10 8:05 GMT+02:00 Stefano <notifications@github.com>:

**Comment by stef145g** [comment]
Related Issue: #1189

**Comment by stef145g** [comment]
Pull Request #1191 has been created to address this issue.
The buttons OK, Cancel, Clear have been renamed to Activate, Deactivate and Clear respectively. The Save button has been removed and the functionality incorporated in Activate and Clear.

Operation:
- On selecting **Activate** the changes are automatically saved in the selected position. On reopening the filter, the settings are restored for this position.
- On Selecting **Deactivate**, the filter is disabled.
- On **Clear**, the settings are cleared in the dialog, as previous, but automatically clears the saved setting.

This should make the filter more intuitive and easy to use.

**Comment by stef145g** [comment]
The Transaction filter has been modified to make usage easier and together with the multiple transaction editing should make this process easier. I am not convinced that a separate screen is required, as this would just duplicate existing functionality.

**Comment by corse63** [comment]
Thx no problem

**Comment by slodki** [comment]
See #1678
