### ISSUE TITLE
Fatal error while installing last version Portable 32 and 64bits

### ISSUE THREAD

**Issue by Epitaxy1961** [moneymanagerex/moneymanagerex#1182]
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
![immagine](https://cloud.githubusercontent.com/assets/29224141/26819295/8a05f7c4-4a9e-11e7-91c2-c3313a6df04a.jpg)

**Comment by slodki** [comment]
Should work in 1.4.x
