### ISSUE TITLE
Stocks Total Currency conversion error

### ISSUE THREAD

**Issue by Jeremiearnaud** [moneymanagerex/moneymanagerex#1185]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hi everyone !

I discovered a bug on the home page under the stocks accounts section.

My base currency is EUR and I have two stocks accounts, one in EUR and one in USD. Everything works fine except that when converting the USD amount of the USD stocks account into the base currency to add it to the Total of the stocks section, the conversion is made the wrong way : USD value is multiplied by 1.12 in place of 0.88. Resulting in overvalued stocks section and overvalued Grand Total.

I also have two cash accounts : one EUR and one USD but there's no problem there, the conversion is made right and the total display a correct value.

Does anyone have the same issue ? Am I using currencies wrong (I don't think so because everything works fine with the cash accounts...)

Thank you for making this software awesome and free !

**Comment by stef145g** [comment]
![screenshot 2017-06-12 10 59 13](https://user-images.githubusercontent.com/6927151/27016014-e0b477c6-4f5d-11e7-91a6-7ddd5cadee12.png)
Trying to duplicate the problem,
Currency EU = 1 
Currency US = 0.8923

Stock account section same as Bank Account Section
