### ISSUE TITLE
Mac Builds Not available

### ISSUE THREAD

**Issue by vinodraut** [moneymanagerex/moneymanagerex#1188]
It seems that you have stop giving MAC builds!!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.macOS.md

**Comment by vomikan** [comment]
https://github.com/tomasfrtala/moneymanagerex/releases

**Comment by vinodraut** [comment]
Thanks
