### ISSUE TITLE
Could you please make sticky the option s chosen for transaction filter

### ISSUE THREAD

**Issue by corse63** [moneymanagerex/moneymanagerex#1189]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [x ] Mac OSX
  - [x ] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by corse63** [comment]
When working with my transactions, I would like to be able to make a default filter applied when entering the screen.
The default option I use is everything but re-conciliated . When I exit an account it is lost and I have to reset it.
Could it be possible to memorize the latest filter and apply it when viewing an account. To be simple the default filter could be the same for all account viewing

**Comment by stef145g** [comment]
When opening the Transaction filter and the filter is set up and saved using the save icon (bottom left), the next time it is opened, the settings will be preserved. Selecting OK will enable the filter and cancel will disable it. To clear the setting, use clear and save. This removes the permanent setting.

From the title, I assume that you wish to see the modified settings on reopening the filter after using OK, and cleared when using the cancel button.

**Comment by corse63** [comment]
I tried many times does not seem to work


2017-06-10 9:07 GMT+02:00 Stefano <notifications@github.com>:

**Comment by stef145g** [comment]
Pull Request #1191 has been created to address this issue.
 The buttons OK, Cancel, Clear have been renamed to Activate, Deactivate and Clear respectively. The Save button has been removed and the functionality incorporated in Activate and Clear.

Operation:
- On selecting Activate the changes are automatically saved in the selected position. On reopening the filter, the settings are restored for this position.
- On Selecting Deactivate, the filter is disabled.
- On Clear, the settings are cleared in the dialog, as previous, but automatically clears the saved setting.

This should make the filter more intuitive and easy to use.

**Comment by corse63** [comment]
Thx
