### ISSUE TITLE
unable to enter new transactions

### ISSUE THREAD

**Issue by arkadymulyaki** [moneymanagerex/moneymanagerex#1192]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by arkadymulyaki** [comment]
(new user) After filling in the relevant fields in the dialogue box and hitting "OK," the dialogue box vanishes but the transaction isn't recorded.

**Comment by stef145g** [comment]
Strange? What version of Windows are you using?
