### ISSUE TITLE
Provide undo function for mass update transactions

### ISSUE THREAD

**Issue by corse63** [moneymanagerex/moneymanagerex#1193]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [x ] Mac OSX
  - [ x] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ x] 1.2.x
  - [ ] 1.1 or older

**Comment by corse63** [comment]
MMX provides a nice functions by allowing you to make a massive update (or delete) using the feature to perform operations on all transaction selected with the active filters
However in case of wrong actions, it might leads to serious problems.

Would it be possible to provide on those massive actions, those manipulating all visible transactions, an undo function, that would allow to recover in case of a wrong action

**Comment by Dandy64** [comment]
It can be a good idea to add a **Save** button to Money Manager Ex. 
Instead of Undo function or in addition to such function user should have a chance to exit from the program without saving.
Of course, it is necessary to show a warning message if the user leaves the program without saving.

**Comment by vomikan** [comment]
I don't like idea to add a Save button. I like the feature when all transactons enter immidiatly.

Related issue:
https://github.com/moneymanagerex/moneymanagerex/issues/2963

**Comment by whalley** [comment]
**QUESTION** - I propose that the ability to recover deleted transactions is probably as far as we want to go here, and suggest we close this issue. Views welcome.

**Comment by tactilis** [comment]
> I propose that the ability to recover deleted transactions is probably as far as we want to go here

Agreed.  Anything else gets pretty complicated.

If I screwed up a mass update, I'd revert to my most recent backup and learn not to make the mistake again.

If I was concerned ahead of time that a mass update I was about to make might be wrong, I'd take a copy of my .mmb first.

**Comment by vomikan** [comment]
@n-stein , @whalley Isn't this case a repetition of this:
Add a Deleted/Trash transaction feature #2963
?

**Comment by tactilis** [comment]
> Isn't this case a repetition of this:
Add a Deleted/Trash transaction feature https://github.com/moneymanagerex/moneymanagerex/issues/2963

No, it's completely different.
#2963 'moves' transactions that the user deletes to the Deleted Transactions area.
The user can restore them from there if the deletion was an error.

That is not the same as Undo (the subject of this issue), which would undo any change, including bulk updates.

In the discussion above, we question the need for Undo (and all the complexity it entails). @whalley and I think we should close this issue (i.e. as won't implement).

**Comment by n-stein** [comment]
> @whalley and I think we should close this issue (i.e. as won't implement)

I third this motion.
