### ISSUE TITLE
Navigation Panel is on top of Accounts Pane

### ISSUE THREAD

**Issue by wirmike** [moneymanagerex/moneymanagerex#1195]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by wirmike** [comment]
This issue appeared during May2017.
I had previously upgraded MMEX to v.1.3.1 shortly after its release with NO issues.
The Navigation panel was (happily) on the LHS, with the open Accounts panel to the RHS and both were scrollable.  This was a VERY workable arrangement.
Within an open session the situation changed to the one reported.
I have tried a solution (dragging panes) proposed in a Forum, but to no avail.  I cannot find any way to revert to the side-by-side panel views.  The current (vertical) arrangement is difficult to work with and am keen to revert to the staus quo.
My OSX is currently at MacOS Sierra 10.12.5.  I cannot find anything here to suggest a solution.
Regards

**Comment by stef145g** [comment]
Have you tried to reset the initialisation parameters?
Rename the mmexini.db3 file. All parameters will be reset to default.

**Comment by wirmike** [comment]
Stefano,

Thank you for picking up the ‘post’.

I’ll try what you suggest, BUT, do you have a suggestion as to what I should rename the ***ini.db3 file to?   Should I rename it back after ‘all has been restored/reset'?

Also, have you an inkling as to how this has occurred?

Was it:
something that I had unwittingly done?
a spontaneous/unexplained programme action?

Thank you again.

I’ll look at the programme folder/s in the meantime to find that ***ini.db3 file.

Regards,

MikeD

**Comment by stef145g** [comment]
Renaming the file to something like: mmexini_org.db3 is OK. You could also delete it, as mmexini.db3 will be recreated. I am not sure where the file is located in a Mac. The old file can then be examined and compared to the recreated file to possibly identify the problem if one exists.

As to the cause, it may be a glitch in saving/reloading screen parameters. Cause unknown.

**Comment by wirmike** [comment]
Stefan,

I shall report in due course.

Regards,

MikeD

**Comment by wirmike** [comment]
Stefano,

I have looked thru the MMEX User-guide but am finding difficulty in working out how to reset the ‘initialisation parameters’.
Can you advise?

Also, I am having difficulty in locating the .db3 file.
As MMEX runs as an MMEX App, might this be significant?
(Having said that, I am really less than impressed w/- Finder!!!  And the non-Windows-like folders presentation!)

I will continue my search.

Sorry for coming back for advice again, but thank you for your quick replies.

Regards,

MikeD

**Comment by wirmike** [comment]
I have now upgraded to v. 1.3.3 and the issue has now 'corrected' itself.

Thanks for the guidance given.
