### ISSUE TITLE
Foreign Calenders

### ISSUE THREAD

**Issue by mkhoshbin1** [moneymanagerex/moneymanagerex#1196]
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

As of 1.3.1 there is no way to use foreign calendars (e.g. [Iranian Calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar#Solar_Hijri_and_Gregorian_calendars)) in reports which makes using them more difficult in other countries.
I propose one of the following:
1. (The simple version): Reports for "current financial month" and "current financial month to date". Similar versions exist for financial year, but not for financial months. The problem with this method is the difference between length of months in different calendars.
2. (The sophisticated version): Support for additional calendars. Ultimately, I imagine the following (IMHO):
a. A secondary calendar being selected in settings.
b. The current (main) calendar being used for calculations. Conversions and queries should be done with this in accordance to conversion rules of the secondary calendar. Code can be adapted from other FOSS projects such as [FarsiCal](https://github.com/arminmacx/FarsiCal).
c. Display of the secondary calendar alongside the main calendar. For example there can be two headers or two dates in reports. <br>It's important to have the main calendar since many services (banks, SMS, etc.) use the Gregorian calendar.

**Comment by vomikan** [comment]
CLOSE: Wontfix

REASON: This issue was raised in 2017 by a developer. Address the problem when/if a real world user raises a new issue about this.
