### ISSUE TITLE
Editing a Transaction Deletes it from Account View

### ISSUE THREAD

**Issue by myntric** [moneymanagerex/moneymanagerex#1197]
This previously happened in 1.3.1 and I upgraded to 1.3.3 this morning and was able to duplicate the same problem.  When I edit any transaction within an Account View and click "Save", it is no longer displayed in Account View and the "Account Bal" reflects the fact it is gone.  I then re-add the transaction and if I edit it again, it will disappear; however, if I run a Transaction Report Filter, it shows the transaction or each time I've entered it whether it's displayed in Account View or not, usually multiple times.  I've attached screenshots of the Active View and Transaction Report (with redacted confidential information) and can duplicate repeatedly.

![active view](https://user-images.githubusercontent.com/6606302/27481268-cc1b9468-57e9-11e7-9483-bba0b2ff9498.JPG)
![transaction reports](https://user-images.githubusercontent.com/6606302/27481270-cf11e79e-57e9-11e7-8658-a0ab116698dc.JPG)

- Check OS
  - [X ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by stef145g** [comment]
Do you have any filters active in Account View?

**Comment by myntric** [comment]
No. I triple checked I had all the filters cleared. Even when I applied a
filter with the Payee name it only showed the single transaction.

**Comment by stef145g** [comment]
Have you tried to replicate problem in a test database with only a few transactions, and what fields are changed when editing. I am not able to replicate the problem.

**Comment by myntric** [comment]
I created a test database and it I was not able to duplicate it either.  I
tried all of my backup databases and the same problem occurred.  Looks like
I may need to start over and re-enter everything?

**Comment by stef145g** [comment]
Can you examine the database external to MMEX?

**Comment by myntric** [comment]
I deleted all the duplicate records in CHECKINGACCOUNT_V1.  I'm wondering
if it's a display issue.  I edited a record within MMEX and it disappeared
from the Account View; however when I went into the records using SQLite DB
Browser the record does still exist.  This would explain why it (rather I)
was creating duplicate records when it appeared to disappear where it was
only disappearing from the screen rather than database.

**Comment by myntric** [comment]
It looks like the issue is that when I edit a transaction it sets
ACCOUNTID=19 rather than 1.  According to the table ACCOUNTLIST_V1,
ACCOUNTID 19 is a "Shares" ACCOUNTTYPE which is odd.  I'm not sure why
editing a transaction moves it from my checking to a stock share account
that I've setup.  That stock share account had 0 everything and looks like
one I might've canceled out when entering it so I deleted it, manually
changed the ACCOUNTID to 1 again for the missing transactions and now
everything is working perfectly (including editing transactions).

**Comment by stef145g** [comment]
There is an issue with 1.3.3 that if you attempt to duplicate a share transaction that things get messed up. Now corrected in 1.4.x that duplicates of share transactions is not allowed. Not sure if this may have caused the problem, but hopefully you have fixed the problem in your database.
