### ISSUE TITLE
Pb in android shares

### ISSUE THREAD

**Issue by fabien69** [moneymanagerex/moneymanagerex#1198]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

When buying shares and which one resells later the credit and the debit appear in the application windows. But in the android version only credits appear.

**Comment by slodki** [comment]
So in the Windows version your transactions are displayed correctly and the problem is in the Android version?

**Comment by fabien69** [comment]
Yes in the Windows version my transactions are displayed correctly and the problem is in the Android version.

**Comment by slodki** [comment]
You should go to the [Android project issues](https://github.com/moneymanagerex/android-money-manager-ex/issues) list and create bug report there.
