### ISSUE TITLE
Empty MyUsage report generates JS error

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1203]
When USAGE_V1 table is empty (= first run) or date range selected gives empty set of stats (= Last Year when used only few days) the following report page is generated in tmp:

```javascript
var data = {
    labels: [

            ],
    datasets: [
        {
            fillColor : 'rgba(129, 172, 123, 0.5)',
            strokeColor : 'rgba(129, 172, 123, 1)',
            pointColor : 'rgba(129, 172, 123, 1)',
            pointStrokeColor : "#fff",
            data : [

                    ],
            title : "FREQUENCY"
        }
        ]
    }
    var opts= { annotateDisplay : true, responsive : true };
```
and ChartNew generates following error:

```
** Message: console message: file:///tmp/mmex_slodki_tmp/ChartNew.js @3271: TypeError: undefined is not an object (evaluating 'statData[i][0].tpchart="Line"')
```
Empty dataset should be detected at [myusage.cpp](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/myusage.cpp#L134) and chart creation skipped.

**Comment by vomikan** [comment]
I can't reproduce it in 1.4.0

**Comment by slodki** [comment]
1. Delete mmexini.db3 file
2. Start MMEX from linux console
3. Create new db in MMEX
4. Click on usage report
5. Switch MMEX window to linux console -> there is ChartNew error displayed
6. Open /tmp/mmex_*_tmp/index.html file with text editor -> empty data table exists in script section
7. Open index.html file with FF browser and open debug console -> JavaScript error is displayed
