### ISSUE TITLE
Unable to upgrade Linux Ubuntu 1.2.7 and unable to turn off nag screen.

### ISSUE THREAD

**Issue by cdcavell** [moneymanagerex/moneymanagerex#1205]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

**Comment by slodki** [comment]
Do you have problem with ubuntu upgrade due to unmet mmex packages required dependencies or with mmex package upgrade? Attach apt/dpkg error from unsuccessful upgrade.

What "nag screen" you cannot turn off? Could you attach screenshot?
