### ISSUE TITLE
Store right application ID in sqlite database header

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1206]
SQLite supports [tagging file](https://www.sqlite.org/fileformat.html#application_id) as associated with a particular application. This allows identify application regardless filename extension. It's as easy as adding one [SQL statement](https://www.sqlite.org/pragma.html#pragma_application_id) to the database creation or update: `PRAGMA application_id = 0x4d4d4558 ;`.

It can be added without database version bump because it doesn't change database schema and it's transparent to the mmex application.

0x4d4d4558 value is best for mmex :smile: and is not used by other apps, so it should be registered at SQLite [magic.txt](http://www.sqlite.org/src/artifact?ci=trunk&filename=magic.txt).

**Comment by slodki** [comment]
TODO:
- [ ] update SQLite [sources](https://www.sqlite.org/src/artifact/8273bf49ba3b0c85)
- [ ] implement in [file](https://github.com/file/file/blob/master/magic/Magdir/sql) tool

**Comment by vomikan** [comment]
CLOSE: fixed

REASON: https://github.com/moneymanagerex/moneymanagerex/issues/1254 solves the problem of registering the .mmb file type on Linux and a different issue exists for Windows.
