### ISSUE TITLE
Update or replace Cajun

### ISSUE THREAD

**Issue by yaomtc** [moneymanagerex/moneymanagerex#1207]
I use Solus. A package request for Money Manager EX [was rejected](https://dev.solus-project.com/T1055), the reason being that Cajun was too old.

[I took a look at Cajun.](https://github.com/cajun-jsonapi/cajun-jsonapi) It hasn't had any changes at all since May of 2015, most of Cajun's development was from 2011 or earlier (latest release: 2013), and a pull request has gone untouched for a year and a half (followed by two more recently).

I found [this benchmark comparison](https://github.com/miloyip/nativejson-benchmark) of various C/C++ libraries, including the latest Cajun. Its conformance was just below average, and its parsing time was the highest of them all, by far, nearly double of the next slowest result.

Given this information, I think replacing Cajun with something else would be best, seeing as its development seems to have halted and there are better options available. However, if that's not feasible at this time, you could at least update to 2.0.3. As far as I can tell, MMEX is still using Cajun 2.0.1... **from 2009!**

**Comment by guanlisheng** [comment]
@yaomtc good suggestion and welcome your PR to replace cajun.

**Comment by slodki** [comment]
* [RapidJSON](https://github.com/Tencent/rapidjson) requires VC2008/GCC 3.8/Clang 3.4
* [nlohmann/json](https://github.com/nlohmann/json) requires VC2015/GCC 4.9/Clang 3.4

**Comment by stef145g** [comment]
I have come to the conclusion that we should use [RapidJSON](https://github.com/Tencent/rapidjson)

**Comment by baimafeima** [comment]
I am also looking forward to seeing Money Manager Ex in Solus. Has `cajun-json` already been replaced in the latest 1.4.0-alpha.3? @stef145g

**Comment by stef145g** [comment]
I have now made more progress in converting cajun-json to RapidJSON, but still have much to do

**Comment by stef145g** [comment]
Update: further progress has been made with still a few modules to be converted to rapidjson. Interested users can see the progress on "stef145g/moneymanagerex/rapidjson" branch.
My first attempt on my "rapidjson_switch" branch was not successful and has therefore been deleted, but has provided valuable training on rapidjson usage.
