### ISSUE TITLE
Money manager crash on start

### ISSUE THREAD

**Issue by Kobi777** [moneymanagerex/moneymanagerex#1209]
Application 1.2.7 was working and 1.3.3/1.3.1 are both crashing on the start (no window is shown only the crash report - with a crash I believe).
- Check OS
  - [x] Windows (7)
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x both x32 and x64
  - [ ] 1.2.x
  - [ ] 1.1 or older

[MoneyManagerEx_dbgrpt-4532-20170701T094542.zip](https://github.com/moneymanagerex/moneymanagerex/files/1116922/MoneyManagerEx_dbgrpt-4532-20170701T094542.zip)

**Comment by stef145g** [comment]
Please refer to #1231

**Comment by slodki** [comment]
@Kobi777 could you confirm solutions given by @stef145g are working for you?

**Comment by Kobi777** [comment]
Yes, it is, thanks!
