### ISSUE TITLE
PPA does not exist

### ISSUE THREAD

**Issue by marjolin** [moneymanagerex/moneymanagerex#1210]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [ x] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Allegedly the following command lines shall install the current release of MMEX:

sudo apt-get install python-software-properties

sudo apt-add-repository ppa:dwrj87/mmex-test

sudo apt-get update && sudo apt-get install mmex

but they don't. The named repository does not exist.

**Comment by slodki** [comment]
Please see #1169. Use https://packagecloud.io/moneymanagerex/moneymanagerex

**Comment by marjolin** [comment]
Hello Slodki,

thank you for your response.

The fault report is about the homepage and the Wiki which still refer to
that PPA.
When I follow the instructions given beyond the link above

marco@Sol:~$ curl -s
https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh
| sudo bash
[sudo] Passwort für marco:
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing
/etc/apt/sources.list.d/moneymanagerex_moneymanagerex.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
marco@Sol:~$ sudo apt-get install mmex=1.4.0
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  mmex
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.
Es müssen 8.755 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 25,6 MB Plattenplatz zusätzlich benutzt.
Holen:1 https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu
xenial/main amd64 mmex amd64 1.4.0 [8.755 kB]
Es wurden 8.755 kB in 9 s geholt (956 kB/s).
Vormals nicht ausgewähltes Paket mmex wird gewählt.
(Lese Datenbank ... 286482 Dateien und Verzeichnisse sind derzeit
installiert.)
Vorbereitung zum Entpacken von .../archives/mmex_1.4.0_amd64.deb ...
Entpacken von mmex (1.4.0) ...
Trigger für desktop-file-utils (0.22-1ubuntu5.1) werden verarbeitet ...
Trigger für bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) werden
verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...
Trigger für gnome-menus (3.13.3-6ubuntu3.1) werden verarbeitet ...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.15-0ubuntu1) werden verarbeitet ...
mmex (1.4.0) wird eingerichtet ...
marco@Sol:~$


and start MMEX 1.4.0 I get the following message:


[image: Inline image 1]

Kind regards

Marco

**Comment by slodki** [comment]
The most important part - image - is not attached. Could you edit your message and add it?

**Comment by marjolin** [comment]
Hello Slodki,

I am sorry but I can see the image in my out box. Nevertheless I type the
text here:

Title: mmex Error
Text: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]: no
such column: STATEMENTLOCKED

Kind regards

Marco

**Comment by slodki** [comment]
It was fixed as #1147 on May 20, but binaries at packagecloud were built May 8.
Please check packages at https://packagecloud.io/slodki/moneymanagerex (latest build) - they should work until when official repo will be updated.

**Comment by marjolin** [comment]
Same behaviour. Sorry.

marco@Sol:~$ curl -s
https://packagecloud.io/install/repositories/slodki/moneymanagerex/script.deb.sh
| sudo bash
[sudo] Passwort für marco:
marco@Sol:~$ sudo apt-get install mmex=1.4.0
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  mmex
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Es müssen noch 0 B von 8.755 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 25,6 MB Plattenplatz zusätzlich benutzt.
Vormals nicht ausgewähltes Paket mmex wird gewählt.
(Lese Datenbank ... 286690 Dateien und Verzeichnisse sind derzeit
installiert.)
Vorbereitung zum Entpacken von .../archives/mmex_1.4.0_amd64.deb ...
Entpacken von mmex (1.4.0) ...
Trigger für desktop-file-utils (0.22-1ubuntu5.1) werden verarbeitet ...
Trigger für bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) werden
verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...
Trigger für gnome-menus (3.13.3-6ubuntu3.1) werden verarbeitet ...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.15-0ubuntu1) werden verarbeitet ...
mmex (1.4.0) wird eingerichtet ...
marco@Sol:~$ ^C
marco@Sol:~$



22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED
22:34:11: ACCOUNTLIST_V1: Exception SQL logic error or missing database[1]:
no such column: STATEMENTLOCKED

**Comment by stef145g** [comment]
This is a database problem, and possibly caused by a past programming misalignment with the Android version. This can be corrected by patching the database with the SQL statement:

`PRAGMA user_version = 6;
`

For further info Ref: https://sourceforge.net/p/moneymanagerex/bugs/927/

**Comment by marjolin** [comment]
Hello Stefano,

I just deleted the old database and created a new one with version 1.4.0.
Let's see how that works.

Kind regards

Marco
