### ISSUE TITLE
Fullscreen menu item's checkbox not synchronized with window state

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1216]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [x] git master

Checkbox in the `View` -> `Toggle Fullscreen` menu item is not synchronized with real window state after using `F11` or toolbar button.

**How to reproduce**
1. Start program in normal window
2. Checkbox in `View` -> `Toggle Fullscreen` is switched off
3. Press `View` -> `Toggle Fullscreen` menu item
4. Main window is full screen now
5. Press `F11` or toolbar icon to change full screen to normal window
6. Main window is not full screen now
7. **Checkbox in `View` -> `Toggle Fullscreen` is switched on (!)**

**Proposal**
1. Add [wxITEM_CHECK](http://docs.wxwidgets.org/trunk/defs_8h.html#abd0c640814a55e4adda3bce698646d2da92800d0bce3f5f62d522427453920915) to the toolbar icon for fullscreen switch
2. Synchronize menu item and toolbar button status with real window state using suggestion from [forum](https://forums.wxwidgets.org/viewtopic.php?t=8594)

**Comment by vomikan** [comment]
CLOSE: fixed

REASON: Works correctly now.
