### ISSUE TITLE
Recurring transactions

### ISSUE THREAD

**Issue by Big-Mug** [moneymanagerex/moneymanagerex#1217]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by callmenemo491** [comment]
Duplicate of #1218.
