### ISSUE TITLE
General Report Manager: Cannot create new report

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#1219]
All menu items are greyed out in general report manager when trying to create a new report.

![grm 1 3 3](https://user-images.githubusercontent.com/6977203/27981570-70cb757c-6353-11e7-9abd-e25e1850bccb.png)

Confirmed on MacOS X, MMEX v1.3.3

**Comment by omalleypat** [comment]
@vomikan This worked in v1.2.7, but not in v1.3.0 and newer.

**Comment by vomikan** [comment]
it's working on Windows
![screenshot 335](https://user-images.githubusercontent.com/6836805/27986439-e3f06c2e-6407-11e7-936f-f40a02860d81.jpg)

**Comment by kennydrobnack** [comment]
Confirmed - I'm also seeing this bug in 1.3.3 on Mac but not on Windows.

**Comment by omalleypat** [comment]
MMEX v1.2.7 was using wxWidgets 3.0.2 while MMEX v1.3.0 used wxWidgets 3.1.0. Any chance that could be part of the issue? Didn't see anything obvious in the code...

**Comment by omalleypat** [comment]
So it looks like this is a wxWidgets issue. I recompiled the v1.2.7 tag with wxWidgets 3.1.0 and it doesn't work.

**Comment by omalleypat** [comment]
It is a wxWidgets bug:
http://trac.wxwidgets.org/ticket/17459

**Comment by vomikan** [comment]
Related bug
https://github.com/moneymanagerex/moneymanagerex/issues/1240

**Comment by jesuswearspink** [comment]
Any solutions to this??? I still see it happening and I have no clue how to fix it in the code...??

**Comment by slodki** [comment]
It has been fixed in upstream wxWidget master branch (wxWidgets/wxWidgets@361d7b493860c1b9aa7414bbf9bf4bd27d703744) just 14 hours ago. We must wait for next (3.1.1) wxWidgets version or cherry pick this patch.

**Comment by jesuswearspink** [comment]
What does cherry pick mean?

**Comment by slodki** [comment]
To copy only this one patch from new version of wxW and use it with old version used to build MMEX

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=23&p=179346&sid=7591c773ab0c6585d11b697f67aeacd1#p17934

**Comment by omalleypat** [comment]
New build of v1.3.3 posted. [Click here for more info.](https://www.moneymanagerex.org/news/item/74-updated-mac-build-v1-3-3)

**Comment by slodki** [comment]
This is not fixed, but we use workaround for this while we wait for upstream fix in wx-3.1.1.
All CI MMEX 1.4.0 builds for Mac uses wx 3.0.3 from brew bottles for now and should work correctly.

@omalleypat Could you confirm [latest MMEX 1.4.0 builds for Mac](https://github.com/slodki/moneymanagerex/releases/tag/test1) don't have this error?

**Comment by Lou1025** [comment]
No, no grey out on menu items. Just when I try to drag the SQL command from the listing to the window the "+" sign moves with the mouse but when I let go of the mouse no command transfers to the window.
