### ISSUE TITLE
Buttons background color not visible in View Options dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1226]
Colors can be changed and work at transactions view but are not displayed before and after change in `Tools`->`Options`->`View Options`->`User Colors`:

![mmex-linux-colors](https://user-images.githubusercontent.com/3155552/27994932-e03ac7b8-64c6-11e7-894f-091023f49b0c.png)

It can be related to GTK port of wxWidgets - it uses [as many native controls as possible](http://docs.wxwidgets.org/3.1/page_port.html#page_port_wxgtk) and problems with wxButton background were [reported](https://forums.wxwidgets.org/viewtopic.php?p=5386#p5386).

![mmex-linux-gtk](https://user-images.githubusercontent.com/3155552/27995061-568208fe-64c8-11e7-911e-1ed44993d9d3.png)

<hr><small><b>Version</b>: 1.4.0-Alpha.1 ⬥ db 7 ⬥ git 346331ab (2017-07-08) patch-github-issues<br><b>Libs</b>: wxWidgets 3.0.2 ⬥ SQLite 3.14.1 ⬥ wxSQLite3 3.4.0 ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>OS</b>: Ubuntu 17.04 "zesty" ⬥ Linux 4.10.0-26-generic x86_64 ⬥ Polish UTF-8 <br><b>Build</b>: Jul 9 2017 13:29:15 ⬥ GNU GCC/G   6.3.0 20170406 ⬥ CMake 3.7.2 ⬥ GNU Make 4.1</small>

**Comment by vomikan** [comment]
![screenshot 339](https://user-images.githubusercontent.com/6836805/27995133-c1640736-64d1-11e7-8522-711a931d523e.jpg)

**Comment by slodki** [comment]
I know windows is ok - it's different wxWidgets port (press `Ctrl`+`Alt`+middle mouse button on MMEX window to display wxWidgets port details).

There are some changes in GTK3 port - but Ubuntu uses now GTK2 build of wxWidgets.
