### ISSUE TITLE
MMEX 1.3.1,1.3.3 crash on opening database (windows 10)

### ISSUE THREAD

**Issue by aksnowman** [moneymanagerex/moneymanagerex#1231]
MMEX crashes on my Windows 10 laptop when opening a database I've been using via 1.2.7 Portable
![image](https://user-images.githubusercontent.com/510971/28101632-4d8b6d80-6676-11e7-8ccc-31aa25db772f.png)

I can open MMEX through the first screen, select "Open Existing Database", select the database file I used in 1.2.7, when I hit "Open" MMEX closes the file open dialogue and instantly locks up. After 15-30-ish seconds, I get a "has stopped responding" message.
![image](https://user-images.githubusercontent.com/510971/28101678-8cb90c42-6676-11e7-9eae-50f5f42b5423.png)

After reading through several possibly related bugs, I've already tried opening the MMEX database in 1.2.7 and disabling { web server, check for updates, and send usage statistics }.

Not sure if either of these make any difference, but my mmb file and the corresponding attachments directory are within a dropbox folder, and I have created some reports in 1.2.7.

I may be a day or two between responses (depending on requests for testing), but am very interested in doing what I can to help resolve this issue!

And completely unrelated to this bug, but I don't see "Report a Bug" available under the "Help" menu in 1.3.3
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.

Your OS:
- [x] Windows (10 Pro)
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x (I believe I tested 1.3.1 portable 32/64 bit, and know today I have tested 1.3.3 installed and portable)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by aksnowman** [comment]
For the heck of it, I also tried opening 1.3.3 (installed version) in Windows 7 compatibility mode, Windows 8 compatibility mode, and Windows 7 compatibility mode w/ override high DPI (application) enabled and disable fullscreen optimizations disabled, no change (same result - hanging & crashing after opening database).

**Comment by stef145g** [comment]
Has the database been used by the android version of mmex?

**Comment by stef145g** [comment]
The above may seen as silly question but it may relate to https://sourceforge.net/p/moneymanagerex/bugs/927/

**Comment by aksnowman** [comment]
Not silly at all, yes I do use the Android version as well. I will read more on the linked thread later when I get a chance.
________________________________

**Comment by stef145g** [comment]
I have now updated the release section so you should be able to use [mmex v1.4.0-alpha.1](https://github.com/moneymanagerex/moneymanagerex/releases) which has an automatic detection and fix for this problem.

**Comment by aksnowman** [comment]
Downloaded, but was a late night tonight and is going to be an early morning tomorrow, so at least tomorrow evening before I can try to figure out how to build it from the .zip, thanks!

**Comment by vomikan** [comment]
Jast expract to any folder then run mmex.exe

**Comment by aksnowman** [comment]
Ahh, the Portable version worked perfectly, opened the file, it said it updated the version, and recommended I run the database optimizer. Data seems to be showing, and no crash on initial run. I'll test it out more tonight.

I was initially trying the main download where I didn't see any executables.

**Comment by aksnowman** [comment]
@stef145g Confirmed, I've played around all over in v1.4.0-alpha1 tonight and haven't had any issues. Should I close this issue, or does it need left open for any kind of tracking?

Thanks a ton!

**Comment by stef145g** [comment]
Excellent. It appears that it was worth the effort to provide an automatic detection and fix.
