### ISSUE TITLE
Issue with MAC version of the program

### ISSUE THREAD

**Issue by EvBef** [moneymanagerex/moneymanagerex#1232]
Hello, guys. We were downloading your program and found out you don't have 1.3.3 update for MAC. Can you please tell us the time when the update for 1.3.3 will come. 

Thanks in advance. 

Best regards.

**Comment by omalleypat** [comment]
The download for v1.3.3 is posted in the releases area of GitHub here:
https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.3.3/mmex_1.3.3_macos10.9.dmg
