### ISSUE TITLE
Crash bug with version 1.3.1 for MAC 

### ISSUE THREAD

**Issue by EvBef** [moneymanagerex/moneymanagerex#1233]
Hello, 

Regarding the fact that we can't download the version 1.3.3 we tried to download the version 1.3.1, but it did not let us download it coz mmex-v1.3.1-macOS10.9.dmg is crushing. See the issue file in attach. 

Please, help us to solve this issue. 

Thank you in advance 

Regards
![mmex](https://user-images.githubusercontent.com/30110408/28110021-b15148c0-66f9-11e7-869e-bdbce836892c.png)

**Comment by omalleypat** [comment]
Could you provide an english translation of that message? Thanks!

**Comment by slodki** [comment]
Google:
> The opening of the program "mmex" failed due to damage. Move the program to the trash.
> [...]

**Comment by omalleypat** [comment]
New build of v1.3.3 posted. [Click here for more info.](https://www.moneymanagerex.org/news/item/74-updated-mac-build-v1-3-3)
