### ISSUE TITLE
1.4.0 version - no more cash slow for specific account

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/moneymanagerex#1234]
I updated on 1.4.0 alpha release.

There isn't option for cash flow on specific account or account as like 1.3.3 version ?

thanks

giorgio

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/72a8b09584137982e4e71a8201b00042ab996927

**Comment by ggraziotti** [comment]
Ok, it's closed. But now with version I have to download now ?

**Comment by stef145g** [comment]
You can use AppVeyor builds to get the latest windows versions [here](https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/mmex-1.4.0-ALPHA-1.606/job/8i07pcy9b43mr728/artifacts)
or 
https://ci.appveyor.com/project/guanlisheng/moneymanagerex

You can also refer to [wiki/How-to-download-the-mmex-build]
(https://github.com/moneymanagerex/moneymanagerex/wiki/How-to-download-the-mmex-build) to explain how AppVeyor works.

**Comment by ggraziotti** [comment]
Thanks, I downloaded It.
