### ISSUE TITLE
Update wizard showing old change log ( newest is 1.3.0-Alpha )

### ISSUE THREAD

**Issue by andistern** [moneymanagerex/moneymanagerex#1235]
Sorry to bother, but an accounting software that shows old Versions will not enhance its reputation

> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.

There is no "Report a Bug" - entry in the Help Menu

Your OS:
- [X] Mac OSX 10.11.6

MMEX version:
- [X] 1.3.1

Update Wizard suggest 1.3.3, but available is 1.3.1 only:

https://downloads.sourceforge.net/project/moneymanagerex/v1.3.1/mmex-v1.3.1-macOS10.9.dmg?r=http%3A%2F%2Fwww.moneymanagerex.org%2Fdownload&ts=1499897338&use_mirror=kent

Screenshot:
![bildschirmfoto 2017-07-12 um 12 06 04](https://user-images.githubusercontent.com/1109617/28142171-f7c2fa68-675f-11e7-9617-c944c5081a6e.jpg)

please let me know, what I could do to help!

regards

**Comment by stef145g** [comment]
This has now been updated and 1.3.3 should be available for Mac
A more up to date version is also available for [mmex v1.4.0-alpha](https://github.com/tomasfrtala/moneymanagerex/releases)

**Comment by andistern** [comment]
Thank you very much for the quick reply, the "What's new" Window still shows only Versions from July 1st 2016 and older.

Regards

![bildschirmfoto 2017-07-13 um 08 56 16](https://user-images.githubusercontent.com/1109617/28154177-6115d208-67a9-11e7-8101-1fdcc84ac776.jpg)

**Comment by andistern** [comment]
same applies to 1.4.0-Alpha
![bildschirmfoto 2017-07-13 um 09 03 40](https://user-images.githubusercontent.com/1109617/28154424-51ef5582-67aa-11e7-9fe3-c24d2fdc520f.jpg)

**Comment by guanlisheng** [comment]
@andistern going to close this issue as we are going to use https://github.com/moneymanagerex/moneymanagerex/releases to instead our built-in one.

**Comment by slodki** [comment]
We can use GitHub [Releases API](https://developer.github.com/v3/repos/releases/) to read released versions, dates and descriptions in JSON (see https://api.github.com/repos/moneymanagerex/moneymanagerex/releases).

**Comment by guanlisheng** [comment]
going to close this as i have fixed the note from our homesite and we can consider the improvement on API late
