### ISSUE TITLE
CMake errors on Arch Linux

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#1238]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

I'm not able to build this on Arch Linux 64bit, it gives the following error

```
[ 40%] Building CXX object CMakeFiles/mmex.dir/src/general_report_manager.cpp.o
In file included from moneymanagerex/src/general_report_manager.cpp:20:0:
moneymanagerex/src/general_report_manager.h:102:5: error: ‘wxWebView’ does not name a type; did you mean ‘wxListView’?
     wxWebView* m_outputHTML;
     ^~~~~~~~~
     wxListView
moneymanagerex/src/general_report_manager.cpp: In constructor ‘mmGeneralReportManager::mmGeneralReportManager(wxWindow*, wxSQLite3Database*)’:
moneymanagerex/src/general_report_manager.cpp:230:7: error: class ‘mmGeneralReportManager’ does not have any field named ‘m_outputHTML’
     , m_outputHTML(nullptr)
       ^~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::createOutputTab(wxNotebook*, int)’:
moneymanagerex/src/general_report_manager.cpp:395:5: error: ‘m_outputHTML’ was not declared in this scope
     m_outputHTML = wxWebView::New(out_tab, ID_WEB);
     ^~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp:395:20: error: ‘wxWebView’ has not been declared
     m_outputHTML = wxWebView::New(out_tab, ID_WEB);
                    ^~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnUpdateReport(wxCommandEvent&)’:
moneymanagerex/src/general_report_manager.cpp:634:9: error: ‘m_outputHTML’ was not declared in this scope
         m_outputHTML->SetPage(report->DESCRIPTION, "");
         ^~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnRun(wxCommandEvent&)’:
moneymanagerex/src/general_report_manager.cpp:650:9: error: ‘m_outputHTML’ was not declared in this scope
         m_outputHTML->ClearBackground();
         ^~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnSelChanged(wxTreeEvent&)’:
moneymanagerex/src/general_report_manager.cpp:756:9: error: ‘m_outputHTML’ was not declared in this scope
         m_outputHTML->SetPage(description, "");
         ^~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::showHelp()’:
moneymanagerex/src/general_report_manager.cpp:1008:5: error: ‘m_outputHTML’ was not declared in this scope
     m_outputHTML->LoadURL(url);
     ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/mmex.dir/build.make:591: CMakeFiles/mmex.dir/src/general_report_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/mmex.dir/all] Error 2
make: *** [Makefile:152: all] Error 2```

**Comment by stef145g** [comment]
Looking at your report, it appears that wxWidgets may have a problem on your system. Please check the wxWidgets installation and possibly recompile it. Then recompile mmex.
Works on [other systems](https://travis-ci.org/moneymanagerex/moneymanagerex)

**Comment by vomikan** [comment]
https://www.archlinux.org/packages/extra/x86_64/webkit2gtk/

**Comment by Dialga** [comment]
@vomikan I had both of those packages installed beforehand and it still failed to build.

**Comment by vomikan** [comment]
@tomasfrtala what do you think about this issue?

**Comment by vomikan** [comment]
May be webkitgtk-3.0 ?

**Comment by slodki** [comment]
`webkit2gtk` package is [linked to gtk3](https://www.archlinux.org/packages/extra/x86_64/webkit2gtk/) and when used with `gtk2` gives above errors. Solution is to use `webkit2gtk` with `wxgtk3` both linked to `gtk3`.

It isn't easy because `wxgtk` is buggy in Arch - [wx-config is renamed](https://www.archlinux.org/packages/extra/x86_64/wxgtk3/files/) and not symlinked for compatibility. CMake don't find this tool and stops with _wxWidgets not found_ error. So [workaround](https://github.com/slodki/moneymanagerex/blob/arch-linux-package/dockers/Dockerfile.archlinux#L10) is necessary.

Could you test Arch [binary package](https://github.com/slodki/moneymanagerex/releases/tag/test-arch-linux) built on Travis CI platform? We need use native `makepkg` Arch tool because CPack doesn't support Arch tar.xz packages yet.
