### ISSUE TITLE
64 bit update is still 1.3.1 not 1.3.3

### ISSUE THREAD

**Issue by alankmiller** [moneymanagerex/moneymanagerex#1239]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue
> for similar problem - update existing issue instead of creating new one.
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.
> 4. Put some descriptive name for your issue in the Title field above.
> 5. Replace this text (marked with >) with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 6. Include steps to reproduce your issue, attach screenshots where appropriate.
> 7. Mark (put x inside brackets: [x]) correct answers below.

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by guanlisheng** [comment]
Fixed
