### ISSUE TITLE
MME 1.3.3 for Mac problem with attachment

### ISSUE THREAD

**Issue by mconsonni** [moneymanagerex/moneymanagerex#1240]
With this new release I can't attach nothing to my operation
Option is gray!
![schermata 2017-07-15 alle 16 09 04](https://user-images.githubusercontent.com/30197939/28239959-07719018-6978-11e7-81de-858f609b4214.png)

**Comment by vomikan** [comment]
Thank you for your report.
It is a wxWidgets bug:
http://trac.wxwidgets.org/ticket/17459

**Comment by mconsonni** [comment]
Thank you, but how can I solve it?

**Comment by vomikan** [comment]
We are looking a solution. For now possible solution is downgrade wx and rebuild mmex.

**Comment by omalleypat** [comment]
New build of v1.3.3 posted. [Click here for more info.](https://www.moneymanagerex.org/news/item/74-updated-mac-build-v1-3-3)
