### ISSUE TITLE
Cannot instal PPA

### ISSUE THREAD

**Issue by tosim91** [moneymanagerex/moneymanagerex#1241]
Running Linux Mint 18.2-MATE. Cannot install PPA. Terminal says: "No JSON OBJECT COULD BE DECODED".

**Comment by vomikan** [comment]
I recommend to build the app from scratch
https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.Ubuntu.md

**Comment by vomikan** [comment]
Or try https://packagecloud.io/moneymanagerex/moneymanagerex
