### ISSUE TITLE
Error 11 "database disk image is malformed" after updating to 1.3.3

### ISSUE THREAD

**Issue by jhessin** [moneymanagerex/moneymanagerex#1242]
Your OS:
- [ ] Windows
- [X] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

After updating to 1.3.3 I was able to open and successfully enter several entries into my database. When trying to modify a previous entry I received this error:

Error: 11
database disk image is malformed[11]: database disk image is malformed

Is there any way to recover my data? I haven't backed up my database since march and I really don't want to enter all that info again (I tried downloading the CSV list from the bank and that never works right
![mmex error](https://user-images.githubusercontent.com/6241466/28243799-de924346-6994-11e7-9903-7779cc80cd70.png)).

UPDATE:
When trying to load my backup I got the following errors:

19:39:13: BUDGETSPLITTRANSACTIONS_V1: Exception database disk image is malformed[11]: database disk image is malformed
19:39:13: BILLSDEPOSITS_V1: Exception database disk image is malformed[11]: database disk image is malformed, {
	"BDID" : 32,
	"ACCOUNTID" : 1,
	"TOACCOUNTID" : -1,
	"PAYEEID" : 79,
	"TRANSCODE" : "Withdrawal",
	"TRANSAMOUNT" : 115.76999999999999602,
	"STATUS" : "F",
	"TRANSACTIONNUMBER" : "",
	"NOTES" : "*RECURRING*",
	"CATEGID" : 8,
	"SUBCATEGID" : 31,
	"TRANSDATE" : "2017-07-01",
	"FOLLOWUPID" : -1,
	"TOTRANSAMOUNT" : 115.76999999999999602,
	"REPEATS" : 203,
	"NEXTOCCURRENCEDATE" : "2017-07-01",
	"NUMOCCURRENCES" : -1
}
19:39:13: database disk image is malformed[11]: database disk image is malformed

**Comment by vomikan** [comment]
May be there are others backup files?
Is DB has a copy in Dropbox service?
Are any *.mmb files in DB folder?

**Comment by jhessin** [comment]
I was able to download v.1.3.1 and now the Database works. (phew) - not updating again until they work out the kinks (I thought this was supposed to be the stable build).

**Comment by fsantana** [comment]
I'm having this error when I try to open the file on a Meizu M4 phone with Flyme OS (Android). I sync via Dropbox with my computer and with two devices. In Moto G4 Play (Android 7.1) and in the computer it opens normally, in M4 (Flyme OS 5.1) I get the message: Error: database disk image is malformed (code 11)
