### ISSUE TITLE
Investment Commission when selling is added to total (instead of deducted).

### ISSUE THREAD

**Issue by Adelzu** [moneymanagerex/moneymanagerex#1244]
1) Create Investment Account
2) Add Shares (Which creates a new Shares Account).
3) Sell those Shares deposit transaction (Use the Commission Field).
4) Notice that the deposit amount is calculated as ( NumberOfShares * PricePerShare + Commission). This works file when buying because the entire total is negated in the balance. However in this case it should be (Number of Shares * PricePerShare - Commission).

Your OS:
- [X ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by stef145g** [comment]
This was initially reported on Sourceforge.net https://sourceforge.net/p/moneymanagerex/bugs/1032/
and was fixed with #1187
Available via [Nightly builds on Windows](https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/mmex-1.4.0-ALPHA-1.583-gjdoqxfb)
