### ISSUE TITLE
DB shared with Android problem: CHECKINGACCOUNT_V1: Exeption database disk image is malformed

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/moneymanagerex#1248]
I have a problem with my DB on window 10 64bit (1.4.0 alpha 1 release).
DB is on gdrive account.
I use it with android, work fine.
When I open it on window app say me: CHECKINGACCOUNT_V1: Exeption database disk image is malformed (11).
How to fix it ?
I can create a new DB on android app but:
How to upload it (new one file) on gdrive and sync it on window ?

I haven't backup file.... on GDRIVE or in nylon pc

Thanks
Giorgio

**Comment by stef145g** [comment]
Please refer to #1231 as this may solve this problem

**Comment by stef145g** [comment]
@ggraziotti is this still an issue? 
also please refer to #1250 that will provide sql examples of how to examine your database
Program found here: https://sqlite.org/2017/sqlite-tools-win32-x86-3200100.zip
on SQLite3 site: https://sqlite.org/download.html
