### ISSUE TITLE
MMEX Database upgrade to version 7 failed

### ISSUE THREAD

**Issue by toonarmy1953** [moneymanagerex/moneymanagerex#1250]
Your OS:
- [x] Windows 10
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [x] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

![image](https://user-images.githubusercontent.com/30410490/28525344-cfb57d28-707b-11e7-95b8-ab3fb4cfe135.png)

Version 1.27 is the stable version I am using and have reverted back to when encountered the attached error.
Tried to install 1.31, 1.32 and 1.33 with same issues

**Comment by stef145g** [comment]
This problem is encountered when a database has been upgraded to version 7
This upgrade to the database adds 7 new fields to the accountlist_v1 table.
You will need to examine the database to determine the  database user version number and see what fields are contained in the accountlist_v1. The problem appears to be caused by the mismatch between Android and desktop versions using the same database.

**Comment by stef145g** [comment]
@toonarmy1953 The automatic fix in the 1.4 Alpha release version should fix this problem.
 Is this still an issue?

**Comment by toonarmy1953** [comment]
Hi

Still an issue, using 1.2.7. I will download 1.4 when available and try again

Thank you

**Comment by toonarmy1953** [comment]
Hi Stefano

Installed win64-mmex-1.4.0-ALPHA-3. And got the attached error. Reverted back to 1.2.7 which is stable.

Thank you

Michael

**Comment by stef145g** [comment]
Can you execute the sql commands:
`PRAGMA user_version;`
This will show the current version of the database.
and
`select sql from sqlite_master where name =  "ACCOUNTLIST_V1";`
This will show what fields are in AccountList table.

You should be able to use the General Report manager if you don't have access to a SQLite database program.

**Comment by toonarmy1953** [comment]
Hi Stefano

As requested please find under detail you requested.

SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open martin.mmb
sqlite> PRAGMA user_version;
7
sqlite> select sql from sqlite_master where name = "ACCOUNTLIST_V1";
CREATE TABLE ACCOUNTLIST_V1(ACCOUNTID integer primary key, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */, ACCOUNTNUM TEXT, STATUS TEXT NOT NULL /* Open, Closed */, NOTES TEXT , HELDAT TEXT , WEBSITE TEXT , CONTACTINFO TEXT, ACCESSINFO TEXT , INITIALBAL numeric , FAVORITEACCT TEXT NOT NULL, CURRENCYID integer NOT NULL, STATEMENTLOCKED integer, STATEMENTDATE TEXT, MINIMUMBALANCE numeric, CREDITLIMIT numeric, INTERESTRATE numeric, PAYMENTDUEDATE text, MINIMUMPAYMENT numeric)
sqlite>

Thank you

Michael

**Comment by stef145g** [comment]
Hi Michael, thanks for providing the feedback.

It appears that your database is already at version 7 and mmex should be able to open it. To test this I did the following:

From the sql command CREATE TABLE... you supplied I created a new table as follows:
1. Obtained the command from SQL Command:
`select sql from sqlite_master where name = "BILLSDEPOSITS_V1";`
2. reformatted the output to create 2 new sql commands to include a semi-colon at the end.
3. Using sqlite3.exe I created a new totally empty database
Use `.open test_1.mmb`
4. Created the 2 tables using my newly created commands
5 Reset the user version using the sql command:
`pragma user_version = 7;`
6 Checked that only 2 table names existed in the database using the SQL command:
`select name from sqlite_master;`
7. Opened the newly created table using MMEX

All went well. I ended up with a new database with no data, which I expected.
I cannot appear to duplicate your problem.

**Comment by toonarmy1953** [comment]
Hi Stefano

Me again, I have 2 x files I access and have now established 1 is V7 and the one below is V6, can you shed any light on it.  This file is the one that gets the error as I was able to run the previous one with the updated software.

SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open colmanlyons.mmb
sqlite> PRAGMA user_version;
6
sqlite> select sql from sqlite_master where name = "ACCOUNTLIST_V1";
CREATE TABLE ACCOUNTLIST_V1(ACCOUNTID integer primary key, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */, ACCOUNTNUM TEXT, STATUS TEXT NOT NULL /* Open, Closed */, NOTES TEXT , HELDAT TEXT , WEBSITE TEXT , CONTACTINFO TEXT, ACCESSINFO TEXT , INITIALBAL numeric , FAVORITEACCT TEXT NOT NULL, CURRENCYID integer NOT NULL, STATEMENTLOCKED integer, STATEMENTDATE TEXT, MINIMUMBALANCE numeric, CREDITLIMIT numeric, INTERESTRATE numeric, PAYMENTDUEDATE text, MINIMUMPAYMENT numeric)
sqlite>

Kind Regards

Michael

**Comment by stef145g** [comment]
This is better. Use the command:
`pragma user_version = 7;`
on the database. This will fix it.

**Comment by toonarmy1953** [comment]
Thank you all is now fine.

Very satisfied, love you early responses

Michael
