### ISSUE TITLE
Add slack link to invite end user to join our slack channel

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#1251]
http://slack.moneymanagerex.org/

**Comment by slodki** [comment]
Already added to [about menu](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmframe.cpp#L2517) link to http://slack.moneymanagerex.org/ ([link here](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/constants.cpp#L176))...
❓

**Comment by guanlisheng** [comment]
i meant to the desktop application

**Comment by vomikan** [comment]
![screenshot 363](https://user-images.githubusercontent.com/6836805/28567854-74a07f34-713c-11e7-9924-878c18afa548.jpg)

**Comment by guanlisheng** [comment]
Thanks and seems it is available for v1.4.x
