### ISSUE TITLE
Use PackageCloud as official MMEX repo from next release

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1253]
[PackageCloud](https://packagecloud.io/) is universal packages repo for different distributions with CI support.

Pros:
- free for OS projects
- supported packages:
  - RPM
  - DEB
  - Debian source packages (DSCs)
- integration with Travis CI
- packages GPG signing keys
- download stats with API access
- distributions (multiple versions and arch) supported:
  - Amazon Linux
  - elementary OS
  - Debian
  - Ubuntu
  - Raspbian
  - SUSE Linux Enterprise Server
  - openSUSE
  - Fedora
  - LinuxMint
  - Oracle Linux
  - RedHat
  - CentOS
  - Scientific Linux
- installation instructions with automatic script for end-users available
- automatic new version notification & upgrade for users with native distribution / GUI tools
- we have it [created](https://packagecloud.io/moneymanagerex/moneymanagerex) already 😃 

Problems:
- MMEX cannot be find in official distribution repos by end-user
- user must add new repo (like PPA)
- uploaded files are auto renamed - problem with updating the same version of packages (for example daily dev builds)
- existing doc & instructions should be updated

Is MMEX repo configured as OS repo (25 GB storage and 250 GB bandwidth) or free plan (250 MB & 250 MB - this is to low for us)?

**Comment by vomikan** [comment]
IMHO We should

**Comment by slodki** [comment]
#1262 must be fixed first - see [CI deploy errors](https://travis-ci.org/moneymanagerex/moneymanagerex/builds/261669111)

**Comment by vomikan** [comment]
CLOSE: outdated

REASON: Overtaken by later events regarding MMEX repos.
