### ISSUE TITLE
Register filetypes for mmex at system level in Linux

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1254]
This should allows for mmb/emb/mmdbg files:
- display dedicated icon
- display informative description
- associate default application

XDG standard:
- [Shared MIME-info Database](https://specifications.freedesktop.org/shared-mime-info-spec/latest/)
- [Association between MIME types and applications](https://specifications.freedesktop.org/mime-apps-spec/latest/)
- [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/)
- ArchLinux [description](https://wiki.archlinux.org/index.php/default_applications)

#1206 could be used

**Comment by ovari** [comment]
@joshua-stone are you able to implement this? Thank you

**Comment by joshua-stone** [comment]
I don't know of how to do all of the translations, but there are many examples to go on:

https://invent.kde.org/multimedia/kdenlive/-/blob/master/data/org.kde.kdenlive.xml

**Comment by ovari** [comment]
Does the Xournal++ file https://github.com/xournalpp/xournalpp/blob/master/desktop/com.github.xournalpp.xournalpp.xml can help with translations? The code from the file is shown below.

```
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
	<mime-type type="application/x-xojpp">
		<comment>Xournal note file</comment>
		<comment xml:lang="hu">Xournal jegyzetfájl</comment>
		<glob pattern="*.xoj"/>
	</mime-type>
	<mime-type type="application/x-xopp">
		<comment>Xournal++ note file</comment>
		<comment xml:lang="hu">Xournal++ jegyzetfájl</comment>
		<glob pattern="*.xopp"/>
	</mime-type>
	<mime-type type="application/x-xopt">
		<comment>Xournal++ note file</comment>
		<comment xml:lang="hu">Xournal++ jegyzetfájl</comment>
		<glob pattern="*.xopt"/>
	</mime-type>
</mime-info>
```

Other Xournal++ files which have translations are:
* https://github.com/xournalpp/xournalpp/blob/master/desktop/com.github.xournalpp.xournalpp.desktop
* https://github.com/xournalpp/xournalpp/blob/master/desktop/com.github.xournalpp.xournalpp.appdata.xml

Thank you

**Comment by ovari** [comment]
@joshua-stone could you please create the file and contents without translations?  Please advise where the file is located so Hungarian translations can be added later. Thank you

**Comment by joshua-stone** [comment]
I've added files here:

https://github.com/moneymanagerex/moneymanagerex/pull/6005

**Comment by ovari** [comment]
Should the milestone be changed to 1.6.4? Thank you

**Comment by ovari** [comment]
Is `SQLite3 database` showing instead of `MMEX database`? Is so, should this issue be re-opened? Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/02cff7c5-81b9-464d-a6d6-0586a98efd68)

```
Money Manager Ex
• Version: 1.6.4-Beta.7 64-bit
• Built on: Jun 15 2023 22:59:53
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-43-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by ovari** [comment]
Verified fixed. Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/65e48e18-819e-4d7a-b8a7-6c41bcee4dcf)

```
Money Manager Ex
• Version: 1.6.4-Beta.8 64-bit
• Built on: Jun 17 2023 03:26:43
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-43-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by ovari** [comment]
Verified hu (Hungarian - magyar) locale fixed. Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/6f1a5d08-d6e3-4ccf-9a7b-4275ed6e4dc1)

**Comment by ovari** [comment]
At [Features](https://github.com/moneymanagerex/moneymanagerex#features):

> International language support: [Crowdin](https://crowdin.com/project/moneymanagerex), [Desktop icon](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/applications/org.moneymanager.MMEX.desktop), [AppData](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml), [Filetype associations](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/mime/packages/org.moneymanager.MMEX.mime.xml)

Links don't work as missing `ex`, hopefully fixed with https://github.com/moneymanagerex/moneymanagerex/pull/6025

Thank you
