### ISSUE TITLE
Register filetypes for mmex at system level in Windows

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1255]
This should allows for mmb/emb/mmdbg files:
- display dedicated icon
- display informative description
- associate default application

Should be done by installer for all Windows users.

**Comment by slodki** [comment]
Some info about NSIS installer: sqlitebrowser/sqlitebrowser#279

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: Nice to have but not essential. Users can associate .mmb with MMEX app via file Properties.
