### ISSUE TITLE
Toolbar icons active but not working when no database is opened

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1256]
Steps to reproduce:
1. Start MMEX
2. Click `Create a New Database` at start-up dialog
3. Click `Cancel` at `Choose database file to create` dialog
4. Click on toolbar icons
    - Transaction Report Filter
    - Show the Options Dialog
    - New Transaction
5. Above icons are active but do nothing. They should be inactive

Related to #1245

<hr><small><b>Version</b>: 1.4.0-Alpha.1 ⬥ db 7 ⬥ git 7e43643 (2017-07-24)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 6.3) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Jul 24 2017 20:28:26 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 8.1 (build 9600), 64-bit edition Little endian ⬥ Polish windows-1250 ⬥ 1680x1050x32bit 98x98ppi</small>

**Comment by stef145g** [comment]
Ref PR #1263
