### ISSUE TITLE
Inconsistent copyright info

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1257]
There are different copyright statesments displayed in different places of mmex. They should be the same.

* [about dialog](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/constants.cpp#L88)
  `Format("(c) 2005-%d Madhan Kanagavel", COMPILE_YEAR)`

* [license.txt](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/license.txt#L20)
  >Copyright (C) 2009-2017 Nikolay
Copyright (C) 2011-2017 LiSheng [guanlisheng]
Copyright (C) 2013-2016 James [siena123]
Copyright (C) 2013-2017 Gabriele[gabriele-v]
Copyright (C) 2010-2017 Stefano [stef145g]
Copyright (C) 2009-2010 VaDiM, Wesley Ellis
  >
  >Copyright (C) 2005-2009 Madhan Kanagavel

* [contrib.txt](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/contrib.txt#L364)
  >Copyright (C) 2009-2017 Nikolay
Copyright (C) 2011-2017 LiSheng [guanlisheng]
Copyright (C) 2013-2016 James [siena123]
Copyright (C) 2013-2017 Gabriele[gabriele-v]
Copyright (C) 2010-2017 Stefano [stef145g]
Copyright (C) 2009-2010 VaDiM, Wesley Ellis

* [help file english/russian](https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/index.html#L2117)
  >Ⓒ 2005-2009 Madhan Kanagavel

* [help file polish](https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/index_pl.html#L1922)
  >Copyright ª 2005-2013  CodeLathe LLC. All rights reserved.

* [help file spanish](https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/index_sp.html#L1745)
  >Copyright Ⓒ 2005-2016, CodeLathe LLC. Todos los derechos reservados.

* [help file hungarian](https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/index_hu.html#L1607)
  >Copyright ª 2005-2011  CodeLathe LLC. All rights reserved.

![mmex-license2](https://user-images.githubusercontent.com/3155552/28591797-3c81958e-7187-11e7-9aa0-855aa29fe12f.png)
![mmex-license](https://user-images.githubusercontent.com/3155552/28590814-cb37b94c-7183-11e7-8ece-a65c2b99cd86.png)

See also #763.

**Comment by vomikan** [comment]
How it should be?
Ⓒ 2005-2009 Madhan Kanagavel

**Comment by slodki** [comment]
Why not:

  >Copyright (C) 2009-2017 Nikolay
Copyright (C) 2011-2017 LiSheng [guanlisheng]
Copyright (C) 2013-2016 James [siena123]
Copyright (C) 2013-2017 Gabriele[gabriele-v]
Copyright (C) 2010-2017 Stefano [stef145g]
Copyright (C) 2009-2010 VaDiM, Wesley Ellis
Copyright (C) 2005-2009 Madhan Kanagavel

**Comment by slodki** [comment]
Next case:

* [mmex.rc](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/mmex.rc#L73)

  >Copyright (C) 2017 Money Manager EX

**Comment by vomikan** [comment]
I've counted 3 main copyrights:
- [v] © 2005-2009 Madhan Kanagavel  
- [ ] 2005-2008 CodeLathe LLC
- [ ] Copyright (C) 2017 Money Manager EX

I think we should leave 2 points: Madhan and MMEX team

- [ ] Copyright (C) 2013 - 2018 MMEX Team

**Comment by slodki** [comment]
It should be clear if ther is one copyright holder or group of individuals. As MMEX project does not require CLA (Contributor License Agreement) i think we should use someting like "MMEX Team" with link to list of authors.

**Comment by vomikan** [comment]
I am a team member and never be a part of CodeLathe LLC

Madhan Kanagavel is author who developed till 2009. And  CodeLathe LLC his child.

**Comment by slodki** [comment]
My proposal:
> Copyright Ⓒ 2005-2009 Madhan Kanagavel
> Copyright Ⓒ 2013-2018 MMEX contributors

Plural form is better here IMHO. Team is not strictly defined (there are GitHub teams for example...) and can be separate organization and single copyright holder.

https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

**Comment by ovari** [comment]
Does the information in the red box need to be removed too:
![image](https://user-images.githubusercontent.com/17465872/45219709-1f7cca80-b2ef-11e8-93e8-90dc440458d4.png)
