### ISSUE TITLE
share transaction sell stocks commission calculate issue 

### ISSUE THREAD

**Issue by cloudmaple** [moneymanagerex/moneymanagerex#1259]
Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

In share transaction, selling stocks's commission is being calculated in a wrong way.
The total deposit should be (share number) x (share price) - commission

It is different from buying stocks.

**Comment by stef145g** [comment]
Please refer to #1244

**Comment by slodki** [comment]
PR #1187
