### ISSUE TITLE
Add envelope budgeting option

### ISSUE THREAD

**Issue by kennydrobnack** [moneymanagerex/moneymanagerex#1260]
A great feature to add would be the ability to do what is called "envelope style" budgeting to budgets. An example of how I would think this should work:

1. When creating a budget, there would be an option to do envelope style or not. If you leave this unchecked, budgets would continue to behave as they currently do.
2. If you check the envelope style option when creating the budget, it would give you the option to set a starting balance for each category. In the reports and budgets, it would show the following for each month:
    * Starting balance
    * Added amount for the month
    * Remaining at the end of the month.

**Comment by stef145g** [comment]
After seeing an explanation for Envelope Budgeting, I like the concept which is the reason for assigning this to myself.

As in your point 2, would this be on each category or category branch head?
  
I was thinking on a different approach. As a concept, I was thinking about creating budgeting accounts, where transactions in a budget account were actually the same transaction in a real account, but I am investigating the method and feasibility of adding this feature.

**Comment by slodki** [comment]
Do you mean http://www.wikihow.com/Do-Envelope-Budgeting or https://www.daveramsey.com/blog/envelope-system-explained?

It's supported in mmex already as multiple cash type accounts:
1. Configure mmex with your normal accounts (i.e. wallet cash, checking bank acc, credit card)
2. Add new cash account with name "groceries budget"
    - you can set initial balance during creating account
    - you can select custom icon for this acount
3. Add amount to your budget by:
    - creating transfer transaction from your other account (i.e. wallet, bank account)
    - direct deposit transaction from outside world (from other people, your paycheck etc.)
4. Spend your money from this budget category as withdrawal transactions
5. All mmex views and reports can display your operations from "groceries budget" account as aggregates or details, can be reported daily/weekly/monthly...
6. Your cash in envelopes is displayed in cash accounts summary

**Comment by kennydrobnack** [comment]
> As in your point 2, would this be on each category or category branch head?

> I was thinking on a different approach. As a concept, I was thinking about creating budgeting accounts, where transactions in a budget account were actually the same transaction in a real account, but I am investigating the method and feasibility of adding this feature.

stef145g,
I was thinking the budgets would be per sub-category. For example I've got a category called "Needs" and within that are sub-categories like "Gas", "Groceries", and "Utilities" Each category would have its own budget.

I was looking around at how budgets are implemented, especially at the database layer and my suggestion seemed to be the easiest way to get this functionality. Of course, that may not be the best option. I know some other applications implement budgets as some kind of account that money can be deposited into or withdrawn from. The one thing I'd want to be sure of with this: I want to make sure that transactions that impact a budget would come out of the budget no matter what account the transaction happens in. I hope that makes sense.

Some kind of virtual account may be another option.

**Comment by kennydrobnack** [comment]
> Do you mean http://www.wikihow.com/Do-Envelope-Budgeting or https://www.daveramsey.com/blog/envelope-system-explained?

> It's supported in mmex already as multiple cash type accounts:

slodki,
I've been a pretty avid follower of Dave Ramsey's teachings for quite a while, so I was thinking more like an electronic version of the cash envelope system. You would take any money you have available in your checking account or cash and distribute it into virtual envelopes. When you spend money from any of those accounts, or even credit cards, the money would be taken out of your budget category.

I don't think the budget setup you suggested would work for my workflow. Sounds like a GREAT setup if you're doing all cash, or some other setup with only one account. I'm budgeting across multiple accounts, and probably with a few too many categories to be manageable with multiple accounts.

**Comment by stef145g** [comment]
When @kennydrobnack mentioned this on Slack I had the same idea as @slodki , but I realised that this would have implications on attempting to reconcile accounts. This is the reason for coming up with the idea of creating Budget Accounts. These would be virtual accounts connecting transactions of real accounts to the actual budget "envelope" via the transactions. As a concept I believe this would work, but I still need to figure out the actual implementation of how this would be implemented.

**Comment by aksnowman** [comment]
Just pinging in that I would *love* this functionality as well! I will try to poke around and see if I can come up with a reasonable way to implement something like this, too.

**Comment by seevali** [comment]
Any update regarding this?

**Comment by jasonrush** [comment]
Hello,

Unfortunately life got busy and Money Manager Ex is too detailed for the wife and I to keep up on, so I've moved on to less detailed budgeting solutions.

Jason Rush
Systems Administrator
(806) 686-4264
jason@jason-rush.com<mailto:jason@jason-rush.com>
[logo]

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: Complex feature request, overtaken by subsequent budgeting enhancements.
