### ISSUE TITLE
Linux packages should follow naming standards

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1262]
Should be:
* Ubuntu `mmex_1.4.0~alpha3-0ubuntu12~zesty_amd64.deb`
* Debian `mmex_1.4.0~alpha3-12~stretch_amd64.deb`
* Fedora `mmex-1.4.0.alpha3-12.fc24.x86_64.rpm`
* etc.

where
* 1.4.0.alpha3 is mmex version
* 12 is package version distributed
* zesty/stretch/fc24 are distribution codenames

CMake has support for [CPACK_DEBIAN_FILE_NAME](https://cmake.org/cmake/help/latest/module/CPackDeb.html#variable:CPACK_DEBIAN_FILE_NAME)=DEB-DEFAULT and [CPACK_RPM_FILE_NAME](https://cmake.org/cmake/help/latest/module/CPackRPM.html#variable:CPACK_RPM_FILE_NAME)=RPM-DEFAULT already.

**Comment by stef145g** [comment]
I agree.

In the Windows file spec, the build number was also included, but would have no reference in the Mac or Linux builds.

The package name change occurred in the conversion to automatic builds via cmake.

**Comment by slodki** [comment]
We can add commit hash to the daily builds (not for distribution) but to identify files on developer disk 😄 

I don't know how to calculate in CMake build number / package version. It could be CI build number, but for Travis it's not reset at version change, and it will have gaps (7->24->156, not 1->2->3...). And will be empty if build on local computer, not CI platform.

**Comment by slodki** [comment]
Arch Linux: mmex-1.4.0.alpha3-12-x86_64.pkg.tar.xz

**Comment by NHellFire** [comment]
Just so you know, the Ubuntu versioning format you have is incorrect. Ubuntu's matches Debian's and ubuntu# is only appended to the revision if there are Ubuntu specific changes required.

Daily builds would be best using 1.4.1~gitDATE.COMMIT. Where 1.4.1 is the version number for the next stable release, DATE being the commit date in YYYYMMDD and COMMIT being the short commit hash.

**Comment by slodki** [comment]
I used 0ubuntuX to indicate we use different build script for Debian and Ubuntu packages.

**Comment by NHellFire** [comment]
Shouldn't need different scripts for Debian and Ubuntu. The majority of packages build the same.
I'm just interested because I'm looking at packaging this in a way suitable for a PPA. For inclusion in official repos, it would require dynamic linking against third-party libraries and not building them in-tree: https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code

**Comment by slodki** [comment]
Now we have blocker #1331 for Debian/Ubuntu builds...

**Comment by slodki** [comment]
@NHellFire we are using dynamic linking against distro packages where possible. But some packages from official repos are unusable - see #1612, #1473.
It's better to have working app in unofficial repo then non-working one in official repo.
