### ISSUE TITLE
Cannot start mmex 1.3.3.

### ISSUE THREAD

**Issue by jax79sg** [moneymanagerex/moneymanagerex#1266]
After download the dmg and overwriting the mmex.app. Start the app and encounter this error.
"mmex cannot be opened because of a problem.
Check with the developer to make sure mmex works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS."

Your OS:
- [ ] Mac OS Sierra. version 10.12.6

MMEX version:
- [ ] 1.3.x

Crashlog:
Process:               MMEX [1227]
Path:                  /Applications/mmex.app/Contents/MacOS/MMEX
Identifier:            com.yourcompany.MMEX
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MMEX [1227]
User ID:               501

Date/Time:             2017-07-30 12:45:28.340 +0100
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12

Time Awake Since Boot: 11000 seconds
Time Since Wake:       6500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/wxmac/lib/libwx_osx_cocoau_core-3.0.dylib
  Referenced from: /Applications/mmex.app/Contents/MacOS/MMEX
  Reason: image not found

Binary Images:
       0x100e21000 -        0x1014fdfff +com.yourcompany.MMEX (1.0 - 1) <7BC8317B-F1A7-3B1F-9297-EE4910695461> /Applications/mmex.app/Contents/MacOS/MMEX
       0x10655c000 -        0x106599dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff8b033000 -     0x7fff8b23fff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <01518CAB-7DAD-3F09-83F8-B9FE0ABE998F> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff8b79d000 -     0x7fff8b79dfff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8bc55000 -     0x7fff8bc55fff  com.apple.Cocoa (6.11 - 22) <85EDFBE1-75F0-369E-8CA8-C6A639B98FA6> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff8e1ca000 -     0x7fff8e260ff7  com.apple.framework.IOKit (2.0.2 - 1324.60.3) <7CE4C98B-107C-3AAA-B49A-F2ACFCBBF526> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff91230000 -     0x7fff9123efff  com.apple.opengl (14.0.16 - 14.0.16) <167C9883-A79E-3B7F-AFED-8CD6683B291D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffa0448000 -     0x7fffa0449ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib

**Comment by jax79sg** [comment]
Further update.
Attempted to build wxwidget. However encounter error on QTKit/QTKit.h file not found.

**Comment by jax79sg** [comment]
Solved the problem by brew install wxmac

**Comment by guanlisheng** [comment]
thanks @jax79sg and feel free to join our slack channel.  slack.moneymanagerex.org
