### ISSUE TITLE
Transaction Report - Blank Entries in v1.3.3

### ISSUE THREAD

**Issue by ceshaz** [moneymanagerex/moneymanagerex#1269]
Hi there, 

I am trying to generate a general report from "Transaction Report", but it brings only empty entries. 
On previous versions, I used to select only Account name and Date Range to generate them. 
I tested on version 1.3.1 with the same filter setting and everything worked fine. 
The current version is MMEX version is a portable 1.3.3. 

Tks

**Comment by vomikan** [comment]
How to reproduce?

**Comment by ceshaz** [comment]
Please, see attached print screens with the same procedures (the first two are from 1.3.1 portable, followed by other two from 1.3.3 portable). Both versions are 64 bit windows portable and using the same encrypted (.emb) database.
Let me know if you need any additional information.
Tks 




![1 3 1 - filter](https://user-images.githubusercontent.com/16801805/28786590-0620e978-75f0-11e7-9c6a-d3f7fec7eb8b.png)
![1 3 1 - result](https://user-images.githubusercontent.com/16801805/28786589-061d66b8-75f0-11e7-8b3c-bd159cf9a697.png)
![1 3 3 - filter](https://user-images.githubusercontent.com/16801805/28786593-062e56bc-75f0-11e7-94c4-9ff182294f87.png)
![1 3 3 - result](https://user-images.githubusercontent.com/16801805/28786592-062863e2-75f0-11e7-81ce-1b389c9c5209.png)

**Comment by vomikan** [comment]
Ì've created ned DB from scratch in mmex 1.3.1. Put one transaction into "Pessoal (Conta Corrente)" cash account. Create a report. Then open the just created DB in mmex 1.3.3. Working.
![screenshot 380](https://user-images.githubusercontent.com/6836805/28813893-e2ae06ec-76a3-11e7-9b5c-184f768a5ce3.jpg)
![screenshot 379](https://user-images.githubusercontent.com/6836805/28813898-e65ef5c6-76a3-11e7-88e9-f47c514f05c6.jpg)

**Comment by ceshaz** [comment]
I deleted the portable version and installed a new 64bit version.

Everything worked fine now. Thanks! 

Btw, this app is really great!
