### ISSUE TITLE
Stable code link down loads unstable Alpha for Mac

### ISSUE THREAD

**Issue by sndgibson** [moneymanagerex/moneymanagerex#1270]
Attempting to download 1.3.3 for MacOS and the link is for the 1.4 Alpha
Thanks

Your OS:
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by guanlisheng** [comment]
@sndgibson this link has been fixed
