### ISSUE TITLE
Cannot edit Payees in v.1.3.3

### ISSUE THREAD

**Issue by wirmike** [moneymanagerex/moneymanagerex#1273]
After upgrading to 1.3.3 I cannot amend (edit) Payee names
The 'edit' option on right-click in the list of payees in Organise Payees is greyed-out on the chose (highlighted) payee and also in the Cog menu if the Payee is fully specified in the Search field.

This worked on previous release.

No other issue found w/this release.

OS: Sierra 10.12.5.

Hope this helps.

Regards

Your OS:
- [ ] Windows
- [X] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by omalleypat** [comment]
New build of v1.3.3 posted. [Click here for more info.](https://www.moneymanagerex.org/news/item/74-updated-mac-build-v1-3-3)

**Comment by slodki** [comment]
duplicate of #1219
