### ISSUE TITLE
Transaction filter shows no transactions even when matching transactions exist

### ISSUE THREAD

**Issue by ZaccyM** [moneymanagerex/moneymanagerex#1276]
When filtering transactions or generating a transaction filter report, no transactions appear if the ending date of the date range is today's date even if there are other matching transactions on dates included within the date range.

Steps to reproduce:
1. Click on "Transaction Report" under the "Reports" subtree in the navigation section.
2. Select the "Date Range" filter and set the second date to today's date and the first date to an earlier date, ensure there are transactions on a date earlier than today's date.

Your OS:
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
This issue will fixed in v 1.4.0
Nightly builds are already available here:
https://ci.appveyor.com/project/slodki/moneymanagerex
