### ISSUE TITLE
Reports to compare analogous period from current month with X previous months

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/moneymanagerex#1286]
ON REPORT SECTION ON THE LEFT:

1 - Is possible to add the options DAILY, ANNUAL in addition to MONTLY and SUMMARY, on all reports ?

2 - Is possible to add a report for **montly fraction** ? (Example today is 11th day of the month. Make a report **from day 1 to day 11** (better if customizable interval 1 to 31), for the **previously 12 months** (better if customizable interval from 1 to X previous months). Theese reports for income/expense, categories...). Should be better for compare actual month interval performance, with previous months performaces.

**Comment by slodki** [comment]
Do you mean:
- *current month* (from 1st to today)
- *current year* (from Jan 1st to today)
- *year ago* (from the same date but year ago +1 day to today)

"Previously X months" you have used can have different meaning for different people...

**Comment by ggraziotti** [comment]
X months, is like 1, 2, 3.... (Number of previously months to compare).

Report should be compare: A customizable interval of days,  with the same interval of previous months, for: caterories, income, expence, income/expence.....

**Comment by ggraziotti** [comment]
Example: Report applied to current year, should compare, the same days interval (customizable), of every months, from GEN to AUG.

**Comment by slodki** [comment]
When today is Mar 10 *previous month* could be:
1. February from 1st to 28th (without last 10 days from March), 28 days
2. Last 30 days (when month is defined as 30 day like in banking) from Mar 9th to today, 30 days
3. Last 31 days (when month is defined as such by someone) from Mar 8th to today, 31 days
4. From N+1 day in last month to today - from Mar 11 to today, 28 days

I think 1st meaning is the most natural but is different then your IMHO.

All above can have variants with end of period on last midnight or with current day included...

**Comment by ggraziotti** [comment]
If today is MAR 10, actual interval is from 1 to 10 of MAR, previous month interval to compare is, from 1 to 10 of February. 😀 Same period of different months.
Report have to compare 1 to 10 days of previously months, Feb, Gen, Dec, Nov.....

**Comment by ggraziotti** [comment]
Same month interval, applied to previously months.

**Comment by slodki** [comment]
So this should be something like comparing budget execution for similar period in previous months (or maybe years). To discover someone spends money on something faster then in previous month but slower then in May...

**Comment by ggraziotti** [comment]
Yes.
So user should be monitor same/similar period, compared with previous period. Example interval of 3 to 7 day interval of current month, with 3 to 7 day interval of, previously 12 months, current year months, last 24 months.....

**Comment by slodki** [comment]
It can be useful to compare first X days of current year with first X days of previous year too...

**Comment by ggraziotti** [comment]
Yes

**Comment by ggraziotti** [comment]
If the input is customizable, can be useful to compare erevithing you want. Should be comparable for example: on a specific account and or specific category and or payee, compare 1-10 day interval of current month, with 3-23 day interval of previously months. The report can be very elastic, if input is customizable on: day interval 1, day interval 2 to compare, period to compare (previous month, current year, last X months, last 1 or 2 or 3 years, all historical period) on all or specific categories, accounts, payee.

**Comment by ggraziotti** [comment]
Can be the reports proposed useful ?
Should my propose have future on MMEX development activity, on future milestone ?

**Comment by slodki** [comment]
If only someone wants to code this...

**Comment by ggraziotti** [comment]
ok, tks. I'm waiting, and follow.

**Comment by vomikan** [comment]
Do you need somthing like this?
https://github.com/moneymanagerex/general-reports/tree/master/CategoriesStatLast12Months

**Comment by ggraziotti** [comment]
No, the report that You poster, is for months. 
I santi a report for a part of the months.

**Comment by vomikan** [comment]
I am not affirm that the report above is exactly are you looking for.
That report may be changed for your needs.

**Comment by ggraziotti** [comment]
Yes, of corse. Tks

**Comment by vomikan** [comment]
This should be reported here
https://github.com/moneymanagerex/general-reports/issues

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/general-reports/issues/44

**Comment by vomikan** [comment]
@ggraziotti could you please check SQL that provided under link above?

**Comment by ggraziotti** [comment]
I will test it on next Saturday, tks

**Comment by ggraziotti** [comment]
tested the code today 5 febbrary 2018. So I expected a report for income/expenses from 1th to 5th days of each months. The report would be better detailed for income and expenses and on each category.

There are 2 main problem:

    the report for previous months report the data for all the month, not only the part for period from1 to 5 days, of each the previous months.
    The report qork only on expenses and not on income.

tks

giorgio
