### ISSUE TITLE
Problem following the latest instructions in BUILD.md

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1293]
Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

I realise the changes to the build are still a "work in progress" but thought I would try to build from scratch after the removal of the pre-built VS project files and using the latest BUILD.md instructions. I am running an upto date version of Win10 Creators and VS2017 Community
Hit a problem trying to create Project file or NMAKE when running under the VS 2017 Command prompt with messages as follows (my italics)..
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cd D:\Projects\moneymanagerex\build

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release ..
_CMake Error: The source directory "C:/Program Files (x86)/Microsoft Visual Studio/2017" does not appear to contain CMakeLists.txt._
Specify --help for usage, or press the help button on the CMake GUI.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
_CMake Error: The source directory "C:/Program Files (x86)/Microsoft Visual Studio/2017" does not appear to contain CMakeLists.txt._
Specify --help for usage, or press the help button on the CMake GUI.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community> 

CMakeLists.txt is present in the moneymanager directory and copying it to D:\Projects\moneymanagerex\build does not help. Any idea on what I am doing wrong ?

**Comment by slodki** [comment]
Your `cd D:\Projects\moneymanagerex\build` is not working for some strange reason.

`cmake` command must be run from build directory (where temporary and binary files will be created) and path to the source tree must be passed as an argument - if you use `build` subdir this is `..`, if you use old `build\release` this is `..\..` or you can simply use your `D:\Projects\moneymanagerex\build`.

**Comment by stef145g** [comment]
For windows the best option is to download and install cmake-3.9.0-win64-x64.msi then use the windows GUI interface.

On opening the application, select the project and a build location, then use the configure and generate, you can create the msvc project files. 
![cmake](https://user-images.githubusercontent.com/6927151/29267915-1292287c-812e-11e7-9346-e602f0015c9f.png)

This gives an example of the output you should get, then you can open the project which will lunch msvc on the correct project

This works on Win10 version 1703 build 15063.540

**Comment by stef145g** [comment]
open the build.md file https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#microsoft-windows-with-visual-studio 
and select the gettext link. Download and install the package then run cmake again. This should now work

**Comment by grumpy235** [comment]
Stefano,
Thanks I'll give that a go - I had already downloaded Cmake 3.9.0 but had not used the gui.
I have just compiled successfully what I generated in my previous reply.
When I execute the mmex I generated in D:\Projects\moneymanagerex\bin\Release then I get an error message telling me D:\Projects\moneymanagerex\bin\Release\res\home_page.htt cannot be found - which is reasonable as the res folder has not been created. Looking through CMakeLists I can see reference to it...
ELSEIF(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    SET(INSTALL_DOC_DIR ".")
    SET(INSTALL_RES_DIR "res")
    SET(INSTALL_PO_DIR "po")
    SET(INSTALL_MO_DIR "po/en")
and later
# Resources
INSTALL(FILES
        "${CMAKE_SOURCE_DIR}/3rd/ChartNew.js/ChartNew.js"
        "${CMAKE_SOURCE_DIR}/3rd/sorttable.js/sorttable.js"
        "${CMAKE_SOURCE_DIR}/resources/home_page.htt"
        "${CMAKE_SOURCE_DIR}/resources/kaching.wav"
        "${CMAKE_SOURCE_DIR}/resources/master.css"
        DESTINATION "${INSTALL_RES_DIR}")

Should CMAKE have created the directory and done the copy or have I made an error?

**Comment by slodki** [comment]
@stef145g can give you detailed instruction where to change settings in VS GUI.

Default build command only produce exe file and do not prepare rest of the resources. You must build `install` or `package` target to move all required files in one place (with `install` target) and build installer/zip from them (with `package` target). Yes, you are right - cmake has all required logic for this task already.

I see we need additional instructions in BUILD.md for GUI lovers :smile:

**Comment by grumpy235** [comment]
Slodki,
OK - I'll have a play.
I started with command line processes back in the '70s but have been converted, too much hard work remembering command line syntax 😄

**Comment by stef145g** [comment]
@grumpy235, You can get the INSTALL project to run correctly if you change line 289 in CMakeList.txt
from
"${CMAKE_SOURCE_DIR}/bin/${PROJECT_TARGET_BIN}.exe"
to
"${CMAKE_SOURCE_DIR}/bin/**Release/**${PROJECT_TARGET_BIN}.exe"

Also in the CMake GIUI (shown above), make the change to the line containing **CMAKE_INSTALL_PREFIX** similar to the line in the picture above. 

After each change to the GUI parameters, you must Configure, Generate and Open Project
In the project, use the Project Only option to select the correct project. as shown
![screenshot 2017-08-17 21 21 24](https://user-images.githubusercontent.com/6927151/29410017-27cefb5a-8392-11e7-8aa1-a00046ec6b04.png)

Explanation:
Location of my repo is: c:\git\moneymanagerex.master
(Reason for .master is that I sometimes use multiple copies of the moneymanagerex repo)
The CMAKE_INSTALL_PREFIX is set as to release (above) or change release to debug and rerun the configure/generate/open_project and build INSTALL

This generally only needs to be run once unless you delete the location of the builds. Even though the release version is copied for debug and release, the MSVC GUI will still recognise the newly created builds of debug or release. This is a work around until we find a final solution for CMake.

**Comment by grumpy235** [comment]
Stefano,
Many thanks for the explanation - the penny has just dropped on why there are now 8 projects! I'll give it a go.
I guess this will get sorted once Gabriele and slodki fix up Pull 1299

**Comment by slodki** [comment]
Please check if PR #1312 is enough to close this issue.

**Comment by grumpy235** [comment]
Looks like it, I'll give it a go later this week.
Thanks for all the hard work
