### ISSUE TITLE
Hot key for 'enter' & 'tools' is the same 

### ISSUE THREAD

**Issue by flyhmstr** [moneymanagerex/moneymanagerex#1295]
alt-t is used for main menu 'Tools' and the 'Enter' button in the recurring transactions screen effectively preventing the use of a hot key for 'Enter'

Your OS:
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

1.3.3 for Windows

**Comment by vomikan** [comment]
@flyhmstr how to reproduce it?

**Comment by flyhmstr** [comment]
Enter "Recurring Transactions" screen
Select a transaction to enter
Depress and hold "alt", the hot key identifiers appear on the menu bar and buttons in the recurring transaction screen.

The hotkey assignment for "Tools" in the main menu and "Enter" in the recurring transaction screen are both set to "alt-t"

In my testing now following this sequence alt-t brings up the "Enter recurring transaction" dialog, a second use of alt-t brings up the Tools main menu drop down.

On other tests, if the mouse is clicked in the white space in the navigation bar on the left (without changing the selected screen) alt-t becomes the Tools drop down on the first and subsequent uses.

Suggestion, the hot key mapping for the "Enter" button in the recurring transaction screen should be changed to something else which is currently unused.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2929

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/3570/commits/e5553c6cdca9b32d19108445bdc0da77916c9409
