### ISSUE TITLE
Year end rollover

### ISSUE THREAD

**Issue by Big-Mug** [moneymanagerex/moneymanagerex#1297]
>This is bog standard, my financial year ends I won't to create a new year with all balance brought forward.  Have been asking for this but nobody seems interest, only interested if you are a geek or techy.  Accounting structures seem less important

**Comment by stef145g** [comment]
Generally data is just added to the existing database and the database can have multiple years. Use the transaction filters to get the required year or financial year. Not sure why this is requested.

**Comment by stef145g** [comment]
The database I use for my data contains over 7 years of data and makes it real easy to track expenses in any year, including the new financial year.

**Comment by Big-Mug** [comment]
All true, but does prove that programming has become lay as a result of memory and storage becoming cheaper and more powerful. If this is to take its place as accounting software, it should apply accounting rules.  A year end roll over is far better than storage of huge amounts of data. If businesses used that rule heaven help us!

**Comment by jesuswearspink** [comment]
@Big-Mug  I totally agree with you. I would much prefer that there be an option to do it year by year

**Comment by Dandy64** [comment]
> Generally data is just added to the existing database and the database can have multiple years. Use the transaction filters to get the required year or financial year. Not sure why this is requested.

I absolutely agree! To be honest I do not understand the "roll over" term at all. What does it mean? 
I keep all the data for previous years in the DB and filters allow me to receive any information I need any year or/and months etc.
OK, maybe it is important for small businesses I dunno. 

_"I would much prefer that there be an option to do it year by year"_
What does it mean - year by year?

Perhaps this is an important term in accounting, but from a database view, everything must be saved and kept forever and nothing can be deleted.
Even more, I can say that if the user deleted anything, this is not physical delete, rather logical delete! The saved data is still kept in the DB, but it is just marked like "deleted". That's mean that it won't be shown to the user anymore, but not deleted.

**Comment by whalley** [comment]
#3554 would be essential for this so that we can date the rollover balance for accounts at start of new year.

**Comment by TomAff** [comment]
Account can be blocked for previous years. 

According to the german law every posting has to be blocked. So I think it is not allowed to use the Software in an accounting department

**Comment by Dandy64** [comment]
> So I think it is not allowed to use the Software in an accounting department
As for as I understand this program intends for personal use only.

**Comment by vomikan** [comment]
> Account can be blocked for previous years.
> 
> According to the german law every posting has to be blocked. So I think it is not allowed to use the Software in an accounting department

You can lock any account for any date
![image](https://user-images.githubusercontent.com/6836805/152643255-2320ae5c-d47a-40f5-8e0e-802872d87889.png)

**Comment by Dandy64** [comment]
> You can lock any account for any date (but with some restrictions))
I suppose that **TomAff** means something else. The official accounting programs do not allow to make any changes after saving transactions.

**Comment by learingmmex** [comment]
i think the feature _"to add initial balance date to accounts"_ need to be prioritized

**Comment by whalley** [comment]
> i think the feature _"to add initial balance date to accounts"_ need to be prioritized

I'd like this also. I've tentatively allocated this (https://github.com/moneymanagerex/moneymanagerex/issues/3554) to v1.5.24, will look to get this implemented in next month or so (hopefully).

**Comment by vomikan** [comment]
> > i think the feature _"to add initial balance date to accounts"_ need to be prioritized
> 
> I'd like this also. I've tentatively allocated this (#3554) to v1.5.24, will look to get this implemented in next month or so (hopefully).

We have already discussed this and came to the conclusion that the date of the first transaction is the date of account initialization.

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: Discussion in the issue showed little appetite (or need) for providing this feature, which is more relevant to business style accounts.

**Comment by luisdev** [comment]
> CLOSE: wontfix
> 
> REASON: Discussion in the issue showed little appetite (or need) for providing this feature, which is more relevant to business style accounts.

I agree! I always want access to ALL my transactions (for reporting).

**Comment by whalley** [comment]
> > CLOSE: wontfix
> > REASON: Discussion in the issue showed little appetite (or need) for providing this feature, which is more relevant to business style accounts.
> 
> I agree! I always want access to ALL my transactions (for reporting).

Yes, same here. If the feature were ever implemented it would be optional.
