### ISSUE TITLE
About -> Community icon can be more readable

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1301]
I think there should be some space between foreground and background images. Compare:
![mmex-community-icon](https://user-images.githubusercontent.com/3155552/29485383-43d1400c-84d1-11e7-8ae1-d18e52bb5fdd.png)![mmex-community-icon-fixed](https://user-images.githubusercontent.com/3155552/29485385-4767b732-84d1-11e7-9580-ee07b7054970.png)

I added some white around heads to separate them from background...

**Comment by vomikan** [comment]
What about this one?
https://openclipart.org/detail/101989/population

**Comment by vomikan** [comment]
@slodki 
What about this one?
https://openclipart.org/detail/101989/population

**Comment by vomikan** [comment]
![community16](https://user-images.githubusercontent.com/6836805/31131801-dc260b02-a863-11e7-9477-1942b2afd1b5.png)
![community24](https://user-images.githubusercontent.com/6836805/31131803-dc3aef4a-a863-11e7-8c18-0f4cbc829b92.png)
![community32](https://user-images.githubusercontent.com/6836805/31131804-dc5c685a-a863-11e7-9a6e-d35bbe50cc8b.png)
![community48](https://user-images.githubusercontent.com/6836805/31131802-dc3a4022-a863-11e7-8fdf-b43a68d914e8.png)

**Comment by slodki** [comment]
Could we remove 3 leftmost?
2 blue are to similar,  orange one over red is also hard to distinguish. 5 should be enough.

**Comment by slodki** [comment]
Removing shadow can be an option

**Comment by slodki** [comment]
![population_new_16](https://user-images.githubusercontent.com/3155552/31203746-b30ad2b0-a968-11e7-8e18-77da860cde8b.png)
![population_new_32](https://user-images.githubusercontent.com/3155552/31203435-546fbafa-a967-11e7-8d84-4e62755ef62e.png)
![population_new_48](https://user-images.githubusercontent.com/3155552/31203437-592b3f92-a967-11e7-90d0-7d6507b00ca3.png)

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  width="64" height="64" viewBox="-3.5 -1 32 32">
  <symbol id="man" viewBox="-64 0 129 334" preserveAspectRatio="xMinYMin meet">
    <path d="m0 0c-18.382 0-33.288 14.992-33.288 33.487 0 14.385 9.0173 26.649 21.673 31.39v6.6022c-30.178 2.3566-43.372 14.386-45.267 35.786l-7.0436 79.557c7.3483 11.773 14.697 5.6024 22.045 0l7.0436-70.949c0.31698-3.193 1.4339-6.1765 3.8773-8.6168l-5.689 91.31c-0.19734 3.1674 1.2208 6.1246 3.3303 8.6193-0.36623 1.9668-0.4586 4.126-0.57348 6.3883l-5.0426 99.294c-0.53906 10.615 3.8669 19.191 8.6746 19.191h11.158c4.8077 0 8.5265-8.5612 8.6746-19.191l1.3669-98.097h17.487c0 0.004-0.00005 0.007 0 0.0107l1.2216 99.473c0.13054 10.63 3.8669 19.191 8.6746 19.191h11.158c4.8077 0 9.1973-8.5752 8.6746-19.191l-4.8974-99.473c-0.14763-2.9983-0.35415-5.808-0.97596-8.2384 1.791-2.3535 2.9972-5.0775 2.8172-7.9772l-5.6891-91.668c-0.048-0.77309-0.0881-1.5321-0.25396-2.271 4.4351 2.7564 6.7456 6.7943 7.2214 11.245l7.5854 70.949c9.3018 8.7842 15.756 6.7897 20.944 0l-7.5854-79.556c-2.0832-21.849-15.759-33.932-47.265-35.914v-5.9338c13.465-4.2903 23.222-16.963 23.222-31.931 0-18.495-14.898-33.487-33.279-33.487z" />
  </symbol>
  <g stroke-width="2" stroke="white">
    <use xlink:href="#man" x="5"  y="1"  height="18" fill="#0084c8"/>
    <use xlink:href="#man" x="13" y="0"  height="19" fill="#f60"/>
    <use xlink:href="#man" x="0"  y="8"  height="20" fill="#ff4141"/>
    <use xlink:href="#man" x="17" y="8"  height="20" fill="#10b000"/>
    <use xlink:href="#man" x="8"  y="10" height="20" fill="#555"/>
  </g>
</svg>
```

**Comment by vomikan** [comment]
![community](https://user-images.githubusercontent.com/6836805/31222015-498b4d0e-a9ce-11e7-95b8-2f754fbb6ab4.png)

![community24](https://user-images.githubusercontent.com/6836805/31222016-499ef7fa-a9ce-11e7-92c8-ef599958c88a.png)
![community32](https://user-images.githubusercontent.com/6836805/31222017-49a151bc-a9ce-11e7-9db6-1dd1e1faa654.png)
![community48](https://user-images.githubusercontent.com/6836805/31222018-49a3c104-a9ce-11e7-9f59-b3571534663f.png)

**Comment by vomikan** [comment]
![screenshot 561](https://user-images.githubusercontent.com/6836805/31223722-e1f6dcca-a9d3-11e7-98ec-8ad93cbbae9b.jpg)

**Comment by slodki** [comment]
We will add more people to this icon if our community grow in the future:
![i](https://us.123rf.com/450wm/kudryashka/kudryashka1502/kudryashka150200266/37038363-grupo-de-personas-boceto-de-su-dise-o.jpg?ver=6)

**Comment by vomikan** [comment]
:)
