### ISSUE TITLE
Wrong parsing of QIF data

### ISSUE THREAD

**Issue by Marc69009** [moneymanagerex/moneymanagerex#1304]
Your OS:
- [X] Windows

MMEX version:
- [X] 1.3.3

The QIF file (content copied and pasted below) contains MCHEQUE N° 8400780
After parsing in MMEX the note field is 

CHEQUE N

....the number is lost
Please note that this bug has been existing since early 0.9x versions

Original content of QIF file is as below

!type:Bank
D04/08/17
T-25.00
MCHEQUE N° 8400780
^

**Comment by vomikan** [comment]
Before import be sure if the file in UTF8 encoding.
