### ISSUE TITLE
WebApp import does not work on macos

### ISSUE THREAD

**Issue by andersonvom** [moneymanagerex/moneymanagerex#1305]
Clicking the menu option `File` - `Import` - `WebApp...` doesn't do anything.

Your OS:
- [ ] Windows
- [X] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.3 (DB v.7)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Do you have this service? Is any transactions registered by it?
https://github.com/moneymanagerex/web-money-manager-ex

**Comment by slodki** [comment]
@andersonvom If you have still this problem in 1.4.0-alpha.6 too please reopen this issue and add more details.
