### ISSUE TITLE
Compile errors with Visual Studio 2012

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1307]
MMEX current git master version cannot be compiled with MSVC version 17.0.61030.0. It reports multiple errors for `db` and `model` header files. Maybe specific feature of C++ compiler is required and not checked be CMake? Or we use different C++ standard then requested in CMake script?

Is it possible MMEX is incompatible with MSVC_VERSION<=1800?

Please see build log attached.

[log.zip](https://github.com/moneymanagerex/moneymanagerex/files/1254144/log.zip)

**Comment by slodki** [comment]
Some Microsoft doc to verify https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by vomikan** [comment]
Seems in general developers are using VS2017. I recommend to upgrade from 2012

**Comment by slodki** [comment]
[Variadic templates](https://en.wikipedia.org/wiki/Variadic_template) are supported since [VS 2013](https://devblogs.microsoft.com/cppblog/c1114-stl-features-fixes-and-breaking-changes-in-vs-2013) and are required for `db/Table*.h`.
