### ISSUE TITLE
monthy cash flow report

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/moneymanagerex#1310]
I use 1.4.0 alpha 2 release on windows 10.
The report seems to simulate only part of the 10 years (only for income ?)
Seem to simulate deposit only for 1 year ?.
On recurring transaction I entered some transactions with blank recurring times, like infinite.

Can someone check the report ?

Thanks

giorgio

<hr><small><b>Version</b>e: 1.4.0-Alpha.2 ⬥ db 7 ⬥ git 4d4d4d3 (2017-08-11)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 10.0) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Aug 10 2017 23:54:43 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 10 (build 14393), 64-bit edition Little endian ⬥ Italian windows-1252 ⬥ 1366x768x32bit 135x135ppi</small>

**Comment by vomikan** [comment]
@ggraziotti  could you provide a screenshot?
I can't reproduce it.

**Comment by ggraziotti** [comment]
Sorry. My mistake, on make report and report bug. Work fine.
