### ISSUE TITLE
How to delete extra reports that do not work

### ISSUE THREAD

**Issue by jesuswearspink** [moneymanagerex/moneymanagerex#1315]
Hello - I tried to add these new reports, none of which worked and I would like to delete them. But I can't not right click on them or make them go away. As you can see in the photo that I have uploaded, I am referring to the ones that are located after the forecast report

![screen shot 2017-09-06 at 2 30 33 pm](https://user-images.githubusercontent.com/31674016/30134071-31df9614-9313-11e7-9451-4ebc6d805c6d.png)

Mac OS
MMEX version: 1.3.3

**Comment by vomikan** [comment]
![screenshot 467](https://user-images.githubusercontent.com/6836805/30242766-39b521da-95a5-11e7-839a-bd13aaf37167.jpg)

**Comment by vomikan** [comment]
This feature already available for v 1.4.0
But I don't recommend you to upgrade before bugs #1219 #1273 would be fixed.

**Comment by omalleypat** [comment]
New build of v1.3.3 posted. [Click here for more info.](https://www.moneymanagerex.org/news/item/74-updated-mac-build-v1-3-3)

**Comment by slodki** [comment]
@jesuswearspink There should be no problem with alpha version 1.4.0 on Mac - you could try unstable Mac builds to use this new ability to hide selected reports.
