### ISSUE TITLE
MMEx 1.3.3 crashes after trying to open an existing database

### ISSUE THREAD

**Issue by Bruno1200** [moneymanagerex/moneymanagerex#1322]
I just upgraded to Version 1.3.3 and it keeps crashing every time I try to open my database. It is the second time it happens. Last time I just decided to move back to the previous edition I had downloaded to my computer. The error message is: Money Management Software has stopped working. What should I do?

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by Bruno1200** [comment]
I just upgraded to Version 1.3.3 and it keeps crashing every time I try to open my database. It is the second time it happens. Last time I just decided to move back to the previous edition I had downloaded to my computer. The error message is: Money Management Software has stopped working. What should I do?

**Comment by Bruno1200** [comment]
Just an update, version 1.2.7 x64 is the only one which opens my database .mmb

**Comment by stef145g** [comment]
Have you used your database using the Android version?
Your problem may be solved using the solution provided by #1250
Please try https://github.com/moneymanagerex/moneymanagerex/releases

**Comment by Bruno1200** [comment]
Sorry for the late reply Just tried to install and it worked!!! Thank you so much for your help!
Happy Thanksgiving!
