### ISSUE TITLE
'unexpected character in number token:' or silent crash when opening database in Release only

### ISSUE THREAD

**Issue by danielrempel** [moneymanagerex/moneymanagerex#1323]
Compiled a release from master branch, tried to open existing database, mmex shows dialog:
```
 'unexpected character in NUMBER token:'
```
without the description of the unexpected character.

When I click "open last opened database" MMEX silently crashes (same for `$ mmex testdb.mmb`)

Empty DB causes crash, too:
[db.zip](https://github.com/moneymanagerex/moneymanagerex/files/1304328/db.zip)

Also, when I built a debug version from the same source, it opened the database successfully and didn't say anything regarding the unexpected character in the terminal.

Environment:
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by danielrempel** [comment]
```
cajun:/home/daniel/MyProjects/moneymanagerex/3rd/cajun/json/reader.inl:554: Reader::Parse: did not consume the whole string: str='0
', current result: 0
```

I suppose the reason this error doesn't happen in debug build is related to the fact mmex complains about not having its internal files:
```
can't open file '/home/daniel/MyProjects/moneymanagerex/build-debug/src/share/mmex/res/home_page.htt' (error 2: No such file or directory)
```

**Comment by danielrempel** [comment]
Traced it to 
```
void mmPrintableBase::setSettings(const wxString& settings)
```

The interesting moment is that after I added several std::cout-s to this function mmex stopped crashing on `./src/mmex ../build/testdb.mmb`

**Comment by slodki** [comment]
See also #773 & #1175

**Comment by danielrempel** [comment]
Forgot to mention: I dumped the strings, mmex tried to parse with Reader::Parse(), it was the settings string from mmPrintableBase::setSettings(const wxString& settings); the failure happened on the last element, "CHART" (int) - cajun complained about '\n' in stream.
The function got executed something like 10 times from start of mmex prior to segfault and the first several executions (with the same `'CHART" : 0\n}`) didn't cause it to throw an exception. Maybe I didn't see the real difference between the strings?

BTW, did I miss something or setSettings really receives a string with json inside which has got a string with json inside? (i.e. `"{ "object1" : "{ "one" : 1, "two" : 2}" }"`)

I couldn't get cajun to fail in similair way on the dumped settings string (it didn't agree to parse it at all).

**Comment by vomikan** [comment]
This bug not 1.4.0 specific. Its json parser problen. It depend on network setting.If mmex cant receive news json data then this error appears. I have tried to fix it without success.

**Comment by danielrempel** [comment]
Maybe it's worth trying to change json parser?

**Comment by slodki** [comment]
We can store settings in text file using [wxFileConfig](http://docs.wxwidgets.org/3.0/classwx_file_config.html) without json conversion.

**Comment by slodki** [comment]
@danielrempel we have ticket #1207 for replacing cajun already - but no progress on this

**Comment by MartinX3** [comment]
Same problem here with v1.4.0-alpha.3 on Ubuntu 17.10 x64
Don't use network setting.
Can't open my database. :(

**Comment by MartinX3** [comment]
Sad to see, that I can't access my financial data anymore because of this bug.
Using Ubuntu Mate x64 17.10
1.4.x zesty give me this error
1.4.x xenial gives me a segfault
1.3.3 I can't find any debian package

**Comment by aligitor** [comment]
I experienced the very same issue for months, thus I couldn't use the software on computer (I tried on Fedora and Ubuntu as well, many times). Now I noticed that I don't need to compile myself: I added the MMEX repository on Ubuntu 16.04 (as described here: https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md#linux) and installed the app from there. Now I can open my existing database on Linux without problem!

**Comment by MartinX3** [comment]
@aligitor
Thank you for your help, but in already know this repo and I get the same error with there builds.
So I compiled on my own in the Past and it works.

_Sent from my Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vomikan** [comment]
May be I have fixed this.

**Comment by slodki** [comment]
@danielrempel @aligitor @MartinX3 Please test [fixed build](https://github.com/slodki/moneymanagerex/releases/tag/test2)

**Comment by MartinX3** [comment]
@slodki 
`mmex: error while loading shared libraries: libwx_gtk2u_unofficial_core-3.1.so.1: cannot open shared object file: No such file or directory`
