### ISSUE TITLE
Report names in tree view not updated when changed GUI language

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1324]
Report names in left panel are remembered when database is created and not updated/translated when program language changes:

![reports](https://user-images.githubusercontent.com/3155552/31048026-62132ff2-a615-11e7-94d6-4db60a89005e.png)

Translated names are displayed at right panel so translations are available and should be used.

*Transaction Raport* (the last one on the screenshot) works as expected - name is updated to current GUI language.

<br><small><b>Version</b>: 1.4.0-Alpha.3 ⬥ db 7 ⬥ git 79562d4 (2017-08-11)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 6.3) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Aug 11 2017 11:55:37 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 8.1 (build 9600), 64-bit edition ⬥ Polish windows-1250 ⬥ 1920x1080x32bit 127x127ppi</small>

**Comment by vomikan** [comment]
Да ладно!? Проверю.

**Comment by vomikan** [comment]
![screenshot 549](https://user-images.githubusercontent.com/6836805/31078998-dfb6d4ae-a78c-11e7-9a3c-f80fa4dba6f1.jpg)
It should work properly.

**Comment by slodki** [comment]
1. Install MMEX git master
2. Start MMEX and switch language to French.
3. Start MMEX and create new database
4. Report names in tree view are in **Polish** (current windows locale?) - **should be translated to French**
5. Report name on right panel is translated to french
6. Switch language to Russian
7. Start MMEX and load previous database
8. Report names in tree view are in **Polish** (current windows locale?) - **should be translated to Russian**
9. Report name on right panel is translated to Russian

**Comment by vomikan** [comment]
Seems reports structure is initiilizing before locale settings become. 
![screenshot 553](https://user-images.githubusercontent.com/6836805/31128258-ecfcfaee-a859-11e7-90fc-2e276a385d71.jpg)
![screenshot 552](https://user-images.githubusercontent.com/6836805/31128259-ed09d8e0-a859-11e7-9fea-ce6c4c60d2db.jpg)
