### ISSUE TITLE
Reconciled helper function

### ISSUE THREAD

**Issue by Flavien06** [moneymanagerex/moneymanagerex#1325]
Hello,
I would like to propose a reconciled assistance function.
I receive my bank statement with the initial and final balance.

The idea would be to enter the initial balance (or balance since the last reconciliation) and the final balance.

Then, the transactions to be reconciled "R" are cheked, and we see difference between the final balance, the initial balance and the reconciled transactions.

While arrive to 0 we are sure that the bank statement is godd reconciled.

______________________________________________________

Bonjour,
Je voudrais proposer une fonction d'assistance de réconciliation.
L'idée serait d'entrer le solde initial (ou solde depuis la dernière réconciliation) et le solde final.
Ensuite, on valide les opérations à réconcilier "R" et on voit la différence entre le solde final, le solde initial et les opérations réconciliées.
Arriver à 0 on est sur que le relever banquaire est bien réconcilier.

**Comment by whalley** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=10515

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: There are later discussions ongoing about how MMEX might help with reconciliation (for example https://github.com/moneymanagerex/moneymanagerex/discussions/5992) and helpful advice on the forum (for example https://forum.moneymanagerex.org/viewtopic.php?p=24077#p24077)
