### ISSUE TITLE
Untranslated report headers

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1327]
Report period drop-down selector uses translated values, but report header below uses untranslated English strings:
![raport header](https://user-images.githubusercontent.com/3155552/31054879-1abf1cf4-a6bc-11e7-8c96-28fa54299dca.png)

We should use translated strings in both places.

<br><small><b>Version</b>: 1.4.0-Alpha.3 ⬥ db 7 ⬥ git 79562d4 (2017-08-11)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 6.3) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Aug 11 2017 11:55:37 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 8.1 (build 9600), 64-bit edition ⬥ Polish windows-1250 ⬥ 1920x1080x32bit 127x127ppi</small>

**Comment by vomikan** [comment]
I'll fix in #1328
