### ISSUE TITLE
MMEX not supported by next Debian/openSUSE release in 2019

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1331]
Debian [dropped libwebkitgtk-1.0 and libwxgtk-webview3.0 support](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790222) for buster (planned for 2019).

Ubuntu [dropped libwxgtk-webview3.0 support](https://launchpad.net/ubuntu/+source/wxwidgets3.0/3.0.3.1+dfsg2-1) for artful **planned for 2017-10-19**. I've created [upstream bug report](https://bugs.launchpad.net/ubuntu/+source/wxwidgets3.0/+bug/1720953) for this.

There will be no easy way to install MMEX into latest Ubuntu release in 2 weeks!

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libwxgtk-webview3.0-dev : Depends: wx3.0-headers (= 3.0.3.1+dfsg-1) but 3.0.3.1+dfsg2-1 is to be installed
                           Depends: libwxgtk3.0-dev (= 3.0.3.1+dfsg-1) but 3.0.3.1+dfsg2-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by slodki** [comment]
Some info about wxgtk switching to WebKit2GTK+: http://trac.wxwidgets.org/ticket/17650

**Comment by slodki** [comment]
Debian Buster and Ubuntu Artful: `Unable to locate package libwxgtk-webview3.0-dev`

**Comment by slodki** [comment]
openSUSE Tumbleweed: nothing provides webkitgtk-3.0

**Comment by emagra** [comment]
up??
some usefull link

https://forum.moneymanagerex.org/viewtopic.php?f=25&t=7275

But opening my mmb error occurs
"Unexpected character in NUMBER token: "

News on official resolutions?

**Comment by mayou36** [comment]
Any news on this so far?

**Comment by slodki** [comment]
We can use https://repos.codelite.org/wx3.1.1/

**Comment by swt2c** [comment]
BTW, wxWebView will be back in Ubuntu Bionic, but you will have to build against the GTK+3 version of the package.

**Comment by MartinX3** [comment]
Missing sqlite3secure.h under Ubuntu 18.04 with https://repos.codelite.org/wx3.1.1/ enabled

**Comment by slodki** [comment]
@MartinX3 We use latest wxsqlite3 version compiled from sources. Ubuntu/Debian wxsqlite3 packages are build without cipher support and MMEX linked with them has no cipher support (cannot open/create encrypted db).

**Comment by MartinX3** [comment]
@slodki How to build it then?
I need to build it myself, because I don't find your latest test build. (Upgrade to 18.04 removed MMEX)
Or can you provide the travis-ci artifacts?
It would be nice if you use your CI to provide builds. :)

**Comment by slodki** [comment]
Uninstalling wxsqlite3 system package should be enough - MMEX CMake build script will use their own sources to build it.

**Comment by MartinX3** [comment]
THX, that's the final solution. :)

**Comment by slodki** [comment]
Try our new repo:
```
echo deb https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu/ bionic main > /etc/apt/sources.list.d/mmex.list
wget -O /etc/apt/trusted.gpg.d/mmex.pub.asc https://packagecloud.io/moneymanagerex/moneymanagerex/gpgkey
apt update
apt install mmex
```

```
> apt show mmex

Package: mmex
Version: 1.4.0~alpha4-0ubuntu1~bionic
Priority: extra
Section: misc
Maintainer: MoneyManagerEx Developers <developers@moneymanagerex.org>
Installed-Size: 14,7 MB
Depends: wx3.0-i18n:all, libc6 (>= 2.15), libcurl4 (>= 7.16.2), libgcc1 (>= 1:3.0), liblua5.3-0, libstdc++6 (>= 5.2), libwxbase3.0-0v5 (>= 3.0.4+dfsg), libwxgtk-webview3.0-gtk3-0v5 (>= 3.0.4+dfsg), libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg)
Replaces: moneymanagerex
Homepage: http://www.moneymanagerex.org/
Download-Size: 6 449 kB
APT-Sources: https://packagecloud.io/moneymanagerex/moneymanagerex/ubuntu bionic/main amd64 Packages
Description: Simple to use financial management software
```

**Comment by MartinX3** [comment]
Thx very much.
And you should update the "xenial readme".

Will you give us new alpha builds on a weekly or monthly base?

**Comment by slodki** [comment]
@MartinX3 See #1614

**Comment by MartinX3** [comment]
@slodki You are amazing!

**Comment by MartinX3** [comment]
Fresh installed Linux Mint 19 Mate x64
Can't install MMEX from repository or the nightly build.
I already added :i386 as architecture.

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mmex : Hängt ab von: wx3.0-i18n:all ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by infidelus** [comment]
Can't install from the repo mentioned above on Linux Mint 19.

The following packages have unmet dependencies.
 mmex : Depends: wx3.0-i18n:all but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by swt2c** [comment]
@slodki why do you have all architecture specified in the Depends: for wx3.0-i18n.  Depends: wx3.0-i18n should be fine.

**Comment by slodki** [comment]
wx3..0-i18n package in Ubuntu repos is tagged with all arch. CPack creates dependency to wx3.0-i18n:386 while building mmex:386 without it. Yes, this is workaround but it's working.

**Comment by MartinX3** [comment]
Can you change wx3.0-i18n:all to wx3.0-i18n:amd64 ?

**Comment by slodki** [comment]
apt reports something like "wx...:386 not available" when mmex:386 has wx3.0-i18n:386 as dependency

**Comment by MartinX3** [comment]
wx3.0-i18n:i386 doesn't exist on Ubuntu 18.04
So mmex isn't installable.
You need to change the dependency to wx3.0-i18n:amd64 or remove the dependency.
Or mmex need to be an entire x64 application.

**Comment by slodki** [comment]
MMEX installs on both [x64](https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/398942230#L901) and [i386](https://travis-ci.org/moneymanagerex/moneymanagerex/jobs/398942243#L903) Ubuntu 18.04 with current CPack config.

**Comment by slodki** [comment]
We don't use TravisCI OS but docker images for all linux distributions. Above logs are from bionic docker machines. I'll add cosmic packages soon.

@MartinX3  Are you sure wx3.0-i18n package for amd64 architecutre exists at all? I can find only [wx3.0-i18n_3.0.4+dfsg-3_all.deb](https://packages.ubuntu.com/bionic/wx3.0-i18n) package.

**Comment by MartinX3** [comment]
@slodki 
There is only the "all" package.
But since I switched from 16.04 to 18.04 I've got this problem, which makes mmex uninstallable OR breaks my system, if I don't manipulate the dependency. :(

**Comment by slodki** [comment]
@infidelus is not using Ubuntu but Mint

@MartinX3 I cannot reproduce your problem - see Travis logs above. Can you check you have https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887378 installed (this should use [Multi-Arch](https://wiki.debian.org/Multiarch/HOWTO))?

**Comment by swt2c** [comment]
> @MartinX3 Are you sure wx3.0-i18n package for amd64 architecutre exists at all? I can find only wx3.0-i18n_3.0.4+dfsg-3_all.deb package.

That's the heart of the problem here.  wx3.0-i18n is now an architecture independent package (arch all).  The real solution here is to remove the architecture from your Depends for wx3.0-i18n.

**Comment by slodki** [comment]
libwxgtk-webview3.0 updated with libwxgtk-webview3.0-gtk3 in Debian Buster and Ubuntu Bionic/Cosmic. No libwxgtk-webview3.0 package in Ubuntu Artful repos - we use libwxgtk-webview3.1 package distributed by CodeLite.

**Comment by MartinX3** [comment]
I installed the new tara nightly from 12 hours ago.
Still same error which breaks my system

```bash
$ sudo apt autoremove 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt --fix-broken install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mmex : Hängt ab von: wx3.0-i18n:all ist aber nicht installierbar
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt --fix-broken install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
```

**Comment by slodki** [comment]
@MartinX3 It's problem with your OS. Our packages install without problems in Linux Mint 18/19 and Ubuntu distributions. See [logs from installation](https://travis-ci.com/slodki/mmex-mint-tests/builds/79020328).
I'll remove Mint packages as Ubuntu versions install without problems.

Please open separate issue if you have problem with mmex - this one is about missing libwxgtk-webview library and it's fixed already.

**Comment by slodki** [comment]
Please also verify #1612 if using latest Ubuntu/Debian distro.

**Comment by MartinX3** [comment]
@slodki 
You mentioned in #1612 that I need to rebuild mmex from sources.
Do I need to download the nightly and compile mmex on myself, to use wxwidgets 3.1.1 from this repo ?
Or will it be integrated in the latest nightly?

**Comment by slodki** [comment]
We use CodeLite repo only to build Ubuntu Artful packages. You must rebuild MMEX to use your own version of wxw different then from your distribution.

**Comment by MartinX3** [comment]
Then I better should ignore #1612 if I need to do this by hand. :)
