### ISSUE TITLE
View -> Swith Application language icon

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1336]
Your OS:
- [x] Windows
- [x] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by vomikan** [comment]
![language24](https://user-images.githubusercontent.com/6836805/31269559-aa9e38a2-aa89-11e7-89fb-f2969ae42350.png)
![language32](https://user-images.githubusercontent.com/6836805/31269560-aac4f4f6-aa89-11e7-8741-00e4e11c7754.png)
![language48](https://user-images.githubusercontent.com/6836805/31269562-aaeeb80e-aa89-11e7-9160-1e04bdf36d6b.png)
![language](https://user-images.githubusercontent.com/6836805/31269561-aae26298-aa89-11e7-858c-5618fe4e6e6c.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/1335

**Comment by vomikan** [comment]
![language16](https://user-images.githubusercontent.com/6836805/31268193-dd49d62c-aa83-11e7-88eb-8e7ad5676cba.png)
![language24](https://user-images.githubusercontent.com/6836805/31268196-dd6023be-aa83-11e7-93cb-e0811bdb4ad4.png)
![language32](https://user-images.githubusercontent.com/6836805/31268195-dd5b2bca-aa83-11e7-9a0c-ea95064da714.png)
![language48](https://user-images.githubusercontent.com/6836805/31268194-dd5a8e22-aa83-11e7-9674-31670ead401f.png)

**Comment by vomikan** [comment]
@slodki there are two sets of icons. Whitch one would you prefer?

**Comment by slodki** [comment]
![https://commons.wikimedia.org/wiki/File:Antu_amarok_change_language.svg](https://commons.wikimedia.org/wiki/File:Antu_amarok_change_language.svg)

**Comment by vomikan** [comment]
I think it's not acceptable
![lang16](https://user-images.githubusercontent.com/6836805/31276302-d9217cd8-aaa3-11e7-93b0-73d2621b546a.png)

**Comment by slodki** [comment]
![lang_ico2](https://user-images.githubusercontent.com/3155552/31286719-5d6d1f22-aabf-11e7-8a07-8f3cd81c8926.png)

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="128">
  <g stroke="green" fill="green" stroke-width="3" stroke-linejoin="round">
    <ellipse cx="24" cy="22" rx="23" ry="20" stroke="none"/>
    <path d="m3 45l14 -5l-9 -5z" stroke="redt"/>
  </g>
  <text x="4" y="29" fill="white"
    style="font-size:22px;font-family:Arial,Helvetica;font-weight:bold">
    ㄆA
  </text>
</svg>
```
