### ISSUE TITLE
Database made out of v1.4.0 Alpha3 - Values lose assignment

### ISSUE THREAD

**Issue by mouzzza** [moneymanagerex/moneymanagerex#1337]
Your OS:
- [x] Windows 10

MMEX version:
- [x] 1.4.0 Alpha 3 portable

Hi,
I use MMEX on Windows and Android.
On Windows I use v1.4.0Alpha3. On Android I use both versions, stable and beta.

The Problem:
Yesterday I've done some Transactions on Windows. In the afternoon I wanted to add some more on Android but I saw that the account-groups have lost the assignment to the accounts.

Sry for poor Explanation, but see on the Pics.

OK
![correct assignment](https://user-images.githubusercontent.com/20276767/31275546-fae89e5c-aa97-11e7-8561-8de80a7b6334.png)

Wrong
![wrong assignment](https://user-images.githubusercontent.com/20276767/31275549-fce8fc56-aa97-11e7-93f2-b61089ec0300.png)

**Comment by slodki** [comment]
The problem is visible in Android version and desktop version shows right values?

**Comment by mouzzza** [comment]
@slodki
The problem is visible in both Android versions and in Windows Stable release  v1.3.3

Only Win v1.4 Alpha is showing me the correct numbers!!

I think the Alpha has written an error to the database. Alpha itself can read it correct, the others don't.

**Comment by slodki** [comment]
When you upgrade MMEX version the database file structure can also be upgraded so it's not recommended to open it with older version after upgrade.

Your problem with desktop version is 1.3.3 incorrectly displays values from 1.4.0 version without any warning about incompatible version used?

**Comment by mouzzza** [comment]
@slodki
My problem is that I'm now able to work with v1.4 Alpha only.

I am working with Alpha and Android versions​ for a longer time now.
But the problem exists (I guess there aren't any differences in database) since i've deleted some transactions on Alpha.

**Comment by mouzzza** [comment]
Had to mark as reconciled again some Transactions.

**Comment by stef145g** [comment]
Quote by @mouzzza 
>Had to mark as reconciled again some Transactions

This may be due to #1180
