### ISSUE TITLE
Can't open a loan account on Android app

### ISSUE THREAD

**Issue by Lorraine911** [moneymanagerex/moneymanagerex#1339]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [X] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
Please open this issue on [**android**-money-manager-ex](https://github.com/moneymanagerex/android-money-manager-ex/issues) repo.
