### ISSUE TITLE
Placeholder description in rpm

### ISSUE THREAD

**Issue by lonemadmax** [moneymanagerex/moneymanagerex#1340]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

When building an rpm, the description of the package is the content of `/usr/share/cmake/Templates/CPack.GenericDescription.txt`, instead of the nice specific one defined for `CPACK_PACKAGE_DESCRIPTION`.

From https://cmake.org/cmake/help/latest/module/CPackRPM.html#variable:CPACK_RPM_PACKAGE_DESCRIPTION, it seems the correct name is `CPACK_RPM_PACKAGE_DESCRIPTION` (at least for rpm, I don't know cmake to say `CPACK_PACKAGE_DESCRIPTION` is wrong), or that the description can be in a file and `CPACK_PACKAGE_DESCRIPTION_FILE` should point to it.

**Comment by slodki** [comment]
You are right - this one variable [is not copied from CPACK_PACKAGE_* variables](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CPackRPM.cmake#L1849).
