### ISSUE TITLE
File conflicts in rpm for Fedora

### ISSUE THREAD

**Issue by lonemadmax** [moneymanagerex/moneymanagerex#1341]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

The generated rpm pretends to own (or something) same shared directories that at least in Fedora 26 conflict with packages filesystem, hicolor-icon-theme and fedora-logos.

Works for me by adding the following line to a new `CPackProperties.cmake` file, but I don't know enough of cmake and rpm to know whether that's The Right Thing:
`SET(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION /usr/share/applications /usr/share/icons /usr/share/icons/hicolor /usr/share/icons/hicolor/scalable /usr/share/icons/hicolor/scalable/apps)`

**Comment by slodki** [comment]
I don't use rpm distribution - thanks for your support.
Default [CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST](https://cmake.org/cmake/help/latest/module/CPackRPM.html#variable:CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST) list is really short...

**Comment by lonemadmax** [comment]
Well, I don't use other distributions and don't really know rpm. This might be a Fedora-only issue and adding those paths to the exclude list may break other systems. Maybe we should wait for someone else to pop in and comment.

**Comment by slodki** [comment]
@lonemadmax This should be avoided in packages. Packages should not change permissions, owners etc. attributes of important system folders they not own.

Could you check if [fixed packages](https://github.com/slodki/moneymanagerex/releases/tag/test-rpm) are OK now?

**Comment by lonemadmax** [comment]
I confirm the fc26 rpm in that link installs without conflicts or any kind of error or warning. It also has a description, the program runs, and the package uninstalls cleanly.
