### ISSUE TITLE
Include required wxMac library into Mac binary package

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1342]
It could be hard for end-user to manually install wxWidgets binaries on Mac (using brew) required to run MMEX.

We should statically link this library with MMEX for Mac or include shared libraries copy into distributed Mac package.

**Comment by slodki** [comment]
@omalleypat Could you test [new Mac binaries](https://github.com/slodki/moneymanagerex/releases/tag/test-mac-static5) with wxMac included (statically linked)?

**Comment by omalleypat** [comment]
@slodki - tested the 10.13 release, crashes on launch with 
`Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib`

**Comment by slodki** [comment]
[wxMac formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb) is used to build static version of wxmac.

libjpeg/libpng/libtiff should be statically linked into wxMac library. brew formula [uses dynamic versions](https://travis-ci.org/slodki/moneymanagerex/jobs/287432501#L2387) (.dylib) even if static versions (.a) exists.

**Comment by slodki** [comment]
While static linking MMEX with libpng it gives following error on OSX>10.11:
```
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Preinstalled zlib cannot be linked with libpng even if libpng is compiled locally... I'll try to recompile zlib.

**Comment by slodki** [comment]
wxMac brew bottle contains dynamic version only. To link statically MMEX wxMac must be installed with `--with-static` option (this trigger compiling from sources) then linked with static brew versions of libpng/libtiff/libjpeg/zlib.

Mac binary Drag'n'Drop packages will be 50% bigger and include all required wxWidgets libraries. Build time on Travis takes about 35 minutes.

Cmake script on Mac will try to use static wxMac version if available then fallback to dynamic one.

@omalleypat Could you verify [latest Mac binaries](https://github.com/slodki/moneymanagerex/releases/tag/test-mac-static2)?

**Comment by omalleypat** [comment]
Tested 10.13 build - confirmed working. Thanks for your effort!

**Comment by slodki** [comment]
@omalleypat Could you test if we can use the "oldest" Mac binary (=10.10) on newer OSX versions?
Then we can build and distribute one package compatible with all OSX versions.

Binary packages differences:
- OSX version used on build machine (this shouldn't impact on package compatibility)
- brew installed libraries (this shouldn't impact on package compatibility as we do static linking now)
- Xcode version used to compile (*"You should install and use the cross-development SDK for that version of OS X"*)
- mmacosx-version-min compile parameter (*"You must target your compile for the oldest version of OS X on which you want to run the executable"*)

`mmex-1.4.0.alpha3-osx10.10.dmg` package should be usabe on all OSX  >=10.10 IMHO

**Comment by omalleypat** [comment]
I have confirmed that the 10.10 package works on 10.13.

**Comment by slodki** [comment]
thx
