### ISSUE TITLE
Outdated translation instructions for the users

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1345]
I wonder what is the right flow for updating MMEX translation for end-users:
- [x] ~~GitHub po/README.md~~ & [SourceForge wiki](https://sourceforge.net/p/moneymanagerex/wiki/Translation/)
   > Post your translated .po file on the forum or Email it to zealsupport mailing list
- [x] Forum / Translations / [Translation Readme](https://forum.moneymanagerex.org/viewtopic.php?f=6&t=129)
   > Once you have a translation, please post in the forum, creating a new forum post with the language the translation is
- [x] Forum / Translations / [How to manage translation](https://forum.moneymanagerex.org/viewtopic.php?f=6&t=8013) (sticky!)
   > Could you join us https://poeditor.com
- [ ] website points to [Launchpad Translations](https://translations.launchpad.net/mmex)
- [x] users can create Github PRs or issues with updated translations directly
- [x] https://www.transifex.com/mmex
- [ ] https://translations.launchpad.net/mmex
- [x] https://github.com/moneymanagerex/moneymanagerex/wiki/Translation

Forum and SF points user to 1.2.x .po files!

**Comment by slodki** [comment]
**Proposal:**
Replace [Launchpad Translations](https://translations.launchpad.net/mmex) with GitHub App like [Crowdin](https://github.com/marketplace/crowdin). This will allow users to generate a pull request to MMEX repository automatically. See also #1623 too.

Then all documentation should be updated of course.

We must update translations for 1.4.0 release!

**Comment by slodki** [comment]
1. Is Transifex mentioned somewhere in doc/website?
2. Is it in sync with MMEX sources repo (webhook in git repo)?
3. Can users create PRs directly to GitHub MMEX repo?
4. Is it possible to manage multiple branches (like 1.2.x, 1.3.x, 1.4.x) in parallel?
5. Can it display sourcecode context next to translated string as wxWidgets macros don't support translation context param?

I think above points are important to manage translation workflow easily.

**Comment by slodki** [comment]
Problems from first post are still not fixed

**Comment by vomikan** [comment]
> users can create Github PRs or issues with updated translations directly

Automatically.

**Comment by vomikan** [comment]
> I am envolved some people into https://www.transifex.com/mmex

I've deleted this project
