### ISSUE TITLE
Consolidate README.md and README.TXT

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1349]
[README.md](/moneymanagerex/moneymanagerex/blob/master/README.md) and [README.TXT](/moneymanagerex/moneymanagerex/blob/master/README.TXT) are very similar but different and should be consolidated into one file.

**Comment by ovari** [comment]
Where is [README.TXT](https://github.com/moneymanagerex/moneymanagerex/blob/master/README.TXT) used?

Can README.TXT be deleted?

**Comment by vomikan** [comment]
> Where is [README.TXT](https://github.com/moneymanagerex/moneymanagerex/blob/master/README.TXT) used?
> 
> Can README.TXT be deleted?

I was sure that this file is used in the About dialog. But in place of the application description, there is information about the components.

At the moment there is only a link to the file, but it is not used.

**Comment by vomikan** [comment]
let's think again. This file is located in the archive of the portable build, as well as after installation.
This is a good practice. Is it really worth deleting this file? It is static and you can not change it for 100 years.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/0fd4e7dc-f530-4187-9c2d-03a62bfc6c70)

**Comment by tactilis** [comment]
The Supported Platforms information in README.TXT is significantly out of date compared to the up to date information here  https://moneymanagerex.org/docs/downloads/compatibility/

For example on Windows: 95, 98, ME, 2000, NT, XP are not supported platforms. Not that anyone is likely to be running these now.

**Comment by vomikan** [comment]
> Windows: 95, 98, ME, 2000, NT, XP are not supported platforms

Money Manager Ex is a free, open-source, cross-platform, easy-to-use personal 
finance software. It primarily helps organize one's finances and keeps track 
of where, when and how the money goes.

MMEX includes all the basic features that 90% of users would want to see in a
personal finance application. The design goals are to concentrate on simplicity
and user-friendliness - something one can use everyday.


Let's leave only the description.
