### ISSUE TITLE
Provide 'due date' for every transaction

### ISSUE THREAD

**Issue by rrremedio** [moneymanagerex/moneymanagerex#1354]
It would be easier to enter the occurrence date and its due date, as long I cannot import recurrent transactions. Besides it would be easy forecast each account cash-flow.

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by whalley** [comment]
@rrremedio I know this was raised a long time ago......   Can you elaborate on what the requirement is here?

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: The OP gave little information about the requested feature and did not respond in 2022 when asked for more details about their requirement.
