### ISSUE TITLE
The transaction dialog shows date in MM/DD/YYYY format whatever the locale

### ISSUE THREAD

**Issue by lonemadmax** [moneymanagerex/moneymanagerex#1358]
The input widgets for dates (transaction dialog, recurring transactions, etc) show dates in MM/DD/YYYY format, despite the locale indicating a different one and the format chosen in preferences being also different. Calendar widgets are in English and start the week on sundays, again not in accordance with the locale.

The dates in transactions lists and reports correctly use the format from the preferences.

My locale:

```
$ locale
LANG=es_ES.utf8
LC_CTYPE="es_ES.utf8"
LC_NUMERIC="es_ES.utf8"
LC_TIME="es_ES.utf8"
LC_COLLATE="es_ES.utf8"
LC_MONETARY="es_ES.utf8"
LC_MESSAGES="es_ES.utf8"
LC_PAPER="es_ES.utf8"
LC_NAME="es_ES.utf8"
LC_ADDRESS="es_ES.utf8"
LC_TELEPHONE="es_ES.utf8"
LC_MEASUREMENT="es_ES.utf8"
LC_IDENTIFICATION="es_ES.utf8"
LC_ALL=
$ locale -k LC_TIME
abday="dom;lun;mar;mié;jue;vie;sáb"
day="domingo;lunes;martes;miércoles;jueves;viernes;sábado"
abmon="ene;feb;mar;abr;may;jun;jul;ago;sep;oct;nov;dic"
mon="enero;febrero;marzo;abril;mayo;junio;julio;agosto;septiembre;octubre;noviembre;diciembre"
am_pm=";"
d_t_fmt="%a %d %b %Y %T %Z"
d_fmt="%d/%m/%y"
t_fmt="%T"
t_fmt_ampm=""
era=
era_year=""
era_d_fmt=""
alt_digits=
era_d_t_fmt=""
era_t_fmt=""
time-era-num-entries=0
time-era-entries="d"
week-ndays=7
week-1stday=19971130
week-1stweek=4
first_weekday=2
first_workday=2
cal_direction=1
timezone=""
date_fmt="%a %b %e %H:%M:%S %Z %Y"
time-codeset="UTF-8"
```

Defining LC_ALL or LANG doesn't make a difference. Changing to another language does change the interface (when set to use system locale) but doesn't change the format in the date and calendar widgets.

<hr><p><b>Version</b>: 1.4.0-Alpha.3 ⬥ db 7 ⬥ git d0f05a17 (2017-10-19) master</p>
<p><b>Libs</b>: wxWidgets 3.0.3 (wxGTK 3.22) ⬥ wxSQLite3 3.4.1 (SQLite 3.20.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4</p>
<p><b>Build</b>: Oct 21 2017 12:03:12 ⬥ CMake 3.9.1 ⬥ GNU Make 4.2.1 ⬥ gettext 0.19.8.1 ⬥ GCC 7.2.1 20170915 (Red Hat 7.2.1-2) ⬥ Fedora 26 'TwentySix'</p>
<p><b>OS</b>: Fedora release 26 (Twenty Six) "TwentySix" ⬥ Linux 4.13.5-200.fc26.x86_64 x86_64 ⬥ Spanish (UTF-8) ⬥ 1366x768x24bit 96x96ppi</p>

**Comment by slodki** [comment]
MMEX ignores locale (aka system settings) now. See #1150 for number formatting problems.

**Comment by slodki** [comment]
For start of the week see #1105

**Comment by vomikan** [comment]
possible related issue #1456

**Comment by vomikan** [comment]
#2290
