### ISSUE TITLE
Upgrade from 1.2.7 to higher version is not working

### ISSUE THREAD

**Issue by rohamkocka** [moneymanagerex/moneymanagerex#1361]
Your OS:
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [X] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

Hello,
I use my MoneyManager on both of Windows 10 and Android -- they work fine. But I cannot upgrade my Windows client higher than 1.2.7, because I will get only an error message and my instance will have been collapsed. I attached the dump files.
Thank you.
[bin.zip](https://github.com/moneymanagerex/moneymanagerex/files/1406031/bin.zip)
[WER703B.tmp.txt](https://github.com/moneymanagerex/moneymanagerex/files/1406032/WER703B.tmp.txt)

**Comment by stef145g** [comment]
Please refer to #1248, #1250, #1231

A problem has been identified that upgrading v1.2.x to v1.3.x when the database has been used on an Android device causes v1.3.x not to upgrade properly using Windows. The version v1.4.0-alpha.3 has provided a fix which correct this incompatibility. Issues #1248 and #1250 provide info on how to check database manually.
