### ISSUE TITLE
Adding transaction has a noticeable lag

### ISSUE THREAD

**Issue by mikinw** [moneymanagerex/moneymanagerex#1363]
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.
There is no such option in my app.

Even using a new database, when I add a new transaction, there is a noticeable lag between pressing the OK button and the dialog to disappear.

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.3
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Please try to delete mmexini.db3 file then restart mmex.

**Comment by mikinw** [comment]
It solves the problem, thanks.
