### ISSUE TITLE
Crashes after download

### ISSUE THREAD

**Issue by palibby** [moneymanagerex/moneymanagerex#1364]
I have used MMEX for 2 years.  Yesterday it said that there was an error and I needed to eject the disk image.  I've tried re downloading, but it crashes before it can open.  I have 2 years of data saved to a thumb drive that I cant access.  Thank you for any help you can give me.

Your OS:
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
Please reopen if it's not working in 1.4.0-alpha.4.
