### ISSUE TITLE
Font size in Account View too small

### ISSUE THREAD

**Issue by frjoeanddelphy** [moneymanagerex/moneymanagerex#1365]
Your OS:
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Screenshot please.
What is the screen resolution?

**Comment by frjoeanddelphy** [comment]
Thanks for the response! The screen resolution is 1920x1080. I am using an iMac with OS X 10.12.6. This is a screen shot box the Account view:

**Comment by vomikan** [comment]
@frjoeanddelphy ???

**Comment by frjoeanddelphy** [comment]
Thanks! I lowered the screen resolution, and now everything is fine.
