### ISSUE TITLE
Crash whenever you close MMEX 1.4.0 Alpha 3

### ISSUE THREAD

**Issue by keinejiang** [moneymanagerex/moneymanagerex#1366]
Crash whenever you close MMEX 1.4.0 Alpha 3. Attached the debug report.

My OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

[MoneyManagerEx_dbgrpt-796-20171103T152449.zip](https://github.com/moneymanagerex/moneymanagerex/files/1439959/MoneyManagerEx_dbgrpt-796-20171103T152449.zip)

**Comment by vomikan** [comment]
Потоком была предпринята попытка прочитать или записать данные на виртуальный адрес, к которому он не имеет соответствующего доступа

**Comment by vomikan** [comment]
Could you try to disable backup option on exit.

**Comment by vomikan** [comment]
![default](https://user-images.githubusercontent.com/6836805/35734370-fab8f90c-0831-11e8-96a2-054af8b8c270.PNG)

**Comment by slodki** [comment]
There is no bug in MMEX code really? App shouldn't crash even with option selected or not...
