### ISSUE TITLE
Advanced payee search

### ISSUE THREAD

**Issue by FerdinandoLM** [moneymanagerex/moneymanagerex#1368]
Is it possible to add an andvanced payee search method, in order to search for word in the middle of the payee string? On android version of money manager ex this is already doable, why not port this into windows build? 

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Just use the '*' placeholder
![screenshot 604](https://user-images.githubusercontent.com/6836805/32539248-dd189606-c479-11e7-9110-c79f41d78b93.jpg)
![screenshot 603](https://user-images.githubusercontent.com/6836805/32539249-dd37418c-c479-11e7-8c76-9ad356f1e815.jpg)

**Comment by slodki** [comment]
But [manual](http://desktop.moneymanagerex.org/#section9) says:

> Use the % as a wild-card to match many characters                     in the filter.
> Use _ to match a single character in the filter.

This is not working. See also #1298

**Comment by slodki** [comment]
It [uses](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/model/Model_Payee.cpp#L58) only [* and ? chars](http://docs.wxwidgets.org/3.1/classwx_string.html#a0fef65e3bf7f77fa6858521f29a84e20).

**Comment by vomikan** [comment]
? works as well
![screenshot 610](https://user-images.githubusercontent.com/6836805/32592971-10e0eeb2-c537-11e7-944e-ab30a5d0f5ce.jpg)

**Comment by slodki** [comment]
The doc is still wrong and should be fixed

**Comment by slodki** [comment]
manual fixed
