### ISSUE TITLE
add support for Bitcoin Cash & Ethereum

### ISSUE THREAD

**Issue by DLSS604** [moneymanagerex/moneymanagerex#1369]
I would appreciate it if someone could add support for Bitcoin Cash & Ethereum so i can manage these aswell.

**Comment by slodki** [comment]
Bitcoin [is added](https://github.com/moneymanagerex/database/commit/a170cca1f171ec1cfaacc6d0a5854873bb4295b0#diff-b902d2912b8eb59251e7eed1dea0c1b8R318) in 1.4.x already.

**Comment by DLSS604** [comment]
i know, 
and i've been using it, however bitcoin (BTC) is pretty much unusable for small transactions due to the high fees & slow confirmation times (also why it's crashing now as it can't cope)

Bitcoin Cash (BCH) forked from BTC on august 1st and before segwit & RBF (replace by fee) were implemented, making 0conf transactions secure. Staying true to the nakamoto whitepaper aswell as implementing a much needed blocksize increase causing fees to remain low & transactions to be much faster (as the mempool gets cleared a lot faster) and the developement team is a lot better currently working on some huge improvements that are long past due. (and with massive industry & miner support)

**Comment by ajthemacboy** [comment]
I would like this too. Ethereum is on Yahoo Finance, is there any way to add it as a custom currency with conversion to USD?

**Comment by vomikan** [comment]
https://github.com/CoinCapDev/CoinCap.io

**Comment by vomikan** [comment]
```
{
  "altCap": 285453826587.58673,
  "bitnodesCount": 11346,
  "btcCap": 182584580883.59998,
  "btcPrice": 10572.582691032363,
  "dom": 69.98,
  "totalCap": 468038407471.1865,
  "volumeAlt": 1053532307.8669212,
  "volumeBtc": 2455864612.219064,
  "volumeTotal": 3509396920.085986,
  "id": "ETC",
  "type": "cmc",
  "_id": "af8e196a-19af-4763-afbd-cb134882d67c",
  "price_btc": 0.003296180689989057,
  "price_eth": 0.04081044713180649,
  "price_usd": 34.62475171096191,
  "price_ltc": 0.1664756506715852,
  "price_zec": 0.0805600756352672,
  "price_eur": 28.053,
  "market_cap": 3463114240.1385202,
  "cap24hrChange": -11.38,
  "display_name": "Ethereum Classic",
  "status": "available",
  "supply": 100018457,
  "volume": 943431000,
  "price": 36.9217,
  "vwap_h24": 37.12393031245106,
  "rank": 14,
  "alt_name": "ethereum-classic"
}
```
