### ISSUE TITLE
Option to import stock quotes from a CSV file

### ISSUE THREAD

**Issue by wbwiltshire** [moneymanagerex/moneymanagerex#1370]
Since the Yahoo Quote service has been deactivated, allow users to import a CSV file with stock quote data (e.g. Ticker, Price, Date) which would be inserted/update the STOCKHISTORY table.  Perhaps the "Refresh stock quotes from Yahoo" button on the Stock Portfolio screen could be re-purposed.  This would also trigger an update of each stocks current market value and the overall Stock Portfolio market value.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1367
