### ISSUE TITLE
Add support for custom field columns

### ISSUE THREAD

**Issue by olicooper** [moneymanagerex/moneymanagerex#1371]
It would be nice to be able to right click on the columns (especially in 'Account View') and be able to display custom fields.
It would also be great if we could use the import feature to import to custom fields.

In particular, I am looking to have "Transaction Type" field (separate from Category) that has the following possible options: "BGC;BP;CHQ;COR;CPT;CSH;DD;DEB;DEP;FPI;FPI;INT;TFR" and be able to import my transaction list to it from a CSV export from my bank.

Currently, the transaction types i mention above are stored under the category field which isn't ideal.
I am using the software predominantly for personal finance.

Your OS:
- [x] Windows

MMEX version:
- [x] 1.3.x

**Comment by vomikan** [comment]
#1585

**Comment by slodki** [comment]
Now in #1664
