### ISSUE TITLE
Edit transactions in list results after report filter applied

### ISSUE THREAD

**Issue by mariolences** [moneymanagerex/moneymanagerex#1372]
Hello. If i want to use benefits of multiple category transaction, i need to use report filter. As in android version, please add support also in PC version to edit transactions directly from transaction list results after report filter applied.

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by stef145g** [comment]
Using the Transaction Report filter will create a report which cannot be edited, This report will link a transaction to the transaction list where it can be edited.

When the transaction filter is applied within an account, you will then have the capability to edit the transactions. Selecting another account will maintain the active filter elements.
