### ISSUE TITLE
Problem with currency rate

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/moneymanagerex#1373]
Your OS:
- [X] Mac OSX

MMEX version:
- [X] development version (git master branch)

For some reason, MMEX does not use the "last rate" value of a currency to convert the amount of an account into the base currency (which is shown in the Organise Currency... menu) but only use the "Conversion to Baserate" value which is shown in the "Edit" currency window.

**Comment by mr10008** [comment]
The "last rate" value used to be updated from Yahoo finance API service that is now non-functional.
