### ISSUE TITLE
daily or occasional expenses transaction

### ISSUE THREAD

**Issue by noelthesilent** [moneymanagerex/moneymanagerex#1374]
Hi All,
        I am a new user it look great the only thing that I feel that I need [Cannot speak for others] is a daily or occasional expenses transaction area to be able to use for well daily or occasional expenses transaction that are random one offs. I would not be inclined to use put these in the "Recurring Transactions" as I would stop using the program once it became a total mess of obsolete single transactions filling the screen. It would make the cleanliness and usability your software now has vanish! I really HATE BOOK-WORK or any accounting I like important things in this pile and all the other crap in that pile it keeps things simple. :)
thank you
Noel 

Your OS:
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by stef145g** [comment]
As a once of transaction, I would create a new transaction in an account or use the toolbar "New Transaction" icon. Using the icon you will need to specify the account.

For simplification, after selecting an account, use the pop-up menu to create a specific Withdrawal, Deposit or Transfer transaction. Also, if you set up a payee using a specific category makes the creation of a transaction very easy to create. For the daily expenses, you can create a Wallet account. This way, all your daily expenses can come out of your wallet account.

Recurring Transactions should be used for regularly occurring or periodic transactions that will occur at some point in time.

**Comment by whalley** [comment]
Closing as described solution is deemed acceptable and originator of original issue has not responded to contradict this.
