### ISSUE TITLE
Report with long date range problem

### ISSUE THREAD

**Issue by ilmiman** [moneymanagerex/moneymanagerex#1377]
Hi, 
Windows 10 / MoneyManager 1.3.3 DB v7 error while trying to create a "Bericht" with given long
date range.
Thank's for help
Wbr Mikel

[Berichte.pdf](https://github.com/moneymanagerex/moneymanagerex/files/1538972/Berichte.pdf)

**Comment by slodki** [comment]
Could you describe steps you execute before error is displayed and exact error message?

**Comment by slodki** [comment]
@ilmiman: is this the same problem as #1378?

**Comment by vomikan** [comment]
Please reopen with more details how to reproduce.
