### ISSUE TITLE
I cant sync to google, it keeps saying filename different from local and im not sure what this means 

### ISSUE THREAD

**Issue by byrnet1** [moneymanagerex/moneymanagerex#1383]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [X] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
Please create issue at [moneymanagerex/android-money-manager-ex](https://github.com/moneymanagerex/android-money-manager-ex) if you are using Android version.
