### ISSUE TITLE
Enable/disable payees

### ISSUE THREAD

**Issue by marcoverga86** [moneymanagerex/moneymanagerex#1390]
Hi,
it happened to me that I created some payees that I used only once or twice (or maybe there is some payee that I don't use anymore).
Now when I create a new transaction and I have to select a payee in the list I have every payee (I know I can have the payee set by default for a category).

Would it be possible to add the ability to hide some payees? I mean, when I go in the "Organize Payees" form and I right click on one of them to have an third option: Add - Edit - **Disable** (or Enable if it's already disabled).
By doing this, when creating a new transaction only the active payees will be shown. 

Your OS:
- [x] Windows
- [x] Mac OSX

MMEX version:
- [x] 1.3.x

Thanks,
Marco

**Comment by marcoverga86** [comment]
And also, the same thing could be applied to categories, as well!

**Comment by slodki** [comment]
Please look at #1368. I think this should be enough to quickly select payee from list.

Payees are created on-the-fly during batch transaction import in my case, I don't want to control them (consolidate different spellings only). Payees are used not only for tracking transfers to important companies, but to store details of my all transactions. I've new payees every day.

**Comment by vomikan** [comment]
I recommend to merge all unused payees to one, for example, "outdated" or "unused"
![image](https://user-images.githubusercontent.com/6836805/35732698-83db225c-082b-11e8-9381-07dd6d708c44.png)

**Comment by marcoverga86** [comment]
Well, merging the unused categories/payees in a new one called "old" or "unused" for me it's not a solution... I would lose the history of my expenses, so for me it's not a "solution found", because it's a "workaround"! I thought I proposed a good enhancement (also because I don't think it's too expensive to implement), but nevermind, I've been using this program as is for 7 years, I think I'll have no problem to keep it as is!

**Comment by slodki** [comment]
So you don't want to hide or disable payees/categories but only to display shorter list as suggestion for entering values. The method described above in #1368 will shorten the list to few entries just after entering few chars from keyboard.

**Comment by marcoverga86** [comment]
Slodki, you're talking of **filtering them on the fly**. I'd like to have an option to hide them by default, because I don't want to see in the list of the categories the entry "University rent", because I finished the university 8 years ago, and that category (and the associated payee) for me are dead. But I don't want to "delete" them (or move them to a "not-used" category, because otherwise I'd lose track of my expenses)...

**Comment by slodki** [comment]
Sorry, i don't understand your needs. You don't want see University category, but you want see expenses in this category. You want to move this category to "not-used" but it should be still used by many of your old transactions.

**Comment by marcoverga86** [comment]
I'd like to see "university" only in old transactions, but it should be hidden in the list of the categories, because it's "inactive" (or not used, or cancelled, call it the way you want). Technically speaking, on the categories table there should be a field named active/cancelled/disabled that can be set to 1 and so, when selecting a category for a new transaction, I'd never see "University" because it would be (logically) cancelled. And obviously I couldn't delete it, because it's a Foreign Key on the checking_account tables.

**Comment by vomikan** [comment]
I suggest to use dot as prefix for unused payees and categories. 
In that case we can update payee and transactions UI to skip that names.

**Comment by marcoverga86** [comment]
Sorry for the late reply...
Yes, that would be a great idea!! Thanks!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4216

**Comment by whalley** [comment]
Part 1 - Support for Payees - https://github.com/whalley/moneymanagerex/commit/0408214731f94b384496ad7e5dc78cccda9e56b5

**Comment by whalley** [comment]
I've noticed we us the term 'Hidden' for similar functionality with Categories. Perhaps this is better wording?

**Comment by tactilis** [comment]
Agreed. Hidden expresses clearly the fact that you won't _see_ the Payee in the drop down list.

Whereas Inactive represents the 'status' of a Payee, which may mean different things to different people.
