### ISSUE TITLE
Unexpected character in NUMBER token: crash

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#1392]
Hi, I was trying installing on Linux (fed up with windows... :)  )
OS: Linux mint 18.3 Sylvia cinnamon
MMEX version: 1.4.0- alpha.3
Was following the install steps on the web page:[https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux](url)
which went just fine, but when i'm running the app, i'm getting : 
> Unexpected character in NUMBER token: > crash popup
![image](https://user-images.githubusercontent.com/7680483/34564957-926b215e-f161-11e7-8b51-f82d92e3b1d6.png)

Any idea? Am i doing something wrong here?
Meny thanks
Avi

**Comment by lonemadmax** [comment]
cf #773, #1175 and #1323

FWIW, I also suffered this problem, but it has never repeated for quite some time. I was playing with sources and configuration files on something unrelated, so I can't tell whether it went away because of cleaning up configuration stuff or by updating the program.

Last time I updated master had d0f05a17, which is some 50 commits after release of 1.4.0-alpha3, so it might be worth a try to update to master.

**Comment by avma** [comment]
Great thanks, i'm going to try this and see how goes it...

**Comment by slodki** [comment]
We should wait for #1207 to have this one fixed

**Comment by avma** [comment]
Unfortunately that did not work for me, removed and made a fresh install from master c8e77b4  some 20 hours ago but same error pops up.
On the log file i found this line:
![image](https://user-images.githubusercontent.com/7680483/34643101-2a656f2a-f327-11e7-9b24-2e3d11836f77.png)

**Comment by avma** [comment]
#1207  is more than six month old :( any chance it will happen sometime soon?

**Comment by vomikan** [comment]
#1175 #773

**Comment by vomikan** [comment]
Is last build with new DB fails too?

**Comment by avma** [comment]
actually i was not been able to compile from git. 

MAKE PACKAGE ended with:
> [100%] Linking CXX executable mmex
/usr/bin/ld: libMMEXLib.a(relocatepayeedialog.cpp.o): undefined reference to symbol '_ZThn760_NK10wxTextCtrl7HitTestERK7wxPointPl@@WXU_3.0'
//usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/mmex.dir/build.make:100: recipe for target 'src/mmex' failed
make[2]: *** [src/mmex] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/mmex.dir/all' failed
make[1]: *** [src/CMakeFiles/mmex.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
>

**Comment by MartinX3** [comment]
Is it now fixed with latest commit?

**Comment by avma** [comment]
Unfortunately no...

`MMEX configuration summary

Version        : 1.4.0~alpha3
Commit         : 181a8cb4 (2018-03-14)
Branch         : master
Build tests    : OFF
Host system    : Linux x86_64
Target system  : Linux x86_64
Build types    : Release
Generator      : Unix Makefiles
Install prefix : /usr/local`

MAKE PACKAGE ended with prety much the same error:

`[100%] Linking CXX executable mmex
/usr/bin/ld: libMMEXLib.a(relocatepayeedialog.cpp.o): undefined reference to symbol '_ZThn760_NK10wxTextCtrl7HitTestERK7wxPointPl@@WXU_3.0'
//usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/mmex.dir/build.make:100: recipe for target 'src/mmex' failed
make[2]: *** [src/mmex] Error 1
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/mmex.dir/all' failed
make[1]: *** [src/CMakeFiles/mmex.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by slodki** [comment]
@avma Please test fixed version from https://github.com/slodki/moneymanagerex/releases/tag/test2
