### ISSUE TITLE
Add trans to asset crashes the app

### ISSUE THREAD

**Issue by dsnunez** [moneymanagerex/moneymanagerex#1395]
I created an asset, created a brand new account for it (the app said there was no account found and asked mr if I wanted to create one and so I did) and then I clicked button "Add trans" and the app crashed.

Tried it all over again and the result was the same.

I'm using MMEx 1.3.3, with CLP in spanish

Your OS:
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x (1.3.3)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
@dsnunez Could you try 1.4.x version? I cannot reproduce this error on 1.4.x version.

**Comment by dsnunez** [comment]
I did. It crashed again. I sent the debug report generated by the 1.4 version.
Let me know if you need more information in order to reproduce this error.

**Comment by slodki** [comment]
@dsnunez I cannot find debug report attachment you mentioned above. Could you attach it to this issue?

**Comment by siowena** [comment]
Is this related to #2288
