### ISSUE TITLE
"Can not save BILLSDEPOSITS_V1" error while MMEX using >93% CPU usage

### ISSUE THREAD

**Issue by simply-does-it** [moneymanagerex/moneymanagerex#1400]
1. I  cannot "Use Help->Report a Bug in MMEX" because MMEX on my computer is close to frozen even for simple tasks.

2. Windows 10 Home desktop
AMD Athlon II X2 245 Processor 2.90 GHz, 7.75 usable RAM

3. Fairly recently, MMEX started running extremely slowly, or even freezing, when doing any action such as
- open an account by left-clicking on the account name,
-  left-clicking on 'New' or 'Edit' within an account, 
- right-clicking on an account name to obtain that menu, 
- choosing Initial Balance from that menu,
- on New Item, selecting Payee or Category dropdowns, 
-Within New Item, clicking on OK when the entry is completed.
When the program appears to hang, at any of these stages, I escape by ending that item in the Windows Task Manager processes section. This happens frequently. For complicated actions (not just changing an amount), I close down MMEX after every action. Fortunately so far, MMEX has remembered what I have just done, even though I cannot save as I go.

4. When this started, 
- I upgraded to 1.3.3, but that did not help. 
- Nor has using 1.4.0 Alpha.3. 
- I added 127.0.0.1 to the Window Firewall exceptions. That did not help. 
- I 'stripped back'the database for the 15-odd accounts to the last two years' transactions by wholesale deleting almost two decades of entries!
This did not help.
(Stripping back also messed up the balances for each account, which then required each Starting Balance to be corrected. For small accounts with less than a page of transactions, only one correction was needed. For other accounts, multiple corrections were needed as the current Balance figure jumped greatly above and below the number wanted. With each change, MMEX froze, taking ages to close the pop-up for making changes, and when the pop-up closed, not changing the Balance. The corrections only appeared when MMEX restarted. However, I did note that as the corrections required became less extreme - say adding or subtracting £300 instead of say £20,000 - the Account Balance started to correct without having to reset if I waited enough.)

5. During all this, I have only once received an error message: Can not save BILLSDEPOSITS-V1.
I saved the log (eventually): 
"18:19:15: can not save BILLSDEPOSITS_V1
18:19:16: can not save BILLSDEPOSITS_V1
18:19:16: can not save BILLSDEPOSITS_V1
18:19:17: can not save BILLSDEPOSITS_V1
18:19:18: can not save BILLSDEPOSITS_V1
18:19:19: can not save BILLSDEPOSITS_V1
18:19:20: can not save BILLSDEPOSITS_V1
18:19:21: can not save BILLSDEPOSITS_V1
18:19:22: can not save BILLSDEPOSITS_V1
18:19:23: can not save BILLSDEPOSITS_V1"

6. My CPU usage is consistently being at least 93% when MMEX is open, with MMEX being listed as 80% and upwards CPU usage.

7. I am not a techie, but can generally follow instruction.
I don't want to be giving wrong suggestions, but might there be something like a cache that needs clearing?
It has taken me over a week to reach this point of writing to github.com. I had to do my end-of-year's accounts so I haven't been just able to post my message and wait for answers. However, I hope my keeping going has provided other information.

I would be grateful for advice on how to solve this.

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
See #1424 for solution (uncheck "send usage statistics" in options menu).
