### ISSUE TITLE
Non working currency button at Edit Asset Transaction dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1403]
There is [button with account currency label](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/usertransactionpanel.cpp#L152) next to amount field at Edit Asset Transaction dialog:

![mmex-currency-button](https://user-images.githubusercontent.com/3155552/34653758-f515ed66-f3f0-11e7-9754-a7ab4d95f555.png)

The button is active but there is no action when clicking on it.
@stef145g It should be changed for text label IMHO if not planned for later use.

**Comment by stef145g** [comment]
Control has been changed
