### ISSUE TITLE
Problem: conflicting requests - nothing provides wx-i18n needed by mmex-1.4.0~alpha3-1.fc27.x86_64

### ISSUE THREAD

**Issue by lverissimo** [moneymanagerex/moneymanagerex#1406]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux (FEDORA 27) 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

After sucessfully building the complete package I got an error while trying to install using dnf install. 
Any help is helpfull. Thank you.

**Comment by lonemadmax** [comment]
In CMakeLists.txt change
`SET(CPACK_RPM_PACKAGE_REQUIRES wx-i18n)`
into
`SET(CPACK_RPM_PACKAGE_SUGGESTS wxGTK3-i18n)`

That worked for me in F26, and when I checked, that seemed to be right for F27 and rawhide, although I didn't test those. In fact F26 and F27 wouldn't need anything, as the translated strings that the requirement is for were included in the wxGTK3 package. But in rawhide they were split into their own wxGTK3-i18n.

**Comment by lverissimo** [comment]
thank you! I had to remove the line to get it to work.
