### ISSUE TITLE
balance discrepancy between desktop and android tablet

### ISSUE THREAD

**Issue by realhelpinc** [moneymanagerex/moneymanagerex#1410]
On a credit card there is a discrepancy in the balance from a shared file in dropbox, the desktop showing one amount and the tablet showing a different amount. The desktop is correct but the tablet is showing a $2.09 discrepancy.

The balance was correct for the first 2 weeks using the software before this happened. I waited to verify that the file had updated before opening on both ends.

**Comment by slodki** [comment]
Please use moneymanagerex/android-money-manager-ex#606 if data displayed at PC is correct.
