### ISSUE TITLE
mismatch between MMEX and wxW build versions in AppVeyor builds

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1411]
After last [AppVeyor update](https://www.appveyor.com/updates/) MMEX binaries not start:
![error](https://user-images.githubusercontent.com/3155552/35184207-886dffc6-fdf2-11e7-9a04-b4b5a8ff3388.png)

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by stef145g** [comment]
Updates to VS2017 requires the builds for wxWidgets to be updated in the AppVeyor cache.
This can be achieved by preventing AppVeyor to use the cache data, so it can rebuild wxWidgets, and then restoring the usage of the cache.

**Comment by slodki** [comment]
AppVeyor script must detect MSVC version and invalidate cache when changed. New recompiled wxWin will be cached when the job finish.
CLcache tool will detect cl.exe binary file change and rebuild its cache automatically.
