### ISSUE TITLE
Monthly Summary of Accounts crashes application

### ISSUE THREAD

**Issue by d03j** [moneymanagerex/moneymanagerex#1414]
Hi,

I'm a new user and we use MMEX primarily via two Android phones syncing to the same gdrive folder. I wanted to use the desktop at home when reconciling transactions and have set up a gdrive sync for that purpose. The syncs work fine as long as one of us does not update the database between the other one opening the app and modifying a record. :)

On my desktop,  application crashes the when I click on Monthly Summary of Accounts.

Originally I thought it might have to do with not having payees against my transactions. I noticed the desktop version did not let me edit transactions recorded on the Android apps because they lacked a payee. I created a generic payee and updated all records so they had a payee.

All other reports seem to be working except for this one.

Could this be due to me having less than a month worth of transactions?

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by tycariadus** [comment]
I too am having the same issue.  Running this crashes the app.

**Comment by d03j** [comment]
The workaround for now is to use dropbox. you can follow the issue here https://github.com/moneymanagerex/android-money-manager-ex/issues/1168#issuecomment-364577056
