### ISSUE TITLE
Prepare docker image with MMEX application

### ISSUE THREAD

**Issue by luoyanghero** [moneymanagerex/moneymanagerex#1419]
I use CentOS7.4 x64;

> [lb@localhost pyuv_docker]$ uname -a
> Linux localhost.localdomain 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> [lb@localhost pyuv_docker]$ docker -v
> Docker version 1.13.1, build 28e44a9
> 

I download moneymanagerex docker image from dockerhub. the version as follow:

> docker.io/moneymanagerex/moneymanagerex        v1.3.x                         1069c77e40a8        6 months ago        1.13 GB

First I pull the image from docker.io;
then I try to run the image using the follow command:

> $ sudo docker run docker.io/moneymanagerex/moneymanagerex:v1.3.x

I expect to show a GUI, but it ouput many compile log, a long-time past, it stucked here, no GUI show.
So how should I run the docker image?

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by luoyanghero** [comment]
I can find the image still running.

> [lb@localhost w]$ sudo docker container ls
> [sudo] password for lb: 
> CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
> 868c5094cb6f        moneymanagerex/moneymanagerex:v1.3.x             "/bin/sh -c './con..."   4 hours ago         Up 4 hours                              vigilant_banach
> d120dd3b1baa        docker.io/moneymanagerex/moneymanagerex:v1.3.x   "/bin/sh -c './con..."   14 hours ago        Up 14 hours                             agitated_kalam
>

**Comment by slodki** [comment]
I think this image was prepared for developers to compile sources of MMEX. It's very old, it runs `./configure && make -j10` command and not `cmake` we use now...

I'm the author of [moneymanagerex/mmex_build_env](https://hub.docker.com/r/moneymanagerex/mmex_build_env) - there are many images with clean install of different linux distributions with required packages to build MMEX packages, used by Travis CI script.

Your suggestion to have docker image to run MMEX app from is interesting, but I don't see any benefits - installing package dedicated for your distro/arch should be simpler and easier.

**Comment by slodki** [comment]
@guanlisheng Should we delete moneymanagerex/moneymanagerex docker hub repo as outdated?

**Comment by slodki** [comment]
@luoyanghero Do you know (as CentOS user) why this command fails in CentOS 7:
```
rpm --import https://getfedora.org/static/352C64E5.txt \
&& yum -y install http://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

Loaded plugins: fastestmirror, ovl
Cannot open: http://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
Error: Nothing to do
```

Or how to add epel repo to the CentOS 7 configuration? We need this to prepare binary packages for el.7 distributions like CentOS

**Comment by guanlisheng** [comment]
fine to remove docker if it can not be updated.

slodki <notifications@github.com>于2018年1月30日周二 下午7:22写道：

**Comment by slodki** [comment]
@guanlisheng We have updated dockerfile in `dockers/ubuntu.xenial/Dockerfile` already. The differences are:

1. No MMEX sources included in image so we can use the same docker image for different MMEX versions / commits / branches using `docker run -v` command to mount MMEX sources dir as volume on the fly.

2. No default command set via `CMD` dockerfile command - we can use different build command lines to use custom build options like debug/release, with test executable, for x86/x64 etc.

**Comment by slodki** [comment]
It's not easy task to run GUI application from docker image. There are many problems with user ID mapping, sharing disk volumes, accessing host graphical environment (Xorg etc.).

Snap simplify distribution system-independent packages with all above problems already solved and fully integrated with user desktop environment. MMEX is avaiable at [Snap Store](https://snapcraft.io/mmex) already.

I think packaging MMEX into docker image is not needed.
