### ISSUE TITLE
monthly report problem

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/moneymanagerex#1422]
Montly report on income-expenses report that tha upper bar for custom report with custom period and custom accounts.

Will be useful the same upper bar for custom report on Montly report on categories.

On the custom report bar is possible to add categoris filter in addidion to period and accounts ?

Thanks 

Giorgio Graziotti

**Comment by ggraziotti** [comment]
shoud be a new and useful feature ...

**Comment by vomikan** [comment]
Related issue #1085
