### ISSUE TITLE
MacOS Bundle plist incomplete

### ISSUE THREAD

**Issue by bestlem** [moneymanagerex/moneymanagerex#1441]
Your OS:
- [ ] Windows
- [X] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

the bundle identification has several fields that are left as default. They should show details corresponding to mmex. I have taken information from https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1 tables 2.6 and 2.7.

You can see them some output in the crash report from macOS e.g. bug #1440 here

The fields are
CFBundleIdentifier currently left to com.yourcompany.MMEX surely better as org.moneymanagerex.mmex
CFBundleExecutable should it be lower case
CFBundleVersion  current;y set to 1 should be from version.h (probably 1.4.0) but could have a build number attached.
CFBundleShortVersionString currently 1.0 should be 1.4.0

Also should we be setting CFBundleDisplayName? It needs localisation
Similarly for NSHumanReadableCopyright

**Comment by bestlem** [comment]
I have generated a file that I think is correct see attached.




However I did this after altering the cmake files I think I need for https://forum.moneymanagerex.org/viewtopic.php?f=7&t=7409
I think I can get this fix working in the current Cmake files but would like to have comments from other MacOS developers and/or someone who knows the cmake build to see if I am doing the correct thing.

**Comment by core-code** [comment]
the CFBundleLongVersionString entry has been deprecated for more than 10 years and should probably be removed

**Comment by slodki** [comment]
Does CFBundleLongVersionString generate any problem?

**Comment by core-code** [comment]
i don't think it generates any problem but it has been deprecated so long that it isn't even listed on Apple's developer site anymore. i think deprecation was around 2005.
