### ISSUE TITLE
Account missing when editing entry

### ISSUE THREAD

**Issue by beekay70** [moneymanagerex/moneymanagerex#1447]
![mm bug](https://user-images.githubusercontent.com/34241422/36631086-a7da8306-1969-11e8-9bfd-a35fd68599ec.JPG)

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Is the pulldown menu contains items?
This bug already fixed. What mmex version are you used?

**Comment by vomikan** [comment]
Related #1375 #1043 #1348
