### ISSUE TITLE
add missing currencies using ISO 2417:2015 list

### ISSUE THREAD

**Issue by sermai** [moneymanagerex/moneymanagerex#1449]
helllo,

i wish it was possible to include zambian Kwacha as a currency with the right acronym (ZMW), and that already input values for which the currency exchange was already calculated, would not change once the exchange rate is updated/recalculated. greetings

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [x] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [x] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Any currency may be added by user manually.

![image](https://user-images.githubusercontent.com/6836805/37328981-04d398a4-26ad-11e8-9363-541c4b9aa682.png)

**Comment by slodki** [comment]
moneymanagerex/database@81227d73453dbcb129a52934096c35b3ca22f3fe
