### ISSUE TITLE
mmex UI language

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1452]
Now OS settings is using for User Interface Language.
I need English or sometimes any other language.
It should be option to change a Language.

Your OS:
- [X] Windows
- [X] Mac OSX
- [X] Linux 

MMEX version:
- [X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] development version (git master branch)

**Comment by slodki** [comment]
`View` -> `Switch Application Language` + restart is not enough?

**Comment by vomikan** [comment]
:)
