### ISSUE TITLE
Currency separator not displaying on latest Master

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1456]
I have downloaded and compiled (with latest VS2017) the source at tag v1.4.0-Alpha.3 commit 79562d4 and the Home Page displays totals correctly i.e. 12345.67 displays as £12,345.67 with currency set to UK Pounds. Transactions display correctly as well - no currency symbol but thousands separator is present.

Download and compile with latest master at commit 532956f and 12345.67 now appears as £12345.67 on the Home Page and as 12345.67 in a transaction display - thousands separator has disappeared.
 
Using the same test database for both levels of source and CURRENCYFORMATS_V1 table looks fine.
Can you reproduce or is this "user error" ?

Your OS:
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
![default](https://user-images.githubusercontent.com/6836805/36856183-70d65288-1d86-11e8-85c2-58b20000be41.JPG)

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?t=39002

**Comment by slodki** [comment]
In 21ad7d9b76dba08348714fa88eb10d1ddafe37ba we [stopped always use English locale](https://github.com/moneymanagerex/moneymanagerex/commit/21ad7d9b76dba08348714fa88eb10d1ddafe37ba#diff-4c1142bf1ba27682b8dfed154c0c56a3L145) in mmex. Now system configured locale settings are used - user can change them outside mmex app.

Please verify your system settings - locale installed, used, currency settings.

**Comment by grumpy235** [comment]
Thanks guys. I'll have a play.
So although 1.4.0Alpha3 tag is dated Aug 11th and 21ad7d9 is dated earlier (Aug 3rd) it did not make it to Alpha3 ?

**Comment by grumpy235** [comment]
Changed language to English and to English(US) under VIEW menu on latest MMEX and still NO Grouping char for either language.
Checked Windows 10 "Region & Language" panel and they are as expected - United Kingdom for Region and English(United Kingdom) for Language. They have always been that for years!
Tried changing Language to German via MMEX VIEW option. Now get text in German as expected and money with a £ prefix and no group character - reasonable I guess as still using a currency of "UK Pound"
Just searched MMEX latest source for wxLOCALE_THOUSANDS_SEP and can find no hits so I guess MMEX is not using wxLocale to format money numbers but I guess must be doing it via CURRENCYFORMATS_V1. Perhaps the i18n change has affected this process

**Comment by grumpy235** [comment]
Debugging Model_Currency.cpp

1.4.0alpha3 level 
Model_Currency::toString references Model_Currency::os_group_separator() which returns a sys_thousand_separator of "," which is the expected value
Currency string is then formatted correctly.

Current master level
sys_thousand_separator returned is " " so Group Character in currency table row is ignored !

**Comment by slodki** [comment]
Swiching language under `View` menu changes only translation strings for GUI, without impact on used locale.

See also #1150 #1153 #1358

**Comment by grumpy235** [comment]
Looks like the used locale is now different to that used before the translation changes and is possibly not initialised?
The wxWidgets example for i18n sets up the frame with its own "locale" [https://github.com/wxWidgets/wxWidgets/blob/master/samples/internat/internat.cpp]

**Comment by grumpy235** [comment]
Just for interest, I have just run with wxWidgets 3.1.1 and that does not fix the problem

**Comment by grumpy235** [comment]
I have "fixed" the missing group separator for my setup (UK Pound and GUI in English) by putting the following lines back which were removed by the i18n commit..

**mmex.h**
wxLocale& getLocale();
wxLocale m_locale; // locale we'll be using

**mmex.cpp**
wxLocale& mmGUIApp::getLocale()
{
    return this->m_locale;
} 

/* Setting Locale causes unexpected problems, so default to English Locale*/
    app->getLocale().Init(wxLANGUAGE_ENGLISH);
	
It now displays money numbers as before with the correct group separator i.e. comma.
Switch language to German-GUI text changes and money still OK - BTW not all items in File/Accounts/Tools/View/Help are translated. The actual headings are translated but for example in Accounts, the text is still "Reallocate Account".

**Comment by slodki** [comment]
Could you test with `app->getLocale().Init();` (it's equal to `app->getLocale().Init(wxLANGUAGE_DEFAULT, wxLOCALE_LOAD_DEFAULT);`)?

We want to be able to swich use locale selected at system level then change translations without impact on locale. Forcing `wxLANGUAGE_ENGLISH` is not good for all users.

**Comment by grumpy235** [comment]
Was thinking about that but I simply followed what was in the comment.
The change works for me with Windows 10 set to UK.
Both numbers and money have the correct thousands delimiter.
Changing the language to German (thousands delimiter is a full stop I think) simply changes the GUI text, as expected no affect on numbers or money. Guess someone needs to test with a Windows Regional setting which does not use "," for thousands and "." for decimal just to be sure.
