### ISSUE TITLE
MMEX crash after selecting report several time

### ISSUE THREAD

**Issue by gusman** [moneymanagerex/moneymanagerex#1473]
Your OS
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.3
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

** Uname **
>Linux 4.15.9-1-ARCH #1 SMP PREEMPT Sun Mar 11 17:54:33 UTC 2018 x86_64 GNU/Linux

**Procedure:** 
> 1. MMEX using database that stored in dropbox
> 2. Before starting MMEX dropbox sync shall complete
> 3. Select report several times
> 4. MMEX become crashes

**Stack Trace:**
>#0  0x00007f598110f860 raise (libc.so.6)
>#1  0x00007f5981110ec9 abort (libc.so.6)
>#2  0x00007f5982364652 n/a (libwx_baseu-3.0.so.0)
>#3  0x00007f59814a3dd0 __restore_rt (libpthread.so.0)
>#4  0x00007f59802aadae g_type_check_instance_is_a (libgobject-2.0.so.0)
>#5  0x00007f597ffa5428 g_dbus_server_get_client_address (libgio-2.0.so.0)
>#6  0x00007f5983b80c92 n/a (libwx_gtk3u_webview-3.0.so.0)
>#7  0x00007f5980283c5d g_closure_invoke (libgobject-2.0.so.0)
>#8  0x00007f5980297b50 n/a (libgobject-2.0.so.0)
>#9  0x00007f59802a0806 g_signal_emit_valist (libgobject-2.0.so.0)
>#10 0x00007f59802a1240 g_signal_emit (libgobject-2.0.so.0)
>#11 0x00007f597d7abac4 n/a (libwebkit2gtk-4.0.so.37)
>#12 0x00007f597d794147 n/a (libwebkit2gtk-4.0.so.37)
>#13 0x00007f597d5c3d9a n/a (libwebkit2gtk-4.0.so.37)
>#14 0x00007f597d5c43e3 n/a (libwebkit2gtk-4.0.so.37)
>#15 0x00007f597d7d09e3 n/a (libwebkit2gtk-4.0.so.37)
>#16 0x00007f597d7ad955 n/a (libwebkit2gtk-4.0.so.37)
>#17 0x00007f597d7b4ba9 n/a (libwebkit2gtk-4.0.so.37)
>#18 0x00007f59802898e8 n/a (libgobject-2.0.so.0)
>#19 0x00007f598028b670 g_object_new_valist (libgobject-2.0.so.0)
>#20 0x00007f598028b9fa g_object_new (libgobject-2.0.so.0)
>#21 0x00007f597d7d3cdc webkit_web_view_new_with_context (libwebkit2gtk-4.0.so.37)
>#22 0x00007f5983b81d3e _ZN15wxWebViewWebKit6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_ (libwx_gtk3u_webview-3.0.so.0)
>#23 0x00007f5983b8b135 _ZN9wxWebView3NewEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizeS4_lS4_ (libwx_gtk3u_webview-3.0.so.0)
>#24 0x00000000006143a0 n/a (mmex)

**Error / Warning  Message:**
>Got reply:
>GIF89a
>
>(mmex:5409): GLib-GIO-CRITICAL **: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER >(server)' failed
>
>(mmex:5409): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
>
>(mmex:5409): GLib-GIO-CRITICAL **: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER >(server)' failed
>
>(mmex:5409): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
>
>(mmex:5409): GLib-GIO-CRITICAL **: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER >(server)' failed
>
>(mmex:5409): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
>http://www.google-analytics.com/collect?an=MoneyManagerEx&av=1.3.3&cd1=gtk&>cid=gtk_20171125183311692&dp=/frame/panel/mmReportsPanel&dt=mmReportsPanel&sd=24-bits&sr=1366x768&t=pageview&tid=UA-51521761-6&v=1 
>User-Agent: Linux 4.15.9-1-ARCH x86_64
>
>Got reply:
>GIF89a
>
>(mmex:5409): GLib-GIO-CRITICAL **: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER >(server)' failed
>
>(mmex:5409): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
>http://www.google-analytics.com/collect?an=MoneyManagerEx&av=1.3.3&cd1=gtk&cid=gtk_20171125183311692&dp=/dialog&dt=Debug%20report%20%22mmex%22&sd=24-bits&sr=1366x768&t=pageview&tid=UA-51521761-6&v=1 
>User-Agent: Linux 4.15.9-1-ARCH x86_64
>
>(mmex:5409): Gtk-WARNING **: Negative content width -11 (allocation 1, extents 6x6) while allocating >gadget (node entry, owner GtkEntry)
>
>(mmex:5409): Gtk-WARNING **: Negative content width -11 (allocation 1, extents 6x6) while allocating >gadget (node entry, owner GtkEntry)
>Got reply:
>GIF89a
>http://www.google-analytics.com/collect?an=MoneyManagerEx&av=1.3.3&cd1=gtk&cid=gtk_20171125183311692&dp=/dialog&dt=Debug%20report%20%22mmex%22&sd=24-bits&sr=1366x768&t=pageview&tid=UA-51521761-6&v=1 
User-Agent: Linux 4.15.9-1-ARCH x86_64

**Comment by slodki** [comment]
@gusman Could you try my [today's build](https://github.com/slodki/moneymanagerex/releases/tag/test1) pkg.tar.xz package - it should [install](https://travis-ci.org/slodki/moneymanagerex/jobs/356825827#L1667) without errors.

**Comment by gusman** [comment]
@slodki 
I already tried again, using today's build : mmex-1.4.0.alpha3-1-x86_64.pkg.tar.xz 
The same problem still occurs.

Below is coredump stack trace:
Stack trace of thread 1260:
>#0  0x00007f5c37ee1860 raise (libc.so.6)
>#1  0x00007f5c37ee2ec9 abort (libc.so.6)
>#2  0x00007f5c393b3652 n/a (libwx_baseu-3.0.so.0)
>#3  0x00007f5c38275dd0 __restore_rt (libpthread.so.0)
>#4  0x00007f5c366dadae g_type_check_instance_is_a (libgobject-2.0.so.0)
>#5  0x00007f5c34e13428 g_dbus_server_get_client_address (libgio-2.0.so.0)
>#6  0x00007f5c39690c92 n/a (libwx_gtk3u_webview-3.0.so.0)
>#7  0x00007f5c366b3c5d g_closure_invoke (libgobject-2.0.so.0)
>#8  0x00007f5c366c7b50 n/a (libgobject-2.0.so.0)
>#9  0x00007f5c366d0806 g_signal_emit_valist (libgobject-2.0.so.0)
>#10 0x00007f5c366d1240 g_signal_emit (libgobject-2.0.so.0)
>#11 0x00007f5c3292eac4 n/a (libwebkit2gtk-4.0.so.37)
>#12 0x00007f5c32917147 n/a (libwebkit2gtk-4.0.so.37)
>#13 0x00007f5c32746d9a n/a (libwebkit2gtk-4.0.so.37)
>#14 0x00007f5c327473e3 n/a (libwebkit2gtk-4.0.so.37)
>#15 0x00007f5c329539e3 n/a (libwebkit2gtk-4.0.so.37)
>#16 0x00007f5c32930955 n/a (libwebkit2gtk-4.0.so.37)
>#17 0x00007f5c32937ba9 n/a (libwebkit2gtk-4.0.so.37)
>#18 0x00007f5c366b98e8 n/a (libgobject-2.0.so.0)
>#19 0x00007f5c366bb670 g_object_new_valist (libgobject-2.0.so.0)
>#20 0x00007f5c366bb9fa g_object_new (libgobject-2.0.so.0)
>#21 0x00007f5c32956cdc webkit_web_view_new_with_context (libwebkit2gtk-4.0.so.37)
>#22 0x00007f5c39691d3e _ZN15wxWebViewWebKit6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_ (libwx_gtk3u_webview-3.0.so.0)
>#23 0x00007f5c3969b135 _ZN9wxWebView3NewEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizeS4_lS4_ (libwx_gtk3u_webview-3.0.so.0)
>#24 0x0000559ac04fede6 _ZN14mmReportsPanel14CreateControlsEv (mmex)

**Comment by slodki** [comment]
I see there are [2 versions of wxWidgets avaiable in Arch](https://www.archlinux.org/packages/extra/x86_64/wxgtk/): compiled against gtk2 and gtk3.
I will try to rebuild Arch MMEX package to use wxgtk2 in place of wxgtk3.

**Comment by slodki** [comment]
Sorry, but  Antonio Rojas [dropped webview support from wxgtk2](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/wxgtk) package and wxgtk3 is the only option left.

Are you using latest 3.0.4 version? It should *allow using more recent WebKit2GTK+ in wxWebView*...

**Comment by gusman** [comment]
@slodki Yes, I am using wxgtk3 version 3.0.4.

Also, after I changed my webkit2gtk package from 2.18.6 to 2.20.0, then I tried to run mmex of today's build I got message "mmex: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: soup_session_connect_async". And mmex cannot be executed.

**Comment by slodki** [comment]
Our build uses:
- webkit2gtk-2.18.6-1
- wxgtk-common-3.0.4-1
- wxgtk3-3.0.4-1

I'll try to add testing repo, install newer versions and rebuild MMEX...

**Comment by gusman** [comment]
Arach Linux today's release already includes "webkit2gtk 2.20.0-1".
I try to rebuild using todays source code with commit sha1: 4e5fa9096, the same problem still occurs.

Below is the stack trace:
>#0  0x00007f925184b860 raise (libc.so.6)
>#1  0x00007f925184cec9 abort (libc.so.6)
>#2  0x00007f9252d1e652 n/a (libwx_baseu-3.0.so.0)
>#3  0x00007f9251bdfdd0 __restore_rt (libpthread.so.0)
>#4  0x00007f925005ad0e g_type_check_instance_is_a (libgobject-2.0.so.0)
>#5  0x00007f924e78f918 g_dbus_server_get_client_address (libgio-2.0.so.0)
>#6  0x00007f9252ffbc92 n/a (libwx_gtk3u_webview-3.0.so.0)
>#7  0x00007f9250033c2d g_closure_invoke (libgobject-2.0.so.0)
>#8  0x00007f9250047bb0 n/a (libgobject-2.0.so.0)
>#9  0x00007f9250050746 g_signal_emit_valist (libgobject-2.0.so.0)
>#10 0x00007f9250051180 g_signal_emit (libgobject-2.0.so.0)
>#11 0x00007f924c54b3a4 n/a (libwebkit2gtk-4.0.so.37)
>#12 0x00007f924c533737 n/a (libwebkit2gtk-4.0.so.37)
>#13 0x00007f924c2a003a n/a (libwebkit2gtk-4.0.so.37)
>#14 0x00007f924c2a0302 n/a (libwebkit2gtk-4.0.so.37)
>#15 0x00007f924c2a0823 n/a (libwebkit2gtk-4.0.so.37)
>#16 0x00007f924c571c23 n/a (libwebkit2gtk-4.0.so.37)
>#17 0x00007f924c54d885 n/a (libwebkit2gtk-4.0.so.37)
>#18 0x00007f924c554b99 n/a (libwebkit2gtk-4.0.so.37)
>#19 0x00007f9250039898 n/a (libgobject-2.0.so.0)
>#20 0x00007f925003b620 g_object_new_valist (libgobject-2.0.so.0)
>#21 0x00007f925003b9aa g_object_new (libgobject-2.0.so.0)
>#22 0x00007f924c57592c webkit_web_view_new_with_context (libwebkit2gtk-4.0.so.37)
>#23 0x00007f9252ffcd3e _ZN15wxWebViewWebKit6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_ (libwx_gtk3u_webview-3.0.so.0)
>#24 0x00007f9253006135 _ZN9wxWebView3NewEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizeS4_lS4_ (libwx_gtk3u_webview-3.0.so.0)

**Comment by avma** [comment]
Hi,
Just to let you know all this is still happening on a fresh install of Linux mint 19 tara and the latest nightly build commit: 9944a79 (2018-06-06)...
My best regards
Avi

**Comment by gusman** [comment]
I just build MMEX V1.3.3  on Debian Jessie and Deploy it on Debian Jessie.
This 'repor't crash issue does not occur anymore.

**Comment by alerque** [comment]
It sounds like this is what I'm seeing too ... the first report (of any kind) runs fine but the second report (of any kind) always crashes hard.

Archlinux + MMex 1.3.3 here too.
