### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1474]
Autocomplete based on existing tags for notes field.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/896

**Comment by slodki** [comment]
More options:
- tags hierarchy (grouping tags, family := child wife sister etc)
- tags cloud to quicky select most frequent

**Comment by vomikan** [comment]
#1585

**Comment by slodki** [comment]
Do you mean mltiple choice = tag?
This require autocomplete, adding missing on-the-fly...
This implementation forces no tag hierarchy.
I wonder if implementing [tag cloud main page widget](https://www.google.com/search?q=tag+cloud&tbm=isch) is possible

**Comment by vomikan** [comment]
>Do you mean mltiple choice = tag?

Even string with autocomplite is ok fot this

**Comment by slodki** [comment]
Tag should allow to store multiple values.
I think custom field is only workaround and not user friendly tags implementation
