### ISSUE TITLE
Enable transfers between accounts

### ISSUE THREAD

**Issue by Letme** [moneymanagerex/moneymanagerex#1475]
This is a feature request somehow similar to #1103 but a lot easier. Imagine you have multiple accounts (like credit card, cash, savings) where you transfer money between them. In Payee option you could by default include all existing accounts and when one takes a minus amount the other would get plus that same amount.

Below is an example:
```
Account A = 100 USD
Account B = 50 USD
Transfer from account A to B 25 USD (so you put a minus on account B)
Automatically generate transfer of + 25 USD on account B (this feature would be great)
```

**Comment by vomikan** [comment]
What is difference between you proposal and just transfer transaction?

**Comment by Letme** [comment]
Transfer transaction does not automatically generate the positive transfer on account B.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/37586156-7a3fb24e-2b6c-11e8-92dd-8102ac6de7b1.png)
