### ISSUE TITLE
SmartScreen issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1486]
Windows protected your PC
Windows SmartScreen prevented an unrecognized app from starting, Running this app might put your PC at risk.

Your OS:
- [X] Windows 8, 10

![image](https://user-images.githubusercontent.com/6836805/37699315-123f2548-2cf8-11e8-97c4-d34b6399b6e9.png)

**Comment by vomikan** [comment]
https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/

**Comment by slodki** [comment]
see #1501

**Comment by slodki** [comment]
![screenshot 22](https://user-images.githubusercontent.com/3155552/39425707-e790c62c-4c7c-11e8-993b-552983f5ef69.png)
