### ISSUE TITLE
Crash while setting base currency in new database wizard

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1489]
Crash while setting base currency in new database wizard

1. Start MMEX
2. Select `Create new database` option from start-up dialog
3. Follow *New Database Wizard* steps to the base currency selection screen with `Set Currency` button
4. Open *Currency Dialog*
5. Click on any currency in left panel **with right mouse button**
6. Select `Set as Base Currency` from context menu
7. MMEX crashes with following stack trace:

   ```xml
    <frame level="0" function="mmGUIApp::reportFatalException(wxDebugReport::Context)" offset="0000036a"/>
    <frame level="1"/>
    <frame level="2"/>
    <frame level="3" function="mmMainCurrencyDialog::SetBaseCurrency(int&amp;)" offset="000000bf"/>
    <frame level="4" function="mmMainCurrencyDialog::OnMenuSelected(wxCommandEvent&amp;)" offset="0000007c"/>
    <frame level="5" function="mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&amp;), wxEvent&amp;)
   ```

5b. Select any currency in left panel **with left mouse button**

6b. Click on `Select` button at the bottom

7b. Selection is made and wizard continues without problems

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by vomikan** [comment]
```
    Model_Currency::Data* BaseCurrencyOLD = Model_Currency::instance().get(baseCurrencyOLD);
    BaseCurrencyOLD->BASECONVRATE = 1;
```
