### ISSUE TITLE
Icon/Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [moneymanagerex/moneymanagerex#1491]
Good day @moneymanagerex, 
I am a designer and i am proposing an icon/logo design  for the app. I made an issue in the android version and Sir @MisterY  advised me to make also an issue here in the desktop version because its in the same brand. Below are the links to my design proposal and I'm hoping that you will like it and use it. Thanks and Best regards! 

ICON
http://res.cloudinary.com/tobaloidee/image/upload/v1521730001/MONEYMANAGEREX/MMEX-01.png

LOGO IDEA ( I also incorporated the "Birds Eye View" statement in the description of the app )
http://res.cloudinary.com/tobaloidee/image/upload/v1521729838/MONEYMANAGEREX/logo_idea.png

BENEFITS-IMPROVEMENTS
http://res.cloudinary.com/tobaloidee/image/upload/v1521729839/MONEYMANAGEREX/benefits_improvements.png

LOGOTYPES
http://res.cloudinary.com/tobaloidee/image/upload/v1521729834/MONEYMANAGEREX/logotypes.png

Im hoping for your positive response. Best regards! Thanks!

Tobaloidee

**Comment by snarchio** [comment]
Nice and definitively better than the original one
Only a point: the logo inside the circle seems a little small. Maybe it cam be enlarged a bit making the external "lines" of the M a little more vertical

**Comment by MisterY** [comment]
I've also added some comments in the issue in the Android repo, reiterating the point from @snarchio.

**Comment by vomikan** [comment]
FYI 
Here is a separate repository for any kind of pictures.
https://github.com/moneymanagerex/Art

**Comment by Tobaloidee** [comment]
Hello Sirs, I'm glad that you liked my design. I'm going to edit and take account your valuable suggestions. I'll make an issue in the Art repo and attached my links there as Sir @vomikan instructed. 
Thanks so much!

**Comment by Tobaloidee** [comment]
Just finished the editing Sir.. I made an issue in the Art repo and put the links there. Thanks!

**Comment by slodki** [comment]
Please continue discussion at moneymanagerex/Art#1
