### ISSUE TITLE
OK button in Relocate Category Dialog not grayed out

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1497]
OK button should be inactive and grayed out while both categories are not selected by user or have the same value.

Now it's always active and clickable but do nothing if both categories are not selected.
OK button should be inactive if user select the same category as source and designation too.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/38883617-2a2d87ce-4276-11e8-972e-e81d7c819d5e.png)
