### ISSUE TITLE
Seg fault  GA request details

### ISSUE THREAD

**Issue by nishantdawar2009** [moneymanagerex/moneymanagerex#1506]
today i launch the mmex but it was crashed with following error in terminal

moto@moto:~$ mmex
http://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-51521761-6&cid=gtk_20180322163904548&dp=/dialog&dt=Debug%20report%20%22mmex%22&sr=1920x1080&sd=24-bits&an=MoneyManagerEx&av=1.4.0-Alpha.3&cd1=gtk&plt=0
User-Agent: Linux 4.13.0-37-generic x86_64

Segmentation fault (core dumped)

**Comment by vomikan** [comment]
Try to delete ~/.mmex/mmexini.db3

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1144

**Comment by vomikan** [comment]
Here https://github.com/moneymanagerex/moneymanagerex/releases is macos-mmex-1.4.0-ALPHA-3.dmg file available. This issue possible fixed.

**Comment by slodki** [comment]
But @nishantdawar2009 uses alpha3 already. Please test one of Mac packages from https://github.com/slodki/moneymanagerex/releases/tag/test2
