### ISSUE TITLE
Money Manager EX will not install on Ubuntu 17.10

### ISSUE THREAD

**Issue by erica1963** [moneymanagerex/moneymanagerex#1507]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by erica1963** [comment]
Money Manager EX will not install on Ubuntu 17.10

**Comment by vomikan** [comment]
What version are you trying to install?
Did you tryed nightly build?
https://github.com/slodki/moneymanagere ... /tag

**Comment by erica1963** [comment]
I downloaded the latest stable release, searched all over the net on how to install the program, even ran the commands on their site, went looking for the installer, and nothing. This should be a straight forward process, not a process that takes literally days to figure out.

**Comment by slodki** [comment]
Installation instructions are in the [INSTALL](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md#linux) file.

MMEX doesn't work on Ubuntu >=17.10. There is no support for wx webview. For details see #1331.
