### ISSUE TITLE
import: please add "localization" option for numbers

### ISSUE THREAD

**Issue by giorgiobeggiora** [moneymanagerex/moneymanagerex#1517]
As in the title, please add this option. In example, in Italy we use "," as decimals separator, and "." as thousands separator. Thanks.

**Comment by vomikan** [comment]
@giorgiobeggiora, just change base currency settings.

**Comment by slodki** [comment]
@giorgiobeggiora What is the format of imported data? QIF, CVS?
QIF forces to use dot as decimal point.
For CVS there is #1122, with more examples for this issue.
@vomikan why it's closed? - multiple users report this as error!
