### ISSUE TITLE
Some currency names cannot be translated

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1528]
ISK, NIO, STD, VEF names are not marked for translation and cannot be displayed in user selected language.

**Comment by stef145g** [comment]
#1531 has been created to test this translation issue. The names contain UTF-8 characters in the names and there were not translated for a reason. Please test before accepting this PR as this may cause other issues.

**Comment by slodki** [comment]
@stef145g Please look at moneymanagerex/database@c7f3114606d289313919bb3fe376952327da65f2 and moneymanagerex/database@81227d73453dbcb129a52934096c35b3ca22f3fe
Global solution for this issue and moneymanagerex/database#20

**Comment by stef145g** [comment]
@slodki I had a look at database and found an error. Duplicate entry hs now been commented out.
Also sqlite2cpp has been modified to accommodate translation of Unicode names as well and added to existing PR. Please review

**Comment by slodki** [comment]
I've tested on Linux and Windows and this is enough to use `wxTRANSLATE(L"unicode string")` and this will work without problems. I cannot reproduce #739 with current wxWidgets and our CI toolchain (no `#pragma execution_character_set("utf-8")`required).

You can test with [windows binaries](https://ci.appveyor.com/project/slodki/moneymanagerex/build/1439) yourself from my [test-utf8-translation](https://github.com/slodki/moneymanagerex/commits/test-utf8-translation) branch. *Venezuelan Bolívar* is translated into Polish, and *Icelandic króna*, *Nicaraguan córdoba*, *São Tomé and Príncipe dobra* are left without translation and are displayed correctly in Linux, Windows, English or Polish translation.

**Comment by vomikan** [comment]
@slodki no problems with this release
![currecy](https://user-images.githubusercontent.com/6836805/38437062-0157db14-39df-11e8-8cd4-63ac1c0071b6.png)
