### ISSUE TITLE
Background is not drawn correctly

### ISSUE THREAD

**Issue by linwaytin** [moneymanagerex/moneymanagerex#1529]
My OS is Manjaro Linux, which is a Arch Linux based distribution. The version of MMEX is 1.3.3.

The problem is the background. It seems that it's not redrawn, as shown in the images. This may be due to the wxgtk toolkit on linux. 
![screenshot_20180331_151202](https://user-images.githubusercontent.com/12767902/38167191-e27bf8a2-34f6-11e8-94de-99e7ab639a2a.png)
![screenshot_20180331_151309](https://user-images.githubusercontent.com/12767902/38167195-ecaeb6a2-34f6-11e8-8c8b-27f053cf6ccb.png)

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
Could you test different app using wxgtk library?
Please post your gtk+ and wxgtk installed package versions?

**Comment by linwaytin** [comment]
My gtk is **3.22.28**, and wxgtk is **3.0.4**.

I have another wxgtk app. It has the same problem, so I guess this should be the library's problem.

**Comment by linwaytin** [comment]
It seems that this bug has been reported before.
https://bugzilla.redhat.com/show_bug.cgi?id=1393847
According to this webpage, the problem seems to have been fixed.

**Comment by slodki** [comment]
But it was fixed in wxgtk ~3.0.2 (2016) and you are using latest version 3.0.4.
I think it's  different bug, but not MMEX related.

**Comment by linwaytin** [comment]
The bug is gone on my computer, after upgrading yesterday. I guess it's due to the upgrade of gtk libraries. 

The following is from my 
>[2018-04-14 14:12] [ALPM] upgraded gtk-update-icon-cache (3.22.28-1 -> 3.22.29+86+gd92df4ff2c-1)
>[2018-04-14 14:13] [ALPM] upgraded breeze-gtk (5.12.3-1 -> 5.12.4-1)
>[2018-04-14 14:15] [ALPM] upgraded gtk3 (3.22.28-1 -> 3.22.29+86+gd92df4ff2c-1)
>[2018-04-14 14:15] [ALPM] upgraded gtk-doc (1.27-1 -> 1.28-1)
>[2018-04-14 14:15] [ALPM] upgraded gtksourceview3 (3.24.6-1 -> 3.24.7-1)
>[2018-04-14 14:16] [ALPM] upgraded kde-gtk-config (5.12.3-1 -> 5.12.4-1)
>[2018-04-14 14:17] [ALPM] upgraded lib32-gtk3 (3.22.26-1 -> 3.22.29+60+ge42d8598ca-1)
>[2018-04-14 14:21] [ALPM] upgraded webkit2gtk (2.18.6-1 -> 2.20.1-1)`
