### ISSUE TITLE
Diff. column in currency dialog always empty

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1536]
It doesn't matter if history was manually entered or downloaded - this column is always empty.
It should display something (?) or be removed.

<hr><small><b>Version</b>: 1.4.0-Alpha.3 • db 7 • git 304a8c27 (2018-04-08) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 3.5.9 (SQLite 3.22.0) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.55.1 • OpenSSL 1.0.2g • zlib 1.2.11 • libidn2 2.0.2 • libpsl 0.18.0 • ( libidn2 2.0.2) • librtmp 2.3<br><b>Build</b>: Apr 9 2018 22:34:07 • CMake 3.9.1 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.2.0 • Ubuntu 17.10 'artful'<br><b>OS</b>: Ubuntu 17.10 "artful" • Linux 4.13.0-38-generic x86_64 • KDE Polish (UTF-8) • 1280x1024 24bit 96x96ppi</small>

**Comment by slodki** [comment]
Any idea what should be displayed there?

**Comment by vomikan** [comment]
- Open amount - closed amount.
- Amount - (transfer amount  from / to amount)
