### ISSUE TITLE
Wrong transaction amount when split is used

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1539]
1. Create new database with PLN as base currency
2. Create checking account (in PLN)
3. Add split transaction with fractions of PLN
See attached database with 1 account and 1 split transaction.
[test.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/1892229/test.mmb.zip)
4. Account balance and transaction total amount is truncated to integer value
5. Split details show correct values and sum

When MMEX is running under Polish locale (`LC_ALL=pl_PL.UTF-8 mmex`):
![mmex-err-pl](https://user-images.githubusercontent.com/3155552/38527413-e7efea08-3c5a-11e8-8d7b-85bdd3cb3f43.png)

When MMEX is running under no locale (aka C locale, `LC_ALL=C mmex`):
![mmex-err-c](https://user-images.githubusercontent.com/3155552/38527417-eeb5305a-3c5a-11e8-8c02-6929f5dea73c.png)

This is #1150 (and #1153 ?)related IMHO.

<hr><small><b>Version</b>: 1.4.0-Alpha.3 • db 7 • git 304a8c27 (2018-04-08) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 3.5.9 (SQLite 3.22.0) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.55.1 • OpenSSL 1.0.2g • zlib 1.2.11 • libidn2 2.0.2 • libpsl 0.18.0 • ( libidn2 2.0.2) • librtmp 2.3<br><b>Build</b>: Apr 9 2018 22:34:07 • CMake 3.9.1 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.2.0 • Ubuntu 17.10 'artful'<br><b>OS</b>: Ubuntu 17.10 "artful" • Linux 4.13.0-38-generic x86_64 • KDE Polish (UTF-8) • 1280x1024 24bit 96x96ppi</small>

**Comment by vomikan** [comment]
@slodki I am using current master. I can't open your test.mmb file

![image](https://user-images.githubusercontent.com/6836805/38550784-161fcbd6-3cc0-11e8-9676-b5eff43e0a8a.png)

**Comment by slodki** [comment]
@vomikan I know nothing about db version 8 - I suppose you are using some experimental build of your own code?

**Comment by vomikan** [comment]
@slodki here it is
https://github.com/moneymanagerex/database/blob/master/database_version_8.sql
But I am not using it.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/38851232-8dfdcbdc-421d-11e8-856e-70c04efe0d31.png)
I can reproduce it on Windows

**Comment by vomikan** [comment]
Seems this changes made this effect:
https://github.com/moneymanagerex/moneymanagerex/commit/ff8e4488a12447f01eca17d4f5768ba66d4b2b29#diff-7e62e71d1dc93c7390fad08325f4d31e

Now calculations does not working in case if any decimal separator used.
For example:
2.2+2.2=2
2,2+2,2=2
But:
2+2=4

**Comment by vomikan** [comment]
If I revert default locale to English calculator start working and split amount became valid
 ```m_locale(wxLANGUAGE_ENGLISH)```

**Comment by vomikan** [comment]
@slodki could you test if ```m_locale(wxLANGUAGE_ENGLISH)``` works?

**Comment by slodki** [comment]
I think this could be [lua related](http://lua-users.org/wiki/LuaLocales) problem...
