### ISSUE TITLE
MMEX crash after update to RapidJSON

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/moneymanagerex#1542]
Your OS:
- X Mac OSX

MMEX version:

- X development version (git master branch)

Hello,
since a few days, MMEX crash at startup with my database. This crash seems to have appeared after the update to RapidJSON. Since then, I have updated MMEX from git master and it still crash. Using the MMEX alpha from github release (v1.4.0-alpha.3) works. 
If I create a new database from MMEX git master, the MMEX (master) works as expected. However, if I create a new database using MMEX v1.4.0-alpha.3, mmex from master crashes. 

Launching from the command line yields the error message: 

    Assertion failed: (false), function operator[], file /Users/xraynaud/GitHub/moneymanagerex/3rd/rapidjson/include/rapidjson/document.h, line 1117.
    Abort trap: 6

Thank you very much for your help.

**Comment by xraynaud** [comment]
I'm answering my own problem. The problem arise due to entries in INFOTABLE_V1. In the database created using v1.4.0-alpha.3, there is a bunch of entries names REPORT_X containing 
   {
    	    "REPORTPERIOD" : 0,
	    "DATE1" : "2018-04-10",
	    "DATE2" : "2018-04-10",
	    "ACCOUNTSELECTION" : 0,
 	    "NAMECOUNT" : 0,
	    "CHART" : 0
    }

These entries are not in the database created using master. Removing them makes possible to open in master the db created with v1.4.0-alpha.3 

I have no clues what these entries are.

**Comment by slodki** [comment]
412ced85055cf55197efa0d2cdd8fd6afbfe624f ?
