### ISSUE TITLE
Budget Estimate with Bi-Monhtly Category is Wrong

### ISSUE THREAD

**Issue by MrMontana1889** [moneymanagerex/moneymanagerex#1549]
Open an MMEX database
Create or edit an existing budget
Edit any category i.e. Income -> Salary
Set the type to Income
Set the frequency to Bi-Monthly
Set the value to 1000
Click OK

"Bi-Monthly" is typically defined as being paid 2x a month - the 15th and last business day (most common).  When you setup the budget using these settings the Estimated value is calculated as $500 (which is $1000 / 2) instead of $2000 (which is $1000 * 2).  This throws off the entire budget as the estimated income is now 1/2 of what is expected.

For an annual budget, the estimated should be Amount * 24 (2x/Month is 12 * 2 = 24)

<hr><small><b>Version</b>: 1.4.0-Alpha.3 • db 7 • git 670237c7 (2018-04-12) master<br><b>Libs</b>: wxWidgets 3.1.2 (wxMSW 10.0) • wxSQLite3 3.5.9 (SQLite 3.22.0) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.59.0 • WinSSL<br><b>Build</b>: Apr 13 2018 07:00:15 • CMake 3.10.18011902-MSVC_2 • MSBuild 15.6.85.37198 • gettext 0.19.8.1 • Microsoft Visual Studio 15.0 • Microsoft Visual C   19.13.26131.1 • Windows SDK 10.0.16299.0<br><b>OS</b>: Windows 10 (build 16299), 64-bit edition • English (U.S.) (windows-1252) • 1920x1080 32bit 102x102ppi</small>

**Comment by vomikan** [comment]
```
    else if (repeatsType == REPEAT_BI_WEEKLY)
        dt = dt.Add(wxTimeSpan::Weeks(2));
    else if (repeatsType == REPEAT_MONTHLY)
        dt = dt.Add(wxDateSpan::Month());
    else if (repeatsType == REPEAT_BI_MONTHLY)
        dt = dt.Add(wxDateSpan::Months(2));
```

**Comment by MrMontana1889** [comment]
Hi Vomikan,

In Quicken, the dialog looks like this when setting up bi-monthly (a.k.a. Twice a Month):

![twice a month bill setup quicken](https://user-images.githubusercontent.com/17349904/38879463-65be64b0-4231-11e8-9e51-4a4fa513e6b1.png)

Perhaps in MoneyManagerEx, the UI should be updated to work in a similar fashion?

Based on some quick searches, bi-monthly can mean either "every 2 months" or "twice a month" but based on one of the references the latter is rarely used for this term.  Another label for it is "semi-monthly".

So in MMEX, either it needs a new repeat period of Twice per Month where the two dates are specified or fix the existing logic to treat Bi-Monthly as Twice per Month.

It seems like having a new option is best as some users may need a "true" bi-monthly repeat option.

Kris (MrMontana1889)

**Comment by vomikan** [comment]
I cant change this dt.Add(wxDateSpan::Months(2) to dt.Add(wxDateSpan::Months(0.5);
Seems in that case the labels should be changed to "Every Two Weeks" and "Everry 2 Months"

**Comment by whalley** [comment]
Agree, this can be fixed by label wording in the . po files. I'll make changes to the GB/US files. Other translations if need needed to be picked up via crowdin.

**Comment by whalley** [comment]
Actually the recurring transactions (BillDeposits) already used "Fortnightly" for Bi-Weekly, which is good. So have used that for the budgeting. Have amended both recurring transaction and budgeting to use "Every 2 months" for Bi-Monthly.

**Comment by 2BeeOrNot** [comment]
The ambiguity of "bi".

The OP originally stated that bimonthly is defined as 2x a month (more commonly semimonthly). They subsequently acknowledged it is more commonly used to mean every 2 months. But it can go either way. You are changing "Bi-Monthly" to "Every 2 Months". That's good - like defining it mathematically. No ambiguity.

Same for biweekly. Does that mean twice a week or every two weeks. More commonly used to mean every other week but it too can go either way. So why go with "Fortnightly"? On the other side of the pond this Old English term is rarely used. Why not change "Bi-Weekly" to "Every 2 Weeks"?

"Every 2 Months" and "Every 2 Weeks". Simple. No ambiguity. No "isn't that a game?"

My thoughts on this change.

**Comment by whalley** [comment]
Point accepted. As we already have "Fortnightly" defined and in-use elsewhere  (i.e. recurring transactions) I have used that. But in order to satisfy our cousins across the pond I have mapped this to "Every 2 weeks" in the en_US.po file.
