### ISSUE TITLE
Edit Multiple Transactions at Once

### ISSUE THREAD

**Issue by ldsands** [moneymanagerex/moneymanagerex#1550]
Enhancement Request. I have been using R to doing budgeting but I would like to use something easier. I really like what you guys have however one issue that I find while importing everything into your application I find that I cannot change the category for multiple transactions. This is pretty much essential while importing a year worth of transactions. I know I can set the default for future imports but that doesn't help for transactions already imported. I think it would also be useful to change the Payee name as well many at a time to more understandable names. Thank you for your work on this application I do really like it.

Your OS:
- [X] Windows

MMEX version:
- [X] 1.3.x

**Comment by slodki** [comment]
You can select multiple rows with Shift key then click edit button in 1.4.x version of MMEX - see #909 for details
