### ISSUE TITLE
Build instructions need an update after PR #1547

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1553]
Do Build instructions need an Update after "chore(wxsqlite3): update wxsqlite3 to v4.0.2 and sqlite3 to v3.23.1 "

On Windows 10/Visual Studio, following command..
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=D:\Projects\curl-7.59.0 ..

gives the following error...

-- Found CURL: D:/Projects/curl-7.59.0/lib/libcurl.lib (found version "7.59.0")
-- Tuning for Visual Studio IDE
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at 3rd/CMakeLists.txt:184 (TARGET_COMPILE_FEATURES):
  TARGET_COMPILE_FEATURES no known features for C compiler  <------
  "MSVC"
  version 19.13.26131.1.
-- Found Gettext: C:/Program Files/gettext-iconv/bin/msgmerge.exe (found version "0.19.8.1")

I guess I have to run "util/MSVC-C.cmake.patch" before running CMake ?

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by grumpy235** [comment]
Another change that might be needed, currently in BUILD.md we have..
cd "%DevEnvDir%CommonExtensions\Microsoft\CMake\CMake\share\cmake-**3.8**\Modules"

But my installation has cmake-3.10 with a fully patched VS2017

**Comment by grumpy235** [comment]
So I have now run the patch file using the modified instructions and an authorised command prompt. 
MVSC-C.cmake now exists in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\share\cmake-3.10\Modules\Compiler

Still getting the same error though

**Comment by slodki** [comment]
We cannot follow every Microsoft patch in VS distribution...

**Comment by slodki** [comment]
@grumpy235 Please compare [cmake log](https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/338/job/qptrd26hf527wlho#L123) before patch:
```
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```
and [cmake log](https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/351/job/ph6onan5np4s1apu#L124) after patch:
```
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```
Using CMake 3.11

**Comment by grumpy235** [comment]
**@slodki** Found an easier solution, simply commented out the offending line(184) in 3rd/CmakeLists.txt and everything builds just fine.

**Comment by slodki** [comment]
wxSQLite3 has already workaround for MSVC in utelle/wxsqlite3@3a242680d23e5cbd1400ef70f43cf145a607b8be
