### ISSUE TITLE
Use .mmb extension for both normal and encrypted databases

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1570]
We can auto-detect if password is required to open database file and ask user when needed.

This change will allow on-the-fly encryption/decryption of opened database without need to close it, rename file and checking if similar file with matching extension is not blocking file rename.

**Comment by slodki** [comment]
PR #1573 is ready for validation

**Comment by vomikan** [comment]
This Db encrypted in previous release. Password is: '1'

[test_enqrypt.zip](https://github.com/moneymanagerex/moneymanagerex/files/1933133/test_enqrypt.zip)

I can't open it after this commit.

**Comment by slodki** [comment]
I forgot set previous codec and used newer one.
