### ISSUE TITLE
Better icon for show/hide custom fields in transaction dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1590]
My proposal: use 2 icons depending on right panel (with custom fields) state `>>` and `<<`.

**Comment by vomikan** [comment]
<img src="https://openclipart.org/image/32px/svg_to_png/170475/simplearrow.png&disposition=attachment" alt="Arrow - simple" title="Arrow - simple by  diamonjohn ( https://openclipart.org/user-detail/diamonjohn )" />

<img src="https://openclipart.org/image/32px/svg_to_png/2210/kuba-arrow-button-set-2.png&disposition=attachment" alt="arrow-button-set" title="arrow-button-set by  kuba ( https://openclipart.org/user-detail/kuba )" />

**Comment by slodki** [comment]
This icon will be placed on the button so 1st is better - there will be frame around from the button. The 2nd proposal will render as circle in a rectangle...

**Comment by vomikan** [comment]
It's possible to use bitmap not button.

**Comment by vomikan** [comment]
[simplearrow_left.zip]

(https://github.com/moneymanagerex/moneymanagerex/files/1963594/simplearrow_left.zip)

**Comment by vomikan** [comment]
[simplearrow_left.zip](https://github.com/moneymanagerex/moneymanagerex/files/1963596/simplearrow_left.zip)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/39473576-33034c52-4d58-11e8-9ed2-86d3dec7f904.png)
