### ISSUE TITLE
mysterious not working button in transaction dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1591]
1. Create new database with checking account
2. Click new transaction toolbar icon
3. Try to click on button marked below
4. There is no description (tooltip) for this button, clicking on it do nothing

We should add better icon and tooltip for frequent note selection button. And even disable it if there are no notes to select.

**Comment by slodki** [comment]
I forgot attachment... 😁

**Comment by slodki** [comment]
![mmex10](https://user-images.githubusercontent.com/3155552/39194341-cd3123ba-47dd-11e8-971a-c57d80373630.png)
![mmex11](https://user-images.githubusercontent.com/3155552/39194355-d1df1520-47dd-11e8-9dc5-0531aa90f595.png)

**Comment by vomikan** [comment]
There are no transactions in DB. Therefore no notes. Nothing to use.

**Comment by slodki** [comment]
That's true. But user don't know this and don't know why this button is not working.
We should:
- disable this button if there are no notes to select
- change icon to something related to "note template selection"
- add missing tooltip with button function description

**Comment by slodki** [comment]
#1298
