### ISSUE TITLE
SourceForge overwrites release description at GitHub Releases

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1611]
Manually prepared release description is overwritten with:
```markdown
[![Download Money Manager Ex](https://a.fsdn.com/con/app/sf-download-button)](https://sourceforge.net/projects/moneymanagerex/files/v1.4.0-alpha.4/v1.4.0-alpha.4.zip/download)
```

**Comment by gabriele-v** [comment]
Probably I've understood where it comes from, but I'm not admin of GitHub MMEX repository.
@vomikan or @guanlisheng could you check if there is some sourceforge webhook or make my user admin so I can try to fix it?

**Comment by gabriele-v** [comment]
@slodki I've contacted Sourceforge support, they are asking me if you have created it via web or API and if you have issued a draft before final release or immediately definitive release.
Thanks

**Comment by gabriele-v** [comment]
I've access to SourcForge MMEX as admin and integration seems active and fine from configuration.

**Comment by slodki** [comment]
I have tagged commit using git, then CI created release at GitHub, I've manually edited description from web, then CI added more files to it. After some time old release description was overwritten by SF icon.

**Comment by slodki** [comment]
They should ADD their content and not overwrite existing one.
BTW this badge is really stupid - it links to random (?) binary file. Can we turn this "feature" off for mmex repo?

**Comment by gabriele-v** [comment]
They told me that they are already adding at the end, but there are some "race conditions" with CI that could cause this problem.
We need integration active in order to have automatically uploaded releases also on SF page.

**Comment by slodki** [comment]
But the "automatic upload of releases" on SF is not working. Please look at:
https://sourceforge.net/projects/moneymanagerex/files/v1.4.0-alpha.3/
https://sourceforge.net/projects/moneymanagerex/files/v1.4.0-alpha.4/
https://sourceforge.net/projects/moneymanagerex/files/nightly/

**Comment by gabriele-v** [comment]
SF wrote me that should be fixed now, but anyway they told that integration works just for first pubblication and not for consecutive updates of a release, so we should issue release when everything it's ready.

**Comment by slodki** [comment]
But GitHub Releases have more features like drafts, pre-releases, final releases. And they can be edited, have multiple attachments etc. - SF doesn't support all GH features IMHO.
