### ISSUE TITLE
“Transaction Reports” filter window

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1613]
https://forum.moneymanagerex.org/viewtopic.php?t=7479

In the “Transaction Reports” filter window, at the bottom there is a series of buttons [1,9], just below the text field box.
I use this facility quite often - especially when I have forgotten where I put what in what account, but leaving the button on “1”.

Can you say how these are supposed to be used? I cannot find any guidance in the Documentation and after some experimentation I have not (yet) had any success.

Regards

**Comment by slodki** [comment]
Duplicate of #1298?
