### ISSUE TITLE
Publish nightly builds for testers

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1614]
Our CI infrastructure is ready for this. We have Windows binaries available for users already as AppVeyor artifacts. We should publish nightly (or even every commit) builds for Linux and Mac too.

**Comment by MartinX3** [comment]
I will test the Linux Ubuntu Bionic builds on productivity base. :D

**Comment by slodki** [comment]
1st proposal:
* separate packagecloud repo with *nightly* name
* every successful Travis CI build (not tagged) will be pushed to it
* files will be overwritten with the same name/version - package build will be always 1

To test:
- [ ] possibility to push files with the same name to packagecloud - there was "filename already exists" earlier
- [ ] test packagecloud repo with `apt install --reinstall mmex` command (upgrade will not work with the same package version)

**Comment by MartinX3** [comment]
@slodki 

> possibility to push files with the same name to packagecloud - there was "filename already exists" earlier

Why not using a combination of date and time of build with the version number together in the filename and in the debian package version number?
So I see when it was build and put this information easily in the bug report.
And you won't get this error message.

**Comment by slodki** [comment]
All build details are avaiable in about dialog in mmex.

**Comment by slodki** [comment]
Because of travis-ci/dpl#812 nightly builds will be deployed to GitHub Releases under special release name *nightly*.
Travis CI cron will be responsible for triggering nightly build by tagging latest commit on master branch with *nightly* tag. PR #1622

**Comment by MartinX3** [comment]
So there will be no new automatically uploaded packagecloud packages?

**Comment by slodki** [comment]
Nightly build are to dangerous to auto upgrade. I think manual download should be enough now.

**Comment by MartinX3** [comment]
When I use the nightly builds, will I get a notification, when a new nightly build is available or how can I receive this information automatically?

**Comment by slodki** [comment]
It's simple - nightly build is available... every night :-)

**Comment by MartinX3** [comment]
Hihi, I will test them as often as I use MMEX regularly :)

**Comment by slodki** [comment]
Please remember - nightly builds will crash, delete records from your database, change your system settings, change LCD colors, eat paper from printer and dig holes in your harddisk...

Please wait till tomorrow - you will see them at [Releases](https://github.com/moneymanagerex/moneymanagerex/releases) page.

**Comment by vomikan** [comment]
>nightly builds will crash, delete records from your database, change your system settings, change LCD colors, eat paper from printer and dig holes in your harddisk...

That is not true. 
Some pepple so sereous that dont understand jokes.

**Comment by MartinX3** [comment]
@vomikan But it ate my paper! :sob:

**Comment by slodki** [comment]
They shouldn't try to use nightly builds. Seriously.
Or remove paper from printer before running nightly build from floppy disk on computer with old CRT monitor.

**Comment by vomikan** [comment]
@MartinX3 please create new case. This is sereous bug.
It should be investigated. Msy be it was Friday 13 or fool moon?
Possible solution is do not build nightly release at that nights.

**Comment by MartinX3** [comment]
@vomikan why is my printer bleeding?
What have you done? 😱

**Comment by slodki** [comment]
appveyor/ci#2319

**Comment by slodki** [comment]
travis-ci/dpl#816

**Comment by slodki** [comment]
travis-ci/dpl#821

**Comment by whalley** [comment]
Regular MacOS builds can be found here: https://mmex.ipx.co.uk/ until we get Travis builds working again

**Comment by whalley** [comment]
Closing as this should now be tracked against the CircleCI builds that are regularly being built.
https://github.com/moneymanagerex/moneymanagerex/issues/4880
