### ISSUE TITLE
Save As not update recent files list

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1620]
Exported database file is opened in MMEX after successful saving but not available from recent files submenu.

**Comment by scilganon** [comment]
it works **as expected**

---

if i understand correctly, case is following:

1. open existed database
2. file -> save as
3. enter name
4. press save

then mmex opens newly created file, and "recent files"-list gets new record of opened file

```
➜  moneymanagerex git:(master) ✗ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

```
mmex: 1.3.3, db v.7
```

**Comment by gabriele-v** [comment]
Confirm fixed
