### ISSUE TITLE
Delete outdated mmex project at Launchpad

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1623]
https://launchpad.net/mmex:
![mmex2](https://user-images.githubusercontent.com/3155552/39586809-480516ac-4ef8-11e8-9031-a32f4943297c.png)
![mmex1](https://user-images.githubusercontent.com/3155552/39586800-4234e392-4ef8-11e8-8ba9-dc5492489180.png)

**Comment by danilolutz** [comment]
How or where can i help with portuguese brazilian translation?

**Comment by slodki** [comment]
1st option - only web browser file editor required: navigate to [po directory at GitHub](https://github.com/moneymanagerex/moneymanagerex/tree/master/po), display the right file (pt_BR.po in your case), click "Edit this file" pencil icon at upper right corner and fix translation strings (after msgstr). Please remember: "# fuzzy" comment above string means guessed, wrong translation in most cases - should be verified and corrected; "# c-format" marks strings where %X markers must be preserved.
**Risk**: .po files can be outdated and not aligned with current MMEX version, you can waste your time translating them. There is `"POT-Creation-Date: 2018-04-30 17:00+0200\n"` in the file header containing last synchronization date.
After translation save changes using "Propose file change" button.

2nd option: regenerate .po file before translation using [update-po-files.sh script](https://github.com/moneymanagerex/moneymanagerex/blob/master/util/update-po-files.sh) executed under linux/cygwin environment against git repo cloned sources. gettext tools required. Then use any text file to translate .po file and use "Upload files" command in GitHub interface (inside po directory) to send translated file to GitHub.

MMEX developers will verify updated file structure and include it in next MMEX version. If you have gettext tools available you can compile binary version of .po file (using `msgfmt` command) and replace original file from installed MMEX to use your own translation.

**Comment by slodki** [comment]
@danilolutz We have two Portuguese brazilian translations in `pt_BR.po` and `portuguese_br.po.2nd`. Could you select the one we should update/use? Or maybe consolidate them into one?

**Comment by slodki** [comment]
See #1345 issue too

**Comment by danilolutz** [comment]
The `portuguese_br.po.2nd` looks more complete, but i should probably wait for transifex. I think this way i don't waste work and time.

**Comment by slodki** [comment]
https://translations.launchpad.net/mmex is still active and should be deleted:

![screenshot](https://user-images.githubusercontent.com/3155552/52170985-d7a28800-2754-11e9-8889-c7c748ccf61d.png)

**Comment by vomikan** [comment]
It's stupid situation, but I don't know how to delete the project. I am owner but interface dies not provide intuitive way to delete it.
