### ISSUE TITLE
Yearly Accounts Balance Report - wrong today's value

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1625]
1. One account with transactions:
![mmex1](https://user-images.githubusercontent.com/3155552/39606259-d6283518-4f34-11e8-9602-45757de38b07.png)

2. Monthly Accounts Balance Report doesn't show any future values, the last is "today" and it's OK:
![mmex2](https://user-images.githubusercontent.com/3155552/39606267-e0720044-4f34-11e8-9f83-83012f1122b2.png)

3. Yearly Accounts Balance Report shows future value (end of current year) but "today" values are wrong:
![mmex3](https://user-images.githubusercontent.com/3155552/39606271-e4ca54e8-4f34-11e8-9504-a385433642c1.png)

[test.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/1972893/test.mmb.zip)

<hr><small><b>Version</b>: 1.4.0-Alpha.4 • db 10 (aes128cbc) • git 08193284 (2018-05-03) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 4.0.2 (SQLite 3.23.1) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.58.0 • OpenSSL 1.1.0g • zlib 1.2.11 • libidn2 2.0.4 • libpsl 0.19.1 • ( libidn2 2.0.4) • nghttp2 1.30.0 • librtmp 2.3<br><b>Build</b>: May 3 2018 17:00:58 • CMake 3.10.2 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.3.0 • Ubuntu 18.04 'bionic'<br><b>OS</b>: Ubuntu 18.04 LTS "bionic" • Linux 4.15.0-20-generic x86_64 • KDE Polish (UTF-8) • 1280x1024 24bit 96x96ppi</small>

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/1657/commits/77ec25c74e4d1dd6e516db8a39dd22ee1bd25308
