### ISSUE TITLE
Custom Fields Data storing

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1634]
We have Custom Fields different types templates stored in CUSTOMFIELD_V1 table.
And details that stored in CUSTOMFIELDDATA_V1. 
There are some fields to implement this functionality:
```enum REFTYPE { TRANSACTION = 0, STOCK, ASSET, BANKACCOUNT, BILLSDEPOSIT, PAYEE};```
Now Custom Fields type 'TRANSACTION' used for Transaction Dialog and Transaction Filter dialog.
In future it may be implemented for Recurring Transactions Dialog.
 Transaction Filter dialog has 9 settings. Every transaction has ID and every Recurring Transactions has ID.
I can't save Transaction Filter settings because the same ID reserved for transactions.

Please advise.

![image](https://user-images.githubusercontent.com/6836805/39663740-5f2dd7da-5081-11e8-8b49-5b27ac53a118.png)

**Comment by gabriele-v** [comment]
You can simply add a new type (entity) in Model_Attachment::REFTYPE and Model_Attachment::REFTYPE_CHOICES for Transaction Filter and Recurring transactions.
That's the reason why I said that we should move them outside of Model_Attachment: Attachment it was the first feature needing these, but now that there are multiple functions, we should put the in a dedicate class

**Comment by gabriele-v** [comment]
Note: Recurring transaction it's already there, it's BILLSDEPOSIT

**Comment by gabriele-v** [comment]
Now that I've tested it I've found another problem in case of TransFilter / TransDialog:
custom fields types should be the same because you want to search for the same fields inserted in transactions, that's the only case in MMEX because actually only TransFilter exists, not AccountFilter I.E.

So when saving custom fields type (not data), only for TransDialog, the same record should be saved (and updated/deleted) for TransFilter. Then in customfielddata for TransFilter reftype you will have the id of the transfilter setting.

**Comment by vomikan** [comment]
@gabriele-v 
> the same record should be saved 

I think so but the code became too complex.

**Comment by slodki** [comment]
Using the same config data for X_dialog and X_filter makes easier to validate consistency when user remove custom field definition.

**Comment by gabriele-v** [comment]
@vomikan seems that "floppy icon" to save search it's disappeared too, how to save settings?

**Comment by vomikan** [comment]
Floppy icon was created by me. Then someone has removed it. 
I liked flippy.

**Comment by gabriele-v** [comment]
So how I can save a new filter without the button?

**Comment by vomikan** [comment]
Just klick the 'Actuvate' button.

**Comment by gabriele-v** [comment]
I think that in some cases they are not saved. I'll try to reproduce.

**Comment by vomikan** [comment]
Regarding this issue I suggest to add one more field into CUSTOMFIELDDATA table.
For example: SUBFIELDID

![image](https://user-images.githubusercontent.com/6836805/39688936-980345ec-51dd-11e8-8653-9c35a3695011.png)

In that case Filter, Reccuring and Transaction Dialogues will have the same logic but all settings may be saved separatly.
Bingo.

**Comment by gabriele-v** [comment]
I not agree, in this case you will have both poor DB and code. DB side because you have an ID that it's unclear and code side because you still need to use some if during custom field save (in mmcustomdata that it's already quite complex).
IMHO the cleanest way it's to save/update/delete 2 more times the "transaction" custom fields as "Filter" and "Recurring", we will use the same if that will be used to save custom field data with SUBFIELDID but at least they are in a really easy cpp (customfieldeditdialog) and DB structure will remain very clear.

**Comment by gabriele-v** [comment]
Also, in your case when querying with GRM you need two where clausole on different tables:
`WHERE CUSTOMFIELD.REFTYPE = 'Transaction' AND CUSTOFIELDDATA.SUBFIELDID = 'xxx'`
instead of a single
`WHERE CUSTOMFIELD.REFTYPE = 'Transaction'`

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/155199761-c38555ed-8167-4078-8552-fe3f439b88be.png)

**Comment by vomikan** [comment]
What else needs to be done:
1) When changing the saved values - updating the dialog
2) Value comparison for multiselect field
3) Displaying UFC fields in the report

**Comment by whalley** [comment]
If I run a Transaction Report then switch back to a checking account view I get a crash
[crash.txt](https://github.com/moneymanagerex/moneymanagerex/files/8119796/crash.txt)
.

**Comment by vomikan** [comment]
> If I run a Transaction Report then switch back to a checking account view I get a crash [crash.txt](https://github.com/moneymanagerex/moneymanagerex/files/8119796/crash.txt) . Destructor issue?

I can't reproduce this issue but there is anothe one.
I case if checking account panel is avtive then a Transaction Report have been running
all custom fields settings became empty
![image](https://user-images.githubusercontent.com/6836805/155212722-b5655ae3-da4d-4653-b11b-5240721f9cac.png)
I think it because there are two   Transaction Report  instatses running.
I have an idea about this.

**Comment by vomikan** [comment]
Update
I can reproduce the bug
![image](https://user-images.githubusercontent.com/6836805/155213434-28923fd6-202d-4d76-bf68-f509ab21fd8e.png)

**Comment by vomikan** [comment]
What else needs to be done:

[] When changing the 'Settings' values - updating the dialog
[] Value comparison for multiselect field
[] Displaying UFC fields in the report
[] Clear all fields + UDFC

**Comment by vomikan** [comment]
I can't find a way to fix it. The code is quite confusing.

**Comment by whalley** [comment]
@vomikan I'll see if I can get some time to make sense of it... No promises :-)

**Comment by whalley** [comment]
@vomikan Not had chance to look in detail yet, but reverting the SharedPtr changes stops the crash. Was there some memory leak issues that pushed you to change this part of the code?
[git.diff.txt](https://github.com/moneymanagerex/moneymanagerex/files/8148650/git.diff.txt)

**Comment by vomikan** [comment]
These changes are not made to combat leakage. There is such a hidden problem: If you launch the application and click the Transaction Report, then close this window and repeat again, then there are two instances of this dialog in memory. I realized this when a search by the ID of the customized fields gave an incorrect result. Ie, there were windows, but not for the active window, but the one that is stored in memory.

**Comment by whalley** [comment]
@vomikan Yes, it is complicated and my head hurts a bit ... The attached changes, whilst not ideal, should at least help find the correct dialog. 
[git.diff.txt](https://github.com/moneymanagerex/moneymanagerex/files/8160011/git.diff.txt)

**Comment by vomikan** [comment]
@whalley I find your fix useful. Fixed problems with falling after editing a transaction from a report. Custom fields in Transaction report works ок when an account screen is open.

But :(  (I'll try to fix)
Detected memory leaks!
Dumping objects ->
{1724361} normal block at 0x000001F430B9DAF0, 9219 bytes long.
 Data: <           0    > FA FA FA FA FA FA FA FA F0 DA B9 30 F4 01 00 00 
{1719025} normal block at 0x000001F431040340, 16 bytes long.
 Data: <x {-            > 78 10 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1717665} normal block at 0x000001F431040FC0, 16 bytes long.
 Data: <   0            > 18 CC B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717664} normal block at 0x000001F4310408E0, 16 bytes long.
 Data: <   0            > D8 CB B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717663} normal block at 0x000001F431040F20, 16 bytes long.
 Data: <   0            > 98 CB B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717662} normal block at 0x000001F431040F70, 16 bytes long.
 Data: <X  0            > 58 CB B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717661} normal block at 0x000001F431040570, 16 bytes long.
 Data: <   0            > 18 CB B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717660} normal block at 0x000001F431040160, 16 bytes long.
 Data: <   0            > F8 CA B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717659} normal block at 0x000001F42D80F560, 32 bytes long.
 Data: <L e i s u r e : > 4C 00 65 00 69 00 73 00 75 00 72 00 65 00 3A 00 
{1717658} normal block at 0x000001F431040ED0, 16 bytes long.
 Data: <   0            > 88 CA B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717657} normal block at 0x000001F42D80EDE0, 32 bytes long.
 Data: <a b d u l   m a > 61 00 62 00 64 00 75 00 6C 00 20 00 6D 00 61 00 
{1717656} normal block at 0x000001F4310400C0, 16 bytes long.
 Data: <P  0            > 50 CA B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717655} normal block at 0x000001F431040390, 16 bytes long.
 Data: <   0            > 18 CA B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717654} normal block at 0x000001F43103FF80, 16 bytes long.
 Data: <   0            > E0 C9 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717653} normal block at 0x000001F42D80FCE0, 32 bytes long.
 Data: <2 0 2 1 - 1 2 - > 32 00 30 00 32 00 31 00 2D 00 31 00 32 00 2D 00 
{1717652} normal block at 0x000001F431040070, 16 bytes long.
 Data: <   0            > 98 C9 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717651} normal block at 0x000001F431040DE0, 16 bytes long.
 Data: <X  0            > 58 C9 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717650} normal block at 0x000001F431040CA0, 16 bytes long.
 Data: <   0            > 20 C9 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717649} normal block at 0x000001F431040890, 16 bytes long.
 Data: <   0            > E8 C8 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1717648} normal block at 0x000001F43103FDA0, 16 bytes long.
 Data: <   0            > A8 C8 B9 30 F4 01 00 00 00 00 00 00 00 00 00 00 
{1380860} normal block at 0x000001F430B9C890, 1936 bytes long.
 Data: < * *            > 10 2A A6 2A F7 7F 00 00 BE 00 00 00 04 00 00 00 
{1368692} normal block at 0x000001F430B7A780, 1 bytes long.
 Data: < > 00 
{1367944} normal block at 0x000001F42D76D3E0, 80 bytes long.
 Data: <R e p o r t   G > 52 00 65 00 70 00 6F 00 72 00 74 00 20 00 47 00 
{1367782} normal block at 0x000001F42D7C7540, 16 bytes long.
 Data: <  {-            > F0 10 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367781} normal block at 0x000001F42D7C7630, 16 bytes long.
 Data: <  {-            > B8 10 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367779} normal block at 0x000001F42D7C6CD0, 16 bytes long.
 Data: <P {-            > 50 10 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367778} normal block at 0x000001F42D7C6C80, 16 bytes long.
 Data: <  {-            > 18 10 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367773} normal block at 0x000001F42D757F40, 48 bytes long.
 Data: <T r a n s a c t > 54 00 72 00 61 00 6E 00 73 00 61 00 63 00 74 00 
{1367772} normal block at 0x000001F42D7C7B30, 16 bytes long.
 Data: <  {-            > C0 0F 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367771} normal block at 0x000001F42D7C6F00, 16 bytes long.
 Data: <  {-            > 98 0F 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367770} normal block at 0x000001F42D7C7900, 16 bytes long.
 Data: <x {-            > 78 0F 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367769} normal block at 0x000001F42D7C7950, 16 bytes long.
 Data: <  {-            > F8 0E 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367768} normal block at 0x000001F42D7C6EB0, 16 bytes long.
 Data: <  {-            > C0 0E 7B 2D F4 01 00 00 00 00 00 00 00 00 00 00 
{1367763} normal block at 0x000001F42D7B0EB0, 640 bytes long.
 Data: <  $*            > 90 DA 24 2A F7 7F 00 00 00 CD CD CD CD CD CD CD 
{1311125} normal block at 0x000001F42D8074C0, 24 bytes long.
 Data: <P  *     z_-    > 50 B8 0A 2A F7 7F 00 00 D0 7A 5F 2D F4 01 00 00 
Object dump complete.
The program '[18312] mmex.exe' has exited with code 0 (0x0).

**Comment by vomikan** [comment]
How to reproduce the memory leak:
1) After start mmex press press the funnel (Transaction Report)
2) Press OK to sort some data
3) Click the link for the transaction
4) Cancel
5) close the app

**Comment by vomikan** [comment]
What else needs to be done:

- [x] When changing the 'Settings' values - updating the dialog
- [ ] Value comparison for multiselect field
- [ ]  Displaying UFC fields in the report
- [ ]  Clear all fields + UDFC
