### ISSUE TITLE
Display custom item in transaction panel

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1664]
It's a part of #1585

**Comment by vomikan** [comment]
One more field needed. It should be string. Values: UDFC01, UDFC02, UDFC03 etc
![image](https://user-images.githubusercontent.com/6836805/40009373-7aeb32b2-57aa-11e8-8c82-955daf64e2f2.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/40009498-de030816-57aa-11e8-97d1-be19e58fd65a.png)

**Comment by vomikan** [comment]
#1628 should be fixed first

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/40233701-b70bb29e-5aac-11e8-9b05-622e34c65c7c.png)

**Comment by vomikan** [comment]
Test DB
[ttttt4.zip](https://github.com/moneymanagerex/moneymanagerex/files/2016746/ttttt4.zip)

**Comment by whalley** [comment]
This has already been fixed.
