### ISSUE TITLE
Source at 4bc41cb and V7 Database upgrade issue

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1667]
**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

Just a heads up on a possible V1.4.0 upgrade problem.
Compiled the source at 4bc41cb and then tried to open my V7 database expecting to get a successful upgrade message similar to when I upgraded to V13 with a previous level of master but got the following..
![capture](https://user-images.githubusercontent.com/24897056/40040206-2bd14cf4-5811-11e8-88a1-437f6584971c.JPG)

Not sure if the article in the Wiki applies as I did not get that far.

**Comment by grumpy235** [comment]
Just checked the user_version on my V7 database and it confirms as 7
** One thing I did notice is that the Version 13 code in DB_Upgrade.h has not had the user_version updated from 12 to 13 **

**Comment by slodki** [comment]
MMEX app will add it's own user_version pragma at the end of SQL from DB_Upgrade.h. Statement inside SQL is for creating/upgrading db files outside MMEX app.

**Comment by slodki** [comment]
It's my error: in db version 7 we must open ACCOUNTLIST_V1 not ACCOUNTLIST:
https://github.com/moneymanagerex/moneymanagerex/blob/4bc41cb5e3c00873bbf7b6d4a734c88b3bf8120e/src/dbupgrade.cpp#L35

**Comment by grumpy235** [comment]
That works for the conversion to V13 and box appears confirming the update.
wxWidgets then throws some Debug Alerts..
![capture1](https://user-images.githubusercontent.com/24897056/40051882-2ab4e286-5834-11e8-8305-b88bdfbbb5ba.JPG)
Once they have cleared then get..
![capture2](https://user-images.githubusercontent.com/24897056/40051902-3e5ac0e4-5834-11e8-9531-a597e4ce5f02.JPG)

**Comment by grumpy235** [comment]
Re-instated Gabriele-v changes to DB_Table.h and DB_Table_Currencyformats.h, re-compiled and all errors messages have been removed and Home Page is now populated.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1670
@grumpy235 how to fix?

**Comment by grumpy235** [comment]
My quick fix was to look at source of "fix(headers): add missing includes in header files" showing before and after data and simply eye-ball what was there. 
For example 
struct SorterByBASECONVRATE needs to be removed
BASECONVRATE needs removing from the odd SQL statement
The binds need changing as well etc.
I assume slodki will fix things when he next logs on

**Comment by slodki** [comment]
PR #1644 should include database submodule update.
After #1644 merging rebased #1666 removed some changes from DB_Table*.h files generated from database submodule...

**Comment by slodki** [comment]
wrong db spec from database submodule will be fixed in #1670
