### ISSUE TITLE
Improve transaction filter's preset selection GUI

### ISSUE THREAD

**Issue by EBiForE** [moneymanagerex/moneymanagerex#1675]
I tried to create my reports but it is not exactly easy as I thought, even if I could still do it
I have noticed that the reports on operations are easy and immediate, so I asked myself, is it possible to save them ?
The disappointing response was, no

The solution that I propose, precisely, is simple : to save as reports, also the reports on operations

The alternative would be to make it easier to create the reports, without writing the query, using simple filters

In a few words, I should be able to save the query or the operations done by this box so it can be recalled without having to set up again
![screenshot 2018-05-16 21 04 03](https://user-images.githubusercontent.com/39346742/40138339-b37e4eea-594c-11e8-9d0d-b8a0c45a5651.jpg)

**Comment by EBiForE** [comment]
Thanks for letting me know
In fact I did not understand that they were used
But so I have to remember the number of the filter or scroll them all until you find the one saved and 10 are few
It would be more useful to be able to save them as reports so you can start them with just one click and find them immediately thanks to the name

**Comment by gabriele-v** [comment]
First step (quite easy) could be to replace numbers with a combobox showing the name of the filter.
Your suggestion it's useful but it will involve some more coding changes.

**Comment by EBiForE** [comment]
I know, in fact I'm here to help you as I can, unfortunately I can not help you directly in the code myself, but I think that making filters easier to spread much more software, also the current filters are improved because for example you can not search the transactions to be monitored in all accounts
![screenshot 2018-05-18 14 38 05](https://user-images.githubusercontent.com/39346742/40235006-19d7bd40-5aa9-11e8-9aae-b196d701e11b.jpg)
This does not work, in fact it only looks for the first account, the item "all accounts" should be added to the list of accounts

**Comment by vomikan** [comment]
In case if "Conto" checkbox is unticked all accounts used for searching.

**Comment by EBiForE** [comment]
When i press "Activate" button it search only in my "Portafoglio" account
I have latest version i.e. 1.4.0-alpha1

**Comment by vomikan** [comment]
OK
I'll check this issue one more time and add diskette ico for saving search options.
PS If you want to start competition whose English is worst - welcome.I'll win becouse my English so bad that you even can't emagine.

**Comment by gabriele-v** [comment]
@vomikan I'm checking into settings is as combobox, is a feature that I've would to add because now checkboxes are not easy to understand. If I found something for accounts I'll let you know.

**Comment by vomikan** [comment]
I like idea one click report activation.

**Comment by vomikan** [comment]
I have an idea. If Date from - to would be redesigned like this:

![dates](https://user-images.githubusercontent.com/6836805/40268890-6da375a6-5b7e-11e8-8dc1-9487a64773e8.PNG)

all presets may be present in navigation panel

![image](https://user-images.githubusercontent.com/6836805/40268903-a964a5e2-5b7e-11e8-9787-51b998a667fe.png)

as subitems of "Transaction Report".

It may be good alternative of GRM

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/40988551-0ed34cda-68f4-11e8-91d4-bceb77a49de0.png)

**Comment by slodki** [comment]
The *Include Similar* label should be changes to something like *Include subcategories*. It is not clear to me what *similar* means and why this option is active if subcategory is already selected above.

There should be some warning maybe if user enter inconsistent data into *Type* and *Amount Range* fields like "deposit from -100 to -10".

**Comment by vomikan** [comment]
I think bettet to change it to "exclude subcategories".

**Comment by andrepg** [comment]
Hey, just no not open another issue (yet). Does anybody else have a problem with Date selector? For me, in Recurring Transactions, when using a date to filter my recurring, MMEX actually does not filter. 

Any other filters work, just date when using Recurring Transactions feature. It's expected?

**Comment by vomikan** [comment]
@andrepg this bug has been reported and fixed. Will be working  fine in next stable release

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/41088633-ae0f58ca-6a48-11e8-956a-669dd0b961d5.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/41145810-f0e567d6-6b09-11e8-87bd-19796f5f00d0.png)

**Comment by slodki** [comment]
@vomikan What about this?
![mmex-preset](https://user-images.githubusercontent.com/3155552/42127532-b6b78baa-7c9a-11e8-9ec9-a9d9127d7026.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3298
