### ISSUE TITLE
First debug run from fresh build tutorial fails: missing some wxWidgets DLLs

### ISSUE THREAD

**Issue by StefanRickli** [moneymanagerex/moneymanagerex#1676]
Hi, this is my first open source participation, so please bear with me.

I forked the current mmex repo into my account and followed the tutorial in BUILD.md (difference: mmex project is not in default directory) to get to a first build on my laptop.

I use Win10x64 German with VS Community GUI.

Building the project in VS works fine, it throws no apparent errors.

When I try to run the project, mmex.exe throws a series of similar error messages like the one on the screenshot.
![image](https://user-images.githubusercontent.com/19881323/40170320-68ef4f88-59c8-11e8-9477-8521cf3cc18f.png)

The affected files are

- `wxmsw30ud_core_vc141_x64.dll`
- `wxbase30ud_net_vc141_x64.dll`
- `wxmsw30ud_qa_vc141_x64.dll`
- `wxmsw30ud_html_vc141_x64.dll`
- `wxbase30ud_xml_vc141_x64.dll`
- `wxmsw30ud_aui_vc141_x64.dll`
- `wxmsw30ud_adv_vc141_x64.dll`
- `wxmsw30ud_stc_vc141_x64.dll`
- `wxmsw30ud_webview_vc141_x64.dll`
- `wxmsw30ud_vc141_x64.dll`

Apparently they all stem from `wxMSW-3.0.4_vc141_x64_Dev.7z`, but I can't think of a reason why they should be missing from the `build\install\bin` directory.

What's interesting is that in [this chapter of BUILD.md](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#visual-studio-gui-with-project-file) at the line `cmake -G "Visual Studio 15 2017" -DCMAKE_PREFIX_PATH=c:\libcurl ..`, these files also don't show up in the CMake output under "Run-time DLLs".
(Only `wxbase30u_vc141_x64 wxbase30u_net_vc141_x64 wxbase30u_xml_vc141_x64 wxmsw30u_adv_vc141_x64 wxmsw30u_aui_vc141_x64 wxmsw30u_core_vc141_x64 wxmsw30u_html_vc141_x64 wxmsw30u_qa_vc141_x64 wxmsw30u_stc_vc141_x64 wxmsw30u_webview_vc141_x64 msvcp140 ...` are mentioned in the CMake log and are present in `build\install\bin`)

When I manually copy the missing files into `build\install\bin`, mmex.exe throws another error on startup:
![image](https://user-images.githubusercontent.com/19881323/40187981-2d3ef2aa-59f9-11e8-9469-c3e29242d2dc.png)

That's as much as I could find out until now.

**Comment by vomikan** [comment]
Wx widgets should be builded in Debug mode x64 as well.

**Comment by slodki** [comment]
1. First error - probably you unpacked wxWidgets *.zip file into wrong directory:
> Unpack archives to `c:\wxWidgets\` or `c:\Program Files\wxWidgets\`.
>
>   You may select different directory but then `wxwin` environment variable
>   must be set:
>
>       setx wxwin c:\path\to\unpacked\wxwidgets\files
There is no need to copy them to the build\install\bin IMHO

2. This means DLLs where compiled with different version of MSVC then your MMEX binary. You must compile DLLs yourself if you cannot find binaries matching your installed MSVC version.

**Comment by slodki** [comment]
See #1411.
You should try [latest wxW 3.1.1 version](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.1) - i think this should help.

**Comment by StefanRickli** [comment]
@slodki Okay, it runs now <3!
I really needed the newer wxW version, BUT it still needed manual copying of the `*ud*.dll` files.

### Concrete steps that I used:
Download the following files from [wxW Releases](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.1):
- `wxWidgets-3.1.1-headers.7z`
- `wxMSW-3.1.1_vc141_x64_Dev.7z`
- `wxMSW-3.1.1_vc141_x64_ReleaseDLL.7z`

I unpacked the files in `C:\wxwidgets`. The folder now looks like this:
![image](https://user-images.githubusercontent.com/19881323/40202953-ea3bf856-5a23-11e8-8b10-7889eea87d44.png)

I then deleted my `build` folder and redid [the build tutorial from here](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#visual-studio-gui-with-project-file).
CMake would still not copy all needed DLLs and thus running the debugging session still gave me the missing DLL errors.

After copying all `*ud*.dll` files from `C:\wxwidgets\lib\vc141_x64_dll` to `build\install\bin` mmex.exe now starts up. No new build in VS was needed.

Does CMake maybe expect the files in a different folder?

**Comment by gabriele-v** [comment]
Have you set variable wxwin to your folder?
(point nr. 4 here https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#visual-studio-gui-with-project-file)
It's working fine on my side without need to manual copy them

**Comment by StefanRickli** [comment]
As the wording suggests that we only need to run this line when we place the files in a non-standard folder, I didn't run it.

I'll try again, but this time with explicit setting of the wxwin variable. Will report back.

**Comment by slodki** [comment]
I don't have VS installed at the moment to verify, but you can try to add the dll directory to the environment under Project Properties->Debugging->Environment and set `PATH=%WXWIN%\lib\vc_x64_dll;%PATH%
$(LocalDebuggerEnvironment)` or similar.

**Comment by StefanRickli** [comment]
Okay, [the lines here in CMakeLists.txt](https://github.com/moneymanagerex/moneymanagerex/blob/38261d80ec5a1c2c72006cd040f5b5c251a24a28/CMakeLists.txt#L370) are responsible that the DLLs mentioned in `build/cmake_install.cmake`.

Further, I noticed that `CMAKE_INSTALL_DEBUG_LIBRARIES` is set nowhere, so by running
`cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=c:\libcurl -DCMAKE_INSTALL_DEBUG_LIBRARIES=true ..` instead of `cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=c:\libcurl ..`
and then building the program in VS2017, the DLLs get copied/installed correctly.

**Comment by gabriele-v** [comment]
Wxwidgets DLL are not needed for deploy, so they shouldn't be copied or stay into the "install" folder.
They are needed only for building, but your building machine needs to know where they are located, that's the aim of wxwin environment variable. Have you set it?

**Comment by StefanRickli** [comment]
@gabriele-v 

> Have you set it?

I'm sorry, I forgot to mention. Yes - I did set it to `wxwin=C:\wxwidgets`, but that didn't help.

> they shouldn't be copied or stay into the "install" folder

I'm getting confused now. Please have a look at the generated `cmake_install.cmake` after running
`cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=c:\libcurl ..` and the `install_manifest` after building with VS.
You can clearly see that cmake is being instructed to install several files which it then copies to `build/install/bin`.

I have also attached the build log of VS.

[01_cmake_in_VS_dev_cmd_prompt.txt](https://github.com/moneymanagerex/moneymanagerex/files/2025377/01_cmake_in_VS_dev_cmd_prompt.txt)
[02_resulting_cmake_install.cmake.txt](https://github.com/moneymanagerex/moneymanagerex/files/2025378/02_resulting_cmake_install.cmake.txt)
[03a_VS_build_log.txt](https://github.com/moneymanagerex/moneymanagerex/files/2025379/03a_VS_build_log.txt)
[03b_resulting_install_manifest.txt](https://github.com/moneymanagerex/moneymanagerex/files/2025380/03b_resulting_install_manifest.txt)

**Comment by slodki** [comment]
@StefanRickli Did you tried to set PATH in VS debugging settings? I don't like to waste disk space...
DCMAKE_INSTALL_DEBUG_LIBRARIES is set to OFF by default as distributing debug versions of DLLs is prohibited and install step is included in the final packaging process.

We add install target (CMake step) into default VS build command
https://github.com/moneymanagerex/moneymanagerex/blob/38261d80ec5a1c2c72006cd040f5b5c251a24a28/CMakeLists.txt#L301
to have some MMEX specific files (like translations, config file, web page templates...) in place ready to run debug session. DLLs are added not for VS debugging proposes but for CPack installer creation.

You can:
- copy DLLs with install step (DCMAKE_INSTALL_DEBUG_LIBRARIES is required for Debug build)
- configure paths to libraries in VS (setting PATH should be enough)
- use static linking with wxWidgets library

**Comment by gabriele-v** [comment]
On my pc it works fine after set the environment variable.
Please check in Windows environment variable if it's there.

**Comment by StefanRickli** [comment]
Also @gabriele-v 
Do you mean the `wxwin` environment variable? Yes, it is defined. See the first attached file above (01_cmake_in_VS_dev_cmd_prompt.txt). I ran the `set` command to ensure that it's set.

**Comment by gabriele-v** [comment]
Yes, seems fine but lowercase. I don't know if it's case sensitive, but I have WXWIN uppercase

**Comment by StefanRickli** [comment]
@gabriele-v 
It doesn't work on my 2nd laptop as well... :-\
There I had none of the stuff pre-installed and I followed the tutorial very strictly, including setting WXWIN (uppercase this time).

Can you tell me which version of VS, wxW and curl you use and which branch of mmex you have checked out?
Something must be different...

@slodki 

> configure paths to libraries in VS (setting PATH should be enough)

If you mean setting `mmex Properties \ Debugging \ Environment` to `PATH=%PATH%;C:\wxwidgets\lib\vc141_x64_dll`, then this actually works.

Is that a fix or a workaround now?

**Comment by slodki** [comment]
> If you want to debug MMEX with dynamically linked wxWidgets (using DLLs) you must add path to your `lib\vc*_x64_dll` dir under `Project Properties` -> `Debugging` -> `Environment` (like `PATH=c:\wxWidgets\lib\vc141_x64_dll;%PATH% $(LocalDebuggerEnvironment)`

should be added to BUILD.md

**Comment by gabriele-v** [comment]
Hi @StefanRickli , sorry for the delay.
I'm using VS 2017 Community 15.6.6, Curl 7.59.0 and Wx 3.1.1 on Windows Server 2012R2 VM.
Obviously MMEX it's at latest master commit.
