### ISSUE TITLE
Allow transactions with empty payee

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1679]
*I'm always frustrated when...* MMEX ask me to enter a payee name even if it's unknown.

It's common for "cash" type accounts some spending have unknown payee (when I don't remember shop name from my last trip for example).
Even bank statements can include encoded payee names with only meaningless strings (like vending machine ID without company name).

MMEX should allow user to leave payee field empty (NULL).

User can create fake payee with "unknown" or similar name, but this solution have some drawbacks: payee field must be selected, special value searched and selected in transaction dialog.
The only benefit is the possibility to rename this special payee to user preferred name.

Is there any technical reason we must have PAYEEID NOT NULL?

**Comment by gabriele-v** [comment]
If you run a payee report, then how will transaction been shown? How to search transactions with null payee?

IMHO better to add an option saying "use payee X if payee field is empty" and near to it a payee selection, where you can choose a payee (Unknown or something else).

**Comment by vomikan** [comment]
It's already realized in QIF (may be in CSV) import. If payee nor present in the imported file the NULL value raplaced by "UNKNOWN"

**Comment by gabriele-v** [comment]
Yes, but maybe we could add a global option to specify category (if someone prefers something else).

**Comment by slodki** [comment]
You can use standard way to search for empty fields: activate filter on payee field with checkbox and leave value empty:

![bez tytulu](https://user-images.githubusercontent.com/3155552/40237800-bb0d0276-5ab1-11e8-8212-e7e7c4a52206.png)

Transactions with NULL PAYEEID are displayed as "Payee Error" now but this can be changed to "<none>", "<unknown>", "<undefined>" depending on context.

After manually changing PAYEEID to NULL in db file MMEX works normally, except:
- NULL value displayed as "Payee Error" in checkingpanel and as empty string in payee report
- transaction filter dialog is using empty string "" in place of NULL as filtering criteria
- transaction dialog validator does not allow empty value in payee field.

![bez tytulu](https://user-images.githubusercontent.com/3155552/40238252-fd7523fe-5ab2-11e8-9fc4-5ca05109e2db.png)
![bez tytulu](https://user-images.githubusercontent.com/3155552/40238284-104de09c-5ab3-11e8-842d-04ef18302a55.png)
![bez tytulu](https://user-images.githubusercontent.com/3155552/40238342-32edf916-5ab3-11e8-808f-1c1d5c500ec6.png)

alpha.4 database file attached for testing (NOT NULL constraint removed from checkingaccount payeeid field and 2 transactions with NULL PAYEEID entered).
[test_NULL_PAYEEID.zip](https://github.com/moneymanagerex/moneymanagerex/files/2017134/test_NULL_PAYEEID.zip)

**Comment by gabriele-v** [comment]
Personally I'd prefer to don't introduce NULL int values with a "self made" ORM like MMEX one, considering that workaround (Unknown, that's the same way that QIF, Android and WebApp version works) should be quite simple. Maybe just add an option to select category so could be different from unknown.

**Comment by slodki** [comment]
It is unintuitive to select some strange value from long list to mark the field is empty/missing.
It doesn't make sense for me to add separate checkbox "use empty/unknown/undefined value for this field" instead of accept empty value in combobox.

We can enforce user to always enter string "none" into notes field to confirm he don't want to store any notes too...
We should improve UX here.

**Comment by gabriele-v** [comment]
Notes filed is not mandatory by name (notes are additional data), category and payee are mandatory by name. If you to override default behavior, then you can null it but activating a specific option.
For example I always want to be sure that there is payee in my transactions (a part for reconciliation), then how do you handle it? Put a checkbox near to payee? It will be even poor...

**Comment by slodki** [comment]
@gabriele-v What does it mean "payee is mandatory by name"? There are many use cases mentioned above proving this is not true. Payee is mandatory by our database design and in many other financial app is implemented as optional.

Two more cases:
1. future transactions - I want to enter transaction planned for next month, but I didn't select shop/company so far
2. Share transactions - MMEX requires to select payee even if transaction is simple transfer between my own 2 accounts (investment and share accounts)

**Comment by gabriele-v** [comment]
When you make a deposit/whitedrawal, then a payee it's always present. Then, if you don't know it yet (future transactions) or because you don't want to trace it (reconciliation, small purchases) it's another matter. In case of investment and share payee IMHO should be the share company or the investment itself.

We are just seeing the same thing from two different POV:
- You consider payee as optional, so you need to find a way (option?) to "force" if someone wants the payee mandatory
- I consider payee as mandatory, so I need to find a way (option with default) if someone wants it optional

Then which POV is the right one, we can discuss, but anyway we need an option for the other case.

**Comment by slodki** [comment]
There is always the second participant of transaction. That's true.

It's not true that payee can be always identified. Some transaction types cannot identify payee by their nature: charity donations on the street, anonymous blockchain transfers, shopping done by your children. 
Sometimes payee isn't identified by it's name but different ID (like address, bank account number, terminal ID etc.) unsuitable for use as a name.

This issue is not about technical implementation (I've changed it's title from original "Remove NOT NULL from PAYEEID column") but about UX. It's not important for me if ability of using empty payee will be opt-in or opt-out.
We should improve entering transaction ergonomy. Now user:
- enters transaction details
- accepts transaction
- pop-up with error description for payee field is displayed
- must select payee field
- must search for arbitrary value
  - scrolling very long list
  - or entering name from keyboard
- must confirm highlighted value selection
- can accept transaction

Only 2 first steps should be required to enter transaction. It's OK for me to activate this behavior in MMEX global options, store empty payee as hardcoded text value into database etc.

**Comment by gabriele-v** [comment]
Ok, that's better. I completely agree that we should offer the possibility to "skip" the payee, for the UX we are on the same page. My question was mainly technical (referred to NULL) and default/opt MMEX behaviour: honestly I don't know which is the best approach/default, but for sure we have to support both scenarios (payee required and payee unrequired).

**Comment by vomikan** [comment]
Categories and payees should cover 100% of transactions. 
It's not possible GROUP BY NULL in case if empty values would be present. 
I suggest do not use empty values on DB side. But it may be variants in UI side.

**Comment by slodki** [comment]
@vomikan tested on prepared db file attached above:
```sql
sqlite> select TRANSID, PAYEEID, TRANSAMOUNT, TRANSDATE from CHECKINGACCOUNT_V1;
TRANSID     PAYEEID     TRANSAMOUNT  TRANSDATE 
----------  ----------  -----------  ----------
1           1           1            2018-05-18
2           1           2            2018-05-18
3           2           3            2018-05-18
4           2           4            2018-05-18
5                       5            2018-05-18
6                       6            2018-05-18

sqlite> select PAYEEID, COUNT(*), SUM(TRANSAMOUNT) from CHECKINGACCOUNT_V1 group by PAYEEID;
PAYEEID     COUNT(*)    SUM(TRANSAMOUNT)
----------  ----------  ----------------
            2           11              
1           2           3               
2           2           7

sqlite> select TRANSID, PAYEEID, TRANSAMOUNT, TRANSDATE from CHECKINGACCOUNT_V1 where PAYEEID is null;
TRANSID     PAYEEID     TRANSAMOUNT  TRANSDATE 
----------  ----------  -----------  ----------
5                       5            2018-05-18
6                       6            2018-05-18
```
There is no problem with GROUP BY on column with NULL values.

**Comment by gabriele-v** [comment]
If you switch from required to optional, then no changes are required. If you switch from optional to required, then payee set in settings as default for empty payee will be used.
In this case I think it will be better to have default as required and optional as "automatically use this one if payee empty", so you can use that one for old transactions too when switching behavior.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/627
