### ISSUE TITLE
Wrong scale on Stocks Performance Report

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1690]
X-Axis is not using time scale - generated charts are wrong:

First segment for 2 months have the same horizontal width as 2nd segment for 1 week:
![mmex1](https://user-images.githubusercontent.com/3155552/40563735-30aac75c-6066-11e8-8911-875f102a59ba.png)

With only some historical rates downloaded parts of chart are squashed (Feb-Mar):
![mmex2](https://user-images.githubusercontent.com/3155552/40563738-34794908-6066-11e8-9528-607f4ebc520f.png)

Compare above chart with original chart from Yahoo for the same period:
![mmex3](https://user-images.githubusercontent.com/3155552/40563751-3f641c94-6066-11e8-9213-58c810d7eb3e.png)

**Time scale for x-axis must be used in Stocks Performance Report charts.**

**Comment by whalley** [comment]
The time series are now correct and is resolved as part of https://github.com/moneymanagerex/moneymanagerex/issues/1689 . This can be closed.
