### ISSUE TITLE
Building with VS and native CMake doesn't work

### ISSUE THREAD

**Issue by StefanRickli** [moneymanagerex/moneymanagerex#1692]
I'm currently correcting BUILD.md and this issue concerns [this part of the tutorial](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#visual-studio-2017-gui-with-native-cmake-support).

Every time VS tries to run  `/CMakeLists.txt`, it stops with the following error:

    CMake Error at C:\(A)\aProgrammieren\by_topic\moneymanagerex\CMakeLists.txt:284 (SET_TARGET_PROPERTIES): SET_TARGET_PROPERTIES can not be used on an ALIAS target.

It seems that the following line sets the mentioned alias
https://github.com/moneymanagerex/moneymanagerex/blob/d17dad2eebab7b3105d53d48785bb19c35e0d9ae/CMakeLists.txt#L281

which is then used shortly after in the line that causes the error:
https://github.com/moneymanagerex/moneymanagerex/blob/d17dad2eebab7b3105d53d48785bb19c35e0d9ae/CMakeLists.txt#L284

According to the [CMake documentation](https://cmake.org/cmake/help/v3.0/policy/CMP0028.html), since cmake version 3.0 this fails with an error. It could be mitigated by using a `cmake_policy` statement, but in my version 3.11 this doesn't work anymore. Maybe the syntax has been completely abandoned.

I then tried getting rid of the alias **which worked** on my machine:

1. In `/CMakeLists.txt:281`, remove this line.
2. In `/CMakeLists.txt:284`, change `CURL::libcurl` to `CURL`.
3. In `/src/CMakeLists.txt:314`, change `CURL::libcurl` to `CURL`.
4. I'm not sure if item (3) in the tutorial, that requires to set `CMAKE_PREFIX_PATH`, is needed anymore. On my machine, building works without.

(There's the same problem as in #1676 with running `x64-Debug`, but that's another issue to open. Installing and running `x64-Release` works.)

Can someone confirm that the above steps 1-3 are appropriate and step 4 about removing (3) in the tutorial is correct?

**Comment by slodki** [comment]
There are different curl packages - some of them include cmake configuration script but sometime it's missing.
We are trying to use 2 methods to read libcurl configuration:
1. configuration script distributed with libcurl package
2. module distributed with cmake package
First is better IMHO, but we must support 2nd too. They use different library name so cmake script creates alias to use one of them.

CMP0028 is not releated to your problem as it will:
> issue a FATAL_ERROR if a link dependency contains double-colons but is not an IMPORTED target or an ALIAS target.
And our target is alias target.

You should check why no *.cmake config file is installed after curl compilation. This causes 2nd detection method to be used, alias created and error generated.

Additional cmake script line forcing static libcurl version should be moved before alias creation (maybe twice for 2 IF branches).

**Comment by StefanRickli** [comment]
OK, it works now.

2 unfortunate things happened:
- I inserted the _variables_ block that defines `CMAKE_PREFIX_PATH` at the wrong place, so it wasn't active but also didn't generate an error.
- Because of that, the standard search paths were searched by `find_package`, which then found a curl include directory in my anaconda folder (which was part of my `PATH` variable).

Correctly inserting the `CMAKE_PREFIX_PATH` definition in _CMakeSettings.json_ solved the problem.

I'll include a more precise statement about this in the corrected BUILD.md.
