### ISSUE TITLE
Custom Fields Menu abends at commit d17dad2e

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1693]
Thought I would have a play with the new Custom Fields Manager so...

Source at commit d17dad2e and compiled with VS2017
Source compiled cleanly
Start program and create a new database, fill in currency and create a single account but add  no data
Click Custom Fields Manager on Tools menu, get an empty panel with Close button and "wheel" button
Left Click on wheel symbol "other tools" and select only option available which is Add, others are greyed out.
Program abends with an access violation
<exception address="344d4f6a" name="ACCESS_VIOLATION" code="c0000005"/>

Bug is reproducable for me and I hope for you as well but if you need more info please let me know

Run under VS Debug gives the following
![vs_debug](https://user-images.githubusercontent.com/24897056/40661951-e5b806f8-634c-11e8-9a7c-74a8d5f9c769.JPG)

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by vomikan** [comment]
@grumpy235 thank you for your report.

**Comment by grumpy235** [comment]
Nikolay,
That fixes the abend and I now get the "New/Edit Custom Field" panel which I was expecting.
I'll continue "playing"
Many thanks
