### ISSUE TITLE
UX improvement for Relocate Payee Dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1696]
- [x] Add `Delete source payee` checkbox and delete unused payee after successful operation
- [x] Do not close dialog after operation - this will allow multiple operations in a row
- [x] Hide unused payees from source selection combo - selecting unused payee disables `OK` button

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1390

**Comment by slodki** [comment]
It's still possible to open this dialog with empty source payee list (when there is no transactions at all in a new database). It's not worth to detect it and complicate code IMHO.

**Comment by vomikan** [comment]
It may be closed?

**Comment by slodki** [comment]
Yes. I have implemented solution but is not elegant. Cancel will allow to close such useless dialog.
