### ISSUE TITLE
New features are introduced in version 1.4 

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1697]
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=7576

Hi!

What new features are introduced in version 1.4 compared to version 1.3.3 ?
I installed version 1.4 alpha 4 and I do not see the difference (I'm not talking about changes under the hood (bug fix, library updates etc))

Thx

**Comment by slodki** [comment]
Partially this is duplicate of #1298.
But [ChangeLog](https://github.com/moneymanagerex/moneymanagerex/blob/master/version.txt) should be updated too.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1968
