### ISSUE TITLE
After GDPR question: simplify usage statistics?

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1699]
Why we collect usage statistics with time details? It's useless for consolidation from multiple sources without timezone info.

It's really important for us to know which mmex function user is using in the morning or at night?
I think collecting date with number of seconds should be enough and this will simplify usage json data from:
```json
{
    "start": "2018-03-31 21:07:27",
    "end": "2018-03-31 21:20:01",
    "usage": [
        "{\"module\":\"Home Page\",\"start\":\"2018-03-31T21:07:32\",\"end\":\"2018-03-31T21:07:32\"}",
        "{\"module\":\"Home Page\",\"start\":\"2018-03-31T21:11:28\",\"end\":\"2018-03-31T21:11:28\"}",
        "{\"module\":\"Home Page\",\"start\":\"2018-03-31T21:16:30\",\"end\":\"2018-03-31T21:16:31\"}",
        "{\"module\":\"Home Page\",\"start\":\"2018-03-31T21:16:31\",\"end\":\"2018-03-31T21:16:31\"}",
        "{\"module\":\"Home Page\",\"start\":\"2018-03-31T21:19:45\",\"end\":\"2018-03-31T21:19:45\"}"
    ],
```
to
```json
{
    "start": "2018-03-31",
    "end": "2018-03-31",
    "usage": [
        "{\"module\":\"Home Page\",\"seconds\":\"23242\"}"
    ],
```

**Comment by vomikan** [comment]
```"end": "2018-03-31",```
Is redundantly.

**Comment by grumpy235** [comment]
I would ask is why collect any form of statistics in the first place. This is not a commercial product, maintenance is done on a best efforts basis from enthusiasts like yourselves so where is the benefit. First thing I do when downloading a new version is check that stats collection is off but maybe I'm just paranoid  :smile:

**Comment by slodki** [comment]
@grumpy235 #MeToo

**Comment by vomikan** [comment]
We (in fact one person @lisheng) develope method for stat collection.

**Comment by bestlem** [comment]
re GPDR - who would be sued for breaking of the rules? Who owns the data collected. Unless explicitly stated aren't the only people visible the contributers.

Thendoes contributing add libaility?

**Comment by vomikan** [comment]
@guanlisheng please comment

**Comment by slodki** [comment]
There is no risk related to GDPR because we don't collect any personal data (allowing user identification). As long as we don't store any personal data we don't have to respond to user requests because we don't have their data.
There should be visible benefit from the gathering even anonymous data - users (like me) will turn this feature off if they will not see any benefits (even as stupid as funny charts on webpage...) for them.

**Comment by gabriele-v** [comment]
IMHO knowing how many users are actually using MMEX it's useful and not just a funny chart..

It was added also to understend which are the more used functions in order to improve them or drop something else that it isn't used at all.

**Comment by guanlisheng** [comment]
Back to the original subject, we would do some simplification here if needed.

**Comment by ovari** [comment]
Please set the default to **disabled/off** for `Send anonymous statistics usage data`. Thank you

**Comment by gabriele-v** [comment]
There are lots (or almost all) of other software set by default to send statistics..
