### ISSUE TITLE
SQL logic error[1]: duplicate column name: CURRENCY_TYPE

### ISSUE THREAD

**Issue by StefTas5562** [moneymanagerex/moneymanagerex#1705]
**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [X] Linux Mint Sylvia
- [X] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [X] 1.4.x Alpha
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

I have the same issue how https://github.com/moneymanagerex/moneymanagerex/issues/1632.
But I need a patch because I was three weeks on Holiday and I have add and change a lot into my DB with Android :-)
The patch from issue #1632 doesn't work for me.

Regards, Stefano

**Comment by andrepg** [comment]
Hey, The patch also won't work for me. But I've edited my database just like patch does and now MMEX Desktop opens my database. It's a SQL command to change a "**user_version**" property into "**Pragmas**" section. Opening file with text editor will show you this.

_If you don't know what you doing with database, make a backup before anything !_

**Comment by StefTas5562** [comment]
Thanks a lot. That's resolved my problem and my DB is now correct.
But I have updated the PRAGMA user_version with an "DB Browser for SQLite", because the currency_type_patch.mmdbg doesn't work with MMEX
Regards, Stefano

**Comment by andrepg** [comment]
Yeah, I had to open my DB with DB Browser for SQLite also because patch was not applied.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2353
