### ISSUE TITLE
MMEX database upgrade to version 10 failed!

### ISSUE THREAD

**Issue by Mitya969** [moneymanagerex/moneymanagerex#1710]
<hr><small><b>Version</b>: 1.4.0-alpha.4 • db 13 (aes128cbc) • git 157fd845 (2018-06-09) master<br><b>Libs</b>: wxWidgets 3.0.4 (wxGTK 3.22) • wxSQLite3 4.0.3 (SQLite 3.23.1) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.58.0 • OpenSSL 1.1.0g • zlib 1.2.11 • libidn2 2.0.4 • libpsl 0.19.1 • ( libidn2 2.0.4) • nghttp2 1.30.0 • librtmp 2.3<br><b>Build</b>: Jun 12 2018 20:48:45 • CMake 3.10.2 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.3.0 • Ubuntu 18.04 'bionic'<br><b>OS</b>: Ubuntu 18.04 LTS "bionic" • Linux 4.15.0-23-generic x86_64 • English (UTF-8) • 1600x900 24bit 48x48ppi</small><br><br>

On opening existing Db created in v.1.3.3 (DB v.7) on Windows 10 I'm presented with following error:<br>
<b>MMEX database upgrade to version 10 failed!</b>
Please restore DB from autocreated pre-upgrade backup and retry or contact MMEX support
constraint failed [2067]: UNIQUE constraint failed: CURRENCYFORMATS_V1_NEW.CURRENCY_SYMBOL

**Comment by slodki** [comment]
https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems#unique-constraint-failed-currencyformats_v1_newcurrency_symbol

**Comment by Mitya969** [comment]
Excellent. That did the trick. Thank you
