### ISSUE TITLE
Crash when trying to print current view (when wrong default printer is set)

### ISSUE THREAD

**Issue by Fabi54321** [moneymanagerex/moneymanagerex#1712]
**Describe the bug**
When I press "print current view" button and in Windows my DYMO LabelWriter 450 is set as default instead of a "normal" printer, MMEX crashes completely (closes without any error message) a second after the print preview windows shows up.

**To Reproduce**
1. Have a special printer like the DYMO LabelWriter installed (maybe it is only necessary to have a much smaller paper size?)
2. Click on 'print current view' icon or click on 'File'->'Print...'
3. See preview window for about one second
4. See MMEX crashing / closing without any message

**Expected behavior**
MMEX should not crash. It should work for any printer or show an error that the current printer is not supported.

**Screenshots**
none

**Additional context**
Problem occurred because default printer was changed due to Windows 10's "smart" "Let Windows manage my default printer" feature.  

**Your OS:**
- [x] Windows 10
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x (1.3.3)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by whalley** [comment]
@Fabi54321 Are you able to confirm if this is still an issue with the latest MMEX version?

**Comment by whalley** [comment]
Closing as really old... @Fabi54321 if this is still a concern we can reopen.
