### ISSUE TITLE
Memorising categories based on payee

### ISSUE THREAD

**Issue by chmcf** [moneymanagerex/moneymanagerex#1717]
It would be useful to have the ability to memorise the categories of some transactions based on payee, for example all withdrawals to my landlord are for rent.  This would simply assigning categories to transactions after importing from csv file.

**Comment by slodki** [comment]
Tools -> Organize Payees -> right mouse button or gearwheel button -> Define Default Category

**Comment by chmcf** [comment]
It only appears to categorize new transactions not imported ones? Or am I
missing a step (newbie user)?

**Comment by slodki** [comment]
There is code for manually added trensactions:
https://github.com/moneymanagerex/moneymanagerex/blob/20f883322129529a75e1043920d80c8e40158e16/src/transdialog.cpp#L785

and for imported csv records:
https://github.com/moneymanagerex/moneymanagerex/blob/20f883322129529a75e1043920d80c8e40158e16/src/import_export/univcsvdialog.cpp#L763

**Comment by chmcf** [comment]
Ok thank you so much
