### ISSUE TITLE
QIF import fails for single-digit dates

### ISSUE THREAD

**Issue by fljmayer** [moneymanagerex/moneymanagerex#1718]
**Describe the bug**
I exported a QIF file from Quicken 2016 and tried to import it into MoneyManagerEx. It detected the date format DD/MM'YY. I got many errors in the log about invalid dates. Apparently MoneyManagerEx doesn't like single-digit months. I wasn't able to change the date format.

**To Reproduce**
Here is an example record that cannot be imported:
^
D6/ 4'18
U-135.00
T-135.00
C*
POkefenokee Swamp Park
MOKEFENOKEE SWAMP PARK
LRecreation
^

**Expected behavior**
MoneyManagerEx should be able to import a valid QIF file.

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/47636389-2b577100-db69-11e8-8aa8-1991c121e474.png)

**Comment by vomikan** [comment]
```((([0 ][1-9])|(1[0-2]))|([1-9]))\/((([0 ][1-9])|([1-2][0-9])|(3[0-1]))|([1-9]))'(([ ][0-9])|([0-9]{1,2}))```
``` 8/ 1'7```
https://regex101.com/
