### ISSUE TITLE
CANNOT MAKE REPORTS WITHIN RANGE OF DATES

### ISSUE THREAD

**Issue by msjakas** [moneymanagerex/moneymanagerex#1722]
I cannot generate reports within specific range of dates. For example, the "where the money goes" report, I have several options in the the scroll bar, and next to it there is a window to chose a date range which appears NOT ACTIVE for me (in grey color). 

I was expecting to have the possibility to introduce the date ranges in the shown window next to the Reports scroll bar:

![image](https://user-images.githubusercontent.com/41064758/42519585-44619d24-845c-11e8-95dc-5e7c48bd7f91.png)

I an using Mac OSX

**MMEX version 1.3.3

**Comment by slodki** [comment]
In 1.4.x there is the last option "custom" in the combobox (below "current month" etc.) - it will allow to define from - to dates. All other list item have predefined dates.

**Comment by msjakas** [comment]
Thanks Slodki for your sugestion. But I just check that the version 1.4.x
is an unstable version. So i don't want to install it just in case i have
problems with it.

**Comment by slodki** [comment]
It's available in 1.4.0 (#1059) as described in #789
