### ISSUE TITLE
Since Ubuntu 18.04 I can't install MMEX wx3.0-i18n:all not installable

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#1726]
**Describe the bug**
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mmex : Hängt ab von: wx3.0-i18n:all  but it is not installable
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
When I force install this application, it works but it breaks my system.
I can't install applications anymore, until I remove the damaged package mmex.

**To Reproduce**
Install the package (nightly too)

**Expected behavior**
An installable package.

**Screenshots**

**Additional context**
@slodki 
@infidelus
@swt2c
Since switching to Ubuntu 18.04 (Linux Mint 19 & Ubuntu Mate 18.04), I get this problem.
Even on a fresh installation.
Linux Mint and Ubuntu are very similar, they use the same software repositories.
But additionally Linux Mint uses its own too.

To workaround this issue, I edit the debian package and modify the control file in the DEBIAN folder.
I  change
`Depends: wx3.0-i18n:all,[...]`
to
`Depends: wx3.0-i18n,[...]`

**Your OS:**
- [X] Linux Mint 19 / Ubuntu Mate 18.04

**MMEX version:**
- [X] 1.4.x
- [X] development version (git master branch)

**Comment by MartinX3** [comment]
How do you install the package?
If I use
`dpkg -i mmex.deb`
I can install it without problems, but can't execute
`apt autoremove`
after that.

**Comment by slodki** [comment]
Please compare your /etc/apt/* with docker images

**Comment by MartinX3** [comment]
The sad thing is, that no 3rd party repo changed my system packages.
I use
bionic-backports
bionic-security
bionic-updates
bionic/main
bionic/universe
bionic/multiverse
bionic/restricted
tara/main
tara/non-free
tara/universe

**Comment by slodki** [comment]
`:all` dependency should be supported as described in [MultiarchSpec](https://wiki.ubuntu.com/MultiarchSpec#Extended_semantics_of_per-architecture_package_relationships). Repo servers can list `all` arch packages [in separate list](https://wiki.debian.org/DebianRepository/Format#Architectures) so missing `all` package can be repo error too.

wx3.0-i18n package was fixed 4 moths ago:
```
  * debian/control.in: Multi-Arch changes (Closes: #887378)
    + Change wx3.0-headers to Architecture: all and Multi-Arch: foreign
    + Change wx3.0-i18n to Multi-Arch: foreign
    + Change wx3.0-examples to Multi-Arch: foreign
    + Change wx3.0-doc to Multi-Arch: foreign
    + Change wx3.0-headers dependents from binary to source version

 -- Scott Talbert <swt@techie.net>  Wed, 14 Mar 2018 23:35:28 -0400
```

We needed `:all` dependency in MMEX package in February as in #1431. Now I will test above fixes and try to remove workaround.

I don't use aptitude.

**Comment by MartinX3** [comment]
Thank you, that you will test to remove this workaround.

I changed my repository to the standard linux mint selection, but still get this error.
So it can't be a repo error.

By the way @slodki is it possible to create a full amd64 mmex package, without any i386?

**Comment by slodki** [comment]
You can see in [test results](https://travis-ci.org/slodki/moneymanagerex/builds/404159528) (with `:all` removed):
* fixed (>=3.0.4+dfsg-1) wx3.0-i18n package
* *or* my workaround from #1431 with :all dependency

is required for correct dependency resolution.

@MartinX3 I don't understand your question: `*_amd64.deb` packages don't contain any i386 binaries.

**Comment by slodki** [comment]
Dependency are dynamically determined based on both packages architectures and other params as described in MultiarchSpec linked above:

> `Architecture: all` packages will, at least initially, be treated as equivalent to packages of the native architecture for all dependency resolution. This means that for an `Architecture: all` package to satisfy the dependencies of a foreign-architecture package, it must be marked `Multi-Arch: foreign` or `Multi-Arch: allowed`.

Problem exists for i386 packages for distributions with not fixed wx3.0-i18n package.

**Comment by MartinX3** [comment]
So do you have an idea how to fix this weird behaviour?
I never got this error before or at any other package.

**Comment by MartinX3** [comment]
I reinstalled my laptop, so I can close this issue und will not anymore bother you with this bug. :)
And switched to Linux Mint 19 x64 Cinammon.
