### ISSUE TITLE
Blurred charts in reports

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1733]
![mmex](https://user-images.githubusercontent.com/3155552/42966087-4aa58488-8b9c-11e8-9de2-98771ea63d4c.png)

![mmex](https://user-images.githubusercontent.com/3155552/42966149-85f85344-8b9c-11e8-96df-9d819582c0d1.png)

If MMEX window is maximized charts are ok (sharp).

<hr><small><b>Version</b>: 1.4.0-alpha.4 • db 13 (aes128cbc) • git ebb7c09d (2018-07-15) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 4.0.4 (SQLite 3.24.0) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.58.0 • OpenSSL 1.1.0g • zlib 1.2.11 • libidn2 2.0.4 • libpsl 0.19.1 • ( libidn2 2.0.4) • nghttp2 1.30.0 • librtmp 2.3<br><b>Build</b>: Jul 15 2018 15:41:07 • CMake 3.10.2 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.3.0 • Ubuntu 18.04 'bionic'<br><b>OS</b>: Ubuntu 18.04 LTS "bionic" • Linux 4.15.0-24-generic x86_64 • KDE Polish (UTF-8) • 1280x1024 24bit 96x96ppi</small>

**Comment by gabriele-v** [comment]
I confirm the same problem on Windows

**Comment by vomikan** [comment]
#1734
