### ISSUE TITLE
Bring "balance account" feature from mobile to desktop

### ISSUE THREAD

**Issue by yaomtc** [moneymanagerex/moneymanagerex#1735]
In the Android version, when you long-press an account, you have the option to edit or balance the account. Selecting "balance account" brings up a dialog to enter the current amount of the account. When entered, a new transaction is added to the account with "Balance Adjustment" added as a payee, and the amount of the transaction bringing the account to the amount you entered.

On desktop, right-clicking an account doesn't give you this option. It would be useful for all platforms to have this simple little feature, I think.

**Comment by slodki** [comment]
See #1678
