### ISSUE TITLE
Categories Monthly report totally broken

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1738]
From attached db:
[test.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/2211839/test.mmb.zip)

![mmex](https://user-images.githubusercontent.com/3155552/42973314-0de1af1a-8bb3-11e8-8f7d-e7b3d202851a.png)
![mmex](https://user-images.githubusercontent.com/3155552/42973371-3bccc96e-8bb3-11e8-982f-3d2383e13126.png)

<hr><small><b>Version</b>: 1.4.0-alpha.4 • db 13 (aes128cbc) • git ebb7c09d (2018-07-15) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 4.0.4 (SQLite 3.24.0) • Mongoose 6.11 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.58.0 • OpenSSL 1.1.0g • zlib 1.2.11 • libidn2 2.0.4 • libpsl 0.19.1 • ( libidn2 2.0.4) • nghttp2 1.30.0 • librtmp 2.3<br><b>Build</b>: Jul 15 2018 15:41:07 • CMake 3.10.2 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.3.0 • Ubuntu 18.04 'bionic'<br><b>OS</b>: Ubuntu 18.04 LTS "bionic" • Linux 4.15.0-24-generic x86_64 • KDE Polish (UTF-8) • 1280x1024 24bit 96x96ppi</small>

**Comment by lonemadmax** [comment]
Disclaimer: I don't know c++ nor wxWidgets, I just thought it could be some problem handling NULL in SQL and when I found no SQL I couldn't stop "debugging by cout".

https://github.com/moneymanagerex/moneymanagerex/blob/d353afecb161fd30133b2df42196375168d3c136/src/model/Model_Category.cpp#L174-L175

After line 175 `idx` takes the values:

> 201800	201800	201800	201800	201800	201800	201800	201700	201700	201700	201700	201700

initializing just 201800 and 201700, and making the rest of calculations wrong.

Taking the `&` out in the declaration of `d` in line 174 seems to make everything work. These also seem to work, whatever they each mean:
`const wxDateTime d = start_date.Subtract(wxDateSpan::Months(m));`
`const wxDateTime d = start_date - wxDateSpan::Months(m);`
`const wxDateTime &d = (new wxDateTime(start_date))->Subtract(wxDateSpan::Months(m));`
