### ISSUE TITLE
Distribute MMEX using snap/flatpack

### ISSUE THREAD

**Issue by BearzRobotics** [moneymanagerex/moneymanagerex#1740]
**Is your feature request related to a problem? Please describe.**
no, this is more for the distribution of the app on Linux.

**Additional context**
I was wondering if you guys had any plans to support Ubuntu's snap package or flatpacks? When I went to your downloads page you only had instructions for installing a prebuilt binary on Arch Linux. Were as snap and flatpacks are cross distro packaging formats that would enable the easy instillation on a lot more Linux distros without having to compile it from source.

**Comment by slodki** [comment]
Please use instructions from [INSTALL](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md) file to install MMEX on different Linux distros.
See also #1419 proposal.

**Comment by BearzRobotics** [comment]
I got it to build from source and am able to use it. This was just a suggestion to make using your software easier for people in the Linux community.

**Comment by slodki** [comment]
First version published at store (using #1742):
```
$ snap info mmex
name:      mmex
summary:   Money Manager Ex - simple to use financial management software
publisher: slodki
contact:   https://www.moneymanagerex.org/
license:   GPL-2.0
description: |
  Money Manager Ex (MMEX) is a free, open-source, cross-platform,
  easy-to-use personal finance software. It primarily helps organize
  one's finances and keeps track of where, when and how the money goes.
  MMEX includes all the basic features that 90% of users would want to
  see in a personal finance application. The design goals are to
  concentrate on simplicity and user friendliness - something one can
  use everyday.
snap-id: eLWRGvEBIudTVQrrLF0X5iBbr1wiDPvE
channels:                            
  stable:    –                       
  candidate: –                       
  beta:      –                       
  edge:      1.4.0-alpha.4 (1) 118MB devmode
```
To install run `sudo snap install --devmode --edge mmex` from terminal.

```
$ snap list
Name       Version        Rev   Tracking  Developer  Notes
core       16-2.33.1      4917  stable    canonical  core
mmex       1.4.0-alpha.4  1     edge      slodki     devmode
snapcraft  2.42.1         1594  stable    canonical  classic
```

**Comment by BearzRobotics** [comment]
Thank you, that was fast. I re-posted the instructions and a link back here to Solus page were people (including myself) were requesting this. I got it installed in only a few seconds with that command.

**Comment by slodki** [comment]
travis-ci/dpl#845

**Comment by jeroen7s** [comment]
snap seems to be out of date
