### ISSUE TITLE
Can't install from source in Ubuntu 16.04

### ISSUE THREAD

**Issue by malapradej** [moneymanagerex/moneymanagerex#1745]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue
> for similar problem - update existing issue instead of creating new one.
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.
> 4. Put some descriptive name for your issue in the Title field above.
> 5. Fill form below with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 6. Include steps to reproduce your issue, attach screenshots where appropriate.
> 7. Mark (put x inside brackets: [x]) correct answers below about your OS and MMEX version used.
> 5. Remove this text marked with >.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by malapradej** [comment]
I have tried installing mmex from the package manager, as well as using other repositories to no avail. I was thus left with trying to compile from source. I used the recommended steps:

    git clone --recursive https://github.com/moneymanagerex/moneymanagerex
    mkdir moneymanagerex/build
    cd moneymanagerex/build/
    export MAKEFLAGS=-j2
    cmake -DCMAKE_BUILD_TYPE=Release ..
    cmake --build . --target package


It comes up with the following error:

    [100%] Linking CXX executable mmex
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFGetVersion@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFReadRGBAImageOriented@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `_TIFFfree@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `_TIFFmalloc@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
    /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/mmex.dir/build.make:2961: recipe for target 'src/mmex' failed
    make[2]: *** [src/mmex] Error 1
    CMakeFiles/Makefile2:292: recipe for target 'src/CMakeFiles/mmex.dir/all' failed
    make[1]: *** [src/CMakeFiles/mmex.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by malapradej** [comment]
I managed to get it installed using:

    curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh | sudo bash
    sudo apt update && sudo apt install mmex

But I assume this will be an unstable release?

**Comment by slodki** [comment]
I will not push old releases there as i dont know packages quality. Future releases will be published there.
Or you can use universal snap package but this will waste some disk space (it contains libraries copy to ensure compatibility with different distributions)

**Comment by malapradej** [comment]
@slodki I tried snap but it didn't work.

**Comment by malapradej** [comment]
@slodki I have the following libtiff packages installed:

i   libtiff-tools                   - TIFF manipulation and conversion tools    
i A libtiff5                        - Tag Image File Format (TIFF) library      
i   libtiff5:i386                   - Tag Image File Format (TIFF) library      
i   libtiff5-dev                    - Tag Image File Format library (TIFF), deve
i   libtiffxx5                      - Tag Image File Format (TIFF) library -- C+

**Comment by malapradej** [comment]
@slodki and the following wx packages:

i   libwxbase2.8-0                  - wxBase library (runtime) - non-GUI support
i A libwxbase3.0-0v5                - wxBase library (runtime) - non-GUI support
i   libwxbase3.0-dev                - wxBase library (development) - non-GUI sup
i   libwxgtk-media2.8-0             - wxWidgets Cross-platform C++ GUI toolkit (
i A libwxgtk-webview3.0-0v5         - wxWidgets Cross-platform C++ GUI toolkit (
i   libwxgtk-webview3.0-dev         - wxWidgets Cross-platform C++ GUI toolkit (
i   libwxgtk2.8-0                   - wxWidgets Cross-platform C++ GUI toolkit (
i A libwxgtk3.0-0v5                 - wxWidgets Cross-platform C++ GUI toolkit (
i   libwxgtk3.0-dev                 - wxWidgets Cross-platform C++ GUI toolkit (
i   python-wxgtk2.8                 - wxWidgets Cross-platform C++ GUI toolkit (
i A python-wxgtk3.0                 - Python interface to the wxWidgets Cross-pl
i   python-wxtools                  - Tools from the wxPython distribution      
i   python-wxversion                - API for selecting the wxPython version to 
i A wx-common                       - wxWidgets Cross-platform C++ GUI toolkit (
i   wx2.8-doc                       - wxWidgets Cross-platform C++ GUI toolkit (
i   wx2.8-examples                  - wxWidgets Cross-platform C++ GUI toolkit (
i   wx2.8-headers                   - wxWidgets Cross-platform C++ GUI toolkit (
i A wx3.0-headers                   - wxWidgets Cross-platform C++ GUI toolkit (
i   wx3.0-i18n                      - wxWidgets Cross-platform C++ GUI toolkit (

**Comment by malapradej** [comment]
I managed to get it installed from source in the end so I will close this.
