### ISSUE TITLE
decimals removed from figures input in transaction box

### ISSUE THREAD

**Issue by ValDiMello** [moneymanagerex/moneymanagerex#1748]
**Describe the bug**
after opening the box to input a new transaction, the decimals of the figure inserted in the Amount box are rounded to zero, and decimals are therefore not calculated as part of the deposit or withdrawal.

**To Reproduce**
1. select any account
2. click on 'new' button
3. input date, staus, type and amount (input a figure with decimals, i.e. 3.45 or 3,45)
4. hit enter
5. observe that the 3,45 or 3.45 is now changed to 3.00

**Expected behavior**
decimals should not be zeroed.
after hitting enter 3.45 should remain 3.45 and not become 3.00

**Screenshots**
...i do not think this is necessary...

**Additional context**
can it be my win10 regional settings?

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x (1.3.3)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by whalley** [comment]
Closing as the recent changes to locale handling have fixed any issues in this area.
