### ISSUE TITLE
Putting a character in an operation amount makes the application crash

### ISSUE THREAD

**Issue by GhaziTriki** [moneymanagerex/moneymanagerex#1754]
**Describe the bug**
Putting a character in an operation amount makes the application crash.

**To Reproduce**
1. Go to 'Bank Accounts' after creating a bank account.
2. Click on 'New' at the bottom bar.
3. Fill 'Amount' with non numeric characters and focus out.
4. The application crashes immediately.

**Expected behavior**
The application should not crash and saving the operation should not be possible.

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x (Portableapps.com)
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by GhaziTriki** [comment]
Was this issue fixed in 1.4.x?

**Comment by GhaziTriki** [comment]
Nice, can you please update the version of http://portableapps.com to 1.4.x?

**Comment by slodki** [comment]
I know nothing about portableapps.
You can download portable MMEX from [GitHub Releases](https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.4.0-alpha.4) as ZIP ready to run.
