### ISSUE TITLE
Bug: Unable to open encrypted emb file of v 1.3.3 on latest 1.4 alpha 4

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#1760]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue for similar problem - update existing issue instead of creating new one.
> 3. Put some descriptive name for your issue in the Title field above.
> 4. Replace this text (marked with >) with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 5. Include steps to reproduce your issue, attach screenshots where appropriate.
> 6. Please do not remove information attached below this text.

<hr><small><b>Version</b>: 1.4.0-alpha.4 • db 13 (aes128cbc) • git ccd9d829 (2018-08-16)<br><b>Libs</b>: wxWidgets 3.1.1 (wxMSW 10.0) • wxSQLite3 4.0.4 (SQLite 3.24.0) • Mongoose 6.12 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.59.0-DEV • WinSSL<br><b>Build</b>: Aug 16 2018 01:11:17 • CMake 3.11.3 • MSBuild 15.7.180.61344 • gettext 0.19.8.1 • Microsoft Visual Studio 15.0 • Microsoft Visual C   19.14.26433.0 • Windows SDK 10.0.14393.0<br><b>OS</b>: Windows 10 (build 17738), 64-bit edition •  (windows-1252) • 1366x768 32bit 84x84ppi</small>

I get the following error. I have added Indian currency if that helps debug.

![screenshot_20180816_153723](https://user-images.githubusercontent.com/12392746/44202846-bd56fc80-a16a-11e8-9781-44092040ad3a.png)

**Comment by slodki** [comment]
#1578 
[Upgrade to 1.4.0 problems](https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems)
