### ISSUE TITLE
Android Pie sync to cloud storage not working

### ISSUE THREAD

**Issue by Timp58** [moneymanagerex/moneymanagerex#1762]
My Pixel XL has been upgraded to Android P.  The downwards sync of the database from cloud storage works fine but trying to upload the changed database back to Google drive or One drive does not work.  The process reports its has been successful on the phone but when the database is opened on the PC the changes are not there.

**Comment by gabriele-v** [comment]
Moved to https://github.com/moneymanagerex/android-money-manager-ex/issues/1247
Please follow updates there.
