### ISSUE TITLE
Cannot set "home screen" summaries to "expanded" state

### ISSUE THREAD

**Issue by 48mWsPK** [moneymanagerex/moneymanagerex#1774]
**Describe the bug**
Upgraded from previous (0.9.x.x) version; Home screen accounts summaries are now "folded" - how to get MMEX to show them "expanded"?

**To Reproduce**
Start MMEX 1.4.0-alpha+ and see home screen of updated DB. To see all data I have to click the "+" icon on each "Balance" column...

**Expected behavior**
Probably option in "Settings" dialog to make possible changing default/desired state of "Home screen" accounts, or something during DB upgrade to fix problem...

**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [X] 1.4.x - 1.4.0-alpha.6, Git commit: dd01f5ac (2018-08-20)
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by gabriele-v** [comment]
Latest MMEX versions save the status of account summaries, so if you expand it and then close MMEX,
next time you open it's already expanded.
The same, if you close MMEX with it collapsed, then next time will be collapsed.
