### ISSUE TITLE
Update status for 2 characters transfer

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#1775]
We should release a patch for https://github.com/moneymanagerex/database/issues/32 and consequently drop support in model (if exists) for 1 character transfer.
I think it's the right time to do it before official 1.4.0 that will anyway beak android compatibility because of table name changes.

**Comment by slodki** [comment]
Maybe old behavior (from #1773) should be default for 1.4.0 release? If old database will be auto converted to new statuses user won't be warned...

**Comment by gabriele-v** [comment]
Agree that have be fixed for 1.4.0 but we should have just one DB model with 2 characters, we cannot support both 1 and 2 characters in DB for transfers, because it will mean different SQL reports etc..

If global option "reconcile transfers separately" is disabled (default) then
- Single character shown in the GUI (but still 2 characters in DB that will always be equal)
- Reconcile as previous mmex versions
If it's enabled:
- Two characters shown in the GUI (and obviously in DB)
- Reconcile as actually in master
