### ISSUE TITLE
Filtering statuses using Transaction report problems

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1777]
Test case:
![mmex](https://user-images.githubusercontent.com/3155552/44509890-5b8b1b00-a6b3-11e8-9f31-763fa066a035.png)

Filtering for status = none: two transactions are missing (7 & 9):
![mmex2](https://user-images.githubusercontent.com/3155552/44509942-82e1e800-a6b3-11e8-9e04-ad8a20810716.png)

Filtering for status = reconciled: 6th transaction is missing:
![mmex3](https://user-images.githubusercontent.com/3155552/44510076-e0763480-a6b3-11e8-9f3e-6679185b78fa.png)

Filtering for status = void: 5th transaction is missing:
![mmex4](https://user-images.githubusercontent.com/3155552/44510322-ac4f4380-a6b4-11e8-8924-e21b461310ba.png)

Filtering for status = all except reconciled: two transactions are missing (5 & 7):
![mmex5](https://user-images.githubusercontent.com/3155552/44510472-10720780-a6b5-11e8-9e78-5d2c344a5e03.png)

Related to #1180 and #1208? All withdrawals are reported OK.

<hr><small><b>Version</b>: 1.4.0-alpha.6 • db 13 (aes128cbc) • git dd01f5ac (2018-08-20) master<br><b>Libs</b>: wxWidgets 3.1.1 (wxGTK 2.24) • wxSQLite3 4.0.4 (SQLite 3.24.0) • Mongoose 6.12 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.58.0 • OpenSSL 1.1.0g • zlib 1.2.11 • libidn2 2.0.4 • libpsl 0.19.1 • ( libidn2 2.0.4) • nghttp2 1.30.0 • librtmp 2.3<br><b>Build</b>: Aug 21 2018 08:51:45 • CMake 3.10.2 • GNU Make 4.1 • gettext 0.19.8.1 • GCC 7.3.0 • Ubuntu 18.04 'bionic'<br><b>OS</b>: Ubuntu 18.04.1 LTS "bionic" • Linux 4.15.0-32-generic x86_64 • KDE Polish (UTF-8) • 1680x1050 24bit 96x96ppi</small>

**Comment by slodki** [comment]
This should be rewritten?
https://github.com/moneymanagerex/moneymanagerex/blob/dd01f5acb7aae7b51a3fafb1362c87106422c8ad/src/filtertransdialog.cpp#L576

BTW: It's unclear for me what is difference between "Un-Reconciled" and "All Except Reconciled". We should rename this to something easy to understand.
```c
else if ("U" == filterStatus) // Un-Reconciled
{
    return "" == itemStatus || "F" == itemStatus;
}
```

**Comment by gabriele-v** [comment]
Maybe could be renamed to "To be reconciled (Status N&F)"  ?
"All except reconciled" could stay as is.

**Comment by vomikan** [comment]
Is status 'NR' has sense? I mean in real live for transfer A->B if some transfer not reconcilled in account A but reconcillen in account B?

**Comment by vomikan** [comment]
IMHO the bug is invalid.
In case if account not selected in a filter settings used first status. In the sample above trx#7 is R.
I can't reproduce the issue with trx#9.

And Voids work for me as expected (based on my logic).

**Comment by gabriele-v** [comment]
See #1773

**Comment by vomikan** [comment]
Regarding "Un-Reconciled" and "All Except Reconciled"...
What an empty or None status mean? Seems it's the same as  "Un-Reconciled".

"All Except Reconciled" it's all others but not R.

**Comment by slodki** [comment]
@vomikan 
User has created 2 transfers between accounts: A&rarr;B and B&rarr;A and marked them both for future inspection while listing transactions on A account. There will be FN and NF statuses.
He will find only one transaction while searching for F status (FN, A&rarr;B). If he change filter to search only for B account different one transaction will be listed.

"status=X and account=Y" filter cannot return more transactions then "status=X" filter.
"filter uses only first status field" logic is not acceptable.

**Comment by vomikan** [comment]
```    else if ((itemStatus.empty() || "N" == itemStatus || "F" == itemStatus) && filterStatus == "U") // Un-Reconciled```
Now Un-Reconciled it's N & F 
A bit stuped.

**Comment by slodki** [comment]
Expected bahviour:

| transaction | status | account: none</br>status: R | account: A</br>status: R | account: B</br>status: R |
|---|---|:-:|:-:|:-:|
| A &rarr; out | F 
| A &rarr; out | R | :heavy_check_mark: |:heavy_check_mark:
| A &larr; in | F
| A &larr; in | R | :heavy_check_mark: |:heavy_check_mark:
| B &rarr; out | F
| B &rarr; out | R |:heavy_check_mark: ||:heavy_check_mark:
| B &larr; in | F
| B &larr; in | R |:heavy_check_mark: ||:heavy_check_mark:
| A &rarr; B | FF
| A &rarr; B | FR | :heavy_check_mark: ||:heavy_check_mark:
| A &rarr; B | RF | :heavy_check_mark::hammer_and_wrench: |:heavy_check_mark:
| A &rarr; B | RR | :heavy_check_mark: |:heavy_check_mark:|:heavy_check_mark:
| B &rarr; A | FF
| B &rarr; A | FR |:heavy_check_mark::hammer_and_wrench:|:heavy_check_mark:
| B &rarr; A | RF | :heavy_check_mark:||:heavy_check_mark:
| B &rarr; A | RR | :heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:

:hammer_and_wrench: marks transactions should be reported but are not - this should be fixed
First filter must be logical sum of the next two more detailed filters.

![mmex1](https://user-images.githubusercontent.com/3155552/47589157-99811580-d968-11e8-81f9-4937969b40bc.png)

![mmex2](https://user-images.githubusercontent.com/3155552/47589167-9f76f680-d968-11e8-9b13-05792c1b1c9e.png)

**Comment by vomikan** [comment]
It's should work now
