### ISSUE TITLE
Restored Database from backup, problem with OLE Automation

### ISSUE THREAD

**Issue by PaulDarnell** [moneymanagerex/moneymanagerex#1788]
**Describe the bug**
I have just had to restore my files from a backup after a computer rebuild. I opened the database and the cursor just flashes on the home page. If I go to an account it just returns to the home page. I can see the graphs updating in time with the flashing. It then returns string of errors OLE Automation error in Navigate: error code 0 (see attached) 

**To Reproduce**
Open MM

**Expected behavior**
I expect the screen to be stable

**Your OS:**
- [ ] Windows 10 1803

**MMEX version:**
- [ ] 1.4.x

[MoneyManager Problem.txt](https://github.com/moneymanagerex/moneymanagerex/files/2332925/MoneyManager.Problem.txt)

**Comment by slodki** [comment]
Home page in MMEX is rendered using Windows internal IE engine - OLE Automation error can be related to communication problem between MMEX and IE.
Account panel (transaction list) is not using IE webview - I think db file can be corrupted making impossible to display account data - in details and summary at home page.
