### ISSUE TITLE
"nightly" should not be a git tag

### ISSUE THREAD

**Issue by alerque** [moneymanagerex/moneymanagerex#1796]
Please don't tag the repository with transient data. The recently added [nightly](https://github.com/moneymanagerex/moneymanagerex/releases/tag/nightly) tag should not be a git tag. Git tags should be reserved for non-moving targets, things that stay the same. V1.3.1 is always going to point to the same git commit.

If you want a nightly build system it should build on HEAD and be released somewhere else. It can be labeled nightly somewhere else where the links always update to point to the latest build.

**Comment by slodki** [comment]
Why? Could you describe your problem with mmex here?
There is no restriction for using tags for temporary marking a pint in git history.

Our build system builds on HEAD. Why should it be released somewhere else? GitHub links always update to the latest build.

Do you have any proposal or PR?
