### ISSUE TITLE
Unable to install on Linux Mint 19 Cinnamon (based on the Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#1801]
[Installing MoneyManagerEx For Ubuntu 16.04 [LTS] Xenial](https://packagecloud.io/moneymanagerex/moneymanagerex) does not work with [Linux Mint 19](https://www.linuxmint.com/rel_tara_cinnamon.php). Linux Mint 19 is based on [Ubuntu 18.04 LTS](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes). Could you please update the instructions to install MoneyManagerEx on the latest Ubuntu LTS?  Thank you

> The repository 'https://packagecloud.io/moneymanagerex/moneymanagerex/linuxmint tara Release' does not have a Release file.

![image](https://user-images.githubusercontent.com/17465872/45085699-b35e6300-b144-11e8-92a4-9aeb9404fc08.png)

**Comment by slodki** [comment]
Please follow https://packagecloud.io/moneymanagerex/moneymanagerex/install#manual-deb using `ubuntu` and `bionic` as the params.

**Comment by slodki** [comment]
Linux Mint users should run the following command to add MMEX repo with Ubuntu packages:
```sh
curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh | os=ubuntu dist=xenial sudo -E bash
```
for Linux Mint 18.x, or
```sh
curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh | os=ubuntu dist=bionic sudo -E bash
```
for Linux Mint 19.x.

`os=xxx dist=yyy` before `sudo -E` will force specific distribution and skip auto-detection.
