### ISSUE TITLE
Distribute MMEX as deb package

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#1805]
Please add a `deb` file to the [MMEX Download page](https://www.moneymanagerex.org/download) so that MMEX does not need to be complied from the source code. The `deb` file will also enable installation on desktop and laptop computers with no internet connection required.

Examples of other software programs which allow `deb` file downloads are:
* [LibreOffice](https://www.libreoffice.org/download/download/?type=deb-x86_64&version=6.1.0&lang=en-GB)
* [Manager](https://www.manager.io/desktop/download/)

Thank you

**Comment by slodki** [comment]
There are many deb packages already avaiable for the next (not finished yet) MMEX version 1.4.0 - please read [INSTALL.md](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md) file.

We should update website instructions too - as described in #1169
