### ISSUE TITLE
GitHub error when using Help menu item "Report a Bug"

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#1807]
**Describe the bug**
GitHub error when using Help menu to 'Report a Bug'

**To Reproduce**
1. No web browser open and not signed into GitHub.
2. MMEX → Menu Bar → Help → Report a Bug
3. Error
`https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fmoneymanagerex%2Fmoneymanagerex%2Fissues%2Fnew%3Fbody%3D%253e%2520Please%2520follow%2520these%2520tasks%2520before%2520submitting%2520new%2520bug%3A%250a%253e%25201.%2520Use%2520Help-%253eCheck%2520for%2520Updates%2520in%2520MMEX%2520to%2520get%2520latest%2520version%2520-%2520your%2520problem%2520can%2520be%2520fixed%2520already.%250a%253e%25202.%2520Search%2520https%3A%2F%2Fgithub.com%2Fmoneymanagerex%2Fmoneymanagerex%2Fissues%3Fq%3Dis%3Aissue%2520for%2520similar%2520problem%2520-%2520update%2520existing%2520issue%2520instead%2520of%2520creating%2520new%2520one.%250a%253e%25203.%2520Put%2520some%2520descriptive%2520name%2520for%2520your%2520issue%2520in%2520the%2520Title%2520field%2520above.%250a%253e%25204.%2520Replace%2520this%2520text%2520%28marked%2520with%2520%253e%29%2520with%2520detailed%2520description%2520of%2520your%2520problem.%250a%253e%2520Read%2520https%3A%2F%2Fwww.chiark.greenend.org.uk%2F~sgtatham%2Fbugs.html%2520for%2520useful%2520tips.%250a%253e%25205.%2520Include%2520steps%2520to%2520reproduce%2520your%2520issue%2C%2520attach%2520screenshots%2520where%2520appropriate.%250a%253e%25206.%2520Please%2520do%2520not%2520remove%2520information%2520attached%2520below%2520this%2520text.%250a%250a%253chr%253e%253csmall%253e%253cb%253eVersion%253c%2Fb%253e%3A%25201.4.0-alpha.6%2520%25e2%2580%25a2%2520db%252013%2520%28aes128cbc%29%2520%25e2%2580%25a2%2520git%2520122cf75e%2520%282018-09-05%29%253cbr%253e%253cb%253eLibs%253c%2Fb%253e%3A%2520wxWidgets%25203.0.4%2520%28wxGTK%25203.22%29%2520%25e2%2580%25a2%2520wxSQLite3%25204.0.4%2520%28SQLite%25203.24.0%29%2520%25e2%2580%25a2%2520Mongoose%25206.12%2520%25e2%2580%25a2%2520RapidJSON%25201.1.0%2520%25e2%2580%25a2%2520Lua%25205.3.3%2520%25e2%2580%25a2%2520libcurl%25207.58.0%2520%25e2%2580%25a2%2520OpenSSL%25201.1.0g%2520%25e2%2580%25a2%2520zlib%25201.2.11%2520%25e2%2580%25a2%2520libidn2%25202.0.4%2520%25e2%2580%25a2%2520libpsl%25200.19.1%2520%25e2%2580%25a2%2520%28%2Blibidn2%25202.0.4%29%2520%25e2%2580%25a2%2520nghttp2%25201.30.0%2520%25e2%2580%25a2%2520librtmp%25202.3%253cbr%253e%253cb%253eBuild%253c%2Fb%253e%3A%2520Sep%25205%25202018%252022%3A47%3A17%2520%25e2%2580%25a2%2520CMake%25203.10.2%2520%25e2%2580%25a2%2520GNU%2520Make%25204.1%2520%25e2%2580%25a2%2520gettext%25200.19.8.1%2520%25e2%2580%25a2%2520GCC%25207.3.0%2520%25e2%2580%25a2%2520Ubuntu%252018.04%2520%2527bionic%2527%253cbr%253e%253cb%253eOS%253c%2Fb%253e%3A%2520Linux%2520Mint%252019%2520Tara%2520%2522tara%2522%2520%25e2%2580%25a2%2520Linux%25204.15.0-33-generic%2520x86_64%2520%25e2%2580%25a2%2520English%2520%28Australia%29%2520%28UTF-8%29%2520%25e2%2580%25a2%25201920x1848%252024bit%252096x95ppi%253c%2Fsmall%253e`
![image](https://user-images.githubusercontent.com/17465872/45214274-5813a880-b2dd-11e8-9054-27e41c68820d.png)

**Expected behavior**
No error on GitHub when 'Report a Bug'.

**Screenshots**

**Additional context**
Error does not seem to happen if signed into GitHub before 'Report a Bug'

**Your OS:**
- [x] Linux Mint 19 Cinnamon 64-bit

**MMEX version:**
- [x] 1.4.0-alpha.6

**Comment by slodki** [comment]
GitHub login page should be presented and issue form loaded after successful login. See url structure:
> https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fmoneymanagerex%2Fmoneymanagerex%2Fissues%2Fnew%3Fbody

It should *login* then *return to* /issues/new with preloaded info...

**Comment by ovari** [comment]
Thank you

**Comment by slodki** [comment]
But this not work as expected at GitHub side. I will investigate this... It must be working for not logged-in users

**Comment by vomikan** [comment]
May be rhis article will help?
https://developer.github.com/v3/issues/#create-an-issue

**Comment by vomikan** [comment]
Workaround provided:

![image](https://user-images.githubusercontent.com/6836805/58762932-c5e3bc80-855d-11e9-93f0-4b3ac094cb50.png)
