### ISSUE TITLE
Hide or close accounts

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#1808]
**Is your feature request related to a problem? Please describe.**
Account feature requests:
- [x] Hide or close an account
- [x] View previously hidden accounts in the Account List
- [x] Unhide an account

**Describe the solution you'd like**
There many reasons, personal and practical, why you might want to change the way an account is displayed in MMEX. Providing a great set of options and a lot of flexibility to set things up just the way you want is needed.

**Describe alternatives you've considered**
[Quicken: How do I Hide or Close an Account?](https://www.quicken.com/support/how-do-i-hide-or-close-account)

Thank you

**Comment by slodki** [comment]
To open/close an account or mark as favorite use `Accounts` &rarr; `Edit Account` and change *Account Status* or *Favorite Account* checkbox. Icon in nav tree will update after change.

You can filter accounts displayed in nav tree using `Tools` &rarr; `Options...` &rarr; `View Options` and changing *Account Visible* drop down list selection - possible values are: All / Open / Favorites.

**Comment by ovari** [comment]
Thank you

**Comment by lucaritossa** [comment]
Is this still valid? 
I can't find the option to show only open/favorites account and let hidden the closed account.
