### ISSUE TITLE
Crashes on Mac unless you don't use it right away

### ISSUE THREAD

**Issue by rjdeible-github** [moneymanagerex/moneymanagerex#1816]
On Imac Late 2015 model I have been experiencing crashes which seem to happen if I try to make a entry right after I open the application.  I has happened once after it had been open for about five minutes but I was moving around in the program a 
lot.  Usually it happens when I try to make a entry or a reoccurring entry but a couple times (2 or 3) it happened when I opened it and tried to view a report or the reoccurring transactions page.  I am not getting any error messages the program just shuts down and a message comes up asking if I want to report it and reopen the program.  I am uploading two crash logs my oldest and newest one.
[MMEX_2018-08-19-093401_Imac1.txt](https://github.com/moneymanagerex/moneymanagerex/files/2386724/MMEX_2018-08-19-093401_Imac1.txt)
[MMEX_2018-09-06-203204_Imac1.txt](https://github.com/moneymanagerex/moneymanagerex/files/2386725/MMEX_2018-09-06-203204_Imac1.txt)

**Comment by slodki** [comment]
What MMEX version are you using?

The crash is caused by refreshing transaction list (`TransactionListCtrl::~TransactionListCtrl()`) in timer event (`mmGUIFrame::OnAutoRepeatTransactionsTimer()`):
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff672b3b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6747e080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff6720f1ae abort + 127
3   libsystem_malloc.dylib        	0x00007fff6730d822 free + 521
4   com.yourcompany.MMEX          	0x000000010d9f9ad9 wxWindowBase::DestroyChildren() + 25
5   com.yourcompany.MMEX          	0x000000010d8aea9f wxWindow::~wxWindow() + 335
6   com.yourcompany.MMEX          	0x000000010d45c77e TransactionListCtrl::~TransactionListCtrl() + 14
7   com.yourcompany.MMEX          	0x000000010d9f9ad9 wxWindowBase::DestroyChildren() + 25
8   com.yourcompany.MMEX          	0x000000010d8aea9f wxWindow::~wxWindow() + 335
9   com.yourcompany.MMEX          	0x000000010da226a5 wxSplitterWindow::~wxSplitterWindow() + 69
10  com.yourcompany.MMEX          	0x000000010d9f9ad9 wxWindowBase::DestroyChildren() + 25
11  com.yourcompany.MMEX          	0x000000010d8aea9f wxWindow::~wxWindow() + 335
12  com.yourcompany.MMEX          	0x000000010d4521ee mmCheckingPanel::~mmCheckingPanel() + 14
13  com.yourcompany.MMEX          	0x000000010d490af3 mmGUIFrame::cleanupHomePanel(bool) + 35
14  com.yourcompany.MMEX          	0x000000010d4905d7 mmGUIFrame::createHomePage() + 615
15  com.yourcompany.MMEX          	0x000000010d481595 mmGUIFrame::OnAutoRepeatTransactionsTimer(wxTimerEvent&) + 2101
16  com.yourcompany.MMEX          	0x000000010d473949 mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const + 25
```

Do you have any recurring transactions defined in this db? Are you using WebApp in MMEX?
Are there any transactions displayed at right panel just before crash or list is empty?

**Comment by whalley** [comment]
I can't reproduce this and have never encountered it.
