### ISSUE TITLE
Il file MMEX crittografato .emb non viene riconosciuto valido dall'Applicazione per Android.

### ISSUE THREAD

**Issue by gianni5252** [moneymanagerex/moneymanagerex#1818]
Uso MMEX 1.3.3. ed ho provato, dopo aver scaricato l'App per Android versione 4.2, di sincronizzare il file con estenzione .emb ma questo file non viene riconosciuto come valido per cui non lo posso utilizzare.
Se invece il file MMEX non è crittografato  allora viene regolarmente aperto. Ovviamente, per la sicurezza 
 e riservatezza dei dati contenuti nel file, non posso usare sul Pc l'estensione .mmb

S.O. Windows 10 aggiornato
Versione MMEX 1.3.3.

Grazie   Gianni

**Comment by slodki** [comment]
Encrypted databases are not supported by MMEX Android application. It can be implemented in the Android project in he future. See moneymanagerex/android-money-manager-ex#135.
