### ISSUE TITLE
Duplicate transfer transaction should not be in advanced

### ISSUE THREAD

**Issue by hkdennis2k** [moneymanagerex/moneymanagerex#1829]
**Describe the bug**
When duplicate a transfer transaction, without using advanced)
The result transaction should be simple and having same amount in both in/out accounts.

Which is broken since for a while that,  even the checkbox is not checked.
The result transaction be saved in advanced mode and the amount in destination account has unexpected value saved.

**To Reproduce**
1. Setup two accounts A and B
2. Create a transaction A to B with $1
3. Create second transaction A to B with $2
4. Close and restart MMEX
5. Right-click on the first transaction. Select "duplicate transaction"
6. Ensure it is not "advanced" and update amount as $3.    
7. Click OK to clone

**Expected behavior**
After step 5, advanced checkbox sometime is checked unexpected with a value.
After step 7, check the third transaction. It could be in advanced with various value 

**Screenshots**

**Additional context**

**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [X] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

1.3.3

**Comment by vomikan** [comment]
I can.t reproduce this issue in v.1.4.0
