### ISSUE TITLE
Cryptocurrency portfolio tracker with updates from Coinmarketcap/Livecoinwatch

### ISSUE THREAD

**Issue by Dooli02** [moneymanagerex/moneymanagerex#1834]
**Describe the solution you'd like**
At the moment ive seen that you can create a stock portfolio which you can include bitcoin by using the stock symbol from Yahoo.
Is it possible to not rely on Yahoo for Bitcoin pricing and to expand the cryptocurrency portfolio for other coins as well to update from Coinmarketcap or livecoinwatch by using their api to get a round about price figure?
I think if you had to include the api pricing from each and every exchange, would be quite tiresome and getting an estimated price from Coinmarketcap or livecoinwatch would be much simpler.

If i create a new account and choose Crypto, it creates it as 'crypto wallets', but i see no way to create transactions that will include something simple like:
- Crypto name bought
- Crypto Symbol (auto-completes when typing it)
- Price bought/sold at
- Date bought/sold at
- Have the crypto update its current price live on its own every x minutes and show whether you are at a loss or profit for that certain cryptocurrency.
- Notification for when price increases for that crypto transaction you made.
- Notification for price alerts for all cryptos that will check Coinmarketcap or livecoinwatch

The only transactions you can create in a crypto account is withrawal/deposit/transfer like a normal checking account.

If im not mistaken at the moment i dont see any feature like this, and would be really useful to have.
If there is something like this and ive completely missed it, please could you point me where to set it up?

Using latest version 1.4.0-Alpha 6-1

**Comment by tmlee** [comment]
For cryptocurrency data, may i suggest our API at coingecko.com/api
Happy to answer any concerns or questions you may have

**Comment by vomikan** [comment]
MMEX used "https://coincap.io/front"; for crypto currencies since v. 1.4.0.

![image](https://user-images.githubusercontent.com/6836805/47573415-eef7fb00-d945-11e8-87c0-9312d540b5d4.png)

**Comment by slodki** [comment]
You can use transfers between your USD and crypto accounts to track amount and price for exchange transactions made.
You can always display your crypto account value in base currency - calculated from the latest online rates.

**Comment by s33rd** [comment]
> You can use transfers between your USD and crypto accounts to track amount and price for exchange transactions made.
> You can always display your crypto account value in base currency - calculated from the latest online rates.

@slodki can you please explain how exactly to do this??
- I created a Crypto account called BTC_Test with currency BTC
- The base currency is EUR
- A transaction of deposit/withdrawal was made of 0.001 BTC
How exactly can i see a field with the displayed value in EUR?

**Comment by slodki** [comment]
1. Open EUR account in the right panel
2. Add new transaction using `New` button from the bottom toolbar
   - set transaction type to `Transfer`
   - set your EUR account as `From` (should be already set)
   - set your bitcoin account as `To`
   - select `Advanced` checkbox
   - enter EUR amount in the first and the BTC amount in the second field in `Amount` line
3. Your transaction will be visible in both acoounts with xchg rate defined during step above
4. If you want to display estimated bitcoin value in base currency you should
   - verify latest values for BTC are downloaded in `Currency dialog`'s right panel
   - right click on BTC account in nav tree then select `Foreign Currency Balance` option - account's balance will be displayed using EUR and BTC currencies.

**Comment by dckc** [comment]
I see how to get ETH prices, but what about ATOM? The currency dialog only seems to allow 3 characters in the symbol field.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/currencydialog.cpp#L171

**Comment by vomikan** [comment]
When I've changed max length for the currency symbol ATOM starts working.
![image](https://user-images.githubusercontent.com/6836805/70526863-94c2f500-1b5b-11ea-98b8-3d677c64dc9f.png)
What is a proper amount should be here?

**Comment by vomikan** [comment]
I've committed 6
