### ISSUE TITLE
Installing mmex on Kubuntu 18.04

### ISSUE THREAD

**Issue by p2635** [moneymanagerex/moneymanagerex#1841]
I am a newb trying to install: https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md. I am not very technical so I was hoping someone would help me through this... It says stuff about Docker which I don't even have installed?

I want to try this out, I couldn't find it in 'Discover' on Kubuntu? I even tried running sudo apt install moneymanagerex/mmex...

**Comment by slodki** [comment]
Try [INSTALL.md](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md#linux) instructions first.

**Comment by slodki** [comment]
Duplicate of  #1169

**Comment by p2635** [comment]
Thanks.. didn't even see that bit.

**Comment by slodki** [comment]
There is error at webpage linking to BUILD instructions (for developers) in place of INSTALL (for end users).
