### ISSUE TITLE
Strange characters

### ISSUE THREAD

**Issue by p2635** [moneymanagerex/moneymanagerex#1842]
**Describe the bug**
Seems to be weird characters when I open mmex.

**To Reproduce**
1. Open MMEX

**Expected behavior**
Able to see something human?

**Screenshots**
![image](https://user-images.githubusercontent.com/4522927/46629837-18d5b300-cb3a-11e8-91e3-b9988895a9e5.png)

**Additional context**
OS is in Japanese.

**Your OS:**
Kubuntu Linux 18.04

**MMEX version:**
Appears to be 1.4.0-alpha.6

**Comment by slodki** [comment]
You can start MMEX from the terminal window using `LANG=C mmex` command to switch to English. You can replace `C` with any locale installed on your computer.

Do you use UTF-8 locale?

**Comment by p2635** [comment]
LANG=en mmex seems to work for me, but its going to be annoying to keep having to execute it like that unless I create a shortcut or something. And the answer to the second question... I don't know, how do I know if I'm using that locale?

**Comment by slodki** [comment]
You can easily [change MMEX language from menu](https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems#translation-cannot-be-loaded) - using LANG variable is a workaround for the first run only.

The reason for the strange characters can be:
- no fonts installed for selected language
- locale setting not matched to fonts encoding
- untranslated MMEX texts and problem with displaying English (?)

**Comment by p2635** [comment]
Thanks @slodki, the support here is super fast. I will try those, I think I will close this as you've done more than enough!
