### ISSUE TITLE
MMEX website: captcha doesn't show up in contact form

### ISSUE THREAD

**Issue by Kaligule** [moneymanagerex/moneymanagerex#1850]
**Describe the bug**
I want to fill in the contact form on the website. It seems like a captcha is required, but no captcha is provided.
(I didn't find a better place to file this issue, I am happy to resubmit it on a different place if you point me to it.)

**To Reproduce**
1. Go to 'https://www.moneymanagerex.org/about/contact'
2. No captcha shows up (see screenshot)

**Expected behavior**
No captcha is needed or there is a captcha to solve.

**Screenshots**
![no_captcha](https://user-images.githubusercontent.com/3586246/47339127-8b967080-d69a-11e8-99ee-31a3f2a64971.png)

**Additional context**
I tried in multiple browsers (eg chromium) and had no adblock enabled.

**Your OS:**
Linux

**Comment by sanecito** [comment]
Also came here to report this. Also confirmed on Windows 10 Ent and Manjaro KDE across IE11, Chrome, and Firefox. @gabriele-v since you seem to be assigned is there a recommended workaround to contact in the interim for questions (i.e. donating to enable librem5 support)?

**Comment by whalley** [comment]
Contact form not present on new site.
