### ISSUE TITLE
Q: whether to remove an internal web server from the next version?

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1852]
Do you really use this feature?

It can send homepage panel content to your browser without the ability to follow links or display more details. MMEX app must be running, TCP port opened for access from different computer and IP address of the computer running MMEX entered into a web browser. Some security aspects were discussed in #893 already.

After #1831 and #1851 internal MMEX web server (based on Mongoose) can be easily removed from sources.
Existing code can be preserved in a separate branch for future development and removed from the master branch.

**Comment by slodki** [comment]
Home panel displayed in MMEX window:
![mmex1](https://user-images.githubusercontent.com/3155552/47443995-c4773800-d7b5-11e8-94c0-9798790071f6.png)

Th same home panel displayed in a web browser using the internal web server:
![mmexweb](https://user-images.githubusercontent.com/3155552/47444004-ca6d1900-d7b5-11e8-8087-aacb6bcadf02.png)

**Comment by vomikan** [comment]
Seems js has disabled in external brouser.
