### ISSUE TITLE
Transaction report does not work since last update

### ISSUE THREAD

**Issue by stantheman1** [moneymanagerex/moneymanagerex#1857]
<small><b>Version</b>: 1.4.0-Alpha.3 ⬥ db 7 ⬥ git 79562d4 (2017-08-11)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 10.0) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Aug 11 2017 11:55:37 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 10 (build 17134), 64-bit edition Little endian ⬥ English windows-1252 ⬥ 1280x1024x32bit 96x96ppi</small>

**Comment by slodki** [comment]
Please verify with the latest alpha.6 or describe what is not working.

**Comment by stantheman1** [comment]
Hi
It was a computer issue.  Everything now working ok.
Thank you.
S.Pearce
