### ISSUE TITLE
Transaction Report Filter not working

### ISSUE THREAD

**Issue by MartinGarside** [moneymanagerex/moneymanagerex#1864]
![image](https://user-images.githubusercontent.com/44744937/47963146-b3cd8a00-e01f-11e8-86f9-1e29a33cc41d.png)
![image](https://user-images.githubusercontent.com/44744937/47963161-03ac5100-e020-11e8-81e9-e5f8e03b8c34.png)
1st screen shot shows set up for information request. Second screen shot shows results. This should have thrown up several transaction but shows nothing I have checked for the latest up date and I have it. This happen on any request I make and has been an on going issue for several months now,  I believe since the last up grade as I used to be able to retrieve the information. Was hoping you would notice and resolve the issue.

**My OS:**
Windows 10

**MMEX version:**
![image](https://user-images.githubusercontent.com/44744937/47963252-28ed8f00-e021-11e8-99c0-248d86d0102a.png)

**Comment by MartinGarside** [comment]
Looked deeper into this the ‘Transaction Report filter’ works until you set a date period then nothing is thrown up. I am working through entering more than one filter, but so far it works until a date criteria is set and that is one of the most important filters. I am unsure if this is the answer as in the Transactions filter dates are shown as 8 digit dated (07/11/2018), but in the account item listing they are shown as 6 digit (07/11/18). I am going to look at the date format to see if it can be changed

 

Mr Martin.G.G.Garside

66 Walton Green

New Addington

Surrey CR0 0TW

Hme. 01689 846674

Mbl. 07854 394348

e mail. Martin.g.g@blueyonder.co.uk

**Comment by MartinGarside** [comment]
Further to my last message had a go at downloading the portable version but hit a buffer as was being asked to subscribe/buy win zip. Not entitled to trial as used that about 18mths back (once only)and will not pay for something I used once a year or less with what they are charging. I don’t mind subscribing to your software as I am a frequent user and do give periodically donations as it a great product. Also the version that is on offer via the download in lower than the one you are suggesting. I would hope that if I did manage to download it I could upgrade it?. I also noticed that you do versions for Mac and android but nothing for iPad. Is something in the pipeline

Sent from my iPad
Martin G Garside

**Comment by slodki** [comment]
@MartinGarside Please verify your Windows have no malware installed - downloading zip file on fresh Windows installation doesn't ask for additional software installation. This can be misconfigured your web browser or Windows Explorer configuration.
This is not MMEX related at all.

**Comment by slodki** [comment]
There where reports date filter was broken in v1.3.3 and fixed in v1.4.0 - see #1378.

**Comment by vomikan** [comment]
Outdated?
