### ISSUE TITLE
alldata view is blocking db upgrade to v10

### ISSUE THREAD

**Issue by Balgofil** [moneymanagerex/moneymanagerex#1865]
Hi,

I tried to upgrade from mmex 1.3.3 (Arch Linux standard version) to the git version (Arch Linux AUR package). I had run into the issues described in [Upgrade-to-1.4.0-problems](https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems). I fixed these issues with sqlitebrowser because with mmex I can't view the mmdbg files (as mentioned [here](https://sourceforge.net/p/moneymanagerex/bugs/927/)).

Now the db seems to be OK. But in the upgrade process I got the following error message:

>MMEX database upgrade to version 10 failed!
>
>Please restore DB from autocreated pre-upgrade backup and retry or contact
>MMEX support
>
>SQL logic error[1]: error in view alldata: no such table: main.currencyformats_v1 

Is there any solution to this issue?
Thanks

**Comment by slodki** [comment]
You can try manually `DROP VIEW IF EXISTS alldata;`

**Comment by Balgofil** [comment]
Thanks,
that solved the issue.
