### ISSUE TITLE
Report Assistance

### ISSUE THREAD

**Issue by MarcusGHub** [moneymanagerex/moneymanagerex#1867]
Just asking for some assistance with creating a report.

The report below shows me all the deposits made for the year 2018, from payee 'Tricia' with the word 'digicel' in the subcategory.

> select
> 	CHECKINGACCOUNT.TOTRANSAMOUNT as [AMOUNT],
> 	CHECKINGACCOUNT.TRANSDATE as [DATE],
> 	CHECKINGACCOUNT.NOTES
> from
> 	PAYEE,
> 	CHECKINGACCOUNT,
> 	SUBCATEGORY
> where
> 	PAYEE.PAYEEID=CHECKINGACCOUNT.PAYEEID
> 	and CHECKINGACCOUNT.SUBCATEGID=SUBCATEGORY.SUBCATEGID
> 	and PAYEE.PAYEENAME='Tricia'
> 	and CHECKINGACCOUNT.TRANSCODE='Deposit'
> 	and SUBCATEGORY.SUBCATEGNAME like '%digicel%'
> 	and CHECKINGACCOUNT.TRANSDATE>='2018-01-01'
> 	and CHECKINGACCOUNT.TRANSDATE<='2018-12-31'
> order by
> 	CHECKINGACCOUNT.TRANSDATE asc

She recently made a deposit with the word 'digicel' in the subcategory, but it's a split transaction. I'm not seeing that in the report. How do I account for split transactions?

Thanks in advance.

**Comment by slodki** [comment]
You can start from #1662 then filtering values returned

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/general-reports/tree/master/Withdrawals

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/general-reports/tree/master/PayeeTrend
