### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [moneymanagerex/moneymanagerex#1869]
i've downloaded Version '1.3.3' and 1.4 beta but when selecting it in the Finder and using 'Get Info' it shows Version '1.0'

responsible garbage entries from your Info.plist file:

```

    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
```

**Comment by slodki** [comment]
already fixed as #1441

**Comment by core-code** [comment]
perfect thanks

**Comment by core-code** [comment]
i can see things have improved. however the official 1.3.4 release has the CFBundleVersion '1.3.4rc7'

it seems things are still not really in-sync here
