### ISSUE TITLE
Compile error C2026 in DB_Upgrade.h after 958f9b6

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1872]
**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

Looks like the attached change
![db_upgrade](https://user-images.githubusercontent.com/24897056/48336445-307fea00-e658-11e8-9c23-e12bb0f72289.PNG)
has messed with string lengths and so has broken the 16380 single byte limit when using VS2017
All works well when replaced with previous DB_Upgrade.h. I guess DB_Upgrade.h was erroneously included as I cannot see any typos it is fixing.

**Comment by slodki** [comment]
Long string constants are split into smaller chunks for MSVC compiler and this must be preserved in sources:
https://github.com/moneymanagerex/moneymanagerex/blob/92dcabe247b241108436b372174f3d2b1f64515c/util/sqliteupgrade2cpp.py#L60
