### ISSUE TITLE
PCLoud 

### ISSUE THREAD

**Issue by freeTexas** [moneymanagerex/moneymanagerex#1876]
Android App constantly asking for PCLoud (?????????????????????) login. Don't have it , never will. If this continues, I'll go somehere else. Its not even an option to be ignored.

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [x] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by freeTexas** [comment]
Android App constantly asking for PCLoud (?????????????????????) login. Don't have it , never will. If this continues, I'll go somehere else. Its not even an option to be ignored.

**Comment by vomikan** [comment]
please report bugs to moneymanagerex/android-money-manager-ex repo!

**Comment by slodki** [comment]
See moneymanagerex/android-money-manager-ex#1270
