### ISSUE TITLE
Wrong JSON for CMakeSettings.json

### ISSUE THREAD

**Issue by scilganon** [moneymanagerex/moneymanagerex#1878]
**Describe the bug**
file has unsupported syntax (comments are denied)

https://stackoverflow.com/a/4183018

**Comment by vomikan** [comment]
Do you mean this line?
  // Дополнительные сведения об этом файле см. по адресу https://go.microsoft.com//fwlink//?linkid=834763.

**Comment by scilganon** [comment]
added fix #1879

**Comment by scilganon** [comment]
need to merge fix of fix :sweat_smile: #1880
