### ISSUE TITLE
Q: is it possible not to generate reports directly?

### ISSUE THREAD

**Issue by scilganon** [moneymanagerex/moneymanagerex#1883]
such request won't be the single #1859

is it possible to make a kind of report-gallery, which could be managed from GUI?

if someone wants to generate own report - just add its generator to gallery and run it

results will be available over webview (or external browser), 

the only things it requires:
 - clear API + docs (at least UML for db)
 - UI changes for storing gallery

**Comment by slodki** [comment]
There is General Report Manager to add any custom SQL report with HTML layout to MMEX and display it in app. There is also GitHub repo with additional reports ready to download...
Unecrypted MMEX database can be opened with any reporting tool with SQLite support.

**Comment by scilganon** [comment]
did not notice it :+1: 

could we raise advantages in `README.md` to prevent such questions? :sweat_smile: 

cause bunch of tech info overflows main info

**Comment by scilganon** [comment]
what about adding possibility of importing reports from repository directly? in such case user shouldn't know about git-repo and installation process

e.g., IntellijIdea with its plugins: 
 - install from repo
 - install from disk

**Comment by slodki** [comment]
There is info about additional reports available to users in README already (https://github.com/moneymanagerex/moneymanagerex#tips). We should add the link to MMEX documentation after link to INSTALL IMHO.

The repo needs redesign - reports must be linked to the db version supported.
Our db upgrade [scripts [fix already imported report definitions](https://github.com/moneymanagerex/database/blob/14aafa8b1d17212c5d41db474772888a42ddcdc3/incremental_upgrade/database_version_12.sql#L763) (SQL) but old report in GitHub repo is not fixed and will not work in new app version.
