### ISSUE TITLE
MMEX for Android cannot see database file in Dropbox

### ISSUE THREAD

**Issue by Timkendal** [moneymanagerex/moneymanagerex#1884]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue
> for similar problem - update existing issue instead of creating new one.
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.
> 4. Put some descriptive name for your issue in the Title field above.
> 5. Fill form below with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 6. Include steps to reproduce your issue, attach screenshots where appropriate.
> 7. Mark (put x inside brackets: [x]) correct answers below about your OS and MMEX version used.
> 5. Remove this text marked with >.

**Describe the bug**
I'm not sure if this is a bug or not!

I have MMEX running on my Imac (Mojave).  No problems.  The Database is in Dropbox/Apps/ Moneymanagerex Mobile, and is called Our Accounts.mmb

I have just downloaded the Android App from the App Store, and when I try to select the database, I get a message 

   The Database in Dropbox/Apps/ Money Manager Ex Mobile is empty ....

Notice the spaces which are not correct.

How do I point the app to the database please?  (or do I have to create a new Dropbox folder, and move the database?  Presumably I can tell the Desktop app where to find the database after I have done this.

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by scilganon** [comment]
could you reopen this bug in [here](https://github.com/moneymanagerex/android-money-manager-ex) and close this one according to 

> Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!
