### ISSUE TITLE
db v11 is not recognized by the beta version of android app

### ISSUE THREAD

**Issue by gianni5252** [moneymanagerex/moneymanagerex#1886]
Ho installato sullo smartphone Huawei P20 Lite con S.O Android  8.0. (Oreo) la versione Beta . Purtroppo il Database caricato da Dropbox non funziona perchè, seppur sincronizzandosi, non riconosce il Database versione 11 ma solo la versione 7 e quindi non apre il relativo file segnalando Errore. Purtroppo ho avuto l'infelice idea di passare sul computer dalla versione stabile 1.3.3. alla 1.4.0 Alpha 6 instabile non sapendo poi che l'applicazione Beta dello smartphone non avrebbe riconosciuto il cambiamento della versione del Database- Non c'è la possibilità di tornare alla versione 7 del Database e alla versione stabile 1.3.3. sia sul computer e sia sullo smartphone? Grazie   Giovanni Francesco De Giorgi

**Comment by slodki** [comment]
There is a separate issue for an android app: moneymanagerex/android-money-manager-ex#1245
