### ISSUE TITLE
Cash flow report crashes

### ISSUE THREAD

**Issue by alex-che** [moneymanagerex/moneymanagerex#1889]
When I select Reports->Cash Flow->Daily or Monthly the application crashes.

Debug report attached.

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

[MoneyManagerEx_dbgrpt-15664-20181207T171344.zip](https://github.com/moneymanagerex/moneymanagerex/files/2657549/MoneyManagerEx_dbgrpt-15664-20181207T171344.zip)

**Comment by slodki** [comment]
Extracted from debug report:
> `<system description="Windows 10 (build 17134), 64-bit edition"/>`
> `<module path="D:\programs\mmex-1.4.0-alpha.6-win32-portable\bin\mmex.exe" address="00350000" size="006ad000" version="1.4.0.0"/>`
> `<exception code="c0000005" name="ACCESS_VIOLATION" address="6631fbb6"/>`
> `<stack>
    <frame level="0" function="wxDateTime::ParseDate" offset="00000056"/>`

**Comment by slodki** [comment]
@alex-che Do you have an empty account (with no transactions) in the db? If yes - this error is already fixed in #1781

**Comment by alex-che** [comment]
@slodki exactly.
After I've added a transaction to the empty account, the crash is gone.
Thanks.

**Comment by vomikan** [comment]
real fix
https://github.com/moneymanagerex/moneymanagerex/issues/2047
