### ISSUE TITLE
editing more than one transaction

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1895]
when editing more than one transaction, selecting "transfer" in type, the payee is not selectable, also it does not allow manual input of my existing accounts.

https://forum.moneymanagerex.org/viewtopic.php?f=8&t=7827

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
This widget does not handle transfers.
Payee selector does not have "add new payee" option.
![image](https://user-images.githubusercontent.com/6836805/49857480-b633b880-fe03-11e8-8791-001540d27302.png)

**Comment by slodki** [comment]
But there is no Payee at all in the transfer transaction - only two accounts (from - to).
Transfer type transactions are broken in multiple places in MMEX - see #1863 for example.

**Comment by slodki** [comment]
Update multiple transactions feature results are undefined for transfers IMHO:
* Will selected status update both statuses of transfer or only one (from or to)?
* Which account will be the target when withdrawal/deposit transaction will be converted to transfer type?
* Will entered amount update source or target amount of transaction?
* Will the entered payee be ignored in case of transfer transaction?

**Comment by slodki** [comment]
It's also unclear what happens if I change amount and/or category in case of split transaction update using this feature.

**Comment by vomikan** [comment]
I've developed this tool before transfers has two statuses.
I think this tool ignore transfers if payee changed and also has other restrictions to save updated transactions valid.
But it's really unclear for users, agreed.

**Comment by vomikan** [comment]
related issue https://github.com/moneymanagerex/moneymanagerex/issues/1775
