### ISSUE TITLE
MMEX crashes without translation files while using wxWidgets 3.1.2

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1899]
When:
* `Model_Usage::pageview()`
* `Model_Report::get_html()`
* `mmHelpPanel::CreateControls()`
* `mmGeneralReportManager::showHelp()`
* `mmAppStartDialog::OnButtonAppstartHelpClick`

Why:
* wxWidgets/wxWidgets#1082

**Comment by gabriele-v** [comment]
Confirm fixed in wxWidgets 3.1.3
