### ISSUE TITLE
MMEX not supported by latest openSUSE release

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1903]
Missing webview in openSUSE Tumbleweed (as detected in #1331) impacts latest openSUSE Leap 15.0 release.
Support for wxgtk webview was removed in 2017 for 15.0 as described in [wxWidgets-3_2.changes](https://build.opensuse.org/package/view_file/openSUSE:Factory/wxWidgets-3_2/wxWidgets-3_2.changes):
> -------------------------------------------------------------------
> Sun Oct 15 11:33:14 UTC 2017 - kamikazow@opensuse.org
>
> - Disable WebView for TW and upcoming Leap 15.
>
> -------------------------------------------------------------------

**Comment by PMaff** [comment]
@slodki is this issue still valid?
See
https://github.com/moneymanagerex/moneymanagerex/issues/4154

**Comment by vomikan** [comment]
This case is possible outdated.

**Comment by whalley** [comment]
> This case is possible outdated.

Agreed. We have SUSE builds now. Closing
