### ISSUE TITLE
Generating Cash Flow reports crashes Application

### ISSUE THREAD

**Issue by Jimmyson** [moneymanagerex/moneymanagerex#1905]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue
> for similar problem - update existing issue instead of creating new one.
> 3. Use Help->Report a Bug in MMEX if possible - it will include details important for dev team.
> 4. Put some descriptive name for your issue in the Title field above.
> 5. Fill form below with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 6. Include steps to reproduce your issue, attach screenshots where appropriate.
> 7. Mark (put x inside brackets: [x]) correct answers below about your OS and MMEX version used.
> 5. Remove this text marked with >.

**Describe the bug**
Generating a Monthly or Daily Cash Flow report causes MMEX crash and generate a dump

**To Reproduce**
1. Create a account
~~Add transactions into the account~~
3. Save database
4. Open up the a "Cash Flow" report.
5. Memory Dump profit!

**Expected behavior**
A graphical or table report should be present in the Report Panel

**Screenshots**

**Additional context**
~~My transaction data is is 6-18 months of historical data. Not sure if this is out of range for a report.~~

_Memory Dump and Stack Trace_
[MoneyManagerEx_dbgrpt-2368-20190106T223429.zip](https://github.com/moneymanagerex/moneymanagerex/files/2730414/MoneyManagerEx_dbgrpt-2368-20190106T223429.zip)

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.0-alpha.6
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by Jimmyson** [comment]
Whoops!

Did a bit more digging around, and found that **having an empty "Cash Account" triggered this error!**
I originally put transactions into a Bank Account, which is not the criteria of the report

**Comment by slodki** [comment]
This is already fixed (#1889).
