### ISSUE TITLE
Transaction Report will use currency transformation twice incorrectly

### ISSUE THREAD

**Issue by jeffreyren** [moneymanagerex/moneymanagerex#1909]
**Describe the bug**
Version: 1.3.3
When I use Transaction Report to search some transactions with China Yuan (other than default Australian Dollar), the amount and "Total amount" are calculated incorrectly.
The amount column: It will show ￥3000 (Actually it's $3000).
"Total Amount": it will show $600 (Actuall it is supposed to be $3000).
v1.27 version will display as correct behaviour.

**To Reproduce**
1. set up default currency australia dollar and china yuan CNY (rate is 0.2);
2. add multiple deposit transactions in the account with china yuan, assume ￥15000.
3. Open Transaction report, check Date Range, Category, Include Similar, Type: Deposit; save the filter.
3. Transaction report will show the amount column as ￥3000 (the correct one is $3000).
4. Total amount will show $600 ( the correct one is $3000).
See screen shot below.

**Your OS:**
- [X] Windows

**MMEX version:**
- [X] 1.3.3 will reproduce this.
- [ ] 1.2.7 will NOT reporduce this.

![currency](https://user-images.githubusercontent.com/19634486/50890879-2eb38680-144f-11e9-8681-b6d42b65f6da.png)
![transaction](https://user-images.githubusercontent.com/19634486/50890900-38d58500-144f-11e9-8fc9-af6527901d67.png)
![filter](https://user-images.githubusercontent.com/19634486/50890917-3ecb6600-144f-11e9-9fd4-5989d083bc97.png)

**Comment by jeffreyren** [comment]
Filter screen shot:
![image](https://user-images.githubusercontent.com/19634486/50891104-ad102880-144f-11e9-83ac-0257f8544903.png)

**Comment by slodki** [comment]
I cannot reproduce this in alpha.7:
![mmex](https://user-images.githubusercontent.com/3155552/50921831-3a9c4a00-1449-11e9-8d15-35d5c7b2e166.png)
![mmex2](https://user-images.githubusercontent.com/3155552/50921888-5bfd3600-1449-11e9-92fd-8c833a8ebe12.png)
