### ISSUE TITLE
New language translation

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1916]
How to add new translation?
There are following po files in po folder of mmex:
```
ab - Abkhazian
ar - Arabic
bg - Bulgarian
ca - Catalan
cs - Czech
de - German
el - Greek
en_GB - English
es - Spanish
fa - Farsi
fi - Finnish
fr - French
he - Hebrew
hi - Hindi
hr - Croatian
hu - Hungarian
id - Indonesian
it - Italian
ja - Japanese
ko - Korean
lt - Lithuanian
lv - Latvian
ml - Malayalam
my - Burmese
nb - Norwegian (Bokmal)
nl_BE - Dutch (Belgian)
nl_NL - Dutch
pl - Polish
portuguese_br_2nd - N/A
pt_BR - Portuguese (Brazilian)
pt_PT - Portuguese
ro - Romanian
ru - Russian
sh - Serbo-Croatian
sk - Slovak
sl - Slovenian
sq - Albanian
sr - Serbian
sv - Swedish
ta - Tamil
th - Thai
tr - Turkish
uk - Ukrainian
vi - Vietnamese
zh_CN - Chinese (Simplified)
zh_TW - Chinese
```
I've added da.po for Denmark language but it not available for choice.

**Comment by slodki** [comment]
After `cp -r /usr/share/mmex/ru /usr/share/mmex/da` it was displayed in the View menu.
You must add source .po file to po/ sub dir and install MMEX or manually add compiled .mo file to installed directory - see https://docs.wxwidgets.org/3.1/overview_i18n.html#overview_i18n_mofiles

**Comment by vomikan** [comment]
I have new translation 
Serbian (Latin) - sr_RS@latin
to start it working it should be mmex.mo file in sr_RS@latin directory.

**Comment by vomikan** [comment]
The translation seem useless
[sr_Latn_RS.zip](https://github.com/moneymanagerex/moneymanagerex/files/2749424/sr_Latn_RS.zip)
