### ISSUE TITLE
emb_update

### ISSUE THREAD

**Issue by Teezton** [moneymanagerex/moneymanagerex#1917]
Hi community,

What is this file, it's safe to delete?

![mm](https://user-images.githubusercontent.com/5905860/50985112-709a0680-14fb-11e9-9bb9-f4d0a1ae1857.png)

Best Regards!

**Comment by vomikan** [comment]
It's backup. May be deleted.

**Comment by slodki** [comment]
![mmex1](https://user-images.githubusercontent.com/3155552/50992628-fc219080-1517-11e9-8175-a9098958ee11.png)

**Comment by Teezton** [comment]
If I uncheck that box, the program will not save anymore?

**Comment by slodki** [comment]
Yes
