### ISSUE TITLE
Always "monthly" on Recurring Transactions

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#1918]
On editing a recurring transaction, the field "Repeats" is always monthy - no matter what it was before.

<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git ab83908e (2019-01-06)<br><b>Libs</b>: wxWidgets 3.1.2 (wxMSW 10.0) • wxSQLite3 4.4.0 (SQLite 3.26.0) • Mongoose 6.13 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.62.0-DEV • WinSSL<br><b>Build</b>: Jan 7 2019 23:18:12 • CMake 3.12.2 • MSBuild 15.9.21.664 • gettext 0.19.8.1 • Microsoft Visual Studio 15.0 • Microsoft Visual C   19.16.27025.1 • Windows SDK 10.0.14393.0<br><b>OS</b>: Windows 10 (build 17134), 64-bit edition • German (windows-1252) • 1920x1080 32bit 96x96ppi</small>

**Comment by slodki** [comment]
Cannot reproduce:

![mmex1](https://user-images.githubusercontent.com/3155552/50991100-2c673000-1514-11e9-8e54-27478c587881.png)
![mmex2](https://user-images.githubusercontent.com/3155552/50991112-30934d80-1514-11e9-9db6-b58b1f1d54e6.png)

**Comment by TomAff** [comment]
![grafik](https://user-images.githubusercontent.com/46572503/51133943-83337900-1836-11e9-83cc-88ce58274dd2.png)

**Comment by vomikan** [comment]
Could you reproduce this issue in case if program language is Englush?

**Comment by TomAff** [comment]
![grafik](https://user-images.githubusercontent.com/46572503/51136973-060c0200-183e-11e9-8cf6-9399aff98131.png)

**Comment by vomikan** [comment]
I can't reproduce this issue as well.

**Comment by TomAff** [comment]
I have downloaded this ZIP again and made a test.
https://github.com/moneymanagerex/moneymanagerex/releases/download/nightly/mmex-1.4.0-alpha.6-win64-portable.zip

The issue is still there. Is there any other ZIP I can test?

**Comment by vomikan** [comment]
If reccuring transaction would be deleted then entered again the issue gone?

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/51805865-c6083e80-2283-11e9-84b9-9c5200c9f6cd.png)
