### ISSUE TITLE
Back button on help page makes it empty

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1938]
1. Click on a main node in Navigation Tree like Stock Portfolios, Budget, Reports, Help
2. A help page is displayed
3. Click the Back button at top of the right panel...
4. ... help page disappears
5. Click the Next button...
6. ... help page comes back

Back button should be inactive if there is no previous view to display.

<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git c291e5d5 (2019-01-11) master<br><b>Libs</b>: wxWidgets 3.1.2 (wxGTK 2.24) • wxSQLite3 4.4.0 (SQLite 3.26.0) • Mongoose 6.13 • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.61.0 • OpenSSL 1.1.1 • zlib 1.2.11 • libidn2 2.0.5 • libpsl 0.20.2 • ( libidn2 2.0.4) • nghttp2 1.32.1 • librtmp 2.3<br><b>Build</b>: Jan 11 2019 01:40:32 • CMake 3.12.1 • GNU Make 4.2.1 • gettext 0.19.8.1 • GCC 8.2.0 • Ubuntu 18.10 'cosmic'<br><b>OS</b>: Ubuntu 18.10 "cosmic" • Linux 4.18.0-13-generic x86_64 • KDE Polish (UTF-8) • 1680x1050 24bit 98x99ppi</small>

**Comment by vomikan** [comment]
It seems wxWidget bug.
I've discovered on my host after help page loaded then 
```                m_historyPosition++;``` started twice in void wxWebViewIE::onActiveXEvent(wxActiveXEvent& evt) function.

**Comment by slodki** [comment]
It may be JS redirect from ./index.html?lang=xx ?

**Comment by vomikan** [comment]
No. It absolutely the same behavior for all reports.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/51785981-28bbe600-216f-11e9-9b47-62354b4eb283.png)

**Comment by vomikan** [comment]
Solution:

```
    int helpFileIndex = m_frame->getHelpFileIndex();
    const wxString help_file = wxString::Format("file://%s?lang=%s"
        , mmex::getPathDoc((mmex::EDocFile)helpFileIndex)
        , Option::instance().LanguageISO6391());

    //wxLogDebug("%s", help_file);
    //browser_->LoadURL(help_file);

    browser_ = wxWebView::New(this, wxID_ANY, help_file);
    itemBoxSizer2->Add(browser_, 1, wxGROW | wxALL, 1);
```
