### ISSUE TITLE
MMEX database upgrade to version 12 failed

### ISSUE THREAD

**Issue by petubl** [moneymanagerex/moneymanagerex#1951]
I am trying to open an existing database in 1.4.0alpha 6
I get the message Constraint failed 2067: UNIQUE constraint failed: PAYEE.PAYEENAME

I have been using 1.33 for a long time but i am a complete newbie to programming.

Can anyone advise as to how i can resolve this problem?

![image](https://user-images.githubusercontent.com/47028309/51742232-d365d300-20a1-11e9-9fbe-f88b595a2c07.png)

**Comment by slodki** [comment]
You have 2 payees with the same name. After changing one payee name to uniqe one this problem should be fixed

**Comment by petubl** [comment]
Thank you very much for this slodki! I managed to find more than one duplicate entries...

**Comment by cavoinne** [comment]
Hi, I am having the same issue. Do you any advice on how to spot the duplicate entries?
Can it be done from MMEX itself ? Or did you use to sqlite database editor?

Thanks!

**Comment by vomikan** [comment]
It should be some  sqlite database editor used.

**Comment by cavoinne** [comment]
In case it can help others, here is how I found the duplicate payee using sqlitebrowser tool (link in previous comment form vomikan):
1-Open my MMEX database with the sqlite browser
2-Go to execute SQL tab
3-Enter following SQL code:
SELECT PAYEENAME, COUNT(*)
FROM PAYEE_V1
GROUP BY PAYEENAME
HAVING COUNT(*) > 1
4-Click the play button et voila!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_12.sql#L130

https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_12.sql#L530

**Comment by vomikan** [comment]
I suggest the following SQL
```
with u as (SELECT PAYEENAME||'_'||payeeid  as PAYEENAME, Payeeid, count() c 
FROM PAYEE_V1
GROUP BY PAYEENAME)
SELECT p.payeeid
, case when u.c>1 then u.PAYEENAME else p.PAYEENAME end as PAYEENAME
, p.CATEGID, p.SUBCATEGID
FROM PAYEE_V1 p
 left join u on p.payeeid=u.payeeid
```

![image](https://user-images.githubusercontent.com/6836805/75987050-45912400-5f00-11ea-83a0-390f067c8056.png)

![image](https://user-images.githubusercontent.com/6836805/75987071-517ce600-5f00-11ea-839c-5f4f722f86e6.png)
