### ISSUE TITLE
ChartNew.js outdated

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1961]
Related issues: #1734 #1733 #1690 #1689 #1736

https://github.com/FVANCOP/ChartNew.js/blob/master/README.md

Seems it time to find replacement for this library.

Suggestions:
- https://github.com/puikinsh/gentelella
- https://d3js.org/
- https://github.com/c3js/c3
- https://github.com/chartjs/Chart.js

- [x] development version (git master branch)

**Comment by vomikan** [comment]
Pie chart by https://github.com/chartjs/Chart.js sample:
![image](https://user-images.githubusercontent.com/6836805/51838751-542e0480-2318-11e9-8e51-a6e623070d9c.png)

```
<!doctype html>
<html>
<head>
	<title>Pie Chart</title>
	<script src="Chart.min.js"></script>
</head>

<body>

	<div id="canvas-holder" style="width:40%">
        <canvas id="myChart" width="400" height="400"></canvas>
	</div>

<script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: [
		"Red", 
		"Blue", 
		"Yellow", 
		"Green", 
		"Purple", 
		"Orange"
		],
        datasets: [{
            label: '# of Votes',
            data: [600, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
    }
});
</script>
</body>
</html>
```

**Comment by whalley** [comment]
I'll see if I get some time and work on this over next month or so. Having done some analysis I think that chart.js is probably the most appropriate library to use at this time. It is widely used and has an active developer base.

**Comment by vomikan** [comment]
I think it's time to release 1.3.6.
This changes may be realized in 1.3.7

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/1689

**Comment by vomikan** [comment]
https://github.com/chartjs/Chart.js/releases

**Comment by vomikan** [comment]
Unfortunately Chart.js does not working with Iexplore 1909.
At the same time it working with Edge.

![image](https://user-images.githubusercontent.com/6836805/103224297-86977080-4938-11eb-93cb-202416b3cea8.png)

**Comment by whalley** [comment]
Bulk of reports now running with [ApexCharts](https://apexcharts.com/) - Line, Bar, and Pie converted, just need to get the Radar chart done for the "Budget Category Summary".. Hopefully will publish a preview in next week or so. I've left Chart.js available for GRM reports in case people are using it, but core MMEX reports all using ApexCharts.

**Comment by vomikan** [comment]
[New Report 20201230104853.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/5753463/New.Report.20201230104853.grm.zip)

**Comment by vomikan** [comment]
@whalley  your changes show nothing for me untill I've added

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/103439611-712f8880-4c4f-11eb-94ed-e2ad12aa3a02.png)

**Comment by whalley** [comment]
Good point, thanks for testing on WIndows. Just spotted in the ApexCharts README...

## Using it with IE11

If you need to make it work with IE11, you need to include these polyfills before including ApexCharts

- [promise-polyfill](https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js)
- [classlist.js](https://cdn.jsdelivr.net/npm/eligrey-classlist-js-polyfill)
- [findIndex](https://cdn.jsdelivr.net/npm/findindex_polyfill_mdn) - You will need this only if you require timeline/rangebar charts
- [canvg](https://unpkg.com/canvg@3.0.4/lib/umd.js) - You will need this only if you require PNG download of your charts of your charts

I'm just setting up my Win10 and Linux test rigs for future development testing :-)

As for the colors I left ApexChart to generate them using its standard palette. I agree RED may be best for expenses so I'll add an option to override as needed for charts.

**Comment by whalley** [comment]
Have updated to allow colors to be specified for series in charts. Have used this so that green/red is used for reports that have income/expenses and deposits/withdrawals. 
Also added logic to include other required .js for browsers (i.e. IE11) that need it.

Tested on OSX and Win10.
