### ISSUE TITLE
Importing zero amount transactions from a CSV file

### ISSUE THREAD

**Issue by Jimmyson** [moneymanagerex/moneymanagerex#1963]
**Is your feature request related to a problem? Please describe.**
Presenting an option to import transactions with a Withdrawal or Deposit of 0 _(Zero)_ on CSV files
I am in the process of importing digitised statements, and some of these transactions have no impact on the final balance. The importer is parseing these records as "Invalid Amount", yet the application supports user-created records with a Transaction Amount of 0 _(Zero)_.

**Describe the solution you'd like**
Presenting a checkbox on the UI to allow the user to process Transactions with a Amount, Deposit or Withdrawal of 0 _(Zero)_.
This can allow user to decide to either record or skip "Nil Amount" transactions

**Describe alternatives you've considered**
An alternative could be to have the user add additional records to the Import CSV that can negate the transaction to record a zero, but this would not be consistent with the recorded transaction, in the form of "Phantom Transactions"

**Additional context**
In my case, these recorded transaction are either a combination of Individual Transactions with will be later split in the system, or a reoccuring Interest transaction that deposits no money into the account.

**Comment by slodki** [comment]
1. We should allow importing transactions with 0 amount to be consistent with MMEX GUI functionality
2. There should be an option in the import dialog to *ignore 0 amount transaction records*
