### ISSUE TITLE
Transaction List Exchange rates

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1964]
It would be usefull to show exchange rate and date in this report and totals in base rate for foreign currencies as well.
![image](https://user-images.githubusercontent.com/6836805/51964814-b4d45300-2478-11e9-96bd-3c4879eee2b5.png)

**Comment by whalley** [comment]
@vomikan Not sure we can show the exchange rate and date in this report total as this will differ depending upon the date of the individual transactions and what we have in the historical data. We could however show the foreign currency totals and the totals in base currency.

**Comment by whalley** [comment]
Still think it good idea to show the foreign currency totals and the totals in base currency. So will add this.
