### ISSUE TITLE
Budget report diagram

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1966]
Budget reports has a lot of Radar Diagrams like this:
![image](https://user-images.githubusercontent.com/6836805/51976144-025eb900-2495-11e9-910a-2b4695d6d250.png)
It's not informative.

**Comment by vomikan** [comment]
Better to use Bar chart + line

![image](https://user-images.githubusercontent.com/6836805/51976396-9c266600-2495-11e9-93e1-33a8cff8d4e3.png)

**Comment by vomikan** [comment]
https://github.com/FVANCOP/ChartNew.js/wiki/070_020_Bar#barline

**Comment by vomikan** [comment]
I suggest Bar chart + line chart like this:
![image](https://user-images.githubusercontent.com/6836805/51999802-a021aa80-24cc-11e9-8e83-b72a6ac86aa6.png)
Where months are categories, green line is estimated amounts.

**Comment by whalley** [comment]
@vomikan - Assigned to me and I'll have look at what options we have.
