### ISSUE TITLE
Bold font for mandatory fields

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1968]
![image](https://user-images.githubusercontent.com/6836805/52006371-00b8e380-24dd-11e9-8557-062158b113bd.png)

**Comment by slodki** [comment]
My proposals:
- red border around missing or invalid inputs
- light red background of missing or invalid inputs

![bez nazwy](https://user-images.githubusercontent.com/3155552/52170309-3a415700-2748-11e9-8fa5-b2642f66bace.png)

**Comment by vomikan** [comment]
I am against red frames. This is redundant for the interface.

**Comment by slodki** [comment]
Will you update rest of MMEX GUI to the consistent style?
The manual should be updated too (#1298) as this is not a very common GUI style.

**Comment by vomikan** [comment]
This kind of style has implemented for most basic dialogues. Regarding manual, I am bad copyrighter.
