### ISSUE TITLE
Budget question

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1971]
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=7855

Good afternoon,
I am not sure if this question has been asked before. I have tried to search the forum and could not find the answer for my query. I am having some issues around data displayed in the budget/my logic might be wrong. Let me start from the beginning though with an example scenario.:

1. I have created three accounts - two Current Bank Accounts, one named "Bills" and the second one called "Primary". I have also created one Credit Card account.
2. All income (salary) goes into the "Primary" account. From there, the portion of the money gets transferred to the "Bills" account to cover ongoing expenses.
3. Once a month payment is being made from the "Bills" account to the Credit Card account using transaction type "Transfer".
4. A new budget is getting created which account for all expenses, income etc. 

a) If no changes to the settings are made ("Budget: Include transfers in totals"), and Transfer method is being used to pay the credit card bill, the budget does not take into account the payments I have made towards my credit cards. 

I have tried a workaround where I would first create a transaction - from the "Bills" account withdrawing the money, I have checked the budget, it does record it correctly against my category "Credit card payments" it also correctly updates Actual Expenses. Now I need to create a second transaction in my Credit Card account depositing the exact amount. This action causes Budget to remove the Expense from the "Credit card payments", and it changes total to the pre-payment state. 

b) If I make changes to the settings and decide to display transfers in the budget totals I am getting the following: the data against category "Credit card payments" is displayed correctly. It adds the correct figures to the totals in the budget, but - the budget also displays additional income made from transfer between the "Primary" account and the "Bills" account making the total income figure incorrect. Why would it only record a deposit into the "Bills" account and not take into account a withdrawal from the "Primary" making this budget figure nil? 

What I would want is the ability to pay my credit card bills, record them as expenses (so they show correctly on the budget), but at the same time not get an additional income made from the transfer between the current accounts. 

My explanation is a bit messy, apologies in advance, but if someone could please explain to me how I can achieve the above, I would be grateful.

Kind Regards,
Karol

**Comment by slodki** [comment]
Transfers should be used for moving money between your accounts only - when before and after the transfer you own the money. Transfers must have *transfer* category. Then all works as expected.

![screenshot](https://user-images.githubusercontent.com/3155552/52163883-287c9700-26e9-11e9-9d7e-f45d3160703a.png)

See the attached example.
[test.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/2824370/test.mmb.zip)
