### ISSUE TITLE
QIF import/export issues

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1972]
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=7818

How this came about was when I wanted to create a credit card account in the section allotted to it.

When I first got MMEX there was no credit card section so I entered it as a checking account.

Now however I want to tidy things up a bit and have everything under their own sections. Not realising there was a reallocate account.

Firstly I exported in qif for no other reason than as a trial and I had always used this for data from my bank. This took a short while but looked as if everything was ok, 

I then went to import that data into the newly created account under the credit card heading.

The first 50 lines of the generated qif looks as if they are all category headings.

The lines after that read multiple Errors for categories
Error: Transaction code is missing
( Type:Cat|xxxxxxxxxx|| )

Secondly no payment transactions are shown as apparently there is no category for these. I also presume that transfer has not been allowed for obvious reasons, 

The credit account is then recreated to see if the transactions fair better with another method.

xml appears to export ok, but throws up multiple errors when trying to import its own data.

csv works 

Having done these test, I know there is a reallocate an account, which was used. 

However the fact that the export and import appear not to be working across account types is really a bug.

**Comment by slodki** [comment]
Problematic qif/xml file must be attached with a corresponding working csv file.
