### ISSUE TITLE
Issue with Stocks Report - Performance

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#1973]
**Describe the bug**
Not sure if this is to be expected until Nikolay's reporting changes are complete and not sure when this started to happen but on the latest master, clicking on the Stocks Performance Report gives all the text details of the various stocks (headings etc.) but no data plots.

**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (git master branch)

**Comment by vomikan** [comment]
@grumpy235 thank you for point it. It was my typo. Sorry for that. I've refactored the code with some improvements.

![image](https://user-images.githubusercontent.com/6836805/52062020-c2750000-2580-11e9-8288-e5398a6c3d0a.png)

Related issue: #1736
