### ISSUE TITLE
The color palette for charts is too short - duplicated colors

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1980]
There are many very similar (almost indistinguishable) colors used in pie charts with multiple values:

![screenshot](https://user-images.githubusercontent.com/3155552/52170711-abd0d380-274f-11e9-9ce4-31afa40c2183.png)

[Continuous color interpolation](https://github.com/d3/d3-scale-chromatic) or [discrete scheme](https://jnnnnn.blogspot.com/2017/02/distinct-colours-2.html) schould be use to generate charts with unique colors.

**Comment by vomikan** [comment]
We should add more (look nice) colours but we can't add a lot of then. 
The solution has been implemented by @omalepat but then I've removed the code regarding code simplification project.
Idea is to group small values to one group called 'others'.

**Comment by slodki** [comment]
Please open links above to find ready to use color generator: http://jnnnnn.github.io/category-colors-constrained.html

**Comment by grumpy235** [comment]
Please also include line charts, very limited selection which includes an almost invisible yellow
![line](https://user-images.githubusercontent.com/24897056/52262232-d8d5df80-2923-11e9-8b78-12a949d5064a.PNG)

**Comment by vomikan** [comment]
@grumpy235 what is the chart? How to reproduce this?

**Comment by grumpy235** [comment]
Stocks Performance is the report and I have a number of stocks.
From what I remember of playing with the code some months ago then the line
hb.addLineChart(aData, stock.STOCKNAME, 0, 1000, 400, pointDot, showGridLines);
in summarystocks.cpp drives the report for each stock
htmlbuilder.cpp has a COLORS array and there is getColor function which chooses a color and the offending color is rgba(255, 243, 171, 0.7)

**Comment by vomikan** [comment]
I'll look at the issue but for me a graph is blue.
![image](https://user-images.githubusercontent.com/6836805/52271704-7c8bb380-2955-11e9-964a-d552b1951fec.png)

**Comment by vomikan** [comment]
Seems I've fixed that and all graphs should be blue.

**Comment by grumpy235** [comment]
Thanks, Nikolay, better than a wishy-washy yellow !

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/52398909-b1ba1200-2acb-11e9-9516-5c87bf059820.png)

[colors.zip](https://github.com/moneymanagerex/moneymanagerex/files/2839900/colors.zip)

https://www.rapidtables.com/web/color/RGB_Color.html
```
static const wxString COLORS [] = {
      "rgba(135,206,250,0.7)"
    , "rgba(255,192,203,0.7)"
    , "rgba(210,105,30,0.7)"
    , "rgba(0,255,0,0.7)"
    , "rgba(255,255,0,0.7)"
    , "rgba(0,255,255,0.7)"
    , "rgba(46,139,87,0.7)"
    , "rgba(255,228,196,0.7)"
    , "rgba(138,43,226,0.7)"
    , "rgba(240,128,128,0.7)"
    , "rgba(240,230,140,0.7)"
    , "rgba(65,105,225,0.7)"
    , "rgba(34,139,34,0.7)"
    , "rgba(205,92,92,0.7)"
    , "rgba(192,192,192,0.7)"
    , "rgba(75,0,130,0.7)"
    , "rgba(127,255,212,0.7)"
    , "rgba(255,0,0,0.7)"
    , "rgba(250,128,114,0.7)"
    , "rgba(139,0,139,0.7)"
    , "rgba(255,215,0,0.7)"
    , "rgba(138,43,226,0.7)"
    , "rgba(184,134,11,0.7)"
    , "rgba(255,0,255,0.7)"
    , "rgba(0,191,255,0.7)"
    , "rgba(128,128,0,0.7)"
    , "rgba(70,130,180,0.7)"
    , "rgba(154,205,50,0.7)"
    , "rgba(255,20,147,0.7)"
    , "rgba(139,69,19,0.7)"
    , "rgba(176,196,222,0.7)"
    , "rgba(85,107,47,0.7)"
};
```

**Comment by vomikan** [comment]
![img_20190207_202410](https://user-images.githubusercontent.com/6836805/52439792-7d773d80-2b2d-11e9-9b7f-a021df7c7dfa.jpg)

**Comment by vomikan** [comment]
Seems somthing wrong.
![image](https://user-images.githubusercontent.com/6836805/52551771-f527bf80-2dee-11e9-9b50-46d574cbfa93.png)

**Comment by grumpy235** [comment]
What about using the same color pick code used in payee pie charts for stocks report line charts and then we go back to multi-colors in stocks report?

**Comment by slodki** [comment]
screenshots from #2024:
![mmex1](https://user-images.githubusercontent.com/3155552/52672678-d32d5a80-2f1e-11e9-8afe-7995c5a5d520.png)
![mmex2](https://user-images.githubusercontent.com/3155552/52672686-d7f20e80-2f1e-11e9-9d15-c2be926d2891.png)

**Comment by vomikan** [comment]
let me think about it.

**Comment by vomikan** [comment]
https://www.highcharts.com/demo/pie-donut

**Comment by slodki** [comment]
Two color diverging stacked bar chart (withdrawals on left, incomes on right):

![diverging stacked bar chart](https://peltiertech.com/images/2016-08/DivergeLiars3.png)

**Comment by slodki** [comment]
Draft
[Payees chart.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/2867389/Payees.chart.grm.zip)

**Comment by vomikan** [comment]
IMHO mmex has incorrect reporting concept.
In case if I am worker and receive salary 1-2 times per month and has expenses  every day and expense amount approximately equal salary the category report would look like this one:

**Comment by slodki** [comment]
Which one?

**Comment by vomikan** [comment]
IMHO mmex has incorrect reporting concept.
In case if I am worker and receive salary 1-2 times per month and has expenses  every day and expense amount approximately equal salary the category report would look like this one:
![pie](https://user-images.githubusercontent.com/6836805/52839993-f7e52600-3108-11e9-805e-2d9fe661d5e0.PNG)
Not bad untill incomes will groew.
In case if incomes are 80%, for example, vs expences this pie became like this:
![image](https://user-images.githubusercontent.com/6836805/52840397-2ca5ad00-310a-11e9-8459-b848498f85db.png)
Another issue is that category may be used for transaction them self. it's a bug.
Category should be just aggregator for represent subcategories grouped by the category.

**Comment by vomikan** [comment]
I suggest:
Income vs Expenses
\ ....
Incomes
  \ by Category
       \ by Subcategory
  \ by Payee
Expences
  \ by Category
       \ by Subcategory
  \ by Payee
somthing like this

**Comment by vomikan** [comment]
Here I think an option to add drop down menu into the teport body to swith between Incomes and Expences.
Like this one (screenshot from Forecast Report):
![image](https://user-images.githubusercontent.com/6836805/52840887-b144fb00-310b-11e9-9e7e-5ff1d1b98e05.png)
![image](https://user-images.githubusercontent.com/6836805/52840922-d46faa80-310b-11e9-88d0-a1fe393fa157.png)

**Comment by slodki** [comment]
Please try a fixed report:
[Payees chart2.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/2872382/Payees.chart2.grm.zip)

* time period selection
* incomes / expences / both selection
* linear / log scale selection
* ascending / descending order selection
* dynamic zoom
* animated

SVG tooltips (with detailed payee data) are not working in wxW webview - but work in web browser.

**Comment by slodki** [comment]
[Payees chart3.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/2872432/Payees.chart3.grm.zip)

**Comment by vomikan** [comment]
I like that report itself. How it help us to solve the issue?

PS font to high for me. I've deleted  this line ```        .style("font-size", 0.8*height +'px') ```

**Comment by slodki** [comment]
Placing payee name over its part of the chart eliminates the need to label them distinguishable colors.
We will never have an infinite number of distinguishable colors.
A pie chart is simply inappropriate for this report.

**Comment by vomikan** [comment]
@whalley is this issue outdated?

**Comment by whalley** [comment]
Actually the standard palettes in ApecCharts only have 5 colors each, so there is quote a bit of repeat in many cases. I can easily extend this a bit. Please re-open and assign to me.
