### ISSUE TITLE
Change name of Recurring Transactions to Transaction Planner

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1983]
There are different names in MMEX for BILLSDEPOSITS table functionality:
* main menu, nav tree and right panel title &rarr; *Recurring Transactions*
* tooltips and right mouse button context menu in right panel &rarr; *Bills & Deposits Series*

Both existing names are misleading:
* not only recurring transactions can be stored in BILLSDEPOSITS but one time events too
* transactions not related to bills payments or deposits can be managed there like transfers etc.

Transaction Planner name is clearly describing the purpose of BILLSDEPOSITS table: place for storing planned, not confirmed transactions to be entered into ledger in the future.

**Comment by vomikan** [comment]
Please after 1.4 release

**Comment by vomikan** [comment]
@ovari could you please sort this out?

**Comment by ovari** [comment]
> could you please sort this out?

1. I don't have a problem with `Recurring Transactions`.
2. Quicken uses `Scheduled Transaction List`.
3. `Transaction Planner` seems fine too.
4. What do other financial software programs use?

Can a vote with reasons be taken somewhere online before this is changed?

**Comment by tactilis** [comment]
> I don't have a problem with `Recurring Transactions`

I have no problem with that name.

and this:

> tooltips and right mouse button context menu in right panel → _Bills & Deposits Series_

is no longer the case. They say Recurring Transactions now.

**Comment by ovari** [comment]
`Scheduled Transactions` may be better as there may be a one-time payment/deposit which is not technically a recurring transaction.

**Comment by ovari** [comment]
Seems like there are 26 strings to update https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=recur

**Comment by ovari** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/6156

**Comment by ovari** [comment]
@vomikan can this issue please be closed? Thank you
