### ISSUE TITLE
update-po-files.sh outdated

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1984]
https://github.com/moneymanagerex/moneymanagerex/wiki/Translation

![image](https://user-images.githubusercontent.com/6836805/52182076-55749b00-280a-11e9-8e6c-b25491ee20d2.png)

**Comment by vomikan** [comment]
Script is OK but IMHO useless.
Main tool for update translations is crowdin for now.

**Comment by slodki** [comment]
#1345
