### ISSUE TITLE
Remove low-quality translations from the master branch

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1989]
MMEX installs multiple broken .mo files. They are low-quality non-working translations. See #1988 for statistics.

An MMEX user is prompted to select preferred GUI language but after that GUI strings displayed in GUI are wrong or mixed with English untranslated messages.

There should be quality threshold defined and all .po files not matching criteria moved to archived branch from master and fixed at Crowdin. They can be restored using PR after verifying their quality at Crowdin.

My proposal: 50% translation completed:
```
ru_RU 100%
it_IT  99%
fr_FR  99%
es_ES  99%
pl_PL  98%
he_IL  98%
pt_BR  97%
tr_TR  95%
de_DE  70%
hu_HU  68%
nl_NL  67%
sq_AL  55%
lt_LT  53%
```
All other files will not be distributed in MMEX packages until fixed.

**Comment by slodki** [comment]
#1776 an help to improve missing translations

**Comment by slodki** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=8030

**Comment by vomikan** [comment]
I suggest to add Table_Currencyformats.h file into X-Poedit-SearchPathExcluded-0.
In that case all Currencies go away from po files and percentage of translated string will increase.

**Comment by vomikan** [comment]
before | after
--------|--------
ru_RU 100% | ru_RU 100%
it_IT  99% | pl_PL 100%
fr_FR  99% | it_IT 100%
es_ES  99% | fr_FR 100%
pl_PL  98% | pt_BR  99%
he_IL  98% | es_ES  99%
pt_BR  97% | he_IL  98%
tr_TR  95% | tr_TR  96%
de_DE  70% | hu_HU  80%
hu_HU  68% | nl_NL  79%
nl_NL  67% | de_DE  75%
sq_AL  55% | sq_AL  64%
lt_LT  53% | lt_LT  62%
  \-       | cs_CZ  57%
  \-       | zh_CN  56%
  \-       | sk_SK  55%
   \-      | ja_JP  55%

**Comment by slodki** [comment]
50% is still low-quality translation (every second string in GUI in a different language). This can be accepted for beta but must be much higher (~80%) for final releases IMHO.

**Comment by vomikan** [comment]
I leave most active languages. We should keep big list of languages in Crowdin.
But in release the number of .mo files should be restricted only well translated languages.
@slodki could you change CMake file for that?

**Comment by vomikan** [comment]
>50% is still low-quality translation (every second string in GUI in a different language). 

Not agree. There are a lot of invisible strings like tooltips and some interfaces seldom to use. Practically it possible that incomplited po file covers all user needed visible strings.

**Comment by vomikan** [comment]
To make  more translations we need to involve the public more often through social networks.

**Comment by 48mWsPK** [comment]
I second @vomikan on the "good enough" translations - the one I use was removed 2 weeks ago, and in the latest nightly build of MMEX I already miss it: for me it was good enough for daily use for years, but sadly it is now deemed **unworhty**.

Not so if you ask me...

Thanks for the great app, by the way, and keep up the good work!

**Comment by vomikan** [comment]
@48mWsPK what is your lang.
I'll add it to crowdin.
I hope you will made effort to translation.

**Comment by vomikan** [comment]
#2388
