### ISSUE TITLE
Add "Add/Improve GUI Translation" in the main Help menu

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1990]
A simple link to Crowdin (or README/wiki with detailed instructions - #1345) should be enough.
Just below existing *Report a Bug*.

**Comment by slodki** [comment]
1. Help &rarr; Improve translation
   - should open simple pop-up with instructions like this:

     > You can easily improve translation strings in MMEX GUI using only web browser devoting a few minutes to translate. All translation tasks in the project are managed on the Crowdin platform.
     > 1. Open Crowdin page in your browser
     > 2. Create account / log in
     > 3. Select target language and mmex.po file to translate GUI strings
     > 4. Type untranslated or mistranslated string in the search field on the left, select one of displayed items below
     > 5. Add or fix translation in the center window
     > 6. Click the Save button
     > 7. When the translation or fixes are verified, they will be added to the application.
     >
     > [ CLOSE ] [ OPEN IN WEB BROWSER ]
   - :question: linked to the current GUI language file https://crowdin.com/translate/moneymanagerex/470/en-language or to general tab for language https://crowdin.com/translate/moneymanagerex/language
   - :question: how to do reverse-mapping from MMEX locale to Crowdin language id

2. Add *Add missing...* option as the first item under View &rarr; Switch Application Language with similar pop-up but
   - inform there can translation on-going at Crowdin platform already
   - describe the quality criteria to be met by translation to be added to the application package
   - steps how to start translation for a new language

**Comment by vomikan** [comment]
https://user-images.githubusercontent.com/6836805/53188845-3dc55100-3617-11e9-865d-1081955dc101.png
