### ISSUE TITLE
Add Crowdin badge to the main project README.md

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1991]
With progress meter of MMEX translation.
https://twitter.com/crowdin/status/431069657399705600
https://crowdin.uservoice.com/forums/31787-collaborative-translation-tool/suggestions/5498117-widget-to-show-translation-rates

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/52207301-1425cf00-288e-11e9-9c28-f981f327518c.png)
