### ISSUE TITLE
Create Recurring Transaction from an existing transaction

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1992]
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=8035:

Can we use an existing transaction and generate a Recurring transaction with the same inputs.
Like Duplicate a transaction. That way, the number of inputs for the recurring transaction is minimized.
Thoughts??

**Comment by slodki** [comment]
implemented since v1.2.0 as #311
Documentation should be updated: click right mouse button on existing transaction then select `Create Reoccuring Transaction`

**Comment by ovari** [comment]
@vomikan can you please close this issue? Thank you
