### ISSUE TITLE
Crowdin files encoding issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2005]
By default files downloaded from Crowdin has UTF8 encoding with BOM

![image](https://user-images.githubusercontent.com/6836805/52410904-f7d29e00-2aea-11e9-852a-39a2c50fa80e.png)
 I am using Notepad++ to fix this issue.
![image](https://user-images.githubusercontent.com/6836805/52410986-3d8f6680-2aeb-11e9-8f79-c70993764025.png)
Otherwise this file does not working (no images, no js).

**Comment by slodki** [comment]
[The byte-order mark (BOM) in HTML](https://www.w3.org/International/questions/qa-byte-order-mark)
