### ISSUE TITLE
Crash with BILLSDEPOSITS.REPEATS == -1

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2010]
**To Reproduce**
1. Go to Recurring Transactions panel
2. Click on `New`
3. Press `OK`
4. Follow tooltip suggestions to enter required validations
5. Go to step 3 above
6. Dialog will close without request to set any repeat parameters
7. New BILLSDEPOSITS record is created in the db with null (-1) REPEATS field value
8. MMEX crashes while refreshing panel
9. MMEX crashes at next restart

**Expected behavior**
Repetition parameters must be validated before creating new Recurring Transaction
#1968

**Comment by d1vyanshu** [comment]
Hi! I want to take this bug. Can you guide me as to where the error is and how to approach this bug?

**Comment by slodki** [comment]
If you have C++ debugger you can run MMEX using it and replay above scenario, analyzing every action just after `OK` button press closing the dialog.

Or you can use any IDE for C++ (or any text editor) to manually follow source code startking from here:
https://github.com/moneymanagerex/moneymanagerex/blob/01a79e8283c10c6bba74f40ec55dcb72684a1cfb/src/billsdepositsdialog.cpp#L946

Error can be in:
* [Model_Billsdeposits](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/model/Model_Billsdeposits.cpp) class
* [mmBillsDepositsPanel](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/billsdepositspanel.cpp)

**Comment by slodki** [comment]
Simple fix is to just improve
https://github.com/moneymanagerex/moneymanagerex/blob/01a79e8283c10c6bba74f40ec55dcb72684a1cfb/src/billsdepositsdialog.cpp#L946
code adding validation for empty values from left-side panel.
