### ISSUE TITLE
xml pharsing error

### ISSUE THREAD

**Issue by 8647742** [moneymanagerex/moneymanagerex#2011]
**Describe the bug**
I'm using version 1.3.3 in Hebrew on win10 and every time I'm starting the app it says "xml pharsing error." awser between every word instead of space it has "!" symbol.

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by 8647742** [comment]
![img](https://user-images.githubusercontent.com/47487038/52526973-de3b7d00-2cc9-11e9-9a4a-3d24069c7b9d.JPG)
here the scree how it looks like.

thank you

**Comment by vomikan** [comment]
Seems it's news data. This issue already fixed in master branch.

**Comment by slodki** [comment]
@8647742 Could you verify 1.4.0-alpha? Tt has #1083 fix included.

**Comment by 8647742** [comment]
its version 1.2.7 but i awser upgraded to 1.3.3 and it has the same
problems and works even slower.

thank you:-))

‫בתאריך יום א׳, 10 בפבר׳ 2019 ב-17:28 מאת ‪slodki‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by vomikan** [comment]
#1083
