### ISSUE TITLE
Replace _() with wxGETTEXT_IN_CONTEXT() where required

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2018]
This is important for i18n (from [wxGetTranslation](https://docs.wxwidgets.org/3.1/group__group__funcmacro__string.html#ga49dcdc17d82a627b7a50d401f1a37d69) spec):
> If context is not empty (notice that this argument is only available starting from wxWidgets 3.1.1), item translation is looked up in the specified context. This allows to have different translations for the same string appearing in different contexts, e.g. it may be necessary to translate the same English "Open" verb differently depending on the object it applies to. To do this, you need to use msgctxt in the source message catalog and specify different contexts for the different occurrences of the string and then use the same contexts in the calls to this function (or wxGETTEXT_IN_CONTEXT() or wxGETTEXT_IN_CONTEXT_PLURAL() macros).

Now it's impossible to do proper translation to Polish:
* open (file) &rarr; otwarty (plik)
* open (account) &rarr; otwarte (konto)

Only workaround like *otwarte(-y)* is possible but not elegant.

We should handle wxWidgets older then 3.1.1 using additional dumb macros like
```c++
#define wxGETTEXT_IN_CONTEXT(context, string) _(string)
```

**Comment by slodki** [comment]
`xgettext` must be invoked with:
* `--keyword="_" --keyword="wxPLURAL:1,2"` for `_()` and `wxPLURAL()` support (#2019)
* `--keyword="wxGETTEXT_IN_CONTEXT:1c,2" --keyword="wxGETTEXT_IN_CONTEXT_PLURAL:1c,2,3"` for `wxGETTEXT_IN_CONTEXT()` and `wxGETTEXT_IN_CONTEXT_PLURAL()` support (#2019)
* `-kwxTRANSLATE` for `wxTRANSLATE()` support

to generate complete `.pot` file for translation.

**Comment by vomikan** [comment]
This string is OK for poedit
```    const wxString text = wxString::Format(
        wxPLURAL(_("%d day remaining"), _("%d days remaining"), daysRemaining)
        , daysRemaining);
```
![image](https://user-images.githubusercontent.com/6836805/55940666-44506c00-5c49-11e9-97a3-0c3664919b97.png)
Fird line should be: 3 дня осталось
