### ISSUE TITLE
Replace _() with wxPLURAL() where required

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2019]
Now we use simple `_("line(s)")` or `_("number of lines")` to describe 0, 1, 2... elements in MMEX GUI messages.

We should use simple `wxPLURAL("line", "lines", n)` - this will generate:
* 0 "lines", 1 "line", 2 "lines"... in English
* 0 "linii", 1 "linia", 2 "linie"... in Polish

**Comment by slodki** [comment]
https://wiki.audacityteam.org/wiki/Making_Audacity_Translatable

**Comment by vomikan** [comment]
This string is OK for poedit
```    
const wxString text = wxString::Format(
        wxPLURAL(_("%d day remaining"), _("%d days remaining"), daysRemaining)
        , daysRemaining);
```
![image](https://user-images.githubusercontent.com/6836805/55940666-44506c00-5c49-11e9-97a3-0c3664919b97.png)
Third line should be: 3 дня осталось

**Comment by vomikan** [comment]
I've fixed ru_RU translation
![image](https://user-images.githubusercontent.com/6836805/55945612-d198be00-5c53-11e9-8147-171237befdbc.png)

ru_RU.po
```
msgid "%d day remaining"
msgid_plural "%d days remaining"
msgstr[0] "%d день остался"
msgstr[1] "%d дня осталось"
msgstr[2] "%d дней осталось"
```

mmex.pot
```
msgid "%d day remaining"
msgid_plural "%d days remaining"
msgstr[0] ""
msgstr[1] ""
```

**Comment by vomikan** [comment]
Crowdin working as well
![image](https://user-images.githubusercontent.com/6836805/55946483-7962bb80-5c55-11e9-8a12-ec9c56dccc5d.png)

**Comment by vomikan** [comment]
Please use the Switch Application Language option in View menu to select one of the %zu available languages.

**Comment by vomikan** [comment]
@slodki it's working exellent, thank you.
![image](https://user-images.githubusercontent.com/6836805/55949868-407a1500-5c5c-11e9-8e6e-38470cc1dd67.png)

**Comment by slodki** [comment]
>Please use the Switch Application Language option in View menu to select one of the 183 available languages.

would be nice :wink:

**Comment by slodki** [comment]
It's time to verify all stings from .pot file and add wxPLURAL (or even wxGETTEXT_IN_CONTEXT_PLURAL!) where required.

**Comment by vomikan** [comment]
@ovari could you please sort this out?
It seems to be completed, perhaps not completely.

**Comment by ovari** [comment]
> could you please sort this out?
It seems to be completed, perhaps not completely.

Perhaps this issue can be closed and if there are explicit strings that need fixing new issues can be created. What do you think? Thank you
