### ISSUE TITLE
UK English (en_GB) translation unavailable

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#2025]
**Describe the bug**
I am using the latest Master source (a440b52) on Windows 10 in UK English. get the following box when I start the program after a successful compilation
![capture1](https://user-images.githubusercontent.com/24897056/52559640-c52bec80-2ded-11e9-83b8-e7ea77d31169.PNG)
Simply clicking OK means things proceed as normal and I can access my data.
As there is no translation for English, I guess code may be missing a check ?

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by grumpy235** [comment]
Done a little bit of digging but have got confused with how wxLANGUAGE_DEFAULT works.
"mmGUIApp::setGUILanguage" in mmex.cpp is issuing the message but this code has not changed since my earlier compile.
On entry variable lang is set to wxLANGUAGE_UNKNOWN so this is immediately changed to wxLANGUAGE_DEFAULT
"if (!trans->AddCatalog("mmex", wxLANGUAGE_ENGLISH_US) && lang != wxLANGUAGE_ENGLISH_US)" is then true and the warning message is produced what I do not understand is how come this is being triggered now when previous master version worked just fine.
Added the following 
wxString diag = mmex::getProgramDescription() at start of "mmGUIApp::setGUILanguage"
and this produced which confirms wxWidgets knows system language is English

Version: 1.4.0-alpha.7
Database version: 13 (aes256cbc)
Git commit: a440b520 (2019-02-11)
Git branch: master

MMEX is using the following support products:
 • wxWidgets 3.1.2 (wxMSW 10.0)
 • wxSQLite3 4.4.1 (SQLite 3.27.1)
 • Mongoose 6.13
 • RapidJSON 1.1.0
 • Lua 5.3.4
 • libcurl 7.64.0-DEV
 • Schannel

Build on Feb 11 2019 17:29:27 with:
 • CMake 3.13.4
 • MSBuild 15.9.21.664
 • gettext 0.19.8.1
 • Microsoft Visual Studio 15.0
 • Microsoft Visual C++ 19.16.27026.1
 • Windows SDK 10.0.17763.0

Running on:
 • Windows 10 (build 17763), 64-bit edition
 •  English (windows-1252)
 • 1920x1080 32bit 96x96ppi

**Comment by slodki** [comment]
You have en_GB locale but we have only en_US implemented. We had empty en_GB distributed and it was possible to load en_GB but it was the same as en_US.
`trans->AddCatalog("mmex", wxLANGUAGE_ENGLISH_US)` fails as there is no en_GB to load (en_US here describes native source language not requiring translation).

You can:
- switch your system locale to en_US :grin:
- manually select en_US in MMEX View menu
- create en_GB translation at Crowdin

We can:
- remove en_GB support in MMEX and always use en_US when en_GB requested

**Comment by slodki** [comment]
You can see [here](https://github.com/moneymanagerex/moneymanagerex/issues/1776#issuecomment-461674299) how many different English locales is available...

**Comment by grumpy235** [comment]
..and these changes are an improvement to the program 😞 
Clicking OK on the box and mmex still continues to work so what exactly is happening with regard to translation ?
Does this mean that anybody with a non-US English locale will get this box as well ?

**Comment by grumpy235** [comment]
Just found "Switch Application Language" in the View menu - had not known it was there as I had not needed a translation before and I guess it is part of 1.4.0 as not present under 1.3.3. Changed it to English (US) and of course I no longer get the box at start up.
Not looked to closely but I cannot see what difference it has made, perhaps some "odd US spellings" but no big deal yet 😄 
Why not change default from "system default" to English(US) which will re-instate a base language of some form of English, remove the confusing box and should have no impact for those already choosing a supported language.
I am not familiar with how translations works under 1.3.3 so might impact migration to 1.4.0 ?

**Comment by slodki** [comment]
My proposal:
1. Replace text in above pop-up with:
   > Cannot load a translation for the default language of your system (UK English).
   >
   > Please use the Switch Application Language option in View menu to select one of the 18 available languages.
2. Implement #1990 for impatient users :wink:

**Comment by slodki** [comment]
There is instruction in the
https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems too

**Comment by grumpy235** [comment]
Text change sounds great to me and would have made things much clearer for me. I assume "UK English" will be replaced by the actual system locale? Sorry I missed the wiki entry, have not looked there since before the details about translation was added 😉 
Impatience would be one attribute for implementing a new translation, the other I guess would be "tech savvy"  😁
Thanks slodki, you and vomikan are doing a great job.
