### ISSUE TITLE
Too many different dates in New Recurring Transaction dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2026]
There are many date fields in this dialog, displaying different values:
![screenshot](https://user-images.githubusercontent.com/3155552/52589558-655e3180-2e3f-11e9-901a-6f7007c8e57b.png)

Today is 2019-02-11:
* date paid 2019-02-15
* transaction dates 2019-02-23
* date due 2019-02-25
* activates in 20 days = 2019-03-03

Qestion: what date is selected for next transaction planned here?

**Comment by andrepg** [comment]
Also, I want to report that the "Date paid" and "Due Date" only can be equals. If we pay some bill after Due date and provide later Paid Date then MMEX will use equal dates to both of them (so, I can't know if bill was paid after or before their Due Date)

**Comment by vomikan** [comment]
In case if trx marked as auto it will executed in Date Paid (Transaction dates the same but calendar widget type).
![image](https://user-images.githubusercontent.com/6836805/56038577-ffa4fd80-5d3a-11e9-9af2-4b1988887065.png)
The Date Due is the entered transaction date.
Other words this feature to enter planned transaction before actual transaction date.

**Comment by vomikan** [comment]
New look of Recurring transaction dialog

![image](https://user-images.githubusercontent.com/6836805/56475858-1cf26e00-6497-11e9-88b8-3ec77eebcb0b.png)
