### ISSUE TITLE
Support for opensuse Leap and Tumbleweed

### ISSUE THREAD

**Issue by DocBox12** [moneymanagerex/moneymanagerex#2027]
Hi!

Why do you not support openSUSE Tumbleweed and Leap 15 but only opensuse 42.x? OpenSuse 42.3 is expected to be maintained until June 30 2019. 

Will you support opensuse Tumbleweed and Leap?

**Comment by slodki** [comment]
We are ready to deliver Leap 15.x packages:
https://github.com/moneymanagerex/moneymanagerex/blob/a440b520a10e3a8d9916403b8db2e18077cd4cb3/.travis.yml#L47

...but #1903 :disappointed:
