### ISSUE TITLE
Default category is not assigned automatically for known payee during .qif import

### ISSUE THREAD

**Issue by xor2003** [moneymanagerex/moneymanagerex#2031]
**Describe the bug**
After .qif import for known payee the category field is empty. Regression?

**To Reproduce**
1. Intall 32 bit v1.3.3.
2. Create new DB. Currency is RUB. Select English everythere.
3. Create payee "TELE2". Assign some default categoty to it.
3. Import attached .qif. Accept to automatically add new payees, etc.
4. See last results it "Category" tab in the import window: Category is found (from default)
5. After import window is closed in the account the column "Catergory" is empty. (Non "Unknown" and not default category.

**Expected behavior**
The default category should be assigned to known payee.

**Screenshots**

**Additional context**

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)
[b.zip](https://github.com/moneymanagerex/moneymanagerex/files/2870449/b.zip)

**Comment by xor2003** [comment]
Sceenshots attached
<img width="857" alt="2" src="https://user-images.githubusercontent.com/1642627/52878587-0f0a2f00-316e-11e9-81c4-e2708ecd16de.png">
<img width="430" alt="1" src="https://user-images.githubusercontent.com/1642627/52878589-0fa2c580-316e-11e9-9d6b-e59ddf1067d4.png">

**Comment by xor2003** [comment]
For my understanding it is a bug

**Comment by xor2003** [comment]
Nikolay, can I try to fix it myself? Where to put attention?

**Comment by vomikan** [comment]
The code is quite complex....
