### ISSUE TITLE
Import error - internal transfers recorded incorrectly (in reverse)

### ISSUE THREAD

**Issue by t4777sd** [moneymanagerex/moneymanagerex#2032]
**Describe the bug**
I am evaluating the software, so I imported from Quicken. Most of the import is correct however the import software is making a simple mistake consistently. **It is recording internal transfers in the reverse of what they actually are**.

For example, pretend there is an internal transfer from Bank#1 to Bank#2. It would be recorded as a withdrawal of money from Bank#1 and a deposit of money to Bank#2. However, the reverse of this is actually done when importing. Bank#1 records a deposit of money and Bank#2 records the withdrawal. Put simply, it records the transfer as Bank#2 -> Bank#1 instead of Bank#1 -> Bank#2

So, it seems to be getting the direction of these transfers wrong. The end result is very incorrect account balances. Unfortunately, in my case, I probably have thousands of these over the last years, so it means I cannot try the software.

**To Reproduce**
1. Export QIF file with all QIF options checked (accounts, payees, etc). Ensure there are internal transfers in the file.
2. Import QIF said QIF file and the transfers will be recorded in reverse

**Expected behavior**
It is expected that a transfer from Bank#1 to Bank#2 will result in a withdrawal in Bank#1 and a deposit in Bank#2 and not the reverse.

**Your OS:**
- [X] Windows

**MMEX version:**
- [X] 1.3.x - It says this is the latest version when I go to Help -> Check For Updates

**Comment by vomikan** [comment]
If you upload QIF sample file with even one transfer transaction it would be helpful.

**Comment by t4777sd** [comment]
Hello Vomikan I am working to find an example case. In an attempt to get an example case with the least possible transactions in it I came across another issue in #2033. I will be uploading an example case for that issue (which appears different than this issue).

Still working on getting a case for this isseu.
