### ISSUE TITLE
Import Error - Failed to import transactions (test file included)

### ISSUE THREAD

**Issue by t4777sd** [moneymanagerex/moneymanagerex#2033]
**Describe the bug**
When trying to debug more #2032 I came across another issue. I exported a single account in quicken versus every account to narrow down just the bank transfer behavior.

I then attempted to import this. What I discovered is that no transactions were created. Attached is an example QIF file. 

**To Reproduce**
1. Import the attached QIF file

**Expected behavior**
The expected bahavior would be that Bank1 has $250,000 in withdrawals. And that Bank2 has $250,000 in debits. Instead, that is not what we see. No transactions are imported and errors are given. This is different than the issue #2032 where transactions are imported, but transfer direction is incorrect (withdrawal / deposit reversed).

**Your OS:**
- [X] Windows

**MMEX version:**
- [X] development version (git master branch)

**Comment by t4777sd** [comment]
I cannot see in github where I can attach a file. So, I will just paste the example qif file for this issue:

`!Type:Bank 
D9/15'18
U0.00
T0.00
CX
POpening Balance
L[Bank2]
^
D9/26'18
U5,000.00
T5,000.00
CX
PBank Transfer
L[Bank1]
^
D10/19'18
U70,000.00
T70,000.00
CX
PBank Transfer
L[Bank1]
^
D10/29'18
U100,000.00
T100,000.00
CX
PBank Transfer
L[Bank1]
^
D10/30'18
U75,000.00
T75,000.00
CX
PBank Transfer
L[Bank1]
^
`

**Comment by t4777sd** [comment]
Here is another test. This was created by creating two banks in quicken Bank1 and Bank2. Bank1 starting balance is 300,000. Transfers are made to Bank2. Ending balance in each should be $45,000 in bank 1 and $225,000 in bank 2. This was then exported using All Accounts in quicken. Only the transactions were exported.

The file transactions fail to import giving an error. Here is the QIF contents: https://paste.ee/p/9eAha

**Comment by vomikan** [comment]
```
!Type:Bank 
D9/15'18
U0.00
T0.00
CX
POpening Balance
L[Bank2]
^
D9/26'18
U5,000.00
T5,000.00
CX
PBank Transfer
L[Bank1]
^
D10/19'18
U70,000.00
T70,000.00
CX
PBank Transfer
L[Bank1]
^
D10/29'18
U100,000.00
T100,000.00
CX
PBank Transfer
L[Bank1]
^
D10/30'18
U75,000.00
T75,000.00
CX
PBank Transfer
L[Bank1]
^
```

**Comment by vomikan** [comment]
https://en.wikipedia.org/wiki/Quicken_Interchange_Format

**Comment by vomikan** [comment]
@t4777sd OK. In your example four transfers to  'Bank1' ?
But it imported as transfer from Bank1.
Could you provide sample for transfer from 'Bank1' ?

**Comment by t4777sd** [comment]
Here are the steps.

1) Create Bank1 in quicken. Set opening balance to 100,000

2) Create Bank2 in quicken. Set opening balance to 90,000

3) on 1/20/2019 transfer from Bank1 to Bank2 77,000. Bank1 balance is 23,000. Bank 2 balance is 167,000

4) on 2/4/2019 transfer from Bank2 to Bank1 24,000. Bank1 balance is 47,000. Bank2 balance is 143,000.

5) Export "All Accounts" in Quicken using QIF format.

6) Import QIF file into Money Market alpha version. MMex shows it read 59 files.

The following log file generated in this case:

`Added account: Bank1
Added account: Bank2
Added payee: Unknown
Date format or date mask is incorrect
Error
( Option:AutoSwitch
Account|Bank|Unknown|Bank1||Deposit )
Date format or date mask is incorrect
Error
( Bank|Unknown|Bank2||Deposit )
Date format or date mask is incorrect
Error
( Clear:AutoSwitch
Option:AutoSwitch
Account|Bank|Unknown|Bank1||Deposit )
Error
( Type:Bank |1/ 1'19|100,000.00|Opening Balance|X|100,000.00|Transfer||Bank1|Transfer )
Error
( 1/20'19|-77,000.00|Bank Transfer|-77,000.00|Transfer||Bank2|Transfer )
Error
( 2/ 4'19|24,000.00|Bank Transfer|24,000.00|Transfer||Bank2|Transfer )
Error
( Type:Bank |1/ 1'19|90,000.00|Opening Balance|X|90,000.00|Transfer|Bank2|Bank2|Transfer )
Import finished successfully
Total Imported : `


The following is the QIF file generated by Quicken:

**Comment by t4777sd** [comment]
In the last message the import was done with Money Manage Ex ALPHA. I attempted it in the latest stable version. The exact same file. Here is the output which you can see is different than the alpha version:

```
Added account: Bank1
Added account: Bank2
Added payee: Unknown
Date format or date mask is incorrect
Error: 
( Option:AutoSwitch
Account|Bank|Unknown|Bank1||Deposit )
Date format or date mask is incorrect
Error: 
( Bank|Unknown|Bank2||Deposit )
Date format or date mask is incorrect
Error: 
( Clear:AutoSwitch
Option:AutoSwitch
Account|Bank|Unknown|Bank1||Deposit )
Error: Transaction Account is incorrect
( Type:Bank |1/ 1'19|100,000.00|Opening Balance|X|100,000.00|Transfer||Bank1|Transfer )
Error: Transaction Account is incorrect
( 1/20'19|-77,000.00|Bank Transfer|-77,000.00|Transfer||Bank2|Transfer )
Error: Transaction Account is incorrect
( 2/ 4'19|24,000.00|Bank Transfer|24,000.00|Transfer||Bank2|Transfer )
Error: Transaction Account for transfer is incorrect
( Type:Bank |1/ 1'19|90,000.00|Opening Balance|X|90,000.00|Transfer|Bank2|Bank2|Transfer )
Import finished successfully
Total Imported : 2
```

**Result in MoneyManager Ex**

1) Bank1 and Bank2 were created as bank accounts
2) Bank1 final balance is $53,000 (it records a $77,000 deposit and a $24,000 withdrawal)
3) Bank2 final balance is NEGATIVE $53,000 (it records a $77,000 withdrawal and a $24,000 deposit)

It appears in this version of MMex the primary issue is the accounts initial balances.
