### ISSUE TITLE
Categories:Monthly report - add date ranges

### ISSUE THREAD

**Issue by phildivalerio** [moneymanagerex/moneymanagerex#2036]
It would be really useful if the Categories:Monthly report would allow date ranges to be specified.

**Comment by vomikan** [comment]
?

**Comment by phildivalerio** [comment]
Hi.  The Categories:Monthy report is very useful, but the only available
view is a rolling 12-month listing with totals.  I'd like to be able to
select fiscal year to date for that report.

Regards
Phil

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=1&t=45612

I am looking something like wxCalendarCtrl but I need only header for month and year selection.
Examples:
[ << < February 2019 > >> ] or [ < February 2019 > ]

**Comment by vomikan** [comment]
done
