### ISSUE TITLE
Resulting transactions sums zero when in Transaction Report there is any "Category" selected

### ISSUE THREAD

**Issue by 48mWsPK** [moneymanagerex/moneymanagerex#2037]
**Describe the bug**
Resulting transactions sums zero when in Transaction Report there is any "Category" selected.

**To Reproduce**
1. Go to 'Reports', 'Transaction Report'
2. Click on 'Category' checkbox, select any of the the possible categories
3. Close category list and then click on 'Activate' button to generate report
4. See error - all listed transactions are with 'Amount' equal to 0 (zero), even though if we click on transaction ID we can see the correct amount

**Expected behavior**
Use the amount set in the transaction in the generated report instead of zeroes only.

**Screenshots**
![1](https://user-images.githubusercontent.com/42578846/53022648-49244b00-3464-11e9-8ce6-703ee9885377.png)
![2](https://user-images.githubusercontent.com/42578846/53022404-c3a09b00-3463-11e9-91a4-a081917850eb.png)

**Additional context**

**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

Version: 1.4.0-alpha.7
Database version: 13 (aes128cbc)
Git commit: ab83908e (2019-01-06)

**Comment by 48mWsPK** [comment]
Is this expected behaviour?

Because I tried filtering by accout, by sum, by status in the Transaction Report Filter dialog, and only when I select 'Category' then transactions show up with amount zero.

**Comment by slodki** [comment]
It's working for me... Could you test using a new db end with new transactions entered?

**Comment by 48mWsPK** [comment]
The problem may have something to do with PORTABLE version - I created a new db, threw in several transactions just for the testing, and the problem persists:

Here is my new DB:
![3](https://user-images.githubusercontent.com/42578846/53072606-4e2ddc80-34ee-11e9-95a3-c963be1718d5.png)

And here I try to filter with Transactions Report only category 'Food:Groceries':
![4](https://user-images.githubusercontent.com/42578846/53072659-7d444e00-34ee-11e9-88d6-cdc5fc117fd5.png)

Do you want me upload the DB for you?
I used encrypted DB, by the way, because I generally use encryption wherever possible...

**Comment by 48mWsPK** [comment]
I also noticed my main DB is using extension .EMB, while the new DB created with Version: 1.4.0-alpha.7, even though **also encrypted** is saved as .MMB file...
Could it be somehow related?

**Comment by slodki** [comment]
Please post your test db... (you have to zip it before posting here)

**Comment by 48mWsPK** [comment]
Here you go:

[test-2019-02-20.zip](https://github.com/moneymanagerex/moneymanagerex/files/2883667/test-2019-02-20.zip)

The password for the test DB is 123

**Comment by 48mWsPK** [comment]
Trying to help here:
What settings are stored in mmexini.db3 that could affect the problem described above?
Because, if I remember correctly, I used my old mmexini.db3 on top of the clean one provided in the .ZIP portable MMEX download....

**Comment by vomikan** [comment]
It's working for me
![image](https://user-images.githubusercontent.com/6836805/53083026-28fd9600-350f-11e9-8264-2a504fc2f0b8.png)

**Comment by 48mWsPK** [comment]
@vomikan Are you sure that you are using the exact same version of MMEX?
I just tried redownloading this [W10 X64 PORTABLE ZIP MMEX](https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.4.0-alpha.7/mmex-1.4.0-alpha.7-win64-portable.zip), extracted it on my D: drive, put the test.mmb file in the folder with the README.txt and version.txt files, launched MMEX from the bin folder, it gave me the error that it cannot fine system translation, so I reached the UI and set language 'English'; then I opened up test.mmb and still the Transaction Report Amount columns had only zeroes in it...
Could it be that I am not using English (US) nor English (UK) as my Windows locale?

Just to compare, what MMEX version are you using, and on what platform/locale?

**Comment by vomikan** [comment]
@48mWsPK I am using only newest even not released version becouse I am developer.

**Comment by 48mWsPK** [comment]
I can confirm that as of 2019-02-21 the portable Windows 64bit version of MMEX identified as 
Version: 1.4.0-alpha.7
Database version: 13 (aes128cbc)
Git commit: d4e4dd91 (2019-02-20)
in the Help -> About dialog box 
**works as expected**

Therefore, I close this issue.

P.S. A small note to developers: please, see how in the releases section, the download files **name** are exactly the same both for the latest nightly and the previous "manual" release, i.e. if one wants to download Win64bit-portable .ZIP the files are named both
**mmex-1.4.0-alpha.7-win64-portable.zip**

for either

`
Pre-release nightly d4e4dd9 nightly
@slodki slodki released this 7 hours ago
release created by AppVeyor CI
`

or

`
Pre-release v1.4.0-alpha.7 ab83908v1.4.0-alpha.7
@slodki slodki released this on 8 Jan
`

P.S. 2: I miss my translation language - how can I help translate MMEX UI?

**Comment by slodki** [comment]
https://crowdin.com/project/moneymanagerex

**Comment by 48mWsPK** [comment]
Just for posterity:
The problem described in this issue is AFAICT fixed with commit 3735a675d0060ecb37a1963.

**Comment by vomikan** [comment]
@48mWsPK what is your language?
If missing in crowdin let me know.

**Comment by 48mWsPK** [comment]
> @48mWsPK what is your language?
> If missing in crowdin let me know.

@vomikan Bulgarian. Yes, vomikan, it is missing in crowdin - please add it so I can contribute...

**Comment by vomikan** [comment]
https://crowdin.com/project/moneymanagerex/bg#
велкам

**Comment by 48mWsPK** [comment]
@vomikan Thanks, mate!

I will work on it when I have some spare time... and I'll let you now when I have something ready.

**Comment by vomikan** [comment]
FYI all changes immediately comes as pull request into my repository. Then I push it to the master branch.
Do not worry about getting me informed.
