### ISSUE TITLE
Just cretaed recurring transaction frequency issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2045]
![image](https://user-images.githubusercontent.com/6836805/53299399-6b461080-384a-11e9-8483-b3bbda27a364.png)

**Comment by vomikan** [comment]
How to reproduce:
![image](https://user-images.githubusercontent.com/6836805/53299431-f0312a00-384a-11e9-8084-0d5bc56971e5.png)

**Comment by slodki** [comment]
duplicate #2010 ?

**Comment by vomikan** [comment]
Possible yes
