### ISSUE TITLE
Cash flow report empty issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2047]
In case if no transactions for "Cashflow" report it ignore recurring transactions.

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/cashflow.cpp#L75

**Comment by slodki** [comment]
This line only skips checking accounts without transactions.

**Comment by vomikan** [comment]
I've changed this line to:
```
double initConvRate = 1;
        if (!transactions.empty())
        {
            // Use account first transaction date for initial balance
            initConvRate = Model_CurrencyHistory::getDayRate(account.CURRENCYID, transactions[0].TRANSDATE);
        }
```
Now I can create cash flow report.

**Comment by vomikan** [comment]
@slodki 
I am disagree regarding balance calculation.
Example. I have bought 100$ last year and spend 3500RUB for it. This year I've bought 100$ and spend 6500RUB.
What is a balance in RUB?
IMHO 13000 not 10000.
For cash flow we need balances for today then add forecast amounts.

**Comment by slodki** [comment]
This is ok only if we use future dates in the report only. This is true for cashflow reports in MMEX.
