### ISSUE TITLE
Category Income/Expenses - Last 12 Months graph needed

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2065]
It would be nice to see bar or line chart with income vs expenses.

Related issues:
https://github.com/moneymanagerex/general-reports/issues/58
https://github.com/moneymanagerex/moneymanagerex/issues/2036

**Comment by vomikan** [comment]
sample:

![image](https://user-images.githubusercontent.com/6836805/53492079-09cfad00-3aa9-11e9-8732-498a7d797f25.png)

**Comment by zsolt89s** [comment]
Hello,

for me it would be a nice feature to filter this report by account. Best would be to select accounts which should be included in the report and which not, but if it would be only a select one account or all accounts option that would be helpful too.

Thanks.

**Comment by vomikan** [comment]
@zsolt89s it's possible and even more easy than #2036
Your FR accepted.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2069
