### ISSUE TITLE
    wxSplitterWindow for GRM

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2066]
It's time to add  wxSplitterWindow for GRM UI 
Sample:
```
    wxSplitterWindow *splitter = new wxSplitterWindow(this, wxID_ANY,
                                            wxDefaultPosition, wxDefaultSize,
                                            wxSP_NOBORDER);
```

**Comment by vomikan** [comment]
I've added splitter between SQL text and DB structure
But can't add splitter where is a yellow line
![image](https://user-images.githubusercontent.com/6836805/53694904-eae15b80-3dc5-11e9-868e-dcdb6213aec5.png)

**Comment by vomikan** [comment]
The same for 
![image](https://user-images.githubusercontent.com/6836805/117480305-1b0a8300-af6a-11eb-93d3-fe30bc2cd80b.png)

**Comment by whalley** [comment]
Splitter for Themes added, that one for GRM looks trickier....

**Comment by whalley** [comment]
> Splitter for Themes added, that one for GRM looks trickier....

My head is spinning trying to sort out the splitter for GRM..... I'll leave it for now.

**Comment by whalley** [comment]
Starting with old school pen and paper helped.... :-) Splitter now added.
