### ISSUE TITLE
Make easier to customise the home page. 

### ISSUE THREAD

**Issue by maikeldotuk** [moneymanagerex/moneymanagerex#2068]
**Is your feature request related to a problem? Please describe.**
Took me a while to figure how to change the content in the homepage, I couldn't find anything about it in the official documentation nor the forums. So I ended up bothering you guys in Slack. Happily I got an answer pretty quickly there. 
The problem is multiple:
1. Lack of documentation about what to edit to change the homepage. 
2. Lack of documentation as to what are each one of the name substitutes on the template of the homepage in /res. 
3. The folder itself copies into /tmp  (not sure why), even though every change I make on the one in /usr/share/mmex appears instantly on the /tmp/copy when I go elsewhere in the application and back to the homepage. So I've ended up moving /usr/share/mmex to ~/.mmex and linking (symlink) to that one so I could edit it without sudo. Let alone backing up the changes from one PC to the another one using Syncthing. 

**Describe the solution you'd like**
1. I would like, upon first usage by a user (sorry, English isn't my first language), for to application to copy the files from the res foolder **to either .config/mmex or .mmex** or wherever in **that user** owned folders. 
2. I would like documented name substitutions for every possible thing that I could put in that file. For example, I'd like to put "$(Company Name) Accounts" in the top but I have no idea what is the variable to extract it. I don't even know if such variable exist. 
3. I want a pony, a bubble bath, two cheese stuffed pizzas and a hammock (kidding). 

**Describe alternatives you've considered**
Point 3 of the first part already described what I've done to customised mine but it's just a hack. To skim through the source code to find the names of the variables was an idea but....why bother when someone more literate on it could just enumerate them in a wiki file? Also I'm not good with C++

**Additional context**
The results of my edits:

![2019-02-27-150129_1921x1076_scrot](https://user-images.githubusercontent.com/29461493/53500312-fec54e80-3aa1-11e9-83e2-ba59cd75ea13.png)

Btw, using stock Bootstrap instead of the tiny version that come included in the master.css file, I didn't need to scale it up to 200 in the Options, for the text to not look **tiny** in that homepage. Also scaling the original template to 200, using that parameter in the Options window, scales e-v-e-r-y-t-h-i-ng up, including the icons. The text becomes readable but the icons look awful, as they become extra-granny-eyesight big.

**Comment by maikeldotuk** [comment]
My next step is to change it entirely to dark mode.

**Comment by vomikan** [comment]
FYI
https://gist.github.com/ZachSaucier/8295d9dc926d7064ff0d4f3f04b35b55

**Comment by l0ner** [comment]
Also: it would be nice to be able to inlude reports (default and user generated) on the homepage.
