### ISSUE TITLE
PPA available?

### ISSUE THREAD

**Issue by natrius** [moneymanagerex/moneymanagerex#2084]
Trying to install it on KDE neon. There is a mention in the scourceforge wiki but it does not work https://sourceforge.net/p/moneymanagerex/wiki/Install%20mmex%20on%20Ubuntu%20Linux/

I would love to see an ppa available to install it on Ubuntu. I found this https://packagecloud.io/moneymanagerex/moneymanagerex but i did not try it right now because it's for Ubuntu 16.04 .

Otherwise i would like to know what i have to do with the instructions in the BUILD.md for Ubuntu with the GCC.

`mkdir moneymanagerex/build
cd moneymanagerex/build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target package`

cmake does not work when trying it, its `cmake not found` 

Greetings

**Comment by slodki** [comment]
Please follow [packagecloud instructions](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md#from-mmex-repository) from [INSTALL.md](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md) to use package repo with unstable packages.

Please follow [Snap Store instructions](https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.md#from-snap-store) if you are interested in the stable version or sharing db with Android app.

PS. You must run each command from BUILD.md separately:
```
mkdir moneymanagerex/build
cd moneymanagerex/build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target package
```
or use `&&` to execute as one pipeline:
```
mkdir moneymanagerex/build && cd moneymanagerex/build && export MAKEFLAGS=-j4 && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target package
```

**Comment by slodki** [comment]
#1169

**Comment by natrius** [comment]
I personally refuse to use snap or docker because there were various security issues with it in the last months. Not your problem, i guess. 

Thanks for your answer, i did run each command on its own, but as said, i got the "cmake not found" (i guess, the messed-up copy&pase code made you think otherwise)

I tried using 
`curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh | sudo bash`
 but i got the following error: 

```
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/moneymanagerex_moneymanagerex.list...curl: (22) The requested URL returned error: 404 


Unable to download repo config from: https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/config_file.list?os=neon&dist=bionic&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
```

But i guess since i don't want to use snap but want to use the android (thanks for the f-droid) there is no sense in trying to get it to run?

**Comment by slodki** [comment]
For 1.3.3 there are  possibilities:
* use snap package
* compile from sources

For 1.4.0 (unstable) there are:
* downloadable deb from GitHub
* snap package
* PPA using (look at the end of this command!)
  ```
  curl -s https://packagecloud.io/install/repositories/moneymanagerex/moneymanagerex/script.deb.sh | os=ubuntu dist=bionic sudo -E bash
  ```

**Comment by natrius** [comment]
Out of curiosity, why not simply making ppa too for the stable versions? Can't use it with the android app right not, but not that big of a problem imho. I mean, somehow there is already a ppa with the versions.
