### ISSUE TITLE
Unable to mark non-selected transaction

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#2090]
**Describe the bug**
It is not possible to mark a transaction that is not currently selected.

**To Reproduce**
1. Open a database
2. Click on any 1 transaction
3. Right click another transaction in attempt to mark it
4. Mark options are shaded out

**Expected behavior**
Ability to mark a transaction not in focus

**Screenshots**

**Additional context**
Currently you have to left click first then right click to mark a transaction which one extra click.

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [x] development version (git master branch)

**Comment by vomikan** [comment]
In that case two transactions being selected.
Edit, copy, move and delete options are available.
If Edit chosen - Multi Transactions update dialog provide an option to update status as well.

**Comment by vomikan** [comment]
It's native OS widget issue
