### ISSUE TITLE
Unable to create custom report

### ISSUE THREAD

**Issue by Lou1025** [moneymanagerex/moneymanagerex#2092]
MMEX version 1.3.3 OS is Mojave . I can get to the report manager but when I get to the place where I need to drag SQL items to the window it looks like it is going to add the command but nothing gets added to the window. Am I missing something?

**Your OS:**
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by Lou1025** [comment]
MMEX version 1.3.3  OS is Mojave . I can get to the report manager but when I get to the place where I need to drag SQL items to the window it looks like it is going to add the command but nothing gets added to the window. Am I missing something?

**Comment by vomikan** [comment]
Is this issue the same ? 
https://github.com/moneymanagerex/moneymanagerex/issues/1219

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/general_report_manager.cpp#L1144

possibly wxUSE_DRAG_AND_DROP not defined for your OS
