### ISSUE TITLE
VS2017 throws compile warning after commit e54aef6

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#2097]
**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
https://user-images.githubusercontent.com/6836805/54277210-479bfd80-45a0-11e9-8fee-37956e04c59e.png

**Comment by grumpy235** [comment]
Thanks Nikolay, that removes the warning message.

**Comment by vomikan** [comment]
@slodki please check if it working on Linux

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/54517032-ab903e80-4971-11e9-9fa4-ab15715cd6f3.png)

https://github.com/moneymanagerex/moneymanagerex/commit/8d352a5d5404fabda6cbdbb9f31418e264f1cfa5

**Comment by vomikan** [comment]
L is working u8 not.
```        data.push_back(wxVariant(is_base_currency ? L"\u2691" : L"")); ```
![image](https://user-images.githubusercontent.com/6836805/54517246-2f4a2b00-4972-11e9-8931-b0f0fd2852c8.png)
