### ISSUE TITLE
add support for date format with dot after ALL date components

### ISSUE THREAD

**Issue by milotype** [moneymanagerex/moneymanagerex#2098]
**Is your feature request related to a problem? Please describe.**
All numerical date values are ordinal numerals in croatian (and other languages). But there's no such date format in the preferences.

**Describe the solution you'd like**
Please add an additional numerical date format in the pull-down within the preferences dialog: "DD.MM.YYYY."

**Comment by vomikan** [comment]
I believe it's already there.

**Comment by slodki** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/e54aef6d13507e596842045875dad98583616cb2/src/util.cpp#L751

https://github.com/moneymanagerex/moneymanagerex/blob/e54aef6d13507e596842045875dad98583616cb2/src/util.cpp#L781

**Comment by milotype** [comment]
**All** date strings need a period. But the **year** is missing it.
Tnank you!
Just checked it again on MacOSX, MMEX 1.3.3

**Comment by slodki** [comment]
Croatian date formatting: http://www.unicode.org/cldr/charts/latest/verify/dates/hr.html

**Comment by milotype** [comment]
Interestingly there are cases, where the period after the "year" is present.
 => see attachment top right side
At the same time, on the left side MMEX shows a ISO format (even though in my prefs I use "DD.MM.YYYY" !!!
![Different dates](https://user-images.githubusercontent.com/43657314/54476695-a1026780-4800-11e9-81e0-e154d2d11e34.png)

**Comment by slodki** [comment]
Calendar widget uses native system control (under wxGTK, wxMSW ports) - wxWidgets cannot modify its appearance, so it's using system settings. All dates generated by MMEX uses the date format from MMEX options.

**Comment by milotype** [comment]
Which dates ar you talking about from my previous attached picture: those in the upper righthand side or on the lower lefthand side?
My locale setting is croatian. (probaly what's used in the upper righthand dates)
My MMEX setting is DD.MM.YYYY
So I don't know where the YYYY-MM-DD is coming from in the lower lefthand side.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/reportbase.cpp#L305

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/55325715-84b42b00-548e-11e9-933a-72a99236f232.png)

**Comment by vomikan** [comment]
I've added OS defined date format into the list of most used date formats.
It seems would work and may be accepted. 
But here is a potential bug. In case if, for example, 'DD.MM.YYYY.' will be saved in portable mode then app moved to other OS without this date format. Export/Import functionality will work with restrictions.
