### ISSUE TITLE
add missing english string in .po/pot file

### ISSUE THREAD

**Issue by milotype** [moneymanagerex/moneymanagerex#2099]
**Describe the bug**
Please add missing english string in .po/pot file for the abbreviated month of "May". All other months have their abbreviations, except for May. (and in croatian it’s called different, and has more than three letters) => see screenshot

**Screenshots**
2_long-month-name.png
![2_long-month-name](https://user-images.githubusercontent.com/43657314/54465197-36a6e400-477a-11e9-8640-03fc2e613d03.png)

**Comment by slodki** [comment]
#2018 is required here

**Comment by vomikan** [comment]
January Jan 
February Feb
March Mar
April Apr
May May !!!!
Here some trick should be help like to add space siffix for short name.

**Comment by slodki** [comment]
No more tricks, just use proper translation function:
```
wxGETTEXT_IN_CONTEXT("full month name", "May")
wxGETTEXT_IN_CONTEXT("3-letter abbreviation", "May")
```

**Comment by vomikan** [comment]
How to integrate it with crowdin or poeditor?

**Comment by slodki** [comment]
1. For `*.pot` file creation following params should be used:
   ```
   XGETTEXT_ARGS="--keyword=_ \
                  --keyword=wxTRANSLATE \
                  --keyword=wxPLURAL:1,2 \
                  --keyword=wxGETTEXT_IN_CONTEXT:1c,2 \
                  --keyword=wxGETTEXT_IN_CONTEXT_PLURAL:1c,2,3 \
                  --language=C++ \
                  --sort-by-file \
                  --add-comments=TRANSLATORS \
                  --from-code=UTF-8 \
                  --add-location \
                  --package-name=MMEX \
                  --no-wrap \
                  --msgid-bugs-address=developer@moneymanagerex.org"
   ```
2. `.pot` fille will contain:
   ```
   #: util.cpp:818
   msgctxt "full month name"
   msgid "May"
   msgstr ""

   #: util.cpp:830
   msgctxt "3-letter abbreviation of month name"
   msgid "May"
   msgstr ""
   ```
3. This can be easily translated into `.po` file:
   ```
   #: util.cpp:818
   msgctxt "full month name"
   msgid "May"
   msgstr "Xyzeetqoirthorthh"

   #: util.cpp:830
   msgctxt "3-letter abbreviation of month name"
   msgid "May"
   msgstr "Xyz"
   ```

There should be place somewhere in Crowodin to define keywords for `xgettext`. Crowdin has a field beneath the string in the translation view where context is shown.

**Comment by vomikan** [comment]
I can't check if it working because #2106

**Comment by vomikan** [comment]
It should be OK
