### ISSUE TITLE
Add AppStream metadata to Linux packages

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2117]
https://www.freedesktop.org/software/appstream/docs/index.html

> Every software center that exists allows the user to look at screenshots and a long description of the application before it is installed. For most users it allows them to answer the question “Do I want to install this application?”. Traditionally in Linux distributions, we have none of this data for the vast majority of our desktop user-installable applications. The packages-descriptions are describing all contents of a package, and not just a single application. They are also often written in a technical language and refer to other packages, which makes it hard for beginners to understand what the application they want to install really does. Additionally, if you are not using Debian or Ubuntu, the package descriptions are often untranslated. Also, packages do not provide some metadata users might be interested in before installing an application.

**Comment by slodki** [comment]
https://wiki.debian.org/AppStream
> The metadata can for example be used by software centers like GNOME Software or KDE Discover to display a user-friendly application-centric way on the package archive.
>
> Additionally, AppStream is used by several other projects, like the Limba installer and LVFS (Linux Vendor Firmware Service) to provide metadata about provided software components.

**Comment by ovari** [comment]
Can this be closed as https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/org.moneymanagerex.MMEX.metainfo.xml is the metadata file? Thank you
