### ISSUE TITLE
1.4.0 Alpha-7 fails to export QIF

### ISSUE THREAD

**Issue by bingalls** [moneymanagerex/moneymanagerex#2123]
When I try to export my database to QIF with Categories, I get (note that none of the error text can be copy/pasted)
A debugging check in this application has failed
/usr/local/include/wx-3.1/wx/strvararg.h(445): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
details:
[01] wxArgNormalizer<int>:wxArgNormaizer(int, wxFormatString const*, unsigned int)
...
<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git ab83908e (2019-01-06)<br><b>Libs</b>: wxWidgets 3.1.2 (wxMac 10.11) • wxSQLite3 4.4.0 (SQLite 3.26.0) • Mongoose 6.13 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.43.0 • SecureTransport • zlib 1.2.5<br><b>Build</b>: Jan 7 2019 23:18:23 • CMake 3.12.3 • Xcode 10.1 • gettext 0.19.8.1 • Clang 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)<br><b>OS</b>: OS X El Capitan Version 10.11.6 (Build 15G22010) • English (U.S.) (Western (Mac OS Roman)) • 1440x900 32bit 111x110ppi</small>

**Comment by slodki** [comment]
```
[1] wxArgNormalizer<int>::wxArgNormalizer(int, wxFormatString const*, unsigned int)
[2] wxArgNormalizerWchar<int>::wxArgNormalizerWchar(int, wxFormatString const*, unsigned int)
[3] wxString wxString::Format<int>(wxFormatString const&, int)
[4] mmQIFExportDialog::mmExportQIF()
[5] mmQIFExportDialog::OnOk(wxCommandEvent&)
[6] mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
```

BTW: there are *Save to file* and *Copy to clipboard* in my assertion dialog window:
![screenshot](https://user-images.githubusercontent.com/3155552/55307149-f1133800-5456-11e9-8128-fe032b23d9d9.png)

**Comment by bingalls** [comment]
![image](https://user-images.githubusercontent.com/761187/55321432-a2aa6d00-5447-11e9-9446-ccb34accea01.png)
Sorry, there are no such buttons in my MMEX. Thanks for showing me how to paste a screenshot in Github.
