### ISSUE TITLE
Aggiunta di un ID progressivo per ogni singolo conto e non progressivo generalizzato

### ISSUE THREAD

**Issue by LinusJak** [moneymanagerex/moneymanagerex#2129]
ID progressivo generalizzato per ogni singolo inserimento.
E' possibile aggiungere un nuovo identificatore per ogni singolo conto grazie.

Complimenti per il programma sempre più performante

LinusJak

**Comment by slodki** [comment]
Che ID intendi: ID della transazione?
Intendi contatori ID transazione separati per ogni conto?

**Comment by slodki** [comment]
![screenshot](https://user-images.githubusercontent.com/3155552/55692037-62497280-59a4-11e9-9b75-f8a151fada97.png)
