### ISSUE TITLE
Snap package reports missing language files

### ISSUE THREAD

**Issue by be-we** [moneymanagerex/moneymanagerex#2131]
The Money Manager Ex snap package on [Snapcraft](https://snapcraft.io/mmex) for _Ubuntu 16.04 or later_ reports missing language files on first startup and the GUI is obviously English only.

![mmex_translation_files_error](https://user-images.githubusercontent.com/16528381/55684065-259b5e00-5947-11e9-8758-1678c6165f8d.png)

**Comment by slodki** [comment]
In MMEX version 1.3.3 no GUI translations are loaded at startup (see above error) nor language cannot be selected in Options menu.

I think it was broken in 99e55bda570dae5069341f5d948981d7c9afc6fa.
Install path for `.mo` files was changed to
https://github.com/moneymanagerex/moneymanagerex/blob/2a90484293b5020556d835054285fd77a3ee1150/build/bakefiles/mmex.bkl#L104

but MMEX 1.3.3 always uses English as GUI language and changes only catalog file loaded from `en` sub-directory.

@vomikan Are we planning any bug-fix releases in 1.3.x branch?

@be-we You can try snap from edge channel (1.4.0 version) but this version is not compatible with Android app.

**Comment by vomikan** [comment]
I have no time for 1.3.x
We should ask @MisterY regarding new DB structure support of android app.
In case if it possible we should release 1.4.0
I beleave fork and release mmex2 good idea as well.

**Comment by MisterY** [comment]
I was hoping it would be possible to just update the schema. After I checked the changes in the database repo, there seem to be too many breaking changes. Pretty much all the queries will need to be changed and tested, all the data definitions updated. This would take a couple of days in the best case, which I, unfortunately, do not have.
I will create an issue in the repo. Perhaps other volunteers would have time to implement this. 
Also, those who really need it can submit pull requests, too. It's an Open Source project.

**Comment by vomikan** [comment]
https://l.facebook.com/l.php?u=https%3A%2F%2Fpoll.app.do%2Fwhat-would-you-prefer-2511558%2Ftfgjc1zF%3Ffbclid%3DIwAR0z3v0JJ0hFY_3swKKO07N-vqk-I-3bbj1RxLbxj1fcGHEJgDYnBbNW_Y4&h=AT1IFXfGcU6bpuOGVyylOjBTn_ayTvmgvsyRfewC2AxWT8r1jXeXOBOj6nvKuftr0NhcuQD-mN-7juOPEnfyUlBxufRanRcUv-h0EkvWc9gL_vBOsltqpFTIOJcKLmJb1NRXyW2p7hsHPtA4wCnoxBti2f-MFaKq_pnfSXqqgRiS3SDw7I_kLQJpUGN5Ai6No7Qrow0XqiT0zlI9mHnTXbImnRh4nvP33dhHXFjFaYppCN4jCE3E-GuJUbLowlTaIPTrvPirMvpl8u8V_SJjgKmUt1xansYsBRSvc5D7aQxyEFLggDOMA0Qmn5fYAUbESO-9hBUSlQP-sx18DwlXc14vHduiyakjCt1RwVDLj-zgvzvJzV6EjkvFSpm8zGy17vXVWHx1tlsxX5tQ3rzcFJRq3tIqdFRMa2co0-aKKAZV_Id2zqIaXSt724An5k0rVkKQYIzpwsKnS2HarQnPiW6kw3sOWeWfzOWEyxls4acEXFdU0RBgP_z9_pbQf3HmmlG3wCABVgX68YxWP0okuGOs14st6n4toILKgJ9wcM6VZUUKTVQDdFZJdqhQMyvi91NJzSLa0zsvjYo0pOR4cSEAxJkXJtPjWE2TJAsi-WhMF6WVUlBNHdQXE_J_cH1WW-eZ

**Comment by slodki** [comment]
I will rebuild snap package with fixed dir structure without changing 1.3.3 version - app code will be the same only dir structure changed.

**Comment by slodki** [comment]
@be-we You can refresh your snap now - it has been fixed.

**Comment by be-we** [comment]
@slodki Thanks for fixing this bug. :+1:
