### ISSUE TITLE
Many bugs with QIF import -- Test cases inside

### ISSUE THREAD

**Issue by t4777sd** [moneymanagerex/moneymanagerex#2132]
Using the very latest alpha version.

**Describe the bug**
Import from valid QIF files generated from quicken does not produce desired results

**To Reproduce**

Here is the QIF file:

```
!Option:AutoSwitch
!Account
NChecking 1
TBank
^
NChecking 2
TBank
^
!Clear:AutoSwitch
!Option:AutoSwitch
!Account
NChecking 1
TBank
^
!Type:Bank 
D1/ 1'18
U0.00
T0.00
CX
POpening Balance
L[Checking 1]
^
D1/ 5'18
U85,000.00
T85,000.00
PPayer #1
LConsulting Income (Business)
^
D1/ 5'18
U-12,000.00
T-12,000.00
PBill #1
LMisc. Expense (Business)
^
D1/ 5'18
U-11,000.00
T-11,000.00
PBank Transfer
L[Checking 2]
^
D1/ 5'18
U-11,039.00
T-11,039.00
PSplit Expense
LAuto & Transport:Gas & Fuel
SAuto & Transport:Gas & Fuel
$-39.00
SHealth & Fitness:Doctor
$-11,000.00
^
D1/ 5'19
U-14,000.00
T-14,000.00
PBank Transfer
L[Checking 2]
^
D1/17'19
U17,500.00
T17,500.00
PSplit Income
LOther Income (Business)
SOther Income (Business)
$5,000.00
SNet Salary
$12,500.00
^
D1/17'19
U-23,200.00
T-23,200.00
PSplit With Transfer
LHealth & Fitness:Doctor
SHealth & Fitness:Doctor
$-12,000.00
S[Checking 2]
$-11,200.00
^
!Account
NChecking 2
TBank
^
!Type:Bank 
D1/ 1'18
U0.00
T0.00
CX
POpening Balance
L[Checking 2]
^
D1/ 5'18
U11,000.00
T11,000.00
PBank Transfer
L[Checking 1]
^
D1/ 5'19
U14,000.00
T14,000.00
PBank Transfer
L[Checking 1]
^
D1/17'19
U11,200.00
T11,200.00
PSplit With Transfer
L[Checking 1]
^
D1/17'19
U-12,500.00
T-12,500.00
PSelf Transfer Payment
L[Checking 2]
^
D3/17'19
U12,650.00
T12,650.00
PSelf Transfer Deposit
L[Checking 2]
^
D4/ 8'19
U137,000.00
T137,000.00
PPayer #2
LNet Salary Spouse
^
D4/ 8'19
U-17,000.00
T-17,000.00
PBill #2
LHealth & Fitness:Dentist
^
```

The QIf file and images of what the results SHOULD be are here: https://send.firefox.com/download/490fe390140b628e/#S2SQQXe-UJ-zgWwH6SCq8A

Summary of **correct** results ending balance:
Checking 1: $31,261
Checking 2: $156,350

Summary of actual results in mm:
Checking 1: $0.00
Checking 2: $120,000

**Comment by vomikan** [comment]
Seems mmex skips 'Self Transfer Payment'
It seems like transfer from 'Checking 2' to the same 'Checking 2' account.
```
D1/17'19
U-12,500.00
T-12,500.00
PSelf Transfer Payment
L[Checking 2]
^
D3/17'19
U12,650.00
T12,650.00
PSelf Transfer Deposit
L[Checking 2]
```

**Comment by vomikan** [comment]
I've changed a bit QIF import. Result:
![image](https://user-images.githubusercontent.com/6836805/55785038-68ca0e00-5aba-11e9-9016-a56a97867f60.png)

![image](https://user-images.githubusercontent.com/6836805/55785072-75e6fd00-5aba-11e9-8c17-4a55a49dd770.png)

**Comment by t4777sd** [comment]
Shouldn't the Checking #1 ending balance be $31,261. Maybe I am misreading the image, but it appears the 2nd to last line is $31,261, but then it gets reduced down to $20,061 which is different than the ending balance it should be.

**Comment by vomikan** [comment]
The last transaction of acc1 is transfer of 11200 to acc2. Tranfers in mmex shown in both acc - whitch money goes out and second one where the money comes.
(Look at the transaction ID)

**Comment by vomikan** [comment]
Seems 'Split With Transfer' is some (magic for me) type of transaction.
