### ISSUE TITLE
android app budgets - estimated values

### ISSUE THREAD

**Issue by brianl44** [moneymanagerex/moneymanagerex#2135]
For the android app in the budgets, can the estimated value and the category totals be made available like in the windows version?
![image](https://user-images.githubusercontent.com/49240552/55812835-4f709400-5ab1-11e9-8d64-3d5f5464e73e.png)

**Comment by vomikan** [comment]
Please reopen the bug here:
https://github.com/moneymanagerex/android-money-manager-ex/issues

**Comment by slodki** [comment]
moneymanagerex/android-money-manager-ex#1348
