### ISSUE TITLE
Slightly wider edit transaction window

### ISSUE THREAD

**Issue by regs01** [moneymanagerex/moneymanagerex#2137]
**Is your feature request related to a problem? Please describe.**
Year is not visible on hiDPI screen with 150% scaling. Some week days also won't fit.

**Describe the solution you'd like**
Just slightly wider window with wider date picker

**Additional context**
<img width="206" alt="mmex_2019-04-10_06-21-38" src="https://user-images.githubusercontent.com/10468217/55849547-ad58b680-5b59-11e9-932a-34342347d294.png">

**Comment by vomikan** [comment]
#478

**Comment by slodki** [comment]
[wxWindow::FromDIP()](https://docs.wxwidgets.org/3.1/classwx_window.html#aa934a31552633c076a87bca1100b0dc5) with example
