### ISSUE TITLE
update

### ISSUE THREAD

**Issue by stantheman1** [moneymanagerex/moneymanagerex#2146]
Hi
Each time I open program it says their is an update.
However I am on Version 1.4 but your NEW version is 1.33  ??
Please explain??
Thanks you

Stanley Pearce

<hr><small><b>Version</b>: 1.4.0-Alpha.3 ⬥ db 7 ⬥ git 79562d4 (2017-08-11)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 10.0) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Aug 11 2017 11:55:37 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 10 (build 17134), 64-bit edition Little endian ⬥ English windows-1252 ⬥ 1280x1024x32bit 96x96ppi</small>

**Comment by stantheman1** [comment]
Hi
Each time I open program it says their is an update.
However I am on Version 1.4 but your NEW version is 1.33  ??
Please explain??
Thanks you

Stanley Pearce

**Comment by slodki** [comment]
You are using 1.4.0-Alpha.3 version and there is a [1.4.0-alpha.7](https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.4.0-alpha.7) version ready for testing.

**Comment by stantheman1** [comment]
Am I able to download version 7. If so, please advise link.
Thanks

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/tags

**Comment by stantheman1** [comment]
Hi
I do not understand.
How can I update to 1.40 Alpha 7

**Comment by slodki** [comment]
Download installer from [this link](https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.4.0-alpha.7/mmex-1.4.0-alpha.7-win64.exe) and install new version over the old one.

**Comment by stantheman1** [comment]
Hi
This did not work. Could not write to file.
My database is now corrupt!
 I can see individual accounts but ACCOUNT LIST says "can't open file
'C/Program Files/Money Manager EX/res/home_page. htt' (error 3: the system
cannot find the path specified.)

Please help me!!!!

Stanley Pearce

**Comment by vomikan** [comment]
Could you try right click option on the downloaded app 'Run As Administrator' ?

**Comment by stantheman1** [comment]
Not possible. I can see individual bank accounts but not the Home page
what can I do???

**Comment by vomikan** [comment]
Extract this file https://github.com/moneymanagerex/moneymanagerex/releases/download/nightly/mmex-1.4.0-alpha.6-win64-portable.zip
And copy home_page. htt to
'C/Program Files/Money Manager EX/res/home_page. htt'

**Comment by stantheman1** [comment]
Hi Nickolay
I do not know how to do this
Step by step instruction please 😕

**Comment by vomikan** [comment]
1. download the file from link above
2. double click on it
3. go to \mmex-1.4.0-alpha.6-win64\res
4. copy home_page. htt
5. past it to C:/Program Files/Money Manager EX/res/

**Comment by stantheman1** [comment]
Thank you.
