### ISSUE TITLE
Problem with account open since 2010

### ISSUE THREAD

**Issue by DavidE2910** [moneymanagerex/moneymanagerex#2153]
I have used this software, and found in general that it is excellent, since 2010. However, having just imported a new set of credit card transactions I find that the balance, which last month balanced to zero, is now over £3000 and it should be zero.

The latest ID number is 13007 and these go down in sequence to 828, then there are 4 payments to the card (in 2010 & 2011) and that's it. What happened to the other transactions I wonder?

![mmex problem](https://user-images.githubusercontent.com/49992623/56753453-7eaa2500-6782-11e9-8ac9-e2076966bb00.jpg)

Using V 1.3.3 (DN v.7)

Any suggestions how to recover?

Hope you can help
Many thanks
David Eccles
deccs2@gmail.com

**Comment by vomikan** [comment]
Please show us during order

**Comment by DavidE2910** [comment]
Hi
I'm sorry, but it turned out to be a complete misunderstanding on my part.
I couldn't find a way to delete or stop my incident report. Please close
the case.

I love your software but would love a faster way to get my recurring
transactions in up to a particular date. It takes me ages.

Many apologies again.
David
