### ISSUE TITLE
Weekday name is displayed outside the transaction dialog's border

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2157]
![screenshot](https://user-images.githubusercontent.com/3155552/56866948-c679b800-69df-11e9-8dd8-f8aa912a7436.png)

<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git b115aedf (2019-04-28) fix-casts<br><b>Libs</b>: wxWidgets 3.1.2 (wxGTK 3.24) • wxSQLite3 4.4.2 (SQLite 3.27.2) • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.64.0 • OpenSSL 1.1.1b • zlib 1.2.11 • libidn2 2.0.5 • libpsl 0.20.2 • ( libidn2 2.0.5) • libssh 0.8.6 openssl zlib • nghttp2 1.36.0 • librtmp 2.3<br><b>Build</b>: Apr 28 2019 17:20:39 • CMake 3.13.4 • GNU Make 4.2.1 • gettext 0.19.8.1 • GCC 8.3.0 • Ubuntu 19.04 'disco'<br><b>OS</b>: Ubuntu 19.04 "disco" • Linux 5.0.0-13-generic x86_64 • KDE Polish (UTF-8) • 1680x1050 24bit 98x99ppi</small>

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=23&t=45830

**Comment by slodki** [comment]
I have tried `.Fit()` or `.Layout()` but it doesn't work. I think `wxStaticText` does not support resizing at all.

**Comment by vomikan** [comment]
@slodki could you, please,  provide screenshot?

**Comment by slodki** [comment]
![screenshot](https://user-images.githubusercontent.com/3155552/56898247-dbfaea80-6a90-11e9-9754-2ee512e4206e.png)
It's a bit wider then before - dialog width is static and depends on language used.
Some widgets below are wider too.

**Comment by vomikan** [comment]
Not bad.
#2137
