### ISSUE TITLE
Transaction dialog's choice items too small

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2158]
`wxChoice choiceStatus_` and `transaction_type_` are smaller than other widgets in the transaction dialog:
![screenshot](https://user-images.githubusercontent.com/3155552/56867092-874c6680-69e1-11e9-8766-9e73a9301c73.png)

<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git b115aedf (2019-04-28) fix-casts<br><b>Libs</b>: wxWidgets 3.1.2 (wxGTK 3.24) • wxSQLite3 4.4.2 (SQLite 3.27.2) • RapidJSON 1.1.0 • Lua 5.3.3 • libcurl 7.64.0 • OpenSSL 1.1.1b • zlib 1.2.11 • libidn2 2.0.5 • libpsl 0.20.2 • ( libidn2 2.0.5) • libssh 0.8.6 openssl zlib • nghttp2 1.36.0 • librtmp 2.3<br><b>Build</b>: Apr 28 2019 15:52:29 • CMake 3.13.4 • GNU Make 4.2.1 • gettext 0.19.8.1 • GCC 8.3.0 • Ubuntu 19.04 'disco'<br><b>OS</b>: Ubuntu 19.04 "disco" • Linux 5.0.0-13-generic x86_64 • KDE Polish (UTF-8) • 1680x1050 24bit 98x99ppi</small>

**Comment by vomikan** [comment]
Windows 10
![image](https://user-images.githubusercontent.com/6836805/56868084-7a863d80-69f6-11e9-8efa-b96159cc425f.png)

**Comment by vomikan** [comment]
@slodki what is 'aaa'  on the picture above?

**Comment by slodki** [comment]
It's account selector widget copied from the same dialog (below).

**Comment by vomikan** [comment]
It happens regarding my changes for
https://github.com/moneymanagerex/moneymanagerex/issues/2137 fix.
I've removed all constant values for sizers.
Now we can leave it as is or made the same size as Account has.

**Comment by vomikan** [comment]
#2157

**Comment by vomikan** [comment]
Ubuntu 20.04

```
Money Manager Ex
Version: 1.3.5-Beta.6
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.3 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.3
• libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Build on May 20 2020 19:47:41 with:
• CMake 3.16.3
• GNU Make 4.2.1
• gettext 0.19.8.1
• GCC 9.3.0 • Ubuntu 20.04 'focal'
Running on:
• Ubuntu 20.04 LTS "focal"
• Linux 5.4.0-29-generic x86_64
• English (U.S.) (UTF-8)
• 1280x979 24bit 96x96ppi 
```
![image](https://user-images.githubusercontent.com/6836805/82475697-8a773080-9ad5-11ea-973e-b6861421cfd0.png)
