### ISSUE TITLE
Financial year settings for GRM

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2169]
Hi,

I'm writing a report that is able to set the transaction dates condition to the financial year month and day start values in the INFOTABLE_V1 that are set from the MMEX options screen.

However, the flag in MMEX for Budget: As Financial Years is in a separate settings db 'BUDGET_FINANCIAL_YEARS'

Anyone know if I can access this setting in SQL, LUA, HTML in reports?

Thanks

https://forum.moneymanagerex.org/viewtopic.php?f=16&t=8201&p=17888#p17888

**Comment by siowena** [comment]
Hi, thanks for looking into.  I'm assuming this will go into 1.4.x - any idea when 1.4 will have a formal release?

**Comment by vomikan** [comment]
@siowena I am working on critical bugs fixing. 
It's list of all bugs:
https://github.com/moneymanagerex/moneymanagerex/labels/bug
I want to release 1.4.0 ASAP.
