### ISSUE TITLE
Adding an entry in the "split dialog" must not change a past transaction

### ISSUE THREAD

**Issue by TomNedry** [moneymanagerex/moneymanagerex#2176]
**Describe the bug**
Adding an new entry in the "split" dialog changes the amount of a past transaction.

**Expected behavior**
The transaction amount of a past transaction (which has already happened) should be constant. Each "split amount" can divide this constant just into "category-parts". In the case that the amount of the past transaction has to be edited, a "lock" has to be removed in advance.

Remark: IMHO the date of a past transaction is "< now", which might be not correct in each case.  

**Your OS:**
- [x] Windows

**MMEX version:**
- [x] 1.3.3

**Comment by vomikan** [comment]
I can't reproduce this issue.

**Comment by TomNedry** [comment]
I can reproduce it in 1.4.0 alpha 7. See Animated-Gif:
https://imgur.com/a/qIhwPzz

**Comment by slodki** [comment]
> The transaction amount of a past transaction (which has already happened) should be constant.

I cannot agree. It's a very common scenario to edit transaction parameters for transactions with dates in the past - I edit most of my transactions after they happen, not necessarily on the same day. It would be stupid if I had to change the computer date to be able to edit the transaction.

Maybe you want some kind of protection / locking for transactions? This should be based on the reconciled status and not the date of the transaction IMHO (reconciled = complete, fixed, verified and consolidated with other transactions).

> Each "split amount" can divide this constant just into "category-parts".

Your example is very simple:
* MMEX now calculate: (50) + (25) = (50; 25)
* you expect calculation like this: (50) + (25) = (50-25; 25) = (25; 25)

What result do you expect for the following cases:
* (1; 10; 100) + (20) = ? (0; 0; 91; 20)? (1; 10; 80; 20)? (0.82; 8.2; 81.98; 20)?
* (1; 10; 100) + (200) = ?
* (1; 10; 100) + (-20) = ? (21; 10; 100; -20)? (1; 10; 120; -20)? (1.18; 11.8; 118.02; -20)?
* (1; 10; 100) + (-200) = ?

**Comment by TomNedry** [comment]
Interesting thoughts!

My use-case was the bill of my weekly shopping in the supermarket. Later i decide to split this total amount into groceries, magazines and clothing. In this case the initial amount has to be constant, and as @slodki said:

> you expect calculation like this: (50) + (25) = (50-25; 25) = (25; 25)

**Comment by vomikan** [comment]
Some scenario already introduced when new transation entering

![image](https://user-images.githubusercontent.com/6836805/58732498-602aef80-83fa-11e9-8e75-323f3c46a5d0.png)

![image](https://user-images.githubusercontent.com/6836805/58732517-720c9280-83fa-11e9-99dd-efd8d56337b6.png)

![image](https://user-images.githubusercontent.com/6836805/58732548-82bd0880-83fa-11e9-81ae-c6f211c2e608.png)

![image](https://user-images.githubusercontent.com/6836805/58732568-910b2480-83fa-11e9-9803-939566b5cfe9.png)

**Comment by TomNedry** [comment]
@vomikan : assuming that the initial amount can't be changed (= the bill was already paid and in my case the transaction line was imported via csv from the web-application of my bank)

1. one can change the initial amount by just adding another number than "30" in your example
2. the user has to calculate the remainder by hand, after adding some "split-values" smaller than the initial amount

I have to mention that i'm using a LibreOffice Calc sheet so far and i'm evaluating applications which are more "robust" and user friendly. GnuCash (too much), HomeBank (too simple) and Quicken (not open source) are handling split-transaction (see docs [Qicken](https://www.dummies.com/personal-finance/money-management-software/quicken/how-to-split-transactions-in-quicken-2015/), [GnuCash](https://lists.gnucash.org/docs/C/gnucash-guide/txns-registers-txntypes.html), [HomeBank](http://homebank.free.fr/help/index.html) ) more or less in that way i mentioned it...

MMEX would be a great choice, because of it's flexible reporting and overall easy to use. But i don't like to have a past transaction amount changed accidentally by a split operation and/or have to calculate the remainder by hand. This would be a real disadvantage!

**Comment by slodki** [comment]
You want to:
divide one existing split (selected from list) into two separate splits:
* original one with value adjusted
* new entered from scratch with any amount value

Restrictions:
* split selected to modify must already exist (to be selectable)
* you cannot adjust multiple splits at once

**Enhancement proposal**
* New "split this" icon will be added to each split displayed in Split Transaction Dialog
* It will open existing the same dialog as `Add` button
* After new split is created and added to list amount value of the original split item will be adjusted: new item value will be substraced

**Examples**
`*` marks existing item selected for modification:
(1; 10; 100*) + (20) = (1; 10; 80; 20)
(1; 10*; 100) + (20) = (1; -10; 20; 100)
(1*; 10; 100) + (20) = (-19; 20; 10; 100)
(1; 10; 100*) + (-20) = (1; 10; 120; -20)
(1; 10*; 100) + (-20) = (1; 30; -20; 100)
(1*; 10; 100) + (-20) = (21; -20; 10; 100)
