### ISSUE TITLE
Graphical issues in MacOS 10.14.5 Mojave Dark Mode

### ISSUE THREAD

**Issue by emistock** [moneymanagerex/moneymanagerex#2186]
**Describe the bug**
While using the latest version of MMEX alpha build on my Mac, I noticed graphical issues on the first startup screen where the graphics are pixelated when my system is in 'dark' mode. These graphical issues do not appear when the system is in 'light' mode. 

**To Reproduce**
1. Have dark mode on in system preferences 
2. Open program

**Expected behavior**
I would expect the graphics to be clear and not pixelated in both light and dark modes. 

**Screenshots**
Screenshot of program startup screen (with system in dark mode)
![Screen Shot 2019-05-26 at 3 08 12 PM](https://user-images.githubusercontent.com/27315187/58387008-c7e1d480-7fcd-11e9-85ca-d290dc5e206a.png)

Screenshot of program startup screen (with system in light mode)
![Screen Shot 2019-05-26 at 3 08 49 PM](https://user-images.githubusercontent.com/27315187/58387010-ce704c00-7fcd-11e9-9943-62176ebdb702.png)

**Additional context**
I am running the latest version of MacOS with the latest alpha release of MMEX. I have also tested this bug by downloading the program on a different computer running the latest MacOS version. The issue can be reproduced on my other computer as well. 

**Your OS:**
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
This image is semi-transparent and has many light gray pixels.
I think it should be removed.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/58749024-44baf580-8489-11e9-8514-ee0ef9149a7b.png)
