### ISSUE TITLE
Recurring Transaction 1st Working Day Of Month

### ISSUE THREAD

**Issue by pnsharp123** [moneymanagerex/moneymanagerex#2187]
Hi, is it possible to have recurring transcation for the 1st working day of the month, like it is possible to choose the last working day of month. So Monday to Friday.

**Comment by slodki** [comment]
What about a more general option for all existing repeat intervals:
* [ ] if it falls out over the weekend (Sa, Su):
  * skip the occurrence
  * change the date for the last Friday
  * change the date for next Monday

We can have more general option if we implement calendars with bank holidays for each country:
* [ ] if it falls out over the bank holidays:
  * skip the occurrence
  * change the date for the last working day
  * change the date for the next working day
