### ISSUE TITLE
Sale Stocks

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2206]
How to sale stocks?

![image](https://user-images.githubusercontent.com/6836805/59198278-02d23380-8b9c-11e9-86bd-21ab5ad92a67.png)
 I suggest to accept negative amount.

**Comment by stef145g** [comment]
Stock sales cannot be done on the stock creation page. Once you have created a stock and an associated stock account, the Add Share Transaction will allow the addition and deletion of stocks. Please refer to the help on Stocks and Shares

**Comment by vomikan** [comment]
https://youtu.be/UJr2M743p10
