### ISSUE TITLE
Transaction report filter category

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2209]
Initial start:
![image](https://user-images.githubusercontent.com/6836805/59205276-441e0f80-8bab-11e9-9466-309b30a8319c.png)
subsequent
![image](https://user-images.githubusercontent.com/6836805/59205320-5e57ed80-8bab-11e9-97db-251b96b5ed7e.png)

**Comment by slodki** [comment]
BTW: why the filter dialog is opened as not configured (no values selected) when a filter is already active? I would expect current filtering criteria displayed in such a scenario.

**Comment by vomikan** [comment]
@slodki don't understand.

**Comment by slodki** [comment]
1. Open account panel to see transactions
2. Click `Transaction Filter` button
3. Activate any criteria from dialog (i.e. type == deposit)
4. Click `Activate` button
5. Selected filter is active - transaction list is updated
6. Click `Transaction Filter` button again
7. **Empty** dialog is displayed - no current filter values are visible

Active criteria should be pre-filled in Transaction Filter dialog to easily modify them.
