### ISSUE TITLE
png::RIGHTARROW_ACTIVE differs little from png::RIGHTARROW

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#2218]
**Describe the bug**
it is very difficult to tell if the filter works

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3155552/59565677-a3ba6600-9056-11e9-8972-d7a4e51d9ab4.png) ![screenshot2](https://user-images.githubusercontent.com/3155552/59565679-a87f1a00-9056-11e9-974e-ced219f0f6de.png)

**Expected behavior**
The red circle should be thicker or the icon should clearly change color.

**MMEX version:**
- [x] development version (git master branch)

**Comment by vomikan** [comment]
https://openclipart.org/ is down as result of DDoS attack :(
