### ISSUE TITLE
Attachment Section

### ISSUE THREAD

**Issue by lalityshinde** [moneymanagerex/moneymanagerex#2224]
i am using this app for years.
I am in requirement for update in attachment.
i suggest to add "attachment" tab/button in each "New translation" section.
so we can add check photo,bill photo or pdf,any other screen shot related to that particular translation. 
Use of this:-
whenever we need we can pull out particular translation and can see detail about that transation

**Comment by vomikan** [comment]
The button for attachments already there:
![image](https://user-images.githubusercontent.com/6836805/63750986-3711e200-c8b7-11e9-9644-9b22c8a1e559.png)
As enhancement drug and drop technology may be added for "Organize Attachments" window.

**Comment by yaomtc** [comment]
Just need this feature added on the Android app: https://github.com/moneymanagerex/android-money-manager-ex/issues/11
