### ISSUE TITLE
CSV Import converting all decimals to 00

### ISSUE THREAD

**Issue by thucar** [moneymanagerex/moneymanagerex#2227]
**Describe the bug**
When importing my bank data using CSV, I've started losing all decimal values after upgrading to 1.4.0-alpha.7

**To Reproduce**
1. Go to 'Import->CSV Files'
2. Browse to a file with the following layout:
```
Date;Payee;Sum;Number;Note
2019-01-03;Some Payee;-7.62;1231212;Groceries
```
3. Set Decimal Char in Import dialog screen to: "."
4. Verify the currency for said account is using the same decimal symbol.
5. Specify fields
6. Verify you can see correct values in both, botton and Right side Preview windows.
7. Click Import
8. Go to Account and find a Withdrawal value of "7.00" instead of "7.62"

**Expected behavior**
The above record gets imported with Withdrawal value "7.62"

**Additional context**
I did not have such issues with the last stable version.

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Thank you for growing this. I'll check.

**Comment by vomikan** [comment]
7a3e15a3
