### ISSUE TITLE
Crash when modal window is opened while a recurring transaction is executed

### ISSUE THREAD

**Issue by peepall** [moneymanagerex/moneymanagerex#2228]
When I open MMEx and immediately create a new transaction manually, the application may crash entirely if a recurring transaction is being executed while the "New transaction" modal window is opened.

When it happens, I must reopen MMEx and then the recurring transaction is displayed, so I can create my new manual transaction again.

I am using MMEx v1.3.3 (DB v7) on Windows 7 x64 SP1.

**Comment by slodki** [comment]
#1816

**Comment by whalley** [comment]
No recent reports of this occurring, closing. If it is encountered again we can open case.
