### ISSUE TITLE
1.4.0-alpha.7, Account attachments fail to open

### ISSUE THREAD

**Issue by fhanzen** [moneymanagerex/moneymanagerex#2229]
Nothing at all happens when attachments associated with accounts are double-clicked. Attachments associated with transactions open as expected however.

**To Reproduce**
1. Right-click on an account and select 'Organize Attachments'.
2. Double-click an existing attachment.

**Expected behavior**
The attachment should open.

**Your OS:**
Linux

**MMEX version:**
Version: 1.4.0-alpha.7

**Comment by vomikan** [comment]
I can't reproduce this.

**Comment by fhanzen** [comment]
In v1.3.3, there are no spaces in the file name or directories associated with account attachments. This is not the case in v.1.4.0-alpha.7. An example filename as listed in the Organize Attachments dialog is, "Bank Account/Bank Account_1_Attach1.pdf". Also, when running mmex from the shell, double-clicking the attachment results in the following being displayed in the terminal:

xdg-open: unexpected argument 'Account/Bank'
Try 'xdg-open --help' for more information.

The spaces appear to be unintentional and are also not being escaped. In moneymanagerex/src/model/Model_Attachment.cpp, if I change the line:

{Model_Attachment::BANKACCOUNT, wxString(wxTRANSLATE("Bank Account"))},

to

{Model_Attachment::BANKACCOUNT, wxString(wxTRANSLATE("BankAccount"))},

then the account attachments open without issue.

Thanks!

**Comment by Fenrihr** [comment]
Same problem with `v.1.4.0-alpha.7-1` in Manjaro Gnome (Arch Linux).
