### ISSUE TITLE
filter clear

### ISSUE THREAD

**Issue by netuser2** [moneymanagerex/moneymanagerex#2233]
Can you add a "clear filter" button? Right now to clear a filter you have to click "transaction filter", "clear" and "ok". That's 3 clicks. If you had a button to clear the filter it would only be 1 click.

**Comment by vomikan** [comment]
Mouse right click?

**Comment by netuser2** [comment]
I did not know that there was a right click option. It's not intuitive. If there was another button just for clearing then it would be easily seen and known. 
The right click will work for me but I hope for a "clear button" by itself.

**Comment by vomikan** [comment]
Related issue: #2238
