### ISSUE TITLE
remember last filter

### ISSUE THREAD

**Issue by netuser2** [moneymanagerex/moneymanagerex#2234]
Can you allow the filter last used to be kept? At times I would like to add some more filters to what I just used or change one thing but I have to start over because it is not kept. 

Also can you display the filter used? This will help with short memory to remember what I just filtered for. It would be even better if the filter is part of the transactions screen so one can filter on the fly and see what filter is currently applied.

**Comment by vomikan** [comment]
What kind of filter?

**Comment by netuser2** [comment]
It does allow to save filters but you have to "save" them. I don't save every filter. If I just want to do a random filter at this moment and after applying it I want to add something else to it then it would have been gone. So remembering the last filter without saving would be good.

**Comment by netuser2** [comment]
This is what I mean by integrating the filter with the window itself.

![image](https://user-images.githubusercontent.com/53388009/62089464-16625800-b237-11e9-95fe-f973fca131a5.png)
