### ISSUE TITLE
make transaction filter and view all transactions buttons bigger

### ISSUE THREAD

**Issue by netuser2** [moneymanagerex/moneymanagerex#2238]
Can you make the buttons for these 2 options bigger? Or can the click field be expanded to include the words of the buttons? Having to drag the mouse to the small circle button is extra mouse dragging.

**Comment by netuser2** [comment]
Like this.

![image](https://user-images.githubusercontent.com/53388009/62090346-94742e00-b23a-11e9-8df5-baeed4ae53cf.png)

**Comment by vomikan** [comment]
What about anly one button?

![image](https://user-images.githubusercontent.com/6836805/62141862-f04fbd00-b2f5-11e9-91a7-a0a70be3f0fc.png)


![image](https://user-images.githubusercontent.com/6836805/62141893-01003300-b2f6-11e9-80b0-55f9e4b19aeb.png)

**Comment by netuser2** [comment]
That would work. Perhaps move the "advanced" option towards the top instead of the bottom?
