### ISSUE TITLE
downloading crypto rates

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/moneymanagerex#2240]
Sorry for the mixup.

I'm using MMEX from Github on Mac.
Since june 18th, when I click on the update rates I get the popup window to appear but rates are not updated. 
I compiled today's version which did not solve the problem. 

Thanks.

**Comment by vomikan** [comment]
I don't understand the issue.

**Comment by vomikan** [comment]
https://github.com/CoinCapDev/CoinCap.io
