### ISSUE TITLE
GUI elements in linux do not render well

### ISSUE THREAD

**Issue by Fenrihr** [moneymanagerex/moneymanagerex#2241]
**OS:**
- Linux: Manjaro (Arch)
- Kernel: 5.2.4-1
- Desktop Enviroment: Gnome and XFCE

**MMEX version:**
- 1.4.0-alpha.7

**Describe the bug**
The buttons and others gui elements do not render well:
![2019-08-04_17-11](https://user-images.githubusercontent.com/380335/62428725-0a651300-b6db-11e9-9c0e-dca7650d6349.png)

I have tested with different desktop themes, modifying the font sizes, changing the scaling factor, resizing the windows etc. but with little to none effect.
The image is the best result that i could make.

**Comment by vomikan** [comment]
Related issue #2158
