### ISSUE TITLE
Transfers between accounts not supported in CSV import

### ISSUE THREAD

**Issue by jaiminim** [moneymanagerex/moneymanagerex#2248]
Did we ever find out how to import a transfer?  I have a bank transfer to a savings account.  The savings account is an account on MMex.  How do I adjust the csv file to import so that mmex records it as a transfer?

**Comment by slodki** [comment]
```mmUnivCSVDialog::parseToken()``` is responsible for imported transaction details. Transfers between MMEX accounts are not supported.

https://github.com/moneymanagerex/moneymanagerex/blob/c2859a7e745b3691b015aca18518d62e911b5828/src/import_export/univcsvdialog.cpp#L1491

**Comment by slodki** [comment]
#343
