### ISSUE TITLE
Categories and Subcategories tree

### ISSUE THREAD

**Issue by leoghepy** [moneymanagerex/moneymanagerex#2251]
Good day to you. I wanted to know if you foresee the possibility of implementing the following functionality.
That is, to be able to print the configuration of Categories and Sub-Categories created by the user using your program

**Comment by vomikan** [comment]
Tools - General Report Manager
![image](https://user-images.githubusercontent.com/6836805/63343047-b7839080-c355-11e9-95b1-b5e2dbb27f0a.png)
New empty report... name....

![image](https://user-images.githubusercontent.com/6836805/63343136-ebf74c80-c355-11e9-921b-430848496064.png

Save - Test - Create template - Run
```
select * from (
select CATEGID, -1 as SUBCATEGID, CATEGNAME from CATEGORY
union all
select s.CATEGID, s.SUBCATEGID, c.CATEGNAME||':'||s.SUBCATEGNAME from SUBCATEGORY s
inner join CATEGORY c on c.CATEGID=s.CATEGID
) t
order by 3

```
