### ISSUE TITLE
Close financial year / month

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#2257]
(financial) Years and/or month can be close.
So there is no possibility to make bookings in closed period.

**Comment by TomAff** [comment]
I just want to block the periods for postings not delelete old ones.

**Comment by vomikan** [comment]
It looks like this is a poorly implemented feature. You can prevent entering transactions at the account level.

![image](https://user-images.githubusercontent.com/6836805/103132864-06fb6e80-46b8-11eb-9d61-01c0676bd174.png)

![image](https://user-images.githubusercontent.com/6836805/103132862-fc40d980-46b7-11eb-9d02-19254f0a305c.png)
But import and others functions may be ignore this settings

**Comment by TomAff** [comment]
Great. It works. But wouldn't it be better to block the transaction, that you do not have the chance to continue.
Locked is locked.

**Comment by TomAff** [comment]
Status can still be changed be keybord (F, R, V, U). Can this be locked too?

**Comment by vomikan** [comment]
I will fix this in the next release.
