### ISSUE TITLE
Closed Files have disappeared and I can't see a way to see them (e.g. to re-open them)

### ISSUE THREAD

**Issue by DavidE2910** [moneymanagerex/moneymanagerex#2258]
Using MMEX V 1.3.3 DB v7, I've suddenly noticed that the closed accounts have disappeared from the account list, which is fine since it unclutters it, but I can't find a way to see all the closed files (so that I can re-open if necessary or review what happened in them)

**Comment by vomikan** [comment]
1
![image](https://user-images.githubusercontent.com/6836805/64433402-0dcb3000-d0c7-11e9-8ef4-c263da2a2cc6.png)
2
![image](https://user-images.githubusercontent.com/6836805/64433459-25a2b400-d0c7-11e9-837d-7aa2a270f27c.png)

**Comment by DavidE2910** [comment]
Many thanks, I missed that option.
David
