### ISSUE TITLE
Use Morningstar to update the stocks

### ISSUE THREAD

**Issue by fra87** [moneymanagerex/moneymanagerex#2259]
Hello

I already asked the question some time ago on the forum (link [here](https://forum.moneymanagerex.org/viewtopic.php?f=23&t=7021)), but since it was quite old and maybe it is tracked better here, I'll post it her.

I need to update the stocks from the website morningstar, since yahoo doesn't have it. I noticed that the android app can update it from that website, but from the app I can't download the history. Is there a way to integrate it in the desktop app and make it available to download the history? 

I could track the search link up to quotes.morningstar.com/stockq/c-header?&t=put_here_the_stock_code, but then

1. it appears that the app does not have the parser and
2. I don't know the way to specify the date

Do you have any idea on how to specify it, or think it is possible to implement it (maybe using also the android app implementation)?

Best regards

**Comment by vomikan** [comment]
yahoo doesn't have what?

**Comment by vomikan** [comment]
Currently mmex use yahoo
For example for IBM share we can request the following data:
https://query1.finance.yahoo.com/v7/finance/quote?symbols=IBM&fields=regularMarketPrice,currency,shortName
```
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "quoteSourceName": "Nasdaq Real Time Price",
        "currency": "USD",
        "market": "us_market",
        "regularMarketPrice": 135.69,
        "regularMarketTime": 1567608765,
        "shortName": "International Business Machines",
        "sourceInterval": 15,
        "exchangeTimezoneName": "America/New_York",
        "exchangeTimezoneShortName": "EDT",
        "gmtOffSetMilliseconds": -14400000,
        "exchangeDataDelayedBy": 0,
        "exchange": "NYQ",
        "marketState": "REGULAR",
        "esgPopulated": false,
        "tradeable": true,
        "triggerable": true,
        "fullExchangeName": "NYSE",
        "priceHint": 2,
        "symbol": "IBM"
      }
    ],
    "error": null
  }
}
```

**Comment by fra87** [comment]
@vomikan In fact what I'm following are some funds. For instance the one with ISIN LU0243957239.
Morningstar tracks it, while yahoo doesn't; with the MMEX app for android I can automatically update it from the app. I was able to get some data in page [http://quotes.morningstar.com/stockq/c-header?&t=LU0243957239](http://quotes.morningstar.com/stockq/c-header?&t=LU0243957239) but I do not know how to go on from this.

**Comment by lonemadmax** [comment]
FWIW, I wrote a python script years ago to get some historic data for funds from Morningstar:
```python
#!/usr/bin/env python3

import sys
import time
import requests

if len(sys.argv) != 5:
    raise SyntaxError(sys.argv[0] + ' ISIN market fromDate toDate')

items = [(i[1], i[4]) for i in [l.split('|') for l in requests.get('http://tools.morningstar.es/es/util/searchfundbyname.aspx?ModuleId=69&LanguageId=es-ES&limit=100&q=' + sys.argv[1].lower()).text.split('\n')] if len(i) > 5 and (i[4] == '' or i[4] == sys.argv[2])]
code = items[0][0]
for i in items:
    if i[1] == sys.argv[2]:
        code = i[0]
        break

data = requests.get('http://tools.morningstar.es/api/rest.svc/timeseries_price/2nhcdckzon?id=' + code + '&currencyId=EUR&idtype=Morningstar&priceType=&frequency=daily&startDate=' + sys.argv[3] + '&endDate=' + sys.argv[4] + '&outputType=COMPACTJSON').json()
for i in data:
    print(time.strftime("%Y-%m-%d", time.gmtime(i[0] / 1000)), i[1])
```

No guarantees and etc, but it seems to still work, or at least get some data:
```
$ ./hist-morningstar.py LU0243957239 BATS 2019-09-01 2019-09-20
2019-09-02 22.33
2019-09-03 22.31
2019-09-04 22.34
2019-09-05 22.4
2019-09-06 22.41
2019-09-09 22.44
2019-09-10 22.44
2019-09-11 22.46
2019-09-12 22.45
2019-09-13 22.52
2019-09-16 22.52
2019-09-17 22.5
2019-09-18 22.5
2019-09-19 22.51
2019-09-20 22.56
```

**Comment by vomikan** [comment]
hist-morningstar.py HSBA LSE 2020-04-09 2020-04-14                                                                                                           [[1586390400000, 4.888], [1586476800000, 4.888], [1586736000000, 4.919]]

**Comment by vomikan** [comment]
https://gist.github.com/jimmysitu/161d2effc0d3b17e401fdafa6e5b615d

**Comment by vomikan** [comment]
Another idea is use some function like googlespreads:
`=IMPORTxml("https://iss.moex.com/iss/engines/stock/markets/bonds/boards/TQOB/securities.xml?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVADMITTEDQUOTE", concatenate("//row[@SECID='",A11,"']/@PREVADMITTEDQUOTE"))
`
`=googlefinance("MSFT")`

**Comment by vomikan** [comment]
https://www.quantshare.com/sa-43-10-ways-to-download-historical-stock-quotes-data-for-free

**Comment by vomikan** [comment]
http://tools.morningstar.es/es/util/searchfundbyname.aspx?ModuleId=69&LanguageId=es-ES&limit=100&q=AAPL
```
Apple Inc|0P000000GY]3]0]E0WWE$$ALL|STOCK|AAPL|NASDAQ|
Apple Inc|0P0001KOM0]3]0]E0WWE$$ALL|STOCK|AAPL|BVL|
Apple Inc|0P0001367D]3]0]E0WWE$$ALL|STOCK|AAPL|XSGO|
Apple Inc|0P0000EEPX]3]0]E0WWE$$ALL|STOCK|AAPL|WBAG|
Apple Inc|0P0001ISID]3]0]E0WWE$$ALL|STOCK|AAPL|PFTS|
```

http://tools.morningstar.es/api/rest.svc/timeseries_price/2nhcdckzon?id=**0P000000GY]3]0]E0WWE$$ALL**&currencyId=**USD**&idtype=Morningstar&priceType=&frequency=daily&startDate=**2020-10-09**&endDate=**2020-10-13**&outputType=COMPACTJSON

```
[[1602201600000, 116.970],[1602460800000, 124.400]]
```

**Comment by vomikan** [comment]
http://tools.morningstar.es/es/util/searchfundbyname.aspx?ModuleId=69&LanguageId=es-ES&limit=100&q=lu0243957239
```
Invesco Funds - Invesco Pan European High Income Fund A Accumulation EUR|F0GBR06T9L]2]0]FOESP$$ALL|FUND|||
```

http://tools.morningstar.es/api/rest.svc/timeseries_price/2nhcdckzon?id=F0GBR06T9L]2]0]FOESP$$ALL&currencyId=EUR&idtype=Morningstar&priceType=&frequency=daily&startDate=2020-10-09&endDate=2020-10-13&outputType=COMPACTJSON
```
[[1602201600000, 22.590],[1602460800000, 22.640]]
```

**Comment by vomikan** [comment]
To get last price of the 'LU0243957239' fund  suggest to create a function to parse html code.
Related issue: #2702 

=IMPORThtml("http://quotes.morningstar.com/stockq/c-header?&t=LU0243957239", "//div[@id='last-price-value']")

![image](https://user-images.githubusercontent.com/6836805/96110094-1441f300-0ee8-11eb-8913-f322ad6275bc.png)

https://support.google.com/docs/answer/3093339?hl=en

**Comment by vomikan** [comment]
http://quotes.morningstar.com/stockq/c-header?&t=AMZN
```
<div  id="last-price-value" vkey="LastPrice">\s*([0-9,.]+)\s*<\/div>
```
![image](https://user-images.githubusercontent.com/6836805/96460456-e3392980-122b-11eb-8329-4d0f04235fc8.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/99964670-b933d380-2da4-11eb-8af3-918be45dd809.png)

**Comment by vomikan** [comment]
> What is this api? are there any docs? how can I get historical financial statements with that url?

There is a special section for questions. It is not necessary to write in a long-closed case.

https://github.com/moneymanagerex/moneymanagerex/discussions
