### ISSUE TITLE
Can't move the application window on iMac

### ISSUE THREAD

**Issue by Asimov940** [moneymanagerex/moneymanagerex#2260]
The MMEX application has lost its top line. Not sure what it's called, it's the one that let's you minimize, maximize or close the window. More importantly, I can't move the application window to a second screen or anywhere else without it. Don't know how it happened, the app simply started up one day as usual, with no way of moving the window from directly underneath the menu bar.
<img width="518" alt="Screenshot 2019-09-04 at 11 04 41" src="https://user-images.githubusercontent.com/54890259/64246231-571f5200-cf04-11e9-91a2-df31f1414aac.png">

**Comment by vomikan** [comment]
try to find and move mmexini.db3 file.

**Comment by Asimov940** [comment]
That did it.

Thank you so much.

Jeff.
