### ISSUE TITLE
Tagging transactions

### ISSUE THREAD

**Issue by simohub** [moneymanagerex/moneymanagerex#2261]
It would be great to be able to apply tags to transactions in order to group them across the categories. For example group all the expenses of a holiday (of different categories) with the same label (petrol, shopping, restaurants, etc...)

**Comment by slodki** [comment]
#490 #1474

**Comment by simohub** [comment]
Ok but I don't find how to enable custom fields on Adroid version. Which menù/button/section I have to use? Thanx

**Comment by simohub** [comment]
I have latest from Goggle Play Store 2019.02.19.995

**Comment by slodki** [comment]
MMEX for Desktop and MMEX for Android are different apps (like Microsoft Office 365 and LibreOffice) sharing the same file format. Please use [Android issues](https://github.com/moneymanagerex/android-money-manager-ex/issues) to ask questions about Android app.

**Comment by slodki** [comment]
moneymanagerex/android-money-manager-ex#1147

**Comment by luisdev** [comment]
Related: https://github.com/moneymanagerex/moneymanagerex/issues/1477
