### ISSUE TITLE
MMEX 1.3.3 x64 crashes when opening on Windows

### ISSUE THREAD

**Issue by Sven1975** [moneymanagerex/moneymanagerex#2263]
Hi,
When opening MMEX, the application crashes immediately on Windows 10 Enterprise.
I'm running MMEX 1.3.3 x64 version on Portable. I have reinstalled the sofware but the issue remains. Same issue with non-portable version which I have installed as well.

You cannot select to open the database. After starting it takes a few moments before the message appears 'Money Management Software has stopped working'. 

Sven

**Comment by vomikan** [comment]
Try to run portable 1.4.0. Switch off network features. Then copy mmexini.db3 file to 1.3.0 folder.
https://github.com/moneymanagerex/moneymanagerex/releases/tag/nightly

**Comment by Sven1975** [comment]
Hi, 

I have tried as you have told me but no success. The 1.4 version does not start. I copied the file to 1.3 folder, but that doesn't solve either.

Sven

**Comment by vomikan** [comment]
Please upgrade
