### ISSUE TITLE
Change category alongside payee modify

### ISSUE THREAD

**Issue by mwessley** [moneymanagerex/moneymanagerex#2264]
After CSV import I have to modify some Payees, sadly the Category does not change automatically alongside

When I change the payee it would be nice if the Category automatically changes to the one the selected Payee is located in.

**Comment by vomikan** [comment]
This option is working only for new transactions.

![image](https://user-images.githubusercontent.com/6836805/79144522-c8db4a80-7dc7-11ea-9cad-6c97f94871f2.png)

**Comment by whalley** [comment]
It works fine for transaction edits also. I can't reproduce this issue.
