### ISSUE TITLE
API-ms-win-crt-runtime-L1-1-0.dll

### ISSUE THREAD

**Issue by sammyy777** [moneymanagerex/moneymanagerex#2265]
>API-ms-win-crt-runtime-L1-1-0.dll

hELLO,

Can anyone help me with the above error.

I had to reinstall after clearing my hard drive, but now it downloads but will not run.

Hope someone can help me fix as have been using for over 2 years without any issues.

Many thanks...........sammy

**Comment by vomikan** [comment]
https://www.threesl.com/blog/fixi-api-ms-win-crt-runtime-l1-1-0-dll-missing-error-install/
it's possible solution.
