### ISSUE TITLE
Langage des fenêtres 

### ISSUE THREAD

**Issue by Leterrier** [moneymanagerex/moneymanagerex#2266]
j'ai téléchargé la dernière version v1.3.3 et à l'usage je constate que les fenêtres sont moité en français (langage choisi par défaut) moitié en anglais. Par ailleurs la police est trouble à l'affichage écran, ce qui n'était pas le cas en v1.0.0.3.
J'ai téléchargé la version 64 bits
![capture money manager 1 3 3](https://user-images.githubusercontent.com/56188291/66252261-933f1000-e759-11e9-8d26-d79f460f40d4.png)

**Comment by slodki** [comment]
English is used as a fallback if a specific GUI item translation is not completed.
MMEX 1.4.0 has a better French support then not updated 1.3.3. You can improveFrench translation yourself without any programming skills using [Crowdin](https://crowdin.com/project/moneymanagerex/fr#)
