### ISSUE TITLE
Crashes when filtering date

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#2270]
Crashes when using date-Filter on Advance Filter

**Comment by vomikan** [comment]
how to reproduce?

**Comment by TomAff** [comment]
Sorry, there was an issue in my database. After optimizing it works.

**Comment by TomAff** [comment]
I get this problem again with one database.
Other databases do work. Optimizing takes no effekt.
Do I have the chance to find the issue?
![2019-11-15 17_59_10-Buchungsfilter](https://user-images.githubusercontent.com/46572503/68961241-3875eb00-07d2-11ea-9fcf-770520e56191.jpg)
![2019-11-15 17_59_33-Debug report _MoneyManagerEx_](https://user-images.githubusercontent.com/46572503/68961249-3dd33580-07d2-11ea-8a1e-b838a2e5e1d2.jpg)

**Comment by vomikan** [comment]
Seems that bug already has fixed.
Try to redefine both dates before report activation. The bug should gone.

**Comment by TomAff** [comment]
Now it works. Thanks a lot.
