### ISSUE TITLE
Decimal number not taken into account

### ISSUE THREAD

**Issue by micheloz** [moneymanagerex/moneymanagerex#2275]
When using a currency (that is not the main one), decimals are not taking into account.
For example :
- the main currency of accounts is Euro (=1)
- other currency used is AUD (=1,62).
- in account using AUD, when enter decimal Numbers (e.g. 1,7),  
=> it remains only an integer part (e.g 2)

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [x] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
@micheloz Could you post MMEX version you are using (1.3.3, 1.4.0 etc)?

**Comment by micheloz** [comment]
I am using win version 1.3.3, decimal are not taking into account on accounts not using the main currency.
On android (ver 2019.02.19.995) the symptoms are the same

**Comment by vomikan** [comment]
Please change currencies format. You can make it the same and match of the OS settings.

![image](https://user-images.githubusercontent.com/6836805/68183377-56ab4200-ffad-11e9-8fea-b0da5070c189.png)

**Comment by micheloz** [comment]
OK, in fact in my session, the scale was left blank. By introducing "2" it works very well.
Thank you for your help
Have a nice day
