### ISSUE TITLE
Migrating from Mac to Fedora (v1.4)

### ISSUE THREAD

**Issue by sebw** [moneymanagerex/moneymanagerex#2276]
I'm moving away from Mac to Fedora.

I was using MMEX 1.4 beta on Mac.

When trying to open the datase under Fedora Linux 30 (mmex installed from RPM found here in the releases section), I get:

```
mmex: relocation error: mmex: symbol _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE5eraseEmm version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference
```

Those wx packages are installed:

```
wxBase3-3.0.4-8.fc30.x86_64
wxGTK3-i18n-3.0.4-8.fc30.noarch
wxGTK3-webview-3.0.4-8.fc30.x86_64
wxGTK3-3.0.4-8.fc30.x86_64
```

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by slodki** [comment]
Package was build using following packages:
```
wxBase3-3.0.4-8.fc30.x86_64
wxBase3-devel-3.0.4-8.fc30.x86_64
wxGTK3-3.0.4-8.fc30.x86_64
wxGTK3-gl-3.0.4-8.fc30.x86_64
wxGTK3-i18n-3.0.4-8.fc30.noarch
wxGTK3-media-3.0.4-8.fc30.x86_64
wxGTK3-webview-3.0.4-8.fc30.x86_64 
```

`cxx`, `basic_string` and `char_traits` suggests there is some problem with wxGTK and stdc++ library...

**Comment by sebw** [comment]
I installed the packages above but still getting the same problem.

I decided to try to create a new database but at the end of the wizard I get this:

```
(mmex:20831): Gtk-CRITICAL **: 11:50:17.463: gtk_tree_row_reference_new_proxy: assertion 'path->depth > 0' failed
mmex: relocation error: mmex: symbol _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE5eraseEmm version WXU_3.0 not defined in file libwx_gtk3u_core-3.0.so.0 with link time reference
```

**Comment by vomikan** [comment]
Most improvement memx is v1.3.5-beta.7. Will be released soon.
Db should be downgraded
https://github.com/moneymanagerex/moneymanagerex/issues/2353
