### ISSUE TITLE
MMEx - Nightly Build for Mac - is broken -Mac says send it to bin! (running Catalina)

### ISSUE THREAD

**Issue by KarenJohns** [moneymanagerex/moneymanagerex#2277]

**Comment by xraynaud** [comment]
I can confirm it is still the case. Launching the program says 'application is broken'. The program works when compiled from source.

**Comment by slodki** [comment]
The problem works without problems when started from Terminal app.
This can be broken by:
- upgrade to macOS 10.14 Mojave
- or building with latest Xcode 11.x
