### ISSUE TITLE
Double multiplication by currency rate in Transaction Report

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#2281]
**Describe the bug**
Transactions in currencies with non 1 conversion rate are multiplied twice in Transaction Report resulting in incorrect Total

**To Reproduce**
1. Create an account with currency with Rate 1 e.g. PLN
2. Create an account with currency with rate e.g. 4 e.g. EUR
<img width="434" alt="Screenshot 2019-11-08 at 11 33 22" src="https://user-images.githubusercontent.com/2995498/68470664-cc691500-021c-11ea-8aad-522409221903.png">
3. Record a transaction for 100 PLN in the PLN account
<img width="1182" alt="Screenshot 2019-11-08 at 11 33 46" src="https://user-images.githubusercontent.com/2995498/68470727-f1f61e80-021c-11ea-8757-c7a3dcece78b.png">
4. Record a transaction for 100EUR in the EUR account
<img width="1140" alt="Screenshot 2019-11-08 at 11 33 55" src="https://user-images.githubusercontent.com/2995498/68470752-00dcd100-021d-11ea-9a35-ed22a0248c47.png">
5. Go to Transaction Report (without specifying any specific filters)
<img width="1452" alt="Screenshot 2019-11-08 at 11 34 30" src="https://user-images.githubusercontent.com/2995498/68470842-2c5fbb80-021d-11ea-828a-f0527f11cd0d.png">
6. Observe that the 100 EUR transaction is already multiplied on the list and appears as 400EUR
and that it is once more multiplied when calculating the Total, resulting in 1700 instead of 500

**Expected behavior**
I assume correctly the 100EUR transaction should appear as 100EUR on the list an The total should be 500

**Your OS:**
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Related issue #1732

![image](https://user-images.githubusercontent.com/6836805/68528928-f77d6280-0309-11ea-8970-d7c5b8d65d9d.png)
