### ISSUE TITLE
Anyway To Get Reports For "Current Week"?

### ISSUE THREAD

**Issue by matthall1998** [moneymanagerex/moneymanagerex#2284]
All I need is for the "Where the Money Goes" to have a drop down selection for Current Week. Anyway I can make that happen? Thank you!

**Comment by vomikan** [comment]
This report may be transformed to weekly report
https://github.com/moneymanagerex/general-reports/tree/master/CategoriesStatLast12Months

**Comment by vomikan** [comment]
[weekly.zip](https://github.com/moneymanagerex/moneymanagerex/files/3855660/weekly.zip)

**Comment by vomikan** [comment]
@matthall1998 in case if mmex 1.4.0 used you can import the report above into GRM.
