### ISSUE TITLE
Split Categories

### ISSUE THREAD

**Issue by MartinRPotter** [moneymanagerex/moneymanagerex#2287]
I'm running Windows 10 with the November update
Latest version of MMEX as below:

MMEX is using the following support products:
wxWidgets 3.1.0
SQLite3 3.14.1
wxSQLite3 3.4.0
Mongoose 6.5
Lua 5.2
Microsoft Visual Studio 1900

Problem
All my entries with spit categories have lost their "Split" detail and are only showing a single category with the total value

**Comment by vomikan** [comment]
In this case, only recovery from backup is possible.
![image](https://user-images.githubusercontent.com/6836805/78459646-2cc48b80-76c3-11ea-9a26-8d6ba8c1e49c.png)
If this option is on, in the same folder where used DB placed more files with suffix  _update_20XX-XX-XX.mmb would be present.
