### ISSUE TITLE
Advanced Filter Notes Comments

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#2295]
**Describe the bug**
Searching for notes/comments in the advanced filter wants the exact text to match any result in the newest nightly.
In the newest alpha (7) it was fine to just write "PayPal" and to find any entries with the word PayPal in its text field.

**To Reproduce**
1. Go to 'Advanced filter'
2. Write a Term in 'Notes'
1. Getting no results until you write the entire text of an existing entry in the search field

**Expected behavior**
I want to find any entry containing the specific search term.

**Additional context**

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [X] development version (6a9d4119 (2019-12-12))

**Comment by vomikan** [comment]
Write
```*PayPal*```
to find any entries with the word PayPal.

**Comment by MartinX3** [comment]
Thank you!
Did I oversee see documentation which special characters are now used for the search function?

**Comment by vomikan** [comment]
@MartinX3 could you write 1-2 sentence regarding this issue then I'll add it to the help pages.

**Comment by MartinX3** [comment]
@vomikan Which kind of explanation do you need?
That the mmex documentation about regex (?) placeholders in the advanced filter is missing?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/mmex.doc
