### ISSUE TITLE
Incorrect balance calculation

### ISSUE THREAD

**Issue by WcRnm** [moneymanagerex/moneymanagerex#2296]
**Describe the bug**
The calculated balance is incorrect in one of my credit card accounts. See attached screenshot.

This type of error makes the application completely untrustworthy :(

**To Reproduce**
Unknown.

**Expected behavior**
The calculated balance should correct

**Screenshots**
![mmex-bug](https://user-images.githubusercontent.com/3332121/71774658-d4e18180-2f27-11ea-8bcc-c13077735504.jpg)

**Additional context**

**Your OS:**
- [X] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [X] 1.3.3
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
I can't reproduce this issue.
Please be sure that transaction filter in "Show all transactions" state.

![image](https://user-images.githubusercontent.com/6836805/89122046-d75f8600-d4cc-11ea-9f67-ce8e6834b5da.png)
