### ISSUE TITLE
Duplicate transfer transaction and "Advanced" option

### ISSUE THREAD

**Issue by sebw** [moneymanagerex/moneymanagerex#2297]
**Describe the bug**
When duplicating a **transfer** transactions, I never tick the "Advanced" box (which I'm not even sure what it is doing). I change the amount (let's say from 20 to 10) and date and save the transactions.

If I edit the transaction again, the Advanced box is ticked with the new amount on the left field and old amount on the right field.

I'm expecting the transaction to not have the Advanced box ticked. Would that be a bug, or a feature?

Two other people mention this occurence here:

https://forum.moneymanagerex.org/viewtopic.php?f=24&t=6429

**To Reproduce**
Duplicated a transfer transaction
Change date
Change amount
Save
Edit again 
Advanced box is ticked

**Expected behavior**
I expect the advanced option not ticked.

**Screenshots**
None

**Additional context**
None

**Your OS:**
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
Hello. Sorry for delay.
The Advanced check box used to change the amount comes to account B (from account A).
In case if both accounts has the same currency do not use the second field.
