### ISSUE TITLE
virustotal report 3 engines detected this file - mmex-1.4.0-alpha.7-win64

### ISSUE THREAD

**Issue by ivanrojasorg** [moneymanagerex/moneymanagerex#2299]
**Describe the bug**
virustotal report 3 engines detected this file - mmex-1.4.0-alpha.7-win64

**To Reproduce**
1. Go to https://www.virustotal.com/gui/file/a4bef80251eff7ce1f7a62d857a45bb2b072d810c0d8e7315e7dcd3bb9f7dfb6/detection
2. See alert of VirusTotal

**Expected behavior**
The correct info is "No engines detected this file "
Like this in mmex_1.3.3_x64_setup.exe
https://www.virustotal.com/gui/file/645d945efebc8f61e5e3d6e3befa64265b6af3042e170d27c5c4dc5dfd347fe4/detection

**Screenshots**
![imagen](https://user-images.githubusercontent.com/17376191/71788637-e3509b80-3002-11ea-9261-66b7984df921.png)

**Additional context**

**Your OS:**
- [X ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ X] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
#2355 related issue
