### ISSUE TITLE
Synchronise not working on SM-A520F, Android 8.0.0 (Oreo), Samsung A5

### ISSUE THREAD

**Issue by OverdueFashion** [moneymanagerex/moneymanagerex#2304]
I have created a database and populated it with 1 expense. 

When I click on  Synchronise I get the following error message "_Invalid remote Uri. Please re-open the database_" --> Re-opening the database does not fix the issue. 

I also do find any setting relating to DropBox or other cloud services to link to.

**Comment by donatusjustin** [comment]
In your DropBox app, create a folder APPS (if it is missing), enter into APPS folder and create another folder MONEYMANAGEREX MOBILE, upload a working MMB file to this folder. Now, run Money Manager Ex app and open your working MMB database from DropBox. I hope this helps. You might encounter errors.
