### ISSUE TITLE
Nightly binary build missing dll-files

### ISSUE THREAD

**Issue by Noiden** [moneymanagerex/moneymanagerex#2305]
**Describe the bug**
After unzip of the nightly portable build I try to start mmex.exe but get the following errors,

missing this dll files,

- libcurl.dll
- lua.dll
- libcrypto-1_1-x64.dll
- libssl-1_1-x64.dll

**To Reproduce**
1. Start mmex.exe
2. Errors comes up

**Expected behavior**
The program would start and not complain about missing dll files.

**Your OS:**
- [X] Windows 10 64 bit

**MMEX version:**
- [X] 1.4.x nightly
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by salvoravida** [comment]
fixed
