### ISSUE TITLE
Changes lost when closing MMEX

### ISSUE THREAD

**Issue by thucar** [moneymanagerex/moneymanagerex#2306]
**Describe the bug**
Yesterday I decided to fully commit and get the full year of 2019 of my finances into MMEX. I imported last years transactions from 2 different bank accounts and two shares accounts. I got through categorizing all my transactions and adding most of my stock transactions. Everything looked great last night.
This morning I opened up MMEX to finish adding stock transactions, only to find that everything I did yesterday is gone. The account I had added is not there, and another account that I had deleted, is back again.
I see an update file from last night (mmex.mmb_update_2020-01-09), timestamped for when I closed MMEX. Is there any hope I could get my changes back from that file?

**Your OS:**
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by siowena** [comment]
If you copy mmex.mmb_update_2020-01-09 and rename it to something meaningful and then open it via the File menu and see if the transactions are in this file.

Rename it so anything, but keep the extension '.mmb'

**Comment by vomikan** [comment]
Please check if you use the same file when mmex start.
