### ISSUE TITLE
Notes on Budget lines

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#2307]
Feature Request / Enhancement

Add the ability to make notes against budget category/subcategory items for the Year and Monthly budgets.

I'd like to record notes as to why I set the budget to X and also why I may change the budget from X -> Y

**Comment by vomikan** [comment]
Frst of all it should be added text column the same way as here:
https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_8.sql

**Comment by vomikan** [comment]
Now I am actively develop the v1.3.4 branch. Main idea to freeze any DB structure changes to get maximum stability and compatibility.
Unfortunately, this helpfull feature can't be realized in nearest future.

**Comment by siowena** [comment]
No worries. It's appreciated the efforts you guys are going to.
If my coding was a little better I'd give it a go, but I'm definitely in the category of "a little knowledge is dangerous"

**Comment by whalley** [comment]
Added, see https://github.com/moneymanagerex/moneymanagerex/issues/4099
