### ISSUE TITLE
download latest build?

### ISSUE THREAD

**Issue by salvoravida** [moneymanagerex/moneymanagerex#2314]
where can i download latest build?

**Comment by siowena** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases

**Comment by salvoravida** [comment]
Great! I need nightly build not years old ones!

**Comment by siowena** [comment]
Apologies, the nightly is usually at the top, though it seems something is broken.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/tags

**Comment by salvoravida** [comment]
> https://github.com/moneymanagerex/moneymanagerex/tags

i'm talking about builds!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-d7b511138238f5f01447

**Comment by salvoravida** [comment]
> https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-d7b511138238f5f01447

404 not found.

**Comment by skizz98** [comment]
> 
> 
> > https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-d7b511138238f5f01447
> 
> 404 not found.

https://github.com/moneymanagerex/moneymanagerex/releases/tag/nightly

**Comment by salvoravida** [comment]
night build windows are corrupted
https://github.com/moneymanagerex/moneymanagerex/issues/2305
https://github.com/moneymanagerex/moneymanagerex/issues/2293

:(

**Comment by vomikan** [comment]
Possible fixed by last commit.

**Comment by vomikan** [comment]
#2305
