### ISSUE TITLE
Relocate Payee shortcut crashes the application when selected

### ISSUE THREAD

**Issue by didikrm** [moneymanagerex/moneymanagerex#2315]
**Describe the bug**
The application crashes when trying to relocate payee from the 'Organize Payees' dialog box.

**To Reproduce**
Tools -> Organize Payees -> Relocate Payee (either from the payee list directly or from the sub-menu).

**Expected Bahvior**
Move payees of a particular name to an alternate name. 

**Workaround**
Tools -> Relocation of...-> Payees

<hr><small><b>Version</b>: 1.4.0-alpha.7 • db 13 (aes128cbc) • git ab83908e (2019-01-06)<br><b>Libs</b>: wxWidgets 3.1.2 (wxMSW 10.0) • wxSQLite3 4.4.0 (SQLite 3.26.0) • Mongoose 6.13 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.62.0-DEV • WinSSL<br><b>Build</b>: Jan 7 2019 23:18:12 • CMake 3.12.2 • MSBuild 15.9.21.664 • gettext 0.19.8.1 • Microsoft Visual Studio 15.0 • Microsoft Visual C   19.16.27025.1 • Windows SDK 10.0.14393.0<br><b>OS</b>: Windows 10 (build 18362), 64-bit edition • English (windows-1252) • 1920x1080 32bit 120x120ppi</small>

**Comment by vomikan** [comment]
I can't reproduce this issue.
Please downgrade to v1.3.4

https://sourceforge.net/projects/moneymanagerex/files/v1.3.4-rc.3/

https://github.com/moneymanagerex/moneymanagerex/issues/2353
