### ISSUE TITLE
XML Parsing error and Unable to check for updates

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#2326]
On opening the program I get the attached error 'XML parsing error. 'mismatched tag' at line 6'.
and when checking for updates I get 'Unable to check for updates!' followed by code.
See attached files
![MMEX Error](https://user-images.githubusercontent.com/39367770/75157271-b0c24580-570b-11ea-9ba8-f4478b54cc24.jpg)
![MMEX Error (2)](https://user-images.githubusercontent.com/39367770/75157285-b4ee6300-570b-11ea-8a2b-50756ff0c7b0.jpg)

**Comment by vomikan** [comment]
#1083

**Comment by vomikan** [comment]
I recommend to download last v1.3.4-beta1. It has the same DB structure and a lot of fixes.
Try a portable release. Copy you db file and open the copy.
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/history
![image](https://user-images.githubusercontent.com/6836805/75157904-1b807a80-5726-11ea-84a3-11504543be6a.png)
