### ISSUE TITLE
MMEX database error

### ISSUE THREAD

**Issue by Teezton** [moneymanagerex/moneymanagerex#2327]
Ok, I did a mistake, I tested the mmex-1.4.0-alpha.7-win64 with my real database, and now I can't open it on the Desktop stable release mmex_1.3.3_x64:

![Image 001](https://user-images.githubusercontent.com/5905860/75318481-656e7b00-5862-11ea-865d-eb6472becb03.png)

Anyway to revert this situation?

**Comment by vomikan** [comment]
In case if a backup option is switched on it should be a backup file in the same folder where is a DB file placed.

**Comment by Teezton** [comment]
> In case if a backup option is switched on it should be a backup file in the same folder where is a DB file placed.

You mean these files?

![Image 002](https://user-images.githubusercontent.com/5905860/75345111-fd388d00-5893-11ea-8edf-3c26e15ef402.png)

**Comment by siowena** [comment]
yep
The 2020.emb_update_2020-02-25.emb will be the last backup from the old app when  you used (not sure if you have set to  create backup before or after use)
The _v7 will be the compatible file for the old app - copy/rename it and then open in the old app - it should have all your Tx to date.

**Comment by Teezton** [comment]
> yep
> The 2020.emb_update_2020-02-25.emb will be the last backup from the old app when you used (not sure if you have set to create backup before or after use - check options)
> The _v7 will be the compatible file for the old app - copy/rename it and then open in the old app - it should have all your Tx to date.

Worked! Thank you!

Quick question, any way to export the new "Reports" and import to mmex_1.3.3_x64? They are much better and simple.

![Image 003](https://user-images.githubusercontent.com/5905860/75352004-eba9b200-58a0-11ea-84dd-0309f1ef1c15.png)

**Comment by vomikan** [comment]
It's hard coded. Unfortunately, not possible.
i'll try to reproduce the new reports structure in mmex v. >= 1.3.4
It's available here:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/history
