### ISSUE TITLE
Transaction Report Filter does not work (returns no results)

### ISSUE THREAD

**Issue by valsamis-d** [moneymanagerex/moneymanagerex#2328]
**Describe the bug**
This pertains to 'Alpha.7' builds. After the build of 2019-01-06 the "Transaction Report Filter" does not work as expected; it returns no results

**To Reproduce**
1. Go to 'Transaction Report Filter'
2. Enter a criterion for Notes
3. Click OK

**Expected behavior**
I'm expecting to see quite a few transactions, but none is shown. Going back to build of 2019-01-06 my transactions are there

**Screenshots**
Build of 2020-02-25:

![Build_of_2020_02_25](https://user-images.githubusercontent.com/17590539/75348511-ab9bfc80-58ab-11ea-9932-1dbcb8f24744.jpg)

Build of 2019-01-06:

![Build_of_2019_01_06](https://user-images.githubusercontent.com/17590539/75348552-c4a4ad80-58ab-11ea-9a96-cc95789a262c.jpg)

**Your OS:**
- [x] Windows 10 Pro

**MMEX version:**
- [x] 1.4.x Alpha 7 Builds

**Comment by vomikan** [comment]
Add the * at the end of looking word.
#2295

**Comment by valsamis-d** [comment]
This worked perfectly! Thank you @vomikan and sorry for not realizing #2295 was already resolved.
