### ISSUE TITLE
database upgrade to version 10 failed

### ISSUE THREAD

**Issue by cavoinne** [moneymanagerex/moneymanagerex#2329]
Hi,

I am trying to upgrade from 1.3.3 to 1.4.0 alpha7

First I got the current format issue (missing EUR symbol for Euro).
After some research of known issues I followed all the steps described here:
https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems
It fixed the missing EUR symbol and removed the duplicates EURO which were per country.

But after all these steps, I have a new error now for which I did not find a solution.
Here is the error message:

MMEX database upgrade to version 10 failed!
Please restore DB from autocreated pre-upgrade backup and retry or contact MMEX support
SQL logic error[1]: error in view alldata: no such table: main.currencyformats_v1

Could you help me with that one?

Thanks.

**Comment by vomikan** [comment]
#1928

**Comment by vomikan** [comment]
Seems problem with alldata view.
If the view deleted then the app starts well.

**Comment by cavoinne** [comment]
Sorry for my ignorance but how do I delete the alldata view?
It's not obvious from #1928 which you pointed to...
Thanks for your help!

**Comment by vomikan** [comment]
I recommend to delete alldata.
In case if this view is used (for some custom reports, for example) it should be updated then created again.

**Comment by cavoinne** [comment]
I understand that you want me to delete alldata but my question how do I do that ?
Thanks

**Comment by siowena** [comment]
There are only two ways I know of:
1. Access the DB through a SQL editor and either delete the view or edit it
2. The team will need to provide a patch file for Database Debug option on the Tools menu.

If you're technically confident, then try option 1.

**Comment by cavoinne** [comment]
OK so in case it can help others here is what I did:
1-Downloaded an sqlite database viewer/editer, this one worked: https://sqlitebrowser.org/
2-Opened my MMEX database with the editor
3-In View, selected alldata view, right click and delete
4-Saved the database

It seems it worked since this DB does not fail at version 10 anymore when I try to load it into MMEX 1.4.0 alpha7. But It fails at version 12 now... Will open a new ticket for this one.
