### ISSUE TITLE
Fedora 31 - Application crash when creating new database

### ISSUE THREAD

**Issue by linuxcrash** [moneymanagerex/moneymanagerex#2332]
**Describe the bug**
On Fedora 31 currently the 1.4.0 Alpha 7 of MMEX does crash randomly with below error:
`
Gtk-CRITICAL **: 15:12:48.087: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
mmex: symbol lookup error: mmex: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE5eraseEmm, version WXU_3.0
`

**To Reproduce**
Open Application on Fedora 31 and create a new DB. For existing DB's try to run a report and then run a second report.

**Expected behavior**
Application should not crash.

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [X] Linux Fedora 31 Kernel 5.5
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [X] 1.4.x -  1.4.0_alpha.7-1.fc30
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
I recommend to downgrade to v1.3.4
https://travis-ci.org/github/moneymanagerex/moneymanagerex/builds/671471158?utm_medium=notification&utm_source=github_status

https://github.com/moneymanagerex/moneymanagerex/issues/2353
