### ISSUE TITLE
Yahoo exchange rates issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2334]
In case if base currency is RUB an exchange rate for PYG not available, but its available with regard to USD.

https://query1.finance.yahoo.com/v7/finance/quote?symbols=PYGUSD=X&fields=regularMarketPrice,currency,shortName

```
{
"quoteResponse" : -{
"result" : -[
-{
"language" : en-US,
"region" : US,
"quoteType" : CURRENCY,
"triggerable" : true,
"currency" : USD,
"regularMarketPrice" : 0.00015062215,
"shortName" : PYG/USD,
"firstTradeDateMilliseconds" : 1070236800000,
"priceHint" : 4,
"regularMarketTime" : 1584753267,
"fullExchangeName" : CCY,
"exchange" : CCY,
"exchangeTimezoneName" : Europe/London,
"exchangeTimezoneShortName" : GMT,
"gmtOffSetMilliseconds" : 0,
"market" : ccy_market,
"esgPopulated" : false,
"marketState" : CLOSED,
"tradeable" : false,
"sourceInterval" : 15,
"exchangeDataDelayedBy" : 0,
"symbol" : PYGUSD=X
}
],
"error" : 
}
}
```

https://query1.finance.yahoo.com/v7/finance/quote?symbols=PYGRUB=X&fields=regularMarketPrice,currency,shortName

```
{"quoteResponse":{"result":[],"error":null}}
```

- [x] v1.3.4

**Comment by vomikan** [comment]
#1530

**Comment by vomikan** [comment]
https://finance.yahoo.com/quote/USDBYN=X/    <- working
https://finance.yahoo.com/quote/RUBBYN=X/   <- not working

**Comment by vomikan** [comment]
https://query1.finance.yahoo.com/v8/finance/chart/RUBUAH=X?period1=1606128217&period2=9999999999&interval=1d&fields=currency

{"chart":{"result":null,"error":{"code":"Not Found","description":"No data found, symbol may be delisted"}}}

**Comment by n-stein** [comment]
Is there still an outstanding issue here? 

This seems to work fine. Yahoo doesn't have a rate for RUB/UAH or RUB/BYN but MMEX fetches the correct rate by converting through USD.

**Comment by whalley** [comment]
Yes, just tried this and it does indeed seem to work. Closing.
