### ISSUE TITLE
import CSVs from Mint.com

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2352]
Didn't see a way to import CSVs from Mint (they use amount in 1 column and a debit/credit column next to it instead of a +/-).

```
Date,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
12/24/2018,Transfer from Bank Account,PAYMENT - THANK YOU,28.9,credit,Credit Card Payment,CREDITCARD,,
12/10/2018,Overstock,"OVR*O.CO/OVERSTOCK.CO - 800-8432446, UT",28.9,debit,Shopping,CREDITCARD,,
10/3/2018,Transfer from Bank Account,PAYMENT - THANK YOU,4.4,credit,Credit Card Payment,CREDITCARD,,
9/21/2018,McDonald's,"MCDONALD'S F6763 - WASHINGTON, DC",1.1,debit,Fast Food,CREDITCARD,,
9/14/2018,McDonald's,"MCDONALD'S F6763 - WASHINGTON, DC",1.1,debit,Fast Food,CREDITCARD,,
9/14/2018,McDonald's,"MCDONALD'S F6763 - WASHINGTON, DC",1.1,debit,Fast Food,CREDITCARD,,
```

**Comment by vomikan** [comment]
Workaround is to use MS Excel to transform the data to proper format

![image](https://user-images.githubusercontent.com/6836805/78170759-1b2d7a80-745c-11ea-88a9-f64dff264219.png)
```
=IF(F2<>"credit";1;-1)*E2
```

**Comment by reddyshyam** [comment]
I know wrong place and am really sorry! I have been on 1.4 alpha7 for ages and don't see any active developement on that.

I see 1.3.4 release round the corner. Can you just open up the 1.4 alpha7 file with 1.3.4 please?

Sorry again!

**Comment by vomikan** [comment]
@reddyshyam  #2353
