### ISSUE TITLE
downgrade DB from v1.4.x to v1.3.x (and v1.5.0)

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2353]
Solution:

1) extract this zip-file to any folder.
[downgrade_db_13_7_v4.zip](https://github.com/moneymanagerex/moneymanagerex/files/5842166/downgrade_db_13_7_v4.zip)

2) Run mmex 1.3.x / 1.5.x and open your DB 
![image](https://user-images.githubusercontent.com/6836805/105171133-f1e6f380-5b2e-11eb-9c2f-dab7d0ce19ee.png)

3) 
![image](https://user-images.githubusercontent.com/6836805/105170914-b0eedf00-5b2e-11eb-8044-38e8e4bc69b9.png)
choose Yes
4) choose previously extracted downgrade_db_13_7_v4.mmdbg file
![image](https://user-images.githubusercontent.com/6836805/105171371-31addb00-5b2f-11eb-8e6e-bcc638046d98.png)
5) Close the app
6) Run the app and choose your DB file. It's already downgraded.
Happy end

--------------------------------8<-----------------------------------------------------
I have been on 1.4 alpha7 for ages and don't see any active developement on that.
I see 1.3.4 release round the corner. Can you just open up the 1.4 alpha7 file with 1.3.4 please?

![image](https://user-images.githubusercontent.com/6836805/78235993-16130e80-74e2-11ea-8590-fff76b1f074f.png)

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older

**Comment by vomikan** [comment]
I was expecting this question. It need to develop a script to restore compatibility.

Yes, development 1.4.0 is suspended. Many new features were added, but there were not enough resources to support the development.
  Version 1.3.4 contains many of the fixes from 1.4.0, but the database remains at version 7, like the most popular version 1.3.3.

**Comment by reddyshyam** [comment]
Thanks @vomikan for the prompt reply and this new ticket. I will keep an eye on this one and downgrade to 1.3.4

Really appreciate all your selfless efforts. 🤝 🙇 👏 🤗

**Comment by vomikan** [comment]
Seems it's just a patch needed. When the "MMEX database upgrade" warning were closed the following dialog appears: 

![image](https://user-images.githubusercontent.com/6836805/78240299-7e182380-74e7-11ea-94f8-5320ddb8f60a.png)

I believe a proper prepared patch can downgrade DB.

**Comment by reddyshyam** [comment]
Hi @vomikan,

I can definitely help. Please let me have the patch. Will let you know how it goes.

**Comment by vomikan** [comment]
Required script would complex.
The following script does upgrade DB.
https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_12.sql

To downgrade DB it should be the script like the provide by the link above but with reverse logic.
For example:
```
CREATE TABLE IF NOT EXISTS ACCOUNTLIST_V1
        (ACCOUNTID integer primary key
        , ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
        , ACCOUNTTYPE TEXT NOT NULL 
        , ACCOUNTNUM TEXT
        , STATUS TEXT NOT NULL /* Open, Closed */
        , NOTES TEXT, HELDAT TEXT
        , WEBSITE TEXT
        , CONTACTINFO TEXT
        , ACCESSINFO TEXT
        , INITIALBAL numeric
        , FAVORITEACCT TEXT NOT NULL
        , CURRENCYID integer NOT NULL
        , STATEMENTLOCKED integer
        , STATEMENTDATE TEXT
        , MINIMUMBALANCE numeric
        , CREDITLIMIT numeric
        , INTERESTRATE numeric
        , PAYMENTDUEDATE text
        , MINIMUMPAYMENT numeric
);

INSERT INTO ACCOUNTLIST_V1
SELECT
ACCOUNTID
, ACCOUNTNAME
, case when ACCOUNTTYPE in ('Cash','Checking','Credit Card','Loan','Term','Investment','Asset','Shares') then ACCOUNTTYPE else 'Cash' end ACCOUNTTYPE 
, ACCOUNTNUM
, STATUS
, NOTES 
, HELDAT
, WEBSITE
, CONTACTINFO
, ACCESSINFO
, INITIALBAL
, FAVORITEACCT
, CURRENCYID
, STATEMENTLOCKED
, STATEMENTDATE
, MINIMUMBALANCE
, CREDITLIMIT
, INTERESTRATE
, PAYMENTDUEDATE
, MINIMUMPAYMENT
FROM ACCOUNTLIST;

DROP TABLE ACCOUNTLIST;
--etc for all tables
.......
-- finish
PRAGMA user_version = 7;
```

**Comment by reddyshyam** [comment]
Hi @vomikan.

Please see if the attached helps. If you confirm, then we can test patching.

[database_version_7.zip](https://github.com/moneymanagerex/moneymanagerex/files/4421475/database_version_7.zip)

**Comment by vomikan** [comment]
| 1.3.4  | 1.4.0  |
|---|---|
|  ![image](https://user-images.githubusercontent.com/6836805/78272612-6b691300-7516-11ea-8b1c-98771e2a63bc.png)  |  
![image](https://user-images.githubusercontent.com/6836805/78272591-61dfab00-7516-11ea-86a7-a23bd02eccc1.png)  |

**Comment by reddyshyam** [comment]
> , case when ACCOUNTTYPE != 'Crypto' then ACCOUNTTYPE else 'Cash' end ACCOUNTTYPE
Hi @vomikan, 

Hope you are just documenting the corrections. I have done the changes my end in the above sql.

**Comment by vomikan** [comment]
CREATE TABLE IF NOT EXISTS ASSETS_V1( .. 
then not needed 
CREATE TABLE ASSETS_V1( ..

PS Good job! Just delete not needed CREATE TABLE xxx

**Comment by vomikan** [comment]
it would not work. May be deleted.

```
-- rename table names used in GRM definitions

UPDATE REPORT SET SQLCONTENT = CONCAT(SQLCONTENT,'_V1') WHERE SQLCONTENT NOT LIKE  '%_V1%' COLLATE NOCASE;
UPDATE REPORT SET LUACONTENT = CONCAT(LUACONTENT,'_V1') WHERE LUACONTENT NOT LIKE '%_V1%' COLLATE NOCASE;
UPDATE REPORT SET TEMPLATECONTENT = CONCAT(TEMPLATECONTENT, '_V1') WHERE TEMPLATECONTENT NOT LIKE '%_V1%' COLLATE NOCASE;
```

**Comment by vomikan** [comment]
DROP TABLE ASSETCLASS;
.....
DROP TABLE SHAREINFO;
-- finish
PRAGMA user_version = 7;

**Comment by vomikan** [comment]
Impossible.
![image](https://user-images.githubusercontent.com/6836805/78275174-eb44ac80-7519-11ea-88af-c7d3ef959a7e.png)

**Comment by vomikan** [comment]
PS 90% done!

**Comment by reddyshyam** [comment]
> Impossible.
> ![image](https://user-images.githubusercontent.com/6836805/78275174-eb44ac80-7519-11ea-88af-c7d3ef959a7e.png)

Except this, done with rest. 

Commented out all drop and update sqls just in case needed again.

[database_version_7.zip](https://github.com/moneymanagerex/moneymanagerex/files/4422327/database_version_7.zip)

**Comment by reddyshyam** [comment]
> Impossible.
> ![image](https://user-images.githubusercontent.com/6836805/78275174-eb44ac80-7519-11ea-88af-c7d3ef959a7e.png)

What are you proposing? drop the column from create ddl and insert sql statements?

**Comment by reddyshyam** [comment]
> CREATE TABLE IF NOT EXISTS ASSETS_V1( ..
> then not needed
> CREATE TABLE ASSETS_V1( ..
> 
> PS Good job! Just delete not needed CREATE TABLE xxx

Thansk @vomikan . I am really glad could help a bit at the least. 😃

**Comment by vomikan** [comment]
```
CREATE TABLE IF NOT EXISTS CURRENCYFORMATS_V1(
CURRENCYID integer primary key, 
CURRENCYNAME TEXT COLLATE NOCASE NOT NULL UNIQUE, 
PFX_SYMBOL TEXT, 
SFX_SYMBOL TEXT, 
DECIMAL_POINT TEXT, 
GROUP_SEPARATOR TEXT, 
UNIT_NAME TEXT COLLATE NOCASE, 
CENT_NAME TEXT COLLATE NOCASE, 
SCALE integer, 
BASECONVRATE numeric, 
CURRENCY_SYMBOL TEXT COLLATE NOCASE NOT NULL UNIQUE
);

INSERT INTO CURRENCYFORMATS_V1 SELECT
  CURRENCYID
, CURRENCYNAME
, PFX_SYMBOL
, SFX_SYMBOL
, DECIMAL_POINT
, GROUP_SEPARATOR
, UNIT_NAME
, CENT_NAME
, SCALE
, BASECONVRATE
, CURRENCY_SYMBOL
FROM CURRENCYFORMATS;
DROP INDEX IF EXISTS IDX_CURRENCYFORMATS_SYMBOL;
DROP TABLE CURRENCYFORMATS;
CREATE INDEX IDX_CURRENCYFORMATS_SYMBOL ON CURRENCYFORMATS_V1(CURRENCY_SYMBOL);
```

**Comment by vomikan** [comment]
Here:
https://github.com/moneymanagerex/moneymanagerex/tree/v1.3.4/src/db
pieces of code where DB tables created.
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.4/src/db/DB_Table_Currencyformats_V1.h#L78
etc

**Comment by reddyshyam** [comment]
Replaced CURRENCYFORMATS_V1 changes listed above.

I am assuming above links were just for my reference. 

[database_version_7.zip](https://github.com/moneymanagerex/moneymanagerex/files/4422536/database_version_7.zip)

**Comment by vomikan** [comment]
Congratulations! This script is working. 
I've used it in SQLiteBrowser
[database_version_7.txt](https://github.com/moneymanagerex/moneymanagerex/files/4423015/database_version_7.txt)

![image](https://user-images.githubusercontent.com/6836805/78289264-8fceea80-752a-11ea-83a7-09ae13933a81.png)

Final step is to make mmdbg file from this one.

**Comment by reddyshyam** [comment]
That's great! Well done @vomikan yourself! 😄 

Can't wait to get the patch and apply!

**Comment by vomikan** [comment]
this release may be used for downgrade DB v13 to V7 using the mmex_DB_downgrade_v13_to_v7.zip file provided in previous post. (The file should be extracted).
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/31917370

**Comment by reddyshyam** [comment]
> [mmex_DB_downgrade_v13_to_v7.zip](https://github.com/moneymanagerex/moneymanagerex/files/4423520/mmex_DB_downgrade_v13_to_v7.zip)
> This patch would working with v1.3.4-rc.3

Thanks @vomikan. Got the patch and will wait for 1.3.4-rc3 to be released to test. Don't see it in releases yet.

🤝

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/31917370/job/ikbc90yo48l68tmx/artifacts

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/31917370/job/gw8hbojwj9soasmq/artifacts

**Comment by reddyshyam** [comment]
Sorry, didn't know that. Just tried and works like a charm! All good my end.

Thanks a ton for your quick solution! 🙇 🤝 👌

**Comment by vomikan** [comment]
Thanks for your cooperation.
It saved me a lot of time.

**Comment by vomikan** [comment]
[downgrade_db_13_7_v2.zip](https://github.com/moneymanagerex/moneymanagerex/files/4432317/downgrade_db_13_7_v2.zip)

**Comment by vomikan** [comment]
[downgrade_db_13_7_v3.zip](https://github.com/moneymanagerex/moneymanagerex/files/4432527/downgrade_db_13_7_v3.zip)

**Comment by jkuj6** [comment]
@vomikan i am having an issue finding any file *.mmdbg in the window browser when trying to apply the patch.  Ive tried version 1.3.4 rc7, ive tried mmex 1.3.5 release with DB v.7.  the mmdbg file you posted above (after extracting) does not appear at all, so i can use it??
Can you please help in telling me any way to convert my encrypted DB to v7 so that i can run 1.3.5 new version?

Ive searched everywhere about this issue and i cannot find a solution.

Im on Ubuntu 18.04

**Comment by vomikan** [comment]
My suggestions:
1) Decrypt DB
2) Use SQLite DEveloper and run mmdbg there

**Comment by bregolino** [comment]
Hi there @vomikan 

Same problem here
![image](https://user-images.githubusercontent.com/54753309/86949332-de40e600-c124-11ea-85dc-9c9f17b32c18.png)

Can you please hep. win10, using v3 script

thanks a lot

**Comment by vomikan** [comment]
@bregolino
The mmdbg file conteins several SQL blocks delimited by semicolon ";"

First:
CREATE TABLE IF NOT EXISTS ACCOUNTLIST_V1(
ACCOUNTID integer primary key
, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */
, ACCOUNTNUM TEXT
, STATUS TEXT NOT NULL /* Open, Closed */
, NOTES TEXT
, HELDAT TEXT
, WEBSITE TEXT
, CONTACTINFO TEXT
, ACCESSINFO TEXT
, INITIALBAL numeric
, FAVORITEACCT TEXT NOT NULL
, CURRENCYID integer NOT NULL
, STATEMENTLOCKED integer
, STATEMENTDATE TEXT
, MINIMUMBALANCE numeric
, CREDITLIMIT numeric
, INTERESTRATE numeric
, PAYMENTDUEDATE text
, MINIMUMPAYMENT numeric
);

second:
CREATE TABLE IF NOT EXISTS ASSETS_V1(
ASSETID integer primary key
, STARTDATE TEXT NOT NULL
, ASSETNAME TEXT COLLATE NOCASE NOT NULL
, VALUE numeric
, VALUECHANGE TEXT /* None, Appreciates, Depreciates */
, NOTES TEXT
, VALUECHANGERATE numeric
, ASSETTYPE TEXT /* Property, Automobile, Household Object, Art, Jewellery, Cash, Other */
);

etc

Solution:
run SQLite Developer http://www.sqlitedeveloper.com/
open your mmb file as DB
Run every sql block one by one until last one PRAGMA user_version = 7;
ignore lines started with --

As result your DB will be upgraded or let me know if some error appears.

**Comment by jkuj6** [comment]
> My suggestions:
> 
>     1. Decrypt DB
> 
>     2. Use SQLite DEveloper and run mmdbg there

Thanks, seems i have got it to work.
I decrypted db and opened it in SQLBrowser.
I simply copied all contents in the .mmdbg into the sql query and ran all cmds at once.  All completed successfully.
Then i opened the new DB with the new version.

**Comment by avma** [comment]
I'm on Linux so this "run SQLite Developer http://www.sqlitedeveloper.com/" does not work for me...

The easiest way to downgrade  the DB that I found was:
          1. Create a new DB with MMeX v1.3.x, 
          2. Use an SQL viewer (I'm using  [https://sqlitestudio.pl/](url))
          2. Open both DBs (1.4.x and 1.3.x) with the SQL viewer
          3. Rename, and add suffix, to the table names in DB 1.4.x :TABLE_NAME_V1 (only to those that exists in DB 1.3.x)
          4. Delete all empty tables from DB 1.3.x
          5. Copy all the tabled you renamed from 1.4.x to 1.3.x
          6. Launch App
10 minutes work max, did this this morning, so fare all looks good.

**Comment by tosim91** [comment]
Been using MMEx since it first came out, on Windows, then on Linux. I've stuck with the 1.40 release all this time, since it worked real good for me all along. I've been in VA hospital for awhile, and got home thgis AM. Upon booting up MMEx, I'm finding it is now v1.5.1, and NOT ACCEPTING MY DB. Even though I requested the debug file, it DOES NOT send it. As I've got a consierable DB, I DO NOT wish to redo from scratch. Will somebody PLEASE send me a link to the 1.4.0deb download link, as I'm not able to find one. Thank you.

**Comment by tosim91** [comment]
I now have the debug file file, but, am totally lost re how to use it. Sure would just prefer the 1.40deb file. Thank you.

**Comment by jeepcook** [comment]
Hello,
I have a database v7. I think I have to upgrade to V13 but I don't know how to do that. Is there an online method, or anybody here can convert it?
Thanks

**Comment by whalley** [comment]
@jeepcook - Why do you think you need to upgrade to v13. All the latest MMEX releases (e.g. v1.5.4) run on the v7 database. The v13 database was only applicable to the v1.4.x branch which is now obsolete.

SO if you are using the latest MMEX releases with the v7 DB that is fine.

**Comment by whalley** [comment]
OK, if you have Android app related issues then please raise them here: https://github.com/moneymanagerex/android-money-manager-ex/issues

**Comment by jeepcook** [comment]
In fact, I use both android and pc version. If I have a bdd error on android, I have the same on pc version I think.

**Comment by whalley** [comment]
Sorry, what is a BDF error?

**Comment by jeepcook** [comment]
Here is the screenshot
![Screenshot_2021-07-29-12-33-43-779_com money manager ex](https://user-images.githubusercontent.com/17811804/127488664-64c8c9be-5127-4095-ab53-209658bffba7.jpg)

**Comment by whalley** [comment]
OK, got it. It's French for Database/Datastore.... 

Looks as if the `tables_v1.sql` file with the database definitions includes these tables but they are never used in the code anyway. 

You can ignore the warning, but probably worth raising an issue with the Android application maintainers to have the offending entries removed.

**Comment by whalley** [comment]
Closing this now.
