### ISSUE TITLE
Is currency grouping implemented?

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#2356]
Hi @vomikan,

Is currency grouping implemented? I see grouping (comma) option in setup but don't really see it anywhere. Please see attached. No rush, just wanted to know if implemented or not.

![Screenshot_03Apr2020_211057](https://user-images.githubusercontent.com/12392746/78379502-18638e80-75f0-11ea-98f8-1dbb3c7e4101.png)

As you are aware 😃 I am on 1.3.4rc3 64 bit and on Windows 10 Pro 64bit 20H1 slow insider latest.

I would have expected to see the values like 1,23,45,67.00

**Comment by vomikan** [comment]
It should be there. Tools - Organize Cyrrency….
![image](https://user-images.githubusercontent.com/6836805/78379725-7cc82300-75db-11ea-9c40-41453795e732.png)

**Comment by reddyshyam** [comment]
Hi @vomikan, 

I did check that before asking. For some reason, it doesnot show my end.

![Screenshot_03Apr2020_213340](https://user-images.githubusercontent.com/12392746/78381350-ddaf2580-75f2-11ea-848d-2d5463526786.png)

**Comment by vomikan** [comment]
It's OK for me.
![image](https://user-images.githubusercontent.com/6836805/78382220-265ce380-75df-11ea-8c31-09a7bfc7882b.png)

I've recommend to upgrade to v 1.3.4

https://sourceforge.net/projects/moneymanagerex/files/v1.3.4-rc.2/

**Comment by reddyshyam** [comment]
Hi @vomikan, thanks for the prompt response. May be we are in the same country. 🤣 

I am already on 1.3.4 rc3 

![image](https://user-images.githubusercontent.com/12392746/78382766-fa4c5d00-75f4-11ea-9cba-baf2bd8e4b64.png)

**Comment by vomikan** [comment]
Okey, the app is new. Currency group separator is present?

**Comment by siowena** [comment]
@reddyshyam can I ask what you Windows settings for Regional Formats setting are?

I ask as 1.3.4 beta 1 had an issue with decimal/separator for Italian users based on their settings.

**Comment by reddyshyam** [comment]
> @reddyshyam can I ask what you Windows settings for Regional Formats setting are?
> 
> I ask as 1.3.4 beta 1 had an issue with decimal/separator for Italian users based on their settings.

Hi,

Thanks for reporting the v12 to v7 db downgrade patch worked. All thanks to @vomikan. 

Regarding my windows settings. Please find the same below.

![Screenshot_04Apr2020_011427](https://user-images.githubusercontent.com/12392746/78399345-5bcef480-7612-11ea-9312-814eaccfa2ad.png)
![Screenshot_04Apr2020_011514](https://user-images.githubusercontent.com/12392746/78399351-5d002180-7612-11ea-93aa-668e9f49015c.png)

**Comment by reddyshyam** [comment]
Hi @vomikan,

Good day! What more information do you need? I have provided with everything @siowena has asked.

**Comment by vomikan** [comment]
IWOMM — It works on my machine!
Unfortunatly, I have no ideas what exactly should be fixed.

**Comment by vomikan** [comment]
#2335
