### ISSUE TITLE
Problem Saving template in " Transaction Report filter" 

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/moneymanagerex#2358]
Cannot save templates 0 to 9 in "Transaction Report filter" .

**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
What mmex version are you using?

**Comment by rmkhalfay** [comment]
1.3.4 rc2

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rmkhalfay** [comment]
Thank you for correcting this; However the CLEAR button does not clear entries. 

Also if you save - in 0 Category "CHARITY:ZAKAT" and in 3 say "INTEREST RMK NRO". Then Click 0 and then click 3, Then the names in CATEGORY are copied from 0 template filter to currently open 3; It becomes "INTEREST RMK NRO: ZAKAT" See images attached
![image](https://user-images.githubusercontent.com/53577940/78579138-84890100-7841-11ea-8034-9c023d3f69c0.png)
![image](https://user-images.githubusercontent.com/53577940/78579294-c5811580-7841-11ea-8f39-e9f164c20c57.png)
![image](https://user-images.githubusercontent.com/53577940/78579663-51933d00-7842-11ea-843f-897345af0edd.png)
