### ISSUE TITLE
Transaction Type change blanks the Payee field

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#2360]
> Replace this text (marked with >) with detailed description of your problem.

Enter all the values for a transaction in the dialog.
Change the Withdrawal to Deposit - this clears the Payee field and forces the user to re-select the value.

> Please do not remove information attached below this text.

<hr>Version: 1.3.4-RC.2<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.2 (wxMSW 10.0)<br>
 • wxSQLite3 4.5.1 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.59.0-DEV WinSSL<br>
<br>
Build: Apr  2 2020 00:01:48 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 18362), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1536x864 32bit 96x96ppi

**Comment by reddyshyam** [comment]
Also blank status field. @vomikan. can you look into this as well please?

**Comment by vomikan** [comment]
@reddyshyam  I can't reproduce this issue.

**Comment by reddyshyam** [comment]
Hi @vomikan,

When I downgraded from V12 to V7 and from 1.4 a7 to 1.3.4 rc3, existing transfers have started showing FF, not sure what they mean too.

After 1.3.4 rc3, any transaction type I change to withdraw to transfer, the status becomes blank no matter how many times i edit it and change to any of the status types. Please see below.

![image](https://user-images.githubusercontent.com/12392746/78457602-09044400-76c9-11ea-87fa-f780832612db.png)

**Comment by siowena** [comment]
Two character Status was a feature of 1.4.x , the 1st character for the source account and 2nd character for the destination account so each account can be flagged reconciled (or other status) separately.

**Comment by vomikan** [comment]
I can't downgrade a test DB
![image](https://user-images.githubusercontent.com/6836805/78459054-00a70b80-76bf-11ea-8727-e62f28f3802f.png)

**Comment by vomikan** [comment]
I've updated the script. 
[downgrade_db_13_7_v2.zip](https://github.com/moneymanagerex/moneymanagerex/files/4432257/downgrade_db_13_7_v2.zip)

But exectly for your issue the following script may be applyed:
```
-- MMEX Debug SQL - Update --

update CHECKINGACCOUNT_V1 set STATUS = substr(case STATUS when '' then 'N' else STATUS end, 1, 1) where TRANSCODE ='Transfer';
```
(Save it as mmdbg file.

**Comment by reddyshyam** [comment]
Hi @vomikan,

Thanks for the debug script. I just ran it and it has fixed the 'FF' thing and made all blank statuses 'N' but when I edit the transaction to change from 'N' to anything else it becomes blank again. Please see below.

![image](https://user-images.githubusercontent.com/12392746/78460496-dc5b2700-76de-11ea-8194-aaac39640993.png)

**Comment by reddyshyam** [comment]
> Two character Status was a feature of 1.4.x , the 1st character for the source account and 2nd character for the destination account so each account can be flagged reconciled (or other status) separately.

Thanks @siowena. You have nailed the issue right. @vomikan has made a script to resolve my issue but still something is wrong. Hope he will be able to eventually figure it out. Thanks for the heads up.

**Comment by vomikan** [comment]
The "N" and empty string is the same "None" transaction status.

**Comment by vomikan** [comment]
Seems N is incorrect.
For example, Transaction filter can't find those transactions.
Therefore, please update you DB by the following script:
```
-- MMEX Debug SQL - Update --

update CHECKINGACCOUNT_V1 set STATUS = (case STATUS when 'N' then '' else STATUS end) where TRANSCODE ='Transfer';
```

**Comment by reddyshyam** [comment]
Hi @vomikan,

Thanks for your efforts, really appreciate it! 

The above fix has made all 'N' to blank but still I cannot edit and change the status. No matter what I set, Void, Follow-up, Duplicate, it still remains blank. Please see below.

![image](https://user-images.githubusercontent.com/12392746/78466552-cf125c80-771f-11ea-9be5-95a4fc164970.png)

**Comment by vomikan** [comment]
@reddyshyam I can't reproduce this issue,
I can change status for a new transaction. The status keeps in case if the transaction type changed.
I can change the status of an exiting transaction.
Also I can change transactions status in Checking panel by pressing R U F D buttons for selected one.

**Comment by vomikan** [comment]
IWOMM — It works on my machine!

**Comment by reddyshyam** [comment]
> IWOMM — It works on my machine!

Good enough for me then. 😃

**Comment by reddyshyam** [comment]
Hi @vomikan,

A quick update. The issue is gone on the 1.3.4 rc3 released here. I just re-installed and all looks good. Thanks again. 👍
