### ISSUE TITLE
Sum on main page for bank account is wrong

### ISSUE THREAD

**Issue by tierradenadie** [moneymanagerex/moneymanagerex#2362]
The sum for a bank account is wrong on the main page, but correct on the bank accounts page. It always shows a value that is approx. 4500 units higher. The total amount on the front page is also wrong, but not by the amount, the bank account is wrong. It shows approx 21500 units more, than the sum of all the accounts, including the wrong bank account value, on the front page show.

**Comment by lebagnasco** [comment]
The sum does not take care of the currancy and adds all values linearly, without using the Conversion to Base Rate, witch is missing.

**Comment by vomikan** [comment]
I can't to reproduce this issue
![image](https://user-images.githubusercontent.com/6836805/80412412-7f662180-88d6-11ea-9fd9-ddf282c8e3b9.png)

**Comment by lebagnasco** [comment]
The issue begins when I update to 1.3.4

1.3.3
[image: image.png]
1.3.4
[image: image.png]

**Comment by tierradenadie** [comment]
I did some testing with the new version 1.3.4. All accounts, except the previously affected account, have the same currency and show the correct value on the front page. Only the bank account, that showed previously a wrong total amount is still affected. The value shown on the front page is always 4500€ higher, than on the account page. The total sum on the front page is also 4500€ higher, than it should be. I made a fictional booking that would make a total of 0€ for the affected bank account. The total on the main page showed 4500€.

**Comment by vomikan** [comment]
@lebagnasco could you upload the pics again?

**Comment by lebagnasco** [comment]
Sure, and I uploaded the other relevant difference between these two
versions,
The & sign is a dummy currency to track past activities and its value is
base currency/100000, in 134 the conversion base rate is missing

**Comment by gabriele-v** [comment]
@lebagnasco could you try with latest 1.3.5 beta? It should be fixed

**Comment by lebagnasco** [comment]
Hello Gabriele.
It's fixed now, thanks a lot.
Regards, Luis
