### ISSUE TITLE
Startup keeps asking to set the language

### ISSUE THREAD

**Issue by grabags** [moneymanagerex/moneymanagerex#2366]
Every time the application is started there is a splash screen asking to set the application language.
This was already set to 'system default'. If this is left alone then the splash is alway shown (see below). If this is changed then the splash goes away. However, it can only be changed by selecting another language - so I chose one at random and now I cannot change back to 'system default'.

It is possible this is due to the packaging. Inspecting and comparing the 'bin' sub-directories to the V1.3.3 installation shows that this version has multiple extra dll's and localization folders.

**Your OS:**
- [X] Windows 10 -  x64 portable installation

**MMEX version:**
- [X] 1.3.x - 1.3.4-RC3

![image](https://user-images.githubusercontent.com/7996223/78569976-3f060d00-781c-11ea-895c-94f820544266.png)

**Comment by grabags** [comment]
BTW - less importantly there is no English (U.K.) option.

**Comment by vomikan** [comment]
Becouse there is no English (U.K.) po file. (Possible en_GB.po)

https://github.com/moneymanagerex/moneymanagerex/tree/v1.3.4/po

**Comment by grabags** [comment]
Yes - there is no 'po' subdirectory in my portable installation for 1.3.4-RC3.
And comparing repository branches 1.3.x and 1.3.4 shows that 1.3.4 has far fewer *.po files. 

I could copy the entire directory from my 1.3.3 installation - if you think this would be a valuable test. Otherwise I'll leave it alone.  It does have a english-uk.po as does the repository.

**Comment by vomikan** [comment]
In bin directory of mmex folder you could create en_GB directory.
When using poeditor (https://poedit.net) edit en_US.po file from https://github.com/moneymanagerex/moneymanagerex/tree/v1.3.4/po
aAs result .mo file would be created. Copy that one into  en_GB directory then rename to mmex.po
