### ISSUE TITLE
v1.3.4-rc.4 Crash on macOS 10.15.4

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2368]
**Describe the bug**
v1.3.4-rc.4 crashes on startup on macOS 10.15.4.

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/wxmac/lib/libwx_osx_cocoau_core-3.0.dylib
  Referenced from: /Applications/mmex.app/Contents/MacOS/mmex
  Reason: image not found

**Your OS:**
- [ ] Windows
- [x] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment]
That has been builded from scratch
[mmex-1.3.4~rc5-Darwin.dmg.zip](https://github.com/moneymanagerex/moneymanagerex/files/4446999/mmex-1.3.4.rc5-Darwin.dmg.zip)


![image](https://user-images.githubusercontent.com/6836805/78718677-65669e00-792b-11ea-9b7a-07c14f6c93d9.png)

**Comment by vomikan** [comment]
seems its result of command brew update && brew install wxmac

https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.4/BUILD.md

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146
