### ISSUE TITLE
1.3.4rc4 Crash at startup on OS X High Sierra

### ISSUE THREAD

**Issue by Petemac3** [moneymanagerex/moneymanagerex#2374]
Apr 10 18:21:39 iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000f.mmex[3503]): Service exited due to signal: Killed: 9 sent by CoreServicesUIAgent[3464]

**Comment by Petemac3** [comment]
Solved it after I found this thread
[https://forum.moneymanagerex.org/viewtopic.php?f=3&t=9146](url)

**Comment by vomikan** [comment]
sudo xattr -rd com.apple.quarantine /Applications/mmex.app

**Comment by vomikan** [comment]
#2374
#2644 #2459
