### ISSUE TITLE
Dates set redesign

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2378]
"Current Financial Year to Date" is useless item and "Current Financial Year" as well.
Because always should be used Financial Year settings:
![image](https://user-images.githubusercontent.com/6836805/79066826-829cc300-7cc3-11ea-96a1-a4486a37ae01.png)
"Last Year" may be deleted in case if slider [<<][>>] would be added

![image](https://user-images.githubusercontent.com/6836805/79066768-17eb8780-7cc3-11ea-95bc-0080dee28a1a.png)

#2372  #2339 #1832

**Comment by how-a** [comment]
The reports are still showing January - December even though my Financial year is April - March

**Comment by vomikan** [comment]
@how-a it's not fixed yet. please be patient.

**Comment by how-a** [comment]
Thanks. I wasn’t sure.

**Comment by whalley** [comment]
Not sure I understand what is needed here? The list of periods looks fine to me.

**Comment by whalley** [comment]
Agreed, I can't see anything more we need to do for this.

**Comment by how-a** [comment]
I updated the application and it came right. Thanks for checking back with
me. Howard.
