### ISSUE TITLE
Bug - select category in recurring transaction

### ISSUE THREAD

**Issue by Ton558** [moneymanagerex/moneymanagerex#2382]
Hi !
This is a bug when selecting a category in a recurring transaction, after selecting the desired category the category does not appear in the button, the software does not take into account the category and impossible to validate the transaction.

regards,

**Comment by vomikan** [comment]
Please, upload an information regarding mmex build.
This information is available in main menu help - About

**Comment by vomikan** [comment]
#2348

**Comment by Ton558** [comment]
Sorry, mmex build 1.3.4 RC4,

**Comment by vomikan** [comment]
@Ton558 thank you for report the bug.
Update already available 
https://sourceforge.net/projects/moneymanagerex/files/v1.3.4-rc.6/
