### ISSUE TITLE
several bugs: transaction filter button, budget visualisation, forecast report

### ISSUE THREAD

**Issue by simao4ever84** [moneymanagerex/moneymanagerex#2385]
Hi.
I have noticed some problem in the last version of mmex app.
1) transaction filter button: it seems to be inactive
 this is the button permitting to open a dialog window and to select specific transactions

2)budget menu commands:  they seem to be inactive
these commands are "Budget setup: with summary"/ "Budget category reports: with summary"

3)forecast report: unreadable
this report charge a large amount of data presenting a understandable graphic. as well the data on the abscissa are to close to be readible

<hr>Version: 1.3.4-RC.7<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.3 (wxMac 10.14)<br>
 • wxSQLite3 4.4.8 (SQLite 3.30.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1<br>
<br>
Build: Apr 14 2020 08:34:17 <br>
 • CMake 3.16.3<br>
 • Xcode 11.4<br>
 • gettext 0.20.1<br>
 • Clang 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)
<br>
<br>
OS:<br>
 • macOS Mojave Versione 10.14.6 (Build 18G4032)<br>
 •  Italian (Western (Mac OS Roman))<br>
 • 1920x1200 32bit 147x147ppi

**Comment by vomikan** [comment]
I can't reproduce points 1 & 2

**Comment by simao4ever84** [comment]
Dear,
here some more details.

I have just compared mmex 1.3.3 and 1.3.4 and I noticed the following:

1) in a bank account section, the filtering button (top of the window) is inactive 
(a screenshot is attached to the message)

2)budget visualisation: summaries do not work
attached the screenshot comparing mmex 1.3.3 and 1.3.4

Dont' hesitate if you need more help.

[Screenshot 2020-04-15 at 10.22.12.png.pdf](https://github.com/moneymanagerex/moneymanagerex/files/4480206/Screenshot.2020-04-15.at.10.22.12.png.pdf)

**Comment by vomikan** [comment]
IWOMM
![image](https://user-images.githubusercontent.com/6836805/79327478-3056de80-7f1d-11ea-99a1-db970702f15f.png)

![image](https://user-images.githubusercontent.com/6836805/79327669-875cb380-7f1d-11ea-9e13-42dde5017a0b.png)


<hr>Version: 1.3.4-RC.7<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.0.4 (wxMac 10.14)<br>
 • wxSQLite3 4.5.1 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1<br>
<br>
Build: Apr 15 2020 13:04:56 <br>
 • CMake 3.17.0<br>
 • GNU Make 3.81<br>
 • gettext 0.20.1<br>
 • Clang 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)
<br>
<br>
OS:<br>
 • Mac OS X (Darwin 18.6.0 x86_64)<br>
 •  Russian (Cyrillic (Mac OS))<br>
 • 1440x900 32bit 72x72ppi

**Comment by simao4ever84** [comment]
Thank you for your message.
I see new organisation of reports and filtering reports.
I see as well that the "transaction filter" is still not working, anyway in the app I use.

Thanks again for your job.

**Comment by vomikan** [comment]
#2238
