### ISSUE TITLE
v1.3.4-rc.7 Issues on macOS

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2388]
**Describe the bug**

MMEX 1.3.4-rc.7 (file name mmex-1.3.4.rc7-Darwin.dmg)
macOS 10.15.4

1. Choosing Create a New Database or Open Existing Database at startup does not use system default language. View -> Switch Application Language to English (U.S.) does nothing.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/63317977/79265410-0f7e8280-7e64-11ea-9d67-0727e8712e4b.png">

2. MMEX -> Options does nothing

3. Choosing Create a New Database or Open Existing Database at startup causes MMEX to maximize the program window.

**Comment by 2BeeOrNot** [comment]
1.3.4-Release (file name mmex-1.3.4-Darwin.dmg) posted a couple of hours ago has these same issues.

**Comment by vomikan** [comment]
@2BeeOrNot unfortunately there are a lot of annoying issues for MAC.
I've added a lot of them last half hour.

**Comment by vomikan** [comment]
except option 1) I can't reproduce this issues.

**Comment by 2BeeOrNot** [comment]
You are correct. Last night I downloaded v1.3.5-beta.2. Same results as before. This time I continued on and created a database doing my best using the create new database dialog in a foreign language. After creating a new database the options menu works and MMEX does not open maximized and retains it's location and size when opened again.

Long time MMEX user, twelve years this month, on Windows. Since I'm a Mac user now I'm wanted to make the move to MMEX on my Mac. MMEX is the only reason I keep the Windows PC around.

Yes there are issues in the Mac version. But I can now try it out. Thanks for your work on fixing Mac issues.

**Comment by vomikan** [comment]
#2370 related issue.

**Comment by 2BeeOrNot** [comment]
Relating to number 1 above, file open, file create and file save as using another language other than the system default and maybe #2370 (several Window and Services menu options in another language):
System Preferences -> Language and Region, select Apps tab, click plus sign, select an app. For me the language for all apps except MMEX is System Default - English. For MMEX it is System Default - Turkish (Turkey). English is not an option to change to. Changing to another language here does change the text used in the Windows and Services menu options and in file open, file save and file create.

![App Language MMEX](https://user-images.githubusercontent.com/63317977/80405376-8702d780-8890-11ea-9947-6ac65c8c4e57.jpg)
![Numbers Language](https://user-images.githubusercontent.com/63317977/80405383-89653180-8890-11ea-8a70-c33b1071cf26.jpg)

**Comment by 2BeeOrNot** [comment]
Seems macOS doesn't know what system language to use for MMEX. Deleting all .lproj folders from contents->resources in mmex.app fixes the menu language issues and file new, file open and file save as for me. Delete some, leave two three *.lproj files, and macOS will choose one of them as system language to use for MMEX.

![MMEX App Lang 4](https://user-images.githubusercontent.com/63317977/80550498-4a1d0a80-898e-11ea-8bf1-f9d0afee30ac.jpg)
![MMEX App Lang 2](https://user-images.githubusercontent.com/63317977/80550510-530ddc00-898e-11ea-881b-64eee261bda2.jpg)
![MMEX App Lang 1](https://user-images.githubusercontent.com/63317977/80550513-54d79f80-898e-11ea-9d72-e5db80087656.jpg)
![MMEX App Lang 3](https://user-images.githubusercontent.com/63317977/80550519-56a16300-898e-11ea-8a1e-c2271147bfd7.jpg)

**Comment by 2BeeOrNot** [comment]
Update of language issues:
macOS 10.15.4
MMEX 1.3.5-beta.2
System language: English (US)

In info.plist:
<key>CFBundleDevelopmentRegion</key>
<string>en-US</string>

Do you need a en-US.lproj folder with a en_US.po file in it? A "base" file without translations in it.

1. Used the file english.mo from mmex_1.3.3_macos10.9-wx3.0.2build.dmg and rename to en_US.po.

2. In mmex.app created a folder named en_US.lproj in the resources folder.
3. Copy en_US.po into folder en_US.lproj

MMEX now uses system language for all menu items, file open, file create and file save as dialogs.

Also the transaction date format in the Transaction Details window matches the date format in Options->General.

Before steps 1-3 the options date format mm/dd/yyyy but in the Transactions Details window it was yyyy/mm/dd.

And all languages are available to select in System Preferences->Language & Region Apps tab.

I don't know if this will cause problems on Macs not using English as the system language.

**Comment by dajo09** [comment]
this version: mmex_1.3.3_macos10.9-wx3.0.2build.dmg, works. the current version on sourceforge throws an error still.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/1989

**Comment by 2BeeOrNot** [comment]
1.3.5-beta.6 solves the problem with the addition of the English .mo files. Thank you.
