### ISSUE TITLE
Grouping on Budget Setup

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#2391]
**Is your feature request related to a problem? Please describe.**
As the years pass by, the Budget Setup gets longer.

**Describe the solution you'd like**
Have the 'month' budgets group on the annual year budget in similar way that Shares group under the portfolio. This can be done as month budgets have the year YYYY-MM.  If someone creates a monthly budget without a year, create a dummy one.

**Describe alternatives you've considered**
Have a 'favorite' option like the account to I can hide old budget setups like non-favorite accounts.

<img width="158" alt="Screenshot 2020-04-17 at 12 09 09 AM" src="https://user-images.githubusercontent.com/44472390/79501966-00542c00-8040-11ea-9844-f80206ada15e.png">

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/79515796-49ad7700-8052-11ea-8f8e-82295ac68a22.png)

**Comment by vomikan** [comment]
In case if this changes would be applied by default budget entries grouping by year.

![image](https://user-images.githubusercontent.com/6836805/79554652-08938200-80a7-11ea-884a-454b801e669b.png)

![image](https://user-images.githubusercontent.com/6836805/79554732-282aaa80-80a7-11ea-93ea-6940327608f4.png)

**Comment by siowena** [comment]
Cool, I like 3.

**Comment by vomikan** [comment]
@siowena You can use this feature if download last build

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32247101/job/3e7v00sw15e51krg/artifacts
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32247101/job/bb1am5fo2f9x5d4w/artifacts
