### ISSUE TITLE
Transaction colour

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2392]
![Screenshot_20200418-150725~2](https://user-images.githubusercontent.com/6836805/79637266-9c884b00-8186-11ea-8b5e-3abbd020e80d.png)

**Comment by vomikan** [comment]
Enough for a start.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/80209774-583ff380-863b-11ea-8b5b-646d3a7f76eb.png)

**Comment by whalley** [comment]
This can be closed now, the colors are displayed correctly.
