### ISSUE TITLE
Build instractions for MAC

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2406]
Build instractions are outdated.

https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#macos-with-homebrew

see https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.5/.travis.yml#L101

- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by whalley** [comment]
Assign this to me please, I'll have a look at it when I get time.

**Comment by vomikan** [comment]
I bereave You can assign yourself.
![image](https://user-images.githubusercontent.com/6836805/103939360-b31f6980-513c-11eb-9dc1-3f3c9c18a0b3.png)
Please feel free to ask for help if something goes wrong.

**Comment by vomikan** [comment]
Pay attention to this project. This is a pure experiment. You can add the file there.
https://github.com/moneymanagerex/mmex.doc

**Comment by whalley** [comment]
Updated build guide - https://github.com/moneymanagerex/moneymanagerex/pull/3580/commits/4c65a0b804eaa6e18996655e5d35647fbea8b933

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/pulls
