### ISSUE TITLE
wxRichToolTip transparent in MAC

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2407]
![image](https://user-images.githubusercontent.com/6836805/80031170-fe7fe200-84f1-11ea-8e1a-5a9c9b2cfd8c.png)

- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by vomikan** [comment]
https://docs.wxwidgets.org/trunk/classwx_rich_tool_tip.html
https://docs.wxwidgets.org/trunk/classwx_rich_tool_tip.html#abc2ac6aff7ca4404622b8e5a24a7d6df

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=23&t=47088

**Comment by vomikan** [comment]
similar issue https://github.com/moneymanagerex/moneymanagerex/issues/1142

**Comment by whalley** [comment]
Tested on 1.3.6 MacOS. Tooltips appear as expected with with correct background and are not transparent. Suggest we close.
