### ISSUE TITLE
Minor problem with compiling 1.3.5 and Curl V7.69.1

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#2409]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.5
  - [ ] 1.2.x
  - [ ] 1.1 or older

Just downloaded the source of 1.3.5 branch and it looks like the changes made to CMakelists in commit fix(up): +curl -mongoose cf3d5bc7cb12ec0ca1ac4fd1b088f6ff1f49fb1f
have gone missing as I now get the following error

-- Found CURL: D:/Projects/curl-7.69.1/lib/libcurl.lib (found version "7.69.1") found components: libcurl
CMake Error at CMakeLists.txt:318 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES can not be used on an ALIAS target.

The Curl dependency check in CMakelists contains the old version of checking..
# --------- curl dependency ---------
FIND_PACKAGE(CURL QUIET COMPONENTS libcurl CONFIG)
IF(CURL_FOUND)
    MESSAGE(STATUS "Found CURL: ${CURL_LIBRARIES} (found version \"${CURL_VERSION}\")")
    SET(CURL_VERSION_STRING ${CURL_VERSION})
ELSE()
    FIND_PACKAGE(CURL REQUIRED COMPONENTS libcurl MODULE)
    ADD_LIBRARY(CURL INTERFACE)
    TARGET_INCLUDE_DIRECTORIES(CURL INTERFACE ${CURL_INCLUDE_DIRS})
    TARGET_LINK_LIBRARIES(CURL INTERFACE ${CURL_LIBRARIES})
    ADD_LIBRARY(CURL::libcurl ALIAS CURL)
ENDIF()
IF(WIN32 AND CURL_LIBRARIES MATCHES "${CMAKE_STATIC_LIBRARY_SUFFIX}$")
    SET_TARGET_PROPERTIES(CURL::libcurl PROPERTIES INTERFACE_COMPILE_DEFINITIONS CURL_STATICLIB)
ENDIF()

Replacing the above with the updated curl check in cf3d5bc7 solves the problem

**Comment by vomikan** [comment]
Could you push a commit regarding this changes or upload a diff file?

**Comment by grumpy235** [comment]
Would love to but my knowledge and confidence using GIT is almost zero so I think it would be best if I leave well alone. I was trying to work out how your cf3d5bc commit went missing as it was pretty large and got totally lost. I was not sure if the apparent removal of cf3d5bc was intentional as it hits quite a few bits of code

**Comment by grumpy235** [comment]
Looks like macos test10 577b319f79a60dd2816e5462fd550fff1806fd1d replaced the new check with the old

**Comment by vomikan** [comment]
Thank you. I'll revert the changes. On MAC some troubles with gettext. It has been fixed by install gettext from sources. Possible some errors was regarding curl.

**Comment by grumpy235** [comment]
Keep up the good work - looks like you are wearing a MAC hat as well as Windows now

**Comment by vomikan** [comment]
Sometimes I use my wife’s MAC air.
It’s not very customary to use it and I don’t know any development tools for that platform.
I can only come across a bug and fix its presence.
Next, I try to guess the decision on the base of the Windows platform.
This is not very effective.
