### ISSUE TITLE
Downloading updates

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#2412]
I receive an email telling me there is a new version namely 1.3.4 I try to download it but the screen comes up with 'Oh no! Some styles failed to load'. This happens every time. I read all the different things going on, fine for geeks but the basics seem to be overlooked. Every time I open up maneymanager now it tells me there is a new version, but try and get it!!!!

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Hello.

First of all the following ling is OK for download the app:
https://sourceforge.net/projects/moneymanagerex/files/v1.3.4/
At start it may be the following window appears:
![image](https://user-images.githubusercontent.com/6836805/80228200-68fe6280-8657-11ea-8fe8-b64f60501bc2.png)
If you do not want to see it every time at mmex start thange the following settings:
![image](https://user-images.githubusercontent.com/6836805/80228384-a95de080-8657-11ea-9af6-8e5c6e7ed588.png)

**Comment by Speigy** [comment]
Tried that, in fact my seeting was already 'Stable' Clicking on the link took me to the same page as I mentioned before?

**Comment by vomikan** [comment]
could you show about dialogue or in main menu. (Help - About)?

**Comment by Speigy** [comment]
About page as requested.
![MMEXAbout](https://user-images.githubusercontent.com/39367770/80805881-140ba080-8bb1-11ea-9442-b8cce0342783.jpg)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2430
