### ISSUE TITLE
Webapp autostart memory leaks

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2413]
in case if after app started and any transaction available in WebApp the following code would be reached. On mmex close:
```
Detected memory leaks!
Dumping objects ->
{477159} normal block at 0x000002410A532240, 16 bytes long.
 Data: <  u A           > A0 0F 75 0A 41 02 00 00 00 00 00 00 00 00 00 00 
{477158} normal block at 0x000002410A750FA0, 72 bytes long.
 Data: <Content-Type: mu> 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 6D 75 
{473435} normal block at 0x000002410A531020, 16 bytes long.
 Data: <  u A           > 00 13 75 0A 41 02 00 00 00 00 00 00 00 00 00 00 
{473434} normal block at 0x000002410A751300, 72 bytes long.
 Data: <Content-Type: mu> 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 6D 75 
{471374} normal block at 0x000002410A530FD0, 16 bytes long.
 Data: <0"u A           > 30 22 75 0A 41 02 00 00 00 00 00 00 00 00 00 00 
{471373} normal block at 0x000002410A752230, 72 bytes long.
 Data: <Content-Type: mu> 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 6D 75 
Object dump complete.
The program '[22760] mmex.exe' has exited with code 0 (0x0).

```

If this dialogue started manually everything is OK.

-  Check MMEX version
  - [x] 1.3.x

```
void mmGUIFrame::OnAutoRepeatTransactionsTimer(wxTimerEvent& /*event*/)
{
    //WebApp check
    if (mmWebApp::WebApp_CheckEnabled())
    {
        if (mmWebApp::WebApp_CheckGuid() && mmWebApp::WebApp_CheckApiVersion())
        {
            mmWebApp::WebApp_UpdateAccount();
            mmWebApp::WebApp_UpdatePayee();
            mmWebApp::WebApp_UpdateCategory();

            mmWebApp::WebTranVector dummy;
            if (mmWebApp::WebApp_DownloadNewTransaction(dummy, true) == CURLE_OK)
            {
                mmWebAppDialog dlg(this);
                dlg.ShowModal();
                if (dlg.getRefreshRequested())
                    refreshPanelData();
            }
        }
    }
```

**Comment by vomikan** [comment]
In case if some transaction imported Detected memory leaks!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.5/src/util.cpp#L811

**Comment by gabriele-v** [comment]
Keep it open because ideally we would like to download automatically again, I'll have a look

**Comment by vomikan** [comment]
you can revert https://github.com/moneymanagerex/moneymanagerex/commit/1f651e4eeadc7a8cb2c07c68ff63494a452aa68d

Should work. But I'll prefer no automatically opened windoe but some icon like a lamp.
Similarly, the news works.

Or something like "in progress" should be added to lock the main app window to avoid start any other dialogues.

**Comment by gabriele-v** [comment]
I have an idea, I'll add it tomorrow

**Comment by vomikan** [comment]
One more reason to avoid auto started dialogues by timer:
At the same time Recurring transactions may be  activaated.

**Comment by gabriele-v** [comment]
Mmhhh yeah but they are both useful, we just need to coordinate them

**Comment by gabriele-v** [comment]
@tccadam if you want to test you have the artifacts here:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32711750/job/v0xh1oqkc6mao997/artifacts

**Comment by tccadam** [comment]
Thanks @gabriele-v ! it works!
