### ISSUE TITLE
Version 1.3.4 does not start on MacOS Catalina

### ISSUE THREAD

**Issue by michalkoza** [moneymanagerex/moneymanagerex#2415]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
Version 1.3.4 does not start on MacOS Catalina
![Screenshot 2020-04-24 at 23 35 58](https://user-images.githubusercontent.com/2995498/80259041-f906d100-8684-11ea-8559-0383a77f3f86.jpg)

**Comment by michalkoza** [comment]
![Screenshot 2020-04-24 at 23 44 03](https://user-images.githubusercontent.com/2995498/80259276-834f3500-8685-11ea-86eb-7f835a30c4e1.jpg)

**Comment by vomikan** [comment]
Is this huck implemened?
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146

**Comment by vomikan** [comment]
https://sourceforge.net/projects/moneymanagerex/files/v1.3.4/
last release

**Comment by michalkoza** [comment]
> Is this huck implemened?
> https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146

Thank you! It works. But it seems the `sudo` is not needed there
