### ISSUE TITLE
Transaction Filter does not open

### ISSUE THREAD

**Issue by Eos1988** [moneymanagerex/moneymanagerex#2417]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

When clicking on the button "Transaction Filter" nothing happens: it is supposed to open a PopUp showing the usable filters (in the previous version it worked).
![Transaction Filter not working](https://user-images.githubusercontent.com/64303236/80274261-69d7d880-86d9-11ea-84ea-a76519aeaf7f.png)

**Comment by vomikan** [comment]
#2238

**Comment by omalleypat** [comment]
confirmed

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/80302412-901d7700-87b2-11ea-8058-d263c18433ac.png)
