### ISSUE TITLE
Payee wrong autofill 

### ISSUE THREAD

**Issue by ghost** [moneymanagerex/moneymanagerex#2418]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

When inserting a new Transaction, during the compilation of the field Payee, the autofill dos not work properly. If there is a payee (ex.: "STA") whose name is composed of the initial letters of another payee (ex.: "Stazione di servizio"), when you start writing the longer payee, the autofill recognized the shorter payee, moving automatically the cursor to the beginning of the field and preventing you from writing the longer payee correctly (see attached compressed video)
[Payee autofill.zip](https://github.com/moneymanagerex/moneymanagerex/files/4532603/Payee.autofill.zip)
.

**Comment by vomikan** [comment]
How to make a video like that?

**Comment by vomikan** [comment]
The bug confirmed. Thank you for your report.

Workaround is to press arrow down button.
![image](https://user-images.githubusercontent.com/6836805/80276017-276cc680-86ee-11ea-852f-2273e144cb1b.png)

**Comment by Eos1988** [comment]
> How to make a video like that?

Using Grab App with macOs. There is a button to register a selection of the screen.

**Comment by Eos1988** [comment]
> The bug confirmed. Thank you for your report.
> 
> Workaround is to press arrow down button.
> ![image](https://user-images.githubusercontent.com/6836805/80276017-276cc680-86ee-11ea-852f-2273e144cb1b.png)

The workaround works, except that it is not possible to select items in the appearing list using the arrows: you have to use the muse to click the desired item.

**Comment by vomikan** [comment]
>The workaround works, except that it is not possible to select items in the appearing list using the arrows: you have to use the muse to click the desired item.

The same for me.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1116

**Comment by whalley** [comment]
Whilst the original text entry issue is not fully fixed the workaround has been further improved. As the user types text into the MacOS combobox the popup will automatically appear making selection of match entries much clearer. 

As the original poster no longer exists on Github to consult I'm going to close this as the workaround seems very usable for this edge condition.
