### ISSUE TITLE
JS Interpreter not working

### ISSUE THREAD

**Issue by andizero** [moneymanagerex/moneymanagerex#2419]
Javascript Elements are not recognised in general reports templates in version 1.3.4
In V1.3.3 it’s working fine with same DB-file

- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Could you export any report for tests on my side?

**Comment by andizero** [comment]
[2_0_Kategorien.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/4532963/2_0_Kategorien.grm.zip)

Did you mean this way?
It's a report i downloaded from the forum with small changes in SQL

**Comment by vomikan** [comment]
That sample (running on Windows v1.3.5)

![image](https://user-images.githubusercontent.com/6836805/80281739-f0aaa680-8715-11ea-9778-203dd793933b.png)

**Comment by andizero** [comment]
three times same sample-db:

V1.3.3
<img width="1250" alt="V1 3 3" src="https://user-images.githubusercontent.com/64307367/80282611-b1c72180-8712-11ea-8c90-61470236c201.png">
V1.3.4
<img width="1291" alt="V1 3 4" src="https://user-images.githubusercontent.com/64307367/80282621-bb508980-8712-11ea-979d-f908f016b991.png">
V1.3.5beta-1
<img width="790" alt="V1 3 5-beta1" src="https://user-images.githubusercontent.com/64307367/80282628-c2779780-8712-11ea-919b-44d2c2fd0271.png">

**Comment by vomikan** [comment]
v1.3.5-beta is using js on home page. How it looks?

**Comment by vomikan** [comment]
Please add more details by main menu Help - Bug report.

**Comment by vomikan** [comment]
For v1.3.5 important notes!
newChart.js and master.css are stored in Virtual File System.
Path should have the following prefix:  "memory:"
![image](https://user-images.githubusercontent.com/6836805/80284074-d5936300-8724-11ea-98cb-4a2ec8ea7511.png)

![image](https://user-images.githubusercontent.com/6836805/80284087-f3f95e80-8724-11ea-9876-9ceb442f3db4.png)

**Comment by vomikan** [comment]
for v1.3.4 js is working seems ChartNew.js version is incorrect.
Please download https://sourceforge.net/projects/moneymanagerex/files/v1.3.5-beta.1/ zip for windows and extract proper file from there.

**Comment by andizero** [comment]
Homepage is working fine on 1.3.4 and 1.3.5
Replaced ChartNew.js from 1.3.3, 1.3.5 mac beta and 1.3.5 win-portable-beta -> no effect
How can i provide more information? Is this right place or should i change to slack as mentioned in BugReport-menu?

**Comment by vomikan** [comment]
In case if Home page is working - everything is OK with CnartNew.js
Path should have the following prefix:  "memory:"!!! See my post above.
