### ISSUE TITLE
Unable to install new version

### ISSUE THREAD

**Issue by Marul1** [moneymanagerex/moneymanagerex#2420]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
I tried to install the new version, but after dragging the icon to Applications, a window opens telling that the file is corrupt.

**Comment by Marul1** [comment]
“mmex” is damaged and can’t be opened. You should move it to the Bin.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2374

**Comment by vomikan** [comment]
run it in console
```xattr -rd com.apple.quarantine /Applications/mmex.app```

**Comment by Marul1** [comment]
Vomikan, I am not a programmer. Can you walk me through? Thank you.

**Comment by vomikan** [comment]
press command + break
type "terminal"
command + С on ```xattr -rd com.apple.quarantine /Applications/mmex.app```
Command + V in the Terminal and Enter

**Comment by Marul1** [comment]
Thank you. Problem resolved.

**Comment by benquan** [comment]
This should not be closed as the workaround is not the definitive solution.

**Comment by BelaMiles** [comment]
Hi, same issue here, on both my Macs. One of my Mac runs Mojave, everything worked fine until today (I think I was on previous version, has it been updated without I realized it was?), now crashes on opening. The other Mac runs Catalina, and I have never been able to instal Mmex on it, it proposes me to put it to the bin. I tried the Terminal command, didn't work... Please help! B.

**Comment by BelaMiles** [comment]
Edit: I could salve the problem on my recent MacBook Pro running Catalina, with the Terminal quarantine thing, but it won't load anymore on my iMac running Mojave...
