### ISSUE TITLE
Manual update of Stock Price appears not to work 1.3.4/1.3.5

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#2421]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Trying to add a stock price by hand, I right click on stock and go to "Edit Stock Investment" and get the following...
![Capture](https://user-images.githubusercontent.com/24897056/80284595-6c592300-8717-11ea-8604-f0041e927d46.PNG)
Price date and Price on the righthand side are greyed out and not active. They can be activated by hitting Add. Changing the date and price and then hitting Add again gets the Stock History updated but Current price stays the same..
![Capture1](https://user-images.githubusercontent.com/24897056/80284695-f608f080-8717-11ea-9f97-d70f6b772d9d.PNG)
Hitting save then changes price just added to the previous price in Stock History
![Capture2](https://user-images.githubusercontent.com/24897056/80284751-41bb9a00-8718-11ea-9d64-93eae63b0147.PNG)
Deleting a price screws things up as well.
Am I doing something wrong or is this a bug ?

**Comment by vomikan** [comment]
Let's figure it out. On the right side we have a story.
The current price is indicated on the left, it can be any.
I easily added a history entry manually. Highlighted in yellow.

![image](https://user-images.githubusercontent.com/6836805/80292671-9e42a780-8760-11ea-9e11-0057346371d1.png)

Current share price it just  a value for a moment when "Refresh Stock Prices from Yahoo" button pressed.

![image](https://user-images.githubusercontent.com/6836805/80292735-5a9c6d80-8761-11ea-9ddd-50124fc3a168.png)

**Comment by grumpy235** [comment]
I am adding stock prices by hand not via any server. This works OK on 1.3.3 by updating the date and current price and it works fine in 1.4 by clicking on the little wheel which was one of your improvements over 1.3.3 logic I think.
In 1.3.4/5 surely "Price Date" and "Price" should be active when the window comes up, I then change the date and price, hit "Add", that updates the History and "Save" will do the recalculation. I assume that is the logic under 1.4 except there I have to hit the "wheel" button to get the option to add or delete a price rather than have them in the clear on the first panel.
