### ISSUE TITLE
Default Payee in Options/Others not working

### ISSUE THREAD

**Issue by alcor-nucleus** [moneymanagerex/moneymanagerex#2426]
When I select Default Payee: 'Last Used' and Default Category: 'None' in the Options/Others dialog, then Payee is empty when creating a new transation (should be pre-filled with the last used payee).
However, when I select Default Payee: 'Last Used' together with Default Category: 'Last used for payee', then it starts working as expected (payee gets pre-filled with the last one).
This used to work well in MMEX 1.3.3.

<hr>Version: 1.3.4<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.2 (wxMSW 10.0)<br>
 • wxSQLite3 4.5.1 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.59.0-DEV WinSSL<br>
<br>
Build: Apr 22 2020 17:43:46 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 17134), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by gabriele-v** [comment]
Fixed
