### ISSUE TITLE
1.3.4 drop down filters not working (month, year this, last etc)

### ISSUE THREAD

**Issue by marty008** [moneymanagerex/moneymanagerex#2427]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Screenshot please. What kind of drop down filters you are talking about?

**Comment by marty008** [comment]
v 1.3.4 on win 64
View transactions - all options - seems as if when calculating end point of display it defaults to all future transactions rather than end of month or year as implied in drop down selection

**Comment by vomikan** [comment]
This?

![image](https://user-images.githubusercontent.com/6836805/80545607-7a7b9d80-89bc-11ea-8cbe-5f4ac347efd8.png)

**Comment by vomikan** [comment]
#2494
