### ISSUE TITLE
Expenses report with multiple currencies adding up only in base currency.

### ISSUE THREAD

**Issue by AlexVanDutch** [moneymanagerex/moneymanagerex#2433]
Dear Support,

I've just downloaded and installed the latest version. I have used this program for the last 3 years without issues.

I use multiple currencies and the totals are always in USD which is my base currency. Which is perfect. However since I've installed to the latest version it does the expenses totals in USD but keeping the format of Vietnamese Dong. So for example if I spend 23.000 VND (1 USD) the totals will show an expense of 23.000 USD. Which is obviously not the case. 

I've tried to update all online currencies and it fixed the problem with the income money. But not for the expenses.

Please help. I love your software.

- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
I can't reproduce this issue.
Please attach a screenshot with sample with the problem.

**Comment by AlexVanDutch** [comment]
Hello and thank you for the reply. So as you can see in the Income vs Expenses reports the income in USD is correct. The expenses includes transactions in VND (Vietnamese Dong). But the total should be in base currency as well (USD)
So the 37 645 732 should be instead about 1604 USD. You see what I mean now?

![EXPENSES](https://user-images.githubusercontent.com/64457067/80898489-32e37180-8d2e-11ea-8bfd-31062c56d034.png)
