### ISSUE TITLE
Field Names and Field Data seems to be mixed up in the database!! (see attachment)

### ISSUE THREAD

**Issue by RO289** [moneymanagerex/moneymanagerex#2434]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
![image](https://user-images.githubusercontent.com/64459272/80454943-25437b80-892b-11ea-8917-eeeb71da79ac.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2026

**Comment by gabriele-v** [comment]
There is a misunderstanding about the "due date" even in the code..

@vomikan @guanlisheng what we consider for "due date"? The next occurrence or the date when transaction is entered? Up to me due date should be next occurrence, but looking at the code looks like next occurrence is the "payment date" and transaction date is the "due date"

**Comment by gabriele-v** [comment]
Looking at this I think instead that it's by design to have it "swapped" in the code, so I think we should just swap the fields in billsdepositsdialog?

https://github.com/moneymanagerex/moneymanagerex/commit/e8352b21c621e43099654e345577cbdf16a306a0#diff-ada267969a6b6c2160b1fa8dbe81e0d6

**Comment by vomikan** [comment]
I have no ideas. I did not dig deep into this topic.
Intuitively, I imagined that one date is the actual charge, and the other is when you need to take care of the charge and register it in propet account.
