### ISSUE TITLE
Icon sizes restricted in MAC

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2442]
Icons size restricted
![Снимок экрана 2020-04-30 в 01 23 29](https://user-images.githubusercontent.com/6836805/80652810-6baaee80-8a81-11ea-9e3b-4cf9217168fc.png)

- Check OS
  - [ ] Windows
  - [x] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2425

**Comment by whalley** [comment]
Fixed.
