### ISSUE TITLE
Web app lost category and sub-category

### ISSUE THREAD

**Issue by sharkyiwc** [moneymanagerex/moneymanagerex#2443]
Hi,

After update from 1.3.3 to 1.3.4, when we use webapp, dropdown menu for category and sub-category is empty.

Thanks for your work

- Check OS
  - [X] Windows
  - [X] Linux 
-  Check MMEX version
  - [X] 1.3.4

**Comment by sharkyiwc** [comment]
Re,

I have try mmex-1.4.0-alpha.7-win64, it's same.
after Sync WebApp, in web page dropdown menu for category and sub-category is empty.
I restore 1.33 and it's back.

Thanks

**Comment by vomikan** [comment]
Screenshot please

**Comment by sharkyiwc** [comment]
Yes,
If you want to highlight that this is not a drop-down menu, OK
On the other hand in version 1.33, this completes automatically in category and sub- is filtre from first category selected.
And this function this loses as much as I do an upgrade.
Thanks

**Comment by sharkyiwc** [comment]
And is not browser history
Just change version, make a import webapp (=sync)

V1.33
![2020-04-30 19_51_36-Window133](https://user-images.githubusercontent.com/251279/80743483-4f5c8f80-8b1d-11ea-93d1-c0acd1cf14c4.png)

V1.34 and +
![2020-04-30 19_50_48-Window144](https://user-images.githubusercontent.com/251279/80743502-584d6100-8b1d-11ea-82d3-97afef232421.png)

**Comment by vomikan** [comment]
I am warking on this case right now.
Can't fix this case https://github.com/moneymanagerex/moneymanagerex/issues/2413

**Comment by vomikan** [comment]
Is't OK?
![image](https://user-images.githubusercontent.com/6836805/80757761-5c897680-8b3d-11ea-899a-5f80a22f4d32.png)

**Comment by vomikan** [comment]
This build should work fine
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32566162/job/l3v93ake7tb0evew/artifacts

**Comment by sharkyiwc** [comment]
Great!
And fast .... Thanks you

**Comment by sharkyiwc** [comment]
Hi,
I'm back after real test and with the version 1.3.5 B2 i have same problem.
I'm sorry for bad news

**Comment by vomikan** [comment]
Because last changes are not included there.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.3.5-beta.3

**Comment by sharkyiwc** [comment]
Hi,

I'm sorry I misunderstood, I thought this version contained the patch.
I also tested this new beta3 version : the patch is still not understood
Thanks

> This build should work fine
> https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32566162/job/l3v93ake7tb0evew/artifacts

**Comment by vomikan** [comment]
The patch should be there.
Here is it:
https://github.com/moneymanagerex/moneymanagerex/commit/1f651e4eeadc7a8cb2c07c68ff63494a452aa68d#diff-b07dde858dcb661e22ee5b5727e7feaf

**Comment by gabriele-v** [comment]
I'm unable to reproduce the issue, which is the configuration of WebApp hosting (PHP, OS etc..)?

**Comment by sharkyiwc** [comment]
Hi,

I point out that it is only when I upgrade my current version 1.33 to a newer one that the problem this product.

I hosted webapp on my Synology
PHP Version 7.3.11
Linux 4.4.59+ #24922 SMP x86_64
Apache/2.4.39

In production, I'm using a win64-portable client under Win10 from a share of my Synology. (Updates are centralized)

I'm creating a test environment.
I copied my database and opened with the latest version 1.3.5 beta3 win64. While keeping the web version as is. Once this version is open, I lose the suggestions in the category and sub-category fields.

For the FR operation, I partially translated webapp into FR. I questioned my webapp FR translation. So I handed in the original English version to retest and confirm the scenario.

The problem is always present as soon as I upgrade to 1.34, 1.35 ...

I reopen my version 1.33 (lucky the database is not upgraded), I go back to webapp and the auto suggestion comes back.

Thank you.

**Comment by sharkyiwc** [comment]
I made a second test by moving on webapp on a host server.

Linux 3.10.0-1062.9.1.el7.x86_64
PHP Version 7.3.17

And the problem's gone.
???

**Comment by vomikan** [comment]
I can confirm this issue.
1.3.3
![image](https://user-images.githubusercontent.com/6836805/80921366-9d240280-8d7e-11ea-8d29-4e400b92cf0c.png)

1.3.5
![image](https://user-images.githubusercontent.com/6836805/80921432-13c10000-8d7f-11ea-9789-d7d10969a707.png)

Environments:
Windows 10 
VertrigoServ\Vertrigo.exe 2.58
(Packages:
Apache 2.4.38
PHP 5.6.40 / 7.1.26
MySQL 5.7.25
phpMyAdmin 4.8.5
SQLite 3.27.2
xDebug 2.6.1 / 2.5.5)

**Comment by vomikan** [comment]
error_code = 0, JSON seems OK
![image](https://user-images.githubusercontent.com/6836805/80922224-44576880-8d84-11ea-92ae-5f318362d6bf.png)

**Comment by vomikan** [comment]
No data in the table
![image](https://user-images.githubusercontent.com/6836805/80922539-81bcf580-8d86-11ea-9f92-53ad404ba5fd.png)

**Comment by vomikan** [comment]
The same file with 1.3.3 running
![image](https://user-images.githubusercontent.com/6836805/80922637-2a6b5500-8d87-11ea-99a8-67da10cd49eb.png)

**Comment by sharkyiwc** [comment]
I also confirm. Always present
Even if you change servers

**Comment by vomikan** [comment]
1.3.3
Money Manager Ex
MMEX использует следующие компоненты:
wxWidgets 3.1.0
SQLite3 3.14.1
wxSQLite3 3.4.0
Mongoose 6.5
Lua 5.2
Microsoft Visual Studio 1900

1.3.5
Version: 1.3.5-Beta.3
• Database version: 7 • (aes128cbc)
• Git commit: 6a1ca784 (2020-05-01) • Git branch: v1.3.5
MMEX is using the following support products:
• wxWidgets 3.1.3 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.58.0 WinSSL
Build on May 1 2020 17:44:32 with:
• CMake 3.12.18081601-MSVC_2
• MSBuild 15.9.21.664
• gettext 0.19.8.1
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27030.1
• Windows SDK 10.0.17763.0
Running on:
• Windows 10 (build 18363), 64-bit edition
• Russian (windows-1251)
• 1920x1080 32bit 96x96ppi

**Comment by gabriele-v** [comment]
Here it's working with PHP 7.1.26

I'd guess it's something between some specific PHP/Apache/Nginx version and RapidJSON or CURL?

**Comment by gabriele-v** [comment]
Are payees working? Problem it's just on categories and subcategories?

**Comment by sharkyiwc** [comment]
I have downgrad my host to PHP Version 7.1.33
and the problem is still there

And payees not working too !

**Comment by gabriele-v** [comment]
Could you put your hosting and Synology on the same PHP version (up to you which version)?
Just to understand if it's a PHP version issue or not

**Comment by sharkyiwc** [comment]
No, sorry, the host gives the supported versions and it's the same thing on the Synology.
host : 7.3.17
Synology 7.3.11

**Comment by sharkyiwc** [comment]
But without changing the host, only the Windows client doesn't work anymore.
From my point of view, if it works in one version, the PHP version should be out of the question!
Or I'm missing something.

**Comment by sharkyiwc** [comment]
I built a PHP 7.1.26 xampp like you.
I redid the test locally with version 1.35 b3
The problem is still there

Money Manager Ex
Version: 1.3.5-Beta.3
• Version base de données: 7 • (aes128cbc)
MMEX utilise les produits suivant:
• wxWidgets 3.1.3 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.59.0-DEV WinSSL
Compilé le May 1 2020 15:48:31 avec:
• CMake 3.16.2
• MSBuild 15.9.21.664
• gettext 0.19.8.1
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
• Windows 10 (build 18363), 64-bit edition
• 1920x1080 32bit 96x96ppi

**Comment by vomikan** [comment]
I've deleted all non latin named categories and it start working!

**Comment by gabriele-v** [comment]
Looks like on mine non latin categories are just not synced, but others are synced correctly

**Comment by vomikan** [comment]
1.3.3
![image](https://user-images.githubusercontent.com/6836805/80924011-6f938500-8d8f-11ea-8c2a-cff241e66847.png)

**Comment by gabriele-v** [comment]
Looks like the issue is in RapidJSON, I'm deeping into it

**Comment by gabriele-v** [comment]
@vomikan could you try to export as JSON something with Cyrillic characters?
From my tests also Export as JSON won't work for Cyrillic

**Comment by vomikan** [comment]
I think the trouble somewhere here:
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.3/src/webapp.cpp#L141

**Comment by gabriele-v** [comment]
Just for reference and keep bug updated, issue it's in RapidJSON here:
`json_writer.String(payee.PAYEENAME.c_str());`

I'm trying to find a solution with @vomikan

**Comment by vomikan** [comment]
```
        wxString s = category.CATEGNAME;
        wxLogDebug("You can do this: %s", s);
        wxLogDebug("Or this: %s", static_cast<const char*>(s.c_str()));
        wxLogDebug("And this: %s", static_cast<const char*>(s.mb_str()));
        wxLogDebug("Or this: %s", static_cast<const wchar_t*>(s.wc_str()));
```
Output:
```
You can do this: бакалея
Or this: бакалея
And this: бакалея
Or this: бакалея
You can do this: träflis
Or this: 
And this: 
Or this: träflis
```

**Comment by vomikan** [comment]
Seems working
```
buffer << wxString(json_buffer.GetString(), wxConvUTF8);
```
![image](https://user-images.githubusercontent.com/6836805/80962516-d9567200-8e15-11ea-9ed1-fabc51d1b19a.png)

**Comment by vomikan** [comment]
@gabriele-v  seems it's not rapidjson issue.

**Comment by gabriele-v** [comment]
> @gabriele-v  seems it's not rapidjson issue.
> 

I think they are two different issues probably: one was JSON not supporting UTF8, other WebApp not importing non-UTF8. I'll have a look at WebApp this evening

**Comment by vomikan** [comment]
Working! Congratulations to all of us.
![image](https://user-images.githubusercontent.com/6836805/80981089-23e5e780-8e32-11ea-8826-820a2d9f0e35.png)

**Comment by sharkyiwc** [comment]
Hi,

Thanks for your job!
