### ISSUE TITLE
Stock report doesn't show gain or loss

### ISSUE THREAD

**Issue by WillemSamyn** [moneymanagerex/moneymanagerex#2446]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
    - [x] Mac OSX
  
-  Check MMEX version
  - [x] 1.3.5.beta3-macos.dmg
 
Stock report doesn't show gain or loss.

**Comment by vomikan** [comment]
Screenshot please.

**Comment by WillemSamyn** [comment]
![Schermafbeelding 2020-05-02 om 12 07 34](https://user-images.githubusercontent.com/64684538/80861514-61e6de00-8c6f-11ea-81d2-483257c42663.jpg)

**Comment by vomikan** [comment]
In general it's working.
See the following example:
![image](https://user-images.githubusercontent.com/6836805/80865199-68398200-8c90-11ea-9830-2c93c494a5c7.png)
Stock prices should be updated manually by the following button:
![image](https://user-images.githubusercontent.com/6836805/80865271-d8e09e80-8c90-11ea-9a25-21b13f094c2a.png)

**Comment by WillemSamyn** [comment]
I keep using version 1.2.7, where it works perfect.

**Comment by WillemSamyn** [comment]
In version 1.2.7. it works fine. I keep using this version.



Met vriendelijke groeten,
Willem Samyn

2020-05-02 13:20:47 +0000 Nikolay <notifications@github.com> :

**Comment by WillemSamyn** [comment]
Hello Nokolay,

I have to excuse myself. Your MMEX is working correctly.
I entered the data of your posting, MTSS.ME as symbol, and pushing the
button I got the wright result immediately.
The reason why I have problems is because I only have ISIN-numbers of bonds
and shares, and I wrote those in the field 'Symbol'. But this way an upload
is not possible.
I don't know where to find the symbols that are expected. So I keep using
version 1.2.7. and I ad the current values manually.
If you could help me finding the correct symbol, I would appreciate it. I
give you an example : LU1165135440. Where do I find the symbol number that
works ?

Met vriendelijke groeten,
Willem Samyn


Op za 2 mei 2020 om 19:10 schreef Nikolay <notifications@github.com>:

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2259

**Comment by WillemSamyn** [comment]
That is how I work now. Using version 1.2.7. I look for stock update on Morningstar or Fundsquare and I manually add a new value. Version 1.2.7 gives me a correct stock report.

**Comment by vomikan** [comment]
```
#!/usr/bin/env python3

import sys
import time
import requests

if len(sys.argv) != 5:
    raise SyntaxError(sys.argv[0] + ' ISIN market fromDate toDate')

items = [(i[1], i[4]) for i in [l.split('|') for l in requests.get('http://tools.morningstar.es/es/util/searchfundbyname.aspx?ModuleId=69&LanguageId=es-ES&limit=100&q=' + sys.argv[1].lower()).text.split('\n')] if len(i) > 5 and (i[4] == '' or i[4] == sys.argv[2])]
code = items[0][0]
for i in items:
    if i[1] == sys.argv[2]:
        code = i[0]
        break

data = requests.get('http://tools.morningstar.es/api/rest.svc/timeseries_price/2nhcdckzon?id=' + code + '&currencyId=EUR&idtype=Morningstar&priceType=&frequency=daily&startDate=' + sys.argv[3] + '&endDate=' + sys.argv[4] + '&outputType=COMPACTJSON').json()
for i in data:
    print("{0}\t{1:9.6f}".format(time.strftime("%d/%m/%Y", time.gmtime(i[0] / 1000)), i[1]))

```
hist-morningstar.py LU1165135440 "" 2020-01-01 2020-05-01 > test.csv 

![image](https://user-images.githubusercontent.com/6836805/80914064-e316a180-8d51-11ea-8af0-448f4f0554f9.png)

![image](https://user-images.githubusercontent.com/6836805/80914079-06415100-8d52-11ea-92f7-223a33762181.png)

**Comment by vomikan** [comment]
The sample above created in 1.3.5-beta.
I've changed a bit py script.

**Comment by WillemSamyn** [comment]
Nikolay,

i can see you managed to make it work with ISIN symbols.
However, I am only a user of MMEX. The solution is too difficult for me to
understand. I don't know what to do with the script or how to use it.

Met vriendelijke groeten,
Willem Samyn


Op zo 3 mei 2020 om 14:25 schreef Nikolay <notifications@github.com>:

**Comment by vomikan** [comment]
I just showed the situation from all sides.
Because there is an interface with a morning star, I will develop rates downloading from different sources. But so far the functionality is not ready.
