### ISSUE TITLE
Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by FeDLviv** [moneymanagerex/moneymanagerex#2447]
Update OS (Ubuntu 18 -> Ubuntu 20), install MMEX (snap -> version 1.3.3):

When database file opening:
/home/........../mmex.mmb
An incorrect password given for an encrypted file 
or 
 Attempt to open a File that is not a database file

**Comment by vomikan** [comment]
Has the .mmb file been encrypted before?

**Comment by FeDLviv** [comment]
Yes, the database is password protected (menu -> tools -> database -> set password)

**Comment by vomikan** [comment]
I recommend to delete password in  Ubuntu previous version or on Windows platform. Then move mmb file to new Ubuntu then set password.

Try to open file in SQLite Browser. 

It is also possible that the integrity of the database is violated (file is not valid).

**Comment by FeDLviv** [comment]
> It is also possible that the integrity of the database is violated (file is not valid).

It works fine still on Windows (v1.4.0-alpha.7), the application previously worked on Ubuntu 18.04 (snap install mmex)

> I recommend to delete password in Ubuntu previous version 

Delete password -> Windows 8.1 application (v1.4.0-alpha.7).

Open DB -> Ubuntu 20.04 (snap install mmex -> 1.3.3):

> MMEX database error!

> MMEX database version 13 doesn't work with this MMEX version.

> Please upgrade MMEX to newer version.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2353

Download this file: downgrade_db_13_7_v3.zip
Extract it into any folder.
Run mmex 1.3.4. Click Yes regarding file from support.

**Comment by FeDLviv** [comment]
> Download this file: downgrade_db_13_7_v3.zip
+

> Extract it into any folder.
+

> Run mmex 1.3.3 (1.3.4 or 1.3.5). Click Yes regarding file from support.
+

File -> downgrade_db_13_7_v3.mmdbg not visible from MMEX :(

![imgonline-com-ua-2to1-QuHOJ6NgvAMl3K](https://user-images.githubusercontent.com/22416797/80918442-980a8780-8d6d-11ea-977a-f936e41cd5be.jpg)

**Comment by vomikan** [comment]
I have no ideas why it not working on Ubuntu 20.04

```
void dbUpgrade::SqlFileDebug(wxSQLite3Database * db)
{
    wxFileDialog fileDlgLoad(nullptr,_("Load debug file"),"","","MMDBG Files(*.mmdbg) | *.mmdbg", wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (fileDlgLoad.ShowModal() != wxID_OK)
        return;
```

**Comment by vomikan** [comment]
Workaround is to using  DB Browser for SQLite  https://sqlitebrowser.org/
Open you mmb file in SQLite Browser and apply content of downgrade_db_13_7_v3.mmdbg file as SQL

**Comment by vomikan** [comment]
https://stackoverflow.com/questions/18726754/wxfiledialog-always-returns-an-empty-string

**Comment by PMaff** [comment]
@FeDLviv did you try mmex 1.5.14 or mmex 1.5.15 with wxWidget 3.1.5 ?

**Comment by fpyshnyi** [comment]
@PMaff I didn't try MMEX (1.5.14 or 1.5.15) with wxWidget 3.1.5

**Comment by FeDLviv** [comment]
@PMaff I didn't try MMEX (1.5.14 or 1.5.15) with wxWidget 3.1.5

**Comment by whalley** [comment]
Can you try the build here https://app.circleci.com/pipelines/github/whalley/moneymanagerex/25/workflows/c24514c8-6aab-40a9-95d5-2a615c322fb0/jobs/29/artifacts

**Comment by whalley** [comment]
Closing as build is available. Feel free to re-open if not working.
