### ISSUE TITLE
Categories do not import when importing qif files

### ISSUE THREAD

**Issue by gmulhall** [moneymanagerex/moneymanagerex#2449]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.4
  - [ ] 1.2.x
  - [ ] 1.1 or older

I downloaded win 64 portable 1.3.4 and found that when importing data using a qif files the categories do not import. Other fields date, payee memo fields import OK. Went back to 1.3.3 and they import OK.

**Comment by gmulhall** [comment]
I've downloaded the portable 64bit Win version and this is still not resolved in that version. I've attached the test file I used. I've not tested any other version.
[test.zip](https://github.com/moneymanagerex/moneymanagerex/files/4739136/test.zip)

**Comment by vomikan** [comment]
@gmulhall 
I've imported it. What's wrong?

**Comment by gmulhall** [comment]
In my case the category is blank. See attached files.
![Problem 3](https://user-images.githubusercontent.com/64715676/83956543-a551ef00-a8a2-11ea-84c1-3149d5c75d19.jpg)
![Problem 2](https://user-images.githubusercontent.com/64715676/83956544-a6831c00-a8a2-11ea-9ba0-dbccae4866ca.jpg)
![Problem](https://user-images.githubusercontent.com/64715676/83956545-a71bb280-a8a2-11ea-8970-4b30099084ec.jpg)
![Version](https://user-images.githubusercontent.com/64715676/83956546-a71bb280-a8a2-11ea-9b58-026108e2f702.jpg)

**Comment by gmulhall** [comment]
In my case importing the category is not imported. See attached files.
![Problem 3](https://user-images.githubusercontent.com/64715676/83956650-b818f380-a8a3-11ea-9665-ca1dd451029b.jpg)
![Problem 2](https://user-images.githubusercontent.com/64715676/83956651-b94a2080-a8a3-11ea-94d5-026be3ee9c3f.jpg)
![Problem](https://user-images.githubusercontent.com/64715676/83956652-b9e2b700-a8a3-11ea-9d4d-374292046a63.jpg)
![Version](https://user-images.githubusercontent.com/64715676/83956653-b9e2b700-a8a3-11ea-9c0a-4429eaf9a85d.jpg)

**Comment by vomikan** [comment]
It's fixed.
Please upgrade to 1.3.5.
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33364416/job/opctwd6v5uubgwna/artifacts

**Comment by gmulhall** [comment]
THANKS !!
