### ISSUE TITLE
amount is 0 on import from WebApp 

### ISSUE THREAD

**Issue by andmau90** [moneymanagerex/moneymanagerex#2450]
import of transactions from webapp contains amount equal to 0 if it contains decimal point.
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
The same for me
![image](https://user-images.githubusercontent.com/6836805/80909598-26f9ae80-8d32-11ea-83bd-16aa8bf8ef24.png)

![image](https://user-images.githubusercontent.com/6836805/80909621-56a8b680-8d32-11ea-8801-f0147d2efe21.png)

**Comment by vomikan** [comment]
Why JSON value "Amount" is a string? It should be double (ID as well).
```
    "0": {
        "ID": "4",
        "Date": "2020-05-03",
        "Account": "GBP",
        "ToAccount": "None",
        "Status": "R",
        "Type": "Withdrawal",
        "Payee": "test",
        "Category": "Gifts",
        "SubCategory": "test",
        "Amount": "123.56",
        "Notes": "",
        "Attachments": ""
    },
```
Better to send cents and precision. For example:
not 123.45 or 123,45 but
12345 2
As result: value = 12345 / 10^2 = 123.45
