### ISSUE TITLE
Version 1.3.4 now adds Unknown subcategory to all imported webapp transactions

### ISSUE THREAD

**Issue by tccadam** [moneymanagerex/moneymanagerex#2451]
I upgraded to version 1.3.4 
now all the transactions that get imported from my webapp that do not have a subcategory get an "Unknown" subcategory automatically added and created in my mmex database.

**Comment by gabriele-v** [comment]
Maybe related to #2443, I've pushed a fix that should be available in next v1.3.5 (probably 1.3.5-beta.4)
Keeping the issue open as reminder.

**Comment by gabriele-v** [comment]
@tccadam could you try with this version?
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.3.5-beta.4 

If it's working we can close the issue.
Thanks

**Comment by tccadam** [comment]
I have not been able to test this because I uninstalled ver 1.3.3, rebooted, then installed v1.3.5-beta.4 but now none of my webapp transactions will download.  I'm wondering, does version 1.3.5-beta.4 require an https link to the webapp in the network options?

**Comment by vomikan** [comment]
That working for me
![image](https://user-images.githubusercontent.com/6836805/81198849-9c7fac00-8fca-11ea-8d7b-b44394225b1a.png)

**Comment by tccadam** [comment]
Hmm, it doesn't download transactions for me any more.  I've tried the Url field with "http://" "https://" and nothing before the domain. The only time anything happens is with the https, I then get a window that pops up about an SSL error, which makes sense. but with http:// or nothing it just doesn't import any transactions. 

Is there a log file somewhere that I can look at?  I've been using the same webapp for about 5 years now through several MMEx updates and it always worked without needing to change anything.

**Comment by gabriele-v** [comment]
In 1.3.5 it doesn't download transactions automatically because in some cases it makes MMEX crash or behaving strange, you need to go to import -> WebApp, try in this way

**Comment by tccadam** [comment]
Ah, ok, It works to download now when I do it manually, however, I still have my original problem where it is adding an "Unknown" subcategory when no subcategory was specified for the transaction in webapp. See picture below:

![image](https://user-images.githubusercontent.com/64762525/81203879-b054ef00-8f85-11ea-96a9-d72455a41f3f.png)

**Comment by gabriele-v** [comment]
Oh, got it.
You need to choose "None" in WebApp if you don't want "unknown".
It has been done like this because IE someone wants to use WebApp just as "quick reminder" so he can then properly add others data at the pc filtering on "unknown".

**Comment by tccadam** [comment]
Ok, I just tried it with 2 separate transactions and picked "None" for subcategory, both still created an "Unknown" subcategory when MMEx imported them.

**Comment by gabriele-v** [comment]
You were right, behaviour has been changed in https://github.com/moneymanagerex/moneymanagerex/commit/5bef9fccbc54a1af5e579dac2ab3132f6ea97b40#diff-858745589877368c3bf03c8569110cfc probably with a wrong copy/paste, I've reverted it and fix will be available in next version.

**Comment by gabriele-v** [comment]
Subcategory it's never "Unknown" because if categories are not managed, unknow category it's enough, so if it's none or empty in MMEX Desktop always mean "no subcategory"

**Comment by tccadam** [comment]
Thanks. I think I'm following and I think I agree. 
So I should keep an eye out for 1.3.5-beta.5 to test it?

**Comment by vomikan** [comment]
IMHO better to redesign the Category and Subcategory windows.
In case if the both field would be joined then more easy to enter transactions.

not
![image](https://user-images.githubusercontent.com/6836805/81208245-6b59a880-8fd7-11ea-8012-9b1b8d585f9b.png)

but
![image](https://user-images.githubusercontent.com/6836805/81208292-7c0a1e80-8fd7-11ea-9ebf-9807fd70df2a.png)

**Comment by gabriele-v** [comment]
Yeah, but in that way it will be tricky to manage autocomplete and what if you have a category that has the colon inside?

**Comment by vomikan** [comment]
The colon should be prohibited during typing or validation.

**Comment by gabriele-v** [comment]
> Thanks. I think I'm following and I think I agree.
> So I should keep an eye out for 1.3.5-beta.5 to test it?

Yep, otherwise you can manually download 1.3.5-beta.4 (x64) including fix here:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32693822/job/3ddbopgg8tfj43eo/artifacts

**Comment by vomikan** [comment]
Usually, as soon as I put a tag and make a release, an error message appears immediately.
But when I wait, nothing happens. Amazing.

**Comment by gabriele-v** [comment]
> The colon should be prohibited during typing or validation.

Probably you are right, because it's a "bug" of desktop version too, because it brings to something like this:
![image](https://user-images.githubusercontent.com/7106290/81208804-e61ec580-8fcf-11ea-9578-f5a165f22c72.png)

**Comment by vomikan** [comment]
It’s not difficult to ban it.

**Comment by gabriele-v** [comment]
Yep, just opened issue https://github.com/moneymanagerex/moneymanagerex/issues/2465

**Comment by vomikan** [comment]
On the other hand, there were requests regarding the division of categories into 3 levels. I think there are users who can use such a sophisticated way of entering categories.

**Comment by tccadam** [comment]
NICE! Thanks Gabriele-V, no more "Unknown" subcategory in the version I downloaded manually.
Any chance to have the option to automatically download webapp transactions again? You're right, it shouldn't be on by default if it is causing problems for some people but I loved that it would automatically check every time I opened it.

**Comment by gabriele-v** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2413 opened again for automatic download

**Comment by tccadam** [comment]
Thanks Gabriele, this is fantastic work! I'll donate again soon!  Love the program and love the new reporting features!
