### ISSUE TITLE
Money Manager não grava

### ISSUE THREAD

**Issue by MaryPrado** [moneymanagerex/moneymanagerex#2454]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ X ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

 MEU ARQUIVO NÃO GRAVA!!! faço todo o trabalho de cadastrar no money manager, ate dou um "salvar como" porem, ao abrir novamente, ele não salva nenhuma configuração. Por favor verifiquem o app para download. meu e-mail maryprado.design@gmail.com, aguardo contato.

**Comment by vomikan** [comment]
unfortunately I can't help with this issue.
