### ISSUE TITLE
v1.3.5-beta.4 - macOS - DMG Image Data Corrupted

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2459]
After licensing screen:
![MMEX Error](https://user-images.githubusercontent.com/63317977/81029250-3a03a000-8e52-11ea-9fb9-72a6eecffa8c.jpg)

**Comment by vomikan** [comment]
Updated

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.3.5-beta.4

Can't upload the file to SF for some technical reasons.

**Comment by 2BeeOrNot** [comment]
Thanks. It installs now.
