### ISSUE TITLE
Moneymanagerex ver 1.3.4 Simple search report cannot search 'notes' field

### ISSUE THREAD

**Issue by governflee** [moneymanagerex/moneymanagerex#2460]
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.

<hr>Version: 1.3.4<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.2 (wxMSW 10.0)<br>
 • wxSQLite3 4.5.1 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.59.0-DEV WinSSL<br>
<br>
Build: Apr 22 2020 17:43:46 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 18362), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2328

**Comment by governflee** [comment]
Is this where you want text? Sorry I am not familiar with these procedures. You are evidently aware of the issue. Adding a * at end of the search word is ok as a workaround. I imagine you would want to return the search facility to normal in due course. I will wait.
Thanks
Governflee

**Comment by vomikan** [comment]
It's not a bug but feature.
For example I want to find the word "Excursion" at the begin of Notes field, шт that case I would enter "Excursion*" to the search field. 
In case if * would be used automatically then not possible to find empty notes fields and as example above.
