### ISSUE TITLE
Bug : police in french

### ISSUE THREAD

**Issue by Ton558** [moneymanagerex/moneymanagerex#2462]
Hi,
On the home page there is a problem with the police for the French language, and also in certain reports.

![image](https://user-images.githubusercontent.com/63596191/81104241-831b2900-8f12-11ea-88c6-038f42d69537.png)

![image](https://user-images.githubusercontent.com/63596191/81104693-32580000-8f13-11ea-9fd2-cbb06c6d709b.png)

![image](https://user-images.githubusercontent.com/63596191/81104785-5287bf00-8f13-11ea-9fb6-53f75b774559.png)

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.5 beta 5
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by gabriele-v** [comment]
@vomikan UTF8 changes issue I guess 😞
I'll have a look tomorrow if I have time

**Comment by gabriele-v** [comment]
Fix sent, will be available in next version
