### ISSUE TITLE
Prohibit semicolon in categories

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#2465]
It should be prohibited to have semicolon in category/subcategory because it causes display problems like this:
![image](https://user-images.githubusercontent.com/7106290/81208934-1a928180-8fd0-11ea-9586-f9c794d1a74b.png)

WebApp and other imports should be updated as well.

**Comment by vomikan** [comment]
On the other hand, there were requests regarding the division of categories into 3 levels. I think there are users who can use such a sophisticated way of entering categories.

**Comment by gabriele-v** [comment]
That's really a "porkaround" I'd say :D

**Comment by vomikan** [comment]
This issue is more complex that it
