### ISSUE TITLE
Export to csv not working

### ISSUE THREAD

**Issue by gloggerS** [moneymanagerex/moneymanagerex#2466]
When trying to export to .csv, the program crashes... I'm using Windows and Version 1.3.4. Let me know, if you need further infos or can / cannot reproduce the issue.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
try 1.3.5-beta
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32696164/job/6tint4tsr1dsqfl6/artifacts
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/32696164/job/rui2j3o5v3autgnt/artifacts
