### ISSUE TITLE
Building mmex on Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2472]
Attempt to build from source code.

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by vomikan** [comment]
sudo apt-get update
sudo apt-get  install cmake 
sudo apt-get  install build-essential 
sudo apt-get  install gettext 
sudo apt-get install  git
sudo apt-get  install  ccache 
sudo apt-get install libwxgtk-webview3.0-gtk3-dev liblua5.3-dev libcurl4-openssl-dev
sudo apt-get install libgtk2.0-dev
apt-get clean

curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
tar -xvjf wxWidgets-*.tar.bz2
cd wxWidgets-3.1.3
./configure --disable-shared --enable-cxx11 --with-cxx=11 --without-libtiff
sudo make install
git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.3.4

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.3.5-beta.4

**Comment by vomikan** [comment]
To many bugs in 1.3.4. I don't recommend uprgade.
https://github.com/moneymanagerex/moneymanagerex/issues?q=is%3Aissue+is%3Aopen+label%3Amac

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/81459449-ad861400-91a8-11ea-95e5-49317da43944.png)

**Comment by XidRanReb** [comment]
> @XidRanReb I can't build a deb package with wx 3.1.3. Could you help with this #2472 ?

I remember troubleshooting an install error with wxWidgets-3.1.3. Did you have any problem with it ? 

Also, I have libwebkit2gtk-4.0-dev and libwxgtk3.0-gtk3-dev. It it helps...

I'm going to try to reproduce on a VM

**Comment by vomikan** [comment]
> I remember troubleshooting an install error with wxWidgets-3.1.3. Did you have any problem with it ?

wx 3.1.3 100% successfully installed.

But after mmex compilation, linker (/usr/bin/ld) errors like 'undefined reference to ...' stoped build process.

**Comment by vomikan** [comment]
FYI https://www.binarytides.com/install-wxwidgets-ubuntu/

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/81579471-e266b680-93b4-11ea-8c6a-c767e3c9329b.png)

**Comment by XidRanReb** [comment]
Hmm, I think I came across this. 

I've added the following repo :
> sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ focal universe'

Not sure if that was the solution :/

**Comment by vomikan** [comment]
Just started ./mmex in the build dir.

**Comment by XidRanReb** [comment]
Are all the solution used documented here ? 

I'll try a fresh install later.

**Comment by vomikan** [comment]
I've tried to put all steps here, Using this case I hope it would be possiblу to make fresh installation of mmex.

**Comment by vomikan** [comment]
Scenario №2
=================

sudo apt-get update
sudo apt-get install cmake checkinstall
sudo apt-get install build-essential
sudo apt-get install gettext
sudo apt-get install git
sudo apt-get install ccache
sudo apt-get install liblua5.3-dev libcurl4-openssl-dev

sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ focal universe'
apt-get update
sudo apt-get install libwxbase3.1-0-unofficial3 libwxbase3.1unofficial3-dev libwxgtk3.1-0-unofficial3
sudo apt-get install libwxgtk3.1unofficial3-dev libwxgtk-media3.1-0-unofficial3 libwxgtk-media3.1unofficial3-dev libwxgtk-webview3.1-0-unofficial3 libwxgtk-webview3.1unofficial3-dev 
sudo apt-get install libwxbase3.1-0-unofficial3-dbg libwxgtk3.1-0-unofficial3-dbg libwxgtk-webview3.1-0-unofficial3-dbg libwxgtk-media3.1-0-unofficial3-dbg wx3.1-i18n

git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.3.5
cd moneymanagerex
mkdir build && cd build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/81750766-c9dec500-94b6-11ea-83a6-b5c67411252c.png)

**Comment by XidRanReb** [comment]
Done a fresh install with following scenario : 

sudo apt-get update
sudo apt-get install curl
sudo apt-get install cmake checkinstall
sudo apt-get install build-essential
sudo apt-get install gettext
sudo apt-get install git
sudo apt-get install ccache
sudo apt-get install libwxgtk-webview3.0-gtk3-dev libwebkit2gtk-4.0-dev
sudo apt-get install liblua5.3-dev libcurl4-openssl-dev
sudo apt-get install libgtk2.0-dev

curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
tar -xvjf wxWidgets-*.tar.bz2
cd wxWidgets-3.1.3
mkdir gtk-build && cd gtk-build
../configure --disable-shared --enable-cxx11 --with-cxx=11 --without-libtiff --enable-webview --with-gtk=3 --enable-unicode --enable-intl
make install
cd ../..
git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.3.5
cd moneymanagerex
mkdir build && cd build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target install

----

for package : 
cmake --build . --target package
sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ focal universe'
apt-get update
sudo apt install ./mmex-[...].deb



is it ok for you ?

**Comment by vomikan** [comment]
This scenario is cool but it working too slow. 
I'll prefer to use scenario #2.

**Comment by XidRanReb** [comment]
Agreed that compilation time for wxWidgets is damn long. 

Does the error "Web extension not found" that you get has an impact ?

Really nice to get a working scenario. Now, I personnaly have to switch back my DB from 1.4.x beta to the 1.3.5 😄

**Comment by vomikan** [comment]
I've not found proper package for web-extensions.
I've just created symbolic link
> cd /usr/llb/x86 64-ltnux-qnu/wx
> sudo ln -s 3.0 3.1.3

**Comment by XidRanReb** [comment]
Just posting my updated scenario (even if it's not your favorite ;D) 
Working on a fresh 21.04 (but got problems with an updated linux from 20.04 to 21.04), but some reporting problem at the moment for 1.5.9

> sudo apt-get update
sudo apt-get install curl
sudo apt-get install cmake checkinstall
sudo apt-get install build-essential
sudo apt-get install gettext
sudo apt-get install git
sudo apt-get install ccache
sudo apt-get install libwxgtk-webview3.0-gtk3-dev libwebkit2gtk-4.0-dev
sudo apt-get install liblua5.3-dev libcurl4-openssl-dev
sudo apt-get install libgtk2.0-dev
>
> curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2
tar -xvjf wxWidgets-*.tar.bz2
cd wxWidgets-3.1.5
mkdir gtk-build && cd gtk-build
../configure --disable-shared --enable-cxx11 --with-cxx=11 --without-libtiff --enable-webview --with-gtk=3 --enable-unicode --enable-intl
make
sudo make install
cd ../..
git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.5.9
cd moneymanagerex
mkdir build && cd build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..
sudo cmake --build . --target install

**Comment by Zeit08** [comment]
Thank you @XidRanReb , I followed your instructions and built the 1.5.9 version on my MXLinux21 (Debian based) distro and it is working. The process took a bit less than 1 hour and I am wondering: do I have to do this procedure at every update? And how to update my my actual build to 1.5.10 for example?

**Comment by XidRanReb** [comment]
Hello @Zeit08 !
Yeah it's long, sadly, it's the one that never fails for me.

To install a new version, 2 scenarios :

# Scenario 1

Fastest, it *should* work : 
You go in the `moneymanagerex` folder created when cloning the repo with the line : 
>  git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.5.9

The you checkout the new version with : 
> git checkout v1.5.10

and continue with 
> cd build
> export MAKEFLAGS=-j4
> cmake -DCMAKE_BUILD_TYPE=Release ..
> sudo cmake --build . --target install

# Scenario 2
Longer but should also always work.
Delete the previously created `moneymanagerex` folder and redo the original process starting at the line : 
>  git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.5.10

*Notice the change of version at the end of the line*

---
Unless there is major change (like new version of wxWidgets required), it would be unnecessary to rebuild wxWidgets.

Also I do not have a test machine available now, so don't hesitate to ask, I may have missed something in my proc.

**Comment by vomikan** [comment]
Simple way for update:

cd moneymanagerex```
git pull
cd build
.....
```

Since the modules are not updated for a long time, you can not update them. But the themes have been updated recently, this requires a command:
```git submodule update themes ```

**Comment by XidRanReb** [comment]
> git pull

As my code clone on a tag, I don't think it would do anything. 
I think it's more reliable to 
> git checkout v1.5.10

It also ensures to stay on prod version.

**Comment by Zeit08** [comment]
It works.  A few questions: how do I know that also other components like wxWidgets have been updated so to do a full build? And why it does not let me update to v1.5.11 saying that it is not found? I just updated to v1.5.10 and it worked, but if I write v1.5.11 it doesn't.

**Comment by Timp58** [comment]
I have just followed the procedure that XidRanRed detailed on Pop OS in a VM and it worked great.  I have only a rudimentary knowledge of what is going on and it is the first time I have compiled a C programme ever!
Why can't these instructions replace the ones that are on the main site pages for compiling from source for Linux?
A second question is if we are able to build successfully build a package why not allow them to be uploaded for distribution to to the community?

**Comment by vomikan** [comment]
> I have just followed the procedure that XidRanRed detailed on Pop OS in a VM and it worked great. I have only a rudimentary knowledge of what is going on and it is the first time I have compiled a C programme ever!
> Why can't these instructions replace the ones that are on the main site pages for compiling from source for Linux?
> A second question is if we are able to build successfully build a package why not allow them to be uploaded for distribution to to the community?

Who forbids you to distribute the package?

**Comment by Timp58** [comment]
The question is not who but how? 
I am simply a user of the software who has been evaluating a possible change from Windows to Linux.  Since I had managed to follow the very helpful instructions given XidRaanRed I thought perhaps I could help others but I don't know how to distribute packages for Linux, I thought the contributors may appreciate some help?.  I am left with the impression that supporting Linux users is not  priority so I'll just leave it at that and not offer any further suggestions

**Comment by vomikan** [comment]
> The question is not who but how? I am simply a user of the software who has been evaluating a possible change from Windows to Linux. Since I had managed to follow the very helpful instructions given XidRaanRed I thought perhaps I could help others but I don't know how to distribute packages for Linux, I thought the contributors may appreciate some help?. I am left with the impression that supporting Linux users is not priority so I'll just leave it at that and not offer any further suggestions

Many years ago, I also switched completely to Linux. It was a very useful experience. It's been about 20 years. In general, little has changed in the Linux world. The team does not have enough resources and knowledge to provide support for the entire variety of Linux distributions. I believe that the support of the max program is the task of the community of a particular distribution. So, for example, do ArchLinux.

**Comment by Zeit08** [comment]
How to correctly uninstall this program that I have built from source using the guide provided by @XidRanReb ?

**Comment by vomikan** [comment]
make clean 
sudo make uninstall

**Comment by Zeit08** [comment]
> make clean sudo make uninstall

Thank Vomikan, but I am not sure how to execute those, it says "No rule to make target... Stop."

I opened terminal and just typed those commands, and I also tried executing those in cd wxWidgets-3.1.5 and cd moneymanagerex but it did not work.

**Comment by vomikan** [comment]
it should be typed exactly in the same directory where the mmex has been builded from scratch.
Somthing like ~/dev/mmex/build

**Comment by PMaff** [comment]
> Hmm, I think I came across this.
> 
> I've added the following repo :
> 
> > sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
> > sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ focal universe'
> 
> Not sure if that was the solution :/

Sorry to come back here: why do we need the codelite repos?
I started to work on a mmex compile in a fresh Ubuntu 20.04 VM and the compilation of wxWidget 3.1.5 and mmex 1.5.14 was all fine but when installing mmex_1.5.14-1~focal_amd64.deb that results in 
```
 mmex : Depends: wx3.1-i18n but it is not installable
E: Unable to correct problems, you have held broken packages.
```
@vomikan : are we missing something important here if we are not  setting up the codelite repos and installing `wx3.1-i18n` ?
Shouldn't all the stuff of wxWidget be installed when we compile wxWidget from source, make install and ldconfig so that we do not need the codelite stuff?
Information about  wx3.0-i18n says something about  "localization" https://howtoinstall.co/en/wx3.0-i18n .

**Comment by vomikan** [comment]
It seems a prebuild wx packages. Using this, you will reduce the build time of the entire project.

**Comment by PMaff** [comment]
> It seems a prebuild wx packages. Using this, you will reduce the build time of the entire project.

But his means we never really compile wxWidget from scratch but we use some other repos to install stuff for wxWidgets :-(
I do not like this idea and codelite somehow is unnecessary in this constellation.
It is not really a matter of mmex but rather one of wxWidget and someone should ask in the forums there.
Maybe I will start that.

It also means that all the official build descriptions that we have for mmex like 
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md
are missing important points. :-(
And it also explains, why installing mmex as deb or rpm fails in some cases.
