### ISSUE TITLE
Grouping character in amount

### ISSUE THREAD

**Issue by ramshake** [moneymanagerex/moneymanagerex#2473]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I upgraded to v1.3.5 beta 5 from v1.3.3. Grouping character is not displayed in the amount. I have 3 currencies in db and it is not displayed for all three currencies. Let me know if you need more info. Thanks

![1](https://user-images.githubusercontent.com/65050316/81457820-4f800f00-915d-11ea-8242-5a8e7bcb1a76.jpg)
![2](https://user-images.githubusercontent.com/65050316/81457819-4ee77880-915d-11ea-88ab-162785f7f02f.jpg)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2356

**Comment by vomikan** [comment]
This line of code is corresponding for concertation number to currency.
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.5/src/model/Model_Currency.cpp#L186

possible OS settings for numbers group separator is missing.

**Comment by ramshake** [comment]
My region is set to English (India). 

![1](https://user-images.githubusercontent.com/65050316/82136219-e0e02880-97d0-11ea-9b25-36264b44a38f.jpg)

I did some digging with OS region setting. When the region is set to English (India),  grouping character is not displayed.

I changed region to English (US), grouping character is displayed correctly.

![2](https://user-images.githubusercontent.com/65050316/82136250-243a9700-97d1-11ea-8c43-c367a00e3b0a.jpg)

In v1.3.3, grouping character for region English (India).

**Comment by vomikan** [comment]
I can reproduce this issue, but I have no ideas how to fix.

**Comment by reddyshyam** [comment]
Hi @vomikan,

Thanks for looking into this. I know I sound silly but in such cases, do you think it makes sense to give user the option of defining a pattern? 

For example, in our scenario, since system locale is not picked properly if user given an input option on the currency screen where he can enter his preference, lets say ##,##,##,##,##,##,##,###.## and the app picking this currency patten if user opts for it. 

What do you think?

**Comment by vomikan** [comment]
Your idea is full of common sense.
But such a change is difficult to implement.
At the moment, I am aiming to fix critical bugs.

**Comment by reddyshyam** [comment]
Hi @vomikan,

Absolutely@fixing critical bugs. I am living with it, just that it resurfaced thought of floating the idea. This can go back to back burner or even forgotten. 😄

**Comment by reddyshyam** [comment]
@vomikan, any chance this revisited please? Without the separator, its hard to know the value.

**Comment by vomikan** [comment]
I'll try to add regexp function like this one

![image](https://user-images.githubusercontent.com/6836805/112141054-e030d380-8be5-11eb-9196-3e82c7be5c67.png)

**Comment by reddyshyam** [comment]
Thanks @vomikan. Regexp is better all the way. You will make my day if this is resolved. 🙂🙏

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=1&t=48163&p=205248#p205248

**Comment by reddyshyam** [comment]
> https://forums.wxwidgets.org/viewtopic.php?f=1&t=48163&p=205248#p205248

Is that you who posted, @vomikan?

**Comment by vomikan** [comment]
> Is that you who posted, @vomikan?

Yep

**Comment by vomikan** [comment]
This piece of code fotmats Indian numbers,
```
    static wxString gs;
    if (gs.empty())
    {
        char buffer[255];
        GetLocaleInfoA(LOCALE_USER_DEFAULT, LOCALE_SGROUPING,
            buffer, sizeof(buffer));
        gs << buffer;
    }

    if (gs == "3;2;0" && fabs(value) >= 1000.00)
    {
        static std::map<int, wxString> gm;
        if (gm.empty()) {
            int g[] = { 13,11,9,7,5,3 };

            for (int i = 0; i < 13; i++) {
                auto *foo = std::find(std::begin(g), std::end(g), i);
                gm[i] = foo != std::end(g) ? os_group_separator() : "";
            }
        }

        wxString res;
        wxString t = wxString::Format("%d", static_cast<int>(fabs(value)));
        std::reverse(t.begin(), t.end());
        for (int i = 0 ; i < t.length(); i++)
        {
            auto test = t[i];
            res << gm[i] << t[i];
        }
        std::reverse(res.begin(), res.end());
        t = res;
        if (precision > 0) {
            float j;
            t << wxNumberFormatter::GetDecimalSeparator();
            wxString dec = wxString::Format("00000000%d", static_cast<int>(modf(fabs(value), &j) * pow(10, precision)));
            dec = dec.Mid(dec.length() - precision, precision);
            t << dec;
        }

        if (value < ROUNDING_ERROR_f32)
            t.Prepend("-");
        s = t;
    }
```

![image](https://user-images.githubusercontent.com/6836805/112199117-e1cabd80-8c1e-11eb-9bac-95df5894949b.png)

**Comment by reddyshyam** [comment]
Looks complex! 😨 

Or alternatively if not working for many locale, user can be given choice of regex ##,##,###.## sort of thing or user given choice to select from dropdown (3,3) or (2,3) which means ###,###,###,### or ##,##,##,### respectively. 

Or safely ignore this for now and I can remind in a month or two months time. 😁

**Comment by vomikan** [comment]
https://github.com/fmtlib/fmt

**Comment by reddyshyam** [comment]
> https://github.com/fmtlib/fmt

Looks promising. 👍

**Comment by vomikan** [comment]
For some reasons using fmt I can't format floating numbers only integer.
```
const wxString Model_Currency::toString(double value, const Data* currency, int precision)
{
    precision = (precision >= 0 ? precision : (currency ? log10(currency->SCALE) : 2));
    wxString s = fmt::format(std::locale("en_IN"), "{0:L}"
        , static_cast<int>(value))
        +
        wxString(fmt::format("{:.{}f}"
            , fabs(value - static_cast<int>(value))
            , precision)).Mid(1);
```

**Comment by reddyshyam** [comment]
> For some reasons using fmt I can't format floating numbers only integer.
> 
> ```
> const wxString Model_Currency::toString(double value, const Data* currency, int precision)
> {
>     precision = (precision >= 0 ? precision : (currency ? log10(currency->SCALE) : 2));
>     wxString s = fmt::format(std::locale("en_IN"), "{0:L}", static_cast<int>(value))
>         +
>         wxString(fmt::format("{:.{}f}"
>             , fabs(value - static_cast<int>(value))
>             , precision)).Mid(1);
> ```

which version of fmt are you using?

**Comment by vomikan** [comment]
this one
![image](https://user-images.githubusercontent.com/6836805/112828998-25974a00-9099-11eb-8d98-aff38551d966.png)

**Comment by reddyshyam** [comment]
> this one
> ![image](https://user-images.githubusercontent.com/6836805/112828998-25974a00-9099-11eb-8d98-aff38551d966.png)

Looks like you have the latest as v7.1.2 fixed few issue with floating point formating

7.1.2 - 2020-11-04
Fixed floating point formatting with large precision (#1976).

**Comment by vomikan** [comment]
I am using 7.1.3 

https://github.com/fmtlib/fmt/issues/2199

**Comment by vomikan** [comment]
https://github.com/fmtlib/fmt/issues/1392

**Comment by reddyshyam** [comment]
> I am using 7.1.3
> 
> [fmtlib/fmt#2199](https://github.com/fmtlib/fmt/issues/2199)

Just perfect! Won't get any easier. :(

Just for discussion sake, can we not just implement a dropdown for group per say with options, 

- locale (which would prefer system's locale), 
- [3] (if locale doesnot work then 3 number grouping all the way 123,456,789.00), 
- [2,3] (India as an example 12,34,56,789.00) and this list can be increased if anyone else complains of other locales. 

The above looks to me a simpler solution rather then spending so much of your time finding an ideal library which works on all OSes.

As I have said before, this can be ignored indefinitely or simply implement the above to give user the choice in case user lives in US but wants to do Indian accounting or vice versa. Depending on locale is not ideal always but again could be just a minorty like me.

**Comment by vomikan** [comment]
I agree that the currency settings are a feature that just allows you to get rid of the OS settings and use your own format. Probably, we need to remove the settings from the currencies and make the choice of locale in the options.

At the moment, we can integrate this library, and either pass the locale as a parameter, or make an item in the options.

**Comment by vomikan** [comment]
I've discovered that this code ``` fmt::format(std::locale("en_IN"), "{:.{}f}", value, precision);```  performance in 100 times less than this
```fmt::format("{:.{}f}", value, precision);```.
The last one in 4 time faster than this ```wxString::Format("%.2f", value);```

**Comment by reddyshyam** [comment]
> I've discovered that this code ` fmt::format(std::locale("en_IN"), "{:.{}f}", value, precision);` performance in 100 times less than this
> `fmt::format("{:.{}f}", value, precision);`.
> The last one in 4 time faster than this `wxString::Format("%.2f", value);`

I guess the performance is because the locale lib probing OS.  Are you still trying to find a solution which fits best for all?

**Comment by vomikan** [comment]
All this will take time.

**Comment by reddyshyam** [comment]
@vomikan, please put this on back burner. Not worth your time and even more so I feel bad.

**Comment by vomikan** [comment]
This will take time, not my involvement, but waiting for the universe to send us a simple and effective solution. Are you willing to wait forever? :)

**Comment by reddyshyam** [comment]
> This will take time, not my involvement, but waiting for the universe to send us a simple and effective solution. Are you willing to wait forever? :)

🤣  Absolutely@waiting forever. As such this amazing piece of application is satisfying so many including me. So few commas (,) here and there wouldnot matter 😜

**Comment by vomikan** [comment]
We are close to fixing this issue
![image](https://user-images.githubusercontent.com/6836805/116876978-fe96df80-ac25-11eb-8e12-be66fb8f84a7.png)

**Comment by vomikan** [comment]
How to affect the locales to number format:
af_ZA | 1223456.78 -> 1 223 456.78
am_ET | 1223456.78 -> 1,223,456.78
ar_AE | 1223456.78 -> 1,223,456.78
ar_BH | 1223456.78 -> 1,223,456.78
ar_DZ | 1223456.78 -> 1,223,456.78
ar_EG | 1223456.78 -> 1,223,456.78
ar_IQ | 1223456.78 -> 1,223,456.78
ar_JO | 1223456.78 -> 1,223,456.78
ar_KW | 1223456.78 -> 1,223,456.78
ar_LB | 1223456.78 -> 1,223,456.78
ar_LY | 1223456.78 -> 1,223,456.78
ar_MA | 1223456.78 -> 1,223,456.78
ar_OM | 1223456.78 -> 1,223,456.78
ar_QA | 1223456.78 -> 1,223,456.78
ar_SA | 1223456.78 -> 1,223,456.78
ar_SY | 1223456.78 -> 1,223,456.78
ar_TN | 1223456.78 -> 1,223,456.78
ar_YE | 1223456.78 -> 1,223,456.78
as_IN | 1223456.78 -> 12,23,456.78
ba_RU | 1223456.78 -> 1 223 456.78
be_BY | 1223456.78 -> 1 223 456.78
bg_BG | 1223456.78 -> 1 223 456.78
bn_BD | 1223456.78 -> 12,23,456.78
bn_IN | 1223456.78 -> 12,23,456.78
bo_CN | 1223456.78 -> 1,223,456.78
br_FR | 1223456.78 -> 1 223 456.78
ca_ES | 1223456.78 -> 1.223.456.78
co_FR | 1223456.78 -> 1 223 456.78
cs_CZ | 1223456.78 -> 1 223 456.78
cy_GB | 1223456.78 -> 1,223,456.78
da_DK | 1223456.78 -> 1.223.456.78
de_AT | 1223456.78 -> 1 223 456.78
de_CH | 1223456.78 -> 1’223’456.78
de_DE | 1223456.78 -> 1.223.456.78
de_LI | 1223456.78 -> 1’223’456.78
de_LU | 1223456.78 -> 1.223.456.78
dv_MV | 1223456.78 -> 1,223,456.78
el_GR | 1223456.78 -> 1.223.456.78
en_AU | 1223456.78 -> 1,223,456.78
en_BZ | 1223456.78 -> 1,223,456.78
en_CA | 1223456.78 -> 1,223,456.78
en_GB | 1223456.78 -> 1,223,456.78
en_IE | 1223456.78 -> 1,223,456.78
en_IN | 1223456.78 -> 12,23,456.78
en_JM | 1223456.78 -> 1,223,456.78
en_MY | 1223456.78 -> 1,223,456.78
en_NZ | 1223456.78 -> 1,223,456.78
en_PH | 1223456.78 -> 1,223,456.78
en_SG | 1223456.78 -> 1,223,456.78
en_TT | 1223456.78 -> 1,223,456.78
en_US | 1223456.78 -> 1,223,456.78
en_ZA | 1223456.78 -> 1 223 456.78
en_ZW | 1223456.78 -> 1,223,456.78
es_AR | 1223456.78 -> 1.223.456.78
es_BO | 1223456.78 -> 1.223.456.78
es_CL | 1223456.78 -> 1.223.456.78
es_CO | 1223456.78 -> 1.223.456.78
es_CR | 1223456.78 -> 1 223 456.78
es_DO | 1223456.78 -> 1,223,456.78
es_EC | 1223456.78 -> 1.223.456.78
es_ES | 1223456.78 -> 1.223.456.78
es_GT | 1223456.78 -> 1,223,456.78
es_HN | 1223456.78 -> 1,223,456.78
es_MX | 1223456.78 -> 1,223,456.78
es_NI | 1223456.78 -> 1,223,456.78
es_PA | 1223456.78 -> 1,223,456.78
es_PE | 1223456.78 -> 1,223,456.78
es_PR | 1223456.78 -> 1,223,456.78
es_PY | 1223456.78 -> 1.223.456.78
es_SV | 1223456.78 -> 1,223,456.78
es_US | 1223456.78 -> 1,223,456.78
es_UY | 1223456.78 -> 1.223.456.78
es_VE | 1223456.78 -> 1.223.456.78
et_EE | 1223456.78 -> 1 223 456.78
eu_ES | 1223456.78 -> 1.223.456.78
fa_IR | 1223456.78 -> 1,223,456.78
fi_FI | 1223456.78 -> 1 223 456.78
fo_FO | 1223456.78 -> 1.223.456.78
fr_BE | 1223456.78 -> 1.223.456.78
fr_CA | 1223456.78 -> 1 223 456.78
fr_CH | 1223456.78 -> 1 223 456.78
fr_FR | 1223456.78 -> 1 223 456.78
fr_LU | 1223456.78 -> 1.223.456.78
fr_MC | 1223456.78 -> 1 223 456.78
fy_NL | 1223456.78 -> 1.223.456.78
ga_IE | 1223456.78 -> 1,223,456.78
gd_GB | 1223456.78 -> 1,223,456.78
gl_ES | 1223456.78 -> 1.223.456.78
gu_IN | 1223456.78 -> 12,23,456.78
he_IL | 1223456.78 -> 1,223,456.78
hi_IN | 1223456.78 -> 12,23,456.78
hr_BA | 1223456.78 -> 1.223.456.78
hr_HR | 1223456.78 -> 1.223.456.78
hu_HU | 1223456.78 -> 1 223 456.78
hy_AM | 1223456.78 -> 1,223,456.78
id_ID | 1223456.78 -> 1.223.456.78
ig_NG | 1223456.78 -> 1,223,456.78
ii_CN | 1223456.78 -> 1,223,456.78
is_IS | 1223456.78 -> 1.223.456.78
it_CH | 1223456.78 -> 1’223’456.78
it_IT | 1223456.78 -> 1.223.456.78
ja_JP | 1223456.78 -> 1,223,456.78
ka_GE | 1223456.78 -> 1В223В456.78
kk_KZ | 1223456.78 -> 1В223В456.78
kl_GL | 1223456.78 -> 1.223.456.78
km_KH | 1223456.78 -> 1,223,456.78
kn_IN | 1223456.78 -> 1,223,456.78
ko_KR | 1223456.78 -> 1,223,456.78
ky_KG | 1223456.78 -> 1 223 456.78
lb_LU | 1223456.78 -> 1 223 456.78
lo_LA | 1223456.78 -> 1.223.456.78
lt_LT | 1223456.78 -> 1 223 456.78
lv_LV | 1223456.78 -> 1 223 456.78
mi_NZ | 1223456.78 -> 1,223,456.78
mk_MK | 1223456.78 -> 1.223.456.78
ml_IN | 1223456.78 -> 12,23,456.78
mn_MN | 1223456.78 -> 1,223,456.78
mr_IN | 1223456.78 -> 12,23,456.78
ms_BN | 1223456.78 -> 1.223.456.78
ms_MY | 1223456.78 -> 1,223,456.78
mt_MT | 1223456.78 -> 1,223,456.78
nb_NO | 1223456.78 -> 1 223 456.78
ne_NP | 1223456.78 -> 1,223,456.78
nl_BE | 1223456.78 -> 1.223.456.78
nl_NL | 1223456.78 -> 1.223.456.78
nn_NO | 1223456.78 -> 1 223 456.78
oc_FR | 1223456.78 -> 1 223 456.78
or_IN | 1223456.78 -> 12,23,456.78
pa_IN | 1223456.78 -> 12,23,456.78
pl_PL | 1223456.78 -> 1 223 456.78
ps_AF | 1223456.78 -> 1.223.456.78
pt_BR | 1223456.78 -> 1.223.456.78
pt_PT | 1223456.78 -> 1 223 456.78
rm_CH | 1223456.78 -> 1’223’456.78
ro_RO | 1223456.78 -> 1.223.456.78
ru_RU | 1223456.78 -> 1 223 456.78
rw_RW | 1223456.78 -> 1.223.456.78
sa_IN | 1223456.78 -> 12,23,456.78
se_FI | 1223456.78 -> 1 223 456.78
se_NO | 1223456.78 -> 1 223 456.78
se_SE | 1223456.78 -> 1 223 456.78
si_LK | 1223456.78 -> 1,223,456.78
sk_SK | 1223456.78 -> 1 223 456.78
sl_SI | 1223456.78 -> 1.223.456.78
sq_AL | 1223456.78 -> 1 223 456.78
sv_FI | 1223456.78 -> 1 223 456.78
sv_SE | 1223456.78 -> 1 223 456.78
sw_KE | 1223456.78 -> 1,223,456.78
ta_IN | 1223456.78 -> 12,23,456.78
te_IN | 1223456.78 -> 12,23,456.78
th_TH | 1223456.78 -> 1,223,456.78
tk_TM | 1223456.78 -> 1 223 456.78
tn_ZA | 1223456.78 -> 1 223 456.78
tr_TR | 1223456.78 -> 1.223.456.78
tt_RU | 1223456.78 -> 1 223 456.78
ug_CN | 1223456.78 -> 1,223,456.78
uk_UA | 1223456.78 -> 1 223 456.78
ur_PK | 1223456.78 -> 1,223,456.78
vi_VN | 1223456.78 -> 1.223.456.78
wo_SN | 1223456.78 -> 1 223 456.78
xh_ZA | 1223456.78 -> 1 223 456.78
yo_NG | 1223456.78 -> 1,223,456.78
zh_CN | 1223456.78 -> 1,223,456.78
zh_HK | 1223456.78 -> 1,223,456.78
zh_MO | 1223456.78 -> 1,223,456.78
zh_SG | 1223456.78 -> 1,223,456.78
zh_TW | 1223456.78 -> 1,223,456.78
zu_ZA | 1223456.78 -> 1,223,456.78

**Comment by vomikan** [comment]
Now new option in the general settings available.
All double values will be formatted regarding the locale chosen.
![image](https://user-images.githubusercontent.com/6836805/116908077-26e50500-ac4b-11eb-8bae-e864aa162d58.png)

If this field is left blank, each currency will be displayed according to its own settings.

**Comment by reddyshyam** [comment]
Sheer brilliance! 🙇🙇🙇 Well done you both! 👏👏👏

The long pending issue using this awesome app is finally resolved. Can't express my joy! 👍 😂 

Thanks again guys! Appreciate your time and efforts.

**Comment by valsamis-d** [comment]
Just a correction for the el_GR locale:

el_GR | 1223456.78 -> 1.223.456**,**78

In Greek locale decimal point is comma

**Comment by whalley** [comment]
Gotcha. I missed that previous discussion. Perhaps we should disable the relevant currency fields if the locale setting is being used.

**Comment by vomikan** [comment]
@valsamis-d choose american locale
en_US | 1223456.78 -> 1,223,456.78
