### ISSUE TITLE
Select button has disabled by default in categories dialog

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2478]
Select button has disabled by default in transaction dialog
![image](https://user-images.githubusercontent.com/6836805/81725799-0eef0100-948f-11ea-93f0-31bd80f7e668.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by gabriele-v** [comment]
Fixed
