### ISSUE TITLE
Useless "Budget Setup: Without Summaries"

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2480]
![image](https://user-images.githubusercontent.com/6836805/81793014-78afef00-9511-11ea-9899-2a4449ab05fa.png)

**Comment by siowena** [comment]
@vomikan - any reason this was removed, I've found this to be useful in v1.3.3 as I can quickly see if, for example, the category for food is budget OK even through I am over on delivery/takeout and underbudget for groceries.

**Comment by vomikan** [comment]
@siowena The bugfix caused a bug.

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33355950/job/ranj4282fgr57oah/artifacts

MS Win build available

**Comment by siowena** [comment]
Thanks, appreciate it.
