### ISSUE TITLE
Crash on account link clicked in Transaction Report

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2483]
![image](https://user-images.githubusercontent.com/6836805/81814116-04854380-9531-11ea-95a4-64ac4097ecbf.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x

```
** (mmex:22994): CRITICAL **: 16:04:13.896: void webkit_web_context_register_uri_scheme(WebKitWebContext*, const char*, WebKitURISchemeRequestCallback, gpointer, GDestroyNotify): assertion 'g_ascii_strcasecmp(scheme, "https") != 0' failed
04:04:13 PM: Debug: Report File Name: mmReportTransactions
04:04:13 PM: Debug: ===== Model_Usage::AppendToUsage =================
04:04:13 PM: Debug: {"module":"Report","name":"mmReportTransactions","seconds":0.018}
04:04:13 PM: Debug: 

04:04:13 PM: Debug: Sending stats (thread 140567885375232, priority 50, Linux 5.4.0-29-generic x86_64, 2 cores): http://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-51521761-6&cid=gtk_20200513010015339&uid=gtk_20200513010015339&dp=/frame/dialog&dt=Transaction%20Filter&ul=en&sr=1920x975&sd=24-bits&an=MoneyManagerEx&av=1.3.5-Beta.6&cd1=gtk&plt=0
04:04:13 PM: Debug: Response: GIF89a
04:04:13 PM: Debug: Sending stats (thread 140567885375232, priority 50, Linux 5.4.0-29-generic x86_64, 2 cores): http://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-51521761-6&cid=gtk_20200513010015339&uid=gtk_20200513010015339&dp=/frame/panel/mmReportsPanel&dt=mmReportsPanel&ul=en&sr=1920x975&sd=24-bits&an=MoneyManagerEx&av=1.3.5-Beta.6&cd1=gtk&plt=0
04:04:14 PM: Debug: Response: GIF89a
04:04:16 PM: Debug: Sending stats (thread 140567885375232, priority 50, Linux 5.4.0-29-generic x86_64, 2 cores): http://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-51521761-6&cid=gtk_20200513010015339&uid=gtk_20200513010015339&dp=/dialog&dt=Debug%20report%20%22mmex%22&ul=en&sr=1920x975&sd=24-bits&an=MoneyManagerEx&av=1.3.5-Beta.6&cd1=gtk&plt=0
04:04:16 PM: Debug: Response: GIF89a
Aborted (core dumped)
```

**Comment by vomikan** [comment]
To fix:
![image](https://user-images.githubusercontent.com/6836805/81816315-d5bc9c80-9533-11ea-8a18-52d6efa6c8c4.png)

**Comment by vomikan** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6836805/81940092-df133b00-95ff-11ea-8263-39bfcddf00ca.gif)

[2020-05-14 16-20-23.zip](https://github.com/moneymanagerex/moneymanagerex/files/4628692/2020-05-14.16-20-23.zip)

**Comment by vomikan** [comment]
``
    browser_ = wxWebView::New(this, mmID_BROWSER);
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "https")));

    Bind(wxEVT_WEBVIEW_ERROR, &mmReportsPanel::OnError, this, browser_->GetId());

....

void mmReportsPanel::OnError(wxWebViewEvent& evt)
{
    wxString uri = evt.GetURL();
.....
}

**Comment by gabriele-v** [comment]
BTW: https://lists.webkit.org/pipermail/webkit-gtk/2018-April/003248.html
Looks to be a limitation of WebKitGTK, is it the bug present on Mac as well?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1612

**Comment by gabriele-v** [comment]
So probably it's fixed with wx 3.1?
TBH I don't like your fix (don't know if it's working too)

**Comment by vomikan** [comment]
The behavior of both Unix-like systems is the same. But I did not check. No access to MAC.

**Comment by vomikan** [comment]
> So probably it's fixed with wx 3.1?

No. I've tested on Ubuntu 20.04 wx3.1.3

**Comment by gabriele-v** [comment]
So should be fine to just put this inside if wxGTK without your other changes:
`browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "https")));`

**Comment by vomikan** [comment]
>  TBH I don't like your fix (don't know if it's working too)

I've commited the small fix to have git pull on MAC and Linux as well.
This patch not 100% fix.

**Comment by gabriele-v** [comment]
But problem is with HTTPS handler from the error..
I don't have access to linux machine but this should fix the issue easily

> So should be fine to just put this inside if wxGTK without your other changes:
> `browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "https")));`

**Comment by vomikan** [comment]
What do you mean?
#if defined (_WXGTK_) ??

**Comment by gabriele-v** [comment]
```
#ifndef __WXGTK__
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "https")));
#else
```
Don't know how to manage HTTPS on GTK after that, but if it doesn't work anyway we have to found something else..

**Comment by vomikan** [comment]
To avoid crashes on ПЕЛ all the following 
```
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "trx")));
    browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new WebViewHandlerReportsPage(this, "attachment")));
```
handlers should be removed.
IMHO https handler ignores. See #2500

**Comment by gabriele-v** [comment]
Mmmhh that's strange because error complains only about HTTPS.
IMHO it's just something that triggers the HTTPS check when a non HTTPS link is selected..

Have you tried removing only the HTTPS?

**Comment by vomikan** [comment]
>  we have to found something else..

mmexfakelink: protocol. 
```<a href='https://www.chiark.greenend.org.uk/~sgtatham/bugs.html'>How to Report Bugs Effectively</a>```
may be changed to 
```<a href='mmexs://www.chiark.greenend.org.uk/~sgtatham/bugs.html'>How to Report Bugs Effectively</a>```

**Comment by vomikan** [comment]
Just discovered 
    Bind(wxEVT_WEBVIEW_NAVIGATING, &mmReportsPanel::OnError, this, browser_->GetId());

**Comment by gabriele-v** [comment]
> > we have to found something else..
> 
> mmex(fakelink): protocol.
> `<a href='https://www.chiark.greenend.org.uk/~sgtatham/bugs.html'>How to Report Bugs Effectively</a>`
> may be changed to
> `<a href='mmexs://www.chiark.greenend.org.uk/~sgtatham/bugs.html'>How to Report Bugs Effectively</a>`
> 
I was think at the same but was disgusting inside to propose it.. :D

**Comment by vomikan** [comment]
I can confirm that crash on Linux host has gone.
