### ISSUE TITLE
Crash or assert on transaction link

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2484]
![image](https://user-images.githubusercontent.com/6836805/81815657-ec162880-9532-11ea-9dd2-df4d393611e8.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

```
(mmex:22770): Gtk-WARNING **: 16:02:10.528: Negative content width -4 (allocation 30, extents 17x17) while allocating gadget (node button, owner GtkButton)

(mmex:22770): Gtk-WARNING **: 16:02:10.571: Negative content width -4 (allocation 30, extents 17x17) while allocating gadget (node button, owner GtkButton)

(mmex:22770): Gtk-WARNING **: 16:02:10.613: Negative content width -4 (allocation 30, extents 17x17) while allocating gadget (node button, owner GtkButton)

(mmex:22770): Gtk-WARNING **: 16:02:10.664: Negative content width -4 (allocation 30, extents 17x17) while allocating gadget (node button, owner GtkButton)
04:02:17 PM: Debug: 1 000.00 -> 1000.00
04:02:17 PM: Debug: 1 000.00 -> 1000.00
/home/nick/moneymanagerex/src/model/Model_Account.cpp(167): assert "false" failed in currency().

```

**Comment by gabriele-v** [comment]
I had the same issue on Windows doing something with a test DB a bit messed up, so I think it could be something more DB related than Linux related. Or you are facing the same issue even with a fresh DB on Linux?

**Comment by gabriele-v** [comment]
I think it's something happening when account currency has been deleted, but my DB has been touched also with SQLite Editor so maybe that's the reason, don't know about your.

**Comment by vomikan** [comment]
I've tested on empty just created DB on Linux host and can't reproduce this on Windows host.

**Comment by gabriele-v** [comment]
It could be something related to new database or account wizard, try to do exactly the same things on Linux and Windows starting from empty DB

**Comment by vomikan** [comment]
Windows output:
```
SQLITE_INSERT
database: main, table: PAYEE_V1, rowid: 1
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
c:\wxwidgets\src\msw\treectrl.cpp(2216): 'TreeView_SortChildren()' failed with error 0x00000002 (Не удается найти указанный файл.).
1 -> 1
200.0000 -> 200,0000
0.0000 -> 0,0000
SQLITE_UPDATE
database: main, table: STOCK_V1, rowid: 1
200.00 -> 200,00
SQLITE_INSERT
database: main, table: CHECKINGACCOUNT_V1, rowid: 1
SQLITE_INSERT
database: main, table: TRANSLINK_V1, rowid: 1
SQLITE_UPDATE
database: main, table: CHECKINGACCOUNT_V1, rowid: 1
SQLITE_INSERT
database: main, table: SHAREINFO_V1, rowid: 1
SQLITE_UPDATE
database: main, table: STOCK_V1, rowid: 1
SQLITE_UPDATE
database: main, table: STOCKHISTORY_V1, rowid: 1
c:\wxwidgets\src\msw\window.cpp(594): 'SetFocus' failed with error 0x00000057 (Параметр задан неверно.).
=========== navTreeStateToJson =============================
{
    "item@Home Page": true,
    "item@Stocks": true
}
SQLITE_UPDATE
database: main, table: INFOTABLE_V1, rowid: 8
```

**Comment by vomikan** [comment]
One more thing. I've adder 
![image](https://user-images.githubusercontent.com/6836805/81930039-a9b32100-95f0-11ea-8f14-f90ef2574cb7.png) button to get online rates for currencies and stocks.
All values may be downloaded by one request. It's sinple and cool and fast.

To keep all used currencies and stock historical data it should be several queries to Yahoo.com with date ranges. It's would be difficult and slow. 

And what we would do in case if Yahoo close API ?
https://github.com/moneymanagerex/moneymanagerex/issues/1367

**Comment by vomikan** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6836805/81940092-df133b00-95ff-11ea-8263-39bfcddf00ca.gif)

**Comment by vomikan** [comment]
Original transaction:
![image](https://user-images.githubusercontent.com/6836805/81977961-76de4c80-9633-11ea-9a77-78f835cf3c4d.png)

Transaction opend by Transaction Filter:
![image](https://user-images.githubusercontent.com/6836805/81978061-a1300a00-9633-11ea-86e5-5d424c03189b.png)

**Comment by vomikan** [comment]
As I see this situation:
@stef145g implemented tecnology for stocks and shares and have made the following video:
https://www.youtube.com/watch?v=UJr2M743p10&lc=UgwbIe1yeuqhBGjcskh4AaABAg
Since Aug 15, 2017 this interface did's updated. Few people use it. There were practically no bugs reported and the design lags behind the transaction window.
As result we have transactions that should be opened not Transaction Dialog but Share Transaction and Asset Transaction.
That is the Super BUG!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2408

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/82021898-627e6c00-9694-11ea-8411-7d33cb95b048.png)

**Comment by vomikan** [comment]
#2404

**Comment by vomikan** [comment]
#2408

**Comment by stef145g** [comment]
@vomikan Quote "As result we have transactions that should be opened not Transaction Dialog but Share Transaction and Asset Transaction.
That is the Super BUG!"

The standard transaction only relates to other standard accounts. Think of it as being in a straight line. An Asset or a Shares account is not a standard transaction but an intrusion to the normal accounts mechanism. Think of this as being a right angles to the normal transactions.

In the database, the TOACCOUNTID for a normal transaction can be either -1 for deposit or withdrawal or the ACCOUNTID for a transfer. To specify that the transaction is NOT a normal transaction but one linked to a Asset or Share, it states 32701 or 32702 (A ToAccountID is then found in the asset or shares link table that ties the asset or share portfolio to the transaction.

When attempting to edit a transaction in the assets or shares account, the correct form will be opened as the transaction will be identified as either a normal transaction or one comming from an asset or share. This is NOT a Super Bug.

This means that when adding a new share transaction, it must be done from the shares portfolio otherwise the transaction will be regarded as a regular transaction and directed to the regular accounts, same as all other regular transactions.
