### ISSUE TITLE
Attachments Settings

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2488]
Better to use  wxComboBox and path validator

![image](https://user-images.githubusercontent.com/6836805/81927798-e846dc80-95ec-11ea-86e8-a580eb3ddb0b.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by gabriele-v** [comment]
We cannot use combobox, because it's possible to use also a fixed path without % placeholders.
I'll fix the path validation

**Comment by vomikan** [comment]
We can

![image](https://user-images.githubusercontent.com/6836805/81941856-0539da80-9602-11ea-8aa4-1b2c11c7127f.png)

**Comment by gabriele-v** [comment]
Is it working on Mac/Linux too? I remember there was an issue with Mac or Linux with that combobox..
Not sure if it was about choices not visible or autocomplete probably

**Comment by vomikan** [comment]
It auto complete issue if you typing. In general it works.
