### ISSUE TITLE
Account naming issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2492]
![image](https://user-images.githubusercontent.com/6836805/82022376-4202e180-9695-11ea-9e0b-1d3e1ef4c145.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/82023221-9a86ae80-9696-11ea-9f2a-7e6e5d2b31f4.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/82032312-b0e73700-96a3-11ea-8141-a12be8c547d1.png)

**Comment by gabriele-v** [comment]
When you edit the stock (ttt3 under MICEX) it's editing (and showing in the right panel) the ttt3 share account that it's normally hidden, so basically it's correct, but it's too difficult to understand for users.
TBH I don't know how to solve it, becasue it's quite difficult from the tree to detect in which case we are..
