### ISSUE TITLE
Future transactions

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2494]
Duplicate?
![image](https://user-images.githubusercontent.com/6836805/82042470-949ec680-96b2-11ea-8cec-d3a84d6389ea.png)

![image](https://user-images.githubusercontent.com/6836805/82042501-a7b19680-96b2-11ea-9d22-37d50d1a4a9f.png)

**Comment by gabriele-v** [comment]
Yep, also above ones (budgets) are duplicated as well.
They should all set the same of options (haven't checked)

**Comment by vomikan** [comment]
Ауфегку not a bug

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/2378
