### ISSUE TITLE
Unused category

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2496]
Seems the option has been added but does not supports properly.

![image](https://user-images.githubusercontent.com/6836805/82064285-3b945a00-96d5-11ea-9a51-e9b2cec95324.png)

**Comment by vomikan** [comment]
I've created a patch.

![image](https://user-images.githubusercontent.com/6836805/82064577-a04fb480-96d5-11ea-943d-aa7bb3774ce4.png)

Now how would be working:
- Category reports;
- GRM reports
- Export (csv, qif, json etc)
- WebApp
- Import
etc

Seems better to remove this feature.

**Comment by gabriele-v** [comment]
Two solutions:
- remove the feature
- always preload with "Unknown" (as done in Import and WebApp)

**Comment by gabriele-v** [comment]
I'll go with proposal nr.2, I have other fixes in progress

**Comment by vomikan** [comment]
Bonus:
https://github.com/moneymanagerex/moneymanagerex/blob/v1.3.5/src/transdialog.cpp#L311-L314

**Comment by gabriele-v** [comment]
Yep, there is a bug in options as well, because UNUSED for payee it's not available as choice..
