### ISSUE TITLE
Attachments folder

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2499]
![image](https://user-images.githubusercontent.com/6836805/82196594-91017e80-9902-11ea-8d7a-7dde11cb7020.png)

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by gabriele-v** [comment]
How to reproduce? Just save or you have changed the path?

**Comment by vomikan** [comment]
it was new db. Then settings change.

**Comment by gabriele-v** [comment]
Fixed
