### ISSUE TITLE
Reports panel

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2501]
This panel has no sense if no widgets needed.
![image](https://user-images.githubusercontent.com/6836805/82446340-2772a300-9aaf-11ea-96a2-f3a5a83300d3.png)

-  Check MMEX version
  - [x] 1.3.x

**Comment by gabriele-v** [comment]
I don't see this as an issue: it's just a header to remind that we are on a report, isn't it?

**Comment by vomikan** [comment]
We should find it  to sitisfy #2502

**Comment by gabriele-v** [comment]
I think we will anyway need to pass isHome as parameter because something else it's different I guess..
