### ISSUE TITLE
version.txt deprecated

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2505]
Versions history is available online.

Hm. What about offline users?

![image](https://user-images.githubusercontent.com/6836805/82490688-4e02ff00-9aec-11ea-9a21-2a89239690ad.png)

https://github.com/moneymanagerex/moneymanagerex/blob/master/version.txt
-  Check MMEX version
  - [x] 1.3.x

**Comment by gabriele-v** [comment]
IMHO we can delete it, I think it's not used anywhere in application, just a TXT file copied in app folder.
