### ISSUE TITLE
money manager ex cannot create shortcut to document and open with new mmex 1.34

### ISSUE THREAD

**Issue by SniperViperReal** [moneymanagerex/moneymanagerex#2507]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [1 ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by SniperViperReal** [comment]
Install version 1.34 have to manually uninstall 1.33 then cannot open shortcut to 1.33 data file in 1.34. Try to specify windows 7 which file to open database with cannot goto directory for mmex1.34 folder bin and select mmex1.34 exe file using browse doesn't register or allow only defaults to internet explorer,  using old version 1.33 but at start pop up annoyance new version available.

**Comment by vomikan** [comment]
Look at this case
https://github.com/moneymanagerex/moneymanagerex/issues/2387

**Comment by vomikan** [comment]
I tecommend mmex v1.3.5-rc.1
