### ISSUE TITLE
graph scaling

### ISSUE THREAD

**Issue by Ton558** [moneymanagerex/moneymanagerex#2508]
Hi,
The graph has a scale problem.
Report : income vs expenses
![image](https://user-images.githubusercontent.com/63596191/82725078-b7e0fb80-9cda-11ea-851d-c8e1d7c3b825.png)

Proposal to extend the graph to the right.
Report : cast flow / daily
![image](https://user-images.githubusercontent.com/63596191/82725223-be23a780-9cdb-11ea-906d-350f3a6e457f.png)

best regards,

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.5.rc1
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
There is auto scaling. Try to change mmex window size you will see that graphs size changes.
I don't know proper solution yet.
