### ISSUE TITLE
0,00 marked as negative

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#2509]
![image](https://user-images.githubusercontent.com/7106290/82730393-7dd62080-9cff-11ea-86ec-5f74a872ca66.png)
![image](https://user-images.githubusercontent.com/7106290/82730396-82023e00-9cff-11ea-902f-3807408c88cc.png)

Tried to open all transactions, rewrite the amounts and save but without success

**Comment by gabriele-v** [comment]
Import attached TXT as CSV with MMEX Format (Date DD/MM/YYY and comma as decimal separator) in an empty account to reproduce

[Test.TXT](https://github.com/moneymanagerex/moneymanagerex/files/4671755/Test.TXT)

**Comment by vomikan** [comment]
I've catch it

![image](https://user-images.githubusercontent.com/6836805/82752301-b809f580-9dc5-11ea-9f85-c7c702b6278d.png)

**Comment by gabriele-v** [comment]
Yep, but deeping into it looks the issue is at database layer, because (I don't remember exact numbers, it's just an example) when reading 1,12 double has value 1,120000001

**Comment by gabriele-v** [comment]
Probably we should round it at some point

**Comment by vomikan** [comment]
std::fpclassify(value) == FP_ZERO does not working :(

**Comment by vomikan** [comment]
Here you can apply a lot of different ways, but you need to find the fastest.

**Comment by vomikan** [comment]
std::numeric_limits<double>::lowest()
Not applicable here.
![image](https://user-images.githubusercontent.com/6836805/82753092-afb4b900-9dcb-11ea-931a-535daa099e7e.png)

**Comment by vomikan** [comment]
OMG
https://stackoverflow.com/questions/19754949/what-is-a-standard-way-to-compare-float-with-zero

**Comment by gabriele-v** [comment]
What I do not understand is this:
![image](https://user-images.githubusercontent.com/7106290/82753340-15ea0d80-9dc5-11ea-8510-0f5da4ea78a7.png)
![image](https://user-images.githubusercontent.com/7106290/82753327-0074e380-9dc5-11ea-95da-0c862dd1dd8c.png)

Looks the issue is in wxSQLite because `q.GetDouble(5)` calls some wxSQLite code

**Comment by vomikan** [comment]
first of all s.SubString(1, 1) is incorrect

**Comment by vomikan** [comment]
I've implemented the solution using some magic number
const float ROUNDING_ERROR_f32 = 0.000001f;

The trouble if in future we start to support crypto currencies with precision >= 6 it would be incorrect again is some cases.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/564

**Comment by gabriele-v** [comment]
Confirm fixed
