### ISSUE TITLE
Latest MAC Stable v1.3.4 - File reports as damaged and does not run

### ISSUE THREAD

**Issue by benquan** [moneymanagerex/moneymanagerex#2510]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [X ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

La Latest MACOS version available is 1.3.4 and downloading the file and running, the system reports as "Damaged File" and will not run. 

To be clear, the DMG file unpacks fine, but the .App is the one that crashes.

Tried:
 - mmex-1.3.4-Darwin.dmg
 - mmex-1.3.4_rc7-Darwin.dmg
 - mmex-1.3.4-macos10.9-wx3.0.4.dmg

The last one that works is:
 - mmex_1.3.3_macos10.9-wx3.0.2build.dmg

**Comment by gabriele-v** [comment]
Try 1.3.5-RC1:
https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.3.5-rc.1/mmex-1.3.5.rc1-macos.dmg

**Comment by benquan** [comment]
Same

![image](https://user-images.githubusercontent.com/3030645/82741743-900d8a00-9d12-11ea-974c-72d4861a29df.png)

**Comment by gabriele-v** [comment]
See solution here: https://github.com/moneymanagerex/moneymanagerex/issues/2420
