### ISSUE TITLE
lost all currency exchange rates

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2512]
https://forum.moneymanagerex.org/viewtopic.php?f=7&t=9338

have installed the version 1.3.5-RC1
I noticed that I lost all currency exchange rates.

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x

**Comment by vomikan** [comment]
![ch](https://user-images.githubusercontent.com/6836805/82761352-9d09a680-9e02-11ea-861f-837d6bff2fa5.PNG)

**Comment by gabriele-v** [comment]
Don't know how to fix/manage it without issue another DB version..

**Comment by vomikan** [comment]
may be make it true by default?

**Comment by gabriele-v** [comment]
You were thinking to completely remove it :)

I think MMEX should be easier by default, then add complexity only if someone wants it..

**Comment by vomikan** [comment]
I mean switch the option "Use currency history" on by default.
        m_currencyHistoryEnabled = Model_Infotable::instance().GetBoolInfo(INIDB_USE_CURRENCY_HISTORY, *false*);

**Comment by gabriele-v** [comment]
I may have another idea, I'll send a PR tomorrow

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/82764261-2aa2c180-9e16-11ea-8ec4-9efce1b520bc.png)

**Comment by gabriele-v** [comment]
Probably the DB has skipped some patches in the past, at the beginning of DB patch procedure there was a bit of mess, that's why we have introduced version 10 (I think) that normalize all tables..

**Comment by gabriele-v** [comment]
Or.. CURRENCYHISTORY it's not initialized during DB procedure, I'll have a look at tu is tomorrow too

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/82764446-6db16480-9e17-11ea-80a2-f43e1e860d9b.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2350

**Comment by gabriele-v** [comment]
> ![image](https://user-images.githubusercontent.com/6836805/82764446-6db16480-9e17-11ea-80a2-f43e1e860d9b.png)
> 

Yep, this should be CURRENCYHISTORY_V1 wrong copy/paste

**Comment by vomikan** [comment]
I remember that iI've fixed that
https://github.com/moneymanagerex/moneymanagerex/commit/c6d62b87598363850d3501892fd5aa323049ba78

**Comment by gabriele-v** [comment]
But that's not a fix, because you get only the previous dates, what if there is a closer rates but as next date?

**Comment by gabriele-v** [comment]
Maybe doing a LESS_OR_EQUAL and a GREAT_OR_EQUAL and then compare? But I remember there were some performance issues so I had to switch to manual queries. Only problem is that manual queries were for DB V10 (without V1 suffix).
I'll try again tomorrow with our model but I'm quite sure performance were poor.

**Comment by vomikan** [comment]
SQL should be avoided.

**Comment by gabriele-v** [comment]
I know but was not able to find another solution in the past.. I'll try again

**Comment by vomikan** [comment]
> But that's not a fix, because you get only the previous dates, what if there is a closer rates but as next date?

Not agree. Previous or the same date should be used. For example if exchange rate has set for Friday that should be used for Saturday and Sunday. Not Monday even if it's available.

**Comment by gabriele-v** [comment]
Mmhhh, regarding saturday/sunday I could agree but considering that in MMEX a rate it's added to history only when you click updates rates (or download full history but that's not a normal behavior), it could be better to use the closer in both directions.

Consider this case:
- History has rates for 1 Jan and 31 Jan
- I add a transaction dated 30 Jan

31 Jan rate should be more closer (in value) to 30 Jan rate than 1 Jan rate..

**Comment by vomikan** [comment]
You're lucky that you don't know what hyperinflation is.
Which can happen in a matter of days.
https://www.xe.com/currencycharts/?from=USD&to=RUB&view=10Y
![image](https://user-images.githubusercontent.com/6836805/82765159-f1ba1b00-9e1c-11ea-8206-e9b0cd5a8876.png)

**Comment by gabriele-v** [comment]
But that's an issue that you cannot resolve even if you use only the previous ones.

At least using both previous/next you better cover my scenario, yours cannot be predicted in any way..

**Comment by vomikan** [comment]
May be used the following scenario:
```
double  nearest = 1.0;
Model_CurrencyHistory::Data_Set Data_history = Model_CurrencyHistory::instance().find(Model_CurrencyHistory::CURRENCYID(currencyID)
        , Model_CurrencyHistory::CURRDATE(Date, LESS_OR_EQUAL));
if (Data_history.empty()) 
{
Model_CurrencyHistory::Data_Set Data =
Model_CurrencyHistory::instance().find(Model_CurrencyHistory::CURRENCYID(currencyID)
        , Model_CurrencyHistory::CURRDATE(Date, GREATER_OR_EQUAL));
    if (!Data.empty()) { 
         nearest = Data.begin().CURRVALUE; 
     }
}
else {
      nearest =  Data_history.back().CURRVALUE;
}

    return nearest;

**Comment by gabriele-v** [comment]
You are still looking at the past only.. If you are using history it's practically impossible to don't have a rates in the past

**Comment by vomikan** [comment]
My proposal is to find nearest value in the past. If the value missing then find nearest value in the future. In that case you will have actual exchange rate if historical data available or some similar exchange rate but not default value 1.
