### ISSUE TITLE
Columns for income and expense are flipped in monthly expenses vs. incomes report in 1.3.4

### ISSUE THREAD

**Issue by tierradenadie** [moneymanagerex/moneymanagerex#2521]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hello,

the new colum chart in the above mentioned report shows the income as expense and vice versa.

**Comment by vomikan** [comment]
Could you, please, provide more info?

**Comment by tierradenadie** [comment]
![image](https://user-images.githubusercontent.com/52632262/82826233-07772100-9ead-11ea-8d86-344b24e1f374.png)

As you can see in the image. The colum for expenses shows the value for the income and vice versa.

**Comment by vomikan** [comment]
I can't reproduce it in 1.3.5-rc.1

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2437
