### ISSUE TITLE
Budget Reports

### ISSUE THREAD

**Issue by how-a** [moneymanagerex/moneymanagerex#2540]
Budget Performance and Summary Reports have a selection list for the various years, but the reports are only 1 Jan - calendar year reports, not the financial year specified in "Options".  ie my Financial year begins 1 April, to co-incide with my Tax Year.

<hr>Version: 1.3.5-Beta.2<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.3 (wxMac 10.13)<br>
 • wxSQLite3 4.4.8 (SQLite 3.30.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0<br>
<br>
Build: Apr 28 2020 21:04:14 <br>
 • CMake 3.16.3<br>
 • Xcode 11.4.1<br>
 • gettext 0.20.1<br>
 • Clang 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)
<br>
<br>
OS:<br>
 • macOS High Sierra Version 10.13.6 (Build 17G12034)<br>
 •  English (New Zealand) (Western (Mac OS Roman))<br>
 • 1920x1080 32bit 103x103ppi

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/2378

**Comment by how-a** [comment]
Why did you call this an enhancement when it was working well in the previous version and is a function that is expected in the documentation?  The report should take the financial year as specified in the user options. I believe it is a bug.

**Comment by whalley** [comment]
Unless I'm mistaken then this was fixed by #1832
