### ISSUE TITLE
Stocks Performance Charts non-linear

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2550]
Sample: IBM
![image](https://user-images.githubusercontent.com/6836805/83037500-86eb2880-a044-11ea-8f6a-8e1b9b34f6d3.png)

-  Check MMEX version
  - [x] 1.3.x

**Comment by whalley** [comment]
@vomikan - Not sure what this is asking for? Can you please clarify.

**Comment by vomikan** [comment]
I don't even remember anymore. I think that the distance on the horizontal axis between the days is not linear. I think we can close this case.
