### ISSUE TITLE
Stock prices update

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2553]
not updated immidiatly

![image](https://user-images.githubusercontent.com/6836805/83050035-9bcfb800-a054-11ea-9a86-789d4554db39.png)

- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Related issue.
https://github.com/moneymanagerex/moneymanagerex/issues/2489

**Comment by whalley** [comment]
@vomikan Not sure I understand the issue. The share price is update when the rates are refreshed.
