### ISSUE TITLE
What budget.cpp for?

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2564]
-  Check MMEX version
  - [x] 1.3.x

**Comment by gabriele-v** [comment]
Looks to be an helper for budgeting reports? Haven't checked if still in use BTW

**Comment by vomikan** [comment]
Then I click on any budget this code run.
It designed as report for reportpanel.
 But budget shown in the budgetpanel.

**Comment by whalley** [comment]
It is still in use in mmBudgetingPanel, mmReportBudgetCategorySummary, and mmReportBudgetingPerformance.

Could be refactored in the future, but at present needed.
