### ISSUE TITLE
Panels not working anymore

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#2575]
In current master, panels (checking, assets. stocks etc..) are completely broken, not possible to show them.
@vomikan that's a monster bug, we cannot commit such broken changes..

Had a quick look but was unable to find the commit that broken it

**Comment by vomikan** [comment]
@gabriele-v please be patient. I'll fix soon.

**Comment by gabriele-v** [comment]
Don't worry, not for me but for people trying nightly builds
