### ISSUE TITLE
Incorrect Download of The latest stable release Desktop 1.3.4 

### ISSUE THREAD

**Issue by gregcap** [moneymanagerex/moneymanagerex#2585]
- Check OS                    [ x] Windows 32bit
- Check MMEX version  [ x] 1.3.x
I was using 32bit 1.3.3 version on my windows 10 pc.
After I installed the 1.3.4 32bit version I had 2 problems.

1 - When I download 1.3.4  Desktop version (the latest stable release of Money Manager EX) and I select the platform **WINDOWS 32bit,** the download installs INSTEAD the version **WINDOWS 32bit portable** .
I suppose there is an error, because if I can start MMEX on top bar I see the following label:
                                           ... file name ... (portable version)"-
Please note that I'm sure I selected the rigth version "WINDOWS 32bit" (NOT "WINDOWS 32bit - PORTABLE").

2- After that, when I open the last database (or an other one) I can only access and update the screens of all my "recurring transaction", **BUT the database do not opens**: no error message is available, nor code occurs, I just wait for many minutes, nothing happens ...
So I reverted back to 1.3.3, but the problem is the same.
The only kind of "solutions" I can apply are:
- re-install each time MMEX, THAN open the file: IT'S OK BUT ONLY ONE TIME.
**So I have to re-install MMEX each time I want restart the application and each time Windows restart.**
Any help ?

**Comment by vomikan** [comment]
1) portable or not depend on mmexini.db3 file location. 
2) it's a bug. #2471

**Comment by vomikan** [comment]
Try new release
https://sourceforge.net/projects/moneymanagerex/files/v1.3.5-rc.2/

**Comment by gregcap** [comment]
Thank you for your help, but my 2 Problems are still open as before

**Comment by vomikan** [comment]
Could you try the following workaroud:
1) Download
https://sourceforge.net/projects/moneymanagerex/files/v1.3.5-rc.2/ portable mmex and extract to c:\Portable_apps\ folder
2) Copy you .mmb file to c:\Portable_apps\moneymanagerex folder
3) Run c:\Portable_apps\moneymanagerex\bin\mmex.exe
4) Open your .mmb file from c:\Portable_apps\moneymanagerex folder

**Comment by gregcap** [comment]
OK ! I found the way for solutions.

I figured out that in the same directory there are 2 programs intalled: 
        C:\Program Files\Money Manager **EX\mmex.exe**
        C:\Program Files\Money Manager **EX \mmex.exe**
the diffference was 1 blank in the name of the directory  pre-setted from the dowload !!!! 
So:
1. - I disintalled both programs, 
2. - I re-installed only 1 version         (1.3.5-RC.2      database: 7 aes128cbc)
3. - I deleted the file mmexini.db3 in its folder (so it DO NOT assume portable, mode as you suggested).

Now all it's ok !!!!

===
Anyway please NotE that I suppose there is an error in download and install procedure of the Windows 32bit platform.
I mean:
- the name of the Directory pre-setted from the dowload procedure to install MMEX i's different from the previous one (difference = 1 blank as above);
- the file mmexini.db3 is always installed in its folder (so it ALWAYS assume portable mode).

Thank you.
