### ISSUE TITLE
Custom Report stopped working: it goes to "https://www.google.com/jsapi"

### ISSUE THREAD

**Issue by valsamis-d** [moneymanagerex/moneymanagerex#2586]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows

-  Check MMEX version
  - [x] 1.4.0-alpha.6 (Git commit: 7b93b598 (2020-04-09) )

At some point one of my custom reports stopped working. Specifically, instead of opening within MoneyManagerEx it opens in Microsoft Edge (new chrome-based version) at the following address "https://www.google.com/jsapi"

**Comment by vomikan** [comment]
For some reasons we stop developing v1.4.0.
Now we actively develop 1.3.5. https://sourceforge.net/projects/moneymanagerex/files/
I suggest to downgrade your DB using the following script:
https://github.com/moneymanagerex/moneymanagerex/files/4432527/downgrade_db_13_7_v3.zip

https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by valsamis-d** [comment]
> 
> 
> For some reasons we stop developing v1.4.0.
> Now we actively develop 1.3.5. https://sourceforge.net/projects/moneymanagerex/files/
> I suggest to downgrade your DB using the following script:
> https://github.com/moneymanagerex/moneymanagerex/files/4432527/downgrade_db_13_7_v3.zip
> 
> #2353

Ouch :(

Can you please help with some short details on how to use the downgrade script?

Thank you
Dimitrios

**Comment by vomikan** [comment]
1) Download 
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33223132/job/kr3y7gnwrj3tx128/artifacts portable mmex and extract to c:\Portable_apps\ folder
2) Download the script provided above and extract it
3) Run c:\Portable_apps\moneymanagerex\bin\mmex.exe
4) Choose your mmb file
5) Say Yes when ascing script and choose script.

**Comment by valsamis-d** [comment]
Perfect! This worked just fine :) Thanks!
