### ISSUE TITLE
Invalid assets in releases

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2588]
![image](https://user-images.githubusercontent.com/6836805/83353466-6e885000-a35b-11ea-8646-db9887c38c07.png)

![image](https://user-images.githubusercontent.com/6836805/83353480-852ea700-a35b-11ea-95e7-36027ebb91e6.png)

**Comment by gabriele-v** [comment]
What about unpublish 1.3.5-RC2?
Doesn't make sense to have the update message sent to all clients..

**Comment by gabriele-v** [comment]
Otherwise we need to merge into 1.3.5 branch and try to release from there

**Comment by vomikan** [comment]
I've updated the release manually.

**Comment by 2BeeOrNot** [comment]
No update for Mac users? :(

**Comment by whalley** [comment]
Think this can be closed now. All new releases have correct assets.
