### ISSUE TITLE
CSV Export crashes with "access violation"

### ISSUE THREAD

**Issue by Noiden** [moneymanagerex/moneymanagerex#2589]
- Check OS
  - [X] Windows 10 Pro (10.0.18363)
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.4.0-alpha.7 (x64)
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
----------------------------------------
When I'm trying to make an CSV Export MMEX crashes.

Get this error in the generated xml-file

`<exception code="0xc0000005" name="ACCESS_VIOLATION" address="0x7ff79df1a80c"/>`

The error from the .dmp file is this,

```
Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
```
I have tried to run it as administrator but same error.

I tried to use an older version of MMEX but could not open the database because of the version of the database.

**Comment by vomikan** [comment]
For some reasons we stop developing v1.4.0.
Now we actively develop 1.3.5. https://sourceforge.net/projects/moneymanagerex/files/
I suggest to downgrade your DB using the following script:
https://github.com/moneymanagerex/moneymanagerex/files/4432527/downgrade_db_13_7_v3.zip

Download
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33223132/job/kr3y7gnwrj3tx128/artifacts portable mmex and extract to c:\Portable_apps\ folder
Download the script provided above and extract it
Run c:\Portable_apps\moneymanagerex\bin\mmex.exe
Choose your mmb file
Say Yes when asks a script and choose the script.

**Comment by Noiden** [comment]
Worked like a charm.

Thanks. :D
