### ISSUE TITLE
OS: Windows 10 PRO 2004 19635.1 28/5/2020

### ISSUE THREAD

**Issue by ANAVSH** [moneymanagerex/moneymanagerex#2593]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by ANAVSH** [comment]
OS: Windows 10 PRO 2004 19635.1 28/5/2020
MMEX version: 1.4.0 alpha.7 win64 portable
Al ejecutar el MMEX.EXE
Abrir base de datos existente: casa.emb
Solicita Password
A partir de ahí MMEX queda bloqueado
Observo que en la carpeta en donde está la BD se ha cambiado la fecha y hora del fichero .emb y el CASA.emb_update_2020-06-02.emb. Eso parece ser antes de bloquearse.
He descargado: mmex-1.3.4-win64 portable 
Pero al ejecutar da el error:  
¡Error de la base de datos!
![Error DB](https://user-images.githubusercontent.com/66308846/83514602-39533d80-a4d4-11ea-812a-e5442fddecd7.JPG)
¿Pueden ayudarme?

**Comment by ANAVSH** [comment]
Aclaración: Cuando solicita la contraseña se introduce y la acepta como correcta

**Comment by vomikan** [comment]
For some reasons we stop developing v1.4.0.
Now we actively develop 1.3.5. https://sourceforge.net/projects/moneymanagerex/files/
I suggest to downgrade your DB using the following script:
https://github.com/moneymanagerex/moneymanagerex/files/4432527/downgrade_db_13_7_v3.zip
Download
https://sourceforge.net/projects/moneymanagerex/files/v1.3.5-rc.2/ portable mmex and extract to c:\Portable_apps\ folder
Download the script provided above and extract it
Run c:\Portable_apps\moneymanagerex\bin\mmex.exe
Choose your mmb file
Say Yes when asks a script and choose the script.

**Comment by ANAVSH** [comment]
Thank you very much for your help. I have followed your instructions and my
problem has been fixed.
Best regards,
Antonio

*---------------------*
*Antonio Navarro Sánchez*
*e-mail: anavsh@gmail.com <anavsh@gmail.com>*
*---------------------*

Este mensaje va dirigido, de manera exclusiva, a su destinatario y puede
contener información confidencial y sujeta al secreto profesional, cuya
divulgación no está permitida por Ley.

En caso de haber recibido este mensaje por error, le rogamos que, de forma
inmediata, nos lo comunique mediante correo electrónico remitido a nuestra
atención y proceda a su eliminación, así como a la de cualquier documento
adjunto al mismo.

 Asimismo, le comunicamos que la distribución, copia o utilización de este
mensaje, o de cualquier documento adjunto al mismo, cualquiera que fuera su
finalidad, están prohibidas por la ley.

En aras del cumplimiento del Reglamento (UE) 2016/679 del Parlamento
Europeo y del Consejo, de 27 de abril de 2016, puede ejercer los derechos
de acceso, rectificación, cancelación, limitación, oposición y portabilidad
de manera gratuita mediante correo electrónico a: *anavsh@gmail.com
<http://gmail.com>*
