### ISSUE TITLE
Decimal separator is not shown

### ISSUE THREAD

**Issue by gusman** [moneymanagerex/moneymanagerex#2594]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X ] 1.3.x

  - [ ] 1.2.x
  - [ ] 1.1 or older
![issue](https://user-images.githubusercontent.com/177091/83532517-8ce77a80-a518-11ea-9ddf-d61e1b4e8a86.png)
![version](https://user-images.githubusercontent.com/177091/83532525-8fe26b00-a518-11ea-8fd0-0f8f476f9cda.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2473
