### ISSUE TITLE
macOS MMEX Icon Too Small

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2596]
MMEX icon in dock and finder is too small compared to other icons.
![MMEX Dock](https://user-images.githubusercontent.com/63317977/83684334-e1403800-a5b4-11ea-85a9-7c597454de18.jpg)
![MMEX Finder](https://user-images.githubusercontent.com/63317977/83684342-e309fb80-a5b4-11ea-9e4b-d0f38b79f37a.jpg)
I enlarged your icon, cropped it, and made a icon bundle with all the sizes and resolutions. IMO looks better.
![MMEX Dock 2](https://user-images.githubusercontent.com/63317977/83684617-5875cc00-a5b5-11ea-86fb-57d996de4414.jpg)
![MMEX Finder 2](https://user-images.githubusercontent.com/63317977/83684623-5ad82600-a5b5-11ea-8567-da4ecdf4aae2.jpg)
If you want to try it let me know and I can try and attach my mmex.icns file. Of course it's bigger at 573 KB.

**Comment by vomikan** [comment]
Could you zip and upload icns file here?

**Comment by 2BeeOrNot** [comment]
Here it is. 
[mmex.icns.zip](https://github.com/moneymanagerex/moneymanagerex/files/4726512/mmex.icns.zip)

**Comment by vomikan** [comment]
Could someone check why MAC build false?
