### ISSUE TITLE
Top Withdrawals in Home Page

### ISSUE THREAD

**Issue by ramshake** [moneymanagerex/moneymanagerex#2601]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

"Top Withdrawals: Last 30 Days" section in Home Page counts share purchase transactions that are marked    as Transfer. Can you exclude the Share transfer transactions from this calculation? Thanks.

**Comment by vomikan** [comment]
How to reproduce?

**Comment by vomikan** [comment]
There is a magic number in the TOACCOUNT field
I don't know how to interpret it
![image](https://user-images.githubusercontent.com/6836805/83948739-01c3f880-a828-11ea-802f-063f2e422487.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2484

**Comment by ramshake** [comment]
Yes, When I was looking at the my DB, all the transfer transactions are marked in TOACCOUNTID as 32702. Maybe you can add a filter to not include transactions with TOACCOUNTID = 32702 when generating Top Withdrawals report. 

![1](https://user-images.githubusercontent.com/65050316/83949812-7167c280-a7eb-11ea-9e83-3c8998f1b993.jpg)
![2](https://user-images.githubusercontent.com/65050316/83949814-73ca1c80-a7eb-11ea-89e3-48417e3ad1bb.jpg)

**Comment by vomikan** [comment]
@ramshake Could you test please
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33359510/job/9va2a802iou1j9nl/artifacts

I am afraid that the same issue for reports as well.
