### ISSUE TITLE
Automatic transaction import

### ISSUE THREAD

**Issue by hedgss** [moneymanagerex/moneymanagerex#2602]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

I have a question.
I am going to write a custom transaction exporter from some banks.
It will generate files with transactions in a format is are supported by MoneyManagerEx.
Is it possible to import the files automatically?

e.g. it can be done if I execute some command to import the data after the export. 
Or MME can import the data automatically when it starts.

I'd like to simplify this process as much as possible.

I know that DB is SQLite and I can update it directly but I don't think that it is a good idea.

**Comment by vomikan** [comment]
Look at https://github.com/moneymanagerex/web-money-manager-ex

**Comment by hedgss** [comment]
@vomikan  
I thought that it is not supported anymore.
The last commit was 4.5 years ago.
Thank you, I will try to use it.

**Comment by vomikan** [comment]
It's good done. No updates needed.

**Comment by gabriele-v** [comment]
FYI looks at the latest posts here:
https://github.com/moneymanagerex/moneymanagerex/issues/2294

If you are able to create an application with a small webserver that has the same API of the WebApp you can act as WebApp and automatically imported into MMEX
