### ISSUE TITLE
Can't run 1.3.4 on MacOs (dmg is damaged and moved to bin)

### ISSUE THREAD

**Issue by Sergius7** [moneymanagerex/moneymanagerex#2603]
When running 1.3.4, MacOS 10.15 indicates that the file is damaged and has to be moved to the bin.

This issue is not happening with 1.3.3 .dmg file, and at 1.3.4. can be workarounded, as indicated at the forum, by running sudo xattr -rd com.apple.quarantine /Applications/mmex.app.

Still, something is wrong and has to be fixed.

- Check OS
  - [ ] Windows
  - [X ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ X] 1.3.4
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146
