### ISSUE TITLE
MacOS 1.3.5 - When adding new expenses, add 00's to 

### ISSUE THREAD

**Issue by Sergius7** [moneymanagerex/moneymanagerex#2604]
At MacOS version of 1.3.4 -stable-, when adding a new Transaction, the amount field gets a pair of 00's each time you move to another text field or combobox option.

At 1.3.3 there is similar behaviour, however it adds ",00"... that means a comma, for decimals, so it's gets added just one time and the next time you move arround, it keep as is.

Looks like that because at 1.3.4 add just 0's without comma, on next actions is still not detecting the decimals portion, and keeps adding 00's....

- Check OS
  - [ ] Windows
  - [X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.5
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by Sergius7** [comment]
First image: version 1.3.3. Notice that App is not following configured theme (dark mode is on).
You type just "1" at Amount, then you select notes (or whatever) and it adds a ",00". If you type decimals, it just do it right too. Also notice that I'm using metric system, where decimals are comma separated. Behaviour is just fine at 1.3.3.

![1 3 3-no_issues](https://user-images.githubusercontent.com/65726188/85347943-735ea080-b4d0-11ea-9221-6a179b023eb0.png)

Next, using 1.3.5 recently out (it was the same with 1.3.4.. this bug was introduced somewhere between 1.3.3 and 1.3.4), dark theme now is on, following setting. I type just "1" at amount, no decimals, nor commas or dots, just "1". Then I highlight notes.

![1 3 5-adding1](https://user-images.githubusercontent.com/65726188/85347946-75286400-b4d0-11ea-9d96-b1146efd6e02.png)

Here you will notice that two 0 are added, creating "100" instead of "1".
![1 3 5-adds00](https://user-images.githubusercontent.com/65726188/85347948-75c0fa80-b4d0-11ea-9b28-2b13c7dbf703.png)

Here I tried to add decimals, but the comma (or dot, I tried both) get's deleted too, and replaced by a pair of 0's... result is also 100. Instead of 1,00 (or 1.00).

![1 3 5-adding1 0](https://user-images.githubusercontent.com/65726188/85347949-76f22780-b4d0-11ea-8a12-3175d909ccd8.png)

**Comment by vomikan** [comment]
Could you check the account currency settings?
What are decimal and group separators?

**Comment by Sergius7** [comment]
Something is wrong with Decimal separator.

White background images are for 1.3.3 and black ones are for 1.3.5. I've added few combinations for decimals and group separators. At 1.3.3 you can see that it's fine. 

At 1.3.5 decimal separator is ignored but looking more in depth, I guess that code is loking for grouping character for decimals too... decimal separator gets duplicated (or empty) based on group Char input and always ignoring decimal char field.

![1 3 3-4](https://user-images.githubusercontent.com/65726188/85494892-ed198b80-b5af-11ea-86e4-2615856647bc.png)
![1 3 3-3](https://user-images.githubusercontent.com/65726188/85494894-edb22200-b5af-11ea-8891-be3b6c4d5c16.png)
![1 3 3-2](https://user-images.githubusercontent.com/65726188/85494896-edb22200-b5af-11ea-9d9b-a4f1bbbf9987.png)
![1 3 3-1](https://user-images.githubusercontent.com/65726188/85494898-ee4ab880-b5af-11ea-989e-2b82fc0777ff.png)
<img width="406" alt="1 3 5-2" src="https://user-images.githubusercontent.com/65726188/85494924-f7d42080-b5af-11ea-8fab-252436e85038.png">
<img width="409" alt="1 3 5-1" src="https://user-images.githubusercontent.com/65726188/85494927-f9054d80-b5af-11ea-95d0-b980f1a76064.png">
<img width="392" alt="1 3 5-3" src="https://user-images.githubusercontent.com/65726188/85494934-facf1100-b5af-11ea-8bd1-0500574fee3f.png">

**Comment by vomikan** [comment]
Thank you for the update.

**Comment by vomikan** [comment]
I suspect the wxNumberFormatter :: ToString function is not working properly.
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/model/Model_Currency.cpp#L187-L206

Related issue #2473

**Comment by whalley** [comment]
Tested this on 1.3.6 and cannot reproduce.
