### ISSUE TITLE
Notes field duplicating in export dialog

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#2614]
Steps to reproduce: 
1. File > Export > CSV
2. Select **Notes** column
3. Click **Add** multiple times
4. Click **Remove** multiple times

Expected behavior: Clicking **Add** should move the Notes column over to the right column (as happens with every other field beside "Notes")

Actual behavior: Clicking **Add** adds it to the right column but does not remove it from the left column. Clicking **Remove** adds duplicate copies of the Notes filed back to the left column. 

MMEX 1.3.4, Windows 10

Edit: Just noticed the **Don't Care** field also behaves incorrectly.

**Comment by vomikan** [comment]
Could you check this issue with new release 
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33518692/job/uflfou7s9r43pf3t/artifacts

**Comment by dbolton** [comment]
I'm still getting the same behavior with the portable version of the the program you linked to.

**Comment by whalley** [comment]
I can't reproduce this issue. Is it fixed? It seems to be.

> Just noticed the Don't Care field also behaves incorrectly.

@dbolton This would seem correct behavior as it allows empty columns to be inserted as needed in the output.

**Comment by vomikan** [comment]
This behavior is exactly the same as when importing. The notes field can be used repeatedly for any data. This is not necessary for export.
This is probably fixed.
