### ISSUE TITLE
Exported CSV is out of order

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#2615]
When I export to CSV I expected the order of transactions to match what I see in Money Manager Ex. Instead it moves all the transfers to the bottom of the list. 

MMEX 1.3.5 RC2, Windows 10

**Comment by vomikan** [comment]
You can save configuration. It's not a bug but feature.

**Comment by dbolton** [comment]
Is there a configuration to sort the CSV file by date in Money Manager Ex? Maybe I'm not following. 

I realize I can sort the CSV when I open it in Excel, or another spreadsheet program.

**Comment by whalley** [comment]
I've just tested this and the exported CSV is in Transaction ID order. This is an enhancement not a bug.
