### ISSUE TITLE
Balances incorrect after sorting columns

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#2617]
Warning: do not do this on an account you care about, since I haven't found a way to get the balance correct again.

1. Add a starting balance to the account (Not sure if this step is needed)
2. Sort by Withdrawal column. Check balances (might be incorrect already)
3. Sort by Deposit column. Check balances
4. Sort by Date column again. Balances are still incorrect.

Closing and reopening the database didn't seem to solve the problem.

Reproduced on both MMEX 1.3.5 RC2 and 1.3.4. Windows 10

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/2296

**Comment by dbolton** [comment]
Original bug report was wrong on step 4. I was comparing to Quicken and had the wrong starting balance in MMEX.

The balances shouldn't be wrong after sorting by a non-date column but that is a different issue.
