### ISSUE TITLE
Crash when selecting "Relocate Payee"

### ISSUE THREAD

**Issue by peternjohansson** [moneymanagerex/moneymanagerex#2620]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Windows 10 Pro x64 version 2004
MMEX version 1.3.5 x64

Steps to reproduce:
- Create new database with one account (or use existing database)
- Add new transactions with different payees 
- Select 'Tools' -> 'Organize Payees...' from main menu.
- Right-click on one of the payees and select 'Relocate Payee'

Screen Dump:
![image](https://user-images.githubusercontent.com/67038492/84856365-c8c92680-b066-11ea-9d57-6fc1f40a1582.png)

Debug File:
[MoneyManagerEx_dbgrpt-6688-20200617T061715.zip](https://github.com/moneymanagerex/moneymanagerex/files/4790418/MoneyManagerEx_dbgrpt-6688-20200617T061715.zip)

**Comment by vomikan** [comment]
Fixed. 

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33573651/job/bta0cyt20ripsr0i/artifacts
