### ISSUE TITLE
graphs text encoding

### ISSUE THREAD

**Issue by Reliable353** [moneymanagerex/moneymanagerex#2621]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows 10x64
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.5
  - [ ] 1.2.x
  - [ ] 1.1 or older
![Аннотация 2020-06-17 110249](https://user-images.githubusercontent.com/33018079/84873305-b44b5500-b08b-11ea-9683-6720605c86bb.jpg)

**Comment by vomikan** [comment]
Fixed. Thank you for your report.

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33573651/job/bta0cyt20ripsr0i/artifacts
