### ISSUE TITLE
Bring back word search in 'Notes' field.

### ISSUE THREAD

**Issue by jpweaving** [moneymanagerex/moneymanagerex#2624]
I used to be able to search the notes field using just one or two words, this would return all transactions where those works were contained in the 'Notes' field. Recently the search returns zero results, unless you enter the exactly the same character that are contained in the notes field you are looking for. This is an invaluable feature, if you want to find and item that you purchased, but can't remember which account you used of when you made the transaction.

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Use *item*

**Comment by jpweaving** [comment]
Brilliant. Problem solved. Thanks
