### ISSUE TITLE
circle diagram pop ups unreadable v.1.3.5, + "category: subcategory"

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2626]
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=9418

circle diagram pop ups unreadable v.1.3.5, + "category: subcategory"

 by vvmagic » 17 Jun 2020 17:54 
Hi. I'm return to v.1.2.3.. - v.1.3.4 very good, but due to "trunc left" - it's delete 'spases' between 'category:' and 'subcategory' at csv-import - so bad for readability on high dpi monitors.. if You will be so kind - to change at function - Model_Category::full_name (at Model_Category.cpp)- string:
return category->CATEGNAME + ":" + sub_category->SUBCATEGNAME;
to 
return category->CATEGNAME + ": " + sub_category->SUBCATEGNAME;
- insert spase after : at ":" - its will be very good..

v.1.3.5 - have same "trunc left" + circle diagram pop up messages will become 'unreadable' for russian lng - some encoding bug(- its so at html source too)..

- thank in advance..

with best wishes..

**Comment by whalley** [comment]
Code now supports user specified delimiter, so this is no longer and issue.

https://github.com/moneymanagerex/moneymanagerex/blob/ecf0d25144caa55f50f46ef93070313e8ad248be/src/model/Model_Category.cpp#L101
