### ISSUE TITLE
Unable to Download Launchable File

### ISSUE THREAD

**Issue by twodogron** [moneymanagerex/moneymanagerex#2627]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [x] Mac OSX
![Screenshot 2020-06-18 at 12 20 45](https://user-images.githubusercontent.com/35066458/85015827-93a0ff00-b160-11ea-87d0-9bd9f4fccc69.png)
 Running Catalina 10.15.5 Unable to launch, download is corrupt. see screenshot. This is after a dozen or more attempts at download from various sites.
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146

**Comment by vomikan** [comment]
This one should work:
https://sourceforge.net/projects/moneymanagerex/files/v1.3.5/mmex-1.3.5-macos10.9-wx3.1.3.dmg/download

**Comment by vinodraut** [comment]
> This one should work:
> https://sourceforge.net/projects/moneymanagerex/files/v1.3.5/mmex-1.3.5-macos10.9-wx3.1.3.dmg/download

Not working
