### ISSUE TITLE
Use fixed-width font in General Report Manager coding screens

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#2629]
I found it difficult to code in the General Report Manager for several reasons, but the easiest to fix would be using a fixed-width font. That way spaces line up consistently with other characters. 

With the current variable-width font, it is difficult to see if I have enough spaces at the beginning of the line, since the spaces are so skinny. 

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
I recommend to develop SQL outside.
My favourite is https://sqlitebrowser.org/
