### ISSUE TITLE
When adding new transaction, cannot close dialog if wrong value is encoded

### ISSUE THREAD

**Issue by phozen** [moneymanagerex/moneymanagerex#2630]
In the amount field, I enter the plus sign before number. A popup appear with error message, but I cannot clear the field, nor close it or cancel it.

The only workaround is to kill the process and start again.

![image](https://user-images.githubusercontent.com/17760168/85235021-02f14a00-b412-11ea-9d7f-759eae3be497.png)

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
mmex uses Lua calculator. 
The "+8+8" value is invalid. But 8+8 is valid.

**Comment by phozen** [comment]
On which version have you tested?

I'm on version 1.3.5

**Comment by vomikan** [comment]
I'm on version 1.3.5 too

**Comment by vomikan** [comment]
I can't reproduce this issue.
