### ISSUE TITLE
Unable to Change Date Format

### ISSUE THREAD

**Issue by twodogron** [moneymanagerex/moneymanagerex#2632]
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.
Date Format cannot be changed from YYYY-MM-DD to UK style DD-MM-YYYY……. Have made many many attempts but when exiting Options date format ALWAYS reverts back to YYYY-MM-DD.
<hr>Version: 1.3.5<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.3 (wxMac 10.15)<br>
 • wxSQLite3 4.4.8 (SQLite 3.30.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2<br>
<br>
Build: Jun 18 2020 23:34:51 <br>
 • CMake 3.16.3<br>
 • Xcode 11.4.1<br>
 • gettext 0.20.1<br>
 • Clang 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)
<br>
<br>
OS:<br>
 • macOS Catalina Version 10.15.5 (Build 19F101)<br>
 •  English (Western (Mac OS Roman))<br>
 • 1920x1080 32bit 94x94ppi

**Comment by 2BeeOrNot** [comment]
In option.cpp did you mean dateforMat, not dateforNat?

void Option::setDateFormat(const wxString& datefornat)
{
    m_dateFormat = datefornat;
    Model_Infotable::instance().Set("DATEFORMAT", datefornat);
}

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33680605/job/72kkhbgkoj2yhj50/artifacts

**Comment by twodogron** [comment]
I'm very sorry but I don't understand the solution. How can I change the Date Format in MMEX to a UK style DD-MM-YYYY format.......
Menu>MMEX>Options>General ?
Any changes made here do not persist when the Menu is closed.
macOS Caterina 10.15.5

**Comment by vomikan** [comment]
Sorry, I can't build binary file for MAC. 
I've implement fix for source code only.
Solutions:
1) Build mmex from scratch https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#macos-with-homebrew 
2) wait a next release. I think it will be available soon.
3) run mmex 1.3.3 then change a date format then start mmex 1.3.5

![image](https://user-images.githubusercontent.com/6836805/85397191-caf61e00-b55b-11ea-8129-5c8acae1bbcb.png)
