### ISSUE TITLE
MacOS - App start out of screen on dual monitors.

### ISSUE THREAD

**Issue by Sergius7** [moneymanagerex/moneymanagerex#2634]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [X] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.3, 1.3.4 and 1.3.5
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hi, I found an issue when using MacOS (10.15) with dual screen configuration. Every time I start the app, app screen gets created at primary screen (laptop screen) but way out margins. You can't reach the red, yellow and green buttons and bars, to move it back. It does every time I open the screen. I tried latest three stable versions.

Workaround is to, close the app (cmd+Q), change the laptop/primary screen resolution to something bigger that secondary display and play around with resolutions and opening/closing the app.

<img width="991" alt="App_Outscreen" src="https://user-images.githubusercontent.com/65726188/85348890-4a8bda80-b4d3-11ea-9c0a-0bdaf6ae766e.png">

Steps I made to reproduce this:

MacOS 10.15.
Two Monitors (HDMI attached).
Open the App (it will opened, most the times, at Primary screen).
Move it to secondary. Get it big enought to use most of the screen.
Secondary screen is upper the primary screen (note allign Tab at Screen configuration).
Close the App.
Open the App (generally will open as screenshot).

I believe that with some extra screen checks for position, this should be fixed.

**Comment by vomikan** [comment]
Possible this issue fixed in v1.3.6. release
https://sourceforge.net/projects/moneymanagerex/files/v1.3.6/
