### ISSUE TITLE
Account visible preferrence not saved

### ISSUE THREAD

**Issue by Patricen1** [moneymanagerex/moneymanagerex#2635]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hi!

Accounts visible preferrence is not saved anymore and comes back to default everytime MMEX is restarted, that's to say all acounts visible.
I'm using installed version, not portable one that could explain the issue.

**Comment by vomikan** [comment]
Can't reproduce it for 1.3.5
|  1 | 2  | 
|---|---|
| ![image](https://user-images.githubusercontent.com/6836805/85384633-01c33880-b54a-11ea-93be-a66aa0f9a530.png) |  ![image](https://user-images.githubusercontent.com/6836805/85384730-1acbe980-b54a-11ea-8d06-6f97428a0ad9.png) |

**Comment by Patricen1** [comment]
Ok, modification within tool / options menu works but not when right clicking on account list. This is probably done on purpose.

**Comment by vomikan** [comment]
It's feature not a bug. This option to temporary change settings until app closed.

**Comment by bregolino** [comment]
same issue in 1.3.6. is there any way to fix it ?
