### ISSUE TITLE
Feature request regarding edit transaction box

### ISSUE THREAD

**Issue by Patricen1** [moneymanagerex/moneymanagerex#2636]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hello,

When typing account or payee, it could be great that pressing enter once the payee is highlighted in the dropdown list would validate the entry. It is currently necessary to proceed to a left mouse click to validate the entry.
A long time ago, the feature existed, but not anymore.

Thanks!

**Comment by vomikan** [comment]
Please report OS version and mmex version.

**Comment by Patricen1** [comment]
Hello,
I'm working with Windows 10 version2004 and mmex 1.3.5
