### ISSUE TITLE
Money Manager Insist Database Is Open

### ISSUE THREAD

**Issue by Starkebogen** [moneymanagerex/moneymanagerex#2637]
Money Manager Insists the database is already open.  I have tried using backup copies from three days ago and also reinstalling Money Manager.  I feel sure I have missed something simple.  Any help or suggestions gratefully received.
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Ignore this message pressing Yes then reopen mmex.

**Comment by Starkebogen** [comment]
Many thanks for this suggestion vomikan.  

Unfortunately it doesn't work in this case.  What I have done is copied the MMEX database to a USB stick and opened that copy on another computer.  That works, which seems to show that the database is ok.  However, I cannot open the original database OR THE COPY on the original computer even after reinstalling Money Manager!

**Comment by vomikan** [comment]
1) the database is ok
2) create the folder c:\portable_apps
3) download and extract https://sourceforge.net/projects/moneymanagerex/files/v1.3.5/mmex-1.3.5-win64-portable.zip/download to c:\portable_apps
4) run "C:\portable_apps\mmex-1.3.5-win64\bin\mmex.exe" and open the copy of your DB.

**Comment by Starkebogen** [comment]
Thanks once again vomikan.  

I had managed to fix the problem before your second response.  I again uninstalled Money Manager and deleted the Money ManagerEX folder which was left in C:/Program Files (I had not done this in previous uninstall/re-installs).  I then downloaded and installed Money Manager -  and the problem seems to be resolved.

Many thanks for your help.
