### ISSUE TITLE
Can't generate print reports

### ISSUE THREAD

**Issue by mrcsmcl** [moneymanagerex/moneymanagerex#2642]
I'm not able to print reports. Once it get generated and I click to print the current view, it opens, but won't show anything and any of the buttons are clickable.

I tried another database that worked on the last version (1.3.4) and on Windows Sandbox, the same happens.

![image](https://user-images.githubusercontent.com/21992269/85924895-8fb16300-b86b-11ea-9fd5-cf06b03e5d42.png)

Version: 1.3.5
• Database version: 7 • (aes128cbc)

Running on:
• Windows 10 (build 19041), 64-bit edition
• Portuguese (Brazilian) (windows-1252)
• 1920x1080 32bit 96x96ppi

**Comment by vomikan** [comment]
Can't reproduce it.
Possibly it depend on default OS printer.

**Comment by mrcsmcl** [comment]
I was woking on previous version (1.3.4). It stopped after update.

**Comment by mrcsmcl** [comment]
Thanks, it worked. I reinstalled Windows PDF Printer and now it's working again.
