### ISSUE TITLE
MMEX damaged when mounting DMG

### ISSUE THREAD

**Issue by tindoge** [moneymanagerex/moneymanagerex#2644]
When downloading MMEX 1.3.5 from sourceforge,
it is reporting that the application is damaged on MacOS 10.15.5

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ X ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ X ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by tindoge** [comment]
Decided to have more of a look into this one and give a few extra details,
error message occurs when running the app from the DMG and also from the applications folder,
the cause of the error message is due to application signing.

When checking the application signature using spctl
`spctl -a -vvvv /Volumes/Money Manager Ex/mmex.app`
i get the error message 
/Volumes/Money Manager Ex/mmex.app: a sealed resource is missing or invalid

**Comment by 2BeeOrNot** [comment]
Right.

For others having this issue the program is not really damaged as Apple says.

MMEX is not signed and notarized with a Apple developer ID and with the com.apple.quarantine attribute it got from downloading from the internet it won't run without removing the com.apple.quarantine attribute.

MMEX does have a code signing resource but it is invalid.
I'm assuming the developer doesn't have a Apple developer ID or they would sign the application. A developer ID requires a yearly fee.

Removing the com.apple.quarantine attribute should allow MMEX to run. It always has for me on my two Mac's.

You can run `xattr -r -d com.apple.quarantine /Applications/mmex.app` after installing MMEX and before opening it or
you can run the command on the .dmg file before running it to install MMEX.

**Comment by vomikan** [comment]
@whalley could we close this issue?

**Comment by whalley** [comment]
Yes it can be closed the DMG and contents are now signed and notarized by Apple and should now install fine.
