### ISSUE TITLE
Recurring Transaction: Due & Paid dates got swapped around

### ISSUE THREAD

**Issue by ndt85** [moneymanagerex/moneymanagerex#2647]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

v1.3.5 have the Recurring Transaction's Due & Paid dates swapped around, which means that I cannot change the Payment date when I enter the transaction. Slightly related minor issue is the description text that's hidden under the repeating period selection...

Screenshot of v1.3.4:
![recurring v1.3.4](https://user-images.githubusercontent.com/67880310/86544340-798d5c00-bf69-11ea-9d26-a00228dba1fc.JPG)

Same screen in v1.3.5:
![recurring 1.3.5](https://user-images.githubusercontent.com/67880310/86544342-7befb600-bf69-11ea-94d1-813a83dfa2f0.JPG)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2434

**Comment by ndt85** [comment]
My take on the fields are:
- Due date is when the bill is dued, which is when I MUST pay it by, ie. The "pay by" date on the invoice, this doesn't change.
- Paid date is when I actually paid it, which may be earlier than the due date, or later.

My current situation is that changing current "Due date" when I enter the recurring transaction doesn't change when it gets entered into the other account - meaning that the "Paid date" value is used to make the transaction, which I cannot change and thus have to do it manually afterwards.

Will create a test account to get screenshots...

**Comment by ndt85** [comment]
Closing this one, will look more closely at the code change above and create new issue if required...
