### ISSUE TITLE
Cannot enter Recurring Transaction earlier than Date Paid

### ISSUE THREAD

**Issue by ndt85** [moneymanagerex/moneymanagerex#2649]
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

This may be because of how I'm using the Recurring Transactions... but here's the scenario:
1. Recurring transaction Dued on 22/07, with Date Paid as 15/07 (I normally pay around 1 week early, just in case of delayed processing)
![enter future](https://user-images.githubusercontent.com/67880310/86982348-64643780-c1cc-11ea-81c0-45cea26337e7.JPG)

2. Something came up and I need to make the payment now - eg. need to make a purchase on the card, so need to pay off some of the balance dued now...

3. the Enter dialog only allow changing Due date
- This seems wrong to me, since the bill's Due date didn't change, it's when I'm making the payment (ie. Date Paid) that's changing
- Setting the date to today
![changed date](https://user-images.githubusercontent.com/67880310/86982383-6e863600-c1cc-11ea-9466-a4272b2e95a0.JPG)

4. Transaction got entered with the existing Paid Date value instead.
![entered using date paid](https://user-images.githubusercontent.com/67880310/86982391-73e38080-c1cc-11ea-8e77-4d392a4ab30a.JPG)

For me, the following changes should be made:
1. Swap around Date Due and Date Paid for the various Recurring Transaction screens
- This will then allow Date Paid to be set when entering the transaction.
2. Allow setting Date Paid to any date when entering the Recurring Transaction:
- Above scenario shows potential for entering the transaction before both Date Paid & Date Due

Existing handling appears fine, summarising here for potential discussion...
- Date Due is when the transaction is dued, this usually doesn't change
- Date Paid is when it is planned to be paid, which cannot be later than Date Due when creating the Recurring Transaction
- You can set the "Date Due" (will be "Date Paid" after above proposed change) past the original Date Due => caters for late payment
- Computation of "next Date Due/Paid" already using original values from the Recurring Transactions, so changing the date when entering have no effect on the next one in the sequence, as expected.

Will take a look through the changes in #2434 to see if I can put together the potential changes for review...

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2647

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=10&t=9988
