### ISSUE TITLE
Database version 14?

### ISSUE THREAD

**Issue by jb-lopez** [moneymanagerex/moneymanagerex#2650]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ x ] Windows
-  Check MMEX version
  - [ x ] 1.4.x

I recently reinstalled my OS and am in the process of reinstalling all the programs. I've tried installing the latest v1.4.x build, but I get the error message `MMEX database version 14 doesn't work with this MMEX version`. It looks like the latest builds in the 1.4.x branch all use database version 13. I'm not sure where I got a build with database version 14.

Do you know which build is using database version 14? Or maybe there is a way to downgrade my database to database version 13?

Thank you for any help. I'd like to not have my years of data be lost.

**Comment by reddyshyam** [comment]
@jb-lopez, 1.4 version is discontinued. Please use 1.3.5

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by jb-lopez** [comment]
Thank you. Using the information in that issue I was able to get my database version to 13 so that I could open it in 1.4. It was a big help to know that it is just a SQLite file.

I reviewed the sql change file at [https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_14.sql](https://github.com/moneymanagerex/database/blob/master/incremental_upgrade/database_version_14.sql).

It appears that all I needed to do was to run the following to get to version 13.

```sql
PRAGMA user_version = 13;
```

The few other changes don't appear to be easily reversible, and it is now working fine.
