### ISSUE TITLE
Transaction Filter and Excel Export Issues

### ISSUE THREAD

**Issue by Aitxh** [moneymanagerex/moneymanagerex#2658]
1) In the new version recently released, the filter for transactions seems to have a bug and can no longer show transactions in the future. 

2) Also, the excel export from a personal report opens excel but no data is placed. 

- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
1) I can't reproduce this issue
![image](https://user-images.githubusercontent.com/6836805/89119898-58615200-d4ba-11ea-8c74-0c50148b5973.png)
2) Please create a new bug report with how to reproduce
