### ISSUE TITLE
Multi transactions update not available

### ISSUE THREAD

**Issue by freiheitsnetz** [moneymanagerex/moneymanagerex#2659]
When selecting multiple transactions entries no edit entry is available. It's grayed out. There are only 3 new entries, copy, delete and 2 mark entries. All other options (including edit) are grayed out.

- Check OS
    - [ ] Windows
    - [ ] Mac OSX
    - [x] Linux 
-  Check MMEX version
    - [x] 1.3.x git master branch
    - [ ] 1.3.x
    - [ ] 1.2.x
    - [ ] 1.1 or older

**Comment by freiheitsnetz** [comment]
Duplicate of which issue? I did not find any when I was looking for.  
Is there any way how I could help finding the cause of this bug?

**Comment by vomikan** [comment]
The feature request should be already opend 

The root issue:
https://github.com/moneymanagerex/moneymanagerex/issues/909#issuecomment-667582594
