### ISSUE TITLE
Notes search only works on first line of text

### ISSUE THREAD

**Issue by ILuvFreeSW** [moneymanagerex/moneymanagerex#2660]
Using the search box at the bottom of an account, which is meant for searching the transaction notes. It only returns transaction that have the search word/phrase in the first line of Notes.  For eg. if I search for "lunch", one transaction has a note that says "Texas Chicken @West Mall" in the first line, carriage return, and "lunch with Mr X" in the second line, this will not come up in the search. Only those with "lunch" in the first line will be found in the search.
![image](https://user-images.githubusercontent.com/12522008/89098972-9c067e00-d41e-11ea-9294-dfd39d2594b5.png)

Using the built-in _Transaction Report_ under **Reports**.
![image](https://user-images.githubusercontent.com/12522008/89098988-c5bfa500-d41e-11ea-8c0d-f1d5109258d5.png)
If we key-in "lunch*" in the _Notes_ search field, similarly only those transactions with the word "lunch" in the first line will be found.
![image](https://user-images.githubusercontent.com/12522008/89099236-62cf0d80-d420-11ea-896e-c6b74c2bd4f7.png)

I am not sure this is by design, or if it is a bug. It sure looks more like a bug or oversight to me, it doesn't make sense to design a search feature that only search the first line.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Please use *lunch*

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/2295
