### ISSUE TITLE
CSV export for "balance" field causes TYPE CONV error when imported in ACCESS

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/moneymanagerex#2662]
[airtel.zip](https://github.com/moneymanagerex/moneymanagerex/files/5010938/airtel.zip)
there is a gap in number e.g. 4709 is 4 709 which causes the problem; please check attached zip file with csv file
There is no problem with Amount field

**Comment by vomikan** [comment]
Could you try to change an account currency format before export?

**Comment by rmkhalfay** [comment]
Sir, I could not find any option to change currency format. I checked in Tools / Organize Currency. My currency is set to 2 decimals and Indian rupee (INR); Please advise how to change currency format?

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/34433731/job/qjkkibky1tv39kro/artifacts

**Comment by rmkhalfay** [comment]
Now same problem is for AMOUNT field in version 1.3.6; there is a gap in number e.g. 4709 is 4 709 which causes the problem;
