### ISSUE TITLE
Branch 1.3.5 misses commits or is it intended?

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#2669]
MMEX version:
  - [ ] 1.4.X
  - [X] 1.3.5
  - [ ] 1.3.4
  - [ ] 1.3.3 or older

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 

# Description of the bug

I compiled the 1.3.5 branch and started MMEX.
It welcomed me with the warning, that I use RC1 and not the stable 1.3.5 version.
Does the 1.3.5 branch misses commits or is that intended?
As example the https://github.com/moneymanagerex/moneymanagerex/commit/5825a39c6043a1edc9a4f496472caa3a40c25dc6 is missing.

# Reproduction

Reproduction steps:

1. Checkout 1.3.5
2. Compile it
3. Run it

Expected result:

Running 1.3.5 stable

Actual result:

Running 1.3.5 RC1

# Additional information

I'm now trying to maintain the Arch AUR package for MMEX since MMEX is my favorite a money app.
https://aur.archlinux.org/packages/moneymanagerex-git/

**Comment by vomikan** [comment]
Master branch is 1.3.5 - 1.3.6

**Comment by vomikan** [comment]
@guanlisheng could you please delete branches 1.3.4 and 1.3.5 & They are deprecated.

**Comment by MartinX3** [comment]
Thank you for the clarification!

I will point the AUR package to the git tag instead of the commit!
