### ISSUE TITLE
Account Advanced filter Un-Reconciled does not working

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2671]
MMEX version:
  - [ ] 1.4.X
  - [x] 1.3.5
  - [ ] 1.3.4
  - [ ] 1.3.3 or older

Operating System:
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
![image](https://user-images.githubusercontent.com/6836805/89163749-ba838b00-d57e-11ea-8f1f-9126e12a25fa.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly
 - [ ] Happened only once

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2631

**Comment by MartinX3** [comment]
Is it possible to release a v1.3.6 @vomikan ? :)
