### ISSUE TITLE
Not working after 1st us.

### ISSUE THREAD

**Issue by Matt-ui-hub** [moneymanagerex/moneymanagerex#2675]
I installed the new update to windows 10, I run the program and the first time it works just fine. Next time I run the program and select the last used file. the program the goes to my system tray. I try running it from there and I get the message that it cannot open the program because and application is using the db. 
I dont have anything else using it.

**Comment by vomikan** [comment]
Could you please provide printscreen?
Also 
> mmex.exe /s 

may be avoid this message. 
![image](https://user-images.githubusercontent.com/6836805/89705625-9a314300-d967-11ea-8eb5-9f81e1c8f9d0.png)

**Comment by Matt-ui-hub** [comment]
[image: image.png]
I ran the program and selected to open an existing file
"When I pick the file which is in my documents dir. I get
"this screen and if I say yes nothing happens.

**Comment by vomikan** [comment]
The image not visible.

**Comment by Matt-ui-hub** [comment]
Thanks for what you have tried to tell me. I is working fine on my Lunix
system so I am giving up on the windows version

**Comment by Matt-ui-hub** [comment]
as an fyi. I have windows 10 on a laptop running mmex ( the
previous version. I am not having any problems on that pc. and as I said my
linux laptop also no problem. It is on the 2 desktop with windows 10 and
the new version of mmex. that is where I am having the problems.
