### ISSUE TITLE
Transaction number automatic 

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/moneymanagerex#2676]
# Description of the feature

Please keep option in setting to automatically enter the next transaction number instead of entering every time with +1
![20200807_223206](https://user-images.githubusercontent.com/53577940/89677476-91585700-d8fe-11ea-9565-28a059ad6f19.jpg)
This will save lot of data entry time and also user can have option to manually enter also

**Comment by vomikan** [comment]
Please report it here:
https://github.com/moneymanagerex/android-money-manager-ex/issues
