### ISSUE TITLE
Transaction Filter, Notes search now only returns exact results

### ISSUE THREAD

**Issue by metalthrashingdan** [moneymanagerex/moneymanagerex#2683]
MMEX version:
 - [ ] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In the Transaction Filter for version 1.3.5, the Notes search now only finds entries with the exact words entered e.g. searching "interest" only returns transactions with "Interest" as the whole of the note (no additional words) and the filter doesn't return any results which contain the word interest along with other words such as an entry reading "Cashback (interest)". Searching in version 1.3.4 used to return all entries containing the word interest which was very useful.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result: Transaction Filter, Notes search returns all entries that contain the search terms regardless of other words present.

Actual result: Transaction Filter, Notes search returns only entries that contain the search terms exactly with no other words present.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2660

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=9851

![image](https://user-images.githubusercontent.com/6836805/133889094-beac488a-6526-4924-87dd-07263b2df1b4.png)
