### ISSUE TITLE
Application crash when selecting 'Relocate Payee' when in the "Organize Payees' dialog

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2684]
MMEX version:
 - [ ] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Application crash when selecting 'Relocate Payee' when in the "Organize Payees' dialog.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Select Tools / Organize Payees from the menu
2. Right click on any Payee and select 'Relocate Payee'

Expected result:

Should bring up the 'Relocate Payee Dialog'  with the selected Payee in the 'Relocate:' field

Actual result:

Application crash

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by didikrm** [comment]
This bug has been around since at least 1.3.3. Note that you get the same result (crash) when you select a payee then click on "other tools" on bottom right. The workaround is to got Tools -> Relocation of ... -> Payees. That does not seem to crash the app.

**Comment by vomikan** [comment]
Screenshot please. I can't reproduce this issue.

**Comment by didikrm** [comment]
[Here](https://imgur.com/a/l5XVRM7) it is.

**Comment by whalley** [comment]
It's fixed in 1.3.6-RC.1

**Comment by didikrm** [comment]
Thanks. I am still on 1.3.5.
