### ISSUE TITLE
Build issue with LuaGlue - Not declared name luaL_checkint

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#2685]
MMEX version:
 - [X] 1.5.6
 - [X] 1.5.1
 - [X] 1.5.0
 - [X] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux 

# Description of the bug

```[ 40%] Building CXX object src/CMakeFiles/mmex.dir/optionsettingsattachment.cpp.o
In file included from /tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueFunction.h:10,
                 from /tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlue.h:12,
                 from /tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/mmTextCtrl.cpp:23:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueApplyTuple.h: In function ‘LuaGlueClass<_Class>* getGlueClass(LuaGlueBase*, lua_State*, int)’:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueApplyTuple.h:20:11: error: there are no arguments to ‘luaL_checkint’ that depend on a template parameter, so a declaration of ‘luaL_checkint’ must be available [-fpermissive]
   20 |  int id = luaL_checkint(s, -1);
      |           ^~~~~~~~~~~~~
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueApplyTuple.h:20:11: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueApplyTuple.h: In static member function ‘static int stack<int>::get(LuaGlueBase*, lua_State*, int)’:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/3rd/LuaGlue/include/LuaGlue/LuaGlueApplyTuple.h:181:10: error: ‘luaL_checkint’ was not declared in this scope; did you mean ‘luaL_checkany’?
  181 |   return luaL_checkint(s, idx);
      |          ^~~~~~~~~~~~~
      |          luaL_checkany
make[2]: *** [src/CMakeFiles/mmex.dir/build.make:550: src/CMakeFiles/mmex.dir/mmTextCtrl.cpp.o] Error 1
```

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Compile MMEX with tag v1.3.5
I use https://aur.archlinux.org/packages/moneymanagerex-git/
That's th ebuild script https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moneymanagerex-git
…

Expected result:
A working build.

Actual result:
Not working anymore.

# Additional information

Maybe since my computer got the package update lua v5.4.0-2

```
Version: 1.5.1 64-bit
• Aufbauend auf Apr 25 2021 10:48:35
• Datenbankversion: 7 • (aes128cbc)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.0.5 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.4.3
• lunasvg 
• libcurl/7.76.1 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0
• gettext 0.21
• apexcharts.js
Genutztes Build:
• CMake 3.20.1
• GNU Make 4.3
• GCC 10.2.0 • EndeavourOS rolling 'rolling'
Läuft auf:
• EndeavourOS Linux "rolling"
• Linux 5.11.16-zen1-1-zen x86_64
• German (UTF-8)
• 3200x1980 24bit 95x95ppi 
```

**Comment by jpgreen18** [comment]
Thank you @fhanzen, your workaround helped me.

Unfortunatly I got this error on build later.

`❯ cmake --build . --target package
[  1%] Generated translations
[  4%] Built target HTML-template
[  4%] Built target SQLite3
[  4%] Built target Translations
[  6%] Built target wxSQLite3
[  7%] Linking CXX executable mmex
/usr/bin/ld: CMakeFiles/mmex.dir/model/Model_Report.cpp.o: in function `Model_Report::get_html(DB_Table_REPORT_V1::Data const*, wxString&)':
Model_Report.cpp:(.text+0x4e54): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: Model_Report.cpp:(.text+0x5509): undefined reference to `lua_newuserdatauv'
/usr/bin/ld: CMakeFiles/mmex.dir/model/Model_Report.cpp.o: in function `LuaGlueCtorMethod<Record>::lua_call_func(lua_State*)':
Model_Report.cpp:(.text._ZN17LuaGlueCtorMethodI6RecordJEE13lua_call_funcEP9lua_State[_ZN17LuaGlueCtorMethodI6RecordJEE13lua_call_funcEP9lua_State]+0x63): undefined reference to `lua_newuserdatauv'
collect2: Fehler: ld gab 1 als Ende-Status zurück
gmake[2]: *** [src/CMakeFiles/mmex.dir/build.make:1729: src/mmex] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:267: src/CMakeFiles/mmex.dir/all] Fehler 2
gmake: *** [Makefile:171: all] Fehler 2`

My system is Fedora 33 see below
❯ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found wxWidgets: -pthread;;;-lwx_gtk3u_core-3.0;-lwx_gtk3u_qa-3.0;-lwx_gtk3u_html-3.0;-lwx_baseu_xml-3.0;-lwx_gtk3u_aui-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_stc-3.0;-lwx_gtk3u_webview-3.0;-lwx_baseu-3.0 (found suitable version "3.0.5", minimum required is "2.9.2") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Checking for one of the modules 'libcurl'
-- Found CURL: /usr/lib64/libcurl.so (found version "7.71.1")
-- RapidJSON found. Headers: /usr/include
-- Found RapidJSON: /usr/include
-- Found Lua: /usr/lib64/liblua-5.3.so;/usr/lib64/libm.so (found version "5.4.2") 
-- 
-- MMEX configuration summary
-- ==========================
-- Version        : 1.3.6
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.10.16-200.fc33.x86_64
-- Fedora 33 'ThirtyThree'
-- CMake 3.18.4
-- GNU Make 4.3
-- ccache
-- GNU 10.2.1
-- wxWidgets 3.0.5
-- wxSQLite3 4.6.0
-- RapidJSON 1.1.0
-- Lua 5.4.2
-- curl 7.71.1
-- gettext 0.21

Hope you can help me

**Comment by fhanzen** [comment]
@jpgreen18, be sure that you are building against lua 5.4 or above. See [http://www.lua.org/manual/5.4/manual.html#8.3](http://www.lua.org/manual/5.4/manual.html#8.3) for additional information. Your log shows:

> -- Found Lua: /usr/lib64/liblua-5.3.so;/usr/lib64/libm.so (found version "5.4.2")

This says 5.4.x was found, but the filename of the shared object suggests otherwise.

**Comment by jpgreen18** [comment]
Thank you a lot for your help @fhanzen 
I think an environment variable wasn't correct. A reboot solved the problem.

**Comment by MartinX3** [comment]
Should get fixed by https://github.com/moneymanagerex/LuaGlue/pull/6

**Comment by MartinX3** [comment]
@vomikan is it possible to merge this hotfix, too? :)

**Comment by MartinX3** [comment]
@vomikan please reopen this issue ticket because of https://github.com/moneymanagerex/moneymanagerex/pull/4164

**Comment by MartinX3** [comment]
Thank you, @vomikan 
I think it should get the `v1.5.13` milestone.
