### ISSUE TITLE
Regression in Transaction report feature

### ISSUE THREAD

**Issue by Marc69009** [moneymanagerex/moneymanagerex#2688]
MMEX version:

 - [X] 1.3.5
 
Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows

# Description of the bug

In "Transaction report" window , when Notes field is selected, and a text enterred for filtering corresponding records, it does not work anymore. The list which is displayed is blank

Works perfectly on 1.3.3, and has been working for years on older versions.

Very useful for obtaining a fllter based on a string contained in the Notes field

# Reproduction

Is the bug reproducible? 
 - [X] Always 

Reproduction steps:

1. Click on Transaction Report" 
2. Enter the text in the Notes field, and click the box
3. Click on OK

Expected result:

The list of transactions which "Notes" field contains the given text

Actual result:

Empty list

# Additional information

Very easy to reproduce, was working perfectly, on older versions
Nikolay sent me an email, asking me to do it again, using tha basic way, as explaned above, but it really does NOT work
I have 2 versions of mmex installed on my computer
1.3.3==> works perfectly
1.3.5==> does not work
I am really convinced it's a regression

**Comment by vomikan** [comment]
Try *text* to search any text string in notes.

**Comment by whalley** [comment]
Have tried this on 1.3.5 and 1.3.6rc1 and you can search using the Notes field but it seems to only match from beginning of field.
E.g. if I have a Note of "ABC DEF" I can search for and find "ABC", but not "DEF"

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/92220191-494c3600-eea4-11ea-8b78-99d14ad07a56.png)

**Comment by Marc69009** [comment]
Great !!! Many Thanks....

It works...

Marc


Le 04/09/2020 à 10:46, Nikolay a écrit :
