### ISSUE TITLE
Incorrect currency translation

### ISSUE THREAD

**Issue by tianainanetapsys** [moneymanagerex/moneymanagerex#2691]
Sorry to write it in here.
But I can't find how to modify the translation (or the abbreviation)  of the currencies?
Actually Money from Madagascar is Ariary, should be shortned as MGA but not FMG as it is displayed in the application.
I can't find it on https://crowdin.com/
Thanks

**Comment by vomikan** [comment]
In case if you can't change currency code I recommend to add new record and assign accounts to new currency.
![image](https://user-images.githubusercontent.com/6836805/92583043-6d3fbb00-f29a-11ea-93e0-bd8e170808c9.png)

**Comment by vomikan** [comment]
v1.3.5
![image](https://user-images.githubusercontent.com/6836805/92583190-a4ae6780-f29a-11ea-9d2a-ed214a902851.png)

**Comment by tianainanetapsys** [comment]
OK Thanks.
So I could edit the currency (I didn't know I could).
I thought it was hard coded in some translation file.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/09/20,
02:53:05 PM
