### ISSUE TITLE
Bug bomb on 9/11/20 Crash adding not subtracting deductions and cannot install new or old versions to fix 

### ISSUE THREAD

**Issue by SniperViperReal** [moneymanagerex/moneymanagerex#2692]
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.

<hr>Version: 1.3.5<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.3 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.59.0-DEV WinSSL<br>
<br>
Build: Jun 17 2020 10:30:46 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1600x900 32bit 72x72ppi

**Comment by vomikan** [comment]
What?
