### ISSUE TITLE
Build fails with wxSQLite3 4.6.0

### ISSUE THREAD

**Issue by rezso** [moneymanagerex/moneymanagerex#2693]
MMEX version:
 - [ ] 1.3.6
 - [x] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Build fails with wxSQLite3 4.6.0:

CMake Error at 3rd/CMakeLists.txt:171 (add_library):
  Cannot find source file:

    wxsqlite3/sqlite3secure/src/sqlite3secure.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at 3rd/CMakeLists.txt:171 (add_library):
  No SOURCES given to target: SQLite3

CMake Generate step failed.  Build files cannot be regenerated correctly.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

# Additional information

Reason:
https://github.com/utelle/wxsqlite3/commit/8afbf1e8841f13d3b2e2a11765cc047b66971225

**Comment by PMaff** [comment]
Were you able to build the latest stable 1.5.12 ?

**Comment by rezso** [comment]
No, same error, because 'git clone https://github.com/utelle/wxsqlite3.git' (or 'git submodule update --init') gets wxsqlite3 4.7.6, but the wxsqlite3/sqlite3secure/src/sqlite3secure.c file removed in wxsqlite3 4.6.0. So you need to update the 3rd/CMakeLists.txt file.

**Comment by PMaff** [comment]
How does your `cmake .` output look like?
On Ubuntu 18.04 with the current 1.5.14-Beta.1 I have:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.14-Beta.1
-- Commit         : 059e5b73c (2022-03-28)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 4.15.0-175-generic
-- Ubuntu 18.04 'bionic'
-- CMake 3.22.0
-- GNU Make 4.1
-- ccache 3.4.1
-- GNU 7.5.0
-- wxWidgets 3.1.5
-- wxSQLite3 4.6.0
-- Lua 5.3.3
-- curl 7.58.0
-- gettext 0.19.8.1
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done
```

Compilation works without problems.
See also:
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#3-compile-and-create-package

**Comment by rezso** [comment]
-- 
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.14
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Ninja
-- Install prefix : /usr
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.10.103-1.x86_64
-- UHU-Linux UBK4 'PAFF'
-- CMake 3.21.2
-- Ninja 1.10.2
-- ccache 4.6
-- GNU 10.2.0
-- wxWidgets 3.1.6
-- wxSQLite3 4.7.9
-- Lua 5.3.6
-- curl 7.82.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring done
CMake Error at 3rd/CMakeLists.txt:181 (add_library):
  Cannot find source file:

    wxsqlite3/sqlite3secure/src/sqlite3secure.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at 3rd/CMakeLists.txt:181 (add_library):
  No SOURCES given to target: SQLite3


CMake Generate step failed.  Build files cannot be regenerated correctly.

Same error with the release tarball, at commit https://github.com/utelle/wxsqlite3/commit/8afbf1e8841f13d3b2e2a11765cc047b66971225
But the 4.6.0 release number appears at the previous commit: https://github.com/utelle/wxsqlite3/commit/664eca3250d82e7984070bd61ab62ae2b409d296

So  sqlite3secure.c removed from wxsqlite3: https://github.com/utelle/wxsqlite3/tree/main/src

**Comment by grumpy235** [comment]
@rezso You are now trying to compile with wxSQLite3 4.7.9 rather than 4.6.0 which is the version used by mmex 1.5.14 source. As you have found Utelle made considerable changes to the way encryption is delivered in 4.7.x and this will require some small changes to the mmex source...

Change #include "sqlite3.h" to #include "sqlite3mc_amalgamation.h" in modules src\dbwrapper.cpp & src\model\Model_Report.cpp

and a rather larger change to 3rd/CMakeLists.txt.

I have got a working version for Win11 by some hit/miss manipulation of 3rd/CMakeLists.txt but my knowledge of Cmake is next to zero I'm afraid and that also goes for Linux so not sure if it would work for Linux.
Your best bet would be to ask @vomikan or @whalley what plans they have to upgrade to the latest version of wxSQLite3.

**Comment by PMaff** [comment]
> ## --
> -- MMEX configuration summary
> -- ==========================
> -- Version : 1.5.14
> -- Host system : Linux x86_64
> -- Target system : Linux x86_64
> -- Build types : Release
> -- Generator : Ninja
> -- Install prefix : /usr
> -- DB encryption : ON


I just wonder about:
`Generator : Ninja`
Why are you using ninja here and not the normal cmake or alike?

On my side:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.14
-- Commit         : 29d21c327 (2022-04-14)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
```

**Comment by PMaff** [comment]
@vomikan : this is quite old, shall we close this since there is no answer from @rezso ?

**Comment by rezso** [comment]
@PMaff : using the ninja generator with cmake is not relevant here. 
I get wxsqlite code with:
git clone https://github.com/utelle/wxsqlite3.git 3rd/wxsqlite3
    cd 3rd/wxsqlite3
    git checkout 01150d2
    cd -

With this checkout the build is succesful. With newer commits not.
