### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by davideschiano** [moneymanagerex/moneymanagerex#2696]
More than an issue this is a point of view about all issues on android version and some on desktop version (but also on ios version at this point). Why not create a web app version? There is the database in sql (the core). A web app will solve many issues and problems and will ensure a future to moneymanager in next years.

**Comment by vomikan** [comment]
Related issue: #2687

**Comment by vomikan** [comment]
Could you try this solution.
https://github.com/moneymanagerex/web-money-manager-ex

Related issue #2687
