### ISSUE TITLE
Unable to change column width in account view (or any other view)

### ISSUE THREAD

**Issue by b-trav** [moneymanagerex/moneymanagerex#2698]
MMEX version:
 Version: 1.3.5
• Database version: 7 • (aes128cbc)

Operating System:
 - Linux 

# Description of the bug

I am running MMEX on a Dell XPS 13 (4K), running Ubuntu 18.04.

I cannot resize the column width. I hover the mouse over border of the column labels, but there is no option to resize them. This is necessary, because I cannot see the figure for amounts larger than -10,000.00.

# Reproduction

Is the bug reproducible? 
 - Always 

Reproduction steps:

1. Open an Account View
2. Attempt to resize "Balance" column 

Expected result:

Cursor changes to "resize cursor" and shifts column width

Actual result:

Cursor does not change, and column width cannot be changed.

**Comment by PMaff** [comment]
Tried this also with 1.5.14-beta.1 on Ubuntu 18.04 
@b-trav : is that what it should do?
: 

https://user-images.githubusercontent.com/93879362/160929884-f3c60af8-d77c-43f2-a576-3a7cdc09d599.mp4

**Comment by b-trav** [comment]
Yep, thanks. Appears to be all fixed. :+1:
