### ISSUE TITLE
Sum selected lines

### ISSUE THREAD

**Issue by keinejiang** [moneymanagerex/moneymanagerex#2699]
There was a feature to sum selected lines in 1.4.0 alpha 7. It is missed in 1.3.5 and 1.3.6. Could you please bring it back?

It is better to sum in "income”, “expense", and "total" separately.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/909

**Comment by vomikan** [comment]
done
