### ISSUE TITLE
Currency thousand's comma missing

### ISSUE THREAD

**Issue by hg6135** [moneymanagerex/moneymanagerex#2701]
![Capture](https://user-images.githubusercontent.com/8367629/95668988-8ccb4b80-0b98-11eb-87cd-5a78d97a977d.PNG)

![Capture1](https://user-images.githubusercontent.com/8367629/95669001-a79dc000-0b98-11eb-81c3-2e648b59ac82.PNG)

version 1.3.5

This issue was not there in ver 1.3.4

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2473
