### ISSUE TITLE
MMEX always tries to connect to vps.moneymanagerex.org on startup

### ISSUE THREAD

**Issue by acicovic** [moneymanagerex/moneymanagerex#2705]
# Environment

MMEX version: 1.3.5
Operating System: Windows 10

# Description

Even though all options in the Network section are disabled, Money Manager Ex tries to connect to vps.moneymanagerex.org upon program startup.

Reproduction steps:

1. Install a firewall
2. Start Money Manager Ex
3. View firewall results

…

Expected result: The program shouldn't try to connect anywhere

Actual result: The program tries to connect to vps.moneymanagerex.org

**Comment by vomikan** [comment]
I can't reproduce this issue.

**Comment by acicovic** [comment]
For firewall, I use SimpleWall:
https://github.com/henrypp/simplewall
https://www.henrypp.org/product/simplewall

I'm using MMEX portable from PortableApps (https://portableapps.com/apps/office/money_manager_ex_portable).

Thanks!

**Comment by whalley** [comment]
The application actually connects to www.moneymanagerex.org, which resolves to **vps.moneymanagerex.org** (162.243.11.131).

From a cursory glance I think it may be the call to getNewsRSS in mmframe.cpp that is making the request. There does not seem any option to disable this.

**Comment by whalley** [comment]
Resolved by 00226f2aed09986eb5a3b7c177aaf4b88a1a60eb 
Can be marked as fixed.

**Comment by whalley** [comment]
@acicovic Are you happy to close this now?

**Comment by vomikan** [comment]
Binary files for Windows are available here:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37804404/job/eyj5d1k4pmkd3nsv/artifacts

**Comment by acicovic** [comment]
Hi guys,

Back then I used MMEX portable edition to find out if it was suitable for someone else, but since then I'm not using it actively. I just downloaded and tested the portable version from the above URL and it's working fine, no unexpected connections appear.

Closing this.
