### ISSUE TITLE
The main window does not appear after the last installation of Windows 10 updates

### ISSUE THREAD

**Issue by havana7** [moneymanagerex/moneymanagerex#2710]
MMEX version:
1.3.5

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows

# Description of the bug
The main window is not displayed, it remains in the vindows bar and does not even show the preview.

If I create a new database the configuration windows are shown but never the main one.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 

Reproduction steps:

1. Open file

Expected result:
Open normally

Actual result:
As attached

![Screenshot](https://user-images.githubusercontent.com/394454/97105272-e1eb7f00-16b9-11eb-836f-65cd740614a2.png)

![Windows update log](https://user-images.githubusercontent.com/394454/97105324-270fb100-16ba-11eb-84e0-1cba42997033.png)

**Comment by vomikan** [comment]
#2694
