### ISSUE TITLE
Libcurl missing

### ISSUE THREAD

**Issue by martinrotter** [moneymanagerex/moneymanagerex#2714]
MMEX version:
 - [x] 1.3.6
 - [ ] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

![image](https://user-images.githubusercontent.com/1255302/98332832-be043380-1fff-11eb-93d0-c24245d5ec3f.png)

I was able to fix the bug by manually downloading `libcurl.dll` from official Curl website.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
@martinrotter Is this still an issue or can we close?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3241
