### ISSUE TITLE
MMEX macOS Apple silicon doesn't run

### ISSUE THREAD

**Issue by MassimilianoPasquini97** [moneymanagerex/moneymanagerex#2724]
MMEX version:
 - [ ] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX doesn't run under rosetta 2, mmex is broken can't be open.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Install Amex
2. Open mmex

Expected result:

mmex run

Actual result:

mmex is broken can't be open.

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146
