### ISSUE TITLE
Split transaction

### ISSUE THREAD

**Issue by rolly2002** [moneymanagerex/moneymanagerex#2727]
# it would be interesting to be able to enter the payee and notes for each item of a split transaction

Please describe your feature with details.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/910
