### ISSUE TITLE
Thousands separator no longer works in 1.3.5

### ISSUE THREAD

**Issue by TomAALTER** [moneymanagerex/moneymanagerex#2728]
MMEX version:
 - [ ] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The thousands separator no longer works. Before switching to stable version 1.3.5 I was still using 1.3.3. On version 1.3.3 the thousands separator works fine, but it does no longer work on version 1.3.5

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Go to valuta manager
2. Go to EUR and check the thousands separator
![moneymanager bug thousands separator](https://user-images.githubusercontent.com/3484331/101277642-2dfc0a00-37b6-11eb-931c-5b0cc4467118.PNG)

3. 

…

Expected result:

€ 123.456,78

Actual result:

€123456,78

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/101278032-a4eece00-37c9-11eb-83a4-c58372293f59.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2473
