### ISSUE TITLE
json data for Google statistics

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2733]
@guanlisheng what do you think if I change the stucture?
Current json data sample for Google statistics:
```
{
"usage":[
{
"module":"Home Page",
"seconds":0.288
},
{
"module":"Report",
"name":"Income vs Expenses Summary - Current Month",
"seconds":5.415
},
{
"module":"Report",
"name":"Income vs Expenses Monthly - Current Month",
"seconds":2.133
},
{
"module":"Report",
"name":"Income vs Expenses Monthly - Last 365 Days",
"seconds":0.03
}
]
}
```
I suggest the following data structure:
"modeule":"Report", "name":"xxx - xxx","seconds":0.03
"module":"Panel","name":"Checking","seconds":0.03
"module":"Dialog","name":"Currency manager","seconds":0.03
etc

**Comment by guanlisheng** [comment]
hey @vomikan, not quite sure which data structure you are referring to. would you expatiate？

**Comment by vomikan** [comment]
That your code:
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmex.cpp#L406-L414

I thought this code sends statistics to Google. But it doesn't seem to be.

**Comment by vomikan** [comment]
I want to fix the following issue:
![image](https://user-images.githubusercontent.com/6836805/102534602-170fbe80-40b8-11eb-8ac2-ac36acb6c751.png)
The same interface has a name in different languages.

**Comment by guanlisheng** [comment]
I would like to keep it unchanged as we have both document path and title separately.
