### ISSUE TITLE
1.3.6 rc1 installation issue.

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#2743]
MMEX version:
 - [ x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 10 pro 64 bit 20h2

# Description of the bug

After installing the setup file, the attached error happens. This has been happening for over 6 months now.

![Screenshot 20201214 2224](https://user-images.githubusercontent.com/12392746/102110659-72914080-3e5b-11eb-9d51-29fda3c07ed9.png)

**Comment by vomikan** [comment]
Please use the following files:
32-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/2p7800dsc7j96leg/artifacts
64-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/p3du7218yegg80ip/artifacts

**Comment by reddyshyam** [comment]
Hi @vomikan, thanks for that. All good now. 👍
