### ISSUE TITLE
Why did you stop working on Version 1.4?

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#2744]
Why did you stop working on Version 1.4?

**Comment by vomikan** [comment]
In version 1.4.0-Alpha, many changes were made to the database structure and many new features were announced. But the team did not cope with the tasks set.

I decided to make useful changes in the stable and most popular stable version 1.3.4. As a result, the release 1.3.6 will be released soon.

I am working on v. 2.0.0 much attention will be paid to investments.
https://github.com/vomikan/moneymanagerex/tree/v2.0.0

Cases:
https://github.com/moneymanagerex/moneymanagerex/issues/2147
https://github.com/moneymanagerex/moneymanagerex/issues/2702

**Comment by TomAff** [comment]
Great. When will the download of the first "testversion" for windows be available approximately?

**Comment by vomikan** [comment]
1.3.6-RC.1 already available
32-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/2p7800dsc7j96leg/artifacts
64-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/p3du7218yegg80ip/artifacts

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-3a1ac24b5a917cfe80d5

**Comment by vomikan** [comment]
Regarding "testversion" (2.0.0) I can't provide  a specific time frame...

**Comment by TomAff** [comment]
I will have a look on this right know.

I remeber, that in 1.3.5 Attachments were not shown in reports when using
<a href="../MMEX_privat_Attachments/Transaction/<TMPL_VAR Filename>">

This doesn't work in 1.3.6 too.
In 1.4 it works 👍 

Finanly. Thanks for your time and MMEX.

Let me know if you have any questions regarding accounting or the german commercial law ;)

**Comment by vomikan** [comment]
```I remeber, that in 1.3.5 Attachments were not shown in reports when using```
What kind of reports you are talking about?
Let's fix it fefore 1.3.6 release.

**Comment by TomAff** [comment]
I created my own report with the custom report manager.

Using the old "alldata" view and added
left join attachment att on att.REFID=cans.transid
to get ATTACHEMENT.Filename

HTML
a href="../MMEX_privat_Attachments/Transaction/<TMPL_VAR Filename>

In 1.4 the PDF is shown in MMEX-Window

In 1.3 I get an error
![error](https://user-images.githubusercontent.com/46572503/102261139-8bf4c400-3f11-11eb-8e7b-5a8dfcfccd09.jpg)

No access to page

• Make sure the web address //ieframe.dll/dnserrordiagoff.htm# is correct.
• Find this website on Bing
•Refresh page

**Comment by vomikan** [comment]
Here is a sample code
https://github.com/vomikan/moneymanagerex/commit/d8953c6678369783d290cd6c746ec8ea0ecec9aa

Try to add target='_blank' into all <a href= in custom reports

**Comment by TomAff** [comment]
tried it.
![2020-12-15 20_32_15-Window](https://user-images.githubusercontent.com/46572503/102263728-feb36e80-3f14-11eb-810d-20f3268293c6.jpg)
...then nothing happend.

link properties
![2020-12-15 20_35_18-Window](https://user-images.githubusercontent.com/46572503/102263857-273b6880-3f15-11eb-9e04-b9166741d117.jpg)

**Comment by vomikan** [comment]
Related issue
https://github.com/moneymanagerex/moneymanagerex/issues/2394

**Comment by TomAff** [comment]
Sorry. I do not know how to handle it.
what should I write behind a href= ?

**Comment by vomikan** [comment]
I think it should be SQL like this:
```
with p as (
select 'file://C:\Dev\mmex\MMEX_recent_7_Attachments\' path
)
select p.path||a.FILENAME, t.* from ATTACHMENT_V1 a
left join CHECKINGACCOUNT_V1 t  on a.REFID=t.TRANSID
left join p
```

**Comment by vomikan** [comment]
Could you export your report? I've adopted it.

**Comment by TomAff** [comment]
[Report.zip](https://github.com/moneymanagerex/moneymanagerex/files/5698365/Report.zip)

**Comment by vomikan** [comment]
That my report. Just for check how links working.
[Attachments.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/5698692/Attachments.grm.zip)

**Comment by TomAff** [comment]
I have donwloaded the new version an tested your report Attachments.grm.zip

Link with "attachement:" works
file-link  file:// don't (nothing happens)
![2020-12-25 11_14_26-Eigenschaften](https://user-images.githubusercontent.com/46572503/103131795-7b2b1780-46a2-11eb-9199-5288088ed9df.jpg)

Merry Cristmas

**Comment by vomikan** [comment]
It's absolutely 100% working for me.
Please check the following settings:
1)
![image](https://user-images.githubusercontent.com/6836805/103132704-0dd5b180-46b7-11eb-96a3-5fcf565c69de.png)
2) Line #2
![image](https://user-images.githubusercontent.com/6836805/103132722-26de6280-46b7-11eb-947c-03e9134bf709.png)
3) both links opens torrent file with associated application
![image](https://user-images.githubusercontent.com/6836805/103132760-52f9e380-46b7-11eb-927e-72ee8d4de6ca.png)

**Comment by TomAff** [comment]
Checked it
![2020-12-25 12_00_21-MMEX Optionen](https://user-images.githubusercontent.com/46572503/103133187-49697f00-46a9-11eb-8fcc-eb5d064f6f2b.jpg)

[Attachments.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/5741812/Attachments.grm.zip)


updated line 2
select 'file://D:\Software\MoneyManagerEx\MMEX_privat_Attachments\Transaction\' path

Link in Report is:
file:///D:/Software/MoneyManagerEx/MMEX_privat_Attachments/Transaction/Transaction_8084_Attach1.pdf
If I paste this link into the Explorer the PDF opens

**Comment by vomikan** [comment]
Could you try to add \ at the end
```select 'file://D:\Software\MoneyManagerEx\MMEX_privat_Attachments\Transaction\' path```

**Comment by TomAff** [comment]
sorry, it was already there. github changed the script. 
![2020-12-25 12_27_15-Allgemeiner Bericht Manager](https://user-images.githubusercontent.com/46572503/103133758-93a02f80-46ac-11eb-83fb-28dd2d1802f4.jpg)

**Comment by TomAff** [comment]
If I do a right click on the link and choose "Save as" PDF will be saved. So the link seems to be correct.

**Comment by TomAff** [comment]
I use this Version
![2020-12-25 12_31_22-Einstellungen](https://user-images.githubusercontent.com/46572503/103133854-3f497f80-46ad-11eb-9875-3a99b92b4b6a.jpg)

**Comment by vomikan** [comment]
Please extract this zip file into C:\temp then run mmex - shortcut.
The attachment report and pdf file included.

![image](https://user-images.githubusercontent.com/6836805/103134183-7e350080-46c0-11eb-992b-fb870fc3dfbe.png)

[mmex-1.3.6-win64_test.zip](https://github.com/moneymanagerex/moneymanagerex/files/5741901/mmex-1.3.6-win64_test.zip)

**Comment by TomAff** [comment]
Still the same

![2020-12-25 12_55_39-Money Manager Ex - C__temp_mmex-1 3 6-win64_test mmb -   portable mode](https://user-images.githubusercontent.com/46572503/103134316-a4eb3b00-46b0-11eb-913a-10546305dffa.jpg)

**Comment by vomikan** [comment]
But it working for me at the same environment....
I have no ideas how to fix.

I can choose "copy link" by right mouse click
```file:///C:/temp/mmex-1.3.6-win64/MMEX_test_Attachments/Transaction/Transaction_1_Attach1.pdf```
And can open it in Edge browser.

**Comment by vomikan** [comment]
This is a simple html file
```
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Hello!</title>
    </head>

    <body>
        <a href="file://C:\temp\mmex-1.3.6-win64\MMEX_test_Attachments\Transaction\Transaction_1_Attach1.pdf" target='_blank'>Transaction_1_Attach1.pdf</a></td>
    </body>

</html>
```
Could you extract it then open?
![image](https://user-images.githubusercontent.com/6836805/103134528-c6edb900-46c2-11eb-81d3-75cc12d8d5c0.png)

[test.zip](https://github.com/moneymanagerex/moneymanagerex/files/5741933/test.zip)

**Comment by TomAff** [comment]
Tested it on another PC. Same issue.
Tested the "Simple HTML file" in MMEX custom Report => nothing happens.
as a html-file (opened in browser) => it works.

But this is not a big problem for me. I can use the attachment: - link

**Comment by vomikan** [comment]
For me if I click the link in html file the pdf document opens in other tab.
![image](https://user-images.githubusercontent.com/6836805/103134677-07016b80-46c4-11eb-8e72-95e2f957522d.png)
If in your case the behavior not the same it seems the bug outside mmex.

Any way thank you for your effort. Thanks to this, important improvements were made to the program code.

**Comment by TomAff** [comment]
"For me if I click the link in html file the pdf document opens in other tab." **=> on my side too.**
_In Browser it works._

If I use the HTML - Code in MMEX it doesn't work

You're welcome. Have a nice Christmas
