### ISSUE TITLE
MMEX 1.3.5 does not open

### ISSUE THREAD

**Issue by samoska** [moneymanagerex/moneymanagerex#2745]
MMEX version:
 - 1.3.5

Operating System:
 - Windows 10 2004

# Description of the bug

MMEX does not open. The window of MMEX does not appear whereas the program is running in task manager. 

If I launch it on compatibility mode for windows 8, a MMEX window pops up telling my database is maybe corrupted, but the main windows can not be dispalyed.

It looks like a display issue but I did not managed to solve it myself.

# Reproduction

Is the bug reproducible? 
 - Always 

Reproduction steps:

1. Launch MMEX

Expected result: Be able to launch MMEX Normally

Actual result: 

# Additional information
None

**Comment by vomikan** [comment]
Please try the following vertion:
32-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/2p7800dsc7j96leg/artifacts
64-bit
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/36824439/job/p3du7218yegg80ip/artifacts

In case if mmex ico apperas in the tray try to press Shift button + right mouse click - mazimized

**Comment by samoska** [comment]
In case if mmex ico apperas in the tray try to press Shift button + right mouse click - mazimized 
--> This solved my issue in 1.3.5 version many thanks ! I was very affraid of loosing my eight years of account history.
