### ISSUE TITLE
Pressing BACK in Add Account Wizard during Name of the Account (blank) fails

### ISSUE THREAD

**Issue by tonypdmtr** [moneymanagerex/moneymanagerex#2750]
MMEX version:
 - [x] 1.3.6
 - [X] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.

Pressing BACK from "Add Account Wizard" during "Name of the Account" with the name blank fails.

Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
@vomikan This can be marked as fixed. https://github.com/moneymanagerex/moneymanagerex/commit/564c3ff6491870e88451ba546aa84f825e30cc2c
