### ISSUE TITLE
“mmex.app” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by db0313** [moneymanagerex/moneymanagerex#2757]
MMEX version:
 - [ ] 1.3.6
 - [x] 1.3.5
 - [ ] 1.3.4 or older
 - [ ] 1.4.X

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by db0313** [comment]
Just downloaded and will not launch. Previous version worked fine. All my data is gone and do have previous version on other laptop. Will use until fix for my main desktop. It is iMac (Retina 4K, 21.5-inch, 2017) 
Great program have been using for years and have contributed.
Thank you

**Comment by vomikan** [comment]
Could you try this release:
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=10304
and that solution if needed
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9146

**Comment by vomikan** [comment]
#2644

**Comment by db0313** [comment]
Thank you, I did get it to work.
Take care & be safe
