### ISSUE TITLE
Enable More then 3 characters as currency symbol to enable CryptoCurrency market fetch from yahoo

### ISSUE THREAD

**Issue by gregoryvanhout** [moneymanagerex/moneymanagerex#2761]
Dear, 

For example markets are marked as following 
BTC-USD

Kind Regards

**Comment by vomikan** [comment]
Bitcoin is BTC
https://query1.finance.yahoo.com/v7/finance/quote?symbols=BTCUSD=X&fields=regularMarketPrice,currency,shortName
Related issue: #2334
