### ISSUE TITLE
Advanced Filter in Accounts doesn't work

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#2765]
MMEX version:
 - 1.3.6

Operating System:
 - Windows
 
Advanced Filter don't work in Accounts. Payee, Category, Type, Status...
Date Filter works. 

In "Transaction Report" the Filter works.

Is the bug reproducible? 
 - Always

**Comment by vomikan** [comment]
Workaround:
Psess Save 
![image](https://user-images.githubusercontent.com/6836805/103290562-eb1b0400-49fa-11eb-8d9e-28efaa685e59.png)
 then OK
