### ISSUE TITLE
Credit Card Pay

### ISSUE THREAD

**Issue by jjrapy** [moneymanagerex/moneymanagerex#2768]
It will be interesting to be available to setup the due date of the credit card and the amount to be payed at that date and that transfer from checking account to credit card account goes into the cashflow of both accounts.

For example: I have recurring transactions of services and utilities in my credit card (tv, internet, insurance, etc.) and I pay all of my debt monthly.

My credit card due date is every 5-8 of the month (if it is on a weekend, it goes to monday or friday dependind on the bank)

So I put them all as recurring transactions in the credit card, but in the cash flow forecast for my checking account it won't take into consideration that flow from checking to credit card. 

Also in the monthly summary of account it won't take into consideration that.

Actually the only way to see my "real" cashflow of money is to set those transactions to my checking account and then switch back.

**Comment by whalley** [comment]
I setup a regular recurring credit card payment (transfer from checking to credit) on the due date with 0.00 as the amount and set it to "Request user to enter payment" and **do not** "Grant automatic execute". That way I get prompted to enter amount.

Some improvements may be:

(1) Option to adjust payment date to next working OR previous working day. 

(2) It would also be good to have an option to calculate the payment amount based on balance at a previous date. I know AceMoney supports this via a 'Balance' function (as noted below)

**Balance function**

Returns current account balance or past balance according to the specified date or a day.

Syntax:

- Balance("account")
- Balance("account"; "date")
- Balance("account"; day)

account - string, name of the existing account.

date - string, date in the standard AceMoney format that is specified in the International Settings dialog.

day - number, day of a month. This number identified a day of the current month or the previous month if the current day is less that the specified day. This argument is handy when you want to pay off a credit card as specified in the statement, but don’t remember the exact amount and kept using the card past the statement end date, so the current balance is different from the statement balance. In that case just specify Balance("American Express"; 25) if bank period ends on the 25th day of every month.
