### ISSUE TITLE
exportar informes a excel

### ISSUE THREAD

**Issue by CAMARASA** [moneymanagerex/moneymanagerex#2769]
> No funciona la exportación a excel de informes
   Le pido informe de categorias mensualmente y con el boton derecho aparece menu. Al elegir Export to Microsoft Excel,
   abre el excel pero no exporta nada.

<hr>Version: 1.3.6 64-bit<br>

Report export to excel does not work
I ask you to report categories monthly and with the right button menu appears. When choosing Export to Microsoft Excel,
opens the excel but does not export anything.

**Comment by vomikan** [comment]
Workaround:
Export the report to html file then open it in Excel.

**Comment by CAMARASA** [comment]
This option does’t exist in menu

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/103300119-35a67b80-4a0f-11eb-9ac1-34f6b0a59e85.png)

**Comment by CAMARASA** [comment]
Perfecto. Gracias
