### ISSUE TITLE
1.4+ to 1.3.6 DB 

### ISSUE THREAD

**Issue by thucar** [moneymanagerex/moneymanagerex#2771]
MMEX version:
 - [ ] 1.3.7
 - [x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Trying to upgrade(downgrade?) from 1.4+ to 1.3.6 but I can not open my old database. I'm getting the following error:
![image](https://user-images.githubusercontent.com/2293862/103407423-5255c700-4b67-11eb-9585-217e0979ecbe.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create a database with MMEX version 1.4.+
2. Try to open the database with MMEX 1.3.6
3. Observe the error

…

Expected result:
The database gets downgraded to be suitable for version 1.3.6 and up

Actual result:
The database is not opened due to a version mismatch

**Comment by vomikan** [comment]
Hi there.

The solution for this issue exists here:
https://github.com/moneymanagerex/moneymanagerex/issues/2353

Unfortunately, it does not working on Linux for reasons I don't understand.

**Comment by thucar** [comment]
Thank you! Strange that I did not find that. The manual approach in the last comment worked for me.
