### ISSUE TITLE
Erreur : Une transaction récurrente dépasse votre limite de compte

### ISSUE THREAD

**Issue by fj18-110** [moneymanagerex/moneymanagerex#2776]
MMEX version:
 - [ ] 1.3.7
 - [X] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

At each opening of my database, i have to validate the error message 
"Une transaction récurrente dépasse votre limite de compte"
47 times and i have 47 recurring transactions....
![image](https://user-images.githubusercontent.com/76882028/103464383-94336880-4d33-11eb-96e6-97016e87df55.png)

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  At the opening (47 times)
2.  At each recurring transaction update (once per update)
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Press "Oui" 
then shift + right mouse key
Choose "miximize" in popup menu

**Comment by fj18-110** [comment]
> Appuyez sur "Oui"
> puis shift + touche droite de la souris
> Choisissez "miximize" dans le menu contextuel

Désolé, j'ai validé les nombreux messages d'erreur identiques, et suivi le conseil, mais aucun menu contextuel ne s'affiche....

**Comment by vomikan** [comment]
Please check accounts balance. Possible, some account min. balance <> 0.00
![image](https://user-images.githubusercontent.com/6836805/103479891-d4512480-4de1-11eb-86f0-600c6fd57e8b.png)

**Comment by fj18-110** [comment]
Oui, parfait. Un compte avait une valeur différente de 0. Je n'ai plus d'erreur.
Merci beaucoup !

Connais-tu la signification de cette variable. A quoi sert-elle ?

**Comment by vomikan** [comment]
Il s'agit d'une tentative d'empêcher l'utilisateur d'entrer des valeurs incorrectes pour, par exemple, les cartes de débit ou de crédit.
Pour ne pas dépasser la limite de crédit.

**Comment by fj18-110** [comment]
> Il s'agit d'une tentative d'empêcher l'utilisateur d'entrer des valeurs incorrectes pour, par exemple, les cartes de débit ou de crédit.
> Pour ne pas dépasser la limite de crédit.

Merci.
