### ISSUE TITLE
Sort Order Resets on Transaction Report after Drilldown

### ISSUE THREAD

**Issue by PaulBP14** [moneymanagerex/moneymanagerex#2784]
MMEX version:
 - [ ] 1.3.7
 - [x] 1.3.6

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Sort Order on the Transaction Report is reset after performing a drilldown on the ID field.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open the Transaction Report
2. Remove all filters and click OK
3. Click on the ID heading to sort by the ID field
4. Click on an ID to drilldown to a transaction
5. Close the Edit Transaction window
6. The transaction report reverts to its default sort order

…

Expected result: The Transaction Report retains the sort order selected (at least until the report is closed) after drilldown

Actual result: The Transaction Report reverts to its default sort order (date) after drilldown

# Additional information

The issue occurs no matter which field is selected for sorting

**Comment by vomikan** [comment]
@PaulBP14 PaulBP14 thank you for your reports this issue.

When transaction report started it sort order by default by date
```    std::stable_sort(trans_.begin(), trans_.end(), SorterByTRANSDATE());```
Then report sort order changed by Java Script function.
In case if some transaction has been edited (or Transaction dialog opened) the transaction list ordered by default fiels "date".

I won't be able to change this at the JS level. I consider the bug insignificant.

**Comment by whalley** [comment]
> I won't be able to change this at the JS level. I consider the bug insignificant.

Agreed.
