### ISSUE TITLE
Refer to 2662; now similar problem for AMOUNT field 

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/moneymanagerex#2785]
MMEX version:
 - [ ] 1.3.7
 - [x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Refer to bug #2662; Balance field is fine now when you export to CSV but now AMOUNT field has gaps in numbers e.g. 3650 is appearing as 3 650

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by rmkhalfay** [comment]
Also the AMOUNT field does not have + or - sign to indicate credit or debit in CSV file

**Comment by vomikan** [comment]
@rmkhalfay could you please test new build with the fix
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37282361/job/ijv382t5a4o9xe0m/artifacts

**Comment by rmkhalfay** [comment]
Sir

I installed Beta version – and noticed that the AMOUNT and BALANCE fields are fine with no gaps as before. But the AMOUNT field should indicate – (negative) for withdrawals and this is not reflected in the exported file snapshots below

Ver 1.3.6 and 1.3.7 beta
Date
Payee
Amount
Balance
Category
SubCategory
Number
Notes
30-01-12
Unknown
26277
26277
Transfer
1
Bal B/F ON : 30-JAN-12
31-01-12
Unknown
127
26150
Tax
TDS SRK NRO
2
TAX Deducted
31-01-12
Unknown
409
26559
interest SRK NRO
3
SBINT FOR THE PERIOD FROM01-AUG-11 TO 31-JAN-12
05-04-12
Unknown
4092
30651
interest SRK NRO
4
2356354000008 / 1:INT PAYOUT
23-04-12
Unknown
899
29752
Tax
TDS SRK NRO
5
2356A00007/65833366

Ver 1.3.4 (same exported file shows -ve sign for withdrawals or deductions)
Date
Payee
Amount
Balance
Category
SubCategory
Number
Notes
30-01-12
Unknown
26277
26277
Transfer
1
Bal B/F ON : 30-JAN-12
31-01-12
Unknown
-127
26150
Tax
TDS SRK NRO
2
TAX Deducted
31-01-12
Unknown
409
26559
interest SRK NRO
3
SBINT FOR THE PERIOD FROM01-AUG-11 TO 31-JAN-12
05-04-12
Unknown
4092
30651
interest SRK NRO
4
2356354000008 / 1:INT PAYOUT
23-04-12
Unknown
-899
29752
Tax
TDS SRK NRO
5
2356A00007/65833366
See text in RED font

Regards
Rayees Khalfay
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vomikan** [comment]
My test.
![image](https://user-images.githubusercontent.com/6836805/104810804-3f4e2280-5808-11eb-8cce-10538da01cd3.png)

![image](https://user-images.githubusercontent.com/6836805/104810850-85a38180-5808-11eb-935e-da3604639546.png)

```
2020-01-15,Coles,"1345,00",Food,Groceries,,
2020-01-15,Auspost,"2123,00",Other Income,,,
2021-01-15,Accessories,"3110,00",Education,Tuition,,
2021-01-15,Accessories,"1000,00",Income,Discount,,
```

Failed!

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/104812372-c30d0c80-5812-11eb-99d5-d023f6a7a64a.png)

```
2020-01-15;Coles;-1345,00;Food;Groceries;;
2020-01-15;Auspost;2123,00;Other Income;;;+2,123.00
2021-01-15;Accessories;-3110,00;Education;Tuition;;
2021-01-15;Accessories;1000,00;Income;Discount;;
2021-01-16;< Cash Stash;1,00;Transfer;;;Cash Stash -> test +1
2021-01-16;> Cash Stash;-1,00;Transfer;;; test -> Cash Stash -1
```

**Comment by vomikan** [comment]
@rmkhalfay could you please test the following build:

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37297135/job/k4e5r3u9mmo6t0m3/artifacts

**Comment by rmkhalfay** [comment]
Works PERFECT now

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
