### ISSUE TITLE
Pressing S in the search field under a bank account cause opening window for saving database 

### ISSUE THREAD

**Issue by DarkDalmatian** [moneymanagerex/moneymanagerex#2787]
By writing S in the search field below a bank account (for example if you want to search for "**s**torage")cause opening window for saving database because in the menu the save database is set to "S" instead of "CTRL+S"

![image](https://user-images.githubusercontent.com/59387935/103767486-0603fe80-5021-11eb-992c-64e972cc4dfd.png)
![image](https://user-images.githubusercontent.com/59387935/103767527-15834780-5021-11eb-81c0-f1fb0abb58e9.png)

**Comment by whalley** [comment]
Updated the crowdin translation that had a spurious character S in. It now aligns with behavior of other languages.

**Comment by whalley** [comment]
Fixed by https://github.com/moneymanagerex/moneymanagerex/commit/29b7a9a75b8563dd33d23676db922e64f6a2bb47
