### ISSUE TITLE
BuyMeACoffe donation link is not working

### ISSUE THREAD

**Issue by ngosang** [moneymanagerex/moneymanagerex#2791]
I want to donate but I can't. :(

**Comment by vomikan** [comment]
Thank you for your appreciation and willingness to help. There is another option - donation via Paypal.
[paypal.com](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=moneymanagerex%40gmail%2ecom&lc=US&item_name=MoneyManagerEx&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHostedGuest";
)

**Comment by guanlisheng** [comment]
exactly that cash.me is only available in the USA
