### ISSUE TITLE
Tabbed view for multiple databases

### ISSUE THREAD

**Issue by sdrzm** [moneymanagerex/moneymanagerex#2792]
> It would be great if there is a tabbed view and so that we can easily navigate between multiple databases. It can be located under toolbar and when moving another tab the program can act as we click open database. It came to my mind because I am working with multiple databases and always clicking File>Recent Files and select. It will be just like a shortcut.

> Please do not remove information attached below this text.

<hr>Version: 1.3.6 64-bit<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.61.0-DEV WinSSL<br>
<br>
Build: Dec 24 2020 15:07:56 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  Turkish (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by vomikan** [comment]
Hello Mr. Stallone :)
 There is a solution for databases.
https://github.com/moneymanagerex/moneymanagerex/issues/2387

**Comment by sdrzm** [comment]
Hello our esteemed developer. I really respect your effort. Thanks for your help for our community.

If we come to the point, I don't need any workaround. Because I can open multiple mmex instances to use different databases at the same time. Or I can open one mmex instance and open desired database to work on it. There is no problem. I wrote it just if it can be easier to work on different databases at the same time. I know it takes time so it is your decision.

**Comment by vomikan** [comment]
Thank you for the suggested idea.
Unfortunately, anything other than woraround has nothing to offer.
To implement the idea with tabs, it will take a lot of hours of development, and there are none.
However, often different ideas are put together in a single puzzle and transformed into something useful.

**Comment by sdrzm** [comment]
Thanks, just keep in my mind. See you.
