### ISSUE TITLE
macOS Builds - 1.37 Beta Requires macOS 11.0?

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2802]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

Big thank you to Mark Whalley for the macOS builds for 1.35 and 1.36. They are signed and notarized so no file is damaged message and you don't having to use xattr to change file attributes to get MMEX to run. And for contributing several macOS specific fixes. macOS builds on Travis have been failing for many months. Glad to see MMEX for macOS is not dead.

However, 1.37 beta 1 and beta 2 require macOS 11.0+. They won't work on 10.15.7. The download link says for 10.10+.
You can tell from the MMEX icon:
![MMEX137](https://user-images.githubusercontent.com/63317977/104791687-9d77f880-5769-11eb-9e83-8360a7af542f.jpg)
If you continue and drag MMEX to Applications and run MMEX you get a message that says 11.0 is required.
![MMEX 137 2](https://user-images.githubusercontent.com/63317977/104792053-13c92a80-576b-11eb-85e2-5e3d295515b4.jpg)

**Comment by whalley** [comment]
Let me check on this. I've not got it automated yet so must have messed something up on the beta build!

**Comment by whalley** [comment]
Can you give this a try... I can't see anything wrong with what I did before but have re-built.

https://drive.google.com/file/d/1k76KvZ1b8gowfE9aXZKBZ5wTuGOAaD4-/view?usp=sharing

**Comment by 2BeeOrNot** [comment]
It works now om 10.15.7. Thank you. Icon resizing works! And the toolbar toggle on/off issue is fixed too!

**Comment by whalley** [comment]
Thanks, will update beta build on my site. Have made sure it's gets built correctly from now on, just need to automate better.
