### ISSUE TITLE
New Transaction - Using Tab to Move Between Fields and Controls Using macOS

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2803]
MMEX version:
 - [] 1.3.7
 - [x] 1.3.6

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

Using Windows the tab key can be used to move between all the fields and controls in the new transaction window. Using macOS only date, amount, account, payee, number and notes can be selected. I believe this is true in 1.35 too.

**Comment by whalley** [comment]
This is standard MacOS behaviour. See - https://www.compsmag.com/how-to/use-the-tab-key-to-switch-between-dialog-buttons-in-mac-os-x/ to enable full use tab key switching. On later OS releases the working is slightly different with just a tick box option.

Please close.

**Comment by 2BeeOrNot** [comment]
Thanks. Didn't know about this macOS system option. Although the article in the link above is fairly current it is little different in the most current macOS 10.15 like you indicated. For anyone else who ends up here it is the only checkbox in Systems Preferences -> Keyboard -> Shortcuts

**Comment by 2BeeOrNot** [comment]
It's not the only checkbox. The checkbox at the bottom left.
![KB Tabs](https://user-images.githubusercontent.com/63317977/104829442-ebf8c600-5841-11eb-92ab-f65725cd9a33.jpg)
