### ISSUE TITLE
Unable to delete entry in recurring transaction list

### ISSUE THREAD

**Issue by Schone59** [moneymanagerex/moneymanagerex#2816]
> Unable to delete entry in recurring transaction list on Version: 1.3.6 64-bit, Database version: 7 • (aes128cbc)

<hr>Version: 1.3.6 64-bit<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.61.0-DEV WinSSL<br>
<br>
Build: Dec 24 2020 15:07:56 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1536x864 32bit 96x96ppi

**Comment by vomikan** [comment]
I can't reproduce this issue.
![image](https://user-images.githubusercontent.com/6836805/105054653-4cc31100-5a83-11eb-8c31-78248c373212.png)

![image](https://user-images.githubusercontent.com/6836805/105054746-649a9500-5a83-11eb-9963-08f9f54bb9ec.png)

**Comment by Schone59** [comment]
Thanks for the quick response.

When I go to Recuring Transactions and highlight a transaction that I want to stop, I click the delete button and the program freezes, I then need to run task manager to stop the program. Have tried running the program as administrator with no effect. I can edit the transaction and save but cannot remove.

Jim

**Comment by vomikan** [comment]
Dear Jim,

Could you create new DB and create similar recurring transaction in it?
In case if a freeze would be reproduced, please send me that file.

Regards,
Nikolay

**Comment by Schone59** [comment]
Attached file after freeze

Regards Jim

**Comment by vomikan** [comment]
I can't find it.

**Comment by vomikan** [comment]
still nothing

**Comment by Schone59** [comment]
Have attached it as a .mmb file.

**Comment by Schone59** [comment]
Have changed the .mmb to .zip

**Comment by vomikan** [comment]
>Have changed the .mmb to .zip
Please drag and drop the zip file here

**Comment by Schone59** [comment]
Your message is ready to be sent with the following file or link attachments:

Test.mmb


Note: To protect against computer viruses, email programs may prevent you from sending or receiving certain types of file attachments. Check your email security settings to determine how attachments are handled.

**Comment by Schone59** [comment]
Nikolay,

I have tried several times to send the Test.mmb file, have sent it to myself and I get the attachment. Do no know what to do now to send this file, any ideas.

Regards Jim

**Comment by vomikan** [comment]
Could you try this service?
https://dropmefiles.com/

**Comment by Schone59** [comment]
Nikolay,
Have sent the file.
Jim

Sent from my iPad

On 20 Jan 2021, at 16:30, Nikolay <notifications@github.com> wrote:

﻿

Could you try this service?
https://dropmefiles.com/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdropmefiles.com%2F&data=04%7C01%7C%7C213de81fde964613364008d8bd60adac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637467570205104634%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xxqIRkahsD%2FwJ0RL8aKj7Ma7eIA166cQWmZDtNTv6Jc%3D&reserved=0>

**Comment by vomikan** [comment]
Send ne back the link to the file, please.

![image](https://user-images.githubusercontent.com/6836805/105217819-69d01080-5b65-11eb-993c-df37956e5a0c.png)

**Comment by Schone59** [comment]
https://dropmefiles.com/rHz4H

**Comment by vomikan** [comment]
Finally I've received the DB file.
I can't reproduce any hangs anyway.

**Comment by Schone59** [comment]
Thanks for trying, I will uninstall the application and the reinstall to see if that sorts it. Regards Jim

Sent from my iPad

On 20 Jan 2021, at 20:14, Nikolay <notifications@github.com> wrote:

﻿

Finally I've received the DB file.
I can't reproduce any hangs anyway.

**Comment by vomikan** [comment]
I have tested with this build
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37363604/job/l2jp9cyb0lam6qh4/artifacts
I recommend to use this build instead 1.3.6.

**Comment by Schone59** [comment]
Nikolay,
Thanks for your help, have installed the build from the link below and no change, still unable to delete item in the recurring transaction list. Not causing any problems at the moment. Will update if I  sort at this end.
Jim
