### ISSUE TITLE
Analytics collected on first run without user consent

### ISSUE THREAD

**Issue by py-crash** [moneymanagerex/moneymanagerex#2817]
One of the great reasons because I use FOSS software is to avoid tracking. However, every time I open MoneyManagerEX a call to google analytics is made giving out a lot of details about my computer. This call is already made on first run without giving any warning before doing it. This is not compliant with the General Data Protection Regulation (GDPR). 

Any collections of metrics should always be done OPT-IN, with explicit user consent.

The use of third party tracker (Google Analytics in this case) should be clearly specified in the privacy policy, because it means sharing data with a third party.

I would also recommend another analytics tools such as [Plausible](https://plausible.io/), used for example by the [elementary OS project](https://plausible.io/elementary.io), or [GoatCounter](https://www.goatcounter.com/).

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/license.txt#L48-L73

**Comment by vomikan** [comment]
Sending this data can be disabled.

![image](https://user-images.githubusercontent.com/6836805/105179936-fe714900-5b3a-11eb-897b-9084bce4c352.png)

**Comment by py-crash** [comment]
>     3. Do we disclose any information to outside parties?
>        We do not sell, trade, or otherwise transfer to outside parties collected information.

 This is literally not true. By using Google Analytics you are sharing information with Google, so you are transferring it with a  third party

**Comment by py-crash** [comment]
The big problem is the analytics is sent on first run before the user even sees the privacy policy.

In a new and fresh install when I run the program the ping will be sent and after that I can disable it. This behaviour is not compliant with the GDPR

**Comment by vomikan** [comment]
I've modified the "About" dialog to show "Send anonymous statistics usage data" check box at initial start

![image](https://user-images.githubusercontent.com/6836805/105219106-1c54a300-5b67-11eb-977a-425e3aad7269.png)

**Comment by whalley** [comment]
It is now explicit when running the application for the first time. Tested and works as described.

**Comment by vomikan** [comment]
@whalley 
>3. Do we disclose any information to outside parties?
   We do not sell, trade, or otherwise transfer to outside parties collected information.

What do you think regarding this text?

**Comment by whalley** [comment]
@vomikan -- I'd suggest re-wording to:

3. Do we disclose any information to outside parties?
Other than for the above mentioned usage statistics collection, we do not sell, trade, or otherwise transfer to outside parties.

**Comment by py-crash** [comment]
> @vomikan -- I'd suggest re-wording to:
> 
>     1. Do we disclose any information to outside parties?
>        Other than for the above mentioned usage statistics collection, we do not sell, trade, or otherwise transfer to outside parties.

You need to disclose the use of a third party tool for being compliant with GDPR. I would suggest:

> We use Google Analytics for collecting anonymous data. Other than for the above mentioned usage statistics collection, we do not sell, trade, or otherwise transfer to outside parties.

It would also be beneficial to link to some outside sources provided by Google for the disclosure: https://support.google.com/analytics/answer/7318509

**Comment by vomikan** [comment]
Currently the Privacy Policy reads from file and has no international information.
I believe this info better to present on c++ side as wxGetTranslation(xxxx) function to have possibility to translate it by [Crowdin.com](https://crowdin.com/project/moneymanagerex)

**Comment by whalley** [comment]
Privacy policy updated to explicitly reference Google Analytics.

https://github.com/moneymanagerex/moneymanagerex/issues/2912 raised to consider enhancement to support of international variants. enhancement

**Comment by OdinVex** [comment]
Why is analytics even used? *getting Microshaft-creepy vibes*
