### ISSUE TITLE
Mmex not launching on Fedora 33

### ISSUE THREAD

**Issue by darkvadd7** [moneymanagerex/moneymanagerex#2824]
MMEX version:
 - [ ] 1.3.7
 - [X] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux (Fedora 33)

# Description of the bug

When launching mmex (with or without sudo), I have the following error:
`mmex: symbol lookup error: mmex: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE9_M_createERmm, version WXU_3.0`

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Just launch mmex or sudo mmex in Terminal.

Expected result:
Mmex start.

Actual result:
Mmex doesn't start.

**Comment by PMaff** [comment]
@darkvadd7 : is this issue still there if you compile wxWidget 3.1.5 and then mmex 1.5.14 ?

**Comment by zurabashan** [comment]
Hello
I have built wxWidgets 3.1.5 for Linux-5.17.11-200.fc35.x86_64 (Fedora 35) in minimal configuration.
After that I still have same error:
```
$ mmex
mmex: symbol lookup error: mmex: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE9_M_createERmm, version WXU_3.0
```
I have installed mmex from here - https://packagecloud.io/moneymanagerex/moneymanagerex/packages/fedora/31/mmex-1.5.3-1.fc30.x86_64.rpm

**Comment by PMaff** [comment]
> Hello I have built wxWidgets 3.1.5 for Linux-5.17.11-200.fc35.x86_64 (Fedora 35) in minimal configuration. After that I still have same error:
> 
> ```
> $ mmex
> mmex: symbol lookup error: mmex: undefined symbol: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE9_M_createERmm, version WXU_3.0
> ```
> 
> I have installed mmex from here - https://packagecloud.io/moneymanagerex/moneymanagerex/packages/fedora/31/mmex-1.5.3-1.fc30.x86_64.rpm

What happens if you compile wxWidget 3.1.5 
with the description here (look out for the prerequisites):
https://docs.codelite.org/build/build_wx_widgets/
and afterwards mmex 1.5.14  with the compile description here (also see the prerequisites):
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md

**Comment by gombosg** [comment]
It also works for me on F36, you have to build for yourself @zurabashan . I'm working on packaging it in my free time, it should be ready by next week.

**Comment by PMaff** [comment]
> It also works for me on F36, you have to build for yourself @zurabashan . I'm working on packaging it in my free time, it should be ready by next week.

You mean packaging for the Fedora 36 repos?

**Comment by Zeit08** [comment]
> It also works for me on F36, you have to build for yourself @zurabashan . I'm working on packaging it in my free time, it should be ready by next week.

So it means that you have the latest version of mmex for fedora36? Would you mind uploading it ?

**Comment by gombosg** [comment]
Hey, I'm on vacation/busy these weeks it's a lot of work to do properly (separating packages). Started to publish here:
https://copr.fedorainfracloud.org/coprs/gombosg/moneymanagerex/builds/
https://pagure.io/user/gombosg

Still need to separate out some packages and finish with a packaging file list.
But you can still easily build for yourself given the build instructions 🙂

**Comment by zurabashan** [comment]
> Hey, I'm on vacation/busy these weeks it's a lot of work to do properly (separating packages). Started to publish here: https://copr.fedorainfracloud.org/coprs/gombosg/moneymanagerex/builds/ https://pagure.io/user/gombosg
> 
> Still need to separate out some packages and finish with a packaging file list. But you can still easily build for yourself given the build instructions slightly_smiling_face

@gombosg yes it is possible with little trick (I must do `cmake -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config .` where wx-config is builded from source wx-widget 3.1.5) and some luck.
When I try do `cmake --build .. --target package` I see errors, that I cannot resolve:
```
gmake[1]: *** [CMakeFiles/Makefile2:442: src/CMakeFiles/mmex.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

So, if someone can build MoneyManagerEx from source on Fedora - I think he or she is a very lucky user

**Comment by PMaff** [comment]
> So, if someone can build MoneyManagerEx from source on Fedora - I think he or she is a very lucky user

The last one that I tried was 1.5.14 here:
v1.5.14 (2022.04.14) [Release Notes](https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.5.14) [#](https://moneymanagerex.org/docs/downloads/older/#v1514-20220414-release-noteshttpsgithubcommoneymanagerexmoneymanagerexreleasestagv1514)
https://moneymanagerex.org/docs/downloads/older/

See also:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1147444707

**Comment by whalley** [comment]
Perhaps try the Fedora 36 CI build - https://github.com/moneymanagerex/moneymanagerex/issues/4880

**Comment by whalley** [comment]
@darkvadd7 Is the fedora 36 build suitable? https://moneymanagerex.org/docs/downloads/latest/

**Comment by whalley** [comment]
Closing as Fedora 36 build available.
