### ISSUE TITLE
Always Opens on Wrong Monitor

### ISSUE THREAD

**Issue by mrando820** [moneymanagerex/moneymanagerex#2826]
MMEX version:

 - [X] 1.3.6

Operating System:
Windows X

# Refuses to remember which monitor to open on.

I move the program to my secondary monitor, but when I close it and reopen, it always opens on my primary. I checked the Settings database (sorry, forgot the name) and it's got the correct negative X,Y coordinates, but it still won't open on the secondary. I don't recall this ever happening on prior versions.

# Reproduction

Is the bug reproducible? 
 - [X] Always 

Reproduction steps:
Just open it, will always be primary monitor.

Expected result:
Open where it was when closed.
Actual result:
Opens with same dimensions as closed, but always on primary monitor.

# Additional information
Tried deleting the configuration database, which recreates fine, and stores the coordinates, but it still opens on wrong monitor.

**Comment by vomikan** [comment]
I tried to reproduce it, but it didn't work. You can make the coordinates passed by parameters. But this is for geeks.

**Comment by mrando820** [comment]
Thanks, going to try a complete uninstall/reinstall. I can’t imagine the code to open on a monitor has changed in years, so maybe something is corrupt on my end.

**Comment by mrando820** [comment]
Looks to me like the change for bugfix #214 caused this:
valx will be a negative number when the primary monitor is on the right, and the program was closed on the left monitor. That's fine, it shouldn't get assigned to zero. Or at least, so I believe.  (mmex.cpp).

    //BUGFIX: #214 MMEX Window is "off screen"
    if (valx < 0)
        valx = 0;
    else if (valx >= sys_screen_x)
        valx = sys_screen_x - valw;

    if (valy < 0)
        valy = 0;
    else if (valy >= sys_screen_y)
        valy = sys_screen_y - valh;

**Comment by vomikan** [comment]
#2694

**Comment by grumpy235** [comment]
Compile under VS2019 throws the following messages-

6>mmhomepage.cpp
6>D:\Projects\mmex\src\mmex.cpp(335,47): error C2668: 'wxDisplay::wxDisplay': ambiguous call to overloaded function
6>D:\Projects\wxWidgets-3.1.4\include\wx/display.h(56,5): message : could be 'wxDisplay::wxDisplay(const wxWindow *)' (compiling source file D:\Projects\mmex\src\mmex.cpp)
6>D:\Projects\wxWidgets-3.1.4\include\wx/display.h(52,5): message : or       'wxDisplay::wxDisplay(unsigned int)' (compiling source file D:\Projects\mmex\src\mmex.cpp)
6>D:\Projects\mmex\src\mmex.cpp(335,47): message : while trying to match the argument list '(int)'
6>D:\Projects\mmex\src\mmex.cpp(350,17): warning C4018: '<': signed/unsigned mismatch

Line 335 is w_xDisplay* display = new wxDisplay((int)0);_
Line 350 is for (int i=0; i<wxDisplay::GetCount(); i++) {
