### ISSUE TITLE
Navigation within program painfully slow

### ISSUE THREAD

**Issue by mrando820** [moneymanagerex/moneymanagerex#2827]
MMEX version:
1.3.6

Operating System:
 - [X] Windows 10

Moving around in the program is painfully slow, for instance, hitting Tools | Options takes about 13 seconds to open the options dialog window.  Picking an account from the main (home) window takes about 8 seconds, and trying to add a new transaction takes about 8 seconds as well. 

There's less than 4000 rows in CHECKING_ACCOUNT_V1

Machine seems fine, Intel I7 with 8 gig ram, not much else running.

Is the bug reproducible? 
 [x] Always

**Comment by vomikan** [comment]
I easily work with a program where there are more than 10,000 transactions.
Could you create new DB? Still slow?

**Comment by mrando820** [comment]
Created a new database, still slow, restarted into safe mode, worked fine there. restarted into regular mode, and it now behaves at normal speed. I suspect latest windows 10 update didn't finish completely or something similar, but a safe mode/regular restart seems to have fixed it.
