### ISSUE TITLE
Income vs Expenses report

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2832]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

I've created separate DB with incomes only then run "Income vs Expenses - Monthly" report with "Overtime" parameter
![image](https://user-images.githubusercontent.com/6836805/106131401-b1612880-6173-11eb-937a-abdceccf7319.png)

I expect to see one green bar in a month, but I see two. The second one has a strange, very big meaning.

Version: 1.3.7-RC.1 64-bit
• db 7 • (aes128cbc)

Libs:
• wxWidgets 3.1.4 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.61.0-DEV WinSSL

Build: Jan 25 2021 11:03:49
• CMake 3.16.2
• MSBuild 15.9.21.664
• gettext 0.19.8.1
• MSVS15.0
• MSVSC 19.16.27035.0
• Windows SDK 10.0.14393.0

OS:
• Windows 10 (build 18363), 64-bit edition
• Russian (windows-1251)

**Comment by vomikan** [comment]
Reason of this issue sample:
```
,{ name: 'Expenses', data: [0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000] }] }
```
comma is data and value separator at the same time.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/106133702-af4c9900-6176-11eb-8626-f8773c1fa424.png)

**Comment by whalley** [comment]
Yes, a locale-specific issue. I see where the error is. Will affect other reports also. Will get a fix done.

**Comment by vomikan** [comment]
@whalley 
Please be so kind as to see what possible fix. I'm very busy this week.

**Comment by vomikan** [comment]
Related issue
https://github.com/moneymanagerex/general-reports/issues/64
