### ISSUE TITLE
Reports Header

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2836]
# Reports Header Style

![image](https://user-images.githubusercontent.com/6836805/106318340-dee7c800-6280-11eb-867e-bc1e3bc654bf.png)

@whalley what do you think about this design of reports header?

PS Colors discussible

PSS https://github.com/vomikan/moneymanagerex/commit/c7a2fc519063ff658510259119d144f623825588

**Comment by whalley** [comment]
@vomikan - Yes, it makes the reports header a bit more compact. I like it. That color seems to contrast well, I have no objection. A couple of things to consider. 
1. I noticed that you dropped the username in the header. All reports included this (if setup in the options). Would need to consider how we want to support that. Possibly include at the top of the right-hand box in BOLD.
2. Other report header info such as list of accounts if 'specific accounts' is selected can get long. Would suggest leaving in left-hand box

**Comment by whalley** [comment]
Probably worth adding a reportHeader method also to standardize them all... Something I was thinking about

**Comment by vomikan** [comment]
@whalley  I've created this one
https://github.com/vomikan/moneymanagerex/blob/master/src/reports/htmlbuilder.cpp#L143-L165
