### ISSUE TITLE
Enter category by keystroke

### ISSUE THREAD

**Issue by garters** [moneymanagerex/moneymanagerex#2837]
# Mouseless Category entry of Data

It would be super handy to be able to choose a Category (or at least get into the Category field) without mouse clicks. (It is not possible to TAB there)
While you are in Data entry within a line, pressing "enter" pops up the edit dialogue leaving the cursor in the date field. How about using the "c" on the keyboard, to jump straight to this field? W
![Data entry](https://user-images.githubusercontent.com/78243707/106345058-32562680-6312-11eb-9c2d-5c2d9a3767f3.png)

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
Workaround
https://osxdaily.com/2014/08/05/toggle-tab-window-navigation-mac-os-x-keystroke/

**Comment by garters** [comment]
Thanks but it doesn’t work. Yes you can tab around, eg {enter}{TAB}{TAB}{TAB}{TAB}{TAB}{TAB}, but the Category field won’t open with “enter”. So you still have to mouse click.
It would be far better with {enter}{C} straight into the field

**Comment by whalley** [comment]
Once you tab to the Category field then press the spacebar and the category dialog should appear.

**Comment by garters** [comment]
Thanks

**Comment by whalley** [comment]
User fix/setting identified.
