### ISSUE TITLE
Multi-change transaction - Old rows still highlighted when changing date

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2848]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

If I select multiple transactions and opt to change the date this works correctly.

However the old rows that were selected remain highlighted **but** they are now highlighting different transactions as the transaction order has now changed.

When editing a single transaction the selected row highlighted moves correctly.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
Not convinced that this is fixed. If I select multiple transactions it now only moves one of them if I change the date.

Also, possibly linked to this change. I get an asset failure when selecting an account.
<img width="940" alt="Screenshot 2021-02-07 at 01 29 44" src="https://user-images.githubusercontent.com/487345/107133815-1f2ff180-68e4-11eb-815e-7fe2180e0641.png">

**Comment by vomikan** [comment]
I expected that similar errors might occur, but I forced the commit to check it faster. Thanks for the report.

**Comment by vomikan** [comment]
Minor errors will be corrected when the case is closed.
