### ISSUE TITLE
CASH ACCOUNT ISSUE

### ISSUE THREAD

**Issue by stantheman1** [moneymanagerex/moneymanagerex#2855]
Hi
I have a cash account on the system.  When deleting two of the cash items which were entered in error a few days earlier, the balance did not adjust correctly.
1)Deposits thereafter were deducted sometimes instead of being added to the balance. 
2)Payments were sometimes added to the balance.
3) In many cases, the addition or subtraction of entries did not change the balance correctly and made no sense at all.

Thank you

Stanley Pearce

<hr>Version: 1.3.6 64-bit<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.61.0-DEV WinSSL<br>
<br>
Build: Dec 24 2020 15:07:56 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19041), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1280x1024 32bit 96x96ppi

**Comment by whalley** [comment]
Have not seen the behavior before. Do you have database (with personal data removed) that is exhibiting this issue that you can share?

**Comment by stantheman1** [comment]
Hi Mark
Unfortunately not.
I spent some time deleting and re-entering data, so that it is now ok.
If it occurs again, I will remove the data leaving just the figures and
send on a screen shot.  Hope that is okay?
Regards
Stanley Pearce

**Comment by whalley** [comment]
Thanks. As much info to work on is always grateful. :-)
