### ISSUE TITLE
mmchecking_list.cpp debug alert

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2870]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

Open app and click on a few accounts in the account navigator....

![Screenshot 2021-02-02 at 20 47 52](https://user-images.githubusercontent.com/487345/106660555-11066c00-6598-11eb-8207-3d40d73847cd.png)

**Comment by vomikan** [comment]
@whalley Please check if this fix helps.

**Comment by whalley** [comment]
@vomikan - Fixed, thanks.
