### ISSUE TITLE
Transfering bookings

### ISSUE THREAD

**Issue by Django84** [moneymanagerex/moneymanagerex#2873]
MMEX version:
 - [ ] 1.3.7
 - [x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. How can I divide an amount into various categories when I want to make a transfer booking?
The corresponding field in the booking mask cannot be selected.
2. How can I split an amount into various categories when I want to do a #transfer booking?
The corresponding field in the booking mask cannot be selected.
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
You can't. Split transactions are not supported for transfers, you would need to create multiple transfers.

I tend to use a single 'Transfer' category for all transfers between accounts and only use other categories for Deposits and Withdrawals. For my usage I see no value in categorizing 'internal' transfers between accounts, and only use these for 'external' income and expenses.

Of course your usage may vary.

**Comment by vomikan** [comment]
#2616 #1396
