### ISSUE TITLE
Graphics is much too large

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2877]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

![image](https://user-images.githubusercontent.com/6836805/106882538-eb8c7600-66ef-11eb-834f-be841955d76a.png)

**Comment by vomikan** [comment]
@whalley could you, please, check how ```  resize: inherit;``` working on MAC?
https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/master.css#L1014-L1022
It does not supported with MS iexplore. 
You can find out how it works here:
https://html5css.ru/edithtm/index.php

**Comment by whalley** [comment]
The CSS change has no impact on the pie/radar sizing on MacOS. 

At present 
`htmlChart += wxString::Format("chart: { type: '%s', toolbar: { tools: { download: false } }, width: '95%%' }", gtype);`
restricts it to 95% for all charts. Why not adjust the %age to, say,  67% for bar/pie and center the <div> in which it is contained?

Not sure what is intended by the `resize: inherit;` as the parent has no resize anyway as far as I can see. Or at least nothing is resizable for me.

**Comment by vomikan** [comment]
I like it.

**Comment by vomikan** [comment]
the graphics are too big depending on the screen resolution, as I have already written to you.

**Comment by whalley** [comment]
I'm not seeing any issue here on either Mac or Windows... Do we have screenshot and detail on the report? E.g. on my test data I get...


![Screenshot 2021-03-05 at 00 49 10](https://user-images.githubusercontent.com/487345/110050817-9c684e00-7d4c-11eb-90d3-37975470feca.png)

**Comment by vomikan** [comment]
I can see the issue only on big screen

![image](https://user-images.githubusercontent.com/6836805/110090789-bafc3280-7da8-11eb-8151-b15c055122fc.png)

**Comment by vomikan** [comment]
https://stackoverflow.com/questions/40526500/css-for-different-screen-resolutions

**Comment by vomikan** [comment]
Here is another example where you can see the problem of too big graphics very well.

![image](https://user-images.githubusercontent.com/6836805/110113090-a6796380-7dc3-11eb-8446-3ae38cabdcca.png)

**Comment by vomikan** [comment]
Simple fix for wide monitor is to add "max-width: 1280px;" at the end of master.css file.

```
div.chart {
  display: flex;
  justify-content: center;
  align-items: center;
  max-width: 1280px;
}
```

@renato-mmex could you please test this solution?

**Comment by renato-mmex** [comment]
|*that was still too big, tried with 800px, that is much better* 
div.chart { display: flex; justify-content: center; align-items: center; 
max-width: 800px; }|



Am 06.03.2021 um 11:31 schrieb Nikolay:

**Comment by whalley** [comment]
Restricting the size on barcharts and linecharts reduces visibility on wider screens, where I previously had the chart stretching to fill the available space it is now squashed into the left hand side with lots of white space to the right. Is the height we maybe want to restrict, which for pie charts will perhaps restrict width also?

e.g.
![Screenshot 2021-03-08 at 20 25 19](https://user-images.githubusercontent.com/487345/110377613-88726400-804c-11eb-9018-68e3c2e0f9d7.png)
![Screenshot 2021-03-08 at 20 24 56](https://user-images.githubusercontent.com/487345/110377617-89a39100-804c-11eb-895e-bf38c6f4613e.png)

**Comment by whalley** [comment]
@vomikan - Is this now fixed? Looks fine to me.

**Comment by vomikan** [comment]
It's still one issue there
![image](https://user-images.githubusercontent.com/6836805/113914322-183f3580-97e6-11eb-8b53-08f586a2e99f.png)

**Comment by vomikan** [comment]
@whalley could you implement your fix for 1.5.0, please?

**Comment by whalley** [comment]
Done

**Comment by renato-mmex** [comment]
Hello dear Nikolay and Mark

Thank you very much for your efforts / commitment to the graphics problem.

But I don't think users are happy with this solution.

On a portrait screen you can live with the size of the graphics, but the 
window flickers, MMEX is blocked and can only be closed via the task 
manager.

On a landscape screen, the graphics are still too big. I am a little 
surprised that a usable graphic size could be found for "My Usage", but 
not for the other graphics.

Many greetings
Renato

Am 09.04.2021 um 20:15 schrieb Nikolay:

**Comment by whalley** [comment]
I'm not sure what the flickering/MMEx blocked issue is. 

I have tried the solution on my MacBook and a large hi-res 27" screen and am unable to see any issues. 

Perhaps Nikolay can comment from a Windows perspective. 

Hopefully we can resolve this.

**Comment by renato-mmex** [comment]
Hi

I test each new version on my 3 screens.
Since the last MMEX versions, MMEX no longer starts on the screen on 
which it was last closed.
MMEX starts on the screen (landscape, 1920x1080) defined for the main 
Windows display.

Because the graphics are not displayed as large (normal size) on the 
screen (portrait format, 1080x1920), I move them there.  If I now select 
Categories/Summary, the scroll bar flickers, it appears and disappears 
and MMEX is dead. We already had this effect when the old master.css was 
still interfering.

I am also moving to the third screen (landscape format, 3840x2160) as a 
test, here there is only the problem that the graphics are even larger / 
dominant.

Greetings Renato


Am 09.04.2021 um 23:50 schrieb Mark Whalley:

**Comment by vomikan** [comment]
I used to see a glitch with flickering, but now I can't reproduce it in a single monitor configuration.
