### ISSUE TITLE
Totals on the "Transaction Report" are misleading when Transfers are included

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2883]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

The totals on the "Transaction Report" are misleading when Transfers are included as they appear as two separate transactions A->B and B->A but both appear as debits from the source account. If you choose to just include Withdrawals and Deposits in the "Transaction" report then the totals are correct.

Think we may need to consider clarifying this on the report and/or excluding transfers from the total

See: https://forum.moneymanagerex.org/viewtopic.php?p=21724#p21724

**Comment by vomikan** [comment]
I can't reproduce this issue

![image](https://user-images.githubusercontent.com/6836805/107130693-3b7e5f00-68e1-11eb-8380-c4fd43245f04.png)

**Comment by whalley** [comment]
Good point. Yes the description of the issue is wrong, my mistake.

The issue is that only the 'Transfer To' items are included in the report, If you select 'Transfer To' in the filter no transfers are shown.

E.g in the attached database where the Total wealth is £1,988. If you do a transaction report for everything then it looks as if the grand total is £-4,012, when in reality it is £-12 (as transfers are not balanced).

[issue2883.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/5937940/issue2883.mmb.zip)
