### ISSUE TITLE
Transaction report style

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2893]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

It's plain designed.
![image](https://user-images.githubusercontent.com/6836805/107145874-a23d6000-6955-11eb-8ca0-73d82becc0f7.png)

**Comment by whalley** [comment]
@vomikan  I think the transaction reports should actually be a wxListCtrl in the same way as we present individual accounts. That way we get the benefit of the full set of available actions and easy multi-editing across accounts. Changing the existing account list control to support an account name column should be straightforward and we just filter on this when displaying individual accounts.

**Comment by whalley** [comment]
Bulk of work done to support this, a few items I need to finish off:
1. Closed account handling - should be able to filter out, the update dialog handles some of this
2. Filter - Should allow multi-account select, and need to check suitability of 'Statement Date' filter
3. Balance not suitable for this view
4. Should we revert to old view for single transaction list control rather than present account? If hidden we can adjust payee with < and > as before
5. Need to remove old report from code as tidy-up.

**Comment by vomikan** [comment]
It turned out interesting. But it is debatable.

**Comment by whalley** [comment]
@vomikan What are your views? I'm thinking the full accounts view fits better into the normal account view rather than the reports. Probably want to retain the existing report and tidy that up if somebody wants a pretty report to view/print.

**Comment by vomikan** [comment]
I have already thought about a similar representation of transactions. The name of this view is more appropriate: "Events". When all transactions are visible, no matter which account. But the priority is sorting by date and time.
![image](https://user-images.githubusercontent.com/6836805/107756835-d5a53380-6d35-11eb-92a7-df57e3ea54d7.png)

We can sacrifice the report in principle or add a menu item - Preview Report.

I am in favor of hiding the "account" column when looking at a single account.
![image](https://user-images.githubusercontent.com/6836805/107756939-f7061f80-6d35-11eb-9ad4-f47cc7fb7661.png)

**Comment by grumpy235** [comment]
Mark,
Minor irritation, compiling using VS2017 throws following warning
2>D:\Projects\mmex\src\mmchecking_list.cpp(314,42): warning C4129: '(': unrecognized character escape sequence
2>D:\Projects\mmex\src\mmchecking_list.cpp(314,42): warning C4129: ')': unrecognized character escape sequence

**Comment by vomikan** [comment]
It's better to use PLURAL
```
    int toPaste = m_selectedForCopy.size();
    wxString pasteStr = (toPaste) ?  _("&Paste Transactions \(%d\)") : _("&Paste Transaction");
    menu.Append(MENU_ON_PASTE_TRANSACTION, wxString::Format(pasteStr, toPaste));
```

```
    int toPaste = m_selectedForCopy.size();
    menu.Append(MENU_ON_PASTE_TRANSACTION,
        wxPLURAL(_("&Paste Transaction"), wxString::Format(_("&Paste Transactions (%d)"), toPaste), toPaste)
    );
```

**Comment by vomikan** [comment]
Or
```
 wxString::Format( wxPLURAL(_("&Paste Transaction"), _("&Paste Transactions (%d)"), toPaste), toPaste)
```

**Comment by vomikan** [comment]
salt is salty 
```
(toPaste < 2) ? 1 : toPaste
```
simple ```toPaste``` should be enough.

**Comment by vomikan** [comment]
Sort order is broken. Can't upload screenshot.

In case if in All trabsaction panel sort order changed to, for example, account then in an named account it would be payee.

**Comment by whalley** [comment]
> simple `toPaste` should be enough.

zero is treated a plural, which I did not want.

**Comment by whalley** [comment]
> 
> 
> Sort order is broken. Can't upload screenshot.
> 
> In case if in All trabsaction panel sort order changed to, for example, account then in an named account it would be payee.

Think I know what that is related to :-)  It's due to the need to adjust the columns based on view - Missed the sort - Will fix later...
