### ISSUE TITLE
Updating prices in Investment Portfolio 

### ISSUE THREAD

**Issue by wirmike** [moneymanagerex/moneymanagerex#2909]
> Using the "Edit Stock Investment" dialogue as per User Guide.  Can amend 'Curr. Share Price' field, but 'Price Date' field greyed-out and unalterable.
Oddly, price date history logged for MAR and JUNE 2020.
Maybe I have missed something!
Hope you can help.
Thank you!
> Please do not remove information attached below this text.

<hr>Version: 1.3.6 64-bit<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMac 10.13)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0<br>
<br>
Build: Dec 28 2020 21:18:13 <br>
 • CMake 3.19.1<br>
 • GNU Make 3.81<br>
 • gettext 0.21<br>
 • Clang Apple LLVM 12.0.0 (clang-1200.0.32.28)
<br>
<br>
OS:<br>
 • macOS High Sierra Version 10.13.6 (Build 17G14019)<br>
 •  English (Western (Mac OS Roman))<br>
 • 1440x900 32bit 144x144ppi

**Comment by vomikan** [comment]
https://www.youtube.com/watch?v=UJr2M743p10

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2919
