### ISSUE TITLE
Printing Account View Crashes MMEX - v1.37

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2915]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Looking at v1.37 build date 2021.02.15 20:15:40 on Windows 7, portable build
Printing Account View crashes MMEX. File->Print... then crash.

Printing Transaction Report works.

Printing Account View with v1.36 portable works.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mmex.exe
  Application Version:	1.3.7.0
  Application Timestamp:	602ad703
  Fault Module Name:	StackHash_dd97
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb67f
  Exception Code:	c0000374
  Exception Offset:	00000000000bf262
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	dd97
  Additional Information 2:	dd97d28f826e7d3eb178af41f482a719
  Additional Information 3:	f594
  Additional Information 4:	f5948e15a2b031d203e5e0dfbc700421

![MMEX 1 37 Print Crash W7](https://user-images.githubusercontent.com/63317977/107999029-730d9b00-6fb4-11eb-80c8-2ecd70b0a02f.png)

**Comment by whalley** [comment]
Has printing of account views ever worked? I appreciate it should not crash (we can fix that). On MacOs I've never had the ability to print, other than from reports.

**Comment by whalley** [comment]
Until I get clarity on whether this has ever worked, I have submitted fix to disable the print menu and toolbar icon when printing is not possible.  So no more crash for this.

**Comment by 2BeeOrNot** [comment]
1.35 and 1.36 on Mac brings up a print dialog but shows and prints a blank page.
1.37 on Mac pops up a message saying "The operation could not be initialized" with a OK button.

1.35 and 1.36 portable on Windows 7 brings up a print preview window and I can print from there.
1.37 portable on Windows 7 crashes.
1.33 installed on Windows 7 brings up a print preview window and I can print from there.

**Comment by whalley** [comment]
@2BeeOrNot Thanks for the exhaustive testing. Will leave this open and investigate further , in the meantime have displayed print for these panels to avoid crash.

**Comment by whalley** [comment]
Actually, just spotted why I broke the print .....(still need to look at Mac blank page issue).... I deleted a virtual function. Will pop it back.

**Comment by whalley** [comment]
Well that was a pain...

1. Print all re-enabled... That was the easy part.
2. Fixing the MAC "...could not be initialized" issue was the pain!  But turned out, as these things do, that I needed to add one extra line to get the print control to generate the page (which was not need for PC).... 

Tested on MAc and PC and printing now works fine.

**Comment by whalley** [comment]
Latest Mac build here: https://drive.google.com/uc?export=download&id=1rB53fqaaDTqSb5tDQF6ggvGcoVuKvLa3
