### ISSUE TITLE
Currency Icon on Tools Menu - Not Square - Cause of Text Alignment Issue on Mac

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2917]
On both Mac and Windows the currency icon in the tools menu for Organize Currency... is not centered horizontally with the icons above and below it. It is most apparent on a Mac where the text is positioned to the left of the other labels. For fun I looked the size of the icons. I created the PNG's in currency_png.h and all the icons are not square. The biggest one is 34 x 48.  The smallest is 11 X 16. I checked a few other icons and they are square except for New Account in the accounts menu which is off a little bit. For more fun I took the original image SVG from openclipart.org, made it square, and created a new currency_png.h file. If I'm correct and you want to try it let me know and I'll post the resized SVG, PNG's, and currency_png.h file.

<img width="354" alt="MMEX Tools Menu 2" src="https://user-images.githubusercontent.com/63317977/108008641-cb519680-6fce-11eb-857d-730e8b491c4f.png">

<img width="335" alt="MMEX Accounts Menu" src="https://user-images.githubusercontent.com/63317977/108007808-db687680-6fcc-11eb-8228-6d42684510bf.png">

**Comment by whalley** [comment]
Yes there are a few inconsistencies there. I think perhaps we want to revisit the icons and update to a more modern set. Some of them are a little too 'busy' when at lower resolution. In the meantime if you do have any better aligned SVGs feel free to supply them.

**Comment by vomikan** [comment]
FYI 
I've used some icones from https://openclipart.org/
https://github.com/moneymanagerex/Art/blob/master/PC/SVG/images.md

**Comment by 2BeeOrNot** [comment]
Here is my currency icon. Original SVG with canvas increased horizontally to make it square. Then centered. Also contains PNG's for each size, .h file for each size and a combined .h file.
[MMEX New Currency.zip](https://github.com/moneymanagerex/moneymanagerex/files/5991412/MMEX.New.Currency.zip)

**Comment by whalley** [comment]
@2BeeOrNot Thanks, I'll look to include that.
