### ISSUE TITLE
All Transactions Panel

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2918]
# All Transactions Panel

![image](https://user-images.githubusercontent.com/6836805/108048081-a9e8bd00-7057-11eb-80a6-95e79f832ddb.png)

https://github.com/moneymanagerex/moneymanagerex/issues/2893

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/108125835-1ac0c100-70ba-11eb-9027-1e6a1f8fc1d5.png)

![image](https://user-images.githubusercontent.com/6836805/108125852-22806580-70ba-11eb-8a8d-4a067c07ec4e.png)

**Comment by whalley** [comment]
https://github.com/whalley/moneymanagerex/commit/26cd2696ba092ffb575ba6bc2ca7a788340d7b43 resolves sort order issue.

**Comment by vomikan** [comment]
An assumption. If separate folder 
![image](https://user-images.githubusercontent.com/6836805/109020768-50256a00-76cb-11eb-83f8-f11606c5c38f.png)
would be created for deleted transaction then any deleted transactions may be undo deleted.
https://www.svgrepo.com/svg/316810/duotone-trash-2

Simple to implement, but an interesting feature.

**Comment by whalley** [comment]
@vomikan - Like the idea, have created feature request.

**Comment by vomikan** [comment]
@whalley  I don't understand is this commit whalley@26cd269 resolves sort order issue?

**Comment by whalley** [comment]
Yes it is, column sort works for me. Are you still having issues?

**Comment by vomikan** [comment]
It was a bug when I have tested last time. I gonna check with last release a bit later.

**Comment by vomikan** [comment]
Unfortunatly, the bug is still there. For example:
1) Click the "Category" column on the "All transactions" view.
![image](https://user-images.githubusercontent.com/6836805/109067396-8250bf00-76ff-11eb-93ba-f7d9c3d128d9.png)
2) Switch to bank account
![image](https://user-images.githubusercontent.com/6836805/109067570-bdeb8900-76ff-11eb-96f3-eb35a1a86a86.png)
 Incorrect column!

**Comment by whalley** [comment]
OK, will check that one out. Good spot.

**Comment by whalley** [comment]
Because the all transaction and normal checking panels have different columns the sort order is now preserved independently, the same was previously done for column width/hiding but I missed the sort setting.

Now fixed.

**Comment by vomikan** [comment]
#3209
