### ISSUE TITLE
Update the application icons

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2923]
# Description of the feature

I think we need to revisit the icons and update to a more modern set. Some of them are a little too 'busy' when at lower resolution.

**Comment by whalley** [comment]
Related https://github.com/moneymanagerex/moneymanagerex/issues/2917

**Comment by whalley** [comment]
Some great icons here: https://www.svgrepo.com/

How do people feel about coloured icons vs grayscale or duotone? I have no real issue so long as the icons are not too 'fussy' or have too many colours and have a common colour theme.

E.g: something like.

![Screenshot 2021-02-17 at 16 15 38](https://user-images.githubusercontent.com/487345/108233780-058c7680-713c-11eb-839e-2cc5c617d593.png)

**Comment by 2BeeOrNot** [comment]
I like your preview above - looks like the duotone collection. I like the outlined collection better. Whatever you choose the icons should have a common look and feel and color scheme like they were all designed by the same person. Most, if not all, of the current icons appear to have originated as clip art of various sizes by different designers and have been resized to be used as a not always square icon.

If you like outline icons have you looked at [https://materialdesignicons.com/](url)? Using the advanced export you can change the foreground (and background) color. So you can have green instead of black, grey or blue without having to edit the image manually if you want a little color.

If you go with new icons how about changing the sort order icon in the account view and all transactions too. IMO it's too tall. It takes up the entire vertical height of the column header. I would like to see a simple up or down arrow.

**Comment by whalley** [comment]
@2BeeOrNot  - Yes there is a good set @ https://materialdesignicons.com/  thanks for the pointer. I also agree about the sort order icon :-)

Do you fancy having a go at compiling a list of SVGs we can use to have a common look and feel. The list of icons can be found here: https://github.com/moneymanagerex/moneymanagerex/tree/master/resources.

Might be worth compiling some sample suggestions intentionally that we can review to see how they look, a set like -

new_db.svg
open.svg
new_acc.svg
home.svg
category.svg
payee.svg
currency.svg
filter.svg
grm.svg
options.svg
new_trx.svg

I can create the pngs and header files from them.

What do you think?

**Comment by vomikan** [comment]
I like the duotone collection better as is. Seems it easy to change the color of the svg file by text editor.
![image](https://user-images.githubusercontent.com/6836805/108265752-3ee3d700-717a-11eb-8be5-1bbba0e1eff4.png)
I suggest assigning a corporate color.

#339933
![image](https://user-images.githubusercontent.com/6836805/108266299-fbd63380-717a-11eb-8802-92a2ee78d5bc.png)

**Comment by vomikan** [comment]
I like #006633 color.

**Comment by whalley** [comment]
Agreed, that color looks good. I'll run the icon samples I have through a script to recolor and push up a screen shot later...

There is already a good selection in the duotone pack so we would just need to handcraft a few extras...

**Comment by vomikan** [comment]
I believe all used icons contains here:
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/images_list.h 
Unfortunately, not clear how they should looks.

**Comment by vomikan** [comment]
I think that an easy way is to create some demo menu or other GUI element where to represent all the icons above.
Or save it to file some way like this:
```
img.SaveFile(name + ".png", wxBITMAP_TYPE_PNG);
```
and create html page like this one:
https://github.com/moneymanagerex/Art/blob/master/PC/SVG/images.md

**Comment by whalley** [comment]
![Screenshot 2021-02-18 at 00 10 59](https://user-images.githubusercontent.com/487345/108284884-f4fcf000-717d-11eb-9a45-67c051438791.png)

Will create something under the Art repo to capture these.

**Comment by 2BeeOrNot** [comment]
I can have a go at documenting current icons and where they are used. And take a stab at maping them to possible duotone icons. I don't want to start if someone else if going to do it (and I'm not the fastes at this ). I'd start with the .md code in [https://github.com/moneymanagerex/Art/blob/master/PC/SVG/images.md](url), put it in my text editor and update it. Then add potential duotone icons. All manually. Quickly looking at the toolbar icons this link is out of date, there are 12 toolbar icons but current 1.37 has 17 icons.

I do like the green. I actually thought of that instead of black, gray or the blue in the image about when I mentioned that [https://materialdesignicons.com/](url) allows you to change colors before downloading. Green like your logo.

For example here I have update the text for the first two toolbar icons to the actual tool tip and put in a random duotone icon.

This is what I added to the file for the duotone icon.  ` | [img](https://www.svgrepo.com/show/316557/duotone-arrow-left-circle.svg) | [page](https://www.svgrepo.com/svg/316557/duotone-arrow-left-circle)`
I know nothing about markdown. Is there a way to make the SVG image slightly bigger?

Ha! As I was writing this your toolbar preview in green popped up. I like it. Maybe you've got this already.

![ToolbarMB3](https://user-images.githubusercontent.com/63317977/108284389-201e1a00-7153-11eb-9b12-366882d8f7ca.jpg)

**Comment by whalley** [comment]
Have added a starter page to begin collating these. @vomikan have pushed to the repo but have not got permission to merge.

@2BeeOrNot My starter is here: https://github.com/whalley/Art/tree/master/Image-Library

Would be great if you could own the collation of these. The important thing to capture is the name and SVG - Can generate everything else from that.

**Comment by vomikan** [comment]
@2BeeOrNot  https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown regarding image scaling.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/108349464-0d0f5680-71f4-11eb-924e-90fcf5cd116b.png)

**Comment by whalley** [comment]
I'm liking some of the choices there...

**Comment by vomikan** [comment]
svg files already there:
https://github.com/moneymanagerex/Art/blob/master/Image-Library/README.md

**Comment by vomikan** [comment]
Warm, lamp color))
![image](https://user-images.githubusercontent.com/6836805/108355019-4d260780-71fb-11eb-9340-73eef8372ec0.png)

**Comment by whalley** [comment]
That icon does fit with the theme :-)

**Comment by whalley** [comment]
Question?: Do you think having icons on the menus gives any benefit? Personally I prefer the menus to just have text. Views?

**Comment by vomikan** [comment]
There are four reasons to remove icons from the menu:
1) Make it easier to switch to new icons;
2) Uniformity in the design of the menu;
3) No one will be offended;
4) In the final, this can be fixed with a single patch.

I couldn't think of a single reason to leave the icons.
0)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/108488347-54a7e800-72b1-11eb-8804-4981cf925ace.png)

**Comment by whalley** [comment]
Yes we should include alongside GNU GPL license, add reference in About / License, and a credit in contrib.txt (already have section on Icons/Art)

**Comment by whalley** [comment]
> 3. No one will be offended;

Somebody is always offended :-)

**Comment by vomikan** [comment]
> Somebody is always offended :-)

See point No. 4

**Comment by vomikan** [comment]
@whalley  I've already thought about it, but I probably failed at the next task.
It's much better to use svg resources without converting it to png 16*16 24*24 etc.
Or use a conversion, but intermediate within the program.
We have a large number of svg files available. In the future, you will still have to redo some of them.
It is much easier to throw a new file without transforming it.

https://docs.wxwidgets.org/trunk/classwx_s_v_g_file_d_c.html

**Comment by whalley** [comment]
http://wxsvg.sourceforge.net/
https://sourceforge.net/projects/wxsvg/files/wxsvg/1.5.22/

**Comment by whalley** [comment]
nanosvg looks the most lightweight and i hope would be fine for the simple SVGs we have.

**Comment by vomikan** [comment]
An Expiriment.
I've created theHeart icon and takeavailable Money icon.

Join it manually using text editor

```
<svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

<path opacity="0.2" fill-rule="evenodd" clip-rule="evenodd" d="M4 7C3.44772 7 3 7.44772 3 8V16C3 16.5523 3.44772 17 4 17H20C20.5523 17 21 16.5523 21 16V8C21 7.44772 20.5523 7 20 7H4ZM12 14.5C13.3807 14.5 14.5 13.3807 14.5 12C14.5 10.6193 13.3807 9.5 12 9.5C10.6193 9.5 9.5 10.6193 9.5 12C9.5 13.3807 10.6193 14.5 12 14.5Z" fill="#006633"/>

<path 
  d="M18 9.5V14.5M6 9.5V14.5M4 17H20C20.5523 17 21 16.5523 21 16V8C21 7.44772 20.5523 7 20 7H4C3.44772 7 3 7.44772 3 8V16C3 16.5523 3.44772 17 4 17ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" 
  stroke="#006633" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<!-- the element below is small heart -->
<path   
   d="M 7.3396333,4.1545432 4.3738867,6.9360361 1.4081399,4.1545432 C 0.71778288,3.4170473 0.75619798,2.2596036 1.4934532,1.5694269 l 0.066993,-0.062662 C 2.2977618,0.81661931 3.4551453,0.85476346 4.1455324,1.5922594 L 4.3738867,1.8299992 4.6022709,1.5922594 C 5.2926279,0.85476346 6.4500418,0.81661931 7.1874172,1.5067656 l 0.066993,0.062661 c 0.7371654,0.6901767 0.7755793,1.8476204 0.085223,2.5851166 z"
   style="stroke-width:0.0300822" fill="#cc3300"/>


</svg>

```

![image](https://user-images.githubusercontent.com/6836805/108523342-d7936780-72de-11eb-993b-9897f94275cb.png)

**Comment by vomikan** [comment]
The same hack with a red cross element
```
<svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">

<path opacity="0.2" fill-rule="evenodd" clip-rule="evenodd" d="M4 7C3.44772 7 3 7.44772 3 8V16C3 16.5523 3.44772 17 4 17H20C20.5523 17 21 16.5523 21 16V8C21 7.44772 20.5523 7 20 7H4ZM12 14.5C13.3807 14.5 14.5 13.3807 14.5 12C14.5 10.6193 13.3807 9.5 12 9.5C10.6193 9.5 9.5 10.6193 9.5 12C9.5 13.3807 10.6193 14.5 12 14.5Z" fill="#006633"/>

<path 
  d="M18 9.5V14.5M6 9.5V14.5M4 17H20C20.5523 17 21 16.5523 21 16V8C21 7.44772 20.5523 7 20 7H4C3.44772 7 3 7.44772 3 8V16C3 16.5523 3.44772 17 4 17ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" 
  stroke="#006633" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<!-- -->
<path   
   d="M 7.3396333,4.1545432 4.3738867,6.9360361 1.4081399,4.1545432 C 0.71778288,3.4170473 0.75619798,2.2596036 1.4934532,1.5694269 l 0.066993,-0.062662 C 2.2977618,0.81661931 3.4551453,0.85476346 4.1455324,1.5922594 L 4.3738867,1.8299992 4.6022709,1.5922594 C 5.2926279,0.85476346 6.4500418,0.81661931 7.1874172,1.5067656 l 0.066993,0.062661 c 0.7371654,0.6901767 0.7755793,1.8476204 0.085223,2.5851166 z"
   style="stroke-width:0.0300822" fill="#cc3300"/>

  <path
     d="m 22.290053,14.364492 -8,8 m 3e-5,-8 7.99997,8"
     stroke="#001A72"
     stroke-width="1.5"
     stroke-linecap="round"
     stroke-linejoin="round"
     id="path965"
     style="stroke:#cc3300;stroke-opacity:1" />
</svg>
```

![image](https://user-images.githubusercontent.com/6836805/108530289-7d96a000-72e6-11eb-9940-66ee5ae870d3.png)

**Comment by whalley** [comment]
Like the idea of maintaining a single image then adding an overly is the way to go. Could also do this by manipulating the image in wxWidgets. 

For the SVG -> PNG conversion I already have a shell script that I use to:
1. Change the SVG color
2. Do the conversion to PNG (at various sizes) 
3. Create the PNG header file.
It can convert them all at once.

Can easily adapt to merge in those extra bits as needed. 

I think doing the conversion at runtime might be a bit costly.

We can in future look to include the conversion as part of the build process.

**Comment by vomikan** [comment]
@whalley  what about this trick?
![image](https://user-images.githubusercontent.com/6836805/108591874-f8f66100-737b-11eb-80e5-87f029c6c1e3.png)
I suggest do not used red small heart to mark favorite accouts. This will be more consistent with the specified style.

**Comment by vomikan** [comment]
I have collected almost a complete collection of icons, except EDIT_ACC.
Thus, the new appearance can be introduced in version 1.3.7

**Comment by whalley** [comment]
Excellent. 

Just a thought, could we perhaps just recolour the icon for favourite and closed. Shade of red for favourite and perhaps gray for closed?

**Comment by vomikan** [comment]
I like the idea to use gray for closed.
![image](https://user-images.githubusercontent.com/6836805/108593494-0c59fa00-7385-11eb-8f4d-85fc14848ae8.png)

**Comment by whalley** [comment]
Just had a thought ....

Why don't we create another category in the navigation view where we display the favourite accounts together. Can still display them in the usual categories. Rather like a favourites in Windows/Mac file browsers.

**Comment by whalley** [comment]
Of course would need a new icon for the favourite group/category. Perhaps a star.

**Comment by vomikan** [comment]
https://www.svgrepo.com/svg/316579/duotone-bookmark

**Comment by vomikan** [comment]
Only now did I realize that this was a brilliant idea. You can not make a separate icon for favorites, but a separate section.
This is not difficult to do. In addition, we reduce the number of images.

**Comment by whalley** [comment]
Yes we just need an icon for OPEN and an icon for CLOSED accounts (same icon, just different colour). 

Favourite accounts are then replicated in a favourite section with the icon you indicated. 

Easy to do as you say.

**Comment by whalley** [comment]
@vomikan. Is this something you want do or should I make the changes?

**Comment by vomikan** [comment]
It seems that everything is clear and we are on the same page.

**Comment by whalley** [comment]
OK, I'll do a first pass with new toolbar, navigation, and turn off menu icons. Once we have reviewed I'll do a second commit with the remaining application icons.

**Comment by vomikan** [comment]
Before | After  
:-- | :-- 
![](https://github.com/moneymanagerex/Art/blob/master/PC/mmex1.png?raw=true) |  ![](https://user-images.githubusercontent.com/6836805/108635683-af983580-7491-11eb-8c20-78543ddb3807.png)

**Comment by vomikan** [comment]
In general I like it very match.

**Comment by whalley** [comment]
Hmm, why are the "Home" and "Cash Flow" icons darker than the other icons?

Whilst I do like the new look, i feel it probably needs a bit of tweaking, e.g.

NEW_DB and OPEN icons need to use lighter opacity like the others, at the moment they don't align with the theme.
SAVINGS_NORMAL / CLOSED icon is a little too cluttered (just my view) need something a bit simpler.
NEW_NEWS - think we should just fill the square in the icon with the green shading rather that use yellow as at present.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/108637067-06097200-749a-11eb-8de9-eb4028eba405.png)

**Comment by vomikan** [comment]
We need to adjust the colors of the graphs to our theme.

**Comment by vomikan** [comment]
![](https://github.com/moneymanagerex/Art/blob/master/Image-Library/SVGs/exclamation.svg)
 What about this icon for new news?

**Comment by vomikan** [comment]
Not sure what is the "Unreconlilled" ico.... possible it's empty transparent png. Now it became black.

![image](https://user-images.githubusercontent.com/6836805/108689411-135e4500-750a-11eb-873e-110d60518467.png)

**Comment by whalley** [comment]
Will have a look at that later, possible linked the 'mask' change I made on the imagelists - works fine on Mac.

What about below for status icons?

Reconciled
![RECONCILED_48](https://user-images.githubusercontent.com/487345/108694103-852c9380-74f6-11eb-8a00-eb356d2da66e.png)

Duplicate
![DUPLICATE_STAT_48](https://user-images.githubusercontent.com/487345/108693997-662e0180-74f6-11eb-8e77-415ff6536792.png)

Follow Up
![FOLLOW_UP_48](https://user-images.githubusercontent.com/487345/108693998-66c69800-74f6-11eb-86ea-0ef08975ac5a.png)

Void
![VOID_STAT_48](https://user-images.githubusercontent.com/487345/108694000-675f2e80-74f6-11eb-90b8-82f0cc23d061.png)

**Comment by vomikan** [comment]
I like these icons. Maybe they're a little complicated.
There are more lightweight ones:
![image](https://user-images.githubusercontent.com/6836805/108695011-d6e21780-7510-11eb-8186-9b0ad88a0b0b.png)

**Comment by whalley** [comment]
OK let's see what they look like. Perhaps with VOID in Red to highlight it?

**Comment by vomikan** [comment]
>Perhaps with VOID in Red to highlight it?

I think so.

**Comment by vomikan** [comment]
An interesting case. Some icons when selected are change his color but others no.
![image](https://user-images.githubusercontent.com/6836805/108709117-5842a580-7523-11eb-8200-4ddcfc6c2198.png)

![image](https://user-images.githubusercontent.com/6836805/108709140-61337700-7523-11eb-85b1-ccb9732dc269.png)

**Comment by reddyshyam** [comment]
Apart from all being single color [which might make it hard for users to know what icon does what (colors are easy to spot than shapes)] I like what I see on beta4. 👍

Could we not bring in colors or mono is the theme going forward?

**Comment by vomikan** [comment]
I've created the following icons:
![image](https://user-images.githubusercontent.com/6836805/108719238-5cc18b00-7530-11eb-857e-8c7d17b96e3f.png)

**Comment by reddyshyam** [comment]
> I've created the following icons:
> 
> ## Statuses
> enum	Meaning	Icon	Alternative
> RECONCILED		![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/check.svg)	
> DUPLICATE_STAT		![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/duplicate.svg)	
> FOLLOW_UP		![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/followup.svg)	
> VOID_STAT		![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/void.svg)	
> ![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/nnews.svg)

These look just great! Simple, minimalistic, colorful and meaningful. 👌

**Comment by whalley** [comment]
These should be in the latest commit.

**Comment by reddyshyam** [comment]
Thanks @whalley, will check them out shortly. 👍

**Comment by grumpy235** [comment]
Guys,
Just in case you forget General Reports Manager will need a small change...
![GRM](https://user-images.githubusercontent.com/24897056/108743758-0bfe6200-7531-11eb-8ee5-6954999093cb.PNG)

**Comment by vomikan** [comment]
![](https://raw.githubusercontent.com/moneymanagerex/moneymanagerex/master/docs/en/grm_toolbar.png)

**Comment by 2BeeOrNot** [comment]
Looking at latest 1.37 portable build on Windows 7. I really like what you have done with the icons. And pulled it together so quickly. A couple of comments.

In addition to New DB and Open DB icons mentioned above being too dark the Register/View Release Notifications icon is too dark too.

IMO the status indicators (void, reconciled etc.) would look better with a larger stroke width. Maybe 2.0 or 2.5 instead of 1.5. The sort indicator icon too.

And probably on your do to list the account user icons all have a black background. Ruins the shiny new chrome.

One change I don't like is the addition of transform: translateY(-1px); to .shadow:hover and .shadowTitle:hover in master.css. On hover the widgets move slightly up when hovered. But I can easily fix it.

MMEX - getting better and now looking better!

**Comment by whalley** [comment]
@2BeeOrNot  - Thanks for the feedback, some good comments there.

I've just posted another commit, mainly some tidy-up of code and organization of icon lists.

At present I've not adopted new icons for these... (Note some of these along with CLIP and WEB appear on dialogs so not sure whether we should stick to black color for these?)

CATEGORY_RELOCATION
CLEAR
EMPTY
LEFTARROWSIMPLE
RIGHTARROWSIMPLE 
IMPORT:
LED_GREEN: 
LED_OFF:
LED_RED: 
LED_YELLOW: 
RIGHTARROW: 
RIGHTARROW_ACTIVE: 
RUN: 
SAVEAS: 
TRXNUM: 
UPDATE:

**Comment by vomikan** [comment]
##options
![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/options.svg)
![]()
![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/clip.svg)
![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/currates.svg)
![](https://raw.githubusercontent.com/moneymanagerex/Art/master/Image-Library/SVGs/grid.svg)

![image](https://user-images.githubusercontent.com/6836805/108779600-2d367100-7578-11eb-8987-2b2dc695bec8.png)

**Comment by whalley** [comment]
Thought an 'eye' would be best of view....

![Screenshot 2021-02-23 at 01 00 57](https://user-images.githubusercontent.com/487345/108789672-a16e1600-7572-11eb-968b-cbef257726f5.png)

Will push change,

**Comment by valsamis-d** [comment]
Hello all,

I'm watching the discussions and wondering where I could get binaries for this 1.37 beta release.

Thank you
Dimitrios

**Comment by reddyshyam** [comment]
> Hello all,
> 
> I'm watching the discussions and wondering where I could get binaries for this 1.37 beta release.
> 
> Thank you
> Dimitrios

Hi Dimitrios,

You can get the latest snapshot from the below link

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex

**Comment by valsamis-d** [comment]
> 
> 
> > Hello all,
> > I'm watching the discussions and wondering where I could get binaries for this 1.37 beta release.
> > Thank you
> > Dimitrios
> 
> Hi Dimitrios,
> 
> You can get the latest snapshot from the below link
> 
> https://ci.appveyor.com/project/moneymanagerex/moneymanagerex

Thanks for the quick response! Pardon my ignorance, but is there any way I could download portable binaries for appveyor?

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37904678

**Comment by reddyshyam** [comment]
Well done @vomikan and @whalley.  👌👍👏 Can't believe just by changing the icons, the app looks entirely re-done. Feels so good. 🙂

**Comment by valsamis-d** [comment]
I agree with @reddyshyam. Indeed the new icons make a great difference! 

Any chance to revise the built-in icons for accounts? The default included ones break consistency of look and feel.

Dimitrios

**Comment by whalley** [comment]
@valsamis-d   --- Yes, this will be looked at!

**Comment by grumpy235** [comment]
Don't think this has been mentioned but for a stock loss then get a black square.
First line is a Loss and second a Gain. Adding a price which converts the loss to a gain gives the correct symbol
![Capture](https://user-images.githubusercontent.com/24897056/108883697-ad52ea00-75fd-11eb-80df-826d81665ac1.PNG)

**Comment by whalley** [comment]
@grumpy235  "Don't think this has been mentioned but for a stock loss then get a black square." -- Fixed, and SVG conversion error.

@2BeeOrNot "IMO the status indicators (void, reconciled etc.) would look better with a larger stroke width. Maybe 2.0 or 2.5 instead of 1.5. The sort indicator icon too." - Fixed, made them 2.5 looks better.

@2BeeOrNot  "In addition to New DB and Open DB icons mentioned above being too dark the Register/View Release Notifications icon is too dark too." - Fixed also.

Have changed the register/view release icon as teh existing one without any fill looked too dark as you say. It will have a bit of fill when new release notes are available.

Will commit changes later this evening

**Comment by whalley** [comment]
> Any chance to revise the built-in icons for accounts? The default included ones break consistency of look and feel.

@valsamis-d  This has been done in latest commit.

**Comment by valsamis-d** [comment]
> 
> 
> > Any chance to revise the built-in icons for accounts? The default included ones break consistency of look and feel.
> 
> @valsamis-d This has been done in latest commit.

They look awesome! Thanks :) Maybe one more, minor, thing to look at is the look when assigning one of the icons to the account. They're kinda hard to see on the black background:

![image](https://user-images.githubusercontent.com/17590539/108951723-335c4880-7671-11eb-8621-0c40a4de64b3.png)

**Comment by whalley** [comment]
@valsamis-d Mac seems to handle the PNG transparency OK, this is limited to Windows.  Have put in a temp Windows only compile difference that seems to work (time permitting I'll see if I can get a consistent solution).

There may be a few more of these lurking around I'll check.

**Comment by valsamis-d** [comment]
> @valsamis-d Mac seems to handle the PNG transparency OK, this is limited to Windows.  Have put in a temp Windows only compile difference that seems to work (time permitting I'll see if I can get a consistent solution).
> 
> 
> 
> There may be a few more of these lurking around I'll check.

Thank you @whalley! It's not a priority. The overall look is just perfect anyway 🙂

**Comment by whalley** [comment]
All icons now updated.

I'm closing this feature issue. If you spot any issues or I have failed to address any comments you have made here then can I please ask that you raise a new defect. This issue is getting a bit long to track now :-)

**Comment by vomikan** [comment]
I am sure this will be the most significant and visible change that users will appreciate.

**Comment by valsamis-d** [comment]
> All icons now updated.
> 
> 
> 
> I'm closing this feature issue. If you spot any issues or I have failed to address any comments you have made here then can I please ask that you raise a new defect. This issue is getting a bit long to track now :-)

Great job @whalley! Thank you 🙂
