### ISSUE TITLE
MMEX database error!

### ISSUE THREAD

**Issue by jcodl** [moneymanagerex/moneymanagerex#2937]
[Window Title]
MMEX database upgrade

[Main Instruction]
MMEX database error!

[Content]
MMEX database version 13 doesn't work with this MMEX version.
Please upgrade MMEX to newer version.

[OK]

I tried version 1.3.3|1.3.6 x64|x86 and same problem :( 13 years of accounting are gone in 60 seconds :( all backups have same problem :(

**Comment by vomikan** [comment]
Please downgrade the DB before use
https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by jcodl** [comment]
Thank you so much MASTER. It is working again :)
