### ISSUE TITLE
Outdated web resource

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2938]
https://play.google.com/store/apps/details?id=com.money.manager.ex

![image](https://user-images.githubusercontent.com/6836805/108817850-8f6b9200-75c9-11eb-90fd-a23e91945974.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2887

**Comment by vomikan** [comment]
seems it should be replaced to http://android.moneymanagerex.org/

**Comment by vomikan** [comment]
I think it would be better to "Goole Play" with "MoneyManagerEx for Android".

**Comment by vomikan** [comment]
http://www.moneymanagerex.org/news?format=feed

**Comment by whalley** [comment]
The link is valid and returns an XML RSS feed. If your browser has the ability to convert the RSS XML to HTML (or you use an extension that does this) then it will display. If not you need to add the URL presented to an RSS reader. 
E.g. in Firefox with the rss.html extension it renders as below:

![Screenshot 2021-02-27 at 18 49 36](https://user-images.githubusercontent.com/487345/109397094-e5736900-792c-11eb-9b80-66da2e2a5d6f.png)
