### ISSUE TITLE
Investment accounts favorites

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2951]
I think it's better to exclude investments from the favorites.
Possible the same for assets.
![image](https://user-images.githubusercontent.com/6836805/108821216-5124a180-75ce-11eb-8bc2-f174d6f8b355.png)

**Comment by whalley** [comment]
What is the reasoning for this? Why not allow the user to include them in favorites if they want to?

**Comment by vomikan** [comment]
1) Stock accounts contains shares, not transactions.
2) Stock accounts may have subaccounts (more closed to checking accounts). 
3) Every accounts in the sample above may be or nor "Favorites" but it is unacceptable to break the connection.
On the example above both MICEX and AAPL are "Favorites" but only MICEX collected in "Favorites" folder.

**Comment by whalley** [comment]
AAPL is also in the Favorites (at the top), though the icon looks wrong - need to look at that.

The favorites just capture what the user has selected for quick access into a list. If for instance the user just want to quickly access APPL stock why should they not be permitted to do that? I'm not sure that what we have breaks anything?

**Comment by vomikan** [comment]
The AAPL is really there. I didn't notice it right away. And the icon that corresponds to the most likely.
