### ISSUE TITLE
Assets transactions

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2952]
I can't explain it, but it doesn't make sense.
![image](https://user-images.githubusercontent.com/6836805/108821641-f5a6e380-75ce-11eb-891a-afecf207f140.png)

**Comment by whalley** [comment]
@vomikan I can't seem to reproduce that. Works fine on OPEN asset accounts but reports the message correctly on CLOSED asset accounts.

**Comment by vomikan** [comment]
[test.zip](https://github.com/moneymanagerex/moneymanagerex/files/6031565/test.zip)
Could you test with the Db attached, please?

**Comment by whalley** [comment]
Hmmmmm.... Yes I get the issue on that DB. Let me check.

**Comment by whalley** [comment]
@vomikan - Just realized I have no idea of how the assets work in MMEX !  Never used them. The odd relationship with accounts and transactions is currently puzzling me...    Might need to park this for now whilst I tidy up a few other things first.. Of course feel free to investigate :-)

**Comment by vomikan** [comment]
>puzzling me
for me as well.
This week i'll got new PC. I can handle this issue.
