### ISSUE TITLE
Dockers

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2959]
@whalley what do you think delete or fix MAC build?

https://travis-ci.org/github/moneymanagerex/moneymanagerex/jobs/760132598

It depend on the folloving code:
https://github.com/moneymanagerex/moneymanagerex/blob/master/.travis.yml#L101-L120

**Comment by vomikan** [comment]
This issue has been fixeb by this commit:
https://github.com/moneymanagerex/moneymanagerex/commit/2e04c25f6d95f64e6e7c8762f259efaf1411d652

**Comment by whalley** [comment]
That is what I like, fixes without me having to comment!
