### ISSUE TITLE
Simplify transfer transaction creation

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#296]
Now we can only add the transfer transaction in checking panel and actually the most intuitive way is from the account itself. 
![mmex_account](https://cloud.githubusercontent.com/assets/721973/5389844/41fad3d6-813e-11e4-88c1-e5bb6707de34.png)

**Comment by guanlisheng** [comment]
Who want to take this?

**Comment by guanlisheng** [comment]
No one? I do think it's very useful

**Comment by vomikan** [comment]
I like the idea but busy now.

2015-03-19 14:51 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/3042b1cf83b6f8e20fc22b300cafd24d7a5cca5d

https://github.com/moneymanagerex/moneymanagerex/issues/420
