### ISSUE TITLE
Add a Deleted/Trash transaction feature

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2963]
# Description of the feature

As suggested by @vomikan in https://github.com/moneymanagerex/moneymanagerex/issues/2918#issuecomment-785143362

We should consider supporting a deleted transaction view from where the user could undone, should be strigh tforward now we have the All Transactions view.

1. Consider auto-delete after 'n' days, and/or delete now.
2. Perhaps color the translation view in light red so user knows he is in this view.
3. Only real option should be to move a transaction back to a given account, all otehr actiosn such as editing must be done once 'un-deleted'
3. Can use this icon
![image](https://user-images.githubusercontent.com/487345/109028792-126c1580-76ba-11eb-82d2-a683fdc978d0.png)
https://www.svgrepo.com/svg/316810/duotone-trash-2

**Comment by n-stein** [comment]
Give PR #5202 and themes PR #3 a go, see what you think.

**Comment by whalley** [comment]
Ecellent.

Couple of quick observations, will do more comprehensive comments when I get more time.

- The deleted transactions are still being be counted in the account balance
- It is possible to edit a deleted transaction, we should disable edit. The transaction dialog should be available but it should not be possible to edit.
- Need to decide what we do with deleted transactions when payee/categories are deleted. E.g. at present it will block deletion of a payee if a transaction using it exists in the deleted state. I think we should allow deletion and remove the deleted transaction.

**Comment by whalley** [comment]
> Hold off this feature until the database changes in https://github.com/moneymanagerex/moneymanagerex/issues/4481 and MMEX v2.0.0 so that deletion can be flagged independently of status? It would then be possible to mark the date/time of deletion so that the deleted transactions can be appropriately ordered.

Good idea. I've already said we should hold off including this in v1.6.0 as we need to do a lot of regression testing and get this right. So we could update the DB in the next release. It is probably cleaner as you say to have a separate marker.

**Comment by tactilis** [comment]
We should also consider whether Undelete Transaction(s) is going to be the full extent of the Undo feature that is periodically requested by users (without much thought about its ramifications).

If we are eventually going to have full-featured Undo, then we should think about how Undelete fits into this.

**Comment by whalley** [comment]
> If we are eventually going to have full-featured Undo, then we should think about how Undelete fits into this.

Can't see that ever happening. Far too much of a re-write for that.

**Comment by n-stein** [comment]
> It is probably cleaner as you say to have a separate marker.

Agreed. Status was the only current field we have that I thought could work. The negative ID idea is interesting, but that's the key field of the database table, so I would be a bit wary of changing it.

**Comment by tactilis** [comment]
> The negative ID idea is interesting

Not very, though. 😉 

Any overloading of existing fields will be a bodge.

Better to design it properly in DB version 16.  Most of the good work you have done can be adapted.

**Comment by tactilis** [comment]
Undo
> Can't see that ever happening. Far too much of a re-write for that.

Agreed. And I really don't see the need for the complexities of Undo if we have the ability in the app to restore deleted transactions and the safety net of database backup files.

**Comment by n-stein** [comment]
A "Changed On" timestamp would also help with identifying the most recently edited transactions. If you make a mistake that impacts a large number of transactions instead of an "undo" button you can sort by changed on date to easily select all the transactions you just changed and correct the mistake.

**Comment by whalley** [comment]
> > It would then be possible to mark the date/time of deletion
> 
> Perhaps something like a "Changed On" timestamp that gets updated whenever a transaction is created, edited, or deleted. Might have more utility.

Think we have a feature request for that somewhere.....

**Comment by tactilis** [comment]
@n-stein 
> Perhaps something like a "Changed On" timestamp that gets updated whenever a transaction is created, edited, or deleted. Might have more utility.

I don't agree that a Changed On timestamp should be updated whenever a transaction is **deleted**.

Deletion followed by Undeletion (i.e. Restoration) of a transaction should _always_ return the transaction to the same state it was in prior to deletion. If you update the timestamp when deleting, then it prevents seamless restoration (just like using a status of 'T' prevented the restoration of the prior Status).

**Comment by whalley** [comment]
OK, sounds like best option then is to add a DELETEDTIME field which holds the time of deletion in YYYY-MM-DDTHH:MM:SS format. If this is present the transaction has been deleted.

**Comment by tactilis** [comment]
@n-stein
> I've updated it to append a "T" to the end of the status when deleted and remove the "T" when restored.

Just checking that this is for testing the functionality associated with Delete/Restore and _not_ for inclusion in an MMEX release until DB v16 & MMEX v2.0.0 when we can add the DELETEDTIME field as the means of signifying that a transaction has been deleted.

If the appended 'T' status code was released in v1.6.1, then we'd have an additional upgrade problem to handle when we release v2.0.0.

**Comment by n-stein** [comment]
Yes, just for testing the rest of the functionality and not intended for inclusion.

Is there a working branch for v2.0?

**Comment by whalley** [comment]
> Is there a working branch for v2.0?

@n-stein No there isn't.  Let's just maintain this against your PR for now. As soon as we get v1.6.0 out (hopefully soon) we can roll this into the v1.6.1Beta.1 and make the DB change, we don't need to wait until v2.

**Comment by tactilis** [comment]
@whalley
> we can roll this into the v1.6.1Beta.1 and make the DB change, we don't need to wait until v2.

For my education please, why is it that some DB changes are being held for v2, while this one can be applied prior to that?
Are there different types of compatibility breaking when the DB schema is updated?

**Comment by whalley** [comment]
> For my education please, why is it that some DB changes are being held for v2, while this one can be applied prior to that? Are there different types of compatibility breaking when the DB schema is updated?

Now that we have broken compatibility with the Android app I feel we can make DB changes as necessary. However, grouping the DB changes limits the number of releases that need upgrade scripts and hence do not support allow fallback to prior version. 

However, I'm wary of making DB changes ahead of actual implementation as we tend to identify other changes/modifications when we implement/test features (e.g. discussion on how we identity the deleted transactions).  I think what would be best is to add tag 'DB Change' to features here in the issue list so we can track those changes that have potential need of DB change.

**Comment by tactilis** [comment]
@whalley 
>Let's just maintain this against your PR for now. As soon as we get v1.6.0 out (hopefully soon) we can roll this into the v1.6.1Beta.1

Unless I am misunderstanding something, it appears that this feature is currently being included in the 1.6.0 builds:
  

![image](https://user-images.githubusercontent.com/4060092/197165512-e61a38f4-63d3-4bd6-ad1e-08ca2e3f7aab.png)

**Comment by whalley** [comment]
It's in a Pull Request with suggested changes to the 1.6.0 Beta2 release but has not been merged. Latest merged code is here....
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/45134132
![CleanShot 2022-10-21 at 10 54 57@2x](https://user-images.githubusercontent.com/487345/197168984-121c2872-3bb3-4b32-972a-29f178672981.png)

**Comment by tactilis** [comment]
Thanks for the explanation Mark.

Maybe I should read...
 
![image](https://user-images.githubusercontent.com/4060092/197179485-0b0c8210-1466-49aa-8c39-3c8e72f513be.png)

**Comment by whalley** [comment]
Now merged into master branch for v1.6.1 Beta testing.

**Comment by n-stein** [comment]
Thanks. Just need a DB v16 upgrade script to add DELETEDTIME to CHECKINGACCOUNT_V1 to continue work on this.

**Comment by n-stein** [comment]
I will add it to my own database for now to continue working, but will reserve my next pull request for when the schema has been updated so it doesn't break anything.

**Comment by whalley** [comment]
> Thanks. Just need a DB v16 upgrade script to add DELETEDTIME to CHECKINGACCOUNT_V1 to continue work on this.

Sure, will do that.

**Comment by whalley** [comment]
Forgot to merge theme changes to add icon and update submodule. Now done

**Comment by whalley** [comment]
DB change (typo on issue number!): https://github.com/moneymanagerex/moneymanagerex/pull/5232/commits/4ff5d3409d1d072ecfb9c2e6576f1b7ff793737e

**Comment by whalley** [comment]
Couple of observations.

- Suggest using the 'T' to delineate the date and time, see: https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

![image](https://user-images.githubusercontent.com/487345/198527803-024c67fe-1037-441d-977e-b28f2c125b63.png)

- It is again allowing me to edit deleted transactions.
- Probably be good to add a 'Deleted On' column to the 'Deleted Transactions' view

**Comment by n-stein** [comment]
> Suggest using the 'T' to delineate the date and time,

Done. Stored with 'T' in the DB but displayed with ' ' in the transaction panel for readability.

> It is again allowing me to edit deleted transactions

Fixed

> Probably be good to add a 'Deleted On' column to the 'Deleted Transactions' view

Done

**Comment by tactilis** [comment]
> Stored with 'T' in the DB but displayed with ' ' in the transaction panel for readability.

Do we take account of the user's timezone when adjusting what is (hopefully) UTC in the database to Local time in the Deleted list?

**Comment by n-stein** [comment]
I used Now() which uses local time by default. All of the other date fields use Today() which also uses local time. We can store in UTC and convert, but is this necessary?

**Comment by n-stein** [comment]
Easy enough. An ISO 8601 timestamp is now stored in UTC and converted to local timezone during display in the transaction panel.

**Comment by n-stein** [comment]
Regarding this bit 
> Consider auto-delete after 'n' days

Performing a time-based deletion during database open should be fairly simple to accomplish with a configurable option under Options -> Other for "Deleted Transaction Retention Period". Maybe incorporate into "Database Backup" section and rename to "Database Options"?

**Comment by whalley** [comment]
Looking great, a few more observations after testing
- The custom fields are still editable for deleted transactions
- The Frequently Used Notes (...) are still usable and can edit deleted transactions.

> Maybe incorporate into "Database Backup" section and rename to "Database Options"?

I prefer that... 

Option is number of days with 30 as default? Perhaps with "0" meaning- 'Never' (for confident, error-free, storage efficient people 😁

**Comment by n-stein** [comment]
> Option is number of days with 30 as default? Perhaps with "0" meaning- 'Never'

I think 30 days is a good default, and 0 would delete immediately (same as current behavior of all releases through 1.6.0). 
In that case, does leaving it blank mean retain 'forever'?

**Comment by whalley** [comment]
> In that case, does leaving it blank mean retain 'forever'?

Or the user enters lot's of 9's....

More seriously. if we are to support 'Forever' then better to have radio buttons for 'Never, 'Forever', 'Days' (with number), rather than by implication. In the DB we can just use -1 for forever.

**Comment by n-stein** [comment]
@tactilis 

> Unless I am misunderstanding something, it appears that this feature is currently being included in the 1.6.0 builds

I noticed this too. AppVeyor is including open pull requests in the beta builds. For example, PR #5244 is still open but is included in the Win beta as of build 5763:

![image](https://user-images.githubusercontent.com/16599929/198716228-7873bcba-9672-4efc-9c0e-90043851efa0.png)

Is this intentional @whalley?

**Comment by n-stein** [comment]
> if we are to support 'Forever' then better to have radio buttons for 'Never, 'Forever', 'Days'

I personally have no need to retain transactions 'forever', and I'm not sure anyone really does. Should we even entertain this option, or just force a non-negative integer input?

**Comment by n-stein** [comment]
> AppVeyor is including open pull requests in the beta builds

I take that back. AppVeyor is creating a single build with the open PR, but does not include it in future builds unless the PR is merged.

**Comment by whalley** [comment]
> > if we are to support 'Forever' then better to have radio buttons for 'Never, 'Forever', 'Days'
> 
> I personally have no need to retain transactions 'forever', and I'm not sure anyone really does. Should we even entertain this option, or just force a non-negative integer input?

I think just 0..999 will be sufficient.

**Comment by whalley** [comment]
> Still, I suppose that means we need to be careful selecting beta build artifacts to only pick the ones with merged code.

Yes. People should be pulling the merged builds not the PRs.

**Comment by n-stein** [comment]
> * The custom fields are still editable for deleted transactions

Fixed

> * The Frequently Used Notes (...) are still usable and can edit deleted transactions

Fixed

Added autodelete after specified number of days. Default is 30. Available via menu path Options -> Others. The cleanup is performed when the database is opened.

![image](https://user-images.githubusercontent.com/16599929/199069310-b7280302-9bf4-4bf6-b12e-5dd8d3e86c09.png)

**Comment by tactilis** [comment]
Current tooltip:

![image](https://user-images.githubusercontent.com/4060092/199075986-96f96858-508f-429e-bb6b-5ff34eb7dc9e.png)

Can I propose that you change the wording to:

"Specify number of days to retain deleted transactions. Transactions older than this will be automatically purged upon database open."

I'm trying to avoid the double use of the word "deleted" in two different contexts, i.e initial deletion and permanent removal.

**Comment by n-stein** [comment]
> change the wording to:\n\n\"Specify number of days to retain deleted transactions. Transactions older than this will be automatically purged upon database open.\

Done

**Comment by tactilis** [comment]
Although the Colour button is insensitive, it is still possible to edit the colour of deleted transactions using the shortcut keys Ctrl+1 to Ctrl+7, and Ctrl+0 to clear the colour.

These keys should be suppressed for deleted transactions.

**Comment by tactilis** [comment]
The deleted transaction highlighted here is a transfer from Acc 1 to Acc 2.

In the Deleted Transactions list:
- The Account is 'Acc 1' (this is correct)
- The Payee is '< Acc 1' (it should be '> Acc2')
