### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2965]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

We took the color #006633 as the basis. 

There is some [magic crap](https://colorscheme.ru/) for identifying matching colors.
![image](https://user-images.githubusercontent.com/6836805/109068137-8204f380-7700-11eb-974d-6eb7d662f636.png)

We need to choose more suitable colors for the graphs.

These colors (income/expences in graph) are very contrasting and not suitable.
![image](https://user-images.githubusercontent.com/6836805/109068342-c85a5280-7700-11eb-856c-b4a9c8a5322c.png)

**Comment by whalley** [comment]
The #006633 color, whilst suitable for icon/site labels, is quite dark for graphs. Personally I like the brighter colors that we have the graphs as it makes them stand out better. I feel as if we use the same or contrasting colors for bar and pie charts then the overall app will become too plain.

I'm no UI expert, so will perhaps I'll leave it for others to comment.

**Comment by vomikan** [comment]
Income | Expences
:--- | :----
![image](https://user-images.githubusercontent.com/6836805/109116137-1ac35f80-7751-11eb-88c0-9ded685b8d68.png) | ![image](https://user-images.githubusercontent.com/6836805/109116258-49d9d100-7751-11eb-9e53-1d6757dc1c27.png)

**Comment by whalley** [comment]
I still prefer the original, the new GREEN does align more closely to the 'theme' but I think the RED looks too dark and needs to be brighter.

Existing
![Screenshot 2021-02-25 at 16 56 30](https://user-images.githubusercontent.com/487345/109188838-3fd4c400-778b-11eb-9f6a-c352dbcbc2f2.png)

Modified
![Screenshot 2021-02-25 at 17 01 33](https://user-images.githubusercontent.com/487345/109188843-4105f100-778b-11eb-9997-9347110502cf.png)

**Comment by whalley** [comment]
Do you think it worthwhile giving people a couple of palettes to choose from for the graphs? Should not be too difficult?

**Comment by vomikan** [comment]
not for ver. 1.3.7

**Comment by whalley** [comment]
Agreed. I'll create a feature request for this and we can look at it in the future.
