### ISSUE TITLE
Support for alternative color palettes

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#2968]
# Description of the feature

A color palette is built into the application for drawing graphs. This palette is fixed.

We should consider providing a number of palettes that the user can choose from and/or allowing the user to define a customer palette.

**Comment by vomikan** [comment]
#3067

**Comment by whalley** [comment]
Palette and other colors for reports can now be defined via metadata.

https://github.com/moneymanagerex/themes
