### ISSUE TITLE
v1.37 New Icons - Mac

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#2970]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

First look at v1.37 for Mac posted yesterday. The navigation and activity highlighting is dark blue, compare to light blue on Win7, making new icons vary hard to see to impossible to see. Same dark blue as on previous Mac version but colored icons were easier to see.

![MMEX Nav Highlight W7](https://user-images.githubusercontent.com/63317977/109240393-6869b780-77a5-11eb-9270-85b6405fefa4.png)
<img width="227" alt="MMEX Nav Highlight" src="https://user-images.githubusercontent.com/63317977/109240403-6bfd3e80-77a5-11eb-9bc3-2f45fca0f850.png">
![MMEX Status Highlight W7](https://user-images.githubusercontent.com/63317977/109240479-8e8f5780-77a5-11eb-95df-f40345ce4bb0.png)
<img width="207" alt="MMEX Status Highligh Mac" src="https://user-images.githubusercontent.com/63317977/109240485-90591b00-77a5-11eb-9875-e2178ffdf480.png">

Not OS specific but several of the user account icons are too big IMO. They are much bigger than the rest of the icons. In Win7 they touch each other but not on Mac. Looking at the images these icons don't have any padding around them on four sides like most of the other icons. They take up the entire width, height or both of the canvas. (about, clock, dog, wallet, cat and trees)

![MMEX Nav User Icons W7](https://user-images.githubusercontent.com/63317977/109240695-f2b21b80-77a5-11eb-8f4f-9e3be4ebd14c.png)
<img width="145" alt="MMEX Nav User Icons Mac" src="https://user-images.githubusercontent.com/63317977/109240699-f47bdf00-77a5-11eb-884a-7b1c38bbf0ab.png">

The next release version deserves more than a .01 version increase to 1.37. v1.50 or v2.00!

**Comment by vomikan** [comment]
As for the size of the icons... It is desirable to bring all the icons to a single size.

![image](https://user-images.githubusercontent.com/6836805/109271305-63961980-7820-11eb-9601-7d028ab8b0f5.png)

These icons can be considered the reference ones.
https://www.svgrepo.com/collection/duotone-basic-interface-icons/

**Comment by whalley** [comment]
Not sure it is possible, or recommended to change, the platform specific colors. WxWidgets uses the native platform color scheme where Dark Blue is used for list and tree control highlighting.

Need to have a think on this one

**Comment by whalley** [comment]
@2BeeOrNot  OK, having thought about this I can add some 'white' to the status icons so that they stand out when selected. See the unselected and selected icons here. Need to perhaps look at this approach for other icons.

What do you think.

![Screenshot 2021-02-26 at 19 37 48](https://user-images.githubusercontent.com/487345/109347041-71708c80-786a-11eb-95cd-38284aebee27.png)

**Comment by 2BeeOrNot** [comment]
I noticed on the most recent Windows build the user account icons I thought were too big have been made smaller. Looks much better IMO.

After posting about the status icons I thought about this some more. It's the highlight color set in System Preferences -> General. I tried other colors even custom and the green is very hard to see on dark highlight colors. I thought maybe making the status icons stroke bigger again after looking at my password manager. The Verizon logo is easy to see on the same highlight color but it's got a bigger stroke. I like the white circle around the status indicator. From the image above it should be easy to see whatever highlight color is used.
![VZW Icons](https://user-images.githubusercontent.com/63317977/109359372-5ba39d00-7853-11eb-8fbd-f9f57d2b441d.jpg)
Programmers and graphic designers too. Thanks for being so receptive to user feedback.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/0e4f9cd48bded8893e62209e5b9e1d07038d4775

**Comment by whalley** [comment]
Have updated icon build script to allow transparency to be replaced by white for all icons in the navigation view. No material effect for Windows, but on MacOS the icons remain clear when navigation rows are selected.

![Screenshot 2021-03-01 at 23 28 22](https://user-images.githubusercontent.com/487345/109572998-177bfb00-7ae6-11eb-9e90-737e0a3f59e3.png)
