### ISSUE TITLE
Duplicate transaction date

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2982]
The date to old when I clone the transaction.
![image](https://user-images.githubusercontent.com/6836805/109416235-00e28080-79ce-11eb-81cc-85d28615a800.png)
 It seems not depend on the following settings:
 
![image](https://user-images.githubusercontent.com/6836805/109416252-21aad600-79ce-11eb-99e0-edf10b982dd3.png)

**Comment by whalley** [comment]
So I think it is behaving as designed. The option you pointed at is "New Transaction Dialog Settings" and is used when creating a new Transaction. When duplicating the complete, existing, transaction details are presented for the user to edit. 

We could change the behavior to generate the date the same as a new transaction; which in most cases I suspect is what the user would want.
