### ISSUE TITLE
Paste transaction do nothing

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2983]
I can't create new transaction by Copy/Past.
![image](https://user-images.githubusercontent.com/6836805/109416359-c88f7200-79ce-11eb-8b48-7c9992f2d97a.png)

**Comment by vomikan** [comment]
DB for reproduce the issue
https://github.com/moneymanagerex/moneymanagerex/files/6056717/test_mmex_db_2021-02-28.zip

**Comment by whalley** [comment]
THis commit broke it: 4b30461fd8b5b43b6c0a0cef873452c52e435126

**Comment by vomikan** [comment]
Thank you.
