### ISSUE TITLE
General Report Manager editor improvement

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#299]
such as 
- more user friendly editor functional as copy/paste/replace
- more syntax
- auto-complete
- static syntax check

**Comment by loki36** [comment]
Hi,

do you think there is a way to add a promt of parameter for repports, in order to pass it to the sql query.

i see 3 types of parameter : string / integer / date

**Comment by guanlisheng** [comment]
Hi, this ticket is for editors improvement purpose. In future we plan to support multi SQLs here
