### ISSUE TITLE
All Accounts displaying in portable application

### ISSUE THREAD

**Issue by benjie500** [moneymanagerex/moneymanagerex#2991]
When I open up the portable application, all of my accounts display regardless of there open/close status. I then proceed to right click on the account section and select accounts visible to "open". If I then close moneymanagerex and re open my database, all accounts are then visible again, regardless of there status.

I only use the portable application on Windows, so unable to verify if this carries across to the full install.

Version 1.3.6

**Comment by vomikan** [comment]
It's feature not a bug.

**Comment by benjie500** [comment]
Hi @vomikan 

Thanks for the reply, I have had a look through the options but can not find an option for this. Can you point me in the right direction?

Thanks

Ben

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/109722377-ac9df300-7bbd-11eb-9ff7-ffaafc2c04ee.png)

**Comment by benjie500** [comment]
Thank you
