### ISSUE TITLE
toolbar icon sizing

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2996]
I find the new green icons dull and confusing, you have to increase the icon size to make them readable / distinguishable.

![image](https://user-images.githubusercontent.com/6836805/109941085-d3eee000-7ce3-11eb-98d1-476f9764bd5e.png)

Maybe you could add an option to this display.

Many greetings
Renato

**Comment by reddyshyam** [comment]
Old looks very out dated but I certainly am for more colors. I too felt single color icons need more attention to know what they are. May be making them multicolor might help but again I guess too much work.

I am 👍 for giving the user option to decide between old or new icons.

**Comment by vomikan** [comment]
I like the uniform style of all icons. But I also noticed that it became more difficult to manage. All icons look monotonous (boring).
Perhaps this is the cost of the transition period. You just have to get used to it.
I suggest you increase the icons and let's see...

**Comment by vomikan** [comment]
@reddyshyam  It is interesting that we are similar in opinion.

As for the work, it is much easier to change the icons than it was before. Just change the svg file. I use [Inkscape](https://inkscape.org/) for this. Let's say thank you @whalley .

https://github.com/moneymanagerex/moneymanagerex/tree/master/resources/toolbar

For anyone who wants to offer a full set of icons, we will make a choice in the app options for this.

See also:
https://github.com/moneymanagerex/Art/tree/master/Image-Library

**Comment by vomikan** [comment]
Look for inspiration in these works: https://www.svgrepo.com/collections/all/2

Almost all of the new icons were taken from this collection:
https://www.svgrepo.com/collection/duotone-basic-interface-icons/

**Comment by reddyshyam** [comment]
Interesting links @vomikan.

Below one looks like will take care of all our icons if we need to move from mono.

https://www.svgrepo.com/vectors/money-business-and-finance/

**Comment by vomikan** [comment]
All the necessary icons are summarized in a tables. 
https://github.com/moneymanagerex/Art/blob/master/Image-Library/README.md
As soon as someone collects the full set, you can make a choice in the settings.

**Comment by whalley** [comment]
My thought was to allow the user to select a 'theme' for the application, and allow these to be built independently of the application build. Though for now we could embed a colored set and duotone set.

As Nikolay mentions please free free to suggest a set of SVGs that we can use. The current full set used within the application are as below, we will need alternates for each of these.

- Toolbar icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/toolbar/README.md
- Navigation icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/navigation/README.md
- Alternate account icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/accounticons/README.md
- Assets icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/assets/README.md
- Settings icons - https://github.com/moneymanagerex/moneymanagerex/tree/master/resources/settings
- Control icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/controls/README.md
- Status icons - https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/status/README.md

**Comment by 2BeeOrNot** [comment]
I like the new green icons. Maybe being mostly a Mac user I am accustom to dull and boring monochrome icons. Maybe use the current  icons and color the outlines and fills? I did this for fun in Thunderbird while taking care of some font and spacing issues.
![TB Folder Icons](https://user-images.githubusercontent.com/63317977/110033148-00682380-7d07-11eb-9363-14db2afaefa2.jpg)

**Comment by reddyshyam** [comment]
> I like the new green icons. Maybe being mostly a Mac user I am accustom to dull and boring monochrome icons. Maybe use the current icons and color the outlines and fills? I did this for fun in Thunderbird while taking care of some font and spacing issues.
> ![TB Folder Icons](https://user-images.githubusercontent.com/63317977/110033148-00682380-7d07-11eb-9363-14db2afaefa2.jpg)

I like the color combinations. 👍👌

**Comment by renato-mmex** [comment]
I don't have any problems with "more modern" symbols, but when they are all the same color, I have trouble finding my way around.
Maybe you have to use MMEX on different monitors with different resolutions, then you realize how unreadable the symbols are.
I use 1080 x 1920 (high) so I don't always have to scroll.
On my 3840 x 2160 it is more difficult to work even though I set it to 150%.

**Comment by vomikan** [comment]
I suggest simply increasing the size of the toolbar icons. It looks better this way.
![image](https://user-images.githubusercontent.com/6836805/110104219-ecc8c580-7db7-11eb-981a-cf09aaf3ecd3.png)

**Comment by vomikan** [comment]
Another option is to create separate settings for icons

![image](https://user-images.githubusercontent.com/6836805/110104608-6a8cd100-7db8-11eb-851f-ef79980f5daa.png)

**Comment by whalley** [comment]
Yes, good idea. I'll add option to set different sizes for each area.

**Comment by whalley** [comment]
I'm also look at an option where we create a zip with the icons so that people can create 'themes' to make it match their own tastes :-)

**Comment by vomikan** [comment]
As we discuss befor in #2923 best option is using https://github.com/memononen/nanosvg to convert svg to png on app start.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/110150336-346b4380-7df0-11eb-9170-9cd6fe96b5b6.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/110159806-3935f480-7dfc-11eb-954d-1b7e5dc75c64.png)

**Comment by renato-mmex** [comment]
Great, only the hint that MMEX must be restarted is missing
