### ISSUE TITLE
the border in the budget performance report issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2997]
MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

the border in the budget performance is in the middle of the numbers

![image](https://user-images.githubusercontent.com/6836805/109941679-73ac6e00-7ce4-11eb-9f86-f2ff8116bb03.png)
It would be very useful to know what has been changed in these beta versions, so you could test specifically these points.
See also: https://forum.moneymanagerex.org/viewtopic.php?f=3&t=10353

Many greetings
Renato

**Comment by whalley** [comment]
Looks like a CSS issue around the table in a div container. I hate playing about with CSS..... We should perhaps look at ditching the <table> html and replacing by <divs> anyway.

**Comment by vomikan** [comment]
https://stackoverflow.com/questions/28316061/table-not-getting-resized-inside-a-div-on-resizing-the-div/28320399#28320399

```
.shadow {
    box-shadow: 0 0 20px rgba(0,0,0,0.5); /* shadow parameters */
    padding: 5px;
    margin: 10px;
	margin-left:2px;
margin-right:10px;
margin-top:5px;
overflow:auto;
height:70%;
background-color:#ccffcc;
}

```

![image](https://user-images.githubusercontent.com/6836805/110199805-463dfc80-7e6b-11eb-96b4-8763214e08f4.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/3004/commits/a2b05fae82f28ad18ecdcd6eca23560bf4d978c7
