### ISSUE TITLE
MS Money support

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#300]
Since there are many audiences who want to switch from MS Money to Money Manager Ex, we will benefit a lot if we support the data migration.

**Comment by loki36** [comment]
I think this is link with #386

**Comment by guanlisheng** [comment]
Ok if ms just provide that format

**Comment by MisterY** [comment]
Some hints on how they are doing it in Moneydance: http://help.infinitekind.com/kb/importing-data-from-banks-and-other-programs/moving-from-ms-money-to-moneydance

**Comment by vomikan** [comment]
Seems like .QIF is the only way to go.
