### ISSUE TITLE
Synchro ANDROID to MMEX v7 on MAC OSX failed. SQL Logic error (1): duplicate column name: STATEMENTLOCKED 

### ISSUE THREAD

**Issue by PieOrg** [moneymanagerex/moneymanagerex#3005]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

Is the bug reproducible? 
 - [ x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. each time I try to open the database synchronized from Android via Dropbox.
2. 
3. 

…

Expected result:

Actual result:
The database cannot be migrated to MMEX v7
# Additional information

If you have a backtrace for a crash or a warning, paste it here.
SQL Logic error (1): duplicate column name: STATEMENTLOCKED

**Comment by whalley** [comment]
@PieOrg Is this still an issue with latest Desktop and Android versions?
