### ISSUE TITLE
Implement Object-relational mapping to SQLite tables

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#301]
we have a general database access layer now which supports
- Generate c++ code from table schema
- CRUD

But it does't support the connection with each table, such as
- has many
- has one
- many to many
- belongs to

**Comment by guanlisheng** [comment]
@gabriele-v would you help to enhance the ORM ?

**Comment by slodki** [comment]
[Object-relational mapping](https://en.wikipedia.org/wiki/Object-relational_mapping) Wikipedia article

**Comment by vomikan** [comment]
REASON: ORM hasn't been implemented in the past 9 years and MMEX development continues OK without it.
