### ISSUE TITLE
Transaction date changes to current date when editing an existing transaction

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3024]
MMEX version:
 - [x] 1.3.7 beta 6

Bug exists in updated development code:  1.3.7 beta 6 - built 08/Mar/2021

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux         Not tested

# Description of the bug

The transaction date field in the Edit Transaction dialog is updated to show the current date when it is opened to edit an existing transaction.  It should remain at the original transaction date.

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
1. View an account (e.g Checking account) with existing transactions
2. Note the date of an existing transaction.
3. Double click the transaction to edit it.
4. Observe that the date in the Edit dialog has changed to the current date.
5. If OK is clicked, the transaction now has the wrong (i.e. today's date)

Expected result:
The date in the edit field should show the original transaction date when the dialog is opened.

Actual result:
The date in the edit field is updated to the current date when the dialog is opened.

# Additional information
This bug does not happen in MMEX 1.3.6  (and _possibly_ not earlier than 1.3.7 beta 6)

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/2982
