### ISSUE TITLE
Crash report collection

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#303]
Since we already have 3k+ daily active users, it becomes important now to collect the crash report from end users. we may need to set up a server for this.
@gabriele-v , i think you can help here.

**Comment by gabriele-v** [comment]
@guanlisheng Any news on this? It could be useful to add in 1.2.0

**Comment by guanlisheng** [comment]
Hi, i think we don't have enough time and resource to make it happen in v1.2.0.
