### ISSUE TITLE
Network icon on the Options dialog is missing

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3030]
MMEX version:
 - [x] 1.3.7 beta 6 

Bug exists in development code: 1.3.7 beta 6 - built 08/Mar/2021

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux     Not tested

# Description of the bug

Network icon on the Options dialog is missing.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 
Reproduction steps:

Display the Options dialog.

Expected result:

The Network icon should be displayed.

Actual result:

A grey placeholder icon is displayed..

![image](https://user-images.githubusercontent.com/4060092/110366785-a9cc5380-803e-11eb-98be-906d83e13a1f.png)

# Additional information

**Comment by vomikan** [comment]
Please update. This issue already fixed.
![image](https://user-images.githubusercontent.com/6836805/110366963-1c95f880-8058-11eb-8200-bd002f4501fa.png)

**Comment by tactilis** [comment]
OK. Apologies. I was using a build from today - but clearly not the very latest.

Thanks for the link
