### ISSUE TITLE
cmake and VS2017

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3034]
Can't build mmex without this changes

![image](https://user-images.githubusercontent.com/6836805/110433982-4421ab00-80c2-11eb-8c4a-130a26ba26a5.png)

```
set(wxWidgets_ROOT_DIR "C:/wxWidgets")
set(wxWidgets_LIB_DIR "C:/wxWidgets/lib/vc_x64_lib"
    CACHE PATH "wxWidgets_LIB_DIR ")
```

**Comment by whalley** [comment]
@vomikan Not sure what the issue is here?

**Comment by vomikan** [comment]
It seems outdated issue.
