### ISSUE TITLE
Cloud storage sync research

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#304]
We may need to sync the database file to some popular cloud storages, such as Dropbox, Google Drive.

**Comment by pentix** [comment]
+1 for other cloud storages than Dropbox

As I see, Dropbox Sync is already implemented, how about Owncloud or an FTP-Server?
I'd like to host my financial data myself...

**Comment by guanlisheng** [comment]
Hi @pentix , Android version has implemented Dropbox sync while desktop is not yet.

**Comment by pentix** [comment]
Oh yes, thank you for your answer! I figured out a small workaround
so I'm independent of other cloud services:

1. Create a 2-way-sync using "FolderShare Lite" on Android
2. Creating a 1-way-sync for each direction using rsync on my Linux desktop

On-the-go entered accounting details are synced up to my SFTP-Server and I can
easily pull them down using rsync. After paying bills and stuff on my desktop I push
those details again to my server and FolderSync gets them automatically on my android device. :)

**Comment by MisterY** [comment]
Just additional reference so we can synchronize efforts:
https://github.com/moneymanagerex/android-money-manager-ex/issues/265

**Comment by MisterY** [comment]
I think a major improvement could be in releasing the file lock on the database, i.e. closing the db connection once it is not needed any more. Keeping the lock on the database file prevents the desktop storage client from synchronizing the file.
If that is solved, we could simply rely on desktop clients for these various providers to keep the file(s) in sync.
Android now supports Dropbox, Google Drive, OneDrive, and Box, btw.

**Comment by ElijahCaine** [comment]
It was already mentioned but +1 on integrating OwnCloud. Any open source app with syncing features ought to be able to sync with an open source cloud :wink:

**Comment by snhv** [comment]
Yes, sync via WebDAV please!

**Comment by wildcatgerry** [comment]
I'm trying to save to OneDrive (win7) and MMEX crashes on save, presumably because the write operation to OneDrive times out in MMEX. Save seems to be successful. Would this research be included in async save operations?

**Comment by dcaixinha** [comment]
+1 for sync via WebDAV!

**Comment by planetahuevo** [comment]
Hi, Not sure if this is the right place. 
I didn´t want to open a new issue and this one seems to be the best place. 
I have been reading about your software, and it seems that there is some problems with the sync with the database is locked in one of the devices. 
I would like to suggest the approach from KeePass, which is a password manager that can be synced by Dropbox. 
The idea is this one: 
https://keepass.info/help/kb/trigger_examples.html#dbsync

You setup a different database for each device and a trigger with a sync to a "master" database that is always unlocked, because no device use it.
What the KeePass does, when you save the file, it syncs the information with the "master", on both ways, getting the info from other devices and sending the info of changes on this device. 
Of course this could generate conflicts and things like that, but the conflicts will appear on every "multidevice" setup anyway.

What do you think? Thanks!

**Comment by erotavlas85** [comment]
Any new about webDav and nextCloud support?
Thank you

**Comment by slodki** [comment]
I don't think Cloud sync of files is financial app task. There are many system-level or user-space tools that can be used with MMEX files. See moneymanagerex/android-money-manager-ex#1250.

MMEX doesn't support concurrent editing the same database (using 2 apps on the same machine or over the internet). Use have to save current changes to db file then open it on 2nd machine.

Concurrent editing feature is not trivial and requires conflict resolution on database row level, triggering cache invalidation and data structures reloading etc.

Now conflicts should be managed on database file level using sync tools - they should ask user before overwriting modified database during sync.

@moneymanagerex/desktop-mmex-team We should close this issue IMHO.

**Comment by slodki** [comment]
@MisterY We don't lock db file in the desktop MMEX version IMHO:

> In NORMAL locking-mode (the default unless overridden at compile-time using SQLITE_DEFAULT_LOCKING_MODE), a database connection unlocks the database file at the conclusion of each read or write transaction. When the locking-mode is set to EXCLUSIVE, the database connection never releases file-locks. The first time the database is read in EXCLUSIVE mode, a shared lock is obtained and held. The first time the database is written, an exclusive lock is obtained and held.

(from https://www.sqlite.org/pragma.html#pragma_locking_mode)

**Comment by MisterY** [comment]
I agree with @slodki. File or database synchronization is out of scope of personal finance software. 
The existing desktop clients for various storage providers already take care of synchronizing files.
Row-level synchronization implies a full replication solution. There might already by something available, hence out of scope of this project.
A quick update on Android developments - I have removed CloudRail from the mobile app as it is no longer supported. Besides, by adding the support for Storage Access Framework, it is now possible to use **any** storage provider. The file access is done through the provider's app, so it will always be up-to-date and removes the burden of supporting various services from us. It also eliminates the need to provide these as modules, as every user will install they favourite provider's app (except Dropbox, it seems, as they are deaf to users' requests in this regard. I'm sorry about that. I also no longer use Dropbox as they don't really support Linux).

**Comment by whalley** [comment]
I agree with @slodki we should close. Closing.
