### ISSUE TITLE
Automatically fallback to readonly mode if the program has no write permission

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#305]
Times we run into a case that Money Manager EX has only the read permission then failed to open it. in this case, the program should fallback to readonly mode and we can still view the reporting and checking panel w/o any modification functionality.

**Comment by vomikan** [comment]
REASON: Hasn't been implemented in the past 9 years and we do have not received multiple requests for a readonly mode.
