### ISSUE TITLE
travis-ci.com

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3053]
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

**Comment by vomikan** [comment]
@guanlisheng seems you owner of the repository.
Could you check the following settings:
Options - Applications

![image](https://user-images.githubusercontent.com/6836805/120903396-938a5f80-c64e-11eb-97ce-e3673b7078eb.png)

![image](https://user-images.githubusercontent.com/6836805/120903424-b1f05b00-c64e-11eb-857a-4b306dd7fb28.png)

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=25&t=10413

**Comment by guanlisheng** [comment]
hey @vomikan, I had re-integrated with travis-ci.com and hopefully all set now.

**Comment by vomikan** [comment]
https://travis-ci.com/github/moneymanagerex/moneymanagerex.github.io

![image](https://user-images.githubusercontent.com/6836805/122715916-46bf9f00-d272-11eb-9f81-5ffb651040f3.png)

**Comment by oldnomad** [comment]
It seems Travis-CI integration is still broken. The last successful build is from Jun 25, and there were no builds since then, for any branches.

**Comment by vomikan** [comment]
> It seems Travis-CI integration is still broken. The last successful build is from Jun 25, and there were no builds since then, for any branches.

Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by vomikan** [comment]
I don't understand what does it mean "Consume paid credits for OSS setting".
It should be some minimun tasks available for OOS. Why it does not working?

**Comment by oldnomad** [comment]
According to [one developer who migrated his project](https://dev.to/yoursunny/travis-ci-pricing-change-usage-based-billing-5gba), OSS projects now get 10000 credits per month (around 1000 minutes of builds). I guess, rebuilding everything on every push won't work any more, unless you migrate it somewhere else.
