### ISSUE TITLE
History exchange rate support

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#306]
Both @vomikan and @gabriele-v think this is a cool feature to stick more audiences here.
anyway, would you guys help to compose some design before coding?

**Comment by guanlisheng** [comment]
Any update?

**Comment by gabriele-v** [comment]
Working on it in next weeks

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/647
