### ISSUE TITLE
New Theme: Colorful

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3063]
# Description of the feature

For a bit of fun, and for those who miss the colorful icons I have quickly assembled a set - it's primarily the toolbar, navigation, and settings - the others are the same as default.

Feel free to update and add the others, my artistic skills and color choices are somewhat lacking....

**Comment by whalley** [comment]
Related #3019

**Comment by vomikan** [comment]
Could you please update
![image](https://user-images.githubusercontent.com/6836805/110841480-f9b54f80-82b6-11eb-8787-09632cdcce93.png)

and add a linlk to the svg repository?

**Comment by vomikan** [comment]
In general it looks nice
![image](https://user-images.githubusercontent.com/6836805/110841597-25d0d080-82b7-11eb-8999-2c1dabb32f17.png)

**Comment by vomikan** [comment]
What do you think about an image as a background on the homepage
![](https://user-images.githubusercontent.com/6836805/83337878-a645b800-a2c7-11ea-99f8-b75a31b4229a.png)

https://github.com/moneymanagerex/moneymanagerex/issues/2386

**Comment by whalley** [comment]
> and add a linlk to the svg repository?

Have updated each theme readme.md to correctly mention the theme name

Not sure what you mean by 'add link to the SVG repository'?

**Comment by whalley** [comment]
> PS But there are too many small details.

Hey, I'm not proud of it, just put up there for people to enhance :-)

**Comment by whalley** [comment]
> What do you think about an image as a background on the homepage

For me, no. Though I appreciate that some people like these sort of things. 

Thoughts:
1. We could allow theme to include a default
2. Allow user to specify their own
3. What is essential is allowing it to be turned off.

**Comment by vomikan** [comment]
> Not sure what you mean by 'add link to the SVG repository'?

I mean somthing like this one:
Original icons here: https://www.svgrepo.com/
or more accurately:
https://www.svgrepo.com/collection/love-and-wedding/ (for example)

**Comment by vomikan** [comment]
I've added jpg file into themes.zip file and change master css 
```
background: url(memory:background.jpg);
  background-size: cover;
```
It does not working. Seems 'background.jpg' does not extracted to VFS.

**Comment by vomikan** [comment]
This may be interesting to set somthing like this as background

![Uploading image.png…]()

**Comment by whalley** [comment]
> Seems 'background.jpg' does not extracted to VFS.

Yes current logic uses .svg files to load the icon images and ignores anything else but master.css.   Will amend to load into VFS all none SVG files.

**Comment by reddyshyam** [comment]
Every day new surprises keep spring up! 😁 I love the colourful theme more than others now. As mentioned before, its easy to understand by color than picture. After switching to colour theme, I switched by toolbar size to 24 from 32. Looks fantastic! Thanks @whalley and @vomikan. 👍👌👏

Regarding background, it should be an _optional_ for users to decide. I am sure there are some great wallpapers just like the one above but if you ask me, transparent background would be fantastic or even plain colours to choose as background.

**Comment by reddyshyam** [comment]
![image](https://user-images.githubusercontent.com/12392746/110919687-8c4f0080-8342-11eb-867a-6df4f1398c4d.png)

Bank Account a credit card?

**Comment by whalley** [comment]
That is a bank debit card not a credit card :-)  

Have a look here - https://www.svgrepo.com/ Feel free to suggest new icons, or identify a set an create you own theme.

**Comment by reddyshyam** [comment]
> That is a bank debit card not a credit card :-)
> 
> Have a look here - https://www.svgrepo.com/ Feel free to suggest new icons, or identify a set an create you own theme.
😁@debitcard.

Finding faults or complaining is so easy but doing something is really hard. 😂

These are the few I thought can replace that not sure too. So will leave in the best hands to choose or ignore. 😉 

https://www.svgrepo.com/download/18524/money-bag.svg
https://www.svgrepo.com/download/205785/money-business-and-finance.svg
https://www.svgrepo.com/download/44222/money.svg
https://www.svgrepo.com/download/56516/money.svg
https://www.svgrepo.com/download/130872/money.svg
https://www.svgrepo.com/download/188816/money-cash.svg
https://www.svgrepo.com/download/244697/coins-money.svg
https://www.svgrepo.com/download/289573/money.svg
https://www.svgrepo.com/download/301519/money.svg

**Comment by whalley** [comment]
I like this one: https://www.svgrepo.com/download/130872/money.svg and think it could work.

If you look for the themes.zip file in the application  bin directory on your PC you can replace the "colorful/navigation/SAVINGS_NORMAL.svg" file to try it out

The full set of icons in the theme are here... https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/themes/colorful/readme.md

Why not have a play with a few other SVGs, just changes the themes.zip and restart the program.  For safety just take a copy of the original zip.

You could also copy the 'colorful' directory in the zip to say 'colorful2' and then edit that.

**Comment by vomikan** [comment]
@whalley thank you!

![image](https://user-images.githubusercontent.com/6836805/110940484-0930a900-8348-11eb-9d73-10503e00a219.png)

[simple-black.zip](https://github.com/moneymanagerex/moneymanagerex/files/6130003/simple-black.zip)

**Comment by reddyshyam** [comment]
> I like this one: https://www.svgrepo.com/download/130872/money.svg and think it could work.
> 
> If you look for the themes.zip file in the application bin directory on your PC you can replace the "colorful/navigation/SAVINGS_NORMAL.svg" file to try it out
> 
> The full set of icons in the theme are here... https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/themes/colorful/readme.md
> 
> Why not have a play with a few other SVGs, just changes the themes.zip and restart the program. For safety just take a copy of the original zip.
> 
> You could also copy the 'colorful' directory in the zip to say 'colorful2' and then edit that.

@whalley, thanks for the heads up. I tried copying colorful to colorful2, replaced the above particular svg and restarted app to get the following error. Ignoring the error, app loads but the new svg is not reflecting if I select the new theme.

![image](https://user-images.githubusercontent.com/12392746/110941821-e9f14600-835e-11eb-8b32-5dc890afb1d5.png)


Also I noticed that if we add new themes with not the default set as current, app throws error. I had to set theme to default before updating the themes.zip file, set the new theme and then restart.

**Comment by vomikan** [comment]
@reddyshyam I can't reproduce this isse
Check that res folder does not contains master.scc and readme.md files
![image](https://user-images.githubusercontent.com/6836805/110942249-9d9c0b00-834a-11eb-8f03-effed67d402b.png)

**Comment by whalley** [comment]
@reddyshyam Yes, cant reproduce problem on Mac either... Make sure the zip contains directories like this.

<img width="618" alt="Screenshot 2021-03-12 at 12 52 30" src="https://user-images.githubusercontent.com/487345/110942704-1773ca80-8332-11eb-8265-44774314d4c1.png">

**Comment by reddyshyam** [comment]
Hi @vomikan and @whalley 

Mine looks like you guys mentioned but still the error happening.

![image](https://user-images.githubusercontent.com/12392746/110943223-f9718e80-8360-11eb-9baa-78ae6dc07134.png)
![image](https://user-images.githubusercontent.com/12392746/110943277-0a220480-8361-11eb-95b8-4a43150aac3b.png)

**Comment by whalley** [comment]
@reddyshyam  That looks fine. just check that the master.css and readme.md is not duplicated in any of the theme directories. If you have not touched any other than colourful2 then just check in that.

**Comment by whalley** [comment]
@vomikan I'm liking your work on colorful2 https://github.com/moneymanagerex/Art/tree/master/themes/colorful2 :-)

**Comment by whalley** [comment]
What are the views on including `home_page.htt` in the theme?

**Comment by reddyshyam** [comment]
> @reddyshyam That looks fine. just check that the master.css and readme.md is not duplicated in any of the theme directories. If you have not touched any other than colourful2 then just check in that.

@whalley, when I copied colorful to colorful2, it copies master.cc and readme.md in there too. Should I delete both from colorful2? I changed #theme = colorful2 on readme.md in colorful2 folder to see if error goes away but didnt.

**Comment by vomikan** [comment]
I'm getting pretty sick of it. Maybe I won't finish. Anyone interested, please participate.
![image](https://user-images.githubusercontent.com/6836805/110973602-7d7e4300-836e-11eb-8aef-844a86283b0b.png)

But it turns out pretty.

**Comment by reddyshyam** [comment]
> @vomikan I'm liking your work on colorful2 https://github.com/moneymanagerex/Art/tree/master/themes/colorful2 :-)

Is it worked further? I thought it is already done.

**Comment by reddyshyam** [comment]
> I'm getting pretty sick of it. Maybe I won't finish. Anyone interested, please participate.
> ![image](https://user-images.githubusercontent.com/6836805/110973602-7d7e4300-836e-11eb-8aef-844a86283b0b.png)
> 
> But it turns out pretty.

@vomikan, its not worth your time or energy. Ground work has been done, please leave it at this. I am sure someone will chip in.

**Comment by vomikan** [comment]
>What are the views on including home_page.htt in the theme?

There are doubts about this. But it can also be useful.
IMHO better to add JSON file with global variables for colors.

**Comment by whalley** [comment]
On the subject of colors, I'm beginning to like the simplicity of the simple-black theme, but **HATE** the background color. :-)

We may need to add have a color override option in the UI settings.... I'm thinking we might need a separate UI panel for the options soon....

**Comment by vomikan** [comment]
I hate that I can't define the color of the main app (not html)

![image](https://user-images.githubusercontent.com/6836805/110976794-6c373580-8372-11eb-8644-964a676a7159.png)

**Comment by vomikan** [comment]
> but HATE the background color. :-)

Redefine to taste.

**Comment by whalley** [comment]
> PS and dark theme not supported on wxWidgets + Windows

Actually its not very compatible with dark mode on Mac

![Screenshot 2021-03-12 at 20 20 34](https://user-images.githubusercontent.com/487345/110994335-8ec84f00-8370-11eb-976e-628239e3f871.png)

Needs a bit more work on the themes, but we can leave that to next release. E.g. the background fill to white on the Mac Navigation icons probably wants to customizable in the theme. Need to meta data to be passed in theme. Will create an enhancement issue.

**Comment by whalley** [comment]
Closing as I suggest we pick up other enhancements as separate issue. Perhaps we leave an open issue to track theme creation/tweaking discussion/commits
