### ISSUE TITLE
Support extra meta data against theme files and user customisation

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3067]
# Description of the feature

Should allow meta-data to be supplied to theme files that can be used to further customize appearance, also consider making some theming options available to user.

To be considered.

1. background image fill for navigation icons
2. colors to be used
3. background image to be used

Possible user options could be defined in meta data in theme and UI dynamically created to allow them to be overridden.

E.g. If theme had (just an example syntax/options)

```
<config>
<color name="naviconfill" text="Navigation Fill Color" user=false>#FFFFFF</color>
<color name="background"text="Background Color" user=true>#FFFFFF</color>
</config>
```

The user will have option to changed the Background Color.

Other options would be possible

**Comment by whalley** [comment]
Related: https://github.com/moneymanagerex/moneymanagerex/issues/3063

**Comment by vomikan** [comment]
I have the following suggestion:
The default theme should be hidden from users.
The user can provide a zip file, not necessarily a complete one, but only with changes.

The name of the theme may be placed in meta data.

The algorithm is as follows: we scan all zip files from the res folder. If the file contains a file with metadata and the name is the correct file.
We read from this file everything that is there. What is not there, we add from the default data.

What will this achieve?
The user will be able to make their own data set and share it with other users. The user is not obliged to strictly observe the structure and completeness of the data in the archive.

**Comment by whalley** [comment]
I follow the idea and think it sounds sensible and easy to adopt. What I'm not sure about is having the user change the resource folder. How about we search for a file in the same directory as the database file for a <dbname>.theme.zip file. Yes if people have multiple dbs they would need to create/copy the custom theme but minor annoyance.

**Comment by whalley** [comment]
Or maybe we just add the option for the user to specify an override file and add the option to the settings.

**Comment by vomikan** [comment]
What about an option like "import theme"?

**Comment by vomikan** [comment]
> ... people have multiple dbs they would need to create/copy the custom theme but minor annoyance.

Related issue
https://github.com/moneymanagerex/moneymanagerex/issues/2387

**Comment by whalley** [comment]
Have added the ability to specify a **userthemes.zip** file in the user directory where the mmexini.db3 file is held.

This user file will allow the user to override any of the built-in system themes or specify a new theme.
Where an existing theme is identified then the user files for that theme will be overwritten.
Where a new theme is identified then the 'default' theme will be used and then the files for that theme will be overwritten.

If a user specified them is selected as the theme to be used and it is subsequently removed then a warning will be issued and the default reverted to.

**userthemes.zip** should consist of a directory for each theme that needs overriding or adding. Within each directory you specify the files you want to change/define, e.g. master.css, CASH_NORMAL.svg -- within the theme directory any structure can be adopted.

**Comment by 2BeeOrNot** [comment]
userthemes.zip or usertheme.zip? Above it's userthemes.zip but this doesn't work. Looking at the changes in your pull request it's usertheme.zip. That works.

This is great. No more lost changes to master.css or custom icons when installing a new version.

While trying this out I noticed that the status icon for duplicate does not have the white circle around it like the other status icons. By design or overlooked?

**Comment by vomikan** [comment]
I like it.

[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6139614/usertheme.zip)

![image](https://user-images.githubusercontent.com/6836805/111120922-0965ba00-857d-11eb-8881-48c38980a1a0.png)

**Comment by whalley** [comment]
Yes, usertheme.zip. Probably needs a user guide entry for this feature.

**Comment by whalley** [comment]
> While trying this out I noticed that the status icon for duplicate does not have the white circle around it like the other status icons. By design or overlooked?

It was by design, honestly. As it was already filled with white rather than the full circle. Perhaps it would be more consistent to have a white border...

**Comment by vomikan** [comment]
> Yes, usertheme.zip. Probably needs a user guide entry for this feature.

IMHO the best place to start is wiki
https://github.com/moneymanagerex/moneymanagerex/wiki

**Comment by vomikan** [comment]
> Perhaps it would be more consistent to have a white border...

I gonna add it.

**Comment by vomikan** [comment]
I've added a background image to this theme
[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6140067/usertheme.zip)

**Comment by whalley** [comment]
@vomikan I had to use 

`background: url(memory:background.jpg) no-repeat center top fixed;`

to get it working on Mac. I would have expected IE on Windows to require the same, perhaps it defaults to VFS? Probably worth considering for compatibility.

**Comment by vomikan** [comment]
I've updated the archive. May be that is a reason of the issue.
The working code (for windows) is:
```
html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
  font-size: 62.5%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  #background-image: url(background.jpg);
  background: url(background.jpg) no-repeat center top fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```

**Comment by whalley** [comment]
Nope, I got that. Only way to get it to work on Mac was below. I would have expected **'memory:....'** to be needed to access the VFS held background.jpg file.
```

html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
  font-size: 62.5%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  #background-image: url(background.jpg);
  background: url(memory:background.jpg) no-repeat center top fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```

**Comment by vomikan** [comment]
This file should be OK 
[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6143896/usertheme.zip)

**Comment by whalley** [comment]
Use of wxHtmlWindow to display the theme manager more scope to quickly add the display of new meta data or information for the theme. Have also added URL link to the theme webpage.

**Comment by whalley** [comment]
Metadata supporte now added. See https://github.com/moneymanagerex/themes for detail on currently supported metadata. Should be easy to add new metadata now.
System themes updated to use new structure. Existing user themes may fail as the theme description data is now part of a "theme" : { .... } element - please adjust any existing user themes.

**Comment by whalley** [comment]
Palette and other colors for reports can now be defined via metadata.

https://github.com/moneymanagerex/themes

https://github.com/moneymanagerex/moneymanagerex/pull/3216
