### ISSUE TITLE
Display change log for new version

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#307]
This will help user knows what expect from update

**Comment by gabriele-v** [comment]
Display ChangeLog is done. I prefer to add a wizard to achive two other features:
1) Manage Database Patch (if it will be needed)
2) Immediatly download new version in download folder

Regarding point 2) I need some help: second wizard panel and logic are already done, but I was not able to:
- Start download & update progress bar (wxGauge) on "Next" click (EVT_WIZARD_PAGE_CHANGED should be used but don't know how)
- Download file from HTTPS, seems that it's not possible with wxWidgets, maybe we should use CURL (http://wxcode.sourceforge.net/components/wxcurl/) ?

**Comment by guanlisheng** [comment]
It would be great if we can integrate [wxcurl](http://wxcode.sourceforge.net/components/wxcurl/). we could do more and more things if we have HTTPS.

Regarding the database patch, do you have a clear approach now? I wish the team would pay more attention one the UE improvements and feature simplification to grow the audiences. as you know that about one-quarter users will not open the program after first run.

**Comment by gabriele-v** [comment]
It could be useful if we will need to patch DB or make some changes. 
Currently we don't need it, but it's one reason why I've choose wizard instead of a simple dialog like about dialog.

**Comment by guanlisheng** [comment]
I knew/know it's very useful and the point is 1) how we implement it, 2) when we can use it and 3) how often we will use it. we should consider the ROI.
