### ISSUE TITLE
Json parse error

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#3078]
MMEX version:
 - [ ] 1.3.7
 - [ x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:

 - [ ] Windows
 - [ ] Mac OSX
 - [x ] Linux 

# Description of the bug

Quotes are not updated when I click the update button (red button at the bottom of the image). I get the error message shown in the image. It's just updated. if I update them one by one. 

![kép](https://user-images.githubusercontent.com/80578702/111125067-7e32f700-8571-11eb-83e7-abe1e4e4782e.png)

Version: 1.3.6 64-bit
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.3 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.3
• libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Build on Feb 26 2021 20:11:04 with:
• CMake 3.16.3
• GNU Make 4.2.1
• gettext 0.19.8.1
• GCC 9.3.0 • Ubuntu 20.04 'focal'
Running on:
• Ubuntu 20.04.2 LTS "focal"
• Linux 5.8.0-44-generic x86_64
• Hungarian (UTF-8)
• 1920x1080 24bit 93x93ppi 
# Reproduction

Is the bug reproducible? 
 - [ x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Could you test the new build?
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/38223923/job/fu97g6084ff19snq/artifacts
I recommend to use  portable vertion.

**Comment by Heny67** [comment]
I tested it under wine and also under windows 10. The result is the same. Stock prices are not updated. And as you can see in the picture only the id and date column can be seen the shares are not. 
![kép](https://user-images.githubusercontent.com/80578702/111169940-b7845a80-85a3-11eb-8ba9-bb3484c53e1e.png)

**Comment by vomikan** [comment]
could you find and delete mmexini.db3 file then try again?

**Comment by Heny67** [comment]
In the meantime, I started under wine again but with an older database backup (July 2020). This will update the exchange rate. 

![kép](https://user-images.githubusercontent.com/80578702/111171142-f070ff00-85a4-11eb-92c0-a49607054ad5.png)

**Comment by vomikan** [comment]
Try to reset the columns settings to the default values.

![image](https://user-images.githubusercontent.com/6836805/111172516-f243be00-85b6-11eb-92b9-6f7da265a5f4.png)

**Comment by Heny67** [comment]
I searched the whole linux file system all the way through but couldn't find any such file (mmexini.db3)

**Comment by vomikan** [comment]
it should be in ~/.mmex folder

**Comment by Heny67** [comment]
I ran the commands in a terminal. At startup, you wrote: 
(mmex:4232): Gtk-CRITICAL **: 16:46:20.058: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
The program started, but the original error remained.

**Comment by vomikan** [comment]
may be 
> mmex -i "~/mmexini.db3"

**Comment by Heny67** [comment]
The column reset is fine thanks, but nothing has changed for this command either.

**Comment by Heny67** [comment]
Hello everyone.
I may have figured out the cause of the error. The share account also contains Hungarian government securities. If I delete the government securities then the stock price will be updated, no error message will appear. Obviously, Hungarian government securities are not listed on the stock exchange, this may be the reason for the error message. Could it be resolved not to update them? Or let’s choose what to update and what not.

**Comment by vomikan** [comment]
My accounts contain securities from the Moscow Stock Exchange that are not listed on Yahoo. This does not lead to errors. Can you make a database (mmb) for me with the records that cause the error?

**Comment by Heny67** [comment]
I hope it will be good.
[test1.mmb.tar.gz](https://github.com/moneymanagerex/moneymanagerex/files/6250160/test1.mmb.tar.gz)

**Comment by vomikan** [comment]
I've got this error:

![image](https://user-images.githubusercontent.com/6836805/113434212-358c9200-93e9-11eb-912c-c8e6472364c0.png)

**Comment by Heny67** [comment]
I have not received such an error message so far.
I deleted the part before n2025 in the original database and now it looks like it is updating the data. I also tested with the mmex-1.5.0-RC.2-win64 portable version and the mmex_1.5.1-Alpha.1-1.focal_amd64.deb version. In both cases, the data is updated.
Thanks for the help. We hope this error does not occur further.
