### ISSUE TITLE
Empty icon

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3079]
Seems we need two empty icons. One for transactions and anothe one for color settings

![image](https://user-images.githubusercontent.com/6836805/111148296-82283e80-859c-11eb-811f-7c4b80f26025.png)

![image](https://user-images.githubusercontent.com/6836805/111149452-f1526280-859d-11eb-8f09-882a3bb4a223.png)

**Comment by vomikan** [comment]
For complete uniformity, it is better to use a white circle for transactions with an undefined status.
But the icon is not used at all in this case.

However, it is used for the color selection menu.

```
<svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle style="fill:#ffffff;fill-opacity:1;" cx="12" cy="12" r="10"/>
</svg>
```

@whalley  could you please fix it?

**Comment by whalley** [comment]
@vomikan -- Sure will sort it later.

**Comment by whalley** [comment]
Added an UNRECONCILED icon for the transaction. EMPTY left as-is.
