### ISSUE TITLE
Multi-selection for checking panel

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#308]
for mark, deletion purpose

**Comment by Chaos99** [comment]
I would second that and add 'editing details' to the list of goals for multi-selected transactions.

Changing the payee, category or status of several transactions at once is a common task.
Also changing the type of several transactions from withdrawal to transfer would be immensely useful.

**Comment by gabriele-v** [comment]
Agree and I'll add it to 1.3

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/1266df2b666dd7235f990d4d963ea9b5f6416e34

https://github.com/moneymanagerex/moneymanagerex/issues/622
