### ISSUE TITLE
1.5.0-RC.1

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#3087]
Operating System: Windows10

I just updated to the new 1.5.0-RC.1 and I love the UI update.
The only things I noticed was on the upgrade I had a recurring transaction of "every 2 weeks" and after the upgrade the dates shortened by a day for some reason.
Also, this RC appears under stable updates on app open. I'm thinking that maybe the RC should not appear to casual users.

**Comment by vomikan** [comment]
It seem like a bug

![image](https://user-images.githubusercontent.com/6836805/111218516-e15f7080-85e7-11eb-9ec2-89aedb26835d.png)

![image](https://user-images.githubusercontent.com/6836805/111218533-e91f1500-85e7-11eb-9bab-dfa5fd3572f2.png)

![image](https://user-images.githubusercontent.com/6836805/111218563-f3411380-85e7-11eb-9459-72eeca24f954.png)

**Comment by reddyshyam** [comment]
Are we jumping from 1.3.7 to 1.5.0?

**Comment by vomikan** [comment]
> Are we jumping from 1.3.7 to 1.5.0?

Yep
