### ISSUE TITLE
Future transactions viewable on more views

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#3088]
Hello,

Currently you are only able to view future transactions on "current" or "all" views. However, it would be great to view future transactions along with 30 days, 90 days, 3 months, etc. 

I regularly enter future transactions and *also* filter down to the last 3 months. It would be great to see the last 3 months as well as future transactions at the same time.

Thank you

**Comment by vomikan** [comment]
May be this way?
![image](https://user-images.githubusercontent.com/6836805/111220855-c6dac680-85ea-11eb-88bd-51f3e20a8a61.png)

**Comment by user8446** [comment]
Yes, you can achieve a filtered view with future transactions using the advanced filter but you would have to remember to re-adjust it every month.
Maybe a radio button such as "include future transactions"? Or since there is already `View > Ignore future transactions` when it is off then future transactions are always included, and when checked they are not.

**Comment by whalley** [comment]
I think it is worth considering what the options are here. 

The actual period selections such as "Last 30 days", "Last 90 days, "Last FY" are all very much time-bounded (as their names suggest) to that period, so future transactions are not applicable. When filters such as  "All Transactions" or "Since Statement Date" filters are selected this is where future transactions can be considered.

I'm of the opinion that the the interpretation of the future transaction option is strictly correct as it stands.

**Comment by user8446** [comment]
That does make sense. So the `View > Ignore future transactions` should probably be global no matter what view you are in.

**Comment by vomikan** [comment]
@user8446 I am not sure 100% but current month, for example, contains all date from 1st to the end of the month.
In the middle of the mont you will see future transactions included in the month.

**Comment by whalley** [comment]
> So the `View > Ignore future transactions` should probably be global no matter what view you are in.

No, what I'm actually saying is the where a time-bounded view is requested (e.g. last 30 days) then the future transactions will NEVER be displayed as you have requested transactions for the last 30 days which by its very nature excludes future transactions.

Where a view such as "Since Statement Date" is specified then this is forward looking and not time bounded (at least towards the future) so the setting for "Ignore future transactions" is applicable. The same would be the case if "All Transactions" were selected as the view.

So my belief is that the existing behaviour is correct.

**Comment by whalley** [comment]
> 
> 
> @user8446 I am not sure 100% but current month, for example, contains all date from 1st to the end of the month.
> In the middle of the month you will see future transactions included in the month.

Agreed, that should be the case.

**Comment by user8446** [comment]
Ok then there should be a way to simply see future transactions without constant switching views. Maybe an Include future transactions selection?

**Comment by whalley** [comment]
We do display future transactions when they are relevant to the time bounds of the view. Why would seeing future transactions be relevant to a view of transactions for the last financial year? Or Last 90 days? Or Last Year? For the current year, yes it would, if the future transaction is still in this year and not 2022.   

If we start displaying future transactions if not relevant for the view it makes no sense.

**Comment by user8446** [comment]
Hi,

Because I always use a filtered view (last 90 days) but also need future transactions as well. Future transactions are pretty common now especially with everything moving to auto-pay as they are scheduled out.
I checked my QuickBooks program as well as my old online checkbook (ClearCheckbook) and both include future transactions without constantly switching views.

**Comment by whalley** [comment]
One option we could consider for this request is to add an option to the 'Advanced' filter and allow the date to be specified as: Starting: 1 month ago, 3 month ago, 12 month ago, current year, current FY then you could setup and would not need to change. This, with no end date, would display future transactions.

**Comment by user8446** [comment]
Agreed, and that would accomplish the same thing

**Comment by vomikan** [comment]
Related issue:
https://github.com/moneymanagerex/moneymanagerex/issues/2378

**Comment by whalley** [comment]
@vomikan - I have this change available, are you creating a v1.5.1 branch to host these so we can concentrate v1.5.0 fixes on the main branch for now?

**Comment by vomikan** [comment]
I am not sure if I can create a new branch in the upstream. I will try tomorrow.

**Comment by whalley** [comment]
No real problem I can hold onto this until we get v1.5.0 out the door.

**Comment by whalley** [comment]
@vomikan - I'm not sure I agree with the changes you have made. As noted above... The current filters were correct and for time-bounded filters the future transactions were not listed. Now if I filter on, say, "Today" I see future transactions.

    We do display future transactions when they are relevant to the time bounds of the view. Why would seeing future transactions be relevant to a view of transactions for the last financial year? Or Last 90 days? Or Last Year? For the current year, yes it would, if the future transaction is still in this year and not 2022.
    
    If we start displaying future transactions if not relevant for the view it makes no sense.
    
    If you need to see future transactions you need to select a view that has them within the time bounds of that view.

**Comment by vomikan** [comment]
It is necessary to take into account the presence or absence of this attribute.
![image](https://user-images.githubusercontent.com/6836805/112722882-e7751b80-8f1c-11eb-9502-844aa1afe7e9.png)

**Comment by whalley** [comment]
Agreed but this only applies when the future lies within the time bounds of the view. E.g. If "This Month" then the future transactions this month will be displayed, if "Today" or "Last 90 days" etc the view is time bounded, as it would be for last financial year. "Current Year" will include all future transactions this year. I'm of the belief that the current filters worked fine. 

We are now inconsistent as "View Current Year" and others do not include 'future transactions'... 

Perhaps we undo this and discuss best approach for this for 1.5.1. Unless it will be a lot of work to undo in which case lease as-is for now and we can still discuss later. It's not a major issue either way

**Comment by user8446** [comment]
From my opinion from an owner of multiple businesses also using other accounting programs, this should be as simple as the "ignore future transactions" either shows future transactions or not, regardless of the picked filtered view. 

Maybe just the wording should be changed to "don't display future transactions" for clarity.

It is definitely a must-have feature though for businesses as well as personal finances.

**Comment by whalley** [comment]
@user8446 Glenn - I appreciate this is important to yourself but we need to consider the wider user base and the fact that changes to existing behavior may cause unforeseen issues for other users that are already familiar with the existing logic. As I have previously noted I have a change that adds a 'From Date' filter option that does not bound the future transactions so should meet your needs, we can look to include this in 1.5.1.

**Comment by user8446** [comment]
Thank you @whalley for the reply. I agree, the two options "last year" and "last financial year" wouldn't have a need for including future transactions or make sense.

**Comment by whalley** [comment]
Extra advanced filter options added - https://github.com/moneymanagerex/moneymanagerex/pull/3163
