### ISSUE TITLE
1.5.0-RC.1  on Mac

### ISSUE THREAD

**Issue by franfos** [moneymanagerex/moneymanagerex#3090]
MMEX version:
 - [X] 1.5.0-RC.1
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX 11.2.2 (20D80)
 - [ ] Linux 

# Description of the bug

I've just downloaded the latest image version for Mac (mmex-1.5.0-RC.1-macos.dmg) and placed it in Applications. After running it, it appears a message warning that the application is corrupted and should be moved to the trash bin.
I also tried compiling the source code, and the resulting program executes, but either opening an old database or creating a new one, the program seems to stuck. It appears the menu, but the main window is blank. Also, no option in the menu unfolds.
I have v1.4.0-Alpha.3 running properly. Do I have to make some kind of upgrade? Do I have to make a clean install (if so, how?)

Thanks!

**Comment by whalley** [comment]
Not sure what the corrupt issue is. I've just re-download the DMG from sourceforge and dragged the app to /Applications on both an M1 Mac (11.2.3) and an Intel Mac (10.15.7) and both work fine. Not sure where the corruption lies, I presume you have tried re-downloading. Does the DMG open and allow you to drag the app to /Applications. In your description it implies you put the DMG in /Applications which is wrong - you just download the DMG, open it, and then drag the app to /Applications.

In addition, v1.4.0 uses a different database schema and development of that was abandoned, see: https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by franfos** [comment]
I have downloaded and tried from sourceforge, and it works. I think I tried the version on Github (mmex-1.5.0-RC.1-macos). The size is quite different. 
And, what about the compiled version? It compiled without errors, but it doesn't works. I made some changes in the source code (not sure if they are valid for anyone) and I would like to keep them.
Anyone could compile it in Mac and made it work?

Thanks.

**Comment by whalley** [comment]
Did you fork the repo? If so, you can raise a merge request if you have changes to share.

**Comment by vomikan** [comment]
https://travis-ci.org/github/moneymanagerex/moneymanagerex/builds/763086056

this service build binaries for all unix like systems. Unfortunatly the buils for MAC does not working.
But the binary file provided by @whalley is OK

**Comment by 2BeeOrNot** [comment]
Why is 1.5.0-RC.1-macos.dmg posted on GitHub? It's not signed so it will tell you the file is damaged. It will run if you remove the quarantine flag. But the first thing you notice is the navigation panel background is two colors. The unused space is grey while the used it white. It uses wxWidgets v3.1.4 whereas the Sourceforge and version at Mark's web page use v3.1.5. Downloading the GitHub version leads to a bad user experience.

**Comment by vomikan** [comment]
@2BeeOrNot help us to fix it, please.

**Comment by 2BeeOrNot** [comment]
I wish I could. The GitHub build is not being signed. It is using a older version of wxWidgets that may be the cause of the navigation panel issue. Not something I have the knowledge to fix.

**Comment by whalley** [comment]
Yes the older wwWidgets causes much of the presentation issue, v3.1.5 is due out shortly and we can look to adopt that for all platforms, in the meantime I could look to change the travis build to use the version I have tested. As for signing/notarizing the file that will require a bit more work and I'd need to look at how to securely storing by developer credentials. Perhaps for now we change the MacOS build to delete the output at the end rather than leaving a broken/unsigned image.

**Comment by vomikan** [comment]
May be it's time to update te folloving code?
https://github.com/moneymanagerex/moneymanagerex/blob/master/.travis.yml#L123-L125

**Comment by whalley** [comment]
Hmm, I did try to build using the last master commit that I had tested but unfortunately the Git commit archive does not include a sub modules so it would need a bit more messing. For now suggest we leave as-is until the 3.1.5 release is available. Don;t really want to just pickup the latest commit as this may break things from time-to-time.

**Comment by franfos** [comment]
@whalley , in the meanwhile, what do you suggest me to do to achieve a successful compilation on mac?

**Comment by whalley** [comment]
@franfos Need to get around to documenting this. Apart from the code signing/notarization for which you need an Apple developer account the basic approach is to download the latest wxWidgets from Github, build that, then build MMEX using that. 

As you seem to already have the Homebrew/Xcode setup then you just need to...

Download and build wxWidgets

```
git clone --recursive https://github.com/wxWidgets/wxWidgets.git
cd wxWidgets
mkdir build-cocoa
cd build-cocoa
export MACOSX_DEPLOYMENT_TARGET=10.14
../configure --enable-debug ---disable-shared  --enable-cxx11 --with-cxx=11 --with-macosx-version-min=10.14 --without-libtiff --enable-universal-binary=arm64,x86_64   
make
```

Build MMEX using your wxWidgets build

```
mkdir build
cd build
cmake -DCMAKE_CXX_FLAGS="-w" -DwxWidgets_CONFIG_EXECUTABLE=<PATH>/wxWidgets/build-cocoa/wx-config -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" --with-macosx-version-min=10.14 ..
cmake --build . --target package
```

where <PATH> points to where your wxWidgets repo is.

This should build a universal image for Apple Silicon and Intel.

**Comment by franfos** [comment]
> @franfos Need to get around to documenting this. Apart from the code signing/notarization for which you need an Apple developer account the basic approach is to download the latest wxWidgets from Github, build that, then build MMEX using that.
> 
> As you seem to already have the Homebrew/Xcode setup then you just need to...
> 
> Download and build wxWidgets
> 
> ```
> git clone --recursive https://github.com/wxWidgets/wxWidgets.git
> cd wxWidgets
> mkdir build-cocoa
> cd build-cocoa
> export MACOSX_DEPLOYMENT_TARGET=10.14
> ../configure --enable-debug ---disable-shared  --enable-cxx11 --with-cxx=11 --with-macosx-version-min=10.14 --without-libtiff --enable-universal-binary=arm64,x86_64   
> make
> ```
> 
> Build MMEX using your wxWidgets build
> 
> ```
> mkdir build
> cd build
> cmake -DCMAKE_CXX_FLAGS="-w" -DwxWidgets_CONFIG_EXECUTABLE=<PATH>/wxWidgets/build-cocoa/wx-config -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" --with-macosx-version-min=10.14 ..
> cmake --build . --target package
> ```
> 
> where `<PATH>` points to where your wxWidgets repo is.
> 
> This should build a universal image for Apple Silicon and Intel.

**Comment by franfos** [comment]
It worked. I could compile it and made it work. Sorry for the late reply.
Regarding the changes I made on my version, I'm not sure if there is another workaround to solve the problem I'm facing without modifying MMEX.
I tell you the situation:
Imaging I have 1000€ in a checking account. I want to buy a car, and get a loan from a bank (10000€ and 100€ per month return).
So, I make a deposit of 10000€ from the bank, and a withdrawal of 10000€ to the car seller.
I create a loan account, with an initial balance of -10000€. But, every month, when I make a transfer (100€) from my checking account to the loan account, that transfer is not treated as a withdrawal.  
So, I changed the reports and the withdrawals / deposits balance in the main screen to treat the transfers to loan accounts as withdrawals.
Is there other way to get this situation?
Other changes I made are auto fill for bank account names and payees, but I see that in the last version there is something similar to what I've done.

**Comment by vomikan** [comment]
@franfos  On the good, the property must be used. A car is an asset that changes in value. Likewise, there are a number of problems with buying stocks. I made an attempt to improve the functionality of the program in version 2.0.

**Comment by franfos** [comment]
Ok, I will not go off topic. I will open an enhancement request for this situation.

Thanks.

**Comment by whalley** [comment]
We are now building against 3.1.5, this can be closed.

**Comment by franfos** [comment]
> We are now building against 3.1.5, this can be closed.

I've tried to compile it again, and I'm having the same issues mentioned at the top of the post. It compiles, but when I open MMEX it gets stuck. I've followed the instructions in BUILD.md. Do I have to make something extra to use wxWidgets 3.1.5?

**Comment by whalley** [comment]
git clone --recursive **--branch v3.1.5** https://github.com/wxWidgets/wxWidgets.git

This should get you the v3.1.5 branch.
