### ISSUE TITLE
Mark All Being Viewed - Too Easy To Change All Transactions

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3093]
It's too easy to select "Mark all being viewed" instead of "Mark all being selected" and change the status of every transaction in the account. I know - I did it testing 1.5.0 on a copy of my DB instead of a sample DB containing a few transactions that I have been using with the 1.37 versions. I suggest having a confirmation popup asking is you really want to do this when selecting "Mark all being viewed".

Also the text for followup in the drop down menu is inconsistent. For "Selected" it is "as followup". For "Viewed" it is "as needing Followup". Should both be the same or is this by design?

**Comment by vomikan** [comment]
I suggest the folloving workaround:
In case if some transactions selected hide the "mark all beeing viewed' menu item.
And vice versa, 
![image](https://user-images.githubusercontent.com/6836805/111342620-ae6eb880-868b-11eb-8b65-7b13d0576d07.png)

**Comment by vomikan** [comment]
Two types of menus. 1) some transaction is selected 2)nothing is selected.

![image](https://user-images.githubusercontent.com/6836805/111347044-e11ab000-868f-11eb-88b3-d55a4fef2429.png)

![image](https://user-images.githubusercontent.com/6836805/111347120-f263bc80-868f-11eb-8242-11a09b0ed954.png)

**Comment by whalley** [comment]
Do we need 'All viewed' ? Why not have the user select ALL rows first (easy enough). Much safer.

**Comment by vomikan** [comment]
Here is another point.  'All viewed' this is all in the current account after filtering.

It seems like an anachronism from the days when you could only select one transaction.  It seems we can remove this menu item.

**Comment by 2BeeOrNot** [comment]
The latest build attempts to address this. But I find it a little confusing. If I click on an account in the navigation panel and then right click on a transaction (it's not selected) the menu the popup menu says "Mark all being viewed". But it only appears to mark the transaction I clicked on.

If I click on a transaction, then right click a transaction or multiple transactions, the menu says "Mark all being selected"

**Comment by whalley** [comment]
Agree, let's remove the ALL VIEWED menu item.

**Comment by 2BeeOrNot** [comment]
Looking at latest build. The fix is great. Much better implementation of changing account status. The all being viewed was dangerous.
