### ISSUE TITLE
Crash If SVG in userthemes.zip Is Bad

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3094]
MMEX version:
 - [X] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

I was trying out userthemes.zip and changed one of the account status icons by editing the SVG with a text editor changing stroke width and color. I don't remember exactly what I did but I deleted or add a character I hadn't intended on changing or deleting. Restarting MMEX caused a crash and the create a crash report window opened. I reviewed the SVG file I had just edited, fixed it and restarted MMEX with no error. If the creation of the icons from the SVG's failed does it cause MMEX to crash?

**Comment by vomikan** [comment]
I had that happen once, too. I had to return the original working files, then change them carefully one by one.

**Comment by vomikan** [comment]
I like this user theme
https://github.com/moneymanagerex/moneymanagerex/files/6143896/usertheme.zip

PS usertheme.zip not userthemes.zip

**Comment by whalley** [comment]
Will see if I can add some safety handling that alerts user to the error and then reverts to the default theme.

Just be more careful :-)

**Comment by vomikan** [comment]
Insert into usertheme.zip the following svg file (ABOUT.svg)
```
<svg viewBox="0 0 24 24">
</svg>
```
or
```
<svg width="24px" height="24px" >
</svg>
```
it's working!
But 
```
<svg width="0px" height="0px" >
</svg>
```
would crash the app.

![image](https://user-images.githubusercontent.com/6836805/111366293-5db78980-86a4-11eb-9bf2-a633b81d94df.png)

**Comment by vomikan** [comment]
That is easy to catch this bug

![image](https://user-images.githubusercontent.com/6836805/111366966-41681c80-86a5-11eb-8a3f-de04566405b6.png)

**Comment by vomikan** [comment]
some default 'document_bak' svg doc may be created to work around this issue
```
        // Generate bitmaps at the resolutions used by the program - 16, 24, 32, 48
        bitmap = (is_svg_ok ? document : document_bak).renderToBitmap(16, 16, 96.0, bgColor);
        programIcons16[svgEnum] = CreateBitmapFromRGBA(bitmap.data(), 16);
```

**Comment by vomikan** [comment]
@whalley please review this code. It's a bug?

![image](https://user-images.githubusercontent.com/6836805/111368273-b6882180-86a6-11eb-9238-ce42d9e4c075.png)

**Comment by vomikan** [comment]
I suggest this svg as replacement for brocken file
```
<svg width="512px" height="512px" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
<polygon points="512,63.368 502.064,50.824 256,245.8 9.936,50.824 0,63.368 243.12,256.008 0,448.648 9.936,461.176 256,266.216,502.064,461.176 512,448.648 268.88,256.008"/>
</svg>
```

![image](https://user-images.githubusercontent.com/6836805/111374750-83e22700-86ae-11eb-838a-e55238b566a0.png)

**Comment by whalley** [comment]
> @whalley please review this code. Is this a bug?
> 
> ![image](https://user-images.githubusercontent.com/6836805/111368273-b6882180-86a6-11eb-9238-ce42d9e4c075.png)

No not a bug. The result is used so that we can be sure a theme matching that in the users selection is found in either the theme.zip or usertheme.zip file.

**Comment by whalley** [comment]
> That is easy to catch this bug
> 
> ![image](https://user-images.githubusercontent.com/6836805/111366966-41681c80-86a5-11eb-8a3f-de04566405b6.png)

If we hit a bad SVG then my suggestion is that we warn the user (and quote the offending file), leaving the default system theme icon. We can repeat for all bad SVGs -- It's the users fault if they have to accept many pop-ups :-)    I was thinking about then reverting to the default theme, but may be best to leave as is and let the user fix the SVG and re-open app.

**Comment by 2BeeOrNot** [comment]
Look at latest build. Tried to crash MMEX with bad SVG. I got a message that SVG was damaged and default was going to be used and was used. Much better than crashing. I'll try and be more careful in the future!

**Comment by 2BeeOrNot** [comment]
Above Nikolay posted a link to a colorful user theme. In it is a image named background.jpg. In master.css it appears to be set as a background image. The image is very colorful but it doesn't appear to work.

**Comment by vomikan** [comment]
@2BeeOrNot I don't remember, you probably use Linux.
There is a difference in the code for this system.
It would be necessary to eliminate it, but there is no way to check the performance.

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmex.cpp#L264-L291

Could you try to remove 'memory:' prefix in the master.css file?

**Comment by 2BeeOrNot** [comment]
Following up on background not working. It was not working for me on Windows 7. I then tried on Mac and it didn't work. I was putting the folder in the above link into my usertheme.zip file and renaming the folder from colorful to colorful-new to retain the original colorful from the resource themes.zip file. I then renamed my usertheme.zip file and used the usertheme.zip file from the link above and the background worked. But why? Because the two theme names start out the same. If I change the folder names so they don't begin the same it works with both colorful folders. 

May this helps better. This does not work. colorful is from the theme.zip file in the resources folder. colorful-new is from the usertheme.zip file link above.
![usertheme1](https://user-images.githubusercontent.com/63317977/111506481-0c4ce000-8720-11eb-8683-09bd117159cc.jpg)

Renaming coloful-new to nikolay-colorful works.
![usertheme2](https://user-images.githubusercontent.com/63317977/111507046-a2810600-8720-11eb-9f67-d799071f49ab.jpg)

A easy way to test this is to rename simple-black to default-simple-black, use default-simple-black, and on restart you'll get the green default theme default. Maybe this issue can be fixed. If not now that I know I won't do that again.

**Comment by whalley** [comment]
Think there may a string comparison bug in there somewhere... Let me investigate.

**Comment by whalley** [comment]
@2BeeOrNot - After a bit of head scratching (and some mild swearing) I realized what was wrong. The zip file stream handling was a little wrong, moved one line of code and now should work. Let me know how it goes.

**Comment by 2BeeOrNot** [comment]
Appears to work OK now.

**Comment by whalley** [comment]
Thanks for confirming.
