### ISSUE TITLE
the master.css is not deleted or reinstalled

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3096]
MMEX version:
 - [x] 1.5.0

I have installed the latest version 15:54:01 and manually deleted all the files master.css.
Now all errors are gone.

By the way: even if I choose the option uninstall the old version when installing, the master.css is not deleted or reinstalled.

![image](https://user-images.githubusercontent.com/6836805/111347946-c1d05280-8690-11eb-999f-d4b606d1554f.png)

**Comment by whalley** [comment]
Would not be an issue on MacOS as the resources are held in the package and the complete package is replaced. Is this an issue then with the install script for windows?

**Comment by vomikan** [comment]
I've installed mmex-1.3.6-win64.exe then remove it.
It's complitly remove C:\Program Files\Money Manager Ex folder with all files included.

But it's a problem for portable installation in case if new release overwrite old.

**Comment by whalley** [comment]
We could put a quick fix in to not load the master.css from the filesystem..

**Comment by vomikan** [comment]
Please
