### ISSUE TITLE
Switch to wxWebViewChromium

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#310]
Then we can have a unified user experience cross all platforms (windows + Mac + Linux).

**Comment by siena123** [comment]
In looking at this, the code changes to mmex are minor. The main work is integrating it into the project (both the build scripts and the installer packages).

**Comment by guanlisheng** [comment]
Cool and thanks

LiSheng

**Comment by guanlisheng** [comment]
How is everything going?

**Comment by siena123** [comment]
I have setup a branch under my fork to start working on this

**Comment by guanlisheng** [comment]
Thanks and please keep us updates week to week

**Comment by siena123** [comment]
Sorry about taking so long but I have successfully compiled a 32-bit windows version using wxWebViewChromium. I will rebase my version (1.2.0-Beta.2) to the master branch and push it to my branch for everyone to look at. I will also put together something telling everyone how I build it for Windows. The Mac and Linux builds will be similar to the steps for Windows although I don't have a current setup to test them.

**Comment by guanlisheng** [comment]
great to provide unified behavior cross all platforms and it would be the big step for the 2h of 2015

**Comment by siena123** [comment]
Code is branch "feat/310" in my repository "https://github.com/siena123/moneymanagerex.git".

Steps to build mmex using wxWebViewChromium:
1. Get chromium embedded using one of the following methods. Tested using release branch 2357.
    (https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding)
        A. Download released branch for required OS.
        B. Build from source code.
            a. Download "automate-git.py" script file.
            b. Run script file. Warning: this can take a long time, for me it was over 20 hours.
                1. For Windows (32-bit):
                    set GYP_GENERATORS=ninja,msvs-ninja
                    set GYP_MSVS_VERSION=2013
                    python /path/to/automate/automate-git.py --download-dir=/path/to/download --branch=2357
                2. For Windows (64-bit):
                    set GYP_GENERATORS=ninja,msvs-ninja
                    set GYP_MSVS_VERSION=2013
                    python /path/to/automate/automate-git.py --download-dir=/path/to/download --branch=2357 --x64-build
                3. For OS X or Linux:
                    export GYP_GENERATORS=ninja
                    python /path/to/automate/automate-git.py --download-dir=/path/to/download --branch=2357
2. Build libcef_dll_wrapper package contained in chromium embedded. Note: requires CMake to build.
    (http://www.cmake.org/)
        A. For Windows (32-bit):
             cd path/to/cef_binary_*
             "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat"
             cmake -G "Visual Studio 12"
             Open cef.sln in Visual Studio
             Change compiler options:
                 General - Treat Warnings as Errors: No
                 Code Generation - Runtime Library: Multithreaded DLL
                 Code Generation- TEnable C++ Exceptions: Yes
                 Language - Enable Run-Time Type Information: Yes
             Build libcef_dll_wrapper
        B. For Windows (64-bit):
             cd path/to/cef_binary_*
             "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"
             cmake -G "Visual Studio 12"
             Open cef.sln in Visual Studio
             Change compiler option from /MT to /MD
             Build libcef_dll_wrapper
        C. For OS X:
             cmake -G "Xcode" -DPROJECT_ARCH="x86_64"
             Open build\cef.xcodeproj in Xcode and select Product > Build
        D. For Linux:
             cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
             make -j4 cefclient cefsimple
3. Set environment variable MMEX_CEF to path/to/cef_binary_*.
4. Copy required files to output directory of MMEX. Note: list is OS depend.
        libcef.dll
        icudtl.dat
        wow_helper.exe (Windows 64-bit)
        d3dcompiler_43.dll (for Windows XP)
        d3dcompiler_47.dll (for Windows Vista and newer)
        libEGL.dll
        libGLESv2.dll
        ffmpegsumo.dll
        locales/
        cef.pak
        cef_100_percent.pak
        cef_200_percent.pak
        devtools_resources.pak
        icudtl.dat
        natives_blob.bin
        snapshot_blob.bin

Additional information can be found from the following locations.
     https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding
     http://hokein.me/wxWidgets/classwx_web_view_chromium.html

Known Issues:
     On Windows must minimize and restore the window to repaint the window for data to be displayed. I seen this early on but don't remember what I did to fix the problem. (I accidentally deleted my changes when I updated to the latest master and I'm redoing them now but wanted to post the current state for people to evaluate.)

**Comment by dwrj87** [comment]
I can do some testing on Ubuntu and Fedora if needed.

1 problem I can see is that it's been put in to the Visual Studio project files, but not in to the Bakefiles. This means that if the project files are regenerated then it will all get removed from them, and I don't think it will build at all on Linux or OSX without it being in the makefiles

**Comment by siena123** [comment]
I just updated the bakefiles.

I also found a stashed copy of the changes that I thought I lost and did not see anything different so the one known issue is likely related to getting the latest of everything. I will continue to work on the known issue.

**Comment by siena123** [comment]
I have fixed the issues that I was seeing on Windows. If everything looks ok for other platforms (OS X, Linux) then I will send pull request to merge with master.

**Comment by gabriele-v** [comment]
I haven't time to test, but how much will it increase MMEX binary files?
If I remember correctly, Chromium was quite big..

**Comment by siena123** [comment]
For 32-bit Windows: about 68 MB
Extra Files: 68 MB
mmex.exe: 0.12 MB (10 MB with ;9.88 MB without)

**Comment by gabriele-v** [comment]
Do we justify 70MB (about 7x size increase) for this? Personally I don't know..

**Comment by guanlisheng** [comment]
I do have concern here for such size increase. maybe we have to pause the processing

**Comment by siena123** [comment]
Using the version 1.2.1 of the 32-bit Windows release as a base line the total install size of mmex is 16 MB so the extra 68 MB would only be about 4.25 times increase in total install size for the application. The size of mmex.exe is 2.34 MB in the released version. The 10 MB that I gave above is not the compressed version that gets distributed nor the full install package size.

**Comment by gabriele-v** [comment]
Maybe it's possible to compress Chromium files too?

**Comment by guanlisheng** [comment]
@siena123 close this due to big sizing for chromium.

**Comment by slodki** [comment]
See also #1331
