### ISSUE TITLE
Transaction goes mad

### ISSUE THREAD

**Issue by Tulevik** [moneymanagerex/moneymanagerex#3101]
MMEX version:
 - [ X ] 1.3.7
 - [ X ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ X ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

After clicking with mouse in Edit Transaction, the new value of money you correct ends up multiplied by an order of 100x or more, whenever you change the field or press Accept button.

# Reproduction

Is the bug reproducible? 
 - [ X ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click on any transaction with right mouse button, and then click Edit Transaction
2. Modify the value in money
3. Press TAB or click on Accept. The value will be multiplied by an order of 100x or more, without a reason.

Expected result: That it don't multiply itself

Actual result: it multiplies itself

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
What currency are you using? Could you attach a screen shot of the transaction before and after you TAB to field and it changes.

**Comment by Tulevik** [comment]
I am using Euros. The following video speaks for itself. It even multiplies the initial budget:

https://user-images.githubusercontent.com/12910599/111639132-3f17d680-87fb-11eb-8873-c2ad6a26e7d2.mp4

**Comment by whalley** [comment]
I'm afraid I can't reproduce this. Can anybody else?

**Comment by Tulevik** [comment]
Is there any chance to bypass this problem? Can I edit the wrong values on the .mmb file with another program?

**Comment by vomikan** [comment]
Could you check the EUR currency settings

![image](https://user-images.githubusercontent.com/6836805/111915071-9f21ad80-8a85-11eb-8f1b-9e1b20c4a56e.png)

Change them regarding regional settings.

**Comment by Tulevik** [comment]
This is what I have (I can't edit the conversion to Base Rate, and there's also a 1e+18 in the last type. It also happens when I change the decimal char to , and the grouping to .
![screenshot 1](https://user-images.githubusercontent.com/12910599/111917391-02104600-8a80-11eb-9a4a-ad782b13e38c.png)

**Comment by Tulevik** [comment]
Ok, I've found the solution:

The decimal char of the numbers' regional configuration in Windows 10 MUST be equal to the one in the currency (same for grouping char). I had a "." in numbers decimal char and a "," in currency (the screenshots were taken after I correct this). Anyway, it still seems strange that the money I entered in the program kept increasing whenever I press TAB, so it is still a bug, isn't it?

![sshot-008](https://user-images.githubusercontent.com/12910599/112012228-4efc2700-8b29-11eb-90a8-015b1f7c5911.png)
![sshot-007](https://user-images.githubusercontent.com/12910599/112012223-4e639080-8b29-11eb-989f-e044287a8f9e.png)

**Comment by ElarsenBP34** [comment]
Hi. I experience a similar problem. I previously used the 1.4.6 version. But converted the DB and changed the version to 1.5.0 with great help from Mark Whalley.

However, after changing version I experience a similar problem as in this bug issue.
I am running macOS Big Sur 11.2.3. With Danish OS settings.

<img width="527" alt="Skærmbillede 2021-04-24 kl  13 08 33" src="https://user-images.githubusercontent.com/83119203/115956633-2daea200-a4fe-11eb-85e3-97849099522e.png">

My base currency in MoneyManager Ex is Danish kroner. And I have selected "," as the decimal char and the "." as the grouping char. Exactly as in the OS settings:

<img width="406" alt="Skærmbillede 2021-04-22 kl  21 47 03" src="https://user-images.githubusercontent.com/83119203/115956700-972eb080-a4fe-11eb-93be-220b10b53a19.png">

But for some reason, the value display sample does not reflect the settings correctly. And it is impossible for me to enter decimal values at all. Also, whenever I tab in the transaction window, the amount field is multiplied.

Mark suggested me to report my issue. Hope someone on the community can help me out on this. 

Also, I have tried to install previous/older versions like 1.3.7 and 1.3.6 to see if this would help. But these versions I cannot open on my Mac. I am told that the versions are corrupt. Even when trying to bypass the open security check.

And the 1.4.6 version I cannot find on your home page anymore. 

Thanks in advance.

KR Erik Larsen

**Comment by whalley** [comment]
@vomikan any insight on this one?

**Comment by vomikan** [comment]
![photo_2021-04-29_11-31-52](https://user-images.githubusercontent.com/6836805/116523314-c702fd00-a8de-11eb-9b65-87cd76463874.jpg)

**Comment by vomikan** [comment]
We can modify the code to permit empty values for group and decimal separators. 
If this values empty return just ```wxNumberFormatter::ToString(value, precision, style);```

```
const wxString Model_Currency::toString(double value, const Data* currency, int precision)
{
    precision = (precision >= 0 ? precision : (currency ? log10(currency->SCALE) : 2));
    int style = wxNumberFormatter::Style_WithThousandsSep;
    wxString s = wxNumberFormatter::ToString(value, precision, style);

    if (currency)
    {
        s.Replace(os_group_separator(), "\t");
        s.Replace(wxNumberFormatter::GetDecimalSeparator(), "\x05");
        s.Replace("\t", currency->GROUP_SEPARATOR);
        s.Replace("\x05", currency->DECIMAL_POINT);
    }

    if (value >= -ROUNDING_ERROR_f32 && s.Mid(0, 1) == "-") {
        s = s.Mid(1);
    }

    return s;
}
```

**Comment by ElarsenBP34** [comment]
An update from me on this one.

I have in the meantime updated my MacOS to Big Sur 11.3. Also, I have tried several setting combinations of grouping and decimal chars. Both in the OS language/region settings as well as in the currency settings in MMEX. Always reflecting the same settings both places.

Also I have tried on MMEX 1.5.0, 1.5.1 and 1.6.0 Alpha. All gives me the same problem.

When previously using 1.4.6 the MMEX currency setting was "." as the decimal char and <space> as the grouping char. But the OS setting was the standard settings for Denmark, ie. "." as the grouping char and "," as the decimal char. And that worked fine in MMEX when using "." as the decimal char when entering transactions.

But that setup in the newer MMEX versions gives me the same problems as described in this issue.

In general what I experience is:

1. The value of the amount field is multiplied by 100 for every tab/keystroke entered in the transaction dialog after entering the amount
2. The grouping char seems like always is part of the decimal char in the value layout.
3. The currency rate of the base currency is showing a very high value when saving changes in the currency manager dialog:
<img width="808" alt="Skærmbillede 2021-04-30 kl  10 05 52" src="https://user-images.githubusercontent.com/83119203/116679583-fda64980-a9aa-11eb-9f1a-dbc3171d98f0.png">

And the bug leaves me with no possibility to save decimal values. The decimal values are always changed to "00".

**Comment by vomikan** [comment]
is wxWidgets 1.3.5 ?

**Comment by vomikan** [comment]
The home page after upgrade to wx 1.3.5

![image](https://user-images.githubusercontent.com/6836805/116696180-3efa2180-a9ca-11eb-882c-f634d0e704eb.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/116696792-09096d00-a9cb-11eb-868e-042acc3c8080.png)

![image](https://user-images.githubusercontent.com/6836805/116696970-4110b000-a9cb-11eb-9a58-76123254ec14.png)

**Comment by vomikan** [comment]
There is no warning but incorrect result:

![image](https://user-images.githubusercontent.com/6836805/116697245-9e0c6600-a9cb-11eb-9f9c-c96f3438856f.png)

**Comment by vomikan** [comment]
double valiue 1.00 became "1,0,000" in case if precision = 4

Conclusion. The wxNumberFormatter::toString function is broken in the WX version 1.3.5.

@whalley  please, downgrade.

**Comment by whalley** [comment]
@ElarsenBP34 Try this build - https://www.ipx.co.uk/mmex/mmex%20v1.6.0-Alpha.1-wx3.1.4-macOS.2021.04.30.dmg

Note there are some UI/font funnies with wx3.1.4 and Big Sur.

**Comment by ElarsenBP34** [comment]
I have tried the referred build:
<img width="416" alt="Skærmbillede 2021-05-01 kl  11 20 20" src="https://user-images.githubusercontent.com/83119203/116778257-1a0cb980-aa71-11eb-88bc-d12fce94ac5a.png">

Unfortunately, this did not solve my problem on the amount being multiplied by 100 by every keystroke. It did, however, solve the problem on the funny rate being displayed for the base currency:
<img width="811" alt="Skærmbillede 2021-05-01 kl  11 35 07" src="https://user-images.githubusercontent.com/83119203/116778305-5f30eb80-aa71-11eb-8ec8-b782812397bb.png">

Futhermore, I have tried to delete the MMEXINI.DB3 file. And re-open the existing database. This as well, did not solve my problem.

**Comment by vomikan** [comment]
I have a counter question. What other (cross-platform) way is there to represent numbers in a specific format? We must take into account that our feature is the mobility of the program. On any OS with any settings, we save what the user has selected.
This is to a certain extent both an advantage and a disadvantage, because you have to invent ways to support this function.

**Comment by whalley** [comment]
Don't we have the cross platform ability built into the application already with the currency manager settings? It seems we have a mix of system locale and the the currency settings in the app. My suggest was to just use the mmex currency settings and use C-locale within the application and then just convert to/from that using the mmex currency settings.

**Comment by vomikan** [comment]
I don't mind

**Comment by whalley** [comment]
Am having problems changing my base currency "UK Pounds". Can't seem to change from grouping char (,) decimal point (.) Tried to change but did not seem to recognize that I had changed it (in the Value display sample), then app crashed.

![image](https://user-images.githubusercontent.com/487345/116979262-b1198180-acbc-11eb-9721-230a3baa62ec.png)

**Comment by ElarsenBP34** [comment]
In my setup this build by Mark Whalley has solved my problem: 
https://www.ipx.co.uk/mmex/mmex-1.6.0-Alpha.1-Darwin-2021.05.03.dmg

I can enter transactions where amounts are not muliplied by 100 by every keystroke. And the value sample is shown correctly in the Currency Manager:

<img width="406" alt="image001" src="https://user-images.githubusercontent.com/83119203/116982749-7bc76080-acc9-11eb-8195-2145c65e342e.png">

**Comment by whalley** [comment]
@vomikan Think we still have problem here. See my last comment. I’m now, since your  recent changes, got problems changing the decimal and grouping chars for my base currency.

**Comment by vomikan** [comment]
It seems that this is a different case.

**Comment by whalley** [comment]
As far as I can tell the locale settings now seem to override the currency settings for the base currency. Any reason why we are now using locale for the currency settings and not the currency manager settings themselves? I had tried to remove that link.

![image](https://user-images.githubusercontent.com/487345/116995365-e381a980-acd1-11eb-8360-3c8648f48e6f.png)

**Comment by vomikan** [comment]
>As far as I can tell the locale settings now seem to override the currency settings for the base currency. 

Yep. As soon as I emvolved Locale setings it overide the currency settings. See my last comment for the case #2473
(You can leave the Locale field empty)
