### ISSUE TITLE
Share User Created Themes?

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3105]
I created a new theme using the background from the colorful theme posted by Nikolay in closed issue #3094 with the default icons changed to blue, a new default bank icon and a couple CSS changes. If you like this bright background it looks good with blue default icons.I named it BubbleBlue.

Is there going to be a way to share user created themes? Post them here? I don't want to post it here unless this is the proper place to share user themes.

**Comment by vomikan** [comment]
Here the file will not be superfluous.
In the future, we can share topics on the forum.
Also we can create wiki page.
Or share the theme files on SF https://sourceforge.net/projects/moneymanagerex/files/

**Comment by 2BeeOrNot** [comment]
Here it is. Maybe a new category on the forum for themes would be a good place to share.

[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6166453/usertheme.zip)

**Comment by vomikan** [comment]
I like it. I suggest to change headers color.

```
.shadowTitle {
    box-shadow: 0 0 15px rgba(0,0,0,0.5); /* shadow parameters */
    padding: 10px;
    margin: 10px;
    background: linear-gradient(to right, #b7cbe4 10%, #d8e1f0 90% );
    display: flex;
    align-items: stretch;
    flex-wrap: wrap;
}
```

![image](https://user-images.githubusercontent.com/6836805/111679717-8077a880-8832-11eb-91d1-d27d3671736a.png)

**Comment by vomikan** [comment]
It is intended to use it in the following way:

![image](https://user-images.githubusercontent.com/6836805/111681112-f597ad80-8833-11eb-8d61-6498433d6c5c.png)

[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6166580/usertheme.zip)

I suggest including this topic in the release.

**Comment by vomikan** [comment]
I see a problem here. This archive will not help an untrained user to change the topic.
The idea of changing the theme is that zip archive containing one of the folders: 'default', 'colorful' or 'simple-black'.
It is not necessary to fill in 100% usertheme.zip.

**Comment by 2BeeOrNot** [comment]
Good catch on the report headers. The green was ugly with my blue theme. I don't use the reports much and didn't think to check them. Won't happen on my next theme!

I used your background linear gradient but changed the box shadow to "box-shadow: 5px 5px 10px rgba(0,0,0,0.5);" to match what I used for .shadow.

**Comment by 2BeeOrNot** [comment]
Users are going to need some education on how to use themes. For starters where to put usertheme.zip. It goes where the mmexini.db3 file is. Where's that? It depends. In macOS it's at ~/Library/Application Support/MoneymanagerEx. In Windows portable it's wherever you extracted MMEX to. If you use the Windows installer in Windows 7 it's in Users\User Name\AppData\Roaming\MoneyManagerEx if I remember correctly. (Mac user, never upgraded beyond 7. Still works after patch Tuesday's!) 

And if you want to design a theme or modify one you need more information. Do I need a complete CSS file or just changes? Do I need all icons or just ones I want to change? The directory structure needs to be the same. The file names need to be the same. Can usertheme.zip contain more than one theme? Can you use your own theme names? If you messed up the default theme will be used.

Some thoughts on usertheme.zip:
If a usertheme.zip file can only contain one theme named default, colorful or simple-black, I only have three themes to choose from at a time. Why not use a unique theme name which will allow for four themes to choose from (the three MMEX installed themes and the theme in usertheme.zip)? If create a red theme naming it simple-black doesn't work. So default? Seems like this should be the MMEX default. So colorful? Should these files name be reserved for minor changes to the three installed themes?

If I submit my BlueBubbles theme using the name usertheme.zip and someone else creates a RedBubbles theme using the filename usertheme.zip BlueBubbles will get overwritten unless the user saves a copy or renames it to save it. Does it make more sense to have the user copy the theme folder from a zip not named usertheme.zip? This is how I am using usertheme.zip. I currently have seven themes to choose from. The three default, with some CSS changes to default, colorful-3, simple-black-BG, BubbleBlue and BubbleBlue2. Next up is using the default icons and coloring them different colors. Works for me.

So maybe allow user submitted themes to use unique theme names. And the smarter than the average bear just know enough to be dangerous user can copy the theme folder in the submitted usertheme.zip file to their usertheme.zip.

In Options->View Options->UI Appearance should Style Template be Theme? These are themes that can be used as a template but they are full themes, not just a template.

Sorry for the length. Just thinking. Thanks for listening (or reading).

**Comment by whalley** [comment]
@2BeeOrNot Great input and observations. Any chance of writing a small user guide/ guidance on how the themes work and how to create your own? We can publish this in the wiki.

**Comment by vomikan** [comment]
It would be great to refine the algorithm so that a completely new custom theme is loaded, regardless of what is selected in the settings.

**Comment by whalley** [comment]
Not sure I understand the issue? A complete new theme can be defined and loaded by adding it to the usertheme.zip. You just fullly define each element. Can you clarify what you mean.

**Comment by vomikan** [comment]
For example. I've created new theme named 'blue' and I want to share it with you.
[usertheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6171127/usertheme.zip)
This file can't be used as is.

**Comment by whalley** [comment]
> It would be great to refine the algorithm so that a completely new custom theme is loaded, regardless of what is selected in the settings.

Or are you suggesting to just override the theme setting if we detect a user theme. Not sure how that works if multiple user themes are defined?

**Comment by vomikan** [comment]
I think so. There are 3 topics in the main program. At the start, we scan the zip archive. As many topics as we find there, we add them to the configuration. Themes from the user archive can be independent or override the existing 3 main themes.

**Comment by 2BeeOrNot** [comment]
Up three posts Nikolay has a link to a blue theme and says it can't be used as it. But it should work. A usertheme.zip can contain only one theme with a unique file name with all the icon SVG's and CSS file. It will be loaded and appear as a theme choice along with the three installed themes. But it doesn't if I replace my usertheme.zip with this one. If I extract the blue folder and add it to my current usertheme.zip 'blue' is now a choice.

If I extract the blue folder to the desktop, delete the blue folder in the zip file and then add back the blue folder from the desktop and save the zip file 'blue' is now a choice along with the three installed themes. Something wrong in the zip file in the link above?

In #3107 @reddyshyam commented on how themes might work. Might be better to wait on writing a small user guide/ guidance until theme implementation is finalized.

**Comment by whalley** [comment]
Will add support for multiple user themes via separate zips shortly. Sounds like this is the best way forward.

**Comment by whalley** [comment]
Now each theme needs to be encapsulated in its own zip file, and I have used the extension `.mmextheme` for these. The theme name is taken from the file name (will look to allow name to be defined by meta data at a later stage). The content of the file can be structured however the user wishes. 

User themes should exist in the usual user data folder in a sub-directory called `themes`, you can add as many as you want.

E.g.  `themes/blue.mmextheme`   (BTW I like the blue theme @vomikan)

So just create a directory with all your theme components, zip it and change extension to `.mmextheme`

**Comment by whalley** [comment]
We an improve usability a bit more in next release (e.g. #3107), but this change at least allows users to manage and share themes better.

**Comment by vomikan** [comment]
After the last changes, things got much better. Thank you. 
[blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175014/blue.mmextheme.zip)

There is a certain inconvenience in the file extension. Exchange here and on the forum will be difficult.
A zip extension would be better.
It is necessary to come up with a name for the metafile, which should be inside the archive, and by the presence of the file it will be possible to decide that this is an archive with a theme.

**Comment by vomikan** [comment]
One more theme is placed here
[yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175125/yellow-blue.mmextheme.zip)

**Comment by reddyshyam** [comment]
> One more theme is placed here
> [yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175125/yellow-blue.mmextheme.zip)
> 
> Created using primarily these icons:
> https://www.svgrepo.com/collection/human-resources-5/

@vomikan, this is causing app to crash. The blue one above is working fine.

**Comment by reddyshyam** [comment]
Thanks @vomikan and @whalley. Great to see theming coming along slowly but strongly. 👍👏🙏

**Comment by reddyshyam** [comment]
> After the last changes, things got much better. Thank you.
> [blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175014/blue.mmextheme.zip)
> In this case, it is necessary to declare that the file extension must be removed. But the zip extension may be hidden for most (Windows) users.
> 
> There is a certain inconvenience in the file extension. Exchange here and on the forum will be difficult.
> A zip extension would be better.
> It is necessary to come up with a name for the metafile, which should be inside the archive, and by the presence of the file it will be possible to decide that this is an archive with a theme.

Blue theme having green ticks, not fair! 😁 😜 

![image](https://user-images.githubusercontent.com/12392746/111869361-13d0eb00-89a5-11eb-9b2d-7068033b92b6.png)

**Comment by vomikan** [comment]
[blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175544/blue.mmextheme.zip)
[yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175545/yellow-blue.mmextheme.zip)

**Comment by vomikan** [comment]
[blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175561/blue.mmextheme.zip)
[yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175562/yellow-blue.mmextheme.zip)

**Comment by reddyshyam** [comment]
> [blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175561/blue.mmextheme.zip)
> [yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175562/yellow-blue.mmextheme.zip)

- yellow-blue still crashes on startup.
- blue crashes on selecting all transtions.

**Comment by vomikan** [comment]
@reddyshyam what is your OS?

**Comment by vomikan** [comment]
I can't reproduce this issue.
![image](https://user-images.githubusercontent.com/6836805/111870128-ea5b9380-8993-11eb-8e7c-87e83d49fc70.png)

**Comment by reddyshyam** [comment]
> @reddyshyam what is your OS?

Windows 10 pro 64bit 20H2 latest

**Comment by reddyshyam** [comment]
> I can't reproduce this issue.
> ![image](https://user-images.githubusercontent.com/6836805/111870128-ea5b9380-8993-11eb-8e7c-87e83d49fc70.png)

Blue theme worked fine until you gave me an update. May be first install it works and further updates not?

**Comment by vomikan** [comment]
I have no ideas. This is a very strange case. 

![image](https://user-images.githubusercontent.com/6836805/111870798-d1ed7800-8997-11eb-9c9d-f2feaceb4e22.png)

https://ci.appveyor.com/api/buildjobs/fp8vcfs5t081jfjy/artifacts/mmex-1.5.0-RC.1-win64-portable.zip

**Comment by vomikan** [comment]
@reddyshyam How I use this themes.

![image](https://user-images.githubusercontent.com/6836805/111870963-cd758f00-8998-11eb-9bb6-79acf505e46c.png)

![image](https://user-images.githubusercontent.com/6836805/111870968-d5cdca00-8998-11eb-8879-0c48c5f6a224.png)

**Comment by vomikan** [comment]
I've got it. In case if not 100% complited theme file placed into 'res' folder mmex crash.

**Comment by reddyshyam** [comment]
My bad! 🤦‍♂️

Still doing in same old res folder. So sorry! 

May be we should by default make themes folder to be obvious? Or even better move default themes (default, simple-black, colourful) into themes folder with a hidden backup of default theme just case crazy user like me deletes all themes? 😜

**Comment by reddyshyam** [comment]
> I've got it. In case if not 100% complited theme file placed into 'res' folder mmex crash.

You nailed it. Didnt catch up with  conversations of creating a themes folder

**Comment by vomikan** [comment]
Anyway, it's a bug. It's better to fix it.

**Comment by reddyshyam** [comment]
> Anyway, it's a bug. It's better to fix it.

Glad you feel it that way! 😁

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3107

**Comment by whalley** [comment]
> After the last changes, things got much better. Thank you.
> [blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175014/blue.mmextheme.zip)
> In this case, it is necessary to declare that the file extension must be removed. But the zip extension may be hidden for most (Windows) users.
> 
> There is a certain inconvenience in the file extension. Exchange here and on the forum will be difficult.
> A zip extension would be better.

I disagree, the purpose of a file extension is to define the scope of a file. E.g we use .mmb for the MMEX DB file and not *.db, *.db3, *.sqlite, etc. Similar for .docx which is a zip also. My view is we should leave it as .mmextheme as this makes it clear what the file format is.

**Comment by vomikan** [comment]
@reddyshyam 

Win+R
``` %userprofile%\AppData\Roaming\MoneyManagerEx\```
![image](https://user-images.githubusercontent.com/6836805/111871475-52fa3e80-899b-11eb-981c-0152dc9561ee.png)

**Comment by reddyshyam** [comment]
> @reddyshyam
> 
> Win+R
> ` %userprofile%\AppData\Roaming\MoneyManagerEx\`
> ![image](https://user-images.githubusercontent.com/6836805/111871475-52fa3e80-899b-11eb-981c-0152dc9561ee.png)

Oh! I was putting them under "Program Files" location. Let me try that

**Comment by whalley** [comment]
> I've got it. In case if not 100% complited theme file placed into 'res' folder mmex crash.

Yes the themes in the res folder are master themes and as such need to full defined. If people edit files in that folder then they run the risk of breaking things and they will be overriden in next release.

> Anyway, it's a bug. It's better to fix it.

Not strictly a bug, that is the way it is designed. I saw no reason to allow the master themes to be partly completed. Only user defined themes can be partially completed.

**Comment by whalley** [comment]
> Hence my suggestion of import or delete theme menu option where things are done in the background and the locations are hidden from user not to mess up. 😃

Yep will look to add that in 1.5.1

**Comment by reddyshyam** [comment]
> > Hence my suggestion of import or delete theme menu option where things are done in the background and the locations are hidden from user not to mess up. 😃
> 
> Yep will look to add that in 1.5.1

Thanks @whalley for taking this up. 🙏

At this rate, looks like we will 1.5.0 and release 1.5.1 instead 😜

**Comment by reddyshyam** [comment]
> [blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175561/blue.mmextheme.zip)
> [yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175562/yellow-blue.mmextheme.zip)

Both the themes looks awesome! 👏 👍 🤝  Thanks @vomikan

**Comment by vomikan** [comment]
Updated
[yellow-blue.mmextheme.zip](https://github.com/moneymanagerex/moneymanagerex/files/6175770/yellow-blue.mmextheme.zip)

**Comment by whalley** [comment]
These two themes look worthy of inclusion into the 'system' themes that we deliver as part of the install. What do you think?

**Comment by vomikan** [comment]
I agree. Moreover, the lula update will not take much time in the future.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/Art/tree/master/themes/yellow-blue

**Comment by vomikan** [comment]
It is advisable to search for themes in a separate repository, such as this one. 
https://github.com/moneymanagerex/Art/tree/master/themes/yellow-blue
All icons are immediately visible. And you can make automatic compression of data into mmextheme packages by a script. Example:

https://github.com/moneymanagerex/general-reports/blob/master/.travis.yml

**Comment by whalley** [comment]
I suggest we move this issue to 1.5.1. In 1.5.0 we can introduce the theme concept then improve usability it in next release.

We now that ability to process user specific themes and validate that they are viable. Suggest we restrict any further changes to this to essential changes otherwise the release of 1.5.0 will be delayed.

**Comment by reddyshyam** [comment]
Current snapshot alerts the following if yellow-blue theme is chosen.

![Screenshot 20210321 190858](https://user-images.githubusercontent.com/12392746/111906930-1e5cb480-8a79-11eb-81e1-96a14b8015ab.png)
![Screenshot 20210321 190853](https://user-images.githubusercontent.com/12392746/111906932-1f8de180-8a79-11eb-8215-0f936637442f.png)

**Comment by vomikan** [comment]
Yep. We (@vomikan  & @whalley ) decided that it is better to use only complete themes.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3107#issuecomment-807364634

**Comment by whalley** [comment]
@vomikan Can you create a "moneymanagerex / themes" repo please.

**Comment by vomikan** [comment]
No

![image](https://user-images.githubusercontent.com/6836805/112652668-b209f880-8e5e-11eb-8911-071f5103bdd1.png)

@guanlisheng  create a "moneymanagerex / themes" repo please.

**Comment by vomikan** [comment]
@whalley 
https://github.com/moneymanagerex/themes

**Comment by guanlisheng** [comment]
@2BeeOrNot  here you go a dedicated forum under business support

https://forum.moneymanagerex.org/viewforum.php?f=32

**Comment by whalley** [comment]
Added all themes to https://github.com/moneymanagerex/themes, have a system and user directory under that. The main repo now has this as a submodule. 

To do:
- Need to tidy up the makefile to create the system themes without having to reference specific themes
- Need travis.yml file to build *.mmextheme file for the themes repo when updated
- Neeed to update theme manager to allow user themes to be imported from the repo

**Comment by vomikan** [comment]
I've created pack.py to zip themes but can't start to use it.
https://github.com/moneymanagerex/Art/blob/master/.travis.yml
https://github.com/moneymanagerex/Art/blob/master/pack.py

**Comment by 2BeeOrNot** [comment]
Downloaded latest build, 1.5.1-Alpha 1. Where is my user theme? And my CSS changes? So mmexini.db3 and themes directory for portable version is now in Users\username\AppData\Roaming\MoneyManagerEX instead of the location I extract MMEX to? Isn't this where the installation version looked for mmexini.db3?

I copied my files to this new(?) location and all is good.

In the link two posts above (https://github.com/moneymanagerex/themes) some changes/corrections?
"(see Default Theme for detail on **teh** full list of icons)"

"The theme itself should be a zip file with an extensions .mmextheme."
Is or must be a zip file?
An extensions or extension?
Maybe "The theme itself is a zip file with an extension .mmextheme."?

Is Options->View Options->Style Template needed with the new theme manager? Or maybe make it Theme Manager with a button that takes you the theme manager?

**Comment by 2BeeOrNot** [comment]
I figured out the location of the mmexini.db3 file and theme directory. I was using the directory MoneyManager137 for testing 1.37 and 1.50. For 1.51 I created a new directory MoneyManager151 and extracted the contents of the file here. MMEX then created the mmexini.db3 and theme directory in AppData\Roaming\MoneyManagerEx. I moved mmexini.db3 and the theme directory to MoneyManager151 and it's working from there like I expected.

**Comment by whalley** [comment]
> In the link two posts above (https://github.com/moneymanagerex/themes) some changes/corrections?
> "(see Default Theme for detail on **teh** full list of icons)"
> 
> "The theme itself should be a zip file with an extensions .mmextheme."
> Is or must be a zip file?
> An extensions or extension?
> Maybe "The theme itself is a zip file with an extension .mmextheme."?

Have updated.

> 
> Is Options->View Options->Style Template needed with the new theme manager? Or maybe make it Theme Manager with a button that takes you the theme manager?

Yes it is duplicate functionality. I favor keeping the option there amongst teh other options - as you not a button to invoke the theme manager may be a sensbile option.

**Comment by whalley** [comment]
> > Is Options->View Options->Style Template needed with the new theme manager? Or maybe make it Theme Manager with a button that takes you the theme manager?

Now replaced by a button to access the Theme Manager.

**Comment by reddyshyam** [comment]
> > > Is Options->View Options->Style Template needed with the new theme manager? Or maybe make it Theme Manager with a button that takes you the theme manager?
> 
> Now replaced by a button to access the Theme Manager.

Looks good. 👏
