### ISSUE TITLE
Where is my settings?

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3107]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/3105

1) Sometimes the mmexini.db3 became broken
2) Users are going to need some education on how to use themes. For starters where to put usertheme.zip. 

It goes where the mmexini.db3 file is. Where's that? It depends. 
+ In macOS it's at ~/Library/Application Support/MoneymanagerEx. 
+ In Windows portable it's wherever you extracted MMEX to. If you use the Windows installer in Windows 7 it's in Users\User Name\AppData\Roaming\MoneyManagerEx if I remember correctly. 
Win10:
"C:\Users\xxx\AppData\Roaming\MoneyManagerEx\mmexini.db3"
+ Linux ```~\.mmex``` ???

We can probably add a menu item that allows us to open the file path via the default browser.
At least somewhere you need to display the path to this file.

**Comment by reddyshyam** [comment]
@Vomikan, Instead of messing with the installation folder, wouldn't it be better if we have a '**Themes**' menu item with sub items 
- Select theme (with further submenu to select the desired one)
- Import a theme (which allows only a zip file with folder structure required for a theme). Once imported, the zip folder will be exploded to directory into may be '**Themes**' folder.
- Delete a theme (with further submenu to select the desired one). This is will delete the specific theme folder it has created. 

If the above is possible and to keep the 'messing' bit to minimal, each theme will copied to a subfolder inside main 'Themes' folder with respective zip file name. Just a thought!

**Comment by whalley** [comment]
I've made some progress with this and now have a simple Theme Manager we can use as the basis for further developing this. 

It displays the available themes and suppports metadata via `_theme.json` file in the .mmextheme file along with a small sample image via a `_theme.png` file

Json currently looks like:
```
{ "name": "MMEX Default Theme",
    "author": "MMEX Team",
    "description": "This is the default MMEX theme and uses the MMEX colour scheme. It is a simple 'duo color' theme",
    "url": "https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/themes/default/readme.md"
} 
```

It supports the ability to:

- View available themes with characteristics from JSON file
- Select a theme to be used (currently duplicates what can be donw via options)
- Delete a user theme (system themes cannot be deleted)
- Import a user theme

(Future improvements: Add full validation of a theme prior to loading, Remove some duplicate theme management logic in the the images.cpp file, add ability to browse and load themes direct from an external site)

Will push this once we start on v1.5.1.

![Screenshot 2021-03-25 at 19 38 10](https://user-images.githubusercontent.com/487345/112533253-a9072180-8da1-11eb-8738-8eabb67262ef.png)

![Screenshot 2021-03-25 at 19 40 09](https://user-images.githubusercontent.com/487345/112533527-f2f00780-8da1-11eb-9650-6cadcefa6f4e.png)


![Screenshot 2021-03-25 at 19 38 43](https://user-images.githubusercontent.com/487345/112533318-b9b79780-8da1-11eb-889e-c4ce954b02df.png)

**Comment by whalley** [comment]
Code is here: https://github.com/whalley/moneymanagerex/tree/v1.5.1

**Comment by reddyshyam** [comment]
Wow! @whalley. Love it, love it and love it. 👍🤝👏👌

**Comment by whalley** [comment]
Pushed to master - https://github.com/moneymanagerex/moneymanagerex/pull/3163

**Comment by whalley** [comment]
Closing this, #3067 will be used to capture further updates

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10382&sid=a64aeed6a15df74da730081524acff32

**Comment by whalley** [comment]
Re-closing as I can't see any existing issue highlighted in the forum thread.
