### ISSUE TITLE
User theme incorrect folder issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3111]
In case if not 100% complited theme file placed into 'res' folder mmex crash.

#3105

**Comment by whalley** [comment]
Messing about with any files in the 'res' folder -  adding, modifying, deleting may cause adverse behavior - it is not just the themes. I don't see why this is a bug. The resource folder is part of the application and should not be modified.

**Comment by whalley** [comment]
What I would suggest is that we make ALL themes need ALL icons and I can add is a check to ensure all icons are present, and report error is any are missing. If somebody wants to create a new theme they would either need to base it on another .mmextheme file for create from new.  That way it is clear.

**Comment by vomikan** [comment]
I suggest to use default theme for all icons in initialization.
Then overwrite all icons that would be founded in other themes.

**Comment by whalley** [comment]
I think we will have disagree on this for now :-)

Whilst I understand your point of avoiding the user missing an icon in a theme by using the default icon set it then means, as I noted above, that the you can no longer guarantee that the user theme will always look the same - the 'default' we use may change over time. I.e. it can break the look-n-fell of the user theme.

If I implement a check to make sure that all necessary icons/files are include in the user theme then it will alert the user to the fact that some are missing and the theme is not compatible with the current application version. This will allow us to also alert users that the theme is out-of-date if new icons or other theme files are added in a new release. Having it silently load the 'defaults' would hide this from the user.

This way we protect the user from creating invalid themes and can make sure it will always display the same no matter what changes in the default.

**Comment by vomikan** [comment]
This will be a good solution. Fewer compromises - higher reliability.

**Comment by vomikan** [comment]
Thanks to the readme.md file, you can define the appearance and completeness of the data.

https://github.com/moneymanagerex/Art/tree/master/themes/yellow-blue

So I support the idea of checking the topic for compliance.

**Comment by whalley** [comment]
Now checks that all icon files exist and can be converted and also that the master.css file is present. If not, the user is warned and the default theme adopted until the issues are fixed.

**Comment by whalley** [comment]
@vomikan Thanks for the tidy-up. We good to close this now?
