### ISSUE TITLE
File Open Database fails to list files in folder

### ISSUE THREAD

**Issue by cliveju** [moneymanagerex/moneymanagerex#3115]
MMEX version:
 - [ X] 1.3.6
(Changelog does not go beyond 1.3.5)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

No .MMB files listed in folder that does contain MMB files. This happens in a One Drive folder. The issue does not occur in a Google Drive folder. I use both on my Windows 10 PC.

Files can be opened by typing in the filename. See screenshot.

Is the bug reproducible? 
 - [ X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Select File Open Database from MMEX menu.
2. Navigate to folder containing MMB files. Nothing displayed except subfolders
3. Try not to panic, your DB has not disappeared!
4. Type in first letters of known filename, list pops up...

Expected result:
Should see a list of MMB files.

Actual result:

# Additional information

![image](https://user-images.githubusercontent.com/62719443/111907427-27d02780-8a4d-11eb-8064-d06d03c88baf.png)

**Comment by vomikan** [comment]
Previously, the emb extension was used for encrypted database files. But after some fixes, all files began to use the mmb extension.I suggest to change emb extantion to the mmb. It should be a solution.

**Comment by cliveju** [comment]
Oh yes, now I see there are different file extensions and there is an option to change the search to .EMB. It would be better for users if the File Open Database simply showed both types.
