### ISSUE TITLE
When viewing any account the last transaction is not initially selected

### ISSUE THREAD

**Issue by ChrisCross321** [moneymanagerex/moneymanagerex#3118]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [X] 1.5.0 RC1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When viewing any account the last transaction is not initially selected
On previous versions (e.g. 1.3.6) when selecting any account the last sorted transaction is always shown and selected. This is especially important when the transactions are sorted by date, as these are the transactions that will generally be worked with and where new ones will be added. Otherwise If there are hundreds/thousands of transactions in an account, you would forever be spending time going to the last transaction.   
With 1.5.0 RC1 when first running MMEX the first time you select any account to view the transactions, although it will show the last transaction, it does not select it, then any subsequent selections of that or any other account will show the beginning of the transactions (instead of the end), meaning you have to manually go to the end of the transaction list every time.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Run MMEX
2. Select any account to view which has multiple screens of transactions (on the first viewing the end of transactions will be viewed although the last transaction is not selected).
3. Select any other account to view which has multiple screens of transactions (the beginning of the transactions are now always selected not the end).
4. Continue selecting any account to view which has multiple screens of transactions, including those you have already viewed (the beginning of the transactions are always selected)  

…

Expected result:
Whenever an Account is selected the last sorted transaction is always selected.

Actual result:
Whenever an Account is selected the last sorted transaction is never selected. (although on the first account view after running MMEX the and of the transactions are viewed, the last transaction is not actually selected).

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Here the m_topItemIndex varible should be equal -1 the account selected.

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmchecking_list.cpp#L975-L977
