### ISSUE TITLE
Pasted transaction not selected

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#3125]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [X]  1.5.0

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When copying/paste a transaction, the pasted transaction it's not automatically selected (was working in 1.3.x)

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Copy a transaction (CTRL + C)
2. Paste it (CTRL + V)

…

Expected result:
Pasted transaction is selected

Actual result:
Copied transaction still remains selected

**Comment by gabriele-v** [comment]
@vomikan not sure if this should be considered an enhancement or a bug because in 1.3.x was working, so I'd consider it a bug or at least a regression

**Comment by vomikan** [comment]
@whalley  will it be possible to implement this for version 1.5.0? Initially, I suggested using a vector with ID of the selected transactions. Then you changed the code. Seems the interface now works with selected lines. This will probably make it more difficult to decide on this case.

**Comment by whalley** [comment]
Will have a look.

**Comment by vomikan** [comment]
MS Excel behavior
![image](https://user-images.githubusercontent.com/6836805/112626207-f2f31480-8e40-11eb-8345-041946a17cf4.png)
If some cells has been copied only new transactions became selected.

MMEX behavior
![image](https://user-images.githubusercontent.com/6836805/112626377-2afa5780-8e41-11eb-88bf-f95954e16bb0.png)
All (source and child) transactions became selected

**Comment by whalley** [comment]
If that is the expected behaviour I can change to support that. Leave it with me.
