### ISSUE TITLE
Wrong sorting icons

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#3126]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [X] 1.5.0

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Not sure if it was the same with 1.3.x, but sorting icon are swapped, or is not an icon issue but on the sorting itself?

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Sort transactions by a column

…

Expected result:
▲ icon should be used when sorting from older to newer date or from A to Z
▼ icon should be used when sorting from nwer to older date or from Z to A

Actual result (swapped):

![image](https://user-images.githubusercontent.com/7106290/112190960-ce5f2880-8c05-11eb-9480-63b3a02e5f59.png) ![image](https://user-images.githubusercontent.com/7106290/112191216-15e5b480-8c06-11eb-866e-35db7902cac2.png)

**Comment by vomikan** [comment]
It's just for comparison
![image](https://user-images.githubusercontent.com/6836805/112202233-30c62200-8c22-11eb-9a26-c7d9fa1df06b.png)

**Comment by gabriele-v** [comment]
Yep, as it look to be in all other software

**Comment by vomikan** [comment]
And we have the same case in third-party code.
![image](https://user-images.githubusercontent.com/6836805/112318163-cd89cd80-8cbd-11eb-9b96-ed9a32133095.png)

**Comment by vomikan** [comment]
file:///D:/test/DataTables-master/examples/basic_init/table_sorting.html
