### ISSUE TITLE
Bank transactions are no longer displayed

### ISSUE THREAD

**Issue by Dom93-del** [moneymanagerex/moneymanagerex#3127]
Translated: 
Hello
For about ten days when I use MMEX the bank transactions are no longer displayed (the view of the account is empty but the values ​​of the account balance and the reconciliation balance are exact). When I create an operation it is taken into account (the balance of the account changes correctly). The transaction also appears in reports but not in the account view or when using the advanced filter.
I uninstalled MMEX then reinstalled it creating a new base but the same problem appeared.
Thank you for your help
Please do not erase the attached information below this text.

> Bonjour 
Depuis une dizaine de jours lorsque j'utilise MMEX  les opérations bancaires ne s'affichent plus (la vue du compte est vide mais les les valeurs de la balance du compte et de la balance de réconciliation sont exactes ). Lorsque je crée une opération elle est bien prise en compte (la balance du compte se modifie correctement). L'opération apparait également dans les rapports mais pas dans la vue du compte  ni en utilisant le filtre avancé.
J'ai désinstallé MMEX puis l'ai réinstallé en créant une nouvelle base mais le même problème est apparu.
Merci de votre aide
> Veuillez ne pas effacer les informations jointes dessous ce texte.

<hr>Version: 1.3.6 64-bit<br>
 • db 7 •  (aes128cbc)<br>
<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.61.0-DEV WinSSL<br>
<br>
Build: Dec 24 2020 15:07:56 <br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • gettext 0.19.8.1<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  French (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
Closing as this is old and dated.
