### ISSUE TITLE
Copy/Past transaction dates

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3130]
When some transactions in the past selected on the Past command they would be inserted for today.

![image](https://user-images.githubusercontent.com/6836805/112447587-8d305b00-8d62-11eb-8088-c417c95e6f94.png)

Is it bug or feature?

**Comment by whalley** [comment]
I think this is by design, I think this is the most useful date to use.

**Comment by vomikan** [comment]
You can break the dates if you copy from one account to another.

**Comment by whalley** [comment]
That sounds a good idea and workable.

**Comment by whalley** [comment]
I'll look at this later this evening

**Comment by whalley** [comment]
We have an option in the settings....

<img width="480" alt="Screenshot 2021-03-26 at 15 21 07" src="https://user-images.githubusercontent.com/487345/112654201-0d2ff100-8e47-11eb-869d-715d3ffa5f7c.png">

The current logic follows the rules defined by this.  I would therefore suggest we leave as currently defined **BUT** where we paste into the original account, with the original date, we mark as DUPLICATE. What do you think?

**Comment by vomikan** [comment]
You are right. It's working well for one transaction.
But it's working bad for manies.

**Comment by whalley** [comment]
Actually, yes. Now we have the pasted transaction highlighted it is clear. Should we therefore leave as-is rather than complicate further?

**Comment by vomikan** [comment]
If someone remembers about it, then it will be possible to look.
