### ISSUE TITLE
1.5.0-RC.1 on Linux mint 20.1

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#3134]
MMEX version:
 - [X] 1.5.0-RC.1

Operating System:
  - [X] Linux 

# Description of the bug

It is not possible to install on the above os.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Download the .deb file (tessa)

2. Run Install
3. It crashes

…

Expected result:

Actual result:

# Additional information: the crash report

If you have a backtrace for a crash or a warning, paste it here.
<?xml version="1.0" encoding="UTF-8"?>
<report version="1.0" kind="exception">
  <system description="Linux 5.8.0-48-generic x86_64"/>
  <modules>
    <module path="[heap]" address="55b592822000" size="0065a000"/>
    <module path="[stack]" address="7fff402fe000" size="00021000"/>
    <module path="[vdso]" address="7fff403c7000" size="00002000"/>
  </modules>
  <stack>
    <frame level="0" function="mmGUIApp::ReportFatalException(wxDebugReport::Context)" offset="00000383"/>
    <frame level="1"/>
    <frame level="2"/>
    <frame level="3" function="CreateBitmapFromRGBA(unsigned char*, int)" offset="00000104"/>
    <frame level="4" function="buildBitmapsFromSVG(wxString, wxString)" offset="000006d9"/>
    <frame level="5" function="mmBitmap(int)" offset="000000bc"/>
    <frame level="6"/>
    <frame level="7" function="navtree_images_list()" offset="0000006c"/>
    <frame level="8" function="mmGUIFrame::createControls()" offset="000001cb"/>
    <frame level="9" function="mmGUIFrame::mmGUIFrame(mmGUIApp*, wxString const&amp;, wxPoint const&amp;, wxSize const&amp;)" offset="0000034d"/>
    <frame level="10" function="OnInitImpl(mmGUIApp*)" offset="00000ecf"/>
    <frame level="11" function="mmGUIApp::OnInit()" offset="000000b8"/>
    <frame level="12" function="wxEntry(int&amp;, wchar_t**)" offset="000000aa"/>
    <frame level="13" function="main" offset="00000028"/>
    <frame level="14" function="__libc_start_main" offset="000000f3"/>
    <frame level="15" function="_start" offset="0000002a"/>
  </stack>
</report>

**Comment by vomikan** [comment]
Is the issue the same?
https://github.com/moneymanagerex/moneymanagerex/issues/3106

**Comment by whalley** [comment]
Sounds like the same issue. @avma - Can you confirm whether you have tested with the latest development build?

**Comment by avma** [comment]
I Think it was, downloaded from here yesterday....
`Package: mmex
Version: 1.5.0-RC.1-1~tessa
Section: misc
Priority: extra
Architecture: amd64
Depends: wx3.0-i18n, libc6 (>= 2.27), libcurl4 (>= 7.16.2), libgcc1 (>= 1:3.0), liblua5.3-0, libstdc++6 (>= 5.2), libwxbase3.0-0v5 (>= 3.0.4+dfsg), libwxgtk-webview3.0-gtk3-0v5 (>= 3.0.4+dfsg), libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg)
Homepage: http://www.moneymanagerex.org/
Replaces: moneymanagerex
Installed-Size: 14994
Maintainer: MoneyManagerEx Developers <developers@moneymanagerex.org>
Description: Simple to use financial management software
`
