### ISSUE TITLE
macOS - No Drop Down Calendar When Entering Transactions Dates

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3139]
Windows users can drop down a monthly calendar and pick a transaction date. I usually enter transaction dates that are a few days before the current date or a few days in the future. I find the calendar very useful to pick a date. I began using MMEX a long time ago on Windows and as a Mac user now I miss the calendar. Mac users only get the spinner, no drop down calendar. Is this something that can be implemented for Mac users?

![Trx Date](https://user-images.githubusercontent.com/63317977/112574582-f943ab00-8dc4-11eb-84f2-5e93a082ee0f.png)

**Comment by whalley** [comment]
I don’t think this is supported via wxWidgets on Mac. I too find it a bit of an annoyance.

**Comment by whalley** [comment]
Would need to look at adding a wxCalendarCtrl pop-up to a custom DatePickerCtrl for MacOS, which is doable.
![image](https://user-images.githubusercontent.com/487345/112634115-18c4ed00-8e32-11eb-9c63-4ddc6224bbf8.png)
https://docs.wxwidgets.org/3.0/classwx_calendar_ctrl.html

**Comment by whalley** [comment]
Looks blocked by this - https://trac.wxwidgets.org/ticket/19229

**Comment by whalley** [comment]
We now have a fix for this - https://github.com/wxWidgets/wxWidgets/commit/8b8c6f8af6feea46957dec9bb1efa6332a50c897

Hopefully this can be unblocked with the release of wx3.1.7

**Comment by vomikan** [comment]
#4301

**Comment by whalley** [comment]
Now implemented for MacOS, Usage is as follows:

1. Right-click on the date field and the popup will appear allowing you to select a date from the calendar view
2. Double-click on a date and it will close the popup and insert the chosen date into the date field
3. Just click anywhere outside the popup and it will disappear.

Functionality should be available on all Date fields in the application.

![CleanShot 2022-07-02 at 19 21 32](https://user-images.githubusercontent.com/487345/177012178-ab5555b8-056c-4b3c-ad5e-0d7bdb492967.png)

![CleanShot 2022-07-02 at 19 22 11](https://user-images.githubusercontent.com/487345/177012198-fe8975af-b0ef-4a65-816c-bedb7ebb04a3.png)


![CleanShot 2022-07-02 at 19 19 54](https://user-images.githubusercontent.com/487345/177012155-98d81b97-0394-4af0-b6cd-e3d55fa622ef.png)

**Comment by whalley** [comment]
Latest MacOS v1.5.17Beta1 has this change and can be found [here](https://mmex.ipx.co.uk/) for testing.

**Comment by whalley** [comment]
Having reviewed against Windows built-in control I've moved the popup position a behavior to align with this

- The popup is now below the date field
- The date control updates as you move through the calendar, no need to double-click

![CleanShot 2022-07-02 at 20 50 19](https://user-images.githubusercontent.com/487345/177014509-6b2828a7-f734-4aaa-a281-ce8d9f050a74.png)

**Comment by 2BeeOrNot** [comment]
Thank you!
