### ISSUE TITLE
Default amount per payee

### ISSUE THREAD

**Issue by franfos** [moneymanagerex/moneymanagerex#3155]
# Description of the feature

I used to work with Microsoft Money Manager, and it had a nice feature I think it could be added to MMEX. The payees had a default category and amount (the last one used). 
This will force to change the order the values are inputed in the transaction dialog, but it could improve transaction's creation speed. The amount would be entered after the payee (or destination account in transfers).
# Use cases
There are many expenses related to one payee that have always the same amount

**Comment by vomikan** [comment]
To speed up, please use the search for a similar transaction, then duplicate it. Or copy and paste.

![image](https://user-images.githubusercontent.com/6836805/112729527-9590bd80-8f3d-11eb-8b40-f36e96cc54d6.png)
