### ISSUE TITLE
Transaction list scrolls to end when CTRL+1 .. CTRL+7 or CTRL+0 pressed

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3157]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux   Not tested

# Description of the bug

When pressing CTRL+1 .. CTRL+7 or CTRL+0 to colour a transaction, the display scrolls to the end of the transaction list.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Have a bank account containing enough transactions to fill the screen 3 or 4 times, so that the scroll bar is displayed.
2. Order the transactions by date ascending.
3. Scroll with the mouse wheel to the start of the list and click on a transaction a few rows down from the top to select it.
4. Press CTRL+7 to colour the transaction. **BUG**: Instead of staying at the same scroll position, the display scrolls to show the final (i.e. most recent date) transaction in the list.
5. Press up arrow. The list scrolls back to (one above) the coloured transaction. **BUG**: Observe that the transaction colour isn't actually shown until you move the mouse cursor over the transaction.
6. Click on the coloured transaction to select it.
7. Press CTRL+0 to remove the transaction colour. **BUG**: Instead of staying at the same scroll position, the display scrolls to show the final transaction in the list.
8. NB in some circumstances (I can't tell exactly when yet), at step 7 the scroll position does _not_ jump to the end of the list. Thereafter it never jumps to the end again when pressing CTRL+[0..7] _unless_ you first select a different bank account (or a Report), then reselect the initial account and repeat from step 3.

Expected result:
When changing the colour of a transaction, the transaction list scroll position should not change.

After pressing up arrow at step 5 above, the transaction colour should be displayed.

Actual result:
When changing the colour of a transaction, the transaction list scroll position scrolls to the end of the list.

After pressing up arrow at step 5 above, the transaction colour is not displayed until the mouse is moved over the transaction.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Same issue on MacOS.

**Comment by vomikan** [comment]
@whalley  is it the same issue?
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10365

**Comment by whalley** [comment]
That report is against Version: 1.3.6 64-bit so it seems an old issue.
