### ISSUE TITLE
Tips not displaying correctly when transaction selection changed

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3161]
MMEX version:
 - [x] 1.5.0 rc2

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux     Not tested

# Description of the bug

1. The tip at the bottom of the screen is displayed for only a brief moment and then disappears when the selection is changed to a different transaction .
2. A new tip is displayed whenever the number of transactions selected (in multi-select) is changed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Display a bank account containing a few dozen transactions. 
2. Click on a transaction near the top of the list to select it. Observe that no tip is displayed.
3. Press the down arrow key repeatedly to individually select subsequent transactions (i.e one selected at a time). **BUG**: Observe that on each key press a tip is displayed very briefly and then disappears.
4. Click on a transaction near the top of the list to select it. Observe that no tip is displayed.
5. Hold down SHIFT and then press the down arrow key repeatedly to select multiple subsequent transactions.  **BUG**: Observe that on each key press, as the selection is increased, a _new_ tip is displayed.
6. A new tip is also displayed on each key press if SHIFT up arrow is now used to decrease the selection.

Expected result:

1. When a tip is displayed, it should remain displayed for more than just a brief moment.
2. When transactions are added to, or removed from, a multi-selection the tip should not change.

Actual result:

1. A tip is displayed very briefly and then disappears.
2. A new tip is displayed every time the number of transactions selected changes.

# Additional information

Some questions...

1. When are tips intended to be displayed?
2. Should a new tip be displayed after a certain length of time, or after a certain number of transaction selections or edits are made?
3. What events, if any, should cause a displayed tip to be cleared?
4. Should there be a 'Show Tips' tick box on the 'Options | View' page so that the display of tips can be suppressed? When you've seen them all several times, they are no longer very helpful.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/2914

**Comment by whalley** [comment]
Tips are displayed when:
1. No transactions are selected
2. Multiple transactions are selected
When a single transaction is selected the area where the tip is displayed is used to display the 'Notes' against a single transaction.
I can't reproduce the issue at step 3 on my Mac. I never get a tip when a single entry is selected.

I like the idea to suppress tips! We should implement this.

**Comment by tactilis** [comment]
@whalley 
> I can't reproduce the issue at step 3 on my Mac. I never get a tip when a single entry is selected.

See the attached video which was recorded on Windows.

The tips flash up briefly when using the arrow keys to move the selection up or down.

They also flash up when selecting a transaction with the mouse, although occasionally the clearing of the tip is so fast that the tip does not appear.


@whalley 
> Tips are displayed when: Multiple transactions are selected

I don't think they should be. Especially if the capability in related issue #2914 is resolved.


https://user-images.githubusercontent.com/4060092/112966978-a78f7d80-9142-11eb-93fe-34801cb59529.mp4

**Comment by whalley** [comment]
Maybe my Mac M1 is too fast :-)

Perhaps we should just display the tip when nothing is selected?

**Comment by vomikan** [comment]
As it was originally intended:
1) tips shown if nothing selected;
2) The transaction notes shown if the transaction selected;
3) If more than 1 transaction selected shown some resume. #2914

**Comment by vomikan** [comment]
I can confirm when pressed and holding the arrow key to move the selection up or down the tips flash up very fast by a nanosecond.

> Maybe my Mac M1 is too fast :-)

No. It seems that Windows so fast that can reproduce it. :)

**Comment by tactilis** [comment]
> PS the "monday" [right] of search fields seems a bug. It should be nothing there.

I have found it useful to have the transaction day displayed.
Perhaps it should be part of the transaction info to be shown below the New Edit Delete buttons when a single transaction is selected:

\-------------------------
[Monday..Sunday]

Some notes here
2nd line of notes here
etc


All to be replaced by the resume if multiple transactions are selected
