### ISSUE TITLE
Theme background color

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3166]
It would be interesting to redefine the color of the main GUI elements according to the chosen theme.

![image](https://user-images.githubusercontent.com/6836805/112983805-c7389d00-9166-11eb-8fa6-31ffd581b2da.png)

**Comment by vomikan** [comment]
We should make the icons transparent.
![image](https://user-images.githubusercontent.com/6836805/113513542-effbd080-9572-11eb-9756-f5743e457cf3.png)

```
void mmGUIFrame::createControls()
{
.....
    m_nav_tree_ctrl->SetBackgroundColour(wxColor(229, 229, 229));

```

**Comment by vomikan** [comment]
@whalley what is the reason that only the account icons have a white mask?

    { "ALLTRANSACTIONS.svg", { ALLTRANSACTIONS, 0xFFFFFFFF } },
    { "NAV_FILTER.svg", { NAV_FILTER, 0xFFFFFFFF } },
    { "NAV_GRM.svg", { NAV_GRM, 0xFFFFFFFF } },
    { "NAV_HELP.svg", { NAV_HELP, 0xFFFFFFFF } },

**Comment by whalley** [comment]
The mask is there to fix this https://github.com/moneymanagerex/moneymanagerex/issues/2970#issuecomment-788394090 . 

Now we have different themes the mask should be driven from the metadata.

**Comment by whalley** [comment]
Metadata now available to customise this: https://github.com/moneymanagerex/themes

**Comment by emagra** [comment]
Yeah, but on Ubuntu 20.10 with dark theme (Yaru-Dark) this is the result.
![immagine](https://user-images.githubusercontent.com/149369/116269823-d1a68080-a77e-11eb-80c7-6794189ef0bd.png)

**Comment by whalley** [comment]
You would need to set colors/navigationPanel. WxWidgets does not in all cases adopt the system color scheme.
