### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3172]
1) cmake command should be ('v' added):
        COMMAND ${CMAKE_COMMAND} -E tar "cvf" "${output_file}" --format=zip -- ${input_files} 

2) on start
![image](https://user-images.githubusercontent.com/6836805/113041844-1dc3cc80-91a3-11eb-97d5-983cd2637e51.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/113046402-b6108000-91a8-11eb-8b82-78607e0b1689.png)

**Comment by whalley** [comment]
Error in CMake

file(GLOB THEME_SIMPLEBLACK_FILES "${PROJECT_SOURCE_DIR}themes/system-themes/simple-black/*")

should be 

file(GLOB THEME_SIMPLEBLACK_FILES "${PROJECT_SOURCE_DIR}/themes/system-themes/simple-black/*")

My error! - Missing "/"
