### ISSUE TITLE
Option to suppress tips

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3180]
# Description of the feature

There hould there be a 'Show Tips' tick box on the 'Options | View' page so that the display of tips can be suppressed.

When you've seen them all several times, they are no longer very helpful.

**Comment by whalley** [comment]
related #3161

**Comment by vomikan** [comment]
We can transform the text area below the panel to html frame and for every tip make a checkbox [x] hide me

**Comment by vomikan** [comment]
Also we need on option to suppress tooltips.

**Comment by whalley** [comment]
Have implemented Tooltip and Money Tip view options so that they can be suppressed or enabled. Have not implemented the [x] hide me option for every tip as I think that could get annoying.

The tooltip suppression needed every ****->SetToolTip() to be changed as the wxWidgets tooltip global disable option does not work on all platforms, a RegEx search/replace worked well thankfully.

**Comment by whalley** [comment]
One thing to add, I left the tooltips on the main toolbar as I think it adds valid context to the icons without being distracting.
