### ISSUE TITLE
wxBitmapButton icon sizes should be consistent with other Buttons and widgets

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3188]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux  Not tested

# Description of the bug

On the Edit Transaction dialog:

1. The 'Number' field changes its vertical size when the 'Populate Transaction #' icon changes size as a result of setting Options | View | 'Others Icon Size'.
2. The text within the 'Number' field is not centred vertically.
3. The 'Organize attachments of this transaction' paperclip icon is too large for the button if Options | View | 'Others Icon Size' is set to 32px.
4. The [...] button is always greyed out (so far as I can see) and has no tooltip to hint at its purpose.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

Note the difference in the Number field and the icon buttons in the attached screenshots:
1. Dialog with 'Others Icon Size' is set to 24px
2. Dialog with 'Others Icon Size' is set to 32px

Expected result:

1. The 'Number' field should not change its vertical size when the icon size is changed.
2. The text within the 'Number' field should be centred vertically.
3. The 'Organize attachments of this transaction' paperclip icon should properly contain the icon.
4. The [...] button should not always be greyed out and should have a tooltip.

Actual result:

See screenshots.

# Additional information

Questions:

1. Should the 'Others Icon Size' option change the size of icons within dialogs?
2. Why do we have an 'Others Icon Size' option at all? Does anyone actually need it?

![image](https://user-images.githubusercontent.com/4060092/113444831-8c479b00-93ec-11eb-85f0-b541e1fd8a03.png)

![image](https://user-images.githubusercontent.com/4060092/113444845-95386c80-93ec-11eb-9c15-f83b51070e2e.png)

**Comment by tactilis** [comment]
This bug is not specific to 1.5.1 Alpha.1.  I have verified that it exists in 1.5.0 RC2 (latest build on master), I have therefore edited the MMEX version in the original report.

**Comment by whalley** [comment]
All these are hopefully fixed. Did not change the [...] button  behavior as that already seems to work OK.

I think longer term we should look to have a 'button size' option to control these to ensure that all the buttons are the same size rather than just scaling those with icons.

**Comment by tactilis** [comment]
@whalley
>  think longer term we should look to have a 'button size' option to control these to ensure that all the buttons are the same size rather than just scaling those with icons.

Agreed.  Assuming that there is any need to change the button size at all. After all, we don't allow changing of field sizes and nobody seems to need that.

**Comment by whalley** [comment]
@tactilis Actually I agree with you. I think for all the buttons we should not scale the image as it is illogical to scale those with an image and those with just text. So it will just be non-button images that we scale.

I'll update the title of the issue and make this change.

**Comment by whalley** [comment]
wxBitmapButton sizes now driven by a constant `mmBitmapButtonSize`, which is currently set to 16x16. This aligns best with other Button sizes, and works fine with scaled resolutions on MacOS.

  If we need to ever programmatically adjust this we can change it from a constant as needed.

@Vomikan - Can you check if this is fine on Win.
