### ISSUE TITLE
Inconsistent highlighting of Recurring Transactions in Navigation pane

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3190]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX Not tested
 - [ ] Linux Not tested

# Description of the bug

The highlighting of the Recurring Transactions entry in the Navigation pane is not consistent with that of the other entries.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Click on the Recurring Transactions entry of in the Navigation pane. Observe that it highlights for a moment in blue but then changes to grey.
2. Click on the Recurring Transactions entry again. Observe that it is now highlighted in blue.

Expected result:

As with the other Navigation pane entries, the Recurring Transactions entry should be highlighted in blue on the first click.

Actual result:

It takes two clicks to properly highlight the Recurring Transactions entry. See the attached video.

# Additional information

https://user-images.githubusercontent.com/4060092/113456225-8fe71c00-9404-11eb-8692-6324520cfc8c.mp4

**Comment by vomikan** [comment]
This is some kind of mystical glitch. I didn't understand where it came from.

**Comment by vomikan** [comment]
@tactilis can you please direct your efforts to finding bugs in version 1.5.0 ? It is on the verge of release. Version 1.5.1 is still very unstable.

**Comment by tactilis** [comment]
> @tactilis could you please direct your efforts to finding bugs in version 1.5.0 ? It should be released soon. Version 1.5.1 is still very unstable.

Sure, no problem Nikolay.

I had misunderstood the request:

"Note: bug reporters are expected to have verified the bug still exists either in the last stable version of MMEX **or on updated development code** (master branch)."

I was looking at the wrong branch I suppose. Github is still new to me.

**Comment by tactilis** [comment]
@vomikan This bug is not specific to 1.5.1 Alpha.1. I have verified that it exists in 1.5.0 RC2 (latest build on master), I have therefore edited the MMEX version in the original report.

**Comment by vomikan** [comment]
All panel call functions work the same way. But only this panel behaves in this way. I couldn't figure out the reason.

**Comment by vomikan** [comment]
One mo issue:
Select Recurring Transactions navigation panel item then press Enter button

![image](https://user-images.githubusercontent.com/6836805/113480171-c1f78d00-949b-11eb-9a2a-4b2a74c69292.png)
