### ISSUE TITLE
Inconsistent highlighting of Transaction Report in Navigation pane

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3194]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux   Not tested

# Description of the bug

The highlighting of the Transaction Report entry in the Navigation pane is not consistent with that of the other reports.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Click on the Transaction Report entry of in the Navigation pane. Observe that it highlights for a moment in blue but then changes to grey when the Transactions Filter dialog is displayed.
2. Click OK in the Transactions Filter dialog to generate the report. Observe that Transaction Report entry it is now _not_ highlighted and that the Reports entry is highlighted.

Expected result:

When clicked on, the Transaction Report entry of in the Navigation pane should highlight in blue and stay highlighted to indicate the report you are interacting with.

Actual result:

Highlighting is inconsistent as described in Reproduction Steps and shown in the attached video.

# Additional information

https://user-images.githubusercontent.com/4060092/113476172-af685e00-9471-11eb-8a9a-4421f48753df.mp4

**Comment by vomikan** [comment]
This is so done on purpose. Otherwise, how can you call the report several times?

**Comment by tactilis** [comment]
I understand.

Does wx not produce an event whenever you click on the tree entry, even if it is already highlighted?

What is the difference between the blue and the grey highlighting?

A minor thing perhaps, but it just feels wrong that the highlight moves to a different entry (i.e. Reports).

**Comment by vomikan** [comment]
>Does wx not produce an event whenever you click on the tree entry, even if it is already highlighted?

No. That's why I had to shift the focus to the Reports item.

>What is the difference between the blue and the grey highlighting?

I have no ideas.

**Comment by vomikan** [comment]
@tactilis 
>What is the difference between the blue and the grey highlighting?

The grey highlighting is meaning navigation panel not in focus.
