### ISSUE TITLE
Transaction text colour for new highlight colours 6 and 7 should be black (not yellow)

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3206]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux  Not tested

# Description of the bug

In version 1.5.0, the colours used to highlight transactions have been updated from very bold colours used in 1.3.x to much softer shades (which is a good improvement).

In 1.3.x the transaction text had to be displayed in yellow to make it readable against the blue and purple highlight of  colours 6 and 7

In 1.5.0 RC2, the transaction text colour for highlight colours 6 and 7 is _still_ yellow. This makes it less readable.

For the new softer shades in 1.5.0, the transaction text should always be black.
 
# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

See the attached screenshot.

1. Colour a set of transactions using CTRL+1 .. CTRL+7
2. Observe that the text colour for highlight colour 6 and 7 is yellow and is harder to read.

Expected result:

In 1.5.0, the transaction text should be black for _all_ the highlight colours to enhance readability.
In the screenshot, I have recoloured the text in rows 9 and 10 to demonstrate this.

Actual result:

Yellow text is not so easy to read. See screenshot rows 6 and 7.

# Additional information

![image](https://user-images.githubusercontent.com/4060092/113505735-aa221680-9538-11eb-9d6c-97fd772f3fbc.png)

**Comment by whalley** [comment]
As the colours are user-selectable we should really be calculating whether to use black or white font. 

Some possible algorithms here:
- https://gomakethings.com/dynamically-changing-the-text-color-based-on-background-color-contrast-with-vanilla-js/
- https://dev.to/isarisariver/how-to-determine-font-color-based-on-a-random-background-color-8ek

**Comment by whalley** [comment]
Font colour is now calculated to complement background. See #3590
