### ISSUE TITLE
Can't start last update on Windows

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3214]
https://github.com/moneymanagerex/moneymanagerex/pull/3213/commits/249447dcc926530fe9ac01640213cf97e24d0ffd

![image](https://user-images.githubusercontent.com/6836805/113915571-9c45ed00-97e7-11eb-89f4-f6b2709b19bc.png)

@whalley I can't fix it.

**Comment by whalley** [comment]
Hopefully fixed... https://github.com/moneymanagerex/moneymanagerex/pull/3215
