### ISSUE TITLE
Left navigation bar icons and items disappear on clicking 

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#3220]
> While clicking on an item in the Left navigation bar, icons and item  disappear from display/ (see image)
![Screenshot from 2021-04-09 13-34-49](https://user-images.githubusercontent.com/7680483/114168497-fb674700-9938-11eb-9854-5c38f9fdc6e8.png)
<hr>Version: 1.5.1-Alpha.1 64-bit<br>
 • Build: apr
  7 2021 16:06:20<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.3 (wxGTK 3.24)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.3<br>
 • lunasvg <br>
 • libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 ( libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.3<br>
 • GNU Make 4.2.1<br>
 • GCC 9.3.0 • Linuxmint 20.1

**Comment by vomikan** [comment]
#658 #516 #1091 #1143 #1764

**Comment by MartinX3** [comment]
Still happening on v1.5.4

**Comment by yaomtc** [comment]
Whenever I edit an account, most of the navigation disappears when I hit OK. If I hover over the panel, this makes the scroll bars appear, which makes some of the panel reappear at the edges. Scrolling the navigation or resizing the panel makes the issue go away until the next time I edit an account. This happens on both X11 and Wayland (Plasma) with 1.5.14 on Arch Linux.

On Wayland, there is additional weird behavior. Often when I switch from one account to another, the name of the account I switched from will flicker. Sometimes, when the window is in the background, a section of the top right of the window will flicker.

Here's a couple screenshots of the first issue. I'll get a capture of the second issue shortly.
![Screenshot_20220519_203753](https://user-images.githubusercontent.com/5534045/169426011-c09d40e8-c676-4c33-8ebd-7e3075bfdc85.png)
![Screenshot_20220519_203738](https://user-images.githubusercontent.com/5534045/169426012-2c202f41-01a9-4243-bc3d-88c241d25037.png)

**Comment by yaomtc** [comment]
Here is the screen capture of the flickering. I wasn't able to reproduce the flickering of the "section of the top right" that I had a couple times before, but I did get the Print button to flicker, at least. https://www.youtube.com/watch?v=bAPsQobxHL4

If that other issue pops up again I'll try to capture it.

**Comment by yaomtc** [comment]
Not sure which directory you want me to run that command in exactly. I tried a few folders from building the package but no dice.

Here's the info from About.

```
Money Manager Ex
Version: 1.5.14 64-bit
• Build on May 16 2022 17:21:12
• Database version: 7 • (aes128cbc)
• Git commit: 29d21c327 (2022-04-14)
MMEX is using the following support products:
• wxWidgets 3.1.6 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.2.4
• lunasvg v2.0.1
• libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.23.1
• GNU Make 4.3
• GCC 12.1.0 • Arch rolling
Running on:
• Arch Linux "n/a"
• Linux 5.17.9-arch1-1 x86_64
• KDE English (United States) (UTF-8)
• 0x0 0bit 96x96ppi

```

**Comment by PMaff** [comment]
Just where you downloaded the mmex sources from github and there in moneymanagerex/build .
But I do guess, that you did not compile mmex from sources?
Can you try:
[Build instrcuctions also for Linux](https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md)

**Comment by yaomtc** [comment]
I should have specified that Arch Linux users build it from AUR: https://aur.archlinux.org/packages/moneymanagerex-git
![Screenshot_20220520_141611](https://user-images.githubusercontent.com/5534045/169588754-6dc6ce99-822f-4ee2-b834-924067e2ace5.png)

**Comment by MartinX3** [comment]
It works here

```
Version: 1.5.14 64-bit
• Aufbauend auf Apr 14 2022 18:48:33
• Datenbankversion: 7 • (aes128cbc)
• Git commit: 29d21c327 (2022-04-14)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.1.6 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.0.1
• libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
• gettext 0.21
• apexcharts.js
Genutztes Build:
• CMake 3.23.1
• GNU Make 4.3
• GCC 11.2.0 • EndeavourOS rolling 'rolling'
Läuft auf:
• EndeavourOS Linux "rolling"
• Linux 5.17.9-zen1-1-zen x86_64
• German (Germany) (UTF-8)
• 1280x720 24bit 96x96ppi
```

**Comment by PMaff** [comment]
I've heard that AUR seems to have some problems. @MartinX3 was posting about this.

On Manjaro I simply did it without AUR by compiling from the source and doing "make install" at the end.
But afair this was on X11 on a VM.
So I cannot tell about Wayland.

**Comment by MartinX3** [comment]
It works great @PMaff 
The problem was just that the wxwidgets 3.1.6 are globally installed and break any other application using wxwidgets, since it seems that only mmex uses the wxwidgets dev version.

**Comment by PMaff** [comment]
I am not sure if AUR was invoked also on my Manjaro VM. How can  I check this?

**Comment by yaomtc** [comment]
If you installed it from AUR, you will have a package installed called moneymanagerex-git. See if this returns anything.

`pacman -Q moneymanagerex-git`

**Comment by MartinX3** [comment]
`pacman` is not an AUR helper.
You need `paru`, `pamac` or `yay`.

Either you install the mmex package via these helpers like a system package or you clone the git of this package and `makepkg` in it.

Then it executes the build script which downloads, (compiles) and installs the software.

**Comment by yaomtc** [comment]
I know `pacman` is not an AUR helper. Those were instructions to see whether `moneymanagerex-git`, the version from AUR, is installed. `-Q` is query, while `-S` is sync/install.

**Comment by PMaff** [comment]
```
pacman -Q moneymanagerex-git
error: package 'moneymanagerex-git' was not found

pacman -Q makepkg
error: package 'makepkg' was not found

[pmaff@virtualmanjaro 1_5_14]$ pacman -Q paru
error: package 'paru' was not found
[pmaff@virtualmanjaro 1_5_14]$ pacman -Q pamac
pamac-gtk 10.3.0-6
[pmaff@virtualmanjaro 1_5_14]$ pacman -Q yay
error: package 'yay' was not found
```

I was only using the normal build description of mmex and doing a "make install" finally.
This installed mmex in
```
[pmaff@virtualmanjaro ~]$ which mmex
/usr/local/bin/mmex
```

**Comment by PMaff** [comment]
Maybe interesting for @MartinX3 :
https://github.com/moneymanagerex/moneymanagerex/issues/4255#issuecomment-1133322669

**Comment by PMaff** [comment]
Hmm, @yaomtc  I just see that you have  `0x0 0bit 96x96ppi` in your About.

**Comment by yaomtc** [comment]
Probably because I'm using Wayland.

**Comment by MartinX3** [comment]
@PMaff you showed us that you've got pamac installed, just use it to install mmex.

And the linked comment is about a different problem.
An enduser can't be forced to compile packages by himself just because mmex uses a not compatible dependency the other software uses as well.

**Comment by PMaff** [comment]
I did not use pamac to install mmex.
I simply did `make install` after compilation.
I think that is the main difference between our installations of mmex.

**Comment by MartinX3** [comment]
Between your `make install` and our `make DESTDIR="${pkgdir}" install`?

**Comment by PMaff** [comment]
Between your package installation via pamac (or similar) and my installation without pamac (or similar) but with `make install`.
But since your compilation process of mmex does not know about your self compiled wxWidget, I do assume,
that there is also a 2nd problem.

**Comment by MartinX3** [comment]
It just executes bash commands

**Comment by PMaff** [comment]
> Probably because I'm using Wayland.

Therefore I am just trying to set up a virtual machine with Manjaro, Plasma and Wayland.
;-)

**Comment by MartinX3** [comment]
Sounds a bit hard
Isn't it possible to choose between DE and display server in the login screen?

**Comment by PMaff** [comment]
> It just executes bash commands

Of course.
But somewhere in the config the pamac (or similar) seems to be refusing to accept a 2nd self compiled wxWidget,
and -as a 2nd problem- your compilation of mmex does not find that 2nd self compiled wxWidget.
At least that is what I read from your comments.

**Comment by PMaff** [comment]
> Sounds a bit hard Isn't it possible to choose between DE and display server in the login screen?

Not for manjaro-xfce-21.2.6-220416-linux515. There is no option to switch to Wayland on the login screen as
described here:
https://forum.manjaro.org/t/how-to-switch-to-wayland-wayland-does-not-work/104546

**Comment by yaomtc** [comment]
I haven't had flickering with any other software. I will test on GNOME (Wayland) and see if it happens there.

Also, XFCE does not support Wayland yet.

**Comment by PMaff** [comment]
That did not work in the virtual machine:
"Some major distributions will be switching to Wayland in the near future. Currently, the video driver included with the guest tooling does not support Wayland. Running a virtual machine results in a black screen after boot (with the correct resolution). "
https://www.virtualbox.org/ticket/13471

Sorry.

**Comment by yaomtc** [comment]
Also happens in GNOME (Wayland). I wonder if this is an issue between wxwidgets and Wayland? https://github.com/wxWidgets/wxWidgets/issues?page=1&q=is%3Aissue+is%3Aopen+wayland

**Comment by vomikan** [comment]
> I don't have other apps to test that use wxwidgets, and don't know of any. I could install one, any suggestions?

I think you could build wx demo file from scratch. 
https://docs.wxwidgets.org/3.0/page_samples.html

**Comment by yaomtc** [comment]
Ah, I see why you suggest that instead of [something else](https://wiki.wxwidgets.org/Project_List) like Audacity (which I actually _did_ have installed)... because I can't run Audacity or Filezilla with the -dev versions of wxgtk, apparently. Great.

**Comment by yaomtc** [comment]
I think I will just stick to using this on Ubuntu on my work computer for now

**Comment by PMaff** [comment]
Invested some time and installed Virtual Box 6.1.34, then I could switch to Wayland in Plasma.
```
loginctl show-session 2 -p Type   
Type=wayland
```
showed that wayland is used.
Compiled wxWidget 3.1.6 and installed it with make install

Afterwards mmex - I checked the latest trunk version:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.15-Beta.2
-- Commit         : 3461a5df4 (2022-05-21)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    :  
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
--  
-- Versions
-- --========--
-- Linux 5.15.38-1-MANJARO
-- ManjaroLinux 21.2.6 'Qonos'
-- CMake 3.23.1
-- GNU Make 4.3
-- ccache 4.6
-- GNU 11.2.0
-- wxWidgets 3.1.6
-- wxSQLite3 4.6.0
-- RapidJSON 1.1.0
-- Lua 5.2.4
-- curl 7.83.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done
```

after the normal build with cmake simply one more with make and at the end `make install`
mmex is in the Office menu then but the icon is missing.
But short test with mmex did not show any flickering or missing menus with English setup.
Switched to Hebrew as language, also no flickering or missing menus.

What might still be the case: that Virtualbox and Wayland behaves different than a non virtual machine.
Did you try to compile a demo for wxWidget 3.1.6 ?
Maybe this helps:
https://bugzilla.redhat.com/show_bug.cgi?id=1925903

**Comment by PMaff** [comment]
auidemo of wxWidget 3.1.6 also works without any flickering.

**Comment by yaomtc** [comment]
I could not remember how to compile code without makepkg and a PKGBUILD, so I found [their instructions](https://wiki.wxwidgets.org/Compiling_and_getting_started)... but the next step is "sudo make install". This is going to install files into root, isn't it? How would I clean this up afterwards? It would be easier if there were a wxWidgets-git package on AUR, but there is not.

**Comment by MartinX3** [comment]
@yaomtc there is
Look at the moneymanagerex-git air package dependencies

And yes, the clean way is the aur package.

**Comment by yaomtc** [comment]
Oh, wxgtk3 *is* wxWidgets? Didn't realize, thanks

**Comment by yaomtc** [comment]
So the code in /src/samples/ doesn't actually get compiled, which makes sense, I guess I have to make another PKGBUILD for that. I'll figure that out later

**Comment by PMaff** [comment]
> I could not remember how to compile code without makepkg and a PKGBUILD, so I found [their instructions](https://wiki.wxwidgets.org/Compiling_and_getting_started)... but the next step is "sudo make install". This is going to install files into root, isn't it? How would I clean this up afterwards? It would be easier if there were a wxWidgets-git package on AUR, but there is not.

This should install into /usr/local , not into /root
To remove that it is as simple as a "sudo make uninstall" then.
The only problem that remains, is, that the AUR package installers install wxWidget 3.1.5 or 3.1.6 into
the (wrong) directory of released software,
whereas the version 3.1.5 and 3.1.6 of wxWidget are not released software, which makes other programs fail afterwards.
See https://github.com/moneymanagerex/moneymanagerex/issues/4255

**Comment by whalley** [comment]
@avma @PMaff  Is this still an issue with the Linux builds?

**Comment by yaomtc** [comment]
Just compiled and installed from AUR, works well again for me.
