### ISSUE TITLE
the scroll bar flickers

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3223]
I test each new version on my 3 screens.
Since the last MMEX versions, MMEX no longer starts on the screen on
which it was last closed.
MMEX starts on the screen (landscape, 1920x1080) defined for the main
Windows display.

Because the graphics are not displayed as large (normal size) on the
screen (portrait format, 1080x1920), I move them there.  If I now select
Categories/Summary, the scroll bar flickers, it appears and disappears
and MMEX is dead. We already had this effect when the old master.css was
still interfering.

I am also moving to the third screen (landscape format, 3840x2160) as a
test, here there is only the problem that the graphics are even larger /
dominant.

Greetings @renato-mmex 
#2877

**Comment by vomikan** [comment]
I can't reproduce this issue with single monitor in portrait mode 1400x3440

**Comment by vomikan** [comment]
Related issue? https://github.com/apexcharts/apexcharts.js/issues/2070

**Comment by renato-mmex** [comment]
I made a video of it, see enclosure.
Greetings Renato

Am 10.04.2021 um 12:34 schrieb Nikolay:

**Comment by vomikan** [comment]
> I made a video of it, see enclosure. Greetings Renato Am 10.04.2021 um 12:34 schrieb Nikolay:

Please, upload file or provide the link.

**Comment by whalley** [comment]
@renato-mmex That layout looks very odd. I see you have the home page still visible in the background of the report view. Also the pie chart does not seem to be displaying!

**Comment by renato-mmex** [comment]
Hello Mark

That is really strange.
I turned my main screen and MMEX made the same mistake.
Then, with the "Category/Summary" selection started, I pushed the MMEX 
window more and more together and suddenly the error occurred.
This happens exactly the same with all graphics.

Greetings Renato

Am 10.04.2021 um 19:36 schrieb Mark Whalley:

**Comment by vomikan** [comment]
No matter how hard I try, I can't reproduce this problem.

![Uploading image.png…]()

**Comment by whalley** [comment]
I spotted some 'funnies' with overflow handling whist testing the latest ApexCharts... be interesting to see if this change fixes this flickering issue... No promises!

**Comment by vomikan** [comment]
Seems this issue fixed.
