### ISSUE TITLE
Organize Attachments dialog refers to internal account number instead of actual account name

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3226]
MMEX version:
 - [x] 1.5.0 RC2

Operating System:
 - [x] Windows
 - [ ] Mac OSX  Not tested
 - [ ] Linux Not tested

# Description of the bug

The Organize Attachments dialog refers to an internal account number instead of the actual account name when viewing the list of attachments for an account.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Right click on an account in the Navigation tree and select Organize Attachments.
or
2. Right click on an account in the Navigation tree and select Edit Account and then click the Organize Attachments (paper-clip icon) on the Edit Account dialog.

Expected result:

The Organize Attachments dialog should show the name of the account in the title bar.

Actual result:

The Organize Attachments dialog shows an internal account number, which has no meaning for the user.

# Additional information

See highlighted text in the screenshot.

![image](https://user-images.githubusercontent.com/4060092/114282842-428b3000-9a3e-11eb-9e3e-220fe0db6e0b.png)

**Comment by whalley** [comment]
Organize Attachments is called from many places - accounts, assets, bill deposits, ...
I  suggest we add a reference name that the caller must supply alongside the RefID, so change

`mmAttachmentDialog(wxWindow* parent, const wxString& RefType, int RefId, const wxString& name = "mmAttachmentDialog");`

to 

`mmAttachmentDialog(wxWindow* parent, const wxString& RefType, int RefId, const wxString& RefIDName, const wxString& name = "mmAttachmentDialog");`

So in the case mentioned in the issue we pass the account name in RefIDName.

**Comment by gabriele-v** [comment]
@whalley IMHO the approach here is wrong. You already have ref type and refid, you can get the refname inside attachment dialog without any other parameters which lead to confusion and it's unclear where they are used/required

**Comment by whalley** [comment]
> @whalley IMHO the approach here is wrong. You already have ref type and refid, you can get the refname inside attachment dialog without any other parameters which lead to confusion and it's unclear where they are used/required

Good point, that is more efficient. Must admit I did not think further than my suggestion from April last year given that there had not been further comment, and just implemented, I'll revert this change and update.

**Comment by whalley** [comment]
@tactilis Does this now look OK Martin?

**Comment by tactilis** [comment]
> Does this now look OK Martin?

Yes, it does thanks.

Sorry for the late response, I was away...    getting married :tada:
