### ISSUE TITLE
Reallocate Payees

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#3238]
This has been an issue for a year or so. I keep a copy of an older MoneyManager Ex just to run this feature as this now takes forever to get the dialog boxes up. If you decide to terminate it the whole program crashes. Can't say I am a fan of the new icons either.

MMEX version:
 - [x] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Reallocate Payee goes away for a long time. Older versions worked as quick as a mouse click! (aka Version 1.2)

Please describe your issue with details. Slow to the point it's locked up
Add screenshot or other files if needed.
This is what Version 1.2 did and worked well!
![Reallocate payee](https://user-images.githubusercontent.com/14268231/114384411-d4757300-9bcd-11eb-8847-56979749b4d7.JPG)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Organize Payees 
2. ReAllocate Payee (by right mouse click)
3. Lock up!

…

Expected result: Should work

Actual result: Doesn't
![Payee Error](https://user-images.githubusercontent.com/14268231/114384733-43eb6280-9bce-11eb-9823-03709d3c65db.JPG)

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
I can't reproduce his issue.

PS There are 4 sets of icons. 
![image](https://user-images.githubusercontent.com/6836805/114450954-55893600-9bdf-11eb-817f-56b9896be556.png)

**Comment by SJK55** [comment]
Is the issue of hang time the number of Payee's or the actual database as my database is 7.8M. Not sure of number of payees however.
I did a test today and it will eventually come up but takes about 1 minute and 7 seconds for Dialog box to appear. ( I suppose I thought it was never coming up, which is why I clicked cancel and it bombed?) In today's world over a minute is a long time!
Conversely open the exact same database (size being 7.8M) with version 1.2, the re-allocate payee takes 2 seconds max! Something has changed from previous version where it worked in an instant. (almost) . Bug or algorithm fail, not sure.
PS Thanks for the tips regards the icons. Great!

**Comment by vomikan** [comment]
1.2.0 source code:
```
    cbSourcePayee_ = new mmComboBox(this, wxID_ANY, ""
        , true //payee mode
        , wxDefaultPosition, btnSize);
    cbSourcePayee_->setSelection(sourcePayeeID_);

    cbDestPayee_ = new wxComboBox(this, wxID_NEW, ""
        , wxDefaultPosition, btnSize
        , Model_Payee::instance().all_payee_names());
    cbDestPayee_->AutoComplete(Model_Payee::instance().all_payee_names());
```
1.5.0
```
    cbSourcePayee_ = new wxComboBox(this, wxID_BOTTOM
        , sourcePayeeID_ == -1 ? "" : Model_Payee::get_payee_name(sourcePayeeID_)
        , wxDefaultPosition, btnSize
        , Model_Payee::instance().used_payee_names());
    cbSourcePayee_->AutoComplete(cbSourcePayee_->GetStrings());
    cbSourcePayee_->Enable();
    cbSourcePayee_->Connect(wxID_ANY, wxEVT_TEXT, wxCommandEventHandler(relocatePayeeDialog::OnPayeeChanged), nullptr, this);


    cbDestPayee_ = new wxComboBox(this, wxID_NEW, ""
        , wxDefaultPosition, btnSize
        , Model_Payee::instance().all_payee_names());
    cbDestPayee_->AutoComplete(cbDestPayee_->GetStrings());
    cbDestPayee_->Connect(wxID_ANY, wxEVT_TEXT, wxCommandEventHandler(relocatePayeeDialog::OnPayeeChanged), nullptr, this);
```

**Comment by vomikan** [comment]
@SJK55 could you help with this issue?
I neen more info.
1)  What kind of the CPU of you PC?
2) What is the RAM capacity?
3) If you start the dialog untill Dialog box to appear what is thr CPU and memory usage? (Press Ctrl + Shift + Esc)
4) how many payees?
  Tools - General Report Manager; Right Click Mouse - on the root item - New empty report; OK OK; SQL
  ```select count(*) from PAYEE_V1``` 
  Test button

**Comment by SJK55** [comment]
Hi thanks for following this up These are results from MMEX Version 1.5.0 64 bit
1. Processor is Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.20 GHz
2. Ram Capacity is 8.00 GB (7.88 GB usable)
3. Power Usage Very High Status Not Responding (I've attached an image to assist)
4. 3635 Payees.
![CPU Memory etc](https://user-images.githubusercontent.com/14268231/114540224-6d6ec180-9c94-11eb-9472-612c949a078f.JPG)

Same tests with same base data (database) but running MMEX Version 1.2.0
1. Same
2. Same
3. See attached Image but response was very quick of course!
![Old MMEX](https://user-images.githubusercontent.com/14268231/114540858-2f25d200-9c95-11eb-9b3b-213fd15fa0b4.JPG)
4. Same (ie 3635 Payees)

If you want more info please ask.

**Comment by vomikan** [comment]
7745 payees.

I managed to get a delay of 4 seconds

![image](https://user-images.githubusercontent.com/6836805/114546702-28cc3180-9c66-11eb-8c2f-c2d3f8487cf4.png)

**Comment by vomikan** [comment]
I've found the bottle neck.
```
    cbSourcePayee_->Append(Model_Payee::instance().used_payee_names()); // this is performance killer. Running 20 sec DEBUG mode
    cbSourcePayee_->Clear();
    cbSourcePayee_->Append(Model_Payee::instance().all_payee_names()); //Running 2 sec DBUG mode
    ```

**Comment by vomikan** [comment]
@SJK55 a bit later a build with the fix would be available.

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/38687033/job/puiu651comonuv5f/artifacts

**Comment by SJK55** [comment]
Thx!
