### ISSUE TITLE
Cashflow report error for negative total

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/moneymanagerex#3240]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [X] 1.5.0 64-bit

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows (portable edition, didn't test on installable version)
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

With new version 1.5 just download and installed, I notice that in CashFlow forecast the graph is showen in asbolute value instead of relative value. 

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Start from new file
2. set new bank account, set initial value to 5000
3. set new recurring montly transaction start from next month withdrawal 1000
4. Open Montly (and also on daily) CashFlow

…

Expected result:
total will be always decreese by 1000 every month and the graph show a line goes below zero

Actual result:
total will be always decreese by 1000 every month BUT the graph show a line goes down until zero and then grow up

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![image](https://user-images.githubusercontent.com/3205448/114406861-2a372480-9ba8-11eb-9ceb-e6af4a2f414b.png)

**Comment by whalley** [comment]
Good spot. The same bug actually manifests itself on the budgets category summary. Fix identified.

Thankfully my cashflow never went negative so never spotted this! :-)

**Comment by vomikan** [comment]
>Thankfully my cashflow never went negative so never spotted this! :-)
Lucky man ))
