### ISSUE TITLE
MMEX shows using libcurl v7.61 which currently has 17 vulnerabilties

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#3241]
MMEX version:
1.5

Operating System:
 - [x ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Hello,
Just bringing attention that MMEX currently shows using v7.61 of libcurl. v7.76 is the latest release. Currently, there are 17 vulnerabilities in v7.61: https://curl.se/docs/vulnerabilities.html

Thank you

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2681
https://github.com/moneymanagerex/moneymanagerex/issues/2714

**Comment by vomikan** [comment]
I have curl installed into C:\curl\
and dll file:
"C:\curl\build\lib\Release\libcurl.dll"

The task is copy the dll file into mmex build bin directory.

@whalley Perhaps you could implement such a fix? I don't understand CMAKE at all.

**Comment by whalley** [comment]
This change should pull the curl dll based on the CMAKE_PREFIX_PATH passed as below. The file will be copied to the install\bin directory.

```
mkdir c:\projects\mmex\build
cd c:\projects\mmex\build
set "PATH=%PATH%;%DevEnvDir%CommonExtensions\Microsoft\CMake\CMake\bin"
cmake -G "Visual Studio 15 2017" **-DCMAKE_PREFIX_PATH=c:\libcurl** ..
```

**Comment by whalley** [comment]
**Still a few funnies with Appveyor build**

**Comment by whalley** [comment]
Should now cope when the .dll is not present, e.g. when option used but static binding or other reason.

**Comment by whalley** [comment]
What is stopping us updating the `.appveyor.yml` file to pickup a later version of curl?

**Comment by vomikan** [comment]
You need to know the correct syntax with paths and the correct edit location in this file.

**Comment by whalley** [comment]
Builds, installs, and runs with latest curl library. Library in installer and portable ZIP.
![CleanShot 2022-04-20 at 00 52 44](https://user-images.githubusercontent.com/487345/164119693-47e87f2a-03b0-4b68-89db-fd6953acba13.png)
