### ISSUE TITLE
Update wizard window not expanded correctly

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3244]
MMEX version:
 - [X] 1.5.0
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

When opening "Help / Check for Updates" from the application menu the following window is presented.
![image](https://user-images.githubusercontent.com/487345/114425016-9158d700-9bb0-11eb-8fd2-d918f4fc92b9.png)

as soon as you attempt to expand the window it sizes correctly.

![image](https://user-images.githubusercontent.com/487345/114425315-dda41700-9bb0-11eb-8d50-aef2c08b2413.png)

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by vomikan** [comment]
GetSizer()->Fit(this);
or
Fit();
I think so.
