### ISSUE TITLE
Cash flow->Daily View inaccurate graph, weird cash flow->monthly

### ISSUE THREAD

**Issue by Enkhist** [moneymanagerex/moneymanagerex#3249]
It appears that in the cash flow->Daily view, the visual graph doesn't draw negative values correctly. It appears to show the absolute value of my accounts when i include my credit card with a negative balance.
Cash flow->monthly seems odd altogether and I can't understand how it arrives to different values.

<hr>Version: 1.5.0 64-bit<br>
 • Build: Apr 11 2021 18:19:20<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3240

**Comment by whalley** [comment]
A fix will be included in v1.5.1 for this.
