### ISSUE TITLE
Recalculate balances for non-default sorting

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#3251]
# Description of the feature
Currently Money Manager calculates balances based on the default order of transactions. If the user changes the order by clicking on a column or filters transactions, then the balances are no longer correct. 

The financial software I've used always recalculates the balances based on the current order. Showing incorrect balances for the current view undermines trust in the software (https://github.com/moneymanagerex/moneymanagerex/issues/2296) and confuses newcomers (https://github.com/moneymanagerex/moneymanagerex/issues/2617) and even [longer time users](https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10367). 

I don't know the performance impact of doing this. It may be that it isn't worth the cost to change (I love that Money Manager EX scrolls really fast compared to Quicken, GnuCash, and others). Or maybe the balance column is blank while Money Manager EX calculate the new balances in the background. 

# Workaround
For users confused by balances to displaying incorrectly, here's how to fix that: 

1. Choose **View All Transactions** > **View All Transactions** to clear any filters.
2. Choose the **ID** column header, then the **Date** column header, to sort by the default order. If the arrow on the Date column points down, choose the **Date** column header again to sort with the oldest transactions at the top.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2729

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3261
