### ISSUE TITLE
Assertion when clicking account link from homepage

### ISSUE THREAD

**Issue by Joker2k** [moneymanagerex/moneymanagerex#3260]
MMEX version:
- git master

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
 When clicking account link from homepage assertion thrown.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create checking account
2. From homepage click link

Expected result:
No assert

Actual result:

# Additional information

![image](https://user-images.githubusercontent.com/8383606/114663193-97f76380-9d02-11eb-9ab9-e283e95fd2d4.png)
![image](https://user-images.githubusercontent.com/8383606/114663099-70a09680-9d02-11eb-916d-e5003d668679.png)
![image](https://user-images.githubusercontent.com/8383606/114663111-77c7a480-9d02-11eb-9632-2eb5801dbddc.png)

**Comment by whalley** [comment]
That looks like a customer build you have there, e.g. older wxWidgets and libcurl from  what we are currently using in windows builds. Does the same issue occur with the builds available on AppVeyor?

**Comment by Joker2k** [comment]
Indeed upgrading wxWidgets to 3.1.4 solves problem
