### ISSUE TITLE
Just questions 

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#3262]
In an older version it was possible to display custom fields data in the account view as a seperate column.
Will this feature come back?

I'm using Version 1.5.0.
Do I have the opportunity to create my own themes now? 
If so, how can I integrate them?

Is the feature request #1919 still interesting or can I only handle it with an asset account?

**Comment by whalley** [comment]
See here for info on themes, though this work is still in development and some of the features will not be available until v1.6 where we have introduced a theme manager to help import and manage the themes. 

Hmmm, I've never really used customer fields, but don't remember us removing support for this in the transactions views... I will check.

**Comment by TomAff** [comment]
Maybe this was in Version 1.4. Didn't have a copy of this.

**Comment by whalley** [comment]
Yes, it was 1.4.x that had this feature. We have https://github.com/moneymanagerex/moneymanagerex/issues/1664 to track this now that 1.4.x is defunct. Will see if we can get it into 1.6.0

**Comment by whalley** [comment]
See also: https://github.com/moneymanagerex/moneymanagerex/issues/3105   for detail on themes
