### ISSUE TITLE
Add Share Transaction Not Updating Amount

### ISSUE THREAD

**Issue by sdtdt2** [moneymanagerex/moneymanagerex#3264]
MMEX version:
 - [x] 1.5.0
 - [ ] 1.3.7
 - [x] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Add Share Transaction screen does not update the Amount field after updating the number of shares and current price fields.  This causes the share to be logged as 0 amount.  This seems to be tied to #2497 which shows as being closed in 1.3.5 but does not work in 1.3.6 and beyond.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click on an active stock
2. Click on Add Trans button
3. Update the Share Number
4. Update the Share Price
5. Click anywhere else
6. Review Amount Field

Expected result:
Amount field should be updated with the Number of Share x the Share Price (i.e. 2 x 150 = 300)

Actual result:
Amount field remains at 0

# Additional information

**Comment by vomikan** [comment]
It seems OK for now

![image](https://user-images.githubusercontent.com/6836805/115955565-e5907f00-a4ff-11eb-9108-60c30f2da8ed.png)

**Comment by sdtdt2** [comment]
The Edit Share Transaction screen seems to work fine.  Here is the Add Share Transaction screen with the Amount set to 0.
![Add_Trans_Broken](https://user-images.githubusercontent.com/82537656/116162402-b6c30600-a6c3-11eb-9303-bb03b9b90d3e.png)

**Comment by whalley** [comment]
Was fixed by this: https://github.com/whalley/moneymanagerex/commit/c2d075a9f2ffbdf79f36dd2b20e87e7f4c2b700e
