### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3265]
>In an older version it was possible to display custom fields data in the account view as a seperate column.
Will this feature come back?

https://github.com/moneymanagerex/moneymanagerex/issues/3262

**Comment by whalley** [comment]
In the transaction view the user specified names should use the field names and not the UDFC01..05 labels.

![image](https://user-images.githubusercontent.com/487345/114934641-10107700-9e32-11eb-925a-1e68f9063a23.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3299
