### ISSUE TITLE
add user color to recurring transactions

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#3267]
In the accountview 
![2021-04-15 09_01_48-Window](https://user-images.githubusercontent.com/46572503/114827797-6bf2e580-9dc9-11eb-85bd-ce5311600776.jpg)

In the recurring transaction view the field is missing.
![2021-04-15 09_01_32-Window](https://user-images.githubusercontent.com/46572503/114827793-6ac1b880-9dc9-11eb-9aba-6ecc6c9d4edc.jpg)

**Comment by whalley** [comment]
This is a good suggestion, I like it.

**Comment by whalley** [comment]
I would have expected the color of the transaction in the recurring transaction view to also be displayed in the selected color alongside recording them in the posted transactions.

**Comment by vomikan** [comment]
It would be next step.

**Comment by TomAff** [comment]
"This is a good suggestion, I like it." 
I have many suggestions :)

**Comment by whalley** [comment]
> "This is a good suggestion, I like it."
> I have many suggestions :)

But are they all 'good' :-)

**Comment by TomAff** [comment]
Some of them :)

I'm Head of accounting department and use MMEX since 2013 for my privat financials.
I am programming in PHP. So I know accounting and programming.
But I don't know how much work it is to realize my ideas in visual studio.
It is not my intension to give you much work just that the MMEX works the way I like to use it. :)
