### ISSUE TITLE
Update to wxWidgets 3.1.5

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3273]
# Description of the feature

wxWidgets 3.1.5 has been released. We should upgrade code-base to use this.

https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.5

**Comment by vomikan** [comment]
```
diff --git a/src/mmex.cpp b/src/mmex.cpp
index bd67b301..fe6de99e 100644
--- a/src/mmex.cpp
+++ b/src/mmex.cpp
@@ -32,6 +32,7 @@
 #include <wx/fs_arc.h>
 #include <wx/fs_filter.h>
 #include <wx/fs_mem.h>
+#include <wx/log.h>
 #include <wx/mstream.h>
 #include "../resources/money.xpm"
  //----------------------------------------------------------------------------
@@ -169,7 +170,7 @@ bool mmGUIApp::OnCmdLineParsed(wxCmdLineParser& parser)
 /*
     See also: wxStackWalker, wxDebugReportUpload.
 */
-void mmGUIApp::ReportFatalException(wxDebugReport::Context ctx)
+bool mmGUIApp::ReportFatalException(wxDebugReport::Context ctx)
 {
     // TODO email it or upload it
     wxDebugReportCompress report;
@@ -187,6 +188,7 @@ void mmGUIApp::ReportFatalException(wxDebugReport::Context ctx)
     if (preview.Show(report) && report.Process()) {
         report.Reset();
     }
+    return true;
 }
 /*
     This method allows catching the exceptions thrown by any event handler.
diff --git a/src/mmex.h b/src/mmex.h
index 0b8347d0..20053e69 100644
--- a/src/mmex.h
+++ b/src/mmex.h
@@ -52,7 +52,7 @@ private:
     wxString m_optParam2;
     bool m_optParamSilent;
     wxSQLite3Database* m_setting_db;
-    void ReportFatalException(wxDebugReport::Context);
+    bool ReportFatalException(wxDebugReport::Context);
     bool OnInit();
     int OnExit();
     void OnFatalException(); // called when a crash occurs in this application

```

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/114936410-12c89780-9e45-11eb-8f52-8d0ef6a8063b.png)

![image](https://user-images.githubusercontent.com/6836805/114936441-1bb96900-9e45-11eb-85f0-41204661c8ad.png)

**Comment by whalley** [comment]
I think that `ReportFatalException(wxDebugReport::Context)` **should** return `void` it looks as if the return is wrong.

```
if (!report.IsOk())
{
    return wxSafeShowMessage(mmex::getProgramName()
        , _("Fatal error occured.\nApplication will be terminated."));
}
```

should be 
```

 if (!report.IsOk())
 {
      wxSafeShowMessage(mmex::getProgramName()
          , _("Fatal error occured.\nApplication will be terminated."));
 }
```

I don't get any Debug Alerts on MacOS, or have not encountered any at present...

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/116695557-75836c80-a9c9-11eb-8c86-b2b63d96536a.png)

**Comment by vomikan** [comment]
#3101

**Comment by whalley** [comment]
Removed reliance on wxNumberFormatter - should also help with currency locale issues.
https://github.com/whalley/moneymanagerex/commit/5c7d5d61379cf97f814ef3518730653b45af7338

**Comment by vomikan** [comment]
It seems the troble in  wxString::FromCDouble function
![image](https://user-images.githubusercontent.com/6836805/116858856-be286900-ac07-11eb-9e33-898d9ef6ac7d.png)

![image](https://user-images.githubusercontent.com/6836805/116858972-edd77100-ac07-11eb-816f-5a2c4b1c04c2.png)

**Comment by whalley** [comment]
Seems a windows thing... What Locale is reported in MMEX/About ?

**Comment by whalley** [comment]
Looking at the wxWidgets code for FromCDouble() iit seems there are a few workarounds in there with it converting to the current locale then trying to convert to clocale.

For this we already handle a FromCDouble like function in htmlbuilder.cpp, so I wonder if we added the below to use instead?

```
wxString mmFromCDouble(double v)
{
    std::ostringstream oss;
    oss.imbue(std::locale::classic());
    oss << v;
    return oss.str();
}
```
I note that the wxWidgets code talks about potential issues on some systems with imbue but have not seen any reports that the code in htmlbuilder.cpp does not work?

Views?

**Comment by vomikan** [comment]
I've added  wxLocale(wxLANGUAGE_ENGLISH);
```
mmGUIApp::mmGUIApp() : m_frame(nullptr)
, m_setting_db(nullptr)
, m_optParam1(wxEmptyString)
, m_optParam2(wxEmptyString)
, m_optParamSilent(false)
, m_lang(wxLANGUAGE_UNKNOWN)
{
    wxLocale(wxLANGUAGE_ENGLISH);
#if wxUSE_ON_FATAL_EXCEPTION
    // catch fatal exceptions
    wxHandleFatalExceptions(true);
#endif
}

```

It fixed warnings. 

I'm trying to apply fmt to simplify the code. This library is also not a gift.
