### ISSUE TITLE
Money Manager EX Update not working on MacBook

### ISSUE THREAD

**Issue by AndyF1955** [moneymanagerex/moneymanagerex#3278]
The Update Wizard links to GitHub but there is no download button and even the website download page fails to update MacBook running Big Sur 11.2.3 - This needs to be rectified and be mindful of a layman like me who needs it nice and simple

**Comment by vomikan** [comment]
https://sourceforge.net/projects/moneymanagerex/files/v1.5.0/

**Comment by vomikan** [comment]
It seems abig button should be added kike this one:
![image](https://user-images.githubusercontent.com/6836805/115042228-f4fa4180-9edb-11eb-9873-58c8a4f1090b.png)

**Comment by AndyF1955** [comment]
Yes I agree, In Mac the update screen doesn't show this link, it takes you to a screen that lists the updates and invites a "Finish" to complete the download but this also does not update the files and won't run.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3244
