### ISSUE TITLE
Money Manager Ex Update Wizard not working in Mac OS Big Sur 11.2.3

### ISSUE THREAD

**Issue by AndyF1955** [moneymanagerex/moneymanagerex#3279]
MMEX version:
 - [ ] 1.14.0 Alpha 6
 - [ ] 1.15.0

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Mac OSX Big Sur 11.2.3

# Description of the bug

Update Wizard Finish Button links to GitHub page with no download button.
A Click on the new version in blue 1.15.0 downloads mmex v15.0 macOS.2020.04.12.dmg
Icon dragged to Applications folder to replace previous
Dialogue that will not run and requesting debug file

# Reproduction

Is the bug reproducible? 
 Always

Apologies I inadvertently closed previous post

Enhancment request for clear download button

Debug Request for seamless version update

**Comment by whalley** [comment]
Not sure what extra is required here....

When I start 1.3.6. I get -
<img width="758" alt="image" src="https://user-images.githubusercontent.com/487345/115095189-3ad4fb00-9f18-11eb-8fea-faf736dac0ea.png">

If I click on the 1.5.0 link I get - 
![image](https://user-images.githubusercontent.com/487345/115095223-63f58b80-9f18-11eb-8e54-5624143a0d3e.png)

once downloaded and installed it works fine.

It seems that @AndyF1955 is starting from 1.4.x in which case the actions identified here: https://github.com/moneymanagerex/moneymanagerex/issues/2353 need actioning.

@AndyF1955 - Can you please advise if the above is correct.

**Comment by AndyF1955** [comment]
Hello. Yes I was starting from 1.4, but unable to run db downgrade file in Mac - Im sorry I'm user end rather than technical. I can still run 1.4 if I leave upgrade alone. Seems from reading 1.5 is a non starter for time being

**Comment by whalley** [comment]
@AndyF1955 Have you followed the instructions here: https://github.com/moneymanagerex/moneymanagerex/issues/2353 if so what failed?

**Comment by AndyF1955** [comment]
I am not able to run the zip file. Mac doesn’t know what program to use to run it. Frustrating

Kind Regards

Andy Fuller
________________________________

**Comment by whalley** [comment]
Use this file - https://drive.google.com/file/d/1Wtuu_2X5edL1WJf3_Q9qiI4rmmXJPXJP/view?usp=sharing

**Comment by AndyF1955** [comment]
I probably need a step by step process as Mac has no application to open file.

It’s more than a little frustrating that when Ive bought a perpetual license this sort if stuff happens.

Hope someone os able to give me a step by step process to resolve as that’s going to be helpful for the majority of front end users like me

Thanks in anticipation

**Comment by whalley** [comment]
> It’s more than a little frustrating that when Ive bought a perpetual license this sort if stuff happens.

Firstly, the software is not licensed, it is free open-source. Where did you 'buy' the license from?

> Hope someone os able to give me a step by step process to resolve as that’s going to be helpful for the majority of front end users like me

If you follow the steps here https://github.com/moneymanagerex/moneymanagerex/issues/2353 but ignore the first step as you can use the debug file here:  https://drive.google.com/file/d/1Wtuu_2X5edL1WJf3_Q9qiI4rmmXJPXJP/view?usp=sharing it should work.

**Comment by AndyF1955** [comment]
I can’t find the details novas it was a couple of years ago, when I used to run the PC Version and was referred to this “Sister program” which was when I downloaded Money Manager which has worked very well until this latest upgrade.

At the moment I have the program running but will try and piece together the process as you set out.

**Comment by AndyF1955** [comment]
I can’t replicate the steps.

Running Debug from within Tools, returns Debug Error, SQL Logic Error [1] incomplete input

Thanks for trying to help

**Comment by whalley** [comment]
Is your DB encrypted? If so, try decrypting and trying again.

**Comment by whalley** [comment]
@AndyF1955 Did the above help solve the problem, if so we can close the issue.

**Comment by AndyF1955** [comment]
Hi Mark, I’m away from home at the moment and will look later on.

Kind Regards

Andy Fuller
________________________________

**Comment by AndyF1955** [comment]
HI,

My database is not encrypted as far as I can see and not compressed.

I just can’t seem to get from 1.4.0 Alpha 6 to any new version.

Update Wizard box takes me to download a file which when opened is 64 bit

Im afraid Im no tech so I need a bit of hand holding, the only thing working for me is 1.4.0 Alpha 6

**Comment by whalley** [comment]
OK, let's step back a little....

1.  Have you downloaded and installed the v.1.5.1 MacOS version here?  https://sourceforge.net/projects/moneymanagerex/files/v1.5.1/mmex%20v1.5.1-macOS.2021.04.24.dmg/download

**Comment by AndyF1955** [comment]
Hello,

Yes and Ive repeated it, followed by trying to open the last opened Database.

I then got this :

**Comment by whalley** [comment]
> I then got this :

Are you missing a screenshot?

**Comment by AndyF1955** [comment]
Do you get it now?

The MMEX Database upgrade came up first and the MMEX upgrade debug request came second

**Comment by whalley** [comment]
No, can't see any screenshot.

What happens if you download https://www.ipx.co.uk/mmex/downgrade_db_13_7_v4.mmdbg
and use this file as input to the upgrade prompt?

**Comment by AndyF1955** [comment]
Hi Mark,

Yes that worked a treat and now showing as up to date version.


Many Many thanks!

Best wishes
