### ISSUE TITLE
Cash Flow/Daily loops and locks up

### ISSUE THREAD

**Issue by marty008** [moneymanagerex/moneymanagerex#3281]
Select Daily within Cash Flow. Doesn't (as per previous version) come up with selection box to select accounts. Defaults to, I suspect, accounts used in last select on previous version. Graphical representation shows values ok but sliders (horiz and vert) are flashing, and program is locked.  Have to end Task in Task Manager. On mmex reload , says that d/b is marked open by another instance. When say no to continue, offers to open last d/b, and starts again. Bug reproducable. D/b size 909kb with 6443 transactions.  Please note I do not want to publish snapshot

<hr>Version: 1.5.0 64-bit<br>
 • Build: Apr 11 2021 18:19:20<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1536x864 32bit 96x96ppi

**Comment by whalley** [comment]
Can you please clarify what your previous version was?

**Comment by marty008** [comment]
Hi I believe it was 1.3.2Sent from my Galaxy
-------- Original message --------From: Mark Whalley ***@***.***> Date: 17/04/2021  02:13  (GMT+01:00) To: moneymanagerex/moneymanagerex ***@***.***> Cc: marty008 ***@***.***>, Author ***@***.***> Subject: Re: [moneymanagerex/moneymanagerex] Cash Flow/Daily loops and locks up (#3281) 
Can you please clarify what your previous version was?

**Comment by vomikan** [comment]
It may be the same bug
https://github.com/moneymanagerex/moneymanagerex/issues/3223

**Comment by marty008** [comment]
Hi Nikolay. Yes, your video looks like my problem.I do not use the pie chart but the graphical display, but the border flashing is identical.RegardsMartinSent from my Galaxy
-------- Original message --------From: Nikolay ***@***.***> Date: 17/04/2021  19:01  (GMT+01:00) To: moneymanagerex/moneymanagerex ***@***.***> Cc: marty008 ***@***.***>, Author ***@***.***> Subject: Re: [moneymanagerex/moneymanagerex] Cash Flow/Daily loops and locks up (#3281) 
It may be the same bug
#3223

**Comment by whalley** [comment]
@marty008  Can this be closed now?  Is the problem still present.

**Comment by marty008** [comment]
Hi Mark, yes thank you Keep up the good workMerry Christmas to all of the teamMartinOn 14 Dec 2021 20:24, Mark Whalley ***@***.***> wrote:
@marty008  Can this be closed now?  Is the problem still present.
