### ISSUE TITLE
Database Downgrade and Application Update Bug?

### ISSUE THREAD

**Issue by MarcusGHub** [moneymanagerex/moneymanagerex#3294]
MMEX version:
 - [X] 1.5.0
 - [ ] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
After updating my copy of the application from 1.4.0-alpha.7 to 1.5.0 and downgrading the database from version 13 to 7 (via https://github.com/moneymanagerex/moneymanagerex/issues/2353), I have noticed 2 changes without one possibly being a bug: budget list layout, RR status transactions and budget date offset option.

**1.** In the screenshot below, that is how all my budgets are arranged. That's the new hierarchy. Is this a bug as a result of the updated application and database conversion?

![Screenshot - Budget Hierarchy Layout](https://user-images.githubusercontent.com/8460723/115219775-71a04200-a0cd-11eb-86c7-ecfbcecfb2e6.jpg)

**2.** Also after the changed, I noticed all my Transfer transactions have changed from the Reconciled (R) status to the RR status. Was I adding the wrong status for my transfers all along? What is the RR status and how do I even add it? 

**3.** After said update and downgrade, there was once a feature that was implemented to offset budget dates as per this issue thread (https://github.com/moneymanagerex/moneymanagerex/issues/1292). The feature is now gone. Was this removed from this application version?

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by MarcusGHub** [comment]
> Hello.
> Thank you for your report.
> 
> The 1.5.0 is improuvment 1.3.6 release. The 1.4.x will not develop. We want users to leave this version of the app, so the numbering has been upgraded to 1.5.0.
> 
> 1. it seems OK for me.
The feature works as it should, however, the layout where 2021-04, 2021-05... are all expandable from 2021-03. Not sure why that is. 

> 2. RR status not available in DB ver. 7 (It may be available in future)
Question: So I should mark all transfers as reconciled right?

> 3. #1292 seems easy to implenent for 1.5.1
Ok thank you. Looking forward to it.

**Comment by vomikan** [comment]
>The feature works as it should, however, the layout where 2021-04, 2021-05... are all expandable from 2021-03. Not sure why that is.

https://github.com/moneymanagerex/moneymanagerex/issues/2391

**Comment by MarcusGHub** [comment]
> > The feature works as it should, however, the layout where 2021-04, 2021-05... are all expandable from 2021-03. Not sure why that is.
> 
> #2391

Ok thank you

**Comment by MarcusGHub** [comment]
Confirming that point 3 in the original post has been re-implemented in version 1.5.1. Thank you.
