### ISSUE TITLE
Unable to add attachment on transaction creation

### ISSUE THREAD

**Issue by MarcusGHub** [moneymanagerex/moneymanagerex#3295]
MMEX version:
 - [X] 1.5.0
 - [ ] 1.3.7
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

![Attachment error](https://user-images.githubusercontent.com/8460723/115226433-d9a65680-a0d4-11eb-81af-e008b54552ed.jpg)

I get the error in the attachment above when I attempt to attach a file to my transaction while creating that transaction for the first time. It will only add after creating the transaction and editing the transaction.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Add a new transaction so that the new transaction window pops up.
2. Now without actually clicking OK to create the transaction, click the attachment icon so that you can attach a file.
3. Attach the file and click OK, then you will get the error.

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Cannot reproduce on MacOS.

**Comment by vomikan** [comment]
On the printscreen provided the path for transaction ID = -1
![image](https://user-images.githubusercontent.com/6836805/115259890-f4131b00-a13a-11eb-82b9-7fdd0484a85d.png)

I can't reproduce it.

**Comment by whalley** [comment]
Looking at the code there is some funny use of -1 in mmTransDialog::OnAttachments if the 'Duplicate' transaction action is used rather than 'New'. But I still don't get an error and the attachment is added.

**Comment by MarcusGHub** [comment]
How else can I assist here?
What should i do to help reproduce the error on your side?

I am using the portable version and the files are stored in One Drive that is synced to my laptop.

**Comment by vomikan** [comment]
We need step by step instractions how to reproduce this issue.

**Comment by MarcusGHub** [comment]
I interacted with the settings and I'm no longer seeing the error message.

The setting was not changed, which is strange.

Path: C:\Users\MarHutchy\OneDrive\Documents\FINANCE\MONEY MANAGER EX\Attachments
![Screenshot_1](https://user-images.githubusercontent.com/8460723/115881525-73417100-a411-11eb-9d91-bc480b7c9bb8.jpg)
