### ISSUE TITLE
Change "saved filters" from check points to Listbox

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3298]
![image](https://user-images.githubusercontent.com/6836805/115309408-e8444a80-a174-11eb-8215-c5eb72b1d0fc.png)

**Comment by TomAff** [comment]
The listbox is no longer available?

**Comment by whalley** [comment]
Yss, still there...
![CleanShot 2022-10-11 at 20 05 05](https://user-images.githubusercontent.com/487345/195177571-aad04d33-f340-4299-9b74-ccc7c0db96b6.png)

**Comment by TomAff** [comment]
But Not in the Account view?!

**Comment by whalley** [comment]
> But Not in the Account view?!

Nope, we just save the advanced filter settings for the account.
