### ISSUE TITLE
Customfielddata will not be delete.

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#3299]
MMEX version: 1.5
Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

By uncheck the customfield, the data will not be deleted in customfielddata_v1

![2021-04-21 12_23_56-Window](https://user-images.githubusercontent.com/46572503/115538983-bd551600-a29c-11eb-8d09-92ababd3a4da.jpg)

**Comment by gabriele-v** [comment]
Hi @vomikan why you have removed RegEx validation and "Now" for Date and Time that were working properly?

**Comment by vomikan** [comment]
> Hi @vomikan why you have removed RegEx validation and "Now" for Date and Time that were working properly?

I've integrated the code from 1.4.x branch. There are probably errors there.

**Comment by gabriele-v** [comment]
> I've integrated the code from 1.4.x branch. There are probably errors there.

So why not fix them? In this way you are definitely loosing some function that was there and no one will think about adding them again

**Comment by vomikan** [comment]
I gona fix that. Please be patient. Thanks you pointing this.

**Comment by gabriele-v** [comment]
No problem, it was just to don't lost the code, maybe just comment it out
