### ISSUE TITLE
Change CSV/XML Import and Export saved template names from radio buttons to listbox

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3314]
# Description of the feature

In #3298 @vomikan has made a very welcome change to the Transaction Filter dialog to switch the Saved Settings from using numbered radio buttons to using named presets in a listbox.

This feature request is for the same type of change to be applied to the CSV/XML Import and Export dialogs.

# Use cases

The justification for this change is improved usability.

Current dialog:
![image](https://user-images.githubusercontent.com/4060092/115789886-c1c52000-a3bd-11eb-85a0-ce866816d534.png)

At present, I have 8 different accounts for which I import CSV files. Each account has a different CSV file format, so I have 8 named templates denoted by the numbered radio buttons.

I have to try to remember which radio button I need to click to load the settings for a particular named account. If the setting names were shown in a listbox (like #3298) then the correct setting to select would be obvious.

**Comment by tactilis** [comment]
For the reasons stated in the original post, this enhancement is still valid. Please could you remove the `stale` label.

**Comment by n-stein** [comment]
Can be closed, this was implemented in #5790.
