### ISSUE TITLE
moneymanagerex (Arch Linux) help files

### ISSUE THREAD

**Issue by shymega** [moneymanagerex/moneymanagerex#332]
In Arch Linux moneymanagerex (repo version) can't find the help files, instead displaying the error message shown [here](https://cloud.githubusercontent.com/assets/1334592/5578819/08e7168e-9027-11e4-9ab2-f9e847e90df5.png) 

The actual help files are actually stored in '/usr/share/doc/mmex/help', so my solution was to run the command: sudo ln -s /usr/share/doc/mmex/help /usr/share/mmex/help
to get moneymanagerex to see the help files.

It could be that the Arch repo version of moneymanagerex hasn't been updated for a while, and upstream may have already fixed this however I thought I'd open an issue nethertheless.

**Comment by guanlisheng** [comment]
I am going to close it soon and feel free to reopen it if needed
