### ISSUE TITLE
Date range filter with names like 'Financial Quarter 2'

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#3324]
# Description of the feature

Can the transaction filter have labelled date range dropdown?

![image](https://user-images.githubusercontent.com/10950385/115980113-8305b480-a5cd-11eb-89b0-11f23e90fafe.png)
![image](https://user-images.githubusercontent.com/10950385/115980128-a6c8fa80-a5cd-11eb-8530-b79d0aeac28a.png)

# Use cases
Choosing This financial year is easier than entering exact dates
Also if I can specify in settings that Australian financial quarter starts on 1 July, then having filter like 'Last Financial Quarter 3' would make it much easier.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/115985736-e552bb00-a5b5-11eb-8f59-b84e756d5c1c.png)

**Comment by sarjanwebdev** [comment]
Oh, I got it, I have to right click on the label {Date Range} next to the check box to get it.

After using MMEX for years on, I feel many pleasant surprises await!

I would not mind having a bigger dialog box that includes a line or two to teach me how to use this hidden gem.

Thansk.

**Comment by whalley** [comment]
@sarjanwebdev  Can we close this or is there something missing you need?

**Comment by sarjanwebdev** [comment]
Can we add an icon or something to make the menu more 'available'?

> @sarjanwebdev Can we close this or is there something missing you need?

**Comment by sarjanwebdev** [comment]
Here is a an expectation of icon with tooltop on hover that explains the hidden usage

![image](https://user-images.githubusercontent.com/10950385/197121840-ffc78c4e-9dcf-475b-9001-c1671ac5a857.png)

**Comment by tactilis** [comment]
@sarjanwebdev 
> Here is an expectation of icon with tooltop on hover that explains the hidden usage

What version of MMEX are you running?

The Transaction Filter on up to date versions of MMEX looks like this:
 
![image](https://user-images.githubusercontent.com/4060092/197157555-db7cbfac-265c-4010-bac8-ece78b5a3df0.png)

**Comment by whalley** [comment]
Yes, I think this issue is out-dated as the UI was changed a few releases ago.

**Comment by tactilis** [comment]
> Yes, I think this issue is out-dated as the UI was changed a few releases ago.

Agreed.

But it was just 5 hours ago that @sarjanwebdev posted a screenshot requesting a tooltip, which makes me question whether he is still using an old version of MMEX - or maybe has upgraded but has not recently used the Transaction Filter.

**Comment by sarjanwebdev** [comment]
My version was old
This can be closed please.

> > Yes, I think this issue is out-dated as the UI was changed a few releases ago.
> 
> Agreed.
> 
> But it was just 5 hours ago that @sarjanwebdev posted a screenshot requesting a tooltip, which makes me question whether he is still using an old version of MMEX - or maybe has upgraded but has not recently used the Transaction Filter.

**Comment by tactilis** [comment]
@sarjanwebdev

> My version was old

Thanks for the confirmation.

Could you always make sure you are using the latest version please before reporting bugs or making enhancement requests.

MMEX development is proceeding fairly quickly so any issues reported against an out of date version may have already been addressed.
