### ISSUE TITLE
Currency dialog: Width / Selected base currency icon / Search field label

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3340]
MMEX version:
 - [x] 1.6.0 Alpha 1
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

1. The default width of the Currency dialog is too small to fully display the Last Rate column.
2. The icon to identify the selected base currency is a small rectangle. It should be a tick (check mark).
3. The 'Search:' label is in the wrong place.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. From Options | General, click on the Base Currency button to open the Currency dialog.

Expected result:

1. The Last Rate column should be fully visible.
2. There should be a tick (check mark) icon next to the selected base currency.
3. The 'Search:' label should be to the left of the Search field.

Actual result:

1. Last Rate column is too narrow.
2. A small rectangle is shown next to the selected base currency.
3. The 'Search:' label is on the right of the Search field.

![image](https://user-images.githubusercontent.com/4060092/116372930-c9912400-a804-11eb-9342-35f373325230.png)

# Additional information

**Comment by vomikan** [comment]
The base currency flag is Ok for me

![image](https://user-images.githubusercontent.com/6836805/116462527-342c7900-a872-11eb-8fff-b134823b084f.png)

**Comment by tactilis** [comment]
I checked 1.6.0 Alpha 1 64 bit with your fixes under Windows 7.

Dialog width is good.
Search label is good.

Selected base currency still has a rectangle next to it as shown in my original report.

What's the reason that a flag character is used? That seems rather cutesy to me.

Anything wrong with having a normal tick icon as is used elsewhere in MMEX?

**Comment by vomikan** [comment]
I think this symbil may be changed to '*' for example or '>'

**Comment by tactilis** [comment]
> @vomikan
> I think this symbil may be changed to '*' for example or '>'

Or perhaps Check Mark [https://unicode-table.com/en/2713/](url), which would be consistent with the use of check marks to indicate a selected item in menus and in dialogs with check boxes, as shown mocked up here:
 
 
![image](https://user-images.githubusercontent.com/4060092/116674794-fd9f4d00-a99c-11eb-8fa9-86d32da03c72.png)
 

I couldn't discover what font is being used in the wx dialogs. Perhaps the reason that the flag is not showing is because that character is not in the version of the font installed on all systems?
 
--- 
 
Also, I was wrong about the dialog width being OK.
It _does_ show the Last rate column now but the dialog width is still too narrow because a horizontal scrollbar is displayed.

![image](https://user-images.githubusercontent.com/4060092/116673131-e8292380-a99a-11eb-93cc-e8f96a4a36c4.png)

Making the dialog just a few pixels wider gets rid of the horizontal scrollbar.
