### ISSUE TITLE
Attachment appended numbers going down instead of up

### ISSUE THREAD

**Issue by withnoe** [moneymanagerex/moneymanagerex#3360]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [x] 1.5.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When adding attachments append number on end of file name numbers are going down instead of up.  Therefore, attachments cannot be added when upgrading since previous append numbers may already be on older file attachments.

# Reproduction

Is the bug reproducible? 
 - [ x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open program 
2. Add entry 
3. Try to add tranactions.
4. loop a few times and it will reach an appended number of a previous attachment. 

…

Expected result: Attachment to be added.

Actual result: Error message or refusal to override previous attachment file with the same number.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

![image](https://user-images.githubusercontent.com/10465797/116725322-c7b79400-a9af-11eb-8412-80a5b6989b00.png)

**Comment by vomikan** [comment]
I can't reproduce it. Can you give us a step-by-step guide?

**Comment by withnoe** [comment]
I think I made some kind of mistake and somehow over wrote the database
with old data but my attachments were still connected to the transactions
that were no longer there.  You can close this ticket.

Thanks
