### ISSUE TITLE
When you login; the window does not open in the place it was shut.

### ISSUE THREAD

**Issue by DrakonDion** [moneymanagerex/moneymanagerex#3361]
> When you login; the window does not open in the place it was shut.

> Please do not remove information attached below this text.

<hr>Version: 1.5.1 64-bit<br>
 • Build: Apr 24 2021 14:32:48<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 2194x1234 32bit 96x96ppi

**Comment by whalley** [comment]
Should be fixed in 1.5.2

https://github.com/moneymanagerex/moneymanagerex/issues/3222

**Comment by DrakonDion** [comment]
Thanks;
Great Work!!!

DrakonDion

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
