### ISSUE TITLE
Enter next booking

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3362]
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=10394

I would appreciate it if after entering a booking, the entry screen cleared and I could immediately enter the next booking.

![](https://forum.moneymanagerex.org/download/file.php?id=1909)

**Comment by whalley** [comment]
Personally, I think it would be better to support an "OK & ADD MORE" button alongside "OK" and "CANCEL"

**Comment by tactilis** [comment]
I agree with @whalley.

**Suggestion:**

1. Buttons displayed when editing an existing (single or multiple) transaction:

![image](https://user-images.githubusercontent.com/4060092/116859988-c331ec00-abf8-11eb-97a2-f2db0cfc10b7.png)


2. Buttons displayed when entering a new transaction:

![image](https://user-images.githubusercontent.com/4060092/116860031-d5ac2580-abf8-11eb-87e1-58a1891ae1aa.png)

**Questions (for discussion)**

To make this feature most useful, we should consider what happens after clicking `OK and add another`; which (if any) of the fields should be pre-populated with the _same_ values as the transaction you have just entered?

1. **Date**?  Yes. This makes sense if you are entering a batch of transactions from a particular day.

2. **Status**?  Probably best to always reset this to None. It's easy to change the status of a batch of entries in the transaction list with the R key after you have competed all entries.

3. **Type**? This should retain the same state of Deposit/Withdrawal/Transfer as the transaction just entered. It would be annoying to have deliberately opened the dialog via the New Withdrawal/New Deposit/New Transfer right click menu and have the Type change back to the default (i.e. Withdrawal) each time you click `OK and add another`.

4. **Amount**? I suggest that this field is always cleared to show that this is a new transaction.

5. **Payee**? It may be convenient to leave this showing the same payee name. It the payee for the new transaction is the same, then it saves mouse clicks. If the payee is different for the new transaction, then it's no more effort to enter it.

6. **Split**? I suggest that this field is always cleared .

7. **Category**? Leave this the same for similar reasons given for Payee.

8. **Number**? Clear this field. Not everyone uses number and it's easy to enter the new one or click the `Populate Transaction #` button.

9. **User Colour**? I suggest that this is set to 'No colour'. As with Status, it's easy to change the colour of a batch of entries in the transaction list with the CTRL+1 to CTRL+7 key after you have competed all entries.

10. **Notes**? I suggest that this field is cleared. It's easy to reselect previously used Notes with the `...` button.


Any thoughts?

**Comment by 2BeeOrNot** [comment]
I agree with @whalley and @tactilis. The idea is good but only having one OK button is not intuitive, the user doesn't expect the entry screen to pop up again. @tactilis has some good thoughts on defaulting some information when "OK Add Another"  or "OK and add more" or "OK & Add More" is clicked.

**Comment by dbolton** [comment]
If space permits, I would change the wording of both OK buttons to clarify.

- OK and close
- OK and new

See also the more comprehensive proposal for data entry that bypasses this issue: https://forum.moneymanagerex.org/viewtopic.php?f=8&t=10394&p=21970#p21970

**Comment by vomikan** [comment]
The parameter has been added 
![image](https://user-images.githubusercontent.com/6836805/116923644-8d741e00-ac5f-11eb-8d8e-ed06d8abcce0.png)

One more option:
Press shift + OK button to enter next transaction immediately.

**Comment by 2BeeOrNot** [comment]
This is working with the Bulk Transactions setting toggle. But I don't experience anything different pressing the shift key and the OK button in a  1.6.0 alpha build. I was expecting with the toggle set to No pressing shift and clicking OK would let me enter a new transaction immediately. Am I wrong?

**Comment by vomikan** [comment]
@2BeeOrNot you are right. I tested it the following way: press left shift button and click the OK button at the same time.

**Comment by tactilis** [comment]
> @2BeeOrNot
> I don't experience anything different pressing the shift key and the OK button in a 1.6.0 alpha build.
> I was expecting with the toggle set to No pressing shift and clicking OK would let me enter a new transaction immediately.

It works as @vomikan intended (for me on Windows).

With the Bulk Transactions option set to No, then clicking OK while holding down the left (or right) Shift key OKs the current entry and pops up the dialog again ready for the next entry.

**Comment by whalley** [comment]
Tested on MacOS.

1. Bulk Setting = No, Shift = No --> Single Transaction entry
2. Bulk Setting = No, Shift = Yes --> Multiple Transaction entry
3. Bulk Setting = Yes, Shift = No --> Multiple Transaction entry
3. Bulk Setting = Yes, Shift = Yes --> Multiple Transaction entry

For (3) should we consider Single Transaction Entry? i.e. use the SHIFT as the toggle.

**Comment by vomikan** [comment]
The cherry on the cake will be if you change the behavior of point 4.
Bulk Setting = Yes, Shift = Yes --> Single Transaction entry

**Comment by whalley** [comment]
Yes I meant 4 rather than 3

**Comment by 2BeeOrNot** [comment]
When I left the comment that Shift OK didn't do anything I was using 1.6.0 Alpha 1 64-bit portable with a build date of 5.3.2021 21:35:42 on Windows. Setting Bulk to yes worked as expected.

 I tried again a few minutes ago using build 5.5.2021 19:52:12 and it works as expected.

Works on the macOS build in nightly I just downloaded. Mark, the link on your web site for 1.6.0 4th May 2021 doesn't work.

Unrelated I noticed the account view colors in the macOS build are as expected. But not in Windows. I think previous 1.6.0 Windows builds had the correct colors. The background for an account with no transactions is light blue but should be white.
1.6.0 macOS and 1.5.1 macOS and Windows
![1 5 1](https://user-images.githubusercontent.com/63317977/117209958-13f64000-adc5-11eb-8b27-351c021044b1.png)
1.6.0 Windows
![1 6 0a 20210505](https://user-images.githubusercontent.com/63317977/117209993-1fe20200-adc5-11eb-9b27-5a2e59e7b88e.png)

**Comment by whalley** [comment]
Links fixed. Just uploaded the latest 1.6.0 Alpha here: https://www.ipx.co.uk/mmex/

**Comment by 2BeeOrNot** [comment]
And removed the May 5th version. This version had the same problem with the colors used in my JSON file that I reported in the Windows version above. The May 6th version fixes the colors. And the latest Windows build fixes it too. Looking at your fix #3382 explains the problem. Thanks.
