### ISSUE TITLE
Theme Colors in JSON FIle

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3365]
MMEX version:
 - [x] 1.6.0a
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [ ] Linux 

1. What does "/colors/listTotal" change? I've change the color to yellow so it stands out and haven't noticed anything changing.

2. "/colors/listBorder" would seem to change a border color by it's name. I found it changes the font color in assets and Stock Portfolio investment account. Is this by design?
![Red](https://user-images.githubusercontent.com/63317977/116819581-a6d17900-ab3e-11eb-8a28-aa25e86b57ba.jpg)

3. Adding a user color for the background color of searches would be helpful in Account View. The default grey doesn't pop out in a screen full of transactions.

**Comment by whalley** [comment]
/colors/listTotal - Seems only to be used in the budget report
/colors/listBorder - Does seem to have some inconsistent usage

More work required to standardise some of the customisation....

**Comment by 2BeeOrNot** [comment]
Thanks. I've never used budgeting or tried it. I'll look there.
