### ISSUE TITLE
Transaction list does not scroll to the selected transaction when changing sort order

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#3377]
MMEX version:
 - [x] 1.5.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When a transaction is selected, changing the sort order, for example by clicking on a different column header, does not keep the selected transaction visible. (The transaction list does not scroll to the selected transaction.)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Select an account with many transactions (the issue is only reproducible if scrolling is required)
2. Select a transaction
3. Change the sort order by clicking on another column name

Expected result: The sort order is changed and the selected transaction remains visible.

Actual result: The sort order is changed, but the selected transaction is not visible.

# Additional information

Workaround: clicking AGAIN on the same column (i.e. reverting the sort order) will scroll the screen to the selected transaction.

![mmex-bug-transaction-sort](https://user-images.githubusercontent.com/1184162/117031036-7d604b00-ad00-11eb-8782-de715c1faa56.png)

**Comment by vomikan** [comment]
The same fix #3372
