### ISSUE TITLE
Repeating Transactions: Provide Payment_Date and Due_Date

### ISSUE THREAD

**Issue by stef145g** [moneymanagerex/moneymanagerex#338]
Method: Replace **Next_Occurence** with **Payment_Date** and **Due_Date**
Within the dialog, the calendar control is renamed to **'Payment Date'** and  will set 'payment date' and 'due date'.
The current database fields will be the meanings modified  as:
**next_occurance** becomes the Payment Date,
**transaction_date** stores the Due date. (Currently not utilised)

Other sections modified accordingly to reflect this change.

**Comment by guanlisheng** [comment]
would we leave a mockup UI to illustrate your idea ?

**Comment by stef145g** [comment]
Stage 1 complete. demonstrates usage.
Available in for test in branch: https://github.com/moneymanagerex/moneymanagerex/tree/stef145g_dev

More work required in a few other sections before it can be released.

**Comment by stef145g** [comment]
Not quite. Trying to satisfy this request:
http://sourceforge.net/p/moneymanagerex/feature-requests/348/

**Comment by guanlisheng** [comment]
okay. so you want (use table.column to avoid confusion)
* BILLSDEPOSITS_V1.TRANSDATE as due date
* BILLSDEPOSITS_V1.NEXTOCCURRENCEDATE as payment date.

It's a great idea that we can utilize BILLSDEPOSITS_V1.TRANSDATE.

Regarding the request, i think it does not make sense to make a transaction before the real schedule.

**Comment by stef145g** [comment]
@guanlisheng The commits you have made to master have now caused a direct conflict with the code in my branch. Does this mean that you don't like my implementation?

Not exactly sure what you mean in your meaning in your last sentence.

**Comment by guanlisheng** [comment]
No and there is no conflict. 
Please rebase your code with master branch.
Last statement means I don't think this feature request make senses.

**Comment by guanlisheng** [comment]
Seems you have reverted your branch and discarded your changes?

**Comment by stef145g** [comment]
The request has merit, although it is a bit confusing. My interpretation is that in providing a payment  and due date, allows the user to cancel a suggested bill date, still maintaining the bill active to allow payment on the actual date of payment without having a payment becoming overdue.

Rebasing to or from master does not work. Conflicts still occurred, making it difficult to resolve. Therefore I have reverted the change. Not sure if I should continue with this or abandon the idea altogether.

**Comment by guanlisheng** [comment]
I thunk you have a draft design before the coding if the request is merit.

My fault that making the rebase failed here while I think it's a regular scenario that multiple changes happened on one single file.

**Comment by stef145g** [comment]
This feature has been implemented.
SHA-1: d2551fe34f2a36c9979bb62e0e00dd6fc8fec2ad

* Merge pull request #346 from moneymanagerex/stef145g_dev
