### ISSUE TITLE
Home Page Widgets/Applets Toggle Status Not Saved

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3387]
MMEX version:
 - [X] 1.5.1
 - [X] 1.6.0a
 - [X] 1.3.6 and maybe prior

Navigation Panel toggles (Bank Account, Cash Accounts etc. expanded/collapsed) are saved.

Home Page toggles (Bank Accounts, Cash Accounts, Term Accounts, Top Categories etc.) are not saved.
If a field in the table INFOTABLE_v1 is created named HOME_PAGE_STATUS containing json like this

{
    "TERM_ACCOUNTS_INFO" : false,
    "ACCOUNTS_INFO" : true,
    "CASH_ACCOUNTS" : false,
    "TOP_CATEGORIES" : false
}

MMEX will expand or collapse the Widgets/Applets when opened but not save the status when MMEX is closed.
It doesn't look like MMEX even creates the DB field.

**Comment by 2BeeOrNot** [comment]
Almost fixed! Did you forget "Upcoming Transactions"? (BILLS_AND_DEPOSITS)

**Comment by whalley** [comment]
Also noticed that on my MacOS build that the URL contained `%23` rather than `#` which made the check for a URI fragment fail. So have escaped it before the check, also fixed issue noted by @2BeeOrNot
