### ISSUE TITLE
locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by yaomtc** [moneymanagerex/moneymanagerex#3394]
MMEX version:
- 1.6.0-Alpha.1
Build on May 6 2021 21:38:58

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

After building on Ubuntu and installing, and opening my database, I get this error and cannot continue:

> locale::facet::_S_create_c_locale name not valid

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Install moneymanagerex
2. Open my database file
3. Error

…

Expected result: 

My database opens, as it does on Arch (community package) and Android (F-Droid)

Actual result:

Database will not open.

# Additional information

[mmex.xml.txt](https://github.com/moneymanagerex/moneymanagerex/files/6438519/mmex.xml.txt)

Once this caused a crash. I've attached the mmex.xml file from that instance.

**Comment by whalley** [comment]
What is the output if you use the `locale` command?

Perhaps try this: https://forum.sinusbot.com/kb/i-get-an-error-like-what-locale-facet-_s_create_c_locale-name-not-valid-what-do-i-do.23

**Comment by vomikan** [comment]
Possible the en_US default value in options should be changed to en_US.ITF-8 or empty.

**Comment by avma** [comment]
I'm facing the same on Linux mint 20.1 x86_64, what more info do you need? maybe i can provide some...

**Comment by vomikan** [comment]
Could you try this solution:
https://community.appdynamics.com/t5/Dynamic-Languages-Node-JS-Python/locale-facet-S-create-c-locale-name-not-valid/td-p/33693

**Comment by avma** [comment]
I wish I'd know how to fix this... ;-) but i sure can provide my locale.
```
❯       locale
LANG=he_IL.UTF-8
LANGUAGE=he_IL
LC_CTYPE="he_IL.UTF-8"
LC_NUMERIC=he_IL.UTF-8
LC_TIME=he_IL.UTF-8
LC_COLLATE="he_IL.UTF-8"
LC_MONETARY=he_IL.UTF-8
LC_MESSAGES="he_IL.UTF-8"
LC_PAPER=he_IL.UTF-8
LC_NAME=he_IL.UTF-8
LC_ADDRESS=he_IL.UTF-8
LC_TELEPHONE=he_IL.UTF-8
LC_MEASUREMENT=he_IL.UTF-8
LC_IDENTIFICATION=he_IL.UTF-8
LC_ALL=
```
BTW: I also tried changing back to en_US.UTF-8, rebuild and launch in en, but was getting the same message.

**Comment by vomikan** [comment]
cat /etc/locale.gen | grep en_US

**Comment by avma** [comment]
```
❯       cat /etc/locale.gen | grep en_US
# en_US ISO-8859-1
# en_US.ISO-8859-15 ISO-8859-15
# en_US.UTF-8 UTF-8
```

![צילום מסך מ־2021-05-12 10-34-52](https://user-images.githubusercontent.com/7680483/117936795-f1f14600-b30d-11eb-9655-c08c15948c21.png)

**Comment by vomikan** [comment]
uncomment the line

en_US.UTF-8 UTF-8

and finally run the command "sudo locale-gen"

**Comment by vomikan** [comment]
@avma seems are you building mmex from scratch.
Plam B:
remove line 63 (  ```wxLocale(wxLANGUAGE_ENGLISH);``` )  in mmex.cpp file.

**Comment by avma** [comment]
None of the above seems to work... 
![צילום מסך מ־2021-05-12 13-19-48](https://user-images.githubusercontent.com/7680483/117959595-d8a7c400-b324-11eb-90a3-b59434bf7701.png)

**Comment by avma** [comment]
I did notice this (dono what it means though)
```
[ 62%] Building CXX object src/CMakeFiles/mmex.dir/optionsettingsgeneral.cpp.o
In file included from /usr/local/include/wx-3.1/wx/intl.h:17,
                 from /usr/local/include/wx-3.1/wx/wx.h:22,
                 from /home/avi/git/moneymanagerex/src/defs.h:30,
                 from /home/avi/git/moneymanagerex/src/constants.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsbase.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsgeneral.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp:19:
/home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp: In member function ‘bool OptionSettingsGeneral::doFormatDoubleValue(const wxString&, wxString&)’:
/home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp:286:21: warning: statement has no effect [-Wunused-value]
  286 |         wxTRANSLATE("**bad locale name**");
      |                     ^~~~~~~~~~~~~~~~~
```

**Comment by vomikan** [comment]
Please move line 286
```wxTRANSLATE("bad locale name");```
to the begin of the function (before ```    double value = 1234567.89;```
or delete it.

**Comment by avma** [comment]
Still the same....

![צילום מסך מ־2021-05-12 14-54-05](https://user-images.githubusercontent.com/7680483/117971033-0e9f7500-b332-11eb-9b53-1c430fe766d2.png)

Same for the error during 'make install'
```
[ 60%] Building CXX object src/CMakeFiles/mmex.dir/optiondialog.cpp.o
[ 61%] Building CXX object src/CMakeFiles/mmex.dir/optionsettingsattachment.cpp.o
[ 61%] Building CXX object src/CMakeFiles/mmex.dir/optionsettingsbase.cpp.o
[ 62%] Building CXX object src/CMakeFiles/mmex.dir/optionsettingsgeneral.cpp.o
In file included from /usr/local/include/wx-3.1/wx/intl.h:17,
                 from /usr/local/include/wx-3.1/wx/wx.h:22,
                 from /home/avi/git/moneymanagerex/src/defs.h:30,
                 from /home/avi/git/moneymanagerex/src/constants.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsbase.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsgeneral.h:21,
                 from /home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp:19:
/home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp: In member function ‘bool OptionSettingsGeneral::doFormatDoubleValue(const wxString&, wxString&)’:
/home/avi/git/moneymanagerex/src/optionsettingsgeneral.cpp:271:17: warning: statement has no effect [-Wunused-value]
  271 |     wxTRANSLATE("bad locale name");
      |                 ^~~~~~~~~~~~~~~~~
```

**Comment by vomikan** [comment]
What about:
https://stackoverflow.com/questions/19100708/mongodb-mongorestore-failure-localefacet-s-create-c-locale-name-not-valid
?
```
sudo locale-gen en_US en_US.UTF-8
sudo locale-gen he_IL he_IL.UTF-8
sudo dpkg-reconfigure locales
```

**Comment by yaomtc** [comment]
After running that (minus the second line) the database now opens. Thanks!

**Comment by avma** [comment]
Yes, same here, I can now load and access the database, however it does not let me change language to He anymore....see attached   screenshot
![צילום מסך מ־2021-05-15 13-02-00](https://user-images.githubusercontent.com/7680483/118356635-ece6fd80-b57e-11eb-99c9-80895ca90256.png)

**Comment by vomikan** [comment]
@avma the Locale setting is not language. It's setting to display currencies. Could you try:
en_US.UTF-8
he_IL.UTF-8
C
C.UTF-8
or leave this field empty.

**Comment by avma** [comment]
You are right of course, my bad.... ]-;
It Does work now....Thank Nikolay

**Comment by ovari** [comment]
### Reproducible with
```
Money Manager Ex
Version: 1.6.0-Beta.2 64-bit
• Build on Oct 22 2022 03:26:47
• Database version: 15 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu.22.04.jammy
Running on:
• Linux Mint 21 "vanessa"
• Linux 5.15.0-52-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

### Terminal output
```$ locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC=en_AU.UTF-8
LC_TIME=en_AU.UTF-8
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY=en_AU.UTF-8
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER=en_AU.UTF-8
LC_NAME=en_AU.UTF-8
LC_ADDRESS=en_AU.UTF-8
LC_TELEPHONE=en_AU.UTF-8
LC_MEASUREMENT=en_AU.UTF-8
LC_IDENTIFICATION=en_AU.UTF-8
LC_ALL=
```
Interesting `LC_ALL=` is `null`. Could this be the source of the error?

Should this issue be re-opened or should this issue be continued at https://github.com/moneymanagerex/moneymanagerex/issues/5204 ?

Thank you

**Comment by whalley** [comment]
> Should this issue be re-opened or should this issue be continued at https://github.com/moneymanagerex/moneymanagerex/issues/5204 ?

Suggest continuing with https://github.com/moneymanagerex/moneymanagerex/issues/5204
