### ISSUE TITLE
third person the category is no more remembered

### ISSUE THREAD

**Issue by Adenadels** [moneymanagerex/moneymanagerex#3395]
Since the 2 last updates, when i chose à third person, the category is no more demembered... i have to select one each time, even if the third person is known.

Than You
adenadels_ugene@yahoo.fr

> Remplacez ce texte (marqué par >) avec une description détaillée de votre problème.
> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.5.1 64-bit<br>
 • Build: Avril 24 2021 14:32:48<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  French (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
I can't reproduce either.

@Adenadels Are you sure you have the Options / Others / Default Category set to use the last category for the payee?
