### ISSUE TITLE
Account list loses focus when using keyboard navigation

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#3396]
MMEX version:
 - [x] 1.5.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

It is not possible to navigate through the account list using the keyboard. After pressing "up" or "down" once, the focus moves to the ledger.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click on any account in the navigation pane
2. Use keyboard navigation to move up or down in the list
3. After key up, the navigation pane loses focus

Expected result: The previous / next account in the list is selected and gets focus.

Actual result: The previous / next account in the list is selected, but the navigation pane loses focus. Subsequent presses of the "up" or "down" keys will select transactions in the ledger.

# Additional information

![mmex-bug-account-navigation-1](https://user-images.githubusercontent.com/1184162/117483686-4f7c4000-af66-11eb-8da1-5ff88c641e03.png)
![mmex-bug-account-navigation-2](https://user-images.githubusercontent.com/1184162/117483702-54d98a80-af66-11eb-98d9-fea135da4151.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3194

**Comment by 2BeeOrNot** [comment]
This issue has be tagged as fixed. Has it been fixed for macOS? Using the up and down arrows in the navigation panel doesn't work at all in latest nightly built on May 9 2921 07:08:41. Same for latest build from Mark built on May 8. Previous nightly built on May 7 and Mark's May 7 build works as described as above.

**Comment by vomikan** [comment]
@whalley please assist

**Comment by whalley** [comment]
Think the `mmGUIFrame::OnKeyPressed(wxTreeEvent& event)` needs an `event.Skip();` at the end otherwise the up/down keys are not going to processed. But I'm intrigued as to why you needed to add the OnKeyPressed method  anyway as the removal of the `SetFocus()` calls alone seems to solve the reported problem.

Was the key handling added for something to do with the Transaction report dialog?

**Comment by whalley** [comment]
Just spotted that keyboard navigation in the transaction list is now broken!

**Comment by 2BeeOrNot** [comment]
Works for me on macOS 10.15.7. 1.6.0 Alpha May 11 from IPX and latest nightly. I can use the up/down arrows to navigate in the account view. Same results on Windows 7. Can't use keyboard to go from navigation panel to account view.

**Comment by whalley** [comment]
Looks like something really odd with my Mac, as rebooting and even using earlier versions of app still exhibit this issue.  I'll close again as seems localised to my setup...

**Comment by vomikan** [comment]
> Can't use keyboard to go from navigation panel to account view.
![image](https://user-images.githubusercontent.com/6836805/117938508-ccfdd280-b30f-11eb-8dc1-cf33ec776517.png)
