### ISSUE TITLE
Favorite or Favourites? Inconsistant Usage - The "U"

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#3399]
MMEX version:
 - [x] 1.5.2

In navigation it's "Favourites". In edit account it's "Favorite". Should be the same - with or without the "u".
In my location it's "Favorite" and "Favorites"
![Fav Spelling](https://user-images.githubusercontent.com/63317977/117515633-d16b6980-af64-11eb-9ac3-332120a13301.jpg)

**Comment by vomikan** [comment]
It's time to fix.

**Comment by 2BeeOrNot** [comment]
I've changed "Favourites" and deleted the "U" in a custom mmex.mo file. Problem is that with each version, release, RC or nightly, my version gets overwritten.

Looking for a translation file where the mmexini.db3 file is located and using it if found would allow a user to have a custom translation file that doesn't get overwritten.

**Comment by whalley** [comment]
EN_GB was fine (Favourite), fixed EN_US (Favorite)

**Comment by whalley** [comment]
> Looking for a translation file where the mmexini.db3 file is located and using it if found would allow a user to have a custom translation file that doesn't get overwritten.

Not sure of the benefit of of user specific custom translation files. The translation files should maintained and shared based on country needs.
