### ISSUE TITLE
System language auto detecting

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#340]
The program should always uses the system language (fallback to english if not available).
I do think it will simplify both the program and end user operation. 
@vomikan @gabriele-v @stef145g @siena123 , what do you think ?

**Comment by vomikan** [comment]
How many mmex used as portable?
system language is not a best solution for this. In other ases it's OK.

2015-01-08 8:29 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by guanlisheng** [comment]
What's the difference between portable and non-portable? they are identical.
Generally, any application should follow its system's language setting.

**Comment by gabriele-v** [comment]
I think that problem here is that we force locale to "en" at start-up instead to use the system one. 
I think that this is also the reason why all system messages (for example caps lock on password) are in English instead of proper system language

**Comment by guanlisheng** [comment]
Agree with @gabriele-v . 
For all, i want to push this out in v1.3 as part of the UX improvement & simplification.

**Comment by guanlisheng** [comment]
Any concern to make this change since I don't want to give users too many options

**Comment by gabriele-v** [comment]
I don't think that it should be closed, because system language it's still English, this only change MMEX Language.

**Comment by vomikan** [comment]
Personally I believe that the app language is user choice.
My fix just help to choose the same language as OS language.

What do you mean 'system language it's still English'?

суббота, 30 января 2016 г. пользователь Gabriele-V написал:

**Comment by gabriele-v** [comment]
Yes, I agree on language. 

I refer to this:
    /* Setting Locale causes unexpected problems, so default to English Locale */
    app->getLocale().Init(wxLANGUAGE_ENGLISH);


This will cause to show all wx system messages and errors in English, I don't know what problems comment refers to, but maybe it could be referred to old wx versions, so we should make some tests..

**Comment by guanlisheng** [comment]
hi @moneymanagerex/desktop-mmex-team , how about to roll out this simplification soon?
