### ISSUE TITLE
Erreur dans l'affichage des opérations planifiées

### ISSUE THREAD

**Issue by btab33** [moneymanagerex/moneymanagerex#3403]
> Dans la page "Accueil", "Echéancier des opérations planifiées" indique que plusieurs opérations sont en retard (cf. image) mais ce n'est pas exact. Toutes les opérations indiquées (sauf la dernière) ont bien été réalisées/pointées et sont programmées de nouveau pour l'année suivante.
Et comme on ne peut pas cliquer sur la ligne pour voir où se trouve l'erreur, on ne peut pas corriger.

![image](https://user-images.githubusercontent.com/83901821/117564971-3df27f80-b0af-11eb-952c-eb788bc10158.png)

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.5.1 64-bit<br>
 • Build: Avril 24 2021 14:32:48<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  French (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by tactilis** [comment]
English translation:

> On the "Home" page, "Upcoming Transactions" indicates that several transactions are overdue (see image) but this is not correct. All the transactions indicated (except the last) have been completed and are scheduled again for the following year.
> And since you can't click on the line to see where the error is, you can't fix it.
>

**Comment by whalley** [comment]
What does the 'recurring transaction' view say for these, in particular the 'Payment' column.

**Comment by btab33** [comment]
Nothing overdue but I see the problem : there are différences between date of paiement and due date. But I don't understand why.
![image](https://user-images.githubusercontent.com/83901821/117613269-eadc0380-b166-11eb-9ccd-57f45e449578.png)

**Comment by btab33** [comment]
Correction done on paiement date. Problem resolved :-)
