### ISSUE TITLE
Enhancement in writing of long numbers

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3431]
To make large numbers easier to read, it would be good to put them in groups of three digits starting from the right:

6532 is often written as 6 532 (or 6,532).

25897 is often written as 25 897 (or 25,897).

596124 is often written as 596 124 (or 596,124).

7538212 is often written as 7 538 212 (or 7,538,212).

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
FYI
https://github.com/moneymanagerex/moneymanagerex/issues/2473

**Comment by Dandy64** [comment]
Well...
1. I don't have Locale (It should be Local, not Local**e**?)
![image](https://user-images.githubusercontent.com/83161661/117964902-dea0a380-b32a-11eb-84a8-caba78b0ca72.png)

2. Yep, I have used Organize Currency for Israeli New Shekel, but it doesn't work. Can it be a bug for a specific currency?
![image](https://user-images.githubusercontent.com/83161661/117965274-3c34f000-b32b-11eb-9b64-3dc8d0bf8e5b.png)

**Comment by vomikan** [comment]
Could you try last build?
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/39130234/job/y5l0fb3tmrumypu7/artifacts

**Comment by Dandy64** [comment]
Not yet))))))

**Comment by vomikan** [comment]
It not released yet but available to anyone who wants to.
