### ISSUE TITLE
No multiselect

### ISSUE THREAD

**Issue by StefBekkevoort** [moneymanagerex/moneymanagerex#3434]
MMEX version:
 - [ ] 1.3.7
 - [ ] 1.3.6
 - [X] 1.5.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug
Mac OSX / Mac Mini M1
I can't multipele items 
-> when I want to use multiselection on recurring transactions or when I want to use multiselection when reconcile a transaction

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:
When using ctrl+mouseklik or shift+mouseklik there should be the possibility to multi select.

Actual result:
No multiselect

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Multiselection does not supported in Recurring Transactions panel.

**Comment by StefBekkevoort** [comment]
The problem also occurs when I want to reconcile a number of transactions...
![Schermafbeelding 2021-05-12 om 19 38 09](https://user-images.githubusercontent.com/84094459/118019814-b1b7b500-b359-11eb-9eb0-57d1ac684e13.png)

**Comment by 2BeeOrNot** [comment]
Multiselect works for me on macOS 10.15.7 and MMEX 1.5.1.
command+click to select individual transactions.
shift+click to select consecutive range of transactions.
Are you selecting before bringing up the popup menu?

You can change the status of selected accounts by pressing R for reconciled, V for void etc. without using the popup menu (in English, don't know if it works the same for other languages).
![MultiSelect](https://user-images.githubusercontent.com/63317977/118047440-baec5600-b348-11eb-988d-7560b52a80bd.jpg)

**Comment by StefBekkevoort** [comment]
Pressing R works !!
Multiselect doesn’t…
I’ll try a reinstall. ( and hope )

Stef

**Comment by StefBekkevoort** [comment]
OS update (11.3.1) + reinstall of MMEX.
Everything works !!
Is there a list of the shortcuts in MMEX?

**Comment by vomikan** [comment]
>Is there a list of the shortcuts in MMEX?

I don't understand the question.

**Comment by StefBekkevoort** [comment]
What I want to know:

R = Reconciled
U = Unreconciled
……



__________________________________

Stef Ballet
Staatsbaan 254
3460 Bekkevoort

***@***.***

**Comment by vomikan** [comment]
F = Follow-up
V = Void
D = Duplicate
Ctrl+1 = Color #1
.....
Ctrl+7 = Color #7
Ctrl+0 = Clear color

**Comment by tactilis** [comment]
F9 = New Transaction
