### ISSUE TITLE
Credit card in reports

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3436]
MMEX version:
 - [x ] 1.5.1
 - [ x] 1.5.2

Operating System:
 - [ x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Let's say I have just 2 accounts: Bank and Credit.

![image](https://user-images.githubusercontent.com/83161661/118089592-32fe5e80-b3d1-11eb-940c-2a2c630da9d8.png)

This month I have just 2 payment I made by my **Credit card**:
1. Visited a Health Store and paid $700.
2. Paid to my dentist $300

![image](https://user-images.githubusercontent.com/83161661/118089975-9e483080-b3d1-11eb-8a0d-6450082593d1.png)

So my total payment is 700 + 300 = $1000 and this is absolutely correct.

Now, I go to my **Bank account**. On the **Bank account** page, I add a transaction for $1000 since, in my bank statement, I always see just the total sum I paid by credit card, without any details. (Details I receive later from the credit company).

![image](https://user-images.githubusercontent.com/83161661/118090672-802f0000-b3d2-11eb-9762-c9c1b1d83193.png)

This is correct as well.

Now, I go to Reports. Most reports show the sum of $2000 instead of $1000. They count Credit cards from the Bank account and every payment from Credit Card as different payments, while Credit card _contains_ all these payments already.

![image](https://user-images.githubusercontent.com/83161661/118091334-5b875800-b3d3-11eb-8f8c-9962dc558e25.png)

![image](https://user-images.githubusercontent.com/83161661/118091398-735edc00-b3d3-11eb-97e3-081e29427060.png)

**One of the possible solutions:**
Add an additional field with a checkbox - whether use this value in reports. By default - yes.

**Comment by vomikan** [comment]
>Now, I go to my Bank account. On the Bank account page, I add a transaction for $1000 since, in my bank statement, I always see just the total sum I paid by credit card, without any details. (Details I receive later from the credit company).

If there is a transaction, there is also its reflection in the report. Mark it as Void. Better status is Follow-up but in this case it will be in the report.

For me Bank Account = Debit Card. I spend money from Credit Card (CC) then transfer money from Bank Account to CC account.

I'll prefer transfer transaction Bank -> CC with  Follow-up status in this case.

**Comment by tactilis** [comment]
I don't believe this is a bug @Dandy64. You are just using MMEX in a less than ideal manner.

As @vomikan suggests, payment of the credit card bill is a _transfer_ from the Bank account to the Credit Card account. Your total wealth changes by only 1,000 (not by 2,000) and this is now shown correctly in the reports.

Here is what I do:

![image](https://user-images.githubusercontent.com/4060092/118100115-ff6e0500-b3cd-11eb-8107-6a88c775de12.png)

As you can see I also colour transfers in the Bank account so that they are easy to see in that account _and_ in the Credit account. You can colour a transaction on the Edit Transaction dialog, or by pressing CTRL+1 to CTRL+7 to apply a colour (or CTRL+0 to clear it).

Here are the reports:

![image](https://user-images.githubusercontent.com/4060092/118100912-eca80000-b3ce-11eb-8540-ce114eb61eef.png)

Does this help?

**Comment by Dandy64** [comment]
Yes, I understand what you are talking about.  In my country it works in different way. I see all my bank transfers, withdraws, etc, immediately at my **Bank account**, while all payments made with my **Credit card** are accumulating at another place. And just at the beginning of next month I see _the total sum_ paid to credit company. List of payments to credit card company is in a different place.
If I mark my Credit card as Void I will not see it in reports, of course. But at the same time the total sum of my **Bank account** will show me incorrect total sum.

Well, actually I have found a way to resolve my problem. Just FYI.
1. I don't use Credit Card Account at all.
2. At my Bank Account I write all my Credit Card payments, marked with yellow color. And I always add the total Credit Card sum, but marked as Void. Just in order to see an exact number as it appears in the bank statement.

**Example**:
I made 2 payments by Credit card:

- Payment A - $300
- Payment B - $200

At my Bank account it looks like following:
![image](https://user-images.githubusercontent.com/83161661/118101445-4d8c0400-b3e0-11eb-9615-650743347e89.png)

In this case I see the correct total sum paid by Credit card (200 + 300 = 500), AND in all reports I can see details of payments without the total 500 twice.

**Comment by Dandy64** [comment]
> I don't believe this is a bug @Dandy64. You are just using MMEX in a less than ideal manner.

I have never said this is a bug. :-)
I was writing my answer to Vomokan and I didn't see your comment yet. I will check and think it over again. Thank you!

**Comment by tactilis** [comment]
@Dandy64
> In my country it works in different way. I see all my bank transfers, withdraws, etc, immediately at my Bank account, while all payments made with my Credit card are accumulating at another place. And just at the beginning of next month I see the total sum paid to credit company. List of payments to credit card company is in a different place.

Yes, that's exactly how it works for me too.  You can see in the example I gave that the credit card spending is accumulating in the Credit card account and then, when the payment is made to the credit card company, you have a transfer from the Bank account.  I just happened to use your dates where everything was shown on the same day.

I don't think it's a good idea to use Void as a way of 'hiding' transactions from the reports.
Using Transfers reflects what is _actually_ happening with the money in the accounts.


@Dandy64
> I have never said this is a bug. :-)

That's true. But it looked like you were reporting one :-)

**Comment by Dandy64** [comment]
Wow, I got it! Thank you very much! You and Vomikan made my day! 👍 

> That's true. But it looked like you were reporting one :-)
No, I have chosen a **Feature request** I believe and Vomikan marked it as a Bug ;-)))

**Comment by vomikan** [comment]
I mark all incoming questions as a bug and assign a milestone. Otherwise, the case may get lost in a large list. Only then do I study the problem and change the status. Thank you all.

**Comment by vomikan** [comment]
@Dandy64 FYI
https://github.com/moneymanagerex/moneymanagerex/issues/3375
