### ISSUE TITLE
It is impossible to delete an empty Account Type

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3439]
MMEX version:
 - [x ] 1.5.2
 - [ ] 1.3.6

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Is the bug reproducible? 
 - [x ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Created a new account type - Assets
2. Created a new account - named Test
![image](https://user-images.githubusercontent.com/83161661/118274583-f95f4d80-b4cd-11eb-9b3b-a6a0cc03aec0.png)
3. Executed right-click at the account Test and chose Delete Account - account Test deleted.

Account Type Assets still exists and **there is no way to delete it.**

![image](https://user-images.githubusercontent.com/83161661/118274925-6b379700-b4ce-11eb-8482-e01131e197d3.png)

…

Expected result: Assets Type deleted

Actual result: Assets Type is not deleted

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
It's a feature not a bug. You can register assets without an account.

**Comment by Dandy64** [comment]
> You can register assets without an account.
Yes, I can. But I **can not delete** it even if registered assets by mistake.

**Comment by vomikan** [comment]
The root item "Assets" not removble. It's not an account.

**Comment by Dandy64** [comment]
> The root item "Assets" not removble. It's not an account.

The root item "Assets" is not present from the beginning. It is the user's decision to add it or not. 
But if the user added it on purpose or by mistake he can't undo it.
Don't you think it sounds a bit weird?

**Comment by vomikan** [comment]
That is Navigation Panel of just created DB 

![image](https://user-images.githubusercontent.com/6836805/118281222-a7222a80-b4d5-11eb-8dc5-b4267145adee.png)

**Comment by Dandy64** [comment]
Yes, you are right! Assets exist from the beginning. :-((

Funny, but **other types** like Loans, Terms, etc are not and can be created by the user and can be deleted. Actually. they are deleted automatically if the user deleted the last account of this type.
Come on, I just have found the issue. If you suppose it is OK, I can stand with it.
