### ISSUE TITLE
Filtering in account view doesn't work

### ISSUE THREAD

**Issue by Chaos99** [moneymanagerex/moneymanagerex#344]
Using version 1.2.0-Alpha.1 on Windows 7 64bit

Setting transactions filters in the account view doesn't change the view.

I've configured a filter, saved it and clicked OK.
The view blinks shortly, but doesn't change.

This is extremely annoying as long as there is no support for multi-select for deleting or changing transactions.

**Comment by guanlisheng** [comment]
@vomikan , would you help to take a look?

**Comment by vomikan** [comment]
I can't reproduce this issue. Working for me.

**Comment by stef145g** [comment]
This was found and fixed after 1.2.0-alpha release 26/12/2014

SHA-1: fdbd9d6ed699b93accb9a5c330f4adf3c78dd56f
* fix(transaction.filter): restore filter functionality.
