### ISSUE TITLE
Blank area at the bottom of the app window

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3440]
MMEX version:
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

What is the purpose of the blank area at the bottom of the app window?

![image](https://user-images.githubusercontent.com/4060092/118299730-03d31480-b4d9-11eb-85d4-8214d45592e9.png)

Was it once intended to be a status line but is now longer required?

# Reproduction

Is the _feature_ reproducible? 
 - [x] Always 

Reproduction steps:

1. Run MMEX.

Expected result:

The area at the bottom of the screen should be used for something (or if no longer required, should be removed).

Actual result:

The area at the bottom of the screen _appears_ to be always be blank and therefore takes up vertical space for no good reason.

# Additional information
 
  [left blank]      ;-)

**Comment by whalley** [comment]
Yes it is the status bar and no we don;t currently use it. Removing it however, at least on MacOS, makes the window look as if it is missing something at the bottom and looks ugly.

All suggestions on innovate ways to use the status bar appreciated :-)

**Comment by valsamis-d** [comment]
> Yes it is the status bar and no we don't currently use it. Removing it however, at least on MacOS, makes the window look as if it is missing something at the bottom and looks ugly.
> 
> 
> 
> All suggestions on innovate ways to use the status bar appreciated :-)

How about displaying the Tips there instead of the area below the transaction list?

See #3161 and #3419

**Comment by tactilis** [comment]
The status bar is not currently big enough for the text of some of the tips - and they definitely won't fit for people who do not use the MMEX window maximized.  And no, we don't want a scrolling marquee! ;-)

Also, the status bar is hidden if MMEX is toggled to Fullscreen (Shift+F11)

**Comment by vomikan** [comment]
#3224 #3180 #2914 #2583

**Comment by vomikan** [comment]
The status bar, in our case, is a decorative element.
Please note that it is not supported on all platforms.

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmframe.cpp#L242-L244
```
#if wxUSE_STATUSBAR
    CreateStatusBar();
#endif // wxUSE_STATUSBAR
```
