### ISSUE TITLE
Value entered into transaction Amount field changes when typing into payee field

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3441]
MMEX version:
 - [x] 1.5.2

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The value entered into transaction Amount field changes when typing into payee field.

Affects 1.5.2
Did not happen in 1.5.1

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. I started from a new database and added a couple of checking accounts.
2. In the first account, add a transaction.
3. Type a value in the Amount field.
4. Type in the Payee field.
5. **Bug:** Observe that the value in the Amount field has changed.

See the attached screen recording.

Expected result:

The Amount should not change when typing in the Payee field.

Actual result:

The Amount does change as shown in the video.

# Additional information

https://user-images.githubusercontent.com/4060092/118321812-0abc5000-b4f6-11eb-957f-7acd96f4d67c.mp4

**Comment by Dandy64** [comment]
**Additional information:**
The behavior depends on the sum. 

**Situation I - Amount = 100**
1. OnBlur 100 changes to 100.00
2. In the field From was written the word "Test" ->No change. The Amount = 100.00

**Situation II - Amount = 1000**
1. OnBlur 1000 changes to 1,000.00
2. In the field From was written the letter "T" ->The Amount has changed = 1.00


* It does not matter which field was chosen, it can be Payee or Notes or Date etc. What is more important it is necessary to lose focus twice - Payee and after that Notes, or Notes and then Dates.

**Comment by tactilis** [comment]
@Dandy64
> What is more important it is necessary to lose focus twice - Payee and after that Notes, or Notes and then Dates. 

I've now found that if you enter an Amount of 1000 and simply press the Tab key to tab to the Account field, the amount will change to 1.00

Any Amount of 1000 or higher changes when you tab out of the field (the value gets divided by 1,000).

**Comment by tactilis** [comment]
Further investigation shows that this incorrect behaviour is somehow connected with the Locale changes that have been made recently.

I've noticed that my Locale is now shown as en-US.UTF-8

![image](https://user-images.githubusercontent.com/4060092/118374252-ea060000-b5b2-11eb-9496-cbe4a5c9d963.png)

If I change Locale to the blank option then the incorrect behaviour of the Amount field no longer occurs.

![image](https://user-images.githubusercontent.com/4060092/118374332-67317500-b5b3-11eb-8ed7-be98cee4f6e6.png)

**Comment by vomikan** [comment]
#2473

**Comment by tactilis** [comment]
Checked on the latest 1.6.0 Alpha.1 on master.

The incorrect changing of the Amount field in the Transaction dialog is now fixed (thanks @vomikan), however the transaction amount is shown with an incorrect grouping character (space instead of comma) for the locale as you can see here:

![image](https://user-images.githubusercontent.com/4060092/118400170-656dbd00-b658-11eb-931f-3c1e768a3414.png)

 
  
Looking at the Currency Dialog, the Decimal Char and Grouping Char fields are greyed out as expected but the Currency Format Sample is wrong (it uses a space grouping char), even though it says Using Locale:

![image](https://user-images.githubusercontent.com/4060092/118400296-ef1d8a80-b658-11eb-9073-9ecc2cde5c62.png)

**Comment by vomikan** [comment]
Did you restart the app? I can't reproduce it.
![image](https://user-images.githubusercontent.com/6836805/118400612-04031980-b66b-11eb-8ad4-3feecd3c3dae.png)

**Comment by tactilis** [comment]
@vomikan
> Did you restart the app? I can't reproduce it.
 
Oh, that was it!  Yes, a restart fixes it.
Sorry to have wasted your time.

However...

This message is not very helpful because it gives the user no indication whether they have changed an Option that does, or does not need a restart:

![image](https://user-images.githubusercontent.com/4060092/118407044-b2608c00-b676-11eb-8525-77ce9899f168.png)

I see that there was a discussion about this between you and @whalley in #3011 here:

[https://github.com/moneymanagerex/moneymanagerex/issues/3011#issuecomment-793902051](url)

While testing MMEX, I have become so used to setting Options that have an immediate effect without a restart that I am now completely 'word blind' to the above warning. I just OK the message by pressing Enter as soon as it pops up.

I note that if you display the Options dialog, make _no changes_, and then click OK, you still get the '_maybe_ you need a restart' warning.

It would be very helpful if changes to a 'needs-a-restart' option could set a flag so that the message is shown _only_ when actually needed.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3011
