### ISSUE TITLE
Recurring Transaction - duplicated button

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3443]
1. Recurring Transaction page
There is a button named Transaction Filter 
![image](https://user-images.githubusercontent.com/83161661/118369688-02731c00-b5ad-11eb-9d14-4b1d5ea9e30b.png)
At the same time there is another button with the same function:
![image](https://user-images.githubusercontent.com/83161661/118369718-220a4480-b5ad-11eb-8403-157c117b3d08.png)

Both buttons together:

![image](https://user-images.githubusercontent.com/83161661/118370400-33a11b80-b5b0-11eb-8ff0-e16c33bb898d.png)
 
Probably it worth hiding one of them. 
![image](https://user-images.githubusercontent.com/83161661/118369688-02731c00-b5ad-11eb-9d14-4b1d5ea9e30b.png)

It is not critical, of course.

**Comment by vomikan** [comment]
The fuel in this screen is Transaction Report. The Recurring Transaction the panel filter. The interface looks the same, but these are different functions.
