### ISSUE TITLE
dd Mon yyyy date format

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3460]
![image](https://user-images.githubusercontent.com/6836805/118675904-a6560500-b803-11eb-9c4b-97a2a6a1e5cb.png)

https://forum.moneymanagerex.org/viewtopic.php?f=10&t=10404

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3323

**Comment by tactilis** [comment]
Thanks @vomikan - I was in the process of raising this but you beat me to it.
