### ISSUE TITLE
Inconsistent display of decimal places

### ISSUE THREAD

**Issue by ratcatcher** [moneymanagerex/moneymanagerex#3466]
MMEX version:
 - [X ] 1.5.1

Operating System:
 - [X ] Windows

# Description of the bug

Most of my transactions are in Euro or Pounds Sterling so have 2 decimal places (cent or pence) defined in the currency (Scale = 2).

I also have some crypto set up with 8 decimal places (Scale = 8) and commodities with 6 decimal places (Scale = 6).

In the latest version, when I make a transfer, the transaction is shown with the wrong number of decimal places in the source and destination account.

For example, I recently sold some Silver for Euro

In the Euro account I see a deposit of "€1,055.330000" (should be "€1,055.33") and a balance of "1561.490000" (should be "€1561.49").

A similar thing happened in reverse when I originally bought the Silver, with the deposit to the XAG account showing 2 decimal places, rather than 6.

# Reproduction

Is the bug reproducible? 
 - [X ] Always 

Reproduction steps:

1. Make a transfer between accounts where the number of decimal places (Scale) is different for the two currencies.
2. Observe the entries in each account.
3. Make a transfer in the opposite direction.
4. Observe the entries in each account.

…

Expected result:

Entries should show the correct number of decimal places for the currency associated with the account.

Actual result:

Entries show the number of decimal places for the wrong currency of the pair (source and destination).

# Additional information

This appears to have started with the latest version.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/118793338-31390d00-b8a1-11eb-9c05-0bf156b8bd28.png)

**Comment by vomikan** [comment]
#2473
