### ISSUE TITLE
Ordering of supported date formats is no longer user friendly

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3469]
MMEX version:
 - [x] 1.6.0 Alpha.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX  Not tested
 - [ ] Linux Not tested

# Description of the bug

Support for new date formats (for import and display) was added in #3323 and #3460.

When these code changes were made, the list of date formats shown in the dropdowns on the Import and Options dialogs changed from a readable, relatively logical ordering to a seemingly random order, as shown here:
 
![image](https://user-images.githubusercontent.com/4060092/118952086-8c2b3c80-b953-11eb-964a-f1bab5c50931.png)
 
This is a regression and it is now _very_ hard for the user's eye to find a particular format because they are no longer grouped into common patterns.

I have taken the current 1.6.0 Alpha.1 list of formats and am proposing a logical grouping and ordering for the dropdowns based on Pattern and Separator. Using this ordering of formats (in the Supported column) would make the dropdowns easier to use.

It's also easier to see from the list, which of the possible formats MMEX does not support.

![image](https://user-images.githubusercontent.com/4060092/118964811-d5818900-b95f-11eb-8f22-32762d467e92.png)

I've attached the spreadsheet from which the above image comes in case anyone wishes to use it in the future when further extending the formats supported.

[MMEX Date Formats.xlsx](https://github.com/moneymanagerex/moneymanagerex/files/6515174/MMEX.Date.Formats.xlsx)

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

N/A

# Additional information

I would also propose that the format:

     Wee DD Mon’YY

would be better shown as:

     Day DD Mon’YY
     
as it is clearer that 'Day' is a day name, as opposed to 'Wee' - which I guess is a shortening of Weekday?

**Comment by tactilis** [comment]
Wow. Fast work @vomikan!

Have you been able to implement a list with a consistent grouping by pattern and ordering by separators within the patterns similar to what I proposed above?  I couldn't find where the list of formats is defined in the source.

**Comment by reddyshyam** [comment]
Thanks @vomikan  for the quick implementation of my request. 👍 🙏🤝👌👏

**Comment by vomikan** [comment]
@tactilis  I want to close this issue for now. 
The table you suggested may be useful in the future. You can probably open a new request to change the date format to some universal constructor like this: [DD][\][MM][\][YYYY].

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/119126955-6037b600-ba3c-11eb-9df6-c75e4abbe6b2.png)

**Comment by tactilis** [comment]
@vomikan
>  I want to close this issue for now.

Yes, of course.

You have fixed the issue of the 'random' list of date formats being difficult to read in 1.6.0.

The order produced by sort is good too because is gives a logical progression from day to month to year in the first field, which is actually better than the order in 1.5.1 (and in my table).

> You can probably open a new request to change the date format to some universal constructor like this: [DD][\][MM][\][YYYY] (five drop down menu).
>PS What about the day of the week?

I thought about doing this previously.
Although it would give the ultimate in flexibility, it would be much slower to select a particular format because of all the mouse moves and clicks needed.

I'll put it on my To Do list and maybe create a mock-up UI for discussion first.
