### ISSUE TITLE
Accounts Visible menu missing check mark to indicate which option is selected

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3474]
MMEX version:
 - [x] 1.6.0 Alpha.1
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX Not tested
 - [ ] Linux Not tested

# Description of the bug

The Accounts Visible menu is missing the check mark to show which of All, Favourites, Open, or Closed is currently selected.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. In the Navigation tree, right click on Bank Accounts, Credit Card Accounts, Loan Accounts, Term Accounts, or Stock Portfolios
2. Observe that the Accounts Visible sub-menu does not have a check mark to indicate which option is currently selected.

Here is a screenshot where All is currently selected:
 
![image](https://user-images.githubusercontent.com/4060092/119017894-64f45f80-b993-11eb-893c-9ac4e437375c.png)
 
Here is a screenshot where Open is currently selected:

![image](https://user-images.githubusercontent.com/4060092/119018004-848b8800-b993-11eb-8c79-27edf70918bb.png)

Expected result:

The Accounts Visible sub-menu should have a check mark to indicate which option is currently selected.

Actual result:

No check mark on the sub menu.

# Additional information

**Comment by tactilis** [comment]
Which issue is this a duplicate of?  I did search before raising it but couldn't find a prior issue covering this.

![image](https://user-images.githubusercontent.com/4060092/119043873-6af93900-b9b1-11eb-96b7-ff6cf0477132.png)

**Comment by vomikan** [comment]
#2635

**Comment by tactilis** [comment]
OK.

However, that's not quite the same issue. In #2635, people were expecting the right-click Navigation | Accounts Visible setting to persist across runs of MMEX.  My enhancement suggestion is not for that - just for a check mark to show which of the views is currently selected selected.

As someone mentioned in the discussion of #2635, Options | View also has an Accounts Visible setting.

I think most of the confusion could be avoided by changing the wording on the Options dialog to indicate that the setting there is applied at startup:

![image](https://user-images.githubusercontent.com/4060092/119168055-6b98da80-ba58-11eb-90bc-a48821cee0b8.png)

By the way, if you do make a change to the options dialog, then the 'ALL' choice in the dropdown ideally should be changed to 'All' to match the case of the other choices and the 'All' setting in the Navigation | Accounts Visible menu.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/120936743-1d4f3100-c712-11eb-8da2-1f141810c30f.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/120936766-3eb01d00-c712-11eb-8935-1e0bb8081c0c.png)
