### ISSUE TITLE
'Delete all transactions in current view' and 'Delete Viewed "F / U" Transactions' does not delete

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3478]
MMEX version:
 - [x] 1.6.0 Alpha.1
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In the transaction list, the right-click menu gives options to:
- 'Delete all transactions in current view'
- 'Delete Viewed "Follow Up" Transactions'
- 'Delete Viewed "Unreconciled" Transactions'

None of these actually delete any transactions.
 
# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Create some transactions with status R, F, and U.
2. Right click on the transaction list and attempt to used any of the options shown below.

![image](https://user-images.githubusercontent.com/4060092/119042594-f4a80700-b9af-11eb-83b4-61d1bd70f7fc.png)

Expected result:

The relevant transactions are deleted.

Actual result:

No transactions are deleted.

# Additional information

**Comment by whalley** [comment]
We did remove some functionality regarding the 'Viewed' transactions (this was around the 'Mark all...' functionality) as it can lead to user error. We don't seem to react to the menu options you noted and I think we should remove them and leave it for user to select transactions first, then just have a "Delete selected transactions" option.

**Comment by tactilis** [comment]
The wording of those 'Delete Viewed..." items has always bothered me. Confusing as to what they would actually delete.

@whalley
> I think we should remove them and leave it for user to select transactions first, then just have a "Delete selected transactions" option.

I agree. Filter and user select is the best way.
Then we'd need just a simple Delete menu item, with the current Confirm Transaction Deletion confirmations.

**Comment by vomikan** [comment]
@whalley, @tactilis Sorry guys, I read your messages after I fixed this.

**Comment by whalley** [comment]
I’m easy, you have fixed the problem. Let’s see what future comments there are (if any) on this.

**Comment by tactilis** [comment]
@vomikan
>Sorry guys, I read your messages after I fixed this.

@whalley
>  Let’s see what future comments there are (if any) on this.

Sorry, but I've got a comment...

The 'Delete Viewed' and 'all in current view' items are IMO very confusing to an average user. They were confusing to me at first - and I do have an IT/Systems Engineering background!

The style of language used is inconsistent on the Delete sub-menu:

![image](https://user-images.githubusercontent.com/4060092/119189816-6c3f6a00-ba74-11eb-9d5b-6ce28e6e134f.png)

What exactly is meant by 'in current view?'
- Does it meant just the transactions I can _see_ on my screen right now (i.e. those that are in view)?
- Or does it mean the (possibly filtered) list of transactions in the entire list?

What exactly is meant by 'Delete **Viewed** "F|U" Transactions'?
- Does Viewed mean the transactions that I have actually _opened_ to view?
- Or does it mean the F|U ones I can _see_ on my screen now?
- Or does it mean the (possibly filtered) list of F|U transactions in the entire list?

I do know the answers - but it's not 100% clear unless you experiment with the commands first to find out what they really do. And since we don't have 'Undo' in MMEX, experimentation is 'dangerous' if you have carefully entered lots of transactions and don't want to risk losing them. The average user won't think to create a test database to experiment on, or to reload a backup .mmb if s/he gets it wrong.

Does anyone really need these Delete menu items when the more obvious behaviour is to delete Selected transactions?

The inconsistency in the language used continues on the next menu item:

![image](https://user-images.githubusercontent.com/4060092/119192271-c130af80-ba77-11eb-9bcc-7db6b266df6a.png)

What is meant by '**being** selected'?
- Does it mean the ones that _are_ selected right now?
- Or perhaps it will be the ones I next select (_being_ selected sounds like you are still in the process of selecting)?

Again, I know the answer. But the menus use confusing inconsistent language. MMEX should be as easy and obvious as possible, especially for new users.

So, the Mark menu should probably say:  'Mark all selected as' > Reconciled / Unreconciled / etc

This may seem picky and pedantic, but I feel it is important if the aim is for MMEX to be used more widely. 

Thoughts?
