### ISSUE TITLE
Summary of Accounts / Monthly

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3479]
![image](https://user-images.githubusercontent.com/6836805/119124311-316c1080-ba39-11eb-98e9-7f186b1bd314.png)

**Comment by vomikan** [comment]
![Uploading image.png…]()

**Comment by whalley** [comment]
Stock/Investment related? I've not got any of these setup in MMEX, just standard accounts and see no failures.

**Comment by renato-mmex** [comment]
I tried to find the version that causes the error and here is the result:
**https://github.com/moneymanagerex/moneymanagerex/pull/3368**
Version: 1.6.0-Alpha.1 64-bit
• Aufbauend auf **Mai 3 2021 17:40:20**
• Datenbankversion: 7 • (aes128cbc)

**Comment by vomikan** [comment]
I need demo DB with this bug. 
I've tested all types of acciunts, Some currencies etc.

**Comment by vomikan** [comment]
@renato-mmex 

The following information will help with the investigation:
1) Base currency
2) Locale Settings
![image](https://user-images.githubusercontent.com/6836805/119662365-f8b5a800-be39-11eb-8433-903014184707.png)

3) The account types used and their currency.

**Comment by vomikan** [comment]
@tactilis You have a talent for finding bugs, even if they don't seem to exist.
Help to close this issue, please.

**Comment by tactilis** [comment]
@vomikan 
> @tactilis You have a talent for finding bugs...

Thank you. I try.  :smiley:

 

> ...even if they don't seem to exist.

:innocent: 


Where was the original bug report in this issue from?  The forum?  I don't remember seeing a post there.

**Comment by vomikan** [comment]
It was a personal meggase. Since the data is private, there is no way to get a database instance.

**Comment by tactilis** [comment]
OK, but did the person who sent the message provide _any_ information at all on what they are doing leading up to the crash?

In your 2nd post above you list the MMEX versions that exhibit the error and those that don't. What was the original user doing when they got the crash? We must have some information to go on

**Comment by renato-mmex** [comment]
Hi Nikolay, I have sent you the .mmb + .db3, I have alienated the data enough to make it less confidential. In this reduced dataset this error also occurs.
by the way: I have documented from which MMEX versions the error occurs, with older MMEX versions there is no error message.

**Comment by tactilis** [comment]
@renato-mmex
What steps need to be taken to produce the crash?

Just open the database - or do something else?

**Comment by renato-mmex** [comment]
Sorry, the title describes at which menu selection the error occurs.
**Summary of Accounts / Monthly**

**Comment by vomikan** [comment]
@renato-mmex  
> I have documented from which MMEX versions the error occurs, with older MMEX versions there is no error message.

We have applied a new library for formatting numbers. Like any innovation, this generates enough errors, unfortunately. In this case, we can not roll back.

**Comment by renato-mmex** [comment]
I don't have a problem with this error, but I reported it so that you can solve the problem for other users.

**Comment by vomikan** [comment]
@renato-mmex  > I have sent you the .mmb + .db3

I didn't find any files in my mail.

**Comment by vomikan** [comment]
It would be good to fix this issue. This is the latest one discovered for today for version 1.5.2.
I would make a release this weekend.

**Comment by renato-mmex** [comment]
Sent again now at .gmail

**Comment by tactilis** [comment]
@renato-mmex 
> Sorry, the title describes at which menu selection the error occurs.
> **Summary of Accounts / Monthly**

OK Renato. Thanks.

It would be very helpful if problem reports were made _directly_ to github using the New Issue | Bug Report template.

That way, the exact actions to produce the problem can be captured in the bug report.

This would allow other people to investigate the problem as well rather, than just put all the load on @vomikan

**Comment by vomikan** [comment]
I can't reproduce this issue using the DBs provided by Renato

![image](https://user-images.githubusercontent.com/6836805/119898215-36095b00-bf4a-11eb-9509-d9e1c89987e1.png)

**Comment by tactilis** [comment]
@vomikan
> I can't reproduce this issue using the DBs provided by Renato

But @renato-mmex can reproduce it?

In which case @renato-mmex, please can we have an exact step by step description of what needs to be done to provoke the crash using the DB you supplied to @vomikan.

**Comment by vomikan** [comment]
How I understed the is only one step:
![image](https://user-images.githubusercontent.com/6836805/119899818-52a69280-bf4c-11eb-8938-387c067642a5.png)

**Comment by renato-mmex** [comment]
That is a mystery.
I have just downloaded the latest version
Version: 1.6.0-Alpha.1 64-bit
- Based on May 27 2021 20:53:02
- Database version: 7 - (aes128cbc)
installed, the error remains.
Have also installed MMEX on another PC and the error comes here too.
(see you tomorrow, good night)

**Comment by tactilis** [comment]
Could you send me Renato's de-personalised database and the .db3 please.

I will try to provoke the bug.

**Comment by tactilis** [comment]
> @renato-mmex will you allow me to post this here?

If not here, you could PM it to me in Slack (assuming Renato is OK with this)

**Comment by renato-mmex** [comment]
I have now installed a US version of Windows10 Pro on another PC and the same problem arises here.

@vomikan
You can send the two files to @taktil, but I don't want numbers of them to be published anywhere.

by the way, if I don't answer immediately, then I'm sorry, I've just been released from hospital and still have to take it easy.

**Comment by tactilis** [comment]
@vomikan 

I get the crash!

I'll PM you the debug zip on Slack

**Comment by vomikan** [comment]
[MoneyManagerEx_dbgrpt-4388-20210528T121037.zip](https://github.com/moneymanagerex/moneymanagerex/files/6560563/MoneyManagerEx_dbgrpt-4388-20210528T121037.zip)

**Comment by vomikan** [comment]
I see a certain antivirus in the log:
HP ProtectTools Security Manager
And CURL function memcpy.
However, this has nothing to do with the report.

It would be necessary to disable the antivirus temporarily and check again.

**Comment by tactilis** [comment]
It's not an antivirus. The HP ProtectTools Security Manager is the admin interface for these components:

![image](https://user-images.githubusercontent.com/4060092/119982345-a1891200-bfb6-11eb-8565-e678562e3334.png)

All of these components are disabled.

However, I don't need ProtectTools, so I will uninstall the package and run MMEX again.

My antivirus is the standard Microsoft Security Essentials. I'll disable that before re-running.

**Comment by tactilis** [comment]
HP ProtectTools removed.  Microsoft Security Essentials AV turned off.

This version of MMEX used:
 
![image](https://user-images.githubusercontent.com/4060092/119994082-29c1e400-bfc4-11eb-9540-72dbbe111a4f.png)
 
Database opened: Finanzen2011.mmb (as supplied)

Click Summary of Accounts | Monthly  -> crash

[MoneyManagerEx_dbgrpt-2284-20210528T144532.zip](https://github.com/moneymanagerex/moneymanagerex/files/6561273/MoneyManagerEx_dbgrpt-2284-20210528T144532.zip)

**Comment by vomikan** [comment]
That is my environment:
```
Version: 1.6.0-Alpha.1 64-bit
• Build on May 28 2021 14:35:25
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg 
• libcurl/7.61.1-DEV WinSSL
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.12.18081601-MSVC_2
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27045.0
• Windows SDK 10.0.17763.0
Running on:
• Windows 10 (build 19042), 64-bit edition
• English (U.S.) (windows-1251)
• 3440x1440 32bit 96x96ppi 
```

I remembered that my curl library is newer than the one that is distributed.
I get a crash when using the latest build: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/39366123/job/qv21r1ckxupi10pg/artifacts

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3241

**Comment by whalley** [comment]
For reference my MacOs builds are using:

`libcurl/7.64.1 (Secure Transport) LibreSSL/2.83 zlib/1.2.11 nghttp2/1.41.0`

**Comment by vomikan** [comment]
The crash desappears if the Asset account initial balance would be set to 0.0

![image](https://user-images.githubusercontent.com/6836805/120172062-59166200-c20b-11eb-912b-f31bac428614.png)

**Comment by renato-mmex** [comment]
Congratulations, I checked it in my test accounting, as soon as you put a value in an asset, the error message comes up.

**Comment by renato-mmex** [comment]
Congratulations, the new version - Building on May 31 2021 12:09:40 works without error message.

**Comment by renato-mmex** [comment]
yes, yes, rejoiced too soon, but the bank account balances are wrong, they are going into minus.

**Comment by vomikan** [comment]
Finding out how to reproduce the error is already half the job. I continue to investigate why the crash occurs.

**Comment by vomikan** [comment]
It seems the latest fix fixed the problem.

**Comment by renato-mmex** [comment]
I think that this problem has not been solved yet, because the results displayed are wrong.

**Comment by vomikan** [comment]
This is a GRM report to control accounts balance.
[Account-Balances.grm.zip](https://github.com/moneymanagerex/moneymanagerex/files/6572247/Account-Balances.grm.zip)

**Comment by renato-mmex** [comment]
I have tested the latest version, the bank accounts are displayed in the account overview, **but the assets and shares are missing.**

**Comment by grumpy235** [comment]
@vomikan I think there may be an issue with the yearly report on Bank Account data, monthly appears fine but yearly does not match up, unless of course I am misinterpreting what this is showing me. Extracts show first 3 columns - Date, Cash, Bank Accounts

![Capture1](https://user-images.githubusercontent.com/24897056/120306505-d56f7a80-c2c9-11eb-8a91-adf7fee95130.PNG)
![Capture2](https://user-images.githubusercontent.com/24897056/120306529-d9030180-c2c9-11eb-9837-a9f9fc8aa03b.PNG)

**Comment by vomikan** [comment]
It's a bug.

**Comment by grumpy235** [comment]
@vomikan Much better now, thankyou

**Comment by vomikan** [comment]
I did not check currency convertions.

**Comment by vomikan** [comment]
The SQl for control result:
``
select sum(bank_accounts) bank_accounts
, sum (ASSETS) Assets
, sum(SHARE_ACCOUNTS) Shares
from (
with b as (
Select sum(TRANSAMOUNT) as balance, ACCOUNTID, ACCNAME from (
                      SELECT c1.ACCOUNTID,
                             (CASE WHEN c1.TRANSCODE = 'Deposit' THEN c1.TRANSAMOUNT ELSE -c1.TRANSAMOUNT END) AS TRANSAMOUNT,
							 (select AccountName from ACCOUNTLIST_V1 where AccountID = c1.AccountID) as ACCNAME
                        FROM CHECKINGACCOUNT_V1 AS c1
			WHERE c1.STATUS NOT IN ('V') 
                      UNION ALL
                      SELECT c2.TOACCOUNTID,
                             c2.TOTRANSAMOUNT,
						    (select AccountName from ACCOUNTLIST_V1 where AccountID = c2.AccountID) as ACCNAME
                        FROM CHECKINGACCOUNT_V1 AS c2
                       WHERE c2.TRANSCODE = 'Transfer' AND c2.STATUS NOT IN ('V') )
group by ACCOUNTID
order by ACCNAME
)
SELECT a.ACCOUNTNAME,
       IFNULL(CH.CURRVALUE, c.BASECONVRATE) AS CURRVALUE, -- Only use ch.currvalue for v13 DB
       c.PFX_SYMBOL,
       c.SFX_SYMBOL,
       c.DECIMAL_POINT,
       c.GROUP_SEPARATOR,
	   a.ACCOUNTTYPE,
       case when a.ACCOUNTTYPE='Checking' then ifnull(b.balance, 0) + a.INITIALBAL end as BANK_ACCOUNTS,
       case when a.ACCOUNTTYPE='Asset' then ifnull(b.balance, 0) + a.INITIALBAL end as ASSETS,
       case when a.ACCOUNTTYPE='Shares' then ifnull(b.balance, 0) + a.INITIALBAL end as SHARE_ACCOUNTS

  FROM ACCOUNTLIST_V1 a
       left JOIN b on b.AccountID = a.AccountID
       INNER JOIN
       CURRENCYFORMATS_V1 AS c ON c.CURRENCYID = a.CURRENCYID
       LEFT JOIN
       CURRENCYHISTORY_V1 AS CH ON CH.CURRENCYID = c.CURRENCYID AND 
                                   CH.CURRDATE = (
                                                     SELECT MAX(CRHST.CURRDATE) 
                                                       FROM CURRENCYHISTORY_V1 AS CRHST
                                                      WHERE CRHST.CURRENCYID = c.CURRENCYID
                                                 )
 WHERE a.ACCOUNTTYPE not IN ('Investment') AND 
       a.STATUS = 'Open'
 GROUP BY a.ACCOUNTNAME
 ORDER BY a.ACCOUNTNAME ASC)
 ```
