### ISSUE TITLE
Transaction dialog search category does not work on OSX

### ISSUE THREAD

**Issue by themnd** [moneymanagerex/moneymanagerex#348]
I'm on MMEX 1.1.2, previously when you enter a new transaction, as soon as you start type some letters in the category field it will narrow the category list with only the categories that match.
Now it does not work at all and if you clear the field first and then start type some letters occasionally you have got some crashes.

**Comment by guanlisheng** [comment]
would mind to have a retry on v1.2.0-beta

**Comment by themnd** [comment]
I tried version 1.2.0-alpha.1 since this the latest version available on the github releases and the behavior is the same.
I've also checked the last two commits in 1.2.0-beta and they doesn't look like to be fixing this bug.
I tried to compile mmex from sources but I'm on Yosemite and seems like I'm missing some pre-requisites, I'm not able to even start the compile process. Is there any mac os x specific documentation?

**Comment by guanlisheng** [comment]
You can click the build status icon in GitHub to see how Travis ci builds the project

**Comment by themnd** [comment]
I'll closed the issue since the problem seems more related to wxwidgets than mmex.
Moreover it will probably work as expected since I've seen this: #359 359

**Comment by omalleypat** [comment]
Did you get it to build on mac os x? I'd love to have some help from another mac person!

http://sourceforge.net/p/moneymanagerex/wiki/Build%20Instructions%20for%20Mac%20OS%20X/

**Comment by themnd** [comment]
I just installed some dependencies with brew (like gettext, bakefile).
You have to remember that once you clone the respository you have to update the submodules: git submodule update.

Thank I did:

```
./bootstrap
./configure
```

and at that point you can do: make

the webview is not working but the transaction list is working correctly.

**Comment by omalleypat** [comment]
Sorry - wasn't clear. I am the mac build maintainer - I have my build environment working. 

By help I meant help with finding and reporting issues that are mac-specific. Not sure about the webview not working - I haven't compiled it in a couple weeks. I'll look into those things soon.

If you have additional feedback on the wiki article to make it clearer, I'd welcome it.

-Pat

**Comment by themnd** [comment]
Sure, I'm using it on a mac and my wife use it on windows.
We share the database through dropbox :-D
I'll report any issue I'll find.
