### ISSUE TITLE
Copy/Past Transaction different accounts

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3482]
The Past Transaction menu item available but does not working.
![image](https://user-images.githubusercontent.com/6836805/119195223-f8f62200-ba8c-11eb-91e2-6c4c4d225dd6.png)

**Comment by whalley** [comment]
Seems that pasting is always pasting transfers into the original account. Suspect this is what you are seeing.

**Comment by vomikan** [comment]
I can't copy transfer transaction from an account to the same account.
![image](https://user-images.githubusercontent.com/6836805/120178383-2328ac00-c212-11eb-8521-d517db78fdc1.png)

**Comment by whalley** [comment]
So, just to check, does this logic sound right..

We have
1. BANK A > BANK B
2. BANK A < BANK B
3. BANK C > BANK D

If we copy 1 & 2 from BANK A and paste in BANK A we paste new transactions as:
5. BANK A > BANK B
6. BANK A < BANK B

If we copy 1 & 2 from BANK A and paste in BANK B we paste new transactions as:
7. BANK A > BANK B
8. BANK A < BANK B

If we copy 1 & 2 from BANK A and paste in BANK C we paste new transactions as:
7. BANK C > BANK B
8. BANK C < BANK B

**Comment by vomikan** [comment]
What is wrong now.
There is transaction BANK A > BANK B
I am on BANK B account view. Copy the transaction and past to the same account.
It became BANK B > BANK B invalid transaction.

**Comment by whalley** [comment]
Yep, above should fix that. Will commit change shortly.
