### ISSUE TITLE
100% failed CSV or XML transaction Import leaves database marked as open when exiting MMEX

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3484]
MMEX version:
 - [x] 1.6.0 Alpha.1
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX Not tested
 - [ ] Linux  Not tested

# Description of the bug

If you import transactions from a CSV (or XML) file and the import fails completely (i.e. **all** lines are Errored), then the database is left marked as open when you exit MMEX and you get the MMEX Instance Check dialog when MMEX is next run.

The database is left in this open state _even_ if you successfully import transactions within the same session after initially doing the failed import.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

**Setup:**

1. Create a new database and add a Checking account. Do not create any transactions.
2. Create a Transactions.csv file containing:
14-05-2021,"Trans 1",£100.00,
18-05-2021,"Trans 2",£100.00,

**Case 1 - Complete Import failure:**

 3. File | Import | CSV Files...
 4. Set the fields as shown here. Note that the Date Format is deliberately set to YYYY/MM/DD so that it does **not** match the format of dates in the CSV. Setting the Import fields incorrectly is an easy error for new users to make.

![image](https://user-images.githubusercontent.com/4060092/119202993-f34b0d00-ba89-11eb-9f4e-d3da41331345.png)

 5. Click Import and note, as expected, that **all** lines in the CSV are Errored. This is important because if any of the lines are successfully imported then the bug does not occur.

![image](https://user-images.githubusercontent.com/4060092/119203474-06aaa800-ba8b-11eb-8830-e603195a8063.png)

 6. Click OK on the message to dismiss it.
 7. Click Cancel on the Import dialog to dismiss it.
 8. Exit MMEX.
 9. Restart MMEX and attempt to open the same database. Observe that the database was left marked as open, even though you exited cleanly.
 
![image](https://user-images.githubusercontent.com/4060092/119203758-c4359b00-ba8b-11eb-81df-600e3922d30f.png)

 10. Click Yes to continue.

**Case 2 - Complete Import failure followed by successful Import in the same session:**

 11. Repeat steps 3, 4, 5, and 6 from above to produce an Import failure.
 12. Now change the Date Format in the Import dialog to DD-MM-YYYY so that it matches the format of dates in the CSV.
 13. Click Import and note that the lines in the CSV have been imported.
 14. Click OK on the message to dismiss it.
 15. Click Cancel on the Import dialog to dismiss it.
 16. Observe that, as expected, there are two transactions shown in the account.
 17. Exit MMEX.
 18. Restart MMEX and attempt to open the same database. Observe that the database was left marked as open, even though you successfully completed an import (after the 100% failure) and exited cleanly.
 19. Click Yes to continue.
 20. Observe that there are **no** transactions shown in the account, i.e. the transactions from the successful import (plus any manual transaction entries or edits that a user may have made after that import) have been lost!
 
Expected result:

The database should not be left open when exiting after a 100% import failure.

Actual result:

A lot of frustration when I first started using MMEX and accidentally triggered this bug and lost a _lot_ of manual transaction edits after an import failure, followed by a successful import in the same session.

It seemed like a random failure at the time and it's taken a long time to discover the steps that lead to this bug occurring.

# Additional information

I have tested import of transactions from CSV and XML files; both can trigger this bug.

I have not, yet, tested QIF Import.

**Comment by tactilis** [comment]
I've found another way in which Import CSV/XML can incorrectly leave the database marked as open, and can therefore cause the loss of any subsequent manually entered transactions.

1. File | Import | CSV Files...
2. Select a .csv file and set up the Import dialog so that all the transactions in the file will be successfully imported.

3. Click Import and then on the confirmation dialog, click Cancel.

![image](https://user-images.githubusercontent.com/4060092/119350250-0252da80-bc97-11eb-84c5-82bfea29c728.png)

4. Now click Cancel on the Import dialog.

![image](https://user-images.githubusercontent.com/4060092/119350597-71303380-bc97-11eb-8713-54aadd86d4e1.png)

5. Exit MMEX.

6. Re-start MMEX. The Instance Check dialog is shown.

![image](https://user-images.githubusercontent.com/4060092/119351226-2b279f80-bc98-11eb-97c9-f0bee2d6e1eb.png)

Expected result:

The database should not be left open after cancelling a successful import.

Actual result:

Confused user and loss of data if s/he has done a subsequent successful import or manually entered any transactions in the same session _after_ cancelling the first import.

# Additional information

It seems that the common action between my two ways of provoking this bug is the Cancelling of the Import dialog, regardless of whether it was after a 100% Errored import or after a successful import.

**Comment by tactilis** [comment]
Nice work.

Tested. All good now.

**Comment by vomikan** [comment]
I have doubts that the correct algorithm is used in the end.
On import:
Begin
Savepoint("IMP");
.... save records .....
ReleaseSavepoint("IMP")

On cancel:
Begin
Savepoint("IMP");
.... save records .....
ReleaseSavepoint("IMP")
Rollback("")

The lack of Commit (in the first case) confuses me, although it works without it.
