### ISSUE TITLE
Report Questions 

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#3485]
V1.5.1

Hello

is there a possibility to use PHP in Report?

Can I use such a "filter-bar" too?
![2021-05-22 11_18_49-Window](https://user-images.githubusercontent.com/46572503/119221417-9eda7880-baef-11eb-9584-7edb8ced1135.jpg)

Can you recommend good websites of lua tutorials? 

Is there a list of internal variables, classes or functions that can be used?

Can I use the commands update and insert?

**Comment by vomikan** [comment]
It was mongoose web server integrated but removed.

**Comment by TomAff** [comment]
Whre do I have dot paste this?
{"&begin_date", "wxDatePickerCtrl", def_date, mmReportsPanel::RepPanel::ID_CHOICE_START_DATE, _("Begin date: ")},
    {"&single_date", "wxDatePickerCtrl", def_date, mmReportsPanel::RepPanel::ID_CHOICE_START_DATE, _("Date: ")},
    {"&end_date", "wxDatePickerCtrl", def_date, mmReportsPanel::RepPanel::ID_CHOICE_END_DATE, _("End date: ")},
    {"&only_years", "wxChoice", def_date, mmReportsPanel::RepPanel::ID_CHOICE_YEAR, _("Year: ")},


"It was mongoose web server integrated but removed."
Will it come back?

**Comment by vomikan** [comment]
There are 4 variable:
"&begin_date"
"&single_date"
"&end_date"
"&only_years"

You can use it in SQL. Sample:
```and strftime('%Y', c.TRANSDATE)= substr('&single_date', 1, 4)```

Result:
![image](https://user-images.githubusercontent.com/6836805/119454416-32ef4e80-bd41-11eb-93e3-0215d96e6754.png)
