### ISSUE TITLE
Import CSV dialog shows only the first 21 rows from the CSV file in the Preview pane

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3487]
MMEX version:
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Import CSV dialog shows only the first 21 rows from the CSV file in the Preview pane.

This is is a change from 1.3.6 which used to show all rows from the file and is causing user confusion when rows are to be ignored from the end of the file. See [https://forum.moneymanagerex.org/viewtopic.php?f=10&t=10406](https://forum.moneymanagerex.org/viewtopic.php?f=10&t=10406)

Is the change from showing all rows to just 21 rows an error in 1.5.1, or was there a reason for doing this?

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. See the detailed description in the MMEX forum post linked above.

Expected result:

The Import Preview pane should show all the rows from the CSV file and correctly indicate which will be ignored at the end.

Actual result:

The Import Preview pane shows only 21 rows from the CSV file and, if the file is longer, will indicate that the wrong rows are going to be ignored.

# Additional information

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/import_export/univcsvdialog.cpp#L1258
```
const int MAX_ROWS_IN_PREVIEW = 20; ```

**Comment by tactilis** [comment]
I tried to dig into the code and saw that MAX_ROWS const but I couldn't work out when the change was made or find the Issue describing _why_ it needed to be made (I'm still trying to learn to navigate around github).

MMEX 1.3.6 does not have the 20 (actually 21) row limit on the preview pane.

I've just extended my 'Fifty row import.csv' mentioned in the forum post to 500 rows and tried to import it using 1.3.6, which doesn't appear to have a row limit.  The preview pane takes slightly longer to refresh with 500 rows but it's still very usable on my 10 year old laptop.

The problem of limiting the rows displayed is that, as reported by the OP in the forum thread, MMEX shows the wrong rows being ignored if you set any 'Rows to ignore From end'.

The OP had a very particular use case in mind but the general one is to have a bank CSV file with...

```
Preamble line 1
Preamble line 2
Preamble line ...
Header line (Date, Payee, Deposit, Withdrawal, etc)
Transaction data line 1
Transaction data line 2
...
Transaction data line N
Postamble line 1
Postamble line 2
Postamble line ...
```

...and if the preview only shows 21 rows, then the user cannot see in the preview which Postamble lines are going to be ignored because it looks as though some of the Transaction data lines are going to be ignored.

Your thoughts?

**Comment by tactilis** [comment]
@vomikan
Is your change from MAX_ROWS_IN_PREVIEW = 20  to  MAX_ROWS_IN_PREVIEW = 50 intended just to be a temporary fix before a more permanent solution is applied in the future?

I'm still not sure what is wrong with the behaviour in 1.3.6 where the preview pane worked OK on a 500 line CSV on an old slow laptop.

I'm just a bit concerned that changing the MAX_ROWS to 50 simply pushes the reported problem of showing the wrong rows being ignored a bit further down the file, rather than correctly previewing them as was done in 1.3.6.

**Comment by tactilis** [comment]
^ Ignore the above.

I've tested it properly now. Your fix is perfect
