### ISSUE TITLE
MMEX Instance Check is not robust - it allows two copies of MMEX to open the same database

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3498]
MMEX version:
 - [x] 1.6.0 Alpha.1
 - [x] 1.5.1

Operating System:
 - [x] Windows
 - [x] Mac OSX  
 - [ ] Linux Not tested

# Description of the bug

It is possible to run two copies of MMEX on the same database without the Instance Check dialog being displayed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Run MMEX and click Open Last Opened Database on the App Start dialog.

![image](https://user-images.githubusercontent.com/4060092/119401058-e2d9a300-bcd2-11eb-9162-a4cf5660104e.png)

2. Leave the above MMEX instance running and run a second copy. Again, click Open Last Opened Database. The Instance Check message will be displayed as expected.

![image](https://user-images.githubusercontent.com/4060092/119403005-a52a4980-bcd5-11eb-93b8-7d3122de7338.png)

3. Click No. The App Start dialog will be displayed again.

4. Click Open Last Opened Database. This time the Instance Check does not get displayed and the 2nd copy of MMEX also opens the database.

Expected result:

At step 4, I would expect the Instance Check to be displayed again because the first instance of MMEX still has the database open.

Actual result:

No Instance Check displayed and the 2nd copy of MMEX opens the database.

# Additional information

Either the 'database in use' indicator is being cleared at the wrong time, or the instance checking logic is wrong because it is possible to run two copies of MMEX on the same database even though you previously clicked No.

**Comment by whalley** [comment]
Yes, the database lock is released when we call `void mmGUIFrame::ShutdownDatabase()`, unfortunately this is called whenever the DB is closed irrespective of whether the application terminated normally or as a result of the file open being aborted due to the lock being in place (we need to open the database to check for the lock).

Need to add a bit of logic to pass the fact that the DB was closed early because of this case and not release the lock.

**Comment by tactilis** [comment]
Tested. All good now.

**Comment by tactilis** [comment]
Spoke too soon. There's still a hole in the checking logic of this build to do with opening Recent Files.

1. Create 2 databases: A.mmb and B.mmb and have MMEX configured to display the App Start dialog.

2. Run 1st instance of MMEX
On the App Start dialog  Open Existing Database | Select A.mmb
Leave this instance of MMEX running

3. Run 2nd instance of MMEX
On the App Start dialog  Open Existing Database | Select B.mmb

4. Using the 2nd instance of MMEX:
File | Recent Files... | A.mmb
The Instance Check dialog is displayed because A.mmb is open in the 1st instance of MMEX.

5. On The Instance Check dialog, click No
The the App Start dialog is displayed.

6. On the App Start dialog   Open Existing Database | Select A.mmb
Observe that A.mmb opens in the 2nd instance of MMEX even though it is still open in the 1st instance.

7. In the 2nd instance of MMEX you can now swap freely between:
File | Recent Files... | B.mmb  and  File | Recent Files... | A.mmb  with no Instance Check displayed.
