### ISSUE TITLE
Transaction display - after adding a transaction

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#3499]
MMEX version:
 - [x ] 1.6.0 alpha-1

Operating System:
 - [x ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Think this or something similar might have been raised before but I could not find a hit on the keywords I used for search so apologies if it has.

There appears to be a change to how new transactions are displayed after adding..
1. Display an account (type checking for me) with more transactions than will fit on the page and which is in ascending date order so latest date is at bottom of display.
2. Add a new transaction with todays date and display does not change so have to scroll down one line to display

Previous behaviour on 1.3 and 1.4 was for the display to scroll forward automatically as part of the transaction being added, not sure when this changed on the 1.5/1.6 branch

Obviously not a show stopper just a tad annoying

Is the bug reproducible? 
 - [x ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by vomikan** [comment]
#3372

**Comment by vomikan** [comment]
It's working as expected for me. Except new transaction does not selected.

**Comment by grumpy235** [comment]
Looks like things are a bit more subtle..

1. Display account and ensure display shows latest entry at the bottom of display and sort on Date ascending
2. Hit new button, fill in details and hit save
3. If the previous last entry was NOT marked as Reconciled then new entry is not shown until you scroll down, if it WAS marked as Reconciled then it is displayed after hitting save

Not sure if it has an effect but I have got "Ignore Future Transactions" checked in Options

Just tried with Date descending so latest entry at the top of the display and that works fine for both of the above scenarios

**Comment by vomikan** [comment]
Confirm

**Comment by grumpy235** [comment]
@vomikan - Many thanks for speedy response, works just fine now
