### ISSUE TITLE
Import from CSV not possible

### ISSUE THREAD

**Issue by kosi2801** [moneymanagerex/moneymanagerex#350]
In 1.2.0-Alpha.1 it seems impossible to import transactions from CSV. No matter how I configure the import fields, it always skips every line with:
 "One of the following fields: Date, Amount, Type is missing, skipping".
As Date and Amount are set in my fields and "Type" is not available in the fields list I guess this is a bug.

Somehow the checks for the required fields seem inconsistent in respect to "Type" elsewhere too, if an import attempt is done without selecting any fields, only "Date" and "Amount" are reported as missing.

**Comment by vomikan** [comment]
Csv sample please

**Comment by kosi2801** [comment]
Csv is with header line and in german, I hope that's not a problem. Import was tried with semicolon as delimiter. Below are two example lines, one outgoing and one incoming transfer (acct. no and transfer id scrambled by me but structure ok). 
Meanwhile I tried a bit around with more fields and different assignments but in my attempts I couldn't succeed. There just seems to be no "Type" field (or one which is interpreted as this) and I'm also unsure which column from the Csv to assign if it were there.

```
Bezeichnung;Valutadatum;Auftraggeber;Auftraggeber BLZ/BIC;Auftraggeber Kontonr./IBAN;Betrag;Ersterfassungsreferenz;Kundendaten/Zahlungsreferenz;Partnername;Partner BLZ/BIC;Partner Kontonr./IBAN;Buchungsdatum;Umsatzzeile 1;Umsatzzeile 2;Zusatztext
"AT    45,85 Maestro POS 05.03.13 19.51K2 TANKE 1324 ABCABC 1324 040";"05.03.2013";"";12345;1234567890;"-45,85";123451234567ALB-123451234567;;"";54321;5432154321;"06.03.2013";"AT    45,85 Maestro POS 05.03.13 19.51K2";"TANKE 1324 ABCABC 1324 040";""
"Guthabenzinsen ";"31.12.2014";"";12345;1234567899;"9,18";123451234567AB1-P12345123456;;"";54321;5432154321;"31.12.2014";"Guthabenzinsen";"";""
```

**Comment by vomikan** [comment]
I've imported this CSV sample successfully.
I'used the next settings:
0 - 6 - Notes
1 - 7 - Don't Care
2 - 7 - Don't Care
3 - 7 - Don't Care
4 - 7 - Don't Care
5 - 2 - Amount(+/-)
6 - 7 - Don't Care
7 - 7 - Don't Care
8 - 7 - Don't Care
9 - 7 - Don't Care
10 - 7 - Don't Care
11 - 0 - Date
Date mask: DD.MM.YYYY

**Comment by kosi2801** [comment]
Ok, this is quite puzzling to me. Which regional settings are set on your machine? Or asked differently: does MMEX expect the Amount decimal delimiter to be "," or "." depending on regional settings?
Is the "Type" field somehow determined internally and if so, what does it depend on?

Are you maybe using a custom build or later MMEX version or did you test with the install package for 1.2.0-Alpha.1 ?

**Comment by vomikan** [comment]
I've made some changes to make settings saving more correct. Nad I used
latest development code.
1.2.0-beta will be available soon.

2015-01-12 16:02 GMT+03:00 kosi2801 <notifications@github.com>:

**Comment by kosi2801** [comment]
Ok, I'll wait for the updated version then and retest.
Am 12.01.2015 14:24 schrieb "Nikolay" <notifications@github.com>:

**Comment by guanlisheng** [comment]
@kosi2801 , any update here and could i close this issue after beta release?

**Comment by kosi2801** [comment]
I retested with 1.2.0-Beta and the field mapping you suggested. Yet no luck, the issue still persists for me.

```
Currency: EURO
Bezeichnung;Valutadatum;Auftraggeber;Auftraggeber BLZ/BIC;Auftraggeber Kontonr./IBAN;Betrag;Ersterfassungsreferenz;Kundendaten/Zahlungsreferenz;Partnername;Partner BLZ/BIC;Partner Kontonr./IBAN;Buchungsdatum;Umsatzzeile 1;Umsatzzeile 2;Zusatztext
"AT    45,85 Maestro POS 05.03.13 19.51K2 TANKE 1324 ABCABC 1324 040";"05.03.2013";"";12345;1234567890;"-45,85";123451234567ALB-123451234567;;"";54321;5432154321;"06.03.2013";"AT    45,85 Maestro POS 05.03.13 19.51K2";"TANKE 1324 ABCABC 1324 040";""
"Guthabenzinsen ";"31.12.2014";"";12345;1234567899;"9,18";123451234567AB1-P12345123456;;"";54321;5432154321;"31.12.2014";"Guthabenzinsen";"";""

Line: 1 One of the following fields: Date, Amount, Type is missing, skipping
Line: 2 One of the following fields: Date, Amount, Type is missing, skipping
Line: 3 One of the following fields: Date, Amount, Type is missing, skipping
Total Lines : 3
Total Imported : 0

Log file written to : C:\Users\Kosi\AppData\Roaming\MoneyManagerEx\tst.txt
```

Any more suggestions? What else could I try or check?

**Comment by guanlisheng** [comment]
@vomikan , would you mind to take a deep look ?

**Comment by vomikan** [comment]
Date mask is OK?

четверг, 15 января 2015 г. пользователь Lisheng написал:

**Comment by kosi2801** [comment]
Aaaah, I think I got it. I did never change/select the date mask as it already correctly showed "DD.MM.YYYY". 
But when I open the dropdown and select the same value "DD.MM.YYYY" again suddenly the import works correctly. See the log where I did just select the same value before the second attempt.
```
Bezeichnung;Valutadatum;Auftraggeber;Auftraggeber BLZ/BIC;Auftraggeber Kontonr./IBAN;Betrag;Ersterfassungsreferenz;Kundendaten/Zahlungsreferenz;Partnername;Partner BLZ/BIC;Partner Kontonr./IBAN;Buchungsdatum;Umsatzzeile 1;Umsatzzeile 2;Zusatztext
"AT    45,85 Maestro POS 05.03.13 19.51K2 TANKE 1324 ABCABC 1324 040";"05.03.2013";"";12345;1234567890;"-45,85";123451234567ALB-123451234567;;"";54321;5432154321;"06.03.2013";"AT    45,85 Maestro POS 05.03.13 19.51K2";"TANKE 1324 ABCABC 1324 040";""
"Guthabenzinsen ";"31.12.2014";"";12345;1234567899;"9,18";123451234567AB1-P12345123456;;"";54321;5432154321;"31.12.2014";"Guthabenzinsen";"";""

Currency: EURO
Line: 1 One of the following fields: Date, Amount, Type is missing, skipping
Line: 2 One of the following fields: Date, Amount, Type is missing, skipping
Line: 3 One of the following fields: Date, Amount, Type is missing, skipping
Total Lines : 3
Total Imported : 0

Log file written to : C:\Users\Kosi\AppData\Roaming\MoneyManagerEx\tst.txt

Imported transactions discarded by user!%d.%m.%Y
Line: 1 One of the following fields: Date, Amount, Type is missing, skipping
Added payee: Unknown
Line : 2 imported OK.
Line : 3 imported OK.
Total Lines : 3
Total Imported : 2

Log file written to : C:\Users\Kosi\AppData\Roaming\MoneyManagerEx\tst.txt

Imported transactions have been flagged so you can review them.Imported transactions discarded by user!
```

Seems that the date format is not correctly transfered to the input routine if the dropdown is never touched. 

PS.: nevertheless, the error log line referring to a "type" field should be changed, at least I have been mislead in the search of the cause quite a bit.

**Comment by guanlisheng** [comment]
I will close it and feel free to reopen it
