### ISSUE TITLE
Fonts in Navigation not visible

### ISSUE THREAD

**Issue by rony925** [moneymanagerex/moneymanagerex#3510]
MMEX version:
 - [ ] 1.5.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Mac OSX Big Sur
 

# Description of the bug

The fonts in the navigation panel are all white same as the background.
I can see only icons no text.
[
<img width="1680" alt="Screen Shot 2021-05-26 at 3 48 01 AM" src="https://user-images.githubusercontent.com/15120867/119566398-4c41da80-bdd5-11eb-8964-8b99fb564e45.png">
]

# Reproduction

Is the bug reproducible? 
 - [ ] Always 

Reproduction steps:

1. Just start the app and it shows as the screenshot
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
#3364

**Comment by vomikan** [comment]
Someone should create black theme
https://github.com/moneymanagerex/themes

**Comment by whalley** [comment]
Agreed. There is a way, certainly on MacOS to determine via the APIs, if Dark Mode is being used. Once somebody creates a default Dark Mode theme we could perhaps use that as the default theme if no other theme selected.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1779
