### ISSUE TITLE
Display the difference value as a line on Income vs Expenses report

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3515]
# Description of the feature

Display the monthly difference value as a line on the "Income vs Expenses" / "Monthly" report. It then aligns better with the report table.

![image](https://user-images.githubusercontent.com/487345/119715702-30cde280-be5c-11eb-9b19-97210de9fee1.png)

**Comment by vomikan** [comment]
I had in mind exactly the same chart for the budget.

https://github.com/moneymanagerex/moneymanagerex/issues/2130
