### ISSUE TITLE
[Att.] is added in notes

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#3517]
MMEX version: 1.5.1
Operating System: Windows

If you change the status of a transaction with an attachment by using the keys R F V... 
[Att.] is added to the notes-field everytime.
![2021-05-27 07_28_04-Window](https://user-images.githubusercontent.com/46572503/119771356-dc5b4f00-bebd-11eb-8999-061e9182cdf9.jpg)

**Comment by tactilis** [comment]
Same incorrect behaviour in latest 1.6.0 Alpha.1

**Comment by TomAff** [comment]
Where can I get 1.6.0 Alpha.1?

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/119805790-3d991780-beea-11eb-8315-af86f6cd2821.png)

![image](https://user-images.githubusercontent.com/6836805/119805880-5acde600-beea-11eb-9b46-d1bf6a52b9f5.png)

**Comment by tactilis** [comment]
@TomAff

As @vomikan said, or go directly here [https://ci.appveyor.com/project/moneymanagerex/moneymanagerex](https://ci.appveyor.com/project/moneymanagerex/moneymanagerex) and look at 'History' for latest merge into master.

Select Platform: x64, then Artifacts.

I'd suggest that you download the portable build because then you can run that as well as keeping your 1.5.1 installed.

**Comment by TomAff** [comment]
Thanks a lot. I use the portable Version since years. It is easy to Update and easy to backup.

The last months I use MMEX more intensiv, creating reports and try to use a lot of feature.

I'm looking forward to every new Version

**Comment by vomikan** [comment]
Possible performance degradation
![image](https://user-images.githubusercontent.com/6836805/119870383-fd598980-bf29-11eb-9892-7821bda1b44e.png)

**Comment by TomAff** [comment]
I'll try to reproduce it as I understand it.
The info, that there is an attachment is loaded into the cache and only output as info in the notes column? It is not saved in the notes field normaly?

When changing the status by pressing key (UFVRD) in the overview, only the "Status" field should be updated. The other fields do not. That should solve the problem.
Or maybe just change the output.
If attachment then notes = [Att.] & Data of the Notesfield

**Comment by vomikan** [comment]
Everything should be OK now

**Comment by dbolton** [comment]
FYI, The download page of the main website has links and instructions for downloading the latest stable build: https://www.moneymanagerex.org/download#Unstable
