### ISSUE TITLE
The Date Format on Export CSV dialog incorrectly affects date display in the account transaction list

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3518]
MMEX version:
 - [x] 1.6.0 Alpha.1

The behaviour does not appear to affect 1.5.1

Operating System:
 - [x] Windows

# Description of the bug

The date format selected on the Export CSV dialog incorrectly affects the date display in the account transaction list.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Create a new database with a Checking account.
2. Set the date format in Options to YYYY-MM-DD as shown and restart MMEX to ensure that the option is applied throughout.

![image](https://user-images.githubusercontent.com/4060092/119825217-9f5b8080-beee-11eb-9287-d8c1512e166f.png)

3. Enter 3 transactions. Note that the date format is as expected.

![image](https://user-images.githubusercontent.com/4060092/119825608-0c6f1600-beef-11eb-8e49-f1da78429f7b.png)

4. File | Export | CSV Files...
Set the export date format to DD/MM/YYYY and then click Cancel to dismiss the dialog.

![image](https://user-images.githubusercontent.com/4060092/119832985-9d95bb00-bef6-11eb-885c-30d7475e4437.png)

5. Carefully move the mouse pointer upwards until it hovers over the _last_ transaction in the list.
BUG: Observe that the date format for that transaction wrongly changes to DD/MM/YYYY

![image](https://user-images.githubusercontent.com/4060092/119829024-b43a1300-bef2-11eb-8e8e-3ac0fc0185f6.png)

6. Exit MMEX and restart.
The date format in the transaction list returns to YYYY-MM-DD as expected.

7. Repeat step 4 above.

8. This time, carefully move the mouse pointer across to the Navigation pane, upwards to the toolbar then across and downwards through the transactions until it hovers over the _last_ transaction in the list.
BUG: Observe that the date format for only the _last_ transaction wrongly changes to DD/MM/YYYY

![image](https://user-images.githubusercontent.com/4060092/119830336-0fb8d080-bef4-11eb-9814-652cbaec4aa6.png)

9. Repeat step 6.

10. Click the Date column header to sort the transactions in reverse date order so that the most recent transaction is at the top. 

11. Repeat step 4.

12. Carefully move the mouse pointer upwards until it hovers over each of the transactions in the list.
This time observe that the date format for _first_ transaction in the list wrongly changes to DD/MM/YYYY

![image](https://user-images.githubusercontent.com/4060092/119834650-0cbfdf00-bef8-11eb-84cb-19ccc5602164.png)

So, it appears that it is the transaction with the most recent date that is affected regardless of where it is displayed in the list.

Expected result:

The Date Format chosen on the export dialog should not affect the date format shown in the transaction list.

Actual result:

As described above.

**Comment by vomikan** [comment]
The reason is that the dates that were previously used are displayed from the cache.
We need to think about how to clear the cache before and after the import.
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/util.cpp#L312-L330

**Comment by tactilis** [comment]
@vomikan
> We need to think about how to clear the cache before and after the _import_.

OK - but to be clear, I was not able to provoke this bug for:

Import of CSV / XML / QIF

or

Export of XML / QIF / JSON

Only for _Export_ of CSV.

It may be lurking for the other types of export and imports, but I couldn't find the the path to trigger it .
 
 
Some other news:  After a lot of experimentation with import & export for this bug, I did manage to provoke the 'bad allocation' that we spoke about yesterday...

![image](https://user-images.githubusercontent.com/4060092/119851513-5dd6cf80-bf06-11eb-9265-32a039ff7ae2.png)

...so in time I may be able to find a repeatable sequence of steps to reproduce this.

Is it feasible that this is related to the display from cache problem? Or do you think it is likely to be something else entirely and just coincidence that I got it here?

**Comment by vomikan** [comment]
>Is it feasible that this is related to the display from cache problem? Or do you think it is likely to be something else entirely and just coincidence that I got it here?

This should be checked after my correction.

**Comment by tactilis** [comment]
@vomikan Your fix looks good. No changes to date format now.

Well spotted the duplicate DD.MM.YYYY format.

![image](https://user-images.githubusercontent.com/4060092/119943195-9cae6900-bf8a-11eb-8799-30c56d06ab04.png)

I suspect that one of them was actually intended to be DD,MM,YYYY like the DD,MM,YY and DD.MM.YY pair in the lines above.

**Comment by tactilis** [comment]
I haven't seen the 'bad allocation' error since you made this fix, however I can't see anything in that area that could have been responsible for it, so maybe it's still there but masked. I'll keep a watch for it.
