### ISSUE TITLE
Loss of colour in Graphs 

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#3527]
MMEX version:
 - [ ] 1.5.x
 - [x] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Minor issue which you may well have already found with Master at ce612a4.
Income expenses applet on home page has lost its colour
![Capture](https://user-images.githubusercontent.com/24897056/120014727-5123ab80-bfda-11eb-905d-095f1333f6a0.PNG)

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by grumpy235** [comment]
@vomikan - just checked and all graphs are now grey

**Comment by vomikan** [comment]
It's seems OK now.
Working with the following JSON:
```
{
  "theme": {
    "name": "MMEX Default Theme",
    "author": "MMEX Team",
    "description": "This is the default MMEX theme and uses the MMEX colour scheme. It is a simple 'duo color' theme",
    "url": "https://github.com/moneymanagerex/themes/blob/master/system-themes/default/README.md"
  },
    "colors": {
        "navigationPanel": ""
    } 
}
```
