### ISSUE TITLE
lunasvg version

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3528]
https://github.com/sammycage/lunasvg/issues/45#issuecomment-850509427

**Comment by whalley** [comment]
@vomikan Is this really on hold? Is it not complete?

**Comment by vomikan** [comment]
This patch not relesed yet https://github.com/sammycage/lunasvg/pull/59/files

**Comment by whalley** [comment]
Lunasvg no longer used.  https://github.com/moneymanagerex/moneymanagerex/issues/3779
