### ISSUE TITLE
lunasvg library upgrade

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3532]
https://github.com/sammycage/lunasvg/tags

v1.4.1                                                                                                                        v1.4.2                                                                                                                        v2.0.0                                                                                                                        v2.0.1  

the function ```bitmap = document->renderToBitmap(i.second, i.second, 96.0 /* lost color */);```

**Comment by sammycage** [comment]
I made incompatible changes to the LunaSVG

Here are some important ones:

1. Change svgdocument.h to document.h
2. Change lunasvg::SVGDocument to lunasvg::Document
3. loadFromData and loadFromFile is now a static function that returns std::unique_ptr
4. DPI parameter has been removed from ``

**Comment by sammycage** [comment]
Change https://github.com/moneymanagerex/moneymanagerex/blob/bbac8cad1dab150d22891fa20a12c240af6b1178/src/images_list.cpp#L35

To

```cpp
#include "../3rd/lunasvg/include/document.h"
```

And

https://github.com/moneymanagerex/moneymanagerex/blob/bbac8cad1dab150d22891fa20a12c240af6b1178/src/images_list.cpp#L368-L389

To

```cpp
                std::unique_ptr<lunasvg::Document> document = lunasvg::Document::loadFromData(static_cast<char *>(buffer->GetBufferStart()), buffer->GetBufferSize());
                if (!document)
                    continue;
        
                int svgEnum = iconName2enum.find(fileName)->second.first;

                std::uint32_t bgColor = 0;
                if (iconName2enum.find(fileName)->second.second)
                    bgColor = bgStringConv;

                lunasvg::Bitmap bitmap;

                // Generate bitmaps at the resolutions used by the program - 16, 24, 32, 48

                for (const auto& i : sizes)
                {
                    bitmap = document->renderToBitmap(i.second, i.second, bgColor);
                    if (!bitmap.valid())
                        continue;
                    programIcons[i.first][svgEnum] = CreateBitmapFromRGBA(bitmap.data(), i.second);
                }
```

**Comment by vomikan** [comment]
@sammycage thank you very much.

**Comment by vomikan** [comment]
'make_unique' is not a member of 'std'
