### ISSUE TITLE
Credit Card balance of zero displayed as negative in ledger and Home page

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#3538]
MMEX version:
 - [ ] 1.5.x
 - [X] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Minor display irritant which for me only applies to Credit Card Accounts, Term and Checking are fine.

What I owe is shown as a negative balance and appears in red on the Home Page - expected, however Reconciled is shown as -0.00 and if I pay off balance completely then balance is now shown as -0.00 as well so still appears in red
![Capture](https://user-images.githubusercontent.com/24897056/120095534-6dc8fc00-c11e-11eb-9aaf-2f282f4bb3ce.PNG)

I guess ensuring zero has a positive sign will fix the display?

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
I couldn't recreate this in 1.6.0 Alpha.1.  Are you running the latest?

![image](https://user-images.githubusercontent.com/4060092/120095873-4ffc9680-c120-11eb-806d-3fd81b10f938.png)

Do you have multiple credit card accounts?

Are you able to share full details of the Home page and of those accounts?

**Comment by tactilis** [comment]
Reproducing your balances:

![image](https://user-images.githubusercontent.com/4060092/120096297-93580480-c122-11eb-95f4-94329d5fb7ec.png)

**Comment by grumpy235** [comment]
@tactilis Running current master (eeeb55f) with LUA and wxsqlite3 at latest version. I'll try the latest GA version.
One thought with your test did you force any counting to be done i.e. some debits/credits? If "Credit" was just initial setup and "Credt2" was just one debit after initial setup then I would expect to see what you see

**Comment by grumpy235** [comment]
@tactilis Just downloaded from SourceForge
Version: 1.5.1 64-bit
• Build on Apr 24 2021 14:32:48
and I now get what you see so something has changed in 1.6.0 Alpha
![Capture](https://user-images.githubusercontent.com/24897056/120097800-67d91800-c12a-11eb-87b5-44188a90c81e.PNG)

**Comment by tactilis** [comment]
@grumpy235 
>Running current master ([eeeb55f](https://github.com/moneymanagerex/moneymanagerex/commit/eeeb55fd60739ad8e5f839c3c03149b5adf04a5f))

Same build here.

> One thought with your test did you force any counting to be done i.e. some debits/credits? If "Credit" was just initial setup and "Credt2" was just one debit after initial setup then I might expect to see what you see

I had debits and credits.

![image](https://user-images.githubusercontent.com/4060092/120098244-9ce66a00-c12c-11eb-8104-5a5fc8486e12.png)

![image](https://user-images.githubusercontent.com/4060092/120098273-d323e980-c12c-11eb-993c-54317b5981ca.png)

![image](https://user-images.githubusercontent.com/4060092/120098219-80e2c880-c12c-11eb-9b5e-605374bad992.png)

 
Clearly, I don't have the transactions that you have.

Are you able to upload your database?
Make a copy of the .mmb and remove any personal details from the transactions. Also **pare the transactions down** to the minimum set that triggers the unwanted display on the Home page.

**Comment by grumpy235** [comment]
@tactilis Not keen on uploading my database as it has 20+ years of data. Will try and reproduce with a test database. Something has changed as **1.5.1 works** for me but 1.6.0 Alpha does not. On Account display zero appears as 0.00 on 1.5.1 and -0.00 on 1.6.0 Aplha so it is consistant :-)

**Comment by vomikan** [comment]
It's not depend on an account type.

**Comment by grumpy235** [comment]
@vomikan - hoped you might work your magic :-)

**Comment by grumpy235** [comment]
@vomikan sorry for not picking up on the previous issue #564, I always have had a problem with knowing which keywords to search a problems database for. Annoying thing is I remember reading #2509 when it was raised. I assumed my problem might have been due to floating point rounding but got even more confused when a new database did not show the same symptom. Some applications I worked with years ago always used integer arithmetic and then shifted the decimal place to the correct position to remove this issue. However as you mention in #2509 this only works for certain situations and 2 or 3 decimal places else you were limiting the size of the numbers you could work with which for crypto with 6 decimal places would be a big problem

**Comment by grumpy235** [comment]
@vomikan unfortunately your latest fix does not clear my problem, however the code in #2509 using ROUNDING_ERROR_f32 works just fine

**Comment by grumpy235** [comment]
@vomikan Many thanks works fine now
