### ISSUE TITLE
Account initial balance is not dated

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3554]
MMEX version:
 - [X] 1.5.x
 - [X] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [X] Mac OSX
 - [X] Linux 

# Description of the bug

If an initial balance is entered for a new account, then this value is shown over all months/years in the "Summary of Accounts" report, because it is not possible to enter an account opening date.

https://forum.moneymanagerex.org/viewtopic.php?f=8&t=10409

**Comment by whalley** [comment]
Would need a DB change to support this.

If implemented we would need to consider existing accounts with an opening balance. In this case we could set the opening date to the date of the earliest transaction on the account (or if no transactions exist use the date of the earliest transaction in the database). Obviously not going to catch all dates correctly, but should handle moist cases.

Or should we consider creating an "Opening Balance" transaction against accounts - need to consider what PAYEE / CATEGORY we use though for this.

Views?

**Comment by tactilis** [comment]
> If implemented we would need to consider existing accounts with an opening balance. In this case we could set the opening date to the date of the earliest transaction on the account (or if no transactions exist use the date of the earliest transaction in the database).

Do you see this as:

a) A one-off setting of the opening date for existing accounts when the new MMEX version is first run and the database is upgraded?
b) A dynamic query, so that for accounts without an opening date, you query the earliest transaction in the account (or the DB).

Option a) should be OK for most users with existing well established accounts because they will contain historical transactions and it is unlikely that the user will subsequently add any transactions _earlier_ than the current earliest transaction date in each account. Option b) would allow for the addition of earlier transactions and would dynamically 'set' the opening date according to what is in the account regardless of what the user does with their transactions, so is arguably 'more correct'. However option b) would be more complex to code and would forever carry the baggage of the current no-opening-date implementation.

 
> Or should we consider creating an "Opening Balance" transaction against accounts - need to consider what PAYEE / CATEGORY we use though for this

I don't favour this approach:
- Would the user be able to delete this special "Opening Balance" transaction or would you have to add code to prevent this?
- What if the user tried to copy/paste it? Or would you have to prohibit this?
- etc

Seems more complicated and harder to get right than your first approach.


> but should handle moist cases.

I regard that as a damp squib  :grinning:

**Comment by vomikan** [comment]
The initializing transaction is quite applicable without changing the database structure. And this technology I met when importing QIF files from other programs. You can make a separate status for such transactions. But we must remember that there is an Android port of our application. Judging by the activity, it is not developing at the moment, but still has a large audience.

https://github.com/moneymanagerex/moneymanagerex/issues/1678

**Comment by renato-mmex** [comment]
**my suggestion would be to remove the opening balance in all accounts.**
Reason: if you enter the balance with an opening entry, this problem does not arise. This would also solve the problem of the foreign exchange rate of this entry. Of course, the exchange rate would have to be entered manually.
But this would also require adjusting the description.

**Comment by vomikan** [comment]
It seems that  an "Opening Balance" transaction the best solution.
The DB structure may be updated without DB vertion upgrade.

Another solution is to count the date of the account balance for the first transaction in the account (if empty, then the current date).

**Comment by whalley** [comment]
We need to make sure this cannot be deleted, is not considered as income/expense in reports,  Payee = "Opening Balance", and a category = "Opening Balance" ? Think we need to carefully outline the rules for this 'special' transaction.

**Comment by tactilis** [comment]
As mentioned earlier:

- Would the user be able to delete this special "Opening Balance" transaction or would you have to add code to prevent this?

- What if the user tried to copy/paste it? Or would you have to prohibit this?

Also:

- Prohibit Duplicate transaction

- Prohibit Move transaction

And:

What are the rules regarding Exporting and Importing an Opening Balance transaction?

**Comment by renato-mmex** [comment]
My concern is that we are increasingly complicating MMEX. The "normal" users, for whom I believe MMEX was created, will soon feel overwhelmed and turn away from MMEX.
After all, an opening balance sheet is only required from larger companies. I would appreciate it if we would first work out a solution / description for this case before we change / realize anything.

**Comment by whalley** [comment]
> After all, an opening balance sheet is only required from larger companies.

Not at all.. New users will likely be adding accounts to MMEX from existing accounts with an existing balances and then adding in new transactions.

**Comment by renato-mmex** [comment]
That is correct, but this is a transfer of account balances and not an opening balance.
.
From my point of view, it must be ensured that these amounts have a posting date and a corresponding exchange rate (for foreign currencies), otherwise some of the evaluations of MMEX are wrong.

**Comment by vomikan** [comment]
The sample of  Quicken QIF file:
```
!Option:AutoSwitch
!Account
NChecking 1
TBank
^
NChecking 2
TBank
^
!Clear:AutoSwitch
!Option:AutoSwitch
!Account
NChecking 1
TBank
^
!Type:Bank 
D1/ 1'18
U0.00
T0.00
CX
POpening Balance
L[Checking 1]
^
D1/ 5'18
U85,000.00
T85,000.00
PPayer #1
LConsulting Income (Business)
```

https://github.com/moneymanagerex/moneymanagerex/issues/2132

**Comment by whalley** [comment]
If we add a new `TRANSCODE` of 'Opening Balance' that will be clean. We then use this instead of acocunt opening balance. Then need to validate use of this in other code to make sure it does not make assumptions that Deposit/Withdrawal/Transfer are the only options.

**Comment by tactilis** [comment]
@renato-mmex
> After all, an opening balance sheet is only required from larger companies.

I don't agree. It's common for normal users to have to do this.

For example, when I started using MMEX, I created checking accounts, credit card accounts, etc to reflect my real world accounts and had to set the initial balance (i.e. opening balance) to match the amount I had in each account. Thereafter, I downloaded transactions as CSV files from the bank and imported them into MMEX.

>  but this is a transfer of account balances and not an opening balance.

Maybe we are talking about different things? I don't understand where a 'transfer of balances' comes in to this? As far as MMEX is concerned this is an initial (i.e. opening) balance for an account _in MMEX_. It doesn't matter what has happened in the real world account prior to it being created in MMEX.

> My concern is that we are increasingly complicating MMEX. The "normal" users, for whom I believe MMEX was created, will soon feel overwhelmed and turn away from MMEX.

I can't see any more complexity here than is actually required. An account must have an opening balance, either set in the Edit Account dialog (as is done now - but with a date field added), or in a proposed new Opening Balance transaction. If MMEX uses the latter approach then certain rules will need to enforced by MMEX (by greying out the relevant menus) to prevent the special transaction being deleted, duplicated, etc.

The hard work is in the code. The presentation of it can be kept simple for the user.

**Comment by vomikan** [comment]
>If we add a new TRANSCODE of 'Opening Balance' that will be clean.

Yep. It does not crash the app. But mmex interprets this as a withdrawal.
![image](https://user-images.githubusercontent.com/6836805/122093655-f67cb300-ce13-11eb-86fd-2ab98c2b43cb.png)

**Comment by whalley** [comment]
I'll pick this one up.

**Comment by whalley** [comment]
Having thought about this and considered the upgrade options I'm thinking that just adding an opening balance date is probably the simplest route here that will have minimal end user impact.

- If we were to add a new CHECKINGACCOUNT transaction for the opening balance (from the current account opening balance) then:
  - We would need to shift the existing transactions down (i.e. change TRANSID) as just adding a new transaction on the same date as first transaction on the account would mean the opening balance item would be after the first existing item (sorted by DATE/ID).
  - This would mean any TRANSLINK, SPLITTRANSACTIONS, CUSTOMEFIELDDATA would need adjusting also.
  - Any attachment files would need renaming to for adjusted TRANSID
  - Areas such as transaction dialog would need amending to disallow deletion of the opening balance entry and allow it to be defined with no PAYEE or CATEGORY - otherwise payee and category reports would wrongly report these.
  - The above (and possibly other areas) would need to have quite a bit of testing to make sure we have not missed any logic that previously just expected WITHDRAWAL/DEPOSIT transaction types.

- Adding the extra date just has a one-time upgrade hit, and an enhancement for reports that need to know the opening date - e.g. "Summary of Accounts". The core logic we have is unchanged.

**Comment by whalley** [comment]
**Proposed changes**

DB upgrade script will pull date of first transaction and if no transactions will use current date.
```
alter table ACCOUNTLIST_V1 add column INITIALDATE text;
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID order by TRANSDATE asc limit 1 );
update ACCOUNTLIST_V1 set INITIALDATE = date() where INITIALDATE is null;
```

Add new field to account dialog
![CleanShot 2022-09-26 at 19 59 33](https://user-images.githubusercontent.com/487345/192358242-9f8586c2-2a0c-4976-b663-92d2a64351f6.png)

Suggested validation logic:

- When editing the account opening date it will not be possible to set a date greater than the date of the first transaction on the account
- When entering a transaction involving the account it will not be possible to set a transaction date earlier than the opening date

Summary of Accounts report will be amended to take notice of the account opening date.

**Comment by tactilis** [comment]
@whalley
> DB upgrade script will pull date of first transaction and if no transactions will use current date.

Will the DB upgrade script apply to a specific version only? For example, when 1.5.23 is run and opens an .mmb that has not yet been upgraded?

Or will the upgrade script also be included in 1.5.24, 1.5.25, 1.5.26... so that users who upgrade MMEX only occasionally and miss 1.5.23 the release still have their databases upgraded?

Assuming the latter, at what point will the upgrade script no longer be included in an MMEX release?

**Comment by whalley** [comment]
DB upgrade scripts are retained forever to allow upgrade from any prior version to latest. 

E.g latest generate upgrade code is here - https://github.com/moneymanagerex/moneymanagerex/blob/master/src/db/DB_Upgrade.h

**Comment by whalley** [comment]
Having tested the DB upgrade scripts it needs a bit of tweaking... :-)
1. If a transfer to the account occurs as the first entry then this is not picked up
2. Investment/stock accounts use a different table

Need to brush up on my SQL :-)

**Comment by whalley** [comment]
All DB changes and support for new opening balance added here - https://github.com/whalley/moneymanagerex/commit/564f265756c985ca79c6a17777751af1f262525c

The reporting now needs updating. to use the date.
