### ISSUE TITLE
Group separator using locale

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#3557]
MMEX version:
 - [X] 1.5.2
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

All amounts use a different decimal separator, different than one set in the currency and also different from Windows settings one. Was working fine in 1.5.1

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

![image](https://user-images.githubusercontent.com/7106290/120802304-9861ed00-c542-11eb-994a-f7634a9cc24a.png) 
![image](https://user-images.githubusercontent.com/7106290/120802373-a879cc80-c542-11eb-83c0-54eb4fb27d34.png)
![image](https://user-images.githubusercontent.com/7106290/120802432-b4658e80-c542-11eb-953c-e4418c62366c.png)

Maybe related to https://github.com/moneymanagerex/moneymanagerex/issues/2473

But I don't understand:
1) If I put it_IT it's still wrong because decimal separator should be comma, not dot
![image](https://user-images.githubusercontent.com/7106290/120803293-af550f00-c543-11eb-9421-53be78f3b641.png)
2) If a locale is choosen, the fields on teh currency manager should be disabled
3) If I leave it empty, it's working as before
4) how to use currency manager settings but Italian locale (interface language)?

**Comment by vomikan** [comment]
@gabriele-v there are 2 options:
1) leave the Locale field empty
2) choose some locale from the list

**Comment by gabriele-v** [comment]
I've understood the bug, don't know why but it was en_US.UTF8 in my case after 1.5.2 upgrade

Then the other bug is why fmt uses dot as decimal separator for Italy but that's another point

**Comment by tactilis** [comment]
@gabriele-v
> 4. how to use currency manager settings but Italian locale (interface language)?

The interface language is independent of the locale.
The interface language is set using the menu item `View | Switch Application Language`.

I guess you know that already, but your words above suggested that it was linked to the locale.

**Comment by gabriele-v** [comment]
> @gabriele-v
> 
> > 1. how to use currency manager settings but Italian locale (interface language)?
> 
> The interface language is independent of the locale.
> The interface language is set using the menu item `View | Switch Application Language`.
> 
> I guess you know that already, but your words above suggested that it was linked to the locale.

Yep, I've noticed it later because TBH I haven't changed it since long time and when I was developing it the language was inside options dialog

**Comment by vomikan** [comment]
I went through all the locales. Neither offers a comma as a decimal separator. :(

**Comment by gabriele-v** [comment]
> I went through all the locales. Neither offers a comma as a decimal separator. :(

You think we should open an issue at fmt?

**Comment by vomikan** [comment]
They can definitely be asked questions. Some locales represent numbers with the same group and decimal separator.

![image](https://user-images.githubusercontent.com/6836805/120817238-37461380-c55a-11eb-9ae5-3f0ee60b47ee.png)

**Comment by gabriele-v** [comment]
I haven't checked how fmt has been integrated in MMEX, but looks like "L" format should be used?
https://isocpp.org/files/papers/P1892R1.pdf
https://github.com/fmtlib/fmt/commit/e4f2cf455e4ff3a065ff931e40b50dae182b4d6f

**Comment by vomikan** [comment]
https://github.com/fmtlib/fmt/issues/2199
