### ISSUE TITLE
Only show/update currencies for open accounts

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#3558]
# Description of the feature

A nice feature in version 1.4.0 was that unused currencies were hidden -- _including those from closed accounts_. Sadly, the latter is missing in 1.5.x: the Currency Dialog and Currency Exchange Rates Applet show currencies used in all accounts, even if they are no longer relevant for the user.

Would it be possible to re-implement this feature?

# Use cases

**Comment by vomikan** [comment]
I used ths feature to show currency exchange rates on the home page. It's feature not a bug.

**Comment by cmbarbu** [comment]
Agreed, I also do not consider this to be a bug. And I really like the exchange rates panel on the home page! It is just too cluttered (in my case) because it lists a lot of currencies that I have used in the past, but no longer care about.

**Comment by cmbarbu** [comment]
Hello, it seems this change has been reverted in the last couple of versions. The panel on the homepage shows all used currencies -- including those for closed accounts.
