### ISSUE TITLE
Currency format locale based options redesign

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#3559]
MMEX version:
 - [x] 1.5.2
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
When starting the Windows version under Wine, the error shown in the image occurs:
![mme](https://user-images.githubusercontent.com/80578702/120831128-86427780-c55f-11eb-9c91-8ef6fa8b6460.png)

However, if I select the language from the drop-down list, the numbers will not be displayed correctly: 
![mme1](https://user-images.githubusercontent.com/80578702/120831615-049f1980-c560-11eb-8b46-00196cc81e59.png)

The English language will remain after the reboot. In both versions, the English language remains.
I wanted to try it under wine because there is no focal version for ubuntu yet. 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Try to set hu_HU.UTF-8 in the Locale field.

**Comment by tactilis** [comment]
@Heny67 You can type **hu_HU.UTF-8** into the locale field.

But, I'd use en.HU as the locale (for number formatting) and set the application language like here (don't forget to restart MMEX after making your changes):

![image](https://user-images.githubusercontent.com/4060092/120836915-0667dd80-c55e-11eb-9b34-41c63214d46a.png)

**Comment by Heny67** [comment]
So okay. However, selecting hu_HU with the general locale option in the drop-down menu still does not display well. If I delete _HU and all that is left is hu, they will already appear correctly.

**Comment by vomikan** [comment]
Seems "Locale" better to rename to "Global digit settings"

**Comment by tactilis** [comment]
@vomikan
> Seems "Locale" better to rename to "Global digit settings"

Yes, but no. (IMO)

Yes, people are confused by Locale. They believe it will set the language used in the UI, as well as the formatting of currency values.

But no, not  "Global digit settings".  That's not the best way convey what you mean (in English).

Busy at the moment - but I'll fut forward a suggestion a bit later if that's OK

**Comment by vomikan** [comment]
We are waiting for your suggestions.

**Comment by tactilis** [comment]
I have observed in posts on GitHub and in the MMEX Forum that some people have difficulty discovering where to go to set the UI language. They expect it to be in Options.  When they look there, they are are confused by locale because they believe it will set the language used in the UI, as well as the formatting of currency values.

Here is a suggestion for avoiding this confusion:

1. Remove the `Switch Application Language` setting from the View menu.
2. Move the `Language` selection to Options.
3. Change `Locale` to `Currency Format` and explain in the text what it does, including how you can set the format manually.

![image](https://user-images.githubusercontent.com/4060092/120867846-adfb0500-c58a-11eb-85cf-7ebc83586cb7.png)

It's just a suggestion for discussion.

**Comment by tactilis** [comment]
I think this old conversation illustrates perfectly the fact that the `View` menu is _not_ an obvious place to look when you want to change the application language: 

[https://github.com/moneymanagerex/moneymanagerex/issues/1452](https://github.com/moneymanagerex/moneymanagerex/issues/1452)

:grinning: :grinning:

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/120886197-68275680-c5f5-11eb-84bb-2dfc3d9146f7.png)

**Comment by gabriele-v** [comment]
> I have observed in posts on GitHub and in the MMEX Forum that some people have difficulty discovering where to go to set the UI language. They expect it to be in Options. When they look there, they are are confused by locale because they believe it will set the language used in the UI, as well as the formatting of currency values.
> 
> Here is a suggestion for avoiding this confusion:
> 
> 1. Remove the `Switch Application Language` setting from the View menu.
> 2. Move the `Language` selection to Options.
> 3. Change `Locale` to `Currency Format` and explain in the text what it does, including how you can set the format manually.
> 
> ![image](https://user-images.githubusercontent.com/4060092/120867846-adfb0500-c58a-11eb-85cf-7ebc83586cb7.png)
> 
> It's just a suggestion for discussion.

I'd agree about this, not sure why it has been moved the language. Or leave it in both places if you prefer, but I'd searched it in options, not really in view.

**Comment by vomikan** [comment]
I'll prefer leave it in both places.

**Comment by tactilis** [comment]
@vomikan
> I'll prefer leave it in both places.

It's not in _both_ places yet. Although the issue is labelled as Fixed, the commit didn't add a `Language` section to the Options dialog.

![image](https://user-images.githubusercontent.com/4060092/120916607-6e274100-c6a2-11eb-9d36-b48f3f651eb7.png)

Also, if you are making a further change to this dialog, could you consider the proposed change of wording to the Date Format section:

Change: `New date format sample`  to  `Date format sample` as shown above.

This is to the consistent with the wording of `Currency value sample`.

The word New is redundant. It's obvious to the user that if they change the format in the dropdown, the format chosen is new.

**Comment by FrancoFra** [comment]
Italian currency must be COMMA for decimal (now DOT).
Thanks
Franco F.
![Currency 2021-06-06 110945](https://user-images.githubusercontent.com/85434493/120919060-f237f380-c6b7-11eb-8ae0-464b5d46ae18.png)

**Comment by vomikan** [comment]
@FrancoFra 
![image](https://user-images.githubusercontent.com/6836805/120919613-2cf35900-c6c3-11eb-8292-34cd771bd94b.png)

**Comment by tactilis** [comment]
@FrancoFra 
> Italian currency must be COMMA for decimal (now DOT).

It's known problem in 1.5.2.  See #3557

A workaround for now is to set your locale to blank, which will allow you to manually set the Group and Decimal Chars in `Organize Currency | EUR | Edit`

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/120920446-82316980-c6c7-11eb-8e63-69a7171a2499.png)

**Comment by FrancoFra** [comment]
This is not Version 1.5.2 64 bit.

Franchi Franco
Loc. Costa Belvedere, 7
43041 – Bedonia (PR)
Cell.: 3318741659

Da: ***@***.***>
Inviato: domenica 6 giugno 2021 12:03
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Currency format locale based options redesign (#3559)


[image]<https://user-images.githubusercontent.com/6836805/120920446-82316980-c6c7-11eb-8e63-69a7171a2499.png>

**Comment by FrancoFra** [comment]
Hi Nikolay.
Really I don’t understand what happened, but after reboot all is ok.
Thanks a lot.
Franco F.

Franchi Franco
Loc. Costa Belvedere, 7
43041 – Bedonia (PR)
Cell.: 3318741659

Da: ***@***.***>
Inviato: domenica 6 giugno 2021 21:14
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Currency format locale based options redesign (#3559)


Closed #3559<https://github.com/moneymanagerex/moneymanagerex/issues/3559>.
