### ISSUE TITLE
Crash in Model_Currency::toString

### ISSUE THREAD

**Issue by Joker2k** [moneymanagerex/moneymanagerex#3585]
MMEX version:
git master

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Crash when creating new database and clicking cancel on new account creation;

No check for currency nullptr:
![image](https://user-images.githubusercontent.com/8383606/121298125-0409d880-c8fc-11eb-9f46-d25e76169018.png)

Next. GetBaseCurrency returning nullptr:
![image](https://user-images.githubusercontent.com/8383606/121298676-f012a680-c8fc-11eb-9678-d0089a338391.png)

Again, using static variables in local function is very sad.

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. From start's splash "Create new database"
2. Click "Cancel"

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
@Joker2k 
>Again, using static variables in local function is very sad.

Give references to the proof of this statement. I don't find them. Moreover, we often use this technique to cache frequently used data.

Sample:
```
Model_Checking::TYPE Model_Checking::type(const wxString& r)
{
    if (r.empty()) return TYPE::WITHDRAWAL;
    static std::unordered_map<wxString, TYPE> cache;
    const auto it = cache.find(r);
    if (it != cache.end()) return it->second;

    for (const auto& t : TYPE_CHOICES)
    {
        if (r.CmpNoCase(t.second) == 0)
        {
            cache.insert(std::make_pair(r, t.first));
            return t.first;
        }
    }

    cache.insert(std::make_pair(r, TYPE::WITHDRAWAL));
    return TYPE::WITHDRAWAL;
}
```
