### ISSUE TITLE
Cannot start: "bad locale name"

### ISSUE THREAD

**Issue by Joker2k** [moneymanagerex/moneymanagerex#3587]
MMEX version:
git master

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Since a while I cannot start mmex on my win7 machine.

![image](https://user-images.githubusercontent.com/8383606/121299787-9b702b00-c8fe-11eb-8d46-89527f0c7403.png)

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. From start's splash "Open last opened database"

…

Expected result:
Program starts

Actual result:
Program closes with error

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
I recommend to clear the following field in mmb file using any SQLite Developer.

![image](https://user-images.githubusercontent.com/6836805/121363317-8798e900-c93f-11eb-8a4b-9a16a0af82a5.png)

**Comment by vomikan** [comment]
Seems it should be added  "try" before any locale usage into wxString Model_Currency::toString function.

```
    try {
        auto test = fmt::format(std::locale(locale.c_str()), "{:L}", 123);
    }
    catch (std::exception & ex) {
        locale = "";
    }
```

**Comment by Joker2k** [comment]
First thing i've checked, my:
![image](https://user-images.githubusercontent.com/8383606/121364049-1b6ab500-c940-11eb-89e7-53584a710337.png)

Unfortunately I'm unable to debug on win7 PC. I don't have issue on my win10 dev machine. 

Even starting new database from splash, I have that error. But program doesn't closes.

**Comment by vomikan** [comment]
Just clear LOCAL field (do not delete the line ut ovly value).

**Comment by Joker2k** [comment]
try/catch doesn't help
LOCALE field have "not null" constraint. Setting to " " doesn't help either
git master as for now doesn't resolve

**Comment by vomikan** [comment]
> try/catch doesn't help
> LOCALE field have "not null" constraint. Setting to " " doesn't help either
> git master as for now doesn't resolve

It should help
 "not null" does not metter. The fmt::format(std::locale(locale.c_str()), "{:L}", 123) function would call exception on any invalid locale value.

**Comment by Joker2k** [comment]
Last commit broke even my win10 machine... 
You should uninit in catch:
![image](https://user-images.githubusercontent.com/8383606/121525293-d35f9700-ca00-11eb-9d19-dc0a21f53c10.png)

Still win7 got "bad locale"....

**Comment by vomikan** [comment]
@Joker2k is it working now?

**Comment by Joker2k** [comment]
no, same "bad locale" on win7 preventing start from portable mode

Version: 1.5.3-Beta.1 
• Build on Jun 12 2021 16:22:03
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.4 (wxMSW 6.1)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg v2.0.1
• libcurl/7.59.0 WinSSL zlib/1.2.8
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.20.21032501-MSVC_2
• MSBuild 16.10.1.27004
• Microsoft Visual Studio 16.0
• Microsoft Visual C++ 19.29.30037.0
• Windows SDK 10.0.18362.0
Running on:
• Windows 7 (build 7601, Service Pack 1), 64-bit edition
• Russian (windows-1251)
• 1920x1200 32bit 72x72ppi

**Comment by vomikan** [comment]
1)
![image](https://user-images.githubusercontent.com/6836805/121778410-6fbfa000-cb9f-11eb-937b-76e81478754e.png)
2)
![image](https://user-images.githubusercontent.com/6836805/121778428-7c43f880-cb9f-11eb-9158-44e54034e72a.png)
3)
![image](https://user-images.githubusercontent.com/6836805/121778654-8adedf80-cba0-11eb-96d5-1a713520d2db.png)

There is only one issue:
![image](https://user-images.githubusercontent.com/6836805/121778700-bb267e00-cba0-11eb-9809-6994e9802ba8.png)

**Comment by Joker2k** [comment]
Yes, finally fixed...
