### ISSUE TITLE
Cannot open file: malloc_consolidate(): unaligned fastbin chunk detected

### ISSUE THREAD

**Issue by camposFabio** [moneymanagerex/moneymanagerex#3589]
MMEX version:
 - 1.5.2

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Arch Linux 

# Description of the bug

When I call mmex and try to open an existing emb file the following error occurs:

```
Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).
malloc_consolidate(): unaligned fastbin chunk detected
[1]    35918 abort (core dumped)  mmex
```

# Reproduction

Is the bug reproducible? 
 - [X] Always 

Reproduction steps:

1.  Just call mmex on terminal
2.  Try to open existing file

Expected result:
Program open database

Actual result:
Program Crash

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
re-generate locale-gen with just en_US.UTF-8

**Comment by camposFabio** [comment]
Same error even after restart with only en_US locale.

mmex worked fine until version 1.3.6

- My default arch locale is is Brazillian Portuguese (pt_BR)
> locale -a
C
en_US.utf8
POSIX
pt_BR.utf8

> locale
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

Tried changing locale.gen

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3394

**Comment by camposFabio** [comment]
Fized in version 1.5.3 Beta. Thanks!
