### ISSUE TITLE
Custom autocomplete ComboBox

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#359]
It will be nice to create a custom ComboBox with autocomplete that will work fine under Windows & Mac, with support for wildcards like \* or % for search in the middle of strings.

Than it could be used in lots of places where autocomplete could help.

**Comment by themnd** [comment]
if you want to shrink down the payee list as soon as you type something in the payee field, you can modify the file src/transdialog.cpp and add this:

	@@ -258,6 +277,34 @@ void mmTransDialog::dataToControls()
	         skip_payee_init_ = true;
	         cbPayee_->SetEvtHandlerEnabled(true);
	     }
	+    else
	+    {
	+        wxArrayString all_payees = Model_Payee::instance().all_payee_names();
	+        if (!all_payees.empty())
	+        {
	+            wxArrayString matchingPayees;
	+            wxString payee_name = cbPayee_->GetValue();
	+            wxString payee_name_l = payee_name.Lower();
	+
	+            for (int idx = 0; idx < all_payees.GetCount(); idx++) {
	+                wxString& s = all_payees[idx];
	+                if (s.Lower().Contains(payee_name_l))
	+                {
	+                    matchingPayees.Add(s);
	+                }
	+            }
	+
	+            wxEventBlocker blocker(cbPayee_);
	+
	+            cbPayee_->Clear();
	+            cbPayee_->Insert(matchingPayees, 0);
	+            cbPayee_->AutoComplete(matchingPayees);
	+            cbPayee_->ChangeValue(payee_name);
	+            cbPayee_->SetInsertionPointEnd();
	+        }
	+    
	+    }

**Comment by gabriele-v** [comment]
Could you help writing a custom autocomplete combo box? It will be nice to use it everywhere in MMEX
