### ISSUE TITLE
Colouring issues on User Coloured transactions and recurring deposits

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3590]
MMEX version:
 - [X] 1.5.x

- The font colors for user coloured transactions are preset to BLACK and YELLOW depending upon the default preset colours, if the colours are changed then the font may be unreadable. The actual font colour should be calculated to contrast with the background colour.

- When reverting to standard colours after a user colour is selected in Recurring transactions the background is not reverted to the alternating pattern. There is an issue with presentation when FOLLOWUPID = 0.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/121420830-31936800-c976-11eb-9ece-444e2099114c.png)

**Comment by vomikan** [comment]
i suggest the following code:
```
const wxColor* bestFontColour(wxColour background)
{
    // http://stackoverflow.com/a/3943023/112731

    int r = static_cast<int>(background.Red());
    int g = static_cast<int>(background.Green());
    int b = static_cast<int>(background.Blue());
    int k = (r * 299 + g * 587 + b * 114);

    wxLogDebug("best FontColour: [%s] -> r=%d, g=%d, b=%d | k: %d"
        , background.GetAsString(wxC2S_HTML_SYNTAX), r, g, b, k);

    return (k > 149000) ? wxBLACK : wxWHITE;
}
```

![image](https://user-images.githubusercontent.com/6836805/121427635-a027f400-c97d-11eb-9b18-d0ebe9a81a58.png)
