### ISSUE TITLE
Use of dot to separate the thousands and decimal

### ISSUE THREAD

**Issue by sirjoe65** [moneymanagerex/moneymanagerex#3596]
> in the Windows version of Money Manager EX 1.5.2 64 bit, I found an error. I have set the options for the display of the figures >according to the use in Italy (".") to separate the thousands and "," to separate the decimal figures) but "." both to separate the >thousands and to separate the two decimal places.
>In previous versions everything was correct. Please solve the problem. Thank you
>
![MMEX](https://user-images.githubusercontent.com/61920723/121521048-e4ee7200-c9f3-11eb-9e24-b30f44cff85f.jpg)

<hr>Version: 1.5.2 64-bit<br>
 • Build: Giu  4 2021 07:16:03<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Italian (windows-1252)<br>
 • 2560x1440 32bit 96x96ppi

**Comment by tactilis** [comment]
Known problem #3557 #3583.   Fixed in the 1.5.3 development version.

A workaround for now in 1.5.2 is to set `Options | General | Locale` to blank, which will allow you to manually set the Group and Decimal Chars as you wish in `Organize Currency | EUR | Edit`

**Comment by sirjoe65** [comment]
Thank you!
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*Sergio Ferraiolo*
la mia casella Email: ***@***.***
Le mie fotografie:
https://www.sergioferraiolo.it/fotografie/fotografie_start.htm
i miei video: www.youtube.com/c/SergioFerraiolo
<http://www.youtube.com/sirjoe7007>
il mio blog: https://sergioferraiolo.com
i miei racconti di viaggio: clicca qui
<http://www.amazon.it/s/ref=nb_sb_noss_1/280-5975249-2156134?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=sergio%20ferraiolo&sprefix=sergio+fe%2Caps&rh=i%3Aaps%2Ck%3Asergio%20ferraiolo>





Il giorno gio 10 giu 2021 alle ore 14:18 Martin ***@***.***>
ha scritto:
