### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by Woo-Cash** [moneymanagerex/moneymanagerex#3598]
I have 2 custom fields: one text and one number with 2 decimal points. While adding new transaction I fill both of them. After saving it looks like this:
![image](https://user-images.githubusercontent.com/5322956/121555495-58ec4280-ca13-11eb-9d14-80e284237c1e.png)
![image](https://user-images.githubusercontent.com/5322956/121555416-48d46300-ca13-11eb-9f9c-900ae2f085ae.png)
But when I open the transaction and click save again, even without changing anything, it's ruined:
![image](https://user-images.githubusercontent.com/5322956/121555573-699cb880-ca13-11eb-9b3c-5a4d0ed610ad.png)
And shouldn't it use the decimal separator from settings? In my case it's comma ",".

Version 1.5.2.

**Comment by whalley** [comment]
Fixed text field save issue, other issue will require more work and possibly work covering by a second issue if we don;t get time to fix for this release.
