### ISSUE TITLE
Assets should be closeable or have an end date

### ISSUE THREAD

**Issue by josh-egan** [moneymanagerex/moneymanagerex#361]
Currently, when an asset is sold, the only way to stop showing the asset is by deleting it. I think it would be better if the asset had an end date so that the asset could show up in the history based on its start and end date.

I ran into this when I was trying to display my net worth over time.

For the time being, I've changed all of my assets to term accounts as a work around. I put in the first transaction for the purchase date and the second transaction is the sale date.

**Comment by stef145g** [comment]
It appears that issues https://github.com/moneymanagerex/moneymanagerex/issues/326 and https://github.com/moneymanagerex/moneymanagerex/issues/336 have a similar theme to this, and could all be done as proposed in https://github.com/moneymanagerex/moneymanagerex/issues/336

**Comment by guanlisheng** [comment]
Not that similar since we do have account for stock. The first step is to support dedicated asset account

**Comment by stef145g** [comment]
Closing this issue and continuing discussion on issue: **Support buying & selling for stock account** #336

**Comment by guanlisheng** [comment]
This is for ASSET instead of stocks

**Comment by stef145g** [comment]
Issue reopened. New solution required.

**Comment by stef145g** [comment]
@josh-egan You may be interested in testing this feature about assets:
Available in the [Artifacts section of the Windows Platform](https://ci.appveyor.com/project/guanlisheng/moneymanagerex)

Similar to Stocks and Shares management, an Asset can now access its own account having the same name as the asset name. This account allows normal transactions to transfer money to assets and vice versa. Transactions to and from Assets can be classified as Transfers or as normal Deposit/Withdrawal transactions, that affect income and expense calculations.

**Comment by stef145g** [comment]
Closing as this should now be handled by the new Asset Management improvements.
