### ISSUE TITLE
date picker has wrong date format

### ISSUE THREAD

**Issue by thomasboehm** [moneymanagerex/moneymanagerex#3619]
In MMEX options I have set the date format to DD/MM/YYYY, yet when I insert a new transaction the date format in the date picker is MM/DD/YYYY and the week starts on Sunday. The date column in my accounts shows the date correctly formatted. In 1.5.1 everything worked as expected.

Edit: There seems to be a mix-up with the locale settings. Now I can't insert transactions with  more than 3 digits. It looks like it converts 1234 to 1,234.00 and then takes the comma as decimal point.

<hr>Version: 1.5.3 64-bit<br>
 • Build: Jun 13 2021 15:24:17<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.0.4 (wxGTK 3.22)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.3<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 ( libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.10.2<br>
 • GNU Make 4.1<br>
 • GCC 7.5.0 • Ubuntu 18.04

**Comment by tactilis** [comment]
> when I insert a new transaction the date format in the date picker is MM/DD/YYYY and the week starts on Sunday

The wxWidgets date picker uses the date format and first day of week that is set in your operating system's Regional Settings.


> There seems to be a mix-up with the locale settings. Now I can't insert transactions with more than 3 digits. It looks like it converts 1234 to 1,234.00 and then takes the comma as decimal point

What locale do you have set in MMEX?

I can reproduce this bug if I set the locale to blank.
If I set it en_GB, transactions with more than three digits (e.g 1,234,567.89) are entered OK

**Comment by thomasboehm** [comment]
> The wxWidgets date picker uses the date format and first day of week that is set in your operating system's Regional Settings.

My system locale is en_GB and the calendar widget in my taskbar shows Monday as start of the week.

```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

> What locale do you have set in MMEX?

> I can reproduce this bug if I set the locale to blank.
> If I set it to en_GB, transactions with more than three digits (e.g 1,234,567.89) are entered OK

After setting en_GB I could enter transactions ok. It also worked when leaving it blank and changing the Grouping Char from space to , in my currencies.

The date picker problem remains though.

**Comment by tactilis** [comment]
Sorry, I should have said:

> _**On Windows**_, the wxWidgets date picker uses the date format and first day of week that is set in your operating system's Regional Settings.

I'm not sure how it works on Linux based systems.

**Comment by vomikan** [comment]
#1358

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=1&t=45716&p=190196&hilit=wxDatePickerCtrl#p190196
