### ISSUE TITLE
Clavier numérique

### ISSUE THREAD

**Issue by Philmar13** [moneymanagerex/moneymanagerex#3622]
Lorsque je veux utiliser le point des décimales sur le clavier numérique, il n'est pas pris en compte et les chiffres s'affichent sans décimale.
version mmex 1.5.2 64 bits

**Comment by Philmar13** [comment]
Lorsque je veux utiliser le point des décimales sur le clavier numérique, il n'est pas pris en compte et les chiffres s'affichent sans décimale.
version mmex 1.5.2 64 bits

**Comment by tactilis** [comment]
@Philmar13
> _When I want to use the decimal point on the numeric keypad, it is not taken into account and the numbers are displayed without decimal._ 

The numeric keypad decimal point works OK here.

1) Are you saying when you type a  .  using the numeric keypad, no character appears?

2) Or do you mean that after you click OK on the transaction dialog, the decimal point is not displayed in the value in the transaction list?

If it is 1), then does MMEX work OK when you use the decimal point on the main keyboard?  Also does the decimal point on the numeric keypad work OK in other applications?

If it is 2), then what `Locale` do you have set on the Options dialog?

In either case, please could you upgrade to MMEX 1.5.3, repeat the test and report your results.

**Comment by tierradenadie** [comment]
Same issue here with a german locale. When I switch the locale to de_DE the values are correctly displayed in the overview. But when I try to add a transaction and use the comma (,) which is used the other way round like in english notation, I get an error message, that the value is incorrect and everything after the comma is set automatically to zero. In this case, I also cannot use the point, as is gets converted to a comma automatically. I switched the locale to en_EN and now it works as it has before the update.

**Comment by vomikan** [comment]
@tierradenadie 
Please update:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/39729911/job/wjl1tfi4mntlcf2o/artifacts

**Comment by tierradenadie** [comment]
I tried the beta, but it didn't solve my issue. What helped was editing the currency settings, changing the seperator from "." to ",". Now it works as expected even in version 1.5.3.

**Comment by vomikan** [comment]
I can't reproduce this issue with 1.5.4

![image](https://user-images.githubusercontent.com/6836805/123251124-82b56700-d4f3-11eb-9f78-1c682977b312.png)

![image](https://user-images.githubusercontent.com/6836805/123251185-92cd4680-d4f3-11eb-9fa4-a0566ecf4405.png)

**Comment by tierradenadie** [comment]
As long as I use the point as decimal char, the issues still exists for me. As soon as I change it to comma, it works as expected. If it isn't reproducable it maybe just a problem with my computer, but I found the mentioned workaround.

Thank you very much for your extremely quick replies. I use Money Mager Ex almost daily and it is a fantastic piece of software. You all are doing an amazing job.
