### ISSUE TITLE
Undefined Locale prevents saving transaction amounts greater than 999

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3626]
MMEX version:
 - [X] 1.5.x

https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10427

Hi,

Last night I upgraded to version 1.5.3 x64 on Win10. My accounts are all set to USD by default. I have never changed currencies or locales. Today when I entered a transaction for $2049, I found that when I tabbed out of the Amount field (or clicked OK to save), $2,049 converted to $2. I played around with this for a while and found that any amount greater than $999 gets truncated and converted to the first digit only. So entering $1234 for the amount converts to $1. Entering 3333 converts to $3. Entering $5555 converts to $5. Etc. I was unable to save my transaction with the correct amount as a result.

I started looking at recent changes in the change log and thought this probably has something to do with the recent locale/currency changes. I looked at my locale in Options and saw that it was undefined (because I have never used it).

![image](https://user-images.githubusercontent.com/487345/122352424-06e17a80-cf47-11eb-8346-3bffd354aee3.png)

So after reading a couple other recent locale issues here in the forum, I tried setting my locale to en_US in Options. 

![image](https://user-images.githubusercontent.com/487345/122352480-1234a600-cf47-11eb-8aea-e0714ef18b13.png)

Once I saved this option change and restarted, I am now able to save transaction amounts greater than $999. That worked for me, but I thought I should post this just as an FYI for the devs to look at, and in case anyone runs into this issue.

**Comment by vomikan** [comment]
I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/6836805/122459084-2ca76780-cfb9-11eb-9621-96de662a5878.png)

**Comment by whalley** [comment]
Neither can I. I'll reach out the reporting user on the forum for more information.

**Comment by vomikan** [comment]
But I found another bug 

![image](https://user-images.githubusercontent.com/6836805/122459824-0fbf6400-cfba-11eb-89f4-07c3f184fa15.png)


![image](https://user-images.githubusercontent.com/6836805/122459774-fcac9400-cfb9-11eb-9e8b-075d58fa28f7.png)

**Comment by whalley** [comment]
Reported fixed. https://forum.moneymanagerex.org/viewtopic.php?p=22139#p22139
