### ISSUE TITLE
Any chance of making the app remember the section visited while closing and nagivate to it upon re-open?

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#3629]
I normally prefer to see all transactions upon opening the app but current default is homepage which makes sense because it gives the summary you wants to see. 

Any chance letting user having this control please? Just a feature request.

**Comment by reddyshyam** [comment]
Thansk @vomikan. Appreciate it. 👍

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2670

**Comment by reddyshyam** [comment]
Wow! Can't believe such old request is not forgotten. Thansk @whalley. Appreciate it. 👏 🤝

**Comment by reddyshyam** [comment]
> It is not fixed. Just closing the duplicate and the feature will be tracked against #2670

Ah! I see, thanks for the heads up. No rush with it. :)
