### ISSUE TITLE
Weekday in transaction dialog

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3632]
@whalley could you check how it looks on MAC? Early I've enabled this for Windows only. 

```
#ifdef __WXMSW__
    wxSpinButton* spinCtrl = new wxSpinButton(this, ID_DIALOG_TRANS_DATE_SPINNER
        , wxDefaultPosition, wxSize(-1, dpc_->GetSize().GetHeight())
        , wxSP_VERTICAL | wxSP_ARROW_KEYS | wxSP_WRAP);
    spinCtrl->SetRange(-32768, 32768);
    mmToolTip(spinCtrl, _("Retard or advance the date of the transaction"));
    date_sizer->Add(spinCtrl, g_flagsH);
#endif
```

https://forum.moneymanagerex.org/viewtopic.php?f=25&t=10423

![image](https://user-images.githubusercontent.com/6836805/122542092-fd354100-d032-11eb-903a-57ae84751842.png)

**Comment by vomikan** [comment]
Windows dialog:

![image](https://user-images.githubusercontent.com/6836805/122542406-500ef880-d033-11eb-9148-9a43767bba43.png)

**Comment by whalley** [comment]
On MacOS the wxDatePickerCtrl already contains a spin button.... Adding in the addition code will just duplicate this, see...
<img width="365" alt="image" src="https://user-images.githubusercontent.com/487345/122554925-7fbd0100-d031-11eb-9653-266005c3f86f.png">

What MacOS lacks is the date dropdown (but we already have ticket to look at resolving that)

**Comment by whalley** [comment]
The MacOs wxDatePickerCtrl already contains a spinner, so this will just duplicate. What MacOS lacks is the date dropdown (https://github.com/moneymanagerex/moneymanagerex/issues/3139).
<img width="365" alt="image" src="https://user-images.githubusercontent.com/487345/122555456-3c16c700-d032-11eb-9b43-bbfed4f54201.png">
