### ISSUE TITLE
Webapp - Payees

### ISSUE THREAD

**Issue by drspoke** [moneymanagerex/moneymanagerex#3643]
MMEX version:
 - [X ] 1.5.3
 

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
I use the mmex Webapp to add operations.
Since the last version, Payees are blank without any histroy and there isn't any completion.
I reset the webapp by deletting the loc .db.
Nothing run.
No payees, and no account name are upload in the webapp.

Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [ X] Always 

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
@gabriele-v  could you, please, comment? Is it reproduced on 1.5.3?

**Comment by vomikan** [comment]
Last changes
https://github.com/moneymanagerex/moneymanagerex/commit/ea18523ec75229d2244de794bed63baf427a2df3#diff-42e385b26b31d148eae399567a50ba82394a5fdfeb2b4faf0e645d086bdcc8a3

![image](https://user-images.githubusercontent.com/6836805/123406594-bfe12e00-d5b3-11eb-82ab-2d4baf4d17e4.png)

**Comment by gabriele-v** [comment]
Unfortunately I cannot test it right now, could you try to revert only that line and provide an artifact so it could be tested?

**Comment by whalley** [comment]
I can't reproduce this. However I could not find a quick way to refresh the webapp DB other than adding/deleting a new account to force the account refresh, then similarly for payee and categories. Once done the accounts are visible via an account drop down and the payees/categories via type-ahead.

I'm adding a Tools/Refresh WebApp option so that you can easily keep them in-sync if you ever need to delete the WebApp DB and start again.

**Comment by whalley** [comment]
@drspoke Are you still experiencing this problem?

**Comment by drspoke** [comment]
> @drspoke Are you still experiencing this problem?

i'm sorry, i'm a noob, How can I test the patch or the solution ?

**Comment by whalley** [comment]
@drspoke You can find latest dev build here: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/id99ma244152d31y/artifacts

**Comment by drspoke** [comment]
@whalley I tried it.
I have delete the MMEX_New_Transaction.db
I launched the app.
-  All accounts are now in the list 
-  All Payees are still missing.

**Comment by whalley** [comment]
@drspoke When you say payees are missing, do they appear as you start typing in the web form? They do not appear as a drop down like the accounts and are only search as you type into the field.

**Comment by drspoke** [comment]
@whalley Nothing appears. When I start to type, tere is no autocompletion.
With DB Browser for SQLite à openned MMEX_New_Transaction.db.
- Account_List-->Full (all accounts are inside)
- Category_lst --> Empty
- Parameters --> 1.0.4
- Payee_Liste--> empty
![Payeelist](https://user-images.githubusercontent.com/33481120/124272993-c46f8e80-db3f-11eb-86a5-33f2996427c2.png)
![categoryList](https://user-images.githubusercontent.com/33481120/124272997-c5082500-db3f-11eb-9eb9-8d0ba3c32bfe.png)

**Comment by whalley** [comment]
Did you refresh the WebApp from the MMEX app?

![image](https://user-images.githubusercontent.com/487345/124273415-e6fda980-db37-11eb-9d3b-82d32c9c1bea.png)

**Comment by drspoke** [comment]
@whalley Yes I do that many times

**Comment by whalley** [comment]
All I can think then is some misconfiguration on the web server. Do the web access and error logs look OK? Or there may be some.

Out of interest have you recently added any new payees? Especially ones with non-alpha numeric characters - &, $, etc? Not saying this is the issue just trying to eliminate a few things.

**Comment by drspoke** [comment]
I unselect & sectect payees and categories. : nothing
I cant find logs....
I just want to know : is it working  with your configuration ?

**Comment by whalley** [comment]
Yes, works fine for me.

**Comment by vomikan** [comment]
@drspoke is any payee has non Latin charecters?

**Comment by drspoke** [comment]
@vomikan @whalley 
I made a lot of tests with a test database.
I found the pb !
You're Write !!!!!
If you don't know yet I'am French and we use specific characteres like :é;à;è;ïî&....(I don't know if its non latin charachers)
If I use paye with classicals characters,  webapp works fine.
If a payee has a specific characters like é in the app, the refresh of the webapp empties the list....
Thx

**Comment by whalley** [comment]
@drspoke Thanks for helping to identify the bug and the cause. We will look to rectify this.

**Comment by drspoke** [comment]
@vomikan @whalley  Is it possible to test the solution ?

**Comment by vomikan** [comment]
There is nothing for test fo now.  May be a the end of the week.

**Comment by whalley** [comment]
@drspoke I've just changed one of my payees and re-synced the WebApp and it works. see below.

Do you have specific Payee name that causes the issue?

![image](https://user-images.githubusercontent.com/487345/125503181-99b9d7de-ade2-48ca-8707-0c4e8826cb73.png)

**Comment by drspoke** [comment]
@whalley I think it's ok.
If you want I can send you a .csv with my payees....

**Comment by whalley** [comment]
I've not changed anything..... Is it working for you?

**Comment by drspoke** [comment]
@whalley sorry,  I think we didn't understand each other.
When I said " I think it's ok" I was talking about your representative exmple of my beneficiaries...

**Comment by whalley** [comment]
OK, well syncing that Payee detail works… So I can’t reproduce your problem.

**Comment by drspoke** [comment]
@whalley 
Well iI think its a very strange probleme.... is it possible to enable logs on the web app to check the table loading ?
If you want, i all my accounts and operations are wiped, can you test with the debug db please ?
Thx
[debug.zip](https://github.com/moneymanagerex/moneymanagerex/files/6828178/debug.zip)

**Comment by whalley** [comment]
Have tested your DB with the instaleld WebApp and it works fine for both payees and categories. Maybe it is something to do with your WebApp/Server sertup?

![image](https://user-images.githubusercontent.com/487345/125912690-83f199f1-5d37-4fce-9202-2eb40450afc9.png)

![image](https://user-images.githubusercontent.com/487345/125912826-fdbcfef5-44be-44eb-b502-89af5452eece.png)

**Comment by whalley** [comment]
@drspoke Let me send you the credentials for my WebApp so that you can try yourself.... Might narrow it down to the webserver/webapp implementation you have if that works.

Where can I send this detail?

**Comment by drspoke** [comment]
@whalley Hello I have news !!!!!
this bug is driving me crazy !!!!!
I tryed to use MMex with an Mac os version. It's all good.
Webapp is correctly synchronized.
When the web is ok, i use my mmex windows version.
Sorry my main computer is a PC..
After that operation the payee list is totaly empty.
So i think the windws version delete all payee list in the webapp.
I use the same .mmb on the mac os and windows .....

**Comment by whalley** [comment]
@drspoke Thanks for update and helping to narrow down the source of the issue.

**Comment by vomikan** [comment]
one more issue
![image](https://user-images.githubusercontent.com/6836805/126999779-ee2d7278-de1b-4b86-8b9a-d625eee35c06.png)

**Comment by drspoke** [comment]
@vomikan 
I have this version
![webapp](https://user-images.githubusercontent.com/33481120/127000492-b4a07fd1-3a96-473c-a8db-071a87ea0cef.png)
I you want you can use it to test....

**Comment by vomikan** [comment]
As soon as I've added new account named Russin charicters mmex send the following json
```
{
    "Accounts": [
        {
            "AccountName": "HGFF11.SA"
        },
        {
            "AccountName": "My Bank"
        },
        {
            "AccountName": "USD"
        },
        {
            "AccountName": "Проверка"
        }
    ]
}
```
Then the table Account_List ("www\mmex\MMEX_New_Transaction.db") became empty.

**Comment by vomikan** [comment]
I've changed the following line:
![image](https://user-images.githubusercontent.com/6836805/127012888-96f9fead-fdb6-4dd8-b9de-358c48160b39.png)



```
{
    "Accounts": [
        {
            "AccountName": "HGFF11.SA"
        },
        {
            "AccountName": "My Bank"
        },
        {
            "AccountName": "USD"
        },
        {
            "AccountName": "РџСЂРѕРІРµСЂРєР°"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/6836805/127012806-4a2fd6a8-422b-429c-9fdf-462c8f4c80dd.png)

**Comment by gabriele-v** [comment]
To be honest I don't have a clear view.
Because MMEX is not distorting characters without the wxString::FromUTF8 is simply sending them encoded as UTF8, as expected from PHP json_decode.
If we would like to prettify it also for MMEX debugging visualization I can add a utf8_encode on the WebApp: it's prettier but we are making two more encoding, one in the desktop MMEX and the other in the webserver that could be omitted.

**Comment by vomikan** [comment]
> To be honest I don't have a clear view.
> Because MMEX is not distorting characters without the wxString::FromUTF8 is simply sending them encoded as UTF8, as expected from PHP json_decode.
> If we would like to prettify it also for MMEX debugging visualization I can add a utf8_encode on the WebApp: it's prettier but we are making two more encoding, one in the desktop MMEX and the other in the webserver that could be omitted.

```
public static function bankaccount_insert_json ($BankAccountJSON)
        {
            $bankaccounts_json_list = json_decode(mb_convert_encoding($BankAccountJSON, 'UTF-8'),true);
```

This solution get me unreadable symbols

![image](https://user-images.githubusercontent.com/6836805/127031428-3315c0a4-94ff-4168-b15d-d515e83c86a3.png)

**Comment by gabriele-v** [comment]
Use
`$bankaccounts_json_list = json_decode(utf8_encode($BankAccountJSON),true);`

**Comment by drspoke** [comment]
I don’t want to be boring but i don’t have the pb withe the account list, my pb is with te payee list. I don’t understand anything with coding. Maybe it’s perhaps the same solution…..

**Comment by whalley** [comment]
@drspoke The account list was just used as an code example. Don't worry this is being addressed for account names, category names, and payee names.

**Comment by drspoke** [comment]
@whalley @vomikan I just want to say :
THANK YOU VERY MUCH !
i 've tested the last beta version compiled yesterday night and it works.
You're the bests !!!!!
