### ISSUE TITLE
Value in the sale of stocks by adding the rates

### ISSUE THREAD

**Issue by mouraee** [moneymanagerex/moneymanagerex#3644]
MMEX version:
 - [ ] 1.5.x
 - [X ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X ] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
By including a sale of a stock, the fee is being added to the amount received when the right is to reduce the rate

![mmex_22062021](https://user-images.githubusercontent.com/7883494/122925162-f2cdbc80-d33c-11eb-85cf-e0b1f5ed75e4.JPG)
![mmex_22062021b](https://user-images.githubusercontent.com/7883494/122925167-f3665300-d33c-11eb-953f-763ce11196f4.JPG)

# Reproduction

Is the bug reproducible? 
 - [ X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Add Stock Transaction
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
It seems 
8 * 91,65 + 0,20 = 733,40

**Comment by mouraee** [comment]
When you sell an asset, you must subtract the rate to know the actual result of the sale, as this will be your actual profit or loss.

**Comment by mouraee** [comment]
When you buy an asset, you add the fees (because you increased its cost), when you sell an asset, you subtract the fees (because you received a lower amount). The difference between the amount you sold and the amount you bought is the profit or loss

**Comment by vomikan** [comment]
I may be wrong, but the sale of assets has not been implemented.

**Comment by mouraee** [comment]
Yes, it has already been implemented. The print screeen above is the sale function (For each stock an auxiliary account is created, when you buy a stock a debit is generated on this account and when you sell a stock a deposit is generated).

The only problem is that the deposit generated on the sale of the stock is adding up the fee, when the right thing is to subtract the fee (if you paid what you will receive is the amount minus the fee)

**Comment by whalley** [comment]
Also spotted that the amount is not updating when the no of shares, price, or commission is changed. Should be fixed now.

**Comment by vomikan** [comment]
There are doubts about the correctness of such a decision. There must be a condition. In one case, we add the commission, in the other we subtract it.

**Comment by mouraee** [comment]
In the buy add the fee (deposit)
8 * 91.65 + 0.20 = 733.40

At Sale, the rate decreases (Withdrawal)
8 * 91.65 - 0.20 = 733.00

**Comment by whalley** [comment]
But isn't the commission the cost of making a deposit or withdrawal? So always taken from the amount.

Not sure when we would ever ADD the commission. What is the use case? You can always use a negative commission if it is an edge case.

**Comment by mouraee** [comment]
Thanks for your attention. This is normal in investment. What matters is how much you paid (including fees) and how much you received (since you don't get fees, you have to subtract fees). In the end, it's how much you have as a balance.

**Comment by mouraee** [comment]
"You can always use a negative commission if it is an edge" this can be a work around, but negative rate doesn't exist, if you think it's better, ok

**Comment by mouraee** [comment]
![mmex_30062021](https://user-images.githubusercontent.com/7883494/123981821-ebd82700-d998-11eb-936b-6e368ab2aee3.JPG)
Work around worked. Tks

**Comment by 2BeeOrNot** [comment]
I'm confused.

I agree with @mouraee. There was a fixed label applied. Then removed. There is a pull request on this issue. Now it's marked as solution found.
Was the pull request to allow negative commissions? Is the solution to use a negative commission?

---------
I've adjusted the share price as a work around to get the transaction total I wanted.
IMO this isn't an edge case. @mouraee says a negative commission works so I'll try it.

If I buy 1 share of Apple today at $140 and the broker commission is $15 I need $155 in my cash account to execute the trade (add the commission).

If I change my mind later today and sell this one share at $140 and the broker commission is $15 I get $125 deposit into my cash account (subtract the commission).

I lost $30.

**Comment by mouraee** [comment]
Exactly @2BeeOrNot you would have lost $30. That's how it works in any application that has fees. Just to demonstrate that the negative rate shouldn't be a solution: how much did I pay in fees in a given period? Using the negative fees, by default, would sum wrong:

In the buy add the fee (deposit)
8 * 91.65 + 0.20 = 733.40

At Sale, the rate decreases (Withdrawal)
8 * 91.65 - 0.20 = 733.00

Right : 0.20 + 0.20 = 0.40
Work Around: 0.20 + -0.20 = 0.00

**Comment by whalley** [comment]
Admittedly I've not really used the shares functionality but think I understand what is now needed. 

@mouraee @2BeeOrNot  @vomikan  can you please test.

**Comment by mouraee** [comment]
![mmex_stocks_shares](https://user-images.githubusercontent.com/7883494/124026644-548ac800-d9c8-11eb-8372-ced57b1cb44a.JPG)

http://github.moneymanagerex.org/moneymanagerex/docs/en/stocks_and_shares.html
Sorry, but is this correct?

I may be wrong, but I think it was reversed.

The purchase is transaction type is Withdrawal;
A Sale is transaction type is Deposit.

In the purchase (transaction type is Withdrawal) add the commission (8 * 91.65 + 0.20 = 733.40)

On sale (transaction type is Deposit) subtract the commission (8 * 91.65 - 0.20 = 733.00)

![mmex_Purchase](https://user-images.githubusercontent.com/7883494/124028198-1b535780-d9ca-11eb-9998-5f4b451abfe3.JPG)
![mmex_Sale](https://user-images.githubusercontent.com/7883494/124028218-21e1cf00-d9ca-11eb-95b2-8febcc5c4b19.JPG)

Tks

**Comment by whalley** [comment]
@mouraee 

Think we are getting there :-)

The tooltip states "Withdraw funds from or deposit funds to this Account." so yes I agree. Have reversed logic.

Buy = "Withdraw" (add commission)
Sell = "Deposit" (subtract commission)

Should we actually use "Buy" and "Sell" as the labels for the transaction type?

**Comment by whalley** [comment]
@mouraee @vomikan @2BeeOrNot  We OK to close this now?

**Comment by mouraee** [comment]
Hi,
Version: 1.6.0-Alpha.1 64-bit
• Build on Jun 6 2021 07:04:34
• Database version: 7 • (aes128cbc)

No OK.

I'm selling the stock. When I sell, money enters my account, but not the entire amount, because I had to pay a commission.

Withdrawal is correct. The stock value plus the commission leaves my account.

Sorry, I don't think I can explain it any better than that.


![image](https://user-images.githubusercontent.com/7883494/125682614-18296bb3-50d0-4aba-b7a1-8053809c649a.png)

![image](https://user-images.githubusercontent.com/7883494/125682688-1141594e-498e-474e-8347-789c5a6917d8.png)

**Comment by whalley** [comment]
Odd.... I've just tried it using the latest 1.5.4-Beta.1 release for MacOS and it works as expected:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/487345/125684347-6f3fe2f8-ea5c-476d-85c1-7584efdaa291.png">

Note the 1.6.0-Alpha release should not be used as it is out-of-date now, just use 1.5.4 latest. https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/trrjekob0qgp3s1x/artifacts

**Comment by mouraee** [comment]
thanks, all right

**Comment by 2BeeOrNot** [comment]
A little late to the party. Using the July 3rd build of 1.5.4 for Mac it is working as expected.
