### ISSUE TITLE
backup files has the same extension as main file

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3648]
IMHO it would be better to hide them from open menu.

![image](https://user-images.githubusercontent.com/6836805/123217413-36f2c580-d4d3-11eb-9ca0-ab44d4b3c3fe.png)

**Comment by whalley** [comment]
I personally think backup files should have a separate extension. I avoids accidentally opening them as a normal MMEX database. If somebody wants to recover a backup then it is easy enough to change the extension. Perhaps a .bak extension?

However, I'm cool with either option, or even just leaving it as is?

**Comment by vomikan** [comment]
It is better to change the extension, since there were calls with incomprehensible behavior and "disappearing data", probably related to the opening of backups.

**Comment by tactilis** [comment]
> It is better to change the extension

Agreed.

With the new backup extension added to the Open file type dropdown?

- MMB Files (*.mmb) 
- Encrypted MMB Files (*.emb)
- **Backup MMB Files (*.bak)**

![image](https://user-images.githubusercontent.com/4060092/123409228-dc766980-d5a5-11eb-80cd-80c26600ca8b.png)
 
Or should the file type dropdown be more informative and say:

- MMEX Database (*.mmb) 
- MMEX Encrypted Database (*.emb)
- MMEX Database Backup (*.bak)

or perhaps more succinctly: 

- MMEX Database (*.mmb) 
- Encrypted Database (*.emb)
- Database Backup (*.bak)

**Comment by vomikan** [comment]
Related issue
https://github.com/moneymanagerex/moneymanagerex/issues/1570

**Comment by tactilis** [comment]
An example of a user becoming very confused by the use of the .mmb file type for backup databases:

[https://forum.moneymanagerex.org/viewtopic.php?t=10432&p=22153](https://forum.moneymanagerex.org/viewtopic.php?t=10432&p=22153)
