### ISSUE TITLE
Transaction Report 

### ISSUE THREAD

**Issue by LourencoJuniorNg** [moneymanagerex/moneymanagerex#3649]
I would like to request a transaction report with the accumulated amount not only consumption. 
for example: 

Account Amount                      Deposit                  Consumption                     Accumulated 
2000                                          50                          20                                       2030

on the transaction report. 
![image](https://user-images.githubusercontent.com/86386625/123220170-f775aa80-d4cd-11eb-92de-963059219630.png)
as de image above transcribe there's only consumption reflected on the transaction report. 

I would like to request the feature, I have been using MMEX for a while for professional money management. 
I hope you take it into account.

Best regard

**Comment by whalley** [comment]
@LourencoJuniorNg  Firstly, you are using an old version of MMEX, please consider updating to the latest v1.5.3.

The summary at the end of the Transaction Report gives an 'accumulation' of all transactions in the report. 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/487345/123226921-ffcce600-d4cb-11eb-8027-78e179b53e24.png">

Is perhaps what you want a summary of all accounts over a defined period with the deposits, withdrawals, and net balance for the period?

**Comment by vomikan** [comment]
@whalley What do you think? Is this request already outdated?

**Comment by whalley** [comment]
@vomikan  Yes, this is already covered. Closing
