### ISSUE TITLE
Data for Closed Accounts not included in Summary Of Accounts 'Monthly' or 'Yearly' Reports 

### ISSUE THREAD

**Issue by ChrisCross321** [moneymanagerex/moneymanagerex#3650]
MMEX version:
 - [x] 1.5.2
 - [x] 1.5.3

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When running Summary Of Accounts 'Monthly' Report all history data from accounts that have been closed are no longer included in all the previous months. This appears to be the case for all types of accounts.
This also occurs for the Summary Of Accounts 'Yearly' Report for accounts that have been closed.
This bug did not occur on version 1.5.1 and all previous versions.  

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Run Summary Of Accounts 'Monthly' Report and take a screenshot of the results for checking.
2. Select any 'Open' account that has had a balance for at least a few months and set it to 'Closed'.
3. Rerun Summary Of Accounts 'Monthly' Report and check data against report run in (1.) and the report will now be missing the history data from the account now closed. 
4. Alternatively run Summary Of Accounts 'Monthly' from version 1.5.3 and using the same database file run the report using version 1.5.1 and compare the results.  The differences will be any closed accounts.
5. The same outcome should occur when you run Summary Of Accounts 'Yearly', although data will have to have existed in closed accounts for over a year to clearly see the bug. 

…

Expected result:
All the history of data from closed accounts should be included and appear for each Month (or Year) in the reports.
   
Actual result:
No history of data from closed accounts is included therefore does not appear each Month (or Year) in the reports.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3625.

Fix available, will be in 1.5.4.
