### ISSUE TITLE
DEPOSIT ENTRY PROBLEM

### ISSUE THREAD

**Issue by BKtheDJ** [moneymanagerex/moneymanagerex#3656]
Money manager version 1.5.3 will not accept deposit or payment entries over $999.99. They have to be broken down into groups of less than $1,000.00 each.

**Comment by tactilis** [comment]
Known problem. Duplicate of #3626

Fixed in next version. Please see: [https://forum.moneymanagerex.org/viewtopic.php?p=22139#p22139](https://forum.moneymanagerex.org/viewtopic.php?p=22139#p22139)
