### ISSUE TITLE
Translation strings

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3660]
@whalley  please make this strings identical.
![image](https://user-images.githubusercontent.com/6836805/123675589-93474380-d84b-11eb-8104-576e5553c9e1.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/123681696-c8a35f80-d852-11eb-975a-9c1ea83d0366.png)

**Comment by whalley** [comment]
Made mental note to be consistent in future!

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/3662
