### ISSUE TITLE
Travis-Ci

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#3665]
Should we move to travis-ci.com? Looks like .org is not working anymore

**Comment by tactilis** [comment]
#3053

**Comment by gabriele-v** [comment]
![image](https://user-images.githubusercontent.com/7106290/123702366-525b2900-d863-11eb-80fb-93c1fa62cec3.png)

Here we had also Travis in the past, not only AppVeyor

**Comment by whalley** [comment]
Think that now we have both AppVeyor and Circle-ci running there is currently no need to consider Travis-ci. Closing.
