### ISSUE TITLE
Dark Mode theme lacks contrast in wcTreeCtrl's on MacOS

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3666]
MMEX version:
 - [X] 1.5.x

There is an issue with rendering the buttons on wxTreeCtrl's - https://trac.wxwidgets.org/ticket/19204. They are always rendered in black which causes problems on DarkMode theme. There is no contrast between the buttons and the background

Suggest changing:

`"navigationPanel": "#07072B",`

![image](https://user-images.githubusercontent.com/487345/123715942-4e360800-d871-11eb-93d8-976e2ac8c17d.png)
![image](https://user-images.githubusercontent.com/487345/123716045-8a696880-d871-11eb-992c-db8f9a5a93df.png)

to:

`"navigationPanel": "#444444",`

![image](https://user-images.githubusercontent.com/487345/123715877-2ba3ef00-d871-11eb-822b-dbd68a08176f.png)
![image](https://user-images.githubusercontent.com/487345/123716108-b5ec5300-d871-11eb-84c5-9f98db505abf.png)

**Comment by MartinX3** [comment]
Fixed in Linux as well
