### ISSUE TITLE
Crash on database creation 1.5.3

### ISSUE THREAD

**Issue by tayrayb** [moneymanagerex/moneymanagerex#3667]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [x] Linux 

# Description of the bug

Money Manager EX 1.5.3 crashes on making a new database, when setting the currency. This happens in both Linux and Windows.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  Create new database
2.  Set Currency
3.  CRASH!

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

[report.tar.gz](https://github.com/moneymanagerex/moneymanagerex/files/6729901/report.tar.gz)

**Comment by Dandy64** [comment]
I can confirm this problem. It was reproduced on Windows 10 on 2 laptops: Dell and Lenovo.

**Comment by whalley** [comment]
Sam on MacOS.

https://github.com/moneymanagerex/moneymanagerex/blob/107af4e06a0a0fc8af5d9a976c936c260d20d012/src/wizard_newdb.cpp#L137

From a quick scan , easiest fix is to set currencyID_ to a default currency here (maybe the first one we find in DB) as no default obviously exists yet?
