### ISSUE TITLE
Show remaining credit limit on Credit Cards

### ISSUE THREAD

**Issue by Adelzu** [moneymanagerex/moneymanagerex#3678]
# Description of the feature

In the credit card transactions list (or basically any account). It would be nice to add a column that shows the remaining amount for credit limit. For example, if i set the credit limit of Card 1 to $1,000.00 the column will show the running remaining credit limit by using the formula {Credit Limit} - {Balance}.

This would make it easier to reconcile transactions and to understand if an action is needed.

**Comment by Adelzu** [comment]
formula {Credit Limit} - {Balance} is incorrect. It should be formula {Credit Limit} + {Balance} as balance is negative while the credit limit is not.

**Comment by Adelzu** [comment]
If anyone can guide me to the right direction on where this needs to be done, i will be able to do it (Hopefully).
Also, how do you compile the project and debug it?

**Comment by vomikan** [comment]
Win or nix?
