### ISSUE TITLE
Provide 'view reset' option

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3681]
https://forum.moneymanagerex.org/viewtopic.php?p=22184#p22184

It is possible to undock the toolbar and navigation panel and somehow 'lose' them. Even an attempt to hide/unhide the bars will restore them to the 'hidden' undocked position. 

It is suggested we have a 'reset view' option that could be used to re-dock the toolbars and perhaps also recentre the application on the main display.

**Comment by renato-mmex** [comment]
![Daumen](https://user-images.githubusercontent.com/76920138/124178832-42855400-dab2-11eb-9b23-00378c930ddb.gif)

**Comment by tycariadus** [comment]
This is still an issue especially when using a single screen / travelling.  The Navigation screen seems to have undocked itself from the left hand side and become a pop out, or when re do View Navigation it puts it at the top using unnecessary space.  How do you reset it back to to the original default?

**Comment by whalley** [comment]
Have assigned to a release.

**Comment by tycariadus** [comment]
Thanks Mark for this and the other email !!
