### ISSUE TITLE
Import data in multiple accounts with single file

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#3683]
# Bulk Import
Allow importing into multiple accounts using single csv file. On the import dialog, provide a link to a little help article on how to use this feature.
TODO Support a new column in import CSV file - here are options.
1. 'Account Name': allow the name of the account as user  configured when creating account. Must add validation to disallow two accounts with same name.
2. 'Account Number': allow the full account number which can be a unique identifier, in most cases
2. 'Account Id' : allow the ID of the account. On Account Edit screen, READONLY display the account ID from database and mention

Here is the account number I am referring to
![image](https://user-images.githubusercontent.com/10950385/124205215-23bfa580-db24-11eb-887b-2b0c16879661.png)

# Use cases

User has multiple accounts with one bank.
User has to do a bit of massaging of exported CSVs in Excel before importing into MMEX.
1. add comments to description
2. change date format
3. append balance to the notes etc.
These operations are better done in one file rather than repeated in each file.
But currently MMex allows only import one file per account.
If we do allow import into multiple accounts, this can be solved.

**Comment by tactilis** [comment]
May I ask please:

1. How many accounts you have with the same bank?

2. How frequently you download transactions from the bank and import into MMEX?

3. Whether the bank provides a means of downloading a single CSV file for all the accounts, or whether your single CSV file would exist only as a result of having to massage the separate CSV files in Excel?

4. What _exactly_ is the massaging of the CSV that is required? Is this something that might be handled in MMEX by appropriately extending the import functionality?

**Comment by sarjanwebdev** [comment]
> May I ask please:
> 
> 1. How many accounts you have with the same bank?
9
> 2. How frequently you download transactions from the bank and import into MMEX?
1st of every month for last month
> 3. Whether the bank provides a means of downloading a single CSV file for all the accounts, or whether your single CSV file would exist only as a result of having to massage the separate CSV files in Excel?
Bank only allows one file per account
Because my data preparation process is same for all 9 files, I want to combine the CSVs, prepare and import in one go.
Sometimes an account would have only 1 transaction, I still have to go through the entire drill for one file, but including it as a line in a big file makes life easy.
> 4. What _exactly_ is the massaging of the CSV that is required? Is this something that might be handled in MMEX by appropriately extending the import functionality?
MMEX can handle date formats, but adding comments in description is a manual task
Also, bank gives a balance on each line, But MMEX has it's own calculated balance on each DISPLAYED transaction row. Would it still make sense to import balance column?

**Comment by tactilis** [comment]
The requirement:

> 9 accounts
> Imported 1st of every month for last month
> Bank only allows one file per account
> Because my data preparation process is same for all 9 files,

I'd seriously look at investing some time to write some AutoIt scripts to automate this repetitive task - both the Excel part and the MMEX Import part.

AutoIt is a brilliant tool for automating this sort of repetitive task. It's well worth investing a bit of time to learn how to use it. You can tailor to scripts to match _your_ particular workflow, which will be different from other people's workflows.

**Comment by tactilis** [comment]
> Also, bank gives a balance on each line, But MMEX has it's own calculated balance on each DISPLAYED transaction row. Would it still make sense to import balance column?

Why?

What would you expect MMEX to do with the balance read from the CSV file?

MMEX _has to_ calculate the balance itself, based on the transactions that are entered in its transaction list. If you added, deleted, or modified a transaction in MMEX for whatever reason, then you would expect MMEX to calculate an updated balance, rather than display the original balance imported from the file.

**Comment by sarjanwebdev** [comment]
> > Also, bank gives a balance on each line, But MMEX has it's own calculated balance on each DISPLAYED transaction row. Would it still make sense to import balance column?
> 
> Why?
> 
> What would you expect MMEX to do with the balance read from the CSV file?
> 
> MMEX _has to_ calculate the balance itself, based on the transactions that are entered in its transaction list. If you added, deleted, or modified a transaction in MMEX for whatever reason, then you would expect MMEX to calculate an updated balance, rather than display the original balance imported from the file.

I copy/append the bank's balance at the end of the description on each line, because when visually reconciling at the end of each day, it is easy to tally if balances match.

**Comment by tactilis** [comment]
Still trying to properly understand your exact workflow, which is important because you are requesting some significant changes to MMEX, which would require a lot of development and testing from the overworked Devs. Such changes, if implemented, need to be right and really need to be useful to many people, not just a few.

> because when visually reconciling at the end of each day, it is easy to tally if balances match

Not sure I understand this statement because a few messages ago you said you imported transactions on:

> 1st of every month for _last_ month

Why are you having to reconcile a balance at the end of _each_ day?  Don't you just check the MMEX calculated balance, which is based on the imported transactions, with the bank balance for the end of the month?

**Comment by sarjanwebdev** [comment]
> Still trying to properly understand your exact workflow, which is important because you are requesting some significant changes to MMEX, which would require a lot of development and testing from the overworked Devs. Such changes, if implemented, need to be right and really need to be useful to many people, not just a few.
> 
> > because when visually reconciling at the end of each day, it is easy to tally if balances match
> 
> Not sure I understand this statement because a few messages ago you said you imported transactions on:
> 
> > 1st of every month for _last_ month
> 
> Why are you having to reconcile a balance at the end of _each_ day? Don't you just check the MMEX calculated balance, which is based on the imported transactions, with the bank balance for the end of the month?

I understand the impact here.
Please de-prioritise this. It's very specific to my case scenario.
Thanks for the attention.

**Comment by sarjanwebdev** [comment]
I just discovered the close issue button
