### ISSUE TITLE
Empty row detection messed up records

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#3685]
MMEX version: 1.5.x
Money Manager Ex
Version: 1.5.3 64-bit
• Build on Jun 13 2021 15:28:37
• Database version: 7 • (aes128cbc)

Operating System: Windows

# Description of the bug
MMEx import could sense empty rows

# Reproduction
Is the bug reproducible? 
 - [ ] Always 

Reproduction steps:

1. Download bank CSV 
2. Open in excel
3. Delete some records which were already imported before
4. Excel leaves ",,,," in those deleted rows in CSV
5. Import in MMEX
6. Navigate the account.
7. MMEX Crashes. 

…

Expected result:
MMEX should not crash

Actual result:
MMEX Crashes
Potential cause is the date format translation
Best mitigation is to reject such empty rows

# Additional information

File in VS Code at repro step 4
![image](https://user-images.githubusercontent.com/10950385/124216158-e31e5700-db38-11eb-9756-82f2e630c5ab.png)

MMEX Records displayed in Valentina Studio SQL Browser
![image](https://user-images.githubusercontent.com/10950385/124216218-0ea14180-db39-11eb-833f-d59d3fe73ea9.png)

**Comment by tactilis** [comment]
> Delete some records which were already imported before
> Excel leaves ",,,," in those deleted rows in CSV

It sounds as though you are not actually _Deleting_ the rows but are just clearing the contents of those rows.

Like you, I have to remove any previously imported transactions - but I _delete_ the rows. I do not get the problem that you are seeing.

That said, MMEX should not crash on invalid input.

To help @vomikan fix this, could you post a screenshot of your Import dialog, so that he can see the order of fields and the date format you are using.

**Comment by whalley** [comment]
Such input is not valid as you would expect correct data to be present in each line of file, however I agree MMEX should not be crashing.

As noted delete the rows in Excel first before exporting.

**Comment by sarjanwebdev** [comment]
![image](https://user-images.githubusercontent.com/10950385/124257266-8db16c80-db6f-11eb-8eca-d94ca7e185fb.png)

**Comment by sarjanwebdev** [comment]
I feel this still holds value

**Comment by n-stein** [comment]
@sarjanwebdev I believe I fixed this a while ago, possibly for 1.6.4 but definitely for 1.7.0. MMEX will disregard records with no tokens when importing and throw a message in the log such as "Line 2: Empty". Can you confirm you no longer experience this issue?

**Comment by whalley** [comment]
Closing. We can re-open as needed.
