### ISSUE TITLE
Allow filter by transaction highlight color

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#3686]
# I can add color to rows but cannot filter by that

![image](https://user-images.githubusercontent.com/10950385/124220129-b9692e00-db40-11eb-9c1b-80a684e49f5f.png)

**Comment by vomikan** [comment]
Related issue:
https://github.com/moneymanagerex/moneymanagerex/issues/3653

**Comment by whalley** [comment]
Fix pushed to master repo (commit message has wrong issue no) - https://github.com/moneymanagerex/moneymanagerex/pull/3713

**Comment by sarjanwebdev** [comment]
Thank you team! This works!
