### ISSUE TITLE
QIF file dates should be configurable

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#369]
Currently, the dates in exported .qif file are stored in ISO format (D2015-01-24). 
Quicken imports this but shows the imported transaction(s) at the beginning, instead of the end, of the transaction list. The displayed date in Quicken looks correct but something is obviously wrong. While this is clearly a Quicken bug, it would still be helpful to be able to configure the date for the export file in order to work around this problem.
The date configuration for the desktop version contains all the Quicken date formats already. Only, the set date is not used when exporting to .qif file.
When Quicken exports the .qif file, the dates are in the following format: MM/DD'YY (1/24'15)

For this reason, the category does not get imported into Quicken. If I fix the date manually, the transaction gets imported correctly.

**Comment by guanlisheng** [comment]
@vomikan ,would you help to take a look ?

**Comment by vomikan** [comment]
@guanlisheng Please exams
https://github.com/moneymanagerex/moneymanagerex/compare/QIFexport?expand=1

**Comment by guanlisheng** [comment]
Would you mind to send a pull request?

**Comment by MisterY** [comment]
Thanks, guys! Looking forward to the new release.

**Comment by MisterY** [comment]
I don't see any changes in the latest beta. Is there a way to set the date format for QIF export?

**Comment by MisterY** [comment]
I see it. Thanks!
