### ISSUE TITLE
Asset Transactions don't add up to home screen or Asset Value

### ISSUE THREAD

**Issue by Philo21** [moneymanagerex/moneymanagerex#3692]
MMEX version:
 - [X] 1.5.3 Portable 64bit
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Asset Current Value does not add up to the transactions below it.  
however the asset account view shows correctly.

If you turn off the Transfer button then it changes the Asset Overview Initial value to to - and current value to - (see last image)

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Add asset transaction Deposit (transfer Ticked) Status reconciled. Select payee and category.
2. Click ok
3. 

…

Expected result:
Initial value should stay the same. Actual value should increase by amount deposited or withdrawn
Actual result:
Initial result and Current value remain the same. even after restart

# Additional information

![image](https://user-images.githubusercontent.com/2927552/124675564-3bba6f00-df00-11eb-8322-701b6e17b26d.png)
![image](https://user-images.githubusercontent.com/2927552/124675592-46750400-df00-11eb-9541-f1881778e4a6.png)
![image](https://user-images.githubusercontent.com/2927552/124675665-673d5980-df00-11eb-9ec7-daff05b3e47c.png)
If you turn off the Transfer button then it changes the Asset Overview Initial value to to - and current value to - (see last image)
![image](https://user-images.githubusercontent.com/2927552/124675881-e0d54780-df00-11eb-8458-081be822959e.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3545
