### ISSUE TITLE
Crashes when "Set Currency" button is clicked during database creation

### ISSUE THREAD

**Issue by Strongbeard** [moneymanagerex/moneymanagerex#3694]
MMEX version:
 - [x] 1.5.3
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Money Manager EX 1.5.3 on Windows 10.0.19042 crashes when the `Set Currency` button is clicked during first database creation on a system. I do not know if this only occurs on systems that never had Money Manager EX installed on them before since I have no other systems to test this on.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Install Money Manager EX 1.5.3 64-bit to "C:\Program Files\Money Manager EX" (Only tested on the regular version. Not the portable version.)
2. Run the program.
3. Click `Create a New Database`
4. Enter any name for the `File name:` textbox and click the `Save` button.
5. Click the `Next >` button in the `New Database Wizard` window.
6. Click the `Set Currency` button. Error also occurs when a value has been entered into the `User Name` textbox. Crash also occurs when `back` and `cancel` are selected instead.
7. `Debug report "MoneyManagerEx"` window appears.

Expected result:
A dialogue window appearing allowing the user to select a currency.

Actual result:
A crash report window appears.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
[MoneyManagerEx_dbgrpt-16008-20210708T181618.zip](https://github.com/moneymanagerex/moneymanagerex/files/6787587/MoneyManagerEx_dbgrpt-16008-20210708T181618.zip)

**Comment by tactilis** [comment]
Known problem, fixed in next version.

Please see #3667
