### ISSUE TITLE
Problem building latest master on linux, Can't find wxWidgets_LIBRARIES

### ISSUE THREAD

**Issue by CorneliaXaos** [moneymanagerex/moneymanagerex#3695]
Hello, I have been trying to build the latest master branch for Linux (PopOS, Hirsute) as prebuilt binaries aren't available for it.  Things used to build just fine (back around 1.2 or 1.3, I think) but at some point they stopped functioning.  I noticed the build instructions changed for MacOS and now references steps that probably don't apply to Linux builds (despite the Linux build steps saying to do what MacOS does) so I've done the following:

1. Cloned the wxWidgets repository, checked out tag v3.1.5, built, and installed system wide.  (`wx-config --version-full` seems to confirm this as a success)
2. Cloned the MoneyManagerEX repository, and attempted to configure it to build:
```
mkdir moneymanagerex/build
cd moneymanagerex/build
cmake -DCMAKE_BUILD_TYPE="Release" ..
```

This produces the following error:
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
  least version "2.9.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
  CMakeLists.txt:293 (find_package)
```

I attempted to resolve this issue myself and after a few hours of searching have come up dry.  I'm aware of [this issue](https://github.com/moneymanagerex/moneymanagerex/issues/1947) that was closed a while back, and have attempted a few of the fixes there.  None of them seem to work.  I could use a bit of assistance on this, and can provide any information needed.

**Comment by vomikan** [comment]
sudo ldconfig
After wx install

**Comment by CorneliaXaos** [comment]
Hey, @vomikan ,  I did that after completing the wxWidgets build and install process outlined [here.](https://github.com/wxWidgets/wxWidgets/blob/master/docs/gtk/install.md)  If the library path is the problem, it is not because of missing the ldconfig step.

**Comment by whalley** [comment]
When building MMEX add something like below to reference your 3.1.5 wxWidgets build? 

-DwxWidgets_CONFIG_EXECUTABLE={PATH-TO-wxWidgets}/wxWidgets-3.1.5/build/wx-config

**Comment by CorneliaXaos** [comment]
@whalley , I tried:
```
cmake -DCMAKE_BUILD_TYPE="Release" -DwxWidgets_CONFIG_EXECUTABLE=/home/cornelia/Programming/wxWidgets/buildgtk/wx-config ..
```
and it still fails with the same error.  wxWidgets is checked out and built at v3.1.5 .  I believe I tried this yesterday as one of the possible solutions, but it wasn't working.  (I should also clarify that I have moneymanagerex checked out to master sometime yesterday.  Commit ce989600561da700981c13353872ad32c522e270 .

**Comment by vomikan** [comment]
Do you tried this solution?
https://github.com/seandepagnier/rtlsdr_pi/issues/25#issuecomment-624861477

**Comment by CorneliaXaos** [comment]
@vomikan yes, and I don't have any alternatives for wx-config.  The version I built and installed is the only one on my system.

**Comment by CorneliaXaos** [comment]
So I resolved my issue.  wxWidgets wasn't building with webkit support and that was why it was "failing to find" wxWidgets.  As a tip to anyone who might find this in the future, if something in cmake fails, check if there's debug messages you can enable:

**<cmake-installation>/Modules/FindwxWidgets.cmake:160"
```
# FIXME: This and all the DBG_MSG calls should be removed after the
# module stabilizes.
#
# Helper macro to control the debugging output globally. There are
# two versions for controlling how verbose your output should be.
macro(DBG_MSG _MSG)
#  message(STATUS
#    "${CMAKE_CURRENT_LIST_FILE}(${CMAKE_CURRENT_LIST_LINE}): ${_MSG}")
endmacro()
macro(DBG_MSG_V _MSG)
#  message(STATUS
#      	  "${CMAKE_CURRENT_LIST_FILE}(${CMAKE_CURRENT_LIST_LINE}): ${_MSG}")
endmacro()
```
**cmake -DCMAKE_BUILD_TYPE="Release" ..**
```
1-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_FIND_COMPONENTS : core;qa;html;xml;aui;adv;stc;webview;base;scintilla
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_SELECT_OPTIONS=--debug=no
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_CXX_FLAGS=-I/usr/local/lib/wx/include/gtk3-unicode-3.1 -I/usr/local/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXGTK__ -pthread
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_DEFINITIONS=_FILE_OFFSET_BITS=64;wxDEBUG_LEVEL=0;WXUSINGDLL;__WXGTK__
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_INCLUDE_DIRS=/usr/local/lib/wx/include/gtk3-unicode-3.1;/usr/local/include/wx-3.1
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_CXX_FLAGS=-pthread
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets required components : core;qa;html;xml;aui;adv;stc;webview;base
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets optional components : scintilla
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_LIBRARIES=-L/usr/local/lib;-pthread;;;-lwx_gtk3u_core-3.1;-lwx_gtk3u_qa-3.1;-lwx_gtk3u_html-3.1;-lwx_baseu_xml-3.1;-lwx_gtk3u_aui-3.1;-lwx_gtk3u_stc-3.1;-lwx_gtk3u_webview-3.1;-lwx_baseu-3.1
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets_LIBRARY_DIRS=/usr/local/lib
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(171): wxWidgets not found due to following missing libraries: wx_gtk3u_webview-3.1
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_FOUND           : FALSE
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_INCLUDE_DIRS    : /usr/local/lib/wx/include/gtk3-unicode-3.1;/usr/local/include/wx-3.1
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_LIBRARY_DIRS    : /usr/local/lib
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_LIBRARIES       : 
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_CXX_FLAGS       : -pthread
-- /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake(167): wxWidgets_USE_FILE        : /usr/share/cmake-3.18/Modules/UsewxWidgets.cmake
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
  least version "2.9.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
  CMakeLists.txt:293 (find_package)
```

Though.. hopefully in the future you will actually be able to enable those debug messages without manually removing the comments..

It finally works..  and no more random crashing when switching between reports (because of custom built wxWidgets).  Thank you all for your patience and the work you do on this software.
