### ISSUE TITLE
'Confirm to add new payee' ignored

### ISSUE THREAD

**Issue by davidgreen99** [moneymanagerex/moneymanagerex#3696]
When I am creating a transaction and enter a payee for the first time, I am forced to add new payees to my payees list, even if I don't want to.

1. Open the **New Transaction** dialog.
2. Enter details including a new payee.
3. In the **Confirm to add new payee** dialog, select **No**.

Expected behaviour: Transaction is created and the payee is not added to the payees list.
Actual incorrect behaviour: the **New Transaction** dialog stays open and the transaction does not complete. The only way to complete the transaction is to select **Yes** in the **Confirm to add new payee** dialog!

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1390

**Comment by whalley** [comment]
This is expected behavior. The 'Confirm to add new payee dialog' is askeing you to confimr that you wish to add a new payee and have not mistyped an existing Payee.  All Payees must be in the Payee list. See link @vomikan mentioned for suggestions on maintaining the Payeee list.

**Comment by davidgreen99** [comment]
Thank you for your quick reply and explanation. The fact that I reported this as a bug shows that the purpose of the  'Confirm to add new payee' dialog is not clear. Basically, the question "do you want to add new payee?" strongly suggests that you can choose NOT to remember the payee!

If payees are always added, I don't think it is necessary to interupt the workflow by displaying this confirmation dialog at all. Reasoning:
- the Payee field already presents a list of similar payees, helping me to pick an existing payee spelling
- users expect new payee details to be remembered for next time (i.e. get added to the payees list). After all, this is smart software!

If you are determined to show a confirmation dialog, please make it's purpose less ambigous by making the following text label improvements:
- title 'Confirm to add new payee' change to 'Confirm payee name'
- text 'Do you want to add new payee?' change to 'Is this payee spelt correctly?' (yes/no)
