### ISSUE TITLE
Minor GUI improvement

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3701]
It is worth to make all the tables titles **bold** or/and add a bit of color to the titles' (upper) line.

![image](https://user-images.githubusercontent.com/83161661/125605120-1b8624ff-4585-4eeb-a05e-2cbae97df516.png)

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by tactilis** [comment]
@Dandy64 I don't know why your header row doesn't have any shading.

As you can see below, mine does.

![image](https://user-images.githubusercontent.com/4060092/125669895-4adbbb09-1300-4375-9c5a-acd789df83e2.png)
 
I'm on Windows 7 and using the MMEX default theme. You haven't said what your OS and MMEX theme is.

Bold headers are **not** common in applications:

![image](https://user-images.githubusercontent.com/4060092/125671085-4e9a5c65-7c6f-4b8a-b1a6-1ab2d7cf233c.png)

![image](https://user-images.githubusercontent.com/4060092/125671652-e956e6b6-7346-45c6-bb43-e38e555151b0.png)

![image](https://user-images.githubusercontent.com/4060092/125672038-e4746fed-4df7-4192-9ba4-879ce6d902f3.png)

**Comment by whalley** [comment]
On MacOS with the default theme I get below. Which, whilst using the same color, seems fine and my list font is slightly larger.  I'm not sure how easy in wxWidgets this color can be changed - form a cursory glance it is not obvious.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/487345/125683084-7a0ad841-a842-467f-a7f6-20bd838c2f83.png">

**Comment by Dandy64** [comment]
"I'm on Windows 7 and using the MMEX default theme. You haven't said what your OS and MMEX theme is."

Sorry. Windows 10, MMEX 1.54 Beta (1.53 - the same)
![image](https://user-images.githubusercontent.com/83161661/125776174-b4a7b07a-bd75-4f58-8d53-bc89e0cecc72.png)

**Comment by vomikan** [comment]
How it looks on Windows 10 

![image](https://user-images.githubusercontent.com/6836805/127750290-9c999714-fe30-48ef-ae03-8758bbd3e97e.png)

All other applications look similar. I think we should rely on the style of the operating system here, and not add something else to the application.

**Comment by vomikan** [comment]
We will leave everything as it is. Don't get us wrong.
