### ISSUE TITLE
Minor GUI fix

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3702]
MMEX version:
 - [x ] 1.5.x
 - [ ] 1.6.x
It is necessary to add an automatic space between Category and Subcategory, otherwise, the user needs manually add extra space before every Subcategory.
_Dining out.

![image](https://user-images.githubusercontent.com/83161661/125605618-b5a8404a-bcb4-4d9f-8ae7-3e65a2f79559.png)

Operating System:
 - [ x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Try to change the category delimiter

![image](https://user-images.githubusercontent.com/6836805/125608000-b0fa02dd-007e-445d-946c-aa68c1d4ebe4.png)

**Comment by Dandy64** [comment]
No, I tried all of them.

**Comment by vomikan** [comment]
I don't understand the essence of this case.

**Comment by Dandy64** [comment]
I have chosen a category **Food** and a subcategory **Dinning out**.

In the transaction, it looks like **Food:Dinning out**, without space between **Food:** and **Dinning out**. 
It must look like **Food: Dinning out**. So in order to add a space between the Category and Subcategory, I need to edit every subcategory item to add extra space before the subcategory name.
For example:
...........Dinning out turns into ............_Dining out

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/125623461-f000286e-9c50-4e92-9ed0-a8565243f95f.png)
![image](https://user-images.githubusercontent.com/6836805/125623399-b3030534-59ad-409c-afb6-a9ba4bca1e6b.png)

**Comment by Dandy64** [comment]
![image](https://user-images.githubusercontent.com/83161661/125624813-84acbad8-af2e-4fce-b8cf-96eb91d5ceef.png)
![image](https://user-images.githubusercontent.com/83161661/125624913-4de7fccf-c43f-4a23-b23b-a065b7ac92b5.png)

**Comment by Dandy64** [comment]
I have said that I tried all the options of Category Delimiter.

**Comment by vomikan** [comment]
I am confused why it working for me.

**Comment by Dandy64** [comment]
I have found when it happens! :-) If Locale empty...

![image](https://user-images.githubusercontent.com/83161661/125630730-6965dab2-8178-4d33-916a-148cdba8e75b.png)

**Comment by Dandy64** [comment]
If I change it from empty to En-US for example, this **:** start working!

**Comment by vomikan** [comment]
It's a strange behavior. possible a bug.
