### ISSUE TITLE
Apertura nuovo conto Saldo iniziale

### ISSUE THREAD

**Issue by Tullio24** [moneymanagerex/moneymanagerex#3703]
Se crei un nuovo conto o vai a modifica conto saldo iniziale non accetta Saldo Iniziale se l'importo necessita sia del punto che della virgola e chiede di inserire un valore calcolato. Purtroppo non riesco ad inserire l'immagine

<hr>Version: 1.5.3 64-bit<br>
 • Build: Giu 13 2021 15:28:37<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Italian (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Using Google Translate:

> If you create a new account or change initial balance account does not accept initial balance if the amount needs to be the point and of the comma and asks to enter a calculated value. Unfortunately I can't enter the image

Is this the locale problem?

It may be fixed for 1.5.4 already

**Comment by whalley** [comment]
@Tullio24  Is this issue fixed for you in v1.5.4 ?

**Comment by whalley** [comment]
No response from issue originator. View is that this is fixed by the recent locale fixes so closing. 

@Tullio24 if you are still experiencing the issue it can be re-opened.
