### ISSUE TITLE
cannot set currency when creating new database

### ISSUE THREAD

**Issue by aragorn7773** [moneymanagerex/moneymanagerex#3704]
Hi, I just downloaded 1.5.3 for MacOS and when creating a new db, I click Set Currency button and it crashes every time without fail.  This bad, because I have also tried to skip setting the currency and I typed in my user name, clicked continue and get an error telling me that I MUST set the currency. I try and it crashes with out fail. 

HELP!

**Comment by aragorn7773** [comment]
however, 1.5.2 allows me to set the currency as expected and demanded and I can continue.  I do not advise using 1.5.3 and suggest you remove it for MacOS users until this critical bug is fixed.

**Comment by barryburton** [comment]
Same issue on Windows 10, needed to use an older version to create a database file.

**Comment by aragorn7773** [comment]
I did the same thing.  1.5.2 works as advertised.

Allen

**Comment by aragorn7773** [comment]
anyone know if this issue is being addressed?

**Comment by vomikan** [comment]
Known problem, fixed in next version.

Please see #3667

**Comment by aragorn7773** [comment]
Thx so much for responding Nikolay. I deeply appreciate being notified and to know that the bug is fixed. 👍 😄 😄 😊 😊 

Thank you

Allen

**Comment by aragorn7773** [comment]
this issue has been found and fixed in the next version.  God bless the developers!!! :)
