### ISSUE TITLE
Changing transaction type

### ISSUE THREAD

**Issue by farfenoogan** [moneymanagerex/moneymanagerex#3705]
Version: 1.5.3 64-bit
• Build on Jun 13 2021 15:28:37
• Database version: 7 • (aes128cbc)MMEX version:

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code  (It does)
(master branch).

Operating System:
 - [ ] Windows 10

# Description of the bug
I recently decided to change the transaction type on a certain group of transactions, as I have over the years used 2 different types in these transactions (Withdrawal and Transfer).  When I changed the transaction type from Withdrawal to Transfer, the amount changed from $1,000.00 to $1.00 and no matter how many times I tried to set the correct amount it would always return to $1.00.  To fix the amount I used DB Browser to find and fix the transaction.  The correct amount is shown in MMEX afterwards.

# Reproduction

Is the bug reproducible? 
 - [X] Always 

Reproduction steps:

1. Edit a withdrawal transaction
2. Change the type to Transfer
3. The amount changes to $1.00 at that point.

Expected result:
The type changes and nothing else about the transaction is changed.

Actual result:
The type changes and the amount changes as well

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Please evaluate this issue with newest build
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/40028803/job/2hueqfd8m48ssbl0/artifacts

**Comment by whalley** [comment]
@farfenoogan Do you still have this issue with the v1.5.4 release?

**Comment by farfenoogan** [comment]
No. It appears to be corrected

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
