### ISSUE TITLE
Amount field enters "," as "."

### ISSUE THREAD

**Issue by aka13-404** [moneymanagerex/moneymanagerex#3709]
MMEX version:
 - 1.5.4 portable

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - Windows

Is the bug reproducible? 
 - Always 

I have a pc with a german QWERTZ layout. On the numerical keyboard I therevore have the "," (COMMA) and not the "."(FULL STOP)  as on an English keyboard. My currency is set properly. 
![image](https://user-images.githubusercontent.com/51682059/126188267-bae5ed4a-5d13-4bc9-b119-d941fe781039.png)

When I try to enter an Amount, the "," key on the numerical block is interpreted as a "."
![image](https://user-images.githubusercontent.com/51682059/126188457-ea4c7ada-3fa0-4863-94cd-ead00752adee.png)
In all other fields, other apps and on windows the key works properly. 

I think this behavior started appearing since 1.5.3, but I am not sure.

I would appreciate any help and ideas on what might be causing the issue, since it is driving me mad.

**Comment by whalley** [comment]
Related? https://github.com/moneymanagerex/moneymanagerex/issues/3622

**Comment by aka13-404** [comment]
Seems related to me, yes.

![image](https://user-images.githubusercontent.com/51682059/126475869-a10df85c-54bb-4214-bd65-cde6235a1e0d.png)
First I tried setting the region to blank. My machine runs with "Germany" region, with "English(Germany)" as regional format data.

When blank, the entered sign remains "." (FULL STOP), which gets ignored, and ",00" is added at the end. 
![image](https://user-images.githubusercontent.com/51682059/126479425-b930d5dc-c691-4a30-84d9-2dd23a8bd184.png)


The funny thing is, that no matter what I try to enter in the field, it does not let me save, so I can not edit/add transactions with this region setting.
![image](https://user-images.githubusercontent.com/51682059/126479355-63f41cd8-f7b0-47ac-bcce-4fa6ed7d87a7.png)




When changing the region setting en_US, the the entered sign remains "." (FULL STOP), which works as expected, and lets me save transactions.
![image](https://user-images.githubusercontent.com/51682059/126480315-2aae7974-52cd-4359-8def-b523989af9ba.png)


When I set the region back to de_DE, and go to "Organize currency", the EUR has "." (FULL STOP) set as the decimal, while the preview at the bottom stays correct. If I edit it by hand, and set it to "," (COMMA), my keyboard starts working as expected in the amount  field,  and I can create and edit transactions again.
![image](https://user-images.githubusercontent.com/51682059/126483288-32a40987-9a31-4051-ab7d-76a3645b2139.png)

**Comment by TomAff** [comment]
I left it blank and it works :)
![2021-07-23 09_45_12-MMEX Optionen](https://user-images.githubusercontent.com/46572503/126752025-3cb0d92c-2d7d-4f7c-a1fd-45f1598cd56f.jpg)

**Comment by aka13-404** [comment]
Must be something trailing from old versions in the config, perhaps? 
I will try a clean install and report back.

**Comment by whalley** [comment]
@aka13-404 Did you resolve this?

**Comment by whalley** [comment]
Closing as no response from originator and likely issue is now fixed.
