### ISSUE TITLE
Payee changes when editing existing transaction (to change account)

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#3714]
MMEX version:
 - [x] 1.5.x

Operating System:
 - [x] Mac OSX

# Description of the bug

If you edit an existing transaction in order to change the account, the payee also changes to the new account name. 

# Reproduction
Create Transaction
Edit Transaction
Modify the account in the transaction dialog
Notice that the payee changes to be the same as the new account name

Is the bug reproducible? 
 - [x] Always 

…

Expected result: Payee should not change when editing account on an existing transaction

Actual result: Payee changes to new account name

**Comment by tactilis** [comment]
@omalleypat  I am unable to reproduce this using the description you have given.

Firstly, please state which version of MMEX you are using? You say 1.5.x but we need to know whether you see the problem in the latest version 1.5.4

Secondly, please provide the _exact_ steps to reproduce this:


An example, showing what I get is:

- [x] 1.5.4
- [x] Windows

1. Create two accounts: Account A and Account B
2. In Account A, enter a transaction with payee Payee A. Withdrawal or Deposit, Amount, and Category are not important. Click OK.
3. Edit the transaction and change the account to Account B. Click OK.
4. Observe that the transaction now appears in Account B and that the payee is still Payee A.

Expected Result
Payee name does not change when the account is changed

Actual Result
Payee name does not change when the account is changed


I'm not saying your report of what you see is incorrect. But it's not possible to reproduce it here, so I may have misunderstood your description, or there's something odd about your version of MMEX

**Comment by whalley** [comment]
Must be a Mac issue as I can replicate this. I will look at this.
