### ISSUE TITLE
Invalid vector<T> subscript error

### ISSUE THREAD

**Issue by TonySLondon** [moneymanagerex/moneymanagerex#3727]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Trying to delete tranaction

Please describe your issue with details.
![MMEX Error](https://user-images.githubusercontent.com/88109285/127377811-e005731e-840b-4561-be54-c579276f3c9f.jpg)
![MMEX Error](https://user-images.githubusercontent.com/88109285/127377882-d7dc3782-f4dd-4ddc-8794-c9ccc389edf2.jpg)

Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Can you please indicate the exact version of MMEX from the Help/About menu.

Is it possible to take a copy of you database and cut it down to the transaction that is causing the issue, then share?

**Comment by IanS5** [comment]
I was getting the same error trying to delete a transaction and its account. Here's the database, everything except the relevant account has been stripped out.

[VectorError.zip](https://github.com/moneymanagerex/moneymanagerex/files/6913390/VectorError.zip)

**Comment by whalley** [comment]
OK, I can see this is a share account. The transaction you have would seem to indicate it is link to some stock portfolio that is no longer there. I'm not too familiar with the investments/shares handling within MMEX (bit of a mystery to me and I've never had chance to investigate), I'll therefore have to leave it and hope somebody else to investigate this one at present. Alternatively I'll pick it up at a later date.

**Comment by IanS5** [comment]
The stock portfolio was there when the error started. I tried deleting it to get rid of the child share accounts, but it didn't remove this one.

**Comment by IanS5** [comment]
I've investigated a bit and it looks like the issue is a missing TRANSLINK record. The error occurs on [Model_Translink:145](https://github.com/moneymanagerex/moneymanagerex/blob/ff99e8b209e2bb2d370fe7494bca330c7501d5dc/src/model/Model_Translink.cpp#L145). It could also be `Model_Checking::foreignTransaction` returning a false positive, since `Model_Translink::RemoveTranslinkEntry` was called because it returned true. I'm not familiar enough with the codebase to tell.

**Comment by IanS5** [comment]
seems like the delete function isn't handling values from `UserTransactionPanel::CheckingType()` correctly. TOACCOUNTID set to those values on  `usertransactionpanel:473`

**Comment by vomikan** [comment]
#4129
#4113
