### ISSUE TITLE
Help/About display geometry

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#3738]
MMEX version:
 - [x] 1.5.5
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [X] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

**Help/About**
Running on:
• Windows 10 (build 22000), 64-bit edition
• German (windows-1252)
• 2560x1440 32bit 96x96ppi

would be correct:

Running on:
• **Windows 11** (build 22000), 64-bit edition
• German (windows-1252)
• **3840x2160** 32bit 96x96ppi

# Reproduction

Is the bug reproducible? 
 - [x ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by vomikan** [comment]
It shown virtual display size not real

![image](https://user-images.githubusercontent.com/6836805/127747471-32855268-85d2-4834-aada-ca0714a8b5e7.png)

I does not have  Windows 11.

**Comment by renato-mmex** [comment]
The fact that the virtual size of the display is shown is a bit confusing,
It is even more confusing that the virtual size of the main screen is displayed and not the virtual size of the monitor used by MMEX (in case of multiple monitors).
The Windows version is probably read out with a function, I wonder why the version 11 is not displayed here.
