### ISSUE TITLE
coincap.io API for crypto currencies

### ISSUE THREAD

**Issue by IanS5** [moneymanagerex/moneymanagerex#3743]
MMEX version:
 - [x] 1.5.x
 - [x] master (commit 9afa1e7b7db3b1e76f78ba0f06cf3d22be8e0258) 
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX can't find rates for SKALE (SKL).

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open the Currency Dialog
2. Add a new currency with symbol set to `SKL`
3.  Click the download currency values button

Expected result:

MMEX finds SKL conversion

Actual result:

MMEX fails to find SKL conversion

# Additional information

I'm pretty sure this happens becuase SKALE isn't on yahoo. Is it possible to fall back to CoinCap or another crypto-specific API?

**Comment by vomikan** [comment]
There is no any data on Yahoo regarding SKALE

https://query1.finance.yahoo.com/v7/finance/quote?symbols=SKL-USD&fields=regularMarketPrice,currency,shortName

**Comment by vomikan** [comment]
https://coincap.io/assets/skale-network

https://coincap.io/assets/skale-network
https://api.coincap.io/v2/assets/skale-network/history?interval=d1

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/128193362-bdf4b9b2-a996-4626-954c-45dd9664a567.png)
