### ISSUE TITLE
search doesn't work !!! I enter a word which I know is there in the note and nothing will return

### ISSUE THREAD

**Issue by jcodl** [moneymanagerex/moneymanagerex#3749]
<hr>Version: 1.5.5 64-bit<br>
 • Build: Čec 31 2021 11:25:27<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Czech (windows-1250)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
@jcodl Currently, the search matches from the start of the Notes text.

If the word you want to find is not at the start you need to use * as a wildcard.

Example:

Transaction 1 notes:   Car repairs
Transaction 2 notes:   More car repairs

Search:

Car     (matches Transaction 1)
car      (matches Transaction 1)

*Car*  (matches Transaction 1 and 2)
*car*   (matches Transaction 1 and 2)


NB. The MMEX Help file in section 7 'Searching for Information'. does not currently mention the need to use wildcards. It really ought to do so.

Also, in section 7.1 the Help says 'The search is case sensitive'. This is incorrect; the search is case insensitive.

**Comment by jcodl** [comment]
i found a solution, it is needed tu use * when i search hecht it is working for me search *hecht* :)

**Comment by jcodl** [comment]
thank you
