### ISSUE TITLE
Transaction Report Filter settings items in Navigation tree

### ISSUE THREAD

**Issue by drspoke** [moneymanagerex/moneymanagerex#3750]
# Description of the feature

Hello,
it would be really cool to use the transaction filter report as a template for the reports.
Not knowing anything about SQL, lua ..... that would allow me to see all the reports one under the other and we could have more than 10 reports ....
You will find in pictures what I imagine .....
Thank you
![1](https://user-images.githubusercontent.com/33481120/128153577-a3c8bea5-8b02-4272-8d7e-e42c80730da6.png)
![2](https://user-images.githubusercontent.com/33481120/128153648-8ef6286d-181f-4245-8547-eef62a0ebc1e.png)
![3](https://user-images.githubusercontent.com/33481120/128153814-4d579240-902e-4fef-895c-8df06f65b1f5.png)

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
That is an interesting idea. 
Most easy implementation would be adding saved settings under "Transaction Report" navigation item.

![image](https://user-images.githubusercontent.com/6836805/128157419-b26f4b90-5758-4ecc-a0c3-d4cc046586a5.png)

**Comment by vomikan** [comment]
Related issues
https://github.com/moneymanagerex/moneymanagerex/issues/3353
https://github.com/moneymanagerex/moneymanagerex/issues/3324
https://github.com/moneymanagerex/moneymanagerex/issues/2232

**Comment by vomikan** [comment]
Thanks to this change, it is possible to present each saved report in the additional menu of the navigation tree.
https://github.com/moneymanagerex/moneymanagerex/issues/4250

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/168476477-800f3836-3f95-459e-9f13-388bbb21b32b.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/168591755-7eec3c33-89ea-4024-86b6-abd3a276212a.png)

**Comment by vomikan** [comment]
- [ ]
