### ISSUE TITLE
Accounts selection in Advanced filter for single account list view is confusing

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3756]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

We recently updated the transaction filter to support the selection of multiple accounts. Basically the filter is defined to make visible any transaction that includes any selected account(s) (which includes the TO account for transfers).

However when viewing a single account in the accounts view the ability to change the accounts viewed does not make sense and this option should be disabled.

Whilst I understand what the current behavior is;  as the transaction list is already filtered by the account in question the behavior of the filter account can be confusing. 

Views?

<img width="845" alt="image" src="https://user-images.githubusercontent.com/487345/128311851-bce5ae0e-a30b-4c64-bb6e-15871c5baa8e.png">

**Comment by 2BeeOrNot** [comment]
I agree. It doesn't make sense and may cause confusing results from my experience. For example viewing Checking and in the advanced filter selecting Savings.

To use the account view and select accounts I start in All Transactions view and then using the advanced filter to select accounts. This seems to give me reliable results.
