### ISSUE TITLE
macOS: New Transaction Hot Key should be CMD+N

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3763]
**Pre-requisities:**

macOS 10.15 and up
MMEX 1.5 and up

**Steps:**

1) Run MMEX
2.1) Choose any account
2.2) OR Choose All Transactions
3) Press CMD+N

**Current Result:**

1) Dialog window "Save" "Choose database file to create" opens

**Expected Result:**

1) "New Transaction" dialog opens
2) "File" -> "New Database" does not have "Cmd+N" shortcut associated with it

**Comment by whalley** [comment]
My experience is....

1. From the Home Page pressing CMD+N brings up the new database dialog.
2. In an account view pressing CMD+N brings up the new transaction dialog. The reason for this is that we override the command accelerator to make new transaction selection the default assignment.
3. In the ALL account view pressing CMD+N causes and application crash--- **I will look to fix.**
3. In a report view pressing CMD+N brings up the new database dialog.

Interesting to note that you did not experience the crash when in ALL account view.

**To avoid confusion we could probably remove the global CMD+N/CMD+O accelerators as creating new DB and opening DB are not frequent actions warranting a key accelerator.**

**Comment by tygryk** [comment]
Hi, thank you for the prompt reply. 

App Crash was next on my list, I just could not identify the cause. It happened just once and never reproduced after app restarted.

Yes, I agree DB creation is a rare task.

I wish I could attach a video. I definitely cannot invoke new transaction with hot keys. However, we probably might ignore it for now if you are planning on accelerators removal.

Thank you, again.

**Comment by tygryk** [comment]
btw, just in case. 

There's a line in "mmex.po" translations' file that should probably be adjusted as well

"&New Database	Ctrl-N"

**Comment by whalley** [comment]
Crash fixed. I left the Ctrl+O in for opening database as this had no clash with any accelerator.

**Comment by tygryk** [comment]
Sorry for bothering and taking your time. CMD+N is disabled at all in mmex-1.5.6-Beta.1-Darwin-2021-08-16. Will a "New transaction" be assigned to this key combination?

**Comment by whalley** [comment]
CMD+N should be available in the account views. Are you asking to enable this on the home screen?

**Comment by tygryk** [comment]
@whalley thank you for explanation. However it does not work for me at all (( 

Am I doing this right:

Choose any account from the list on the left -> click CMD+N -> New Transaction should open?

**Comment by whalley** [comment]
Yes, works fine for me on MacOS 10.15.7 (Intel) and MacOS 11.5.2 (M1).

Can you try clicking on a transaction in the account view and trying CMD+N , does in work then?
Can you try clicking on a transaction in the account view and trying CMD+U , does the duplicate transaction dialog appear?

**Comment by tygryk** [comment]
I'm on macOS 12.0 beta (21A5304g) Intel

none CMD+N nor CMD+U. 

CMD+U works as just "U" and making the highlighted transaction as "Unreconciled"

Can it be related to keyboard layout? Input mehtid? Hotkeys? Is there a way I can trace codes when keys are pressed?

**Comment by whalley** [comment]
Hmmm, that may indeed be the source of the issue. Sounds like accelerators may be broken in the Beta build.

When I get time I'll install the beta on a test machine and give it a try. I've also raised a query with the wxWidgets team to see if there are any known issues.

**Comment by whalley** [comment]
@tygryk Can you please check what shortcuts you have setup just in case these are overriding the application values.

![image](https://user-images.githubusercontent.com/487345/129813259-41680c4b-a166-497b-b07d-ec7a28dccae5.png)

**Comment by tygryk** [comment]
@whalley thank you for suggested check up. I do not have any specific shortcuts for any apps. The only change I made is for input sources and spotlight. Modifier keys are intact.

<img width="659" alt="Screen Shot 2021-08-18 at 09 35 21" src="https://user-images.githubusercontent.com/9718911/129849833-308a0341-ed2e-4c6d-9e91-b5d1200948de.png">
<img width="661" alt="Screen Shot 2021-08-18 at 09 35 35" src="https://user-images.githubusercontent.com/9718911/129849860-368168fc-9de8-4712-9627-74223658dc04.png">
<img width="658" alt="Screen Shot 2021-08-18 at 09 40 28" src="https://user-images.githubusercontent.com/9718911/129850123-698be4b5-fc57-42a7-96af-b636e462e2f3.png">
<img width="410" alt="Screen Shot 2021-08-18 at 09 35 50" src="https://user-images.githubusercontent.com/9718911/129849877-be232057-4c6e-4310-8052-7cbab5873e9b.png">

**Comment by tygryk** [comment]
@whalley great news

the CMD+N shortcut is now working after update to macOS Monterey Beta 6. Seems they've fixed issue with accelerators what was there in beta 5

Which is more, keyboard input source (language/locale) does not matter. works on all locales, any selected account or in all accounts view, too.

**Comment by whalley** [comment]
Excellent news.

**Comment by tygryk** [comment]
(( @whalley i know this will sound stupid

After MMEX crash the shortcut is not working. At all. MMEX restart won't help

No action required from your side. just wanted to keep you updated. Unless you know how I can catch the accelerator, shmasellerator, whatever the name ))

**Comment by vomikan** [comment]
> (( @whalley i know this will sound stupid
> 
> After MMEX crash the shortcut is not working. At all. MMEX restart won't help
> 
> No action required from your side. just wanted to keep you updated. Unless you know how I can catch the accelerator, shmasellerator, whatever the name ))

Try to delete mmexini.db3 file

**Comment by tygryk** [comment]
@vomikan thank you. Where do I find it on mac? spotlight does know about the file, neither i can see it in MMEX folder

**Comment by whalley** [comment]
It's under a hidden folder. You will find it in: /Users/YOURUSERNAME/Library/Application Support/MoneyManagerEx

See: https://www.ionos.co.uk/digitalguide/server/configuration/showing-hidden-files-on-a-mac/

**Comment by tygryk** [comment]
@whalley thank you ))

yes, it helped

)) and also reset all my settings, font size, etc. 

anyway, CMD+N is working now, again

**Comment by tygryk** [comment]
@whalley it definitely stops working after I make changes to Settings -> Application language. I don't even have top quit/restart app.

The shortcut only works if MMEX's language is English (either "system defaul" or "English U.S." from the list)

Hope it helps

**Comment by tygryk** [comment]
confirmed

- I restored back the previously deleted mmexini.db3
- hen changed MMEX language to English 
 
result: CMD+N is working again.

**Comment by tygryk** [comment]
@whalley in 1.5.7 CMD+N is not working for a locale other than English (see above). Is it yet an accelerator issue or might be fixed somehow even in beta?

**Comment by whalley** [comment]
Yes, I can reproduce this.

**Comment by whalley** [comment]
Should work now... not sure why is was even working for English :-)

**Comment by maksimdzmitryew** [comment]
@whalley I'm absolutely happy to confirm it's working in 1.5.8

Thank you so much
