### ISSUE TITLE
QIF import ignores account type for new accounts

### ISSUE THREAD

**Issue by jeffjl74** [moneymanagerex/moneymanagerex#377]
Version 1.2.0-Beta
When importing a QIF file, the !Account record contains a T line that
specifies the account type. MMEX does not use this information
and always creates Checking accounts for new accounts.

**Comment by guanlisheng** [comment]
Nikolay, would you mind to take a look here?

**Comment by vomikan** [comment]
There are only 3 types of account available in mmex: Checking, CC and Term.
But QIF supports:
Cash
Bank
CCard	
Invst	
Oth A	
Oth L	
Invoice
Because can not be compared directly to all types of accounts, the program simply ignores it.
I can't provide better solution in this case. Any way an account type may be changed manually.
I suggest to close this case. QIF import improvements should be provided first.

**Comment by jeffjl74** [comment]
Fix #378 allows mmex to create Stock accounts for the QIF Invst account type. (And mmex cannot manually change a Checking account into a Stock account.)  The QIF "Oth A" should probably be imported as an mmex Asset account.  I'm not sure whether the "Oth L" liability account would also map to the mmex Asset account.

**Comment by vomikan** [comment]
OK could you please assighn yourself?

**Comment by stef145g** [comment]
fyi, https://github.com/moneymanagerex/moneymanagerex/issues/336
I am reorganising the way stocks and Assets work, by extending the existing functionality. This may impact on what you guys are trying to do.

Further developments has led me to create 2 new account types: Asset Accounts and Share Accounts. These account types don't appear on the home page as these account types are parking accounts to assist in the transfer of money from general/term/credit accounts to stocks or assets. The underlying database structure is explained in issue https://github.com/moneymanagerex/moneymanagerex/issues/336

You can see the progress in the branch 'stef145g_dev'. At this point transfers for Stocks and Shares works well, but further work is still required before I submit this new feature for acceptance into the master branch.

**Comment by jeffjl74** [comment]
I am closing this because any further work would need the extended asset and share accounts that are still in development. Once those accounts are available, the QIF import into them can be revisited.
