### ISSUE TITLE
Adoption of wxBitmapBundle to support HighDPI display

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#3779]
Looks like some code should be added for DPI aware, otherwise MMEX is blurred out on Windows 10  with HighDPI (27" 4K screen at 150%):
https://docs.wxwidgets.org/trunk/overview_high_dpi.html
https://forums.wxwidgets.org/viewtopic.php?f=23&t=46699#p198279

> HiDPI now working after adding: '-DwxUSE_DPI_AWARE_MANIFEST=2' when compiling my project's Windows .rc file with Mingw's windres and copying in 'include/wx/msw/amd64_dpi_aware_pmv2.manifest' from wxWidgets distribution to 'include/wx/msw' at wx install prefix location.

Actual:
![image](https://user-images.githubusercontent.com/7106290/129534034-d8676320-c4be-4eb6-96d3-d188b2690abd.png)

Change this settings (which should be done automatically by the above suggested changes):
![image](https://user-images.githubusercontent.com/7106290/129534174-4d93ab21-ba9b-470c-b9b6-2b50d0dea7e8.png)

Correct result:
![image](https://user-images.githubusercontent.com/7106290/129534128-9898fcc8-885a-445c-9f3d-abc1c3a6a043.png)

**Comment by whalley** [comment]
I note that one of the [roadmap items for wxWidgets 3.2](https://trac.wxwidgets.org/wiki/Roadmap) is better support for high DPI displays.

**Comment by gerstrong** [comment]
I have the same problem with Manjaro Gnome. Using wxwdigets 3.2 here.

![Bildschirmfoto vom 2022-10-05 07-45-22](https://user-images.githubusercontent.com/314853/193989823-254f4567-ce4f-4024-9a17-6105008ea781.png)
![Bildschirmfoto vom 2022-10-05 07-45-07](https://user-images.githubusercontent.com/314853/193989834-9a932aa7-8434-4da3-b304-ca529e3ac931.png)

**Comment by gerstrong** [comment]
Just created PR that at least fixes the toolbar looks: https://github.com/moneymanagerex/moneymanagerex/pull/5163

I will check how to get this done with the other icons.

**Comment by whalley** [comment]
@gerstrong Having made all the changes to use wxBitmapBundle rather than wxBitmap it all seems to work fine on MacOS. I'm going to push a PR with the changes (I have commented out much of the redundant code in case we need to revert anything). It would be interesting to see how this works out on Windows and Linux (I know you noted some issues with GTK) - maybe that we need to raise some issues with the wxWidgets team if that is the case and in the interim put some Linux workarounds in place.

**Comment by gerstrong** [comment]
Thanks, I will have another test on my system. Looking at your commits, it seems to be the same thing I tried before and it failed on my system, which is Linux and wxWidgets compiled against GTK. It might be a GTK only issue. If that is the case we need to check wxWidgets and fix it there. At least most of the wxWidgets classes seem to be support ```wxBitmapBundle``` which is a good start.

**Comment by whalley** [comment]
On MacOS I get an error on application close... Looks like a wxWidgets issue when destroying the wxBitMapBundle's
https://github.com/wxWidgets/wxWidgets/issues/22862

**Comment by whalley** [comment]
Linux test builds can be found here: https://app.circleci.com/pipelines/github/whalley/moneymanagerex

Have tested on Win10 and Linux Ubuntu 20.04 using VMs - Looks OK from quick look but not sure my VMs are using HighDPI.

**Comment by whalley** [comment]
Looks like I need to refactor this to remove the global wxBitMapbundles. See https://github.com/wxWidgets/wxWidgets/issues/22862

```
It's really surprising that you didn't have any problems with global bitmaps with wxGTK, 
destroying them after closing connection to the X server should have resulted in
problems as well.

Creating them after initializing the app is required but not sufficient, they must also be
destroyed before it is shut down.

To be totally fair, we might be able to make using globals work with wxMSW and wxOSX
where the GUI is always available, but this is really impossible with wxGTK where the GUI
is initialized/shut down as part of wxApp initialization/destruction, and as we want to
encourage people writing portable code, it doesn't seem wise to spend efforts on making
this work under non-Unix platforms.

Although having an assert rather than a crash would be preferable, of course...
```

**Comment by gerstrong** [comment]
Hi Mark,

thanks for checking this out.

I can check whether these global ```wxBitmapBundles``` can be moved to a proper class (I'd prefer that anyways). What do you think?

**Comment by whalley** [comment]
> Hi Mark,
> 
> thanks for checking this out.
> 
> I can check whether these global `wxBitmapBundles` can be moved to a proper class (I'd prefer that anyways). What do you think?

It's fine where they are, I've just added code to release the bitmaps in the app closure. This should (and seems to) work OK. It's just that the destructors in WxWidgets assume the UI is still there, so if we remove before we close then that is fine.

**Comment by whalley** [comment]
@gerstrong Have you had chance to check for issues on Linux with adopting wxBitmapBundles for everything?

**Comment by gerstrong** [comment]
@whalley I have changed more ```wxBitmap``` load sections to use ```wxBitmapBundle``` but most of the icons result in blurry scaling. Exceptions are mostly ```wxBitmapButtons``` (these really scale properly for different DPIs). At least nothing gets worse by doing the change but I have the impression that more work needs to be done in the wxWidgets lib itseld, maybe just the GTK variant (not yet tested with other variants). Just give me a couple of days, I am testing my latest changes in another branch and when ready I will open another PR.

**Comment by whalley** [comment]
> @whalley I have changed more `wxBitmap` load sections to use `wxBitmapBundle` but most of the icons result in blurry scaling. 

Interesting, thought I had changed all occurrences. Which areas were still outstanding?

> I have the impression that more work needs to be done in the wxWidgets lib itself, maybe just the GTK variant (not yet tested with other variants). 

We should get these raised with the wxWidgets development team, I have found them quite responsive.

> Just give me a couple of days, I am testing my latest changes in another branch and when ready I will open another PR.

Sure. Thanks.

**Comment by whalley** [comment]
@gerstrong Is the only outstanding issue on this the resolution of https://github.com/wxWidgets/wxWidgets/pull/22879 which seems to be destined for wx3.3.0 ? If so then I suggest we close this one and raise another issue in the on-hold state and await wx3.3.0.

**Comment by gabriele-v** [comment]
@whalley I think this issue diverged from the original one: at least on Windows, the original issue which I highlighted is still there and is not related with icons only. Everything in the interface is blurred: buttons, text, etc... Should we re-open this or create another one? Not sure why title has been changed because they are two different things

**Comment by gerstrong** [comment]
Hi @gabriele-v I have been reporting at wxWidgets and we were able to solve these issues. If you try to build it against a wxWidgets development version (3.3+), the blurryness should not be a problem anymore. Do want to test it? At least on Manjaro with hiDPI I don't have these issues anymore...

**Comment by whalley** [comment]
@gabriele-v  Please open another issue. And apologies if we hijacked your original issue, I had thought the issues were the same.

**Comment by gabriele-v** [comment]
> Hi @gabriele-v I have been reporting at wxWidgets and we were able to solve these issues. If you try to build it against a wxWidgets development version (3.3+), the blurryness should not be a problem anymore. Do want to test it? At least on Manjaro with hiDPI I don't have these issues anymore...
If it's someway possible to get a Windows x64 version of MMEX built on 3.3+ I'm more than happy to test it, unfortunately I don't have my dev environment up anymore to build it by myself.
