### ISSUE TITLE
Duplicate transaction: amount resets if focus is moved out with mouse, not keyboard

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3780]
MMEX version:
 - [x] 1.5.5
 - [ ] 1.6.x

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Amount resets to initial value for a duplicate transaction after cursor focus is moved out with mouse

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Choose a transaction
2. Right click
3. Duplicate -> "Duplicate Transaction" dialog opens. Note down what is the current amount (# 1) from original transaction
4. Only Change amount (# 2) with digits BUT Don't press any key so that current field still has focus and cursor is not moved out
6. Move cursor pointer with mouse/touchpad over but don't press any mouse key yet
7. Click Categories picker
8. "Organize Categories" dialog opens
9.1. Either change by selecting a new category and confirm with OK
9.2. OR Do not change and close the dialog window with "Cancel" or "red dot" in the top left corner

Expected result:

The new amount # 2 remains intact.
Original amount # 1 is not restored.

Actual result:

The new amount # 2 is reset and reverted back to original amount # 1.

# Additional information

This does not happen if cursor focus is changed with keyboard.

Thank you for reviewing this report.

Please let me know if description is clear enough to reproduce.

**Comment by whalley** [comment]
Confirmed.

**Comment by whalley** [comment]
Seems that the focus change behaviour on WIn and Mac is slightly different. This change should make the behavior the same, fixing the issue on Mac with adverse effect on Win. 

@vomikan Can you please double check this works OK on Windows.

**Comment by whalley** [comment]
@tygryk The lastes beta is here with the fix. https://mmex.ipx.co.uk/builds/beta/mmex-1.5.6-Beta.1-Darwin-2021-08-16.dmg

**Comment by tygryk** [comment]
@whalley thank you for the link. I've checked the beta and it looks good to me. I can't reproduce the issue anymore. Kudos!

**Comment by vomikan** [comment]
> @vomikan Can you please double check this works OK on Windows.

Maybe later. Or we are waiting for feedback from our advanced users. Or we believe in a better outcome (is that possible?).
