### ISSUE TITLE
Transaction Type on CSV import is ignored?

### ISSUE THREAD

**Issue by regs01** [moneymanagerex/moneymanagerex#3783]
Yoomoney (former Yandex.Money has a separate type column which is - for withdrawal and + for deposit).

```
+/-;дата;сумма;;статус;название
-;15.08.2021 19:52:02;377,15;RUB;;VKUSVILL
+;15.08.2021 14:52:55;642,28;RUB;;Дополнительное зачисление по операции
-;14.08.2021 12:15:01;2377,63;RUB;;AUCHAN ONLINE
```
Now, if I chose Type for first column and Amount for third there is an option - positive amount if type has Deposit. So with help of any Notepad-type application I've quickly changed all +; into Deposit;

```
+/-;дата;сумма;;статус;название
-;15.08.2021 19:52:02;377,15;RUB;;VKUSVILL
Deposit;15.08.2021 14:52:55;642,28;RUB;;Дополнительное зачисление по операции
-;14.08.2021 12:15:01;2377,63;RUB;;AUCHAN ONLINE
```
Yet it still importing those lines as withdrawal. Is it broken or am i missing something? It's 1.5.5.

**Comment by whalley** [comment]
Oddly looking at the code it seems to use a match against "debit" for a 'type' to indicate a deposit. So try the following

```+/-;дата;сумма;;статус;название
-;15.08.2021 19:52:02;377,15;RUB;;VKUSVILL
debit;15.08.2021 14:52:55;642,28;RUB;;Дополнительное зачисление по операции
-;14.08.2021 12:15:01;2377,63;RUB;;AUCHAN ONLINE
```

@vomikan You have done some work in this side of the program before. Any reason for this?
https://github.com/moneymanagerex/moneymanagerex/blob/a36e9e510157068defbe07b5a6e6fbeb044ff154/src/import_export/univcsvdialog.cpp#L1760

**Comment by vomikan** [comment]
It is not possible to remember. There are a lot of different formats. One user can report an error. After fixing it, you can get an error for another user.

**Comment by regs01** [comment]
It did work.

But may be also do 
`if (token == "debit") || (token == "+") || (token == "Deposit") {`

**Comment by regs01** [comment]
> 
> 
> It is not possible to remember. There are a lot of different formats. One user can report an error. After fixing it, you can get an error for another user.

The problem isn't really in format but in fact that Import dialog says Deposit, but actual is debit. It just should be common. Still, multiple option would be even better, including the one shown in Import dialog.
<img width="329" alt="mmex_2021-08-17_11-40-32" src="https://user-images.githubusercontent.com/10468217/129693907-6e4f868f-ed7b-4af8-b78f-d6f715a843d2.png">

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/132846483-29da3191-109e-47a0-9e5e-87acf8fe12d5.png)
