### ISSUE TITLE
Newly assigned Account is reset if transaction type changed on Edit/Duplicate

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3785]
MMEX version:
 - [x] 1.5.6beta
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [x] Linux 

# Description of the bug

Account is reset if transaction type reverted to original issue.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Edit/Duplicate existing transaction. Transaction type is "Withdrawal
2. Change original Account "From" (# 1) to any other account (# 2)
3. Change Transaction type to "Deposit"

Expected result:

Account "From" remains the newly selected # 2

Actual result:

Account "From" reverts to original value # 1

# Additional information

None.

**Comment by whalley** [comment]
The same is currently true for the Payee/From field.

**Comment by tygryk** [comment]
Fantastic job. Thank you for being so fast and very professional attitude
