### ISSUE TITLE
Summary of Stocks Display - alignment

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#3786]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [x] Linux 

# Description of the bug

Just a minor niggle on the format of the display using Win 10 on 1.5.5 and latest master.
Right-hand side of display - Current Value is always perfectly aligned but as you move further down the display things drift to the left see the following cropped screenshot
![tempsnip](https://user-images.githubusercontent.com/24897056/129711128-ee0ea653-3ac9-438d-9417-6d91192a6b6c.png)

I am guessing this has something to do with the amount of text in the Name column but surely as all the other columns contain some form of numeric field then they can be of a fixed width ?

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by grumpy235** [comment]
@whalley Looks much better many thanks. I forgot to mention the alignment of the grand total line, "Current Value" is at the far right in line with the rows above  but "Gain/Loss" has wandered into the middle

**Comment by whalley** [comment]
Yes I did notice that. As the totals are in a separate summary table at the bottom I did see it as a major issue.

**Comment by grumpy235** [comment]
OK thanks

**Comment by whalley** [comment]
@grumpy235 Report tidied Mr Grumpy.
