### ISSUE TITLE
Can't build 1.5.7

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#3796]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux 

```
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.0.5 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.3
• lunasvg v2.0.1
• libcurl/7.78.0 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.44.0
• gettext 0.21
• apexcharts.js
Genutztes Build:
• CMake 3.21.1
• GNU Make 4.3
• GCC 11.1.0 • EndeavourOS rolling 'rolling'
```

# Description of the bug

Compilation error.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Build it

Expected result:

MMEX

Actual result:

Abort

# Additional information
```
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp: In Funktion »bool getCoincapAssetHistory(wxString, wxDateTime, std::map<wxDateTime, double>&, wxString&)«:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp:971:42: Fehler: nutzlose Umwandlung in Typ »time_t« {aka »long int«} [-Werror=useless-cast]
  971 |             wxDateTime date = wxDateTime(static_cast<time_t>(entry["time"].GetInt64() / 1000)).GetDateOnly();
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp: In Funktion »const wxString getProgramDescription(int)«:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp:1283:26: Fehler: »class wxDisplay« hat kein Element namens »GetPPI«
 1283 |                 display->GetPPI().GetWidth(),
      |                          ^~~~~~
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp:1284:26: Fehler: »class wxDisplay« hat kein Element namens »GetPPI«
 1284 |                 display->GetPPI().GetHeight()
      |                          ^~~~~~
cc1plus: Einige Warnungen werden als Fehler behandelt
make[2]: *** [src/CMakeFiles/mmex.dir/build.make:944: src/CMakeFiles/mmex.dir/util.cpp.o] Fehler 1
```

**Comment by whalley** [comment]
WxDisplay GetPPI requires at least wxWidgets 3.1.2. This release should be built with 3.1.5.

**Comment by whalley** [comment]
See https://github.com/moneymanagerex/moneymanagerex/issues/3695

**Comment by MartinX3** [comment]
Ah, thank you very much
It's sad, since it won't come into the repositories of a linux distribution, since 3.1.x is a development branch and 3.0.x is the current stable branch.

**Comment by whalley** [comment]
Yes, we could really do with somebody with a keen interest in maintaining the Linux binaries so we can keep the LInux builds up-to-date with MMEX development.

**Comment by MartinX3** [comment]
Maybe I can get them to work again at least on arch linux.
I found unofficial 3.1.5 builds in the AUR repository.

**Comment by MartinX3** [comment]
@whalley now it can't compile, because the useless cast is handled as error.

```
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp: In Funktion »bool getCoincapAssetHistory(wxString, wxDateTime, std::map<wxDateTime, double>&, wxString&)«:
/tmp/makepkg/moneymanagerex-git/src/moneymanagerex/src/util.cpp:971:42: Fehler: nutzlose Umwandlung in Typ »time_t« {aka »long int«} [-Werror=useless-cast]
  971 |             wxDateTime date = wxDateTime(static_cast<time_t>(entry["time"].GetInt64() / 1000)).GetDateOnly();
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: Einige Warnungen werden als Fehler behandelt
make[2]: *** [src/CMakeFiles/mmex.dir/build.make:944: src/CMakeFiles/mmex.dir/util.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
```

**Comment by avma** [comment]
I'm Getting the same errors...
`[ 68%] Building CXX object src/CMakeFiles/mmex.dir/util.cpp.o
/home/avi/git/moneymanagerex/src/util.cpp: In function ‘bool getCoincapAssetHistory(wxString, wxDateTime, std::map<wxDateTime, double>&, wxString&)’:
/home/avi/git/moneymanagerex/src/util.cpp:971:93: error: useless cast to type ‘time_t’ {aka ‘long int’} [-Werror=useless-cast]
  971 |             wxDateTime date = wxDateTime(static_cast<time_t>(entry["time"].GetInt64() / 1000)).GetDateOnly();
      |                                                                                             ^
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/mmex.dir/build.make:944: src/CMakeFiles/mmex.dir/util.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:414: src/CMakeFiles/mmex.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
`

**Comment by vomikan** [comment]
Remove
wxDateTime(.              )
Funktion in util.cpp file line 971

**Comment by avma** [comment]
Just to make sure, what exactly should i remove? This is the path to the file: /home/avi/git/moneymanagerex/src/util.cpp

`969    // if the object has both a symbol and id check if the symbol matches the target symbol
970           if (entry.HasMember("priceUsd") && entry["priceUsd"].IsString() && entry.HasMember("time") && entry["time"].IsInt64()) {
971               wxDateTime date = wxDateTime(static_cast<time_t>(entry["time"].GetInt64() / 1000)).GetDateOnly();
972               double price_usd = -1.0;
972               auto priceUSD = wxString::FromUTF8(entry["priceUsd"].GetString());`

**Comment by whalley** [comment]
On MacOS with clang I now get:

```
/Users/mark/gitrepos/moneymanagerex/src/util.cpp:971:31: error: ambiguous conversion for static_cast from 'long long' to 'wxDateTime'
            wxDateTime date = static_cast<wxDateTime>(entry["time"].GetInt64() / 1000).GetDateOnly();
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MartinX3** [comment]
Yes, we all get it with modern dependencies :D

**Comment by MartinX3** [comment]
On Arch Linux it's fixed now with https://github.com/vomikan/moneymanagerex/commit/a50f3c8b438ce82a83b8be444ab5c5ed20e4d1df
(Clang 12.0.1)

**Comment by MartinX3** [comment]
@whalley where you got 12.0.5 from?
Newest is 12.0.1
https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1

**Comment by whalley** [comment]
Xcode 12.5 

https://trac.macports.org/wiki/XcodeVersionInfo#macOS12

**Comment by MartinX3** [comment]
Maybe a problem with `Apple clang`
Is there a way for you to test it with 12.0.1?
The rest of the world doesn't seem to be able to get 12.0.5 now.

**Comment by vomikan** [comment]
@whalley  try to remove
static_cast<wxDateTime>(.    )

**Comment by whalley** [comment]
@vomikan That wont work  as the .GetDateOnly() will not work on a base type.

This works and may work on Linux as it avoids the 'static_cast' which seemed to cause the original issue:
```
time_t dt = entry["time"].GetInt64() / 1000;
wxDateTime date = wxDateTime(dt).GetDateOnly();
```

**Comment by avma** [comment]
If you mean dependencies, no, i have them all...
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.7-Beta.1
-- Commit         : 9125afee (2021-08-27)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.11.0-27-generic
-- Linuxmint 20.2 'uma'
-- CMake 3.21.0-rc3
-- GNU Make 4.2.1
-- ccache 3.7.7
-- GNU 9.3.0
-- wxWidgets 3.1.5
-- Lua 5.3.3
-- curl 7.68.0
-- gettext 0.19.8.1
-- ------------------ 8< -----------------
-- Configuring incomplete, errors occurred!
See also "/home/avi/git/moneymanagerex/build-1.5.6/CMakeFiles/CMakeOutput.log".
```

**Comment by MartinX3** [comment]
@avma submodules like in the submodules in the readme.

@whalley @vomikan the switch to wxWidgets 3.1.x seems to have a siteeffect.
A friend told me that the FTP manger FileZilla doesn't work with it.

On (arch) linux both 3.0.x stable and 3.1.x dev can't be installed at the same time.

**Comment by whalley** [comment]
> @whalley @vomikan the switch to wxWidgets 3.1.x seems to have a siteeffect.
> A friend told me that the FTP manger FileZilla doesn't work with it.
> 
> On (arch) linux both 3.0.x stable and 3.1.x dev can't be installed at the same time.

This is presumably just a development constraint then as we build static libraries for the application.

**Comment by MartinX3** [comment]
> 
> > @whalley @vomikan the switch to wxWidgets 3.1.x seems to have a siteeffect.
> > A friend told me that the FTP manger FileZilla doesn't work with it.
> > 
> > On (arch) linux both 3.0.x stable and 3.1.x dev can't be installed at the same time.
> 
> This is presumably just a development constraint then as we build static libraries for the application.

In linux it's a global installed package as build dependency.
As example in arch Linux the AUR package needs it as a make dependency.

Another solution would be to add rpm/deb/appimage assets to the mmex releases, so an AUR package could fetch them, extract it's contents and install it on the system.

**Comment by whalley** [comment]
> It's normal for windows users to have chaos by having manually downloaded folders of libs and apps cluttered on the hdd/ssd.
> But on Linux we use package managers to install software and update it in a standarized folder structure.

Not sure it is chaos when an application binary comes configured with all the non-OS specific libraries it needs, no dependency issues then. Yes it uses more disk space. But hey, it is what it is.

**Comment by avma** [comment]
@whalley, yes I have followed the readme file to the note, and yes I have all the modules. ( you see, i have only built mmex from source on Linux the last 5 years like a hundred times already)

**Comment by whalley** [comment]
@avma  OK, I was not questioning your ability to build MMEX from source 😀, if you have the fmt submodule present in your repo then I’m not sure what the issue is. You mentioned you had other errors also after the fmt error, what are these?

**Comment by MartinX3** [comment]
Now I can't build 1.5.7 :(

```
/usr/bin/ld: CMakeFiles/mmex.dir/aboutdialog.cpp.o: in function `do_read_file(std::vector<wxString, std::allocator<wxString> >&, wxString const&)':
aboutdialog.cpp:(.text+0x3933): undefined reference to `mmHTMLBuilder::init(bool)'
/usr/bin/ld: aboutdialog.cpp:(.text+0x422f): undefined reference to `mmHTMLBuilder::init(bool)'
/usr/bin/ld: CMakeFiles/mmex.dir/aboutdialog.cpp.o: in function `mmAboutDialog::initControls()':
aboutdialog.cpp:(.text+0x61e8): undefined reference to `mmHTMLBuilder::init(bool)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
```

**Comment by whalley** [comment]
The init method was changed recently, see:

https://github.com/moneymanagerex/moneymanagerex/commit/6814876f054f7a351d00b369d64248b32aed897a#diff-3a26868f92b2572fc997e16ef3ea7ccd6d81a364183389741b72e2dc4e9e742e

![image](https://user-images.githubusercontent.com/487345/133924927-e4dbf44a-a381-4c15-8133-eef3d8b2c567.png)

Not sure what the Linux build issue is though.

**Comment by MartinX3** [comment]
Maybe because it don't know if the true is a bool or this wxString&
at
https://github.com/moneymanagerex/moneymanagerex/blob/b0e2fc37448c21161b05b1078d27c956e415bdf1/src/aboutdialog.cpp#L91

**Comment by vomikan** [comment]
Try to change it to
``` hb.init(true, "");```

**Comment by MartinX3** [comment]
> hb.init(true, "");

I replaced every occurrence with your suggestion and mmex finally builds again. <3

**Comment by MartinX3** [comment]
But checking out the tag `v1.5.7` is giving me
`package: /tmp/makepkg/moneymanagerex-git/src/moneymanagerex/mmex-1.5.8-Beta.1-Linux.tar.gz generated.`

**Comment by MartinX3** [comment]
Should get fixed by https://github.com/moneymanagerex/moneymanagerex/pull/4030
