### ISSUE TITLE
Error in high figures when entering transaction amounts, or in balances / reports.

### ISSUE THREAD

**Issue by JuanJabo1GH** [moneymanagerex/moneymanagerex#3800]
> Hello, I have been a Money user since its inception, I am also an analyst and systems programmer, so I have always been observing the changes that have been made to improve this application.
I have detected some errors that fortunately I have not had the need to report because they have been corrected version after version and I congratulate you for it.
The point that leads me to write to you is that from version 1.5.2 onwards to the current 1.5.6 I have noticed an error that they have not corrected (I leave you a sample image).
In Venezuela, due to high inflation, very high accounting figures are handled that exceed 10 characters or digits (9,999,999,999, oo) or billions. It seems that the system from the commented version does not support these amounts and begins to show figures that do not correspond. Please analyze the situation and tell us what is happening or how to solve it. Thanks.

![imagen](https://user-images.githubusercontent.com/89281363/130304251-98190b1f-336f-43dd-a8f3-d2a6e414d501.png)

I have been doing tests with figures that exceed one billion (more than 10 digits) and regardless of the number or quantity that is placed, it always places the figure shown in the error.

![imagen](https://user-images.githubusercontent.com/89281363/130303957-72a17f17-bd16-43ec-be6a-546a57de69f1.png)

<hr>Version: 1.5.6 <br>
 • Build: Ago 20 2021 09:39:35<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042)<br>
 •  Spanish (Modern) (windows-1252)<br>
 • 1280x1024 32bit 96x96ppi

**Comment by whalley** [comment]
That looks like overflow with an int type (i.e. we have a double larger than the maximum int value), and seems, initially, to be an issue caused when converting the double used to store money to a presentation format. E.g. in Model_Currency.cpp
https://github.com/moneymanagerex/moneymanagerex/blob/ec13e765614d4ac9b0bbff031baae71f45274e22/src/model/Model_Currency.cpp#L231

The timing of when the issue was introduced aligns with the locale changes in this area and the user of the fmt library.

**Comment by whalley** [comment]
Have pushed a change to help fix this. 
![image](https://user-images.githubusercontent.com/487345/130315717-708f4395-9115-4349-ae68-f6279b1eeea0.png)

![image](https://user-images.githubusercontent.com/487345/130315766-0b1ecaec-648e-4cdb-99db-d2632558a757.png)

I did notice also that due to the long numbers the balance presented at the top of the transaction views needs adjusting to accommodate - not fixed that yet.

**Comment by whalley** [comment]
@JuanJabo1GH Please try this build and let me know if it fixes your issues - https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/40468163/job/v8pxny85wh010pey/artifacts

**Comment by JuanJabo1GH** [comment]
> @ JuanJabo1GH Pruebe esta compilación y avíseme si soluciona sus problemas: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/40468163/job/v8pxny85wh010pey/artifacts

Thanks for the proposed solution. Will it be possible to hang the Beta version for 32 bit? since the one you hung up is 64 bit.

**Comment by whalley** [comment]
Try this https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/nq2exg5cnmtrcssn/artifacts

**Comment by JuanJabo1GH** [comment]
Thanks for your contributions, the Beta version that you sent me did not solve the problem either, there I am sending you the images where it shows for version 1.5.1 that it works and also of versions 1.5.2 in advance until the last Beta, which you recommended and it doesn't work or fix the problem.

![imagen](https://user-images.githubusercontent.com/89281363/133004053-d661a2d7-cc7d-4662-b166-778063085b24.png)

**Comment by whalley** [comment]
Hmmm.. Seems to be a Windows issue. Works fine on MacOS.

**Comment by vomikan** [comment]
The real amount of the transaction #22 is 12345678901235.0

![image](https://user-images.githubusercontent.com/6836805/133058382-381f00fe-b8c5-4c6c-a317-86a1be6666f7.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/133060562-c98665a0-bec3-4eab-acdb-9aacb7ab5f5d.png)
![image](https://user-images.githubusercontent.com/6836805/133060672-b09ca3a6-85a9-4c70-8975-0ec445adc94c.png)


```
        s = fmt::format((use_locale == "Y" ? std::locale(locale.c_str()) : std::locale("en_US"))
            , "{:L}", static_cast<long>(fabs(v) + 5 / (pow(10, precision + 1))));`
``

**Comment by whalley** [comment]
Oddly, no. I can change it to 12345678901234.98 and it works and displays OK. I have used so SQL DB browser and can see it presented as 12345678901235.0 but it seems to, in reality, hold the precision OK.

**Comment by vomikan** [comment]
I've changed static_cast<long> to static_cast<long long>
and it became better.

**Comment by whalley** [comment]
I get, at the same point....
<img width="400" alt="image" src="https://user-images.githubusercontent.com/487345/133063569-c4f70d91-ce0f-4260-b9cb-b78cf71a3c11.png">

**Comment by whalley** [comment]
> I've changed `static_cast<long>` to `static_cast<long long>`
> and it became better.
> ![image](https://user-images.githubusercontent.com/6836805/133063477-5913d53f-8028-45f5-a775-09fd1a7d3d45.png)

OK. Seems on Win t

> I've changed `static_cast<long>` to `static_cast<long long>`
> and it became better.
> ![image](https://user-images.githubusercontent.com/6836805/133063477-5913d53f-8028-45f5-a775-09fd1a7d3d45.png)
> but it should be 12345678901235.00

Not sure why is should be 12345678901235.00 ??

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/133065492-25e49380-0c30-4dde-9344-0fcecbf5782a.png)

**Comment by whalley** [comment]
> > Not sure why is should be 12345678901235.00 ??
> 
> Becouse this value in the DB
> 
> ![image](https://user-images.githubusercontent.com/6836805/133065492-25e49380-0c30-4dde-9344-0fcecbf5782a.png)

Yes, as I noted above I can see that when looking at DB. But whey can I change value to 12345678901234.99 or 12345678901234.98 in the DB and it successfully presents OK???   I'm confused.

**Comment by vomikan** [comment]
FYI
unsigned long long: represents an integer in the range from 0 to 18,446,744,073,709,551,615. It takes up, as a rule, 8 bytes (64 bits) in memory.

**Comment by vomikan** [comment]
>Yes, as I noted above I can see that when looking at DB. But whey can I change value to 12345678901234.99 or 12345678901234.98 in the DB and it successfully presents OK??? I'm confused.

Yep. The same for me.

**Comment by whalley** [comment]
All I can think is the SQLLite presentation has limited precision.. Very odd.

**Comment by whalley** [comment]
> FYI
> unsigned long long: represents an integer in the range from 0 to 18,446,744,073,709,551,615. It takes up, as a rule, 8 bytes (64 bits) in memory.
> 
> There are about 36.8 trillion dollars of physical money in the world.
> 
> 38 000 000 000 000$

Sadly, I've got a very very very small %age of that!!!! :-)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3865
