### ISSUE TITLE
translation inconsistent: GRM

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3809]
MMEX version:
 - [x] 1.5.x
 - [x] 1.6.x

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

There are 2 cases in use for "report"/"reports" although there is no visible difference in plural vs singular usage:
1) general reports manager
2) general report manager 

Apologies if I'm missing something.

Expected result:

Let's make it consistent, pls.

Actual result:

Inconsistency.

**Comment by vomikan** [comment]
I don't understand the issue.

**Comment by tygryk** [comment]
@vomikan well, maybe I'm too picky. Please, bear with me. You and the team are doing great job and my only goal is to help make MMEX better, not to offend you.

sometimes "GRM" is written in full as "general reports manager" ("reports" in plural)
sometimes "GRM" is de-abbreviated "general report manager" ("report" in singular)

As a consequence, I have to translate in plural/singular, too. I do so for a number of reasons. E.g., to keep proper connection in translation between separate words of "reports"/"report" at Crowdin platform so later it helps translate faster. And also for UX being consistent: if user saw plural in English UI, then it should be also plural in the language I translated to.

However, to me this is a name of a tool that is a constant. It's like OS "windows" which is always in plural. 

So the "GRM" initialism should either always be in plural or in singular.

Hope, I could explain myself

**Comment by renato-mmex** [comment]
@tygryk You may be right, but from my point of view you shouldn't keep picking on such a minor point. The MMEX developers are doing their best to develop MMEX and fix urgent bugs. I would appreciate it if users would also get their priorities right.

**Comment by tactilis** [comment]
I have to give a counter view Renato.

@renato-mmex
> you shouldn't keep picking on such a minor point
> I would appreciate it if users would also get their priorities right.

From my point of view, there is no problem with people _reporting_ inconsistencies and other minor points with MMEX.

They _are_ real issues that MMEX users have taken the time to raise here and I think this should be encouraged, especially if the reporter thinks about the issue and explains or justifies their proposed change.

Surely it is up to the developers (principally @vomikan and @whalley at the moment) to decide what _their_ priorities are for making changes (or not) as they see fit.

Without wishing to be disrespectful to you, there have been a few posts where the tone seems to be one of trying to suppress the reporting of what you regard as 'low priority' issues.

In my view, there's no harm in these issues being raised, discussed, and then a priority assigned by those who are choosing to do the work.

This is open source software. Everybody can contribute in large or small ways.

**Comment by renato-mmex** [comment]
@tactilis
you write: This is open source software. Everybody can contribute in large or small ways.

Maybe that is why you are entitled to contribute my opinion.

**Comment by tygryk** [comment]
@renato-mmex why are you so harsh on people?

**Comment by whalley** [comment]
If people find issues, no matter how small, I’m happy for them to raise it. The developers can then prioritise.

**Comment by vomikan** [comment]
@tygryk 
You translate both into Russian and Belarusian. Translate creatively so that it is clear and readable in the target language. This may differ in the original, since the rest of the languages are different.

Ты переводишь как на русский, так и на белоруский языки. Переводи творчески, чтобы было понятно и читаемо на языке перевода. В оригинале это может отличаться, так как остновы языков разные.

P.S. It is difficult to offend us, we simply ignore offensive messages.
Thank you for your contribution to the translation, corrections and active participation.
