### ISSUE TITLE
Request to change the way a "Duplicate Record" is created

### ISSUE THREAD

**Issue by DavidCinUK** [moneymanagerex/moneymanagerex#3810]
> When you create a "Duplicate Record" that new record takes today's date.  However, if you are duplicating a record that has a future date it would be much more useful to keep that future date as the date for the new record rather than the new record's date reverting to "today's" date.  Earlier versions of MMEx used to work that way but recent updates moved away from that logic for some reason.   If there was a good reason why the current logic was changed to, may be you could provide a "setting option" whereby the user can select to "set any new duplicate record's initial date to be today's date" or "set the duplicate record's initial date to be the date of the record being duplicated"

> Please do not remove information attached below this text.

<hr>Version: 1.5.6 64-bit<br>
 • Build: Aug 20 2021 09:29:18<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1920x1200 32bit 96x96ppi

**Comment by whalley** [comment]
See https://github.com/moneymanagerex/moneymanagerex/issues/3784
