### ISSUE TITLE
Date Range menu disapears

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3820]
![image](https://user-images.githubusercontent.com/6836805/131021227-dff196ae-8aab-4182-8b11-398daa6c11d1.png)

**Comment by whalley** [comment]
@vomikan Think we something similar to https://github.com/moneymanagerex/moneymanagerex/blob/17c88316003e2003eaa856f84bb0a2ce9b0e7703/src/util.cpp#L1529 for the transaction font coloring as some transactions become unreadable

E.g.
![image](https://user-images.githubusercontent.com/487345/131228723-299d2e17-a28d-4eae-8922-0943c8328d23.png)

**Comment by vomikan** [comment]
We can add a small colored square.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/131715443-692833ad-a2a6-469b-862a-a01f43b151b0.png)
