### ISSUE TITLE
Translation typo: "This can for currency rate changes"

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3828]
docs -> index.html 

The string in English "This can for currency rate changes" is missing some essential words ))

P.S. Pardon my brevity

**Comment by vomikan** [comment]
What word is missing?

**Comment by tygryk** [comment]
@vomikan 

Sorry, I can't say for sure. I see that a second verb is missing and probably a noun. Maybe like "This can **be used** for …" or "This **ratio will be taken** for…" or "This **field** can **be used** for…". I'm not the author of the original text so can't say what the author meant to express.

Here's the full context

Advanced
For a transfer transaction, when the amount in the From Account is different to the To Account, the difference is recorded in the separate fields. This can for currency rate changes.


Hope it helps

**Comment by tactilis** [comment]
Options:

1. This can be used for currency rate changes.

2. This can be used to allow for currency rate changes.

3. This can be used to account for currency rate changes.

2 and 3 are more specific than 1.

I favour 2.

Take your pick.
