### ISSUE TITLE
Where the Money Goes > view Details of Transactions

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#3829]
# Description of the feature

I would appreciate it as a great help if I could directly view the related details in a window in the evaluation "Where the Money Goes".

<img width="513" alt="MMEX28" src="https://user-images.githubusercontent.com/76920138/131391597-51ee6a65-bd09-47ba-a0d6-de7a8de8abfd.png">

**Comment by whalley** [comment]
#3283 

Hopefully will have this implemented soon

**Comment by renato-mmex** [comment]
Hello vomikan and whalley
Thanks for this feature, great job, this is a real step forward for the evaluations (analysis of income/expenses)
![Klatschen](https://user-images.githubusercontent.com/76920138/140200843-68afbe6a-02ba-4bbf-8127-8ef9a6df6601.gif)
.

**Comment by wilrino** [comment]
Thank you vomikan and whalley!!!
This feature is really useful!
