### ISSUE TITLE
GPL Version

### ISSUE THREAD

**Issue by dwrj87** [moneymanagerex/moneymanagerex#383]
In LICENSE, it contains GPLv2

In setup/linux/debian/build_new.sh it states GPLv3

In setup/linux/rpm/mmex.spec it states GPLv2

On the website, it states GPLv2

**Comment by guanlisheng** [comment]
thanks @dwrj87.
@vomikan , please help to here to make them consistent

**Comment by dwrj87** [comment]
`ack GPL` returned this (I've stripped out anything relating to 3rd party stuff)

setup/linux/debian/copyright
12:License: GPL-3.0+
14:License: GPL-3.0+
29: Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

setup/linux/rpm/mmex.spec
12:License:        GPL2 or any later version

po/arabic.po
7429:#~ msgid "Released under the GNU GPL License"
7430:#~ msgstr "الاصدار تجت تصريح GPL مجاني ومفتوح المصدر"

po/russian.po
7380:#~ msgid "Released under the GNU GPL License"
7381:#~ msgstr "Распространяется на правах лицензии GNU GPL"

po/spanish.po
7613:#~ msgid "Released under the GNU GPL License"
7614:#~ msgstr "Publicado bajo Licencia GNU GPL"

po/swedish.po
7340:#~ msgid "Released under the GNU GPL License"
7341:#~ msgstr "Utgiven under GNU GPL License"

po/chinese_zh.po
7452:#~ msgid "Released under the GNU GPL License"
7453:#~ msgstr "遵循 GNU GPL 協議"

po/dutch.po
7339:#~ msgid "Released under the GNU GPL License"
7340:#~ msgstr "Uitgebracht onder GNU GPL licentie"

po/serbo-croatian.po
7526:#~ msgid "Released under the GNU GPL License"
7527:#~ msgstr "Softver pod GNU GPL licencom"

po/dutch_be.po
7549:#~ msgid "Released under the GNU GPL License"
7550:#~ msgstr "Uitgebracht onder GNU GPL licentie"

po/norwegian.po
7457:#~ msgid "Released under the GNU GPL License"
7458:#~ msgstr "Sluppet under GNU GPL lisens"

po/german.po
6982:#~ msgid "Released under the GNU GPL License"
6983:#~ msgstr "Veröffentlicht unter der GNU GPL Lizenz"

po/turkish.po
7514:#~ msgid "Released under the GNU GPL License"
7515:#~ msgstr "GNU GPL Lisansı altında geliştirilmiştir."

po/serbian.po
7439:#~ msgid "Released under the GNU GPL License"
7440:#~ msgstr "Програм је под GNU GPL лиценцом"

po/hungarian.po
7320:#~ msgid "Released under the GNU GPL License"
7321:#~ msgstr "A GNU GPL licenc alapján terjesztve"

po/czech.po
7315:#~ msgid "Released under the GNU GPL License"
7316:#~ msgstr "Released under the GNU GPL License"

po/latvian.po
7488:#~ msgid "Released under the GNU GPL License"
7489:#~ msgstr "Izlaists saskaņā ar GNU GPL Licences noteikumiem"

po/romanian.po
7491:#~ msgid "Released under the GNU GPL License"
7492:#~ msgstr "Lansat sub Licența GNU GPL"

po/portuguese_portugal.po
7529:#~ msgid "Released under the GNU GPL License"
7530:#~ msgstr "Lançado sob licença GNU GPL"

po/slovenian.po
7491:#~ msgid "Released under the GNU GPL License"
7492:#~ msgstr "Program pod GNU GPL licenco"

po/vietnamese.po
7119:#~ msgid "Released under the GNU GPL License"
7120:#~ msgstr "Được phát hành theo giấy phép GNU GPL"

po/chinese_chs.po
7300:#~ msgid "Released under the GNU GPL License"
7301:#~ msgstr "遵循GNU GPL 协议"

po/ukrainian.po
7473:#~ msgid "Released under the GNU GPL License"
7474:#~ msgstr "Розповсюджується згідно до ліцензії  GNU GPL "

po/hindi.po
5896:#~ msgid "Released under the GNU GPL License"
5897:#~ msgstr "GNU GPL लाइसेंस के तहत जारी"

po/greek.po
7606:#~ msgid "Released under the GNU GPL License"
7607:#~ msgstr "Εκδόθηκε κάτω από άδεια GNU GPL "

po/croatian.po
7523:#~ msgid "Released under the GNU GPL License"
7524:#~ msgstr "Softver pod GNU GPL licencom"

po/tamil.po
7276:#~ msgid "Released under the GNU GPL License"
7277:#~ msgstr "GNU GPLன் கீழ் வெளியிடப்பட்டது."

po/indonesian.po
7828:#~ msgid "Released under the GNU GPL License"
7829:#~ msgstr "Di rilis di bawah lisensi GNU GPL"

**Comment by vomikan** [comment]
What kind of licemse we will prefer?
GPLv3 ??

**Comment by guanlisheng** [comment]
The key is to keep consistent 

LiSheng

**Comment by vomikan** [comment]
Hi team,

What kind license we will prefer?
Just for me I don't undestand diff between GPLv2 vs GPLv3 etc


2015-02-12 0:47 GMT+03:00 David Jones <notifications@github.com>:

**Comment by siena123** [comment]
We should check the other licenses that we are using. See the section "New
Compatible Licenses" section of
http://www.gnu.org/licenses/quick-guide-gplv3.html. If we are using any of
the GPL3 compatible only licenses then we need to update to GPL3.

The link also explains the major differences between version 2 and 3. My
vote would be to update from GPL2 to GPL3 regardless of any possible
compatibility issue I mentioned above.

- James

**Comment by siena123** [comment]
In checking, It looks like we are not using any incompatible licenses such that we must use GPL3 but I would still recommend updating all instances to show GPL3.

**Comment by guanlisheng** [comment]
Done or not? I want to close the ticket soon?

**Comment by dwrj87** [comment]
I'd be happy to do the work if it's decided on GPLv3

**Comment by guanlisheng** [comment]
i think we should on GPL2

**Comment by dwrj87** [comment]
The majority of the current files state GPLv2, as does the website. Therefore, since there is one for 2, one for 3, I recommend keeping with the status quo and I'll get rid of the reference to GPLv3
