### ISSUE TITLE
Date spinner on Enter Recurring Transaction not working

### ISSUE THREAD

**Issue by PaulBP14** [moneymanagerex/moneymanagerex#3830]
This has been broken for a few versions now, go to Recurring Transactions. Select one and right-click. Choose Enter Recurring Transactions, the date in the top right is "Date Paid" - the date can be freely amended using the keyboard and the calendar but the up and down arrows do not do anything.

**Comment by whalley** [comment]
I presume you mean "Enter Next Occurrence". 

I can reproduce this on Windows. On MacOS this works fine (as the spinner is integrated into the control). 

The Edit Recurring Transaction spinner works OK, it is just the "Enter Next Occurrence" that is wrong.

**Comment by PaulBP14** [comment]
Apologies, yes "Enter Next Occurrence"
