### ISSUE TITLE
Balance error

### ISSUE THREAD

**Issue by eddietheone** [moneymanagerex/moneymanagerex#3831]
I have downloaded the 1.6 version and I have one account that  shows a wrong balance.
Luckily it is a very short account so far.

I debited the account with an amount of 737.37 balance showed as -737.37
I then transferred a sum of 737.37 to cover it and the balance showed as 0.00
All correct so far
I then transferred another amount to the account of 91.03 and the balance showed as 0.00 instead of 91.03
I then entered the debit of 91.03 and the balance showed as -91.03 when it should have been 0.00.  

MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I can't reproduce this. Can you check that on the transfer the 'Advanced' option was not selected. The only way I can reproduce the 'error' transfer is by using the advanced option as below.

![image](https://user-images.githubusercontent.com/487345/131503735-7bf82617-57f3-40c3-8b33-8aadeb82934b.png)

**Comment by tactilis** [comment]
@eddietheone
Do you mean MMEX version 1.5.6, instead of 1.6 ?

>  I then transferred another amount to the account of 91.03 and the balance showed as 0.00 instead of 91.03

Have you perhaps accidentally set the status of that transaction to Void? Doing so would prevent it being included in the calculation of the balance. 

Can you include a screenshot please showing the transactions that you have described?

**Comment by eddietheone** [comment]
The advanced option is not checked. I have found if you click on the date
column you can get it to display properly  and back to wrong by clicking
the date again.

**Comment by whalley** [comment]
Tnink some screenshots would be helpful in diagnosing this.

**Comment by tactilis** [comment]
I can't reproduce it either. I've tried reordering the date column and others too.

So two screenshots please @eddietheone, showing a) the incorrect balance and b) the correct balance when you reorder the dates.

Could you also ensure that you have the ID column displayed when you take the screenshots.

**Comment by eddietheone** [comment]
Yep how do I do the screen please and then attach it to the mail please.
Not done that before.

**Comment by whalley** [comment]
https://support.microsoft.com/en-us/windows/use-snipping-tool-to-capture-screenshots-00246869-1843-655f-f220-97299b865f6b

Best to click on the 'View in Github' option on the mail then you can just paste or drag the image to the response area when writing the response. As noted.

![image](https://user-images.githubusercontent.com/487345/131562796-f0b9b87c-bed0-4811-8918-7aebbdb05bb6.png)

**Comment by eddietheone** [comment]
Thanks, I'll check it out.

**Comment by eddietheone** [comment]
I have managed to do 2 screen shots of the issue which are attached. Hope
they are of some use to you.
Cheers Edward

**Comment by tactilis** [comment]
@eddietheone 
> I have managed to do 2 screen shots of the issue which are attached.

There are no screenshots attached.

Please could you go to [github.com/moneymanagerex/moneymanagerex/issues/3831](https://github.com/moneymanagerex/moneymanagerex/issues/3831) and attach your screenshots there.

**Comment by whalley** [comment]
@eddietheone Can we assume this is now sorted and we can close. If not please post the screenshots requested.

**Comment by eddietheone** [comment]
Yes sorted now I think
