### ISSUE TITLE
Account Statement

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3839]
@all 

I have a question. Are these labels clear to the user? Does it make sense to search for synonyms?
The translation into Russian is done terribly, because the translators give options that do not convey the meaning of these controls.

![image](https://user-images.githubusercontent.com/6836805/131998725-ab1f0f4f-7331-45a3-8312-749924ffd847.png)

**Comment by reddyshyam** [comment]
Clear to me in English.

**Comment by vomikan** [comment]
@tygryk  let's fix it

![image](https://user-images.githubusercontent.com/6836805/132060721-1150cf2b-7f56-4ebe-b3a7-4d63cc89619c.png)

**Comment by vomikan** [comment]
Statement ['steɪtmənt] n
gen. | ведомость; ведомость (as in); сообщение; изложение; выписка; утверждение; официальный отчёт; положение; спецификация; формулировка; бюллетень; декларация; постановление (Notburga); доклад (Notburga); комментарий (положение нормативного документа, содержащее информацию, поясняющую суть требования или правила, а также примеры его применения ABelonogov); объяснительная (charen); информация из официальных источников; постановка задачи; высказывание; ведомость (as in statement of sales, etc.); информационное письмо (Alexander Demidov); идея (например, collection statement - идея ювелирной коллекции silverwayg); показатель (Skygirl)
Gruzovik | выступление
account. | заполнение анкеты; ответ опрашиваемого лица; подсчёт; сметная калькуляция; форма отчетности (inn)
amer.usg. | выписка из счёта

 Мне нравится "Выписка"
 
 statement: Состояние   [v] Зафиксировать
 reconciled date: Дата фиксации
