### ISSUE TITLE
Can't type in HML Scale factor

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3846]
MMEX version:
 - [x] 1.5.6

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

Can't type in number for HML scale factor.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open Settings CMD+,
2. View Options
3. HML Scale Factor
4. Type in 150

Expected result:

Number is typed fine and accepted.

Actual result:

Error sound and no number appears.

# Additional information

Only can change value with buttons up/down

- "Budget Offset (days)" accepts typing in numbers
- If I copy value "15" from "Budget Offset (days)" to "HML Scale Factor" then I can type in "0" at the end of the inserted value. If I copy "1" then I can't type anything at the end
- if there are 2 numbers already in the field then I can type anything after them. And then I can remove numbers that were there before my typing. If there are less than 2 digits in the field (1 or 0) then typing is not allowed.

<img width="422" alt="Screen Shot 2021-09-09 at 16 25 32" src="https://user-images.githubusercontent.com/9718911/132695893-f69b7e1a-b8ff-4112-b428-8f553aaadcc9.png">

**Comment by tygryk** [comment]
@whalley apologies. did not want to spoil your day.

**Comment by whalley** [comment]
Can you delete the mmexini.db3 file and restart MMEX. There may be a corruption in it. It should not be possible to have an empty value. The default is 100 and the range for the value is 25 to 300.

**Comment by tygryk** [comment]
deleted mmexini.db3

same issue

**Comment by tygryk** [comment]
ignore empty value

event when value is not empty and has 1 digit i cannot type in

**Comment by whalley** [comment]
Yes, I can reproduce. If you use the spin control to get down to 25 (the minimum) delete the '5' it will not allow '4' to be entered.... Seems to be an issue with values less than 25 being entered. On windows in allows lower values to be entered but will revert to lowest value, e.g. 25 when applied. 

Seems to be a MacOS wxWidgets issue as it works fine on Windows... Will investigate later.

**Comment by whalley** [comment]
It's been a bug in wxWidgets for 11 years, but not yet fixed! https://trac.wxwidgets.org/ticket/12968

**Comment by tygryk** [comment]
gosh! does not sound promising to me. so it'll be a "no fix" for MMEX I guess?

**Comment by whalley** [comment]
I've implemented a workaround :-)

**Comment by tygryk** [comment]
@whalley I confirm it's working in my case. You are a God! )) Thank you for such a fast implementation
