### ISSUE TITLE
Ability to specify which columns are include in transaction report

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3863]
# Description of the feature

How can I select which columns will appear in a transaction report?
I mean, when I use the "Transaction Filter" window to have a list of transactions (for instance: all the ones relative to the year 2020), the resulting report has 9 columns (date, account, payee etc etc...) I would like to toggle out some of those columns, that I don't need, so that they won't appear in the report. Is that possible? Thank you.

https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10477

**Comment by vomikan** [comment]
I think the following GUI desighn is Ok for this issue

![image](https://user-images.githubusercontent.com/6836805/133942835-644d6960-127e-468b-b177-81e52ab5816e.png)

**Comment by 2BeeOrNot** [comment]
This is great. I can hide the ID and color columns.

This is marked closed but the hidden columns are not persisted. Not between transaction reports without saving as a preset. Not saving as a preset. Other filters are persisted between transaction reports without saving as a preset and saved as a preset.

**Comment by vomikan** [comment]
> This is great. I can hide the ID and color columns.

Thank you

> This is marked closed but the hidden columns are not persisted. Not between transaction reports without saving as a preset. Not saving as a preset. Other filters are persisted between transaction reports without saving as a preset and saved as a preset.

I'm not sure if it's worth saving these settings. It is probably necessary to separate the saving of settings for invoices and reports, then implement the saving of parameters. So far, in the next release, this will be without saving.
