### ISSUE TITLE
Search zone for Categories 

### ISSUE THREAD

**Issue by drspoke** [moneymanagerex/moneymanagerex#3864]
# Description of the feature
When you add or edit a transaction, sometimes (Often...) you modify the category
In the top of the category window, A search box would be very useful .
You have always have the choice to expense each master categeroies to found the correct, or you make a search and you find it directely.

![2021-09-16 14_39_01-Money Manager Ex - C__Users_banorga_Google Drive_Mes Documents_Banque_MoneyManag](https://user-images.githubusercontent.com/33481120/133614381-47e13849-8692-4cc4-a3f0-b645df0812c9.png)

**Comment by vomikan** [comment]
Just expand then select root item then type first letter of the [sub]category name.

![image](https://user-images.githubusercontent.com/6836805/133622624-f8750b91-b1e8-46a7-a68f-9bc48e23bcc1.png)

**Comment by whalley** [comment]
Search has already been added, this issue is not outdated. Closing
