### ISSUE TITLE
The selection "last month" is wrong

### ISSUE THREAD

**Issue by gidammex** [moneymanagerex/moneymanagerex#3870]
> È sbagliata la selezione "mese scorso": oggi è il 19/09/2021 e "mese scorso" mi dà:  da 01/06/2021 a 31/07/2021 invece di: da 01/08/2021 a 31/08/2021 (versione aggiornata oggi 19/09/2021 alla 1.5.7 64 bit. Grazie
> Per favore non rimuovere le informazoni allegate sotto questo testo.

<hr>Version: 1.5.7 64-bit<br>
 • Build: Set 18 2021 17:22:19<br>
 • db 7 •  (aes128cbc)<br>
 • git 576cc4b (2021-09-18)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Italian (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by renato-mmex** [comment]
Translated as www.deepl.com :

The selection "last month" is wrong: today is 19/09/2021 and "last month" gives me: from 01/06/2021 to 31/07/2021 instead of: from 01/08/2021 to 31/08/2021 (version updated today 19/09/2021 to 1.5.7 64 bit. Thanks
