### ISSUE TITLE
Invalid sector <T> subscript

### ISSUE THREAD

**Issue by TonySLondon** [moneymanagerex/moneymanagerex#3874]
> Replace this text (marked with >) with detailed description of your problem.
Invaled vector <T> subscript
> Please do not remove information attached below this text.

<hr>Version: 1.5.0-RC.2 64-bit<br>
 • Build: Mar 28 2021 10:06:37<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1920x1080 32bit 96x96p
![Invalid](https://user-images.githubusercontent.com/88109285/134318152-9a1cd595-aaf4-4b93-8fc7-62a9d493a505.jpg)
p
![Invalid](https://user-images.githubusercontent.com/88109285/134318230-a4bb3cec-3a71-4df0-a1d5-e566ec90464c.jpg)
i

**Comment by renato-mmex** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=3&t=10481

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3833
