### ISSUE TITLE
Reminder of one-off payments

### ISSUE THREAD

**Issue by ecofielder** [moneymanagerex/moneymanagerex#3883]
Hello,

sorry for my bad english.

I'm a programmer too. I would like to comment on the program. This feature has been missing from the program for a long time.
On the Summary page, in listing due transactions the item that was recorded for one-time performance only does not appear. And I think that would be very important. This is because the program does not warn me about this.

I don't think the development is complicated either, as the line is expanded with + one query. The other missing feature is to send an email notification of due items.

Many thanks

Mihaly Hajas
by ECOfield TECH

**Comment by vomikan** [comment]
I can't reproduce it.

As for sending emails, this should be implemented on the server side. A similar solution could be implemented using WebApp
https://github.com/moneymanagerex/web-money-manager-ex

**Comment by whalley** [comment]
Closing. Not reproducible and e-mail sending out of scope.
