### ISSUE TITLE
MMEX 1.4.0 has stopped opening databases on iMac.  

### ISSUE THREAD

**Issue by MReynolds58** [moneymanagerex/moneymanagerex#3886]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [ x] Mac OSX
 - [ ] Linux 

# 1.4.0 no longer opens databases.  Tried to upgrade to 1.5.7 but this does not open either 
MMEX 1.4.0 has stopped opening databases on iMac.  

<img width="467" alt="Screenshot 2021-09-25 at 17 38 35" src="https://user-images.githubusercontent.com/91384546/134779043-9d320335-18b6-41fb-8183-3d3dd45fd131.png">

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  Open MMEX 
2. Select open database 
3. Chose any database from list 

…

Expected result: data 

Actual result:no data showing 

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2353
