### ISSUE TITLE
forum registration

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3888]
![image](https://user-images.githubusercontent.com/6836805/134818292-21ae10c9-dbd8-49b1-9129-9c0aaea055e5.png)

**Comment by renato-mmex** [comment]
I was able to complete the registration without any problems.
I have informed the user

**Comment by vomikan** [comment]
Possible it depend on browser. It was my attempt to create new account. I used MS Edge.

**Comment by renato-mmex** [comment]
**I have just tested with** 
Microsoft Edge
Version 94.0.992.31 (Offizielles Build) (64-Bit)
**no problem**
