### ISSUE TITLE
manual share price is not saved

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#3892]
MMEX version:
 - [x] 1.5.8 Beta1

Operating System:
 - [x] Windows 11

# Description of the bug

manual share price is not saved

# Reproduction

Is the bug reproducible? 
 - [x] Always 
<img width="295" alt="MMEX30" src="https://user-images.githubusercontent.com/76920138/135122383-55a7af21-c7ae-464a-a61c-4ba1c2bf478e.png">

**Comment by whalley** [comment]
Seems to work OK for me on MacOS and Win 11. See below.

![CleanShot 2021-09-28 at 23 30 47](https://user-images.githubusercontent.com/487345/135174646-1ec6f1a7-1d79-40a6-9835-865795d3c84f.gif)

**Comment by grumpy235** [comment]
@whalley I don't think your example works on Windows. I did raise https://github.com/moneymanagerex/moneymanagerex/issues/2421 and have been doing the following ever since
1. Click Add
2. Change the date
3. Update **Curr.Share Price field**
4. Hit save then close

**Comment by renato-mmex** [comment]
@whalley
I have tested it really seriously.
On the input mask it works, **but it is not saved in the database.**

as @grumpy235 describes, also mutations are not saved

**Comment by renato-mmex** [comment]
Addendum: the display does not show the whole history of the courses
Mutations as well as new courses can apparently only be executed within the display (~one year).

my stock history has 2839 entries starting 2001-05-01

Have now corrected the wrong value with the DB Browser.

**Comment by grumpy235** [comment]
@renato-mmex better translation of what I assume originally was Kurs is I think price rather than course and what I assume originally was 'die Veränderung' would be modifications. In English, mutation would be used for describing the difference between Covid-19 Alpha and Covid-19 Delta. 😀

**Comment by renato-mmex** [comment]
have tried to reproduce the error in a test accounting, without success.
So I have deleted all the information in my accounting except the "STOCKHYSTORY_V1".  Of the 2839 entries, only the latest from 2020/2021 are displayed.
But I also notice that there are different entries (with 12 decimal places)

[Stock.zip](https://github.com/moneymanagerex/moneymanagerex/files/7254517/Stock.zip)

![image](https://user-images.githubusercontent.com/76920138/135333970-9788a3c1-2eb9-4841-8dcc-a3b79dfcd05d.png)


Yes, I know my English leaves something to be desired, sorry if it's just sometimes misspelled.
At my school time shortly after the second world war, there were still no English lessons.

**Comment by whalley** [comment]
> At my school time shortly after the second world war, there were still no English lessons.

Dein Englisch ist besser als mein Deutsch !!

**Comment by renato-mmex** [comment]
@whalley Oh yes, www.deepl.com helps me, but also makes mistakes.
