### ISSUE TITLE
Cash flow chart of past years

### ISSUE THREAD

**Issue by wilrino** [moneymanagerex/moneymanagerex#3895]
In the predefined **reports**, the useful function has been created to visualize the **cash flow** of the next year or the next 10 years.

Sometimes I happen to have to view the cash flow trend of the _previous months_ (and I solve it by exporting the data to excel and creating a graph).

It would be nice to be able to **customize the period** of the cash flow chart by changing the settings of the already existing chart.

Thank you very much!

**Comment by whalley** [comment]
By cash flow trend of previous months are you referring to the detail available on the Income vs Expenses Report? This has recently been updated to plot the 'cumulative' figure (in effect the cash flow for previous months) See: https://github.com/moneymanagerex/moneymanagerex/issues/3875. Is this sufficient for your needs?

**Comment by wilrino** [comment]
Thank you Whalley!
Yes, the result that interested me is the same (I was looking for the cumulative but by intuition I started from the cash flow graph that shows the future, but this solution is also fine!)!
Thank you very much, also for the quick reply!
I await the version v1.5.8
