### ISSUE TITLE
UI Appearance settings don't persist on upgrades

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#3903]
Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Hello,

I just upgraded to 1.5.8 and have noticed on this upgrade as well as previous upgrades that UI appearance settings don't persist. Specifically, I have adjusted column widths in the register, have a custom HTML scale factor, and use the default theme. 
On upgrade the theme changes to yellow-blue and the column width and scale factors are reset.

Thank you!

**Comment by vomikan** [comment]
It seems you lost mmexini.db3 file.

**Comment by user8446** [comment]
Hi,
The settings persist on opening/closing MMEX so I have that file. I checked and it's in the folder with a modified time that matches the upgrade. 
Are you saying it got lost on the upgrade?

**Comment by vomikan** [comment]
Anyway it already overwritten on the upgrade. I recommend to make a copy of this file before next upgrade.

**Comment by user8446** [comment]
No problem, I'll do that. Is the expected behavior to not overwrite on an upgrade?

**Comment by vomikan** [comment]
It's nothing has been changed in the code of the application regarding this. 

Could you, please, clarify what type the program are you using (portable or not).

**Comment by tactilis** [comment]
And please say in which folder you have your mmexini.db3 file?

**Comment by user8446** [comment]
Im using the installed 64-bit windows version and the file is in C:\Program Files\Money Manager EX

**Comment by vomikan** [comment]
It should not be there C:\Program Files\Money Manager EX
Becous it a system folder and should be protected.

**Comment by user8446** [comment]
Ok where should it have been located? 
FYI I installed with the exe installer and didn't move the file.

**Comment by vomikan** [comment]
On MS Windows it should be here:
%USERPROFILE%\Application Data\MoneyManagerEx
In case if you uninstall the application the folder "C:\Program Files\Money Manager EX" would be deleted with your mmexini.db3 (settings).
I recommend to move the mmexini.db3 file from C:\Program Files\Money Manager EX to %USERPROFILE%\Application Data\MoneyManagerEx

**Comment by user8446** [comment]
Ok thank you... I will do that and close this and see if the settings persist on the next update.

**Comment by vomikan** [comment]
> Ok where should it have been located? FYI I installed with the exe installer and didn't move the file.
> 
> Edit: I found another mmexini.db3 file in `C:\Users\####\AppData\Roaming\MoneyManagerEx` It's size is a litter bigger at 188kb vs 64kb like the one in `C:\Program Files\Money Manager EX`

regarding the information above...
Just delete C:\Program Files\Money Manager EX\mmexini.db3
