### ISSUE TITLE
Database access password protection

### ISSUE THREAD

**Issue by ansvver83** [moneymanagerex/moneymanagerex#3906]
Good morning
the title says all
thank u for your time

**Comment by whalley** [comment]
What about it?
![CleanShot 2021-10-03 at 19 07 19](https://user-images.githubusercontent.com/487345/135766155-e4f2c60e-a6be-4959-84a9-bfd5b31db2d8.png)

**Comment by tactilis** [comment]
@ansvver83
> the title says all

No it doesn't.
It's not even a question.

This will help:

**How to ask  a software support question**

1. Explain what you are trying to do – your 'big-picture' goal.
2. Take the time to explain _clearly_ the problem you are experiencing.
3. Show what 'solutions' you've already tried.
4. Share any error messages or the exact commands you're using (if applicable)
