### ISSUE TITLE
compile issue ubuntu 20.04

### ISSUE THREAD

**Issue by JordanDoane** [moneymanagerex/moneymanagerex#3911]
When I use "cmake --build . --target package" I get
 home/jordan/mmexx/moneymanagerex/src/util.cpp: In function ‘const wxString getProgramDescription(int)’:

/home/jordan/mmexx/moneymanagerex/src/util.cpp:1284:26: error: ‘class wxDisplay’ has no member named ‘GetPPI’
 1284 |                 display->GetPPI().GetWidth(),
      |                          ^~~~~~

/home/jordan/mmexx/moneymanagerex/src/util.cpp:1285:26: error: ‘class wxDisplay’ has no member named ‘GetPPI’
 1285 |                 display->GetPPI().GetHeight()

**Comment by vomikan** [comment]
It seems you need to build wxWidgets 3.1.6 firstly.
https://github.com/moneymanagerex/moneymanagerex/issues/4298
