### ISSUE TITLE
Share Accounts and Extra Columns

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3912]
# Description of the feature

The “View” option to show Share Accounts appears to reset after the app is closed. This is not in itself and issue, but I am finding that many times I would have liked the option to preserve the setting until I choose to cancel it. (I am going thru an exercise of updating scrip issues and the Share Accounts view is as, a consequence being used intensely).  Perhaps having the View option combined with the existing Share Accounts’ collapsibility in the Navigation Pane would provide a nice degree of flexibility?

Connected to this use would be columns to show the acquisition, disposal and the current balance of shares. To provide the option to de-clutter, these three new columns could be added to the ‘drop-down’ used to de-select specific fields from the shares Account view.

The question that I wonder about is, ‘Why were these share columns not provided in the first place? Or have I missed a point?’

Hope this makes sense.

**Comment by whalley** [comment]
Lost reason/source for raising this. Will close.

**Comment by tactilis** [comment]
> Lost reason/source for raising this. 

FYI, it was from this forum post:

https://webcache.googleusercontent.com/search?q=cache:h1mxJj7e05EJ:https://forum.moneymanagerex.org/viewtopic.php%3Ft%3D10497

(using Google cache because the forum thread has been deleted)

**Comment by whalley** [comment]
>The “View” option to show Share Accounts appears to reset after the app is closed. This is not in itself and issue, but I am finding that many times I would have liked the option to preserve the setting until I choose to cancel it. (I am going thru an exercise of updating scrip issues and the Share Accounts view is as, a consequence being used intensely).  Perhaps having the View option combined with the existing Share Accounts’ collapsibility in the Navigation Pane would provide a nice degree of flexibility?

Fixed. https://github.com/moneymanagerex/moneymanagerex/issues/4907

> Connected to this use would be columns to show the acquisition, disposal and the current balance of shares. To provide the option to de-clutter, these three new columns could be added to the ‘drop-down’ used to de-select specific fields from the shares Account view. The question that I wonder about is, ‘Why were these share columns not provided in the first place? Or have I missed a point?’

Should be covered in separate enhancement issue if anybody wants to raise with detailed use-case.
