### ISSUE TITLE
Stock report crashes

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#3926]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Selecting stock report -> summary on the right will cause the program to crash. 

![Névtelen1](https://user-images.githubusercontent.com/80578702/137713995-3b9b724b-e337-422f-9e60-a641f2e153d3.png)

[mmex.xml.tar.gz](https://github.com/moneymanagerex/moneymanagerex/files/7363988/mmex.xml.tar.gz)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

# Additional informatio
![Névtelen](https://user-images.githubusercontent.com/80578702/137713100-97ecbfca-d522-44f4-b321-f06f58f28974.png)

**Comment by XidRanReb** [comment]
Same here with a fresh 1.5.9 on Ubuntu 21.04

![Screenshot from 2021-11-03 16-37-45](https://user-images.githubusercontent.com/47121395/140092853-f7e031c3-6029-476a-ae82-dc1f0ed80e66.png)

**Comment by XidRanReb** [comment]
I was looking for the possible problematic commit.

If it can help, cf7f479 seems to introduce the bug.

**Comment by whalley** [comment]
Have reverted one of the change smade in https://github.com/moneymanagerex/moneymanagerex/commit/cf7f47975eb9b3e1671e5964a6c6354e7963be99 to "src/reports/summarystocks.cpp" as it was redundant for the report anyway.
![CleanShot 2021-11-04 at 00 46 04](https://user-images.githubusercontent.com/487345/140238771-e91f5361-0dd5-43cb-a66a-2d321ac50a47.png)

Let me know if that helps (though I'm not convinced it will)

**Comment by whalley** [comment]
Mis-numbered the commit. The PR is https://github.com/moneymanagerex/moneymanagerex/pull/3973

**Comment by XidRanReb** [comment]
Hu ! This was the reason !

Good catch and thank you for the fix !!
