### ISSUE TITLE
Currency exchange rates info

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3933]
Rates should be digit not currency
![image](https://user-images.githubusercontent.com/6836805/138551741-3135ba27-8bfe-4b25-b776-186185eec990.png)

**Comment by Hintsmth** [comment]
I've updated to 1.5.9 but a problem still remain. 
RUB is my main currency.
![1](https://user-images.githubusercontent.com/33121649/141651950-54931c39-7377-456a-a7f5-26fa3ebc6f21.png)

**Comment by whalley** [comment]
@Hintsmth Have you refreshed the currency rates?
