### ISSUE TITLE
Favourites Yes or No 

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#3939]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
If I don't select an open account as favourite it doesn't appear in the relevant list i.e a Bank Account which is unticked as a favourite doesn't appear in the Favourites or in the Bank Accounts. Tried closing and re-opening database, no effect.
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
@Speigy Do you still have this issue or can we close?

**Comment by TonySLondon** [comment]
Thank you, this has solved the 'problem'. Kind regards. Tony
