### ISSUE TITLE
Modify Sub-Category selection on Transaction Report

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#3944]
# Description of the feature

The current implementation only allows selection of a single category, a single category/sub-category combination or ALL sub-categories of a single category.
My request would be to improve the sub-category selection to allow one or more rather than just ALL.

In my case I have a Category C1 which has sub-categories of S1, S2, S3 and S4. The current implementation limits me to a report on for example C1/S3 or C1/(S1-S4), I would like to be able to select on C1/S2 and C1/S4 and for the data to be presented in a single report

**Comment by whalley** [comment]
The filter logic implemented in `src/filtertrans.cpp` supports the specification of multiple catgeories, utilising this with the transaction filter dialog may be useful if implementing this feature.
#3283

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4226
