### ISSUE TITLE
Recurring Transactions Entry

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3948]
I have noticed an issue when entering a Recurring transaction. After I enter the transaction the entry is moved to the bottom of the list with its next recurring date. However, focus is still maintained on that entry. In previous versions of your software the application returned focus to the next entry in the list. I have to specifically click on the next entry. This is an issue when I have more entries in the Recurring transaction list than will fit in the window. This means I have to scroll back up the list in order to select the next entry. I am using the following version under Windows 10:

Version: 1.3.6 64-bit
• Database version: 7 • (aes128cbc)

Is there an option somewhere that I am missing that can change this action?

Thanks,
Joyce

https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10365

**Comment by howff** [comment]
Thank you :-)
