### ISSUE TITLE
Totals in the main list are wrong

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#395]
Please see issue https://github.com/moneymanagerex/android-money-manager-ex/issues/22

The same thing happens in the desktop version on Windows. The total expenses, after spending €20 Euros in Hungary, show up as €1 226 059.70 for the month.
I wish it was that easy. :)

<s>All the values in the database look correct so I assume that the error is in the formula somewhere in the application.</s>

**Comment by vomikan** [comment]
Could you provide simple test DB with this issue?

2015-02-20 13:02 GMT+03:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
# Test 1

PC:
- create db
- create EUR account, initial balance €100
- create HUF account, initial balance 0

- sync via Dropbox

Android:
- create transfer EUR->HUF of €50.

Result: can't edit the HUF amount. The currency for EUR account is displayed as "L". (?)

https://www.dropbox.com/s/fw684qti9fuvxw9/alen.mmb?dl=0

# Test 2

PC:
- create db
- sync via Dropbox

Android:
- create EUR account, initial balance €100
- create HUF account, initial balance 0
- create transfer of €50 EUR->HUF, destination amount 15000 Ft. (amount editable)
- update currencies

Result: the EUR/HUF rate is wrong.

https://www.dropbox.com/s/j0nwm15hjm14bnj/test2.mmb?dl=0

My conclusion is that the error is somewhere in Android currency update. My original issue was solved after I updated currencies in the Windows desktop version of Money Manager Ex.

What was confusing in the original case was that, in Android, the rate was displayed as 306, which looked correct as that is the rate. But in reality the currencies were swapped. The real rate was supposed to be 1/306 = 0.0033. This is the rate that was set after the desktop currency update.

I'll copy this comment into the related GitHub issue, as well.

**Comment by MisterY** [comment]
I checked the database I used for testing a few days ago. There, HUF has a Scale of 1 and Conversion of 306.673.

**Comment by MisterY** [comment]
Found the cause. The currencies are reversed when calling the API in Android version.

`http://www.freecurrencyconverterapi.com/api/convert?q=EUR-HUF&compact=y`

Which URL are you guys using in desktop version?

**Comment by MisterY** [comment]
OK, I submitted a fix. Cheers!

**Comment by vomikan** [comment]
We used yahoo
 "http://download.finance.yahoo.com/d/quotes.csv?s=%s&f=sl1c4n&e=.csv";
where %s is
USDUER=X for example

2015-02-20 17:52 GMT+03:00 Alen Siljak <notifications@github.com>:

**Comment by vomikan** [comment]
just compare
http://www.freecurrencyconverterapi.com/api/convert?q=EUR-HUF&compact=y
result

{"EUR-HUF":{"val":306.6727}}


and
 http://download.finance.yahoo.com/d/quotes.csv?s=EURHUF=X&f=sl1c4n&e=.csv
result
EURHUF=X,306.0359,"EUR","EUR to HUF"
seems the same

2015-02-20 18:21 GMT+03:00 Nikolay Akimov <nikolay.akimov@gmail.com>:

**Comment by MisterY** [comment]
Right. And Yahoo generally seems more stable and responsive.
Maybe Alessandro decides to rewrite the update in the Android version. Or I might also try to do that when I find some time, and join the project.
