### ISSUE TITLE
automatic assignment

### ISSUE THREAD

**Issue by loki36** [moneymanagerex/moneymanagerex#396]
I want create a way to make automatic assignment on transaction

a way could be create a new table with rules for automatic assignment and apply it after import.

a table "field" where store all field's name where criterion could be apply
a table "condition" where we store condition code and label (ex : like - like / equal - = / ...)
a table "assignment" for rules assignment

are you interested with this feature ?

```
--creation table assignment
CREATE  TABLE  IF NOT EXISTS "main"."field" (
  "field_s" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "name" VARCHAR NOT NULL UNIQUE
);

INSERT INTO hip_field (name) VALUES ('note');

CREATE  TABLE  IF NOT EXISTS "main"."condition" (
  "condition_s" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "name" VARCHAR NOT NULL UNIQUE,
  "code" VARCHAR NOT NULL,
);

INSERT INTO hip_condition (name,code) VALUES ('like','like');

CREATE  TABLE  IF NOT EXISTS "main"."assignment" (
  "assignment_s" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
  "name" VARCHAR UNIQUE,
  "field_s" INTEGER NOT NULL,
  "condition_s" INTEGER NOT NULL,
  "criterion" VARCHAR,
  "third_s" INTEGER NOT NULL DEFAULT (-1),
  "third_overwrite_flag" NOT NULL DEFAULT (0),
  "subcategory_s" INTEGER NOT NULL DEFAULT (-1), 
  "subcategory_overwrite_flag" NOT NULL DEFAULT (0), 
  FOREIGN KEY(third_s) REFERENCES third(third_s),
  FOREIGN KEY(subcategory_s) REFERENCES subcategory(subcategory_s),
  FOREIGN KEY(field_s) REFERENCES field(field_s),
  FOREIGN KEY(condition_s) REFERENCES condition(condition_s)
);

example :
INSERT INTO "assignment" VALUES ("2","COFIROUTE","1","1","%COFIROUTE%","59","0","119","0");
INSERT INTO "assignment" VALUES ("14","Free Telecom","1","1","Free Telecom","15","0","108","0");
```

**Comment by vomikan** [comment]
I like this idea. We need a way to cut payee names after import.

Fyi
http://sourceforge.net/p/moneymanagerex/feature-requests/286/
 21 февр. 2015 г. 18:51 пользователь "loki36" <notifications@github.com>
написал:

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/feature-requests/314/

**Comment by loki36** [comment]
Hi,
I've made the new feature on my github repo under branch feature/master/automatic-assignment for database and moneymanagerex.

If you could have a look and say if it's ok for a pull request or if it need change, will great

**Comment by loki36** [comment]
Assignment main dialog is available with magic_wand or with menu

![capture du 2015-02-28 00 49 57](https://cloud.githubusercontent.com/assets/2657181/6423291/f7dfe910-bee3-11e4-8eda-3c6b23a24f13.png)

![capture du 2015-02-28 00 50 26](https://cloud.githubusercontent.com/assets/2657181/6423293/02a9430a-bee4-11e4-9121-53ef154eff8e.png)

![capture du 2015-02-28 00 46 44](https://cloud.githubusercontent.com/assets/2657181/6423296/07e6105a-bee4-11e4-89af-73b4d59d5846.png)

**Comment by guanlisheng** [comment]
@loki36 , this is a quite cool feature and would we have a more implicit naming to indicate that it's for checking transaction only.
a pull request is welcome!

**Comment by loki36** [comment]
I could add a new field in "assignment" table to indicate on which table execute the query.
with that we could extend this feature to other transaction type in future.

This feature needs a pull request on database github repo.

**Comment by guanlisheng** [comment]
After thinking over, I find it is too complex to understand for end users .

**Comment by loki36** [comment]
I can try to make a gui more easier to understand.
homebank use this interface :  
![capture du 2015-03-23 00 36 34](https://cloud.githubusercontent.com/assets/2657181/6772113/d71f3000-d0f4-11e4-8e72-9b2f59e0cb00.png)

**Comment by guanlisheng** [comment]
ok and look forward to the new look & feel.

**Comment by pluk77** [comment]
you can have a look here for another gui example. 

http://www.mechcad.net/products/acemoney/tutorial.shtml

ps, this is probably the only feature thats stops me from using this application as it will take way too long to import all my bank statements.

**Comment by artkrz** [comment]
Please make this happen. :+1:

**Comment by Fidelix** [comment]
This is one of 2 things stopping me from using mmex.
The other one is mass operations.
