### ISSUE TITLE
Windows version is not displayed correctly

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#3960]
Windows version 11 is displayed as windows 10

![image](https://user-images.githubusercontent.com/76920138/139488469-2bedfb56-5590-4d54-9efc-256ba482ba3c.png)

**Comment by whalley** [comment]
Think we might need for wXWidgets to catch up with the Win 11 release
https://github.com/wxWidgets/wxWidgets/blob/0ac8a75e9749c6cd715013c058616dc5d6a52ae3/include/wx/msw/private.h#L950

Also, I run Windows under ARM64 and there is no distinction between this and the Intel/AMD flavour.

**Comment by whalley** [comment]
Fix available in wxWidgets. Probably best to leave until next 3.1.x release.

https://github.com/wxWidgets/wxWidgets/commit/6cef0c046421d0f493159ac5ce70b2126e6d012b

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4290

**Comment by whalley** [comment]
Upgrade to wxWidgets 3.1.6 does indeed fix this issue....

![CleanShot 2022-04-18 at 00 04 09@2x](https://user-images.githubusercontent.com/487345/163735441-7bd04b01-8fd5-462d-ad13-0a7837ff1eeb.png)
