### ISSUE TITLE
Transactions color change

### ISSUE THREAD

**Issue by tosim91** [moneymanagerex/moneymanagerex#3965]
Running Linux Mint-MATE,20.2; using mmex 1.5.3. Been using mmex since its inception in Windows, and then in Linux. When I changed Transactions color from Default to another color, it locked up my computer to the point where I had to shut down.I wound up rebooting several times, as each time I clicked on the mmex icon, total lockup occurred.

**Comment by PMaff** [comment]
Just tried 
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.14-Beta.1
-- Commit         : 059e5b73c (2022-03-28)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 4.15.0-175-generic
-- Ubuntu 18.04 'bionic'
-- CMake 3.22.0
-- GNU Make 4.1
-- ccache
-- GNU 7.5.0
-- wxWidgets 3.1.5
-- wxSQLite3 4.6.0
-- Lua 5.3.3
-- curl 7.58.0
-- gettext 0.19.8.1
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done

```
on Ubuntu 18.04 without crashing the machine.

https://user-images.githubusercontent.com/93879362/160927087-2f3fcd65-5430-499c-9f9f-0ca5827c7d4b.mp4

**Comment by PMaff** [comment]
@vomikan : maybe it is a bit confusing that the color is not shown unless you select another entry?
See above short "screen film".
I guess this is because the item is still selected, if you select ok and the color of the selection is "overlapping" the color of the
item. I am not sure, if there is another possibility of the GUI.

**Comment by whalley** [comment]
Suspect the only option to avoid this is to programmatically unselect the entries for which the Color has been changed. This however will probably make this inconsistent with other behaviour.

**Comment by tactilis** [comment]
This is one of my biggest bugbears with MMEX.  

I colour transactions (using Ctrl+1 .. Ctrl+7) as a way of highlighting those that I need to follow-up in different ways. The different user colours signify different things to me.

From a UI and workflow point of view, it is very frustrating that transactions completely lose their User Colour when they are selected. This also occurs for non-selected transactions that you simply hover the mouse over them! When this happens, I lose the visual information that the colour represents.

I would like to request that the row retains its colour when it is clicked on (or is hovered over*), maybe with a bolder outline if that's possible in the wx control to indicate selection (see the way that coloured cells are border-highlighted in Excel), or that some part of the row (maybe the leftmost displayed column) retains the user highlight colour.

* Why do we even need a colour change for hover-over? Cells (or rows/columns) don't change colour or their border in Excel when all you do is move the mouse over them. You can see perfectly well where the mouse cursor is, so what additional information is the hover-over colour change giving in MMEX? If we removed this, then all that would need to be handled is the colour change on row selection.

**Comment by whalley** [comment]
One point of note: Need to also consider those who navigate using keyboard and not just mouse.

**Comment by tactilis** [comment]
> Need to also consider those who navigate using keyboard and not just mouse.

Good point Mark. I tend to use keyboard more than mouse when moving to adjacent (or nearly adjacent transactions).

Assuming it is possible with the wx control used, setting a border colour for the row (like in Excel) to indicate selection would still work OK with keyboard navigation. The aim is to avoid replacing the User Colour with a 'selected row' colour.

By the way, I find the worst aspect of the mouse 'hover over' colour is when, if I am using keyboard navigation, the mouse pointer is left somewhere over the transaction list. The transaction that happens to be currently under the pointer will lose its User Colour, even though it has nothing to do with where I have navigated to using the keyboard.

**Comment by PMaff** [comment]
One way would be that the color shown is a mixture of selection color and changed color but I do not
know if wxWidget is capable doing so and if this is consistent with other GUI standards.
