### ISSUE TITLE
mmParseDisplayStringToDate() is broken

### ISSUE THREAD

**Issue by jeffjl74** [moneymanagerex/moneymanagerex#397]
Commit c5972a3, util.cpp line 176 added an "&" to the return assignment for date_formats_regex().at(). This does not work. The new "&regex" is not a date format regular expression string and the following pattern matching gets random results. (I am building with Visual Studio Express 2013.)

**Comment by stef145g** [comment]
I see the problem and have committed a fix to master branch.
Please recheck.

**Comment by jeffjl74** [comment]
The fix works. Thanks.
