### ISSUE TITLE
Windows 10 - Windows Security Scan is reporting version 1.5.9 (Window 64 bit) as Spursint.Q!cl Trojan

### ISSUE THREAD

**Issue by wbwiltshire** [moneymanagerex/moneymanagerex#3977]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Windows 10 - Windows Security Scan is reporting version 1.5.9 (Window 64 bit) as Spursint.Q!cl Trojan

Please describe your issue with details.
Downloaded latest release (mmex-1.5.9-win64.exe) from Github release repo and received Virus message from Windows Defender (Windows Security).  It says the file is Trojan:Win32/Spursint.Q!cl.  Please advise.

Add screenshot or other files if needed.
![image](https://user-images.githubusercontent.com/6923693/140569908-3aaf3f37-cac1-46b7-8a13-5efff91cd427.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Even if the files are downloaded from this source?
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.5.9

**Comment by wbwiltshire** [comment]
Yes, as indicated in the original bug report.  I downloaded from the Github release repo, which is where you link points.

**Comment by renato-mmex** [comment]
I have checked 1.5.9 as well as 1.5.10-Beta.1 with Defender dated 05/11/2021 21:14 and there is no warning.

**Comment by whalley** [comment]
I can't reproduce on Win 11 ARM-64.

**Comment by Dandy64** [comment]
I have checked it with Avira - clean.

**Comment by wbwiltshire** [comment]
My Windows Security is up to date.  I tried to download again from the link provided above (see screen shots).

![image](https://user-images.githubusercontent.com/6923693/140589739-68398d2e-4148-458d-93f2-d0a1563b0891.png)
![image](https://user-images.githubusercontent.com/6923693/140589880-4dcbe528-59c9-43fc-be53-8fa4d8fa3c54.png)
![image](https://user-images.githubusercontent.com/6923693/140589924-285a56b3-a853-4ca6-a1ba-4122e5d67b4e.png)

**Comment by tactilis** [comment]
A quick search shows that there are lots of false positive reports of Spursint.F!cl / Spursint.Q!cl. 

What do you get if you submit the file for analysis here https://www.microsoft.com/en-us/wdsi/filesubmission.

In the meantime, you could download and us the portable version of MMEX 1.5.9

**Comment by wbwiltshire** [comment]
Thank you.  The above was informative, but ultimately unhelpful.  I submitted the file to Microsoft via the link above and received the following response (apparently there are 1209 files in the file/package):

**Submission details
mmex-1.5.9-win64.exe
Submission ID: d3668461-6db7-4072-a0da-312136677d4dStatus: 
RejectedSubmitted by: warren@seagullconsulting.biz
Submitted: Nov 7, 2021 10:18:02 AMUser Opinion: Incorrect detection
Analyst comments:

Your submission has been refused due to too many files in your submission.

This can occur if you included too many files or if the container file you submitted explodes to too many children. If your file still requires analysis, please resubmit with fewer files or just the file that needs analysis.

Thank you for contacting Microsoft.**
