### ISSUE TITLE
Problems with qif file imports

### ISSUE THREAD

**Issue by Paomare** [moneymanagerex/moneymanagerex#3979]
MMEX version:
 - [x] 1.5.x

Operating System:
 - [x] Windows
 - [x] Mac OSX
 

# Description of the bug

I have used the Microsoft Money 2000 program to date to manage expenses.
When I import the QIF file from the old program, everything works with payees and banks, but the amounts are shifted with decimals (ES: a movement of 1.00 becomes 100.00).
Can anything be done to solve the problem?
If someone could answer in Italian it would be easier to understand.
Thanks

**Comment by vomikan** [comment]
Could you, please, choose the same Decimal char from the dropdown menu as in the QIF file values.
![image](https://user-images.githubusercontent.com/6836805/140777578-8ab9801e-7170-4f30-aff4-186f7cdc1f46.png)

**Comment by whalley** [comment]
@Paomare Do you still have this issue?

**Comment by Paomare** [comment]
No tahnks
_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)_/)

Paolo Marendon
Via dell'Ancora, 69
48122 Punta Marina Terme (RA)
ITALY


Il giorno mer 20 apr 2022 alle ore 09:42 Mark Whalley <
***@***.***> ha scritto:
