### ISSUE TITLE
1.5.10-Beta.1 crashes with warnings about missing themes

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#3980]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

See 
https://forum.moneymanagerex.org/viewtopic.php?p=22555#p22555

Same issue for stable 1.5.9

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. build 1.5.10-Beta.1
2. start ../src/mmex

Expected result:
3. mmex starts normal

Actual result:
3. Warning dialogs appear about missing themes
4. mmex core dumps

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3853

**Comment by vomikan** [comment]
@PMaff  Is the bug still exists?

**Comment by PMaff** [comment]
> @PMaff Is the bug still exists?

I did not compile 1.5.9 or 1.5.10-Beta.1 since then. Funny thing: with the same setting I was able to compile 1.5.6. 
See: https://forum.moneymanagerex.org/viewtopic.php?f=25&t=10467
I also
"backported" the -Werror=useless-cast fix from 1.5.7 to 1.5.6 so currently I have a running 1.5.6 compiled on the same environment, where1.5.9 and 1.5.10-Beta.1 failed.

**Comment by PMaff** [comment]
> @PMaff Is the bug still exists?

Took some time to compile the newest version, compiling is all ok as before.


-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.10-Beta.2
-- Commit         : 054a4951a (2021-11-09)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 4.15.0-162-generic
-- Ubuntu 18.04 'bionic'
-- CMake 3.10.2
-- GNU Make 4.1
-- ccache 3.4.1
-- GNU 7.5.0
-- wxWidgets 3.1.5
-- wxSQLite3 4.6.0
-- Lua 5.3.3
-- curl 7.58.0
-- gettext 0.19.8.1
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done

Same error warning messages as described here:
https://forum.moneymanagerex.org/viewtopic.php?f=25&t=10511

...V15_10/moneymanagerex/build$ ./src/mmex
Gtk-Message: 00:41:10.257: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:32.792: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:35.149: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:36.268: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:36.978: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:38.533: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 00:41:39.876: GtkDialog mapped without a transient parent. This is discouraged.
Aborted (core dumped)

Bug also exists in 1.5.10-Beta.2 .

**Comment by PMaff** [comment]
Regarding "needs more info" : do you need more information from me?

**Comment by PMaff** [comment]
I was checking out 1.5.11-Beta.1 today. Compiling was ok.
When I ran mmex with 
build$ ../src/mmex 
it core dumped again.

The debug output 
[...]
Debug: Scanning [/home/[...]MMEX/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [default]
[...]
showed me a way so I simply copied
../_CPack_Packages/Linux/DEB/mmex-1.5.11-Beta.1-Linux/usr/share 
to
/home/[...]/MMEX/V15_11/moneymanagerex/src/.

and voila: I was able to run:
moneymanagerex/build$ ../src/mmex

Afterwards installing 
moneymanagerex/mmex_1.5.11-Beta.1-1~bionic_amd64.deb
was ok.
So I do have a running 1.5.11-Beta.1 now.

**Comment by vomikan** [comment]
@whalley , could you investigate the CMAKE file?
It seems the problem is hiding there.

**Comment by PMaff** [comment]
I had a look at src/images_list.cpp:
there you have 
bool processThemes()
returning a boolean which seems to be ignored in
void reverttoDefaultTheme()
reverttoDefaultTheme() is also called in 
void LoadTheme() - so if nothing is found that is as far as I can see the way to the core dump.

I am not a pro with cmake, but in CMakeLists.txt  I see
[...]
else()
    set(MMEX_DOC_DIR share/doc/mmex)
    set(MMEX_RES_DIR share/mmex/res)
if it is not APPLE or WIN32, which seems to be relative to the directory, where mmex is called.
This would fit to the
src/share/mmex/res/themes
above when calling
build$ ../src/mmex

**Comment by whalley** [comment]
I'm not that familiar with the Linux build structure, but if the files are there under the `_CPack_Packages` directory then it seems that the makefile is working and building the files. I would have expected an mmex executable to be under there also rather than  `../src/mmex` ... At least that is how it works under MacOS.

@PMaff Is there an mmex executable under `_CPack_Packages/....` that you can execute?

**Comment by PMaff** [comment]
> I'm not that familiar with the Linux build structure, but if the files are there under the `_CPack_Packages` directory then it seems that the makefile is working and building the files. I would have expected an mmex executable to be under there also rather than `../src/mmex` ... At least that is how it works under MacOS.
> 
> @PMaff Is there an mmex executable under `_CPack_Packages/....` that you can execute?

There are 2 mmex binaries

one in
`_CPack_Packages/Linux/DEB/mmex-1.5.11-Beta.1-Linux/usr/bin  15185800 bytes`
and one in
`moneymanagerex/src   19828568 bytes`

Both can be executed now but If I remove the share in moneymanagerex/src only the one in
_CPack_Packages/Linux/DEB/mmex-1.5.11-Beta.1-Linux/usr/bin
can be executed and the other one gives the known warnings and core dumps.

**Comment by whalley** [comment]
Yes the packaged version under `_CPack_Packages` is the one I would have naturally used as it has the resources alongside it.

**Comment by PMaff** [comment]
Yep the directory structure there seems to be the better one.
Although mmex should not core dump if it does not find the themes. ;-)

**Comment by PMaff** [comment]
This is the output when running moneymanagerex/src$ ./mmex :

```
moneymanagerex/src$ ./mmex 
21:56:26: Debug: Adding duplicate image handler for 'PNG file'
Gtk-Message: 21:56:26.927: GtkDialog mapped without a transient parent. This is discouraged.
21:56:29: Debug: 2020-11-26 - 2021-09-19
21:56:29: Debug: 2020-11-26 - 2021-06-23
21:56:29: Debug: 2020-11-26 - 2020-10-30
21:56:29: Debug: 2020-11-26 - 2020-05-22
21:56:29: Debug: 2020-11-26 - 2020-05-13
21:56:29: Debug: 2020-11-26 - 2020-05-05
21:56:29: Debug: 2020-11-26 - 2020-04-13
21:56:29: Debug: 2020-11-26 - 2020-04-11
21:56:29: Debug: 2020-11-26 - 2020-03-10
21:56:29: Debug: 2020-11-26 - 2019-10-19
21:56:29: Debug: getNewsRSS: New articles = 2
21:56:29: Debug: -- Metadata Phase?: YES
21:56:29: Debug: Scanning [/home/[...]/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [colorful]
21:56:29: Debug: -- Metadata Phase?: YES
21:56:29: Debug: Scanning [/home/pmaff/.mmex/themes/] for Theme [colorful]
Gtk-Message: 21:56:29.034: GtkDialog mapped without a transient parent. This is discouraged.
21:56:30: Debug: -- Metadata Phase?: YES
21:56:30: Debug: Scanning [/home/[...]/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [default]
21:56:30: Debug: -- Metadata Phase?: NO
21:56:30: Debug: Scanning [/home/[...]/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [default]
Gtk-Message: 21:56:30.765: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 21:56:31.411: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 21:56:33.659: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 21:56:34.385: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 21:56:35.060: GtkDialog mapped without a transient parent. This is discouraged.
21:56:35: Debug: -- Metadata Phase?: YES
21:56:35: Debug: Scanning [/home/[...]/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [default]
21:56:35: Debug: -- Metadata Phase?: NO
21:56:35: Debug: Scanning [/home/[...]/V15_11/moneymanagerex/src/share/mmex/res/themes] for Theme [default]
Aborted (core dumped)
```
In the working version I switched to the colorful theme.
After the src/mmex version crashes, the working version also has default theme again.

**Comment by PMaff** [comment]
`/tmp/mmex_dbgrpt-10762-20211126T215635/mmex.xml `shows:

[...]
```
  <stack>
    <frame level="0" function="mmGUIApp::ReportFatalException(wxDebugReport::Context)" offset="0x11c" address="0x55f758d76aa4" module="./mmex"/>
    <frame level="1" function="mmGUIApp::OnFatalException()" offset="0x1d" address="0x55f758d770a5" module="./mmex"/>
    <frame level="2" offset="0x1bcd2c" address="0x7faf89298d2c" module="/usr/local/lib/libwx_baseu-3.1.so.5"/>
    <frame level="3" offset="0x12980" address="0x7faf88155980" module="/lib/x86_64-linux-gnu/libpthread.so.0"/>
    <frame level="4" function="wxObject::wxObject(wxObject const&amp;)" offset="0x22" address="0x55f758bb0f64" module="./mmex"/>
    <frame level="5" function="wxGDIObject::wxGDIObject(wxGDIObject const&amp;)" offset="0x23" address="0x55f758bc41cd" module="./mmex"/>
    <frame level="6" function="wxBitmapBase::wxBitmapBase(wxBitmapBase const&amp;)" offset="0x23" address="0x55f758d0c667" module="./mmex"/>
    <frame level="7" function="wxBitmap::wxBitmap(wxBitmap const&amp;)" offset="0x23" address="0x55f758d0c69b" module="./mmex"/>
    <frame level="8" function="mmBitmap(int, int)" offset="0x13c" address="0x55f758d097ea" module="./mmex"/>
    <frame level="9" offset="0x66a56f" address="0x55f758d0456f" module="./mmex"/>
    <frame level="10" function="navtree_images_list()" offset="0x69" address="0x55f758d057df" module="./mmex"/>
    <frame level="11" function="mmGUIFrame::createControls()" offset="0x18f" address="0x55f758d810c1" module="./mmex"/>
    <frame level="12" function="mmGUIFrame::mmGUIFrame(mmGUIApp*, wxString const&amp;, wxPoint const&amp;, wxSize const&amp;)" offset="0x485" address="0x55f758d7d9fb" module="./mmex"/>
    <frame level="13" function="OnInitImpl(mmGUIApp*)" offset="0xd75" address="0x55f758d77e1d" module="./mmex"/>
    <frame level="14" function="mmGUIApp::OnInit()" offset="0x4d" address="0x55f758d78319" module="./mmex"/>
    <frame level="15" function="wxAppConsoleBase::CallOnInit()" offset="0x25" address="0x55f758d79199" module="./mmex"/>
    <frame level="16" function="wxEntry(int&amp;, wchar_t**)" offset="0x92" address="0x7faf891d8932" module="/usr/local/lib/libwx_baseu-3.1.so.5"/>
    <frame level="17" function="main" offset="0x22" address="0x55f758d75c08" module="./mmex"/>
    <frame level="18" function="__libc_start_main" offset="0xe7" address="0x7faf87d73bf7" module="/lib/x86_64-linux-gnu/libc.so.6"/>
    <frame level="19" function="_start" offset="0x2a" address="0x55f758bad15a" module="./mmex"/>
  </stack>
```

**Comment by whalley** [comment]
The default theme is an essential file and without this it cannot run. No distribution should be without it, so the only reason it should fail is if some corruption has occurred. Yes, we could protect against all potential corruptions and maybe we should buy effort is small. We can add to backlog.

**Comment by whalley** [comment]
Should now exit gracefully if no workable theme is found, even if the default theme is broken.

**Comment by PMaff** [comment]
> Should now exit gracefully if no workable theme is found, even if the default theme is broken.

Tested with version 1.5.12 stable by simply calling 
moneymanagerex/build$ ../src/mmex

Exits gracefully with:
![exitsgraceful](https://user-images.githubusercontent.com/93879362/151719988-7ef24f44-4028-4571-b841-f91683fe3371.jpg)

**Comment by PMaff** [comment]
Would it help if I put my deb package for Ubuntu 18.04 LTS 
mmex_1.5.12-1~bionic_amd64.deb
here:
https://github.com/moneymanagerex/moneymanagerex/releases

I can try stable 1.5.12 also on SuSE Leap 15.2 .

**Comment by whalley** [comment]
@PMaff  yes, some workable Linux builds for the latest release would be very useful and I'm sure much appreciated by other Linux users

**Comment by PMaff** [comment]
> @PMaff yes, some workable Linux builds for the latest release would be very useful and I'm sure much appreciated by other Linux users

How can I put it there?
Is there some upload?
Shall I send it to you?

**Comment by whalley** [comment]
@PMaff Not sure about access rights to that. You can upload [here](https://1drv.ms/u/s!AkTX0ojXg_ughI9NT6TE15lmpbjlrg?e=4HPNJW) for now.

**Comment by PMaff** [comment]
I cannot upload there without having an account, which is of course missing. ;-)

**Comment by whalley** [comment]
If you select "Sign In options" you can login using your GitHub ID.

**Comment by PMaff** [comment]
Ok I was able to upload the mmex_1.5.12-1~bionic_amd64.deb . I will now try 1.5.12 stable on SuSE Leap 15.2 , but I have to update a few packages on the old machine before that. ;-)

**Comment by whalley** [comment]
Great. Have upload the mmex_1.5.12-1~bionic_amd64.deb asset.

**Comment by PMaff** [comment]
I cannot test all the features of course so one of those Ubuntu 18.04 users, that use more features than I do, has to test .
Maybe mark it as privately build or similar, because not everybody will like to install a deb from unknown source. ;-)

**Comment by PMaff** [comment]
Ok the SuSE Leap 15.2 version of mmex 1.5.12 stable is ready.
There are 2 issues when installing with
zypper in ./mmex-1.5.12-1.x86_64.rpm
:
a) the SuSE package system does not know about my self compiled wxWidgets 3.1.5
so it complains:
"Problem: nothing provides 'libwx_baseu-3.1.so.5()(64bit)' needed by the to be installed mmex-1.5.12-1.x86_64
 Solution 1: do not install mmex-1.5.12-1.x86_64
 Solution 2: break mmex-1.5.12-1.x86_64 by ignoring some of its dependencies"

I ignore this with '2' since I know that wxWidget 3.1.5 is there.

b) it complains about the package not being signed:
"mmex-1.5.12-1.x86_64.rpm:
    Package is not signed!

mmex-1.5.12-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i"

   I also ignore that.
   Up to now I never had problems this way.

**Comment by PMaff** [comment]
I also uploaded 
mmex-1.5.12-1.x86_64.rpm
for OpenSuSE Leap 15.2 .

Since OpenSuSE leap 15.2 seems to be end of life, I will have to upgrade to 15.3 or Tumbleweed. I will take a look at mmex then, if this is finished.

**Comment by whalley** [comment]
Please track all further discussion on these builds against #4154 that is pinned to the issue list for now.
