### ISSUE TITLE
Account balances using red font

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3991]
![image](https://user-images.githubusercontent.com/6836805/141118810-1df42c8a-463c-445f-9d2c-6ae2860a6389.png)

**Comment by whalley** [comment]
A good request, but I don't think wxListCtrl supports the ability to change the font colour of an individual column. You can change the complete row but not an individual column of a row. This would need a bit of thought :-)

**Comment by Dandy64** [comment]
Maybe this is useful, I dunno...
https://discuss.wxpython.org/t/changing-the-font-colour-of-a-selected-item-in-the-checklistctrl/26437

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?t=30658
