### ISSUE TITLE
Incorrect balances being computed

### ISSUE THREAD

**Issue by hayeswt** [moneymanagerex/moneymanagerex#3993]
Version 1.5.5 See below.  I first noticed this after installing v1.5.9.  I rolled back to v1.5.5 and still noted this issue.  In the attached image, use a calculator to run through the deductions on the left, starting with the first balance on the right (e.g. 13,785.27 - 42.47 = 13,742.80, **not** 12084.05 as calculated by the application).  Any fix will require the recalculation of all transactions from the beginning of the database file.  Also noted dates were not being sorted correctly (ref 2nd screen shot)

![Capture](https://user-images.githubusercontent.com/86615874/141204246-2bb86a5d-9a37-401f-ab14-872a5e2b1556.PNG
![Capture2](https://user-images.githubusercontent.com/86615874/141205584-1daa2e6a-086d-4f96-bdf6-c5cadcb7a18d.PNG)
)

**Comment by whalley** [comment]
The line-by-line balance is calculated based on date order then transaction ID if dates are the same.

When sorting is not by date the line-by-line balance will **NOT** be re-calculated, it will continue to represent the balance on that date.

Is this cause of your query?

**Comment by hayeswt** [comment]
Hi Mark.

I think I understand what I was seeing now.  I was watching for the balance to recalculate regardless of which column is serving as the sort base.  I can also see that what I was watching for isn't practical at all.  Thanks for the info, and I'll close this ticket.

Bill
