### ISSUE TITLE
When Re-allocating an Existing Payee the search bar is stuck on one character

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#3996]
MMEX version:
 - [X] 1.5.9

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 10

# Description of the bug
Re-allocate Existing Payee, the second drop box only allows one alpha character, i denies and second or third character to search. Annoying!

Re-allocating an existing Payee, the second window opened stops any searching after second character. 
Relocate selection good. The 'To' box refuses to allow more than one character searching.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Click Person Icon (Show Organize Payees Dialog)
2. Pick a Payee
3. Right mouse click Relocate Payee
4.  to drop box only allows one character before locking on the first instance of payee. (could be long way from what you want)

…

Expected result:
more characters to search on narrowing the correct payee

Actual result:
Fiddly mouse scrolling to get to intended payee

# Additional information

If you have a backtrace for a crash or a warning, paste it here
![Relocate](https://user-images.githubusercontent.com/14268231/141434780-337cccf6-3003-46a9-9ab7-d00674ec3ced.JPG)
.

**Comment by vomikan** [comment]
@whalley , could you investigate this dialog box?
There is definitely a bug specific to the MAC system. The right and left widgets are different. This was done a long time ago within the framework of the case #1116 (or similar).

**Comment by 2BeeOrNot** [comment]
No, not a macOS bug. Autocomplete doesn't work at all for payee relocation, Relocate: or To:. Like #3988 

I can confirm the OP's issue on Windows 7.

And another strange one. I have three payees that start with 'Sc' and three that start with 'Af'. After pressing 'S' pressing 'c' closes the Relocate Payee Dialog window. But pressing 'A' and then pressing 'f' does nothing.

After pressing 'S' the first match is highlighted in the text box. Deleting the match character by character to the 'S' gets me popup of all the 'S' matches, five in my case.

**Comment by whalley** [comment]
Yes, I can see what the windows bug is and have identified simple fix. Will also look to add 'AutoComplete' functionality for macOS like the other dialogs :-)

**Comment by SJK55** [comment]
Thank you. That works fine now!
