### ISSUE TITLE
Right to Left for RTL languages

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#3997]
> Home page elements should also be RTL oriented. 
> I'm quite sure it was ok on previous version 1.5.8 as i remember...
Also, it would be nice to have on the main screen monitory numbers separated with comma. It looks like the settings in currency managed do not take effect, so  I would expect that the separator will be at least driven from my system's locale. 
![mmex home page no thousands separator](https://user-images.githubusercontent.com/7680483/141497420-98cb0b79-e595-4434-a78e-020b4834b993.png)
![MMEX currency manager, 000 separator is there but no effect](https://user-images.githubusercontent.com/7680483/141653367-4d290c9f-f02d-4b0a-a3dc-720d21c8061d.png)

**I love the new look and all the great job you did working on this package!**

<hr>Version: 1.5.10-Beta.2 64-bit<br>
 • Build: נוב 12 2021 17:25:22<br>
 • db 7 •  (aes128cbc)<br>
 • git e79418800 (2021-11-12)<br>
 • master<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxGTK 3.24)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.3<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 ( libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.21.0-rc3<br>
 • GNU Make 4.2.1<br>
 • GCC 9.3.0 • Linuxmint 20.2

**Comment by avma** [comment]
![mmex home page no thousands separator](https://user-images.githubusercontent.com/7680483/141496718-2cabff96-49ef-40d5-bcdf-0a1b997a8319.png)

**Comment by vomikan** [comment]
Related issue #3925

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3999

**Comment by avma** [comment]
Do you think uninstalling and rebuilding might help?

**Comment by vomikan** [comment]
I think it won't help. But you will definitely get a number of improvements that have already been developed.

Remove us_US.UTF8 from the settings. At the same time, the currency settings will have to be used.

**Comment by avma** [comment]
I'll give it a go and let you know if it is any better...
