### ISSUE TITLE
Thousands separator is missing

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#3999]
> The thousands separator is missing. Although it is present in the currency setting dialog (see screenshot) it is not showing on the reports or on the transaction entry screen. 
![MMEX currency manager, 000 separator is there but no effect](https://user-images.githubusercontent.com/7680483/141674011-bd3c272b-e416-4c73-a0d7-855e88eb3ee8.png)
![mmex transaction entry no 000,0 separator](https://user-images.githubusercontent.com/7680483/141674096-0c93ce14-d3e8-4308-afc2-8e093f6a8045.png)

<hr>Version: 1.5.10-Beta.2 64-bit<br>
 • Build: נוב 12 2021 17:25:22<br>
 • db 7 •  (aes128cbc)<br>
 • git e79418800 (2021-11-12)<br>
 • master<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxGTK 3.24)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.3<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 ( libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.21.0-rc3<br>
 • GNU Make 4.2.1<br>
 • GCC 9.3.0 • Linuxmint 20.2

**Comment by vomikan** [comment]
Related issue #3925

**Comment by vomikan** [comment]
Could you, please, app settings?
![](https://user-images.githubusercontent.com/80578702/138025406-a037e93f-2568-4b04-96a6-28d802787f3b.png)

**Comment by avma** [comment]
Here it is, I logged out and in again, but nothing really changed... 
![mmexapp setting en_US](https://user-images.githubusercontent.com/7680483/141821248-762faf01-46bc-470c-8d11-2b57d0a94041.png)

**Comment by vomikan** [comment]
Could you delete the en_US value (leave the locale field empty)?

**Comment by avma** [comment]
I've done all that, it does not have any effect on the amounts... although in the example on the setting dialog it looks ok (see marked '1', but on the reports it still does not show separators, see marked '2')
![mmex app setting WITH en_US](https://user-images.githubusercontent.com/7680483/141954815-888d6b89-f467-4fa5-a0c9-1c2f6cf1e3cc.png)

**Comment by vomikan** [comment]
I have no explanation as to why it might work this way.

In general it's working

![image](https://user-images.githubusercontent.com/6836805/142266251-a5d15e58-3eba-4fa5-8196-d59456e2df74.png)

**Comment by n-stein** [comment]
I think this has been resolved by #6074.

**Comment by whalley** [comment]
@avma  Can you please confirm if this was fixed in the v1.7.0 release.
