### ISSUE TITLE
I've updated to 1.5.9 but a problem still remain.

### ISSUE THREAD

**Issue by Hintsmth** [moneymanagerex/moneymanagerex#4006]
I've updated to 1.5.9 but a problem still remain. 
RUB is my main currency.
![1](https://user-images.githubusercontent.com/33121649/141651950-54931c39-7377-456a-a7f5-26fa3ebc6f21.png)

_Originally posted by @Hintsmth in https://github.com/moneymanagerex/moneymanagerex/issues/3933#issuecomment-968097894_

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2334
