### ISSUE TITLE
Add Optional Display of Notes Field to Upcoming Transactions

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4007]
I recently updated from 1.5.1 to 1.5.9, and I like the new "Account/Payee" display on the Upcoming Transactions section of the home page. Having both fields helps remind me what a transaction is for, without having to go directly to that section. What would also be helpful would be the option of including the "Notes" field in that same display. I have many transactions that are between the same combination of Accounts and Payees that even this latest update doesn't always prevent me from clicking on the Recurring Transactions link to figure out what a particular upcoming transaction is for.

I think this should definitely be optional, since some people may not have the screen width/resolution to comfortable display one more field in that section (fortunately for me, I have a pretty wide screen). Even if it is optional, it's probably necessary to truncate that field's Home Page display to a fixed number of characters (unless you add the ability to slide the width of the various fields, but I suspect that could really complicate the update).

Any chance of adding this field to the display?

https://forum.moneymanagerex.org/viewtopic.php?f=8&t=10519

**Comment by whalley** [comment]
I suggest following as display....

If note exists it will be displayed under the Payee in italics, otherwise display will be as existing.

![CleanShot 2021-11-19 at 20 18 33](https://user-images.githubusercontent.com/487345/142686480-e2212dbb-2bc0-4566-96b3-fb3231330602.png)

**Comment by vomikan** [comment]
Ideas 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_tooltip
https://www.accessibility-developer-guide.com/examples/widgets/tooltips/

**Comment by whalley** [comment]
For now I truncated any notes that are > 150 chars. We could add the tooltip option to the truncated version and limit to one line but will will require a bit of fiddling with the HTML styles to implement non overflow. I'm not convinced of teh benefit.
