### ISSUE TITLE
Transaction report ->Presentations options

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4009]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Presentation options are not saved. It is necessary to set them again for every transaction report execution.
![image](https://user-images.githubusercontent.com/83161661/142760371-c0227c59-9fb7-4214-8786-9596531bae6e.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Opened an existing and saved Transaction report
2. Choose presentation options
3. Clicked at Save button

…

**Expected result:**
1. The report shows correct numbers and presents all the data according to chosen presentation options.
2. The report is saved and next time all the chosen options should be set by default.

**Actual result:**
1. Everything is correct.
2. The report is saved besides Presentation options. It is necessary to set them every time the report is executed.
# Additional information
This is a very cool feature - thanks!

**Comment by whalley** [comment]
Yes, this is the behaviour at present. If there is consensus to save these options then we can do it. 

I personally feel it would be useful to save these alongside the filter options. Any objections?
