### ISSUE TITLE
Memory VFS already contains file 'Transaction-Withdrawals.grm'!

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4014]
![image](https://user-images.githubusercontent.com/6836805/142907804-30ae8867-0f5d-4c36-96ff-9fb6114ff330.png)

**Comment by whalley** [comment]
Don't think we need these in VFS anyway... Should be included in this exclusion code?

https://github.com/moneymanagerex/moneymanagerex/blob/652d748991e12c37daa7674e064b2f0b3cf3c99e/src/mmex.cpp#L274

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3961
