### ISSUE TITLE
Currency exchange rates - currency values history

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4020]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I wanted to update currency values history just for my transactions, but I received updates for all the dates.

1. Opened Currency Dialog screen
![image](https://user-images.githubusercontent.com/83161661/142998483-5e2aa076-bf7a-43c5-8070-09c0ea3cbc4a.png)
 
2. Pressed Download Values History icon
![image](https://user-images.githubusercontent.com/83161661/142998696-8b9dc594-d798-46c4-a8dc-173038afa04e.png)

3. Pressed No option
![image](https://user-images.githubusercontent.com/83161661/142999199-09b04334-b3a6-457e-8312-3099c7b154f0.png)

4. I have received **all** values for **all** dates
![image](https://user-images.githubusercontent.com/83161661/142998902-6596fd1d-c98d-40c6-bd61-8fcafd82eb62.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

It looks like the Yes and No buttons execute the same action.

**Comment by vomikan** [comment]
It's ready for tests

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/41636339/job/6y7e63gsnfjlcnmx/artifacts
