### ISSUE TITLE
Budget categories research

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4023]
We can make similar links for categories for Budget Category Summary , which will redirect to the transaction category report.
![image](https://user-images.githubusercontent.com/6836805/143248695-480a748b-3914-42a3-b7b0-c66a14950037.png)

#3283

**Comment by vomikan** [comment]
Something is going wrang

![image](https://user-images.githubusercontent.com/6836805/143551906-bd9fa0f7-8432-4315-b2a1-f5deef4731a5.png)


![image](https://user-images.githubusercontent.com/6836805/143551939-5ddd6212-f614-4c76-83f8-cdd4348a9f74.png)

**Comment by whalley** [comment]
You have the "View / Budget Report: with Summaries" option turned off, I never even knew we had that option :-)

Will fix.

**Comment by vomikan** [comment]
It seems OK now.
