### ISSUE TITLE
Report graph causes app to freeze when window not 'Maximised'

### ISSUE THREAD

**Issue by jpweaving** [moneymanagerex/moneymanagerex#4025]
All versions for the last year or so have frozen when I make a change to the 'Daily' Transaction Report when the graph is shown and the window is not maximised. To use the graph feature, I have to remember to only use it with the window maximised. Once it crashes you are stuck with the report graph marked as 'Show', so the next time you try to open a report, the app freezes unless you maximise the window first.
This is in version Version: 1.5.10 64-bit and every version after 1.3.6-win64.
My system is Windows 10 Home, AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G  3.10 GHz,

**Comment by tactilis** [comment]
I can reproduce this.

However, I find that the app is not completely frozen - it just appears to hang for several seconds due, I think, to the amount of time it takes to recalculate or redraw the graph. While it is doing this, the Show/Hide dropdown is unresponsive.

If I have the graph shown in a non-maximized window, then just re-sizing the window can cause MMEX to appear to hang  for several seconds. Most of the time it does eventually recover - however, I did manage to get it to 'freeze' after resizing several times. MMEX was unresponsive and was using very high CPU. I had to kill the mmex.exe process to recover.

**Comment by whalley** [comment]
Maybe it is one we could look at optimising.

**Comment by whalley** [comment]
@jpweaving @tactilis Have disabled animations on the ApexCharts reports to see if this improves the performance. Can you please test latest build here: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/vob27lhe3kt3fa95/artifacts

If this improves things I can leave as-is or add an option for the user to enable the animations if they are happy with potential performance hit and want that little bit of elegance :-)

**Comment by whalley** [comment]
Actually I've tried on a Windows machine and it is still very sluggish and resizing windows causes hang ups (or long delays) @tactilis noted. So this does not fix it. Seems to be related to ApexCharts on the windows web engine being used.

**Comment by tactilis** [comment]
> So this does not fix it.

Agreed.

Max CPU and had to kill mmex.exe process

**Comment by whalley** [comment]
I'll upgrade to latest ApexCharts release (already started - there are a few tweaks needed) and have a few other things I can look at to optimise. Will need to wait for another week though due to availability.

**Comment by jpweaving** [comment]
I have isolated my hanging problem a little more, I have no programming
experience, so I have no solutions to offer.
MMEx only hangs and becomes completely unresponsive to any actions, when I
reduce the window to about 1/3 of the screen and then change the 'Specific
Account' with the Chart on 'Show'. The 1/3 screen view is so I can view my
online banking at the same time as MMEx, I can work around the problem by
'Maximising' the window before changing accounts. I love this software,
Thanks so much.
[image: 2021-11-26 (2).png]

**Comment by whalley** [comment]
@jpweaving Can you check if this issues still exists with v1.5.11

**Comment by jpweaving** [comment]
You fixed it. Brilliant.
I have tried to get it to play up, but it does whatever I ask it to do.
Changing window sizes and Specific accounts, no problem.
Thanks very much.

**Comment by jpweaving** [comment]
Awesome, thanks!
