### ISSUE TITLE
Bug QIF Import on master branch under ubuntu

### ISSUE THREAD

**Issue by loki36** [moneymanagerex/moneymanagerex#403]
Version of master branch crash on QIF import under ubuntu due to line 176 on file util.cpp
```
replace
const wxString& regex = date_formats_regex().at(mask);
by
const wxString regex = date_formats_regex().at(mask);

```

**Comment by guanlisheng** [comment]
@loki36 , please send a pull request here
@vomikan please fix the remaining ones

**Comment by loki36** [comment]
Hi,

fix(QIF.import.ubuntu) #403 is already merge here in the master branch since Feb 28, 2015

**Comment by guanlisheng** [comment]
Thanks for the confirmation and i will close it right now.
