### ISSUE TITLE
fast payer search

### ISSUE THREAD

**Issue by wilrino** [moneymanagerex/moneymanagerex#4031]
As on the APP x Android, when creating a new transaction, it would be convenient to be able to select the payer also by typing a part of the name, as if using the * keyword * command.

Now a list box is used which shows payers in alphabetical order, if I don't remember exactly how I saved it I use the Android APP and then use the same name on the computer.

If it were possible, thank you very much!

**Comment by gianni5252** [comment]
........Ma questo già succede!!!!! Come tu stesso dichiari, nel secondo capoverso, si apre una "finestrella o casella "come tu la chiami con tutti i beneficiari ( se ci sono ) che_ iniziano solo con le lettere man mano digitate  ( e solo con quelle ) e non invece, come ho capito, con tutti i beneficiari presenti nella rubrica che nulla hanno a che fare con quanto digitato.

**Comment by gianni5252** [comment]
........Ma questo già succede!!!!! Come tu stesso dichiari, nel secondo capoverso, si apre una "finestrella o casella "come tu la chiami con tutti i beneficiari ( se ci sono ) che iniziano SOLO con quelle lettere man mano digitate   e non invece, come ho capito, con tutti i beneficiari presenti nella rubrica che nulla hanno a che fare con quanto digitato. Spero di essere stato chiaro. Ti saluto, Giovanni D.G.

**Comment by wilrino** [comment]
> ........Ma questo già succede!!!!! Come tu stesso dichiari, nel secondo capoverso, si apre una "finestrella o casella "come tu la chiami con tutti i beneficiari ( se ci sono ) che iniziano SOLO con quelle lettere man mano digitate e non invece, come ho capito, con tutti i beneficiari presenti nella rubrica che nulla hanno a che fare con quanto digitato. Spero di essere stato chiaro. Ti saluto, Giovanni D.G.

Ciao Giovanni, 
grazie della risposta. 
Forse non mi sono spiegato bene, faccio un esempio.
Se tra i destinatari ho salvato MARIO ROSSI e per cercarlo digito ROSSI non mi esce... ovviamente esce se digito MARIO.
Mentre sull'APP Android se digito ROSSI mi appare perchè vengono cercati i beneficiari che "contengono" la parola cercata (Rossi) e non che iniziano per quella parola.

IN ENGLISH:
Hi John,
thanks for your answer.
Perhaps I have not explained myself well, I give an example.
If I have saved MARIO ROSSI among the recipients and to search for him I type ROSSI it does not come out ... obviously it comes out if I type MARIO.
While on the Android APP, if I type ROSSI, it appears to me because the beneficiaries who "contain" the searched word (Rossi) and not who begin with that word are searched for.

**Comment by vomikan** [comment]
On the Windows platform, you can press Alt+down arrow. The full list of payees will appear.
If you enter the first letter of the name, a list will also appear.

If you can't remember any particular recipient, first enter the Organize Payee dialog.
![image](https://user-images.githubusercontent.com/6836805/152421284-d7d8b83d-9c8e-475b-8ccd-6e22c60d16c5.png)

I suggest doing nothing on this application.

**Comment by 2BeeOrNot** [comment]
When entering a transaction *rossi will find "Mario Rossi" and "Rossi, Mario". No need to search in organize payees. This also works in Organize Payees.

![Untitled](https://user-images.githubusercontent.com/63317977/152454928-8484f87d-dc5c-4b52-994f-c43a7307431f.jpg)

**Comment by vomikan** [comment]
> When entering a transaction *rossi will find "Mario Rossi" and "Rossi, Mario". No need to search in organize payees. This also works in Organize Payees.
> 
> ![Untitled](https://user-images.githubusercontent.com/63317977/152454928-8484f87d-dc5c-4b52-994f-c43a7307431f.jpg)

@2BeeOrNot it does not working for me (on Windows).

**Comment by 2BeeOrNot** [comment]
You're right. I tried on my old Windows 7 PC and it doesn't work when entering a new transaction. It does work on macOS.

**Comment by wilrino** [comment]
> When entering a transaction *rossi will find "Mario Rossi" and "Rossi, Mario". No need to search in organize payees. This also works in Organize Payees.
> 
> ![Untitled](https://user-images.githubusercontent.com/63317977/152454928-8484f87d-dc5c-4b52-994f-c43a7307431f.jpg)

That's right, it would be more comfortable! (maybe even without having to type * as it happens on the app, but even with the * it is more comfortable than now)
But with windows 10 it doesn't work 😅

Yes, the alternative is to look for the payer in the organizer, but it would be more convenient to search while entering the transaction 😉

**Comment by vomikan** [comment]
I have an idea. We can assign a call to the payers dialog using a keyboard shortcut (or pressing Enter when the field is empty). The payer found in the dialog will be substituted in the transaction dialog field.

**Comment by wilrino** [comment]
> 

Good idea Vomikan! Thank you so much for the excellent work
