### ISSUE TITLE
Program Crashes on Organize Payees or Organize Categories

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#4032]
# Description of the bug

MacOS - Program crashes on "Organize Payees" or "Organize Categories" before the dialog for those items opens.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Money Manager Ex
Version: 1.5.10 64-bit
• Build on Nov 23 2021 18:22:45
• Database version: 7 • (aes128cbc)
• Git commit: 42f2794b5 (2021-11-23)
• Git branch: v1.5.x
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxMac 10.15)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg v2.0.1
• libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.21.3
• GNU Make 3.81
• Clang Apple LLVM 13.0.0 (clang-1300.0.29.3)
Running on:
• macOS Catalina Version 10.15.7 (Build 19H1519)
• English (U.S.) (Western (Mac OS Roman))
• 1280x1024 32bit 72x72ppi

**Comment by whalley** [comment]
I cannot reproduce. Any chance of supplying a cutdown database that I can test.

**Comment by omalleypat** [comment]
> I cannot reproduce. Any chance of supplying a cutdown database that I can test.

Ok shoot. I just tested another smaller db and it worked ok so I think it is my database. I'll play with it. There are 1354 payees in the one that is crashing.

**Comment by omalleypat** [comment]
Still an issue on v1.5.11 with my db. I also confirmed that it doesn’t happen on windows v1.5.11.  I’ll post a redacted db.

**Comment by whalley** [comment]
> Still an issue on v1.5.11 with my db. I also confirmed that it doesn’t happen on windows v1.5.11. I’ll post a redacted db.

Thanks for the update. If you can get that redacted DB I can investigate what the Mac issue is then.

**Comment by omalleypat** [comment]
@whalley while working on redacting the db, I realized that it will actually pop open the organize payees dialog…it just took 1m20s to do so (with spinning ball and “application not responding”). I had always force quit before that long.

**Comment by omalleypat** [comment]
@whalley I think it is a performance issue with a large number of payees. I created a new MMEX database, when used SQL to add 1500 payees.
`
INSERT INTO PAYEE_V1 (PAYEEID, PAYEENAME, CATEGID, SUBCATEGID) VALUES ('1' , 'PAYEE0001', -1, -1);
INSERT INTO PAYEE_V1 (PAYEEID, PAYEENAME, CATEGID, SUBCATEGID) VALUES ('2' , 'PAYEE0002', -1, -1);
` etc...

and it takes > 1 minute to open the "Organize Payees" dialog. I've attached that db I created here. 
[lotsofpayees.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/7739913/lotsofpayees.mmb.zip)

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3238

**Comment by omalleypat** [comment]
Possibly similar/same issue when editing recurring transaction and clicking the "Payee" button which opens the "Organize Payees" dialog.

**Comment by whalley** [comment]
Seems as if wxDataViewListCtrl has performance issues when the number of items grows. Suspect the only way to fix this is to write the control.
https://trac.wxwidgets.org/ticket/19173

**Comment by whalley** [comment]
Can confirm it is the wxDataViewListCtrl, that is really sluggish. hHve made a change and it now loads almost instantly. Need to get the rest of the code to now work with this and will hopefully post fix in next day or so.
