### ISSUE TITLE
Budget setup - Amount summary

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4034]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

The summary of the Amount field is empty.

![image](https://user-images.githubusercontent.com/83161661/143920930-1ad9f498-1f19-4070-bf67-20aa7c045d31.png)

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
On a purple background is the sum of all subcategories for this category.
Therefore, it is possible to add up only expenses, but not planned expenses for different periods.

**Comment by Dandy64** [comment]
Version 1.55

![image](https://user-images.githubusercontent.com/83161661/144008039-848acdd7-08c1-4785-8a4b-1cc70f8744f7.png)

**Comment by Dandy64** [comment]
Sorry, you are right.
