### ISSUE TITLE
Cannot Backdate error correction entries into the database it turns deductions into deposits.

### ISSUE THREAD

**Issue by SniperViperReal** [moneymanagerex/moneymanagerex#4035]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
I keep 2 sets of books and forgot to make the entries for autopayments health insurance in July 5 July 2021 make Medicare extended and Prescription insurance corrections.  I entered the correct date for autopay deductions and the correct amount. MMEX makes the error correcting entry a deposit in the total instead of a deduction.  So I tried changing the date of the forgotten entries to todays date 11/30/21 and it processed the deduction and provided the correct new total amount.  As program stands deductions are counted as deposits if you try to make the date of transaction error entry prior to Todays date.  When I did this it added the deduction amount to the total balance instead of subtracting it.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
@SniperViperReal I can't quite follow what you have been doing here. Can you perhaps describe the steps to reproduce the issue with screenshots.

**Comment by whalley** [comment]
No further clarification received. @SniperViperReal feel free to add more detail and re-open.
