### ISSUE TITLE
Current year range has wrong periods in December

### ISSUE THREAD

**Issue by junkie765** [moneymanagerex/moneymanagerex#4036]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
On Monthly Income vs Expenses Report, when selecting Current year it shows the period as it is 2022. If I want to see the current year details, I have to select Last Year.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/54117504/144234349-b4142f5e-1f65-4988-815e-cedad7833e51.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/54117504/144234554-5c340e17-be62-4163-90da-dd734464f52d.png">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  go to reports
2.  Expand Income vs Expenses
3.  Click on Monthly
4.  Select Current Year (selects automatically 01.01.2022 to 31.12.2022) or Last Year (selects automatically (01.01.2021 to 31.12.2021)

Expected result:
Selecting Current year must show data for 2021
Selecting Last Year must show data for 2020
Actual result:
Current year shows data for 2022 (none obviously)
Last year shows data for 2021

**Comment by duedipicche** [comment]
I have the same problem, current financial year and current year do not match as of today 2nd December, current year shows data for 2022, current financial year shows data for 2021.

**Comment by junkie765** [comment]
> I have the same problem, current financial year and current year do not match as of today 2nd December, current year shows data for 2022, current financial year shows data for 2021.

Yes, now that you mentioned it, it was working couple of days ago. I haven't changed anything. Only added some new transactions.

**Comment by vomikan** [comment]
@whalley  
Probably, this bug manifests itself on the first day. Will this fix be the solution?

![image](https://user-images.githubusercontent.com/6836805/144257594-d7fc427a-d8e2-46ab-aa4c-72765bf6f58b.png)

**Comment by junkie765** [comment]
Same problem on report Categories->Summary and Income vs Expenses->Monthly

<img width="327" alt="image" src="https://user-images.githubusercontent.com/54117504/144435321-8024e1c6-551d-42de-99b0-aabaa40da420.png">

**Comment by whalley** [comment]
@vomikan Will have a look at this at weekend when I'm back in UK.

**Comment by vomikan** [comment]
Volunteers are required to check date ranges.

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/41751690/job/9fvo0p3c0kofp0pf/artifacts

**Comment by Cappuccinolace** [comment]
Beta version fixed the issue for me.

**Comment by vomikan** [comment]
This code requires additional investigation.
src/reports/categexp.cpp 
```
 //temp_date.setValidDate(mmDateRange::START);
    //temp_date.setValidDate(mmDateRange::END); 
```

**Comment by whalley** [comment]
> Volunteers are required to check date ranges.

@vomikan Seems to work fine from my initial review and testing. I guess the only material change (with the exception of the bug fix of course) is that the maximum start date is now limited to 28 days. The previously logic allowed it to be higher but restricted it if month had less days. E.g. you could have start date set to 30th of month (that work work for 11 months, but would revert to 28/29th in Feb). I personally have no issue with this and it simplifies the logic which gets my vote :-)

> This code requires additional investigation. src/reports/categexp.cpp:293
> 
> ```
>  //temp_date.setValidDate(mmDateRange::START);
>     //temp_date.setValidDate(mmDateRange::END); 
> ```
Yes, I think the `temp_date.findEndOfMonth();` works fine here
