### ISSUE TITLE
Show current year

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#4037]
MMEX version:
 - [x] 1.5.10
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Since today (2021-12-01) it shows all transactions of 2022 when I select "show current year"

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4036
