### ISSUE TITLE
stock for gold and other cannot download new pricess!

### ISSUE THREAD

**Issue by jcodl** [moneymanagerex/moneymanagerex#4041]
![image](https://user-images.githubusercontent.com/79454792/144526102-fe1c4538-5355-402b-91e5-3b42ccb845a8.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/144573706-ee762b34-133f-4f6e-9ae3-51dd648739df.png)

https://query1.finance.yahoo.com/v7/finance/quote?symbols=gc=f&fields=regularMarketPrice,currency,shortName
