### ISSUE TITLE
Update to ApexCharts 3.28.2

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4048]
# Description of the feature

Keep current with ApexCharts development

https://github.com/apexcharts/apexcharts.js/releases/tag/v3.31.0

**Comment by whalley** [comment]
Whilst v3.31.0 is the latest release it has an issue that manifests itself on the MMEX charting https://github.com/apexcharts/apexcharts.js/issues/2807.

So upgrading to v3.30.0

**Comment by vomikan** [comment]
Something is going wrong
![image](https://user-images.githubusercontent.com/6836805/144834921-89e43290-1864-4961-bad4-42d5de0cc510.png)

**Comment by whalley** [comment]
Is it just the linegraphs that use 'datetime' that are failing? Or are all graphs on Windows failing. Looks fine on MacOS with YYYY-MM-DD format.

**Comment by vomikan** [comment]
Suddenly, all charts stopped being displayed regardless of the date format.

**Comment by whalley** [comment]
Just tried it on Windows and all graphs seem to fail....  There are a few .js files needed for IE that were changed recently for 3.30.0 that I thought I had picked up...
https://github.com/apexcharts/apexcharts.js/blob/v3.30.0/README.md#using-it-with-ie11

**Comment by vomikan** [comment]
It's working in the following environment:
![image](https://user-images.githubusercontent.com/6836805/144848681-f27219cc-f8a9-41f6-8893-f01ba64c096c.png)

mmex at start:
File: apexcharts.min.js has been copied to VFS
File: ChartNew.js has been copied to VFS
File: classlist.min.js has been copied to VFS
File: findindex.min.js has been copied to VFS
File: format.js has been copied to VFS
File: home_page.htt has been copied to VFS
File: kaching.wav has been copied to VFS
File: mmex.ico has been copied to VFS
File: mmex.png has been copied to VFS
File: polyfill.min.js has been copied to VFS
File: resize-observer.js has been copied to VFS
File: sorttable.js has been copied to VFS
File: umd.min.js has been copied to VFS

**Comment by vomikan** [comment]
I found that if I accept all the recent changes, but replace the file apexcharts.min.js from the release
https://github.com/apexcharts/apexcharts.js/releases/tag/v3.28.2
all graphs became working.

**Comment by vomikan** [comment]
Related issue: #4025

**Comment by renato-mmex** [comment]
Congratulations, the display of the graphics has never been so good.
