### ISSUE TITLE
Current Year not correct

### ISSUE THREAD

**Issue by PastorSnell** [moneymanagerex/moneymanagerex#4055]
Transaction reports choosing Current Year to date yields search range of "From 2022-01-01 till 2021-12-06" and thus shows nothing.

<hr>Version: 1.5.10 64-bit<br>
 • Build: Nov 23 2021 15:42:53<br>
 • db 7 •  (aes128cbc)<br>
 • git 4b8bb17 (2021-11-23)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 22000), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by PastorSnell** [comment]
noticed same issue in prior version 1.5.9

**Comment by vomikan** [comment]
v1.5.11
![image](https://user-images.githubusercontent.com/6836805/144914147-46b56c6b-42f2-45c1-8b8e-4e73723abd81.png)

v1.5.10
![image](https://user-images.githubusercontent.com/6836805/144914335-6a4e0bc3-7d18-4980-bb0c-e6b5a05c6c1c.png)
