### ISSUE TITLE
Budget question

### ISSUE THREAD

**Issue by loki36** [moneymanagerex/moneymanagerex#406]
Hi,

I don't know if it's the good place to ask my question, But I'm looking for the best way to input my budget.

I want have a yearly budget :
with some entries for the year (i found how)
with some entries for the year by month (or other) (i found how two)
with some entries for one or some defined month (I don't find how do for yearly budgets).

And I want to be able to see this budget by month or by year and from the beginning of year until current month.

That's I understand, I can enter budget for a year or for a given month, but not all in one time, right ?

**Comment by vomikan** [comment]
All budgets are independent. You can create budget for 2015 and for 2015-03 as well.
The budget for march of 2015 will not included into the yealy budget 2015.
Proper place to ask questions like his is a forum.
http://forum.moneymanagerex.org/
