### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by joestefl** [moneymanagerex/moneymanagerex#4060]
Many items are in  english instead of in italian. (like category)

<hr>Version: 1.5.11 64-bit<br>
 • Build: Dic  7 2021 12:41:07<br>
 • db 7 •  (aes128cbc)<br>
 • git 40b3964 (2021-12-06)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 22000), 64-bit edition<br>
 •  Italian (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
The translations are provided by volunteers... https://crowdin.com/project/moneymanagerex

I've checked the Italian translations and most involving 'Category' are there.

You can either submit corrections using the above site or can you provide specific examples that need fixing.

**Comment by joestefl** [comment]
I know that.
I wrote the above because up to 3 or 4 previous versions the Italian translation was perfect.
Maybe something got lost along the way

**Comment by joestefl** [comment]
i try to send you image with correction in e few hours. Thanks

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/145210200-80c7840a-42db-4bb4-be00-6818f7d4c88f.png)
