### ISSUE TITLE
ORGANIZE PAYEES Error

### ISSUE THREAD

**Issue by BigPacket** [moneymanagerex/moneymanagerex#4070]
MMEX version:
 - [x] 1.5.11
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
In "ORGANIZE PAYEES". I right click on the payee name and select "Edit". When I edit the payee, I get the error "Payee with the same name exists".

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Tools, ORGANIZE PAYEES... Pick and Payee, Right Click and select "Edit". Edit the Payee, Click "OK" and the error appears -"Payee with the same name exists".
2. 
3. 

…

Expected result: Be able to Edit the Payee.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I cannot reproduce this. Please note that payee matching is case-insensitive, so Payee, PAYEE, PayEE are all the same. Is this what you are encountering?  

Actually we should perhaps allow the name to be changed in these circumstances if it was mistyped in the first place. Editing inline (e.g. clciking on payee name in list and then editing) rather than via the dialog supports this.

Workaround is to change PAYEE to XPAYEE then to Payee   (where XPAYEE does not exist)

**Comment by renato-mmex** [comment]
I can only confirm Whalley's statement.

**Comment by whalley** [comment]
Have made the dialog name edit allow case changes to existing name to match behavior for in-line edit.

@BigPacket Can you confirm if this was your issue or you are still having issues with changing payee names.

**Comment by renato-mmex** [comment]
the mutation of the text works now, but the upper/lower case is not respected.  If I want to add a value "Test" and I already have a value "TEST", then there is an error message

<img width="176" alt="image" src="https://user-images.githubusercontent.com/76920138/146174388-3b4a8ae8-d267-4953-86b6-cb86a96163c1.png">

**Comment by Dandy64** [comment]
I suppose that this is correct behavior. 
If a user is creating a password upper and lower cases are very important. But let's say there is a drop-down data window with cities names. The user starts writing and autocompletes suggests different variants. Actually, the user can write whatever he wants: london, londoN, LONDON, lOnDoN, the system should recognize and save the only correct value - London.
So IMHO "TEST" and "Test" should be treated as the same value.

**Comment by tactilis** [comment]
>Actually, the user can write whatever he wants: london, londoN, LONDON, lOnDoN, the system should recognize and save the only correct value - London. So IMHO "TEST" and "Test" should be treated as the same value.

@Dandy64 I agree that searching and autocomplete should be case insensitive. However I don't agree with your statement _"the system should ... save the only correct value - London."_  MMEX will not know the 'correct' capitalisation. The system should save the capitalisation chosen by the user when he enters or edits the payee.

**Comment by whalley** [comment]
> the mutation of the text works now, but the upper/lower case is not respected. If I want to add a value "Test" and I already have a value "TEST", then there is an error message
> 
> <img alt="image" width="176" src="https://user-images.githubusercontent.com/76920138/146174388-3b4a8ae8-d267-4953-86b6-cb86a96163c1.png">

@renato-mmex That is correct behavior.

**Comment by Dandy64** [comment]
_"@renato-mmex That is the correct/intended behavior."_
Yep, this is exactly what I mean.

_"MMEX will not know the 'correct' capitalisation. The system should save the capitalisation chosen by the user when he enters or edits the payee."_
Should the system save the variant chosen by the user or not, it's all about definitions.
