### ISSUE TITLE
Compile directions wrong for Linux

### ISSUE THREAD

**Issue by jelabarre59** [moneymanagerex/moneymanagerex#4074]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X ] Linux 

# Description of the bug

the instructions for compiling under linux say: 
------------------
4. Compile and Create Package
Same as for macOS
------------------
However the compilation command for MacOS contains a lot of MacOS-specific switches.

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction
Read through the directions, and find the command we are expected to use with Linux contains MacOS-specific switches.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. read compilation directions for mmex under Linux
2. find the command line we are supposed to use is full of MacOS switches
3. no further steps

…

Expected result:

compilation command instructions would be appropriate for Linux

Actual result:
compilation command instructions are not appropriate for Linux

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
@PMaff Are you able to help provide these instructions.
https://forum.moneymanagerex.org/viewtopic.php?t=10537

**Comment by PMaff** [comment]
Sorry, was a bit busy these days.
See here:
https://github.com/moneymanagerex/moneymanagerex/pull/4148#issue-1118694341
