### ISSUE TITLE
Repeating Transfer

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#408]
I think a bug has been introduced with repeating transfers. To reproduce:

1. Set up a new repeating transaction. Set it to "Transfer" and choose two accounts and amount $1000. Click OK.
2. Enter the transaction, but change the amount to $800 on entering. The "From" account will have $800, but the "To" account will have $1000, despite the "Advanced" setting not being checked in the original repeating transaction or the entered transaction.

**Comment by omalleypat** [comment]
@stef145g - would you have a look at this one?

**Comment by vomikan** [comment]
I can

2015-03-07 16:14 GMT+03:00 omalleypat <notifications@github.com>:

**Comment by vomikan** [comment]
I can't reproduce this issue.
As soon as I change focus from AMount field - the To Amount changed as well at the same moment.

**Comment by stef145g** [comment]
@omalleypat - I have looked at this and I **have** been able to reproduce this problem.

@vomikan - I did this as a 3 stage process as follows: (Interpreting @omalleypat 's description)

1. Create a new standard **transfer** repeating transaction - Enter. **Result: All Good**
2. Edit the same repeating transaction, and change the amount. -  Enter - **Result: NOT Good**
3. Edit the same repeating transaction again. - The transaction is set to 'Advanced' and the advanced amount displays the original value.

@vomikan  - Please investigate further.
If you want me to investigate further, you can re-assign.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/b8b2717851a627ed567e6d1f5e9dfd76f9a412d1
