### ISSUE TITLE
Summary of shares report not displaying fractional shares if total is greater than 1

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#4087]
MMEX version:
 - [x] 1.5.11

Operating System:
 - [x] Windows

# Description of the bug
Summary of shares report (built in MMEX, left menu) not displaying fractional shares if total is greater than 1.
This is that the report shows:
![image](https://user-images.githubusercontent.com/6977203/147836591-1c461575-acbe-4411-8cdf-29cfd837bc48.png)
This is the actual data:
![image](https://user-images.githubusercontent.com/6977203/147836605-ad5e35f5-0662-480a-91a9-113c11061154.png)
It seems decimals only shown if total is less than 1 share.

# Reproduction

Is the bug reproducible? 
 - [x] Always

**Comment by n-stein** [comment]
This appears to have been purposefully changed back in May 2016 (commit 1684f4d), although I do not know the reasoning. Previously all values were reported to 4 decimal precision, but that was changed to only apply when the floor is 0.

https://github.com/moneymanagerex/moneymanagerex/blob/fecd876bb1d70a5291496a79390314ab1ed03e35/src/reports/summarystocks.cpp#L144

**Comment by whalley** [comment]
Yes, does seem a little odd, I wonder if the intention was to remove decimal places if the number of shares was not fractional?

**Comment by vomikan** [comment]
It should be ```if(floor(value) == value)```
or
```entry.qty ==  static_cast<double>(static_cast<int>(entry.qty))```
