### ISSUE TITLE
Transaction not organizing with others with the same date

### ISSUE THREAD

**Issue by relmers** [moneymanagerex/moneymanagerex#4090]
I recently came upon this software. I imported a csv file from another app and everything seemed fine. I currently have all transactions dated today or before aligned properly except for one. I also have all of Januarys recurring transactions displayed but they are grayed out since they haven't been entered yet because of future dates. 

The issue I have, is any new entries that I add today, such as an "interest earned"  dated for yesterday is located at the top of the page beyond all the January unentered transactions. I tried changing the date of this transaction to the year 2020 and it still stay at the top of the page and does not align with the rest of the transactions with similar or same dates. 

Money Manager Ex
Version: 1.5.11 64-bit
• Build on Dec 7 2021 12:41:07
• Database version: 7 • (aes128cbc)
• Git commit: 40b3964 (2021-12-06)
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg v2.0.1
• libcurl/7.61.0-DEV WinSSL
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.16.2
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
Running on:
• Windows 10 (build 19043), 64-bit edition
• English (U.S.) (windows-1252)
• 1920x1080 32bit 96x96ppi

**Comment by relmers** [comment]
UPDATE to include:
**Money Manager Ex
Version: 1.5.11 64-bit
• Build on Dec 7 2021 12:41:07
• Database version: 7 • (aes128cbc)
• Git commit: 40b3964 (2021-12-06)
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg v2.0.1
• libcurl/7.61.0-DEV WinSSL
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.16.2
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
Running on:
• Windows 10 (build 19043), 64-bit edition
• English (U.S.) (windows-1252)
• 1920x1080 32bit 96x96ppi**

**Comment by tactilis** [comment]
@relmers  I'm guessing that you have the transactions sorted by ID.

You should sort them by Date.

Click on the column header to change the sort order.

![Sort by date](https://user-images.githubusercontent.com/4060092/147853332-9c79a66c-92d6-4ad1-8107-6af5eb3801fb.png)

**Comment by relmers** [comment]
Yep, you were correct. I didn't think about that being the issue since the transaction had a highest ID number> I now realize that the ID number corresponds to when the transaction was generated and nothing to do with the date. 

I appreciate you taking the time to answer my problem.

Happy New Year....

Bob
