### ISSUE TITLE
future bookings are displayed incorrectly on homepage 

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4092]
MMEX version:
 - [x] 1.5.12-Beta.1  64-bit

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows

# Description of the bug

**If you use the "Ignore Future Transaction" option, the bookings will still be displayed on the homepage.**

# Reproduction

Is the bug reproducible? 
 - [x] Always 

# Additional information

<img width="278" alt="image" src="https://user-images.githubusercontent.com/76920138/147955657-0a2d55b3-68eb-4ac6-8794-4ed4a3cdbf16.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/76920138/147955292-e66b63e3-b393-4230-9efe-236defc96dcc.png">
<img width="241" alt="image" src="https://user-images.githubusercontent.com/76920138/147955313-a39ff463-1807-4f2d-9daf-050ebce347c7.png">

**Comment by whalley** [comment]
The 'Ignore Future Transactions' does not apply to the reports. The 'Current Month' report includes EVERYTHING this month. Is the 'Current Month to Date' the report you want on the home page. You can select this from the options.

![CleanShot 2022-01-03 at 18 57 15](https://user-images.githubusercontent.com/487345/147968734-642d44c5-a96f-4a04-9646-c84744c5a7b1.png)

**Comment by renato-mmex** [comment]
From my point of view, the option 'Ignore Future Transactions' in the settings is superior and binding for all reports.

**Comment by whalley** [comment]
At present the 'Ignore Future Transactions' seems to taken into consideration in reports

- Budget Category Summary -- These do not have the period selection
- Budget Performance -- These do not have the period selection
- Categories
- Payees

From my point of view I would prefer the periods in the reports to guide what is reported. E.g Current Mon/Year/ Financial Year (complete or 'to date'), and if I entered a period into the future manually I would want the report to include all transactions. After all the data range specification is a user option, if the user just wants transactions to date then they should specify a reporting period that covers this. I feel it confusing to specify a period but then have the end ignored. I'd prefer the Category/Payee reports to use the full range like the other reports.

If we really want to restrict what is reported and in-effect make 'Current XXX' and 'Current XXX to Date' the same by overriding with 'Ignore Future Transactions' then we probably need some form of indication to the user in the reports that this is active when a future end date is specified.

**Comment by renato-mmex** [comment]
as it is always realized, it is urgent that the user can understand what kind of bookings this evaluation consists of and since we cannot provide an up-to-date manual it is difficult in any case.

**Comment by whalley** [comment]
Have amended reports that specify a date range into the future to ignore future transactions if the option is set, and indicate when this has been done in the report. 

Where an explicit date range has been specified by the user then this will override the 'ignore future' option and the user specified range will be honoured.
