### ISSUE TITLE
Repository update-Unable to

### ISSUE THREAD

**Issue by tosim91** [moneymanagerex/moneymanagerex#4096]
While updating Linux Mint 20.2(Uma), received following error message:
The repository 'https://packagecloud.io/moneymanagerex/moneymanagerex/linuxmint uma Release' does not have a Release file.Updating from such a repository can't be done securely, and is therefore disabled by default.See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by PMaff** [comment]
Did you try the very easy way of compiling
wxWidget 3.1.5 (see : https://docs.codelite.org/build/build_wx_widgets/#gtk3-recommended ) 
and 
mmex 1.5.14 (see https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux )?
