### ISSUE TITLE
Select all the visible transactions using `Cmd + A`

### ISSUE THREAD

**Issue by anirudhbagri** [moneymanagerex/moneymanagerex#4098]
# Description of the feature

Ability to select all the visible transactions using `Cmd + A` (MacOS).

(I have not tried if it works for linux/windows with Crtl+A.)

**Comment by Heny67** [comment]
Hi!
Ubuntu 20.04 account view does not work. (Unfortunately)

**Comment by tactilis** [comment]
CTRL+A/CMD+A is not currently defined as a wxAcceleratorEntry, so it won't do anything on any OS.

It may be a good idea to provide it but in the meantime it's very easy to press **Home** then **Shift+End** to select all transactions in an account.

@anirudhbagri  What is your need for selecting all?  i.e. what is the operation that you are wanting to do on the transactions when all are selected?

**Comment by anirudhbagri** [comment]
@tactilis, for an example I want to bulk edit those transactions as tranfer.

**Comment by tactilis** [comment]
@vomikan I can confirmed that your CTRL+A fix does select all transactions.

However, the call of SetItemState() in OnSelectAll() causes the summary panel at the bottom of the screen to be updates for each row in turn: 
```
    for (int row = 0; row < GetItemCount(); row++) {
        SetItemState(row, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED);
```

This is not useful to the user and can take a long time if there are 1000s of transactions.

If you select all by pressing **Home** (to move to the top of the list) and then **Shift+End** (to select to the end) then the summary panel is only updated once.

Is there another way of setting the selected state of the rows without causing multiple updates to the summary panel please?

**Comment by vomikan** [comment]
@tactilis thank you for pointing this issue.

**Comment by tactilis** [comment]
Confirmed that the summary panel update is good now
