### ISSUE TITLE
Notes field for budget page

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4099]
# Description of the feature

Please describe your feature with details.

There is a nice option to add a custom field in any grid for any account: bank, credit, cash, term.
![image](https://user-images.githubusercontent.com/83161661/148687072-0c11bb6f-3a50-4573-ac11-22b1da002f7e.png)

It would be cool to add the same option for the Budget page. For example, I would like to add Comments for every line in Budget's grid.
![image](https://user-images.githubusercontent.com/83161661/148687237-b70abd1a-c389-4eaa-828d-ba3ef4df4b8c.png)

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
I'll prefer to add the Description field only.

**Comment by vomikan** [comment]
I like it!
![image](https://user-images.githubusercontent.com/6836805/195455619-5fdc65dd-896b-4eb9-b328-1d0666918897.png)
