### ISSUE TITLE
back up problem mac OS Monterey 12.0.1 with MMEX 1.5.11

### ISSUE THREAD

**Issue by Allotmentman** [moneymanagerex/moneymanagerex#4102]
> I have been sluggish in keeping up to date with MMEX versions having used 1.1.1 for many years!!
I have recently updated to version 1.5.11. 
I have checked the box "backup on exit" and get the following message when closing the application. MMEX would appear to  have backed up the database as there is a .bak file with the correct date and time

I’m running Money Manager Ex 1.5.11 on Mac OS Monterey 12.0.1

I get this message when closing down MMEX after creating a new database or using existing database

Cannot enumerate files ….. ????-??-??.bak (error 1: Operation not permitted)

I do not get this message when using previous version 1.1.1 

> Please do not remove information attached below this text.

<hr>Version: 1.5.11 64-bit<br>
 • Build: Dec  7 2021 16:05:52<br>
 • db 7 •  (aes128cbc)<br>
 • git 40b3964b1 (2021-12-06)<br>
 • v1.5.x<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMac 12.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.21.3<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 13.0.0 (clang-1300.0.29.3)
<br>
<br>
OS:<br>
 • macOS Version 12.0.1 (Build 21A559)<br>
 •  English (Western (Mac OS Roman))<br>
 • 1440x900 32bit 144x144ppi

**Comment by vomikan** [comment]
Is your mmb file name contains non latin characters?

**Comment by Allotmentman** [comment]
Hi there

The file name is 21.12 xxxxx v2.mmb

Hope this helps

Dave

**Comment by whalley** [comment]
Can't seem to re-produce this.  Where is your DB located? 

I just created a dummy DB, closed, opened, etc and the backup files seem to be created OK.

![CleanShot 2022-01-10 at 19 04 15](https://user-images.githubusercontent.com/487345/148824153-f5414252-cc43-4507-889f-87f21c8dab1e.png)

**Comment by Allotmentman** [comment]
On the SSD
On reflection this issue seems to happen after the first backup of the day. I tend to open and close often more than once a day

Hope this helps

**Comment by tactilis** [comment]
> On the SSD

@whalley means, in which folder is your database located

> On reflection this issue seems to happen after the first backup of the day.

_Seems_ to happen? Or always happens? Or only happens? ...after the first backup of the day?

It would be helpful to others trying to solve this for you if you gave precise details.

**Comment by whalley** [comment]
@Allotmentman  Can you please clarify if this issues still exists. If so can you provide the precise details under which it occurs.

**Comment by whalley** [comment]
@Allotmentman Closing..... if you can reproduce then feel free to re-open.

**Comment by Allotmentman** [comment]
Hi there
 This happens every time I close MMEX and a back up is made xxxxxxx.bak where my previous version the backup was named xxxxx.mmb

A backup version completed each time MMEX is closed 

Kind regards

Dave

**Comment by tactilis** [comment]
The file type for backups was changed from .mmb to .bak in MMEX version 1.5.6.
See https://github.com/moneymanagerex/moneymanagerex/issues/3648

**Comment by tactilis** [comment]
@Allotmentman 
Today you wrote:
> This happens every time I close MMEX and a back up is made

but 10 days ago you wrote:
> On reflection this issue seems to happen after the first backup of the day. I tend to open and close often more than once a day

Which is it please?

**Comment by Allotmentman** [comment]
Every time

**Comment by whalley** [comment]
Do you have

**Comment by tactilis** [comment]
@Allotmentman
 
@whalley is referring to these options

![image](https://user-images.githubusercontent.com/4060092/150333910-c79c4bc5-9842-49e6-b054-d3c8f1d1345c.png)

**Comment by Allotmentman** [comment]
I have not ticked the backup on start and have max files as 10, otherwise all is as the settings in your snapshot

**Comment by tactilis** [comment]
@Allotmentman
Please could you provide a screenshot of the folder showing the details of **all** the *.mmb and the *.bak files - see the one from @whalley [here](https://github.com/moneymanagerex/moneymanagerex/issues/4102#issuecomment-1009252679)

And as @whalley requested:
> Can you let me know what the permissions are on the folder containing the database and backups

**Comment by Allotmentman** [comment]
Please find enclosed screenshots that may help in deciding what I have done wrong

**Comment by Allotmentman** [comment]
<img width="1440" alt="Screenshot 2022-01-20 at 14 29 57" src="https://user-images.githubusercontent.com/97443802/150401599-e05e75b2-5374-4a52-8096-ab60795406c8.png">
<img width="1440" alt="Screenshot 2022-01-20 at 14 47 24" src="https://user-images.githubusercontent.com/97443802/150401598-eccb8907-2032-4248-9f20-c72106f2316d.png">

**Comment by vomikan** [comment]
I see question marks instead of numbers in the file name. I don't understand how they got there.
![image](https://user-images.githubusercontent.com/6836805/150404045-86e85908-486d-476d-997d-25fd4cca2e33.png)

**Comment by whalley** [comment]
All I can think of is perhaps a locale related issue that is affecting the wxDateTime class.

@Allotmentman What are your language/region settings in MacOS?
![CleanShot 2022-01-20 at 19 50 01](https://user-images.githubusercontent.com/487345/150411687-e6218c0b-d51a-4bb4-bb78-464145dfbcec.png)

Also what is the locale setting in MMEX.
![CleanShot 2022-01-20 at 19 52 43](https://user-images.githubusercontent.com/487345/150412108-898e2b31-f703-4962-ac0d-a6dd834b14cb.png)

**Comment by Allotmentman** [comment]
<img width="1440" alt="Screenshot 2022-01-21 at 12 57 05" src="https://user-images.githubusercontent.com/97443802/150531954-b7d96439-3912-4a45-b59c-49dde43be97d.png">
<img width="1440" alt="Screenshot 2022-01-21 at 12 57 31" src="https://user-images.githubusercontent.com/97443802/150531976-06158858-003b-4c2f-9e15-563d6310a82c.png">

I have changed in the currency area I have changed from blank to en_GB.
this had no effect when closing down, although I did wonder how to achieve commas  with thousands of pounds. Thats sorted, so thanks for that

Where the ?????? come from I have no idea

How frustrating

**Comment by tactilis** [comment]
@Allotmentman, why have you closed this issue?

Are you saying that you no longer get the 'Cannot enumerate files' error?

**Comment by Allotmentman** [comment]
I didn’t know I had closed this issue. I am still getting the same problems

**Comment by tactilis** [comment]
> I didn’t know I had closed this issue. I am still getting the same problems

![image](https://user-images.githubusercontent.com/4060092/150630986-4949b6ab-485b-42a7-86b1-1eacd287d686.png)
 
  
Could you re-open it please

**Comment by 2BeeOrNot** [comment]
Looking at this post [https://github.com/moneymanagerex/moneymanagerex/issues/4102#issuecomment-1017808617](url) above I see 13 backups but the OP said max files is 10. So why haven't the three oldest backups been deleted? And the three backups are from the previous calendar year. Could MMEX be enumerating the backup files and trying to delete the three oldest backup files and failing for some reason? I tried with max files 13 with backups in 2021 and 2022 and MMEX worked as expected. Delete or move the backups from 2021 and see what happens?

**Comment by Allotmentman** [comment]
Please find enclosed screenshot of latest folder where MMEX files live and the result from closing down MMEX
it makes no difference as how many backup max files i have the same issue occurs.
Interestingly the previous version of MMEX i was using allowed multiple backs on the same day where this version does not. Is this correct?
<img width="1440" alt="Screenshot 2022-01-23 at 14 52 15" src="https://user-images.githubusercontent.com/97443802/150684441-1d3fb4b8-01e9-4fe2-a6f2-08559b237194.png">

**Comment by tactilis** [comment]
> Interestingly the previous version of MMEX i was using allowed multiple backs on the same day where this version does not.

Multiple = TWO.

You can set MMEX to create a backup each time it starts and/or each time it exits (see MMEX Options).

They are labelled:
database name.mmb_start_YYYY-MM-DD.bak
database name.mmb_update_YYYY-MM-DD.bak

There is _only one_ start or update file for each day (ie containing a backup from the most recent MMEX start or exit).

The only difference from older versions of MMEX is that backup files used to have a file type of .mmb but that cause confusion for some users; they were accidentally opening backups instead of their current database file.

**Comment by whalley** [comment]
> Looking at this post [https://github.com/moneymanagerex/moneymanagerex/issues/4102#issuecomment-1017808617](url) above I see 13 backups but the OP said max files is 10. So why haven't the three oldest backups been deleted? And the three backups are from the previous calendar year. Could MMEX be enumerating the backup files and trying to delete the three oldest backup files and failing for some reason? I tried with max files 13 with backups in 2021 and 2022 and MMEX worked as expected. Delete or move the backups from 2021 and see what happens?

Yes, good point. The backups are working it is the tidy-up that is failing.
https://github.com/moneymanagerex/moneymanagerex/blob/2dbb40e8800220a116acf862457bc1b278740f6b/src/dbupgrade.cpp#L159

Looking at the code I can't see any issues, all I can think is that there are permission issues when performing the 'wxFindFirstFile' file lookup.

**Comment by 2BeeOrNot** [comment]
@whalley: Line 1150 is where the error is thrown. The problem looks to begin at line 1146:
 `1146: gs_dir.reset(new wxDir(gs_dirPath));`
 `1148: if ( !gs_dir->IsOpened() )`
Something gone wrong in opening/setting the directory path before the actual call to find the first matching file?
Maybe as @vomikan asked above a non latin character in the path? I can't duplicate using the same path, database name and permissions @Allotmentman used. I'm on macOS 12.1 using MMEX 1.5.11.

@Allotmentman  Have you/can you copy the database to the root of your documents folder and try it from there?
Documents/22.12 payday.mnb, not Documents/MMEX/MMEX 2022/current/22.12 payday.mnb

**Comment by tactilis** [comment]
> @Allotmentman Have you/can you copy the database to the root of your documents folder and try it from there?
Documents/22.12 payday.mnb, not Documents/MMEX/MMEX 2022/current/22.12 payday.mnb

NB  .mmb  (not .mnb)

**Comment by whalley** [comment]
@Allotmentman Can you please check what these permissions are set to.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/487345/150702521-a73ff24b-f173-4ce7-9abb-8b627415009f.png">

**Comment by 2BeeOrNot** [comment]
Interesting. I deleted MMEX from Files and Folders. Started MMEX and opened the database /Users/xxxx/Documents/MMEX/MMEX 2021/current/21.12 payday v2.mmb. I was asked if MMEX could access the Documents folder. I agreed. No errors. I changed MMEX settings to make backups on startup and restarted MMEX using the same database. No errors. I then removed access to Documents folder by unchecking it and reopened MMEX using the same database. MMEX worked. But why, shouldn't I have been asked if MMEX can access the Documents folder? But on closing MMEX I got a similar error message but entirely different layout. But when I opened a database in the root of Documents I got the same error format as @Allotmentman. I then then removed MMEX from Files and Folders and restarted MMEX. I was asked if MMEX could access the Documents directory. I did not agree. But MMEX opened the database.

You may have solved this issue.

![MMEX Error 75](https://user-images.githubusercontent.com/63317977/150704298-e7380642-35ee-42a7-8404-8c2e6b352c54.jpeg)

**Comment by vomikan** [comment]
May be BackupName[Backup Type] return null value in some scenarious like @2BeeOrNot describes above?

**Comment by Allotmentman** [comment]
Hey guys
It's fixed. Documents folder, wasn't checked
All is now fixed
I thank you all very much for your time and effort on this. 
well impressed
Cheers 
Dave

**Comment by whalley** [comment]
Thanks for confirming....

**Comment by Pablito1104** [comment]
Grazie mille @renato-mmex, ho risolto concedendo i permessi in security/privacy.
