### ISSUE TITLE
mmex not opening for a second time, corrupted db3 file

### ISSUE THREAD

**Issue by Iss-in** [moneymanagerex/moneymanagerex#4103]
MMEX version:
 - [x] moneymanagerex 1.5.5-1

Operating System:
 - [X] Linux  Arch/sway

# Description of the bug
Most of the time mmex doesnt open after the first run is closed. 
getting `[1]    184103 killed     mmex` on running in a terminal on 2nd time. only sollution is to remove the $HOME/.mmex folder and reload the db file

# Reproduction
run mmex and close it. open it again

Is the bug reproducible? 
 - [x] Always 
 - [ ] 
Reproduction steps:

1. Run mmex for the first time
2. close it using the file menu option or close button
3. it wont run again unless you delete the $HOME/.mmex fodler

…

Expected result:

mmex wont run for a 2nd time

Actual result:
should run everytime opened

# Additional information
wxgtk-common 3.0.5.1-3
wxgtk2 3.0.4-2
wxgtk3 3.0.5.1-1

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Could you upload $HOME/.mmex/mmexini.db3 file after mmex closure?

**Comment by Iss-in** [comment]
not sure what happened, cant reproduce it anymore after a day, didnt even restart my system. will see if happens again

**Comment by whalley** [comment]
Closing. @Iss-in please reopen if you encounter this again.
