### ISSUE TITLE
Invalid vector <T> subscript

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#4113]
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.

<hr>Version: 1.5.11 <br>
 • Build: Dec  7 2021 12:51:16<br>
 • db 7 •  (aes128cbc)<br>
 • git 40b3964 (2021-12-06)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 22000), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

I have reported this twice before but I am not a geek so nobody deals with it. I will persevere and hope to get a resolution.
![MMEX error](https://user-images.githubusercontent.com/39367770/149509262-d8e42d1d-8ec0-4232-a11e-54e054f22e4a.jpg)

**Comment by vomikan** [comment]
How to reproduce?

**Comment by whalley** [comment]
@Speigy  Closing. Please re-open if you can describe how to replicate.
