### ISSUE TITLE
Incorrect "Summary of Accounts" balance

### ISSUE THREAD

**Issue by Yurand** [moneymanagerex/moneymanagerex#4116]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
"Summary of Accounts" shows incorrect balance.

# Reproduction
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

You have 2 accounts: one account with currency A - $50 (base currency), second with currency B - 50 Br

Now add exchange rates for B.

1/1/2021 - 1:1
2/1/2021 - 1:1.1
3/1/2021 - 1:1.2
4/1/2021 - 1:1.3
5/1/2021 - 1:1.4
6/1/2021 - 1:1.5
7/1/2021 - 1:1.6
8/1/2021 - 1:1.7
9/1/2021 - 1:1.8
10/1/2021 - 1:1.9
11/1/2021 - 1:2.0
12/1/2021 - 1:2.1

Add spending at 1/1/2021

Now click on "Summary of Accounts" - Monthly

The Balance for all months will be 100. It is incorrect since the final balance should be $155. And you should see increases each month.

Here is a database file that shows the issue:

[mmbtest.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/7882030/mmbtest.mmb.zip)

**Comment by vomikan** [comment]
There are 2 solutions:
1) Update currency rates for one (or more) year
![image](https://user-images.githubusercontent.com/6836805/149802385-e875ec6a-fee1-481b-b2a5-e37852c1b656.png)


2) Switch off the Currency History parameter
![image](https://user-images.githubusercontent.com/6836805/149801976-dfc7f50c-f93f-4937-a4c1-cc69a9718a18.png)

**Comment by Yurand** [comment]
1) I used fake rates to show the problem (downloading real rates have no effect, I still see $100 in the report)
2) Changing "Use currency history" seems have no effect on "Summary of Accounts" report.

Tested on 1.5.11 and current master

**Comment by vomikan** [comment]
Could you try this DB?
[mmbtest.zip](https://github.com/moneymanagerex/moneymanagerex/files/7883376/mmbtest.zip)

**Comment by Yurand** [comment]
Tested.

Now it shows 69.54 for December 2020, and 69.15 for all months in January 2021 - January 2022 range. It is also wrong since exchange rate is different for different months.

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/3554

**Comment by Yurand** [comment]
Created PR #4959 that fix the issue.

Attached DB that show issue. You see 99 for all months, but this amount should he changed every month due to added historic conversion rates.

[mmbtest.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/9389884/mmbtest.mmb.zip)
