### ISSUE TITLE
Wrong rates in "Currency Exchange Rates" table on home page

### ISSUE THREAD

**Issue by Yurand** [moneymanagerex/moneymanagerex#4118]
MMEX version:
 - [x] 1.5.11
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
If you use 3 or more currencies, "Currency Exchange Rates"  shows the wrong rates.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create 3 accounts with 3 different currencies (update their rates)
2. See "Currency Exchange Rates" table on Home Page

…

Expected result:

|         |BYN | EUR  | USD|
|------|------|------|-----|
| BYN |   | 2.9325 |2.57|
| EUR |  0.3410 | | **0.8764** |
| USD |  0.3891 | **1.1410** | |

Actual result:

|         |BYN | EUR  | USD|
|------|------|------|-----|
| BYN |   | 2.9325 |2.57|
| EUR |  0.3410 | | **1.1410** |
| USD |  0.3891 | **0.8764** | |

**Comment by vomikan** [comment]
It seems to me that I have specifically distributed these values so that what is greater than one on the one hand, those that are greater on the other.

**Comment by Yurand** [comment]
I think the data in this table should be consistent, for example for each row "how many in other currency I will get for 1 unit" or for each column "how many in other currency I will get for 1 unit". Currently, it is mixed.
