### ISSUE TITLE
Stocks Report corrupted in v1.5.11

### ISSUE THREAD

**Issue by ChrisCross321** [moneymanagerex/moneymanagerex#4120]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When running v1.5.11 the Stocks Report shows a corrupted graph whereas with v1.5.10 the graph is as expected.  I used the same data file for both versions. See screenshot examples attached

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click on Stocks Report
2. Select Period: pull down to Over Time 
…

Expected result:

See attached expected screenshot from v.1.5.10 

Actual result:

See attached corrupted screenshot from v.1.5.11 

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

![MMEX-v1 5 10-Stocks Report Screenshot As Expected](https://user-images.githubusercontent.com/18583879/149995155-37007f56-f734-41bd-96c1-6a00a983a312.jpg)

![MMEX-v1 5 11-Stocks Report Screenshot Corrupted](https://user-images.githubusercontent.com/18583879/149995186-9249cbe9-172d-4a15-b11c-bc8e2d8931bd.jpg)

**Comment by vomikan** [comment]
I can'r reproduce this issue.

**Comment by whalley** [comment]
Possibly linked to this change? https://github.com/moneymanagerex/moneymanagerex/commit/bf1c6f069e698ce2871caa7629c0b1990b5bb85e#diff-81b88148c161dd8c082d3a11c0748c1399dbdbbe076c97351515cec718052c6b

**Comment by whalley** [comment]
Can't reproduce on my setup, but this fix might help.

**Comment by renato-mmex** [comment]
I can only confirm this error
From my point of view the calculation of the day is wrong, display with "last month" is correct, all other selections are wrong

<img width="662" alt="image" src="https://user-images.githubusercontent.com/76920138/150028249-f4f5fdf1-63bf-46fc-bdf5-597a810efa8c.png">

**Comment by whalley** [comment]
Does the build here fix the issue??? - https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/42248857/job/8h5f5xt9s41ssrmk/artifacts

**Comment by ChrisCross321** [comment]
Thanks Mark,

Just tested and fixes the problem, many thanks for your help, Chris..

**Comment by whalley** [comment]
@ChrisCross321 Thanks for confirming... hoped it might!
