### ISSUE TITLE
Duplicate Recurring Transaction

### ISSUE THREAD

**Issue by sharkei2018** [moneymanagerex/moneymanagerex#4124]
# Description of the feature

I would like to be able to duplicate a recurring transaction where the majority of the fields contain the same values.

# Use cases

This would save me having to enter similar details in more than one 'New' transaction.
It could be actioned with an additional button at the bottom of the window, alongside 'New' and 'Edit', or as an option behind the right mouse.

**Comment by whalley** [comment]
Sounds a reasonable suggestion.

**Comment by grumpy235** [comment]
@whalley think last commit might have a typo, surely it should be "&Dup.." rather than "D&up.." ?
![Screenshot 2022-01-26 093158](https://user-images.githubusercontent.com/24897056/151138432-0cb02680-b740-4dc0-ba18-88754ac7173c.png)
"

**Comment by whalley** [comment]
No. The 'D' keyboard shortcut is used for Delete action.

**Comment by grumpy235** [comment]
Best I did more learning/research before opening my mouth, I think !
Mind you U for Duplicate is not that obvious.

**Comment by whalley** [comment]
> Mind you U for Duplicate is not that obvious.

:-) Agreed, but D was taken.

**Comment by sharkei2018** [comment]
Thanks so much everyone for adding this functionality.  Brilliant!!

**Comment by sharkei2018** [comment]
A suggested enhancement for the list of Recurring Transactions, but would help wherever there is a button that has a shortcut attached to it.
Can the shortcut key letter be underlined in the button along the bottom of the screen?

**Comment by tactilis** [comment]
> Can the shortcut key letter be underlined in the button along the bottom of the screen?

Hold fire @sharkei2018. That's not the 'right' solution.

There's a bug in MMEX relating to menus and shortcut keys and I will be raising a separate bug report about it soonish (when I get the chance)

**Comment by sharkei2018** [comment]
I've noticed that when a transaction that has a Custom Field is duplicated, the new transaction isn't populated with the Custom Field value.

![Duplicate Transaction without Custom Field](https://user-images.githubusercontent.com/44469703/152357762-659b9889-a4ad-4a94-a7cd-7080bfb3c8e3.jpg)

@tactilis for information

**Comment by whalley** [comment]
Same applies to cut/paste operations..
