### ISSUE TITLE
Add to Account Details

### ISSUE THREAD

**Issue by sharkei2018** [moneymanagerex/moneymanagerex#4126]
# Description of the feature

When adding or editing an account, under account details, Others, as well as Account Number, Held At etc, I would like a field to enter Sort Code.
![Edit Account Money Manager](https://user-images.githubusercontent.com/44469703/151015442-4c81348d-3353-420e-a9ea-815fb15f7ac5.jpg)

**Comment by whalley** [comment]
As bank account numbers differ globally unless you use the [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number) it would be unwise to specify a [sort-code](https://en.wikipedia.org/wiki/Sort_code) as these tend to be UK & Ireland focused.

I prefix the sort code to the account number, any reason why this would not work for your use-case?

e.g. enter something like 11-22-33 12345678

**Comment by sharkei2018** [comment]
Good thinking @whalley and @tactilis .  I should have checked to see if the Account Number field was limited to numbers, but as it will accept all characters, then your suggestion will resolve my feature request.  So simple, but I just hadn't thought of it! :)
Thanks.
