### ISSUE TITLE
DUPLICATED TRANSACTIONS

### ISSUE THREAD

**Issue by stantheman1** [moneymanagerex/moneymanagerex#4132]
>Hi
I get the occasional problem of DUPLICATED TRANSACTIONS appearing in my bank accounts.

I have to delete them as the balance on the account is incorrect.

Have you had this problem reported by other customers please?

Regards

Stanley Pearce

**Comment by tactilis** [comment]
@stantheman1

Not enough information to help you yet.

1. Are you manually entering transactions or importing them from a CSV/QIF file?

2. Do they appear straight away, or do you notice them at a later point?

3. Are the duplicated transactions Deposits/Withdrawals, or are they Transfers?

4. Might you be accidentally copy & pasting the transactions to create duplicates?

**Comment by stantheman1** [comment]
Hi
Please see my replies below.

**Comment by tactilis** [comment]
The above answers all noted.

@stantheman1 Could you post a screenshot of the account showing a transaction that you entered and its duplicate please.

**Comment by tactilis** [comment]
@stantheman1 Another question:

Have you perhaps inadvertently created a Recurring Transaction that is periodically generating transactions in the affected account, which therefore look like duplicates (except for the date)?

**Comment by stantheman1** [comment]
Sorry Martin, I have already corrected all duplicate entries in order to
have correct bank balance.
Just wondering if anyone else is having the same issue.
Regards
Stanley Pearce

**Comment by whalley** [comment]
@stantheman1 I've certainly never encountered this, especially if they have been manually entered. Are you sure you are not making entries in your sleep :-)  

Seriously, if this happens again the take a screen snapshot noting the actual transaction numbers.

**Comment by tactilis** [comment]
@stantheman1 
> Sorry Martin, I have already corrected all duplicate entries in order to have correct bank balance.

That's unfortunate from the point of view of finding and solving the problem. 

As @whalley says, if you ever have duplicate transactions again, please report them here and so we can investigate for you.

Note that if you mark the duplicates with a status of Void, then they won't be counted as part of your balance. You can then easily delete them _after_ we have worked out where they are coming from.

**Comment by stantheman1** [comment]
OK thanks

**Comment by whalley** [comment]
@stantheman1  - I'll close for now, but if this occurs again please re-open and post your screenshots.
