### ISSUE TITLE
UI enhancement - Position of Frequently Used Notes button on Transaction dialog 

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4139]
This is a proposal for a small UI enhancement aimed at:
1. Helping new users understand the operation of the Frequently Used Notes button on the Transaction dialog.
2. Making the arrangement of the Frequently Used Notes, Users Colours, and Attachments buttons more logical.

It does not involve any functionality changes - only the layout of the buttons.

It is prompted by my own confusion about the purpose of the Frequently Used Notes button when I first started using MMEX, and some posts on the forum which show that other users have had similar initial confusion.

Here's the bank account New Transaction dialog _before_ any notes have been added to previous transactions in the account.

If you hover the mouse pointer over the button as shown, no tooltip is displayed because the button is insensitive. The purpose of the button is therefore a complete mystery:
![image](https://user-images.githubusercontent.com/4060092/151697435-62242abb-f5da-4705-bab9-1b817012634f.png)
 
Here's the dialog _after_ some notes have been added to a previous transaction in the account.

It's only after the user has added some notes that they can discover what the button is for:
![image](https://user-images.githubusercontent.com/4060092/151697514-671ecbe6-b15d-4740-a4f5-17689b4bc8ff.png)
 
I propose that we rearrange the buttons as shown here:
![image](https://user-images.githubusercontent.com/4060092/151697710-49b41c0d-b1fb-4ba7-9527-13b724e50904.png)

The positioning of the Frequently Used Notes button next to the Notes label suggests that it has something to do with notes, even if it is initially insensitive and there is no tooltip.

I have also swapped the order of the Users Colours and Attachments buttons. To my mind, the colour of a transaction is an _attribute_ of the transaction itself, so the button comes first, whereas attachments feels like they _'hang on the end'_ of the transaction, so the button should be placed last.

It's a small change to the dialog, but IMO, improves comprehension.

Note that the Recurring Transaction dialog has a similar arrangement of Frequently Used Notes, Users Colours, and Attachments buttons, so if this proposal is accepted, then that dialog should be updated similarly.

Also, on the Recurring Transaction dialog, the Notes label and the buttons are positioned too far above the Notes entry field. The positioning is not consistent with the label and buttons on the normal Transaction dialog discussed above. It's just UI polish, but it helps make MMEX look like a professional product.

![image](https://user-images.githubusercontent.com/4060092/151698140-30dbc733-44c7-4e4f-a6a0-0beed76e2a2f.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/152372655-e06aad28-45a2-476c-87cc-60dd728e0f13.png)

**Comment by tactilis** [comment]
That's great. Thanks @whalley
