### ISSUE TITLE
Suggestion: Change string "repeating" to "recurring" (transactions)

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#414]
I believe the term "recurring" is more often used in relation to financial transactions so I'd suggest the visible labels to be renamed accordingly.
Some users also mention "recurring" here in the issue list so it seems that the term is a bit more suited for the purpose.

**Comment by guanlisheng** [comment]
I second this change, totally.
@moneymanagerex/desktop-mmex-team , what's your option?a

**Comment by siena123** [comment]
I am fine using either term but I belief "recurring" is more grammatically correct.

**Comment by stef145g** [comment]
I agree to the change.

**Comment by guanlisheng** [comment]
@MisterY , we think this request does make sense and we will make this change in v1.2.0 release.

**Comment by MisterY** [comment]
Thanks guys! :+1: 
We've got the same thing ready in the Android version and waiting for your go-ahead.
