### ISSUE TITLE
Selection List for Number Field when Creating or Editing Transactions

### ISSUE THREAD

**Issue by sharkei2018** [moneymanagerex/moneymanagerex#4144]
It's coincidental that Martin has made proposal #4139, as I have been looking at the functionality of the 'Frequently Used Notes' with regard to possibly replicating it for the 'Number' field.

I don't remember the last time I had a transaction that had a transaction number, like a cheque number to identify it, as bills are paid and purchases made using methods other than cheques.  I should say at this point that I am in the UK and use Internet Banking a lot.  
So for a long time I have been entering one of the following in the 'Number' field for each transaction - Direct Debit, Standing Order, Manual Transfer, Faster Payment, Online Payment, ATM, Direct Deposit, Direct Transfer, Debit Card and maybe others.

As you can imagine, that's a lot of typing, and I was going to ask if there was any way of providing a selection list for the 'Number' field via a button, in a similar way to how the 'Frequently Used Notes' button works for the 'Notes' field.  This additional button would be alongside the 'Populate transaction number' button which would still be needed for those MMEX users who do still have sequential numeric references to identify the transaction with their financial organisation.

If this was possible, then strictly the description 'Number' wouldn't be quite accurate and maybe 'Identifier' would be better?

'Frequently Used Notes' are currently listed for the particular account that the transaction is being created in, although I would have thought that the same note might apply to more than one account.  The way that I am using the 'Number' field is certainly not account specific and applies to the whole of the MMEX database.

If implemented it would require changes to all the Transaction windows, both single and recurring where the 'Number' field appears.

I hope this makes sense and shall be interested to hear what others think about this as an enhancement for MMEX - it would certainly help me to create a transaction faster :)

**Comment by tactilis** [comment]
@sharkei2018
A couple of thoughts:

> the description 'Number' wouldn't be quite accurate and maybe 'Identifier' would be better?

There is already an ID column (you may have hidden it) that is the MMEX transaction ID, so Identifier is probably not a good choice of name.

>  have been entering one of the following in the 'Number' field for each transaction - Direct Debit, Standing Order, Manual Transfer, Faster Payment, Online Payment, ATM, Direct Deposit, Direct Transfer, Debit Card and maybe others.

Have you explored Custom Fields?

Look at Tools | Custom Fields Manager...

It would allow you to create exactly the selection list that you want. Here I've created a Type field:

![image](https://user-images.githubusercontent.com/4060092/151709830-f20cb97a-f2c4-40ae-841f-55e33652822a.png)

And here is the custom field in use:

![image](https://user-images.githubusercontent.com/4060092/151709881-07fa2b2e-d9f4-401d-b21a-1537651091d9.png)

You can, of course, drag the user defined Type field to wherever you want in the transaction list. It does not need to be at the end.

**Comment by sharkei2018** [comment]
Thanks for that information Martin and the work you did to create the example Custom field.

To answer your point about the description/name of the field, then as ID and Type are already being used, something like Bank Reference might describe it better?

You have identified a (big) gap in my knowledge about the features of MMEX - I didn't know that Custom fields could be created, not having seen anything about them.  Is there anything in the MMEX User Manual that I'm missing?
Since becoming aware of Custom Fields, I've searched the community pages and they haven't proved very helpful either.  There could be other functionality that I'm ignorant about as well!

Are Custom Fields available on the Recurring Transactions screens?  I've looked for a 'Show/Hide' arrow like the one on the Single Transaction screen, but can't see it.

You say that the custom field can be dragged to wherever you want in the transaction list.  I haven't been able to do that - I can't find a way to select it and then drag.

I think you're right though.  If I could add a Custom field to Recurring Transactions as well as Single ones, then I could use that functionality.

Thanks for your continuing help to make MMEX better.

Keith

**Comment by tactilis** [comment]
@sharkei2018
I'll answer each of your points in turn...

> as ID and Type are already being used, something like Bank Reference might describe it better?

A field name of 'Type' is not already being used by MMEX.  'Type' is just the name of a Custom Field that I created as an example to show what _you_ could do. You can call your custom field 'Bananas' if you like; it's _your_ field so can have _your_ choice of name.

> You have identified a (big) gap in my knowledge about the features of MMEX - I didn't know that Custom fields could be created, not having seen anything about them. Is there anything in the MMEX User Manual that I'm missing?

That's currently a problem. MMEX has a lot of functionality, some of which is not covered at all in the documentation. Custom Fields is one example.

I tend to discover MMEX capabilities by reading posts on the forum (or here on github) and, most importantly, by exploring the menus (top level menus and right click) throughout the app. Then experiment on a dummy database (not your main one).

What we really need is someone to act as a technical author to help write the missing bits of the manual.
Care to help as you discover things? A fresh pair of eyes is always useful.

> There could be other functionality that I'm ignorant about as well!

Yes. I'm sure.
And for me too, I'm sure.

Just keep experimenting and then ask questions here.

> Are Custom Fields available on the Recurring Transactions screens? I've looked for a 'Show/Hide' arrow like the one on the Single Transaction screen, but can't see it.

Custom fields are not currently available when you _create_ a recurring transaction. Each time a recurring payment is due, a new single transaction is generated in the appropriate account. You can then edit that transaction to edit the custom field.

If you use recurring transactions a lot and would find it useful to set the custom field value when you _create_ the recurring transaction, then you could raise an enhancement request. However, I'd urge you to fully explore the use of custom fields first and sort out your workflow before requesting the development of a new feature.

> You say that the custom field can be dragged to wherever you want in the transaction list. I haven't been able to do that - I can't find a way to select it and then drag.

You do it in the same way you drag columns in Windows Explorer (or virtually any other application with a grid view)...

https://user-images.githubusercontent.com/4060092/151863577-a45774dc-836e-475f-9065-d083dbdb3f66.mp4

**Comment by tactilis** [comment]
> Thanks for your continuing help to make MMEX better.

It's almost 100% @vomikan and @whalley who actually _make_ MMEX better.

I and others just help by finding bugs and putting forward proposals for enhancements.

**Comment by sharkei2018** [comment]
@tactilis 
My turn to comment in turn, lol.

The Edit Transaction screen above _describes_ 2 of the fields as Type - the 3rd one where you can select Withdrawal, Deposit, Transfer and your Custom Field.  I assume that the MMEX database stores the field with a different name from the one displayed.

I'm not sure my skills would allow me to become a technical author and write documentation from scratch.  For example I don't know what some of the words in the Custom Field screen mean (RegEx for example), but I'm always happy to review documentation before it's published.  Maybe in the future I will feel confident enough to give it a try :).

I will take your advice and have a look through the MMEX menus to see if there is any functionality that I'm not aware of that would help me manage my finances.

I misunderstood your comment about being able to drag the custom field.  I thought you were referring to the position on the _Edit_ Transaction screen rather than the _List of_ Transactions screen.  I _did_ know how to drag a column to a different position.

I have over 100 Recurring Transactions which get generated every month, so editing the custom field for each of those is not practical.  I need to be able to set a custom field value when I create the Recurring Transaction or carry on manually typing the string into the Number field as I do now.

I see that this was looked at previously 'Cannot set custom fields in recurring transaction template #1595' and then here 'Custom Fields improvements #1585'.  My reading at the end of #1585 is that this is still an ongoing issue and it looks like vomikan might have added it to the v1.6.0 milestone?

Thanks for your patience and continued support.

**Comment by tactilis** [comment]
@sharkei2018 
> The Edit Transaction screen above describes 2 of the fields as Type - the 3rd one where you can select Withdrawal, Deposit, Transfer and your Custom Field. I assume that the MMEX database stores the field with a different name from the one displayed.

'Type' is just a _label_ on the  Withdrawal, Deposit, Transfer dropdown. It doesn't matter how it's handled in the database. That an internal detail that should be (and is) hidden from users. You can see in the example Custom Field I created above that you can name it 'Type' with no problems. Again, it shouldn't matter to users how that's handled internally in the database.

But just in case you are still concerned...   :grinning: 

![image](https://user-images.githubusercontent.com/4060092/151955225-3be52e83-e4b9-4575-bf7b-b75591c6c877.png)
 
  
> I'm not sure my skills would allow me to become a technical author and write documentation from scratch. For example I don't know what some of the words in the Custom Field screen mean (RegEx for example)

Adapting some words that @dbolton wrote in the forum:

RegEx (short for "Regular Expression"): This is a 'pattern' that is used to validate inputs. For example if you created a custom field called "Web link" (e.g. a link to a photo of a purchase receipt maybe), you might want to require that the field starts with "https://". The regular expression for that would be:

```https:\/\/.*```

If you haven't used Regular Expressions before, here's a good resource: http://www.regular-expressions.info/quickstart.html
And here is a site where you can test RegExs: https://regex101.com/

**Comment by tactilis** [comment]
@sharkei2018 
>I have over 100 Recurring Transactions which get generated every month, so editing the custom field for each of those is not practical. I need to be able to set a custom field value when I create the Recurring Transaction or carry on manually typing the string into the Number field as I do now.

With that many Recurring Transactions, I think you have demonstrated a very good use case for being able to add custom fields.

> I see that this was looked at previously 'Cannot set custom fields in recurring transaction template #1595' and then here 'Custom Fields improvements #1585'. My reading at the end of #1585 is that this is still an ongoing issue and it looks like vomikan might have added it to the v1.6.0 milestone?

#1585 covers a lot of things, some of which are implemented, some are not. The v1.6.0 milestone just means that it's a good idea but implementation is some way off.

I'll raise a new enhancement request, specifically for Custom Fields support in Recurring Transactions and reference this conversation.

**Comment by sharkei2018** [comment]
@tactilis 

Will you check something for me please.

1. I reposition a Custom Field column in a Transaction list,

![Custom Field 1](https://user-images.githubusercontent.com/44469703/152036066-4e3448f4-4430-4505-8fdb-6c74efb700d0.jpg)

2. I close MMEX,
3. I open MMEX and the Custom Field has reverted to the last column.

![Custom Field 2](https://user-images.githubusercontent.com/44469703/152036153-150325a2-fa96-4a9b-afb3-1f5bcb484d6b.jpg)

Does the same thing happen for you?

Thanks for creating #4159

**Comment by tactilis** [comment]
@sharkei2018 
It's not just the position of Custom Field columns that are not remembered when MMEX is closed and reopened. If you change the order of _any_ columns, the new order is not saved.

If you right click a column heading and Hide/Show columns, then that _is_ saved.
Similarly, if you change a column width, then that is also saved.

IMO, column order should be saved. I've raised #4160

**Comment by tactilis** [comment]
@vomikan This issue can be closed.

The OP's problem was dealt with and #4159 & #4160 were raised to track the additional items that were discussed.
