### ISSUE TITLE
Feature: Remember the last Amount along with the last Category 

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#415]
Originally posted to the Android version, https://github.com/moneymanagerex/android-money-manager-ex/issues/45, but I see that this would require a database change so I'm posting here as well to see whether it fits with the overall goals.

A combination of 
- saving the last amount and 
- the preference setting of whether to use the saved amount for new transactions when the Payee is selected

would be great.

**Comment by guanlisheng** [comment]
I don't think it's a valid request since the amount should vary.

**Comment by AlessandroLazzari** [comment]
I agree with the comment by guanlisheng

**Comment by guanlisheng** [comment]
@MisterY  would we close it ?

**Comment by MisterY** [comment]
Sure. The "duplicate transaction" feature makes up for it.
