### ISSUE TITLE
Summary Report - mismatch between Chart pop-up and raw data

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#4150]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

There appears to be a mismatch with the chart pop-up and the raw data

# Reproduction
Hover mouse over the chart and I get the following...
![Screenshot 2022-01-31 144931](https://user-images.githubusercontent.com/24897056/151816201-0eaf7478-ea5c-4756-971e-8d4633066393.png)
This does not match the data list
![Screenshot 2022-01-31 145001](https://user-images.githubusercontent.com/24897056/151816292-3bf8ea6f-b544-499e-a8a7-ac26307739a7.png)

Stocks and Assets are the wrong way round. My database has never contained Assets so always expect zero.

Is the bug reproducible? 
 - [x] Always in 1.5.12 and Master
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by grumpy235** [comment]
@whalley Many thanks for the quick fix. No big deal but the chart numbers are also a penny higher then the raw data, I assume due to a difference in rounding method ?

**Comment by whalley** [comment]
Rounding issue should be fixed.
