### ISSUE TITLE
Incorrect last day for "show last month" menu item

### ISSUE THREAD

**Issue by k7s5a2** [moneymanagerex/moneymanagerex#4155]
MMEX version:
 - [x] 1.5.12

Operating System:
 - [x] Windows

# Description of the bug
no transactions between 28.01.2022 to 31.01.2022 when "show last month" is selected

# Reproduction
Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
1. open any account
2. switch show button to "show last month"
3. dates are visible only to 28.01.2022 - 1.png
4. switch show button to "show last 30 days"
5. dates are visible to 31.01.2022 - 2.png

Expected result:
all transactions visible

Actual result:
lack of transactions from 29.01.2022 to 31.01.222

attached files
![2](https://user-images.githubusercontent.com/98802697/151929544-1c057c22-3c87-46dc-b362-6ef78640aca2.png)
![1](https://user-images.githubusercontent.com/98802697/151929547-52af71cc-7924-4f50-b65c-41ef39b03abf.png)

**Comment by whalley** [comment]
Looks like this commit broke things - https://github.com/moneymanagerex/moneymanagerex/commit/4df6df39e1fa9072533d4c823efb0d45b98bebcc#diff-250e25059d55de8faffb719c2c3ace9092d06501aa07a8f0c672d4b612287a7f

**Comment by SanTaSoft** [comment]
It seems that the new version doesn't save anything. I have worked with Stocks and added a few transactions, but when I reopened the app, nothing seemed to be there

**Comment by tactilis** [comment]
The above comment is in the wrong Issue.

Now raised in #4157

**Comment by whalley** [comment]
@vomikan See you have picked this up. I think the 'mmDate' code has got a little messy over time (I may of course be responsible for some of this :-) ... Think the key thing is to nail down the End Date and then work back.

**Comment by Giacomo8023** [comment]
ho provato a fare quello che dicono ma non cambia nulla anche creando un nuovo database.- Come si può risolvere

**Comment by vomikan** [comment]
We need to test the dates more carefully. I applied a simple fix, hopefully successfully. If there is anything else to fix, please don't hesitate.

**Comment by Giacomo8023** [comment]
> Dobbiamo testare le date con maggiore attenzione. Ho applicato una soluzione semplice, si spera con successo. Se c'è qualcos'altro da sistemare, non esitare.

cosa faccio allora???

**Comment by vomikan** [comment]
There are installers for Windows available now:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/42415960/job/brqe1b3w4jqqvebo/artifacts

**Comment by Giacomo8023** [comment]
Grazie mille ora a ripreso a funzionare correttamente

**Comment by whalley** [comment]
> We need to test the dates more carefully. I applied a simple fix, hopefully successfully. If there is anything else to fix, please don't hesitate.

I've re-read the code and done some further testing and all looks good now. Just bad luck that Dec and Jan had 31 days!

**Comment by vomikan** [comment]
13 moon harmonic calendar would save us from such a misunderstanding.
![image](https://user-images.githubusercontent.com/6836805/152049200-ec273ab5-ecdc-43b1-94db-0f4dafa6d872.png)

**Comment by tactilis** [comment]
> 13 moon harmonic calendar would save us from such a misunderstanding.

I'll raise a feature request :smiling_imp:

**Comment by whalley** [comment]
> > 13 moon harmonic calendar would save us from such a misunderstanding.
> 
> I'll raise a feature request 😈

Don't you dare!
