### ISSUE TITLE
Error de traduccion

### ISSUE THREAD

**Issue by Josmanmale** [moneymanagerex/moneymanagerex#4156]
Buenos dias
La última actualizacion no tiene traducido al español el apartado Detalle, al introducir o duplicar un nuevo importe en el apartado Detalle de la transacion, solo sale en ingles
Saludos

<hr>Version: 1.5.12 64-bit<br>
 • Build: Ene 30 2022 16:07:10<br>
 • db 7 •  (aes128cbc)<br>
 • git 41c490f (2022-01-30)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Spanish (Modern) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by vomikan** [comment]
https://crowdin.com/project/moneymanagerex/es-ES

Cualquiera puede registrarse en esta plataforma y contribuir a la traducción.
