### ISSUE TITLE
MMEX apparently doesn't save anything

### ISSUE THREAD

**Issue by SanTaSoft** [moneymanagerex/moneymanagerex#4157]
MMEX version:
 - [x] 1.5.12
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I added transactions and Stock options, but when I reopen the app, they don't seem to be there. It asks the recurring transactions to be added as well every time.

# Reproduction

Basically add anything, then close the app and reopen it.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open the app
2. Add transactions / stock 
3. Close the app
4. Open it again

Expected result: The added transactions / stocks are there

Actual result: No transactions or stocks added in the last session are there

# Additional information

My database is on a network drive

**Comment by tactilis** [comment]
@SanTaSoft
> My database is on a network drive

Have you tried creating a new database for test purposes on a local drive? Do transactions you enter there get saved and are visible when you next open MMEX?

**Comment by Dandy64** [comment]
Well, I have the last version of MMEX - 1.5.12. I don't use Stock options, but all other transactions, including recurring, were saved with no problem.

I use a portable version (64) running from a USB stick.

**Comment by Giacomo8023** [comment]
ho provato a fare quello che dicono ma non cambia nulla anche creando un nuovo database.- Come si può risolvere

**Comment by SanTaSoft** [comment]
So what I could collect so far:
After installation, up from version 1.5.9, the first run could not see network drives.
![image](https://user-images.githubusercontent.com/10990940/151999533-7a6dbf56-675b-4d0f-9b4f-3fd327f95009.png)

But after I close it and reopen the app, it can see everything. Probably when I first opened the app after installation, and it said it could not find the database, I opened a backup maybe (that's on me).
When I can actually open the correct database, it seems to contain the correct data.

**Comment by Giacomo8023** [comment]
nulla.- non è cambiato nulla.-

**Comment by tactilis** [comment]
@Giacomo8023 
> ho provato a fare quello che dicono ma non cambia nulla anche creando un nuovo database.- Come si può risolvere

_"I tried to do what they say but nothing changes, creating a new database.- how can it be solved"_

> nulla.- non è cambiato nulla.-

_"nothing. - nothing has changed."_

It's not clear at all what problem you are having @Giacomo8023 

Nobody can help you unless you explain _exactly_ what is happening for you.

**Comment by Giacomo8023** [comment]
il mio problema è quello indicato nella discussione.- In pratica inserendo le transazioni con data dal 29/01/2022 al 31/01/2022 le stesse non appaiono nella schermata "mostra il mese scorso" mentre appaiono nella schermata "mostra tutte le operazioni" Questo bug si è presentato con la nuova versione che ho installato mentre con la vecchia andava tutto bene.- Per capire vi allego schermate.- Grazie Ho risposto nella modo sopraindicato perchè ho seguito delle possibili soluzioni ma non è cambiato nulla.- Grazie.-
![2](https://user-images.githubusercontent.com/98830384/152019056-958d7a1b-19cb-4805-8157-0c3fe92fd76f.png)
![1](https://user-images.githubusercontent.com/98830384/152019060-b7ace7fa-8d97-48d0-9171-e33ff61c7111.png)

**Comment by whalley** [comment]
This is 

> il mio problema è quello indicato nella discussione.- In pratica inserendo le transazioni con data dal 29/01/2022 al 31/01/2022 le stesse non appaiono nella schermata "mostra il mese scorso" mentre appaiono nella schermata "mostra tutte le operazioni" Questo bug si è presentato con la nuova versione che ho installato mentre con la vecchia andava tutto bene.- Per capire vi allego schermate.- Grazie Ho risposto nella modo sopraindicato perchè ho seguito delle possibili soluzioni ma non è cambiato nulla.- Grazie.-

my problem is the one indicated in the discussion. - In practice, by inserting the transactions with date from 01/29/2022 to 01/31/2022 they do not appear in the "show last month" screen while they appear in the "show all operations" screen "This bug occurred with the new version that I installed while everything was fine with the old one. - To understand I am attaching screenshots. - Thanks I answered in the way indicated above because I followed the possible solutions but nothing has changed. - Thanks. -

So this is the bug #4155 which is now fixed.

**Comment by Giacomo8023** [comment]
si confermo e stato risolto con la versione "beta"

**Comment by tactilis** [comment]
> si confermo e stato risolto con la versione "beta"

I confirm and have been solved with the "beta" version.
