### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4162]
![image](https://user-images.githubusercontent.com/6836805/152153911-1990b9b4-ff12-4643-a3e3-b8a56140efc4.png)
Has anyone encountered this?

I've changed 1.5.13 to the draft state

![image](https://user-images.githubusercontent.com/6836805/152154321-86a974b4-1966-4a3f-8d6b-77044a57184e.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/152154536-2ebfbbdf-aad0-4026-85d0-c5d2acee09f3.png)

**Comment by whalley** [comment]
That is an old build (v1.3.3) and I don't think we released a v1.3.7, so no idea what is going on there !!!!!

**Comment by tactilis** [comment]
@vomikan Has the person raising the problem been asked to completely un-install MMEX and then do a fresh re-install (instead of an upgrade)?
