### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by PaulusThe1** [moneymanagerex/moneymanagerex#4163]
I use MoneyManagerEX from many years because is wonderful. I have also Android version (latest version 2019.02.19.995), but this version seems not run correctly on Android 12. Why you don't develop a new Android version?

Thanks for your attention

P.s.: Sorry for my English

**Comment by whalley** [comment]
Hi @PaulusThe1  - The Android version has not kept pace with the desktop version due to lack of developers able/willing to support it.

@vomikan I can't seem to transfer the issue to the Android app issue tracker, perhaps you can.
