### ISSUE TITLE
Monthly budget doesn't include monthly estimations of the annual budget

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#4165]
# Description of the feature

I created an annual budget, with a monthly estimation of Netflix subscription, and after that I created a monthly budget that depends on the annual budget, but the monthly budget doesn't include the estimation of the Netflix monthly subscription added on the annual budget.

If you create an annual payment that is established as monthly, should be included in the monthly budget IMO.

Annual budget: 
![image](https://user-images.githubusercontent.com/11770760/152324892-60ed272d-ed6d-4e70-9800-78271d51bd73.png)

Monthly budget of February:
![image](https://user-images.githubusercontent.com/11770760/152324950-ce9d8923-0437-41f1-bdc4-03b3d0f24a6b.png)

In the February budget, it should show an estimation of "-10", as established on the annual budget.

# Use cases

With the current implementation makes that your monthly budget is not complete since you have to check also the monthly estimations that are on the annual budget.

Not sure if this is a bug or the expected behaviour so opening as a feature request.

**Comment by BanCrash** [comment]
@whalley sorry for the misspelling and the bad translations, I will refrain to open more PRs until my brain can be fully focused on the writing :/

**Comment by whalley** [comment]
> @whalley sorry for the misspelling and the bad translations, I will refrain to open more issues until my brain can be fully focused on the writing :/

@Bancrash - Not a problem at all, I only edited to make it easier for others to read, I appreciate you posting in English in the first place given if it is not your native language.

**Comment by whalley** [comment]
I'm not an expert of the MMEX budget functionality and don't use it, others who do may be able to comment further. However having look at the logic used it would seem that the Yearly and Monthly budget entries are use independently when setting up and reporting. I suspect that was the design.

There have been requests to improve the setup of budgets, e.g. #3258

**Comment by BanCrash** [comment]
> I'm not an expert of the MMEX budget functionality and don't use it, others who do may be able to comment further. However having look at the logic used it would seem that the Yearly and Monthly budget entries are use independently when setting up and reporting. I suspect that was the design.
> 
> There have been requests to improve the setup of budgets, e.g. #3258

If that is the case what does this setting?

![image](https://user-images.githubusercontent.com/11770760/152600824-48980ac0-0a0f-4dcf-b69c-781f01bd3562.png)

I thought that when you base your monthly budget on an annual budget it would get the monthly estimations that are already established.

Sorry if it's a dumb question, I checked the [wiki](http://github.moneymanagerex.org/moneymanagerex/docs/en/budget.html) but didn't see an answer.

**Comment by whalley** [comment]
All that does is take a copy of an existing Year (or monthly) budget setup and duplicates in the Year/Month budget you are creating.

**Comment by BanCrash** [comment]
> All that does is take a copy of an existing Year (or monthly) budget setup and duplicates in the Year/Month budget you are creating.

Oh, thank you, now I got it. I did the budget after creating the month thinking that they would be "linked" so when you change something that affects the other it will get automatically updated.

Then I will close this feature request and check if that link is already suggested, and if not I'll open a new one.

Thanks!
