### ISSUE TITLE
I've noticed that when a transaction that has a Custom Field is duplicated, the new transaction isn't populated with the Custom Field value.

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4168]
I've noticed that when a transaction that has a Custom Field is duplicated, the new transaction isn't populated with the Custom Field value.

![Duplicate Transaction without Custom Field](https://user-images.githubusercontent.com/44469703/152357762-659b9889-a4ad-4a94-a7cd-7080bfb3c8e3.jpg)

@tactilis for information

_Originally posted by @sharkei2018 in https://github.com/moneymanagerex/moneymanagerex/issues/4124#issuecomment-1029023119_

**Comment by whalley** [comment]
Same applies to cut/paste operations.

**Comment by tactilis** [comment]
@whalley Attachments are not cloned when a transaction is duplicated (or copy/pasted)

I think they should be.  i.e. the duplicated transaction should be an exact clone

Thoughts?

**Comment by sharkei2018** [comment]
I agree with @whalley, a duplicated transaction should be identical to the original.  However, if you have a look at the definition of a clone on the various dictionary internet sites, it is sometimes described as a _similar_ copy rather an _identical_ one.

**Comment by tactilis** [comment]
@sharkei2018 
> However, if you have a look at the definition of a clone on the various dictionary internet sites, it is sometimes described as a similar copy rather than an identical one.

Perhaps. But is not relevant to MMEX.

The term "clone' is just used internally to mean make a copy.
