### ISSUE TITLE
Useful additions

### ISSUE THREAD

**Issue by FelixofTarn** [moneymanagerex/moneymanagerex#4170]
# Description of the feature

An End of Year rollover would be  extremely useful. I don't like the idea of the database filling up with year upon year. An end of year rollover reoport is an extremely useful accounting tool.
Secondly. This can be done another way by creating a new database. However, whilst balance are easy to enter recurring transactions, payees and categories cannot be exported, this means manually entering these 'by hand'. Also the ability to export account information.
The addition of these would help with the end of year process.
Thank you

Please describe your feature with details.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1297

**Comment by TomAff** [comment]
Hey don't you make a copy of your database and delete the postings?

**Comment by vomikan** [comment]
Apparently, there is a lot of manual work on transferring the balance sheet.

https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances
This report can help in determining the balances for a certain date.

You can also make a script that will do this automatically.
You can launch it from the application through this menu.
![image](https://user-images.githubusercontent.com/6836805/152642928-8232ac8f-4035-40f6-b068-293c95135ac8.png)

**Comment by Dandy64** [comment]
_"Apparently, there is a lot of manual work on transferring the balance sheet.
https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances
This report can help in determining the balances for a certain date."__

By the way, there is a small bug in this report.
I have 3 accounts:
One was defined in NIS currency.
The second one was defined in Pounds.
The third one was defined in Swiss Franc.

But the Balance is shown like all 3 accounts are in NIS (New Israeli Shekels).

![image](https://user-images.githubusercontent.com/83161661/152648959-57664c4d-0250-42d2-b591-feb48918af07.png)

**Comment by vomikan** [comment]
@Dandy64 is currencies rate updated?

**Comment by Dandy64** [comment]
Yes, the currency rate was updated.
I have taken the Account Balance report from the URL you posted above:
https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances

Your report looks a bit different. Where have you downloaded it from?

**Comment by vomikan** [comment]
@Dandy64 I did not download this report, it is included in the distribution.
![image](https://user-images.githubusercontent.com/6836805/152654486-d9908e3e-21de-416c-9917-2f194766a103.png)

![image](https://user-images.githubusercontent.com/6836805/152654514-256c455a-0c65-414f-8987-0fdaac85b18c.png)

First one
![image](https://user-images.githubusercontent.com/6836805/152654526-459135c3-52fc-4cd3-b0e9-1a8d6ac76340.png)

**Comment by Dandy64** [comment]
It looks like I did too many unnecessary things. :-)) I have found a very stupid and complicated way!
Thanks, I will check it immediately.

**Comment by vomikan** [comment]
The files were added to the distribution relatively recently. Previously, there was no such option and I had to download files.

**Comment by Dandy64** [comment]
The report works without problems. Probably, I missed a press release and I did knot know that it was added an option to import reports, so I was doing it in the old manner. Thank you!

**Comment by whalley** [comment]
Will be tracked as part of https://github.com/moneymanagerex/moneymanagerex/issues/1297
