### ISSUE TITLE
last month transactions

### ISSUE THREAD

**Issue by aleksandra83110** [moneymanagerex/moneymanagerex#4173]
> When i want to see last month transactions it shows only transactions made until 2022-01-28 when it should show until 2022-01-31
![bug1](https://user-images.githubusercontent.com/99023707/152529427-98d10fba-22ca-4a92-b140-f8c6a2e6d2e5.png)

<hr>Version: 1.5.12 64-bit<br>
 • Build: sty 30 2022 16:07:10<br>
 • db 7 •  (aes128cbc)<br>
 • git 41c490f (2022-01-30)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  Polish (windows-1250)<br>
 • 1920x1200 32bit 96x96ppi

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4155
