### ISSUE TITLE
Creating a new transaction with Custom Field

### ISSUE THREAD

**Issue by sharkei2018** [moneymanagerex/moneymanagerex#4176]
A proposal for a minor enhancement to entering a new transaction.

When a new transaction is entered the following window is displayed for the User to complete:

![New transaction window](https://user-images.githubusercontent.com/44469703/152635956-c9750b0b-37e0-421e-bc4b-83115a0b55f9.jpg)

If Custom Fields have been created, then it is likely that the User will want to enter a value(s) in the Custom Field(s), so the following expanded window should be opened automatically, rather than the User having to click the right-hand arrow alongside OK / Cancel buttons.

![New transaction window expanded](https://user-images.githubusercontent.com/44469703/152636046-5f84a61d-23c8-4d84-8ebb-fe739c5792cc.jpg)

I know it only saves 1 click but ...... :)

**Comment by tactilis** [comment]
> If Custom Fields have been created, then it is likely that the User will want to enter a value(s) in the Custom Field(s),

I don't agree.

I use custom fields but I enter values for them for only a subset of transactions.

I would not want the expanded dialog to appear every time I entered a new transaction.

Note that the expanded dialog _is_ displayed if you view a transaction that already has custom field values set.

**Comment by vomikan** [comment]
Initially, I set such logic that the window appears only if  custom fields are filled in.
You can make it appear every time there is at least one field. But I'd rather not change anything.

**Comment by sharkei2018** [comment]
OK @vomikan
