### ISSUE TITLE
Proposed improvemnet to category summary report

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4186]
# Description of the feature

The presentation category summary data is misleading in how it presents category summaries. E.g in the below report the first 'Category Total' appears at first glance to be for all the categories above it. However it does of course only relate to the 'Home' category. You can see the totals and how they are presented. If a category only has one subcategory to report then no 'Category Total' is presented. 
![image](https://user-images.githubusercontent.com/487345/152693095-b129c615-ca59-4ddf-9fb0-e2a2abb5fe26.png)

Whilst we could add a 'Category Total' to all categories this would extend the report rather than keeping concise.

I propose to use row colour highlighting to distinguish between each category and report the total at the end of each category as in the below proposal. This way the category group is clear and removes the need for a 'Category Total'.
![image](https://user-images.githubusercontent.com/487345/152693357-356e1ac6-9398-494a-91b4-370ee0d63d18.png)

What do people think?

**Comment by vomikan** [comment]
Such a change can save paper in some cases when printing a report. At the same time, it does not become clearer.

**Comment by whalley** [comment]
I feel you are right about it not being much clearer.... :-)

If I implement #3998 it should hopefully clearer where we start with the list of Categories and then allow to drill down and expand all or subset of subcategories... 

I'll close this and work on #3998.
