### ISSUE TITLE
Filter out obsolete currencies in Currency Dialog and Currency Exchange Rates

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#4187]
# Description of the feature

The Currency Dialog and Currency Exchange Rates list all currencies used. This includes currencies that belong to _closed accounts_. It would be nice to allow users to filter out these lists to only show currencies for open accounts only.

For instance, in the image below, BCH is no longer used (the corresponding account is closed). I am no longer interested to see this currency, nor the exchange rates for it on the start panel.

![currencies-dialog-unused](https://user-images.githubusercontent.com/1184162/152786279-a982265d-70d4-4997-8907-143183954fa1.PNG)

This was originally implemented in 1.5.3 (following [#3558](https://github.com/moneymanagerex/moneymanagerex/issues/3558)), but has since been reverted.

**Comment by whalley** [comment]
Was reverted as part of #4019

**Comment by vomikan** [comment]
I can't reproduce the 4019 bug, with the following fix.

**Comment by whalley** [comment]
I can reproduce...

1. Create a new account with some random currency (I used Algerian Dinar!)
2. The currency now appears in the list of currencies on the currency dialog
3. Close the account just created
4. The currency is still present in the currency dialog

The change made earlier exclude the currency if there were no open accounts using it.

**Comment by vomikan** [comment]
It seems we understand the problem differently.

I can't reproduse the thing you can.
![image](https://user-images.githubusercontent.com/6836805/153048649-ecbf4107-19f1-4ab7-9a79-858223539579.png)

![image](https://user-images.githubusercontent.com/6836805/153048739-6aaff03f-6879-459e-ac47-bfe3b6f5a516.png)

**Comment by whalley** [comment]
How odd... When I do the same I still get the currency displayed, which would seem to align to this change:
https://github.com/vomikan/moneymanagerex/commit/c4805112dc379e615e1ff036a407479a99807dd6#diff-7f661b4b4e34afb32f45108150038a5dc79830dbac38c029bdbfa2fed5bf284c
![image](https://user-images.githubusercontent.com/487345/153097998-c8c63b4b-65ca-4864-b900-3d5781015d4f.png)

My findings align with that reported by @cmbarbu 

When Yen account open
![image](https://user-images.githubusercontent.com/487345/153097524-cc2e3988-4fd9-4222-bbdc-189cab7e31ba.png)

When Yen account closed
![image](https://user-images.githubusercontent.com/487345/153097619-13b83a9f-d975-4ce7-86ce-2519bf4146dc.png)

**Comment by vomikan** [comment]
@whalley it sems my mistake. I've created a fix but forget it to apply.
Then I've commited it with the next one.
