### ISSUE TITLE
UI scaling issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4188]
![Screenshot_2022-02-08-00-35-50-34_a23b203fd3aafc6dcb84e438dda678b6](https://user-images.githubusercontent.com/6836805/152875907-0cae7bee-9d2c-400c-90b1-f61c5f960889.jpg)

**Comment by whalley** [comment]
Yes, a little scant on information. Is this a High DPI issue scaling issue on Windows?

**Comment by vomikan** [comment]
I've reserved it by FB personal message.
I couldn't get any more useful information besides the screenshot.

**Comment by vomikan** [comment]
I can't reproduce this issue  (mmex 1.5.13) with the following display settings:
![image](https://user-images.githubusercontent.com/6836805/152957050-cf1b38aa-7e49-482b-8a6b-f8f776868d0a.png)

The transaction dialog is looking good
![image](https://user-images.githubusercontent.com/6836805/152957131-d82dfd98-acfb-4020-a13e-87559b2b0462.png)
