### ISSUE TITLE
Categories Monthly Report end date wrong

### ISSUE THREAD

**Issue by PGCBM** [moneymanagerex/moneymanagerex#4189]
MMEX version:
 - [x] 1.5.x
Operating System:
 - [x] Windows

# Description of the bug

I am not sure if there is a setting I am missing but in the Categories Monthly Report the end of the month always shows as 28/mm/yyyy rather than the actual month end date e.g. 31/mm/yyyy for December
# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1.  Go to 
2. Categories Monthly Report
3. Using the move 1 month Date button backwards or forwards 

…

Expected result:  for December 2021 I would expect the till date to show as 31/12/2021

Actual result:  28/12/2021

# Additional information

I can enter the date 28/12/2021 in the Income vs Expenses Monthly - Custom report which then shows all transactions for the month
![MMEX01](https://user-images.githubusercontent.com/99240351/152932030-3b55b975-a65c-497a-b983-043dcee248ea.jpg)

**Comment by whalley** [comment]
Yes, I can see where this is occurring...
