### ISSUE TITLE
Add transaction from account tree directly

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#420]
I think it's pretty intuitive to create a new transaction via the account tree.
![mmex_account_2](https://cloud.githubusercontent.com/assets/721973/6725805/a783339e-ce49-11e4-980d-690585248209.png)

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team  any one want to take this issue?

**Comment by siena123** [comment]
Pull request submitted.

**Comment by vomikan** [comment]
Please use #xxx in a Pull request header. In that case the PR will be referenced in the proper issue topic.
