### ISSUE TITLE
Home Page Customization and home_page.htt

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#4204]
I like to have a minimal home page. I don't need to see the number of transactions. I don't use assets so I don't need to see assets. I don't need to see income vs expenses and the graph. So I modify home_page.htt. But every time there is  a update I have to run MMEX, close it, then update home_page.htt in MMEX.app. On macOS if I don't run the program before updating home_page.htt macOS complains and won't run due to signing.

A quick and easy solution would be to wrap each of the home page widgets in an ID. That way I can control the display of the widgets I don't want using master.css in my custom theme which doesn't change with every update.

Another solution would be to put home_page.htt in the theme files but then if you make a change I may miss out on the change because I would be using home_page.htt in my theme, not the one in your default themes.

![MMEX HP 50](https://user-images.githubusercontent.com/63317977/153735360-fc109c1c-2fa9-4139-b680-f378e54923bd.jpeg)
![MMEX home_page htt 75](https://user-images.githubusercontent.com/63317977/153735388-3539fcd6-8e97-4cef-a680-e6010dd61f13.jpeg)
![MMEX master css 80](https://user-images.githubusercontent.com/63317977/153735401-f2f73d91-7826-440b-ad3d-1982231a8540.jpeg)
[home_page.zip](https://github.com/moneymanagerex/moneymanagerex/files/8054846/home_page.zip)

**Comment by Dandy64** [comment]
I  suppose this is a good idea - Home Page customization. I don't care of the number of transactions and  I don't need to see assets either.
It looks like the best place where user will be able customize the Home Page is Options -> Home
![image](https://user-images.githubusercontent.com/83161661/153744301-cdd9d58d-2491-4708-9b0d-46e2196ca23e.png)
Of course, user doesn't know HTML, so the customization should be user friendly - just checkboxes and dropdown windows: hide/unhide etc...

**Comment by whalley** [comment]
#3918

**Comment by whalley** [comment]
Will be tracked as part of https://github.com/moneymanagerex/moneymanagerex/issues/3918
