### ISSUE TITLE
Option to link a monthly budget to an annual budget

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#4214]
Come from #4165
# Description of the feature

When you create a new monthly budget, would be very useful to have the option to "link" that monthly budget to an annual budget, so one change on one of them affects the other.

Example: You create a new estimation of a monthly expense of 100 € for parking category on the annual budget, then the monthly budget automatically gets updated with 100 € estimated on the same category. 

The opposite should work too, if you edit the monthly budget with an estimation of a monthly expense, the annual budget should get automatically updated too.

# Use cases

This would make more useful the budgets feature since currently annual and monthly budgets are working as different budgets. and with this they will be dependant of each other.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4165

**Comment by vomikan** [comment]
I think it will be a good improvement

**Comment by whalley** [comment]
I propose the following:

- The existing 'Budget Setup' remains the same. You enter Yearly and Monthly budgets.
- We introduce an option to specify how the yearly and monthly budgets estimates interact
  -  MERGE (default) - The yearly and monthly budget estimates are combined, e.g. you can define an annual budget for a category but add (or subtract) more for certain months.
  -  MONTH OVERRIDE - If a budget for a month is defined then it will override the yearly figure, e.g. you can define an annual budget for a category but change it for certain months.

In the 'Budget Performance' and 'Budget Category Summary' reports we only allow the Years to be specified - not sure why we need to monthly budgets to be selectable here. If no yearly budget estimate is setup, just monthly figures, then we can still present that year for selection.

Does that make sense? Any further suggestions.

**Comment by BanCrash** [comment]
> I propose the following:
> 
>     * The existing 'Budget Setup' remains the same. You enter Yearly and Monthly budgets.
> 
>     * We introduce an option to specify how the yearly and monthly budgets estimates interact
>       
>       * MERGE (default) - The yearly and monthly budget estimates are combined, e.g. you can define an annual budget for a category but add (or subtract) more for certain months.
>       * MONTH OVERRIDE - If a budget for a month is defined then it will override the yearly figure, e.g. you can define an annual budget for a category but change it for certain months.
> 
> 
> In the 'Budget Performance' and 'Budget Category Summary' reports we only allow the Years to be specified - not sure why we need to monthly budgets to be selectable here. If no yearly budget estimate is setup, just monthly figures, then we can still present that year for selection.
> 
> Does that make sense? Any further suggestions.

For me that would be just perfect :thumbsup:

**Comment by whalley** [comment]
Have added option:
![CleanShot 2022-09-14 at 00 24 52](https://user-images.githubusercontent.com/487345/190026692-c8c8011e-32e0-4160-b6a7-ba11dc0281b6.png)
If checked then any monthly budget will override the yearly budget, otherwise the monthly budget will be added to the annual budget.

When selecting budgets in the budget reports only years can be specified. The report will merge yearly and monthly budgets based on the above option.
![CleanShot 2022-09-14 at 00 26 39](https://user-images.githubusercontent.com/487345/190026993-a59e06ce-04dc-4e53-848a-9a0d72c35f4c.png)

**Comment by BanCrash** [comment]
> Have added option: ![CleanShot 2022-09-14 at 00 24 52](https://user-images.githubusercontent.com/487345/190026692-c8c8011e-32e0-4160-b6a7-ba11dc0281b6.png) If checked then any monthly budget will override the yearly budget, otherwise the monthly budget will be added to the annual budget.
> 
> When selecting budgets in the budget reports only years can be specified. The report will merge yearly and monthly budgets based on the above option. ![CleanShot 2022-09-14 at 00 26 39](https://user-images.githubusercontent.com/487345/190026993-a59e06ce-04dc-4e53-848a-9a0d72c35f4c.png)

That's nice, thank you!

**Comment by whalley** [comment]
@BanCrash Would be good if you could test this Beta build and report back any issues.
https://ci.appveyor.com/api/buildjobs/jxdaxqbd9xdxq9sk/artifacts/mmex-1.5.21-Beta.1-win64.exe

**Comment by BanCrash** [comment]
> @BanCrash Would be good if you could test this Beta build and report back any issues. https://ci.appveyor.com/api/buildjobs/jxdaxqbd9xdxq9sk/artifacts/mmex-1.5.21-Beta.1-win64.exe

@whalley I don't know if I'm doing something wrong, but I created a new budget on a test database and I can't get my monthly estimation on the yearly budget:

Monthly budget:
![imagen](https://user-images.githubusercontent.com/11770760/190090553-96f55bc5-ff4f-48a2-b5b5-d3c2de862997.png)

Year budget:
![imagen](https://user-images.githubusercontent.com/11770760/190090602-df45ba26-fe1a-45fb-83b1-a2f71352eac2.png)

Settings:
![imagen](https://user-images.githubusercontent.com/11770760/190090698-8f54877f-05e1-44ef-af9a-1cf37a66cc61.png)

I've tried with the setting enabled or disabled, but there is no difference on the behaviour.

![imagen](https://user-images.githubusercontent.com/11770760/190090926-e93df97f-f1f7-47fe-8d6c-520b550da82f.png)

**Comment by whalley** [comment]
As noted above...

> The existing 'Budget Setup' remains the same. You enter Yearly and Monthly budgets.

The 'budget' is entered as yearly and/or monthly, it is only when creating the budget reports that the merge is done.

**Comment by BanCrash** [comment]
@whalley oh, sorry, I thought you mean with that that there wouldn't be difference while entering the data, not while showing it.

About the reports, the Budget perfomance report so far seems to work fine, but the Budget Category Summary if you have the setting enable it will ignore the data entered on the yearly budget:

Report:
![imagen](https://user-images.githubusercontent.com/11770760/190119680-c5f30e69-b823-462f-9e58-fa50d9ca6446.png)

Yearly budget:
![imagen](https://user-images.githubusercontent.com/11770760/190119753-9df44bf9-0717-4522-9920-60d8dd6898e0.png)

I created 3 monthly budgets, two of them have 50 € as estimated quantity for that category, and the other have 500 €, so that's why I think it ignores the yearly budget.

**Comment by whalley** [comment]
> About the reports, the Budget perfomance report so far seems to work fine, but the Budget Category Summary if you have the setting enable it will ignore the data entered on the yearly budget:

Hopefully now fixed.

> @whalley oh, sorry, I thought you mean with that that there wouldn't be difference while entering the data, not while showing it.

I'm not sure what we can really present differently in the budget setup. Do you have a proposal?

**Comment by BanCrash** [comment]
> > About the reports, the Budget perfomance report so far seems to work fine, but the Budget Category Summary if you have the setting enable it will ignore the data entered on the yearly budget:
> 
> Hopefully now fixed.

If there is a new link I can test it if you want.

> > @whalley oh, sorry, I thought you mean with that that there wouldn't be difference while entering the data, not while showing it.
> 
> I'm not sure what we can really present differently in the budget setup. Do you have a proposal?

My original idea was to show the same as it is being showed on the total column of the Budget perfomance report, so when you override a month it will get get added or substracted to the total quantity on the year. But to be honest your implementation is better than I thought on my original post and I think that now it doesn't have any sense to modify it.

**Comment by whalley** [comment]
Try this: https://ci.appveyor.com/api/buildjobs/cww80macvl2x9v7v/artifacts/mmex-1.5.21-Beta.1-win64.exe

**Comment by BanCrash** [comment]
> Try this: https://ci.appveyor.com/api/buildjobs/cww80macvl2x9v7v/artifacts/mmex-1.5.21-Beta.1-win64.exe

I will make more tests tomorrow but so far I didn't found any more issues. Great job, thanks!
