### ISSUE TITLE
DB ver. 15

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4216]
There is a collection of tables that may be updated:
| ACCOUNTLIST_V1 |  type |
|---|---|
| initialdate (https://github.com/moneymanagerex/moneymanagerex/issues/3554) | TEXT |

| CURRENCYFORMATS_V1 | type | notes |
|---|---|---|
| type | TEXT | (crypto; fiat) |

|BUDGETSPLITTRANSACTIONS_V1 | type |
|---|---|
| notes (https://github.com/moneymanagerex/moneymanagerex/issues/910) | TEXT |

|SPLITTRANSACTIONS_V1 | type |
|---|---|
| notes (https://github.com/moneymanagerex/moneymanagerex/issues/910) | TEXT |

| REPORT_V1 | type |
|---|---|
| active | INTEGER (boolean flag visible or not) or unix date |

| BUDGETTABLE_V1 | type |
|---|---|
| notes (https://github.com/moneymanagerex/moneymanagerex/issues/4099) | TEXT  |
| active | INTEGER|

| PAYEE_V1 | type |
|---|---|
|number (https://github.com/moneymanagerex/moneymanagerex/issues/4280) |  TEXT |
|website (https://github.com/moneymanagerex/moneymanagerex/issues/4280) | TEXT |
|notes (https://github.com/moneymanagerex/moneymanagerex/issues/4280) | TEXT |
| active (https://github.com/moneymanagerex/moneymanagerex/issues/1390) | INTEGER|

| ASSET_V1 | type | notes |
|---|---|---|
| status | TEXT|
| currencyid (https://github.com/moneymanagerex/moneymanagerex/issues/4273) | INTEGER ||
| valuechangemode (https://github.com/moneymanagerex/moneymanagerex/issues/2712) | varchar | linear (amount), percentage |

| CATEGORY_V1 | type | notes |
|---|---|---|
| active (https://github.com/moneymanagerex/moneymanagerex/issues/4730) | INTEGER| |

| SUBCATEGORY_V1 | type | notes |
|---|---|---|
| active (https://github.com/moneymanagerex/moneymanagerex/issues/4730) | INTEGER| |

**Comment by whalley** [comment]
CUSTOMFIELDDATA_V1 - https://github.com/moneymanagerex/moneymanagerex/issues/4159

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4099

**Comment by whalley** [comment]
We don't need the init date for ACCOUNTLIST_V1 - See: https://github.com/moneymanagerex/moneymanagerex/issues/3554

**Comment by vomikan** [comment]
I couldn't think of a way without upgrading CUSTOMFIELDDATA_V1 to store custom fields for recurring transactions.
To avoid negative values (as it is implemented now), we need to add another alternative field for ID. And choose according to the principle that if one field is defined, then ignore the second.

**Comment by whalley** [comment]
> And choose according to the principle that if one field is defined, then ignore the second.

Would we not upgrade the database using SQL script to translate the data to new structure?

**Comment by vomikan** [comment]
> Would we not upgrade the database using SQL script to translate the data to new structure?

Exactly

**Comment by vomikan** [comment]
The current structure:
![image](https://user-images.githubusercontent.com/6836805/170671732-d042d122-bece-421f-a24a-69796ce808de.png)

We need one more field to store the ID of the recurring transaction or another field to store the type (Transactions or RecurringTransactions). 
This is because the REFID field stores the transaction ID from the CHECKINGACCOUNT_V1 table. To store data for Recurring transactions, we need to store the DBID field from the BILLSDEPOSITS_V1 table, but the values may match, which is unacceptable.
It is worth noting that storing a custom date by itself is not a problem. The problem starts when you need to transfer this data from Recurring transactions to regular transactions.

**Comment by vomikan** [comment]
Images for accounts should be stored in the ACCOUNTLIST_V1 table
![image](https://user-images.githubusercontent.com/6836805/170724978-9baeba47-5e04-4c0f-bf8e-b0bbe334cbdd.png)

**Comment by gabriele-v** [comment]
> We need one more field to store the ID of the recurring transaction or another field to store the type (Transactions or RecurringTransactions). This is because the REFID field stores the transaction ID from the CHECKINGACCOUNT_V1 table. To store data for Recurring transactions, we need to store the DBID field from the BILLSDEPOSITS_V1 table, but the values may match, which is unacceptable. It is worth noting that storing a custom date by itself is not a problem. The problem starts when you need to transfer this data from Recurring transactions to regular transactions.

Why you should need to move the REFTYPE to CUSTOMFIELDDATA? CUSTOMFIELDDATA contains only the data itself, the REFTYPE is a property of the CUSTOMFIELD, not of the CUSTOMFIELDDATA.

Considering the DB structure
```
-- Describe CUSTOMFIELD_V1
CREATE TABLE CUSTOMFIELD_V1 (
FIELDID INTEGER NOT NULL PRIMARY KEY
, REFTYPE TEXT NOT NULL /* Transaction, Stock, Asset, BankAccount, RepeatingTransaction, Payee */
, DESCRIPTION TEXT COLLATE NOCASE
, TYPE TEXT NOT NULL /* String, Integer, Decimal, Boolean, Date, Time, SingleChoiche, MultiChoiche */
, PROPERTIES TEXT NOT NULL
);
CREATE INDEX IDX_CUSTOMFIELD_REF ON CUSTOMFIELD_V1 (REFTYPE);

-- Describe CUSTOMFIELDDATA_V1
CREATE TABLE CUSTOMFIELDDATA_V1 (
FIELDATADID INTEGER NOT NULL PRIMARY KEY
, FIELDID INTEGER NOT NULL
, REFID INTEGER NOT NULL
, CONTENT TEXT
, UNIQUE(FIELDID, REFID)
);
CREATE INDEX IDX_CUSTOMFIELDDATA_REF ON CUSTOMFIELDDATA_V1 (FIELDID, REFID);
```

If I get your point, you mean that recurring and normal transaction should have the same customfields, but that's not the case. Consider for example a mortgage (recurring transaction) and monthly mortgage payment (normal transaction checkingaccount): I may want a custom field for the recurring mortgage/loan but which is only for the recurringitself, not for each monthly occasion on the ckecingaccount.

IMHO we should simply do it in this way: transactions has their own cutomfields, while recurring has their own which may be different. During the creation of the normal transaction from recurring, if there is any customfield who exactly match between the two, then it's copied, otherwise is skipped.

**Comment by vomikan** [comment]
> IMHO we should simply do it in this way: transactions has their own cutomfields, while recurring has their own which may be different. During the creation of the normal transaction from recurring, if there is any customfield who exactly match between the two, then it's copied, otherwise is skipped.

This is a good suggestion. From the point of view of implementation, everything will turn out transparently. But the user will have to try to prepare everything so that the transfer of these fields is possible.

I am in favor of not changing the existing structure for CUSTOMFIELD.

**Comment by gabriele-v** [comment]
I think before all of this, we should consider if we would like to break DB structure (Android app won't work) or not. That's the first point, then we can consider other ideas.

**Comment by vomikan** [comment]
Category type?

**Comment by vomikan** [comment]
I think that when adding a number of tables, integrity control is overlooked.
https://www.sqlite.org/foreignkeys.html

Probably (I haven't checked), you can delete the transaction, but the file records associated with it will remain in the table ATTACHMENT_V1.

Another example, the status of an account or transaction can take only one value from the list. This can be verified by the construction: 
```CONSTRAINT status_chk CHECK(STATUS in ('Open', 'Closed'))```

**Comment by gabriele-v** [comment]
I can guarantee that all the cases were managed when I've implemented attachments even without foreign keys. Now I cannot guarantee it because I'm not following anymore every change.

But as I said somewhere else, there are tons of improvements that could be done if you change DB structure, the point is: do we want to break Android compatibility? If the response is yes, then DB versioning is already managed and you can do whatever is needed, if not then every comment about possible DB improvements is useless.

**Comment by vomikan** [comment]
Obvious things:
1) A desktop application cannot develop without changing the database.
2) We don't know if we want to develop separately from the Android app. We need to collect statistics or a public opinion poll.
3) The Android app is no longer being developed.

**Comment by vomikan** [comment]
@gabriele-v In this case, I collect possible options for changing the database, but such that an Android application can work with such a database.
For example, if you add notes for budget lines or split transactions, it will not affect the Android app catastrophically.

The only thing that exists is PRAGMA user_version. Without changing this value, it is impossible to upgrade. But if you change it, then the Android application may refuse to work with such a database.

**Comment by gabriele-v** [comment]
I agree and for me we should have done the separation much earlier even with v. 13

**Comment by gabriele-v** [comment]
> @gabriele-v In this case, I collect possible options for changing the database, but such that an Android application can work with such a database.
> For example, if you add notes for budget lines or split transactions, it will not affect the Android app catastrophically.
> 
> The only thing that exists is PRAGMA user_version. Without changing this value, it is impossible to upgrade. But if you change it, then the Android application may refuse to work with such a database.

IMHO or we completely divide from Android or we stay as is. It doesn't make sense to do changes which are anyway small for the desktop app and won't massively improve it. Also every change should be tested because you cannot guarantee it will work, IMHO it's a mess.

**Comment by vomikan** [comment]
I agree that it's easier to get rid of the Android application.
And we have been developing within the framework of DB version No. 7 for about two years. Then it is difficult to come up with something new or improve the existing one.

**Comment by MartinX3** [comment]
Why not sharing the same code between mmex and the android app except the UI code?
As far as I know it's possible to write C++ Android Apps.

**Comment by vomikan** [comment]
> Why not sharing the same code between mmex and the android app except the UI code?
> As far as I know it's possible to write C++ Android Apps.

Both of these projects are developing chaotically. We don't have a single decision-making center.

**Comment by gabriele-v** [comment]
> Why not sharing the same code between mmex and the android app except the UI code? As far as I know it's possible to write C++ Android Apps.
Not sure about C++ (and SQLite integration), for sure it would be possible using .NET Standard, creatign a unique data layer shared between Android and Desktop (and potentially a web version) and then migrate Android to Xamarin and Desktop to .NET (using mono on MacOS and Linux). IMHO it will open to lots of possibilities (.NET is much powerful than C++ and GUI will be also probably better than wxWidgets) but it will be obviously take much much effort to make it working.

I started something here but never had time to finish it: https://github.com/moneymanagerex/MMEX.NET

**Comment by tactilis** [comment]
@gabriele-v 
> I started something here but never had time to finish it

This is the fundamental problem!

Nobody (i.e. developers, testers, etc) has got enough time to devote to such a huge change - or even to address the 300+ open issues and get them down to a small number. And remember too the abandoned 1.4 development.

It's superb, the work that @vomikan, @whalley, you, and others have done - but it feels to me that porting MMEX to .NET would derail the project for years unless that was a dedicated project team.

**Comment by vomikan** [comment]
https://forum.moneymanagerex.org/viewtopic.php?t=10657

**Comment by whalley** [comment]
Re-added initial/opening date to ACCOUNTLIST_V1   https://github.com/moneymanagerex/moneymanagerex/issues/3554

**Comment by whalley** [comment]
@vomikan For the time fields have we not settled on just extending the date field discuss here: https://github.com/moneymanagerex/moneymanagerex/issues/2729#issuecomment-826313052 this would certainly make existing date comparison logic compatible.

**Comment by whalley** [comment]
@vomikan We already have v8 - v13 of the DB https://github.com/moneymanagerex/database/tags

How were we planing to handle the move to v8 (the new v8) in the git repo? Do we want to go to v14 making the v8-v13 upgrades do no schema changes and perhaps put a check in the code to stop any upgrade from v8-v13 just in case somebody is using the old aborted code?

**Comment by gabriele-v** [comment]
IMHO we should leave v8-13 as they were, issue a v14 with the rollback of that changes (it should be possible with the code in the MMDBG) and then start v15 with the other changes

**Comment by whalley** [comment]
> IMHO we should leave v8-13 as they were, issue a v14 with the rollback of that changes (it should be possible with the code in the MMDBG) and then start v15 with the other changes EDIT: Unless there are any drawbacks or something is lost, obviously

Forgot we had the .mmdg to rollback the database back... will have a look at that.

**Comment by vomikan** [comment]
I have no idea how to upgrade to v15 in the best way.

Since we got rid of the mmex 14 version, we can delete everything after v9.

About naming fields, I also have no preferences.
Yes, it is better to store the time as YYYY-MM-DDTHH:MM:SS

**Comment by gabriele-v** [comment]
> > > code in the MMDBG) and then start v15 with the other changes EDIT: Unless there are any drawbacks or something is lost, obviously
> > 
> > 
> > Forgot we had the .mmdg to rollback the database back... will have a look at that.
> 
> Having looked at it there was a hell of a lot going on between v7 and v14 schemas and whilst the rollback logic could be incorporated it seems over complicated. In addition, forcing a DB downgrade without any user consent for a user using the v1.4.x software does not seem the right thing to do.
> 
> I therefore suggest
> 
> * we go with v15 as the next DB version
> * if we encounter v8-v14 we report an error and direct the user to article here: [downgrade DB from v1.4.x to v1.3.x (and v1.5.0) #2353](https://github.com/moneymanagerex/moneymanagerex/issues/2353)

Ideally upgrade procedure has been made to be pretty stupid, without any specific user interaction.

What about issue a v15 with an error that happens only if DB was at version v14?
Something like adding a column/table that already exists in DB v14 and then drop it.
In case DB was at v7, then it correctly executes the add and drop and then you can issue your v16.
If DB was at v8, it will fail asking to contact support or open a case. Maybe you can improve that to open a link to github issues? I don't remember exactly the error when it fails the upgrade but it should provide some additional info to understand the problem

**Comment by whalley** [comment]
@gabriele-v I like the thinking! Just simulated this and the error is as below, which should be fine...
<img width="260" alt="CleanShot 2022-09-27 at 18 55 59@2x" src="https://user-images.githubusercontent.com/487345/192601438-92d2da82-3ab7-421c-86fe-29f0e51c4edc.png">

**Comment by whalley** [comment]
We also need to be careful when adding new fields before the logic to process them is there. For some fields it is fine e.g. notes fields which can be empty.  But for others e.g. adding something like a status (open/closed) field will cause issues - e.g. we can upgrade all objects to "open" but newly created objects unless we have a default will be NULL which may cause further complexities when we come to implement the correct logic. We could attempt to use defaults in the SQL schema but this may not always be suitable, e.g CURRENCYID against ASSET and may need code changes to support (though we could default to -1 in schema).

Just pointing out we need to be careful bulk adding fields to the schema to be used by logic later because of the above and because when implementing we may identify other/changed needs.

**Comment by whalley** [comment]
> Just pointing out we need to be careful bulk adding fields to the schema to be used by logic later because of the above and because when implementing we may identify other/changed needs. 

Have tested this and the way the logic works (for TEXT at least) is we can set the 'DEFAULT' at schema/upgrade but when new objects are created the 'DEFAULT' is not used and null fields are created if not specified. Probably answers my observation that no existing table columns have defaults in the schema :-)
![CleanShot 2022-09-28 at 00 12 45](https://user-images.githubusercontent.com/487345/192653718-1c6bc573-b835-47e0-80be-ff0bae61457d.png)

So I'll look to provide minimal default setup in code for each new field. We can add the wider logic later.

**Comment by whalley** [comment]
Delaying some of the ACCOUNTLIST_V1 and the CHECKINGACCOUNT_V1, BILLSDEPOSITS_V1 changes to DBv16 as I think there are some other ways to achive these in a more generic manner, which I'll work on later.

**Comment by whalley** [comment]
Have pushed the v15 DB changes: https://github.com/moneymanagerex/database/commit/2ae8a5a01c0ddafc1ba5fbd39e67bd38ddf5fc9b

**Comment by vomikan** [comment]
Using this code here, I propose the appropriate change.
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/constants.cpp#L215-L229

https://github.com/moneymanagerex/database/commit/2ae8a5a01c0ddafc1ba5fbd39e67bd38ddf5fc9b#r85303523

**Comment by whalley** [comment]
> Using this code here, I propose the appropriate change. https://github.com/moneymanagerex/moneymanagerex/blob/master/src/constants.cpp#L215-L229
> 
> [moneymanagerex/database@2ae8a5a#r85303523](https://github.com/moneymanagerex/database/commit/2ae8a5a01c0ddafc1ba5fbd39e67bd38ddf5fc9b#r85303523)

Sure, will update to incorporate.

**Comment by whalley** [comment]
Views on calling next release v1.6.0 in recognition of the DB change that will probably break compatibility with the out-of-date Android version, and make the DB unreadable by v1.5.x releases?

**Comment by whalley** [comment]
Who follows rules, eh :-)

Let's go with 1.6.0 .... the 2.x.x is reserved for the version that automatically creates wealth for its users -) ... or as I have previously discussed with @vomikan when we add some major features (stocks overhaul, online banking integration, etc.)

**Comment by tactilis** [comment]
>  the version that automatically creates wealth for its users

I will look forward to that version

**Comment by whalley** [comment]
> I think that it's the first time that we are breaking Android compatibility (at least in a stable) so I'd agree that breaking compatibility with Android may need a v2.0.0 but in that case 

Will stick with 1.6.0 for now, think it is sufficient differentiation.

> we should consider how to handle all the _v1 in database tables.
> IMHO we should consider (as it was done in "unstable" v12) to completely drop the _v1 at the end of the tables and especially we need the update of v12 that "normalizes" the DB because in the past we have found that really old versions of MMEX created tables wrongly *indexes, types etc..) so starting from a clean base (with select/insert to migrate data) it's the base to properly handle the updates.

I did note the table name translations and referential integrity rules when looking at the DB history, will add as item for v16 DB.

> By the way, once a new version (like v15) is issued, even in an unstable (maybe in a PR it should be possible), it's mandatory to never change the SQL update code because otherwise we will have two different v15. In such case it's better to issue a v16 (we don't pay versions numbers :D )

Noted.

**Comment by PMaff** [comment]
> Android

This breaks the usage on Android.
:-(
https://github.com/moneymanagerex/moneymanagerex/issues/5230

This also means that I have to stay on 1.5.X (was using 1.5.22Beta lately since I was very busy at work and did not check newer versions).

Will there be an update on Android moving the DB also to version 15?

**Comment by PMaff** [comment]
> Views on calling next release v1.6.0 in recognition of the DB change that will probably break compatibility with the out-of-date Android version, and make the DB unreadable by v1.5.x releases?

This breaks the usage on Android.
:-(
https://github.com/moneymanagerex/moneymanagerex/issues/5230

This also means that I have to stay on 1.5.X (was using 1.5.22Beta lately since I was very busy at work and did not check newer versions).

Will there be an update on Android moving the DB also to version 15?

**Comment by tactilis** [comment]
@PMaff 
>  I know that the Android stuff is not developed currently

This is precisely the issue. https://github.com/moneymanagerex/moneymanagerex/issues/5230#issuecomment-1294080445

There is nobody to maintain and evolve the Android version but that should not stop evolution of the desktop application.

If you want no change to MMEX, and compatibility with Android then you have the choice to stay with 1.5.x.

**Comment by whalley** [comment]
> We should also remove the part here:
https://moneymanagerex.org/docs/features/android/
or at least put there some warning, that with 1.6.0 on Win/Mac/Linux the exchange of the DB with Android does not work anymore.
"Looking for the Android Build? [#](https://moneymanagerex.org/docs/downloads/latest/#looking-for-the-android-build)"
and
"The latest Money Manager Ex release uses the database structure of the 1.3.x series and discontinued the structure of version 1.4.x. This maintains compatibility with the mobile app."
here:
https://moneymanagerex.org/docs/downloads/latest/
then is also not valid anymore.

Good points I will fix that.

> Btw. would it be possible to convert the DB Vers. 15 to the version used on Android so that I
can copy the DB to Android?

I'm sure somebody could develop something but it's not on my list of things to do, and will get very messy as we continue to evolve the DB. You should just stick with with v1.5.21 if you want to continue to use Android.

**Comment by PMaff** [comment]
@whalley I understand you mmex guys and currently I decided to go with you to the new version.
You deleted the Android parts of the webpage completely (which is ok), maybe something like
"In previous versions MMEX was usable on Android also.
But Android development for MMEX was dead for a long time.
Progress and a new database format made it necessary to cut off the Android application,
so you will have to stay on version 1.5.21 on the PC to be able to sync with Android.

If you are a Android developer and if you would like to participate, you are very welcome.
Please contact..."

It is probably a bit more complicated with Android for me personally, but I will adapt.

I remember that there was some Web-Version of mmex, but I never looked at this.
Is this still there and would that be usable on an Android handy?

**Comment by whalley** [comment]
> I remember that there was some Web-Version of mmex, but I never looked at this.
> Is this still there and would that be usable on an Android handy?

Yes, I use it on iOS. Should work fine on Android. It is simply used to collate transactions whilst you are away from your desktop.
https://github.com/moneymanagerex/web-money-manager-ex
