### ISSUE TITLE
Reccuring transactions layout grid

### ISSUE THREAD

**Issue by AlessandroLazzari** [moneymanagerex/moneymanagerex#422]
In the window of reccuring transactions is not saved the layout of columns and their width. When thes user close this windows and re-open the layout will be reset

Size of columns that were modified manualy:

![image](https://cloud.githubusercontent.com/assets/7428710/6800893/3a8c8d8e-d223-11e4-956b-4dbddc4d3207.png)

After closing the window and re-opened

![image](https://cloud.githubusercontent.com/assets/7428710/6800914/68113e30-d223-11e4-9357-670d309ffc87.png)

Works fine for normal transactions

Version: 1.2.0-Beta.2 Portable

**Comment by guanlisheng** [comment]
Thanks @AlessandroLazzari for the feedback.
@stef145g  , would you mind to take a look here?

**Comment by stef145g** [comment]
Issued pull request could have cured the problem, but was closed due to it being found to be unacceptable. Someone else can investigate further.

**Comment by stef145g** [comment]
I discovered a merge conflict with the pull request as a result of other commits to master. I have now fixed the resulting conflicts and successfully merged **stef145g/master** with **moneymanagerex/master**. This now resides in my repo.

**Comment by vomikan** [comment]
Closed?

**Comment by stef145g** [comment]
This issue is now fixed in both master and v1.2.x branch
