### ISSUE TITLE
Error in Russian translation

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4224]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The same name in Russian appears twice in Recurring Transaction, while one of them means Duplicate and another one - Delete.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Change application language to Russian.
2. Create any Recurring Transaction.
3. Right-click at the transaction.
![image](https://user-images.githubusercontent.com/83161661/154839188-5136e949-c051-4922-aba0-9128bce6d10f.png)

# Additional information

In English everything looks good:
![image](https://user-images.githubusercontent.com/83161661/154839153-0381b132-311e-400d-854a-42037c89de75.png)

**Comment by vomikan** [comment]
```D&uplicate Recurring Transaction...```
![image](https://user-images.githubusercontent.com/6836805/154841663-fe0bab2f-b3ca-4de4-a2da-13ed17f99ad3.png)
