### ISSUE TITLE
Transaction Filter: Add multiselect for categories and subcategories

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4226]
**Current situation**
There is a very cool Transaction Filter, allowing you to customize and save almost any necessary report.
![image](https://user-images.githubusercontent.com/83161661/154850421-dbf9fa92-17a0-49a3-b7f8-cbe809ff5ce4.png)

**Problem**
This Transaction Filter gives an option to choose just all (if unchecked) or one category and "include similar", but is not flexible enough to allow users to choose a few subcategories if they want.

**From the forum:**
_In my use case, I manage bookkeeping related to accounts of my girlfriend, accounts of me and our joint accounts. I transfer every month amounts on the joint account which does not appear as an expense because it is a transfer. But sometimes, I bought something personally through the joint account so to refund it and let it appear as an expense on my side, I have to do 2 entries (withdraw on my account and deposit on our joint account) so it appears in my reports._
_Obviously this is not convenient and hope someone have a better workaround than me :) I imagine it would be nice to add on categories an information to type the kind of transaction (deposit, withdraw or transfer) to be able to deal with such issue._

_Thanks, yes this is a solution. **However, this will make the transaction be included in income as well, wouldn't it?**_

https://forum.moneymanagerex.org/viewtopic.php?t=10542

So the user has a problem - he has found a wayaround, but this manual transaction from one account to another will look like Income, but it is not correct.

**Solution**:
Add checkboxes for any category and subcategory to give users the option to decide what they want to include in this report.
Something like that:
![image](https://user-images.githubusercontent.com/83161661/154851274-4e2f1fce-3471-4997-9c85-e9aa208773d5.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3752
