### ISSUE TITLE
Cannot edit or add payees in "Edit Recurring Transaction" window

### ISSUE THREAD

**Issue by PaulBP14** [moneymanagerex/moneymanagerex#4227]
MMEX version:
 - [x] 1.5.13
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Since the update to 1.5.13 (may have been 2 versions ago as I skipped a couple) you can no longer add a payee when editing a recurring transaction

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Edit a recurring transaction
2. Click on the payee box
3. If you enter a Payee who does not exist into the search box, nothing happens - Previously the payee would be added
4. Additionally the green 4-leaf clover (?) icon is disabled which normally allows you to add or edit payees
5. Additionally right-clicking an existing payee does not bring up the right-click menu in the way it does on the Organise Payee option on the Tools Menu

Expected result:
You should be able to add a new Payee when editing or adding a recurring transaction, this worked previously.

Actual result:
You are unable to add or edit a Payee from the Edit Recurring Transaction window

# Additional information

**Comment by whalley** [comment]
Confirmed... Perhaps we take this as an opportunity to align the recurring transaction dialog to the 'normal' transaction dialog presentation of accounts/payees.

**Comment by whalley** [comment]
This is the breaking change: https://github.com/moneymanagerex/moneymanagerex/commit/e1453dc36bf57be2e7b0604c15517b44f7458b45

**Comment by whalley** [comment]
Broken by this https://github.com/moneymanagerex/moneymanagerex/commit/2702cad63b9ab24fbd6f9fe454d837e9d180f3e7 i think
