### ISSUE TITLE
Issues with Dark Themes on Sidebar in Linux

### ISSUE THREAD

**Issue by magic-ian** [moneymanagerex/moneymanagerex#4230]
MMEX version:
 - [x] 1.5.1-1~buster_amd64.deb (latest available version for Debian-based distributions; Snap edge is still on 1.4.0-alpha.6)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
When using Adwaita-dark system theme (arguably the most common dark theme used), all 4 themes do not display the text on the left sidebar as dark (black on white), or more preferred, does not display the sidepane itself as a dark background (white on black). Right now it is white on white. 

The previous version did not have this issue, however icons did not have transparencies, and more of the program did not display white on black, so clearly there has been some improvements on the previous version, but there are a couple more things to do to fully implement the changes.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Install Adwaita-dark
2. Install MMEX 1.5.1
3. Open MMEX

…

Expected result:
White on black text throughout the program

Actual result:
White on white text on the sidebar

**Comment by vomikan** [comment]
Could you, please, upload a screenshot?

**Comment by whalley** [comment]
Similar to this? https://github.com/moneymanagerex/moneymanagerex/issues/3364

**Comment by whalley** [comment]
@magic-ian Can you please provide a screenshot to help people better understand this issue you have.
