### ISSUE TITLE
Option to easily view all transactions for a payee by selection

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#4232]
First off, thank you so much for the time and dedication the team puts into this software, I have been a faithful user for over two years and get excited every time I see there is a new version available for download! I've also donated to the project knowing that you do all of this on the side and you have a great community that supports you.

# Description of the feature
I think it would be a nice feature that when selecting a single transaction, to add a "View Payee Transactions" menu option to the right-click context menu. The menu option would then take the user to the Full Transactions grid, and display all transactions that exist for the Payee that was selected. 

# Use cases
The same behavior can be achieved by using the Advanced Filter, but I think it would be convenient for the user and be faster than having to use the filter. This is especially true when the same payee is used on many accounts like in my example screenshot.

Thanks for your consideration!
Rich

![image](https://user-images.githubusercontent.com/95182117/155827927-475cb8ae-c9c2-41c7-9a95-6f61d549909e.png)

![image](https://user-images.githubusercontent.com/95182117/155827950-2a6a045e-712a-42a1-9430-03341d871883.png)

**Comment by vomikan** [comment]
There are many options for this already exists 
1) for one page without choice would be better to create GRM report.
2) the account view may be sorted by payee column. In that case eat to see that kind transactions.

**Comment by rmelillo76** [comment]
> There are many options for this already exists
> 
> 1. for one page without choice would be better to create GRM report.
> 2. the account view may be sorted by payee column. In that case eat to see that kind transactions.

Hi @vomikan, thanks for your reply. Yes I mentioned and agree there are other options, but I don't think they are as convenient as the one I proposed.  A GRM report doesn't meet the request but the built-in transaction report comes close so I can accept that. Sorting the account view comes close, but doesn't solve for  my example of starting on one account, but being able to view transactions from all accounts, which is nice when I want to quickly see past transactions for the payee I am working on.  Thanks again for the great work.

**Comment by n-stein** [comment]
@rmelillo76 I added an option to the context menu. I decided not to go with the "Find" submenu I suggested in #6215 since it felt too restrictive. Instead, you can right click anywhere in the panel and you will get an option to "Find all transactions with ..." whatever cell you clicked on. 

Here's a quick demo:
![mmex_8avhcwwcIM](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/a8d48016-e419-4e47-8c5c-c76514473c69)

Should suit @blueberry-bytes needs as well.

Give it a try and let me know if you have any suggestions for improvements.

**Comment by blueberry-bytes** [comment]
I love you guys so much.

**Comment by rmelillo76** [comment]
This is perfect @n-stein! You've done it again, great clever and practical way to implement my idea. Thank you so much!!

**Comment by whalley** [comment]
Works fine when initiated from single accounts (except observation below) but not when initiated on 'All Transactions'.

Should it not filter only to the account selected when invoked from single accounts?

**Comment by n-stein** [comment]
> Works fine when initiated from single accounts (except observation below) but not when initiated on 'All Transactions'.

Ah, good catch. The filter is applied but the panel doesn't refresh when going from "All Transactions" to "All Transactions". If you click out then back in it applies it. Will force the refresh if already in "All Transactions".

> Should it not filter only to the account selected when invoked from single accounts?

Hmm, I wasn't thinking of it that way -- I thought the desire was to view every transaction with that item regardless of account (unless you selected "Find all transactions with Account..." which would of course filter the account). If we restricted the account when invoked from single accounts then jumping to "All Transactions" is pointless, we could just turn on the "View with Transaction Filter..." setting in the single account panel. 

Do we need a separate option to apply the filter in the current single account panel vs All Transactions, something like `Filter Payee 'Cable Co'` and `Find all transactions with Payee 'Cable Co'` where the former would apply the filter in the current account panel while the latter would jump to All Transactions?

**Comment by blueberry-bytes** [comment]
I haven't tested it yet, I think I would use the "all transactions" much more often but I guess it would be nice to have a choice to stay in the current account. It would be more universal and I suppose it's not hard to do it at this point.

**Comment by n-stein** [comment]
> Works fine when initiated from single accounts (except observation below) but not when initiated on 'All Transactions'

Fixed

**Comment by pdelamotar** [comment]
I just downloaded the latest appveyor compilation regarding this feature, and I get that it has a virus

![Screenshot 2023-10-04 210303](https://github.com/moneymanagerex/moneymanagerex/assets/133933827/ccc96e27-2bbd-461e-8f46-ce506e07c646)

**Comment by n-stein** [comment]
Odd, must be a false positive. Bitdefender doesn't see anything wrong with it:

![odscanlogviewie_ny7OmTAgnd](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/fc187ed3-6b7b-4f7a-8012-d028fdf15abc)

**Comment by whalley** [comment]
> If we restricted the account when invoked from single accounts then jumping to "All Transactions" is pointless, we could just turn on the "View with Transaction Filter..." setting in the single account panel.

I had assumed that this was the way it was going to work. It seems more logical, at least to me, that if you are in a single account view then it would filter only within that account, if you were in the "All Transactions" view then it would filter that.  

Having said that I'm fine with the current implementation and it works well.

**Comment by luisdev** [comment]
Testing this now on:
 Version: 1.7.0-Beta.1 64-bit
• Built on: Oct 4 2023 22:27:08
• Database version: 19 (aes128cbc)
• Git commit: 427aa5b (2023-10-05)

And I must say, it's a REALLY nice feature! Thanks.
:-)

**Comment by whalley** [comment]
Can we close this now?

**Comment by rmelillo76** [comment]
> Can we close this now?

Good by me - thanks all!

**Comment by sarjanwebdev** [comment]
Thank you for this feature!
