### ISSUE TITLE
Dialogs size storing

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4237]
a) When entering a new entry, the previous entries are covered, if I move the window, then the position is not saved and the next entry I have to move again.
I wish that the position of the window is saved.

b) If I want to select a category for a booking, then the "Organize Categories" window is placed directly on the "New Transaction" window. In order to see the values in the "New Transaction" window, I need to move "Organize Categories". Again, the position is not saved.

c) The window "Organize Categories" is relatively small, to make a selection I always have to move it. When I enlarge the window, the size is not saved.

On a PC today, people often use larger screens with larger resolutions, and with such adjustments, more comfort for the user could be reached.

<img width="235" alt="MMEX32a" src="https://user-images.githubusercontent.com/76920138/156747306-ce6624d2-b5bd-4dcc-840d-44ba8500b9f7.png">
<img width="403" alt="MMEX33a" src="https://user-images.githubusercontent.com/76920138/156747359-f1a3fbf9-2cad-4134-ac9c-df2e8fbd1568.png">

**Comment by vomikan** [comment]
Hello Renato,

In order not to make the window with categories so large, you can press the first letter in the category name or even the initial letters in the Expand mode. The categories tree window should be in a focus.

Regards,
Nikolay

**Comment by vomikan** [comment]
@renato-mmex could you, please, test this functionality?
It implemented only for transaction dialog and categories dialog.
We need feedback to understand whether to extend this functionality to other dialogs.

**Comment by whalley** [comment]
This does not seem to do anything for me, nothing seems to be saved/retrieved. It is also potentially an annoying feature if the dialog positions are saved. What happens if I reopen the application but have it on a different screen in a different place. I would have expected something like the split transaction dialog to open up alongside the transaction dialog not someplace it existed when I last used the application.

**Comment by vomikan** [comment]
We can save the name of the Monitor. If the current value does not match the saved one, then ignore the saved settings.

**Comment by vomikan** [comment]
I find it useful to keep the size of the dialog box, but not its position. Probably, it is necessary to roll back to a time when only such an option was supported.

**Comment by whalley** [comment]
This only appears to work if the dialog opened on the primary monitor. I.e. I can open a dialog on my primary display and resize, but if I then move MMEX to a secondary display and the re-open dialog it reverts back to standard size.
