### ISSUE TITLE
Transaction Report -> Transaction Filter: Can't change 'Transfer To' from here.

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#4239]
MMEX version: 1.5.13, macOS. Same on 1.5.14 beta.

The transaction types appear to get their value from whatever filter is applied in the Account View. I can change Withdrawal, Deposit, Transfer From but why not Transfer To? Transfer To can be changed in Account View -> Transaction Filter.
![Trx Filter](https://user-images.githubusercontent.com/63317977/156830755-3c2f25c7-d507-45bb-a58e-420e665401b9.jpg)

![Trx Filter2](https://user-images.githubusercontent.com/63317977/156830798-f4a93b3a-71d6-4d52-aa5d-0ef4eea4ca54.jpg)

**Comment by whalley** [comment]
When the transaction view is not filtered by any accounts it makes no sense to be able to further filter by 'Transfer To'/'Transfer From' so just the option to select a 'Transfer From' is displayed (though this should really just be saying select only transfers (should perhaps look to make sure if one is selected both are selected in this case).

If a subset of accounts are selected then 'Transfer To' can be selected (along with 'Transfer From'). Although having just looked at an example report I think it actually reports the revers of what is selected!!

**Comment by 2BeeOrNot** [comment]
Thanks. I think I understand. Transfer To may be checked or not and greyed out but Transfer From includes both to and from transfers in this case.

But I'm still confused.
Big Bank has transfers to and transfers from Little Bank. $85.00 to Little Bank and $850.00 from Little Bank.
In account view for Big Bank:
I select Transfer To and I get both transfers to and from Little Bank. Same for selecting Transfer From. Selecting either gets me all transfers from and into Big Bank. Not what I expected. My goal was to get just transfers to or transfers from Little Bank, not both.

In All Transactions:
I select Big Bank
I select Transfer To
I get what I expected - just transfers to to Little Bank .
Account: Big Bank / Payee: >Little Bank / Category: Transfer / Withdrawal:$85.00

If I select Transfers From I don't get what I expected.
Account: Little Bank / Payee: > Big Bank / Category: Transfer / Withdrawal $850.00
This is correct but since I was looking for transfers from I expected to see a deposit into Big Bank.

Is there a way to get just transfers from or transfers to (not both) in account view for a single account in account view?

Transaction Report works as expected when selecting Big Bank and transfers to  - the amount is a negative amount or selecting transfers from - the amount is positive. Selecting both shows both transfers to and transfers from both as a negative amount and a positive amount.

Clear as mud?

**Comment by whalley** [comment]
> But I'm still confused. Big Bank has transfers to and transfers from Little Bank. $85.00 to Little Bank and $850.00 from Little Bank. In account view for Big Bank: I select Transfer To and I get both transfers to and from Little Bank. Same for selecting Transfer From. Selecting either gets me all transfers from and into Big Bank. Not what I expected. My goal was to get just transfers to or transfers from Little Bank, not both.

Yes, this is a bug. Will look to fix.

> In All Transactions: I select Big Bank I select Transfer To I get what I expected - just transfers to to Little Bank . Account: Big Bank / Payee: >Little Bank / Category: Transfer / Withdrawal:$85.00

Good.
![CleanShot 2022-03-05 at 18 23 23](https://user-images.githubusercontent.com/487345/156895626-7b69c38b-9d47-4932-886b-305506da95a5.png)


> If I select Transfers From I don't get what I expected. Account: Little Bank / Payee: > Big Bank / Category: Transfer / Withdrawal $850.00 This is correct but since I was looking for transfers from I expected to see a deposit into Big Bank.

Why would expect a Deposit? It does show a 'Transfer From', i.e a Transfer From Little Bank To Big Bank for £850.00
![CleanShot 2022-03-05 at 18 24 30](https://user-images.githubusercontent.com/487345/156895653-8dc956a4-7c87-4c87-9295-85bc3712336f.png)

> Is there a way to get just transfers from or transfers to (not both) in account view for a single account in account view?
> 
> Transaction Report works as expected when selecting Big Bank and transfers to - the amount is a negative amount or selecting transfers from - the amount is positive. Selecting both shows both transfers to and transfers from both as a negative amount and a positive amount.
> 

Will look to fix as noted above.

**Comment by 2BeeOrNot** [comment]
Oh no. I'm back!
First, the new MMEX home page looks nice. Big improvement.

"it makes no sense to be able to further filter by 'Transfer To'/'Transfer From'"
I disagree. I can filter on just about everything else why not transfers?

I would be happy if in single account view I can select 'Transfer From' or 'Transfer To' and just get transfers to or transfers from, not both (unless I select both). Transfers from would be a deposit and transfers to a withdrawal.

Why does All Transactions with no filters only show transfers to (withdrawals)? The balance in the three accounts is 391.10. If you add up all the amounts below you get -601.90. The transfers from (deposits) are missing. Every transfer has a deposit and withdrawal. Filtering on a subset of 'Account' and filtering on 'Transfer To' and/or 'Transfer From' doesn't work, I get the same same three transfers to.
![AllTrx](https://user-images.githubusercontent.com/63317977/157120386-3d00d8ec-7690-495d-b29c-5c1fb285bd46.jpg)

This is inconsistent with Transaction Report. With no filters it displays the transfers to and transfer from. This is how it should IMO.

![TxRpt](https://user-images.githubusercontent.com/63317977/157120823-ced1ebc7-e40b-4125-b0b3-ab9fef490425.jpg)


Below I've filtered on Big Bank, Little Bank and 'Transfer To'. Why do I also get transfers from? It seems MMEX finds a transfer to and since the matching transfer from is in the Account filter it displays it. But for the last transaction MMEX finds the transaction to but the matching transfer from isn't in the Account filter so it only displays the transfer to. If I can filter on 'Transfer To' shouldn't I only get transactions to?
![Rept2](https://user-images.githubusercontent.com/63317977/157132090-bdc728a3-eb73-4b49-af43-c870caa7fab5.jpg)

Below I've filtered on Transfer From instead of Transfer To. Similar to above it seems MMEX can't find a transfer from that matches the Account filter so I doesn't display it at all, both transfer from and transfer to, which is correct. But for the other transfers it displays the transfers to.
![Rept3](https://user-images.githubusercontent.com/63317977/157133052-ea5d5280-0702-4362-8a0c-1b6dba9e8300.jpg)

If users can't filter on 'Transfer To' or 'Transfer From' separately, whether filtering on all accounts or a subset of accounts, should the filter should just be 'Transfers'?

I've said enough. Thanks for listening (reading).

**Comment by whalley** [comment]
@2BeeOrNot Welcome back.... Yes there are a few bugs in this transfer filtering logic, will look to fix when I get a bit of time..

**Comment by whalley** [comment]
Have updated the code to hopefully make this clearer to end users.

1. When 'All accounts' (or an advanced filter from a single account view is selected) is selected then just 'Transfer' is available for the Transaction Type.
2. Have renamesd'Transfer To' to 'Transfer Out' and 'Transfer From' to 'Transfer In'. These represent the direction of the transfer with respect to the accounts selected in the filter. E.g. If accounts A & B are selected then 'Transfer Out' reflects ALL transfers that move funds outside of accounts A & B.

I think other than that the logic works, noting that:

1. In the 'All Transactions' view a transaction that matches the filter is displayed only once.
2. In the 'Transaction Report' a transaction may be reported once or twice depending upon how it matches the filter logic.

Are there any other concerns we need to address?

**Comment by whalley** [comment]
When all accounts are in filter (or selected from single account view):
<img width="409" alt="CleanShot 2022-03-14 at 08 55 15@2x" src="https://user-images.githubusercontent.com/487345/158137949-82f93a40-047a-4b31-a09d-2244ec610062.png">

When accounts are selected:
<img width="409" alt="CleanShot 2022-03-14 at 08 55 48@2x" src="https://user-images.githubusercontent.com/487345/158138018-47b65c45-06e6-4818-b900-62fc4507e126.png">

Unfiltered list of 'All Transactions':
<img width="985" alt="CleanShot 2022-03-14 at 08 59 05@2x" src="https://user-images.githubusercontent.com/487345/158138645-d88d6b99-d9a3-465d-b286-846733e7fcba.png">

All Transactions view when filtered by 'Little Bank' & 'Medium Bank' with 'Transfer Out' only:
<img width="982" alt="CleanShot 2022-03-14 at 09 02 35@2x" src="https://user-images.githubusercontent.com/487345/158139245-35f56638-8759-4dae-b04c-c514db5dcaba.png">

Transaction Report when filtered by 'Little Bank' & 'Medium Bank' with 'Transfer Out' only:
<img width="951" alt="CleanShot 2022-03-14 at 09 01 51" src="https://user-images.githubusercontent.com/487345/158139107-6ad08781-088f-4860-b6ec-03eb84e378e5.png">

**Comment by 2BeeOrNot** [comment]
I'll briefly looked at this last night and wanted to share my thoughts one last time but it was late. I'll look at the screen shots above and the latest build again but it will be later tonight.

**Comment by whalley** [comment]
@2BeeOrNot Any further comments/issues before I close this?
