### ISSUE TITLE
Transaction Report Footers Take Up Too Much Space

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#4240]
The transaction report two footers can take up so much room.
![Footers](https://user-images.githubusercontent.com/63317977/156832711-60c18e94-5835-4414-be1b-ed39ceb66d5d.jpg)
Can the two grand totals be on the same line as the heading?
All Transactions: Withdrawals, Deposits and Transfers:      $391.10
All Transactions excluding Transfers:                                   $391.10

In Filtering Details-

Delete the blank row below 'Filtering Details'?

When filtering on columns can they be on one line like Types? Filtering on three columns takes up five lines.
 
When filtering on accounts is it necessary to list the accounts in the footer since they are in the header too? Here too each filtered account takes up a line. In the header they are on one line.

**Comment by whalley** [comment]
For the first item we need to be careful to consider how this is presented when the report has multiple currencies, see below. Though we could include the total on the heading line as you note. ![CleanShot 2022-03-05 at 19 08 56](https://user-images.githubusercontent.com/487345/156896918-27f4e193-5aa9-4bcd-a657-37a0e7138a91.png)

For the Filtering Details I agree it may be best to capture as a single, line wrapped entry. Though I would suggest leaving the accounts in for completness.

**Comment by 2BeeOrNot** [comment]
It makes sense now. I've never uses multiple currencies.

Putting the filtering details on one line would be nice.
