### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4248]
![Cattura](https://user-images.githubusercontent.com/6836805/157121094-7b1f1d50-9c9b-4d57-8281-3056d0d3289b.JPG)

**Comment by whalley** [comment]
Is that in the Newsfeed RSS or some other import?

**Comment by vomikan** [comment]
I've got the screenshot by WhatsApp messenger.

**Comment by whalley** [comment]
OK, I did test the new RSS feed and it did seem to work OK. Suspect (hope) it is something else.
