### ISSUE TITLE
1.5.14-Beta.1 does not compile on Ubuntu 18.04 'bionic'

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#4258]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

1.5.14-Beta.1 does not compile on Ubuntu 18.04 'bionic'
compile error message:

> [ 49%] Building CXX object src/CMakeFiles/mmex.dir/maincurrencydialog.cpp.o
> ...
> In file included from /home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.h:28:0,
>                  from /home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.cpp:29:
> /home/pmaff/mmextest/latest/moneymanagerex/src/reports/mmDateRange.h: In member function ‘const int mmDateRange::startDay() const’:
> /home/pmaff/mmextest/latest/moneymanagerex/src/reports/mmDateRange.h:167:62: warning: nonnull argument ‘this’ compared to NULL [-Wnonnull-compare]
>  inline const int mmDateRange::startDay() const { return this ? startDay_ : 1; }
>                                                                                       ~~~~~^~~~~~~~~~~~~~~
> cc1plus: some warnings being treated as errors
> src/CMakeFiles/mmex.dir/build.make:590: recipe for target 'src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o' failed
> make[2]: *** [src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. use normal compile command [...]/moneymanagerex/build$ cmake --build .. --target package
2. error stops compilation

…

Expected result: compile normal, link, produce deb-file.

Actual result: compilation not possible under Linux, Ubuntu 18.04 'bionic'

**Comment by whalley** [comment]
Yes, the code looks a bit odd here.... 'this' should indeed always be non-NULL, otherwise don't see how the method could be called! Spotted another redundancy in the initializer also.

**Comment by PMaff** [comment]
Is this already in the code?

I do get "Version        : 1.5.14-Beta.1" here still and compilation fails with:
```
/home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.cpp: In member function ‘bool mmFilterTransactionsDialog::is_custom_field_matches(const DB_Table_CHECKINGACCOUNT_V1::Data&) const’:
/home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.cpp:1797:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return matched == cf.size();
            ~~~~~~~~^~~~~~~~~~~~
cc1plus: some warnings being treated as errors
src/CMakeFiles/mmex.dir/build.make:590: recipe for target 'src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o' failed
make[2]: *** [src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by PMaff** [comment]
```
/home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.cpp: In member function ‘void mmFilterTransactionsDialog::from_json(const wxString&)’:
/home/pmaff/mmextest/latest/moneymanagerex/src/filtertransdialog.cpp:1621:81: error: use of old-style cast [-Werror=old-style-cast]
             auto value = j_doc[const_cast<char*>((const char*)udfc_entry.mb_str())].GetString();
                                                                                 ^
cc1plus: some warnings being treated as errors
src/CMakeFiles/mmex.dir/build.make:590: recipe for target 'src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o' failed
make[2]: *** [src/CMakeFiles/mmex.dir/filtertransdialog.cpp.o] Error 1
```

**Comment by PMaff** [comment]
Success.
Build is complete.
Ticket can be closed for now.

```
[100%] Built target mmex
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: MMEX
CPack: - Install project: MMEX
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/pmaff/mmextest/latest/moneymanagerex/mmex_1.5.14-Beta.1-1~bionic_amd64.deb generated.
```
