### ISSUE TITLE
UK HMRC Digital Tax returns

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4264]
# Description of the feature

United Kingdom (UK) Her Majesty's Revenue and Customs (HMRC) claim they are leading the world in making tax returns digital (MTD) and paper-less. This will make paper returns obsolete. This will go live in the UK financial year starting from April 2023.

Therefore: Have you any plans to make an Interface or Bridging Software between MM Ex's report or export structure and HMRC's APIs?

Informative internet essay about MTD at:
[https://barnesroffe.com/making-tax-digi ... prepared-2](https://barnesroffe.com/making-tax-digital-for-income-tax-be-prepared-be-very-prepared-2)
and the HMRC has advice for developers at :
[https://developer.service.hmrc.gov.uk/g ... vice-guide](https://developer.service.hmrc.gov.uk/guides/self-assessment-end-to-end-service-guide)

https://forum.moneymanagerex.org/viewtopic.php?t=10576

**Comment by jensb** [comment]
"Leading the world in digital" is funny, because paperlass digital-only tax returns in Germany are mandatory (!) since 2011 for anyone with a business, optional for everybody else, and available in some form or other since 1999. Check www.elster.de (ELektronische STeuer-ERklärung). There is an API and all tax software uses this API.

The question is, what is your use case? What information do you want to get out of your tax return and why into MMEX?
If it's just the amount, you'll get that by your bank as well.

**Comment by tactilis** [comment]
> What information do you want to get out of your tax return and why into MMEX?

You have misunderstood what MTD for ITSA is about. This feature request relates to providing information _from_ MMEX _to_ HMRC.

**Comment by jensb** [comment]
True, sorry.
However, the question remains. What is the specific use case? Can you give an example where this would benefit?
Is the idea that you somehow label/tag your expenses in MMEX and upload this as (or supporting) your tax return?
This would need a whole lot of metadata which MMEX simply doesn't have right now, so it would be quite a large task.

**Comment by tactilis** [comment]
> However, the question remains. What is the specific use case? Can you give an example where this would benefit? Is the idea that you somehow label/tag your expenses in MMEX and upload this as (or supporting) your tax return? This would need a whole lot of metadata which MMEX simply doesn't have right now, so it would be quite a large task.

Exactly!

Please see the original request in the forum post [https://forum.moneymanagerex.org/viewtopic.php?t=10576](https://forum.moneymanagerex.org/viewtopic.php?t=10576). I don't think any detailed thought has been given to use case and workflow. I think it just seemed to the OP like a 'Good Idea'.

I have been involved (peripherally) with a company that makes an accounting product for businesses and for landlords that has been extended for HMRC MTD for VAT and is being extended for MTD ITSA. The work for this is huge. The workflow is not as simple as the OP might have thought. There are lots of corner cases to consider. The software, whether full API or Bridging, needs to be approved by HMRC, and need to be kept up to date with any changes at the HMRC end.

Yes, it would be great if this were done (for UK users of MMEX) - but at present, we don't have anyone who has the time to even keep the MMEX User Manual up to date, or to produce a test suite for MMEX, so fulfilling this MTD request would be a massive step and would impose obligations on the project that people may not be willing to take on.

Just trying to be realistic.

**Comment by whalley** [comment]
Given the resources available and the size of this task it just will not happen.
