### ISSUE TITLE
DE Language Pack improvement

### ISSUE THREAD

**Issue by xenon2008** [moneymanagerex/moneymanagerex#4265]
Hello together,

I am new here and installed MMEX for the first time.
I choose German as my Language, and in the Settings i saw a little maybe wrong translation.

![grafik](https://user-images.githubusercontent.com/12835450/160296684-dd1cff0f-89dd-4829-9d87-fd2911bc4683.png)

either the same option is shown twice here, or a translation is not entirely correct.
Since I've only been using the program for 5 minutes, I'm honestly not sure yet 

Kindly Regards from Upper Austria

**Comment by tactilis** [comment]
They are different options:

![image](https://user-images.githubusercontent.com/4060092/160297821-60e6efc5-ea83-4b1f-b334-956a6712b4a5.png)

**Comment by vomikan** [comment]
You can independently suggest the correct translation using this site:

https://crowdin.com/translate/moneymanagerex/470/en-de?filter=basic&value=3#q=%22use%20original%20date%20when%22

Or write the correct phrases in German here. I can easily apply them.

**Comment by xenon2008** [comment]
> I have modified the text. **Originaldatum bei der Duplizierung von Transaktionen verwenden**
> 
> Many greetings from Switzerland

very cool, thanks!
