### ISSUE TITLE
Feature: Indicate split in the recurring transactions list

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#427]
Similar to (https://github.com/moneymanagerex/android-money-manager-ex/issues/78), I believe it would be more user-friendly to display an unambiguous indicator that a scheduled transaction contains a split transaction.

I see that this is already implemented for standard transaction. So, the same thing could be added for the recurring transactions list.

Once a decision is made on the feature, we would implement the same in the mobile version.

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team  any one want to take this? @stef145g

**Comment by stef145g** [comment]
An update for this is in the pull request: Bill deposit updates https://github.com/moneymanagerex/moneymanagerex/pull/449

**Comment by stef145g** [comment]
Implementation now merged into Master ...closing this issue.
