### ISSUE TITLE
memory: prefix

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4275]
I've discovered that memory: prefix not needed for reports in a virtual memory.

![image](https://user-images.githubusercontent.com/6836805/161448259-1f296714-b135-4ab7-8b0a-c73fb6e227fa.png)

**Comment by whalley** [comment]
It seems to be needed on MacOS. Also without the 'memory:' prefix how would you plan to handle the getVFname4print for the Linux temp files?
![CleanShot 2022-04-04 at 01 30 25](https://user-images.githubusercontent.com/487345/161456100-4ac65063-c4ef-4b01-8a52-98cfce322f36.png)

**Comment by vomikan** [comment]
OK, no changes needed for this issue.
