### ISSUE TITLE
Custom financial platform source to track stocks,funds,crypto....

### ISSUE THREAD

**Issue by sogun771** [moneymanagerex/moneymanagerex#4276]
# Description of the feature

Custom source (In addition of Yahoo Finance) to allow multiple financial platform to track automatically stocks, funds, crypto...
Using a predefine list or let custom query (similar to portfolio-performance ? )

# Use cases

Currently, Only Yahoo finance is supported as source but only include major stocks, funds which might not be ideal for a lot of users... allowing to choose which financial platform to track data will be a big milestone for MoneyManager EX (Example from Bloomberg, Investing.com, yahoo finance). 

Thank you

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2702
