### ISSUE TITLE
cannot run Mac version 1.5.13

### ISSUE THREAD

**Issue by alanp864** [moneymanagerex/moneymanagerex#4278]
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already.
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue for similar problem - update existing issue instead of creating new one.
> 3. Put some descriptive name for your issue in the Title field above.
> 4. Replace this text (marked with >) with detailed description of your problem.
> Read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html for useful tips.
> 5. Include steps to reproduce your issue, attach screenshots where appropriate.
> 6. Please do not remove information attached below this text.

<hr><small><b>Version</b>: 1.4.0-alpha.6 • db 13 (aes128cbc) • git d2f82a34 (2018-10-30)<br><b>Libs</b>: wxWidgets 3.1.1 (wxMac 10.16) • wxSQLite3 4.1.1 (SQLite 3.25.2) • Mongoose 6.13 • RapidJSON 1.1.0 • Lua 5.3.4 • libcurl 7.77.0 • (SecureTransport) • LibreSSL 2.8.3 • zlib 1.2.11 • nghttp2 1.42.0<br><b>Build</b>: Oct 30 2018 22:54:39 • CMake 3.12.2 • Xcode 10.0 • gettext 0.19.8.1 • Clang 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)<br><b>OS</b>: macOS Version 10.16 (Build 21D62) • English (Western (Mac OS Roman)) • 2048x1152 32bit 108x108ppi</small>

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by renato-mmex** [comment]
You can send the database as a .zip to mmex-reg@bluewin.ch and I will send you back the converted version.
Greetings Renato (Moderator of MMEX)

**Comment by alanp864** [comment]
Hi Renato,

Thanks for that but I don’t really want to release 16 years of my financial information out to anyone. I’m a retired IT developer, is there any other way we can get this done.

By the way, I’ve now discovered a work round for my 1.4.0 version problem, which is a bit strange. If MMEX is the first app opened after a Mac reboot or restart, it works fine, but otherwise not. I wonder if this is related to the fact I’m normally running Microsoft office apps on my Mac.

Regards

Alan



From: Renato ***@***.***>
Date: Monday, 4 April 2022 at 22:08
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: alanp864 ***@***.***>, State change ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] cannot run Mac version 1.5.13 (Issue #4278)

You can send the database as a .zip to ***@***.******@***.***> and I will send you back the converted version.
Greetings Renato (Moderator of MMEX)

**Comment by renato-mmex** [comment]
Hi Alan
I absolutely understand the reluctance to give your personal information to others. As a former head of IT for a large trust company, I am used to dealing with confidential data. My offer still stands, otherwise I recommend to run the script as described on #2353 (mmex_DB_downgrade_v13_to_v7.zip) under MMEX or with a DB browser (SQLite).
Greetings Renato

**Comment by alanp864** [comment]
Hi Renato,

Brilliant, I’ve run that and now MMEX version 1.5.13 runs fine. It also looks to have a much better interface than the 1.4 version. Well done you guys.

Cheers

Alan

From: Renato ***@***.***>
Date: Tuesday, 5 April 2022 at 11:24
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: alanp864 ***@***.***>, State change ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] cannot run Mac version 1.5.13 (Issue #4278)

Hi Alan
I absolutely understand the reluctance to give your personal information to others. As a former head of IT for a large trust company, I am used to dealing with confidential data. My offer still stands, otherwise I recommend to run the script as described on #2353<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmoneymanagerex%2Fmoneymanagerex%2Fissues%2F2353&data=04%7C01%7C%7C662d15d1f97a462eef1608da16ee69db%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637847510472513510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HXSWLOEaZIfEAE2IDwZZ3JhkEt7bT7F6KQ3rNZAUk2E%3D&reserved=0> (mmex_DB_downgrade_v13_to_v7.zip) under MMEX or with a DB browser (SQLite).
Greetings Renato
