### ISSUE TITLE
Add Payee Information Fields

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#4280]
# Description of the feature

I would like to have additional fields to store details about each payee. I think it would be useful to have account number, contact information, and perhaps address.  Or at a minimum, a notes field where I can store that free form information.

# Use cases
For many payees it's convenient to have payment and contact information, and it would be a nice feature to have this readily available instead of having to refer to another place.

Below is a mockup with my general idea of how this could look. All of the new fields would be optional, and available when editing a payee. The workflow of quickly adding a brand new payee when entering a transaction can remain the same, or be enhanced to show this dialog if desired.

![Snapshot](https://user-images.githubusercontent.com/95182117/162193012-f5c23f79-15ea-4c15-acaf-11753fa8b0df.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4216

**Comment by whalley** [comment]
![CleanShot 2022-10-02 at 19 56 25](https://user-images.githubusercontent.com/487345/193471244-43472180-0390-4811-ba2b-e2656cc1ca32.png)

**Comment by rmelillo76** [comment]
Thanks @whalley!!
