### ISSUE TITLE
Cannot install official .deb file on ubuntu 21.10

### ISSUE THREAD

**Issue by daniele123321** [moneymanagerex/moneymanagerex#4281]
MMEX version:
 - [x] 1.5.13-1

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Installing the .deb file on ubuntu 21.10 results in error (package wx3.0-i18n (not installed)).

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. type: sudo dpkg -i mmex_1.5.13-1.bionic_amd64.deb

…

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by PMaff** [comment]
You mean the Ubuntu build here:
https://github.com/moneymanagerex/moneymanagerex/issues/4154 ?

I compiled this for Ubuntu 18.04 LTS.
Also you have to compile wxWidget 3.1.5 for this.
I doubt that your Ubuntu release has wx3.0-i18n in the repos so probably it won't work for your Ubuntu version.

**Comment by PMaff** [comment]
See
https://github.com/moneymanagerex/moneymanagerex/issues/4298#issuecomment-1105153620
