### ISSUE TITLE
Back link no longer works for "Where the Money Goes" and "Where the Money Comes From"

### ISSUE THREAD

**Issue by dbolton** [moneymanagerex/moneymanagerex#4286]
Steps to reproduce:

1. Open MMEX 1.5.14 (64 bit)
2. Visit **Reports** > **Categories** > **Where the Money Goes** (or **Where the Money Comes From**)
3. In the table, choose a category > subcategory
4. Choose **<<Back**

Expected: it should return to the main page

Actual: nothing happens

I tested the portable version of 1.5.13 and the issue is not present there. Maybe related to https://github.com/moneymanagerex/moneymanagerex/issues/3998.

(Tested on Windows 10)

**Comment by whalley** [comment]
How odd... Don't remember changing in this area :-(

**Comment by whalley** [comment]
![CleanShot 2022-04-15 at 20 47 35](https://user-images.githubusercontent.com/487345/163625671-d2eb3ee7-c8f0-422f-9fce-c1284f6dc71f.png)

**Comment by whalley** [comment]
Fix committed (wrong issue referenced in commit) https://github.com/moneymanagerex/moneymanagerex/pull/4292/commits/b73b70dd9e3e4d69fd7dd48e8fca81f0190c1bd4

**Comment by renato-mmex** [comment]
in the version Version: 1.5.15-Beta.1 64-bit • Build on Apr 16 2022 17:09:01 it is fixed
