### ISSUE TITLE
error when starting the app

### ISSUE THREAD

**Issue by pngkonsta** [moneymanagerex/moneymanagerex#4287]
MMEX version:
 - [x] 1.2.7
 

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 10
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Migrating to Win10 (same db used in Win7) a message as follows comes up when starting the app: "xml parsing error 'mismatched tag' at line 6".

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
You use MMEX version:  1.2.7
Does the error also occur on the current version 1.5.14

**Comment by pngkonsta** [comment]
Re: [moneymanagerex/moneymanagerex] error when starting the app (Issue #4287)


Thank you for your reply.

Although I do not like the interface of v.1.5.14 (and so (so I do not use it)
I did try it and yes, the same message comes up.

Thanks again.



__________________________________

on Friday, April 15, 2022 @ 12:18:15 PM,
you wrote:






You use MMEX version: 1.2.7
Does the error also occur on the current version 1.5.14
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>




-- 

***@***.***

**Comment by tactilis** [comment]
> Although I do not like the interface of v.1.5.14

Serious question:

What aspects of the interface of v.1.5.14 do you not like compared to v.1.2.7?

**Comment by pngkonsta** [comment]
Re: [moneymanagerex/moneymanagerex] error when starting the app (Issue #4287)


Well, this might sound silly but there is no serious reason.
I just do not like those yellow arrows showing sort order.
I do have settled with the older version which I've been using since 2018.
What I mostly like is the I can attach files to every transaction.
Older version has everything I need except for the ability to make a report of not only one account.
I do not know whether newer version can do this since I rolled back to the older version without using the new one at all.
If the new version (or any version from now on) can do this, I will upgrade despite the interface.

Thanks again.



__________________________________

on Friday, April 15, 2022 @ 12:31:50 PM,
you wrote:










Although I do not like the interface of v.1.5.14


Serious question:
What aspects of the interface of v.1.5.14 do you not like compared to v.1.2.7?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>




-- 

***@***.***

**Comment by tactilis** [comment]
Not silly - but you don't have to have yellow arrows.

The latest versions of MMEX allow you to choose a user interface theme.  For example:

![image](https://user-images.githubusercontent.com/4060092/163557833-c269dcbc-9ffc-42bc-afa1-6268ebcedb76.png)
  
   
![image](https://user-images.githubusercontent.com/4060092/163558294-90843054-8d5d-4cfd-9839-93e3f4cd1e21.png)

You can even modify each of the visual elements to create your own theme if you really want to.

**Comment by whalley** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9032#p19237

**Comment by pngkonsta** [comment]
Re: [moneymanagerex/moneymanagerex] error when starting the app (Issue #4287)


Hello again.

Firstly, I must say that I had already visited this page before I wrote to you.

Secondly, I uninstalled and installed again the latest version and the message did not come up again.

Furthermore, I have to apologize as I had not worked with the latest version thoroughly.
As I worked with it again, I changed the interface per your instructions (so now I do like it) and realized that I can make a report of more than one accounts (as I always wished).

So, now, I am really satisfied with the new version.

Thank you.  



__________________________________

on Friday, April 15, 2022 @ 3:41:53 PM,
you wrote:






https://forum.moneymanagerex.org/viewtopic.php?f=24&t=9032#p19237
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>




-- 

***@***.***

**Comment by pngkonsta** [comment]
Re: [moneymanagerex/moneymanagerex] error when starting the app (Issue #4287)


I'll give it a try hoping that message stops coming up.

Thank you for your patience.

Have a nice day.



__________________________________

on Friday, April 15, 2022 @ 1:06:58 PM,
you wrote:






Not silly - but you don't have to have yellow arrows.
The latest versions of MMEX allow you to choose a user interface theme. For example:


You can even modify each of the visual elements to create your own theme if you really want to.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>




-- 

***@***.***
