### ISSUE TITLE
irresovable addiction wx3.1-i18n in Linux deb-package 1.5.13-1

### ISSUE THREAD

**Issue by Xelavir** [moneymanagerex/moneymanagerex#4288]
MMEX version:
 - [x] 1.5.13-1
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x ] Linux 

# Description of the bug

This Deb-package contains "irresovable addiction wx3.1-i18n". Install package is not starting, as the latest version of wx is wx3.0-i18n. Sorry for my English
# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by PMaff** [comment]
see
https://github.com/moneymanagerex/moneymanagerex/issues/4281

You have to compile wxWidget 3.1.5 first, since this is not in this deb file.

**Comment by Xelavir** [comment]
Thanx, solved.
