### ISSUE TITLE
datetime assertions failed

### ISSUE THREAD

**Issue by howff** [moneymanagerex/moneymanagerex#429]
Upon opening my database I am now getting these five error messages. After clicking Continue on all five they repeat again and again (about ten times) before the database finally opens. I've added a new transaction then closed and reopened but the issue persists. Has my database become corrupt?

../include/wx/datetime.h(1702): assert "tm.IsValid()" failed in Set(): invalid broken down date/time

../src/common/datetime.cpp(1221): assert "(0 < day) && (day <= GetNumberOfDays(month, year))" failed in Set(): Invalid date in wxDateTime::Set()

../src/common/datetime.cpp(1544): assert "IsValid()" failed in SetDay(): invalid wxDateTime

../src/common/datetime.cpp(1392): assert "IsValid()" failed in GetTm(): invalid wxDateTime

../include/wx/datetime.h(1740): assert "IsValid()" failed in GetTicks(): invalid wxDateTime

Using ubuntu version 1.1.0 (wxWidgets 3.0.1, SQLite3 3.8.5, wxSQLite3 3.1.1, Mongoose 5.4, Lua 5.2, GNU GCC/G++ 4.8.2)

**Comment by guanlisheng** [comment]
would you mind to share your database for test purpose ?

**Comment by tonnydourado** [comment]
I'm getting a similar error message:

````
ASSERT INFO:
../include/wx/datetime.h(1702): assert "tm.IsValid()" failed in Set(): invalid broken down date/time

BACKTRACE:
[1] wxDateTime::SetYear(int)
[2] wxWizardPage::~wxWizardPage()
[3] wxSharedPtr<wxSQLite3Database>::get() const
[4] wxDebugReportCompress::~wxDebugReportCompress()
[5] wxDebugReportCompress::~wxDebugReportCompress()
[6] wxDebugReportCompress::~wxDebugReportCompress()
[7] wxDebugReportCompress::~wxDebugReportCompress()
[8] wxString wxString::Format<wxString>(wxFormatString const&, wxString)
[9] wxString wxString::Format<wxString>(wxFormatString const&, wxString)
[10] wxEntry(int&, wchar_t**)
[11] __libc_start_main
````

I tried to take a look at the database with sqliteman, but I realized I'm not sure which table is being accessed, from the backtrace information. As a wild guess, It seems that today being the 29th of February might have something to do with it. This does not happen on the mobile app, by the way.

If you guys want, I'm willing to share my database for testing, as long I can send it privately to someone, and you don't intend to publicly share it.

**Comment by guanlisheng** [comment]
@howff would you mind to share your financial year setting here? i am suspect it is caused by incorrect calculation for financial year.

**Comment by vivimos** [comment]
I'm also getting the same error when using arch linux x86_64, MME version 1.2.5. I checked all of the dates in the database finding one error (year 0016) which was corrected but the assertion continues.

My financial year begins January 1st.

**Comment by MartinX3** [comment]
Get the same Error
Linux Mint 17.2 x64 Mate-Edition

MMEX 1.2.4

**Comment by vomikan** [comment]
Is this issue still actual?

**Comment by MartinX3** [comment]
This issue happens only on 29. february, also known as leap day or leap year day.

https://en.wikipedia.org/wiki/February_29

**Comment by vomikan** [comment]
It's already solved.

**Comment by MartinX3** [comment]
Thank you!
In 1.3.0?
