### ISSUE TITLE
wxWidgets 3.1.7 now available

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4290]
# Description of the feature

https://www.wxwidgets.org/news/2022/04/wxwidgets-3.1.6-released/

Should consider updating to include.

**Changes in this release**
In almost a year since the previous release, there have been more than 1700 commits from 82 unique contributors (41 with multiple contributions), so it is impossible to summarize all the changes in this document without making it too long, please see the [fuller changelog](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.6/docs/changes.txt) for more (but still not all) details, but some of the most important changes are:

- New [wxBitmapBundle](https://docs.wxwidgets.org/3.1.6/classwx_bitmap_bundle.html) class allowing to provide art work for both normal and high DPI in a simple way.
- New [wxUILocale](https://docs.wxwidgets.org/3.1.6/classwx_u_i_locale.html) class replacing the old (but still available) wxLocale, but not suffering from its multiple problems and providing more functionality.
- Support for using native spell-checking in wxTextCtrl.
- Support for undo/redo in wxTextCtrl in wxOSX.
- Better drag-and-drop implementation in wxOSX.
- Fixes for important bugs in wxDataViewCtrl under all platforms.
- Many improvements and bug fixes for Wayland support in wxGTK.
- Support for the latest OS versions (Windows 11, macOS 12) and compilers (MSVS 2022, gcc 12, clang 13).
- Project bug tracker has been moved to GitHub Issues.

Notice that in spite of all the changes, this release remains almost completely compatible with 3.1.5 at the API level, so upgrading to it if you’re already using wxWidgets 3.1 should be straightforward.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/163686031-84159b8d-4df0-4f17-b59d-8acfb35c4abc.png)

**Comment by whalley** [comment]
Yep, seems to work fine on MacOS...

<img width="406" alt="CleanShot 2022-04-17 at 23 59 22@2x" src="https://user-images.githubusercontent.com/487345/163735298-214c574f-3d07-49eb-a85b-9611e3afe0d7.png">

**Comment by whalley** [comment]
Also works well with Linux.

![CleanShot 2022-04-18 at 19 11 56](https://user-images.githubusercontent.com/487345/163854184-aa5bfab9-b81b-4b2f-b978-1f15b52c49d7.png)

**Comment by whalley** [comment]
Have found an issue on MacOS when opening the 'New Account' wizard. When having app open on main display then invoking wizard it works fine. However, if I open the wizard with the app on any of my secondary monitors the application crashes. Having debugged it looks like some failure in handling the wxHandleDPIChanged event that is new for 3.1.6.

Could somebody please test the same on Windows using multiple monitors.

**Comment by renato-mmex** [comment]
I have tested under Windows 11 on my 3 monitors, no problem found.
1080x1920 (100%), 3840x2160 (150%), 3840x2160 (150% main monitor)

Version: 1.5.15-Beta.1 64-bit
• Build on Apr 16 2022 17:09:01
• Database version: 7 • (aes128cbc)
• Git commit: d37b74b (2022-04-16)
MMEX is using the following support products:
**• wxWidgets 3.1.6 (wxMSW 10.0)**
• wxSQLite3 4.6.0 (SQLite 3.31.1)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4298#issuecomment-1105153620

**Comment by PMaff** [comment]
Does this mean I should switch to wxWidget 3.1.6 when I compile the Linux binaries here:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issue-1120042178
?
I sometimes use wxWidget 3.1.5 and sometimes 3.1.6 .

**Comment by vomikan** [comment]
I've just upgraded it for Windows build of mmex.
There are no any changes in mmex code regarding this.

**Comment by PMaff** [comment]
> I've just upgraded it for Windows build of mmex. There are no any changes in mmex code regarding this. But @whalley reported some issues with wx 3.1.6 on MAC.

@whalley  writes:
"Until these are resolved the MacOS build will continue to utilise v3.1.5"
so I guess I should stay with wxWidget 3.1.5 also when compiling the Linux stuff?

**Comment by whalley** [comment]
Windows has moved to 3.1.6 so if you have no identified issues on Linux then I would suggest also moving to 3.1.6. I'm just holding back on MacOS until the identified issues are resolved.

**Comment by whalley** [comment]
@vomikan What was the reason to revert to 3.1.5 for non MacOS?

**Comment by vomikan** [comment]
### 3.1.7
Due by June 06, 2022 97% complete
Last release before 3.2.0.

https://github.com/wxWidgets/wxWidgets/milestone/12

**Comment by whalley** [comment]
Question is.... do we want to leave this for v1.5.16 or be brave and roll into v1.5.15 ?

**Comment by vomikan** [comment]
#4335 
It is advisable to leave 3.1.5 until the solution of this case.

**Comment by whalley** [comment]
Issue found on macOS, can somebody confirm if the issue also applies to Windows and Linux?

wx3.1.5
![CleanShot 2022-06-06 at 23 52 37](https://user-images.githubusercontent.com/487345/172262345-7284ee33-e21b-47f3-8a47-ac98df282e57.png)

wx3.1.7
![CleanShot 2022-06-06 at 23 55 17](https://user-images.githubusercontent.com/487345/172262563-0a6dfc35-23db-4b94-a1f8-f357d29f13e5.png)

**Comment by vomikan** [comment]
Without changes.
![image](https://user-images.githubusercontent.com/6836805/172339588-bc1171b6-1e5c-4aa9-aeea-b979792bc385.png)

**Comment by whalley** [comment]
OK, I'll do a bit more investigation to see what resulted in this change of behavior, but sounds like we have a compatible fix.

**Comment by whalley** [comment]
https://github.com/wxWidgets/wxWidgets/issues/22374

**Comment by vomikan** [comment]
The issue fixed 
![image](https://user-images.githubusercontent.com/6836805/172376529-70f16715-16a2-495d-a1ca-5d479045994e.png)

**Comment by PMaff** [comment]
I compiled wxWidget 3.1.7  on a Virtual jammy 22.04 and mmex with:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.15-Beta.4
-- Commit         : e6b7af90f (2022-06-07)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.15.0-33-generic
-- Ubuntu 22.04 'jammy'
-- CMake 3.22.1
-- GNU Make 4.3
-- ccache 4.5.1
-- GNU 11.2.0
-- wxWidgets 3.1.7
-- wxSQLite3 4.6.0
-- RapidJSON 1.1.0
-- Lua 5.3.6
-- curl 7.81.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done
```
and when opening the new transaction dialog, there is a number of assertions like the one in the screenshot:

![assertion3_1_7_mmex1_5_15](https://user-images.githubusercontent.com/93879362/172485550-abef1131-2dad-4e34-8476-6ffdf93d55b7.jpg)

The new transaction dialog hangs then (see 2nd screenshot) and I have to kill mmex afterwards:

![finalwxWidget3_1_7_mmex_1_5_15](https://user-images.githubusercontent.com/93879362/172485717-304f2466-2fc9-4641-8f92-e769d2a9dc46.jpg)

I was using
`...moneymanagerex/build$ ../_CPack_Packages/Linux/DEB/mmex-1.5.15-Beta.4-Linux/usr/bin/mmex `
for testing
and in the xterm I see:
```
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(963): assert ""IsOk()"" failed in GetHeight(): invalid bitmap
../src/gtk/bitmap.cpp(1032): assert ""m_refData"" failed in GetScaleFactor(): invalid bitmap
../src/gtk/bitmap.cpp(970): assert ""IsOk()"" failed in GetWidth(): invalid bitmap
Killed
```

**Comment by whalley** [comment]
> Adding an Expand flag when adding the amount Sizer seems to fix it, but could not spot any change in this area in the release notes.
> ` flex_sizer->Add(amountSizer, wxSizerFlags().Expand());`

https://wxwidgets.org/blog/2021/06/sizer-asserts-in-wxwidgets-3.1/

**Comment by PMaff** [comment]
I just tried in the virtual machine and at least with

```
Money Manager Ex
Version: 1.5.15-Beta.2 64-bit
Build on May 21 2022 19:41:28
Database version: 7 â¢ (aes128cbc)
MMEX is using the following support products:
wxWidgets 3.1.6 (wxGTK 3.24)
wxSQLite3 4.6.0 (SQLite 3.31.1)
RapidJSON 1.1.0
Lua 5.2.4
lunasvg v2.3.1
libcurl/7.83.0 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
gettext 0.21
apexcharts.js
Build using:
CMake 3.23.1
GNU Make 4.3
GCC 11.2.0 â¢ ManjaroLinux 21.2.6 'Qonos'
Running on:
Manjaro Linux "Qonos"
Linux 5.15.38-1-MANJARO x86_64
KDE English (United Kingdom) (UTF-8)
0x0 0bit 96x96ppi
```
there was no such problem.
Where there changes between 1.5.15-Beta.2 and 1.5.15-Beta.4 in the code which break all this?

**Comment by PMaff** [comment]
```
Money Manager Ex
Version: 1.5.15-Beta.4 64-bit
• Build on Jun 11 2022 16:35:34
• Database version: 7 • (aes128cbc)
• Git commit: ed6aa4e5b (2022-06-09)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• lunasvg v2.3.1
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu 22.04 'jammy'
Running on:
• Ubuntu 22.04 LTS "jammy"
• Linux 5.15.0-37-generic x86_64
• English (U.S.) (UTF-8)
• 0x0 0bit 96x96ppi
```
does not throw an assertions.
Now let's recompile 3.1.6 on Jammy. 
;-)

**Comment by PMaff** [comment]
That is, where it throws the first assertion:
![assertionanddd](https://user-images.githubusercontent.com/93879362/173195824-1fae787a-b7a4-462e-9558-7e24868dd3e0.jpg)

**Comment by whalley** [comment]
@PMaff Can you test against the latest master code branch for wxWidgets, there were some very recent changes to image handling - https://github.com/wxWidgets/wxWidgets/issues/22499. Not sure if this is related but always best to check if it has been fixed.

**Comment by MartinX3** [comment]
As far as I see it works as well here

```
Version: 1.5.14 64-bit
• Aufbauend auf Juni 8 2022 22:10:58
• Datenbankversion: 7 • (aes128cbc)
• Git commit: 29d21c327 (2022-04-14)
MMEX verwendet folgene Unterstützungsprodukte:
• **wxWidgets 3.1.7 (wxGTK 3.24)**
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.0.1
• libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
• gettext 0.21
• apexcharts.js
Genutztes Build:
• CMake 3.23.2
• GNU Make 4.3
• GCC 12.1.0 • EndeavourOS rolling 'rolling'
Läuft auf:
• EndeavourOS Linux "rolling"
• Linux 5.18.3-zen1-1-zen x86_64
• (UTF-8)
• 1600x900 24bit 96x96ppi
```

**Comment by PMaff** [comment]
> @PMaff Just a thought, I see they have different LunaSVG builds - lunasvg v2.0.1 and lunasvg v2.3.1 ? LunaSVG was changed here: #4302
> 
> Can you try the latest MMEX build but with lunasvg v2.0.1

I removed the lunavsg from the trunk sources that I get with 
`git clone --recursive https://github.com/moneymanagerex/moneymanagerex`
and copied the 
`cp -a ../../../mmex1_5_14/moneymanagerex/3rd/lunasvg .`
into moneymanagerex/3rd/.

But then I get a compile error:
```
/home/pmaff/Technical/Finance/MMEX/latest/moneymanagerex/src/images_list.cpp:36:10: fatal error: ../3rd/lunasvg/include/lunasvg.h: No such file or directory
   36 | #include "../3rd/lunasvg/include/lunasvg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/CMakeFiles/mmex.dir/build.make:412: src/CMakeFiles/mmex.dir/images_list.cpp.o] Error 1
```
So also the header files changed:
ll ../../lunasvg231/include/lunasvg.h 
-rw-rw-r-- 1 pmaff pmaff 7144 Jun 13 20:33 ../../lunasvg231/include/lunasvg.h

**Comment by whalley** [comment]
The lunasvg version is currently hardcoded into the util.cpp file at present, see https://github.com/moneymanagerex/moneymanagerex/issues/4302 so don't worry about that

**Comment by PMaff** [comment]
> The lunasvg version is currently hardcoded into the util.cpp file at present, see #4302 so don't worry about that. Sounds like the cause is not lunasvg change, at least we have eliminated that!

Ok ,so no need to start all over again but that also means that lunasvg 2.0.1 does not change the error.

**Comment by whalley** [comment]
@PMaff A long shot here.... I had some crashes attributed to image handling in wxWidgets (https://github.com/wxWidgets/wxWidgets/issues/22540) and needed to do a clean/rebuild of wxWidgets that fixed it. Not sure if this would fix your issue.

**Comment by PMaff** [comment]
> @PMaff A long shot here.... I had some crashes attributed to image handling in wxWidgets ([wxWidgets/wxWidgets#22540](https://github.com/wxWidgets/wxWidgets/issues/22540)) and needed to do a clean/rebuild of wxWidgets that fixed it. Not sure if this would fix your issue.

Normally I delete the wxWidgets after I start a new try.
But I will try once more.

**Comment by PMaff** [comment]
Removed
wxWidgets
```
git clone https://github.com/wxWidgets/wxWidgets
cd wxWidgets 
git submodule init
git submodule update
mkdir build-release-gtk3
cd build-release-gtk3/
../configure --disable-shared --enable-stl --enable-utf8only --enable-intl  --enable-xlocale  --enable-webviewwebkit --with-gtk=3
make and make install as sudo
```
as every time.

```
wx-config --version-full
3.1.7.0
```

Then erased latest/moneymanagerex.
`git clone --recursive https://github.com/moneymanagerex/moneymanagerex`

so that I get a brandnew wxWidgets and a brandnew mmex,
compilation is ok, afterwards:
moneymanagerex/build$ ../_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/bin/mmex 
with 
```
Money Manager Ex
Version: 1.5.16-Beta.1 64-bit
• Build on Jun 17 2022 16:51:51
• Database version: 7 • (aes128cbc)
• Git commit: a7f142739 (2022-06-17)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• lunasvg v2.3.1
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu 22.04 'jammy'
Running on:
• Ubuntu 22.04 LTS "jammy"
• Linux 5.15.0-37-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

but still the above error is there.

Btw. with which version shall I compile 1.5.15 : with wxWidets 3.1.5 or 3.1.6?

**Comment by whalley** [comment]
> Btw. with which version shall I compile 1.5.15 : with wxWidets 3.1.5 or 3.1.6?

3.1.5 please, but might be worthwhile holding off for now. We may be looking to get 1.5.16 out next week to address some issues found in 1.5.15.

**Comment by PMaff** [comment]
> > Btw. with which version shall I compile 1.5.15 : with wxWidets 3.1.5 or 3.1.6?
> 
> 3.1.5 please, but might be worthwhile holding off for now. We may be looking to get 1.5.16 out next week to address some issues found in 1.5.15.

Short test of :
```
Money Manager Ex
Version: 1.5.15 64-bit
• Aufbauend auf Juni 17 2022 17:15:19
• Datenbankversion: 7 • (aes128cbc)
• Git commit: e7bb96ccc (2022-06-16)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.1.5 (wxGTK 3.22)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.3
• lunasvg v2.3.1
• libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
• gettext 0.19.8.1
• apexcharts.js
Genutztes Build:
• CMake 3.22.0
• GNU Make 4.1
• GCC 7.5.0 • Ubuntu 18.04 'bionic'
Läuft auf:
• Ubuntu 18.04.6 LTS "bionic"
• Linux 4.15.0-187-generic x86_64
• English (UTF-8)
• 1920x1080 24bit 96x96ppi
```
seems to be ok, but if you say I shall wait till 1.5.16 I will do so.

**Comment by PMaff** [comment]
Opened a issue:
https://github.com/wxWidgets/wxWidgets/issues/22550#issue-1275209465

**Comment by whalley** [comment]
@PMaff Looks like https://github.com/wxWidgets/wxWidgets/issues/22550 is fixed now. Do you want to give it a go?

**Comment by PMaff** [comment]
> @PMaff Looks like [wxWidgets/wxWidgets#22550](https://github.com/wxWidgets/wxWidgets/issues/22550) is fixed now. Do you want to give it a go?

Yes, but before that I will do the various Linux compiles with wxWidget 3.1.5 and the new mmex 1.5.16 stable. ;-)
