### ISSUE TITLE
Unable to install latest production version of app in Ubuntu 21.10

### ISSUE THREAD

**Issue by Aravinth-Earth** [moneymanagerex/moneymanagerex#4298]
MMEX version:
 - [x] 1.5.14-1 [from the official package here](https://moneymanagerex.org/docs/downloads/latest/)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Linux  >> Ubuntu 21.10

# Description of the bug

Unable to install the downloaded package provided in official site (named 'mmex_1.5.14-1.bionic_amd64.deb')

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Download the file from [here](https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.5.14/mmex_1.5.14-1.bionic_amd64.deb)
2. Try install it by any possible way in Ubuntu 21.10

…

Expected result:
Successful installation of package

Actual result:
```
sudo dpkg -i ./mmex_1.5.14-1.bionic_amd64.deb 
Selecting previously unselected package mmex.
(Reading database ... 200700 files and directories currently installed.)
Preparing to unpack .../mmex_1.5.14-1.bionic_amd64.deb ...
Unpacking mmex (1.5.14-1~bionic) ...
dpkg: dependency problems prevent configuration of mmex:
 mmex depends on wx3.1-i18n; however:
  Package wx3.1-i18n is not installed.
 mmex depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0 is not installed.

dpkg: error processing package mmex (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.69ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 mmex
```

# Additional information
1. As the name says bionic, The first query is  - Does it not supports the later version?
2. Tried installing  those specific packages, But seems there are not available to install
    ```
    sudo apt-get wx3.1-i18n
    E: Invalid operation wx3.1-i18n
    
    sudo apt-get libgdk-pixbuf2.0-0
    E: Invalid operation libgdk-pixbuf2.0-0
    ```

**Comment by PMaff** [comment]
See
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1100760778

You have to compile wxWidget 3.1.5 since this is not contained in the Ubuntu 18.04 package that I compiled.
I did not test the *.deb for Ubuntu 21.10 so maybe the 18.04 version is not working for 21.10 at all.

But since the compile instructions for wxWidget 3.1.5 and mmex 1.5.14 are easy, you might try yourself.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4281

**Comment by Aravinth-Earth** [comment]
Willing to try but unfortunately, Not aware of that part of making .deb from source!!
 @PMaff , Have any  steps or guide to refer ?

**Comment by vomikan** [comment]
FYI
https://github.com/moneymanagerex/moneymanagerex/issues/2472

**Comment by PMaff** [comment]
> Willing to try but unfortunately, Not aware of that part of making .deb from source!! @PMaff , Have any steps or guide to refer ?

I am not so sure about the way to do it in Ubuntu 20.04 and 21.10.
See https://github.com/moneymanagerex/moneymanagerex/issues/2472#issuecomment-1104354811

**Comment by Aravinth-Earth** [comment]
I was able to build it successfully(But yet to test all features), with the instructions from above shared issue discussion. Thank you @PMaff  @vomikan 

The config info of .deb for ref:
![MMEX Config](https://user-images.githubusercontent.com/55803552/164421903-e257ca2e-02c4-4362-bdfc-fefc8eca9c22.png)

**Comment by vomikan** [comment]
@Aravinth-Earth could you, please, upgrade wxWidgets 3.1.3 to 3.1.6 ?

**Comment by Aravinth-Earth** [comment]
Sure, I will try update & repackage..

**Comment by Aravinth-Earth** [comment]
@vomikan Here is the latest package info
![mmex about](https://user-images.githubusercontent.com/55803552/164458775-c51c5b64-c029-492f-8023-489ba016b4d6.png)
![mmex config](https://user-images.githubusercontent.com/55803552/164458784-f7702205-a58d-40d4-9fc5-e0cdd36ed5d9.png)

**Comment by Aravinth-Earth** [comment]
## Commands used:
 Adding it for future reference :)

```
curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.6/wxWidgets-3.1.6.tar.bz2
tar -xvjf wxWidgets-*.tar.bz2
cd wxWidgets-3.1.6 && mkdir gtk-build && cd gtk-build
../configure --disable-shared --enable-cxx11 --with-cxx=11 --without-libtiff --enable-webview --with-gtk=3 --enable-unicode --enable-intl
make
sudo checkinstall
sudo ldconfig
cd ../..

git clone --recursive https://github.com/moneymanagerex/moneymanagerex --branch v1.5.x
cd moneymanagerex && mkdir build && cd build
export MAKEFLAGS=-j4
cmake -DCMAKE_BUILD_TYPE=Release ..

cmake --build . --target package

sudo apt install ./mmex-.deb
```

**Comment by PMaff** [comment]
So now we have mmex 1.5.14 for 
Ubuntu 18.04, 20.04, 21.10, 22.04 ,
Suse Tumbleweed,
ManjaroLinux 21.2.6 'Qonos' .

;-)
