### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by LDUNSTONE** [moneymanagerex/moneymanagerex#4304]
> I am importing civ files but when I go to edit them it is changing withdrawals to deposits and changing the values
> Please do not remove information attached below this text.

<hr>Version: 1.5.13 64-bit<br>
 • Build: Feb  6 2022 16:14:04<br>
 • db 7 •  (aes128cbc)<br>
 • git d019150be (2022-02-06)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMac 12.2)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.22.1<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 13.0.0 (clang-1300.0.29.30)
<br>
<br>
OS:<br>
 • macOS Version 12.2.1 (Build 21D62)<br>
 •  English (Western (Mac OS Roman))<br>
 • 2560x1440 32bit 144x144ppi

**Comment by tactilis** [comment]
Please could you post:

1. A couple of lines from your data file.

2. A screenshot of your Import screen

3. A screenshot of the transaction list showing the transactions corresponding to 1. above
