### ISSUE TITLE
La base de datos se ha quedado abierta y no puedo acceder a ella

### ISSUE THREAD

**Issue by 1001balpe** [moneymanagerex/moneymanagerex#4310]
Desde hace un par de días me salen los mensajes adjuntos y me dice que la base de datos probalmenete se haya quedado abierta en anterior uso. No puedo acceder a ella y tengo muchos datos contables importantes. Adjunto capturas de pantala.
![mMEX1](https://user-images.githubusercontent.com/104494112/165480866-1196dde5-71c2-4f4d-85ad-22e184df4d40.jpg)
![mMEX2](https://user-images.githubusercontent.com/104494112/165480874-88021270-1dfa-484b-8bfd-05c28947f6e3.jpg)
Ruego me solucionen el problema lo antes posible. es importante. 
Gracias
Mi dirección es 1001balpe@gmail.com

**Comment by vomikan** [comment]
¿El bagreport se produce cuando hace clic en Yes?

**Comment by 1001balpe** [comment]
El primero, el que me dice que se ha quedado cuando abro la última base de
datos utilizada. Le doy a sí, se abre y cuando pincho en una de las cuentas
se abre el segundo, el Debug

**Comment by vomikan** [comment]
En el lugar donde se encuentra el archivo .mmb necesita ver los archivos con la extensión .bak

Tengo que intentar abrir el archivo .mmb
DB Browser for SQLite https://sqlitebrowser.org / simplemente entender que los datos se abren en principio.

**Comment by vomikan** [comment]
> El primero, el que me dice que se ha quedado cuando abro la última base de datos utilizada. Le doy a sí, se abre y cuando pincho en una de las cuentas se abre el segundo, el Debug

Este es un caso difícil, sin esta base "rota", será casi imposible entender la causa.

**Comment by renato-mmex** [comment]
Hola 1001balpe

Pude abrir el .mmb que me enviaron sin problemas con la última versión de MMEX en https://ci.appveyor.com/project/moneymanagerex/moneymanagerex.
sin ningún problema.
Sugiero desinstalar la versión antigua de MMEX e instalar esta nueva versión.
Si no funciona después, por favor, contáctame.

Muchos saludos Renato

**Comment by 1001balpe** [comment]
Muchas gracias. Lo intentaré. Ya te digo algo.

**Comment by renato-mmex** [comment]
Hola 1001balpe
¿Se ha solucionado el problema?
saludos Renato

**Comment by 1001balpe** [comment]
No  todavía no. Me ha ocurrido cuando actualicé a la nueva versión. Mañana intentaré bajar la versión anterior y probaré.Ya te Figo algo.Gracias Enviado desde mi Galaxy
-------- Mensaje original --------De: Renato ***@***.***> Fecha: 29/4/22  22:33  (GMT+01:00) Para: moneymanagerex/moneymanagerex ***@***.***> Cc: 1001balpe ***@***.***>, Author ***@***.***> Asunto: Re: [moneymanagerex/moneymanagerex] La base de datos se ha quedado abierta y no puedo acceder a ella (Issue #4310) 

Hola 1001balpe

¿Se ha solucionado el problema?

saludos Renato

**Comment by 1001balpe** [comment]
Con la versión anterior ya la he podido abrir y operar sin problemas. Gracias por todoEnviado desde mi Galaxy
-------- Mensaje original --------De: Renato ***@***.***> Fecha: 29/4/22  22:33  (GMT+01:00) Para: moneymanagerex/moneymanagerex ***@***.***> Cc: 1001balpe ***@***.***>, Author ***@***.***> Asunto: Re: [moneymanagerex/moneymanagerex] La base de datos se ha quedado abierta y no puedo acceder a ella (Issue #4310) 

Hola 1001balpe

¿Se ha solucionado el problema?

saludos Renato

**Comment by renato-mmex** [comment]
can be closed

**Comment by ronaldromejo** [comment]
Hola, 
Estoy presentado el error (**La base de datos que está intentando abrir está marcada como abierta por otra instancia de MMEX**) con la v1.7.0 (2023.12.26). Si le indico continuar muestra los datos por un lazo de 5 segundos antes de cerrar la aplicación.

Intente abrir la base de datos con la v1.6.4 (2023.06.20) y me indica que la base de datos fue actualizada y no abre.

**Comment by whalley** [comment]
@ronaldromejo  Please raise a new issue as this one was closed nearly two years ago.
