### ISSUE TITLE
mmex on ubuntu 22.04 

### ISSUE THREAD

**Issue by schugh10** [moneymanagerex/moneymanagerex#4311]
# Description of the feature
No existing version of mmex seems to work on ubuntu 22,04.  Looking for a working version of mmex on 22.04 LTS.

# Use cases

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4281

**Comment by PMaff** [comment]
@schugh10 can you try this one:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106590080
?
Please also read:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106597921

**Comment by schugh10** [comment]
Have recently switched to Linux from Windows, so will appreciate some guidance... ;-)

**Comment by schugh10** [comment]
sk@sk-SVF:~/Downloads$ sudo dpkg -i mmex_1.5.14-1.bionic_amd64.deb 
[sudo] password for sk: 
Selecting previously unselected package mmex.
(Reading database ... 282441 files and directories currently installed.)
Preparing to unpack mmex_1.5.14-1.bionic_amd64.deb ...
Unpacking mmex (1.5.14-1~bionic) ...
dpkg: dependency problems prevent configuration of mmex:
 mmex depends on wx3.1-i18n; however:
  Package wx3.1-i18n is not installed.
 mmex depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0 is not installed.

dpkg: error processing package mmex (--install):
 dependency problems - leaving unconfigured



--- Getting this dependency issue, which is also mentioned in other related issues link that you provided earlier.  Do I need to install some other packages before installing mmex?

**Comment by schugh10** [comment]
$  sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.6/ubuntu/ impish universe'
Repository: 'deb https://repos.codelite.org/wx3.1.6/ubuntu/ impish universe'
Description:
Archive for codename: impish components: universe
More info: https://repos.codelite.org/wx3.1.6/ubuntu/
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_repos_codelite_org_wx3_1_6_ubuntu_-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_repos_codelite_org_wx3_1_6_ubuntu_-jammy.list
Hit:1 http://in.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]                                                                         
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                      
Hit:4 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                                
Get:5 https://packages.microsoft.com/repos/edge stable InRelease [7,343 B]                                                      
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                     
Get:7 http://in.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [17.2 kB]
Get:8 http://in.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [59.3 kB]                 
Get:9 http://in.archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [6,632 B]
Get:10 http://in.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [19.1 kB]                         
Get:11 https://repos.codelite.org/wx3.1.6/ubuntu impish InRelease [2,145 B]                                               
Err:5 https://packages.microsoft.com/repos/edge stable InRelease                                                                        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Err:11 https://repos.codelite.org/wx3.1.6/ubuntu impish InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6856E1DB1AC82609
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [6,624 B]
Reading package lists... Done                
W: GPG error: https://packages.microsoft.com/repos/edge stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/edge stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://repos.codelite.org/wx3.1.6/ubuntu impish InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6856E1DB1AC82609
E: The repository 'https://repos.codelite.org/wx3.1.6/ubuntu impish InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


--- Tried installing the wxWidgets package, but it seems that other dependencies that this package has, they too have issues...

**Comment by schugh10** [comment]
Installed 'wine'. Am able to use the Windows ver of MMEX now.

Will prefer to fix the Linux version and use that...

**Comment by PMaff** [comment]
I put several answers into one:
> Where is " 0843d697419b112e1342dbdf727cc5af mmex_1.5.14-1~jammy_amd64.deb " available for downloading?

I just see that I uploaded it to
https://onedrive.live.com/?id=A0FB83D788D2D744%2167533&cid=A0FB83D788D2D744&authkey=%21AE%2DkxNeZZqW45a4
but @whalley did not put it to 
https://github.com/moneymanagerex/moneymanagerex/releases
as far as I can see.
Currently at
https://github.com/moneymanagerex/moneymanagerex/releases
there is only mmex for Ubuntu Bionic 18.04 LTS.

@whalley or @vomikan: can you add my Ubuntu focal and jammy compilation there?
See
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106590080
for Ubuntu jammy
and
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106588298
for Ubuntu focal

> Installed 'wine'. Am able to use the Windows ver of MMEX now.
> 
> Will prefer to fix the Linux version and use that...

No need to use Wine.
I do see that you try to install the version for Ubuntu 18.04 bionic, that probably won't work
on Ubuntu 22.04 Jammy.
Just wait till you can download the Jammy version.

The issue with wx3.1-i18n is described step by step here:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106597921
Also how you get the keys for the repository.

libgdk-pixbuf2.0-0 has to be installed in the usual way e.g. via Synaptic Package Manager.

These dependency issues have to be installed before installing mmex.

Your above output shows 2 dependency issues and missing keys for the codelite repo,
so you are only 3 steps away from using mmex on Ubuntu
unless you mean other dependencies with "but it seems that other dependencies",
which I cannot see in your above output.

The prerequsites are visible here:
https://github.com/moneymanagerex/moneymanagerex/tree/master/dockers
Just look at the corresponding Docker file.
And for Ubuntu 22.04  jammy you also just have to install the corresponding libs.

**Comment by schugh10** [comment]
After installing dependencies 'wx3.1-i18n' and 'libgdk-pixbuf2.0-0',  and the jammy version of MMEX from the onedrive link provided by you, IT IS WORKING NOW :-)

THANKS so much for your prompt replies and support... 

PS: Find MS Edge to be pretty useful currently as it really has improved and uses a whole lot less memory compared to other browsers. Gave FF on Linux a prolonged innings, but ultimately settled on Edge again because of its comparatively frugal memory usage ;-)  But I'm open to suggestions on other browsers.  Thanks again, guys.

**Comment by whalley** [comment]
Closing... We now have working 22.04 build https://github.com/moneymanagerex/moneymanagerex/issues/4724
