### ISSUE TITLE
Export accounts into separate multiple CSV files in one export click

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/moneymanagerex#4312]
currently the CSV export is exporting data to one file at a time. Feature requested is for the MMEX software to generate multiple CSV files for each account present in the .mmb file in single click; Also the file names can be the "accountname.csv" 

This would help as I have 45 accounts and I have to import these CSV files into my ACCESS database. Every time I need to export one file at a time in MMEX software and takes a lot of time. I cannot use MMEX format exported file as there are no "TRANSFER" transactions in it for destination accounts to which amount is transferred.

**Comment by vomikan** [comment]
To import all invoices at a time, uploading to JSON is better.
I think ACCESS database can import such data.

**Comment by rmkhalfay** [comment]
I just realized that I had already raised the issue earlier #2767 and forgot about it; Sorry for the duplicate request - but I have tried the json import and did not work = please refer to this issue number. Also MMEX CSV format does not work as I mentioned in my above message that the destination accounts do not have the "TRANSFER" transactions listed in the export.

**Comment by rmkhalfay** [comment]
Sir - I exported all data into one csv file in MMEX CSV format; I have many transfer transactions = to explain e.g. I transfer x amount from source account to destination account; The ID column number I checked in source account and then went to destination account to see if the same ID is there; I found only one entry for the source account and no entries in destination account; 
Can you please advise if I am doing something incorrect?

**Comment by vomikan** [comment]
For example
```
ID,Date,Status,Type,Account,Payee,Category,Amount,Currency,Number,Notes
9,2022-04-29,,Transfer,ACC (RUB),"1,00 RUB ACC (RUB) -> 2,00 USD ACC (USD)",Transfer,"-1,00",RUB,#9,
9,2022-04-29,,Transfer,ACC (USD),"1,00 RUB ACC (RUB) -> 2,00 USD ACC (USD)",Transfer,"2,00",USD,#9,
```
![image](https://user-images.githubusercontent.com/6836805/165947579-b180ba78-a7f1-46a1-825c-7ae2ce1cebae.png)

**Comment by rmkhalfay** [comment]
[test.csv](https://github.com/moneymanagerex/moneymanagerex/files/8591944/test.csv)
![image](https://user-images.githubusercontent.com/53577940/165976519-960e3c2d-c849-493b-9784-c57a0f0f9efa.png)
![image](https://user-images.githubusercontent.com/53577940/165976608-99add711-9e7a-4c10-a8f5-2dfc1d7654a5.png)

I created a dummy .mmx file - to check if my data is different / incorrect. With the two acccounts acc1 and acc2 please view the test.csv file; There are no two rows with same ID when I export using MMEX CSV file

Please help me understand what is wrong in my data?

**Comment by vomikan** [comment]
Could you change some transafer transaction to have difference between amount and to amount?
like this one
![image](https://user-images.githubusercontent.com/6836805/165990149-5174da1a-4d34-4c3a-938a-fc9bce97eed4.png)

**Comment by rmkhalfay** [comment]
Sorry did not understand - in my case the currency is same in both accounts so by clicking advanced do I have to enter same amount? When currency is different then I thought from your example you need to enter in the destination currency in other account?

**Comment by rmkhalfay** [comment]
I am also sending the mmb file for your review – which I had sent snapshots earlier

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by vomikan** [comment]
Possible, it's a bug.
