### ISSUE TITLE
Empty dialog with exclamation mark at the beginning

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#4331]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).
Verified with 1.5.16-Beta.1 .

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
At the beginning an empty dialog with exclamation mark and "OK"-button opens.
Version 1.5.16-Beta.1

If setting "German" in the stable version 1.5.14 then this dialog appears with
`build$ ../_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/bin/mmex`
If I set the language in 1.5.14 to "system default" this dialog does not appear.
![onlyOKButton](https://user-images.githubusercontent.com/93879362/167264624-edfe6c49-b7eb-4422-abdd-625f96d287eb.jpg)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1) Compile mmex 1.5.16-Beta.1 from source,
2) start mmex with `build$ ../_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/bin/mmex`
3) an empty dialog with exclamation mark and "OK"-button opens
4) select OK
5) can resume with mmex

…

Expected result:
no empty dialog or at least some information in the dialog
Actual result:
empty dialog without any information

# Additional information

If you have a backtrace for a crash or a warning, paste it here:
before that dialog:
[...]
/tmp/mmex_pmaff_tmp/mmex.png
18:30:01: Debug: Coping file:
/home/pmaff/Technical/Finance/MMEX/latest/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/share/mmex/res/umd.min.js
to
/tmp/mmex_pmaff_tmp/umd.min.js
18:30:01: Debug: Coping file:
/home/pmaff/Technical/Finance/MMEX/latest/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/share/mmex/res/ChartNew.js
to
/tmp/mmex_pmaff_tmp/ChartNew.js
18:30:01: Debug: Coping file:
/home/pmaff/Technical/Finance/MMEX/latest/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.5.16-Beta.1-Linux/usr/share/mmex/res/polyfill.min.js
to
/tmp/mmex_pmaff_tmp/polyfill.min.js
18:30:01: Debug: Adding duplicate image handler for 'PNG file'
Gtk-Message: 18:30:01.973: GtkDialog mapped without a transient parent. This is discouraged.

After selecting OK:
18:33:42: Debug: http_get_data: URL = https://www.moneymanagerex.org/blog/index.xml error = SSL peer certificate or SSH remote key was not OK
18:33:42: Debug: -- Metadata Phase?: YES
[...]

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4296
