### ISSUE TITLE
Ellipsis ...  actualization in the main menu

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4334]
It is necessary to bring it to a single standard. Somewhere there are dots, somewhere they are not. I'm in favor of removing it from the general. This is more unambiguous for translators.

![image](https://user-images.githubusercontent.com/6836805/167295695-17bbdc10-fd14-4497-a0f8-66f6a232bf92.png)

**Comment by renato-mmex** [comment]
I find 36 times points ... in the translation in the po
From my point of view it does not need ....

<img width="131" alt="image" src="https://user-images.githubusercontent.com/76920138/167296144-fd3b5d59-5be1-451c-b89b-c56512a87f63.png">

**Comment by whalley** [comment]
Don't think we can remove this on the MacOS option menu title...
![CleanShot 2022-05-16 at 01 05 30](https://user-images.githubusercontent.com/487345/168500340-5cee7d23-23cd-47c9-9a2d-79acd3a384d7.png)

For reference, Apple guidelines - https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#menu-and-menu-item-titles

state that you should
> Use an ellipsis whenever choosing a menu item requires additional input from the user. The ellipsis character (…) means a dialog or separate window will open and prompt the user for additional information or to make a choice.

**Comment by tactilis** [comment]
> Use an ellipsis whenever choosing a menu item requires additional input from the user. The ellipsis character (…) means a dialog or separate window will open and prompt the user for additional information or to make a choice.

Yes, exactly that.  That's the convention for MacOS, Windows, and Linux.

No ellipsis tells the user that the menu command will have immediate effect.
An ellipsis says that more interaction will be needed.

To me, it felt wrong to remove the ellipsis from MMEX menus because you are going against long established UI guidelines and removing information that signals something to the user.

It is possible that, over the years, the ellipsis has been applied to menus inconsistently within MMEX. I'd be happy to go through all the menus to identify where it should/should not be used if it is decided to revert this change.

**Comment by whalley** [comment]
Perhaps we leave the ... out of the actual wording used for translation and just append in the code based on the UI guidelines. It does not feel right having it in the translatable part of the menu title.

**Comment by vomikan** [comment]
| File | Accounts | Tools | View | Help |
|------|----------|-------|------|------|
| ![image](https://user-images.githubusercontent.com/6836805/169031707-398e85c4-7b3a-4d16-8225-c6b7536136b8.png) | ![image](https://user-images.githubusercontent.com/6836805/169031790-7d713d42-6f11-4cf5-864a-8bad8745f73f.png)|![image](https://user-images.githubusercontent.com/6836805/169031830-f3f87f93-0b76-41ec-8479-fe29c91a0841.png) |![image](https://user-images.githubusercontent.com/6836805/169031863-c3ed7c86-7ee9-45d2-ba9d-f2088ed35215.png) | ![image](https://user-images.githubusercontent.com/6836805/169031928-1f615a0a-8342-47b1-bdb2-c56e368ad427.png) |

**Comment by vomikan** [comment]
Question. Do we need these ellipsis in context menus?

![image](https://user-images.githubusercontent.com/6836805/169034455-8e96d8b9-8227-48cc-bdfc-6310373fe141.png)

**Comment by tactilis** [comment]
> Do we need these ellipsis in context menus? I think so.

Yes, it is the convention...
 

![image](https://user-images.githubusercontent.com/4060092/169140871-8815f96b-5890-4457-a382-9b8f2dfff011.png)
 
 
(Just looking through the MMEX menus now)

**Comment by tactilis** [comment]
Sorry it's late, but here's my view on where the ellipses should and should not be.

[MMEX menu ellipsis.pdf](https://github.com/moneymanagerex/moneymanagerex/files/8731242/MMEX.menu.ellipsis.pdf)

You may have got them all already @vomikan. Happy to discuss any that differ from yours.

**Comment by vomikan** [comment]
> Sorry it's late, but here's my view on where the ellipses should and should not be.

@tactilis Thank you, your file helped a lot.

**Comment by PMaff** [comment]
@vomikan : probably a silly question but do you or your fellow MMEX programmers use resource construction editors to
set up the dialogs and GUI with wxWidget?
[wxWidgets resource system](http://wxwindowsjp.osdn.jp/docs/html/wx/wx477.htm)

**Comment by vomikan** [comment]
> probably a silly question but do you or your fellow MMEX programmers use resource construction editors to
> set up the dialogs and GUI with wxWidget?

No. All the dialogs have been rewritten and if a new dialog is needed, then I just use a similar one as a template.

**Comment by n-stein** [comment]
@vomikan here are a few I messed up when adding the deleted transactions feature if you don't mind removing the ellipses from the right click menu:

![image](https://user-images.githubusercontent.com/16599929/210422981-3fbbb28c-44f0-4916-941b-e34f2b247f3c.png)

**Comment by vomikan** [comment]
@tactilis your expertise is required.
