### ISSUE TITLE
Question: is 1.5.14 removed from public releases?

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#4336]
I don't see it on homepage hence checking.

**Comment by renato-mmex** [comment]
http://moneymanagerex.org/docs/downloads/latest/

**Comment by reddyshyam** [comment]
Regards
Shyam
________________________________

**Comment by reddyshyam** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/12392746/167653867-a7f0dd1e-6a6a-4c8c-ae8a-526e6b24ac21.png">

**Comment by vomikan** [comment]
fixed
