### ISSUE TITLE
Frequently used notes does not display latest notes

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4352]
# Description of the feature

The sort order of the list of frequently used notes when creating/editing transactions is poor. When selecting the (max of 20) notes it uses occurrence frequency then alphabetic sort.

See: https://forum.moneymanagerex.org/viewtopic.php?t=10597

**Comment by vomikan** [comment]
Idea.
The list of notes is formed by a request for previously entered notes. I want to note that within the framework of cases #4250 and #4341, a function for saving an array of data was created. It can be used to store arbitrary notes.
