### ISSUE TITLE
recurring transaction periods calculation

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4360]
There are four items in the recurring transaction dialog menu:
"In (x) Days"
"In (x) Months"
"Every (x) Days"
"Every (x) Months"

```
    else if (repeatsType == REPEAT_IN_X_DAYS) // repeat in numRepeats Days (Once only)
        dt.Add(wxDateSpan::Days(numRepeats));
    else if (repeatsType == REPEAT_IN_X_MONTHS) // repeat in numRepeats Months (Once only)
        dt.Add(wxDateSpan::Months(numRepeats));
    else if (repeatsType == REPEAT_EVERY_X_DAYS) // repeat every numRepeats Days
        dt.Add(wxDateSpan::Days(numRepeats));
    else if (repeatsType == REPEAT_EVERY_X_MONTHS) // repeat every numRepeats Months
        dt.Add(wxDateSpan::Months(numRepeats));
```

![image](https://user-images.githubusercontent.com/6836805/168278346-1d7a4fdb-7b2e-472b-98ac-d1c185c2c8ea.png)

But the calculation for "In" and "Every" happens the same way.
Probably need to change.

**Comment by vomikan** [comment]
Today: 05/13/2022
It seems to me that there should be a possible value for "In (x) Days" (when period days = 10):
06/10/2022 - 07/10/2022, etc.

And for "Every (x) days"
05/23/2022 - 06/02/2022 - 06/12/2022, etc.

**Comment by reddyshyam** [comment]
> Today: 13/05/2022 (May) It seems to me that there should be next values for "In (x) Days" (when period days = 10): 10/06/2022 - 10/07/2022, etc.
> 
> And for "Every (x) days": 23/05/2022 - 02/06/2022 - 12/06/2022, etc.

Hi @vomikan, good day! 

So that I understand it correct, In (x) days is after x-1 days from the start of a month? 

Every (x) days sequential repeat?

If that is correct, your logic sounds good then.

**Comment by whalley** [comment]
@vomikan I've just had my DB screw up. I have an auto-execute recurring transaction set up to recur every 3 months.  The application ended up posting this multiple times and I couldn't access the app as it was constantly posting this. Having looked at the DB it now thinks the payment is 55241 days overdue and it has a payment date of 14/02/1871 !

It seems to be going backward when calculating the next date!

Not had a chance to check if this is related to this change. But manually edited the DB to stop the auto-execute, then deleted to incorrect posts.

![CleanShot 2022-05-15 at 19 36 13](https://user-images.githubusercontent.com/487345/168488700-00cc0ecd-f2cc-459b-a14e-7aaee000088c.png)

**Comment by whalley** [comment]
Think it is the Model_Billdeposits change here https://github.com/moneymanagerex/moneymanagerex/pull/4361/commits/d92c8c173f5230c71780d872bcd12a410cc30de9

For all my recurring transactions the `NUMOCCURENCES` is -1 , so when `Model_Billsdeposits::nextOccurDate(int repeatsType, int numRepeats, wxDateTime nextOccurDate)` is called from `Model_Billsdeposits::completeBDInSeries(int bdID)` it will do a subtraction rather than addition for the next date.

**Comment by whalley** [comment]
Actually, I have the recurring transaction I reported issue with set to 'Quarterly'... The issue arises on all repeating transactions that don't have a `NUMOCCURENCES` defined. 

> Today: 13/05/2022 (May) It seems to me that there should be next values for "In (x) Days" (when period days = 10): 10/06/2022 - 10/07/2022, etc.
> 
> And for "Every (x) days": 23/05/2022 - 02/06/2022 - 12/06/2022, etc.

The current logic, looking at the code is that the "In (X) days" and "In (X) months" set up a one-time recurring transaction that will happen in X days/months. Which seems to do what it says.
