### ISSUE TITLE
Online help pages

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4362]
There are more languages represented in the application than on the website.

![image](https://user-images.githubusercontent.com/6836805/168284157-5e1123cb-1f83-421d-b6d2-6f04f1527360.png)

**Comment by whalley** [comment]
Seems the Github Pages site that makes the files available has not been updated for over 2 years - https://github.com/moneymanagerex/moneymanagerex/tree/gh-pages 

The docs are surfaced from here... https://moneymanagerex.org/moneymanagerex/docs/index.html

I don't have access to the settings to setup the Pages site for this repo and there is no workflow configured to build it. 

@vomikan Do you have access to get this done?

**Comment by whalley** [comment]
gh-pages build now fixed.
https://moneymanagerex.org/ now includes correct documentation that matches that in the application.
