### ISSUE TITLE
Problem with latest version of moneymanager.ex

### ISSUE THREAD

**Issue by huntersmoon100** [moneymanagerex/moneymanagerex#4363]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
I am using moneymanager.ex you have a glitch.  I've been entering fine for about an hour now its not adding up correctly  I was minusing £3 from 919.91 result 1074.01.
- adding £3.00 was correct 1077.01 then taking £2.00 gets £331.24???  I've tried deleting and reposting but same happens.

HELP please.  I've just installed your latest upgrade never had a problem in all the years I have been using it.
contact hunter1613@gmail.com.  
The only way I could find of contacting you.  If I have to lose all this work to go back to a previous edition I am going to cry!!

![1](https://user-images.githubusercontent.com/105508232/168319575-4fc4bd55-3fb0-46f2-893a-c0e3c43f73b7.jpg)
# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once  First time it has happened in years but a new update seems to be the cause.

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by huntersmoon100** [comment]
Guys I am not a computer person, but I have used this money manager for years with no problem. I am 74 years old and fairly computer literate but certainly not a programmer.. I just need some help please.

**Comment by vomikan** [comment]
Could you, please, click on the "Date" column to recover the default transactions sort order?
![image](https://user-images.githubusercontent.com/6836805/168328660-937053a4-9b57-411f-8fec-abeafa6d9afe.png)

**Comment by huntersmoon100** [comment]
Hi Nikolay
I'm not home tonight I will pop over in the morning and send it to you.
Thank you so much for your reply.

Jacqui Hunter

**Comment by huntersmoon100** [comment]
Hi Nikolay

Its weird but when I hit the date button it scrolled up to the top and now
its corrected itself. See attached screenshot.

Any suggestions?

Kind regards

Jacqui Hunter

**Comment by vomikan** [comment]
Hi Jacqui,

Click on the column header one more time, please.

Regards, 
Nikolay

**Comment by huntersmoon100** [comment]
It's still OK. It takes either the dates to the top or bottom but it
scrolls fine both ways.  Is that what you wanted me to do?


Kind regards

Jacqui Hunter

**Comment by vomikan** [comment]
I have lost the essence of the problem. What is currently not working correctly? Screenshots are welcome.

**Comment by tactilis** [comment]
@huntersmoon100 
Jacqui

MMEX _is_ working as intended.

What you are not understanding is that when you click on a column heading (for example 'Date', 'Payee', 'Category'), MMEX sorts the list of transactions according to the clicked column.

MMEX shows you this by displaying a small up or down arrow in the heading next to the column name, according to whether the sorting is in ascending or descending order. If you click on the heading a second time, the order of sorting is reversed.

MMEX can only display the balance (i.e. do the adding up) correctly if you sort by Date.

When you had your original problem, you must have inadvertently clicked on a different column heading.

So, sort by Date, either ascending or descending as you wish, and all will be well.

**Comment by huntersmoon100** [comment]
Thank you for your help. I understand what I've done wrong. I'll double
check in future. You've been brilliant and I do so appreciate you taking
the time to do this.
I've used this application for ages and really love it.
I have contributed before but if I may I'll put a donation in the box.
Regards
Jacqui
