### ISSUE TITLE
Opening MMEX Database - Error (since updating to 1.5)

### ISSUE THREAD

**Issue by tmupton1** [moneymanagerex/moneymanagerex#4368]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

When opening an MMB file that I'd been using for two years, the MMEX program appears with a message saying 2When database file opening: [Name of file] An incorrect passowrd given for an encrypted file or attempt to open a File tat is not a database file."

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open MMEX 
2. Open MMB file (database/backup last opened/saved 8 April 2022)
3.  Error message appears

**Comment by renato-mmex** [comment]
Upgrade from version ...??.. to 1.5.????
Maybe this helps: https://github.com/moneymanagerex/moneymanagerex/issues/2353

**Comment by whalley** [comment]
Have you recently updated the application? If so from what version to what version?
Have you tried going back to a backup file?

**Comment by whalley** [comment]
Closing as no response from originator for nearly 4 months.
