### ISSUE TITLE
Category sort is incorrect with French characters

### ISSUE THREAD

**Issue by LeSabotier** [moneymanagerex/moneymanagerex#4371]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I open the Category selection, names with French accented characters appear at the end of the list. During sort, the accents should be ignored. 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

When entering/editing a transaction, open the Category selection

Expected result:

A...
B...
Élève
Enfants
Épicerie
V...
Z...

Actual result:

A...
B...
Enfants
V...
Z...
Élève
Épicerie

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by LeSabotier** [comment]
Hi,

I just tried with version 1.5.16.Beta.11 (mmex-1.5.16-Beta.1-win64-portable.zip) and the problem is still there. The categories with a name starting with an accented letter E are at the end of the list. They should be listed as part of the other categories names that start with the letter E.

See attached picture.

Thanks

![Categories](https://user-images.githubusercontent.com/105591719/174914547-51a02ee2-5a8a-4cce-b82f-5d5c7259f36a.png)

**Comment by renato-mmex** [comment]
Also with german umlauts the sort does not work correctly:
<img width="153" alt="image" src="https://user-images.githubusercontent.com/76920138/177203652-4cc6fc92-b13b-4660-97a6-6ea485fe6491.png">

**Comment by whalley** [comment]
```
std::wcscoll

int wcscoll( const wchar_t* lhs, const wchar_t* rhs );
Compares two null-terminated wide strings according to the locale most recently installed by [std::setlocale](https://en.cppreference.com/w/cpp/locale/setlocale), as defined by the [LC_COLLATE](https://en.cppreference.com/w/cpp/locale/LC_categories) category.
```
https://en.cppreference.com/w/cpp/string/wide/wcscoll
Override sort with this comparison function?   Can't seem to find anything specific in wxWidgets to assist this.

**Comment by whalley** [comment]
Using std::wcscoll I can seem to get the sort to work with accented characters *BUT* this is case-sensitive, I can't seem to find a case-insensitive equivalent! I'm sure there must be an equivalent but I can;t currently find it!

![CleanShot 2022-07-04 at 20 39 12](https://user-images.githubusercontent.com/487345/177209907-ba23dcf9-7d90-4e3c-bbae-e4f0ff94f5ac.png)

**Comment by whalley** [comment]
<img width="290" alt="CleanShot 2022-07-05 at 13 32 16@2x" src="https://user-images.githubusercontent.com/487345/177328217-6573e4a3-e78c-4cb8-84d8-c735d1385799.png">

<img width="335" alt="CleanShot 2022-07-05 at 13 32 42@2x" src="https://user-images.githubusercontent.com/487345/177328297-cdfd7b3e-a2a3-4493-99bc-44bf278723a2.png">
