### ISSUE TITLE
Transaction report Filtering details

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4401]
![image](https://user-images.githubusercontent.com/6836805/169139095-0e881271-7da5-4211-956e-1d9a097c3d0d.png)

**Comment by vomikan** [comment]
To implement this feature, you need to add style to all themes.

```
/* key / menu sequences */
kbd.menu,
kbd.key,
kbd>samp,
kbd>kbd {
    -moz-border-radius: 3px;
    -moz-box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 2px white inset;
    -webkit-border-radius: 3px;
    -webkit-box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 2px white inset;
    background-color: #f7f7f7;
    border: 1px solid #ccc;
    border-radius: 3px;
    box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 2px white inset;
    color: #333;
    display: inline-block;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 0.85em;
    line-height: 1.4;
    margin: 0 .1em;
    padding: .1em .6em;
    text-shadow: 0 1px 0 white;
}
```

**Comment by vomikan** [comment]
@whalley, is there a desire and an opportunity to choose colors for this style for a dark theme? On Windows, the dark theme is implemented poorly, I don't use it.

**Comment by whalley** [comment]
This is what it looks like this on MacOS, which looks OK.
<img width="911" alt="CleanShot 2022-05-19 at 13 59 14@2x" src="https://user-images.githubusercontent.com/487345/169299303-a6d4c8c2-c30f-44a6-a52a-1a0ae3c62d35.png">

We could add color options. What were you thinking? Foreground and background colors?

**Comment by whalley** [comment]
@vomikan Actually, should this not be in the master.css rather than hardcoded?

**Comment by vomikan** [comment]
I have already written that this style should be placed in themes. But first you need to choose colors for a dark theme.

![image](https://user-images.githubusercontent.com/6836805/169330592-f0bae753-a947-437d-9140-a18e7ed7edd7.png)

**Comment by vomikan** [comment]
A possible option for a dark theme:  
![image](https://user-images.githubusercontent.com/6836805/169342056-5524cad8-95b5-4411-9d33-291f8f1d18f4.png)


```
/* key / menu sequences */
kbd.menu,
kbd.key,
kbd>samp,
kbd>kbd {
    -moz-border-radius: 3px;
    -moz-box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 1px white inset;
    -webkit-border-radius: 3px;
    -webkit-box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 1px white inset;
    background-color: #666;
    border: 1px solid grey;
    border-radius: 4px;
    box-shadow: 0 1px 0 rgba(0,0,0,0.2),0 0 0 1px white inset;
    color: #ddd; /* font color */
    display: inline-block;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 0.90em;
    line-height: 1.4;
    margin: 0 .1em;
    padding: .1em .6em;
    text-shadow: 2px 2px 0 grey;
}
```

**Comment by vomikan** [comment]
In my opinion, the icons on our home page look good. Just a gray rectangle with a white font.
![image](https://user-images.githubusercontent.com/6836805/169361774-68f3318b-0b6a-49ea-a1fe-a4560799d5f7.png)

**Comment by whalley** [comment]
Yes, look OK in Dark Mode also.
<img width="780" alt="CleanShot 2022-05-19 at 20 49 40@2x" src="https://user-images.githubusercontent.com/487345/169391376-27ed0200-8d09-40ed-8646-a063eeed3a47.png">

**Comment by whalley** [comment]
> @vomikan Actually, should this not be in the master.css rather than hardcoded?

I must keep up!

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/169396681-aa4dc5e6-8b8e-48f4-b7e4-dcbd6a3f3d5a.png)

```
kbd.menu,
kbd.key,
kbd>samp,
kbd>kbd {
    background-color: #5a5a5a;
    border-radius: 3px;
    color: #fff;
    display: inline-block;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 0.85em;
    line-height: 1.4;
    margin: 0 .1em;
    padding: .1em .6em;
}
```

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/170587124-6ce21f63-4f34-4f6a-b4db-8146c436e103.png)
