### ISSUE TITLE
Notes are not erased when changing accounts

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#4407]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Version: 1.5.15-Beta.2 64-bit on Linux

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
The comment field at the bottom is not erased when changing the accounts

Please describe your issue with details.
1) select one sub-account 
2) select an item with notes
3) change to other sub-account e.g. "Paysafe" in the attached video.

Result: no item under the new subaccount is selected but the notes from the old selection is still there.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

See above

…

Expected result:
as soon as you change subaccounts in any Account area, all previous notes are deleted from the notes area.

Actual result:
notes stay there even if no item is selected.

https://user-images.githubusercontent.com/93879362/169282043-5654de30-0eed-4b1c-97f6-7972ada75e13.mp4

# Additional information

only screenrecorded video

**Comment by whalley** [comment]
Yep, can replicate this.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/169284002-73367617-e716-4b5d-afba-e071e74896fc.png)

**Comment by PMaff** [comment]
No, it is not the money tips, this is turned off in the menus.
It is the notes of items in the accounts.
See attached short screenrecorded film.

**Comment by vomikan** [comment]
If you turn on the tips, the problem will disappear.
This is the result of fix #3180.
Yes, this is a bug. We need to fix it.

**Comment by PMaff** [comment]
Is corrected now in 1.5.15-Beta.2 on Ubuntu 18.04 LTS.
