### ISSUE TITLE
Categories translation

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4418]
All categories are subject to translation. But in the categories dialog, when you enable any language other than English, all categories are displayed without translation.

![image](https://user-images.githubusercontent.com/6836805/169418053-f534e099-955d-48e4-80ba-920f77018174.png)

db/DB_Table_Category_V1.h:117

![image](https://user-images.githubusercontent.com/6836805/169417847-e4601f92-d390-4be4-ad39-ea71f1dca5c4.png)

Moreover, if this is corrected, there may be a conflict with the algorithm for saving the transaction filter settings. Although not a fact.

**Comment by whalley** [comment]
@vomikan Didn't we cover this here: https://github.com/moneymanagerex/moneymanagerex/issues/3724

Category and subcategory names should only be translated ONCE when the tables are first created.

**Comment by vomikan** [comment]
> Category and subcategory names should only be translated ONCE when the tables are first created.

Yes, I thought so too, but Lisheng insisted on translating categories. Now, I'm leaning towards that opinion too.



> Category and subcategory names should only be translated ONCE when the tables are first created.

And that doesn't work either. I have an OS with an English interface. Initially, when mmex is launched, there is no way to select a language. We have to create an empty database. After that, it is possible to switch the language. Finally, you can create a database for the selected language. The categories are rendered without translation.

**Comment by whalley** [comment]
I don't like the idea of potentially changing, based on translation, something that a user can edit. Perhaps at first start we pop a dialog saying "Do you want to create a default set of categories" if the user says YES then ask what language to use?

**Comment by vomikan** [comment]
There is an option, it seems to me, simpler. Add a language selection at the start of the application and create categories according to the selected language.

![image](https://user-images.githubusercontent.com/6836805/169501397-6384c31b-f6d2-4dcb-81d8-5ec1e4141d9a.png)

**Comment by whalley** [comment]
Yep seems a good suggestion.

**Comment by whalley** [comment]
Have added the option to change language at startup. However, I can't seem to get categories created in the required language when I create the DB? Am I doing something odd here?

**Comment by vomikan** [comment]
There is no translation of categories when inserted into the database. The idea of translating categories at the UI level won earlier.

**Comment by whalley** [comment]
Oh, thought I saw it in the DB code!

**Comment by vomikan** [comment]
> Oh, thought I saw it in the DB code!

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/db/DB_Table_Category_V1.h#L111-L126

wxTRANSLATE does not translate the string. Do not confuse it with _(...) and wxGetTranslation(...)

**Comment by whalley** [comment]
> wxTRANSLATE does not translate the string. Do not confuse it with _(...) and wxGetTranslation(...)

Yep, that was what clouded my mind.

**Comment by whalley** [comment]
@vomikan I also noticed when I ran the python script (was going to update the repo held src/db files before your above commit :-) ) that BD_Table_Currenyformats also had wxTRANSLATE for the currency names that is also now changed. Are your files hand-edited? Any reason why the Currencyformats have been excluded?

I see the appveyor/travis scripts always rebuild these files. (I think it would be good to update these to python3 compatible scripts at some point).

**Comment by vomikan** [comment]
@whalley I didn't use the script. It works correctly, but generates another file. I did not deal with this problem. Because the build is not done automatically for MAC, then you can leave a manual fix.

**Comment by vomikan** [comment]
> I think it would be good to update these to python3

I think it's worth doing this.

**Comment by vomikan** [comment]
@whalley I think it's better to do everything with a script. Was there a conflict after I changed the file manually?

**Comment by whalley** [comment]
There was no 'conflict' it was just that you had not manually updated the 'BD_Table_Currenyformats.h' file. I did regenerate everything from the script. it is just that for people who check out the code and build manually we need to keep the header files updated and hence run the script after we make changes and commit - that is all I did.

If we force everyone to use a script then we should remove the generated headers from the repo, otherwise, we need to re-generate when we make a change that affects them.

**Comment by vomikan** [comment]
I would prefer not to change the file with currencies. We will never wait for translations even in the most translated languages.
Can you rewrite the script to exclude the processing of the file with currencies?

 ```     db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS_V1 VALUES ('1', '%s', '$', '', '.', ' ', '', '', '100', '1', 'USD')", _("United States dollar")));```

**Comment by whalley** [comment]
@vomikan Should I create a pull request of this - https://github.com/whalley/moneymanagerex/commit/192ae0512a00967db84107abca176532f4248ab1
or just ditch it?

**Comment by vomikan** [comment]
> Should I create a pull request of this - [whalley@192ae05](https://github.com/whalley/moneymanagerex/commit/192ae0512a00967db84107abca176532f4248ab1)

Yes, please
