### ISSUE TITLE
Transaction Filter settings

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4419]
1) Period Range -> Custom - an extra element of choice. The user is not given the opportunity to set dates. Yes, but delete this element.
2) From Date - an extra menu. Redundant date range. This is implemented poorly. The dates are initialized after
the user enters the data. Non-standard names of these dates are used. I suggest deleting it.

![image](https://user-images.githubusercontent.com/6836805/169510967-aa203aa3-4469-4cd3-92f0-1c4de3f1d522.png)

**Comment by whalley** [comment]
Yes, for Period Range = "Custom" this is redundant as the Date Range can be used for this. The option should be deleted.

From range was added based on this issue https://github.com/moneymanagerex/moneymanagerex/issues/3088 and provides a way of having a filter that is on end-bounded. I think it should be retained as it complements the "Period Range"

**Comment by vomikan** [comment]
> From range was added based on this issue #3088 and provides a way of having a filter that is on end-bounded. I think it should be retained as it complements the "Period Range"

I have temporarily deleted this menu. This greatly simplified the code.
First you need to make the appropriate mmDateRange classes. Then use them by analogy with the Period Range.

**Comment by whalley** [comment]
@vomikan I'm a bit confused... What was actually wrong with the implementation. It seemed to work fine for me?

**Comment by vomikan** [comment]
> What was actually wrong with the implementation. It seemed to work fine for me?

It works fine. But the source code turned out to be very confusing.
Please be patient, it will be restored soon.

**Comment by whalley** [comment]
OK, I missed that you had been refactoring the code.

> Please be patient, it will be restored soon.

I will try my best :-)

**Comment by vomikan** [comment]
What about the following resign?

![image](https://user-images.githubusercontent.com/6836805/169600226-946e6f73-2d01-4418-aab0-b11051388901.png)

We take the date range we have. And modify the end date with two daws (either one or the other). One sets a date in the distant future, the other sets today's date.

In this case, we get a small list of dates and great possibilities for modification.
For example, all dates up to today.
Last year and all subsequent transactions. Etc...

Additionally, it is necessary to return the dates entered manually.

**Comment by vomikan** [comment]
Another option that is easier to implement is to add items to an existing menu:
Since Start of Financial Year
Since Start of This Year
Since 90 days ago
Since 30 days ago
Since Today

**Comment by whalley** [comment]
This would not have the same capability as at present. E.g. if I currently save a filter with "From  Date" = "90 Days ago" then when I go to the transaction report next week the report would change as the days move on.

What I think you are suggesting would fix the starting 'form date'. 

Unless I'm misunderstanding.

**Comment by vomikan** [comment]
The global option "Ignore Future Transaction" pisses me off. This is poorly implemented and complicates everything.

**Comment by vomikan** [comment]
> E.g. if I currently save a filter with "From Date" = "90 Days ago" then when I go to the transaction report next week the report would change as the days move on.

I do not violate this possibility in any way.

**Comment by vomikan** [comment]
I made an option that I really liked. I hope that you will also appreciate it. It may be done hastily, and there will be mistakes, but I hope for help in correcting errors and tips for improvement.

**Comment by whalley** [comment]
> I made an option that I really liked.

Afraid I don't like this at all. It is very confusing and not intuitive at all in my eyes. E.g. I can select a range of "Last Year" and an end date of Today or Future? 

Your idea of 
>Another option that is easier to implement is to add items to an existing menu:
>Since Start of Financial Year
>Since Start of This Year
>Since 90 days ago
>Since 30 days ago
>Since Today

seems good and does what it says without the complexity of the Today/Future checkboxes. 

> The global option "Ignore Future Transaction" pisses me off

Think you have spent too long on this change :-)

> This is poorly implemented and complicates everything.
> For example: There is the option "Current Month to Date". Ignore Future Transaction does not effect on it.
> Current Month. The end of the month for today is 2022-05-31. Are future transactions ignored?

For "Current Month to Date" the "Ignore Future Transactions" has no effect as "to Date" does not extend into the future.
For "Current Month" the end of the month is in the future so "Ignore Future Transactions" will cap the end date at TODAY.
If "Ignore Future Transactions" is set then we just cap the end date to TODAY if the end date for the range is past today.

**Comment by vomikan** [comment]
> seems good and does what it says without the complexity of the Today/Future checkboxes.

![image](https://user-images.githubusercontent.com/6836805/169639299-f1ee7c9e-0ef8-45d4-975d-6a0b04292b0a.png)

**Comment by gabriele-v** [comment]
I know it will be a bit more complex, but what about adding another numeric input where you can specify the number?

And then list will be only:
- Last 'N' Days
- Current Month
- Last 'N' Months
- Current Year
- Last 'N' Year
- Current Financial Year
- Last 'N' Financial Year
- Over time

Obviously it will probably needs to be added on the usual report because it will change all the mmdate function

**Comment by whalley** [comment]
> I know it will be a bit more complex, but what about adding another numeric input where you can specify the number?

Think this may complicate the range specification for casual users, but I like the idea. Suggest raising an enhancement request for this. There are other ways of doing it.

**Comment by vomikan** [comment]
@whalley, do we accept the new design?

**Comment by whalley** [comment]
Yes, I'm happy with it. Keeps the same functionality with less fields. Good work on this.

**Comment by vomikan** [comment]
Checking for an empty value does not work.
After saving any value, calling the dialog again causes a crash.

![image](https://user-images.githubusercontent.com/6836805/169702234-26dccfb7-2c27-4c6e-94a4-303044e23c46.png)

**Comment by whalley** [comment]
Cannot remove the 'Status' setting against an existing filter. 

E.g. if I save a filter with Status = "Reconcilled" it works, if I then remove the Status checkbox and save it reverts back to checked but with "Unreconcilled" as the status wanted.

**Comment by vomikan** [comment]
> Cannot remove the 'Status' setting against an existing filter.

I can't reproduce this issue.

**Comment by whalley** [comment]
Hmm.. There is another oddity, the period range seems to appear even though I did not set it. Will investigate further when I get time.

https://user-images.githubusercontent.com/487345/169715271-f4e4eb08-cb20-40bf-9024-8ed55e81f6f0.mp4

**Comment by vomikan** [comment]
@whalley, my intuition tells me that the last commit will fix this situation.

**Comment by whalley** [comment]
> @whalley, my intuition tells me that the last commit will fix this situation.

What great intuition you have..... Yes, it does indeed fix it!

**Comment by whalley** [comment]
Noticed that when saving existing settings or creating a new setting label the selected label name would always revert to the first label.

**Comment by vomikan** [comment]
As an experiment, I suggest leaving this (above) change. In this way, you can practice choosing several Payees.
If it turns out to be a good idea, then it can be expanded for cases #4439 and #2232

**Comment by whalley** [comment]
@vomikan Just spotted that autocomplete logic for MacOS had not been implemented for the Payee field in this dialog. Should not affect the Win implementation, but please check.

**Comment by vomikan** [comment]
> Just spotted that autocomplete logic for MacOS

It would be more correct to redefine the wxComboBox class. I see the file mamcombobox.h, but it is not used. With the new class, it will be easier to implement, for example, a category selection dialog.

**Comment by whalley** [comment]
> It would be more correct to redefine the wxComboBox class. I see the file mamcombobox.h, but it is not used. With the new class, it will be easier to implement, for example, a category selection dialog.

Agreed... but this is how it's done elsewhere in the codebase.    Can look to re-factor in next release.

**Comment by vomikan** [comment]
> you can practice choosing several Payees

![image](https://user-images.githubusercontent.com/6836805/169892180-d086e0f7-c4fc-47ed-b20a-f7e0f164306f.png)

![image](https://user-images.githubusercontent.com/6836805/169892238-5cc4081e-b579-4c4a-9c81-e6cbf583ce2c.png)

![image](https://user-images.githubusercontent.com/6836805/169892268-c692ff46-4d23-445c-9d26-cb0b6853368b.png)

**Comment by whalley** [comment]
> > you can practice choosing several Payees

Does not work on MacOS, probably due to the added autocomplete handling.
![CleanShot 2022-05-24 at 00 49 03](https://user-images.githubusercontent.com/487345/169921961-7079b10c-9b2f-403c-8e83-412b2447e430.png)

**Comment by whalley** [comment]
Also, after a failure to validate it seems the 'Cancel' option does not work.


https://user-images.githubusercontent.com/487345/169922577-05ea44c4-e556-43c0-af57-eaec38ada409.mp4

**Comment by whalley** [comment]
> > > you can practice choosing several Payees
> 
> Does not work on MacOS, probably due to the added autocomplete handling.

Update on this. I see that the logic validates that the RegEx matches something before it being allowed. I'm not sure this is the right thing to do here as somebody might setup a filter that currently matches no items,  matching transactions are added later....

**Comment by vomikan** [comment]
> Why impose this arbitrary restriction?

This restriction was originally there. If you enter a value in the Payee field that is not in the list, then this value does not pass validation.

**Comment by vomikan** [comment]
> **UPDATE:** It is saved and I can see that the MacOS logic will clear the field when returned as it does not match a selection. Maybe one to leave for when this gets re-factored.

Any ideas how to fix it?

**Comment by whalley** [comment]
> Any ideas how to fix it?

Not had chance to work though the logic. Maybe later today.

**Comment by vomikan** [comment]
> I think if we update the error message on an informational message (like the entered payee is missing), it will be clearer.

```
                    , wxString::Format(_("You have not used this payee name before. Is the name correct?\n%s"), payee_name)
                    , _("Confirm payee name")
                    ```

**Comment by whalley** [comment]
@vomikan Does windows need to trigger the update event when the payee data is loaded? This is what causes the issue on MacOS. If I disable the event things work fine on Mac.
```
//Payee
    Value& j_payee = GetValueByPointerWithDefault(j_doc, "/PAYEE", "");
    const wxString& s_payee = j_payee.IsString() ? wxString::FromUTF8(j_payee.GetString()) : "";
    payeeCheckBox_->SetValue(!s_payee.empty());
    cbPayee_->Enable(payeeCheckBox_->IsChecked());
    cbPayee_->SetValue(s_payee);
    //{
    //    wxCommandEvent evt(wxID_ANY);
    //    OnPayeeUpdated(evt);
    //}
```

**Comment by whalley** [comment]
Funny 'User specified start day' when reporting... The start day value seems random and sometimes it omits the field correctly.

E.g
![CleanShot 2022-05-25 at 00 25 01](https://user-images.githubusercontent.com/487345/170147822-dfc4d839-00eb-48d3-ab44-a89209a6254d.png)

**Comment by whalley** [comment]
Just noticed that sometimes the category filter, whilst saved in JSON, does not seem to be being processed when retrieving the filter.

Also when deleting a filter the old filter name is still selected.

Will check specifics later.

**Comment by whalley** [comment]
Thought it would be useful to Edit/Delete filters from the Navigation view...

![CleanShot 2022-05-25 at 23 37 10](https://user-images.githubusercontent.com/487345/170381052-fd2291ab-58e4-4a9b-9c19-0d54d55174d0.png)

**Comment by whalley** [comment]
> Just noticed that sometimes the category filter, whilst saved in JSON, does not seem to be being processed when retrieving the filter. **Can't reproduce anymore must have been something odd on my side**

There are still some oddities around the category filter.
![CleanShot 2022-05-26 at 01 30 26](https://user-images.githubusercontent.com/487345/170391065-122e0f27-328b-43bd-ac83-199de9cae9f7.png)

JSON is: `{\n    \"LABEL\": \"Deposits\",\n    \"TYPE\": \"D\"\n}`

Some other filters I have setup have the category set. If I delete these and leave this as the sole filter it is displayed and works fine... Possibly something not being cleared.

**Comment by vomikan** [comment]
> There are still some oddities around the category filter.

I can't reproduce this.

**Comment by vomikan** [comment]
I don't change anything, but this warning appears. Apparently, this was introduced recently.

![image](https://user-images.githubusercontent.com/6836805/170445044-83b60dad-6bf0-4061-af79-ef4874eab07f.png)
