### ISSUE TITLE
comboboxes for categories, payees, accounts

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4439]
I propose an alternative method of entering categories.

![image](https://user-images.githubusercontent.com/6836805/169801461-a4e3c1e4-4849-4a21-af8b-7eb7450d7c08.png)

#2232 #4419

**Comment by whalley** [comment]
Are you suggesting wesupport this in all instances where we enter a category, e.g. Transaction Report and Transactions? If so, I'm supportive.

**Comment by vomikan** [comment]
I suggest making such a choice for the transaction filter. But I don't see any barriers to doing this for transaction dialogs either.

**Comment by gabriele-v** [comment]
What if there is a category with the colon inside? Or it was not possible to add it also within the old form (never tried)?

**Comment by vomikan** [comment]
> What if there is a category with the colon inside?

What do you mean? category:with_colon:subcategory?

**Comment by gabriele-v** [comment]
Yep, or catgeory:subactegory:withcolon

If users were able to insert category or subcategory with the old system, then it's already too late even if you prohibit it in the new one, because something won't work, unless you issue also a DB patch (that at the moment it's standby also for more important changes than this) and prohibit also everywhere else (import, WebApp etc..)

**Comment by vomikan** [comment]
1) I can't enter colon. It seems autoreplace implemented.
![image](https://user-images.githubusercontent.com/6836805/171721825-7a97da71-c477-458f-a062-9825fd748945.png)
2) If you use a colon, it will negatively affect the import. I would recommend to such a user to remove colons from the category names.
3) Even if there is a colon, it does not affect this functionality in any way.
![image](https://user-images.githubusercontent.com/6836805/171723028-793441af-aeb7-48ea-a294-711efc7338d6.png)


![image](https://user-images.githubusercontent.com/6836805/171723050-601cbfa2-c4b9-4730-af85-5252f3a84ac4.png)

**Comment by vomikan** [comment]
Moreover, it is now possible to calculate such categories with a single query.
![image](https://user-images.githubusercontent.com/6836805/171724119-6e45d261-8044-4998-beca-de8e474b3f46.png)

**Comment by vomikan** [comment]
PS In this interface, you cannot create a new category, you can only select from an existing list. Or enter any text as a regular expression (a hidden option for advanced users).

**Comment by gabriele-v** [comment]
Got it, was thinking it will be used also for adding, I don't see any drawback for it as well, a part from the colon.

Because otherwise if used only for search, you will then need another button on the transdialog to open the old dialog to add a new one.

**Comment by gabriele-v** [comment]
What do you mean for payee only? Now in transdialog I can add payee simply typing even if doesn't exist.

The enter key on blank IMHO it's completely not intuitive from user side.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/171739282-fc888eeb-dbfe-41d0-be24-0f12db043a29.png)

![image](https://user-images.githubusercontent.com/6836805/171739331-2af17af7-0de4-419a-83a5-0b2080d0350a.png)

**Comment by whalley** [comment]
MacOS handling should now work.
![CleanShot 2022-06-03 at 01 24 33](https://user-images.githubusercontent.com/487345/171761959-4cabe4d3-1321-4565-b833-db52d00e792c.png)
![CleanShot 2022-06-03 at 01 25 09](https://user-images.githubusercontent.com/487345/171761969-a3906f02-6889-4a9f-94f6-8cd56c0544f0.png)

**Comment by whalley** [comment]
> Another button is not needed. You can click Enter when the window is empty. This is implemented for Payee only yet.

Pressing enter on the PAYEE field gives you the full list to view. For a new PAYEE you just enter the name of the new payee and you will be prompted as appropriate. This seems intuitive.
![CleanShot 2022-06-03 at 08 18 52](https://user-images.githubusercontent.com/487345/171806776-481fc110-b393-4df8-8f68-4b5a193fcf6c.png)

**Comment by gabriele-v** [comment]
Yes, for payee that's fine (but it was already like this in the past), but for categories if you can't add them in this way (and there is the colon issue) than is something different.

**Comment by whalley** [comment]
Some oddities with RegEx handling, based on existing PAYEE handling, that may apply to CATEGORY handing also.

If I have a set of PAYEE's and transactions as:
![CleanShot 2022-06-03 at 08 30 37](https://user-images.githubusercontent.com/487345/171808591-74da2587-b28d-4876-b8f6-9056ee4bd2d4.png)

**Yes, I have defined a PAYEE name with a valid regex format.**

Filtering on a PAYEE that is a regex match results in the regex being used, NOT the actual PAYEE name.
![CleanShot 2022-06-03 at 08 33 15](https://user-images.githubusercontent.com/487345/171812523-e70f5f34-2c42-4679-9e80-09ff3300497b.png)

These are edge cases but probably need thinking about. Perhaps we enforce that for a regex search the user needs to enter a something explict like:  
`^(MYREGEX)$` so in this case `^("A.*)$`
that way it is explicit and the chances of clashing with a valid PAYEE is practically nill. As this is for advanced users who need to understand the regex syntax I don't think this is too onerous.






and tranasactions:

**Comment by vomikan** [comment]
> Some oddities with RegEx handling, based on existing PAYEE handling, that may apply to CATEGORY handing also.

This is an interesting observation. For example, if you call payee one ```*``` (star) symbol, then it is not filtered at all.
Or the payee named ```test (test)``` cannot be found either.
There are many more such examples to come up with.

The following solutions are possible:
1) Limit the character set when creating payee.
2) Mask special characters with a backslash.

**Comment by vomikan** [comment]
An example of how the algorithm works after a fix.
![image](https://user-images.githubusercontent.com/6836805/171837253-c896ca3d-3d8a-4d79-8667-91ea59ee8559.png)

**Comment by whalley** [comment]
I think limiting the character set is difficult now that payees and categories have already been set up. We need to allow the user to define when to use a regex match and when just to use the name as-is. 
The obvious way is to add a checkbox that says 'Use regex?'. But that may be a bit confusing for casual users.

I therefor suggest the introduce a notation for saying 'I want a regex match', something like:
`^(MYREGEX)$` or `regex(MYREGEX)` or `"REGEX"` or `--REGEX--`. The chances of somebody actually having this format as a name is close to 0% so (in my view) we should not worry about it.

Doing this means we have a clear way of saying I want a regex match.

**Comment by whalley** [comment]
Just noticed that the latest fix no longer uses the category delimiter setting when displaying the categories in the drop-down.

I have the delimiter as `" : "` (i.e. space before and after), but am now presented with:
![CleanShot 2022-06-03 at 14 21 06](https://user-images.githubusercontent.com/487345/171862454-a2ca150a-1816-46aa-af2a-50806c045464.png)

**Comment by vomikan** [comment]
Here's how it can work now
![image](https://user-images.githubusercontent.com/6836805/171875887-314b0de1-1878-4d23-afdf-41149c541df8.png)

**Comment by whalley** [comment]
@vomikan Apologies, missed that before I tested. Let me re-test later :-)

Build error on the MacOS specific code, just fixed.

**Comment by gabriele-v** [comment]
I know maybe now it's a bit late, but why two such big changes (this and new filters) in the same version?
Maybe it was better to release the version with new filters, then do the proper bugfixing after release and then make this change.
Instead now after release you will need to bugfix both

**Comment by vomikan** [comment]
> I know maybe now it's a bit late, but why two such big changes (this and new filters) in the same version? Maybe it was better to release the version with new filters, then do the proper bugfixing after release and then make this change. Instead now after release you will need to bugfix both

You're right. There will be mistakes. We need to test it more thoroughly.

**Comment by vomikan** [comment]
For the future, I suggest using different widgets for Payee and to Account in the Transaction Dialog. The elements that are not used for this type of transaction must be hidden.

| label | widget | state |
|------|----------|--|
|   Account   |   [ ______________ ]        |     |  
|   Payee   |   [ ______________ ]       |      Show()
|   to (Account)   |   [ ______________ ]        |     Hide() |

**Comment by whalley** [comment]
> @vomikan Apologies, missed that before I tested. Let me re-test later :-)
> 
> Build error on the MacOS specific code, just fixed.

Apologies for delay in responding, we have had the grandchildren this weekend and they have kept me busy!

Looks good, my observations are now resolved.

**Comment by vomikan** [comment]
The choice of the base currency has been changed.
![image](https://user-images.githubusercontent.com/6836805/172605590-31b2d069-e063-4e31-b3cc-23faac92652b.png)

**Comment by whalley** [comment]
Just spotted that when editing or entering recurring transactions the account is not recognized. Also, the error message needs rewording as there is no button. 
![CleanShot 2022-06-09 at 01 12 22](https://user-images.githubusercontent.com/487345/172738029-2d2b06cb-8fb3-433c-89c1-a885ce480e91.png)

**Comment by vomikan** [comment]
@whalley Thanks for the comments. I have corrected the errors. In the future, everything will correspond to the main interface of the transaction dialog.

**Comment by whalley** [comment]
I like the look of the new category combobox but feel it is too small and needs to be at least as wide as the existing Account/Payee fields.

Maybe we just widen the dialog a bit more or allow it to be expanded.

![CleanShot 2022-06-13 at 01 39 17](https://user-images.githubusercontent.com/487345/173260670-f5108625-6bb3-4f21-9aff-fbede4e6766e.png)

**Comment by vomikan** [comment]
I suggest this view. 
I tried Resize. It works, but there are a lot of strange effects on resizeng.

![image](https://user-images.githubusercontent.com/6836805/173322737-e9b09d6a-df72-476a-bd66-59d9f44585ac.png)

**Comment by whalley** [comment]
I have an issue now that I have used ChangeValue for the mmComboBox fields. I note that for payees the validation is different than for the other comboxes which use `mmIsValid` (See transdialog.cpp). Why do we need `mmSetID`, why not just check using the GetValue() method? Have proposed simplification.

**Comment by vomikan** [comment]
In case if SetValue implemented for mmcombobox the EVT_TEXT would be activated. Then the entered value is compared with the existing data set and the ID is assigned.
In the case of Change Value, the text in the mmcombobox window simply changes. The ID remains the same.

**Comment by whalley** [comment]
Yes, appreciate the event trigger differences between SetValue/ChangeValue. So how does it work on Windows for the Payee where ChangeValue is already used?

Do the changes I proposed to mmSimpleDialog for getting the ID work to solve your issue? And do you still need the EVT_CHILD_FOCUS handling?

**Comment by vomikan** [comment]
This simplification led to regression. Now when printing the name, there is no automatic case alignment.

![image](https://user-images.githubusercontent.com/6836805/174259916-b62fe1e2-96f4-4432-adb4-46d786ef19da.png)

**Comment by whalley** [comment]
Yes, similar to the sort order issue listed here - https://github.com/moneymanagerex/moneymanagerex/issues/4625#issuecomment-1158309755. The std:map does not, by default, use a case-insensitive compare. 

If the rest of the logic looks OK, we can fix that - https://blogs.msmvps.com/gdicanio/2017/09/14/maps-with-case-insensitive-string-keys/

**Comment by whalley** [comment]
That change works for me - https://github.com/vomikan/moneymanagerex/commit/74e46479ac68da645576e1872935f9ce9fd67e74. Just need to get the actual sort order for the list correct now :-)

**Comment by whalley** [comment]
One issue, I guess you could call it a minor irritation, is that when entering categories by hand if I type the main category in a different case the logic correctly fixes this but the text entry is then positioned at the start of comobbox.
![CleanShot 2022-06-17 at 10 30 31](https://user-images.githubusercontent.com/487345/174271092-9b24ec72-6d7c-4043-ad06-c5e73baec2da.png)

**Comment by vomikan** [comment]
#4625

**Comment by jfreves** [comment]
Here it is a good example of fixing something that weren't broken.
Previous interface for categories (single and split) was way better, I'll revert to previous version for sure.

**Comment by tactilis** [comment]
@jfreves
> Here it is a good example of fixing something that weren't broken. Previous interface for categories (single and split) was way better

I agree in part - but I also think it is good to experiment with UI enhancements.

However, I don't think the change should be implemented without first looking at all the requirements and the potential impact on other parts of the application. Doing a master-branch release with only part of the changes made leads to user confusion and frustration.

I do think that category search/selection using the combobox, the operation of the new split transaction dialog, and the organize categories dialog can all be streamlined and made to work well together - but the changes probably should not have been released until they were _all_ done and extensively tested as a beta.

Just my opinion as I'm not doing the work.

**Comment by whalley** [comment]
@jfreves 

> Here it is a good example of fixing something that weren't broken. Previous interface for categories (single and split) was way better

In my view, the new way of entering these fields is greatly improved over the prior mechanism that was inconsistent and cumbersome. The new way allows a common more rapid way of entering accounts, payees, and categories. But appreciate that the views of others may differ.

> I'll revert to previous version for sure.

Of course, that is your choice but you will miss all future updates and features as we are not going back.

@tactilis 
> However, I don't think the change should be implemented without first looking at all the requirements and the potential impact on other parts of the application. Doing a master-branch release with only part of the changes made leads to user confusion and frustration.
> 
> I do think that category search/selection using the combobox, the operation of the new split transaction dialog, and the organize categories dialog can all be streamlined and made to work well together - but the changes probably should not have been released until they were _all_ done and extensively tested as a beta.

Yes, in hindsight, we should have perhaps better managed the rollout of this. We should make better use of the 'Unstable' (perhaps we rename Beta) release channel to widen the test base before the release of major changes.

<img width="540" alt="CleanShot 2022-06-28 at 18 37 23@2x" src="https://user-images.githubusercontent.com/487345/176247236-4e306751-e00d-477d-902c-df4de551c1ad.png">

**Comment by aka13-404** [comment]
I like the new way, that I can search for a category, but what I really enjoyed about the previous versions was the fact that I could have collapsed everything I did not need. Perhaps, when first opening the dropdown, only the "upper" categories can be displayed, and not all subcategories?
