### ISSUE TITLE
Grouping of accounts into subgroups

### ISSUE THREAD

**Issue by aka13-404** [moneymanagerex/moneymanagerex#4449]
# Grouping of accounts into subgroups

I have a lot of different "accounts" which belong to one entity or logical group, and which logically should be grouped together.
I would like to be able to create a collapsible subgroup which would behave like "Bank Accounts", Or "Loan Accounts".

Perhaps it would also be interesting to have a report on this subgroup, instead of individual accounts.
I have attached a mockup to explain what I mean.
I tried my best to search for similar suggestions, and found none.

![image](https://user-images.githubusercontent.com/51682059/169976638-126d1a9e-2792-497d-a1fb-5d776e97c94d.png)

**Comment by aka13-404** [comment]
Yes, 3904 is the same usecase, but for a diffferent structure, I totally missed that one.

**Comment by whalley** [comment]
The more generalised case https://github.com/moneymanagerex/moneymanagerex/issues/3894
