### ISSUE TITLE
Purchase/sale of foreign currencies

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4450]
I am looking for a simple way to post the purchase/sale of foreign currencies.
My suggestion would be an addition to the booking mask in the case "Transfer", if the currencies are not identical, then you should be able to enter an amount for the received account.

**Comment by vomikan** [comment]
I don't understand this request.
The purchase of currency in our case is a transfer from account A to account B.
We have no way to specify the exchange rate and commission, except in the comments.

**Comment by vomikan** [comment]
And what's the problem?

![image](https://user-images.githubusercontent.com/6836805/170038225-09626772-57b1-4a50-9640-b04a979934c9.png)

**Comment by whalley** [comment]
> And what's the problem?
> 
> It's just a transfer. You can make a special category for this.

That's exactly what I do when moving funds between accounts of differing currencies. Works well.

**Comment by renato-mmex** [comment]
Well, that's exactly what I was looking for.
But I did not suspect that this input option is hidden behind "Advanced" in the "Transfer".
In the English help there is a somewhat strange description, but in the German help I find nothing.
There I would like to point out again how important it is that the new features created with much diligence are also documented.
It would save us many questions and show many users what MMEX can really do.
But thanks for helping me to understand MMEX better.

by the way: if I knew how to make corrections to the help, I would do that too.

**Comment by whalley** [comment]
@renato-mmex Agreed, the documentation is sadly lagging behind.

**Comment by vomikan** [comment]
> by the way: if I knew how to make corrections to the help, I would do that too.

The best way: Clone the repository. Edit the file. Send a pull request.
For convenience, I use the [GitHub Desktop](https://desktop.github.com/) application.

**Comment by renato-mmex** [comment]
_Clone the repository_ **as a newbie I need help**
I have installed Github Desktop

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/170125638-93d4b864-d10e-4c64-a519-fa1b1dcc2d20.png)

![image](https://user-images.githubusercontent.com/6836805/170125710-7864e9be-c475-4c6a-b171-0ec1163b8b98.png)

**Comment by vomikan** [comment]
Then I reconnend to install [Atom](https://atom.io/) for html files edit. 
It is important not to break the formatting.

![image](https://user-images.githubusercontent.com/6836805/170132923-bf59dde3-22a1-44b3-bdfe-5522376b1ae1.png)

**Comment by renato-mmex** [comment]
Best thanks, so slowly I see clearly, will practice tomorrow something

**Comment by vomikan** [comment]
@renato-mmex Dear renato, unfortunatly I forget one important think.
First you need to fork the repository.
![image](https://user-images.githubusercontent.com/6836805/170261329-4f2af619-a24c-4382-920b-89a4b9976367.png)

Then clone the https://github.com/renato-mmex/moneymanagerex

**Comment by vomikan** [comment]
After any changes are made, you need to make a summit and send it to the remote repository.

![image](https://user-images.githubusercontent.com/6836805/170262161-a30aa601-d02d-42a0-be77-82e8d5ad7588.png)

After that, you can send these changes to the central repository.
![image](https://user-images.githubusercontent.com/6836805/170261849-7ff5be35-9d6b-49fb-9fc7-41a691ee23e3.png)

**Comment by renato-mmex** [comment]
@vomikan thanks for the tips
my repository is from 26.Dec 2021 can i update this with this pull request ?

<img width="923" alt="image" src="https://user-images.githubusercontent.com/76920138/170348849-36b3d144-bdf5-4692-bbc5-155a501712d6.png">

**Comment by vomikan** [comment]
The easiest way is to use the command line. First go to the repository directory.

```
git remote add upstream https://github.com/moneymanagerex/moneymanagerex.git
git fetch upstream
git checkout master
git rebase upstream/master
```


https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github/7244456#7244456
