### ISSUE TITLE
Allow opening transaction details from a custom report view

### ISSUE THREAD

**Issue by feimosi** [moneymanagerex/moneymanagerex#4465]
# Description of the feature

It'd be really useful to be able to link transactions the same way they are linked in the filter view i.e. clicking on the ID opens the transaction details modal. 

Preview:

_Clicking on the ID:_
![Screenshot from 2022-05-25 22-58-50](https://user-images.githubusercontent.com/5721520/170366260-e9db7f12-4314-47a8-b50d-2c8732644f54.png)
_Opens transaction:_
![Screenshot from 2022-05-25 22-58-19](https://user-images.githubusercontent.com/5721520/170366268-67a5273d-7dd8-46de-ab4c-51916b0641b0.png)

# Use cases

To be able to edit transactions while browsing reports (e.g. correcting errors)

**Comment by vomikan** [comment]
You could import the following report for example:
res\reports\Transaction-BlankNotes.grm

https://github.com/moneymanagerex/general-reports/tree/master/packages/Transaction/BlankNotes

**Comment by whalley** [comment]
Think the issue is that the `mmGeneralReportManager::OnNewWindow `handler does not handle the `trx`, just calls to URLs/Files.

```
void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
{
    const wxString uri = evt.GetURL();

    wxRegEx pattern(R"(^(https?:)|(file:)\/\/)");
    if (pattern.Matches(uri))
    {
        wxLaunchDefaultBrowser(uri);
    }

    evt.Skip();
}
```

**Comment by vomikan** [comment]
> You could import the following report for example:
> res\reports\Transaction-BlankNotes.grm

There is an error in this report. It is necessary to add ```target="_blank"```
In this case, when calling the report from the navigation tree, everything works.
It doesn't work from the General Report Manager. Not sure if it's needed there.

![image](https://user-images.githubusercontent.com/6836805/170438863-a42d1866-1bd2-4317-b0b7-14f207106a5a.png)

**Comment by whalley** [comment]
> In this case, when calling the report from the navigation tree, everything works.

So it does! Good spot.

**Comment by feimosi** [comment]
That's perfect, I didn't know of `target="_blank"`. Thanks!
