### ISSUE TITLE
Default custom field value

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4472]
If the default value is set, the transaction dialog interprets it incorrectly.

![image](https://user-images.githubusercontent.com/6836805/170520368-cf5ec81c-e459-4e5c-9a06-401597ff46a8.png)

![image](https://user-images.githubusercontent.com/6836805/170520484-9ec3821a-46af-4fdf-babb-8b9e524423e2.png)

**Comment by whalley** [comment]
What is the 'Default' value against a custom field intended to mean? 
Is the intention just to populate the field with the value but leave the checkbox unchecked?

**Comment by vomikan** [comment]
> Is the intention just to populate the field with the value but leave the checkbox unchecked?

I think yes.
