### ISSUE TITLE
Add ability the Delete/Rename Transaction Filter settings directly from navigation menu

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4478]
# Description of the feature

In addition to the Edit/Delete capabilities against the Transaction Filter, it would be good to also support a Rename.
<img width="274" alt="CleanShot 2022-05-27 at 15 17 19@2x" src="https://user-images.githubusercontent.com/487345/170717822-bfa6e1cb-4118-46a2-84db-fcc7bbe06ca8.png">

**Comment by whalley** [comment]
@vomikan I have the code for this but will hold to 1.5.16 as I see you are preparing the 1.5.15 release and this also requires some new translations for the error dialog.

**Comment by vomikan** [comment]
Commit it, please.

**Comment by gabriele-v** [comment]
What about a simply right click with edit only that shows the filtertransdialog on that report? It would also help keeping clean mmframe which should be mainly a presentation and not functionality class

**Comment by vomikan** [comment]
> What about a simply right click with edit only that shows the filtertransdialog on that report? It would also help keeping clean mmframe which should be mainly a presentation and not functionality class

In other words, move the rename function to a Transaction Filter dialog?

**Comment by gabriele-v** [comment]
Yep, then once is open you can rename or delete or edit as you wish

**Comment by whalley** [comment]
Personally, I'd prefer to have the Transaction Filter dialog dealing with the editing of a single filter and the management of creating, deleting, and renaming directly from the navigation menu. I.e. add a 'New Filter' option to the navigation menu.  We do similar with accounts....

It seems inconsistent with how we manage accounts, transactions, and recurring transactions that when you invoke the Edit dialog it gives options to create new or delete items.

**Comment by whalley** [comment]
> Can you detect a double click in the Navigation tree?

Yes you can
https://docs.wxwidgets.org/3.1/classwx_tree_ctrl.html

```
wxTR_EDIT_LABELS:
Use this style if you wish the user to be able to edit labels in the tree control.

EVT_TREE_BEGIN_LABEL_EDIT(id, func):
Begin editing a label. This can be prevented by calling Veto(). Processes a wxEVT_TREE_BEGIN_LABEL_EDIT event type.

EVT_TREE_END_LABEL_EDIT(id, func):
Finish editing a label. This can be prevented by calling Veto(). Processes a wxEVT_TREE_END_LABEL_EDIT event type.

EVT_TREE_ITEM_ACTIVATED(id, func):
The item has been activated, i.e. chosen by double clicking it with mouse or from keyboard. Processes a wxEVT_TREE_ITEM_ACTIVATED event type.
```

**Comment by vomikan** [comment]
> EVT_TREE_ITEM_ACTIVATED(id, func):
> The item has been activated, i.e. chosen by double clicking

I think it's worth adding such a fix. This allows you to call reports (and so on) again through a double click.
![image](https://user-images.githubusercontent.com/6836805/170837445-79b49eb3-cfb2-42c1-8715-2ca50a94532b.png)

**Comment by tactilis** [comment]
>  This allows you to call reports (and so on) again through a double click.

That would be great to have

**Comment by vomikan** [comment]
As part of the 1.5.15 release, I consider the task completed.



> keeping clean mmframe which should be mainly a presentation and not functionality class

That's a good point. We need to keep it in mind.
