### ISSUE TITLE
Advance filter settings for account

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4480]
We save only the fact that a cool filter is applied, but not its settings.
You either need to save these settings,
Or do not save at all, because in the filter itself you can create a lot of settings.

![image](https://user-images.githubusercontent.com/6836805/170734005-0cfbff8b-92e0-40e0-bcdf-2c0004aa71bc.png)

#4250
#4216

**Comment by vomikan** [comment]
@whalley This is quite a creative case. It is necessary to somehow force the filter to save JSON for the account. At the same time, it is not a fact that you need to save these settings to a shared named pool. What do you think about?

**Comment by vomikan** [comment]
I see such an implementation. Save separately. Label is the name of the invoice. Block drop-down menu.

**Comment by whalley** [comment]
Now that we have the extra filter functionality, my view is that we maintain a common pool of filters, and just allow the user to select one of these filters from the account view. We just save the chosen filter name.

If the user wants to edit or define a specific filter for the account then they do this from the shared pool.

**Comment by vomikan** [comment]
I checked the functionality when there is only one setting for the account. It turns out that if you click Cancel, the settings are erased. Not very convenient. Perhaps the only thing that needs to be changed is to remove the Advanced Filter saving for each account.

![image](https://user-images.githubusercontent.com/6836805/170782226-9b92f105-297c-4dd2-9c89-f9dd80d5020b.png)
PS Such a rework is not trivial. It's easy to make a mistake.

**Comment by vomikan** [comment]
There are two problems:
1) If a filter settings created in the account view panel it does not appears in the navigation panel;
2) If the account view changed from account A to B then accoutntID for Advanced filter did not changed.

**Comment by whalley** [comment]
@vomikan This change https://github.com/moneymanagerex/moneymanagerex/commit/59c0e83cb77b88fa6f534b6632eef765d10beab3#diff-01c8b567bd20902401c64c4b4c612c19efa15bbbc3c441f38835e86ba522de98 moving the 
```
    if (!selected.empty())
        m_settings_json = selected;
```

before the 
```
  DoInitVariables();
   Create(parent);
```
breaks the ability to jump directly from the nav tree to the settings for a specific filter. Not sure why this was done, was something broken?

**Comment by vomikan** [comment]
@whalley could you, please,  fix it, I have a lot of changes in the code. We'll have to wait a long time.

**Comment by vomikan** [comment]
I have made it so that the Advanced Filter settings are stored separately for the accounts.

So there is less confusion. Works well. I hope you enjoy it.

**Comment by vomikan** [comment]
There are problems:

1) If a filter settings created in the All Accounts view panel it does not appears in the navigation panel. Refresh needed.

**Comment by whalley** [comment]
If we going to make this save the advanced setting for the particular account view then should we not just remove the fields below rather that disabling them. It is clearer and less confusing for the the user. What do you think?
![CleanShot 2022-05-29 at 13 16 44](https://user-images.githubusercontent.com/487345/170867736-4019c448-8179-459f-9ef0-ec9ed221c6d1.png)

**Comment by whalley** [comment]
> 1. If a filter settings created in the All Accounts view panel it does not appears in the navigation panel untill refresh.

Might be missing something here, but why does the 'All Accounts' advanced filter view have the ability to save filter settings but the single account views do not. Should we not be consistent?

**Comment by vomikan** [comment]
> If we going to make this save the advanced setting for the particular account view then should we not just remove the fields below rather that disabling them. It is clearer and less confusing for the the user. What do you think?

Yes, I agree with that. But when I did Hide() for all these elements, artifacts appeared. Enable() works more reliably.

>Might be missing something here, but why does the 'All Accounts' advanced filter view have the ability to save filter settings but the single account views do not. Should we not be consistent?

I suggest storing the filter settings of each account in the ACCOUNT_V1 table in the future #4216, i.e. separately from reports. It's easier to maintain the code this way. This has already been partially implemented.
But for all accounts, it is useful to name a set of settings for different cases.
A simple solution is to store a set of settings for all accounts separately. For example, in ALL_ACCOUNTS_FILTER.

**Comment by whalley** [comment]
> Thus, we get:
> 
> 1. A set of settings that are presented as reports in the navigation tree.
> 2. A set of settings for filtering the All Account view.
> 3. Each account has a simplified dialog and saves the filter settings to itself.
>    I think this is quite logical.

For (2) when you say 'A set of settings' are you proposing that there is a range of settings or a single set as for the single account. I think the single account and All accounts dialog should identical except for the Account being disabled in the single account case.

Hiding all the unused settings for (1) and (2) would be ideal.

**Comment by vomikan** [comment]
> 'A set of settings' are you proposing that there is a range of settings

This one.

> Hiding all the unused settings for (1) ~and (2) would be ideal~.

I suggest hiding only for the panel with single account view.

**Comment by whalley** [comment]
I'm not going to get too hung up over this but I don't see why we support a range of settings for the All Transactions view and not for the single account view? I think they should be consistent. What was your reasoning for this?

**Comment by vomikan** [comment]
I have already given arguments. I probably don't convey thoughts well.
There is a purely technical problem when in the Account view are changed settings or a new setting is created... Refresh of navigation panel needed. 
Or when the setting is created for the account and it is visible as a report and you can change accounts there (add or delete), then it breaks for the account.

It can be done, but it is difficult... I suggest looking around for now with this implementation. A better idea may come with time.

**Comment by whalley** [comment]
Account dialog looks a lot cleaner, but not sure if this happens on Windows but there is a lot of unused spaces in the dialog on MacOS
![CleanShot 2022-05-29 at 19 37 56](https://user-images.githubusercontent.com/487345/170886398-eff5d1d2-0d5a-417b-baa2-f02ffc972957.png)

**Comment by whalley** [comment]
> There is a purely technical problem when in the Account view are changed settings or a new setting is created... Refresh of navigation panel needed.
> Or when the setting is created for the account and it is visible as a report and you can change accounts there (add or delete), then it breaks for the account.

But wouldn't this problem go away if we made the 'All transactions' dialog the same as the single account dialog and did not allow the saving and management of multiple settings? Keeping the 'Transaction Report' setting independent.

**Comment by vomikan** [comment]
There are many accounts in the All Transactions window, not one. Therefore, it will not work to make the dialog similar.

**Comment by whalley** [comment]
> There are many accounts in the All Transactions window, not one. Therefore, it will not work to make the dialog similar.

But just opening up the account as an extra selectable filter item would seem adequate enough.... Anyway, I don't really use the account view filters anyway so will not comment further :-)

**Comment by whalley** [comment]
All Transactions, Advanced Filter...

![CleanShot 2022-05-29 at 20 39 59](https://user-images.githubusercontent.com/487345/170888605-7785a859-3dbc-4e3e-a9d6-7c5f04420df4.png)

**Comment by vomikan** [comment]
> All Transactions, Advanced Filter...

I had this bug, but it disappeared.

**Comment by vomikan** [comment]
Did it get better after these changes?

**Comment by whalley** [comment]
> Did it get better after these changes?

Nope, still there.

**Comment by vomikan** [comment]
Now?

**Comment by whalley** [comment]
> Now?

Nope. The issue seems to be related to the below as the artifacts are hidden if some JSON is saved. If the JSON is empty the disable/hide is not called. I've moved the code to the CreateControls method (probably the best place anyway), so it will always be called.
```
void mmFilterTransactionsDialog::dataToControls(const wxString& json)
{
    if (json.empty()) return;
```
