### ISSUE TITLE
DB ver.17?

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4481]
#4216

| ACCOUNTLIST_V1 |  type |
|---|---|
|  imageID | INTEGER |
|  filter | TEXT |
| sequence | INTEGER |

| CHECKINGACCOUNT_V1 | type |
|---|---|
| ~~time  (https://github.com/moneymanagerex/moneymanagerex/issues/2729)~~ | ~~varchar(5)~~ |
| color | INTEGER | 
| ~~changedtime~~ | ~~TEXT~~ |
| ~~deletedtime (https://github.com/moneymanagerex/moneymanagerex/issues/2963)~~ | ~~TEXT~~ |

| BILLSDEPOSITS_V1| type |
|---|---|
| ~~time~~ | ~~TEXT~~ |
|  color | INTEGER |

| CURRENCYFORMATS_V1 | type | notes |
|---|---|---|
| precision | int | = log10(scale) |
| ~~scale~~ | | |

|SPLITTRANSACTIONS_V1 | type |
|---|---|
| type| varchar |

| CUSTOMFIELDDATA_V1 |  type | 
|---|---|
| REFTYPE  | TEXT   |

| CUSTOMFIELD_V1 |  type | 
|---|---|
| ~REFTYPE~  | ~varchar~  |

**Comment by whalley** [comment]
Consider table renames and referential integrity https://github.com/moneymanagerex/moneymanagerex/issues/4216#issuecomment-1262459149

**Comment by vomikan** [comment]
We need to add a table for the tag(s).

**Comment by n-stein** [comment]
Can we add PARENTID in CATEGORY_V1 for #1477 to this list?
