### ISSUE TITLE
Expanding a collapsed Navigation tree not intuitive for new users

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4483]
MMEX version:
 - [x] 1.5.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I believe, for the first time ever, I accidentally collapsed the Navigation tree, leaving just the Home Page node displayed:
 
 
![image](https://user-images.githubusercontent.com/4060092/170814065-4530066e-31d6-4366-9fc4-6860b6c12a02.png)
 
I must have inadvertently pressed the left-arrow key while Home Page was highlighted.

So, how do you expand the tree again?

I know that the answer is: "press right-arrow", but this will not be obvious to all users, especially new users of MMEX.

In Windows Explorer, you can expand the folder tree by clicking the expand/collapse triangle next to Desktop, or by double clicking on Desktop - but this does not work in MMEX. 
 
![image](https://user-images.githubusercontent.com/4060092/170815413-856ce96f-407c-4995-bf5b-d606ef4c7e4d.png)
 
If it's possible, I propose that we allow double-click on Home Page to expand the tree.

For aesthetic reasons, I am **not** proposing that we add an expand/collapse +/- icon next to Home Page.

Thoughts please?

Can the the Navigation tree respond to double-click?  This reply from @whalley suggests that it can [https://github.com/moneymanagerex/moneymanagerex/issues/4478#issuecomment-1139964458](https://github.com/moneymanagerex/moneymanagerex/issues/4478#issuecomment-1139964458)

**Comment by whalley** [comment]
I say we look to remove the ability to collapse it from HOME,can't see any benefit it brings.

**Comment by vomikan** [comment]
I can't reproduce it.

**Comment by tactilis** [comment]
> I can't reproduce it.

What exactly can't you reproduce @vomikan ?

**Comment by tactilis** [comment]
> I say we look to remove the ability to collapse it from HOME,can't see any benefit it brings.

Agreed. That's would be an acceptable solution

**Comment by vomikan** [comment]
> What exactly can't you reproduce @vomikan ?

I can't collaps the navigation tree to this view:
![image](https://user-images.githubusercontent.com/6836805/170822675-95f4d104-a6f9-4a41-9e3d-ed61a6cebd36.png)

**Comment by tactilis** [comment]
> I can't collaps the navigation tree to this view

1. Left-click on Home Page (or navigate to it using the up-arrow key).
2. Press the left-arrow key

That should collapse it. If it doesn't, then there is something different between our installations.

**Comment by vomikan** [comment]
I think it's easy to ban it. We need to add an event handler. If the root element is in focus, then prohibit it.

EVT_TREE_ITEM_COLLAPSING

**Comment by tactilis** [comment]
In the initial post of for issue ^^ I wrote:

> For aesthetic reasons, I am **not** proposing that we add an expand/collapse +/- icon next to Home Page.

As you can see, on Windows, there is no expand/collapse icon next to Home Page.

However, I've just noticed in the video @PMaff provided here https://github.com/moneymanagerex/moneymanagerex/issues/4470#issuecomment-1140291561, that on Linux, there is an expand/collapse icon next to Home Page.
 
![image](https://user-images.githubusercontent.com/4060092/170838422-9b8a5594-5e5e-4ea3-938c-73f52ad98fa2.png)
 
Since we are now vetoing the collapse event for Home Page, I'm wondering whether there is a way of suppressing the display of the expand/collapse icon for that item?

Does the Mac version have the icon too?

**Comment by whalley** [comment]
Yes Mac version has this also.
![CleanShot 2022-05-29 at 11 48 31](https://user-images.githubusercontent.com/487345/170864195-77787e7b-4d1d-4014-a890-471253ea1124.png)

**Comment by whalley** [comment]
Can't see an obvious way to hide the toggle on the HOME item.

**Comment by tactilis** [comment]
If there isn't a way to suppress the expand/collapse icon for the Home Page item on Linux & Mac, then it doesn't make much sense to veto the collapse event there.

In which case, we definitely should provide the ability to double click Home Page as a means of re-expanding the tree after an accidental collapse (see initial post of this issue)

**Comment by tactilis** [comment]
For aesthetic reasons (and for consistency with MMEX on Mac & Linux, and with Windows Explorer), this might be good to enable

> wxTR_TWIST_BUTTONS:
>
> Selects alternative style of +/- buttons and shows rotating ("twisting") arrows instead. Currently this style is only implemented under Microsoft Windows Vista and later Windows versions and is ignored under the other platforms. Notice that under Vista this style results in the same appearance as used by the tree control in Explorer and other built-in programs and so using it may be preferable to the default style. 

[https://docs.wxwidgets.org/3.0/classwx_tree_ctrl.html](https://docs.wxwidgets.org/3.0/classwx_tree_ctrl.html)

**Comment by vomikan** [comment]
> we definitely should provide the ability to double click Home Page

I do not support this advice. 

A more logical solution has been applied. A double click repeats the action of the selected element.
https://github.com/moneymanagerex/moneymanagerex/commit/c1665ee2732ed5c16461159c78999ecda2d3734e

**Comment by vomikan** [comment]
wxTR_TWIST_BUTTONS does not add a button to the root element.

![image](https://user-images.githubusercontent.com/6836805/170866054-dc25e507-141c-49c7-aa10-88c6c2500fd9.png)

**Comment by vomikan** [comment]
wxTR_NO_LINES:

![image](https://user-images.githubusercontent.com/6836805/170866194-7d73b2b8-848d-4028-a48c-abecc57a60d9.png)

**Comment by vomikan** [comment]
I think you can make a ban on collapsштп only for Windows. However, for other systems, I don't see the point in collapsing all the elements.

```#if defined (__WXMSW__)```

**Comment by tactilis** [comment]
With wxTR_NO_LINES looks cleaner and more modern.

It is then consistent with Windows Explorer and with MMEX on Mac & Linux

**Comment by PMaff** [comment]
Despite the logic of collapsing all:
If the collapse triangle is there in Linux and MacOS, why is it missing in Windows?
This should be consistent.

**Comment by whalley** [comment]
> I don't see the point in collapsing all the elements.

Agreed. What we have implemented seems fine.

**Comment by PMaff** [comment]
> https://docs.wxwidgets.org/3.0/classwx_tree_ctrl.html

Does a (existing?) wxWidget 3.1.5 sample for this for Windows also miss this collapse triangle?

**Comment by PMaff** [comment]
wxWidget 3.1.5 sample samples/treectrl/treectrl on Linux (Ubuntu 18.04):
![trectrlsample](https://user-images.githubusercontent.com/93879362/170870895-dcf249b6-42d7-4224-889b-f63a9a9bf5db.jpg)

**Comment by PMaff** [comment]
tree list sample:

![treelistsample](https://user-images.githubusercontent.com/93879362/170871026-e3fd21e0-3cea-43c0-8e57-ced30fd056be.jpg)

So this triangle is always there on Linux.

**Comment by vomikan** [comment]
> This should be consistent.

wxWidgets uses OS elements. Therefore, there is no guarantee that everything will be the same.

**Comment by PMaff** [comment]
> > This should be consistent.
> 
> wxWidgets uses OS elements. Therefore, there is no guarantee that everything will be the same.

Yeah, I see that Windows is different to Linux and MacOS once more. :-(

![wxWidgetAppearance](https://user-images.githubusercontent.com/93879362/170871514-ef09a83a-df55-4f9b-8f37-0fbd48a883cb.jpg)
( source : https://docs.wxwidgets.org/3.0/classwx_tree_ctrl.html )
Having the '+' there for Windows might be also ok.

**Comment by vomikan** [comment]
@PMaff 

![image](https://user-images.githubusercontent.com/6836805/170872139-418f0094-1805-4d20-916a-2a96f6d41278.png)

![image](https://user-images.githubusercontent.com/6836805/170872289-d6228c01-8402-4cb5-8ea4-335dda56767d.png)

If you remove all styles, it will turn out the same on all OS. But I don't like the way it looks. A completely superfluous element.

Moreover, I think it can be removed for Linux and MAC.

**Comment by PMaff** [comment]
> Moreover, I think it can be removed for Linux and MAC.

Since there is no sense in collapsing "Home Page" and since there is no 2nd element parallel to "Home Page",
removing the collapsing for Windows, MacOS and Linux is OK for me.
To tidy up the view one can collapse the subitems like "Favourites" in the above example.

Btw. one suggestion: can you make some kind of test db, which adresses various important features,
post this somewhere for the testers?
So that we all start with the same starting point to test?

**Comment by vomikan** [comment]
> Btw. one suggestion: can you make some kind of test db

https://github.com/moneymanagerex/moneymanagerex/issues/672

**Comment by vomikan** [comment]
@whally, could you try this patch:

![image](https://user-images.githubusercontent.com/6836805/170873602-601de615-9085-43c3-b1b0-e8917d621bb7.png)

**Comment by PMaff** [comment]
```
void mmGUIFrame::createControls()
{
#if defined (__WXMSW__)
    m_nav_tree_ctrl = new wxTreeCtrl(this, ID_NAVTREECTRL, wxDefaultPosition, wxDefaultSize,
        wxTR_SINGLE | wxTR_HAS_BUTTONS | wxTR_ROW_LINES | wxTR_TWIST_BUTTONS);
#else
    // Under GTK, row lines look ugly
    m_nav_tree_ctrl = new wxTreeCtrl(this, ID_NAVTREECTRL,wxDefaultPosition, wxDefaultSize,
        wxTR_SINGLE | wxTR_HAS_BUTTONS | wxTR_NO_LINES  | wxTR_TWIST_BUTTONS | wxTR_HIDE_ROOT);
#endif
```
then I get:

![nohomebutton](https://user-images.githubusercontent.com/93879362/170876254-980f8522-6b14-401a-8d4f-441dc8ded6b5.jpg)

but before that there are various assert messages about an exanding "Home Page" that is not there (of course):

![assertionnohomepage](https://user-images.githubusercontent.com/93879362/170876378-8dc65691-838e-4807-b42a-15d1a10338ca.jpg)

with:
```
ASSERT INFO:
../src/generic/treectlg.cpp(1862): assert ""!HasFlag(0x0800) || itemId != GetRootItem()"" failed in Expand(): can't expand hidden root

BACKTRACE:
[1] wxGenericTreeCtrl::Expand(wxTreeItemId const&)
[2] mmGUIFrame::loadNavigationTreeItemsStatusFromJson()
[3] mmGUIFrame::DoRecreateNavTreeControl()
[4] mmGUIFrame::SetDatabaseFile(wxString const&, bool)
[5] mmGUIFrame::showBeginAppDialog(bool)
[6] mmGUIFrame::mmGUIFrame(mmGUIApp*, wxString const&, wxPoint const&, wxSize const&)
[7] OnInitImpl(mmGUIApp*)
[8] mmGUIApp::OnInit()
[9] wxEntry(int&, wchar_t**)
[10] main
[11] __libc_start_main
[12] _start
```
I did not search where this wxGenericTreeCtrl::Expand() is.

**Comment by vomikan** [comment]
No  wxTR_HIDE_ROOT please.

**Comment by whalley** [comment]
![CleanShot 2022-05-29 at 16 30 43](https://user-images.githubusercontent.com/487345/170877631-1d25f2e6-3f7e-4eb5-a8c2-5bf027b0fc8e.png)

Looks better the way it was.

Can't believe we are expending energy on something 99% of people will not even notice or care about.

**Comment by PMaff** [comment]
> No wxTR_HIDE_ROOT please.

Ok, then consider my above posting as invalid.

I tried
```
void mmGUIFrame::createControls()
{
#if defined (__WXMSW__)
    m_nav_tree_ctrl = new wxTreeCtrl(this, ID_NAVTREECTRL, wxDefaultPosition, wxDefaultSize,
        wxTR_SINGLE | wxTR_HAS_BUTTONS | wxTR_ROW_LINES | wxTR_TWIST_BUTTONS);
#else
    // Under GTK, row lines look ugly
    m_nav_tree_ctrl = new wxTreeCtrl(this, ID_NAVTREECTRL,wxDefaultPosition, wxDefaultSize,
        wxTR_SINGLE | wxTR_HAS_BUTTONS | wxTR_NO_LINES | wxTR_TWIST_BUTTONS);
#endif
```
to avoid the lines as @tactilis wrote, which results in:

![withhomebutton](https://user-images.githubusercontent.com/93879362/170877822-4c6ebe10-3f82-4475-908b-e2d8394eaacd.jpg)

And yes: it is a very very marginal topic. ;-)

**Comment by tactilis** [comment]
@whalley
> Can't believe we are expending energy on something 99% of people will not even notice or care about.

I care about the original issue; i.e. that if a new user accidentally collapses Home Page (on Windows) it is not obvious how to re-expand it.

Since we have overcome that problem, then I'm happy.


And I'm twice as happy if (on Windows) the [+]/[-] icons are changed using wxTR_TWIST_BUTTONS to be consistent with the expand/collapse icon used in the OS.

And I'm triple happy if the rather old-fashioned connecting lines (on Windows) are gone.

**Comment by whalley** [comment]
> > Can't believe we are expending energy on something 99% of people will not even notice or care about.
> 
> I care about the original issue; i.e. that if a new user accidentally collapses Home Page (on Windows) it is not obvious how to re-expand it.

Agreed, that change was needed...

**Comment by whalley** [comment]
Sorry, but I'm now getting those connecting lines on Mac.   We should add wxTR_NO_LINES, Or was this change intentional? If so, I personally don't like it.

![CleanShot 2022-05-29 at 18 47 51](https://user-images.githubusercontent.com/487345/170884329-019c78c1-f872-4d0b-b921-580692b71f6c.png)

**Comment by vomikan** [comment]
Personally, I like these lines. But since they are not represented, for example, in the navigator, then in general I am for unification.

![image](https://user-images.githubusercontent.com/6836805/170884630-35d7960e-01d8-430b-a00d-0e72ae69a7b9.png)


![image](https://user-images.githubusercontent.com/6836805/170884576-141c1542-ffe2-4403-a563-d2ecea44d878.png)

**Comment by tactilis** [comment]
The Navigation tree looks much cleaner now. Thank you.

The only 'extra' thing that has happened is the addition of part of the highlight border to the left of the icon:
 
![image](https://user-images.githubusercontent.com/4060092/170886767-dc36946c-8e43-4083-afa3-c4cb7cecb3d6.png)
 
The first is from 1.5.14 (i.e. before any changes)

The next 2 are after the initial TWIST changes (but still with the lines). Note the changed blue border.

The last is from the NO LINES build

**Comment by vomikan** [comment]
It looks like this because the background of the picture is white, not transparent. IMO this is not a big problem.

**Comment by tactilis** [comment]
> IMO this is not a big problem.

Agreed.

Thanks to everyone for all the work on this apparently 'minor' change. It's a good improvement to the UI.

**Comment by whalley** [comment]
> The only 'extra' thing that has happened is the addition of part of the highlight border to the left of the icon:

Possibly related? https://github.com/wxWidgets/wxWidgets/issues/22349

**Comment by tactilis** [comment]
@whalley
> Possibly related? https://github.com/wxWidgets/wxWidgets/issues/22349

It looks possible.

Looking at the screenshots from https://github.com/moneymanagerex/moneymanagerex/issues/4483#issuecomment-1140504751

![image](https://user-images.githubusercontent.com/4060092/170945177-17e9f975-edc6-4293-ad90-b40b5c946373.png)

it seems that the left border appeared when wxTR_TWIST_BUTTONS was set (and is present whether there are connecting lines or not).

The presence of the border on the left suggests that the highlight is intended to flow _under_ the MMEX account icon, whereas it didn't do this before the changes were made (see the top screenshot, which is from 1.5.14).

It's interesting that setting wxTR_TWIST_BUTTONS has _apparently_ also changed the highlight colour. Is it possible that something else, in addition to wxTR_TWIST_BUTTONS, was set when this change was made, or was TWIST the only difference?
