### ISSUE TITLE
Error: "Show Money Tips" erases both screens on mmex 1.5.14

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#4494]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Occurs in stable 1.5.14 with wxWidget 3.1.5 .
Better behaviour in 1.5.15-Beta.3 with wxWidget 3.1.5 .

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux 

# Description of the bug

When selecting "Show Money Tips", in 1.5.14 both screen parts are erased.
See 2nd part of attached film.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  open mmex
2.  select "Show Money Tips"
3.  both screen parts are erased

…

Expected result:
maybe only erase the right screen part?
Keep the menu on the left in all cases.

Actual result:
both screen parts are erased

# Additional information
see 2nd part of attached film

https://user-images.githubusercontent.com/93879362/170878389-28241610-5ac0-4d70-8c96-43b3dc6d7b2c.mp4

If you have a backtrace for a crash or a warning, paste it here.

**Comment by PMaff** [comment]
Version: 1.5.15-Beta.3 64-bit
• Build on May 28 2022 18:45:40
• Database version: 7 • (aes128cbc)
• Git commit: https://github.com/moneymanagerex/moneymanagerex/commit/bef96ad50f863c17e20ae4ecd0fe40387b406692 (2022-05-28)
• Git branch: master

with wxWidgets 3.1.5 (wxGTK 3.24)

**Comment by vomikan** [comment]
We cannot change an already released release. We have to wait 1.5.15.

**Comment by PMaff** [comment]
> We cannot change an already released release. We have to wait 1.5.15. You can fix it for yourself personally in the source code.

Yes, that is clear, therfore I wrote:
https://github.com/moneymanagerex/moneymanagerex/issues/4470#issuecomment-1140463440
For the time being the handling of 1.5.15-Beta.3 is ok imho .
