### ISSUE TITLE
Apply button of the Advanced filter panel is hidden by start menu on MacBook Pro 13''

### ISSUE THREAD

**Issue by Eos1288** [moneymanagerex/moneymanagerex#4497]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug
When opening the Advanced filter panel it is not possible to click on the Apply button because it's hidden by the start menu. This panel is also not scalable. 

<img width="552" alt="Schermata 2022-05-29 alle 18 51 11" src="https://user-images.githubusercontent.com/106485729/170882134-b44e565f-45d4-4242-8666-bea961a1b5d8.png">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Just open Advanced filter panel on MacBook Pro 13''

Expected result:
The Apply button is clickable.

Actual result:
The Apply button is hidden.

**Comment by vomikan** [comment]
#4419 As part of this case, the height of the dialog has decreased. A new version is coming out soon.

![](https://user-images.githubusercontent.com/487345/169921961-7079b10c-9b2f-403c-8e83-412b2447e430.png)
