### ISSUE TITLE
Error tooltip

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4517]
Which is better?

![image](https://user-images.githubusercontent.com/6836805/171391060-bd1e2207-94d1-4f14-b492-462f00bc1799.png)

![image](https://user-images.githubusercontent.com/6836805/171391282-5ac080b0-7ace-4ff6-bd54-526ac4f9d1c9.png)

**Comment by tactilis** [comment]
What are the reasons for it being an error?

If it's only that Category can't be blank, then we should say that.


For example:

Category must be specified.

Category can't be blank.

**Comment by renato-mmex** [comment]
please choose a category

**Comment by Dandy64** [comment]
Well, as for me I would prefer the 1st one.

Actually, as a user I need to know 3 things:
1. What kind of problem is it? 
Error, warning, information, etc. 
2. Where this problem has happened? 
In the example above - Category.
3. What should be done to fix it? 
Actually, it can be clear from the 1st (Invalid value can be 0, or wrong date format)

In an ideal case it should be more informative like:

**Invalid value**
Category can not be empty.

**Invalid value**
The correct date format is dd/mm/YYYY

**Comment by PMaff** [comment]
How is this done in MacOS, Windows? (I do not have both at hand)
Linux: tried to find an application that has similar error tooltips, but had no luck by a quick search.
Make it consistent to the way of displaying on these OSes (if possible)
