### ISSUE TITLE
Allow column sorting on Summary of Accounts & Income vs Expenses reports

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#4542]
Hi all!

Couldn't it be possible to sort by date in summary of accounts -> Monatly and Yearly views? Now the current month and year are at the bottom and you always have to scroll down there.
Just click on the column name and the program will display the table accordingly.

**Comment by whalley** [comment]
Can add sorting by any column to the annual report without any presentation issues.

For the monthly report, I would need to change the presentation to below, as the grouping based on year is not practical if the table can be sorted by multiple columns.

Seems fine to me. Views?

![CleanShot 2022-06-05 at 18 36 52](https://user-images.githubusercontent.com/487345/172063133-5a92a0a0-c173-42a8-a688-24ee013f72fb.png)

**Comment by whalley** [comment]
The same unsortable issue occurs with the @Income vs Expenses / Monthly report". Propose updating that also to support sorting.
