### ISSUE TITLE
Categories are not translated into Russian

### ISSUE THREAD

**Issue by Korb** [moneymanagerex/moneymanagerex#4543]
MMEX version:
Версия 1.5.14 64-bit
Собрано Апр 14 2022 15:04:46
Версия базы данных: 7 • (aes128cbc)
Git commit: 29d21c3 (2022-04-14)

Operating System:
Microsoft Windows 10.0.19044.1741

# Description of the bug

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. After launching the application and loading the database, select the Russian language
2. Select "Инструменты" / "Категории" in the menu.

Expected result:

- Автомобиль
- Счета
- Образование
- Еда
- Подарки
- Здравоохранение
- Домашние нужды
- Доход
- Страхование
- Досуг
- Прочие расходы
- Прочие доходы
- Налоги
- Переводы
- Отпуск

Actual result:

A list of categories is displayed:

- Automobile
- Bills
- Education
- Food
- Gifts
- Healthcare
- Homeneeds
- Income
- Insurance
- Leisure
- Miscellaneous
- Other Expenses
- Other Income
- Taxes
- Transfer
- Vacation

![2022-06-05 14 02 09](https://user-images.githubusercontent.com/3509797/172047466-48ab81f7-fc67-4058-9602-752994a59e62.png)

**Comment by Dandy64** [comment]
**You are right**, althgough I do not think it is a big deal. 
Actually, almost everyone creates his own categories even if some of them are quite obvious like Car or Bills.
I prefer to use the program in English interface, but if I switch it to another language I would create my own categories and I do not care if it was translated to my mother tongue or not.

**Comment by vomikan** [comment]
При создании базы данных, создаются категории для выбранного языка.
https://github.com/moneymanagerex/moneymanagerex/issues/4418
В вашем случае, придётся переводить вручную.
