### ISSUE TITLE
Dark mode for help pages

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4545]
We need to redefine the style.
![image](https://user-images.githubusercontent.com/6836805/172049805-ab0793c9-d6dc-46bb-8b56-cabf64930ccf.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3620
https://github.com/moneymanagerex/moneymanagerex/issues/2713
https://github.com/moneymanagerex/moneymanagerex/issues/1779
https://github.com/moneymanagerex/moneymanagerex/issues/2068

**Comment by whalley** [comment]
@vomikan Is https://github.com/vomikan/moneymanagerex/commit/ecb5eca1c1861f1cbfc93658de54b6286171e734 detecting if Dark/Light mode is in operation on Windows?

If so, could we update this?https://github.com/moneymanagerex/moneymanagerex/blob/152546b000c267612bdf1df45575899bdfb9a64b/src/platfdep_win.cpp#L76

**Comment by vomikan** [comment]
> Is [vomikan@ecb5eca](https://github.com/vomikan/moneymanagerex/commit/ecb5eca1c1861f1cbfc93658de54b6286171e734) detecting if Dark/Light mode is in operation on Windows?

Yes, this algorithm reads the corresponding entry from the registry. This record may be missing. I just added it for a test. Can be used.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4560

**Comment by whalley** [comment]
> > Is [vomikan@ecb5eca](https://github.com/vomikan/moneymanagerex/commit/ecb5eca1c1861f1cbfc93658de54b6286171e734) detecting if Dark/Light mode is in operation on Windows?
> 
> Yes, this algorithm reads the corresponding record from the Windows registry. This record may be missing. I just added it for a test. Can be used. It's working.

OK, as this is Windows-specific logic it is probably best if you move this code to the mmex::isDarkMode method and test that the AUTO theme mode works with the default theme and selects LIGHT or DARK mode depending upon Windows setting. 
![CleanShot 2022-06-06 at 20 38 57](https://user-images.githubusercontent.com/487345/172235142-adc83e9e-8774-4072-a361-595dd017d200.png)

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4362

**Comment by whalley** [comment]
```
@media (prefers-color-scheme: dark) {
    body {  
        background: #333;
        color: white;
    }
    a { text-decoration: none; 
        color: yellow; }
}

@media (prefers-color-scheme: light) {
    body {
        background: white;
        color: #555;
    }
    a { text-decoration: none; 
        color: blue; }
}
```

Light Mode:
![CleanShot 2022-09-23 at 01 05 01](https://user-images.githubusercontent.com/487345/191871487-7cc34874-4170-4766-a8b3-4d16b911079c.png)

Dark Mode:
![CleanShot 2022-09-23 at 01 05 47](https://user-images.githubusercontent.com/487345/191871519-ef2b9239-59a4-403a-b4c5-fe98fae494ae.png)

**Comment by whalley** [comment]
Can somebody please test on Windows and Linux systems...

I suspect we need to enable the wxWEBVIEW_BACKEND_EDGE in windows (if not already the default) https://docs.wxwidgets.org/3.2/classwx_web_view.html

**Comment by whalley** [comment]
Works fine on Linux (tested on Ubuntu 20.04)

Linux (Ubuntu) Light Mode:
<img width="1419" alt="CleanShot 2022-09-23 at 09 01 02@2x" src="https://user-images.githubusercontent.com/487345/191916497-bfcc24cd-3cc0-41b6-a950-c2c545430515.png">

Linux (Ubuntu) Dark Mode:
<img width="1419" alt="CleanShot 2022-09-23 at 08 59 13@2x" src="https://user-images.githubusercontent.com/487345/191916351-1eaf525f-dbdb-4a29-8e8d-74d4c19f9592.png">

**Comment by vomikan** [comment]
Windows
![image](https://user-images.githubusercontent.com/6836805/191927395-a64fee02-04f9-455a-be07-df1f71de343f.png)

**Comment by whalley** [comment]
Thought as much. The existing IE backend does not support this. We need to upgrade to wxWEBVIEW_BACKEND_EDGE,

**Comment by whalley** [comment]
Just noted the following, which may add complexity.

https://docs.wxwidgets.org/3.2/classwx_web_view.html
wxWEBVIEW_BACKEND_EDGE (MSW)
The Edge backend uses Microsoft's [Edge WebView2](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2). It is available for Windows 7 and newer.

**This backend does not support custom schemes and virtual file systems.**.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5124 raised to cover the fact that Windows MMEX will not support dark mode help until the backend is changed.
