### ISSUE TITLE
Improving the UX of the "Organize Categories" window — keyboard shortcuts

### ISSUE THREAD

**Issue by Korb** [moneymanagerex/moneymanagerex#4547]
The interface of the "Organize Categories" window is heavily mouse oriented rather than keyboard oriented. In general, the functionality of the interface is sufficient, but the keyboard shortcuts that have become common in various applications do not work, and this is confusing.

`F2` — rename category (preferably right in the window, no popup);
`Ctrl+C` / `Ctrl+X` / `Ctrl+V` — copy, cut and paste the selected category to the specified location (root or first level category);
`F3` / `F4` — copy / paste the selected category to the specified location (root or first level category);
`Insert` / `Ctrl+N` — create a new category in the selected place ("Add" button);
`Delete` — delete selected category;
`Shift+Arrow Up` / `Shift+Arrow Down` / `Shift+Home` / `Shift+End` / `Shift+Page Up` / `Shift+Page Down` / `Shift+LMB` / `Ctrl+LMB` — select / deselect several categories;
`Ctrl+A` — select all categories.

**Comment by vomikan** [comment]
Only one item can be selected in the navigation tree. Therefore, most key combinations are not acceptable in this case.
Therefore, only the following combinations can be used:
```F2``` — rename category (preferably right in the window, no popup);
```Insert``` / ```Ctrl+N``` — create a new category in the selected place ("Add" button);
```Delete``` — delete selected category;
