### ISSUE TITLE
Add a tooltip to the "Статус по умолчанию" field

### ISSUE THREAD

**Issue by Korb** [moneymanagerex/moneymanagerex#4552]
In the "Настройки MMEX" window, on the "Прочее" tab, in the "Параметры диалога новых транзакций" section, there is a "Статус по умолчанию" field with a drop-down list containing the following values:

- Не выверено
- Выверено
- Не учитывать
- Отслеживать
- Повтор

![2022-06-05 18 22 19](https://user-images.githubusercontent.com/3509797/172057908-b6975233-d511-42b5-97f8-6c629b78ab6a.png)

This setting item is not mentioned in the offline Russian-language help for the application. I am not an accountant, and the purpose of this field is not clear to me. I propose to add a brief explanation of what exactly the values chosen in it mean?

**Comment by tactilis** [comment]
> and the purpose of this field is not clear to me.

The field sets the default value of the Status field when new transactions are created as shown below..

It's usual to leave this as Unreconciled and then change transaction(s) to Reconciled (press the R key) when you have created them.

![image](https://user-images.githubusercontent.com/4060092/172058925-25932db6-ed16-413a-8d49-fb81d3e164ee.png)

**Comment by Korb** [comment]
Thank you for trying to explain this concept to me.

> It's usual to leave this default as Unreconciled and then change transaction(s) to Reconciled (press the R key) when you have created them.

I haven't studied accounting, and I don't know any accountants who can clearly explain how a _transaction_ entity can be _Unreconciled_ or _Reconciled_. Reconciled by whom and for what?

**Comment by tactilis** [comment]
@Korb
> I haven't studied accounting, and I don't know any accountants who can clearly explain how a transaction entity can be Unreconciled or Reconciled. Reconciled by whom and for what?

It's not really an accounting issue. I'll try to explain for you.

If you look at section 6.1 of the Help you'll see:


> **Transaction Status:**
> 
> **Unreconciled**: When you enter a transaction, it initially is in the state of Unreconciled. Which means the transaction has not been reconciled with your bank/credit card company's balance.
> 
> **Reconciled**: Once the transaction is checked and verified with a credit card company's balance information, it can be marked as reconciled.


So, for example, if you are manually entering transactions into MMEX each day, as you spend or receive money, they will not yet be reconciled with your bank statement.

When you obtain the statement and go through the transactions, you can change the status to Reconciled.

A quick way to do this is to press a key:

U - Unreconciled
R - Reconciled

Here's an example showing the first transaction as Reconciled and the second as Unreconciled. Note the status column and the icon as the start of the row.

![image](https://user-images.githubusercontent.com/4060092/172067523-2dca6e8a-90be-4606-b377-a32455bf4f62.png)

The other states shown are:

>**Flag For Follow Up**: This status marks transactions as needing more action. For example, you receive a balance statement from the financial institution and you notice that the transaction amount is different between what you recorded and what is in the statement. You can mark it as flag for follow up so that you can followup with the financial institution. (Shortcut key F)
>
>**Duplicate**: The status will be automatically be changed to duplicate if it is recognized as such.  (Shortcut key D)
>
> **Void**: If you entered a transaction that later became invalid or you cancelled the transaction, instead of deleting the transaction you can also mark it as void so you have a record of the transaction.  (Shortcut key V)

Notes:
1. The shortcut keys may be different in different languages (I'm not sure about this)
2. I don't think MMEX automatically changes the transaction status to Duplicate

@vomikan / @whalley Could you confirm 1 and 2 please?

**Comment by vomikan** [comment]
The principle is this. I enter new transactions as they arrive manually. Then I check my bank statement. When the balances match, I mark the transaction as Reconciled. The same for inport,

**Comment by whalley** [comment]
> * The shortcut keys may be different in different languages (I'm not sure about this)

I don't believe this is the case.

> * I don't think MMEX automatically changes the transaction status to Duplicate

Correct, MMEX does not automatically detect duplicates. This is a state that is set by the user. In this instance, the application will continue to count the 'Duplicate' transactions as valid transactions.

**Comment by tactilis** [comment]
> MMEX does not automatically detect duplicates. This is a state that is set by the user. In this instance, the application will continue to count the 'Duplicate' transactions as valid transactions.

That's what I thought.

From the Help:
>> Duplicate: The status will be automatically be changed to duplicate if it is recognized as such. 

So the Help is not just missing descriptions of MMEX functionality, it is wrong in at least one place.

Anyone know a keen Technical Author?

**Comment by vomikan** [comment]
> Anyone know a keen Technical Author?

ncklee@myseneca.ca

**Comment by tactilis** [comment]
I'm happy to contact Kyra if that's appropriate @vomikan 

Do you have any idea whether she is interested in contributing to open source projects? i.e. unfunded work and would need to put in the time to properly understand the application.

And once we do have a good Help manual, we'd need to be disciplined at keeping it up to date for _every_ new capability or change to existing functionality (that is sensible to include in the Help).

**Comment by whalley** [comment]
Interesting article... https://www.stephaniemorillo.co/post/2017/07/06/finding-writers-for-open-source-projects

**Comment by vomikan** [comment]
> Who added the review comments?

davidkbolton@gmail.com

**Comment by tactilis** [comment]
> Interesting article... https://www.stephaniemorillo.co/post/2017/07/06/finding-writers-for-open-source-projects

That's a useful article.

_"...knowing how to use the thing well is key to documenting it"_

Yes, exactly.

Plus, it's not just a one-off activity. It's an on-going task to keep the documentation in step as the application evolves. There's a workflow.

**Comment by renato-mmex** [comment]
In the post: https://github.com/moneymanagerex/moneymanagerex/issues/4544
there is a reference to this article:
https://crowdin.com/project/moneymanagerex/ru#/docs
Now I have a problem. On crowdin there are the program internal texts which should be translated (by the users) into the respective language.
But there are also the help texts to translate. These texts have almost the same content as the https://github.com/renato-mmex/moneymanagerex/tree/master/docs/de_DE based on: https://github.com/moneymanagerex/moneymanagerex/issues/4450
Can someone now clearly define for me which descriptions / help texts are maintained / translated by whom.

**Comment by vomikan** [comment]
@renato-mmex 
How translation works. The English files from the repository are taken as a basis https://github.com/moneymanagerex/moneymanagerex/blob/master/po/mmex.pot
Immediately after the translation, the files (*.po) get into the repository automatically.

There are more help files
https://github.com/moneymanagerex/moneymanagerex/tree/master/docs/en_GB
At the time of online transfer to https://crowdin.com/project/moneymanagerex the help files remain on this site. They can be downloaded and uploaded manually to the main repository https://github.com/moneymanagerex/moneymanagerex . This is my job. It is advisable not to transfer files to repositories https://github.com/moneymanagerex/moneymanagerex/tree/master/docs/de_DE directly, only if it is not a correction of an already translated file.
