### ISSUE TITLE
Recurring transactions repetitions counted badly in Cash Flow reports

### ISSUE THREAD

**Issue by mek-x** [moneymanagerex/moneymanagerex#459]
When set, for example, 10 repetitions and frequency as "monthly" - in Cash Flow report, payments are only reported for 4/5 months. It looks like repetitions are counted twice.

First spotted in version: 1.1.2 stable

**Comment by guanlisheng** [comment]
Please send a pull request to fix the issue

**Comment by mek-x** [comment]
Already done. Thanks!

**Comment by stef145g** [comment]
Fix already merged in master and v1.2.x branch. 
Closing this issue.
