### ISSUE TITLE
Split Transaction Dialog refactoring

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4591]
![image](https://user-images.githubusercontent.com/6836805/173182294-f280e9ea-b61f-43e0-872d-bf73dbd41b3d.png)

**Comment by whalley** [comment]
Are we going to limit to 10 splits? Or is that just an example? Whilst 10 is fine for me... not sure what others do.

**Comment by vomikan** [comment]
> Or is that just an example?

Exactly. It would be unlimit split items interface.

**Comment by whalley** [comment]
Can't add new splits (at least on MacOS) without using keyboard and pressing return on the amount field. Had expected to be able to check the checkbox on the next entry.

An oddity... When trying to add the 6th split the 10th category entry becomes selected not the 6th.

**Comment by vomikan** [comment]
@whalley Yes, to confirm the new split category, press Enter. We can think about how to improve this in the future.



> An oddity... When trying to add the 6th split a new row is created, then can't add anymore

Probably some kind of MAC feature. For my part, I will also check more carefully.

**Comment by whalley** [comment]
Yes, just spotted:
`    if (id < static_cast<int>(m_local_splits.size()) || id < 5)`

**Comment by vomikan** [comment]
> Yes, just spotted:
> ` if (id < static_cast<int>(m_local_splits.size()) || id < 5)`

I was testing on a short list. Then I increased it to 10, but I made a mistake with the constant due to the poor style of setting constants. Fixed it.

**Comment by whalley** [comment]
> Yes, to confirm the new split category, press Enter. We can think about how to improve this in the future.

What just using the checkboxes to enable a split to be setup/managed and adding an 'Add Split' button to the dialog? That way setting up a split is practically the same as removing one, i.e. using the checkbox?

**Comment by vomikan** [comment]
> What just using the checkboxes to enable a split to be setup/managed and adding an 'Add Split' button to the dialog to add an extra row? That way setting up a split is practically the same as removing one, i.e. using the checkbox?

I think it's easy to implement. But in this I see a complication. A little later I will think about this option.

**Comment by whalley** [comment]
Just built against wx3.1.7 and have some dialog funnies on Mac, similar to the others I recently 'fixed'.

![CleanShot 2022-06-12 at 13 22 51](https://user-images.githubusercontent.com/487345/173232965-44c3e07a-3ff8-401e-a437-014332670732.png)

Also get below debug message:
`2022-06-12 13:09:38.736 mmex[99582:15840918] This application is trying to draw a very large combo box, 30 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.`

Will investigate this further....

**Comment by vomikan** [comment]
What they mean ```large combo boxes```?
Large size or large autocomplite vector?

**Comment by vomikan** [comment]
> Just built against wx3.1.7 and have some dialog funnies on Mac, similar to the others I recently 'fixed'.

I am using wx 3.1.7 at the moment.
I observe this effect only if there is a category with a very long name.

**Comment by whalley** [comment]
> > Just built against wx3.1.7 and have some dialog funnies on Mac, similar to the others I recently 'fixed'.
> 
> I am using wx 3.1.7 at the moment. I observe this effect only if there is a category with a very long name.
> 
> > `Vertically resizable combo boxes are not supported`
> 
> I think that here we are talking about a long list of available values. We will probably have to change the logic of the combobox. For example, to load the list by the first letter, after pressing the key.

That does not seem to be the case in my experience. It seems to be related to the height of the textctrl on the row and an attempt then to resize the combobox to match. If I remove the text control from the wxflexgridsizer and make it two columns wide then the earning is not generated. E.g. the below does not generate the message.
![CleanShot 2022-06-12 at 18 42 43](https://user-images.githubusercontent.com/487345/173246095-9a3953ad-e5dc-4beb-b29f-bf2c3ea13210.png)

**Comment by vomikan** [comment]
> Perhaps have one column with a boxsizer in it with the controls?

There is wxFlexGridSizer.

**Comment by whalley** [comment]
Yes, that avoids the error at the expense of the non-expanding category combobox, but I guess we can make that a little wider and make the dialog non re-sizable.

**Comment by vomikan** [comment]
> I'm not sure about the 'old school dialog', why do we need it? It just seems to confuse. It just seems to duplicate what is already there.

> What just using the checkboxes to enable a split to be setup/managed and adding an 'Add Split' button to the dialog to add an extra row?

That's how I understood those words. I also consider this solution redundant. We will consider this an unnecessary experiment.

**Comment by whalley** [comment]
Have done some additional testing, with the following observations (some of which you probably already know about):

- It might be useful, rather that the 'old school dialog' to enable (or create and enable) the next set of category/amount values when the checkbox on a row is selected.
- At present, I can select the checkbox for a row and enter a category and amount reported then click to another field and the total is not updated, on pressing OK the entry is not added. Entries only seem to be processed if ENTER it typed or the 'old school dialog' is used.
- At present, I can select the checkbox for a row and enter just an amount with no category and no error is reported when I press OK.
- Crashes if I type a category that is not currently setup (same applies to basic transaction dialog with no splits)

**Comment by vomikan** [comment]
If we accept that it is necessary to press Enter for each entry, then data entry is quite easy. When entering only an amount without a category, a corresponding warning occurs. I can't reproduce the crash.

![image](https://user-images.githubusercontent.com/6836805/173788855-5ab3f671-cf5b-4821-9a27-5842248cef45.png)

https://user-images.githubusercontent.com/6836805/173788336-2751ef60-2cf2-4335-a2c8-aaaa42455fd9.mp4

**Comment by vomikan** [comment]
> * It might be useful, rather that the 'old school dialog' to enable (or create and enable) the next set of category/amount values when the checkbox on a row is selected.

I need an explanation. Create the next empty line ready to enter values?

> * At present, I can select the checkbox for a row and enter a category and amount reported then click to another field and the total is not updated, on pressing OK the entry is not added. Entries only seem to be processed if ENTER it typed or the 'old school dialog' is used.

I either don't understand the sequence of actions, or I can't reproduce it.



> * At present, I can select the checkbox for a row and enter just an amount with no category and no error is reported when I press OK.

Yes, it is. Without clicking on Enter, the string is not valid yet, so it is ignored without error (checkbox is not active, does not fall under verification).



> * Crashes if I type a category that is not currently setup (same applies to basic transaction dialog with no splits)

I also don't understand how to reproduce this.
![image](https://user-images.githubusercontent.com/6836805/173794185-29902d23-2fd1-4501-a8dc-67cacdcf2dff.png)

**Comment by whalley** [comment]
I think we should validate the presence of valid category and amount on ALL items with checkbox selected when OK is pressed.

Having re-checked, It doesn't crash under wx3.1.5 but the tooltip points to the wrong field.
<img width="421" alt="CleanShot 2022-06-15 at 10 27 31@2x" src="https://user-images.githubusercontent.com/487345/173794178-9fb3b200-540e-4db1-8cca-94c06facc59c.png">

The crash is odd, it is happening in bitmap handling under wx3.1.7 (possibly a similar issue to what @PMaff is seeing with Linux).
<img width="1411" alt="CleanShot 2022-06-15 at 10 30 32@2x" src="https://user-images.githubusercontent.com/487345/173794773-21d60a4f-e7ee-4931-bcd1-90bc17fdca4c.png">

**Comment by vomikan** [comment]
> I think we should validate the presence of valid category and amount on ALL items with checkbox selected when OK is pressed.

In my opinion, this has already been done. Therefore, I do not understand where to go next.

**Comment by gabriele-v** [comment]
@vomikan I think once finished this, you should publish beta and then official release, there are already too many changes for me

**Comment by vomikan** [comment]
> @vomikan I think once finished this, you should publish beta and then official release, there are already too many changes for me

We have moved away from the practice of publishing beta versions. The build after each change can be downloaded for testing. https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/history - platform - artifacts

All these (big) changes were not included in the stable release 1.5.15 (not released yet). But I think it would be nice to include all this there.

**Comment by gabriele-v** [comment]
Understood, was thinking they were all for 1.5.15

**Comment by vomikan** [comment]
There is little feedback. I'm not sure if it's time to release 1.5.15. It would also be nice to understand if you like the latest innovations (split, coordinates storing, comboboxes).

**Comment by gabriele-v** [comment]
I haven't tested the new features yet, but I think the more powerful thing for 1.5.15 will be the new reporting, that looks amazing. Also comboboxes looks cool and easier. Regarding the splits, it may be a bit quicker to add, do you know if it supports the automatic amount like old splits? That was pretty useful.
No real needs for me about the coordinates storing, but it may be useful to someone else if it's not slowing down too much the application.

**Comment by gabriele-v** [comment]
Anyway I think that we should avoid adding new features now and focus optimizing the last ones and then release.
If we release too many changes at the same time, it will be more difficult for users to get addicted as well (and for bugfix as already highlighted).

**Comment by vomikan** [comment]
@gabriele-v 
> if it supports the automatic amount like old splits

This feature is destroyed by the update. I don't see the point in it yet, because the overall result is easy to control.

**Comment by gabriele-v** [comment]
> @gabriele-v
> 
> > if it supports the automatic amount like old splits
> 
> This feature is destroyed by the update. I don't see the point in it yet, because the total result is easy to control.
Consider this case:
- I know the total amount of the transaction, which is let's say 200 Euro, so I add 200 Euro in the amount
- I know it's a split, so I enable the split checkbox and I add let's say 37 Euro under a category
- With previous version, adding another split would automatically add it with 163 Euro without need to remember how much it was the entire transaction amount
- Now instead I'd need to move the split windows, see on the transaction and then type 200-163 in the amount (haven't tried but it should support mmcalc, correct?)

**Comment by vomikan** [comment]
> * Now instead I'd need to move the split windows, see on the transaction and then type 200-163 in the amount (haven't tried but it should support mmcalc, correct?)

Exactly

**Comment by gabriele-v** [comment]
> > * Now instead I'd need to move the split windows, see on the transaction and then type 200-163 in the amount (haven't tried but it should support mmcalc, correct?)
> 
> Exactly

Not sure what do you think about it, but IMHO it's a regression, I'm using it all the time

**Comment by whalley** [comment]
> > I think we should validate the presence of valid category and amount on ALL items with checkbox selected when OK is pressed.
> 
> In my opinion, this has already been done. Therefore, I do not understand where to go next.

Think you have caught some of this with your recent change, shower it is still possible to have a checkbox selected with invalid input, see below.

https://user-images.githubusercontent.com/487345/173832175-b4d78ac3-854c-4f87-9048-e9dba3a442b2.mp4

I still no benefit in the popup dialog when enabling a checkbox, in fact I find it annoying!

> It might be useful, rather that the 'old school dialog' to enable (or create and enable) the next set of category/amount values when the checkbox on a row is selected.
I need an explanation. Create the next empty line ready to enter values?

I was thinking that when the checkbox is selected on a row then we should enable the next row for use (with checkbox unselected - same as is done if ENTER pressed), if the next row is not already enabled. If no next row exists it should be created and enabled with the checkbox disabled - as is done if ENTER pressed.

**Comment by gabriele-v** [comment]
@whalley I agree on both points

@vomikan Understood, but you have anyway to type/calculate something which may be already automatically completed for you

**Comment by whalley** [comment]
The 'Split Transaction Dialog' is opening quite a distance away from the 'New/Edittransaction' dialog it was invoked from. Never noticed this before. The location of opening seems relative to the screen and not relative to the 'New/Edit transaction' dialog.

**Comment by vomikan** [comment]
I have changed the logic of this dialog. Please test it.

**Comment by whalley** [comment]
> I think we should validate the presence of valid category and amount on ALL items with checkbox selected when OK is pressed.
> 
> Having re-checked, It doesn't crash under wx3.1.5 but the tooltip points to the wrong field. 
> 
> The crash is odd, it is happening in bitmap handling under wx3.1.7 (possibly a similar issue to what @PMaff is seeing with Linux). 

Crash on wx3.1.7 now resolved,  for some reason I needed to clean/re-build my wxWidgets build. Now works fine.
