### ISSUE TITLE
Transaction report error

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#4593]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x ] Linux 

# Description of the bug
Selecting transaction report indicates an error.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information
![test](https://user-images.githubusercontent.com/80578702/173184198-7b95f6e3-c4dc-4aad-bc4d-b35f35f1b87c.png)

Money Manager Ex
Version: 1.5.15-Beta.4 64-bit
• Build on Jun 11 2022 10:23:41
• Database version: 7 • (aes128cbc)
• Git commit: ed6aa4e5b (2022-06-09)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.1.6 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• lunasvg v2.3.1
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu 22.04 'jammy'
Running on:
• Ubuntu 22.04 LTS "jammy"
• Linux 5.15.0-37-generic x86_64
• Hungarian (Hungary) (UTF-8)
• 0x0 0bit 96x96ppi

**Comment by PMaff** [comment]
Seems to be a copy of
https://github.com/moneymanagerex/moneymanagerex/issues/4290#issuecomment-1149189638

**Comment by vomikan** [comment]
Please downgrade to  wxWidgets 3.1.5

**Comment by whalley** [comment]
@vomikan Why is this tagged as v1.5.15? Seems related to wx3.1.6+ as noted.
