### ISSUE TITLE
Payee and Category new transaction defaults

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4620]
MMEX version:
 - [x] 1.5.6 Beta1
 - [x] Windows

When entering a new entry, the last used category is no longer forgiven.

Is the bug reproducible? 
 - [x] Always

**Comment by whalley** [comment]
Think we need to look at this logic again.

For Default Payee we have:

- None. Which results in a blank payee, seems good
- Last Used. Finds the last used payee for the account and displays that, seems good
- Unsed. Which results in a blank payee, **how is this different from 'None'?**

For Default Category we have:
- None. Which results in a blank category, seems good
- Last used for Payee. Which looks up the last used for the payee, seems good
- Unused - **Uses an "Unknown" category, creating one if not present. This will break current handling as it does not update the list for the combobox..... Do we really need this?**
- Use default for Payee. **Not convinced this is working.**



If UNUSED is specified and we

**Comment by renato-mmex** [comment]
from my point of view, I would like to see the following options:

- no default (necessary ?)
- last used for this account

Reason: there are transactions that I do over and over again at the same place, such as grocery shopping, parking fees, gasoline, medications

**there is a category delimiter in the settings, it has no effect lately.**

**Comment by whalley** [comment]
> from my point of view, I would like to see the following options:
> 
> * no default (necessary ?)
> * last used for this account
> 
> Reason: there are transactions that I do over and over again at the same place, such as grocery shopping, parking fees, gasoline, medications

Is that for Payee (which we already have) and category (new option)

> **there is a category delimiter in the settings, it has no effect lately.**

This works fine for me, I can change the delimiter and the application conforms.

**Comment by renato-mmex** [comment]
> > from my point of view, I would like to see the following options:
> > 
> > * no default (necessary ?)
> > * last used for this account
> > 
> > Reason: there are transactions that I do over and over again at the same place, such as grocery shopping, parking fees, gasoline, medications
> 
> Is that for Payee (which we already have) and category (new option)

Correct, many times the payee has a direct reference to the category. Example: Tamoil>gasoline, Lidl>groceries
> 
> > **there is a category delimiter in the settings, it has no effect lately.**
> 
> This works fine for me, I can change the delimiter and the application conforms.

Sorry, have overlooked that **MMEX must be restartet**, that the delimiter is reset.

By the way, I find the old representation of the category selection more user-friendly, moreover we have now two different representations
<img width="226" alt="image" src="https://user-images.githubusercontent.com/76920138/174398416-c053207a-7c82-4ad0-bd75-c37da899bfa1.png">
<img width="227" alt="image" src="https://user-images.githubusercontent.com/76920138/174398492-3ede43fd-54f5-4944-a4db-703a6b4b61a1.png">

**Comment by whalley** [comment]
OK, logic reviewed and now implemented.

### For Default Payee we have:

- **None** This will present a blank payee field.
- **Last Used** Finds the last used payee for the account and will present that in the payee field.
- **Unsed** Will always present an "Unknown" payee, if no such payee exists in the payee list it will first be created.

### For Default Category we have:

- **None** This will present a blank category field.
- **Last used for Payee** Will present the last used category for the payee.
- **Use default for Payee** Will present the default category as set by the user against the payee in the payee list.
- **Unused** Will always present an "Unknown" category, if no such category exists in the category list it will first be created.

**Comment by gabriele-v** [comment]
FYI @whalley "unknown" has been added because some users would prefer to have the payee and category as optional and not mandatory (inserting only amount and account), that's the usage case
