### ISSUE TITLE
Reports: Categories and Income vs Expenses

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4622]
MMEX version:
 - [x] 1.5.15
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Drop-down window **Period** is the same for both reports.

# Reproduction

Is the bug reproducible? 
 - [] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:

1. Open Categories report
2. Changed default period to **Last 365 days**
3. Open Income vs Expenses report
4. The default Period is **Last 365 days** too
5. Changed it to **Last 12 months**
6. Open Categories report again

…

**Expected result:**
Categories report Period should be **Last 365 days**
**Actual result:**
Categories report Period is **Last 12 months**
# Additional information
It works vice versa...
If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I can't reproduce this.

**Comment by vomikan** [comment]
I can't reproduce this also.

**Comment by gabriele-v** [comment]
Can't reproduce as well
