### ISSUE TITLE
Allow adding a new Payee from the transaction entry form

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#463]
When adding a new transaction, there can often be a new Payee. It is cumbersome to have to go to Payees form to enter it, then back to New Transaction to select.
Please allow adding a new Payee directly from the New Transaction form, in case a typed-in payee was not found in the list.

**Comment by vomikan** [comment]
Just type the new payee name in payee field.

понедельник, 20 апреля 2015 г. пользователь Alen Siljak написал:

**Comment by MisterY** [comment]
Now I get a prompt to add the Payee. :+1: 

I did try thing before, I swear! :D
