### ISSUE TITLE
Regular Expressions in transaction filter notes

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#4631]
Hello, considering that it has already been implemented for payees/categories, would be possible to have the lookup with Regular Expressions also for the notes?

I know that there are already some wild cards, but it would be useful to have RegEx as well.
![image](https://user-images.githubusercontent.com/7106290/174260887-9cffe3b7-7917-46e2-8ba1-7284e41ec201.png)

I think we may consider as suggested by @whalley to have somethign specific for regex, like Regex[...] to distinguish between standard searches, or enable a checkbox on the side which means use regex.

**Comment by gabriele-v** [comment]
Yes, additional gui element would be useful/clearer but it's not mandatory, we just need a pattern or text to define when is standard search and when is regex

**Comment by whalley** [comment]
> I think we may consider as suggested by @whalley to have somethign specific for regex, like Regex[...] to distinguish between standard searches, or enable a checkbox on the side which means use regex.

Yes, my logic is that power users don't need a checkbox and can enter the text regex[...] (or whatever notation we choose) to distinguish it from a normal match. But 'casual' users don't have to worry about it.

**Comment by vomikan** [comment]
I am in favor of regular expressions being hidden from the eyes of non-advanced users. And for not loading the UI with additional elements. This is how it is now implemented for the Payee and Category fields.
But for Notes, it must be determined in advance which algorithm is used by RegEx or Matches.

**Comment by n-stein** [comment]
Not sure if we were ready to implement this yet as it hasn't had any action in a few months, but I had a go at it this using the regex[...] syntax discussed above. I have put the changes in PR #5142 for review.

**Comment by n-stein** [comment]
New PR #5144
