### ISSUE TITLE
Transfer in Recurring Transactions panel

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4633]
This view is different from other panels.

![image](https://user-images.githubusercontent.com/6836805/174272784-9c79271a-5d39-4c36-8cc5-881b8989565d.png)

**Comment by vomikan** [comment]
I don't see the effect. And there is a bug with editing. The To Account element is not initialized.

![image](https://user-images.githubusercontent.com/6836805/174288501-ec76ab9f-0f13-4412-844e-1f09f94c5a4e.png)

**Comment by whalley** [comment]
Is your transfer to a valid account? Why ERROR ACCOUNT? Seems fine for me and I've not done anything to affect the dialog.

**Comment by vomikan** [comment]
> Is your transfer to a valid account?

No

**Comment by whalley** [comment]
I missed that it was doing a `ChangeValue`. In that case, yes reinstate, but we don't need to set `element_id_` , that is now redundant.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/174292581-29479eb0-0502-49b9-b738-3b67af79d199.png)

**Comment by vomikan** [comment]
> I'll fix and tidy by removing the commented-out code.

I've already fixed something. But new bug is represented above.

**Comment by whalley** [comment]
Yep, just posting fix now.
