### ISSUE TITLE
Transaction report not working with version 1.15.5

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#4642]
MMEX version:
 - [x] 1.5.15
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [ x] Mac OSX
 - [ ] Linux 

# Description of the bug 
Saved transaction report lost in new version 

Please describe your issue with details.
 Creating new it shows all zeros 
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Need help or fix this issue 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
#4623
