### ISSUE TITLE
Display window too small

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4647]
MMEX version:
 - [x] 1.5.6 Beta1
 - [x] Windows 11

The display window is too small for the display of German texts

<img width="327" alt="image" src="https://user-images.githubusercontent.com/76920138/174428681-f724a2c7-6c08-402e-9209-1f5ffbb2e560.png">

**Comment by vomikan** [comment]
Dear Renato, could you, please, show icon size settings as well?

**Comment by renato-mmex** [comment]
great, thanks a lot
