### ISSUE TITLE
Input not allowed for custom decimal fields when precision set >0.

### ISSUE THREAD

**Issue by f-hansen** [moneymanagerex/moneymanagerex#4651]
MMEX version:
 - [x] 1.5.15

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The GUI does not allow populating custom decimal fields when the precision is set to >0.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

# Screenshots

![decimal_issue_digits_scale](https://user-images.githubusercontent.com/53111364/174460938-aa0338fe-b3f3-4356-b2d6-9a7d837f25e0.png)

![decimal_issue](https://user-images.githubusercontent.com/53111364/174460845-ef3e5e3e-32bd-4d06-9374-5395a102555d.png)

**Comment by vomikan** [comment]
In general, it works. Apparently, some special case.
![image](https://user-images.githubusercontent.com/6836805/174475207-2f4affb8-af30-4626-93b5-c6ef5e311260.png)

**Comment by whalley** [comment]
I can't reproduce this either on MacOS.

**Comment by vomikan** [comment]
@f-hansen could you prepare anonymized DB with this issue to share it for us?

**Comment by f-hansen** [comment]
@vomikan, as requested, here is an  example DB:
[test.mmb.gz](https://github.com/moneymanagerex/moneymanagerex/files/8937419/test.mmb.gz)

After looking at this more, I noticed some warning and critical messages. The following message always occurs when exiting the custom fields manager.

> ** (mmex:745054): CRITICAL **: 01:10:37.772: Cannot register URI scheme memory more than once

However, the following messages only occur when selecting an account that has a custom decimal field with a precision > 0. They do not occur otherwise.

> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_spin_button_new_with_range: assertion 'step != 0.0' failed
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_spin_button_set_value: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_entry_set_alignment: assertion 'GTK_IS_ENTRY (entry)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_entry_set_width_chars: assertion 'GTK_IS_ENTRY (entry)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_spin_button_set_wrap: assertion 'GTK_IS_SPIN_BUTTON (spin_button)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_is_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_fixed_put: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_set_direction: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_handler_block: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_get_realized: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): GLib-GObject-WARNING **: 01:09:25.379: invalid (NULL) pointer instance
> 
> (mmex:745054): GLib-GObject-CRITICAL **: 01:09:25.379: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_get_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.379: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.380: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.380: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.380: _gtk_widget_get_preferred_size_and_baseline: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.380: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.380: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (mmex:745054): Gtk-CRITICAL **: 01:09:25.423: gtk_container_set_focus_chain: assertion 'GTK_IS_WIDGET (tmp_list->data)' failed

Thank you, and please let me know if there is anything else I can provide.

**Comment by vomikan** [comment]
I can assign any value. The only thing is that the arrows do not change the value, only from the keyboard.

![image](https://user-images.githubusercontent.com/6836805/174568904-05a19e08-5fbc-4cb7-86a3-19fc2962b039.png)

**Comment by whalley** [comment]
That test DB works fine on MacOS. Same observation as @vomikan regarding the buttons.
<img width="825" alt="CleanShot 2022-06-20 at 10 18 56@2x" src="https://user-images.githubusercontent.com/487345/174569564-d5527021-c93f-42e0-8cc1-2476daf81672.png">

**Comment by f-hansen** [comment]
@vomikan, it's working perfectly after your fix. Thank you much!
