### ISSUE TITLE
No summary data after Shift-Click selection of multiple transactions

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4652]
MMEX version:
 - [x] 1.5.15

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

From [https://forum.moneymanagerex.org/viewtopic.php?p=23021](https://forum.moneymanagerex.org/viewtopic.php?p=23021)

Selecting multiple transactions using Ctrl+Click shows summary data in the bottom panel:

![image](https://user-images.githubusercontent.com/4060092/174474274-028730d9-5f67-478e-ad89-f5602b5ab82a.png)

However, if the multiple transactions are selected using Shift-Click (or Shift-up/down Arrow) then the summary data is not displayed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Expected result:

Summary data should be shown whenever multiple transactions are selected, regardless of how the selection is made.

**Comment by vomikan** [comment]
#3419
