### ISSUE TITLE
Transaction display after category selection

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4663]
MMEX version:
 - [x] 1.5.16 Beta1
 - [x] Windows 11

<img width="337" alt="image" src="https://user-images.githubusercontent.com/76920138/174498427-b880a817-2a5f-4ce6-8c52-3a4b173e563e.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/76920138/174498439-5a48ebf7-4315-426c-b170-11abfb3c85b5.png">

**Comment by tactilis** [comment]
@renato-mmex, I don't see that effect. The dialog width is OK here, regardless of which Category is chosen.

@vomikan, for some reason the Advanced check box (next to Type) on Renato's dialog is too small. It's OK on mine.

@renato-mmex 
> 1.5.6 Beta1

Note, it's 1.5.**16** Beta 1

**Comment by vomikan** [comment]
> I don't see that effect.

It depend on some category name lengh. It's too long.
