### ISSUE TITLE
Reports - Stocks Report is not exists

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4665]
MMEX version:
 - [x] 1.5.15
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

All the reports were hidden in the new Hide Reports window, besides Stocks Report. But the Stocks Report is not exists.
![image](https://user-images.githubusercontent.com/83161661/174499793-c4d16255-7776-4f08-b4f3-50352ad17152.png)

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
Is any Investment account available?
