### ISSUE TITLE
Transaction report name/title

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#4680]
# Description of the feature
Transaction report name it's now a bit "hidden" under small label field, especially if you have multiple row returned.
I'd suggest to place the  name as title instead of "Transaction Report" or adding it at the end, in this case it would be "Transaction Report - Interessi"

![image](https://user-images.githubusercontent.com/7106290/174659082-35b46230-5923-4c4c-aafb-4df776066e8a.png)

**Comment by whalley** [comment]
Good idea... I've added to the label after the report type title.
