### ISSUE TITLE
Transaction report filters for "transfer out" and "transfer in" not working as expected

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#4684]
MMEX version:
 - [x] 1.5.16-Beta.1 64-bit (https://github.com/moneymanagerex/moneymanagerex/commit/2c00c92478b765e635c9e06c571d7e18bf23a052)
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Regardless of which box is checked ("Transfer out", "Transfer in", or both), both types of transfers are shown in the transaction report.

![image](https://user-images.githubusercontent.com/1184162/174666600-e38ee725-774c-4d3b-a80f-6cce0540f929.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create a transaction that is a transfer between two accounts
2. Create a transaction report and select Type: "Transfer in"

Expected result: Only one transaction ("in") should be displayed

Actual result: Both sides of the transaction ("in" and "out") are displayed

**Comment by whalley** [comment]
There was an extensive discussion on this here: https://github.com/moneymanagerex/moneymanagerex/issues/4239

@cmbarbu Can you confirm if you have All Accounts selected in the filter? In this case you will get Transfers In and Out as noted in above issue.

However I have spotted something that looks odd...
When an empty filter is edited and type only selected the allows both Transfer Out / Transfer In to be specified which is wrong as 'All Accounts' is selected.
![CleanShot 2022-06-21 at 01 16 18](https://user-images.githubusercontent.com/487345/174691721-2393097f-2272-449d-9bf4-316d5640081a.png)

If I select the Account checkbox and unselect then only 'Transfer' is allowed - which is correct.
![CleanShot 2022-06-21 at 01 18 42](https://user-images.githubusercontent.com/487345/174691960-26e17f96-3393-45a1-8de0-ca4de529a659.png)

**Comment by cmbarbu** [comment]
> @cmbarbu Can you confirm if you have All Accounts selected in the filter? In this case you will get Transfers In and Out as noted in above issue.

@whalley No, I had not filtered by Account.

> If I select the Account checkbox and unselect then only 'Transfer' is allowed - which is correct.

Good catch, I had not noticed that!

Thank you for the quick fix!
