### ISSUE TITLE
Reports - Payees

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4687]
MMEX version:
 - [x] 1.5.15
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Payees Report shows My_Company where I received a salary (Income) as a payee.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. I have created a new Test DB with 2 transactions only:
 **Income** from my company (10,000) and **Expense** in a supermarket (-500)
![image](https://user-images.githubusercontent.com/83161661/174758932-e5e9a15e-f303-4f34-a8cc-018838748a26.png)
2.  Open Payees Report
![image](https://user-images.githubusercontent.com/83161661/174759178-a63be3d1-41de-4cfb-a53a-df3f1b3ef5f2.png)

…

**Expected result:**
It should be just payees - shops, organizations, or people I have paid to.
**Actual result:**
There is My_Company as a payee, **but My_company is not the payee.** There is another report Income vs Expenses where it is relevant.
![image](https://user-images.githubusercontent.com/83161661/174762734-31d09075-f834-4597-816d-62be140bb9a4.png)

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
There has a been a discussion before about the meaning of Payee - See https://github.com/moneymanagerex/moneymanagerex/issues/4297

In effect where MMEX uses Payee it relates to both Payee and Payer. As such, the report would seem to be correct.

**Comment by Dandy64** [comment]
Yes, I got it. And the Help is very clear indeed. 
In this case, I do not agree with using the word "Payee" and the Cambridge Dictionary thinks so.
**A payee - is a person who the money is paid or should be paid to.**
[https://dictionary.cambridge.org/dictionary/english/payee]
