### ISSUE TITLE
Reports - Cash Flow - Monthly

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4688]
MMEX version:
 - [x] 1.5.15
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In the Test DB there are just 2 transfers:
- Income + 10000
- Supermarket - 500
The graph Cash Flow - Monthly looks very weird.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  Open Reports - Cash Flow - Monthly
![image](https://user-images.githubusercontent.com/83161661/174767026-40383273-34cd-45f6-986f-f39e367f6496.png)
 and up to 21.05.2032 
It looks like it is going to be the same sum for 10 years ahead. Perhaps this report is not relevant at all.

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
The cash flow report considers future transactions (i.e. in the recurring transaction list) and how it may influence your account balances. Assuming you have no future transactions then the report would seem correct.

**Comment by tactilis** [comment]
@Dandy64
What were you expecting to see?

**Comment by Dandy64** [comment]
It looks like this report brings no useful information.  I can not imagine a situation I need it. My income is changing and me expenses are changing either an all the time. So any forecast for 10 years ahead is absolutely useless.
You do not agree, do you?
Anyway, in this version of MMEX there is a very cool option to hide unnecessary reports and for me, this is the case.
----------------------------------------------------------------------------------------------------------------
_BTW, it would be a nice feature for accounts - show/hide specific accounts. I have a few closed accounts and I would prefer not to see them in the list._

**Comment by Dandy64** [comment]
@tactilis 
"...some people (or small businesses) have stable income & expenses and can forecast their cashflow"
So, in this case, they have more or less the same number!

**Comment by whalley** [comment]
> BTW, it would be a nice feature for accounts - show/hide specific accounts. I have a few closed accounts and I would prefer not to see them on the list.

There are options available to hide closed accounts.

<img width="557" alt="CleanShot 2022-06-21 at 13 02 14@2x" src="https://user-images.githubusercontent.com/487345/174794516-7d659a53-c60b-4b90-bd1c-cb1ae3e819d3.png">

<img width="573" alt="CleanShot 2022-06-21 at 13 03 57@2x" src="https://user-images.githubusercontent.com/487345/174794874-73221187-8cb4-42b0-bf2b-81afaf6268a1.png">

**Comment by Dandy64** [comment]
"There are options available to hide closed accounts."

You are right. Sorry, I did not see this feature.
