### ISSUE TITLE
Reports 

### ISSUE THREAD

**Issue by Freddiejunior** [moneymanagerex/moneymanagerex#4691]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result: Reports - should open a list of reports

Actual result: Reports - nothing happens

Additional information: I have updated to version 1.5.15 and have completed the month of May transactions and went to do a summary report of income and expenses by category for the month of May and the year to date (January 1 to May 31), which I do every month. When I click on Reports nothing happens and I can find no other way to access this. Without being able to generate these reports, the program, beyond recording all the transactions which occurred during the month and verifying bank and credit card balances are correct, is useless. This needs to be fixed. In the meantime, I need to see if I can revert to the previous version.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Right click on Reports and make sure that yours are not hidden:

![image](https://user-images.githubusercontent.com/4060092/174869085-ca09d6a4-f122-4e4e-bb79-be59b7ba6c9d.png)

**Comment by Freddiejunior** [comment]
OK. That works. I had to download the new version again as I had reverted to the previous version. There is now a little triangle beside reports which opens the report list.

Thank you.

________________________________

**Comment by tactilis** [comment]
@Freddiejunior
> There is now a little triangle beside reports which opens the report list.

Yes, it's standard tree navigation:
- Click on the triangle to expand/collapse a branch
or
- Use the Right-arrow/Left-arrow key to expand/collapse a branch
