### ISSUE TITLE
Latest upgrade seems a downgrade for speed in accessing accounts

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#4695]
MMEX version:
 - [x] 1.5.15

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11

# Description of the bug
Since updating the switching between accounts has frozen the app. I have gone back to earlier version.

Please describe your issue with details.
I thought great new version but it's slow and freezes on me. Same database in use (8.7Mb)
Screenshot won't show anything except - not responding

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1.  Upgraded to latest version
2.  Open app
3. Switch between accounts
4. App freezes
5. Un-installed and re-installed earlier version.
6. Open app
7. Switch between accounts ok.
8. I have doe this twice to confirm the issue
…

Expected result:
Better 
Actual result:
Worse run time and locks
# Additional information
I access the files from Google drive. (is this a factor?) But it's the same storage for both versions, Yet newer is 'unstable'

**Comment by reddyshyam** [comment]
Shouldn't we be doing an emergency release to push this out instead of waiting for next version which might be a month or so knowing the release cycle?

**Comment by whalley** [comment]
> Shouldn't we be doing an emergency release to push this out instead of waiting for next version which might be a month or so knowing the release cycle?

A new release is planned very soon.

**Comment by reddyshyam** [comment]
> > Shouldn't we be doing an emergency release to push this out instead of waiting for next version which might be a month or so knowing the release cycle?
> 
> A new release is planned very soon.

Thanks @whalley. :)
