### ISSUE TITLE
I no longer have the saved filters of the previous version since the implementation of version 1.5.15

### ISSUE THREAD

**Issue by Dellyes** [moneymanagerex/moneymanagerex#4696]
Je n'ai plus les filtres enregistrés de la version précédente depuis la mise en place de la version 1.5.15. 

> Remplacez ce texte (marqué par >) avec une description détaillée de votre problème.
> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.5.15 64-bit<br>
 • Build: Juin 16 2022 09:13:44<br>
 • db 7 •  (aes128cbc)<br>
 • git e7bb96c (2022-06-16)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  French (windows-1252)<br>
 • 1360x768 32bit 96x96ppi

**Comment by tactilis** [comment]
The title says:  **I no longer have the saved filters of the previous version since the implementation of version 1.5.15**

**Comment by Dandy64** [comment]
See **Transaction Reports settings lost with v1.5.15** #4623
