### ISSUE TITLE
Create mmDatePickerCtrl

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4708]
For consistency and to avoid code complexity when creating Date controls that require a spinbutton (WIn/Linux) and the day of week static text we should create a custom control that encapsulates these.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4759#issuecomment-1173095062

**Comment by whalley** [comment]
https://github.com/whalley/moneymanagerex/commit/5fac978f3ba5885a0928a4791317c1ed04a065f5
