### ISSUE TITLE
Transferring between two accounts with same currency get converted into base currency using reverse forex 

### ISSUE THREAD

**Issue by didikrm** [moneymanagerex/moneymanagerex#4710]
MMEX version:
 - [x] 1.5.16
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Transferring from one account to another account that uses the same currency. 2 issues are encountered: 1) the receiving account gets the amount converted into base currency 2) it uses 1/forex.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Assume base currency in USD and transfer from GBP account to another GBP account. Create a transfer of 100GBP 
![01](https://user-images.githubusercontent.com/60562871/175487380-86bc4c52-cc67-4d93-85a7-185193c2bfd2.JPG)

2. The amount is automatically converted to 75.98 , which appears to be the reverse of GBX->USD. However, the value in the sending account remains correct at 100GBP and the advanced box is not activated. This is not right (I think previous versions had that issue) but as long as value does not change in the account, it's fine.
![02](https://user-images.githubusercontent.com/60562871/175487708-1a21d4c1-9cfa-4422-b876-b13e594006d4.JPG)

3. However, on the other end, the amount received is 75.98 and the advanced box is activated. If you disable the advanced box and press ok, it will keep the 75.98 value. The only way to keep 100GBP on both sides is to activate advanced box and manually write 100 in both text boxes and press ok. 
![03](https://user-images.githubusercontent.com/60562871/175487909-6aaabf56-053d-43e4-bc46-3ed4449d0e2c.JPG)

4. If you click on the transaction again on either account, everything seems to be working (advanced is disabled but the value is reverted back to 75.98 but not used as explained in step 2). You need to click on Cancel to keep things working because if you click on Ok (in either account) you'll face the same problem described in step 1.
![04](https://user-images.githubusercontent.com/60562871/175489063-2159a498-abaa-4216-b25e-adf9c7b00131.JPG)

…

Expected result:
There shouldn't be currency conversion when transferring between two accounts that use the same currency
The advanced option shouldn't be activated in the receiving account if it's not activated in the sending accounts
Even if currency conversion to base currency is used, somehow it's dividing by forex rather than multiplying. 
Actual result:
Results explained above with illustrations.
# Additional information
I think this issue started to appear since 1.5.14.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
![CleanShot 2022-06-24 at 11 08 54](https://user-images.githubusercontent.com/487345/175513983-20d119c0-9d0f-46e3-8f2d-644b7b76b4fa.png)

The cause of the advanced flag being set - think that should be `m_advanced == !m_new_trx` but not sure what the real purpose is as nothing actually gets done here. 

Does not fix the to amount being calculated wrongly on the display

**Comment by whalley** [comment]
![CleanShot 2022-06-24 at 11 21 46](https://user-images.githubusercontent.com/487345/175515995-a8b5e9da-4934-4a16-b512-758c1f2d15ca.png)

Think that should be `if (m_to_currency && (m_currency != m_to_currency)) {`

Maybe (I'm sure there are) other impacts... 

@vomikan Not got access to my Mac build laptop this weekend, so could you fix and test.

**Comment by vomikan** [comment]
I'm in the country. Also with limited access. But I think that there is no need to recalculate at some average rate. In real life, the bank's rate is always different from the average. I am for only manually entering the amount.

**Comment by whalley** [comment]
But I guess for the case where the two accounts are in the same currency (albeit different from base currency) we could default to the same value.

**Comment by vomikan** [comment]
> the case where the two accounts are in the same currency

Yes, but the amount recalculation is a result of the conversion algorithm. I suggest to renove  it.

**Comment by whalley** [comment]
> Yes, but the amount recalculation is a result of the conversion algorithm. I suggest to remove it.

I think you are right, having reviewed my workflow I always just override whatever is calculated and use the rate and use the relevant bank rate. I support removing the calculation.

**Comment by whalley** [comment]
Have also added a warning if the accounts have differing currencies and 'advanced' not specified.
