### ISSUE TITLE
V1.5.15/16 has Changed display appearance on Windows - Font now too large

### ISSUE THREAD

**Issue by cliveju** [moneymanagerex/moneymanagerex#4711]
MMEX version:
 - [x] 1.5.15 or 16 (upgraded from 1.5.14)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11

The font used is larger than before, making  it very hard to use MMEX. The screen can't contain all the information.  To avoid showing my personal accounts, I have attached the settings screen, which is now unusable. in part (it has no scroll facility and doesn't fit my screen any more).

I may downgrade to 1.5.14 to continue using MMEX.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

[MMEX 1.5.15 on Win-11 screen.pdf](https://github.com/moneymanagerex/moneymanagerex/files/8980583/MMEX.1.5.15.on.Win-11.screen.pdf)

**Comment by renato-mmex** [comment]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/76920138/175673236-765af000-f690-463f-8a32-72054fe1d199.png">

**Comment by cliveju** [comment]
I can't reach the font size box, it's off the bottom of the screen. The
font size has not changed on previous releases.

**Comment by cliveju** [comment]
I have managed to change the icon size as suggested but there is no control
over the font size used to display data. It's too large now.

**Comment by renato-mmex** [comment]
What is the resolution of the screen and how is the scaling set in Windows?

**Comment by renato-mmex** [comment]
I also have 3840x2160 and the recommended Windows 11 setting is 150%.

**Comment by cliveju** [comment]
As you can see our Pcs think differently!  My PC is a laptop with only a
13" screen.  I just tried 150% and I can't read anything, it's too tiny.

[image: image.png]

**Comment by tactilis** [comment]
> I also have 3840x2160 and the recommended Windows 11 setting is 150%.

The % will vary according to the DPI of the screen

A large monitor screen will have fewer DPI (bigger pixels) than a small laptop screen of the same resolution

**Comment by cliveju** [comment]
Yes, I suspect that the developer has a large screen so has not
encountered this issue.
