### ISSUE TITLE
Streamlining the Split Transaction dialog

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4712]
_[Updated to add Points to note, item h)]_

Following on from the discussion in #4664 about the usability of the tick boxes in each row of the Split Transaction dialog in v1.5.16, here is a proposal for streamlining the operation of that dialog.

1. On opening the dialog from the New Transaction dialog with no figure in the Amount field and no Category set, the Split Transaction dialog is displayed as shown:

![image](https://user-images.githubusercontent.com/4060092/175791585-22f8f1da-f578-4d29-aa3e-72cd9ddd81e0.png)

Points to note:
a) The word 'Dialog' has been removed from the title (it clearly _is_ a dialog, so we don't need to tell the user).

b) Labels of Category and Amount have been added to make clear the purpose of the fields.

c) The dialog initially contains 2 rows; the user wants to split the transaction, so it's sensible to default to 2 rows, which is probably the most common split.

d) Each time the [+] button is clicked an additional row is added below the existing rows; the height of the dialog will increase to accommodate this. Once the dialog reaches a maximum height (for example, with 10 rows), a scroll bar appears to scroll the rows as implemented in the current design.

e) To keep the UI as uncluttered as possible, there is no button to remove a row. It is not needed - see point f).

f) Clicking OK when one or more rows are blank is not an error; blank rows are simply ignored. Thus, the user can simply delete the data from the fields to remove part of an existing split.

g) Clicking OK when any rows contain Category text but no Amount (or vice versa) is an error; an error pop-up will be displayed in the first field that contains an error. We should consider unifying the error pop-up messages for the Split Transaction and Edit Transaction dialogs (the exact text can be decided on in a subsequent message in this thread)

h) The Total field should be updated when focus is in an Amount field and the user enters/edits/deletes the digits and then any of:
 - Presses Enter while still in the Amount field
 - Changes focus by clicking in any Category field, clicking in a different Amount field, clicking on the [+] button
 - Changes focus by pressing Tab (or Shift+Tab) to tab to a different field or button
 - Clicks on the OK button. The dialog would normally close at this point but may not due to a field validation error

2. On opening the dialog from the New or Edit Transaction dialog with a figure in that dialog's Amount field and/or category text in the Category field, the Split Transaction dialog is displayed with the first row amount and/or category populated accordingly.

![image](https://user-images.githubusercontent.com/4060092/175791575-644bfac8-f0e6-4bff-8dec-e6ba0de04266.png)

3. On opening the dialog from the Edit Transaction dialog with a split transaction, the dialog will be populated according to the split.

![image](https://user-images.githubusercontent.com/4060092/175791801-55888f6b-3b01-4c57-96dc-3d124da45064.png)

Further discussion may be required but I have tried to document all the necessary behaviour.

**Comment by vomikan** [comment]
@tactilis It remains to add a button (I can't align it using sizers) and, probably, event handling to change the combobox.
Now the logic is close to what you would suggest?

**Comment by tactilis** [comment]
@vomikan

> Now the logic is close to what you would suggest?

Good work!

But I think it's a bit early to say about the logic yet, especially as there are still the tick boxes and no [+] button yet.

I will certainly test it well when there is a bit more done.

I did notice, for example, that the Transaction Amount does not currently populate the split Amount when there is no Category on the Transaction dialog.

![image](https://user-images.githubusercontent.com/4060092/175819688-06279860-9ed3-49dc-9881-cd0f8302394e.png)

This is covered by point 2 above:

"2. On opening the dialog from the New or Edit Transaction dialog with a figure in that dialog's Amount field _**and/or**_ category text in the Category field, the Split Transaction dialog is displayed with the first row amount _**and/or**_ category populated accordingly."

Please note the use of "and/or" - I tried to write the specification as precisely as I could so that the functionality would be as useful as possible to the end user.
 
 
Thanks for making this change to the Split Transaction dialog @vomikan. I know you put a lot of work into the v1.5.16 implementation and it must be a bit frustrating when there are complaints and you have to rework the code.

**Comment by tactilis** [comment]
> But I saw the cleanest option was to have the delete buttons against all existing splits and a button that allowed splits to be added

That would work @whalley. I assume that the [-] actually removes the row, not just clears the data. 

And I like the explicit [Add Split] button better than [+]

A couple of questions:

1. Would you allow use of the [-] buttons to remove **_all_** the rows?  I think the answer should be Yes because any row should be capable of being removed and [Add Split] would permit rows to be added again.

2. If a user pressed [Add Split] and then didn't fill in Category and Amount, would you treat that as an error when OK is pressed, or would you just ignore the blank row?

**Comment by whalley** [comment]
> That would work @whalley. I assume that the [-] actually removes the row, not just clears the data.

Yes, removing the row is what I had in mind.

> 1. Would you allow use of the [-] buttons to remove **_all_** the rows?  I think the answer should be Yes because any row should be capable of being removed and [Add Split] would permit rows to be added again.

I would propose that it is **not** possible to remove the last row as that would then imply that no splits exists, just the one category. This is similar to when you first split a transaction with one category.

> 2. If a user pressed [Add Split] and then didn't fill in Category and Amount, would you treat that as an error when OK is pressed, or would you just ignore the blank row?

An error I would suggest. Keeping the UI simple and explicit is always best rather than implying that empty rows are intentional.

**Comment by tactilis** [comment]
> I would propose that it is not possible to remove the last row as that would then imply that no splits exists, just the one category. This is similar to when you first split a transaction with one category.

Good point.

That would allow the first (and only) row to be populated from the Category and Amount of the non-split transaction, and then, if the user pressed OK, it would validate correctly and still be a non-split transaction

**Comment by tactilis** [comment]
@vomikan 
The approach that @whalley was proposing was to have a 'remove' button on each row. Pressing the button would **remove** that row.

What we have at the moment is rather confusing - unless you plan on getting rid of the check boxes.

![image](https://user-images.githubusercontent.com/4060092/176137009-42b6599e-ec96-4132-a125-46f853c4a044.png)

**Comment by vomikan** [comment]
> But then that's no different from a user manually clearing the data in a row.

Exactly

**Comment by whalley** [comment]
Not sure how complete the implementation is now, but a few comments on MacOS presentation.

When opening the 'Split Transactions' dialog on an existing transaction with no splits I get

<img width="413" alt="CleanShot 2022-06-28 at 16 14 25@2x" src="https://user-images.githubusercontent.com/487345/176215933-cd0452a1-864f-4c18-bb21-c3b720e36ba2.png">

If I add an additional category and press 'Add Split' I get a scroll window with the new category... There is a lot of wasted space in the dialog. 

<img width="414" alt="CleanShot 2022-06-28 at 16 13 40@2x" src="https://user-images.githubusercontent.com/487345/176215814-fd4b541a-d04c-4245-be4d-48c3f81b28b9.png">

If I remove a split the category and amount gets cleared but the category combobox is dropped down with the list of selections.

<img width="413" alt="CleanShot 2022-06-28 at 16 17 08@2x" src="https://user-images.githubusercontent.com/487345/176216842-b567faf3-33cc-497a-b5a2-7820655fcdf3.png">

On reopening the space is filled but new splits result in a scroll window for the existing splits.

If the layout is complex and is causing this then perhaps put the 'Add Split' 'Remove Split' and totals at the top above the splits and create the scroll window to occupy all the space below. Not ideal I know.

**Comment by whalley** [comment]
I'll let you continue with the restructuring...... :-) I like the idea of disabling the row when removing, however (at least on MacOS) I get the dropdown as soon as it is removed/disabled. If this is a MacOS oddity then I'll look at it once you have finished your re-structure.

**Comment by vomikan** [comment]
> I get the dropdown as soon as it is removed/disabled.

It seems MAC specific issue,

**Comment by whalley** [comment]
> It seems MAC specific issue

Sorted.

**Comment by cmbarbu** [comment]
I just wanted to point out a very useful feature of the split transaction dialog that **still** exists in v1.5.16+, but that took me a while to realize how it is working in the new implementation. (In fact, I accidentally figured it out while preparing screenshots for a bug report... 😄)

Before 1.5.16, the dialog had a drop-down for specifying the transaction **type** (i.e. withdrawal or deposit).

![mmex-split-transaction-type](https://user-images.githubusercontent.com/1184162/176401988-c842aa04-48cb-4fbe-bfbb-8ee3433c1d53.PNG)

In 1.5.16+, this drop-down has been removed, but the functionality is retained. One simply needs to append a minus sign in front of "opposite" sub-transactions. In other words, a "-50" sub-transaction in a deposit transaction means a withdrawal of 50, **and vice-versa**.

![mmex-split-transaction-type-new](https://user-images.githubusercontent.com/1184162/176402015-3067fd74-0c36-4c1f-b99a-0cc818a95ac1.PNG)

There are occasional transactions where this distinction is useful, so thank you very much for keeping this in! And, hopefully, other people might stumble upon this message while looking for the drop-down in the new versions.

As a final suggestion, a tooltip explaining this when hovering over the amount box would probably be very useful.
