### ISSUE TITLE
Add new subcategory

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4714]
It seems the message incorrect. It should be "Enter the name for the new **sub**category"

![image](https://user-images.githubusercontent.com/6836805/175806217-3248301f-1d16-48ca-8c92-64dd4ff53c2d.png)

After subcategory added it should be in the focus.
![image](https://user-images.githubusercontent.com/6836805/175916530-d0cc9e43-3da3-4c9d-aaab-0f4d1832d20c.png)

**Comment by whalley** [comment]
> It seems the message incorrect. It should be "Enter the name for the new **sub**category"

The wording seems fine to me, and the same wording is used to add a top-level category or a sub-category. In both cases, the terminology "category" is adequate to describe this. I do not think it will cause any confusion.
