### ISSUE TITLE
Inconsistent behaviour when pressing Enter in transaction category field

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4717]
MMEX version:
 - [x] 1.5.16

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

As discussed in #4713, pressing Enter in an empty Category field in v1.5.16 is intended to open the Organise Categories dialog.

However, the behaviour is inconsistent (does not always work) and there are some focus bugs in that area too.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create a payee which does not have an associated category and one that does.

![image](https://user-images.githubusercontent.com/4060092/175811496-2e528463-3c80-43d7-9462-c2d128749d37.png)

Follow _all_ these steps **_exactly_** as written:

2. Confirm the expected behaviour:
2.1 Open the New Transaction dialog
2.2 Click in the blank Category field
2.3 Press Enter. The Organize Categories dialog is displayed **(Expected behaviour)**
2.4 Click cancel to dismiss the Organize Categories dialog

3. Demonstrate incorrect Category behaviour:
3.1 Click the down arrow in the Payee field and select No Cat Payee
3.2 Click in the blank Category field
3.3 Press Enter. The Organize Categories dialog is **not** displayed **(Incorrect behaviour)**

4. Demonstrate incorrect Category behaviour:
4.1 Click the down arrow in the Payee field and select Optician. The Healthcare:Eyecare category is filled in.
4.2 Click in the Category field and delete the Healthcare:Eyecare text.
4.3 Press Enter. The Organize Categories dialog is **not** displayed **(Incorrect behaviour)**

5. Demonstrate incorrect Split Transaction focus behaviour:
5.1 Following on from step 4.3, press Tab to tab the focus to the Split Transaction button
5.2 Click in the empty Category field to change the focus back to that field. The flashing text entry caret is in that field
5.3 Press Enter. Note that the Split Transaction dialog is displayed! **(Incorrect behaviour)**
5.4 Click Cancel on the Split Transaction dialog to dismiss it. Note that the Category field has been filled in again with Healthcare:Eyecare **(Incorrect behaviour)** 

6. Demonstrate incorrect Split Transaction focus behaviour:
6.1 Note that, following on from step 5.4, focus is in the Category field; the flashing text entry caret is in that field and, as expected, the Split Transaction button does not have focus
6.2 Press Enter. Note that the Split Transaction dialog is displayed! **(Incorrect behaviour)**
6.3 Click Cancel on the Split Transaction dialog to dismiss it. The Split Transaction button has focus.

Expected result:

1. Consistent behaviour regarding displaying the Organize Categories dialog when pressing Enter in the blank Category field.
2. Do not display the Split Transaction dialog when Enter is pressed and the Split Transaction button does not have focus.

Actual result:

As described in the reproduction steps.

# Additional information

I will be soon be making a proposal (issue #4713) which, if adopted would remove the Enter key behaviour in the Category field and may simplify the fixing of the above bugs.

**Comment by vomikan** [comment]
@tactilis could you, please, update the case?

**Comment by tactilis** [comment]
> I need a simple list of bugs without common explanations.

I don't know how to describe these bugs accurately without providing exact step by step instructions on how to reproduce them.

I have gone through steps 1 to 6 in https://github.com/moneymanagerex/moneymanagerex/issues/4717#issue-1284893237 using build v1.5.17-Beta.1 Jun 29 2022 07:19:35, commit 23abb49.

The previously incorrect behaviour at step 3 and 4 is now fixed :+1: 

The previously incorrect behaviour at step 5 and 6 has changed (not completely fixed). There is still a bug which causes the Split Transaction dialog to be displayed when it should not be :-1: 

I've set out below the exact steps to reproduce this bug (on Windows 7). It would be useful if @whalley could confirm the behaviour on macOS too.

1. Display the New Transaction dialog.
2. Left-click in the blank Category field.
3. Press Tab to move the focus to the 'Use split Categories' button (the button now has a highlight around it).
4. Left-click in the blank Category field. The 'Use split Categories' button no longer has a highlight around it.
5. Press Enter. The Organize Categories dialog is displayed.
6. Click Cancel. The Organize Categories dialog is dismissed. **The Split Transaction dialog is displayed** (**bug**)

**Expected result:** The Split Transaction dialog is not displayed at step 6.

**Actual result:** The Split Transaction dialog is displayed at step 6. This only happens if focus has been on the  'Use split Categories' button and then moved off that button.

**Additional information:** Similar behaviour occurs if at step 4 you left-click in the Payee field, step 5 press Enter, step 6 click Cancel on the Organize Payees dialog. **The Split Transaction dialog is displayed** (**bug**)

**Comment by whalley** [comment]
I can't reproduce it either on MacOS.

**Comment by tactilis** [comment]
I've done some further testing on Windows 7 and 10 - same behaviour on both.

There is definitely a problem with button focus, or the subsequent event handling, when the the Organize Categories dialog (or the Organize Payees dialog) is displayed by pressing Enter in the Category (or Payee) combo box and then cancelled, _after_ focus has previously been on another button.

In the videos above, I demonstrated the problem when I tabbed to the  'Use split Categories' button.

In the three videos below, I demonstrated the same problem when **tabbing** to:

1. The 'Populate Transact #' button
2. The 'Colours' button
3. The 'Organize Attachments' button
 
https://user-images.githubusercontent.com/4060092/176664065-dcc4c247-df67-4ec3-9875-e7ce28ebc777.mp4
 
https://user-images.githubusercontent.com/4060092/176664142-27d0e29e-7629-4cde-98f3-7da0afb0dd1b.mp4
  
https://user-images.githubusercontent.com/4060092/176664202-f4a712fa-5302-4c6c-8793-9d62c193fe33.mp4

It's impossible to believe that this bug is specific to my set-up because I observe it on two fresh (portable) installs of MMEX, on two different computers, on two different versions of Windows.

**Comment by whalley** [comment]
As noted, I can't reproduce on MacOS but have tried on my Win11-Arm VM and *can* reproduce... Must be something funny in the 'OnFocus()' handling.

**Comment by whalley** [comment]
There is some Windows-specific code that accounts for the differences. Have made a change that will hopefully avoid the event propagation anyway.

```
void mmTransDialog::OnCancel(wxCommandEvent& WXUNUSED(event))
{
#ifdef __WXMSW__
    if (object_in_focus_ != wxID_CANCEL && wxGetKeyState(WXK_ESCAPE))
            return m_button_cancel->SetFocus();

    if (object_in_focus_ != wxID_CANCEL) {
        return;
    }
#endif
```

**Comment by tactilis** [comment]
All fixed now. Thanks
