### ISSUE TITLE
Block Categories

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#4730]
I only post on subcategories. 
To avoid postinging on categories, it would be great if I can block them

**Comment by whalley** [comment]
What I'm suggesting is that we could present the list like below if the "Only use Categories where no sub-category exists" option is set. Note "Gifts" has no sub-categories so is presented.

![CleanShot 2022-06-27 at 20 02 40](https://user-images.githubusercontent.com/487345/176016311-fc172080-4e34-44a8-8e6a-59e35d0d0dbb.png)

**Comment by TomAff** [comment]
If I wann to use "Dental" I could Write the word in the old treeview. Now I habe to scroll down. It's not so comfortable

**Comment by whalley** [comment]
On MacOS you can type `*Dental` to filter the list. Not sure if WIndows autocomplete handles this.

**Comment by tactilis** [comment]
@whalley 
> What I'm suggesting is that we could present the list like below if the "Only use Categories where no sub-category exists" option is set. Note "Gifts" has no sub-categories so is presented.

That's definitely an option. Alternatively you could maybe look at the possibility of fixing (and extending) the existing Hide Category functionality (Gas and Maintenance are hidden):

![image](https://user-images.githubusercontent.com/4060092/176022680-5d3fd121-6ea3-4bfa-8d11-4d67ba8b868b.png)

This currently doesn't work with the new combobox list; hidden categories are still displayed (see Car:Gas and Car:Maintenance): 

![image](https://user-images.githubusercontent.com/4060092/176022987-47b59d07-bf19-43fc-a914-4bb92a3506f0.png)

And if you select Hide on a top level category, the entire sub-tree is hidden.

Just wondering whether we should still have this Hide/Unhide capability at all - or whether it could be extended to allow hiding of the top level categories but not the subs, which would give you what you are wanting to achieve.

**Comment by vomikan** [comment]
It is better to leave hiding categories until the next case is implemented:

https://github.com/moneymanagerex/moneymanagerex/issues/4216
