### ISSUE TITLE
Add profits to budget

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#4741]
Hi again,

I want to know if there is a way to set an estimation and real of profits on the budgets. I were using an Excel where on the beginning of the month I established a profits goal to help me saving some amount of money each month, since when I'm close to reach the goal I stop buying things than can wait or if a month I overpass the goal the next month I can compensate it.

So if this is already available, in the estimation you will set your goal, and with each transaction the real value will increase or reduce with the real profits. So if you have a goal of "100" and you have an income of "1000", the estimation will show "100" and the real "1000", but after that if you buy something for "500", the real will reduce to "500" too.

Other alternative would be automatically calculate the estimation with the established estimations (income estimated - expenses estimated = estimated profits).

_Originally posted by @BanCrash in https://github.com/moneymanagerex/moneymanagerex/discussions/4181_

**Comment by whalley** [comment]
@BanCrash  I'm not sure I fully understand what is being asked here.

Does the 'Income vs Expenses' / 'Monthly' report not help you track this, admittedly it does not include an 'estimated figure' but it will give you historical and current month views of income, expense, (income - expense), and a cumulative total.

So if your monthly goal was to grow income by "100" then you can see the current month status and have a view from previous months along with the cumulative view overtime.

**Comment by BanCrash** [comment]
@whalley currently I'm using that report, yeah, but it doesn't give the approach that I want. 

My point is that each month I set a goal basing of different circunstances (if I'm going to have a big expense on the next months, if I'm going to have more incomes than usual...), so yes the cumulative will tell me all the profits, but won't let me know what I really wanted to save each month. 

Year budget mockup:
![imagen](https://user-images.githubusercontent.com/11770760/189378349-4e933a79-502f-4dc8-9077-d836a687d383.png)

Month budget mockup:
![imagen](https://user-images.githubusercontent.com/11770760/189378284-1d517e3d-998e-4a4e-8b51-d0fb1b9528ea.png)

This is something that will also get boosted if/when #4214 gets added, but I don't think it's necessary to add that first to have this.

The difference with the report is that in the report you only see the real value, but you don't know what goal did you had for each month / the entire year, that's why I think adding to the budget would be very useful. Like I said on the original post, previously I was using an Excel where I have on each month set the saving goal, and then in the first page I have a table where I have all the goals for each months, the real obtained, and the percentage:

![imagen](https://user-images.githubusercontent.com/11770760/189380671-53c76574-a899-4a9e-97d1-835c8d466444.png)

With this Excel I forced myself to each month save a specific amount of money, and if one month for any reason I didn't achieve it then the next month I know that I have to save more than my already specificed amount in order to recover the 100% global percentage.

I don't know if I explained myself well since I find hard to talk about these matter in english ,let me know if something needs to be clarified.

**Comment by BanCrash** [comment]
@whalley I think that would be awesome, yeah!

**Comment by whalley** [comment]
Thinking about it further... I should take all the budget estimates, across all categories, for the given month and use this value rather than explicitly defining a 'Savings Goal' category. That makes more sense from a UI perspective and aligns with the current budget implementation.

**Comment by BanCrash** [comment]
> Thinking about it further... I should take all the budget estimates, across all categories, for the given month and use this value rather than explicitly defining a 'Savings Goal' category. That makes more sense from a UI perspective and aligns with the current budget implementation

That sound fine for me too :thumbsup:

**Comment by whalley** [comment]
@BanCrash Would the below meet your needs?

![CleanShot 2022-09-14 at 17 20 39](https://user-images.githubusercontent.com/487345/190209067-0f4e1e80-fff6-4f3c-91ea-c04035c4c36d.png)

**Comment by BanCrash** [comment]
> @BanCrash Would the below meet your needs?
> 
> ![CleanShot 2022-09-14 at 17 20 39](https://user-images.githubusercontent.com/487345/190209067-0f4e1e80-fff6-4f3c-91ea-c04035c4c36d.png)

Yes, that would be enough for me 👍

**Comment by whalley** [comment]
https://ci.appveyor.com/api/buildjobs/94b63eovbab4j2ml/artifacts/mmex-1.5.21-Beta.1-win64.exe

**Comment by BanCrash** [comment]
> https://ci.appveyor.com/api/buildjobs/94b63eovbab4j2ml/artifacts/mmex-1.5.21-Beta.1-win64.exe

Tested and seems to work fine, thank you!
