### ISSUE TITLE
Delete source category after relocation

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4748]
Need a similar function for categories.

![image](https://user-images.githubusercontent.com/6836805/176257585-c161e34d-f899-4893-9b76-ed66694c0270.png)

**Comment by whalley** [comment]
Fixed as part of https://github.com/moneymanagerex/moneymanagerex/issues/4749   https://github.com/whalley/moneymanagerex/commit/ce5de5d31d959b757c3e623e0a62c8bbfd9f12fe
