### ISSUE TITLE
Relocate Dialogs find entries when nothing specified

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4749]
The source payee/category is matching against existing transactions when no payee/category is specified.

![CleanShot 2022-06-28 at 20 18 08](https://user-images.githubusercontent.com/487345/176267186-ca684285-4183-4547-a4ad-67a765c39c18.png)

![CleanShot 2022-06-28 at 20 19 02](https://user-images.githubusercontent.com/487345/176267340-6db34490-36d8-4171-8b05-4074916630f1.png)

**Comment by vomikan** [comment]
I can't reproduce this.

**Comment by whalley** [comment]
Looking at the` relocatepayeedialog.cpp `code it will find PAYEEID = -1 which matches TRANSFERS, so it is picking these up. 

Not checked the relocatecategorydialog.cpp code yet.

**Comment by vomikan** [comment]
> it will find `PAYEEID = -1 `which matches TRANSFERS,

Really.

**Comment by vomikan** [comment]
Empty categories are probably split.

**Comment by whalley** [comment]
The empty category matches relate to the recurring transaction lookup and finding (-1,-1) when they have split transactions.  

Found the issues now, will fix.
