### ISSUE TITLE
wxWidgets 3.2.0

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4759]
https://www.wxwidgets.org/news/2022/06/wxwidgets-3.2.0-release-candidate/

wxWidgets 3.2.0 release candidate is now [available on GitHub](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.0-rc1). This release is not perfect (we might need a few more years for this), but if no catastrophic problems are discovered, it will soon officially become 3.2.0, starting the next ABI-stable release series – the first one since the release of 3.0.0 almost 9 years ago.

Please help us with testing this release by [reporting any problems](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.0-rc1), especially new ones, in it, so that we could still fix them before the final 3.2.0, without waiting for another decade to do it in 3.4.0. Thanks in advance!

Suggest we test all platforms against this to make sure we can flag any issues to the team prior to formal release....

Closing https://github.com/moneymanagerex/moneymanagerex/issues/4290 (3.1.7) and we should track any issues against 3.2.0-RC1 here.

**Comment by whalley** [comment]
No issues identified so far on MacOS.
![CleanShot 2022-06-30 at 09 20 24](https://user-images.githubusercontent.com/487345/176628809-2aaac30b-2ad3-4d07-b7dc-fd834576da1b.png)

**Comment by tactilis** [comment]
If a Windows build can be made available, I'm happy to test it.

Will the builds using wxWidgets 3.2.0 RC1 be separate from those using 3.1.5, or do you plan to simply switch the MMEX 1.5.17 Betas to wxWidgets 3.2.0 RC1?

**Comment by whalley** [comment]
Given past RC to final release cycles, it is probably only going to be a few weeks before formally issued (subject to any major issues being found). So my view is that we start running our betas on the 3.2.0 release candidate. If we want to revert back prior to our v1.5.17 release then we can do it, but it at least gives us better test coverage when we test the betas.

The quicker we get onto the 3.2.0 the better it will be for the packaged Linux builds as the Linux repos will start picking up this next stable release of wxWidgets.

@vomikan What do you think?

**Comment by whalley** [comment]
Hmmm, that did not seem to go well. Thought I had updated the version but the wxWidgets check failed. Not sure if it was because of the RC status in the version number as it seemed to work OK with x.x.x version numbers... Needs a bit more investigation.

**Comment by whalley** [comment]
Not quite sure what is going on with the build scripts and `wx3.2.0-rc1` ... Will have a look when I get a bit more time.

Revert build back to 3.1.5 for now!

**Comment by whalley** [comment]
Seems to be related to cmake - https://gitlab.kitware.com/cmake/cmake/-/issues/21544

**Comment by whalley** [comment]
Finally, after a short battle with this (and a quick education on how cmake modules work), I think we now have something usable. In summary:

- There is an issue recognizing the latest wxWidget versions (there is actually a hard-coded list in one of the cmake modules) - See https://gitlab.kitware.com/cmake/cmake/-/issues/21544
- An update to the cmake module has been made to make this a little more flexible, but it will only be made available in cmake 3.25, the AppVeyor build uses 3.16
- To work around this I have taken the updated module and override the lookup in CmakeLists.txt if we have cmake < 3.25

![CleanShot 2022-07-01 at 08 48 36](https://user-images.githubusercontent.com/487345/176849954-e80ada34-1041-42ab-873a-f436788cd5b6.png)

**Comment by renato-mmex** [comment]
So far I have not noticed any problems.

**Comment by XidRanReb** [comment]
Seems to have the same problem under Linux, the wxWidgets check failed.
I'll try to dig deeper when I have time.

**Comment by whalley** [comment]
@XidRanReb So long as you are building using CMakeLists.txt I updated then this should work. What is the error you are getting, have you re-built from scratch?

**Comment by PMaff** [comment]
The newest wxWidget 3.2.0.0 from the wxWidget trunk does not have the problem with the webview-sample.
But they asked me to open another ticket for the hanging assertion dialog in wxWidget 3.1.7 :
https://github.com/wxWidgets/wxWidgets/issues/22596

**Comment by PMaff** [comment]
We do have a compile error for the newest trunk version of mmex:
```
latest/moneymanagerex/src/mmSimpleDialogs.cpp:424:59: error: use of old-style cast to ‘class wxWindow*’ [-Werror=old-style-cast]
  424 |     wxWindow *dateCtrl = (wxWindow*) event.GetEventObject();
      |                                                           ^
      |                          -----------
      |                          static_cast<wxWindow*> (          )
cc1plus: some warnings being treated as errors
gmake[2]: *** [src/CMakeFiles/mmex.dir/build.make:608: src/CMakeFiles/mmex.dir/mmSimpleDialogs.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
...
gmake[1]: *** [CMakeFiles/Makefile2:442: src/CMakeFiles/mmex.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```
for:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.17-Beta.1
-- Commit         : 4462b1ac7 (2022-07-03)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.15.0-40-generic
-- Ubuntu 22.04 'jammy'
-- CMake 3.22.1
-- GNU Make 4.3
-- ccache 4.5.1
-- GNU 11.2.0
-- wxWidgets 3.2.0
-- wxSQLite3 4.6.0
-- RapidJSON 1.1.0
-- Lua 5.3.6
-- curl 7.81.0
-- gettext 0.21
```

**Comment by XidRanReb** [comment]
Yep, it's a fresh install, and it uses your CMakeLists.txt.
Maybe related to the snapcraft mecanism, I'll check that too

The error : 
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "2.9.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  util/FindwxWidgets.cmake:984 (find_package_handle_standard_args)
  CMakeLists.txt:296 (find_package)


-- Configuring incomplete, errors occurred!

```

**Comment by XidRanReb** [comment]
OK so based on @PMaff comment, it should work well.
The error probably comes from my build setup as I use the CMakeList. 
I'll check that !

The error was 
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "2.9.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  util/FindwxWidgets.cmake:984 (find_package_handle_standard_args)
  CMakeLists.txt:296 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by PMaff** [comment]
@XidRanReb what does your 
`wx-config --version-full`
say?

Did you use
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux
?

**Comment by XidRanReb** [comment]
Ok, a link to wx-config was broken, evreything's under control now ;)

**Comment by whalley** [comment]
Release Candidate 2 issued.

**Comment by tactilis** [comment]
All builds seem to be broken after the above wx v3.2.0-rc2 change

**Comment by whalley** [comment]
Yes, I jumped the gun!  The release has been tagged but not released yet! Reverted back :-)

**Comment by PMaff** [comment]
I do see "Latest Stable Release: 3.2.0" on https://www.wxwidgets.org/downloads/ .
Did you try that, @whalley or @vomikan ?

**Comment by PMaff** [comment]
> Ok, a link to wx-config was broken, evreything's under control now ;)

Maybe a config and compile from scratch would be good then.
;-)
I never had a broken link to wx-config.

**Comment by whalley** [comment]
> I do see "Latest Stable Release: 3.2.0" on https://www.wxwidgets.org/downloads/ . Did you try that, @whalley or @vomikan ?

Yes, did see it. We should adopt this.

**Comment by whalley** [comment]
All good on MacOS...
![CleanShot 2022-07-08 at 20 33 36](https://user-images.githubusercontent.com/487345/178058936-d7152dba-70e6-4538-8825-813d6c6bac09.png)

**Comment by XidRanReb** [comment]
> > Ok, a link to wx-config was broken, evreything's under control now ;)
> 
> Maybe a config and compile of that wxWidget version from scratch would be good then. ;-) I never had a broken link to wx-config. But let's see what 3.2.0 does.

Indeed I was talking about a snapcraft build which require specific care between different stages of build.

**Comment by whalley** [comment]
Looks fine on Win 11 also.
![CleanShot 2022-07-08 at 23 46 25](https://user-images.githubusercontent.com/487345/178079265-595dfeea-c2d9-47a9-8d9f-ad5e3defe96c.png)

**Comment by MartinX3** [comment]
Runs fine on Arch Linux

```
Version: 1.5.16 64-bit
• Aufbauend auf Juli 14 2022 22:26:25
• Datenbankversion: 7 • (aes128cbc)
• Git commit: 9d7ca6e2b (2022-06-23)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.0 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.3.1
• libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0
• gettext 0.21
• apexcharts.js
Genutztes Build:
• CMake 3.23.2
• GNU Make 4.3
• GCC 12.1.0 • EndeavourOS rolling 'rolling'
Läuft auf:
• EndeavourOS Linux "rolling"
• Linux 5.18.10-zen1-1-zen x86_64
• German (Germany) (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by PMaff** [comment]
There are problems with Wayland and wxWidget 3.2 with Ubuntu 22.04 on a Virtual Machine:
https://github.com/moneymanagerex/moneymanagerex/issues/4724#issuecomment-1193201713

I guess, if the webview sample of wxWidget 3.2 does not work, parts of mmex will also not work.

**Comment by PMaff** [comment]
I do have a solution for the problem with Wayland and wxWidget 3.2.0.
Sort of.
The webview sample of wxWidget 3.2 did not work - empty white panel and
`** (webview:76811): WARNING **: 00:47:02.808: GDK is not able to create a GL context, falling back to glReadPixels (slow!): Unable to create a GL context`
as error message.
That lead me to
https://bugs.launchpad.net/ubuntu/+source/evolution/+bug/1966418
and
"Workaround #1

You can run the app from the command line with
WEBKIT_DISABLE_COMPOSITING_MODE=1 evolution
(Replace evolution with the name of the webkit app you are trying to use)"

So 
`[...]wxWidget/3.2.0/wxWidgets/build-release-gtk3$ WEBKIT_DISABLE_COMPOSITING_MODE=1 samples/webview/webview`
works for Wayland but it is not a very elegant solution.

@whalley : shall I create a new ticket for this issue?

**Comment by whalley** [comment]
> @whalley : shall I create a new ticket for this issue?

Yes, we should create a ticket for this.
