### ISSUE TITLE
Aggregation in sum field broken

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#4767]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I can't write 10+10 anymore. It becomes `10,00`

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open an entry
2. Write 10 + 10

Expected result:
20,00

Actual result:
10,00

# Additional information

N/A

**Comment by whalley** [comment]
Sure we fixed this here: https://github.com/moneymanagerex/moneymanagerex/issues/4716

Are you using the latest beta?

**Comment by MartinX3** [comment]
No, I use 1.15.16 and didn't find this issue ticket by searching before. xD

**Comment by whalley** [comment]
No problem, thanks for confiming.
