### ISSUE TITLE
Default category for transfers

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4779]
It is usual to use a single category for Transfers, in my case I use "Transfer", as such we should support a default when creating new transactions. I suggest introducing a default as below that would be used when a Transfer is selected. Possibly want to rename the existing setting to make it clear it only applies when Payees (Withdrawals//Deposits) are present.

![CleanShot 2022-07-04 at 11 37 48@2x](https://user-images.githubusercontent.com/487345/177138758-5e554b47-c65f-4413-a000-2c9600d76d7a.png)

**Comment by tactilis** [comment]
I've just looked at your fix.

In billsdepositsdialog.cpp (and I presume transdialog.cpp) you have:

``` 
   else if (m_transfer && m_new_bill
                    && Option::instance().TransCategorySelectionTransfer() == Option::LASTUSED)
    {
        Model_Checking::Data_Set transactions = Model_Checking::instance().find(
            Model_Checking::TRANSCODE(Model_Checking::TRANSFER, EQUAL)
            , Model_Checking::TRANSDATE(wxDateTime::Today(), LESS_OR_EQUAL));
```

This selects the latest (in a date-wise sense) transaction that is dated today (or earlier) and then uses that category for the transfer.

It does not select the 'last used' (in the sense of the last _entered_) transfer category.

So if you enter transactions out of order (i.e. later transactions and then earlier ones), then the code will not give you the 'last used' category, rather it will give the most recent (date-wise) category.

The same applies to the look up of the 'last used' payee.

None of this may really matter; but it seems that Last Used may turn out not to be the last category/payee that the user actually entered.



So, if you are entering some older transfers (earlier date than the latest transaction

**Comment by gabriele-v** [comment]
It may be get too complex, but what about a third option (or even change last used) to matches the account pair?

I have a global "Transfer" category, but under that I have "ATM Withdrawals", "ATM Deposit" etc.. in this case the last used for example for the pair FROM:BankXXX TO:Cash would be ATM Withdrawals, while FROM:Cash  TO:BankXXX would be ATM Deposit

**Comment by whalley** [comment]
> It may be get too complex, but what about a third option (or even change last used) to matches the account pair?
> 
> I have a global "Transfer" category, but under that I have "ATM Withdrawals", "ATM Deposit" etc.. in this case the last used for example for the pair FROM:BankXXX TO:Cash would be ATM Withdrawals, while FROM:Cash TO:BankXXX would be ATM Deposit

I did choose a global context for the "Transfer Last Used"  in that it searches for the last category found for a transaction across all accounts working back from today. For the "Deposit/Withdrawal Last Used" it does search based on the  account.

Thinking about it I can change the "Transfer Last Used" to do the same, as it would have no material effect if you used a global default.   

> It does not select the 'last used' (in the sense of the last entered) transfer category.

Correct it uses 'last used' chronologically starting from today. This has always been the case so I don't suggest changing it.

**Comment by gabriele-v** [comment]
> I did choose a global context for the "Transfer Last Used" in that it searches for the last category found for a transaction across all accounts working back from today. For the "Deposit/Withdrawal Last Used" it does search based on the account.
> 
> Thinking about it I can change the "Transfer Last Used" to do the same, as it would have no material effect if you used a global default.

Problem is that we would need an additional field on accounts table, otherwise is a mess to store them in infotable..
Better to leave as is I think.

**Comment by whalley** [comment]
> Problem is that we would need an additional field on accounts table, otherwise is a mess to store them in infotable..
> Better to leave as is I think.

No, I was thinking it just searches for the last used category for a transfer in the account. But I now see that you want which would not work. In theory, we could search for the last account/toaccount pair and use that otherwise use the last category for transfer in the account. But perhaps now getting a bit messy for minimal gain.

**Comment by gabriele-v** [comment]
You are right, the additional field may not be needed, but it will require much more complex lookup code
