### ISSUE TITLE
User interface scaling too tiny on high DPI devices

### ISSUE THREAD

**Issue by vaxul** [moneymanagerex/moneymanagerex#478]
Hi,

I'm new to this project. I really like to test this software. Unfortunately, it's hardly usable on my primary device.

Is it possible to help you fixing this issue?

Screenshots from Lenovo Yoga 2 Pro with Money Manager EX v1.1.2 with:
- 3200 x 1800 pixels
- Windows 8.1
- 250% scaling (by default)

![screenshot 8](https://cloud.githubusercontent.com/assets/3798226/7665712/1b82218a-fbc5-11e4-8d91-20c827b093f1.png)
Tiny texts and icons.
![screenshot 9](https://cloud.githubusercontent.com/assets/3798226/7665759/192c0ab6-fbc7-11e4-8f04-2af21dbf0955.png)
Windows with fixed widths. Is not possible to scale this edit windows.

Best regards,

vaxul

**Comment by dwrj87** [comment]
If you go to Tools>Options>View Options>HTML Scale Factor, and increase it's value

**Comment by vaxul** [comment]
> If you go to Tools>Options>View Options>HTML Scale Factor, and increase it's value

There is no such option. Only an option for "Report Font Size"

**Comment by dwrj87** [comment]
Deleted my comment before you replied because I realised it was wrong :)

**Comment by vomikan** [comment]
Font scaling feature will be available in v. 1.3.0.
But it's seems icons scaling needed.
17 мая 2015 г. 14:30 пользователь "David Jones" <notifications@github.com>
написал:

**Comment by dwrj87** [comment]
Ah, I run off of the development version.

Will the icons scale OK or does the resolution need increasing?

**Comment by vomikan** [comment]
IMHO scaled icons will be looks bad. But i'll try.
Seems we need more icons 24*24, 32*32 as minimum.
Better to have svg icons then transform them into png -> xpm.
Best solution is used svg icons. Not sure if wxWidgets support it.

N.
17 мая 2015 г. 14:46 пользователь "David Jones" <notifications@github.com>
написал:

**Comment by dwrj87** [comment]
Here are the dimensions of the current images

about.xpm	XPM	16x16
accounttree.xpm[1]	XPM	16x16
addacctwiz.xpm[2]	XPM	116x260
appstart.xpm[3]	XPM	16x16
art.xpm[4]	XPM	14x16
assets.xpm[5]	XPM	16x16
attachment.xpm[6]	XPM	16x16
calendar.xpm[7]	XPM	16x16
card_acc_closed.xpm[8]	XPM	16x16
card_acc_favorite.xpm[9]	XPM	16x16
card_acc.xpm[10]	XPM	16x16
car.xpm[11]	XPM	16x16
categoryedit.xpm[12]	XPM	16x16
cat.xpm[13]	XPM	16x16
chartpiereport.xpm[14]	XPM	16x16
checkupdate.xpm[15]	XPM	16x16
clearlist.xpm[16]	XPM	16x16
clock.xpm[17]	XPM	16x16
coin.xpm[18]	XPM	16x16
customsql.xpm[19]	XPM	16x16
delete_account.xpm[20]	XPM	16x16
dog.xpm[21]	XPM	16x16
downarrow_red.xpm[22]	XPM	16x16
downarrow.xpm[23]	XPM	16x16
duplicate.xpm[24]	XPM	16x16
edit_account.xpm[25]	XPM	16x16
empty.xpm[26]	XPM	16x16
encrypt_db_edit.xpm[27]	XPM	16x16
encrypt_db.xpm[28]	XPM	16x16
error.xpm[29]	XPM	16x16
exit.xpm[30]	XPM	16x16
facebook.xpm[31]	XPM	16x16
filter.xpm[32]	XPM	16x16
flag.xpm[33]	XPM	16x16
general_report_manager.xpm[34]	XPM	16x16
google_play.xpm[35]	XPM	16x16
help.xpm[36]	XPM	16x16
hourglass.xpm[37]	XPM	12x16
house.xpm[38]	XPM	16x16
issues.xpm[39]	XPM	16x16
leds.xpm[40]	XPM	16x16
magic_wand.xpm[41]	XPM	16x16
main-setup.xpm[42]	XPM	48x48
mmexico.xpm[43]	XPM	32x32
mmex.xpm[44]	XPM	32x32
moneyaccount.xpm[45]	XPM	16x16
money_dollar.xpm[46]	XPM	16x16
money_euro.xpm[47]	XPM	15x16
money.xpm[48]	XPM	400x209
newacct.xpm[49]	XPM	16x15
new_transaction.xpm[50]	XPM	16x16
new.xpm[51]	XPM	16x16
notify.xpm[52]	XPM	16x16
open.xpm[53]	XPM	16x16
preferences-attachments.xpm[54]	XPM	48x48
preferences-network.xpm[55]	XPM	48x48
preferences-other.xpm[56]	XPM	48x48
printpreview.xpm[57]	XPM	16x16
printsetup.xpm[58]	XPM	16x16
print.xpm[59]	XPM	16x16
reconciled.xpm[60]	XPM	16x16
relocate_categories.xpm[61]	XPM	16x16
relocate_payees.xpm[62]	XPM	16x16
rightarrow.xpm[63]	XPM	16x16
rt_exec_auto.xpm[64]	XPM	16x16
rt_exec_user.xpm[65]	XPM	16x16
rubik_cube.xpm[66]	XPM	15x16
saveas.xpm[67]	XPM	16x16
save.xpm[68]	XPM	16x15
savings_acc_closed.xpm[69]	XPM	16x16
savings_acc_favorite.xpm[70]	XPM	16x16
schedule.xpm[71]	XPM	16x16
stock_acc_closed.xpm[72]	XPM	16x16
stock_acc_favorite.xpm[73]	XPM	16x16
stock_acc.xpm[74]	XPM	16x16
term_acc_closed.xpm[75]	XPM	16x16
term_acc_favorite.xpm[76]	XPM	16x16
termaccount.xpm[77]	XPM	16x16
tipicon.xpm[78]	XPM	16x16
trans_from.xpm[79]	XPM	16x16
trans_into.xpm[80]	XPM	16x16
trash.xpm[81]	XPM	12x16
trees.xpm[82]	XPM	15x16
unreconciled.xpm[83]	XPM	16x16
uparrow.xpm[84]	XPM	16x16
update_currency.xpm[85]	XPM	16x16
user_edit.xpm[86]	XPM	16x16
view.xpm[87]	XPM	48x48
void.xpm[88]	XPM	16x16
web_money.xpm[89]	XPM	16x16
web.xpm[90]	XPM	16x16
work.xpm[91]	XPM	16x14
wrench.xpm[92]	XPM	16x16
yandex_money.xpm[93]	XPM	16x16

**Comment by vomikan** [comment]
All small icons are 16*16 (if smaller than 16*16 it should be fixed).



воскресенье, 17 мая 2015 г. пользователь David Jones написал:

**Comment by vaxul** [comment]
> Btw, 1.2 is the latest version https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.2.0

Current version on the main page is 1.1.2:
http://www.moneymanagerex.org/

But sure, I could try the latest git master.

> Font scaling feature will be available in v. 1.3.0.

Does this have any effect to the wizard windows (f.e. new transaction) too? Elements like the dropdowns are too small to display the content. (see 2nd screenshot in the initial post)

**Comment by vomikan** [comment]
Font scaling only for html (reports and homevpage).
I've missed second screenshot. Will investigate this issue for dripdown
menu as well.

воскресенье, 17 мая 2015 г. пользователь vaxul написал:

**Comment by vomikan** [comment]
I think the Panel Icons may be scaled or recreated for 32x32 size.
![32x32](https://cloud.githubusercontent.com/assets/6836805/7683140/c8f05cda-fd85-11e4-8f18-7cae99003c05.png)

**Comment by vomikan** [comment]
Now it looking 
![UI](https://pbs.twimg.com/media/CRw5ooFUkAAqyjm.png)

Still need idea how to increase wx fonts.

**Comment by vomikan** [comment]
May be this will help http://docs.wxwidgets.org/trunk/classwx_window.html#acd955418c336e73b3e32cadf1ca46e29

**Comment by vomikan** [comment]
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6345

Apparently a number of other software applications are also having problem scaling in high DPI displays. The workaround described [here](http://www.danantonielli.com/adobe-app-scaling-on-high-dpi-displays-fix/) worked beautifully for MMEX on the Surface Pro 4. The site also explained what caused the problem. It is a workaround so ultimately the application has to be fixed.

http://www.danantonielli.com/adobe-app-scaling-on-high-dpi-displays-fix/

**Comment by guanlisheng** [comment]
@vomikan would you close this ?

**Comment by vomikan** [comment]
No. There are a lot of scaling issues. Or it may be closed as 'accepted'.

понедельник, 22 февраля 2016 г. пользователь Lisheng написал:

**Comment by vomikan** [comment]
http://winaero.com/blog/how-to-fix-apps-that-look-small-on-high-dpi-and-high-resolution-displays/

**Comment by vomikan** [comment]
https://msdn.microsoft.com/en-US/en-en/library/ms235229.aspx

**Comment by vaxul** [comment]
https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update/

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/bugs/953/

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/bugs/953/attachment/money.jpg

**Comment by slodki** [comment]
Could anybody retest it with wxWidgets 3.1.0?

>wxWidgets 3.1.0 has been released today, as planned, and can be downloaded from GitHub. As for the last couple of releases, we provide binaries for the selected Windows compilers (Microsoft Visual C++ and MinGW-TDM) in addition to the source downloads.
>
>As always, there were too many new features and bug fixes to list them all here, please see the change log for the fuller list but, briefly, the main changes in this release are:
>
> * Better support for high DPI displays, especially under Windows.
>
>[...]

**Comment by slodki** [comment]
From wxWidgets [Roadmap](http://trac.wxwidgets.org/wiki/Roadmap):
> we plan to release 3.1.2 in June 2018, with 3.2.0 following before the end of the year.
>
> One of the big planned changes for this 3.2 is **better support for high DPI displays**, but there are, of course, many, many other fixes and improvements in it as well.

**Comment by vomikan** [comment]
wxWindow::SetWindowVariant()

**Comment by slodki** [comment]
[wxWindow::FromDIP()](https://docs.wxwidgets.org/3.1/classwx_window.html#aa934a31552633c076a87bca1100b0dc5) with example

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?f=23&t=47111
https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests?redirectedfrom=MSDN
