### ISSUE TITLE
Math operations don't work anymore

### ISSUE THREAD

**Issue by Stef-Feanx** [moneymanagerex/moneymanagerex#4783]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Math operations in the amount field doesn't work in 1.5.16
Verified on 3 different computers.
Addition, substraction of a number still display the first amount tha was already in the field.
Have to go back to 1.5.15 to make it work again.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. edit a field with 100.00 diplayed
2. write "-5" after, clic "enter"
…

Expected result: "95"

Actual result: "100"

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Fixed https://github.com/moneymanagerex/moneymanagerex/issues/4716
