### ISSUE TITLE
Report Category including all sub-categories

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4789]
See: https://forum.moneymanagerex.org/viewtopic.php?t=10626

Hi,
I updated the application but there is no longer the possibility to extract the report including subcategories.

before there was the flag to indicate to take into account all subcategories

![image](https://user-images.githubusercontent.com/487345/177500395-86b9af84-2912-4bff-a1e0-cee1df27e474.png)

**Comment by whalley** [comment]
This is where the use of regular expressions is needed. It is not very obvious to users.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4618

**Comment by vomikan** [comment]
We can return the checkbax as it was before. If there is a checkbox is checked then add .* to the search text, if this line corresponds to a category from the list (Otherwise, the query string can be considered a regular expression.).
In principle, it is not a complicated fix.

**Comment by renato-mmex** [comment]
I would also welcome this checkbox back.
Lately I have the impression that the usability of MMEX suffers because of the not self-explanatory new options.

**Comment by vomikan** [comment]
It's definitely better than it was!
