### ISSUE TITLE
(German) language strings "out of sync"?

### ISSUE THREAD

**Issue by vaxul** [moneymanagerex/moneymanagerex#479]
I found wrongly spelled german translations in the "usage statistic" options.
![screenshot 10](https://cloud.githubusercontent.com/assets/3798226/7665998/dca94404-fbd1-11e4-9c12-2ef877821115.png)
It is spelled "Benutzungsstatistik" with an "u" instead of the umlaut "ü".
But it's odd, that this translation is fixed but not merged from the [Launchpad (number 951)](https://translations.launchpad.net/mmex/trunk/+pots/moneymanagerex/de/+translate?batch=10&show=all&search=usage).
Even more odd is, that the tooltip description from the checkbox is wrong spelled in Lunchpad (number 953) but correct in the current build (v1.1.2).

Best regards,

vaxul

**Comment by vomikan** [comment]
We just include translation from the forum: http://forum.moneymanagerex.org/viewforum.php?f=6&sid=8f449bd5c260f449ba508f76a7443a62. In future will used web interface like Crowdin.
