### ISSUE TITLE
Odd Window positioning behaviour (MacOS)

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4791]
When re-opening MMEX the application recognizes that it can fit into one of the attached monitors and then opens in the X,Y position *BUT* it opens at another location. In addition to opening on the wrong display, the toolbar then has additional margin padding

![CleanShot 2022-07-06 at 17 06 32](https://user-images.githubusercontent.com/487345/177620950-4752e43e-d4af-4e78-806b-72e161d5434b.jpeg)

On my setup the windows are reported as:
```
screen 0: x:0, y:25, w:1680, h:969, fit:false, primary:true
screen 1: x:-918, y:-1415, w:3440, h:1415, fit:false, primary:false
screen 2: x:-3478, y:-1415, w:2560, h:1415, fit:true, primary:false
```

In reality, the screens are laid out as:
![CleanShot 2022-07-06 at 19 31 06](https://user-images.githubusercontent.com/487345/177621276-87ac5aff-eea6-4337-bd58-b17d2215f3cf.jpeg)

The saved position that the application is trying to recover to is:

`saved dimensions : x:-3087, y:-1232, w:1850, h:993, maximized:false`

this should restore to screen 2 but actually restores across screens 0 and 1, as shown below in yellow
![CleanShot 2022-07-06 at 19 31 06](https://user-images.githubusercontent.com/487345/177622284-1d9e194d-bd2b-478f-ac4e-6ac8c6904e46.jpeg)

Needs a bit of investigation....

**Comment by whalley** [comment]
Tried re-ordering logical screens to be one continuous row..

```
saved dimensions : x:5331, y:-157, w:1431, h:802, maximized:false
screen 0: x:0, y:25, w:1680, h:1025, fit:false, primary:true
screen 1: x:1680, y:-365, w:3440, h:1352, fit:false, primary:false
screen 2: x:5120, y:-365, w:2560, h:1415, fit:true, primary:false
current dimensions : x:851, y:-157, w:1431, h:802, maximized:false
```

...but same result

As soon as the mmGUIFrame is created with (x:5331, y:-157, w:1431, h:802), I check the Window size via:
```
app->m_frame = new mmGUIFrame(app, mmex::getProgramName(), wxPoint(valX, valY), wxSize(valW, valH));
int x,y,w,h;
app->m_frame->GetPosition(&x,&y);
app->m_frame->GetSize(&w,&h);
wxLogDebug("mmGUIFrame: %d,%d,%d,%d", x,y,w,h);
```
but get:
`Debug: mmGUIFrame: 851,-157,1431,802`

**However......**
If I do this
```
app->m_frame = new mmGUIFrame(app, mmex::getProgramName(), wxPoint(valX, valY), wxSize(valW, valH));
wxPoint point(valX, valY);
app->m_frame->SetPosition(point);
```
The window is correctly placed, **but** the toolbar still has extra padding. Something must be screwing up in mmGUIFrame of wxFrame that is causing this odd positioning and sizing.

...the quest continues.

**Comment by whalley** [comment]
Only way I could find of fixing the toolbar padding issue, which only seemed to appear on retina Mac screens was to change wxToolBar to wxAuiToolBar, which seemed the right way to go anyway.

@vomikan Can you please check for no ill effects on Windows.

**Comment by tactilis** [comment]
@whalley

 First run on Windows 7:
  
![image](https://user-images.githubusercontent.com/4060092/178038730-727ceb40-8517-4ffd-a594-b896e4ae1866.png)

**Comment by tactilis** [comment]
The toolbar seems to be set to a height appropriate for Toolbar icon size: Huge

![image](https://user-images.githubusercontent.com/4060092/178039428-ab332f7a-f672-4951-b6f5-fb9204b6bb5c.png)

**Comment by tactilis** [comment]
Note that detaching the toolbar sets height correctly... until it is reattached

https://user-images.githubusercontent.com/4060092/178039936-e65348d6-a22c-4353-a7fb-e534815b661d.mp4

**Comment by whalley** [comment]
Hoping this will fix it...
`    toolBar_->SetToolBorderPadding(1);`

On MacOS...
![CleanShot 2022-07-08 at 19 35 03](https://user-images.githubusercontent.com/487345/178050795-c96d5053-f8c5-4fa8-8bcd-b2c131f53f6f.png)

**Comment by whalley** [comment]
Put on hold until wxWidgets team can comment on the window positioning.

**Comment by tactilis** [comment]
@whalley
> Hoping this will fix it...   toolBar_->SetToolBorderPadding(1);

Yep. All good under Win 7 now.

**Comment by tactilis** [comment]
Sorry, I spoke too soon.

The toolbar no longer occupies the full width of the main window. 

 
![image](https://user-images.githubusercontent.com/4060092/178063054-e1cbb811-bafa-4a32-9115-e780e92c13eb.png)
 
 
The toolbar background colour used to run across the entire width, which looks better than the above

**Comment by whalley** [comment]
Having the toolbar sized to fit the tools allows it to be moved to the right if needed and allows us to add another toolbar if needed, e.g for access to reports or whatever.

**Comment by tactilis** [comment]
OK. Understood.

**Comment by whalley** [comment]
wxWidgets team have fixed the window positioning error, so we can pick up in next wxWidgets release.... https://github.com/wxWidgets/wxWidgets/commit/5c5d5f524b2bc21a7681ad1ea4b5e2395dcea427

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5100

**Comment by whalley** [comment]
Confirmed. Fixed in wx3.2.1.
