### ISSUE TITLE
Catagorey and sub cat check box in transection filter

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#4805]
# Description of the feature
Currently when you choose a category in report field , you can not include sub category. I would like to see a checkbook to include sub Cat.
Thanks
Ashok
Please describe your feature with details.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4789
