### ISSUE TITLE
Make Payee optional

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#481]
We have a request from users to make the Payee an optional field on transactions. The Category is required and that is usually enough.
This would cover simple scenarios where users only want to track spending per category, not going more detailed to provide every Payee.

What would be the consequences?

Linked item: 
https://github.com/moneymanagerex/android-money-manager-ex/issues/278

**Comment by guanlisheng** [comment]
i think one default payee is enough.

**Comment by dwrj87** [comment]
I think the request is more on the lines of not having to enter a payee. At the moment, you have to enter one

**Comment by MisterY** [comment]
I looked at the technical side. It should not be a big deal to implement. Transfers, for example, have no Payee, so there is already a case like this.
I believe disabling the validation would be all that is needed. The reports already handle empty payee field correctly.

**Comment by vomikan** [comment]
I vote to disable validation.

среда, 20 мая 2015 г. пользователь Alen Siljak написал:

**Comment by aquirin** [comment]
Same for me, I vote to disable validation or have an option to always use the same default payee, configurable in the options.
