### ISSUE TITLE
Multi-transaction update of Payee Name causes "Payee Error"

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#4813]
Select two or more transactions, right click and choose Edit to perform a multi-transaction update.  Click the Payee checkbox and select a new Payee from the drop down box. After clicking OK, 'Payee Error' displays in the transaction list and on reports and is blank when subsequently clicking edit.

![image](https://user-images.githubusercontent.com/95182117/178973638-71c0c915-f9d1-4a3b-b13c-22f837eb8d33.png)

![image](https://user-images.githubusercontent.com/95182117/178973334-b4109136-7233-448b-91db-c03f26223368.png)

![image](https://user-images.githubusercontent.com/95182117/178974165-abc60ff8-6418-4b13-a7dd-e92a3f90c897.png)

<hr>Version: 1.5.17-Beta.1 64-bit<br>
 • Build: Jul 10 2022 08:58:17<br>
 • db 7 •  (aes128cbc)<br>
 • git 18f394b (2022-07-10)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  English (United States) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Also, in the Multi Transactions Update dialog:

1. Pressing Enter in the Payee field does not open the Organize Payees dialog. It should do so.
2. Pressing Enter in the Category field does not open the Organize Categories dialog. It should do so.

**Comment by rmelillo76** [comment]
Thank you @vomikan and @tactilis ! I see it now works correctly in the latest 1.5.17 dev build. I also confirmed pressing enter now opens each dialog when the values are empty.
