### ISSUE TITLE
List buttons are greyed out

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#4814]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Lists like account, from, category have a grayed out arrow button until I empty its text.
I assume because the `autocompletion` delivers no entries except the prefilled one until I modify its text field.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Using lists with prefilled text fields

Expected result:
The arrow button should open the complete list after I open a dialog.

Actual result:
It's greyed out.

# Additional information
```
Version: 1.5.16 64-bit
• Aufbauend auf Juli 14 2022 22:26:25
• Datenbankversion: 7 • (aes128cbc)
• Git commit: 9d7ca6e2b (2022-06-23)

MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.0 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.3.1
• libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0
• gettext 0.21
• apexcharts.js

Genutztes Build:
• CMake 3.23.2
• GNU Make 4.3
• GCC 12.1.0 • EndeavourOS rolling 'rolling'

Läuft auf:
• EndeavourOS Linux "rolling"
• Linux 5.18.10-zen1-1-zen x86_64
• German (Germany) (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by vomikan** [comment]
>Lists like account, from, category have a grayed out arrow button until I empty its text. I assume because the autocompletion delivers no entries except the prefilled one until I modify its text field.

When solving case #4625, we changed the algorithm. Now the full list is loaded only when the wxComboBox is in focus. I.e. you need to move the cursor to it. Perhaps it works differently on the Linux platform.

**Comment by vomikan** [comment]
How it's working on Windows 10
https://user-images.githubusercontent.com/6836805/179211586-f02ae3f7-a80a-44ab-82de-29653812ef55.mp4

**Comment by MartinX3** [comment]
@vomikan did you test it with prefilled text fields?

**Comment by vomikan** [comment]
> @vomikan did you test it with prefilled text fields?

No. As I wrote earlier, the list is filled in when you click (change focus) on the arrow on the right, which is part of the xwComboBox.  It looks like this arrow is an add-on in Linux.

**Comment by MartinX3** [comment]
With filled I mean it's already selected with a previously choose value as example in the filter or if I open an entry.

**Comment by vomikan** [comment]
> With filled I mean it's already selected with a previously choosed value as example in the filter or if I open an entry.

I can't understand this sentence.

It would be great if you could build a program with the fix I provided.

**Comment by gabriele-v** [comment]
> With filled I mean it's already selected with a previously choosed value as example in the filter or if I open an entry.

I've understood what you mean and on Windows is working fine, so it's something Linux specific
