### ISSUE TITLE
Attachments file name missing

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#4815]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
When adding an attachment, the default attachment name should be the file name, instaed now it's empty

# Reproduction
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Pick the file "test.txt" and add as attachment

Expected result:
It should propose "test" as attachment name

Actual result:
Attachment name is empty

# Additional information
Involved line is this one: https://github.com/moneymanagerex/moneymanagerex/blob/501abc65342b2ef48bfc6f1d7ceec8f69935f781/src/attachmentdialog.cpp#L171

But it hasn't been changed in 5 months, so the problem is probably a change in mmDialogComboBoxAutocomplete which is not handling anymore the defaultText parameter: https://github.com/moneymanagerex/moneymanagerex/blob/501abc65342b2ef48bfc6f1d7ceec8f69935f781/src/mmSimpleDialogs.cpp#L583

**Comment by vomikan** [comment]
Could you add the screenshot, please?
Ans step by step instructions for reproduce this issue.

**Comment by gabriele-v** [comment]
Maybe later, but look at the second piece of code and you understand easily. Default Text is a function parameter but it's never used

**Comment by vomikan** [comment]
It looks like a fix, but I don't see in practice what has changed.
![image](https://user-images.githubusercontent.com/6836805/179220157-5c843fef-2142-4b04-8101-da47b2d0802a.png)

**Comment by gabriele-v** [comment]
First use case:
- Adding a new attachment, I pick the invoice.txt file
![image](https://user-images.githubusercontent.com/7106290/179222624-39a3e3f8-354d-419a-8f60-ddbcc614ef6a.png)
- Attachment description is empty
![image](https://user-images.githubusercontent.com/7106290/179222691-dddfb059-7c16-4c4b-ab73-cb54dda37012.png)
Before it was showing the FileName (in this case "invoice")

Second use case:
- Renaming an attachment (old description was "Fattura")
![image](https://user-images.githubusercontent.com/7106290/179222882-126fe737-ef9c-4137-a567-c073e1286783.png)
- New description is empty
![image](https://user-images.githubusercontent.com/7106290/179222994-5febd05b-113f-4c8a-a166-47cc6a769eed.png)
Before it was showing the "old" Description (in this case "Fattura")

Not sure it it's used somewhere else.


By the way the change that have broken it is from this:
https://github.com/moneymanagerex/moneymanagerex/blob/e7bb96ccc91c23afc375d575589e1098e4f15a3c/src/mmSimpleDialogs.cpp#L489
to this
https://github.com/moneymanagerex/moneymanagerex/blob/9d7ca6e2bf1789691f9d30243650971a6a1f03d8/src/mmSimpleDialogs.cpp#L417
So not sure but maybe the best approach would be to add the default in mmComboBoxCustom

**Comment by gabriele-v** [comment]
@vomikan sorry to bother again about this issue, but looks like that at least on Windows the text is not in focus anymore.
Default is working, but focus is somewhere outside so you cannot type directly.

Thanks
