### ISSUE TITLE
Transaction filter 'broken' in v1.5.17 64-bit on Win7pro

### ISSUE THREAD

**Issue by git29jet** [moneymanagerex/moneymanagerex#4826]
> Tried to recreate a transaction filter report that I had successfully completed in v1.5.16. Resulting screen contained NO results.
Actions taken - after trying fewer 'condition' settings in filter setup dialog and getting NO results I reverted to v1.5.16. Report produced as before update. 
Original filter settings = specific CC account; date range 6/14-7/16-22; Category= food:groceries; type: withdrawal; group by: payee
Observation- transaction filter report works correctly in v1.5.16 but does not work in v1.5.17.
BTW- I have NOT experienced crash of v1.5.16 on my win7 pro 64-bit system
> Please do not remove information attached below this text.

<hr>Version: 1.5.16 64-bit<br>
 • Build: Jun 23 2022 13:19:39<br>
 • db 7 •  (aes128cbc)<br>
 • git 9d7ca6e (2022-06-23)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
See: https://github.com/moneymanagerex/moneymanagerex/issues/4843
