### ISSUE TITLE
Options fields fit if resized

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#4827]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Not urgent and only esthetic, but I think these three fields should enlarge and fit to options window if resized:

![image](https://user-images.githubusercontent.com/7106290/179461086-a1d244bb-67b0-48bb-9e1e-037ef0005625.png)
![image](https://user-images.githubusercontent.com/7106290/179461179-b92e0526-a0e4-4fba-803e-0cf5c123a08a.png)

PS: it was probably my fault, because I've added these fields in the past :)

**Comment by whalley** [comment]
Just spotted I missed the attachments dialog. Now corrected
