### ISSUE TITLE
Decimals in transaction dialog

### ISSUE THREAD

**Issue by Joker2k** [moneymanagerex/moneymanagerex#483]
Variable m_currency which first inited correctly in mmTransDialog::mmTransDialog constructor get erroneously overwritten in mmTransDialog::onFocusChange (called by mmTransDialog::CreateControls again from constructor). This leads to forcing currency to BaseCurrency in transaction dialog.

**Comment by vomikan** [comment]
I think best solution would be to ignore all currencies setting except base
currency. In that case user will have thecdame input method for all
accounts and all doalogues.

вторник, 19 мая 2015 г. пользователь Joker2k написал:

**Comment by thePanz** [comment]
I can confirm this bug (see also: http://sourceforge.net/p/moneymanagerex/bugs/682/)

**Comment by thePanz** [comment]
Any news on this issue? Using two credit accounts with different currencies is problematic now!

**Comment by vomikan** [comment]
As workaround - make used currensies settings the same

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/659
