### ISSUE TITLE
Last Used Category is not filled in when selecting Payee from Organize Payees Dialog

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#4838]
MMEX version:
 - [x] 1.5.17

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Reproduction steps:**
1. Create a new transaction and position the cursor into the Payee field.
2. Press Enter to open the Organize Payee dialog.
3. Select a payee from the list that contains a Last Used Category. Double click or press OK to select the item.
4. The dialog closes and the Payee is populated on the new transaction, but the category remains empty.

**Expected result:**
The Category field should populate the appropriate category from the selected payee.,

**Actual result:**
The Category field is empty.

**Comment by tactilis** [comment]
Related issue #4836

**Comment by nungon** [comment]
After upgrading to 1.5.17 and 1.5.18 it does not keep the last category for a given payee. Instead it selects another payee never used before, so you have to select it manuall once and again for the same payee. It worked fine until 1.5.17

**Comment by schmidthappens4** [comment]
I was/am experiencing this issue as well and just upgraded to the latest version (1.5.18 64-bit) (portable version) and the issue is still occurring.
