### ISSUE TITLE
Same currency in advanced transaction dialog

### ISSUE THREAD

**Issue by Joker2k** [moneymanagerex/moneymanagerex#484]
textAmount_ and toTextAmount_ transaction dialog fields are using the same currency m_currency, which in fact is not how it suppose to do with advanced option in my opinion.

**Comment by vomikan** [comment]
It's to avoid different mask usage in one dialogue.
For example
USD->EUR
1.25 -> 1,11

вторник, 19 мая 2015 г. пользователь Joker2k написал:
