### ISSUE TITLE
Cash Flow reports settings

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4840]
There are hard coded time diapason for Cash Flow Daily report like one year and 10 years for monthly report.
We can increase the convenience by using the same widget as it was just done for the CashFlow Transactions report. #4830

![image](https://user-images.githubusercontent.com/6836805/179722380-39dd90f3-03ab-4dd2-8101-43216c61ef84.png)

**Comment by whalley** [comment]
I was planning, as part 2 of https://github.com/moneymanagerex/moneymanagerex/issues/4830, to make the reports a bit more consistent. Using the same field to set the range is a good idea.

**Comment by whalley** [comment]
Fixed alongside https://github.com/moneymanagerex/moneymanagerex/issues/4830
