### ISSUE TITLE
No category when transfer transaction

### ISSUE THREAD

**Issue by camposFabio** [moneymanagerex/moneymanagerex#4841]
Version: 1.5.17 64-bit
• Construir em Jun 30 2022 14:31:06
• Versão do Banco de Dados:7 • (aes128cbc)
• Git commit: 1559b0d21 (2022-06-30)
O MMEX está usando os seguintes produtos de suporte:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.3.1
• libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0
• gettext 0.21
• apexcharts.js

Build using:
• CMake 3.23.2
• GNU Make 4.3
• GCC 12.1.0 • Arch rolling

Running on:
• Arch Linux "n/a"
• Linux 5.18.12-arch1-1 x86_64
• Portuguese (Brazil) (UTF-8)
• 0x0 0bit 96x96ppi

Problem:
When inserting an Transfer type transaction the category field of the destination account is not filled:

![image](https://user-images.githubusercontent.com/40764894/179807687-b563e062-b4de-4b81-9f6a-e567371fb5c6.png)

**Comment by tactilis** [comment]
You are not running the release version of 1.5.17.  You are running 1.5.17 Beta, despite what the Version info says

Yours version was built on 30 June.

1.5.17 was not released until 17 July.

Unfortunately, there was a bug for a short while where some of the 1.5.17 Beta versions were incorrectly labelled as 1.5.17. See #4808

Please update to the release version.

**Comment by camposFabio** [comment]
Fixed with last 1.5.17 source. Thanks
