### ISSUE TITLE
Transaction Report - no data

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4843]
https://forum.moneymanagerex.org/viewtopic.php?t=10634

**Comment by whalley** [comment]
I've just noticed that the start date keeps reverting back to today.

**Comment by whalley** [comment]
![CleanShot 2022-07-20 at 11 13 39@2x](https://user-images.githubusercontent.com/487345/179958198-017ff67b-787d-47d4-90c1-db65d021dfeb.png)

**Comment by whalley** [comment]
Need to hold my hands up here on this one. When I re-implemented the date control in the mmSimpleDialogs.cpp file I did not pass the event on when handling so the OnDateChanged event was not being passed back to the main application. Think that is *part* of the cause of the issue. However, there seems to be another issue with saving/recovering the date start/end.
