### ISSUE TITLE
"Empty" Transaction Report

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#4844]
# Description of the feature
When pressing "Transaction Report" in the navigation tree, it opens the transaction filter with the first saved setting loaded.
If the click comes from "Transaction Report" item, it would be useful to open it empty and maybe without the request to save when executed.

# Use cases
I have saved reports which I open regulary, but sometimes I'd like to generate a quick report just once to double check something.
In this case is a bit painful to clean all the filters/columns etc.. that I have on the first setting and especially remember to don't save it to don't override the saved one.

**Comment by whalley** [comment]
Yes, now we have easy access to the saved transactions from the tree view this seems a reasonable suggestion.

**Comment by renato-mmex** [comment]
I have saved a report with **.empty** it always appears in the first place, so default
