### ISSUE TITLE
Wrong category selected for existing payee

### ISSUE THREAD

**Issue by Paul343412** [moneymanagerex/moneymanagerex#4853]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [] 1.5.16
 - [ ] 1.5.17 Beta
 - [ x 1.5.17] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

when entering a new transaction for an existing payee, the category was remembered and pre-loaded.  Now a random or no category is picked up.  The link between payee and category has been broken.

If I look in the list of payees, the default categories are correct, so it is not a problem with the categories listed for payees, but the way the new dialogue box works

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  select an account
2.  select new to add a transaction
3. select an existing payee
4. note that the category displayed is incorrect
5. note also that the drop down list has changed to category:sub category rather than choose one then the other

…

Expected result:
default category is presented

Actual result:
some other category is presented
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
#4838 #4836
