### ISSUE TITLE
Nuova operazione - categorie

### ISSUE THREAD

**Issue by GinoPari** [moneymanagerex/moneymanagerex#4859]
Quando si inserisce una nuova operazione, le categorie vengono visualizzate non raggruppate ma in un lungo elenco ed è alquanto scomodo andare a cercare la categoria interessata. Questo malfunzionamento si è verificato dopo aver installato l'aggiornamento alla versione 1.5.17 64-bit

<hr>Version: 1.5.17 64-bit<br>
 • Build: Lug 17 2022 13:24:17<br>
 • db 7 •  (aes128cbc)<br>
 • git 0dba2ea (2022-07-17)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Translation:

> when inserting a new operation, the categories are displayed not grouped but in a long list and it is somewhat uncomfortable to go looking for the category concerned.this malfunction occurred after installing the update to version 1.5.17

@GinoPari 

1. In the Category field, start typing a few letters of the name of the category and a filtered list will be displayed

or

2. Press the Enter key in the blank Category field and the Organize Categories dialog will be displayed

**Comment by renato-mmex** [comment]
In english:
When entering a new task, the categories are displayed not grouped but in a long list, and it is somewhat inconvenient to go searching for the relevant category. This malfunction occurred after installing the update to version 1.5.17 64-bit

Maybe this will help: https://github.com/moneymanagerex/moneymanagerex/discussions/4834
