### ISSUE TITLE
Installation error ver 1.5.17

### ISSUE THREAD

**Issue by tycariadus** [moneymanagerex/moneymanagerex#4860]
MMEX version:
 - [x] 1.5.17
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

Please describe your issue with details.
Trying to install new version, works as normal then error as per attached occures and if you ignore, the installation looks okay but version 1.5.16 is still there

![Screenshot 2022-07-24 095908](https://user-images.githubusercontent.com/36563561/180639983-ad9ccd88-e9a0-4586-b1cc-bd323712c5d3.jpg)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@tycariadus
Try un-installing your existing version of MMEX first, then installing 1.5.17.

Please report here if the error remains or is gone.

**Comment by tycariadus** [comment]
Already tried that and got the same error

**Comment by tactilis** [comment]
This may be a permissions problem, i.e. not specific to MMEX/

After uninstalling, is the folder C:\Program Files\Money Manager EX\bin empty?

After uninstalling, are you able to reinstall 1.5.16? Or does the problem now affect that version as well?

**Comment by vomikan** [comment]
It's like being blocked by an antivirus.

https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.5.17/mmex-1.5.17-win64-portable.zip

Inside the archive in the bin folder there is also this file. If it is deleted when unpacking, then it's definitely a matter of antivirus.

If it unpacks without problems, then you can run bin\mmex.exe

**Comment by tycariadus** [comment]
Noted but never happened before so what's the solution?

**Comment by tycariadus** [comment]
Thanks - all solved.  The bin was not empty so deleted all files and
reinstalled.

 

Cheers


Simon
