### ISSUE TITLE
Integer and Decimal custom fields are treated like Strings in the Account view

### ISSUE THREAD

**Issue by f-hansen** [moneymanagerex/moneymanagerex#4868]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Values of custom integer and decimal fields are all displayed left-aligned. Sorting on these fields is also lexical instead of numeric.

# Screenshots

![b1](https://user-images.githubusercontent.com/53111364/180671579-640ca8d4-28d7-41ea-b60b-189173d0336d.png)

![b2](https://user-images.githubusercontent.com/53111364/180671592-5340cfdd-bfbe-48ac-9025-0aaf1a7e124c.png)

**Comment by tactilis** [comment]
It should also be noted that:

1. In the normal account transaction lists (i.e. bank, term, share, asset), the ID field is left aligned. As it is a numeric value, it should be right aligned.
 
![image](https://user-images.githubusercontent.com/4060092/186854534-45f1c404-84b5-4a5f-a041-27aca7e4b724.png)

2. For Investment accounts (Stocks), the ID field and the Share Total field are already right aligned:

![image](https://user-images.githubusercontent.com/4060092/186854907-b4f1b81c-ead6-4563-b863-b5716eb8545f.png)

3. For Recurring Transactions, the ID field _is_ right aligned but the Payments Left / Repetitions fields are left aligned. They should be right aligned.
 
![image](https://user-images.githubusercontent.com/4060092/186855959-fe89017a-fb18-48b5-b970-2926e42eca30.png)

**Comment by whalley** [comment]
The transaction report also needs updating for the DECIMAL and INTEGER custom fields so that they can be correctly presented and sorted.

**Comment by tactilis** [comment]
@whalley
Alignment looks good everywhere now with the exception of the Integer and Decimal custom field headings on the Transaction Report:

![image](https://user-images.githubusercontent.com/4060092/187020237-05af3aae-9b4b-4a2d-9c2b-0fcad572b38c.png)

And maybe ID too?

**Comment by whalley** [comment]
Annoyingly I did spot that when coding the other changes, but forgot about it!
