### ISSUE TITLE
Custom field designated as UDFC01 does not appear in the Account view

### ISSUE THREAD

**Issue by f-hansen** [moneymanagerex/moneymanagerex#4869]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

While UDFC02 designations and up appear just fine in the account view, UDFC01 does not.

# Screenshots

![c1](https://user-images.githubusercontent.com/53111364/180671710-c353a0cf-5e30-4c46-bd77-f0c26f72be94.png)

![c2](https://user-images.githubusercontent.com/53111364/180671718-f890c53d-91c5-4d08-9f28-9baa4b42a011.png)

**Comment by whalley** [comment]
I can't reproduce this. Are you sure you have the field selected for view?
![CleanShot 2022-07-25 at 08 54 33](https://user-images.githubusercontent.com/487345/180726856-7419a155-ef35-4610-b4dd-9e8bc74bf2fb.png)

**Comment by f-hansen** [comment]
@whalley Well, don't I feel stupid! You are correct. I'm sorry about this.
