### ISSUE TITLE
Just part of tooltip is shown

### ISSUE THREAD

**Issue by Jurkis** [moneymanagerex/moneymanagerex#487]
Open stocks report "Last 30 days".
Move mose over the last day stock price.
Tooltip with date and price is open, but it's hidden behind vertical scrollbar.

![hiddentooltip](https://cloud.githubusercontent.com/assets/8310079/7720699/fb33140e-fed8-11e4-8141-fd08b6306231.png)

**Comment by guanlisheng** [comment]
Great catch 

LiSheng

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/493
