### ISSUE TITLE
Allow notes in Split Category transactions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#488]
We have several requests from the users, and I also believe it can be useful sometimes and is a part of QIF specification, to have separate Notes for each of the Split Categories.

Linked issue in the mobile version: https://github.com/moneymanagerex/android-money-manager-ex/issues/253

**Comment by MisterY** [comment]
More requests from the users.

**Comment by vomikan** [comment]
In my opinion we can use json in a notes field.

**Comment by guanlisheng** [comment]
close this since we are planning to fix this via #709
