### ISSUE TITLE
Use for CircleCI for pipeline builds

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4880]
I have been looking at the use of CircleCI for pipeline builds... So far I have:
1. Created CircleCI account 
2. Created Docker images for Ubuntu Bionic, Focal, and Jammy, including the OS, build tools and wxWidgets 3.2.0 build (currently on Docker Hub under whall3y/mmex)
3. Created a simple circleci/config.yml file that will build MMEX for the above Linux OS variants and wxWidgets

To do:
1. ~~Add to standard MoneyMangerEx PR processing (needs GitHub admin permissions to do this)~~
2. Add docker images to standard moneymangerex/* images (needs Docker Hub permissions for this)
3. ~~Add more Linux builds~~
4. ~~Add Windows Build (or we might want to stick with Appveyor for this to keep the diversity of build systems)~~
5. ~~Add MacOS Build~~
6. Tidy-up build scripts (sure we can make it more elegant), and look to make use of caching to improve efficiency and reduce minute consumption

I will need some help to create the docker images for other Linux distributions and to test the created images

**Comment by whalley** [comment]
Latest builds can be seen here: https://app.circleci.com/pipelines/github/whalley/moneymanagerex?branch=master

**Comment by whalley** [comment]
Docker Images: 
![CleanShot 2022-07-28 at 19 48 08](https://user-images.githubusercontent.com/487345/181614873-e0c38d5a-ba12-49de-989a-5e161c5093d5.png)

**Comment by whalley** [comment]
Have removed the dependency on wx3.2-i18n from these builds. Would be good to get some wider testing on these to check if they are really needed. As discussed here: https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1191435935

**Comment by whalley** [comment]
To do:

Add to standard MoneyMangerEx PR processing (needs GitHub admin permissions to do this)
Add docker images to standard moneymangerex/* images (needs Docker Hub permissions for this)
Add more Linux builds
Add Windows Build (or we might want to stick with Appveyor for this to keep the diversity of build systems)
~~Add MacOS Build~~
Tidy-up build scripts (sure we can make it more elegant), and look to make use of caching to improve efficiency and reduce minute consumption

**Comment by PMaff** [comment]
@whalley : some questions:
1) is this some kind of Jenkins + Online Build chain?
2) are you building all that on a Wayland Jammy Ubuntu?
I ask because I will not go for Wayland when I will update to Ubuntu 22.04 in the future as there is no XFCE support
for Wayland. So I will stick to X11 and it would be good to have a possibility to build for the Wayland alternative.

**Comment by whalley** [comment]
> @whalley : some questions:
> 
> 1. is this some kind of Jenkins + Online Build chain?

In essence, yes... See: https://circleci.com/docs/about-circleci

> 2. are you building all that on a Wayland Jammy Ubuntu?
>    I ask because I will not go for Wayland when I will update to Ubuntu 22.04 in the future as there is no XFCE support
>    for Wayland. So I will stick to X11 and it would be good to have a possibility to build for the Wayland alternative.

Basically, we build a container for the OS with all the tools to build MMEX, including WXWidgets 3.2. This is the run, MMEX repo clones, and then built.

You can see the content of the containers here: https://hub.docker.com/r/whall3y/mmex/tags

Basically it takes the standard ubuntu image on docker hub (e.g. https://hub.docker.com/_/ubuntu?tab=tags)
and then runs the following to install needed tools and build wxWidgets
```
apt update 
apt install -y --no-install-recommends cmake build-essential libssl-dev gettext git pkg-config lsb-release file ccache libgtk-3-dev liblua5.3-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev wget unzip
apt clean
cd /
wget --no-check-certificate https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.0/wxWidgets-3.2.0.zip
unzip -d wxWidgets wxWidgets-*.zip
rm wxWidgets-*.zip
cd wxWidgets
mkdir build-linux
cd build-linux
../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl
make
```

The CircleCI config is here: https://github.com/moneymanagerex/moneymanagerex/blob/master/.circleci/config.yml
```
version: 2.1
jobs:
  build-linux:
    machine: true
    steps: 
      - run:
          name: Checkout code
          command: |
            cd $CIRCLE_WORKING_DIRECTORY && \
            git clone --recurse "$CIRCLE_REPOSITORY_URL" .
      - run:
          name: Build DB headers and prepare to build
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/src/db && \
            python ../../util/sqlite2cpp.py ../../database/tables_v1.sql && \
            rm -f sql*.sql *.mmdbg && \
            python ../../util/sqliteupgrade2cpp.py ../../database && \
            cd ../.. && \
            mkdir build && \
            mkdir -p /tmp/artifacts
      - run: 
          name: Build MoneyManagerEx (Ubuntu Jammy Jellyfish)
          command: |
            docker run -it --rm -w /moneymanagerex/build -v $HOME/.ccache:/root/.ccache -v $CIRCLE_WORKING_DIRECTORY:/moneymanagerex whall3y/mmex:ubuntu-jammy bash -c "rm -rf * && cmake -DwxWidgets_CONFIG_EXECUTABLE=/wxWidgets/build-linux/wx-config -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target package" && \
            cp $CIRCLE_WORKING_DIRECTORY/build/mmex_*.deb /tmp/artifacts
      - run: 
          name: Build MoneyManagerEx (Ubuntu Focal Fossa)
          command: |
            docker run -it --rm -w /moneymanagerex/build -v $HOME/.ccache:/root/.ccache -v $CIRCLE_WORKING_DIRECTORY:/moneymanagerex whall3y/mmex:ubuntu-focal bash -c "rm -rf * && cmake -DwxWidgets_CONFIG_EXECUTABLE=/wxWidgets/build-linux/wx-config -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target package" && \
            cp $CIRCLE_WORKING_DIRECTORY/build/mmex_*.deb /tmp/artifacts
      - run: 
          name: Build MoneyManagerEx (Ubuntu Bionic)
          command: |
            docker run -it --rm -w /moneymanagerex/build -v $HOME/.ccache:/root/.ccache -v $CIRCLE_WORKING_DIRECTORY:/moneymanagerex whall3y/mmex:ubuntu-bionic bash -c "rm -rf * && cmake -DwxWidgets_CONFIG_EXECUTABLE=/wxWidgets/build-linux/wx-config -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target package" && \
            cp $CIRCLE_WORKING_DIRECTORY/build/mmex_*.deb /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
  build-macos:
    macos:
      xcode: 13.4.1
    steps: 
      - run:
          name: Checkout code
          command: |
            pwd && \
            git clone --recurse "$CIRCLE_REPOSITORY_URL" .
            mkdir -p /tmp/artifacts
      - run:
          name: Build MoneyManagerEx (MacOS) - Just build x86_64 architecture as part of CI
          command: |
            pwd && \
            brew install ccache gettext cmake curl pkg-config wxwidgets@3.2 && \
            mkdir build-cocoa && \
            cd build-cocoa && \
            cmake -DCMAKE_CXX_FLAGS="-w" -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10  .. && \
            cmake --build . --target package && \
            cp *.dmg /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  mmex-builds:
    jobs:
      - build-linux
      - build-macos
```

We can setup the Linux build environment however we want by tweaking the docker images.

**Comment by PMaff** [comment]
I will test your mmex_1.5.19-Beta.1-1~jammy_amd64.deb (rename it to mmex_1.5.19-Beta.1-1~jammy_amd64_fromCircleCI.deb ) now on Jammy 22.04 with Wayland.

**Comment by PMaff** [comment]
I cleaned wxWidget (uninstall does not remove some directories :-( ).
I recompiled wxWidget 3.2.0 from github with your
`../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl`
instead of my:
`build-release-gtk3$ ../configure --disable-shared --enable-stl --enable-utf8only --enable-intl  --enable-xlocale  --enable-webviewwebkit --with-gtk=3`
to see if there is some error with my config, but still I get the same 2 errors (assertion and non-closeable About-dialog).

I will now try the wxWidget zip file.

**Comment by whalley** [comment]
Thanks for the testing. At this point in time, all I can do is await somebody who can successfully build this on 22.04 then we can replicate that in the build system.

**Comment by PMaff** [comment]
The next step will be recompiling wxWidget 3.2.0 and the latest mmex on Jammy with X11 and then we see, if the errors are
there also.
Building works on Ubuntu 22.04, but these strange errors would be bad, if they also occur on X11.
I do hope this is only a matter of Wayland. When simply using the Ubuntu 22.04 system there are also certain issues, that are
strange for me: e.g. sometimes I cannot copy text and then paste it with middle mouse, something that always works with
XFCE + X11. I do have the impression, that it was too early to adopt Wayland for Ubuntu.

**Comment by whalley** [comment]
Linux builds reverted to wx3.1.7 https://github.com/moneymanagerex/moneymanagerex/issues/4895

**Comment by whalley** [comment]
Added Fedora 36 build... would be good if somebody could test.

**Comment by zurabashan** [comment]
On my Fedora 36:
It's trying to change language to system locale. I don't know why. In options I configured English (US) because in my native language mmex has bad translation.
When I try to run updated mmex i's show me the error:
![изображение](https://user-images.githubusercontent.com/4153182/183132795-de3ee817-5e09-4ef2-bd18-b608b05ca390.png)
After pressing "OK" nothing happens.

If I kill app by pid and start again - no any errors (even if start it from terminal) or windows with errors and/or with mmex app itself.

If I downgrade app (I have 1.5.14 rpm package) - it runs with my system locale language.

**Comment by PMaff** [comment]
@whalley or someone else: can you check, if on a Wayland system with Ubuntu 22.04 the wxWidget 3.1.7 also makes problem?
Please check on a real installed system since I am not sure if my VirtualBox does something wrong here.
See:
https://forum.moneymanagerex.org/viewtopic.php?p=23266#p23266

**Comment by PMaff** [comment]
> The next step will be recompiling wxWidget 3.2.0 and the latest mmex on Jammy with X11 and then we see, if the errors are there also. 

Ubuntu 22.04 + X11 with wxWidget 3.2.0 and mmex 1.5.18 seems to work.
So it seems to be only Wayland + wxWidget 3.2.0 / 3.1.7 that produces errors.

**Comment by whalley** [comment]
> > The next step will be recompiling wxWidget 3.2.0 and the latest mmex on Jammy with X11 and then we see, if the errors are there also.
> 
> Ubuntu 22.04 + X11 with wxWidget 3.2.0 and mmex 1.5.18 seems to work. So it seems to be only Wayland + wxWidget 3.2.0 / 3.1.7 that produces errors.

Track this issue here: https://github.com/moneymanagerex/moneymanagerex/issues/4895

**Comment by PMaff** [comment]
https://app.circleci.com/pipelines/github/whalley/moneymanagerex/95/workflows/2a0305b9-a6bf-463a-a588-ecf159ec524d/jobs/167
:-)
Is a `export MAKEFLAGS=-j4` prossible? It looks a bit slow.

That
`/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.8, needed by /usr/lib64/gcc/x86_64-suse-linux/12/../../../../lib64/libwebkit2gtk-4.0.so, may conflict with libjpeg.so.62`
is something I also had on Suse once. I have to check how I got rid of it...

Is that 1hrs limit something which you can enlarge without paying?
It looks as if the build failed because of that limit.
Maybe use 
`make -j8 ` for wxWidget
`MAKEFLAGS=-j4 ` for mmex?

**Comment by whalley** [comment]
Yep, not really took much notice of the times before. Will update to use full cpu's. The wxWidget build is fine that is done before uploading to docker hub, and the image is just downloaded as part of the build.

**Comment by PMaff** [comment]
That looks much better:
https://app.circleci.com/pipelines/github/whalley/moneymanagerex/96/workflows/20d4383c-f4ae-4af4-8134-2483b9083346/jobs/168

**Comment by whalley** [comment]
Needs a bit more tidying on build naming, but that is a minor issue.

**Comment by PMaff** [comment]
> On my Fedora 36: It's trying to change language to system locale. I don't know why. In options I configured English (US) because in my native language mmex has bad translation. When I try to run updated mmex i's show me the error: ![изображение](https://user-images.githubusercontent.com/4153182/183132795-de3ee817-5e09-4ef2-bd18-b608b05ca390.png) After pressing "OK" nothing happens.
> 
> If I kill app by pid and start again - no any errors (even if start it from terminal) or windows with errors and/or with mmex app itself.
> 
> If I downgrade app (I have 1.5.14 rpm package) - it runs with my system locale language.

I do have a similar dialog on the Ubuntu 20.04 from https://moneymanagerex.org/docs/downloads/latest/
with mmex 1.5.20 : 

![Ub2004_1_5_20message](https://user-images.githubusercontent.com/93879362/190270263-f6de4206-e221-44c9-b05d-2cf3ea05f9d0.jpg)

I did not change the language before and only updated from 1.5.14 to 1.5.20 .

**Comment by whalley** [comment]
Added CircleCI download instructions to MMEX website. https://moneymanagerex.org/docs/downloads/development/#i-classfa-brands-fa-linuxinbsplinux

**Comment by whalley** [comment]
Going to close this now. We have the docker images and we have the CircleCI builds running for each PR. Any further linux builds and fixes should be covered by new issues.

Before we formally publish any new linux builds we need:

- Docker image for the build environment that includes the support wxWidgets build
- Updated to CircleCI.yml file to build
