### ISSUE TITLE
Search consistency for Payee and Category dialog

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#4885]
# The New Transaction dialogue box has the ability to search when opening up the Payee. I would like the Category to have the same search ability.

The new feature with wildcards available in the Payee Dialogue box is a game changer! The Category Dialogue should be consistent and have the same search ability!

As an additional. most users are unaware that hitting enter opens up this dialogue box. (as there is a down arrow shown indicating mouse click) Why not put a Red or Green shape near the rectangle indicating across all 'like' boxes that Enter is a function too!

If not obvious, explain the use cases or problems to solve.
![Payee Search Box](https://user-images.githubusercontent.com/14268231/181655459-6add61e2-14c2-461b-9cd9-2db74036ea1d.jpg)
![Category no search available](https://user-images.githubusercontent.com/14268231/181655465-29956dec-88b7-42ba-a939-3d0ce160a3dc.jpg)
![Eneter Feature request](https://user-images.githubusercontent.com/14268231/181656136-e3c87d42-5760-4694-9b14-e611bf2a10ac.jpg)

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4247

**Comment by SJK55** [comment]
whalley, that does sound like a good idea. https://github.com/moneymanagerex/moneymanagerex/issues/4607

Additional to my original request for consistency with search in the dialogue boxes applies to the top line icons where Organize Categories and Organize Payees differ in that Payees has a search box. Categories doesn't. I find sometimes I know I created a sub category but can't remember where it was or if I've store the same 'type' in two different places.  See attached images
![Organize Categories - No Search Function](https://user-images.githubusercontent.com/14268231/181713038-b05b747b-fdda-4be2-82c5-f627584109d8.jpg)
![Orgainze Payees with search function](https://user-images.githubusercontent.com/14268231/181713059-1c25ba61-c376-4a3b-b4bd-da976163ec66.jpg)
.

**Comment by tactilis** [comment]
> SJK55: I find sometimes I know I created a sub category but can't remember where it was or if I've store the same 'type' in two different places.

It would help if typing in the Category combobox (in the Transaction dialog) to produce a filtered list of categories would search for the entered text _anywhere_ in the category:subcategory text instead of just matching at the beginning of the category text.

IMO, this matching should be done without requiring the use of wildcards

**Comment by SJK55** [comment]
I totally agree. This is a feature of the Android version. Very handy! (But I can't run Android version on one tablet (Samsung) and support is nil for that project - development stopped a few years ago ) (Sorry I digress) Yes the search would be AI intuitive.
