### ISSUE TITLE
After you have relocated a Payee successfully (confirmed) the dialogue box should clear from screen.

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#4887]
MMEX version:
 - [X ]1.5.18 64 Bit

Operating System:
 - [x] Windows 11

# After completing Relocation of Payee no 'success' or anything really confirms it has happened. The only way to exit is 'Cancel'

Relocate Payee should show success or end the dialogue box upon completion. Having Cancel as the option seems incorrect like you are not wanting to complete the action. (like a negative response)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Top icon 'Human' open
2. Pick a Name
3. Right Mouse click for options
4. Pick Relocate Payee
5. 5. Click in the to. (maybe capitalize the 'T'?
6. Pick the 'to' Payee
7. Click Delete source payee after relocation
8. Click OK.  Please confirm box comes up. Which you click 'Ok'
9. Only Cancel is highlighted at completion.
10.  As you already confirmed relocation, why this dropping back to the previous dialogue appears. The confirmation should finalise the request. 

…

Expected result:
When acknowledge re-allocation Dialogue box and it's parent disappear.

Actual result:
Parent Dialogue box is displayed with Cancel only option to clear from screen.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![Relocate fault 2](https://user-images.githubusercontent.com/14268231/181716688-500b03a8-0edc-4739-8add-e3811192aae6.jpg)
![Relocate fault](https://user-images.githubusercontent.com/14268231/181716696-697e293b-b09a-4169-b7c1-36b90bbfe1e0.jpg)

**Comment by tactilis** [comment]
> I suggest renaming the buttons on both dialogs to "Relocate" and "Exit"

"Relocate" and "Close".

"Exit" should be reserved for closing the entire application
