### ISSUE TITLE
Import dialog / Appearance of the list of templates

### ISSUE THREAD

**Issue by Korb** [moneymanagerex/moneymanagerex#4899]
The radio switches with numbers without other signatures are completely incomprehensible. There is neither the name of the block that includes these controls, nor a tooltip. The usual (normal, habitual) way is the creation of profiles, which the user himself assigns names. And they are selected from the drop-down list, be it one or dozens.

![2022-08-03_12-31-19](https://user-images.githubusercontent.com/3509797/182575457-9efae7fd-1c8f-4916-a270-4799e8872a9c.png)

**Comment by whalley** [comment]
Yes, this can be improved...

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/745

**Comment by Korb** [comment]
> #745

Yes, I first found the topic you mentioned, but then I found that it refers to another place in the application - export and import of application settings. Although the topics are related: similar entities should look similar.

**Comment by Korb** [comment]
> Please update if you want to keep the issue open

bump

**Comment by whalley** [comment]
@Korb  Isn't this now resolved? See latest 1.7.0 release candidate 
![CleanShot 2023-12-24 at 13 18 59](https://github.com/moneymanagerex/moneymanagerex/assets/487345/45e9c007-ed65-4701-9fbd-617ff2493a69)
