### ISSUE TITLE
Add Tag/Project field to account transactions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#490]
There is a user request to add Project field to the transactions, for easier grouping, reporting, etc.
We might consider adding Tags, for example, that could be used for this or any similar purpose. In this thread we could analyze the consequences.

**Comment by vomikan** [comment]
I recommend to use the 'number' field for this or the 'notes' field.
But this request is suggested very often.
Seems special table with tags should be added.

четверг, 21 мая 2015 г. пользователь Alen Siljak написал:

**Comment by MisterY** [comment]
Tags can be extremely helpful if one is doing anything but the very straightforward scenarios. I'm getting this request often from people who want to migrate from other apps.
Not having this pretty much excludes MMEX from their list of choices, which is unfortunate considering how simple this concept really is.
Examples of situations that requires tagging would be tracking income from the same Payee that are received for business or personal reasons; tracking Fuel expenses for two different vehicles; separating business and personal expenses while travelling; etc.

**Comment by vomikan** [comment]
feat(CustomFields): Add custom fields feature #663

**Comment by vomikan** [comment]
#1664

**Comment by luisdev** [comment]
Also related: https://github.com/moneymanagerex/moneymanagerex/issues/1474
