### ISSUE TITLE
Window dimensions not reported correctly in 'About'

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4900]
![image](https://user-images.githubusercontent.com/6836805/182609713-59499f4f-7bac-4cd2-ab63-df08f8a9bc38.png)

_Originally posted by @vomikan in https://github.com/moneymanagerex/moneymanagerex/issues/4724#issuecomment-1203895474_

**Comment by PMaff** [comment]
> ![image](https://user-images.githubusercontent.com/6836805/182609713-59499f4f-7bac-4cd2-ab63-df08f8a9bc38.png)
> 
> _Originally posted by @vomikan in [#4724 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/4724#issuecomment-1203895474)_

I am not sure, if this is an issue of the virtual machine in my cases.
Also up to now I did not realize any negative effects of this 0x0 dimensions in the About window.
YMMV

**Comment by PMaff** [comment]
About:
```
Money Manager Ex
Version: 1.5.19-Beta.2 64-bit
• Aufbauend auf Aug 16 2022 13:53:28
• Datenbankversion: 7 • (aes128cbc)
• Git commit: d9530924f (2022-08-16)
• Git branch: master
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.0 (wxGTK 3.22)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.3
• lunasvg v2.3.1
• libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
• gettext 0.19.8.1
• apexcharts.js
Genutztes Build:
• CMake 3.22.0
• GNU Make 4.1
• GCC 7.5.0 • Ubuntu 18.04 'bionic'
Läuft auf:
• Ubuntu 18.04.6 LTS "bionic"
• Linux 4.15.0-191-generic x86_64
• English (United Kingdom) (UTF-8)
• 1920x1080 24bit 96x96ppi
```
if not run in a virtual machine looks ok.
