### ISSUE TITLE
Toolbar is wrong colour in dark mode

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4905]
MMEX version:
 - [x] 1.5.18 Beta
 - [x] 1.5.19 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

As reported here [https://forum.moneymanagerex.org/viewtopic.php?p=23191](https://forum.moneymanagerex.org/viewtopic.php?p=23191) the toolbar colour is not correct in dark mode.

![image](https://user-images.githubusercontent.com/4060092/182792717-e8848875-5a95-4ed5-a59c-b32d48ec09e8.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Select dark mode in 1.5.18 (or 1.5.19 Beta)
2. Restart MMEX

Expected result:

Toolbar should be dark.

Actual result:

See screenshot

**Comment by whalley** [comment]
Whilst there don't seem to be any issues on MacOS dark mode, this change may help.

**Comment by vomikan** [comment]
> Whilst there don't seem to be any issues on MacOS dark mode, this change may help.

I've tested this. It does not help.

**Comment by tactilis** [comment]
Agreed, it's still the same.

The question is, what changed to the handling of dark mode between 1.5.13, where it clearly worked, to 1.5.18.

I don't use dark mode, so I never noticed the release version (or beta), where this happened.

**Comment by vomikan** [comment]
> The question is, what changed to the handling of dark mode between 1.5.13, where it clearly worked, to 1.5.18.

The toolbar was "wxToolBar" then became "wxAuiToolBar".

**Comment by whalley** [comment]
Yes, was changed here... https://github.com/moneymanagerex/moneymanagerex/issues/4791

Some discussion wxAuiToolBar here: https://stackoverflow.com/questions/23366944/how-to-set-wxauitoolbar-background

**Comment by vomikan** [comment]
One more issue
![image](https://user-images.githubusercontent.com/6836805/182858123-af4f17ca-9161-44bc-982e-22658a64387f.png)

It seems was an separate bug report but I can't find it.

**Comment by vomikan** [comment]
Admittedly, even if you roll back the changes https://github.com/whalley/moneymanagerex/commit/b00ba2c6a38fbf1ab2d657515eba43e7c579d8df, the dark theme on Windows looks bad.

![image](https://user-images.githubusercontent.com/6836805/182861806-e76299f2-21f5-4cf8-b934-b47fb1ad21fe.png)

**Comment by whalley** [comment]
Removing myself from this one as there seem to be quite a few 'Dark Mode' restrictions on Windows and I've not really got the time to evolve this on Windows.
