### ISSUE TITLE
Display Share Accounts - the setting is not saved

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4907]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [x] 1.5.19 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

There is a Share Account that I would prefer to see every time I open the MMX.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Reproduction steps:**

1. Go to View ->Display Share Accounts - check
2. The Share Account is visible in the left menu tree
3. Closed the program
4. Opened it again

…

**Expected result:**
The Share Account is shown in the left menu tree
**Actual result:**
The account is hidden. It is necessary every time repeat the View ->Display Share Accounts steps. 

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
I can confirm that issue. But it may be a feature not a bug.
