### ISSUE TITLE
Not possible to enter any split transaction in split transaction window.

### ISSUE THREAD

**Issue by Eduardo3382** [moneymanagerex/moneymanagerex#4909]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [ ] 1.5.16
 - [x]1.5.19 beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Not possible to load any split transaction 

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create or editing a transaction to split in 2 different expenses
2. Select the icon close category field to split in 2 different expenses
![Screenshot from 2022-08-04 09-37-34](https://user-images.githubusercontent.com/39868347/182883553-64020a42-058b-4829-9542-3e1bd6ba51e3.png)
3. A window for split transaction is open to enter the expenses
4. select the amount field in order to enter the figure, and amount field disappear from the windows.
![Screenshot from 2022-08-04 09-38-01](https://user-images.githubusercontent.com/39868347/182883730-b5ae96ae-5857-4346-bf24-2c30172c9c3b.png)

…

Expected result:
Create or edit a transaction for split a transaction with 2 expenses
Actual result:
There is not any way to update change figure in amount field, so not possible to enter any split transaction.
![Screenshot from 2022-08-04 10-18-33](https://user-images.githubusercontent.com/39868347/182883893-b4af99f2-a214-4d8b-9381-091056f02bcc.png)

# Additional information
There is another window issue for selecting or enter information in Transaction filter transactions in a view (see the attached screenshot).
![Screenshot from 2022-08-04 10-52-03](https://user-images.githubusercontent.com/39868347/182883933-f6cc41d0-aa4e-4920-bebf-2dc94a8d4f3d.png)
In this case, is not allowed to select a range of amounts.
If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Related: https://github.com/moneymanagerex/moneymanagerex/issues/4911

**Comment by vomikan** [comment]
Could you change the window size by dragging thr right buttom corner of the dialog?

![image](https://user-images.githubusercontent.com/6836805/183090861-5d230477-27f5-4b59-8ccd-03fc97d21c0e.png)

**Comment by Eduardo3382** [comment]
Right, I was not aware I can change the window for the first case, (splitting transaction), enlarging it, I can enter the figure in the amount field. Thanks.
But In the second case for selecting a transaction (transaction filter window), there is not any way to change the size of the window, nor enter range amount to filter the transactions view.

**Comment by vomikan** [comment]
#4911

I've changed a bit the code. It may be affected to this case also.
