### ISSUE TITLE
Column Issue in Account View

### ISSUE THREAD

**Issue by dwrj87** [moneymanagerex/moneymanagerex#491]
I right clicked on ID column, went to Hide/Show Columns > and deselected ID

As you can see from this screen shot, the column data is still there and getting screwed up along with the date

If I follow the same steps to re-enable the column, it doesn't work

![mmex column issue](https://cloud.githubusercontent.com/assets/7465843/7758561/6faa00fc-0002-11e5-8b70-013d8b3db5e2.png)

**Comment by vomikan** [comment]
I can't reproduce this.

**Comment by dwrj87** [comment]
I'll see if I can do some digging to find out what is going on

**Comment by dwrj87** [comment]
Closing this as while I can reproduce on my computer, I can't work out what is going on and I can't reproduce it elsewhere

**Comment by MartinX3** [comment]
#749
Still open.
