### ISSUE TITLE
Buttons become hidden on Split Transaction dialog 

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4911]
MMEX version:
 - [ ] 1.5.19 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Add Split / Remove Split buttons and the OK / Cancel buttons on the Split Transaction dialog become hidden as more splits are added.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

I start with a new installation of MMEX so that all fonts, dialog sizes, and icon sizes were at their default settings.

1. Add splits to a transaction
2. Observe that after a certain number of splits have been added the Add Split / Remove Split buttons and then the OK / Cancel buttons become hidden as shown in the video.

In the video, I am adding splits by pressing Enter when in the Amount field. Note that the same problem occurs if you use the Add Split button instead.
 
https://user-images.githubusercontent.com/4060092/182908100-b1deb6f4-3864-4189-a304-2f68c5a8b6db.mp4

 
Expected result:

1. The splits scrollbar should appear at an earlier point so that the buttons do not become hidden.
2. The default height of the dialog should perhaps be a little taller so that more splits can be viewed before a scrollbar is required.
3. The dialog should have a minimum height set so that it is not possible to resize it to reduce the height to the extent that the buttons cannot be seen. In fact, does it need to be resizeable at all?

Actual result:

Buttons become hidden; see video.

**Comment by whalley** [comment]
I wonder (but don't really want to open the discussion and change this logic again!!) whether use of a wxListView (as done for 'Organize Payees' would make the management of splits easier...

**Comment by tactilis** [comment]
> I wonder (but don't really want to open the discussion and change this logic again!!) whether use of a wxListView (as done for 'Organize Payees' would make the management of splits easier...

IMO, the logic of the Split Transaction dialog is OK. You have _direct_ access to the combobox to filter/select/enter categories.

If it was managed like the Organize Payees dialog, then we'd need an Add button, which would pop-up a dialog containing a categories combobox, which after entry, you'd then have to OK...    Feels much slower than the current workflow. 

It seems to me that all that is required is to decide how many rows we are going to allow to be displayed (perhaps 4 or 5) before the scroll bar appears _and_ make sure that the dialog is sized appropriately so that, with the maximum number of rows displayed, the buttons don't get hidden.

**Comment by whalley** [comment]
> If it was managed like the Organize Payees dialog, then we'd need an Add button, which would pop-up a dialog containing a categories combobox, which after entry, you'd then have to OK... Feels much slower than the current workflow.

@tactilis Yes would be a little more cumbersome.

What we need then, is to try to get the sizers correct to support the below with YELLOW areas fixed and GREEN the scroll area, and the minimum size of the window is enough to hold the fixed area and a number of rows from the scroll area.

![CleanShot 2022-08-04 at 20 47 03](https://user-images.githubusercontent.com/487345/182939997-add1731d-e6d7-4ee9-b43d-4418a7561963.png)

**Comment by tactilis** [comment]
> What we need then...

Yes, exactly so.

**Comment by vomikan** [comment]
IMHO Fit() should be added.

**Comment by vomikan** [comment]
https://user-images.githubusercontent.com/6836805/183091939-cbf0370d-a65f-4fac-b059-f61f198a9587.mp4

**Comment by tactilis** [comment]
I'm uncertain what point you are making in the video.

The dialog should either be a have a fixed size, or if it is to be resizable, it should have a minimum size below which it cannot be sized.

**Comment by vomikan** [comment]
> I'm uncertain what point you are making in the video.

I actually show that the window can be reduced to zero. And this needs to be fixed.
