### ISSUE TITLE
DECLARE_EVENT_TABLE

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4913]
In all examples, this construction is in private
```
private:
    DECLARE_EVENT_TABLE()
```

In our code, always in public

**Comment by whalley** [comment]
_It doesn't matter where it appears but it's customary to put it at the end **because the macro changes the access type internally** so it's safest if nothing follows it._

See below:

https://docs.wxwidgets.org/3.2/overview_events.html
> First define one or more event handlers. They are just simple methods of the class that take as a parameter a reference to an object of a wxEvent-derived class and have no return value (any return information is passed via the argument, which is why it is non-const). You also need to insert a line with the macro indicating that the class uses an event table, like this:
> 
> [wxDECLARE_EVENT_TABLE](https://docs.wxwidgets.org/3.2/event_8h.html#ab6eca03fad44ec10b75d3cb82e9219e3)();
> somewhere in the class declaration. It doesn't matter where it appears but it's customary to put it at the end because the macro changes the access type internally so it's safest if nothing follows it.
>
