### ISSUE TITLE
Change the term 'Scale' to 'Decimal Places' for the English translation of MMEX

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4918]
MMEX version:
 - [x] 1.5.18

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [x] Linux 

# Description of the bug

As discussed in the forum here: [https://forum.moneymanagerex.org/viewtopic.php?p=23203](https://forum.moneymanagerex.org/viewtopic.php?p=23203), the use of the word 'Scale' as the label for the field that specifies the number of decimal places for a currency causes some confusion for English speaking users of MMEX.
 
![image](https://user-images.githubusercontent.com/4060092/183266237-2cbde716-3964-4c67-8dff-d707ee887a3d.png)
 
Can we change the label to say 'Decimal Places' for the English translation of MMEX please?
 
![image](https://user-images.githubusercontent.com/4060092/183266250-95440b08-2f86-4ba9-a8f9-b46fe511a751.png)
 
Similarly, Scale is used in the **Custom Field editor**:
 
![image](https://user-images.githubusercontent.com/4060092/183266490-d4eccdc4-57ce-4f07-a0f1-cca46256a076.png)

Can we change the Label to 'Decimal Places' and the tooltip to 'Enter the number of decimal places'.

**Comment by vomikan** [comment]
https://crowdin.com/project/moneymanagerex/en-GB
