### ISSUE TITLE
edit existing category name and entering a colon 

### ISSUE THREAD

**Issue by xerophyllum** [moneymanagerex/moneymanagerex#4919]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [ ] 1.5.16
 - [ ] 1.5.17 Beta
 - [x] Other 1.5.18 64bit

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

when editing an existing category and adding a colon to the name, while it appears as a colon in the editing window, after clicking [ok] the colon is displayed as a pipe |.  and subsequently in any place where that category appears, it appears as a pipe and not a colon

if you add a new category and use a colon, it appears as expected -- a colon

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. tools | organize categories
2. select an existing category, [edit]
3. add a colon to the name
4. [ok]

…

Expected result: : 

Actual result: |

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
This is deliberate behaviour (a feature). Not a bug.

The colon is the category:subcategory separator character. It should not appear in the category or subcategory name.

The OnEdit function contains:

```
    if (text.Contains(":")) {
        text.Replace(":", "|");
    }
```

It would perhaps be better if entering a colon in the category name produced an error message and the change was disallowed - but the current solution is a reasonable alternative.

**Comment by whalley** [comment]
However, as @xerophyllum has noted, creating a new category allows a colon to be entered.

My preference is to disallow the use of colons in category or subcategory names.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2465
