### ISSUE TITLE
Fehler bei der automatischen Zuordnung der Kategorie

### ISSUE THREAD

**Issue by gozlaw** [moneymanagerex/moneymanagerex#4920]
> Bei definierten Empfängern wird die Kategorie falsch zugeordnet. (siehe scrennshots)
![Screenshot (3)](https://user-images.githubusercontent.com/110814626/183372572-26f738e2-8dbb-4c0c-9f5f-fa06352da189.png)
![Screenshot (4)](https://user-images.githubusercontent.com/110814626/183372577-549ea905-d10d-439d-8daa-04741fc7689c.png)

> Bitte entfernen Sie die unter diesem Text enthaltenen Informationen nicht.

<hr>Version: 1.5.18 64-bit<br>
 • Build: Juli 27 2022 22:24:57<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22000), 64-bit edition<br>
 •  German (Germany) (windows-1252)<br>
 • 1600x900 32bit 96x96ppi

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4886
