### ISSUE TITLE
Default Categories are not entering automatically

### ISSUE THREAD

**Issue by Pbtmccoy** [moneymanagerex/moneymanagerex#4925]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [ ] 1.5.16
 - [ ] 1.5.17 Beta
 - [x ] Other (please specify) Version: 1.5.18 64-bit • Build on Jul 27 2022 22:24:57

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 10
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open New Transaction dialog box
2. Enter data:  Date, Status, Type, Amount, Account, Payee by using the tab key to each field.
3. Default category NO LONGER auto fills since recent updates to versions 1.5.17 and 1.5.18

…

Expected result:  Default Category, when one is assigned to a Payee, should auto fill in the Category field.

Actual result:  Nothing.  Category must be chosen by beginning to type it and choosing it from the drop down lists.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4886
