### ISSUE TITLE
Term account columns 

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#4927]
# Description of the feature
In term account I like to see additional columns 
Please describe your feature with details.
Currently you can not add additional columns , you can hide or rearrange only.
Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.
I like two additional colums , one for date field this can be end date.
another column would be "interest" field
currently I am using Notes field to show end date and interest.
love to see this in future build.
Thanks
Ashok

**Comment by whalley** [comment]
Not quite sure of use case here, are these items you want to be able to change on a per-transaction basis. Or are the values thoses stored against the account? If account level then it makes no sense to hold as a transaction column, if per-transaction then have you looked at custom fields?

**Comment by arp2164** [comment]
I am attaching screen shot, may be that will clear what I am asking for. At present there are 10 columns , I want to add two extra columns one for end date & one for Interest
<img width="960" alt="Screen Shot 2022-08-10 at 3 35 36 PM" src="https://user-images.githubusercontent.com/107713258/184016780-4111b49e-dedb-483b-b61d-fce62d952274.png">
.I guess you may have to create a new transection filter showing extra two fields when creating New values?

**Comment by whalley** [comment]
But what does end date mean? Is the date the account ends?

What does interest mean? Is it the account interest rate?

**Comment by arp2164** [comment]
End date is maturing date.
Interest is accumulated interest paid on maturity.

**Comment by whalley** [comment]
Then why do you need these on a per transaction basis? Would these not be set against the account?

**Comment by tactilis** [comment]
@arp2164
Your use case still is not clear.

1. Is this an account where you are depositing a single payment (when you open the account) and then interest accrues monthly (or annually, or whatever) until the end of a fixed term? In which case there will be only one transaction made in the account.

Or

2. Is it an account where you can make additional deposits (after the initial deposit) and interest accrues as above?  In which case there will be multiple transactions in the account.


You will presumably be typing in the end date?

Are you expecting MMEX to calculate the accrued interest, or are you also typing that in?


If you answer these questions, we may have a clearer idea of what you are trying to do.

**Comment by arp2164** [comment]
Number (1) is the correct. It’s a single deposit and on maturity term interest paid. Its a single transaction per deposit . However there are multiple deposits  with different terms of single deposit with different maturity dates.
Interest is the number typed in. 
yes the end date can be typed in.

**Comment by rmelillo76** [comment]
Hello @arp2164 , as others said, custom fields would handle what you are asking for if you want to capture these details at the transaction level. Just bear in mind these fields will also appear and be available to non-term accounts (if you have any).

Below are some example screenshots on how you could configure them for your use case.

![image](https://user-images.githubusercontent.com/95182117/184044389-61ad7178-ac92-439f-8d3f-2e45c7bedd7e.png)

![image](https://user-images.githubusercontent.com/95182117/184044405-175211c2-ea6f-4deb-9420-bd5fb382ebec.png)

![image](https://user-images.githubusercontent.com/95182117/184044398-b60df906-da79-43df-9635-83d4ddeb8696.png)



![image](https://user-images.githubusercontent.com/95182117/184044346-873937af-b2c5-4e8d-aa97-b4df2b2469f1.png)



![image](https://user-images.githubusercontent.com/95182117/184044716-815b100d-4fe6-4c05-9eab-c187c5a46b26.png)

**Comment by tactilis** [comment]
Very nicely explained @rmelillo76

The problem for @arp2164 will be that, as you say, the Interest and Maturity Date custom fields will appears in all other transaction views, such as regular bank accounts.

![image](https://user-images.githubusercontent.com/4060092/184078150-d26de436-ba22-4982-abf6-33a90568c6ec.png)
 
 
The only solution for this would be to enhance MMEX so that we could choose (and have remembered) the columns to be displayed on a _per account_ basis.

![image](https://user-images.githubusercontent.com/4060092/184078511-a1d80b3b-4eb1-41e5-b8fd-0c0b0e6a4f1a.png)
 
 
In the meantime, it may be better for @arp2164 to continue using the Notes column for Interest and Maturity date.

**Comment by arp2164** [comment]
Very well explained and given instruction by @rmelillo76 but I agree with @tactillis.
I can hide the columns but then to see my Term account you have to unhide to show again. May be in future updates it can be displayed on a per account basis.
Thanks for your prompt input.

**Comment by whalley** [comment]
Given the conclusion on this, i.e. the need to per-account based column show/hide.... this is covered by https://github.com/moneymanagerex/moneymanagerex/issues/3373. So marking as duplicate and closing.

**Comment by arp2164** [comment]
> Given the conclusion on this, i.e. the need to per-account based column show/hide.... this is covered by #3373. So marking as duplicate and closing.

I have ver 1.6 but I don’ see it’s added. Can you tell me when it will be added. 
thanks
Ashok

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3373 is currently targeted at [v1.6.3](https://github.com/moneymanagerex/moneymanagerex/milestone/41)

**Comment by arp2164** [comment]
I have asked is it possible to have extra columns on per account basis ? I assume you said will be added in 1.6.3. I have version 1.6.3 but don't see this is implemented. Please let me know when it will be added.
Thanks
Ashok

**Comment by whalley** [comment]
I did not say it would be in v1.6.3, but that it was targeted at v1.6.3... As things stand it https://github.com/moneymanagerex/moneymanagerex/issues/3373 is now targeted at v1.6.5.
