### ISSUE TITLE
Copying/Editing split transaction breaks the Add/Remove Split buttons

### ISSUE THREAD

**Issue by aka13-404** [moneymanagerex/moneymanagerex#4928]
MMEX version:
 - [x] 1.5.18
Operating System:
 - [x] Windows

# Description of the bug

I tried my best to search the repo, but have not found a similar recent issue.

When I create a new transaction, and click on "plus" symbol, to create a split, I get the new split window, with "add split", "remove split" buttons. 
![image](https://user-images.githubusercontent.com/51682059/184332382-387145f4-2b6f-40ad-9eae-cf2870d10559.png)

When I try to edit a split transaction, either just to correct the categories, or I copy a split transaction for another use, the window breaks, and I can not add or remove splits.
![image](https://user-images.githubusercontent.com/51682059/184332725-27d7c083-4ee6-4cf3-a9d7-769ac50cffc5.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

Try to edit a split transaction

Expected result:

To be able to edit the split, add or remove split

Actual result:

Not being able to edit or save the split.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4911
