### ISSUE TITLE
Operazione ricorrente con + transazioni non permetta la modifica

### ISSUE THREAD

**Issue by marcop1960** [moneymanagerex/moneymanagerex#4931]
> Una operazione ricorrente in cui viene divisa la transazione , una volta inserita, non permette la variazione o aggiunta di righe.
Non sono presenti comandi di OK oppure Annulla.

![Issue  2022-08-13 133812](https://user-images.githubusercontent.com/111181778/184492264-8e735697-8b9c-4a27-a041-0592f867f06a.jpg)
.

<hr>Version: 1.5.18 64-bit<br>
 • Build: Lug 27 2022 22:24:57<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
> a recurring operation in which the transaction is divided, once inserted, does not allow the variation or addition of lines.
there are no ok commands or cancels.

It's a bug. Just resize the Split dialog by dragging the bottom right corner.

See https://github.com/moneymanagerex/moneymanagerex/issues/4911

**Comment by marcop1960** [comment]
Thx so much

Il sab 13 ago 2022, 13:53 Martin ***@***.***> ha scritto:
