### ISSUE TITLE
slow at saving transactions

### ISSUE THREAD

**Issue by dbrooks4082** [moneymanagerex/moneymanagerex#4932]
> version 1.5.18
slow at saving transactions.  Every so often it will save at a normal speed.
> Please do not remove information attached below this text.

<hr>Version: 1.5.18 <br>
 • Build: Jul 27 2022 22:35:30<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22000), 64-bit edition<br>
 •  English (United States) (windows-1252)<br>
 • 1280x960 32bit 96x96ppi

**Comment by whalley** [comment]
Not enough information to investigate this. What is the size of DB, how many transactions? When you say 'slow', how long does it take? Where is the database stored - local HD, network, USB, or a cloud sync folder. Is 'every so often' once a week? a day? an hour? How many 'normal speed' (and what speed do you define as normal?) transactions before a slow one?

**Comment by whalley** [comment]
@dbrooks4082 Feel free to re-open if you can supply more information
