### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by btab33** [moneymanagerex/moneymanagerex#4933]
La catégorie par défaut attachée  à certains tiers n'est pas (plus) correctement reprise lors de la création d'une transaction alors que tous les précédentes sont correctement catégorisées.
The default category of some payee is no always attached when creating a new transaction although all previous transactions with this payee is correctly set with this category. 

<hr>Version: 1.5.18 64-bit<br>
 • Build: Juil. 27 2022 22:24:57<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  French (France) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Duplicate.

It's already fixed in the 1.5.19 Beta builds.

See https://github.com/moneymanagerex/moneymanagerex/issues/4886
