### ISSUE TITLE
Summary of Accounts - charts issue

### ISSUE THREAD

**Issue by akslow** [moneymanagerex/moneymanagerex#4934]
MMEX version:
 - [ ] 1.5.17
 - [x] 1.5.18
 - [ ] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

For some data there is a problem with charts. Just look at attached data on screenshot and the chart 
![Bez tytułu](https://user-images.githubusercontent.com/109437617/184544154-80ab428f-bf94-43b3-acb7-654e11fef0ab.png)

Value below -45000 but on chart its close to 0. When I generate chart only for one value its ok but when more are enabled there is an error.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
It's a result of the area chart being stacked and the top line being the balance,  I think this could be better presented as a stacked bar graph with negatives below line and positives above, this will need a line showing the balance (+ve totals - -ve totals).

**Comment by whalley** [comment]
Would somethimng like this be more suitable:

<img width="1173" alt="CleanShot 2022-08-15 at 15 48 36@2x" src="https://user-images.githubusercontent.com/487345/184658243-dc95c802-3e82-42f0-94e6-0dc040572b14.png">

**Comment by akslow** [comment]
if it can't be fixed it's a good idea.

I attach screenshot To compare how chart looks only for Loan Accounts. Levels above / below 0 are completely different.

**Comment by whalley** [comment]
It is the nature of the stacked area chart, it will take value A, add value B, add value C, add value D, etc. So if A=100, B=-50, C=200, D=-25 then it will plot 100, 50, 250, 225.... If you just plot one value over time you will indeed see the correct values for the plotted value.

The stacked bar graph seems a better representation.

**Comment by akslow** [comment]
If I see that right. I think your idea to separate accounts with negative balance and show them below "0" is good idea. Type of chart doesn't really matter.
