### ISSUE TITLE
New transaction category

### ISSUE THREAD

**Issue by scubapaul** [moneymanagerex/moneymanagerex#4935]
I don't know if this is the correct place to comment on this but here are my thoughts.
I recently uploaded version 1.5.18 on my pc. 
I went back to version 1.5.15 because I didn't like the way the category section opens up fully expanded when entering a new transaction in version 1.5.18.
I don't know if this was implemented in versions 16, 17 or 18 but please go back to the previous category version.

**Comment by tactilis** [comment]
If you press the Enter key (aka Return key) when the Category field is blank, it will still display the old tree-style category screen from which you can select a category:subcategory.

Or...

If you start typing the name of a category in the field (e.g Bill or Income), you will get a filtered list of categories matching what you have typed.

Some further improvements in this area have be made for 1.5.19
