### ISSUE TITLE
Optimise/Fix use of mmTextCtrl in dialogs using this control

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4946]
https://github.com/moneymanagerex/moneymanagerex/issues/4921 introduced some improvements in mmTextCtrl (e.g recalculation when focus changes). 

Need to review all re-use of this control to ensure the code is optimal and making best use of the common behaviour.

**Comment by whalley** [comment]
Status:

Quite a lot to review.... All the following use mmTextCtrl, here is a summary of any issues and changes proposed. I'll tick them off when reviewed and implemented, then need to give them a good test!

- [ ] Account Dialog - initial balance, uses account currency
- [ ] Account Dialog - minimum balance, currently uses 2 decimal point precision, should use account currency
- [ ] Account Dialog - credit limit, currently uses 2 decimal point precision, should use account currency
- [ ] Account Dialog - interest Rate, currently uses 2 decimal point precision,  leave as-is
- [ ] Account Dialog - minimum payment, currently uses 2 decimal point precision, should use account currency

- [ ] Asset Dialog - asset name - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Asset Dialog - amount, uses base currency
- [ ] Asset Dialog - value change rate, should continue to use 3 decimal points precision
- [ ] Asset Dialog  - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Asset New Transaction - amount - uses account currency

- [ ] Recurring Transaction Dialog - amount - Should use account currency
- [ ] Recurring Transaction Dialog - to Amount - Should use 'to' account currency

- [ ] Budget Entry Dialog - amount - Should use base currency

- [ ] Main Currency dialog - value - should use currently selected currency

- [ ] Edit Currency Dialog  - name - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Edit Currency Dialog  - symbol - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Edit Currency Dialog  - conversion rate - Should continue to use SCALE as the precision

- [ ] Filter Transaction Dialog - min amount - Continue to use base currency
- [ ] Filter Transaction Dialog - max amount - Continue to use base currency

- [ ] Share transaction Dialog - stock name - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Share transaction Dialog - stock symbol - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Share transaction Dialog - Share number - Should continue to use the 'Share Precision Option'
- [ ] Share transaction Dialog - Share price - Should continue to use the 'Share Precision Option'
- [ ] Share transaction Dialog - Share commission - Should continue to use the 'Share Precision Option'
- [ ] Share transaction Dialog - share lot - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Share transaction Dialog - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Share New Transaction - amount - uses account currency

- [ ] Stock Dialog - stock name - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Stock Dialog - stock symbol - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
- [ ] Stock Dialog - Share number - Should continue to use account currency unless 'Share Precision Option' is more decimal points
- [ ] Stock Dialog - Share price - Should continue to use account currency unless 'Share Precision Option' is more decimal points
- [ ] Stock Dialog - Share commission - Should continue to use account currency unless 'Share Precision Option' is more decimal points
- [ ] Stock Dialog - Current price - Should continue to use account currency unless 'Share Precision Option' is more decimal points
- [ ] Stock Dialog - historic price - Should continue to use account currency unless 'Share Precision Option' is more decimal points 
- [ ] Stock Dialog - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl

- [ ] Split transaction Dialog - amount - Should use account currency

- [ ] Transaction Dialog - amount - Should use account currency
- [ ] Transaction Dialog - to Amount - Should use 'to' account currency

**Comment by tactilis** [comment]
And this field?

Transaction Dialog - Number - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl.
 
 
Recurring Transaction Dialog and Asset Dialog appear to be OK.

**Comment by whalley** [comment]
> And this field?
> 
> Transaction Dialog - Number - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl.

Yes, forgot about that as I've already fixed it in the code but not submitted! Have added to list for completeness.

> Recurring Transaction Dialog and Asset Dialog appear to be OK.

Not checked code yet, but it may indeed be correct.

**Comment by whalley** [comment]
@tactilis Think I've now caught all areas and done a tidy-up/bug fix. Could you please perform a good test of the functionality across a range of currencies to make sure there are no major errors here.

**Comment by tactilis** [comment]
> Could you please perform a good test of the functionality across a range of currencies to make sure there are no major errors here.

Will do.

**Comment by tactilis** [comment]
Testing 1.5.20 Beta - commit: 0c9d866 (2022-08-22)

The first difference I've noticed in this version is that in any account currency field, when you press the Return key you get a 'ding' sound. It signals an error, as though you have entered an invalid character.

For example, in Edit Transaction:

1. Type 123 in the Amount field.
2. Press Return. The field updates to 123.00 and you get a  **ding!**
3. Do some maths (eg. type + 1 after the 123.00)
4. Press Return. The field updates to 124.00 and you get a  **ding!**

The ding didn't happen in 1.5.19. 

I'll keep testing but if you can find and fix issues as I report them I'll update to the fixed version as I go.

There is

**Comment by tactilis** [comment]
Now testing 1.5.20 Beta - commit: 94842f1 (2022-08-22)

The 'ding' sound reported above **no longer** occurs when pressing Return in the Edit Transaction Amount field.

However it **does** occur in the Edit Account Initial Balance field.

But aren't Edit Transaction Amount and Edit Account Initial Balance both account currency fields? Why are they behaving differently?

Also, the 'ding' when pressing Return happens in the  Edit Transaction Number field.

**Comment by whalley** [comment]
Think the 'ding' is related to event propagation. For the Amount field the event is caught in the 'mmTextCtrl' field handling and also caught in the dialog, for the initial balance it is only caught in the 'mmTextCtrl' field and does not need to be handled in the dialog... I suspect something is then causing the 'ding'.   Annoyingly, the 'ding' does not occur on MacOS.

Apart from the 'ding' (which I'll look into), it would be good to see if you have identified any other issues.

**Comment by tactilis** [comment]
> it would be good to see if you have identified any other issues

I'm working my way through all the dialogs & fields.

Here are a few observations:

From your list:
1. >  Asset Dialog - amount, uses base currency

Why base currency and not account currency?

2. > Asset Dialog - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl

In the Edit Transaction dialog if you enter Notes as:
ABCD
EFGH

they are displayed in the Notes column as "ABCD EFGH" as expected.

However, for assets, they are displayed in the Notes column as "ABCDEFGH"

3. > Asset Edit Account Dialog

I have the currency set to 4 decimals/comma dp/space grouping and I entered 1234,5678 into the fields.

Normal account:
 
![image](https://user-images.githubusercontent.com/4060092/186213536-e7e482c2-65e4-4b95-adec-7a8bb6bea76d.png)

Asset account:

![image](https://user-images.githubusercontent.com/4060092/186213840-705cc5d4-0089-4eea-b7f9-044bd2b7ec87.png)
 
You may have missed updating this dialog?  Also, why isn't this common code with the normal Edit Account Dialog?
 
 
I'll keep going and report as I go but it may take a couple of days to finish due to other things.

**Comment by tactilis** [comment]
[Continuing the numbering from above, so you can easily reference the observation]

4.> Asset New Transaction - amount - uses account currency

Currency set to 4 decimals/comma dp/space grouping and I entered 1234,5678 into the fields
 
Note the surprising rounding to 2 dp in the Advanced Amount field even though it is displaying 4 decimals.

![image](https://user-images.githubusercontent.com/4060092/186217536-b473deeb-4088-4f5d-ba78-aff51262d76c.png)

**Comment by whalley** [comment]
> 1. > Asset Dialog - amount, uses base currency
> 
> Why base currency and not account currency?

There does not need to be an account when managing assets

<img width="349" alt="CleanShot 2022-08-23 at 19 00 04@2x" src="https://user-images.githubusercontent.com/487345/186231188-61a0cf8d-59a0-4034-bd13-4f694c712a96.png">

> 2. > Asset Dialog - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl
> 
> In the Edit Transaction dialog if you enter Notes as: ABCD EFGH
> 
> they are displayed in the Notes column as "ABCD EFGH" as expected.
> 
> However, for assets, they are displayed in the Notes column as "ABCDEFGH"

I can't reproduce.
<img width="916" alt="CleanShot 2022-08-23 at 19 06 44@2x" src="https://user-images.githubusercontent.com/487345/186232472-fc3f565a-88c2-453f-8019-af231eb0c59b.png">

> 3. > Asset Edit Account Dialog
> 
> **UPDATE: IGNORE THE REPORT BELOW. MY ERROR - I HAD THE ASSET ACCOUNT STILL SET TO UK POUND!**
> 

Ignored.

> 4.> Asset New Transaction - amount - uses account currency
> 
> UPDATE: IGNORE THE REPORT BELOW. MY ERROR - I HAD THE ASSET ACCOUNT STILL SET TO UK POUND!

Ignored.

**Comment by whalley** [comment]
The Ding sound be fixed.... (hopefully)

**Comment by whalley** [comment]
Point of note... All overrides of the mmTextCtrl `EVT_TEXT_ENTER` event have been dynamically bound so that they occur first and as they don't call `event.Skip()` will result in no duplicate calls.

**Comment by tactilis** [comment]
Now testing 1.5.20 Beta - commit: 2d07543 (2022-08-23)

Perhaps I wasn't supposed to update to this version. Very broken.

5> New/Edit Transaction (Transfer).

See the video.

- Note that the 2 dp rounding in the Advanced Amount field (as reported at 4. above) _is_ a real bug (i.e. it wasn't caused by my accidental mixing of EURO/4dp with UK POUND/2dp)

- Note the movement of the text entry caret as I move the mouse selection point in a different field.

https://user-images.githubusercontent.com/4060092/186266434-0153c50d-ea08-4de0-b517-7cab601f673b.mp4

**Comment by tactilis** [comment]
> The Ding sound should be fixed.... (hopefully)

Confirmed fixed. Thanks

**Comment by tactilis** [comment]
Regarding 2. above.

>>  However, for assets, they are displayed in the Notes column as "ABCDEFGH"

>I can't reproduce

Nor can I now!

But it was definitely there. I compared Notes entry in a Bank account (worked as expected) and an Assets account (concatenated the lines every time). I repeated it several times with new transactions. Unfortunately I didn't record a video.

I'll keep a look out for it occurring again and try to pin down what's happening.

**Comment by whalley** [comment]
> Note the movement of the text entry caret as I move the mouse selection point in a different field.

Hopefully fixed. 

> Note that the 2 dp rounding in the Advanced Amount field (as reported at 4. above) is a real bug (i.e. it wasn't caused by my accidental mixing of EURO/4dp with UK POUND/2dp)

I can't seem to reproduce this. Can you share the currency settings for the two accounts in question

**Comment by tactilis** [comment]
Now testing 1.5.20 Beta - commit: 2dd6cb9 (2022-08-23)

Regarding 2. above:

>> However, for assets, they are displayed in the Notes column as "ABCDEFGH"

> I can't reproduce

Found it again. The Notes concatenation bug is in the Asset itself, not the asset transactions.

![image](https://user-images.githubusercontent.com/4060092/186371507-8ffdc4c4-a506-423c-904b-356967616589.png)
 
I see also that there is no Recently Used Notes button on this dialog, so it clearly does not share code other dialogs that have Notes.

The whole area of Assets needs an overhaul anyway, I don't fully understand it - and I encountered a crash somewhere along the way, which I'm trying to reproduce.

Do you want to fix the Notes concatenation here (plus anything else I find to do with the TextCtrl changes) and then we address Assets more generally in a separate issue (when we have time)?

**Comment by tactilis** [comment]
Regarding 5. above:

>> Note the movement of the text entry caret as I move the mouse selection point in a different field.

> Hopefully fixed.

Yes. That's fixed. Thanks

**Comment by whalley** [comment]
> Do you want to fix the Notes concatenation here (plus anything else I find to do with the TextCtrl changes) and then we address Assets more generally in a separate issue (when we have time)?

Yes, any pre-existing issues unrelated to this change should be recorded as other issues - otherwise I might never get this issue closed :-)

**Comment by tactilis** [comment]
Regarding 5. above:

>> Note that the 2 dp rounding in the Advanced Amount field (as reported at 4. above) is a real bug (i.e. it wasn't caused by my accidental mixing of EURO/4dp with UK POUND/2dp)

> I can't seem to reproduce this. Can you share the currency settings for the two accounts in question.

Base currency is Euro with 4 dp:
 
![image](https://user-images.githubusercontent.com/4060092/186377180-c634645d-c39e-44b1-b7cd-439d8f9391a9.png)
 
Both bank accounts are set to Euro:

![image](https://user-images.githubusercontent.com/4060092/186378251-5216f3e0-8ccb-4838-883f-228fd599bda1.png)
 
As you can see in the video below, the incorrect rounding to 2 dp in the Advanced Amount field occurs _prior_ to the To account being specified. Once the To account it is set, then the appropriate number of dp is allowed (I pressed Return after updating the digits) - but by then, the value the user entered has been changed.

Note that the Advanced Amount field does always display 4 dp in keeping with the From account's currency setting, so we just need to avoid the incorrect rounding to 2dp.

https://user-images.githubusercontent.com/4060092/186382804-77376b4c-5c4c-40e9-bfb5-6f364c66a840.mp4

**Comment by whalley** [comment]
> As you can see in the video below, the incorrect rounding to 2 dp in the Advanced Amount field occurs prior to the To account being specified.

I'm tempted to disallow the advanced setting until the 'To' account is specified as we don't know the currency detail yet.

**Comment by whalley** [comment]
> As you can see in the video below, the incorrect rounding to 2 dp in the Advanced Amount field occurs prior to the To account being specified. Once the To account it is set, then the appropriate number of dp is allowed (I pressed Return after updating the digits) - but by then, the value the user entered has been changed.

Fixed.

**Comment by tactilis** [comment]
Now testing 1.5.20 Beta - commit: fbae72a (2022-08-24)

Edit Transaction Advanced Amount field rounding

> Fixed. Will use base currency settings until account is specified.

Confirmed fixed.

**Comment by whalley** [comment]
Just noticed some of the number fields in the account dialog are not right aligned. Will fix in next commit..

**Comment by tactilis** [comment]
> Just noticed some of the number fields in the account dialog are not right aligned.

I was just about to report those :smile:

**Comment by tactilis** [comment]
6. > Edit Account dialog

As you noticed, Initial Balance, Minimum Balance, Credit Limit are not right aligned.

Minimum Payment _is_ right aligned but does not appear to use account currency.
- It initially displays only 2 dp (in my 4 dp test) until a new value is entered and Return is pressed.
- It allows letters to be typed (the other account currency fields disallow letters and produce a ding).

You can see both these problems here:

https://user-images.githubusercontent.com/4060092/186479712-4fd3b82c-aae3-4850-bf02-e43537045a01.mp4

At the end of the video I attempt to enter letters into the Credit Limit field but, as expected, none are allowed.

**Comment by whalley** [comment]
> Minimum Payment is right aligned but does not appear to use account currency.
>
> It initially displays only 2 dp (in my 4 dp test) until a new value is entered and Return is pressed.
> It allows letters to be typed (the other account currency fields disallow letters and produce a ding).

Sorted, validator was wrong. Keep 'em coming....

**Comment by tactilis** [comment]
OMG, two completely different ways to create an asset transaction!
 
![image](https://user-images.githubusercontent.com/4060092/186491206-89e039aa-7321-4245-af2e-c3875faf2203.png)
 
Hard to maintain and very confusing for users. The legacy dialog needs 50% of it removed! (In due course, obviously)

**Comment by tactilis** [comment]
7. > Recurring Transaction Dialog - amount - Should use account currency
    > Recurring Transaction Dialog - to Amount - Should use 'to' account currency
    
The fields themselves seem OK but I've observed that there is a difference in behaviour compared to the bank Transaction Dialog.

In bank Transactions, when you tick Advanced, the To Amount is initially zero:
 
![image](https://user-images.githubusercontent.com/4060092/186502645-6037e4b8-2622-4f95-ba92-bb6370cee9b1.png)
 
But for Recurring Transaction, when you tick Advanced, the To Amount is pre-filled with the Amount.

![image](https://user-images.githubusercontent.com/4060092/186503218-b085f7e8-d539-4533-a9e6-fc798cc0510b.png)

I think the bank transaction dialog behaviour is better because you will always want to explicitly enter a value in To Amount that is different to the value in Amount.

Also the Recurring Transaction has the same concatenation bug with multi-line notes:

![image](https://user-images.githubusercontent.com/4060092/186504821-97e47552-800b-4643-be07-dcb35b645722.png)

**Comment by tactilis** [comment]
> Budget Entry Dialog - amount - Should use base currency

I don't do budgeting in MMEX (yet). I've looked at the Help and set a year and a month but can't find a Budget Entry with an Amount field.

Could you point me in the right direction please?

**Comment by whalley** [comment]
> Could you point me in the right direction please?

Setup for a month/year then double click on one the rows.

![CleanShot 2022-08-24 at 20 40 34](https://user-images.githubusercontent.com/487345/186508443-abb43686-877f-47d1-a205-a43ad8f2cc82.png)

**Comment by whalley** [comment]
> The fields themselves seem OK but I've observed that there is a difference in behaviour compared to the bank Transaction Dialog.
> In bank Transactions, when you tick Advanced, the To Amount is initially zero:
> But for Recurring Transaction, when you tick Advanced, the To Amount is pre-filled with the Amount.
> I think the bank transaction dialog behaviour is better because you will always want to explicitly enter a value in To Amount that is different to the value in Amount.

Have aligned the dialogs... will be included in commit later this evening.

> Also the Recurring Transaction has the same concatenation bug with multi-line notes:

Can't reproduce...
![CleanShot 2022-08-24 at 20 59 06](https://user-images.githubusercontent.com/487345/186512051-380f109a-6509-4401-b8e9-b53c801b5db7.png)

**Comment by tactilis** [comment]
>> Also the Recurring Transaction has the same concatenation bug with multi-line notes:

> Can't reproduce...

It's 100% repeatable here:

https://user-images.githubusercontent.com/4060092/186514026-84f790ed-be08-435d-9839-9900e35dcf18.mp4

Likewise for assets https://github.com/moneymanagerex/moneymanagerex/issues/4946#issuecomment-1225406862.

I'm puzzled as to how straightforward string handling can be different between between platforms.

**Comment by tactilis** [comment]
8. > Stock Dialog - notes - Should not use mmTextCtrl as this is normal string, change to wxTextCtrl

Same problem here with concatenation of Notes
 
![image](https://user-images.githubusercontent.com/4060092/186525586-6ca70c3d-5fb4-46ec-b2fa-b98eb1035086.png)
 
There must be a difference in the code that handles Notes between those dialogs that display Notes correctly in the transaction list and those that concatenate all lines with no spaces.

**Comment by tactilis** [comment]
OK Mark, I've been through your entire list - and a few other places along the way.

**Comment by whalley** [comment]
> OK Mark, I've been through your entire list - and a few other places along the way.

Great, thanks for that Martin. I'll look into what you have reported....

**Comment by whalley** [comment]
> I'm puzzled as to how straightforward string handling can be different between between platforms.

**wxTextCtrl Text Format**
The multiline text controls always store the text as a sequence of lines separated by '\n' characters, i.e. in the Unix text format even on non-Unix platforms. 

I know what to do to fix the presentation.

**Comment by whalley** [comment]
Should now have covered all items found in testing.
