### ISSUE TITLE
Problem entering decimal numbers

### ISSUE THREAD

**Issue by xraynaud** [moneymanagerex/moneymanagerex#4950]
MMEX version:
 - [ X] 1.5.19

Operating System:
 - [ X] Mac OSX

# Description of the bug

When I enter amounts with decimal numbers, they are always rounded at the 2nd number: 0.123 becoms 0.12.  The problem did not occur with c1.15.18.

# Is the bug reproducible? 
 - [x] Always 
 

Reproduction steps:

Create a new entry, enter a number with 3 decimal values

Expected result:

Have an amount with 3 decimal values

Actual result:

The third decimal is 0

# Additional information

My Mac is configured for french language.

**Comment by vomikan** [comment]
Where do you enter this value and what are the related account and currency settings?

**Comment by xraynaud** [comment]
The problem seem to occur in most number fields: 
- new operation window amount field, with currency settings decimal set to 8, 
- new stock investment window share number and share amount fields

The problem also occur when I set mmex language to english (but with this language setting, the decimal separator is still ',')

**Comment by tactilis** [comment]
@xraynaud 

It's not the MMEX Language that sets the currency format. See these Options:

![image](https://user-images.githubusercontent.com/4060092/185739200-067dfa7d-b3f3-4fbc-a757-bc9808d3720f.png)

**Comment by xraynaud** [comment]
@tactilis Thanks. I changed the currency format but the problem is still there.

**Comment by tactilis** [comment]
@xraynaud

If you have the country code filled in in Options, then the format of currency, including the number of decimal places, will be determined by the locale set in your operating system:
 
![image](https://user-images.githubusercontent.com/4060092/185743565-ad92c652-a231-4d17-8537-7432d8c88b2f.png)
 
However, if you leave the country code blank, then you can set the currency format as you wish:

![image](https://user-images.githubusercontent.com/4060092/185743706-ad7a25a3-a45c-4922-82c1-2527c3bc3708.png)
 
![image](https://user-images.githubusercontent.com/4060092/185743766-cf0daf1e-e3c5-4419-a2a6-d90084f61b85.png)

The above was on Windows but it should work the same on MacOS

**Comment by xraynaud** [comment]
@tactilis I also tried this but the bug is still here. I don't think the problem is a currency formatting problem. All number fields have this bug (even the transaction number field in the new transaction window).

**Comment by tactilis** [comment]
@whalley can you check this on MacOS? 

Could it be related to the recent decimal custom field fixes?

**Comment by whalley** [comment]
Yes, it is an error related to the decimal custom field fixes, that should apply to all platforms. In cases like the transaction dialog the actual currency to use is not passed to the  mmtextctrl class so the base currency is used.

**Comment by whalley** [comment]
Just checked v1.5.18 and the issue exists but only manifested itself if you entered RETURN on the amount field to force the calculation.  Not we calculate on focus change the issue becomes very obvious.

**Comment by whalley** [comment]
Fixed as part of https://github.com/moneymanagerex/moneymanagerex/issues/4946

**Comment by aka13-404** [comment]
Can I safely roll back to 15.18 if I need this from 15.19?

**Comment by tactilis** [comment]
The database format is unchanged between 1.5.18 and 1.5.19, so no problem simply reinstalling 1.5.18
