### ISSUE TITLE
Small display on part of screen

### ISSUE THREAD

**Issue by ShanniTe** [moneymanagerex/moneymanagerex#4953]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [11] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
I have used the Options to set the font size, but I cannot find anything that would change the size of the rest of the home screen. Is there any way I could find it?? Or is it a bug?? I can barely see the Upcoming transactions - which I really need to see! I am disabled, and I've been using this program for ages, but I've just upgraded to Win 11 and I'm having a problem.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result: Help.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![Screenshot 2022-08-20 231005](https://user-images.githubusercontent.com/97408948/185747743-b8c6758c-e55d-4e61-a371-d8209001a75b.png)

**Comment by tactilis** [comment]
Increase the HTML Scale Factor


![image](https://user-images.githubusercontent.com/4060092/185747948-9f8e79c6-c096-4bbe-ad32-98db22ec2bf7.png)

**Comment by ShanniTe** [comment]
Yes - that fixed it!!! Thank you!!! Thank you very much!!!!
