### ISSUE TITLE
mmex 1.5.19 : wrong behaviour of autoselection of category

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#4954]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19
 - [x] 1.5.20 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

If you select a payee, in version 1.5.16 the corresponding last category was selected without clicking into the
category field:

https://user-images.githubusercontent.com/93879362/185753785-48528a37-6b16-473d-b91f-28ad659a184f.mp4

In version 1.5.19 stable one has to addionally click into the category field
to get the last used category (usability + 1 click) and
if you then change the payee, the category of the previous payee stays the same until you click into the
category field:

https://user-images.githubusercontent.com/93879362/185753154-d27b8374-8c25-4408-ae36-f0a765812800.mp4

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Select Payee

Expected result:
previous category for this payee is inserted into category field automatically -with these settings:

![1_5_19setting](https://user-images.githubusercontent.com/93879362/185753287-c97dd3da-b956-4efd-b41c-fd78475b4397.jpg)

Actual result:
you need one more click in the category field (that would be ok)
but
2nd bug: the category field does not change when changing the payee.

**Comment by tactilis** [comment]
Confirmed as same behaviour on Windows.

**Comment by n-stein** [comment]
This behavior only occurs if you start typing in the payee text control then select an item in the virtual listbox generated by autocomplete. If you directly select the payee from the combobox dropdown it fills the category instantly with the correct value, even when previously filled. 

I suspect it has to do with events generated by clicking in the autocomplete listbox not being handled the same way as clicking in the combobox listbox.

**Comment by vomikan** [comment]
This is definitely fixed for the transaction dialog. But switching categories occurs with a delay when changing focus.

**Comment by n-stein** [comment]
@PMaff Give it a test and see if this is the behavior you are expecting.

**Comment by PMaff** [comment]
> @PMaff Give it a test and see if this is the behavior you are expecting.

It is now like before and so it is much better in 1.5.21 !
Thanks @n-stein !

Issue was already closed which is ok.
