### ISSUE TITLE
Integer Custom Field - erroneous behaviour

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4955]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Integer custom fields have incorrect behaviour as shown in the video:
 
https://user-images.githubusercontent.com/4060092/185762853-46b300f6-fded-4254-a8f5-c320382a4579.mp4

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Follow these steps in the video:

1. Type a value in the Integer custom field. Note that the checkbox does not automatically become ticked.
**[Bug 1: The checkbox should become ticked as the user types]**

2. Click _once_ on the checkbox. Note that the tick appears for just a fraction of a second and then disappears.
**[Bug 2: Clicking on the checkbox should set the tick]**

3. Click on the checkbox again. Note that the tick _is_ now displayed.

4. Delete the contents of the custom field and then click once on the checkbox again to untick it. Note that the custom field now contains the value -2147483647.
**[Bug 3: Unticking the checkbox should not change the contents of the custom field]**

**Comment by whalley** [comment]
I can't seem to reproduce this on MacOS.

**Comment by tactilis** [comment]
> I can't seem to reproduce this on MacOS.

None of it?  In 1.5.19?

Not even Bug 1?  So, for you on MacOS, the Integer checkbox becomes ticked as soon as you type a character (like it does for Decimal)?

Different MMEX code for MacOS and Windows?

Different wxWidgets behaviour for MacOS and Windows?

Bug 2 is very puzzling; although it's hard to see in the video, the tick does appear for a moment, then is gone.

Bug 3 is odd as well:  -2147483647 is -(2^31 - 1).  Where's that coming from?

**Comment by whalley** [comment]
> > I can't seem to reproduce this on MacOS.
> 
> None of it? In 1.5.19?

Apologies I was a bit lazy in testing/replying !

> 
> Not even Bug 1? So, for you on MacOS, the Integer checkbox becomes ticked as soon as you type a character (like it does for Decimal)?

Yes, this bug is there.

> Bug 2 is very puzzling; although it's hard to see in the video, the tick does appear for a moment, then is gone.

Can't reproduce this.

> Bug 3 is odd as well: -2147483647 is -(2^31 - 1). Where's that coming from?

I can tick/untick and it does not alter the value in the integer field. But I have noticed that if the field is cleared and then unticked and ticked the previous value is represented.

There is something funny here... Will investigate.

**Comment by tactilis** [comment]
Bug 1
> Yes, this bug is there.

:+1: 

Bug 2
> Can't reproduce this.

So, as soon as you click the checkbox, the tick appears (and stays)?
I get:
- First click; the tick flashes.
- Second click; the tick appears and stays. But you need to follow exactly the steps in the video; i.e open the dialog, clear the field, type some digits, and then click on the (currently unchecked) checkbox.

Bug 3:
> I can tick/untick and it does not alter the value in the integer field.

Yes. Agreed.

> But I have noticed that if the field is cleared and then unticked and ticked the previous value is represented.

I think you may have edited a transaction that already had an Integer custom field saved. Yes, you get the previous value back.

But if I start from a transaction with **no previous value set** and do exactly what I say at step 4 (and show in the video), then I get -2147483647. Same for you?

**Comment by whalley** [comment]
Integer handing show now be the same as Decimal handling but with whole numbers.

**Comment by tactilis** [comment]
Now testing Version: 1.5.20-Beta.1  Git commit: 7270278 (2022-08-25)

@whalley
> Integer handing should now be the same as Decimal handling but with whole numbers.

Unfortunately, there is a bug relating to integer formatting that prevents round-tripping of the integer value when the transaction dialog is repeatedly OK'd and reopened.

I'm demonstrating the bug for an integer custom field, but it may affect other integer fields too. I'll leave you to assess this.

Note that:
- Base Currency is UK Pound (2 Decimal Places and Grouping Char is a space).
- Account Currency is UK Pound.

Watch the value of the custom field in the transaction list and in the edit transaction dialog...
 
https://user-images.githubusercontent.com/4060092/186725856-acc4a800-20dc-4b57-98e8-1e8654403650.mp4

Now I've changed the Grouping Char to comma and I repeat the process...

https://user-images.githubusercontent.com/4060092/186725908-c699af67-26e0-4538-8fb3-3f2e642eb135.mp4

**Comment by whalley** [comment]
@tactilis Good catch... There would have been a similar issue also with DECIMAL's with 0 Decimal Places (in fact DECIMAL with 0 Decimal places is now exactly the same as INTEGER).

**Comment by tactilis** [comment]
Confirmed fixed
