### ISSUE TITLE
The 'Number' Column Evaluates Numbers

### ISSUE THREAD

**Issue by pri4sama** [moneymanagerex/moneymanagerex#4956]
The Number column now evaluates the numbers given. For instance, I used this section for installment payments as 1/24, 6/12 etc. for the past 10 years. But now this gets evaluated to a decimal value. I think it is very useful the older way. Because, the installments can be easily identified that way.

Thank you so much for the great software !!! (I have been using it for 10 years now)

<hr>Version: 1.5.19 64-bit<br>
 • Build: Aug 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22000), 64-bit edition<br>
 •  English (United States) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by techpatriot** [comment]
I can confirm I have the same issue.  I just used the Number column to store check numbers.  Now they get converted to a decimal value after manually entering.  I can click the "populate transaction #" button and it will fill in a whole number, but it'll be the wrong number (as it just happens to be a different number not in sequence).

<hr>Version: 1.5.19 64-bit<br>
 • Build: Aug 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  English (United States) (windows-1252)<br>
 • 2560x1440 32bit 96x96ppi

**Comment by tactilis** [comment]
This issue has been reported already.  Duplicate of #4951

Please could you close this issue so the bug can be tracked under 4951.

**Comment by pri4sama** [comment]
Closing the issue since a duplicate of #4951.
