### ISSUE TITLE
Functionality has been removed

### ISSUE THREAD

**Issue by Asimov940** [moneymanagerex/moneymanagerex#4957]
When entering a new transaction, the Number field under the category field has been changed in version 1.5.19 so that it's numerical only. That's fine, but it has been an alphanumeric field for at least as long as I've been using the app. And that's how I use it. The data structure I use no longer works because no more alpha characters. I can't change my workflow just because of this, so I recovered version 1.5.18 and don't intend to install any more upgrades. I've no doubt making this a numbers only field is terrific for those users who want that for error correction, but there's also the rest of us who have lost the use of the field as we define it.
[Screen 1.pdf](https://github.com/moneymanagerex/moneymanagerex/files/9388996/Screen.1.pdf)
[Screen 2.pdf](https://github.com/moneymanagerex/moneymanagerex/files/9388997/Screen.2.pdf)

**Comment by whalley** [comment]
This is a bug and will be rectified in 1.5.20!
https://github.com/moneymanagerex/moneymanagerex/issues/4951

**Comment by Asimov940** [comment]
Brilliant, thanks!

Jeff.
