### ISSUE TITLE
Problem Number in transactions

### ISSUE THREAD

**Issue by EmanuelJoaoMarquesMiranda** [moneymanagerex/moneymanagerex#4963]
> Substitua este texto (marcado com>) pela descrição detalhada do seu problema.
> Por favor, não remova as informações anexadas abaixo deste texto.

<hr>Version: 1.5.19 <br>
 • Build: Ago 19 2022 15:22:38<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1)<br>
 •  Portuguese (Portugal) (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

Problem:
After the last update of MMEX 1.5.19, the “Number in transactions” field only allows monetary values, and should be free. (as in previous version 1.5.18)

**Comment by whalley** [comment]
Will be fixed in v1.5.20.
https://github.com/moneymanagerex/moneymanagerex/issues/4951
