### ISSUE TITLE
Stock Portfolio Gain/Loss

### ISSUE THREAD

**Issue by babbishkamath** [moneymanagerex/moneymanagerex#4969]
> In my portfolio view I would like to see the gains(profits)made by selling shares in the report or an additional field  in the stats line to show the gains or loss made by the portfolio including the sold shares. Currently it shows only the gain/loss  for active shares. The gains made by selling shares does not reflect on any 'Balance' at present
![123](https://user-images.githubusercontent.com/111977534/186403283-f9d51199-d753-42b5-aa6a-96daa2f0f698.png)

<hr>Version: 1.5.18 64-bit<br>
 • Build: Jul 27 2022 22:24:57<br>
 • db 7 •  (aes128cbc)<br>
 • git 6dba91a (2022-07-28)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22622), 64-bit edition<br>
 •  English (India) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by reddyshyam** [comment]
Hi, not sure if mine is the same issue as well but gain/loss shows the same current price. Please see below.

![image](https://user-images.githubusercontent.com/12392746/189063758-05ef3f5d-a756-4ee1-acf4-60f3eb446902.png)

**Comment by babbishkamath** [comment]
Yes you can see that happening in the last line.



![image](https://user-images.githubusercontent.com/111977534/189487327-84416360-e420-413e-8e0b-2890a4c18d58.png)

**Comment by n-stein** [comment]
@babbishkamath I added the Realized Gain/Loss from sales as a new column (also in the summary report). Check it out once the PR is merged.

@reddyshyam I'm guessing you haven't added any share transactions yet? In the current release your gain/loss will be the same as current total value until you add the first share transaction due to the way investment value is calculated. I have changed this behavior and the gain/loss should appear correctly when you initially create investments.

**Comment by reddyshyam** [comment]
> @babbishkamath I added the Realized Gain/Loss from sales as a new column (also in the summary report). Check it out once the PR is merged.
> 
> @reddyshyam I'm guessing you haven't added any share transactions yet? In the current release your gain/loss will be the same as current total value until you add the first share transaction due to the way investment value is calculated. I have changed this behavior and the gain/loss should appear correctly when you initially create investments.

Hi @n-stein, your guess is correct in my case. Thanks for the fix. Appreciate it. 👍 Will check it out when the next version is out.

**Comment by babbishkamath** [comment]
> @babbishkamath I added the Realized Gain/Loss from sales as a new column (also in the summary report). Check it out once the PR is merged.
> 
> @reddyshyam I'm guessing you haven't added any share transactions yet? In the current release your gain/loss will be the same as current total value until you add the first share transaction due to the way investment value is calculated. I have changed this behavior and the gain/loss should appear correctly when you initially create investments.

Hi @n-stein  I am happy note, waiting eagerly to check it out.
