### ISSUE TITLE
Possible Bug 

### ISSUE THREAD

**Issue by karnak17** [moneymanagerex/moneymanagerex#4970]
> Having just loaded Version 1.5.19 64 bit, I find that when I try to edit at Stock Investment displayed in my Stock Portfolio by inserting a note in the "Note Box" It only seems to accept alpha characters, when I type 'Converted to Class A' it will accept it and Save it but if I type any number e.g. 'Converted to Class 1' and Save it is saved as  numerical digits, in this case it displays 1.00. 
> Please do not remove information attached below this text.

<hr>Version: 1.5.19 64-bit<br>
 • Build: Aug 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
Yes, it is a bug. Fixed here: https://github.com/moneymanagerex/moneymanagerex/issues/4951

v1.5.20 will have the fix.

**Comment by tactilis** [comment]
@karnak17 
If it is causing you a problem, then you can easily reinstall 1.5.18 until 1.5.20 is released.

**Comment by karnak17** [comment]
Thanks very much for the comments, no real problem at present but will revert if necessary
