### ISSUE TITLE
Transaction report - add feature to group by "type"

### ISSUE THREAD

**Issue by epeph** [moneymanagerex/moneymanagerex#4971]
Currently in the transaction report, there is the possibility to group the transactions by category, payee or account. To grant a better overview about withdrawals and revenues, it would be great to have the opportunity to group by "type" as well.
![Bildschirmfoto 2022-08-24 um 21 50 28](https://user-images.githubusercontent.com/112021234/186510167-baf975c8-91a6-4d4b-aef0-4eda0fc0e9a4.png)

**Comment by whalley** [comment]
Seemed a good suggestion and easy to implement.
