### ISSUE TITLE
Auto-fill for text fields is incomplete when "/" is in the suggestion

### ISSUE THREAD

**Issue by Gigific** [moneymanagerex/moneymanagerex#4976]
MMEX version:
 - [x] 1.5.17
 - [x] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [x] Other (Seems to be a very old bug)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When you have a category, payee or account that has a "/" in the name and you start typing it the field, the auto-fill function will crop the text till the first "/". It is necessary to explicity select the complete text from the drop-down menu to have it imported completely.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1) Start typing an item name that has a "/" as part of the text:
![immagine](https://user-images.githubusercontent.com/110192669/186750644-b11bd55e-73a1-4aba-81eb-956b6652d3ff.png)
2) See that only part of the name is suggested. If you hit the TAB key to move to another field, then the incomplete text is used. If you use an arrow key to highlight the text from the drop-down menu, then the text is imported completely.

Expected result:
Suggestion should be complete regardless of special characters in the item name.
Actual result:
Sometimes the suggestion is incomplete when non-alphanumeric characters are present in the item name
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
This may be a windows limitation; the MacOS implementation does not support the auto-filling on TAB navigation at all.

https://social.msdn.microsoft.com/Forums/en-US/ee7f05b9-3ce2-4485-8e21-e83a6a54b917/autocomplete-ends-at-forward-slash?forum=winforms

Despite this being an old discussion I can still find no option for this: https://docs.microsoft.com/en-us/windows/win32/api/shldisp/ne-shldisp-autocompleteoptions

**Comment by tactilis** [comment]
@Gigific You will either need to use the arrow key to highlight the text from the drop-down menu, or use a different character to separate the two parts of your category name.

_All_ non-alphanumeric characters, except / and \  (and : which MMEX reserves as its category:subcategory delimiter) work correctly.

For example, this category name works as expected: ```ABC`¬¦!"£$%^&*()-_=+[]{}|,.<>? DEF```

**Comment by Gigific** [comment]
Thank you! I edited my accounts and categories containing a "/" with a "-" and the auto-fill worked perfectly!

**Comment by whalley** [comment]
Nothing we can do as it's a windows API related issue that we cannot overcoem.
