### ISSUE TITLE
Integer and decimal custom values are not right aligned in the transaction list

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4977]
MMEX version:
 - [ ] 1.5.20 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In the transaction list, integer fields are left aligned.

The values should be right aligned.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create an integer and a decimal custom field and populate several transactions with progressively larger values.

Expected result:

The integer and decimal values should be right aligned as per the entry field on the transaction dialog

Actual result:

![image](https://user-images.githubusercontent.com/4060092/186767241-2ef31572-236c-434c-850a-edc4059a72b8.png)

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4868
