### ISSUE TITLE
Advanced Filter not saving new 'Date Range' value

### ISSUE THREAD

**Issue by rusty6285** [moneymanagerex/moneymanagerex#4982]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x ] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When applying an advanced filter and selecting a new data range, the new filter only applies the one time, and reverts to a different (prior) value when restarting the application, or even when navigating to a different account.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
Think it is more general than that as it doesn't correctly save the Advanced settings. Also spotted a validation error on the data range.

**Comment by whalley** [comment]
Thought I had fixed this but there are still some issues here....
