### ISSUE TITLE
Operation number automatically converted to numeric when contains a numeric value

### ISSUE THREAD

**Issue by GhaziTriki** [moneymanagerex/moneymanagerex#4983]
MMEX version:
 - [x] 1.5.19

Operating System:
 - [x] Windows

# Description of the bug

When creating or updating an operation, the number field gets automatically converted to numeric if it contains a numeric value.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

Create a new operation and add number than contains a numeric value.

Expected result:

Value should stay the same. It has never been the case, being a `Money Manager Ex` since 2013.

Actual result:

The value is evaluated to number.

# Additional information
![operation_number](https://user-images.githubusercontent.com/4991088/187073770-08976163-a51a-4662-873b-8ae73211e749.gif)

**Comment by tactilis** [comment]
Duplicate of #4951 

Thanks for reporting this. This is a known problem and will be fixed in v1.5.20.

Please revert to 1.5.18 until 1.5.20 is out if this bug is causing you problems

**Comment by GhaziTriki** [comment]
Thanks @tactilis.
