### ISSUE TITLE
Boolean and Date custom field improvements

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4987]
MMEX version:
  - [x] 1.5.20 Beta
 
Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

1. The control (a checkbox) for setting a Boolean custom field value is not consistent with the display of the Boolean value in the UDCF column. Also, the control is currently positioned on the far right and looks out of place.

2. The format of dates in the UDCF column does not match the selected in Options | General | Date Format. 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

1. The control for Boolean should be a FALSE/TRUE dropdown that is left aligned.
2. The custom control date format on the transaction list should match the format of the transaction date.

![image](https://user-images.githubusercontent.com/4060092/187096459-784ef4f2-af4d-48ee-b95c-926d9a2e3a00.png)

**Comment by whalley** [comment]
- Date format fixed...
- Have left the boolean as a checkbox (now left justified on entry dialog) but it is now presented as a cross or tick in the account view. If the user wants FALSE/TRUE they can use the use the 'SINGLECHOICE' field type and define a boolean themselves.

**Comment by tactilis** [comment]
Now testing 1.5.20-Beta.1 commit: 9377dc1 (2022-08-29)

Opening the same database as above, resulted in:

![image](https://user-images.githubusercontent.com/4060092/187250692-1e6eb3fe-30dc-4d2a-b480-d58717e51fd3.png)

**Comment by whalley** [comment]
I get:
![CleanShot 2022-08-29 at 17 49 02](https://user-images.githubusercontent.com/487345/187252663-efea18d1-ca52-4fec-b13d-13d2435b900e.png)

Unicode issue?

**Comment by whalley** [comment]
I need to also make the same change to the transaction report.

**Comment by vomikan** [comment]
Just FYI
U+2713 ✓
U+2717 ✗

**Comment by tactilis** [comment]
> Unicode issue?

> Just FYI    U+2713 ✓   U+2717 ✗

Yep. Checked that.

What font is used in the transaction list?

**Comment by whalley** [comment]
@vomikan Do you have the same issue with U+2713 and U+27217 being used on the list control to show the boolean status?

**Comment by vomikan** [comment]
There are no issues in the report and transaction panel.


|![image](https://user-images.githubusercontent.com/6836805/187281765-0ef77982-34ec-4832-8aa1-38837f7ebf99.png)  ![image](https://user-images.githubusercontent.com/6836805/187281829-1c935415-4b6d-4f36-8c83-f6132ac93a2b.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/187282112-e16c3d4e-6ca8-4a50-94d9-99f43616b70e.png)

here ould be better to use wxRadioButton

**Comment by whalley** [comment]
> ![image](https://user-images.githubusercontent.com/6836805/187282112-e16c3d4e-6ca8-4a50-94d9-99f43616b70e.png)
> 
> here would be better to use wxRadioButton

Yes, it may be a bit more obvious to have a False/True radio button.

**Comment by whalley** [comment]
> Now testing 1.5.20-Beta.1 commit: [9377dc1](https://github.com/moneymanagerex/moneymanagerex/commit/9377dc121ce4d22237df0ea3b622624da721884e) (2022-08-29)
> 
> Opening the same database as above, resulted in:
> 
> ![image](https://user-images.githubusercontent.com/4060092/187250692-1e6eb3fe-30dc-4d2a-b480-d58717e51fd3.png)

Have tested latest build on my Dev Win11 VM and get the same results....

**Comment by whalley** [comment]
@tactilis Please test latest build. The unicode characters now work fine on my Win VM.

**Comment by tactilis** [comment]
Now testing 1.5.20-Beta.1 commit: 5490458 (2022-08-30)

@whalley The cross and tick are now displayed, although the tick looks 'odd'. It's not the nice looking tick shown in your and @vomikan's screenshots.

It's the same symbol that is shown (on my PC) in the Currency dialog:

![image](https://user-images.githubusercontent.com/4060092/187377051-9a6da39b-13a9-4b4a-a2dc-66b67529c0ac.png)

From @vomikan's earlier comment, it is clear that my PC _is_ capable of displaying the tick correctly:

![image](https://user-images.githubusercontent.com/4060092/187381716-22fd4089-38a0-472e-99ad-9f9c91497e2d.png)

So there's something different happening in MMEX. Font related perhaps?

**Comment by whalley** [comment]
> From @vomikan's earlier comment, it is clear that my PC _is_ capable of displaying the tick correctly:

I suspect that is how it is presented in the transaction report webview.

**Comment by tactilis** [comment]
> So there's something different happening in MMEX. Font related perhaps?

I've just tried pasting the characters into the MMEX Notes field and get the same odd looking tick:
 
![image](https://user-images.githubusercontent.com/4060092/187384205-d04fbf2a-6b82-485d-a7da-7c44ff9995f5.png)

Then I tried pasting the same text into several other applications and they all display the good looking tick  ✓

**Comment by tactilis** [comment]
>> From @vomikan's earlier comment, it is clear that my PC is capable of displaying the tick correctly:

> I suspect that is how it is presented in the transaction report webview.

Yes.

![image](https://user-images.githubusercontent.com/4060092/187387685-f8ef4926-9c91-4641-90ed-7165f753ffc4.png)

**Comment by whalley** [comment]
Have you changed any system font settings on your Windows machine? On a base Windows 11 install it looks fine:
<img width="215" alt="CleanShot 2022-08-30 at 11 03 50@2x" src="https://user-images.githubusercontent.com/487345/187409725-1dfc6e20-94e3-4b01-9465-6bd64af325f9.png">

Have tried on corporate work laptop and also works fine...

**Comment by tactilis** [comment]
> Have you changed any system font settings on your Windows machine?

I'm not aware of any "system font settings" that can be changed.

I certainly haven't removed any fonts from the system.

**Comment by tactilis** [comment]
The puzzling thing (to me) is that the tick displays OK in other applications I paste the character into.

**Comment by whalley** [comment]
Not sure what else we can do to help, you may need to investigate/experiment a bit... or may need to live with the 'ugly' tick :-).   I just booted up an old Win10 laptop I have and installed MMEX. The tick looks the same as my Win 11 VM.

**Comment by tactilis** [comment]
> you may need to investigate/experiment a bit

In case it helps anyone else...

I have found out what font is causing the ugly tick, but not yet why it is being used for the tick and cross characters in MMEX on my PC.

Using Chrome I went to https://wordmark.it and entered  ✓ ✗ and selected 'Your Fonts'.

Scrolling, through the fonts, revealed that the offending one was the Meiryo font family.
 
![image](https://user-images.githubusercontent.com/4060092/187443248-befffe24-ce09-45a1-a524-e7386088468d.png)
 
Looking in the Fonts folder shows that Meiryo and Meiryo UI is a Japanese font. Apparently they are installed by Microsoft as part of Office.
 
![image](https://user-images.githubusercontent.com/4060092/187443669-b0c25a41-7105-4aa2-a4c9-773487c916dd.png)

Unfortunately, you cannot simply delete Meiryo and Meiryo UI because they are protected system fonts:
 
![image](https://user-images.githubusercontent.com/4060092/187444063-99ed6f1e-c2cf-49a3-a6e7-3913551b084d.png)

WikiHow shows how to work around this [https://www.wikihow.com/Delete-Protected-System-Fonts-in-Windows-7](https://www.wikihow.com/Delete-Protected-System-Fonts-in-Windows-7)

The steps to take ownership of the font and delete it are fairly lengthy. I don't plan on doing this now, as I will be moving to Windows 11 soon (new laptop).
