### ISSUE TITLE
Category collapsed state

### ISSUE THREAD

**Issue by norameme** [moneymanagerex/moneymanagerex#4989]
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.

<hr>Version: 1.5.19 64-bit<br>
 • Build: Aug 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1776x1000 32bit 96x96ppi

<BR><br>
Request/Issue
<br>
Remembering if the tree was opened or collapsed on refresh:
<br>
Details: when I was going through the categories, some items I have collapsed to remember that I already review that category in full.  As I was reviewing the rest - every time I added or edited a category, the list will refresh (as it should) but all categories and subcategories would be opened again. It would be great if the refresh can remember that the category has been collapsed and refresh with that category collapsed.

**Comment by whalley** [comment]
Spotted an error in the "Show All" logic handling, will fix.
