### ISSUE TITLE
Asset Name and Asset Notes - numbers only

### ISSUE THREAD

**Issue by norameme** [moneymanagerex/moneymanagerex#4990]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Bug/Issue: Asset Name and Notes - only numbers

If the Asset name or not in the asses have numbers and letters - only numbers would be displayed

In the assets view I have created new assets; and every time when I wanted to name an asset - it had to be either letters ONLY because if the asset name will have letters and numbers - only numbers would be displayed and with the decimal of 2 - i.e. name: assets 1=> will be displayed as 1.00 when created.

There is no way of correcting that unless I use letters only.

The same with the comments field in the assets - absolutely the same situation as above - must be letters ONY or it will be displayed as a number:
For example: Notes created: ' the evaluation of the assets was performed on 22 July 2022' ->> on creation or on refresh would read -> 22.00.

the same if I try to amend the notes field - if there will be numbers in addition to letters or symbols, the only numbers would be retailed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Fixed here. https://github.com/moneymanagerex/moneymanagerex/issues/4946

Fix will be in v1.5.20. You can revert back to v1.5.18 if it is causing you an issue.
