### ISSUE TITLE
Number field forces decimal notation from 1.5.19

### ISSUE THREAD

**Issue by iugrina** [moneymanagerex/moneymanagerex#4991]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

I was able to add numbers to the number field previously without these numbers becoming "real" decimals, i.e. 1021 becoming 1,021.00

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Create a new entry and add a number (e.g. 1021) to the number field. MMEX will automagically create 1,021.00 out of it.

Expected result: 1021

Actual result: 1,021.00

# Additional information

I have a lot of reports to work with numbers  from the Number field and they don't work anymore since 1,021.00 doesn't match 1021 and similar.

**Comment by whalley** [comment]
Fixed here. https://github.com/moneymanagerex/moneymanagerex/issues/4946

Fix will be in v1.5.20. You can revert back to v1.5.18 if it is causing you an issue.
