### ISSUE TITLE
RIFERIMENTO ALFANUMERICO NEL CAMPO NUMERO

### ISSUE THREAD

**Issue by maxime1163** [moneymanagerex/moneymanagerex#4998]
> Fino alla versione 1.5.18 nell'inserimento di una operazione dei conti bancari era possibile registrare nel campo "Numero" anche un riferimento ALFANUMERICO (alphanumeric string).
> Dalla versione 1.5.19, se si inserisce nel campo "Numero" un riferimento ALFANUMERICO (alphanumeric string), questo viene trasformato dall'applicazione in un numero.
> N.B.: nel DB il campo TRANSACTIONNUMBER della tabella CHECKINGACCOUNT_V1 è correttamente impostato a TEXT. Quindi l'applicazione NON dovrebbe convertire in numero un riferimento ALFANUMERICO

<hr>Version: 1.5.19 64-bit<br>
 • Build: Ago 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1680x1050 32bit 96x96ppi

**Comment by tactilis** [comment]
Duplicate of https://github.com/moneymanagerex/moneymanagerex/issues/4951

Thanks for reporting this. This is a known problem and will be fixed in v1.5.20.

Please revert to 1.5.18 until 1.5.20 is out if this bug is causing you problems
