### ISSUE TITLE
Boolean custom field misalignment

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4999]
MMEX version:
 - [x] 1.5.20 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The use of radio buttons for Boolean custom field is a good improvement (thanks @vomikan & @whalley).

However the field label and the controls are no longer aligned due to the use of a radio box.

The radio box is not necessary since there is no box title. The radio buttons alone are sufficient and look neater.

Removing the radio box will also bring the custom fields back into alignment with the transaction fields.

Current layout:
 
![image](https://user-images.githubusercontent.com/4060092/187466460-6bc8f4e8-f417-4592-a09e-98764085ae80.png)
 
Proposed layout:

![image](https://user-images.githubusercontent.com/4060092/187467299-e92a1854-4520-4414-8345-484bb2e1919c.png)

**Comment by vomikan** [comment]
There is an options to change it to wxSlider

**Comment by whalley** [comment]
> The radio box is not necessary since there is no box title. The radio buttons alone are sufficient and look neater.

Not quite as simple as you may think. The way the custom field logic works it allows only a single widget for the control. To use 2 radio buttons would break this unless I encapsulated it into a single control. I did look at removing the border on the radiobox but wxWidgets does not seem to support that. 

> There is an options to change it to wxSlider

That would work, perhaps we have middle value on the slider, to offer some form of quantum state :-)

My other favoured option is a simple wxToggleButton that switches between False/True when pressed.

**Comment by tactilis** [comment]
@vomikan
> here is an options to change it to wxSlider image

Personally, I think that your idea to use radio buttons is perfect. The purpose and usage of this UI is very clear.

The only issue I was pointing out was the vertical alignment

**Comment by tactilis** [comment]
Ah, I've just see @whalley's post. I understand the problem now.

> My other favoured option is a simple wxToggleButton that switches between False/True when pressed.

In which case, we may as well stick with my False/True dropdown button (what is it called in wxWidgets please?)

**Comment by tactilis** [comment]
> perhaps we have middle value on the slider, to offer some form of quantum state

:smile:

**Comment by tactilis** [comment]
> To use 2 radio buttons would break this unless I encapsulated it into a single control.

Is that a lot of work?  The side by side radio buttons look great.

**Comment by whalley** [comment]
> Is that a lot of work? The side by side radio buttons look great.

Probably not... let me see.

**Comment by whalley** [comment]
Now wxRadioButton's - Made a bit of 'headroom' for multiple widgets per custom item, and some boolean specific handling.

**Comment by vomikan** [comment]
Excellent!

![image](https://user-images.githubusercontent.com/6836805/187524325-4efdf78b-b74a-4aed-bb6a-e807684ad8f5.png)

**Comment by tactilis** [comment]
>  radio gaga (https://github.com/whalley/moneymanagerex/commit/421b694acf250d722e1c7b4e0eeef71469c9a6b8)

Radio goo goo!

Well done.
