### ISSUE TITLE
Saved Transaction Reports don't work in Linux

### ISSUE THREAD

**Issue by thomasboehm** [moneymanagerex/moneymanagerex#5000]
MMEX version:
 - [ ] 1.5.17
 - [] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

When saving a Transaction Report with a category as filter, it returns an empty report when I run it the next time. The Category in the Filtering Details is empty, even though I can see it in the database when looking into it with SQLiteBrowser.

![](https://i.imgur.com/FYbo8Rd.png)

It works when I use a Payee as filter instead.

In Windows it works with the same database though.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Create a transaction report, select a Category as Filter and save it. The Transaction Report works from this window as expected, but when I return later and click the saved Trransaction Report, it is empty.

Expected result:

Saved Transaction Reports should work.

Actual result:

Saved Transaction Reports are empty.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
I can't reproduce this on Windows.

**Comment by whalley** [comment]
Can't reproduce on MacOS either.

@thomasboehm Can you should us what the SQLiteBrowser is showing for the report detail.

**Comment by vomikan** [comment]
@thomasboehm 
Could you please do a simple investigation. You need to launch the report manager ![image](https://user-images.githubusercontent.com/6836805/187527353-ae214879-2350-4c4d-a34c-5629e5060bd6.png)
. Create a new report via the context menu of the navigation tree. In the new report, insert the following script in the SQL tab and execute it.
Show the output.

![image](https://user-images.githubusercontent.com/6836805/187526756-c8db4e09-0167-4af9-8da9-4c5bbe19b263.png)

```
select INFOVALUE from INFOTABLE_V1
where INFONAME='TRANSACTIONS_FILTER'
```

**Comment by thomasboehm** [comment]
> I can't reproduce this on Windows.

As I wrote, it only happens in Linux.

> Can you should us what the SQLiteBrowser is showing for the report detail.

`[
    "{\n    \"LABEL\": \"Amazon\",\n    \"PAYEE\": \"Amazon\",\n    \"CATEGORY\": \"Homeneeds:Equipment\"\n}"
]`

**Comment by vomikan** [comment]
Let's try to make a report. Everything is as I described above, but you still need to click the 'Create Template' and Save buttons. There we will see how MMEX itself, and not a third-party program reads the data.

![image](https://user-images.githubusercontent.com/6836805/187529104-f868b391-e303-4f56-ae29-2a50b00e2487.png)

**Comment by thomasboehm** [comment]
The output is the same. For some reason I cannot copy and paste the text from the output, so here's a screenshot

https://i.imgur.com/4WpNL3q.png

I guess the problem doesn't lie with the database as it works in Windows and MacOS, it seems to be a problem with the Linux client.

**Comment by tactilis** [comment]
@thomasboehm FYI, you don't need to put screenshots on imgur and link to them from here.

You can just paste the image straight into the github discussion. You can see the image if you click on the Preview tab.

**Comment by thomasboehm** [comment]
> @thomasboehm FYI, you don't need to put screenshots on imgur and link to them from here.
> 
> You can just paste the image straight into the github discussion. You can see the image if you click on the Preview tab.

I tried earlier and it didn't work.
![Selection_065](https://user-images.githubusercontent.com/9038242/187540416-85c33d40-c5f1-47e2-9514-a59332556d7c.png)

Now it does after adjusting ublock origin.

**Comment by whalley** [comment]
Confirmed this is an odd Linux issue. I have replicated this on Ubuntu 20.04.

**Comment by whalley** [comment]
Initial setup of transaction filter
![CleanShot 2022-08-31 at 00 20 18](https://user-images.githubusercontent.com/487345/187560270-d50b9285-0855-4dc6-aebc-66ff4813a178.png)

Run against this filter
![CleanShot 2022-08-31 at 00 20 47](https://user-images.githubusercontent.com/487345/187560327-b3b377ba-a659-4c68-8715-080cd768c851.png)

Go back to edit filter
![CleanShot 2022-08-31 at 00 21 15](https://user-images.githubusercontent.com/487345/187560364-6e5f8790-b8b9-4cee-9038-9e6dbced6298.png)

So it's recognising that there is category data in the setting but not able to retrieve/display.

**Comment by vomikan** [comment]
> I tried earlier and it didn't work.

just manually insert the url into markdown conteiner ```![](http....)``` thank you in advance
![image](https://user-images.githubusercontent.com/6836805/187644502-908b8e09-ffe2-4740-b293-35be41ff1e99.png)

**Comment by whalley** [comment]
@thomasboehm Should be fixed now. You can try one of the linux builds with the fix here: https://app.circleci.com/pipelines/github/whalley/moneymanagerex/88/workflows/7328cf7d-618f-4753-949f-fe2b0141e514/jobs/158/artifacts

**Comment by thomasboehm** [comment]
Thank you very much. It works as expected with this version.
