### ISSUE TITLE
Date custom field focus and update issues

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5003]
MMEX version:
 - [x] 1.5.20 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

1. The Date custom field (and by extension, all date fields) do not gain focus when the user clicks the up/down buttons. They should do.

2. The Date custom field enable/disable check box does not become ticked when the user clicks the up/down buttons. It should do.

3. The Date custom field on the transaction dialog updates when the user clicks the up/down buttons but the new date is not saved when OK is clicked. It should be saved.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Watch the video and note:

1. Focus is initially on the transaction's Date field as expected.
2. Focus does not move to the Date custom field when its up/down buttons are clicked.
3. The Date custom field enable/disable check box does not become ticked automatically.
4. After the transaction is saved and reopened, if the custom field date is changed using the up/down buttons, the change is not saved when the transaction is saved.

https://user-images.githubusercontent.com/4060092/187536502-4477a4d4-2b07-4519-b71f-8a263128871e.mp4
 
 
Sorry @whalley - I bet you thought you were finished with Custom Fields!  :smile:

**Comment by whalley** [comment]
> Sorry @whalley - I bet you thought you were finished with Custom Fields!

I don't bloody use these fields so am getting no material benefit from this work :-)

Found an error with Date Calendar functionality also so that is a positive!

**Comment by tactilis** [comment]
> I don't bloody use these fields so am getting no material benefit from this work :-)

But you'll get a lot of kudos (from those that do) :+1: :+1:

**Comment by tactilis** [comment]
Confirmed fixed. Thank you.
