### ISSUE TITLE
Place focus in the Search field when Organize Categories dialog is opened

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5016]
# Description of the feature

Change the Organize Categories dialog so that when it is opened (from the Tools menu, the Toolbar button, or by pressing Enter in an empty Category combobox) the Search field has focus.

# Use cases

1. Would permit immediate searching (filtering) of the categories without having to click in the Search field every time.
2. Would make the behaviour of the Organize Categories dialog consistent with Organize Payees, which does focus the Seach field when it is opened.

Suggestion was raised here https://github.com/moneymanagerex/moneymanagerex/discussions/5015

**Comment by whalley** [comment]
It already does this for me on MacOS.

**Comment by whalley** [comment]
Yes, I don't actually see how it does this on MacOS!!!... But the above fix should do it on all platforms.

**Comment by tactilis** [comment]
Confirmed fixed now.
