### ISSUE TITLE
Bitcoin settings

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5018]
https://user-images.githubusercontent.com/6836805/187896854-c14802df-fc97-4498-bd20-8e8aec056927.mp4

![image](https://user-images.githubusercontent.com/6836805/187897051-521a8dc8-d313-452f-9f3a-7bb0e9507334.png)

![image](https://user-images.githubusercontent.com/6836805/187897498-b5edd431-e11d-4db3-a767-bcf896526ce5.png)

**Comment by vomikan** [comment]
I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/6836805/187907754-6bb83173-4951-443f-9515-4a5cea7b94e7.png)

![image](https://user-images.githubusercontent.com/6836805/187907878-44338607-69e8-4ec8-891d-2b12e0b2d816.png)

![image](https://user-images.githubusercontent.com/6836805/187907967-2e06a6b7-cf03-4349-9384-6a595ce97cf0.png)

**Comment by whalley** [comment]
Neither can I the precision calculation for BTC seems to work fine. Do we know what build this was?

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/187909964-2acbbad8-4172-4aa0-b8cc-3b6a03515b51.png)

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44647705/job/1xo2n96m1jbod7g1/artifacts

Fixed already in beta 1.5.20
