### ISSUE TITLE
Display 'Split Summary' infotip sometimes not displayed

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5019]
MMEX version:
 - [x] 1.5.20 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Proficient users of MMEX tend to have have Show Tooltips turned off to avoid the repeated display of tooltips describing functionality that the user is already very familiar with.

![image](https://user-images.githubusercontent.com/4060092/187912078-82fac23f-09b4-40f5-b58e-ad5b47b4c267.png)

Unfortunately, when tooltips are off, the useful Split Summary 'infotip' (see below) that would otherwise be displayed when hovering over the split button, is no longer shown.

![image](https://user-images.githubusercontent.com/4060092/187912219-91ea515d-866f-4b4a-ac4c-29eaedb5a7e9.png)

Expected Result: As the Split Summary infotip is a different type of 'tooltip' from those that simply describe a button's purpose. The Split Summary infotip should be displayed even if the Show Tooltips option is off.

**Comment by whalley** [comment]
@tactilis Are you sure? Having looked at the code and tested this 'tooltip' IS displayed regardless of the tooltip setting.

**Comment by tactilis** [comment]
This is weird. I cannot reproduce it now. Although I was sure enough about it at the time.

And if the code shows that it is displayed regardless of the tooltip setting, then I must have been mistaken. Apologies for wasting your time.

**Comment by tactilis** [comment]
@whalley
I've reopened this issue as there is definitely something odd happening leading to the non-display of the Split Summary infotip.

Today when using the latest build (1.5.20-Beta.1 commit: c9956e0 (2022-09-01)), I observed the _same_ incorrect behaviour as reported above, i.e. **no display** of the Split Summary infotip when hovering over the Split button - however, this time it was with the option Show toolips **turned on** - but the odd thing was that the normal 'Use split Categories' tooltip was not displayed either, despite having the option on.

I have no idea how I triggered this behaviour, so while investigating, I closed MMEX, restarted it and created a new split transaction. This time, as you can see in the video, the 'Use split Categories' tooltip was displayed before defining the split (as expected) but also **after** the split was defined (display of Split Summary infotip expected):

https://user-images.githubusercontent.com/4060092/188078651-619fc3c9-9f27-4ee0-b97c-1d3d475a84cc.mp4

I'll keep investigating...

**Comment by whalley** [comment]
Yes, a slightly different case. Have fixed.

**Comment by tactilis** [comment]
> Yes, a slightly different case. Have fixed.

Unfortunately, it's not fully fixed yet.

Further investigation shows that the bug shown here https://github.com/moneymanagerex/moneymanagerex/issues/5019#issuecomment-1235154956 (i.e display of the 'Use split Categories' tooltip instead of the Split Summary infotip) 'is related to the transaction not yet having been saved.

This is what happens if Option Show tooltips is on:

1. New Withdrawal...
2. Click the Split button, enter the splits, click OK.
3. Hover over the Split button. ' The 'Use split Categories' tooltip is displayed instead of the Split Summary infotip. :-1:
4. Select a payee and OK the transaction to save it.
5. Open the saved transaction.
6. Hover over the Split button. The Split Summary infotip is displayed. :+1: 

If Option Show tooltips is off, everything works as expected:

1. New Withdrawal...
2. Click the Split button, enter the splits, click OK.
3. Hover over the Split button. The Split Summary infotip is displayed. :+1: 
4. Select a payee and OK the transaction to save it.
5. Open the saved transaction.
6. Hover over the Split button. The Split Summary infotip is displayed. :+1:

I still don't know how I got the into the situation with a spilt defined but no infotip (or tooltip) displayed at all. If you are able to fix the above, I'll keep probing.

**Comment by whalley** [comment]
Have followed steps and I cannot reproduce.

**Comment by tactilis** [comment]
Does this (the latest) not contain your fix?

![image](https://user-images.githubusercontent.com/4060092/188140216-49256ff8-f0d2-4c50-b626-dd7a5b37fdfb.png)


https://user-images.githubusercontent.com/4060092/188140259-aea8f239-7ac2-49d3-8b45-1eadf6d82d86.mp4

**Comment by whalley** [comment]
> Does this (the latest) not contain your fix?

Nope, looks like the CI build was cancelled. Think @vomikan is preparing for the v1.5.20. So probably best to wait for that.

Trust me, the issue you raised is fixed :-)

**Comment by tactilis** [comment]
> Trust me, the issue you raised is fixed

Indeed it is. Thank you Mark.

I'm glad that all these odd little bugs are being knocked on the head.
