### ISSUE TITLE
Deux chiffres après la virgule pas nécessaire 

### ISSUE THREAD

**Issue by dan03410** [moneymanagerex/moneymanagerex#5020]
Dans cette nouvelle version dans la colonne "Numéro" le chiffre apparait maintenant avec deux chiffres après la virgule, ce qui n'et pas nécessaire pour ce numéro.

ENG: In this new version in the "Number" column the number now appears with two decimal places, which is not necessary for this number.

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.5.19 64-bit<br>
 • Build: Août 19 2022 15:12:04<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414 (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  French (France) (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by whalley** [comment]
It's a known bug. See https://github.com/moneymanagerex/moneymanagerex/issues/4951

It will be fixed in 1.5.20.

In the meantime, if it is causing you problems then you can reinstall MMEX 1.5.18 and continue as before.
