### ISSUE TITLE
Share prices rounded to 2 decimal places in 6 precision

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#5032]
MMEX version:
 - [X ] 1.5.19
 
Operating System:
 - [ ] Mac OSX
 
When entering share prices into the dialog I select the date, enter the share prices (0.7464) and on clicking Add button, it rounds to 2 decimal places (0.75). Another share prices enter 0.7743 rounds to 0.77.  This also happens on the entering share price on the left side where 'Save' recalculates the investment values.

# Reproduction
Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
- double click investment and open Edit Stock Investment dialog opens
- click Add button and enter/edit the date and stock price of the investment 0.7464 and then click add
- new row added (if new date) or existing row updated with a 2 decimal places 0.75

- edit Curr. Share Price values in 
Expected result:
- New share prices entered in the Stock History Options list with 4 decimal places.
- Share Values calculated on 4 decimal place value.

Actual result:
- New share prices entered in the Stock History Options list with 2 decimal places.
- Share price values are rounded to 2 decimal places.

**Comment by siowena** [comment]
<img width="673" alt="After Screen Shot 2022-09-02 at 16 57 30" src="https://user-images.githubusercontent.com/44472390/188193318-d1b93595-2ccf-4bb5-b558-d4c610053838.png">
<img width="675" alt="Before Screen Shot 2022-09-02 at 16 56 49" src="https://user-images.githubusercontent.com/44472390/188193337-12cacc68-ba1e-43f8-b1a7-5a7ae2fad610.png">

Added screenshots before and after Add/Save buttons clicked.

**Comment by siowena** [comment]
<img width="675" alt="Before Add Screen Shot 2022-09-02 at 17 00 52" src="https://user-images.githubusercontent.com/44472390/188193644-458da796-b1fd-4098-8505-f3cb4fe4ff30.png">

**Comment by renato-mmex** [comment]
Perhaps this setting is not correct:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/76920138/188194769-441caef3-b917-4afe-b72d-268a42f9415a.png">

**Comment by tactilis** [comment]
@siowena 
Please update to version 1.5.20, which was released today, and report whether you still have the problem.

**Comment by tactilis** [comment]
I've just tested 1.5.20. The bug as reported above appears to be fixed.
