### ISSUE TITLE
Filter on Date / Period - Will not pick up current date and date range including current date.

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#5035]
MMEX version:
 - [X] 1.5.20 64 bit Latest Release not Beta

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 

# Description of the bug
Entries made with today's date not being picked up with Filter.
1. I made entries today, 
2. I went to check with the latest release which 'Number' fields where corrupt due to previous MMEX release problem with that field.
3. I used the Filter to show all records for the last 20 days or so.
4. When applying the filter including today's date the on screen error says "Invalid Value - Date"
5. When I also chose Date Range with both start and finish dates of today, (Default) if you only click "Date Range" it works.
6. But no results appear of today's transactions!

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
1. Open MMEX
2. Add entries to any account etc with today's date. (Important)
3. Close the database if you want but it makes no difference to the bug.
4. Click Top line "Funnel" icon for Filter
5. Click into tick box for "Date range" (No other items picked ie all defaults)
6. Default "From" and "To" are today's dates (No labels "From" and "To" but for assistance.)
7. Click OK
8. No results . (This is a Bug)
9. Open Filter again.
10. Date Range "From' ONLY, set to a past date.
11. Click OK
12. "To" date area error message "X Invalid Value - Date"
13. Open Filter again with Period Range clicked.
14. From drop list one option is 'Today" - Pick that
15. It works but no results even though an entry was made today! - (This is a Bug)
16. I also tried 'Current Month" Same result but all entries up to yesterday displayed. (This is a Bug)
17. I would believe all other periods would have same result in missing today's entries.

Expected result:
All of the above should include today's entries in the displayed filters. 

Actual result:
Filter rejects displaying today's entries and calls an error if today's date is From and To.
Period selections also only show up to yesterday's transactions. Will not show today's in any format requested.

# Additional information
Only discovered this bug today when checking previous entries for 'Number' issue introduced in prior MMEX releases.
I see in the Report "From and "To" are called "Since" and "Before" (noticed on screen after report created)

If you have a backtrace for a crash or a warning, paste it here.
![Date Bug in Filter with Today Date](https://user-images.githubusercontent.com/14268231/188249545-9909d45c-bfe7-4ee0-8636-7d44dd3ef9a5.jpg)
![Filter on Today Start End](https://user-images.githubusercontent.com/14268231/188249550-7614e72d-1a97-4a4d-b6d2-266e6e9e0fcb.jpg)

**Comment by tactilis** [comment]
Bug reports confirmed.

- 'Invalid Value'  if To Date is set to today's date.
- Today's transactions not included in the report if date range is set to the current day.

As a workaround until this is fixed, you can set the To Date to a future date (e.g 04/09/2022 in the above example).

**Comment by SJK55** [comment]
Thanks tactilis, I tried the work around but my app is doing a lot of nothing.
Spinning circle been going for a while! (minute or 2) It seems a hard ask for future date but works eventually!
I did speed it up by narrowing it to one account type instead of all. But it then harks the question, the filter should only look at dates (reduced subset) and maybe work on account selected after? (might speed it up?) Just an observation.

**Comment by SJK55** [comment]
Just one more on this same bug.
I noted when as above I set dates to yesterday and one day in the future (as you suggested) it 'appeared' to pick up the selected account with today's entries.
I say 'appeared' as one entry from today did not appear. I wondered why.
Initially it seems it that entry status was default or Unreconciled ie I didn't add any status to it. I changed it to Reconciled and I believe it appeared in the next filter.
But next time I did the same filter, regardless of Reconciled or Unreconciled, it won't appear after the filter processes.
Just this entry.  (I can't work out why?)
I've tried this at least 10 times with same result. Got me why the work around only works on a few entries not all?
I added 2 new entries for today later and they both appear! This is bizarre! Still will not show the other one from today!
I even deleted the one entry that can't be seen in the date filter using the forward date method.
I added new entry to see if a glitch was affecting this one entry. Made no difference. It doesn't see this entry. Very odd.
The one the filter can't 'see' is a split transaction. 
I recreated that by a new transaction. Filter displayed it. I edited the transaction and added one split. Straight away the filter can't display it. The split shouldn't have any effect on a date? But it does. Another hidden Bug within this date filter issue!

**Comment by whalley** [comment]
I've just tested this. Think I'm testing what is described. And I don't see an issue on MacOS.


https://user-images.githubusercontent.com/487345/188278725-56064367-2fbe-471e-9789-8c14148cc62b.mp4

**Comment by tactilis** [comment]
This bug is about Reports Mark.

https://user-images.githubusercontent.com/4060092/188279150-8237cbfb-1841-4b19-a927-e20d4363345c.mp4

**Comment by tactilis** [comment]
The above video shows that today's transaction (03/09/2022) is excluded from the Transaction Report if the date range is left at the default (From 03/09/2022 - To 03/09/2022).

When I set the To date to 04/03/2022, it does include the 03/04/2022 transaction.

Note that if I set the From date earlier, then as reported, you get an 'Invalid value: Date' error:

![image](https://user-images.githubusercontent.com/4060092/188279336-043648b8-9d34-4636-8d65-e053dfdcf82b.png)

**Comment by whalley** [comment]
> This bug is about Reports Mark.

Is it? The reproduction steps from @SJK55 make no mention of the reports - just looks like the filter on the account views. However the logic is shared to large extent.

**Comment by tactilis** [comment]
The transaction list Advanced Filter works fine (as shown by your video and my own testing).
The Transaction Report filter does not.

I was surprised, because I thought there was shared code between the two dialogs.

@SJK55's bug reports are sometimes not as clear as they might be.  Sorry @SJK55 but sometimes the wording is a little muddled.

However, the clue might be in the definition of Since & Before in the report.
Since 03/09/2022 but Before 03/09/2022 may not capture a transaction _on_ 03/09/2022 depending on how the conditional has been coded.

**Comment by whalley** [comment]
If you select the Period/Date range and save it with a report name. Does this now work?

**Comment by tactilis** [comment]
> f you select the Period/Date range and save it with a report name. Does this now work?

No _and_ Yes.

If you:

1. Just tick Date Range  (leaving the defaults of 03/09/2022 - 03/09/2022)
2. Save the report (I used name 03-03)
3. Click OK to run the report

There are no transactions in the report.

However, if you then:

4. Open the filter dialog again
5. Select the 03-03 filter (it was selected by default as it was only one saved)
6.  Click OK to run the report

The 03/09/2022 transaction is included in the report.

**Comment by tactilis** [comment]
Tested 1.5.21-Beta.1 commit: 5d8e78d (2022-09-04)

Confirmed working now.

**Comment by SJK55** [comment]
Did you people miss the fact I mentioned in the filter only, not report (I never mentioned reports)
That split's won't appear. As I said a Bug within a Bug even with the date setting to future.
I think you may have missed that?

Plain speaking if you create a transaction with today's date and use  Martins? fix of setting a future date to see it in the filter, split transactions will not appear? 

If that doesn't make sense please tell me.

**Comment by tactilis** [comment]
@SJK55 
> I never mentioned reports

You included a screenshot of the Transaction Report in your original post. This led to testing of that area of functionality and has helped reveal the underlying cause of the problem on the Transaction Filter dialog.

@whalley has fixed bug. The will be included in 1.5.21.

**Comment by SJK55** [comment]
Ok. No problems!
