### ISSUE TITLE
CSV files import: error when amount field is selected

### ISSUE THREAD

**Issue by artemiogr97** [moneymanagerex/moneymanagerex#5039]
Description:

Open the csv import dialog
Tyr to import the data  using the amount field
The following two options don't work, all the values are imported as withdrawals:
![image](https://user-images.githubusercontent.com/57588855/188308745-bd2e42ba-a9d0-43df-bbe3-a0fb9331a260.png)

**Comment by whalley** [comment]
Seems to work fine for me.

When you say "The following two options don't work", which 2 options are you referring to - the field you have shown as 3 options? As the 'Positive of type has 'Deposit' implies you have a type field with the amount present also.

Can you provide an example CSV and the full import settings.

**Comment by artemiogr97** [comment]
Options "Positive values are deposits" and "Positive values are withdrawals" doesn't work.

My import options are the following:
![image](https://user-images.githubusercontent.com/57588855/188313499-44503011-50d8-4e41-a56e-aefe845c7fb4.png)
Example of csv file:
[test.csv](https://github.com/moneymanagerex/moneymanagerex/files/9484672/test.csv)
When the first option is selected I get the following result after the import:
![image](https://user-images.githubusercontent.com/57588855/188313645-f2f3f0bf-7f30-453c-aa0a-5f354d288a92.png)
Expected result:
![image](https://user-images.githubusercontent.com/57588855/188313806-3ed4309a-701e-4a80-8d0c-3bf71a4c508c.png)

**Comment by artemiogr97** [comment]
This problem seems to happen only when the field "Type" is selected at the same time that any of the first two options are selected

**Comment by whalley** [comment]
Why would you use the options "Positive values are deposits" and "Positive values are withdrawals" if a transaction type is defined? As you have seen these options are only used if the type field is not present. If a type field is present I think it makes sense for that to take precedent.

**Comment by tactilis** [comment]
@artemiogr97, to reinforce what @whalley has said...

Regardless of the column being called Type, you don't actually have a Type data field in your test csv file.

Lines 4 and 5 both have a Type of 'test', which is unrelated to whether the Amount value is a deposit or a withdrawal. You **must** therefore set column 4 to Don't Care, so that MMEX Import ignores it.

![image](https://user-images.githubusercontent.com/4060092/188330639-e58635be-6171-4a1b-9926-39ffa7297526.png)

**Comment by artemiogr97** [comment]
I just marked that column as "Don't care" and the behavior is what I expected, thanks for the help.
Either way, it seems counter-intuitive to me that it is possible to choose an option that will be completely ignored, maybe if the field "Type" is present the other 2 options ("Positive values are deposits" and "Positive values are withdrawals") should disappear ?

**Comment by vomikan** [comment]
Is solution found?

**Comment by n-stein** [comment]
Is it sufficient to simply force selection of "Positive if type has 'Deposit'" whenever Type is included in the field list?

**Comment by n-stein** [comment]
How about this:

When the user selects "Type" for import, then tries to change the Amount Sign selection to something other than "Positive if type has 'Deposit'" it reverts and presents a message.

![image](https://user-images.githubusercontent.com/16599929/210589876-54cc772d-5bee-4fb3-8ee2-0cc531cd4b94.png)

**Comment by n-stein** [comment]
I fixed this in #5772 so this issue can be closed.
