### ISSUE TITLE
Create new category failing

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#5046]
MMEX version:
 - [x] 1.5.20

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I create a new booking and write the custom text ´Heim- Hausbedarf:Haustier´ into the category field.
It fails with "invalid value".

It worked in the past.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
I create a new booking and write the custom text ´Heim- Hausbedarf:Haustier´ into the category field.

Expected result:
A new category.

Actual result:
It fails with "invalid value".

# Additional information

Since the dialog window is modal I need to close it and loose the stuff I wrote into the new booking?

**Comment by whalley** [comment]
To create a new category - start with an empty category field and press return. You should be able to add a new category then return to the transaction dialog.

**Comment by MartinX3** [comment]
Thank you, I already did that.
But is there a way to get the old feature back?
It adds now extra steps if there is a category missing.

**Comment by whalley** [comment]
Given that there is a mechanism to create a new category, and the fact that new category creation is much less frequent than new payee creation, I'm not sure of the merits of introducing more complexity/options in this area to avoid a few extra few steps.

**Comment by MartinX3** [comment]
But why did it work before?
Was it a complicated code hack?

**Comment by whalley** [comment]
It may have worked before but we have done quite a few changes in this area and now have, what I think, is stable and acceptable to users. I'm wary about making more changes at this point so would suggest we hold off on any more non-essential changes.

**Comment by MartinX3** [comment]
Sadly the change made it worse.
If I edit or add an entry and choose a category
1. there is no scrollbar anymore, I need to use the scroll wheel of my mouse and it takes ages of fast scrolling which hurts my finger.
2. I can't simply write a part of a word to search for an entry. I need to explicitely begin with the start of the correct entry I want to search. So it's hard to use this feature and I need to open the list and get the 1. problem.

**Comment by tactilis** [comment]
@MartinX3 
I agree with @whalley, however I'm interested to find which version of MMEX had the behaviour you describe, where you could type a new category:subcategory name and have MMEX add it to the list of available Categories.

To be clear, are you referring to a version of MMEX that has the old style Category selection as shown on the left, or the new style shown on the right?

![image](https://user-images.githubusercontent.com/4060092/188601000-c17a4a19-b08e-4851-b83e-894444d80c39.png)

**Comment by vomikan** [comment]
> But why did it work before?

Never. It looks like you are confusing with payee.

> To create a new category - start with an empty category field and press return. You should be able to add a new category then return to the transaction dialog.

This is the solution of the case.

However, you can get confused and make an automatic category addition, as it has already been done for payee. But I don't think that's a good idea. As a result, there may be chaos in the categories.

**Comment by tactilis** [comment]
Thanks @vomikan. That's what I thought too, hence my question to @MartinX3.

Adding a new category is really no slower then before. Previously, you had to click the Select Category button to bring up Organize Categories, and now all you need to do is press Enter in the blank Category field. And your other improvements have streamlined the selection of categories.

@MartinX3 does bring up a couple of related valid points though:

>If I edit or add a booking entry and choose a category:
>1.  there is no scrollbar anymore, I need to use the scroll wheel of my mouse and it takes ages of fast scrolling which hurts my finger.
>
>2. I can't simply write a part of a word to search for an entry. I need to explicitely begin with the start of the correct entry I want to search. So it's hard to use this feature and I need to open the list and get the 1. problem.

I think that Martin must have some categories with a very large number of subcategories. For example, once he has created the new category (Heim- Hausbedarf:Haustier / **Home house supplies:Pet**) he wants to allocate that to a transaction. Because we anchor the search to the start of the category string, he can't just type 'Haustier' and have the list filtered. He has to type 'Heim' and then is presented with a very long list of his Heim****:**** categories.

A few other people have raised this point too.

I think we should consider whether _not_ anchoring the search would give a better experience for users or not.

**Comment by vomikan** [comment]
The situation is this: On MAC and on WIN, wxComboBox works differently. I believe this is implemented with a bug on MAC.. Using this bug, @whally made the search on MAC better than it is possible on WIN.
Making this search the same for all systems is a non-trivial task. It needs to write you own ComboBox.

**Comment by whalley** [comment]
> a bug on MAC..

The bug is now a feature :-)

**Comment by whalley** [comment]
> a bug on MAC..

The bug is now a feature :-)

**Comment by whalley** [comment]
No change planned to support creation of category via direct input into combobox.
To manage categories you need to open the 'organize categories' dialog either via menu option or by typing RETURN on empty combobox
