### ISSUE TITLE
Calculation and display errors in the securities portfolio

### ISSUE THREAD

**Issue by btab33** [moneymanagerex/moneymanagerex#5049]
1. Les colonnes "Valeur totale actuelle" et "Gain / Pertes" sont identiques dans l'affichage des titres alors que le calcul est correct en bas de page
2. Pour plusieurs titres, deux lignes de calcul sont affichées en bas de page. La deuxième ne correspond à rien de connu.
![Capture d’écran 2022-09-06 081449](https://user-images.githubusercontent.com/83901821/188561051-e7aac9be-44e1-4d03-b94c-eae29ca42220.png)

<hr>Version: 1.5.20 64-bit<br>
 • Build: Sept.  2 2022 14:12:10<br>
 • db 7 •  (aes128cbc)<br>
 • git 3e27ceb (2022-09-02)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22000), 64-bit edition<br>
 •  French (France) (windows-1252)<br>
 • 3840x2400 32bit 96x96ppi

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4969

**Comment by reddyshyam** [comment]
Hi, not sure if mine is the same issue as well but gain/loss shows the same current total value. Please see below. I am on v1.5.20

![image](https://user-images.githubusercontent.com/12392746/189063758-05ef3f5d-a756-4ee1-acf4-60f3eb446902.png)

**Comment by n-stein** [comment]
Fixed

![image](https://user-images.githubusercontent.com/16599929/190234323-0412cae9-1ef1-4126-8f59-076981b8418b.png)
