### ISSUE TITLE
Incorrect ascending/decending sort order indicator for Assets/Recurring Transactions columns

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5054]
MMEX version:
  - [x] 1.5.20

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The sort order indicator for Assets columns shows ascending when the order is descending, and vice versa.

Here, Initial Value is sorted as ascending but the descending indicator is displayed.

![image](https://user-images.githubusercontent.com/4060092/189140024-83cfbc01-cd78-4a01-80d4-149a40f47d77.png)

The problem exists for _all_ columns.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
Having checked, the same is also true for Recurring Transactions.

**Comment by tactilis** [comment]
It's the Australian version of MMEX
