### ISSUE TITLE
Organize Category dialog does not scroll newly added items into view 

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5056]
MMEX version:
 - [x] 1.5.20 

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The work done for #4989 has improved the Organize Categories dialog so that the category tree collapsed/expanded state is now remembered when it refreshes following the addition of a category/subcategory.

However the tree still scrolls to the top and highlights the root node (Categories) when the new item is added. The user then has to scroll to view the new item to check that it was entered OK, and perhaps to enter more subcategories within the category.

It would be more helpful if:
1. The list is refreshed and scrolled to always show the new item.
2. The new item is highlighted so that it can be easily identified.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Add a new subcategory to a category near the bottom of the tree:

![image](https://user-images.githubusercontent.com/4060092/189159170-bd8e74f5-2fc6-4396-987b-a0d00e6b54d2.png)

Expected result:

The new item is visible and is highlighted:

![image](https://user-images.githubusercontent.com/4060092/189159801-e2b86054-026c-4c26-b164-454aacaf2a34.png)

Actual result:

The list is displayed with the root node highlighted.

![image](https://user-images.githubusercontent.com/4060092/189163592-a2704902-6625-4a84-9ec8-567bbaec0e8e.png)

# Additional information

Note that when an item is deleted, the tree does not scroll and the item that was immediately above the deleted item is highlighted. This makes it easy for the user to see the change they have made, and perhaps to delete more subcategories within the category. This behaviour should be retained.

**Comment by tactilis** [comment]
> Just tried this on MacOS. It seems to work.

I'm testing 1.5.21-Beta.1 commit: 5e8eff3 (2022-09-08), which includes your Show All fixes, so is the correct version.

Some odd tree widget behaviour on Windows not actioning the highlighting you are doing?

**Comment by whalley** [comment]
I can't see why it does not work in Windows.
https://github.com/moneymanagerex/moneymanagerex/blob/ee98b3fd393180df9e465f4349d16edf93397c62/src/categdialog.cpp#L255

@vomikan Are you able to investigate.

**Comment by n-stein** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/ee98b3fd393180df9e465f4349d16edf93397c62/src/categdialog.cpp#L404

https://github.com/moneymanagerex/moneymanagerex/blob/ee98b3fd393180df9e465f4349d16edf93397c62/src/categdialog.cpp#L434

https://github.com/moneymanagerex/moneymanagerex/blob/ee98b3fd393180df9e465f4349d16edf93397c62/src/categdialog.cpp#L177-L184

The call to fillControls at the end of OnAdd resets the selected item ID to the root node. Just removing the call to fillControls() on 404 and 434 leaves the parent expanded but still selected. If you want the newly added one to be focused you need to add
```
m_treeCtrl->SelectItem(tid);
m_treeCtrl->SetFocus();
```

**Comment by whalley** [comment]
> The call to fillControls at the end of OnAdd resets the selected item ID to the root node. Just removing the call to fillControls() on 404 and 434 leaves the parent expanded but still selected. If you want the newly added one to be focused you need to add
> 
> ```
> m_treeCtrl->SelectItem(tid);
> m_treeCtrl->SetFocus();
> ```

Yes, that works on MacOS fine.

FYI, in FillControls the selected item ID was recalculated
here:
https://github.com/moneymanagerex/moneymanagerex/blob/882bdda4f11c8e694c937a600f1ec15d1e3e5b3d/src/categdialog.cpp#L205
and here:
https://github.com/moneymanagerex/moneymanagerex/blob/882bdda4f11c8e694c937a600f1ec15d1e3e5b3d/src/categdialog.cpp#L224

and then selected and made visible here 
https://github.com/moneymanagerex/moneymanagerex/blob/882bdda4f11c8e694c937a600f1ec15d1e3e5b3d/src/categdialog.cpp#L254-L255

This, oddly, worked on MacOs but not Windows...

Anyway, fixed now. Thanks for the PR.

**Comment by tactilis** [comment]
Confirmed working on Windows now.  Thanks

**Comment by whalley** [comment]
Slight issue. By not calling fillControls() is that the newly added item is not sorted.

**Comment by n-stein** [comment]
Good catch. Fixed by sorting children of m_selectedItemNode.
