### ISSUE TITLE
In-place editing of asset name allows asset with blank name to be created

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5057]
MMEX version:
 - [x] 1.5.20

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX supports the in-place editing of an asset's name by clicking on an already highlighted row in the Assets list.

This functionality permits an asset to be renamed to have a blank name.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

In the Assets list:

1. Single-click on an asset to highlight the row.
2. Single-click again on the highlighted row. A small editing box is displayed with a space(?) character highlighted.
3. Press the Delete key to delete the space, then press Return.
4. Note that the asset name is now blank, which would not be a valid name if entered/edited via the Edit Asset dialog.

https://user-images.githubusercontent.com/4060092/189173010-54faac70-e385-44ef-b0e0-7dca7185a9c5.mp4

Expected result:

Either the in-place editing should be corrected so that it is not be possible to rename an asset to have a blank name.

Or, **better still**, the current in-place renaming of assets functionality should be removed because:
1. It is inconsistent with all other transaction editing within MMEX and appears to poorly implemented (for example, it does not pre-fill the editing box with the asset's current name).
2. It bypasses the validation checks that are made when editing an asset using the Edit Asset dialog.
 
Actual result:

See the video.

# Additional Information

If in-place editing is ever provided in the future, it should be done directly in the asset/transaction list in a similar manner to which spreadsheet cells are edited - not by displaying a separate editing box.

**Comment by whalley** [comment]
> Or, better still, the current in-place renaming of assets functionality should be removed 

Agreed. Will remove.
