### ISSUE TITLE
Minimum width of Organize Categories dialog allows buttons to become clipped

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5059]
MMEX version:
 - [x] 1.5.21 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The minimum width of Organize Categories dialog is too small. It should not be possible to make it so narrow that buttons become clipped.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Resize the Organize Categories dialog.

The height is correctly constrained to a minimum that keeps all controls visible but the width can be made too narrow for the controls, as shown on the right:

![image](https://user-images.githubusercontent.com/4060092/189191362-050ad37f-ce40-4058-95e4-56513f407333.png)

Expected result:

The layout of controls should constrain the minimum width.

**Comment by tactilis** [comment]
Unfortunately, fix does solve the button clipping problem if the font size in Options | View is set to Large.

It appears that the required width of the buttons is not constraining the minimum width.

![image](https://user-images.githubusercontent.com/4060092/189306013-d42da05e-68a1-4911-8a71-0fd778a1f5f6.png)

**Comment by whalley** [comment]
Should work better now. Only minor glitch is that if the window has previously been saved at a narrower width (i.e. prior to implementing this constraint) then it will open as saved. If the user them resizes it will then adhere to the constraint and will then not allow it to be then reduced..

**Comment by tactilis** [comment]
> Only minor glitch is that if the window has previously been saved at a narrower width (i.e. prior to implementing this constraint) then it will open as saved.  If the user them resizes it will then adhere to the constraint and will then not allow it to be then reduced.

I thought that would be the case, but that is reasonable behaviour.

However, it does actually behave properly (on Windows at least).

Here is the result of setting to minimum width (and height) with a font size of Normal and then changing the font size to Huge. Restart MMEX and open the dialog...

![image](https://user-images.githubusercontent.com/4060092/189350044-c6dcd18d-f7dc-45c7-93bc-f8eca4967cdb.png)
