### ISSUE TITLE
Filter by notes dose not work  in most cases

### ISSUE THREAD

**Issue by BernardoArago** [moneymanagerex/moneymanagerex#5066]
MMEX version:
 - [x] 1.5.20
 - [x] 1.3.6

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Filter only by notes show empty or with less records than really match. For example using (*) at the begining shuld find any chain in center, and dose not

# Rep
![cuenta mmex](https://user-images.githubusercontent.com/113266137/189504176-14e85c9c-286b-449b-89a5-0c1595825af3.png)
roduction
![filtro mmex](https://user-images.githubusercontent.com/113266137/189504179-2115afa4-1d2e-4afa-aa11-55f30116e950.png)
![filtro resultado mmex](https://user-images.githubusercontent.com/113266137/189504182-df51aa5a-9671-4562-8bab-c55b5d6f0e3f.png)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by tactilis** [comment]
This is not a bug.

If you have Notes of  ABCDEFGHI the wildcard * matches as follows:

 ```
1. *  Matches the whole string
 
2. ABC* Matches a string beginning with ABC plus any (including zero) characters after.

3. *DEF*  Matches any (including zero) characters before DEF and any (including zero) characters after.

4. *DEF   Matches any (including zero) characters before DEF which ends the string.
```
1, 2, and 3 will match ABCDEFGHI
4 will not match.

@BernardoArago, you need to put * at the start _and_ the end of your search string.

**Comment by BernardoArago** [comment]
![filtro mmex2](https://user-images.githubusercontent.com/113266137/189527366-e4dc3441-2358-410a-a148-02ceaab53856.png)
![filtro resultado mmex2](https://user-images.githubusercontent.com/113266137/189527371-88d8896b-bfd6-4387-8a36-fac461e8c295.png)

in this last example apears something but not the entrie I show "12/8/2022 Canon GM4010 913111C00492AA21"

![filtro mmex3](https://user-images.githubusercontent.com/113266137/189527609-9336a42e-437e-42e7-b233-1442b77e9566.png)
![filtro resutado mmex 3](https://user-images.githubusercontent.com/113266137/189527615-cd678bcf-9c3e-4f44-8d2b-51d5dd71cca8.png)

**Comment by tactilis** [comment]
It works OK here.

Starting with these transactions:

![image](https://user-images.githubusercontent.com/4060092/189530773-4c793727-6ded-4232-9cab-8f9a0c0265c4.png)

The Canon transaction:

![image](https://user-images.githubusercontent.com/4060092/189530832-92e30435-920d-43f6-bac3-7b6c1799dd46.png)

Filtering in the Account View selects the transaction OK:

![image](https://user-images.githubusercontent.com/4060092/189530857-bd78df4f-9c78-4487-8cb6-e46222a033df.png)

Filtering in the Transaction Report selects the transaction OK:

![image](https://user-images.githubusercontent.com/4060092/189530915-9017f109-b84a-4ea0-a97d-c4012450a6bb.png)

![image](https://user-images.githubusercontent.com/4060092/189530935-55906847-9cb7-419f-8ec1-58d816bd80ac.png)


@BernardoArago are you certain that the string you are filtering on contains _exactly_ the characters that are in the transaction Notes?  (copy & paste from the transaction to be sure). The fact that your Canon transaction _is_ selected when you filter using *913* but not when you use the longer string suggests that something is different between the filter and the Notes.

Could you post a screenshot of your Edit Transaction dialog please?

**Comment by BernardoArago** [comment]
[Original.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/9543258/Original.mmb.zip)
I send a base copy, I deleted 99.9% of the entries, the problem continues. Thank you very much for the help and quick responses. I use the software since 2010 on linux and I use the search in notes a lot.

**Comment by tactilis** [comment]
Thank you @BernardoArago 

Using your database, the filter *913* and *913111C00492AA21* works correctly on Windows in account transaction list and in the Transaction Report.

Here's the report showing your split transaction:

![image](https://user-images.githubusercontent.com/4060092/189546306-da717375-e1f6-4025-9aaa-df7eb3c1c8d3.png)

I see that the string 913111C00492AA21 in your transaction's Notes is on a separate line, so is immediately preceded and followed by a line break. I'm wondering whether this is the cause of the problem.

@whalley, would you be able to investigate on Linux please?

![image](https://user-images.githubusercontent.com/4060092/189546498-db08e81e-823c-4248-b94e-8cd82283c51c.png)

**Comment by tactilis** [comment]
@BernardoArago
In your cut down database, if you edit the transaction so that the 5 lines of the Canon notes are all on a single line with the strings of characters separated by **spaces** as marked below, does the \*913\* and \*913111C00492AA21\* now work or not?

![image](https://user-images.githubusercontent.com/4060092/189547304-bd90bf91-269e-496a-bc65-9d0803eb2429.png)
