### ISSUE TITLE
Building from tar.gz fails

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#5078]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [ ] 1.5.19
 - [x] 1.5.20
 - [ ] 1.5.21 Beta
 - [x] Other (please specify): possible for all releases of mmex

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).
No tar.gz for 1.5.21Beta ?

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I tried to do the 1.5.20 tar.gz file.
There I get errors when doing `cmake .` in `1_5_20fromtgz/moneymanagerex-1.5.20` :
```
CMake Error at CMakeLists.txt:408 (add_subdirectory):
  The source directory

    /home/pmaff/Technical/PC/FinanceMoney/MMEX/1_5_20fromtgz/moneymanagerex-1.5.20/3rd/fmt

  does not contain a CMakeLists.txt file.
```
...
```
CMake Error at 3rd/CMakeLists.txt:34 (add_subdirectory):
  add_subdirectory given source "lunasvg/include" which is not an existing
  directory.


CMake Error at 3rd/CMakeLists.txt:35 (add_subdirectory):
  add_subdirectory given source "lunasvg/source" which is not an existing
  directory.


CMake Error at 3rd/CMakeLists.txt:36 (add_subdirectory):
  add_subdirectory given source "lunasvg/3rdparty/software" which is not an
  existing directory.


CMake Error at 3rd/CMakeLists.txt:37 (add_subdirectory):
  add_subdirectory given source "lunasvg/3rdparty/plutovg" which is not an
  existing directory.

```
...
```
CMake Error at 3rd/CMakeLists.txt:172 (file):
  file STRINGS file
  "/home/pmaff/Technical/PC/FinanceMoney/MMEX/1_5_20fromtgz/moneymanagerex-1.5.20/3rd/wxsqlite3/include/wx/wxsqlite3_version.h"
  cannot be read.
```
...
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.20
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.19.7-1-default
-- openSUSE.20220906
-- openSUSE.Tumbleweed
-- CMake 3.24.1
-- GNU Make 4.3
-- ccache 4.6.1
-- GNU 12.2.1
-- wxWidgets 3.2.0
-- wxSQLite3 4.8.1
-- Lua 5.4.4
-- curl 7.85.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring incomplete, errors occurred!
```

I got the moneymanagerex-1.5.20.tar.gz from here:
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.5.20

Is there a different way of compiling from sources for the tar.gz ?
Do we have to change the description for Linux?
Imho (in my humble opinion) it would be better to have the same way for compiling from Github sources and
tar.gz .

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1) download tar.gz from here: https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.5.20
2) tar -xvzf the file
3) `cmake . ` as in the normal way of cmake for compiling Linux sources in `1_5_20fromtgz/moneymanagerex-1.5.20`

Expected result:
normal cmake config

Actual result:
cmake config fails.

See also:
https://github.com/moneymanagerex/moneymanagerex/issues/4154

**Comment by vomikan** [comment]
This archive contains the source code of the mmex application only and does not include third-party code. Providing such an archive is probably a tribute to tradition. Free software should be distributed with the source code. I don't see the point in this archive. It's not worth using it.

**Comment by PMaff** [comment]
> This archive contains the source code of the mmex application only and does not include third-party code. Providing such an archive is probably a tribute to tradition. Free software should be distributed with the source code. I don't see the point in this archive. It's not worth using it.

Maybe we should make a hint that there is 3rd party software missing in this tar.gz and in the zip file (I guess) and that this
won't compile.

And then point to:
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux

**Comment by vomikan** [comment]
What's wrong with git clone? Why the archive?

**Comment by PMaff** [comment]
> What's wrong with git clone? Why the archive?

Git clone is ok.
We should only tell people, that the archives  *.tar.gz and *.zip only contain the mmex sources and not a compileable package.

**Comment by bkmgit** [comment]
CMake can be updated to download dependencies that are not present.

**Comment by whalley** [comment]
@bkmgit Current CMake assumes you have cloned the repo correctly and hence have the dependencies available. Not sure we should overcomplicate to try pulling in dependencies if the repo has not been cloned correctly, user should re-clone.

**Comment by bkmgit** [comment]
If this does not work for the tar.gz archive, modification can be made as described in the [CMake documentation](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#downloading-and-building-from-source-with-fetchcontent)
