### ISSUE TITLE
Transaction Report and Custom Fields

### ISSUE THREAD

**Issue by RTMWEST** [moneymanagerex/moneymanagerex#5083]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [ ] 1.5.19
 - [x] 1.5.20
 - [ ] 1.5.21 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I find the Custom Field feature extremely useful, however when running a transaction report any transactions with split categories are excluded from the report even though the custom field is selected.

# Reproduction
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Add a custom field to a transaction containing a single category.
Add same custom field to another transaction containing spilt categories.
Create a Transaction Report for the selected custom field.

Expected result:
Both Transactions to be included in the report.

Actual result:
Split category Transaction excluded from the report.

# Additional information

**Comment by whalley** [comment]
Seems fine to me.

Transaction Register
![CleanShot 2022-09-15 at 08 51 26](https://user-images.githubusercontent.com/487345/190347159-a33ad615-f1d1-4d66-86b1-71fcf27b2c54.png)

Splits
![CleanShot 2022-09-15 at 08 52 18](https://user-images.githubusercontent.com/487345/190347311-890df2b3-a90d-4a2e-8cb3-264084f531ac.png)


Transaction Report Setup
![CleanShot 2022-09-15 at 08 50 40](https://user-images.githubusercontent.com/487345/190346968-b34a14fd-1ad0-4eea-9392-90d915689e01.png)

Transaction Report Output
![CleanShot 2022-09-15 at 08 50 07](https://user-images.githubusercontent.com/487345/190346904-62f2e069-e0f8-4ea9-ad71-963cf401ceee.png)

**Comment by RTMWEST** [comment]
Saw your note re the fix, will have another look when v1.5.21 is released.

**Comment by RTMWEST** [comment]
Hi Mark,

 

From your Custom Split check below, I can see it works with setting Custom3 MyInteger as 5

 

I am using Custom Field single, would you mind checking that field as well.

 

Many Thanks.

**Comment by whalley** [comment]
Yep, works find for single choice

![CleanShot 2022-10-11 at 09 00 59](https://user-images.githubusercontent.com/487345/195032870-fc2c343a-f152-492b-bc30-66e4dfd6874c.png)
