### ISSUE TITLE
Organize Payees window very small

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5085]
MMEX version:
 - [x ] 1.5.21 Beta

Operating System:
 - [x] Windows

# Description of the bug

The "Organize Payees" window is very small.
I would welcome it to be a bit bigger.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/76920138/190360259-6c2d9237-24d5-45f2-88b8-9697b0926a6b.png">

**Comment by tactilis** [comment]
You can resize the dialog by dragging the bottom right corner.

The new size will be remembered across re-starts of MMEX
