### ISSUE TITLE
Typo in src/mmframe.cpp, line 86

### ISSUE THREAD

**Issue by sliwowitz** [moneymanagerex/moneymanagerex#509]
On Linux, this line fails due to case-sensitivie filesystem. The include should be model/Model_CurrencyHistory.h (the capital H)

./src/mmframe.cpp:86:41: fatal error: model/Model_Currencyhistory.h: No such file or directory
 #include "model/Model_Currencyhistory.h"

**Comment by guanlisheng** [comment]
Please help to fix the typo

**Comment by gabriele-v** [comment]
Already fixed by another developer
