### ISSUE TITLE
Include Grand Total for Reconcilied Column

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5091]
# Description of the feature

https://forum.moneymanagerex.org/viewtopic.php?t=10684

I'm missing a grand total for the Reconcilied columns in the Home Page.

![image](https://user-images.githubusercontent.com/487345/190659701-4f28a34c-aef5-4a70-8146-127168e89c00.png)

**Comment by whalley** [comment]
I have looked at this and will add the reconciliation summary. However I did notice that the grand total actually includes the asset and stock figures even though it is in a section with the account detail. This is misleading.

![CleanShot 2022-09-18 at 18 31 44](https://user-images.githubusercontent.com/487345/190920860-f079f54c-a31d-4e50-9a08-cabe70009055.png)

I propose therefore we move it outside and present as a top-line item, e.g. 
![CleanShot 2022-09-18 at 18 42 45](https://user-images.githubusercontent.com/487345/190921036-5e9889d1-611d-46db-b7c9-b9b297980c66.png)

**Comment by whalley** [comment]
Views on an overall Net Worth header like this?

<img width="934" alt="CleanShot 2022-09-20 at 14 11 54@2x" src="https://user-images.githubusercontent.com/487345/191267004-d192832b-e31a-42fd-a2a9-38813727be5d.png">

**Comment by renato-mmex** [comment]
From my point of view, the solution has a flaw.
The "Balance" in the title also includes the "Assets" and these are not listed below.

**Comment by whalley** [comment]
Yes, I removed the Assets widget as all it did was report the asset total, so just duplicated what is now in the 'Net Worth' heading.

I'm going to raise another issue to get the asset widget updated to report a summary of the assets in the same way as the 'Stocks' widget does for stocks.
