### ISSUE TITLE
Stocks Summary

### ISSUE THREAD

**Issue by babbishkamath** [moneymanagerex/moneymanagerex#5099]
MMEX version:
 - [ ] 1.5.17
 - [] 1.5.18
 - [ ] 1.5.19
 - [x ] 1.5.20
 - [ ] 1.5.21 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Question
Is it necessary to show stocks with zero positions in the summary report? Specially with repeating colors.
![summary](https://user-images.githubusercontent.com/111977534/190963443-501d04f8-3bd8-4099-a5de-f857047469d7.png)

**Comment by whalley** [comment]
Change the SQL to below in the GRM editor

```
with result as 
( select s1.STOCKNAME, s1.SYMBOL,
    total(s1.NUMSHARES) as NUMSHARES,
    total(s1.VALUE * IFNULL(CH.CURRVALUE, c1.BASECONVRATE)) as VALUE
from ACCOUNTLIST_V1 as a1
inner join  STOCK_V1 as s1 on s1.HELDAT = a1.ACCOUNTID
inner join CURRENCYFORMATS_V1 as c1 on c1.CURRENCYID = a1.CURRENCYID
left join CURRENCYHISTORY_V1 AS CH ON CH.CURRENCYID = c1.CURRENCYID AND 
                                   CH.CURRDATE = (
                                                     SELECT MAX(CRHST.CURRDATE) 
                                                       FROM CURRENCYHISTORY_V1 AS CRHST
                                                      WHERE CRHST.CURRENCYID = c1.CURRENCYID
                                                 )
where a1.ACCOUNTTYPE = 'Investment' and a1.STATUS = 'Open'
group by s1.SYMBOL
order by VALUE desc )
select * from result where VALUE <>0;
```

**Comment by babbishkamath** [comment]
Success :-) Thank you.
