### ISSUE TITLE
#4690 Secondary 'Sort By' Column 

### ISSUE THREAD

**Issue by DavidCinUK** [moneymanagerex/moneymanagerex#5108]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The described enhancement for "#4690 Secondary 'Sort By' Column" re how the secondary "sort by" column feature should work is not too intuitive, or the feature is not working as I'd expect it to as ...
... each time I get one current account's columns to appear correctly when I then switch to viewing a different current account the sort order seems to have changed again
... i.e. I get one account arranged with the sort in an OK form [newest date first, then highest ID first within each single date], but when I switch to a second account the sort has reverted to [newest date first, then smallest ID first within each single date] which is an order which I see is "wrong".

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Once the sort order has been set for one account is should replicate across all other accounts

Actual result:

Once the sort order has been set for one account it does not replicate across all other accounts

# Additional information

Would it be possible to make an enhancement where the "sort logic" can be globally set within the Options section ?
with the main arrangement I'm looking for is to have "Primary Sort Field = Date in 'Latest First' order", then "Secondary Sort Field = ID No. in 'Highest First' order"  

I've reverted to using v1.5.20 version as that version works OK

If you have a backtrace for a crash or a warning, paste it here.

**Comment by sharkei2018** [comment]
DavidCinUK makes a valid point about how to set the sorting - I didn't find it very intuitive, particularly as I don't normally display the ID column.
I would support his suggestion to set the sort order in the global Options and I would set the same order as him, i.e. latest date and then highest ID.  Maybe that could be the default as has been suggested in #4690 already.

**Comment by whalley** [comment]
The saving of sort order is saved independently for the 'All Transactions' view and the individual accounts view (each account having the same sort order). I cannot replicate the issue of the sort order being different across accounts.

Is it possible to record a video of what you are seeing?

**Comment by DavidCinUK** [comment]
Hi Whalley
As the info displayed shows some of my bank account details I'm not really OK with doing a video [assuming I had some software to create such a video]. However, I've got some screen shots taken which show the issue without compromising the account details.
I've added those screen shots, and then annotated them, in the attached .PDF file.  Hopefully you'll be able to see what is causing my concern.
[Issue with ''Sorting'' not working OK in v1.5.21.pdf](https://github.com/moneymanagerex/moneymanagerex/files/9621103/Issue.with.Sorting.not.working.OK.in.v1.5.21.pdf)

**Comment by DavidCinUK** [comment]
Oh ... forgot to say ... re-installing v1.5.20 and then open the same file gets the account order back to the way it was originally prior to installing v1.5.21.

**Comment by whalley** [comment]
Just to show the mechanism for secondary sort and the results I am seeing.

1. Inititally the accounts are sorted by PAYEE
2. Then I sort by ID, which will result in Primary Sort = ID, Secondary Sort = PAYEE
3. Then I sort by DATE, which will result in Primary Sort = DATE, Secondary Sort = ID

As you can see the sort order is retained across all accounts

https://user-images.githubusercontent.com/487345/191688147-82b7b0b4-702b-4f69-a5ca-38f39834c3a3.mp4

**Comment by tactilis** [comment]
@sharkei2018
> DavidCinUK makes a valid point about how to set the sorting - I didn't find it very intuitive

It's a pretty common approach across apps. Windows File Explorer is just one example.

Click on one column to sort that then on a second to sort that. You now have Secondary and Primary columns and the sort order defined.

> particularly as I don't normally display the ID column.

Granted that this may be an issue for some people.

**Comment by whalley** [comment]
> Granted that this may be an issue for some people.

Think you should be able to setup the sort order, e.g. Date/ID then hide the ID column. It should continue to sort by Date/ID.

**Comment by sharkei2018** [comment]
I think you're right, you can hide the column after setting the sort order.

Date > ID is not the order that I would want, as a future transaction, with an earlier ID and a later Date doesn't stay at the top of the list (sorted descending ID and later to earlier date).

If you sort ID > Date (which is the order I would want)
and then you add a transaction for a future date the sort order stays the same (I think)

However, if you sort ID > Date
and there are transactions for today already in the account,
and then you add a transaction for today,
the transaction isn't sorted by ID properly, it's inserted at the end of the transactions with today's date that are already there.  It should be inserted so that the ID sort order is maintained.
Sort ID > Date again, moves the new transaction to the correct place.

I hope I have explained this in sufficient detail for you to replicate what I am seeing, and that I haven't misunderstood what should be happening.

**Comment by sharkei2018** [comment]
I am experiencing a change in the order of transactions (for a particular date) if I make a change to the value of one of the transactions and then have to reset the sort ID > Date for them to appear in the correct order.

If you can't replicate this, then I should be able to provide screenshots to demonstrate what I'm experiencing.

**Comment by sharkei2018** [comment]
And if a transaction is deleted.
It looks like any change to an existing transaction affects the current sort order?

**Comment by sharkei2018** [comment]
And when a transaction is marked 'Reconciled'

**Comment by whalley** [comment]
OK, having setup Date (low->high), ID (high->low) I can see the ID sort order gets reverted to Low->High in the above situations...

**Comment by whalley** [comment]
Pushed this: https://github.com/whalley/moneymanagerex/commit/ddd7ef18dc12d709e178f3484cee568f2744d892

**Comment by whalley** [comment]
Can you please test this v1.5.22Beta release to see if the issue is fixed?
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44854419/job/wqd63yr42jgncsdt/artifacts

**Comment by sharkei2018** [comment]
I think you've sorted it Mark.  I think I've tried all the changes to transactions that weren't correctly actioned in version 1.5.21 and they are now.  Well done in such a short period of time!

**Comment by sharkei2018** [comment]
If a different column is selected for the sort, say Payee, then it is necessary to reset the sort ID > Date.

**Comment by whalley** [comment]
Yes, it remembers the last selected first/secondary sort. If you change it you need to set it back.

**Comment by DavidCinUK** [comment]
A quick report back after I installed the beta.1 version.
The v20 database opened in beta.1 version with the ordering of records unaltered ... a good start   :-)
I edited existing records, added new ones, deleted both old & new records, and in all instances the ordering sequence remained as expected.
whalley ... thanks so much for your rapid update action   :-)
