### ISSUE TITLE
Asset widget on homepage should show list of assets

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5111]
# Description of the feature

Widgets such as the stock widget show a list of stocks and the total value, the asset widget should do the same. At present it just shows a total. 

May need to restrict number should to top valued assets with an 'Other Assets' line once display limit is reached.

https://github.com/moneymanagerex/moneymanagerex/issues/5091

**Comment by whalley** [comment]
[fix(#51111): asset widget detail](https://github.com/moneymanagerex/moneymanagerex/commit/243223af7c31ee305bc19dfed44ea0cc0954b3a0)

**Comment by renato-mmex** [comment]
looks great, best thanks  
![OIP](https://user-images.githubusercontent.com/76920138/191842966-612f9b5e-a2df-48a0-80e0-797304b3f0ff.jpg)
