### ISSUE TITLE
restoring user columns

### ISSUE THREAD

**Issue by norameme** [moneymanagerex/moneymanagerex#5114]
# Description of the feature

Please describe your feature with details.

Every time there is an update to the software, after download I have to hide, remove and add the columns that I use/do not use and move them all around :)
Is there a chance to 'memorise that' and restore/keep them after the software update?
I know its not a big deal, but just nice to have, if nothing else :)

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.
Every time there is an update to the software, after download I have to hide, remove and add the columns that I use/do not use and move them all around :)
Is there a chance to 'memorise that' and restore/keep them after the software update?
I know its not a big deal, but just nice to have, if nothing else :)

**Comment by whalley** [comment]
These should be retained. If you are using the portable version then you may be overwriting your mmex.ini file with the default.

**Comment by norameme** [comment]
That would make sense But also I searched for mmex.ini and could not find any 🤷‍♀️
 
 
  On Thu, 22 Sep 2022 at 21:14, Mark ***@***.***> wrote:   


These should be retained. If you are using the portable version then you may be overwriting your mmex.ini file with the default.

**Comment by whalley** [comment]
Sorry, shuld have said - `mmexini.db3`

**Comment by norameme** [comment]
oh yes - got it - noted
thank you!

-------------------------------------------
Anya
This e-mail message and any attached files have been scanned for the presence of computer viruses. However, you are advised that you open attachments at your own risk. 

    On Friday, 23 September 2022 at 10:42:45 BST, Mark Whalley ***@***.***> wrote:  
 
 


Sorry, should have said - mmexini.db3
