### ISSUE TITLE
colourful icons in portable version

### ISSUE THREAD

**Issue by norameme** [moneymanagerex/moneymanagerex#5115]
# Description of the feature

Please describe your feature with details.
I could swear that at some point I had colourful icons in portable version of the software, but now they are all green - which is O, but it was a bit nicer when I could just follow the colour, rather then to concentrate on the icons :)
as I did have them customised  (i.e. in each section additional sub-category based on colours - personal thing really)
thank you

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.
I could swear that at some point I had colourful icons in portable version of the software, but now they are all green - which is O, but it was a bit nicer when I could just follow the colour, rather then to concentrate on the icons :)
as I did have them customised  (i.e. in each section additional sub-category based on colours - personal thing really)
thank you

**Comment by whalley** [comment]
Try Tools / Theme Manager menu option. 
Select "olorful "theme.

**Comment by norameme** [comment]
Doh.Feel so stupid and so old suddenly Sorry and thank you!
 
 
  On Thu, 22 Sep 2022 at 21:13, Mark ***@***.***> wrote:   


Try Tools / Theme Manager menu option.
Select "olorful "theme.
