### ISSUE TITLE
'Balance' column makes no sense anymore

### ISSUE THREAD

**Issue by jpweaving** [moneymanagerex/moneymanagerex#5123]
> Hi.
The 'Balance' column makes no sense anymore, it no longer gives a running total. I think that it is now just freezing the figure at the balance shown when the transaction was entered into the account, then when listed in Date order, the closing balance for any particular day appears at the bottom entry, not the top. If this is a deliberate change, I may get used to it but it is of no use to me.
Thanks.
> Please do not remove information attached below this text.

<hr>Version: 1.5.21 64-bit<br>
 • Build: Sep 21 2022 09:27:42<br>
 • db 7 •  (aes128cbc)<br>
 • git cb708cc (2022-09-21)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi
![1 5 21](https://user-images.githubusercontent.com/67058137/191940670-ac2dbdae-498d-4466-a7a1-e0f46a24f57b.JPG)

**Comment by vomikan** [comment]
Please note that the sorting algorithm has changed.
https://github.com/moneymanagerex/moneymanagerex/issues/5108

**Comment by n-stein** [comment]
Also #5122

**Comment by jpweaving** [comment]
It's not fixed. It still displays the Balance incorrectly for multiple transactions on the same day if those transactions were entered in random order.

**Comment by whalley** [comment]
> It's not fixed. It still displays the Balance incorrectly for multiple transactions on the same day if those transactions were entered in random order.

That has always been the case, we currently only have Date and order it was entered. We need https://github.com/moneymanagerex/moneymanagerex/issues/2729 to improve this.

**Comment by jpweaving** [comment]
The sort order is not the problem in any way. In 1.5.20 the balance column always makes sense. each entry in the balance column accurately reflects the account balance after that transaction is taken into account. So the balance at the last transaction shown for any day accurately reflects the account balance at the end of that banking day, so the top figure in the balance column always matches the actual balance of that account. In 1.5.21 the balance doesn't make any sense unless you always enter transactions in the order that they occurred. You can end up with a situation where a transaction for a £1.00 withdrawal can result in a balance figure that is higher than the previous one. There is no point in that at all.

**Comment by jpweaving** [comment]
Thanks

**Comment by jpweaving** [comment]
I know I am probably being thick but can you give me a link to 1.5.22 beta
please.

**Comment by whalley** [comment]
For win64 - https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/qp8sa43blbsx4nwk/artifacts

Note - the next build will be v1.6.0, please take a copy/backup of your database before trying beta builds. In particular for this release as it upgrades the database.

**Comment by jpweaving** [comment]
That's great.
Thanks Mark
