### ISSUE TITLE
Saved presets in Transaction Filter and saved column formats

### ISSUE THREAD

**Issue by JuanJabo1GH** [moneymanagerex/moneymanagerex#5127]
- The latest versions: mmex-1.5.15-win32 and mmex-1.5.16-win32 and Up to mmex 1.5.21.
- They are deleting or do not maintain configurations from previous versions, in the case of: Pre-settings saved in Transaction Filter and saved column formats, among others.
- You have to recreate them, something that did not happen or did not happen with the changes in previous versions.
- In short, it seems to eliminate or does not recognize any previous configuration established by the user.

![image](https://user-images.githubusercontent.com/89281363/192066171-ac031956-50e9-4939-91a5-93ce181acaa2.png)

Please do not consider this problem closed because even in the latest version: mmex-1.5.21 this problem continues, please indicate a solution, they reported that in version: mmex-1.5.17 it had been resolved and that is not real or it was not solved, thanks.

From version “mmex-1.5.15” onwards and including the most recent “mmex-1.5.21” . They are not keeping the transaction filter presets, formats or selections in fields to display in tables.
What has as a consequence, that with each update it is necessary to re-establish all these parameters in tables and pre-adjust in transactions.

**Comment by whalley** [comment]
Are you using the portable version or the installed version?

**Comment by whalley** [comment]
@JuanJabo1GH No response to the last query on this. Without more information we cannot progress this and will close.

**Comment by JuanJabo1GH** [comment]
> ¿Está utilizando la versión portátil o la versión instalada?

Versión portable

**Comment by whalley** [comment]
Thanks for confirming. I suspect what is happening is that the mmexini.db3 file that is provided as part of the portable version is overwriting your changes. Make sure you take a copy of the your mmexini.db3 and overwrite the delivered version.

**Comment by JuanJabo1GH** [comment]
> 

Thanks for replying, but the problem continues.
Check suggested file location: “mmexini.db3” and it is located in version: “mmex-1.5.21-win32-portable” in the same main directory of this version.
It is also located at: “C:\Users\Username\AppData\Roaming\MoneyManagerEx”
I replaced it as you suggested and it didn't fix anything at all.
Also delete it from the directory: “C:\Users\UserName\AppData\Roaming\MoneyManagerEx”
And also in the same main directory of this version: “mmex-1.5.21-win32-portable”
What the version 21 program does when making the mentioned changes is to start as freshly installed, an action that does not happen with version 14.

**Comment by whalley** [comment]
Actually having re-read this the filter settings should be saved in your main DB. SO I have not idea what is going on. I'll have to leave it to somebody who can test and debug the Windows portable version as I don't use that package.

Does the same issue arise for you with the non-portable version?

**Comment by JuanJabo1GH** [comment]
> En realidad, después de haber releído esto, la configuración del filtro debe guardarse en su base de datos principal. Así que no tengo idea de lo que está pasando. Tendré que dejarlo en manos de alguien que pueda probar y depurar la versión portátil de Windows, ya que no uso ese paquete.
> 
> ¿Surge el mismo problema para usted con la versión no portátil?



> Actually having re-read this the filter settings should be saved in your main DB. SO I have not idea what is going on. I'll have to leave it to somebody who can test and debug the Windows portable version as I don't use that package.
> 
> Does the same issue arise for you with the non-portable version?


Thank you for your prompt response, in response to your approach to the proposed problem, I notify you that the error or failure occurs in both the installed version and the portable version, I invite you to carry out the test yourself and confirm this statement.

**Comment by JuanJabo1GH** [comment]
> I'm afraid I cannot reproduce this - have set filters in application, upgraded, and they are still there.
> 
> Can you provide a sanitised/cut-down database with filters included that you can share?

Please create filters in version mmex-1.5.14 or lower and then open that same database in version mmex-1.5.21 and you will see the filters and all user-created formats are lost.

**Comment by whalley** [comment]
OK now I understand. This was a consequence of way the reports now implemented and was discussed here.
https://github.com/moneymanagerex/moneymanagerex/issues/4623
There is no fix other than having to re-create.. Once re-created they will be retained across upgrades.
