### ISSUE TITLE
Virus total and Jotti tell that mmex-1.5.21-win64.exe is infect !

### ISSUE THREAD

**Issue by mmlg620** [moneymanagerex/moneymanagerex#5130]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
infect logs

https://www.virustotal.com/gui/file/947e4aec1996d769583cea968b9a02e6517114ce7f9309269c6a67b1a4ac91f9

https://virusscan.jotti.org/fr-FR/filescanjob/9mhg8kegu3

**Comment by whalley** [comment]
We have had this with VBA32 before: https://github.com/moneymanagerex/moneymanagerex/issues/4306

It's a false posisitve.

**Comment by mmlg620** [comment]
OK

**Comment by whalley** [comment]
Response from VBA32....

Hello,
Files are clean. False positive will be removed in the next update.
Thank you.
-- 
Best Regards, Alexey Gerasimenko,
mailto:feedback@anti-virus.by
VirusBlokAda Ltd., Minsk, Belarus

25.09.2022 19:14, Mark Whalley пишет:
[VirusTotal.com](http://virustotal.com/) reports

VBA32 - Win32.Malware.Dropper.Heur
https://www.virustotal.com/gui/file/947e4aec1996d769583cea968b9a02e6517114ce7f9309269c6a67b1a4ac91f9 

https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.5.21/mmex-1.5.21-win64.exe
https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.5.21/mmex-1.5.21-win32.exe

Can you confirm if this is a false positive as other sources report the file as fine.

Mark
