### ISSUE TITLE
MMEX 1.5.21, 1.5.20 : wrong balance

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#5136]
MMEX version:
 - [ ] 1.5.19
 - [x] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The balance is calculated wrong in 1.5.21 :
![SummeFalsch](https://user-images.githubusercontent.com/93879362/192572421-3fad2569-1e54-4ff0-9235-0caaabef47f0.jpg)

It was correct in 1.5.19:
![Summekorrekt1_5_19](https://user-images.githubusercontent.com/93879362/192572552-b4d490f4-a54d-41b0-94fe-94ab59e054ac.jpg)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1) enter a new transaction
2) wrong balance calculated

Expected result:
Correct balance under all circumstances.
This is an important feature of mmex!

Actual result:
Wrong balance.

# Additional information

Is this some reordering bug?
![SummeFalsch_movesdown](https://user-images.githubusercontent.com/93879362/192573320-96edf48a-48f3-45d7-8ea0-a22986659940.jpg)

**Comment by whalley** [comment]
I can't make sense of this without seeing more of the transaction register and knowing the sort order. Can you provide more detail.

Have you tested the latest v1.5.22 beta?

**Comment by PMaff** [comment]
> I can't make sense of this without seeing more of the transaction register and knowing the sort order. Can you provide more detail.
> 
> Have you tested the latest v1.5.22 beta?

I just realized that the sorting algorithms are different in 1.5.22 beta so I switched to that one, where I can get the old date
sort order with correct balance.
I will close this issue now since the 1.5.22 beta seems to be better.
