### ISSUE TITLE
Columns order change on open

### ISSUE THREAD

**Issue by norameme** [moneymanagerex/moneymanagerex#5149]
> Replace this text (marked with >) 
Every time I am moving particular columns, and every time I open the file, they are always moving back.  Those columns are Balance, Status and Category.  The rest columns are, once moved, do not come back.
But the category, Status and balance, always move back.
If I hide them- they stay hidden, but if I move them i.e. change the order - they come back to where they were before I moved them.
I wonder why that is :)  or how to stop them.

> Please do not remove information attached below this text.

<hr>Version: 1.5.21 64-bit<br>
 • Build: Sep 21 2022 09:27:42<br>
 • db 7 •  (aes128cbc)<br>
 • git cb708cc (2022-09-21)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1776x1000 32bit 96x96ppi

**Comment by renato-mmex** [comment]
would it be possible to document the problem a little better, for example with screen shots

**Comment by norameme** [comment]
sure.
Created new account - so there are no entries - please pay attention to the column:   Status and Category and Balance
Screenshot 1 [SC1_ScreenHunter_1132 Oct  01 22 52](https://user-images.githubusercontent.com/112387322/193429780-cf502964-63a3-4cf0-b46f-02c2a86dcbef.jpg)
![SC3_ScreenHunter_1134 Oct  01 22 53](https://user-images.githubusercontent.com/112387322/193429792-104a00de-37b4-4cc8-a5c9-8da96afb51fa.jpg)
- they are in the 'original place'
screenshot 2 (SC
![SC2_ScreenHunter_1133 Oct  01 22 52](https://user-images.githubusercontent.com/112387322/193429787-384aa2c2-8d38-4dc7-90d5-34a8b47abce3.jpg) 
- I moved them to where I want them  all 3 in different places
then I closed the application. -> and restarted the application
screenshot 3 ![SC3_ScreenHunter_1134 Oct  01 22 53] (https://user-images.githubusercontent.com/112387322/193429792-104a00de-37b4-4cc8-a5c9-8da96afb51fa.jpg) - they are all back to the original place!
Why?
lol
![SC3_ScreenHunter_1134 Oct  01 22 53](https://user-images.githubusercontent.com/112387322/193429846-626371d3-a6ec-49b9-a81a-684bbd0d6481.jpg)
![SC1_ScreenHunter_1132 Oct  01 22 52](https://user-images.githubusercontent.com/112387322/193429849-e2128081-5dc2-4bec-910a-b17a1ee58ca3.jpg)
![SC2_ScreenHunter_1133 Oct  01 22 52](https://user-images.githubusercontent.com/112387322/193429851-c2d614d3-e9d2-4869-b27b-bd6b5d599e3d.jpg)

**Comment by renato-mmex** [comment]
thanks, this really seems to be a bug

**Comment by tactilis** [comment]
Duplicate issue.

Please see https://github.com/moneymanagerex/moneymanagerex/issues/4160
