### ISSUE TITLE
Charts are now showing in Windows 64x Portable version.

### ISSUE THREAD

**Issue by dsmalinda** [moneymanagerex/moneymanagerex#5151]
MMEX version:
 - [x] 1.5.19
 - [x ] 1.5.20
 - [x] 1.5.21
 - [x] 1.5.22 Beta
 - [x] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In newer version (Tested on Portable versions only) Charts are not visible in Windows 8. Charts are visible as expected in older version. This can be fixed by replacing older version of **apexcharts.min.js** in **mmex-1.5.xx-win64\res** folder

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Check any chart. Those are not visible

Expected result:

Charts should be visible

Actual result:

Charts are not visible

# Additional information

I was able to fix it by replacing  **apexcharts.min.js**  file in **res** folder. I used an older version of it (Took it from **version 1.5.2**). This solved the issue in newer versions. 

![new js](https://user-images.githubusercontent.com/7107021/193412604-e55ebfa2-3392-4658-9c7f-f6f3deeacd53.PNG)
![old js](https://user-images.githubusercontent.com/7107021/193413012-5f64d2b9-ad11-44af-b368-c74b4900f720.PNG)

**Comment by renato-mmex** [comment]
I have downloaded under Windows 11 Prof 64 Bit the latest .zip version of:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44935400/job/qp8sa43blbsx4nwk/artifacts, unzipped it and started the file .....bin/mmex.exe.
All graphics work for me without problems.

**Comment by whalley** [comment]
I'm afraid Windows 8 is now 10 years old, and whilst it would be great to test, configure, and support older operating systems I'm not sure anybody has the time to do this. All I can suggest is upgrading your installation.
