### ISSUE TITLE
Money Manager balances incorrect

### ISSUE THREAD

**Issue by MelStPier** [moneymanagerex/moneymanagerex#5159]
>The balance calculated with withdrawals and deposits is not calculating correctly.
> Please do not remove information attached below this text.

<hr>Version: 1.5.21 64-bit<br>
 • Build: Sep 21 2022 09:27:42<br>
 • db 7 •  (aes128cbc)<br>
 • git cb708cc (2022-09-21)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1680x1050 32bit 96x96ppi

**Comment by tactilis** [comment]
Duplicate report.

Please see https://github.com/moneymanagerex/moneymanagerex/issues/5139
