### ISSUE TITLE
MMEX v1.5.21 64bit on Mac Catalina 10.15.7

### ISSUE THREAD

**Issue by swanupping** [moneymanagerex/moneymanagerex#5161]
Hi, I'm running MMEX v1.5.21 64bit on Mac Catalina 10.15.7 and seem to have an issue with the app calculating correctly. Even if I try and change dates when payments are made the issue doesn't change. 
I have attached a pdf of one of my accounts to illustrate and you will see that the withdrawal and deposit columns don't result in the correct balance. The green bar in the pdf shows the correct balance from my bank statement.
[MMEX Screenshot 2022-10-04 at 18.48.22.png.pdf](https://github.com/moneymanagerex/moneymanagerex/files/9709551/MMEX.Screenshot.2022-10-04.at.18.48.22.png.pdf)

**Comment by tactilis** [comment]
Duplicate report.

Please see https://github.com/moneymanagerex/moneymanagerex/issues/5139

It looks as though you sorted on a column (other than Date) and then by Date because the IDs are out of order.
