### ISSUE TITLE
Budget history actual totals no longer exclusive to month/year label

### ISSUE THREAD

**Issue by i-embree** [moneymanagerex/moneymanagerex#5165]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The totals in the Actual fields for historical budget pages (those set for prior months/years) are no longer exclusive to the month/year to which they have been set

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Enter transactions for the current month and prior months/years
2. Create budget pages for the months and years where transactions were entered (month pages are based on year pages)

_Expected result:_ Each budget page has totals from transactions exclusively from the month/year to which the page was set

_Actual result:_ Each budget page has totals from transactions whose entry dates are greater than or equal to the month/year to which the page was set

# Additional information

Demo video of this issue is attached

https://user-images.githubusercontent.com/115386454/194739141-1f2d158e-f5c1-4ab6-8b5c-91c4f69edf1e.mp4

**Comment by i-embree** [comment]
Confirmed that this issue is not present in version 1.5.20

**Comment by whalley** [comment]
Already reported and fixed hopefully. https://github.com/moneymanagerex/moneymanagerex/issues/5137

You could try the latest beta if you want to confirm. https://ci.appveyor.com/project/moneymanagerex/moneymanagerex

**Comment by i-embree** [comment]
Oh!  I did not find that original issue when I searched before.  Thank you for pointing me to it.  Sorry about the issue duplication!
