### ISSUE TITLE
Support for additional date ranges

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5167]
Raised via e-mail...

Could you update the Income v Expenses - with 2 Weeks or 14 Days and 2 Months or 60 Days as another options.

**Comment by n-stein** [comment]
Is this related to the Income vs Expenses chart on the homepage (in which case this was resolved by #6072) or to the "Income vs Expenses - Monthly" report?

**Comment by whalley** [comment]
Closed as indeed covered by #6072
