### ISSUE TITLE
Can not save Category_V1 / Subcategory_1

### ISSUE THREAD

**Issue by TomAff** [moneymanagerex/moneymanagerex#5170]
MMEX version: V1.6.0-Beta. 1 64 Bit
 - [x] Windows
Error comes up after database is updated

![2022-10-11 18_07_32-Window](https://user-images.githubusercontent.com/46572503/195144100-1e5e9913-5dea-4fc7-97a8-c7456c0aca87.jpg)

**Comment by TomAff** [comment]
It seems that everything works fine

**Comment by whalley** [comment]
Did it occur directly after the upgrade message or did you add any transaction, change categories, etc before this appeared.

**Comment by TomAff** [comment]
On startup: MMEX Database update successfully done. Then I click on OK.
Then comes the error.

**Comment by whalley** [comment]
OK,  it maybe this code that migrated the 'hidden' category to the main DB tables....
https://github.com/whalley/moneymanagerex/commit/52e7e756f930772e7306730058a9c9b9a2332ec2#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4 it could better protect itself.

Did you have hidden categories previously that are now unhidden?

**Comment by TomAff** [comment]
I used a backup and started with the last MMEX Version. I set all (sub)categories to "show" and started the database with the MMEX beta. Same issue

**Comment by TomAff** [comment]
in the new database the field "active" is 1 in both tables for all (sub)categories

**Comment by whalley** [comment]
If you go back to the old DB what is the setting for INFOTABLE_V1 with INFONAME = HIDDEN_CATEGS_ID ?

`select * from INFOTABLE_V1 where INFONAME = "HIDDEN_CATEGS_ID";`

**Comment by whalley** [comment]
OK, try this:

- Take a copy of that DB and then delete that row.
- Now open that DB in the MMEX Beta to perform the upgrade

Do you get the same error?

**Comment by TomAff** [comment]
No Error! :)

**Comment by whalley** [comment]
Great. So we have narrowed it down a bit...
Can you check that in the database you have CATEGORY_V1 entries for CATEGID = 243, 229, 252, 230, 253, 254, 239, 223, 237 and SUBCATEGORY_V1 entries for 36, 157

**Comment by TomAff** [comment]
Cat 243 and Subcat 157 were missing

**Comment by whalley** [comment]
OK thanks for the testing, seems like the old code somehow left behind remnants of a cat/subcat that had been deleted. I will add logic to catch this.  

Please leave the ticket open and I'll push a fix and you can test with your old DB to make sure it is handled.

**Comment by whalley** [comment]
@TomAff Please test again with the original DB using this build https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/45037158/job/oto9ex6wlgexa9g3/artifacts

**Comment by TomAff** [comment]
Tested. No error!
