### ISSUE TITLE
Monthly budget "Actual" coloum logic error

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#5172]
MMEX version:
 - [x] 1.5.21

Operating System:
 - [x] Linux 

# Description of the bug

The "Actual" column in the **Budget Setup** for a month shows the sum of all actual expenses from the said month until now. e.g. For month September, the Actual expense shows sum of expenses in September and expenses until now in October. 

# Reproduction

Is the bug reproducible? 
 - [x] Always

**Comment by whalley** [comment]
Should be fixed here: https://github.com/moneymanagerex/moneymanagerex/issues/5137

Latest Linux betas can be found here: https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/80/workflows/e49e0887-9149-462c-80e5-4c7ad19c1be2/jobs/81/artifacts
