### ISSUE TITLE
Reinvest dividend

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#5176]
### Discussed in https://github.com/moneymanagerex/moneymanagerex/discussions/5168

<div type='discussions-op-text'>

<sup>Originally posted by **arp2164** October 11, 2022</sup>
Can someone show me how to add dividend reinvestment in stock portfolio.
There are only two inputs 1. Withdrawal and 2. Deposit.
Adding transaction with deposit it removes the shares.
Do I have to use withdrawal?
Any help will be appreciated.
Ashok </div>

**Comment by whalley** [comment]
Suggest leaving as discussion for now as no issues to report (yet!).
