### ISSUE TITLE
balance of each line is incorrect

### ISSUE THREAD

**Issue by fj18-110** [moneymanagerex/moneymanagerex#5182]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

With 1.5.21, the balance of each line is incorrect

![image](https://user-images.githubusercontent.com/76882028/196031498-a5a50834-b2af-4b41-9c04-db372a0903b2.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by fj18-110** [comment]
> 

OK thanks.

But even with sort by OPID, the balance is incorrect....
![image](https://user-images.githubusercontent.com/76882028/196033599-c5756656-d8fd-4d26-bd75-20288562b5ce.png)

Which sort shoud i apply ?

**Comment by whalley** [comment]
Click sort by ID then click Sort by Date in the same direction. What do you get then?

**Comment by fj18-110** [comment]
I've reinstalled previous version. Thanks.

**Comment by whalley** [comment]
v1.6.0 should be out in the next few weeks, however you can try the latest beta here... https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/45082799/job/qhd4n703pj34w7ck/artifacts if you want to give it a go.

**Comment by fj18-110** [comment]
I've installed your beta.
At first launch, MMEX proposes to optimize the database. I've done it.

At the first display, the error remains.
But after a click to switch to Transaction ID order, and another one to come back to date order, it looks like OK.
 
Thanks.

**Comment by whalley** [comment]
Great. Yes we now force source by date to then sort by ID. There is also now an indication of the primary and secondary sort orders.
