### ISSUE TITLE
Transaction Report Date Range not saved

### ISSUE THREAD

**Issue by creepshow007** [moneymanagerex/moneymanagerex#5193]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

When I create a transaction report with a date range (for example 01.01.2022 - 30.06.2022) and save this report, then the result is correct. But when I click the saved report again to show the result, then the date range is always set to today 

Picture 1: set of date range
<img width="558" alt="01_Date_range_set" src="https://user-images.githubusercontent.com/115988185/196363740-bba4e93c-8777-4a74-bf42-0a992039578b.png">

Picture 2: shown date range after save
<img width="513" alt="02_date_range_after_save" src="https://user-images.githubusercontent.com/115988185/196364185-bec9b39d-4731-481c-a843-407279827e0b.png">

Picture 3: shown date range after reopen saved report again
<img width="514" alt="03_date_range_after_reopen_report" src="https://user-images.githubusercontent.com/115988185/196364310-596bfca2-3b90-4dcd-9242-c7e189c0ef54.png">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. create new transaction report with date range
2. save transaction report under a name -> report is open with correct date range
3. open saved transaction report again -> report is open with date range only from today to today

Expected result:
Saved transaction report should also save the date range and when open report again the correct date range should be shown in the result

Actual result:
Saved report is open with date range only from today to today

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Confirmed.
