### ISSUE TITLE
Display Options - Full Transactions Report

### ISSUE THREAD

**Issue by sharkei2018** [moneymanagerex/moneymanagerex#5195]
I've been using Money Manager for a long time and have only just discovered the Full Transactions Report that is available by selecting All Transactions from the Navigation Panel!  What a useful report.

There is a display option that I would like added to the available list and that is Next 7 Days, or even next ? days with the functionality to add a variable number of days.

Current month as a selection does this at the beginning of the month (next 31 days), but reduces to less than 7 days as you approach the end of the month.

I have searched GitHub and the Forum and have been unable to find any other discussions for such a feature, but I apologise if I have missed it or that it can be done using the existing selection criteria.

Such a selection would help me to manage my week ahead cash flow, avoiding the possibility of 'forgetting' about a withdrawal which might mean an account becomes overdrawn.

**Comment by tactilis** [comment]
As a simple work around for your request you could use the Advanced Filter and select the Date Range as shown below.

You could even save this as a named Setting as I have shown and update the date range and re-save it when you wish.
 
![image](https://user-images.githubusercontent.com/4060092/196420702-df9ca068-9cc0-4129-87ac-0e78cbe9cf6f.png)

**Comment by whalley** [comment]
Note that the transaction report only considers transactions that have been posted to an account (which could be future dated) and does not consider transactions that are scheduled (but un-posted) in the recurring transactions.  For reviewing the effect of future scheduled transactions the 'Cash Flow' / ' Transactions' report is probably more suitable.

**Comment by sharkei2018** [comment]
Hi Martin

Yes I had explored the Advanced Filter and as you say, as a work around, I could set up the date range and then just update it every day to roll it forward.  Unfortunately you can't do this if you are in Account View for a single account.  The save as a named Setting is not there, but the date range entered for the Account is remembered by MMEx.
Screenshot

I have also explored the Period Range selection of the Advanced Filter but there aren't any selections which are for future date ranges starting today.

Anyway, the work around you suggest is probably the easiest to set up and maintain in the last week of the month (7 Days), using Current month for the rest of the month, even though Current Month will show posted transactions more than 7 days in the future in the first 3 weeks of the month (if there are any).

**Comment by whalley** [comment]
I think what you want is covered by this enhancement request.
https://github.com/moneymanagerex/moneymanagerex/issues/1633

I'll close this one and see if we can get this feature into v1.6.1 as I think it would be a useful addition.
