### ISSUE TITLE
`en-US` if locale=invalid. was: `mmEx Error` dialog with comment `locale::facet::_S_create_c_locale name not valid`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5204]
MMEX version: 1.5.21

```
Money Manager Ex
Version: 1.5.21 64-bit
• Build on Sep 21 2022 10:21:17
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• lunasvg v2.3.1
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu.22.04.jammy
Running on:
• Linux Mint 21 "vanessa"
• Linux 5.15.0-52-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

Operating System: [Linux Mint](https://linuxmint.com/) 21 Cinnamon

# Description of the bug

# Reproduction

Is the bug reproducible? Always

Reproduction steps:

1. `Create a New Database`
2. Select location `/Desktop/appdata/mmex/test1.mmb`
3. `New Database Wizard`
4. Currency = `AUD`
5. Username = `Óvári`
6. Name of the Account = `s3`
7. `mmEx Error` dialog with comment `locale::facet::_S_create_c_locale name not valid` as shown in the image below:
![image](https://user-images.githubusercontent.com/17465872/197282153-4a83dab7-8a22-48a2-ad45-5b5440d1eb3d.png)

Expected result:
No error

Actual result:
`mmEx Error` dialog with comment `locale::facet::_S_create_c_locale name not valid`

# Additional information

System locale = `English, Australia`
![Language Settings](https://user-images.githubusercontent.com/17465872/197284132-839540df-db05-4eea-a9e5-363b95231f1a.png)

Please advise the commands to produce a backtrace if required.

Thank you

**Comment by whalley** [comment]
See: https://github.com/moneymanagerex/moneymanagerex/issues/3394

**Comment by ovari** [comment]
> See: https://github.com/moneymanagerex/moneymanagerex/issues/3394

Thank you, have added a comment [there](https://github.com/moneymanagerex/moneymanagerex/issues/3394#issuecomment-1288182280).

Should this issue be closed and the issue you referenced re-opened?

**Comment by ovari** [comment]
Fixed with

```
$ sudo dpkg-reconfigure locales
```

Thank you

**Comment by ovari** [comment]
Removing all the languages to only show
![image](https://user-images.githubusercontent.com/17465872/197416604-dad24656-3364-4f74-be57-411dd2f71f23.png)

Then the error comes back.

Can MMEX please work without `en-US` being installed?

i.e. if the language is no present, can MMEX default to `en-US` without installing the `en-US` locale on the operating system?

What do you think?

**Comment by whalley** [comment]
What currency locale do you have specified in MMEX?

![CleanShot 2022-10-24 at 00 26 30](https://user-images.githubusercontent.com/487345/197423275-19e59d4e-b808-4ef7-ba41-387b7540515e.png)

If the locales is not available then just leave blank and defined against the currency.

**Comment by ovari** [comment]
1. MMEX opens because en-US locale is installed (screenshot of `Language Settings` in Linux Mint)
![English, United States locale fully installed](https://user-images.githubusercontent.com/17465872/197423584-825896dd-a23b-4a79-995a-4b7fa709c613.png)
2. The MMEX options can be seen as MMEX doesn't crash
![MMEX Options](https://user-images.githubusercontent.com/17465872/197423552-e9d8ad23-4e8b-45ac-bf78-2268cb03afa5.png)
3. Now, remove English, United States locale (screenshot of `Language Settings` in Linux Mint)
![English, United States locale removed](https://user-images.githubusercontent.com/17465872/197423707-4f57570a-ad0c-49d5-85e5-f372bb745e97.png)
4. Open MMEX
5. Select `Open Last Opened Database`
6. Crash
![locale::facet::_S_create_c_locale name not valid](https://user-images.githubusercontent.com/17465872/197423771-dcb2456e-7cf3-478b-95d1-966dd8d43141.png)

> If the locales is not available then just leave blank and defined against the currency.

Unable to do this as MMEX crashed; however, currency is defined as English, Australia (screenshot of `Language Settings` in Linux Mint)
![Currency English, Australia](https://user-images.githubusercontent.com/17465872/197424018-630384e4-3103-4583-8b3e-b754cb7371f3.png)


Does this help?

**Comment by snezhniylis** [comment]
I have `en_GB.UTF-8` and `ru_RU.UTF-8` locales set, which leads to the same issue. The program will refuse to function properly until I add `en_US.UTF-8` to my `/etc/locale.gen` and regenerate locales with `locale-gen`.

Why isn't this issue discussed more? Doesn't this potentially break the program for the majority of English-speaking Linux users living outside the US?

**Comment by ovari** [comment]
@n-stein does https://github.com/moneymanagerex/moneymanagerex/pull/5679 resolve this issue? Thank you

**Comment by n-stein** [comment]
It very well may, though this issue wasn't on my radar when I submitted that change.

The point in the process where you are receiving this error message is when the account dialog is called. The function FromString2CLocale is called during this time and was previously coded to default to `en_US.UTF-8` when no locale was explicitly set in MMEX options (which would be the case on every new DB). Obviously this would be a problem if you didn't have `en_US-UTF-8` installed. The removal of the default should help. 

Give the beta a try once it's merged (for Linux that's around 3:30 AM UTC the day _after_ the pull request is merged as Linux builds are nightly).

**Comment by ovari** [comment]
Error still present in
```
• Version: 1.6.4-Beta.2 64-bit
• Built on: Feb 20 2023 03:27:10
• Database version: 17 (aes128cbc)
```

**Comment by n-stein** [comment]
That should fix it. Test after it is merged.

**Comment by ovari** [comment]
Will test after merge. Thank you

**Comment by ovari** [comment]
If a locale is selected that is not supported by MMEX, does your patch still work? Thank you

**Comment by ovari** [comment]
> That should fix it. Test after https://github.com/moneymanagerex/moneymanagerex/pull/5700 is merged.

Confirming fixed with https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/495/workflows/91723c24-7381-4297-874a-18983031d20f/jobs/491/artifacts

```
• Version: 1.6.4-Beta.2 64-bit
• Built on: Feb 23 2023 03:27:19
• Database version: 17 (aes128cbc)
```

@snezhniylis can you please test and if this works for you please comment `verified`?

Thank you

**Comment by snezhniylis** [comment]
> @snezhniylis can you please test and if this works for you please comment `verified fixed`?

Verified fixed. Thanks for tagging!
