### ISSUE TITLE
Crash when cancelling the creation of a new database if App Start Dialog has been used

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5205]
MMEX version:
 - [x] 1.6.0 Beta.2 64-bit Git commit: 3541038 (2022-10-19)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX crashes if you cancel the creation of a new database _if_ the App Start Dialog is used.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click Help | Show App Start Dialog
2. Tick 'Show this window next time Money Manager Ex starts'
3. Exit MMEX
4. Start MMEX
5. Click Create a New Database
6. Enter a name for the .mmb file and click Save
7. Click Cancel on the New Database Wizard.  MMEX crashes.

NOTE: MMEX does not crash if MMEX is already running and you use File | New Database... instead of the App Start Dialog.

https://user-images.githubusercontent.com/4060092/197332011-45ed566c-f596-4c9a-8936-acb226a766a9.mp4

**Comment by whalley** [comment]
Confirmed, I can reproduce.

**Comment by tactilis** [comment]
Confirmed fixed.
