### ISSUE TITLE
Transactions not saving upon entry

### ISSUE THREAD

**Issue by Crofter10** [moneymanagerex/moneymanagerex#5206]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ y] Mac OSX
 - [ ] Linux 

# Description of the bug

I have been trying out MMX with a view to moving from Excel spreadsheets. What happens now is when I enter. transaction and press enter it does not appear. At the same time, when I try and add a sequence number it skips from 32 to 34 instead of going from 32 to 33.

It may be that as a novice I am doing something silly :( so any help would be appreciated.

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@Crofter10

> What happens now is when I enter. transaction and press enter it does not appear. 

Have you perhaps inadvertently set the Transaction Filter to a date range that excludes the date of the transactions you are entering?

![image](https://user-images.githubusercontent.com/4060092/197359340-025cd8ee-d7ba-4c36-a947-a5abebd38c26.png)
 
 
> when I try and add a sequence number it skips from 32 to 34 instead of going from 32 to 33.

I expect you already have a transaction with Number set to 33. Clicking the 'Populate Transaction #' MMEX generates a value N+1, where N is the highest Number that is already used by a transaction.

Is there any particular reason that you are populating the Number field sequentially? Most people don't do this. Some people use it to enter a cheque number (if the payment was by cheque), or sometimes a payment reference used by an external organisation.

**Comment by Crofter10** [comment]
tactilis thanks for your response. It does not appear to have been something to do with the date range and th good news is I have now managed to get the account working ok and it squares with my bank statement.

I have also stoped using the number field so that has given me less to think about and if I ever write a cheque again I can still use it for that.

**Comment by tactilis** [comment]
@Crofter10
> the good news is I have now managed to get the account working ok

That's good to hear.

There are a lot of capabilities in MMEX, which you will discover as you explore further. For example, once you get more familiar, you might want to export transactions from your bank and import them into MMEX, which saves manual entry.

If you have any questions, just ask in the `Discussions` tab above.
