### ISSUE TITLE
Issues with budget mgmt

### ISSUE THREAD

**Issue by Jackyzzz27** [moneymanagerex/moneymanagerex#5209]
> good morning, I noticed an issue whenever I open a yearly budget under the budget mgmt area.
In fact, the last column reporting money currently spent for each line, reports the money currently spent for the current year even if I select another year.
If I select, for example, the year 2015 I should see the money currently spent during that year, not 2022 (now). that was the case in the past, but not anymore.

How can I switch to the previous way of seeing data? 
Thanks,

Davide Tartari

> Per favore non rimuovere le informazoni allegate sotto questo testo.

<hr>Version: 1.5.21 64-bit<br>
 • Build: Set 21 2022 09:27:42<br>
 • db 7 •  (aes128cbc)<br>
 • git cb708cc (2022-09-21)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 6.1)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 7 (build 7601, Service Pack 1), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1366x768 32bit 96x96ppi

**Comment by whalley** [comment]
Will be fixed in the soon to be released v1.6.0. See https://github.com/moneymanagerex/moneymanagerex/issues/5137.
