### ISSUE TITLE
Toolbar buttons are erroneously greyed out when opening an existing database via App Start dialog

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5211]
MMEX version:
 - [x] 1.6.0 Beta.2 64-bit Git commit: 0dde336 (2022-10-23)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

If `Open Existing Database` on the App Start Dialog is used to open a DB, some toolbar buttons are erroneously greyed out until the user hovers the mouse over the toolbar.

This defect does not occur if the DB is opened via `Open Last Opened Database`.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

The video shows:

a) Using `Open Existing Database` to provoke the error.
b) Using `Open Last Opened Database` to open the same DB, which does not provoke the error.
c) Using `Open Existing Database` again to show that the error is repeatable.

https://user-images.githubusercontent.com/4060092/197414815-132e317a-b18b-49ba-8ad0-3d103b52a602.mp4

**Comment by whalley** [comment]
Seems to be Windows only issue. Have tested on Mac, Win, and Ubuntu; problem only occurs in Win.

**Comment by n-stein** [comment]
Fixed by PR #5286

**Comment by tactilis** [comment]
Confirmed fixed.
