### ISSUE TITLE
Add `User Interface Language` to `About` dialog

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5213]
Should the `About` dialog contain the system `locale` as it could help with debugging?

```
$ locale
```

https://github.com/moneymanagerex/moneymanagerex/issues/3394#issuecomment-1288182280

What do you think?

Thank you

**Comment by ovari** [comment]
@joshua-stone can this please be added? Thank you

**Comment by joshua-stone** [comment]
How exactly would you like this to be achieved? Embed the equivalent to the following code?

```c++
#include <iostream>
#include <locale>

int main() {
    std::cout << "Locale: " << std::locale("").name() << std::endl;
}
```

```
$ g++ locale.cpp -o locale
$ ./locale 
Locale: en_US.UTF-8
```

**Comment by joshua-stone** [comment]
It's also possible for someone to share locale output from the flatpak environment for debugging purposes:

```
$ flatpak run --command=locale org.moneymanagerex.MMEX 
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by ovari** [comment]
Sorry for the misunderstanding.

Whatever the `User Interface Language` is set in MMEX using `Menu Bar` > `View` > `User Interface Language` > `hu-HU magyar (Magyarország)`

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/6443f87b-017e-4236-918e-92f5470136a6)

At the moment, the MMEX About dialog does not show the `User Interface Language`, i.e. `hu-HU magyar (Magyarország)`.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/8274ad38-2d3b-4c6a-afd5-bd08b960358c)

When writing bug reports, it may be useful to copy and paste the information in the `About` dialog like so:

```
Money Manager Ex
• Verzió: 1.7.0-Beta.1 64 bites
• Készítési időpont: okt. 23 2023, 23:09:00
• Adatbázis verziója: 19 (aes128cbc)
• Git-végrehajtás: ebd054da9 (2023-10-24)
• Git-ág: master
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.2.3 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.4.0-DEV OpenSSL/3.1.3 zlib/1.3 nghttp2/1.56.0
• gettext 0.22
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.27.7
• GNU Make 4.4.1
• GCC 13.2.0
Fut a következőn:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-87-generic x86_64
• English (Australia) (UTF-8)
• 1440x810 24bit 96x96ppi
```

Having `hu-HU magyar (Magyarország)` may be beneficial without users doing special commands.

Thank you

**Comment by joshua-stone** [comment]
@whalley Are there any more changes needed for this enhancement?

**Comment by ovari** [comment]
Thank you for the improvement @joshua-stone.

Can the following please be translated?
1. `System Locale: %s`
2. For consistency, can the English source string `User Application Language: %s` be changed to `User Interface Language: %s`?
3. Should `User Interface Language: %s` be moved to the first section in the About dialog box?
4. Can `bit` and `ppi` please be translatable? `bit` is already translated in the first section.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/098830c9-8a6f-4c5f-99ca-3704612ce3ae)

Thank you once again

**Comment by joshua-stone** [comment]
> Thank you for the improvement @joshua-stone.
> 
> Can the following please be translated?
> 
>     1. `System Locale: %s`
> 
>     2. For consistency, can the English source string `User Application Language: %s` be changed to `User Interface Language: %s`?
> 
>     3. Should `User Interface Language: %s` be moved to the first section in the About dialog box?
> 
>     4. Can `bit` and `ppi` please be translatable? `bit` is already translated in the first section.
> 
> 
> ![image](https://user-images.githubusercontent.com/17465872/278856538-098830c9-8a6f-4c5f-99ca-3704612ce3ae.png)
> 
> Thank you once again

I have a PR that addresses a few of these points:

https://github.com/moneymanagerex/moneymanagerex/pull/6267

I don't have the resources to provide translations for other languages, so volunteers will have to provide their own translations.

As for moving the language strings -- The About dialog seems to group info into three distinct sections

1) version information regarding MMEX, set at build time
2) version information about libraries that MMEX is using, also set at build time
3) system information, which is subject to change.

Having the language strings in group 3 seems most appropriate since the locale and user interface language can change just as much as the kernel version and desktop environment.

**Comment by ovari** [comment]
> I have a PR that addresses a few of these points: https://github.com/moneymanagerex/moneymanagerex/pull/6267

Thank you, please see comment at https://github.com/moneymanagerex/moneymanagerex/pull/6267/files#diff-e7ea321f7d93e2178590e75e0b219718f24f795890c6ee10c5ce3aae1ddbe710R6583

> Volunteers will have to provide their own translations.

Do you know when it will be available to translate at [CrowdIn](https://crowdin.com/project/moneymanagerex)?

> Having the language strings in group 3 seems most appropriate since the locale and user interface language can change just as much as the kernel version and desktop environment.

Thank you for your explanation.

**Comment by joshua-stone** [comment]
> > I have a PR that addresses a few of these points: #6267
> 
> Thank you, please see comment at https://github.com/moneymanagerex/moneymanagerex/pull/6267/files#diff-e7ea321f7d93e2178590e75e0b219718f24f795890c6ee10c5ce3aae1ddbe710R6583
> 

I don't see a comment:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/8183967/b0823816-618d-4f30-8103-f51b8dedcd5c)

> > Volunteers will have to provide their own translations.
> 
> Do you know when it will be available to translate at [CrowdIn](https://crowdin.com/project/moneymanagerex)?
> 

I do not, because I'm not familiar with Crowdin. If there's anyone more familiar with the process who can start translating, then that'd be appreciated.

**Comment by ovari** [comment]
> I don't see a comment:

Sorry, didn't realize needed to submit the comment. Should be [there](https://github.com/moneymanagerex/moneymanagerex/pull/6267#pullrequestreview-1703032873) now.
