### ISSUE TITLE
Show default categories show in the locale of the GUI

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5214]
```
Money Manager Ex
Version: 1.6.0-Beta.2 64-bit
• Build on Oct 22 2022 03:26:47
• Database version: 15 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu.22.04.jammy
Running on:
• Linux Mint 21 "vanessa"
• Linux 5.15.0-52-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```
Operating System: Linux Mint 21 Cinnamon

# Description of the bug
When changing the locale, the default category labels should be localized; unfortunately, the default category labels do not change.

# Reproduction

Is the bug reproducible? Always 

## Reproduction steps
1. Open MMEX with the system locale as hu (Hungarian - magyar).
2. All the categories show in Hungarian.
3. Change the system locale to en-AU (English, Australian).
4. The default categories still show in Hungarian.

![Organize Categories](https://user-images.githubusercontent.com/17465872/197417393-e775c13a-37e3-416f-92e0-667b485be829.png)

## Expected result
The default category labels should show in English.

## Actual result
The default category labels show in Hungarian.

Thank you

**Comment by tactilis** [comment]
This is a feature, not a bug.

The default category names are created using the language that is set when a new database is created.

It would not be easy to translate / re-populate the categories table if you switch the language at a later point because, at that time, the user may have added/deleted/modified the existing categories.

**Comment by ovari** [comment]
> What is your use case for wanting the behaviour you describe please?

* Husband and wife use same computer.
* One signs into computer with Hungarian locale, **default** categories shown in Hungarian.
* At other times the other signs into computer with English locale, **default** categories shown in English.
* Both are using the same MMEX database, with the GUI in their preferred languages. This feature would show the **default** categories in each user's preferred language.

Closing as wontfix as you wrote

> This is a feature, not a bug.

Thank you once again.

**Comment by tactilis** [comment]
Interesting use case @ovari. I can understand why you have asked for the capability.

There's nothing special about the initial (i.e. default) set of categories that are inserted into the categories table when a database is created. They are just there as a 'starter' for the user to adapt however they wish.

MMEX could be supplied with no categories at all and then it would be up to the user to create those that they require. In your case you would then have to choose whether you wanted to create them in English or Hungarian, or even a mixture of the two.

Which would you choose?

**Comment by ovari** [comment]
There are solutions that would make categories show in the locale [out-of-the-box](https://idioms.thefreedictionary.com/Out-of-the-Box); however, there seems to be more pressing issues like:
* https://github.com/moneymanagerex/moneymanagerex/issues/1477
* https://github.com/moneymanagerex/moneymanagerex/issues/5204
* https://github.com/moneymanagerex/moneymanagerex/issues/5216
* https://github.com/moneymanagerex/moneymanagerex/issues/1806
* https://github.com/moneymanagerex/moneymanagerex/issues/1946

**Comment by whalley** [comment]
I don't see any of those as 'pressing' issues.... Admittedly #5204 is a pain but can be worked around by installing en_GB locale.

**Comment by whalley** [comment]
> There are solutions that would make categories show in the locale [out-of-the-box](https://idioms.thefreedictionary.com/Out-of-the-Box)

What solutions are you thinking of?

**Comment by PMaff** [comment]
Btw. the bold display of entries that are "unreconciled" is a very good feature!
Thanks all.
