### ISSUE TITLE
New database wizard is too wide when application language is French

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5218]
MMEX version:
 - [x] 1.6.0 Beta.2 64-bit Git commit: e80b1df (2022-10-23)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When the application language is French, the text on the New Database Wizard is too wide for the screen and is cropped.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Set the language to French.
2. Create a new database.
3. See screenshot below. I've overlaid the English dialog for comparison.

Wizard dialog is too wide - possibly due to missing line breaks in the French translation file?
 
![image](https://user-images.githubusercontent.com/4060092/197420203-e0deb5a7-5482-471b-9b45-2af1417313a3.png)

**Comment by whalley** [comment]
Yes, it's the French translation. I have edited to include line breaks. Should be picked up in next batch of translations.
