### ISSUE TITLE
Search bank account

### ISSUE THREAD

**Issue by maffionegroup** [moneymanagerex/moneymanagerex#5220]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

Italian
quando effettuo la ricerca nei conti bancari inserendo dei filtri la prima ricerca funziona correttamente.
La seconda ricerca esce vuota, pagina bianca.
Chiudendo il programma e aprendo di nuovo la ricerca funziona.

English
when I search the bank accounts by inserting filters the first search works correctly.
The second search comes out blank, blank page.
Closing the program and opening the search again works.

**Comment by whalley** [comment]
Can you provide some screenshots to show which filters you are using please.
