### ISSUE TITLE
AGGIUNGERE UNA CATEGORIA

### ISSUE THREAD

**Issue by maffionegroup** [moneymanagerex/moneymanagerex#5221]
# Description of the feature

Please describe your feature with details.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

Vi chiedo se possibile aggiungere un'altra categoria sotto i conti bancari, portarlo a 3 livelli di categorie

I ask you if possible add another category under bank accounts, bring it to 3 levels of categories

**Comment by whalley** [comment]
Already suggested and likely to implemented. See: https://github.com/moneymanagerex/moneymanagerex/issues/1477
