### ISSUE TITLE
new asset account is shown only after restart

### ISSUE THREAD

**Issue by MiroslavMikus** [moneymanagerex/moneymanagerex#5222]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.6.0 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug & Reproduction
1. Create a new asset with account
2. Asset account is missing
3. Restart MMEX
4. Asset account is shown:

![mmex](https://user-images.githubusercontent.com/29312172/198078483-13ab18de-682f-451e-8542-e5fff0c9c63a.gif)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Expected result:
It would be nice if I do not have to restart MMEX

Actual result:
I have to.

Thanks in advice :)

**Comment by whalley** [comment]
@MiroslavMikus Thanks for reporting. Fix will be in next release.
