### ISSUE TITLE
macOS Beta Builds - Where Did They Go?

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#5226]
I get a screen to login into a Microsoft account. Oh no, a Microsoft account for a Mac user! Say it isn't so!

Before the login screen a page flashes briefly a looks like it says something about no longer available.

**Comment by whalley** [comment]
Yes, I had to change the link. I did update the page here: https://moneymanagerex.org/docs/downloads/development/ but obviously you have it bookmarked.

**https://link.ipx.co.uk/mmex-mac-betas**

Yes, I use M365 on my Mac 😞

**Comment by 2BeeOrNot** [comment]
Yes I had the page bookmarked.
I also tried the beta link at https://mmex.ipx.co.uk/ which didn't work.
The link above works. Thanks.

**Comment by whalley** [comment]
> I also tried the beta link at https://mmex.ipx.co.uk/ which didn't work. 

Opps, missed that one! Will fix.
