### ISSUE TITLE
DB Version 15 destroys important exchange with Android mmex!

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#5230]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 
 - [x] Android

# Description of the bug

previously with 1.5.22 Beta I was able to exchange the DB with my Android mmex.
One of the best features of mmex!
Now with 1.6.0 and the update to DB vers 15 this is gone.
I cannot simply copy the DB to my handy and work with Android mmex there and put it back to
my Linux machine afterwards.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Upgrade DB to Vers 15 with mmex 1.6.0, there is no other way, which is bad.

Expected result:
Keep the exchange with Android mmex. 
One of the best features of mmex.

Actual result:
Error message on Android mmex.
Cannot exchange database anymore.
I will have to revert to 1.5.22 Beta to keep interchange with Android mmex.
That is really bad.

**Comment by tactilis** [comment]
The Release Notes made this clear:

"NOTE: Your database will be updated once you run this version. You will then not be able to open your database with earlier versions of the software or likely run Android versions with the same database. As ever, it is recommended to take a copy of your database prior to installing any new software version"

@PMaff 
> I will have to revert to 1.5.22 Beta to keep interchange with Android mmex.
> That is really bad.

The problem is not with the MMEX desktop application. The database schema has to change to enable to application to evolve and provide more functionality.

The problem is with the Android version of MMEX. Nobody is available to support it and evolve it in step with the desktop version.

**Comment by whalley** [comment]
As noted by @tactilis this is an effect of the Android version no longer being actively maintained. If you want to maintain MMEX Android compatibility then you are going to have to stick with v1.5.21 for the foreseeable future. 

Maintaining the compatibility was holding back the desktop application development that we could no longer allow.

**Comment by Airtay** [comment]
Hello
I experienced the same issue (apologized, I didn't read the warning, as previous updates were OK)
Now my database is upgraded, Does any one knows how to comeback ? I reinstalled previous version 1.5.20, but it can't read the upgraded database. 
Android sync is very important for me
Thank you in advance if you can help me

**Comment by tactilis** [comment]
@Airtay 
The database upgrade process will have produced a series of backup files:

Database_Name_mmb_upgrade_v7_2022-10-30.bak
Database_Name_mmb_upgrade_v8_2022-10-30.bak
...
Database_Name_mmb_upgrade_v14_2022-10-30.bak

(where 2022-10-30 is the date you upgraded)

Database_Name_mmb_upgrade_v7_2022-10-30.bak is a *copy* of your original database prior to upgrade.

1. Reinstall the earlier version of MMEX that your are happy with.
2. Take a copy of the v7 .bak file and rename it to Database_name.mmb
3. Open that .mmb with the earlier version of MMEX

**Comment by Airtay** [comment]
Thank you so much for this answer. But I can’t find the .bak files , can you telle me in which directory they are ? I tried the finding tool, without success.
Thank you again

Airtay

De : Martin ***@***.***>
Envoyé : dimanche 30 octobre 2022 13:01
À : moneymanagerex/moneymanagerex ***@***.***>
Cc : Airtay ***@***.***>; Mention ***@***.***>
Objet : Re: [moneymanagerex/moneymanagerex] DB Version 15 destroys important exchange with Android mmex! (Issue #5230)


@Airtay<https://github.com/Airtay>
The database upgrade process will have produced a series of backup files:

Database_Name_mmb_upgrade_v7_2022-10-30.bak
Database_Name_mmb_upgrade_v8_2022-10-30.bak
...
Database_Name_mmb_upgrade_v14_2022-10-30.bak

(where 2022-10-30 is the date you upgraded)

Database_Name_mmb_upgrade_v7_2022-10-30.bak is a copy of your original database prior to upgrade.

  1.  Reinstall the earlier version of MMEX that your are happy with.
  2.  Take a copy of the v7 .bak file and rename it to Database_name.mmb
  3.  Open that .mmb with the earlier version of MMEX

**Comment by tactilis** [comment]
>  I can’t find the .bak files, can you tell  me in which directory they are ?

Just like the 'normal database backups (which hopefully you have enabled in MMEX | Options), the upgrade backups should be in the same directory as your .mmb file.

They are so on Windows. I see no reason they should be elsewhere on Linux; perhaps someone could confirm please.

**Comment by PMaff** [comment]
> The Release Notes made this clear:
> 
> "NOTE: Your database will be updated once you run this version. You will then not be able to open your database with earlier versions of the software or likely run Android versions with the same database. As ever, it is recommended to take a copy of your database prior to installing any new software version"
> 
> @PMaff
> 
> > I will have to revert to 1.5.22 Beta to keep interchange with Android mmex.
> > That is really bad.
> 
> The problem is not with the MMEX desktop application. The database schema has to change to enable to application to evolve and provide more functionality.
> 
> The problem is with the Android version of MMEX. Nobody is available to support it and evolve it in step with the desktop version.

I've read the Release Note and still had the hope that there is some way to connect the PC version with Android.
I know the old problem, that the Android app is missing developers and that it is dead. :-(

For myself I came to the decision, that the Android app will be synced the last time today with my 
1.5.22beta version and then only used as a kind of cheap "notepad", which I will have to copy to
the PC version manually. :-(
This is a pity, but I understand you developers that you cannot lag behind all the time.
I also read the thread about DB upgrade (just can't find it now).

I do remember about some Web-MMEX: is this usable with the new DB version on an Android handy?

**Comment by whalley** [comment]
> I do remember about some Web-MMEX: is this usable with the new DB version on an Android handy?

Yes, I use it on iOS. Should work fine on Android. It is simply used to collate transactions whilst you are away from your desktop.
https://github.com/moneymanagerex/web-money-manager-ex

**Comment by Airtay** [comment]
I am on windows, the directory of the .mmb file is the dropbox one, and there is no .bak file inside. An other idea ?
Thank you in advance

**Comment by vomikan** [comment]
> I am on windows, the directory of the .mmb file is the dropbox one, and there is no .bak file inside. An other idea ?
> Thank you in advance

Try to fined history of the file. The dropbox has a history of changes and you can roll back to an older version of the file.

**Comment by Airtay** [comment]
Yesss ! it was THE Good solution ! Thank you so much, I was afsaid to loose years. I promis to make 10 backups before each update now ;), an hope the Android app will be update.
Have a nice evening
Airtay

**Comment by tactilis** [comment]
>> dropbox has a history of changes and you can roll back to an older version of the file.

> Yesss ! it was THE Good solution

That's good news @Airtay. 

However, that does not explain why there were apparently no _upgrade_v7 to v14 .bak files generated when the DB upgrade was performed. Any thoughts @whalley, @vomikan ?

**Comment by whalley** [comment]
> Any thoughts @whalley, @vomikan ?

Nope.
