### ISSUE TITLE
When I set up the program I keep getting "MXL parsing error, mismatched tag' at line 6

### ISSUE THREAD

**Issue by Divitopark1** [moneymanagerex/moneymanagerex#5231]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.6.0 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by Divitopark1** [comment]
![Screenshot 2022-10-27 162954](https://user-images.githubusercontent.com/116844709/198394319-92ce6572-b56f-4203-a875-ba8374433ae2.jpg)
![image](https://user-images.githubusercontent.com/116844709/198394654-c7c5fcb2-d98e-4527-b137-21bffe806c61.png)

**Comment by Divitopark1** [comment]
My email is doug@divito.com  724-626-2000.

**Comment by whalley** [comment]
Wow that's an old version. I suggest upgrading to the latest version.

**Comment by tactilis** [comment]
@Divitopark1 

v1.3.3 was released in March 2017!

As @whalley suggests, please upgrade to the latest version v.1.6.0

**Comment by Divitopark1** [comment]
Great! That worked.
