### ISSUE TITLE
Can't connect to WebApp with v. 1.6.0

### ISSUE THREAD

**Issue by Jameskine** [moneymanagerex/moneymanagerex#5233]
I just updated my software version at 1.6.0 but I cannot connect to Web App anymore.
How can I solve?
![Cattura](https://user-images.githubusercontent.com/94283076/198413917-a2211b89-5f75-4bdd-b57b-0c1ee919eb14.PNG)

<hr>Version: 1.6.0 64-bit<br>
 • Build: Ott 27 2022 18:50:51<br>
 • db 15 •  (aes128cbc)<br>
 • git 9191e9b (2022-10-27)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
Hmmm, I'm not aware of anything we changed that would break this. Will need to do a bit of investigation/testing.

Thanks for reporting

**Comment by whalley** [comment]
I cannot reproduce this.
![CleanShot 2022-10-28 at 01 02 12](https://user-images.githubusercontent.com/487345/198419399-3c35def9-f7f8-4b74-9867-c4f861eefca4.png)

Tested with:
MMEX Desktop v1.6.0
WebApp v1.2.1
API v1.0.1

**Comment by whalley** [comment]
@Jameskine Are you still experiencing this? What version of the WebApp are you using?

**Comment by whalley** [comment]
No response. Closing.
