### ISSUE TITLE
Incorrect balance calculation

### ISSUE THREAD

**Issue by Patricen1** [moneymanagerex/moneymanagerex#5238]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [X] 1.6.0 
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

It looks like the issue https://github.com/moneymanagerex/moneymanagerex/issues/5122 is not closed within 1.6.0 version.
Within account view, some withdrawal operations are added to the balancewhile some of the deposit operations are substracted from the balance.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I think we need a bit more information than that. Can you please provide some evidence/screenshots/etc.

**Comment by tactilis** [comment]
@Patricen1
> It looks like the issue https://github.com/moneymanagerex/moneymanagerex/issues/5122 is not closed within 1.6.0 version.
Within account view, some withdrawal operations are added to the balancewhile some of the deposit operations are substracted from the balance.

Please ensure that you are sorting the account transactions by Date.

Click on the Date column header to sort ascending or descending as you choose.

Having done this, is the balance still incorrect

**Comment by Patricen1** [comment]
Oh right! That's a new feature, it wokrs!

**Comment by tactilis** [comment]
@Patricen1
> Oh right! That's a new feature, it works!

In fact, not a new feature. You could always click on **any** column header to set the sort order - but there was a bug (or rather a quirk) in 1.5.21 that could lead to user confusion.

This is fixed in 1.6.0
