### ISSUE TITLE
Merge duplicate rows in Category List

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5241]
```
Money Manager Ex
Version: 1.6.1-Beta.1 64-bit
• Build on Oct 28 2022 07:20:52
• Database version: 16 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0 • Ubuntu.22.04.jammy
Running on:
• Linux Mint 21 "vanessa"
• Linux 5.15.0-52-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

# Description of the bug

From https://github.com/moneymanagerex/moneymanagerex/issues/1477#issuecomment-1294100687

If a category has an amount and also has subcategories, should only 1 line show with `Amount` and `Total` on the one line?
(a) For example, merge the duplicate `Income` and `Miscellaneous` rows.

# Reproduction

Is the bug reproducible? Always

### Reproduction steps:

![image](https://user-images.githubusercontent.com/17465872/198543273-4fb3941e-52fb-4f7a-9454-8539d373d48b.png)

### Expected result:

https://github.com/moneymanagerex/moneymanagerex/issues/1477#issuecomment-1294234703

> This suggestion can only be applied to leaf categories. We could drop Miscellaneous down to one line but Income would have to stay at two. The issue is the two lines serve different purposes: The first line with the "+" is used for navigating the tree, and clicking on it shows/hides the children/subtree. The second line is a link to the transaction report for the category. On any node which has children we need to have both lines (you can see that Qualified and Unqualified only have the transaction link because they are leaves). In fact I originally wrote it in the way you suggest, but then switched to match the 1.6.0 report. **Again, only one line of code to change, the result is**:
>
> ![image](https://user-images.githubusercontent.com/17465872/198542955-b84802cc-266d-46a0-88e1-4254cc4b4ea7.png)

What do you think?

Thank you

**Comment by ovari** [comment]
If the current and proposed behaviour is required, perhaps there could be an `Option` button with the setting `Merge duplicate rows`,

The `Option` button is described with a screenshot of Quicken 2004 at https://github.com/moneymanagerex/moneymanagerex/issues/5242

**Comment by whalley** [comment]
My view: Any line that can be expanded/collapsed should just show total. The actual amounts are listed when you expand.

**Comment by n-stein** [comment]
I agree @whalley. I like the Total to be displayed only on the navigation nodes, and Amount only on the transaction link nodes. It gives you another visual indicator (other than the "+") that there is a different function for these node types.

I also think it looks odd if we suppress navigation rows for categories without children, especially when all other nodes are collapsed.

![image](https://user-images.githubusercontent.com/16599929/198695281-03ecddd4-f75b-43bd-b26f-5d44870cd37d.png)

Compare to current:

![image](https://user-images.githubusercontent.com/16599929/198694562-2e210f1d-7821-4f78-a33d-5011e08bb575.png)

**Comment by whalley** [comment]
We will leave as-is.
