### ISSUE TITLE
Option to `Show all amounts and totals` in Categories List

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5242]
# Description of the feature

Should the `Total` column always have a value?
(a) Even if it is the same as the `Amount` value?
For example: `Capital Gains`, `Qualified` and `Unqualified`.
(b) Even if it is zero?

![Current](https://user-images.githubusercontent.com/17465872/198545151-29d9bfbc-48a8-48cf-a587-46a145d5ff74.png)

@n-stein advised it is doable with image below https://github.com/moneymanagerex/moneymanagerex/issues/1477#issuecomment-1294234703

![Possible](https://user-images.githubusercontent.com/17465872/198544853-31109327-8deb-4964-aaee-6066139d3c10.png)

Perhaps there could be an `Options` button with a setting to `Show all amounts and totals`.

![image](https://user-images.githubusercontent.com/17465872/198546580-0ff9c0c3-c1b5-42ee-9def-1cc5503f296e.png)

In the `Options` button, there could be additional settings to toggle the columns, like:
* `Show Amount column`
* `Show Total column`

What do you think?

Thank you

**Comment by whalley** [comment]
Discusse and addressed by #5241
