### ISSUE TITLE
Latest v1.6.0 release breaks Android MMEX

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#5245]
Hi,

After upgrading to v1.6.0, compatibility with Android MMEX is broken. This appears to be due to https://github.com/moneymanagerex/moneymanagerex/issues/4216.

When starting Android MMEX, this error appears:

`Error: Can't downgrade database from version 15 to 7`

Downgrading to the previous v1.5.21 works as expected.

**Comment by tactilis** [comment]
Please see this discussion https://github.com/moneymanagerex/moneymanagerex/issues/5230

The Release Notes made this clear.

**Comment by user8446** [comment]
Thank you for pointing out this breaking change. Downgraded back to 1.5.21 for now as Android compatibility is a necessity for me.

**Comment by whalley** [comment]
> Downgraded back to 1.5.21 for now ....

You may be there for quite a long time!

**Comment by n-stein** [comment]
Added PR moneymanagerex/android-money-manager-ex#1435 to bring compatability up to v15

**Comment by n-stein** [comment]
I also added support for create/display/change INITIALDATE for accounts, but need to do a bit of cleanup to add checks for TRANSDATE >= INITIALDATE on transaction create/edit.

**Comment by user8446** [comment]
Great news thanks to @n-stein !!

**Comment by whalley** [comment]
@n-stein Presume we need to make changes for the nested categories also.

**Comment by n-stein** [comment]
Yup, I'll work on that now.
