### ISSUE TITLE
chart error

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#5248]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [ ] 1.6.0 Beta
 - [x] 1.6.0 Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Hello everyone!

The charts do not appear on the main page, in the reports, or in the update wizard.

![kép](https://user-images.githubusercontent.com/80578702/198683378-ef9c4c31-ec7e-459c-8f51-64ac39aad6a5.png)
![kép](https://user-images.githubusercontent.com/80578702/198683491-4706a1dc-8061-44ed-a637-7a8083a8b4fb.png)

![kép](https://user-images.githubusercontent.com/80578702/198682887-315b9521-eacd-45c1-a0f6-c7e9f96647af.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Can't reproduce on Windows
![image](https://user-images.githubusercontent.com/16599929/198689948-50914046-3307-4038-8912-1bade663bce4.png)

**Comment by whalley** [comment]
Try this: https://github.com/moneymanagerex/moneymanagerex/issues/4269#issuecomment-1100756578

```
rm ~/.local/share/mime/packages/user-extension-html.xml
update-mime-database ~/.local/share/mime
```

**Comment by Heny67** [comment]
@whalley 
Thanks, that helped.
