### ISSUE TITLE
Failed to upgrade database

### ISSUE THREAD

**Issue by vbojan** [moneymanagerex/moneymanagerex#5249]
MMEX version:
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
The latest version of MMEx fails to upgrade an older version of database with the following exception:

![image](https://user-images.githubusercontent.com/2696314/198727631-a899bb9e-42d0-4e2a-8163-bc01eb69bb7f.png)

The previous version (v1.5.21) worked just fine.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
Simply attempt to open an older version of database.

Expected result:
Database would be converted to the latest version and MMEx would create several backup files, one for each upgrade step (i.e. *.mmb_upgrade_v0_2022-10-28.bak).

Actual result:
An exception is thrown after 14 upgrade steps were apparently completed (backup files 0-14 were created) and MMEx fails to successfully completes the whole upgrade process.

Additional details:
I assume this affects all OS versions.
I've noticed that if a newer version of the database is used (i.e. from the previous v1.5.21 version) it works fine, so I guess a step(s) that existed in previous version for rather older DB versions might have been removed, changed or something was overlooked :( 
Attached is a sample database: 
[Test.zip](https://github.com/moneymanagerex/moneymanagerex/files/9894434/Test.zip)

**Comment by whalley** [comment]
What was your previous version? Was it a 1.4.x release?

**Comment by vbojan** [comment]
Sorry about that. I overlooked to provide that detail.
I attached a sample DB which was created by v0.9.5.1 and it loads/upgrades with v1.5.21 without issue.

**Comment by whalley** [comment]
> I attached a sample DB which was created by v0.9.5.1 and it loads/upgrades with v1.5.21 without issue.

Having looked at that database it is missing quite a few tables that are required and the DB version is being reported as ZERO.

I don't recognise the version number (v0.9.5.1). Can you include a snapshot of the "About" box from the MMEX application that this database works with.

**Comment by tactilis** [comment]
> I don't recognise the version number (v0.9.5.1)

It's truly ancient, from November 2009:

[https://sourceforge.net/projects/moneymanagerex/files/moneymanagerex/Version%200.9.5.1/](https://sourceforge.net/projects/moneymanagerex/files/moneymanagerex/Version%200.9.5.1/)

**Comment by tactilis** [comment]
![image](https://user-images.githubusercontent.com/4060092/198873423-9dcd2356-4661-4dfd-ae0a-5a9533cc6423.png)

**Comment by whalley** [comment]
Good bit of archeology....  I also note that latest version on sourceforge is still v1.5.15.. Probably need to remove the listing.
I'll see if I can get a debug script to upgrade that DB as a one-off.

**Comment by tactilis** [comment]
The odd thing is that the OP @vbojan said...

> The previous version (v1.5.21) worked just fine.

...so I assume that they have v.1.5.21 compatible .mmb files (DB v14) but for some reason they are now attempting to open an ancient .mmb compatible only with MMEX from the v0.9.5.1 era; and that they have _never_ opened that database using a more recent version of MMEX.

@vbojan are the transaction in that ancient .mmb _really_ needed?

Does @whalley need to go to the effort of  creating a debug script to upgrade that DB as a one-off for you?

**Comment by whalley** [comment]
@vbojan I have managed to get you DB update by simply performing the following.

- Open your original DB (as used with v0.9.5.1 app) in v1.5.21 of the app - you will get a message saying the DB has been updated to v7.
- Open the newly updated database in v1.6.0 if the app - you will get a message saying DB has been updated to v15.

This process works on the test DB.

**Comment by vbojan** [comment]
Thank you @whalley for looking into this and sorry about the archeology part in all this.

The reason I'm still using the ancient version is because MMEx has simple import capabilities which are insufficient to import data from any of my financial institutions, so I developed a lot of proprietary scripts for importing transactions from various sources (HTML pages, extracting from CSV etc.) Some of these don't support any export at all, so data needs to be scrapped off of a webpage. As is, I don't see any easy way to support such import, and it certainly wouldn't be generic enough to work for most users, so I never made a related feature request.
Instead, I made a custom workaround that only works for me. I made it originally work with ancient v0.9.5.1 and I run it multiple times per week and then copy into the latest version and upgrade from there to use all other features related to stock, reports etc. The downside is all data needs to be entered into the old version :(

A lot of effort was put into all this to make it work and I have to make updates every time my financial institutions change something or a new one needs to be added. For a while versions v1.x were unstable or were crashing with my scripts. I believe this could have been specific to Windows and installed version of my C++ redistributable package. Later they got more stable but DB schema changed and I never had time to upgrade all of my scripts to work with newer versions :(
For a while I would be running a script to downgrade DB to the older version so I can still use my tools and then upgrade DB again. It's a lot of hassle though.

I opened this bug primarily because it worked in all recent versions up till v1.5.21 and I assume whatever caused it to stop working is specific to v1.6.0. According to you DB schema has changed from v7 to v15 so I assume there's a lot of changes.
I'm surprised though as v7 was released quite a while ago:
https://github.com/moneymanagerex/database/tags

I understand this would be very low priority, but is there a chance to make the upgrade work in v1.6.x so I don't have to run it twice?

**Comment by whalley** [comment]
Must admit that sounds way too fragile a setup.... 

It will likely work if you add the following table to your really old DB.

```
-- Describe REPORT_V1
CREATE TABLE IF NOT EXISTS REPORT_V1(
REPORTID integer not null primary key
, REPORTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
, GROUPNAME TEXT COLLATE NOCASE
, SQLCONTENT TEXT
, LUACONTENT TEXT
, TEMPLATECONTENT TEXT
, DESCRIPTION TEXT
);
CREATE INDEX INDEX_REPORT_NAME ON REPORT_V1(REPORTNAME);


```

**Comment by vbojan** [comment]
Thank you @whalley. That worked 👍
I totally agree about process being fragile as any step can change at any moment and break the fully automated import.
