### ISSUE TITLE
Add split button deletes the previous values

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#5250]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Click on Add Split button deletes all the split transactions in the window.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Create a new transaction
2. Choose a Payee
3. Click on the Use Split Categories button -> popup window of Split Transaction is open.
4. Choose any existing category and add the sum.
5. Click on Add Split button.

**Expected result:**
A new split row is open, all the existing transactions are on the screen.
**Actual result:**
A new split row was open, but the previous transaction (or all previous transactions) was deleted.
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
I can reproduce this using Add Split button.

However, if you always press Enter (which adds a new row) after an Amount is typed in then the previous row is not lost.

Will need to be fixed but at least there is a simple work around.

**Comment by Dandy64** [comment]
Well, you are absolutely right, this workaround I have found too. 
Another trick is simple as well - just click Add Split button in advance as many times as you need to add rows.

Anyway, I would call it a bug...

**Comment by tactilis** [comment]
> Anyway, I would call it a bug...

Of course! I wasn't suggesting otherwise

**Comment by tactilis** [comment]
Tested in 1.6.1-Beta.1 64-bit commit: d680383 (2022-10-31)

Confirmed fixed.
