### ISSUE TITLE
Increase in balance with no obvious reason.

### ISSUE THREAD

**Issue by TonySLondon** [moneymanagerex/moneymanagerex#5256]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).
Updating version resulted in over three thousand pounds being added to my bank account. Impossible to trace why. Backups took on same error. Have reported before but no responses.
This is a serious bug and does need an explantion.
Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Balance increased substantially without any coherent reason apart from an introduction of a new version.
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [] Always 
 - [x ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@TonySLondon 
Where are you reading the increased balance?  In the summary at the top of the screen, or in the Balance column of the transaction list?

IMPORTANT: Which column are you _**currently**_ sorting the transaction by?


Please click on the Date column to ensure that your are sorting the transactions by Date (primary sort) and ID (secondary sort), either ascending or descending as you prefer. Is the balance still wrong?

> Updating version resulted in over three thousand pounds being added to my bank account.
> Impossible to trace why.

Why is it impossible?

> This is a serious bug and does need an explanation.

It may not be a bug. It is possible you are misinterpreting what is being presented.

**Comment by whalley** [comment]
Closing as no response from originator for nearly two weeks.

**Comment by tactilis** [comment]
> Closing as no response from originator for nearly two weeks.

How odd. It seems that the OP also had the same problem in 1.5.18 (Again! apparently)

[https://github.com/billfrankwso2/test01/issues/9](https://github.com/billfrankwso2/test01/issues/9)

"I am running Version: 1.5.18 64-bit on Windows 11. Suddenly, for no obvious reason, the balance of my account was rocketed up by several thousand pounds; I wish! This isn't the first time this has happened. Ideally, I would start a new database, but MMEX has no way of downloading categories or payees to use for a new database. That would be helpful, like an end of year facility. I live in hope. This is, to say the least, an infuriating occurrence. Does anyone have any ideas why this would happen? The database has been ticking along happily, new releases have been taken up, and now this. Again!"
