### ISSUE TITLE
Hide/Unhide Custom Reports

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5259]
![image](https://user-images.githubusercontent.com/6836805/198879991-7cde51ad-fa5b-4c1c-b681-89dc107c3172.png)

**Comment by vomikan** [comment]
Please help, there are two questions:
1) Is this phrase written in English?
"Show/Hide the Report in the main Navigation tree control"

2) What is the best way to mark inactive reports in the GRM navigation tree? Check a box or use an oblique font? Any ideas, please.
Thank you in advance.

**Comment by Dandy64** [comment]
I suppose that an oblique font and pale font would be good. It was realized in the program already.
![image](https://user-images.githubusercontent.com/83161661/198882584-388ffa28-5c6c-4af9-9fa8-a6b17df0a6c1.png)

**Comment by whalley** [comment]
> Is this phrase written in English?
"Show/Hide the Report in the main Navigation tree control"

Don't think we need the uppercase, and I'd suggest removing 'tree control' and it sounds a bit technical, other than that sounds OK...

"Show/Hide the report in the main navigation panel"

> What is the best way to mark inactive reports in the GRM navigation tree? Check a box or use an oblique font? Any ideas, please.

A tick for those enabled would be good for me.

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/198899671-5b70e117-dc2b-4019-9d49-ee92f96a938e.png)
