### ISSUE TITLE
Not Trash

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5267]
[bernard tabuteau](https://crowdin.com/translate/moneymanagerex/470/en-ru?filter=basic&value=5#) (bernard.tabuteau)
Need more information.
It's difficult to translate these words without context : (it's) not trash [French: pas un déchet]. (Do) not trash [French: ne pas jeter à la corbeille]. Etc.

[Óvári](https://crowdin.com/translate/moneymanagerex/470/en-ru?filter=basic&value=5#) (ovari)
Which is best in Hungarian:
1. Nem szemetet
2. Szemétlen
3. Szemét mentes
4. Something else

```
 //Status
    if (statusCheckBox_->IsChecked())
    {
        wxArrayString s = Model_Checking::all_status();
        s.Add(wxTRANSLATE("All Except Reconciled"));
        s.Add(wxTRANSLATE("Not Trash"));
        int item = choiceStatus_->GetSelection();
        wxString status;
        if (0 <= item && static_cast<size_t>(item) < s.size())
            status = s[item];
        if (!status.empty())
        {
            json_writer.Key((i18n ? _("Status") : "STATUS").utf8_str());
            json_writer.String((i18n ? wxGetTranslation(status) : status).utf8_str());
        }
    }
```

**Comment by whalley** [comment]
Perhaps we use "Not Deleted"

**Comment by whalley** [comment]
Actually.. Is this status actually used now?

**Comment by btab33** [comment]
If "Not trash" = "not deleted" then we can translate in French by "non effacé" or "non supprimé"

**Comment by vomikan** [comment]
> If "Not trash" = "not deleted" then we can translate in French by "non effacé" or "non supprimé"

I replaced the term itself. Therefore, a little later you will have to translate it.

**Comment by n-stein** [comment]
> Actually.. Is this status actually used now?

Yeah, good point @whalley. This was left over from the initial code which used status to determine deletion and so the Filter dialog had these "Trash" and "Not Trash" options added to the status filter. Now that we use deleted time instead they are not included in the filter dialog and do not need to be translated.

Perhaps instead we can just include a checkbox for "Show deleted transactions" in the filter dialog?

**Comment by whalley** [comment]
> Perhaps instead we can just include a checkbox for "Show deleted transactions" in the filter dialog?

I'm not convinced we should do anything with these in the application other that allow them to be viewed/recovered from the 'Deleted Transactions' register. To all intents they are deleted and should not be available to the application to use in any form.

**Comment by tactilis** [comment]
> I'm not convinced we should do anything with these in the application other that allow them to be viewed/recovered from the 'Deleted Transactions' register. To all intents they are deleted and should not be available to the application to use in any form.

I strongly agree with this.

Effectively, the deleted transactions are already gone. @n-stein's enhancement has simply provided a last-chance means of recovering them if the deletion was a mistake.
