### ISSUE TITLE
All CC Accounts Reconciled and Balance were off by thousands of dollars. Now when I open program I get msg::"MMEX RECURRING TRANSACTION CHECK, A RECURRING TRANSACTION WILL EXCEED....

### ISSUE THREAD

**Issue by PegasusEd** [moneymanagerex/moneymanagerex#5269]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

 Installed 1.6.0 for mac after using for a short while went to reports then tried to go back to Home, would not open at first, then when it did open All CC Accounts Reconciled and Balance were off by thousands of dollars. Now when I open program I get msg::"MMEX RECURRING TRANSACTION CHECK, A RECURRING TRANSACTION WILL EXCEED YOUR ACCOUNT LIMIT DO YOU WISH TO CONTINUE, YES / NO Can anyone help???

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5256 ?

**Comment by PegasusEd** [comment]
You can find more info under discussions

**Comment by whalley** [comment]
If you go to the "All Transactions" view and sort by ID are there an odd transactions you can see at the end of the list?

**Comment by whalley** [comment]
> You can find more info under discussions

What extra info, are you referring to: https://github.com/moneymanagerex/moneymanagerex/discussions/5266

**Comment by PegasusEd** [comment]
What do you mean by odd? nothing looks different.

**Comment by whalley** [comment]
Where are you reading the increased balance? In the summary at the top of the screen, or in the Balance column of the transaction list?

Please click on the Date column to ensure that your are sorting the transactions by Date (primary sort) and ID (secondary sort), either ascending or descending as you prefer. Is the balance still wrong?

**Comment by PegasusEd** [comment]
Yes sorting by date and Bal is still way off.

**Comment by PegasusEd** [comment]
Try to go back to 1.5.20 and couldn't get it to work after helping 1.6 if I could get 1.5 to work again I will do that.

**Comment by whalley** [comment]
Which balance? That displayed in the panel header, the last transaction (when sorted by DATE/ID), or both?

**Comment by whalley** [comment]
Is the account initial balance set correctly?

> Try to go back to 1.5.20 and couldn't get it to work after helping 1.6 if I could get 1.5 to work again I will do that.

Use your database back from before you upgraded.

**Comment by PegasusEd** [comment]
I tried could not get it to work. Got rid of both applications and both downloads got a new download for 1.5.20 tried to run that work.

**Comment by whalley** [comment]
You have still failed to report what you mean by 'balance', which balance figure is wrong?

**Comment by PegasusEd** [comment]
That’s hard to determine as it goes back more than 5 yrs., but it looks correct.

**Comment by PegasusEd** [comment]
Sorry, thought I had…. the final balance.

**Comment by tactilis** [comment]
>> you have still failed to report what you mean by 'balance', which balance figure is wrong?

@PegasusEd
> the final balance.


We are trying to help you.
Please could you answer the questions and follow this advice from #5256 please?

> Where are you reading the increased balance? In the summary at the top of the screen, or in the Balance column of the transaction list?
>
> IMPORTANT: Which column are you currently sorting the transaction by?
>
> **Please click on the Date column to ensure that your are sorting the transactions by Date (primary sort) and ID (secondary sort), either ascending or descending as you prefer. Is the balance still wrong?**

**Comment by PegasusEd** [comment]
OK, Let’s see if I can be more specific…

Both the Balance in the Summary and on the Transaction Sheet are the same, thay are both wrong.
Every thing is sorted by Date.
Hope these Screen shots help…

Transaction Sheet:


Summary:


As you can see everything is in the negative by quite a lot.  In reality it should be a couple of hundred.

Also, when I open the program I still get the popup msg.: "MMEX RECURRING TRANSACTION CHECK, A RECURRING TRANSACTION WILL EXCEED YOUR ACCOUNT LIMIT DO YOU WISH TO CONTINUE, YES / NO” This displays twice.

Ed

**Comment by whalley** [comment]
Replying with images doesn't work. Can you post them on GitHub please. Also can you check what the Initial Balance and Credit values are on the account.

**Comment by PegasusEd** [comment]
Thank you for your help.  Is there a way I can get v1.5.21 back and working? I have a backup from the 29th and would fill in everything that happened after that date and use that version till a later date.
Thank you,
Ed

**Comment by whalley** [comment]
I'm confused. It seems you already have v1.5.20 working, you said....

> I tried could not get it to work. Got rid of both applications and both downloads got a new download for 1.5.20 tried to run **that work.**

Why not just download v1.5.21 now? There is no database change between these releases.

**Comment by PegasusEd** [comment]
Ok, once I down loaded 1.60.0 the previous version 1.5.21 would not open any backups, a msg. came up that said not compatible, please update.  I tried to uninstall both versions, then re-download v1.5.21 and it would not run unless I update to 1.60.0 ???

**Comment by whalley** [comment]
> Ok, once I down loaded 1.60.0 the previous **version 1.5.21 would not open any backups**, a msg. came up that said not compatible, please update.  I tried to uninstall both versions, then re-download v1.5.21 and it would not run unless I update to 1.60.0 ???

v1.5.21 will be able to open the backups that **it** created prior to the DB upgrade taking place. Are you saying that v1.5.21 will not open these older backups - I find that hard to imagine.

**Comment by PegasusEd** [comment]
This is the msg. I get: “MMEX database upgrade, MMEX database error!, MMEX database version 15 doesn’t work with this MMEX version. Please upgrade MMEX to newer version”.  Then it says “MMEX upgrade, Have MMEX support provided you a debug/patch file?”
I checked the version it shows 1.5.21 64-bit this is on a mac running OS Monterey v12.6

**Comment by whalley** [comment]
Can you upload a listing of the directory contents from the directory where your database file is.

**Comment by PegasusEd** [comment]
I’m sorry, I am not sure what or where that is?

**Comment by whalley** [comment]
> I’m sorry, I am not sure what or where that is?

The directory where the .mmb is. E.g.
![CleanShot 2022-10-31 at 00 34 51](https://user-images.githubusercontent.com/487345/198910044-701e76c9-a5c2-416d-8a22-df21736ae241.png)

**Comment by PegasusEd** [comment]
It will not open “Last opened Database”, I have to open one with “Open Existing Database"

**Comment by PegasusEd** [comment]
I cannot open anything with 1.5.21 only with1.6.0

**Comment by whalley** [comment]
> It will not open “Last opened Database”, I have to open one with “Open Existing Database"

So you know where the .mmb is, so you can supply a listing/screenshot of the directory with all the backups. Please include timestamps also.

**Comment by PegasusEd** [comment]
Is this what you want???

**Comment by tactilis** [comment]
@PegasusEd 

Please stop replying by email. Your images are not included (i.e we can't see them) if you use email.

Please go to https://github.com/moneymanagerex/moneymanagerex/issues/5269 and reply there.

You will be able to type replies, including pasting images. We will be able to see them and assist you.

Thanks

**Comment by PegasusEd** [comment]
Sorry, was not aware the limits with email.  Is this what you wanted???

<img width="680" alt="Screen Shot 2022-10-30 at 18 13 40" src="https://user-images.githubusercontent.com/117033145/199047483-7371eb98-3fa9-4b27-834f-821fd9b4a495.png">

Did this come through???  Also please note this is what I get when I try to open 1.5.21 get update..."_**NOTE: Your database will be updated once you run this version. You will then not be able to open your database with earlier versions of the software"
I have also noticed the inconsistencies are mainly with credit card accounts.

**Comment by tactilis** [comment]
> Did this come through?

Yes. 

That looks a bit of a mess 😉

Could you expand the file name column so we can see the full names please

**Comment by whalley** [comment]
> I have also noticed the inconsistencies are mainly with credit card accounts.

Mainly or solely with credit card accounts?

What is the initial balance on these accounts? Do they look correct? I'm guessing these are the accounts with set credit limits which will account for the message when the system is trying to post new recurring transactions.

We are also still awaiting the response to "Please could you answer the questions and follow this advice from https://github.com/moneymanagerex/moneymanagerex/issues/5256 please?"

**Comment by PegasusEd** [comment]
I know this Has to be as frustrating for you as it is for me.  I don't know what other questions answered and when I click on the  #5256 I see no advice, or cannot see where it is. Here is the file with the expanded file name.

<img width="1072" alt="Screen Shot 2022-10-31 at 10 08 15" src="https://user-images.githubusercontent.com/117033145/199067140-a55b84d9-693b-4f6e-a760-b8a6bcd38d51.png">

**Comment by PegasusEd** [comment]
Both the Balance in the Summary and the Balance on the Transaction Sheet are the same.
Every thing is sorted by Date.

At this point I am ready to scrap what is there and start a new database.
Thank You

**Comment by whalley** [comment]
> At this point I am ready to scrap what is there and start a new database. Thank You

So can we close this issue now?

**Comment by tactilis** [comment]
> Both the Balance in the Summary and the Balance on the Transaction Sheet are the same.
> Every thing is sorted by Date.

OK. That's good.

Do you reconcile your MMEX transactions against your bank account statements? From what date onwards do the balances not agree?

MMEX starts with the opening balance for the account, applies each transaction (a deposit, withdrawal or transfer) in turn, and calculates the new balance. AT the end of each day, the MMEX balance should match your bank statement

What makes you believe that the balances _are_ wrong?
