### ISSUE TITLE
Impossible to open mmex 1.6.0  win32 from version1.51.21 win32

### ISSUE THREAD

**Issue by Atthol** [moneymanagerex/moneymanagerex#5280]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug : When i try to launch MMEX i can see these messages

 First Message is : "Did mmex support provide you with a bug file or patch?"
![mmex](https://user-images.githubusercontent.com/117088429/199014276-53bc4a19-aa45-4ae4-a1d0-2bbd5706641c.png)

second message is :
![mmex2](https://user-images.githubusercontent.com/117088429/199016734-50ab2ef8-bba9-4cea-b3b9-ed36911c6975.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result: Mmex cannot be open and i can't go back to the previus version a see the same message

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
> Impossible to open mmex 1.6.0 win32 from version1.51.21 win32

This is expected behaviour. Once the database is upgraded it is not possible to open it again with a prior version of MMEX.

I've no idea what the issue is with the copy operation. The filename is odd. What exactly is the name of the .mmb you are opening?

**Comment by tactilis** [comment]
My guess...

It looks as though at some point in the past (in 2015) you opened one of the database **backup** files (which used to be named _database\_name_.mmb_update_YYYY-MM-DD.mmb) as though it was your current _database\_name_.mmb database file.

Then it looks as though you did it again, and maybe again.

Each time the filename got longer.

Maybe it is now too long for a Windows pathname.

More recently, the backup files are named _database\_name_.mmb_update_YYYY-MM-DD.bak to try to stop users making this mistake.

**Comment by Atthol** [comment]
I managed to go back to version 1.5.21 and recover my accounts :) but each time I change the tab I have this same message
![mmex3](https://user-images.githubusercontent.com/117088429/199037347-ece36522-0439-433f-a9f5-34592a95dc84.png)
Thanks for your help

**Comment by whalley** [comment]
Check the file permissions on your database.

**Comment by Atthol** [comment]
Thank you , problem solved
