### ISSUE TITLE
Recurring Transactions - Remove filtering

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5281]
MMEX version:
 - [x] 1.6.0

Operating System:
 - [x] Windows

# Description of the bug

The Transaction Filter does not appear to be functional on the Recurring Transactions list. Upon using the dialog to make any selections, the list becomes empty. Is this intention for the filter to work on this screen, or should it be removed?

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
Visit the Recurring Transactions screen. Click the Transaction Filter, and apply any filter (Payee, Date, Type, etc.)

Expected result:
Transactions are filtered

Actual result:
No transactions are displayed.

**Comment by whalley** [comment]
Yes, this needs looking at.

**Comment by whalley** [comment]
**QUESTION** - Do we really need a filter on the recurring transaction list? It is not as if the list will be running to 100's of transactions. Does it just add unnecessary complexity to the application?

**Comment by tactilis** [comment]
> Do we really need a filter on the recurring transaction list? 

It wouldn't worry me if there was no filter. If I really needed to find a particular transaction with, for example, a particular Payee, I'd just sort by that column. Same goes for the other columns.

**Comment by vomikan** [comment]
> It wouldn't worry me if there was no filter. If I really needed to find a particular transaction with, for example, a particular Payee, I'd just sort by that column. Same goes for the other columns.

I think so, too.

**Comment by rmelillo76** [comment]
I agree that a filter is not needed either. Which is partly why I asked if the intention was for it to work or should it be removed. I don't see much value beyond sorting the column headers which works perfectly fine. Thanks!

**Comment by whalley** [comment]
OK, I'll use this issue to tidy up the code to remove the (non-working) support for this. Always good to simplify the code....

**Comment by n-stein** [comment]
@whalley 
Just delete this line
https://github.com/moneymanagerex/moneymanagerex/blob/d0b1b28e715e20c3497d3e2a4a256708fcbdc01d/src/filtertransdialog.cpp#L1298

**Comment by whalley** [comment]
Yep, good spot. That will get it working-ish. But there are other issues I think I spotted when looking at it:
- It currently uses the full filter dialog with different filters settings that mimics the transaction filter rather than the simple checking panel filter (not sure if this good or bad - it is inconsistent)
- Logic for disabling via cancel button is not logical
- Does not check for match on 'color'
- Does not check for custom field matches

We could tidy this or just remove and make future maintenance easier.

**Comment by tactilis** [comment]
I really can't see the point of it.

I'd be inclined to remove the button in the next release and see whether there are any howls of protest.

If there are none, then we could remove the underlying code in the release after that.

If there are a few complaints, we could investigate exactly what they are filtering on and why it's useful to them. Then decide what to do

**Comment by whalley** [comment]
> I'd be inclined to remove the button in the next release and see whether there are any howls of protest.

Good way to test the water.... I like it.
