### ISSUE TITLE
Translator comments 

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5289]
@whalley I didn't notice it before, but there were a lot of questions from translators. I have answered some of them, but some of them are not clear to me. Would it be difficult to walk through them?

https://crowdin.com/translate/moneymanagerex/470/en-ru?filter=basic&value=7

![image](https://user-images.githubusercontent.com/6836805/199216503-c06f0b12-45fd-41ad-b3e8-71590d6e97cc.png)

**Comment by whalley** [comment]
Sure, will pick these up.

**Comment by vomikan** [comment]
It seems that we need to clean up here.

![image](https://user-images.githubusercontent.com/6836805/199231319-cfc2b472-4707-4b70-9a98-c4ee4ec81efd.png)

![image](https://user-images.githubusercontent.com/6836805/199231346-a449ef3b-4320-433e-8d95-7577bc2c2948.png)

**Comment by whalley** [comment]
For consistency with the current list I suspect that
"Advanced Filter" should say "**View based on Transaction Filter**"
the other terminology looks fine.

**Comment by vomikan** [comment]
"View based on Transaction Filter" is too width.
I would just replace "Advanced filter" with "Transaction filter".

**Comment by whalley** [comment]
> I would just replace "Advanced filter" with "Transaction filter".

Hardly any longer than "View Current Financial Year" or "View Since Statement Date" !

**Comment by vomikan** [comment]
And what if you remove the word view for the button, and use it in the menu?

![image](https://user-images.githubusercontent.com/6836805/199262338-3243e6f3-eafb-4fcb-ac00-d466e9b61683.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/199264372-0275d40a-359b-44f7-ac54-409581625443.png)
