### ISSUE TITLE
New transaction - Incorrect minimum balance check

### ISSUE THREAD

**Issue by intcooper** [moneymanagerex/moneymanagerex#5290]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

A transfer created from the target account page leads to an incorrect check for minimum balance (and credit limit).
In fact, the balance used for the calculation is the target account one.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
- Make sure to define a minimum balance for an account (account1)
- Navigate to a different account page (account2)
- Create a new transaction (or duplicate an existing one) 
- Change the transaction type to transfer
- Change the source account to account1
- Change the target account to account2
- Apply

Expected result:
The minimum balance check is performed against the source account balance.

Actual result:
The minimum balance check is performed against the target account balance.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by intcooper** [comment]
I opened pull request #5291 with a fix for the issue.

**Comment by intcooper** [comment]
@whalley should I wait until I verify with the 1.6.1 release to close the issue?
What is the general approach to bugs and features?

**Comment by tactilis** [comment]
> should I wait until I verify with the 1.6.1 release to close the issue?
What is the general approach to bugs and features?

My approach is that I independently test the first Beta build that includes the fix and, if all is OK, I comment on the Issue along the lines of:

> Tested 1.6.1-Beta.1 64-bit commit: dd56bdd (2022-11-01)     _{info copied from the About dialog}_
>
> Confirmed Fixed

If I raised the issue, I then close it.

If someone else raised the issue, I wait for them, @whalley, or @vomikan to close it.
