### ISSUE TITLE
Error when I trying to open Database on Version 16 of the Software

### ISSUE THREAD

**Issue by Neapel1961** [moneymanagerex/moneymanagerex#5297]
> Hello!
I tryed to update to the new Version (16) and I always got an error when I opend the old Database. I thougt that the old DB would automaticly updatet to the new version (see the picture as attechment)

Josef

<hr>Version: 1.5.21 64-bit<br>
 • Build: Sep 21 2022 09:27:42<br>

 • db 7 •  (aes128cbc)<br>
 • git cb708cc (2022-09-21)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 •  German (Austria) (windows-1252)<br>
 • 2736x1824 32bit 96x96ppi
![Error](https://user-images.githubusercontent.com/117263227/199437502-15779c41-fc60-49e3-bd69-d281cd5d7ac9.jpg)

**Comment by whalley** [comment]
Can you please clarify exactly what you are attempting, as it is unclear from your post.

You mention failures trying to open v16 of the database, yet you say you are using MMEXv1.5.21 (which uses v7 of the database), and the error says it is failing to upgrade to v15.

For reference:
- MMEXv1.5.21 uses DBv7
- MMEXv1.6.0 uses DBv15
- MMEXv1.6.1.Beta.1 uses DBv16

You should be able to open an older database version using a later version of MMEX, e.g. MMEXv1.6.1Beta.1 can open database versions v7, v15, and v16.

**Comment by tactilis** [comment]
@whalley Are there any problems upgrading encrypted databases?  Do you need to decrypt before the upgrade?

Might this be the problem here?

**Comment by whalley** [comment]
> @whalley Are there any problems upgrading encrypted databases? Do you need to decrypt before the upgrade?

Nope. It asks for you to enter the passphrase, unencrypts the DB, then does the upgrade check and upgrades as neccessary.

**Comment by tactilis** [comment]
@Neapel1961
Are you still having this problem?

If so, please could you reply to @whalley's request for information here https://github.com/moneymanagerex/moneymanagerex/issues/5297#issuecomment-1299834468

**Comment by Neapel1961** [comment]
Yes, I tried everthing, also with multible Computers

mfg

Josef

________________________________
Von: Martin ***@***.***>
Gesendet: Donnerstag, 17. November 2022 10:40
An: moneymanagerex/moneymanagerex ***@***.***>
Cc: Neapel1961 ***@***.***>; Mention ***@***.***>
Betreff: Re: [moneymanagerex/moneymanagerex] Error when I trying to open Database on Version 16 of the Software (Issue #5297)


@Neapel1961<https://github.com/Neapel1961>
Are you still having this problem?

If so, please could you reply to @whalley<https://github.com/whalley>'s request for information here #5297 (comment)<https://github.com/moneymanagerex/moneymanagerex/issues/5297#issuecomment-1299834468>

**Comment by n-stein** [comment]
The error message is the same as in #5326, so could be another case of corrupted index.

Try the same patch file from that issue
<a href="https://github.com/moneymanagerex/moneymanagerex/files/10023306/f-i-l-z_DB_v15_upgrade_fix.zip">here</a>.

**Comment by n-stein** [comment]
@Neapel1961 

Any update on this? Did the patch file resolve your issue?
