### ISSUE TITLE
User confusion regarding Deleted Transactions node in Navigation tree 

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5298]
**Problem to be solved**

Following the implementation of https://github.com/moneymanagerex/moneymanagerex/issues/2963, I anticipate that there will be confusion for some users, which leads to a flurry of forum questions asking "Where can I see my deleted transactions".

Consider:

1. The user deletes a transaction for the first time after upgrading to 1.6.1:
 
![image](https://user-images.githubusercontent.com/4060092/199443333-5762761f-5508-45fd-8ff6-810022d27794.png)

 
2. They click Yes and are presented with:
 
![image](https://user-images.githubusercontent.com/4060092/199443688-5b69b60e-4605-4865-9108-2798d48d2607.png)
 
3. They ask "Where did my transaction go?" - they have forgotten the exact wording of the delete confirmation message.
It's not at all obvious that they now need to go to the View menu to turn on the display of the Deleted Transactions:
 
![image](https://user-images.githubusercontent.com/4060092/199445477-00ae4e0a-24ae-4698-8587-436aa6304981.png)

We know from other forum questions that many users do not systematically explore all the menus or the Options in MMEX, so will not easily find the View | Display Deleted Transactions menu item.

**Proposed solution**

I propose possible 2 solutions:

1. Always show the Deleted Transactions entry in the Navigation tree and do not have a View | Display Deleted Transactions menu item.

2. Set View | Display Deleted Transactions **on** for all new MMEX installations/upgrades but don't override the setting in the future if the user turns it off.

I favour the simplicity of solution 1 because:
- I cannot imagine that anyone is going to get upset by the presence of a Deleted Transactions node in the Navigation tree.
- The Deleted Transactions node is a reminder to users that they can easily recover deleted transactions.
- Too many View menu items and Options leads to 'decision fatigue for users. It is often simpler to implement what we believe will satisfy 99% of users _and then_, if there are any vocal requests to hide the Deleted Transactions node, we consider whether to implement it.

**Comment by whalley** [comment]
> Always show the Deleted Transactions entry in the Navigation tree and do not have a View | Display Deleted Transactions menu item.

+1 for this (from the two options)

But, can I throw another option out there....

99% of the time people are not interested in the deleted transactions, much like the 'Trash' on your computer. Because of this I would question whether we should use space in the Navigation tree for this. On your PC you don't typically have the 'Trash' as part of your file browser, but it's there to access if needed.

Perhaps we just allow access via Tools / Deleted Transactions and add it to the toolbar ?

**Comment by tactilis** [comment]
> 99% of the time people are not interested in the deleted transactions, much like the 'Trash' on your computer.

Agreed.

> Because of this I would question whether we should use space in the Navigation tree for this.

For me, it's a matter of discoverability. It's only one node and, like the various Account nodes, it opens a 'view' in the right hand transactions panel.

> But, can I throw another option out there....
> Perhaps we just allow access via Tools / Deleted Transactions and add it to the toolbar ?

My argument against this suggestion is that, _because_ the Deleted Transactions list is a view in right hand panel, it should appear in the Navigation tree _and_ it should be highlighted whenever the Deleted Transactions list is displayed.
 
Consider this similar use of Tools | Transaction Report Filter or the corresponding toolbar button...

The video shows:
1. Acc 1 highlighted and it's transactions displayed.
2. Clicking Transaction Report Filter on the toolbar.
3. Display of the Transaction Report - but Acc 1 is still highlighted
4. Repeated attempts to switch back to Acc 1 by single clicking in the Nav tree - the clicks have no effect.
5. Finally I double click on Acc 1, which does change the view.
 
https://user-images.githubusercontent.com/4060092/199475114-0102734f-e1e7-4d5e-825c-f4d8cac9d832.mp4
 
Arguably, this is a bug and we should fix it by refreshing the Nav tree with Transaction Report highlighted when OK is pressed on the Transaction Report Filter dialog.  I can raise a new issue for this if you wish.

But now apply the same logic to your Tools | Deleted Transactions / toolbar button suggestion. If you don't have a node in the Nav tree, then you will have no option but to leave the tree showing Acc 1 (in my example). This is wrong and confusing behaviour IMO when the right hand panel shows deleted transactions.

**Comment by vomikan** [comment]
We can make the following scenario.

In the global settings, add a choice: delete to the trash or permanently.
In the navigation tree, display the basket if it is not empty. Or display it always. We can make 2 icons - an empty basket and a filled one.

So it will be clearer for everyone.

**Comment by vomikan** [comment]
A simple useful change is to make the trash display by default.
![image](https://user-images.githubusercontent.com/6836805/199487457-27dbcac7-68f5-49f3-b0f3-3d7d72615b2e.png)

**Comment by tactilis** [comment]
> In the global settings, add a choice: delete to the trash or permanently.

Why add a Delete to trash/Delete permanently option? It's more complexity and _another_ decision that the user has to think about?

The 'trash' (Deleted Transactions) feature _just works_. There is no downside to it.
No decisions have to be made. Deleted transactions are automatically purged after a period of time.

It's easy to keep adding options on the basis that "It gives users a choice" but there is a cost (maintainability / cluttered UI user decision fatigue) to every new option that is added.

**Comment by whalley** [comment]
> > In the global settings, add a choice: delete to the trash or permanently.
> 
> Why add a Delete to trash/Delete permanently option? It's more complexity and _another_ decision that the user has to think about?

It's already there... You set the retention period to ZERO,

![CleanShot 2022-11-02 at 13 04 25@2x](https://user-images.githubusercontent.com/487345/199496878-3a13860f-e934-4d94-b0e6-437dc3aaa22a.png)

**Comment by whalley** [comment]
> Arguably, this is a bug and we should fix it by refreshing the Nav tree with Transaction Report highlighted when OK is pressed on the Transaction Report Filter dialog. I can raise a new issue for this if you wish.

Yes, please do.

**Comment by Dandy64** [comment]
The simplest way is just to add a couple of sentences to the Help.

I have been using the MMX since 2019 and I have never needed to see the deleted transactions yet. Anyway, if I need it for any weird reason, I would obviously look at the View menu.

But since **tactilis** thinks this can confuse users, I would prefer the 2nd option.
_Set View | Display Deleted Transactions on for all new MMEX installations/upgrades but don't override the setting in the future if the user turns it off._

**Comment by tactilis** [comment]
> I have been using the MMX since 2019 and **I have never needed to see the deleted transactions yet.** 

The capability has not been released yet.

**Comment by Dandy64** [comment]
> The capability has not been released yet.

It doesn't matter. I have never needed this capability.

**Comment by rmelillo76** [comment]
How about something like this - we have an icon that displays on the transaction grid itself when there are deleted transactions that can be restored?
![image](https://user-images.githubusercontent.com/95182117/199535662-91f4a200-42fe-4a37-8274-2ba4029bbe33.png)

And as a bonus (if not overly complex), indicate how many there are. We could even hide the icon when there are none.
![image](https://user-images.githubusercontent.com/95182117/199536531-43c31c0a-6495-4b37-9441-32c9e01d0f54.png)

I think this takes care of the discoverability issue, as well as tidying up the menu and navigation panel. Just an idea, let me know what you think.

**Comment by tactilis** [comment]
@rmelillo76
>  Just an idea, let me know what you think.

I think it's an interesting idea.

But it breaks the underlying mental model that the item that is currently highlighted in the Navigation tree determines the view that is shown in the right hand panel.

The Deleted Transactions view does not 'belong' a specific account. It is a global view, independent of the account that is selected in the tree.

However, I do like the idea that the Deleted Transactions icon could automatically appear (in the Navigation tree) when there are any deleted transactions and be removed when all deleted transactions have been purged (or restored).

This would also cater for @Dandy64's wish never to use or see Deleted Transactions (or the icon); they just set the 'Days to retain deleted transactions' Option to 0, which causes transactions to be permanently deleted straight away. The Nav tree icon will then never appear.

**Comment by rmelillo76** [comment]
> But it breaks the underlying mental model that the item that is currently highlighted in the Navigation tree determines the view that is shown in the right hand panel.

> The Deleted Transactions view does not 'belong' a specific account. It is a global view, independent of the account that is selected in the tree.

I agree with you @tactilis. I hadn't fully thought about what would be displayed to the user immediately after clicking the button. My initial thought was that the button and view would be scoped to items that had been deleted from the account currently selected (or all if on the Full Transactions panel). The Deleted transactions panel would then display for that account, but I can see where this now becomes overly complicated and not consistent with the original goals.

**Comment by n-stein** [comment]
> However, I do like the idea that the Deleted Transactions icon could automatically appear (in the Navigation tree) when there are any deleted transactions and be removed when all deleted transactions have been purged (or restored).

I like this and it is very simple to implement.

How about some combination of the two? Set the default to "Display Deleted Transactions". When there are deleted transactions it will display in the Nav Panel, otherwise will be hidden. If the user manually turns off the display via the "View" menu, it won't show up in the Nav Panel even if there are deleted transactions. I would personally use it like this to avoid Nav Panel clutter while still using the deleted transactions feature "just in case".

**Comment by vomikan** [comment]
> How about some combination of the two? Set the default to "Display Deleted Transactions". When there are deleted transactions it will display in the Nav Panel, otherwise will be hidden. If the user manually turns off the display via the "View" menu, it won't show up in the Nav Panel even if there are deleted transactions. I would personally use it like this to avoid Nav Panel clutter while still using the deleted transactions feature "just in case".

That's exactly what I would do.

**Comment by n-stein** [comment]
PR #5300

**Comment by vomikan** [comment]
@n-stein one litle thing... It is necessary to show the home page after deleting all deleted transactions.
Thank you in advance.

![image](https://user-images.githubusercontent.com/6836805/199582216-16ac090c-2737-4bdf-ba65-b6c16fb4d739.png)

**Comment by n-stein** [comment]
PR #5301 will send you back to home if you restore or purge all the deleted items.
