### ISSUE TITLE
Transaction Report node in Navigation tree is not highlighted when corresponding report is displayed

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5299]
MMEX version:
 - [x] 1.6.1 Beta

Originally discussed here: https://github.com/moneymanagerex/moneymanagerex/issues/5298#issuecomment-1300130758

The Transaction Report node in the Navigation tree does not become highlighted when the Transaction Report is displayed if Tools | Transaction Report Filter or the toolbar button was used to run the report.

The video shows:

1. Acc 1 highlighted and its transactions displayed.
2. Clicking Transaction Report Filter on the toolbar.
3. Display of the Transaction Report - but Acc 1 is still highlighted
4. Repeated attempts to switch back to Acc 1 by single clicking in the Nav tree - the clicks have no effect.
5. Finally I double click on Acc 1, which does change the view.
 
https://user-images.githubusercontent.com/4060092/199523419-3096b8b1-4601-4b14-bc8e-aec5cf923f9c.mp4
 
**Expected result**

1. When the Transaction Report is displayed, the Transaction Report node in the Navigation tree should also be highlighted.

2. Single clicking on Acc 1 in the example above should switch the view back to that account. Note that this bug may be resolved by virtue of fixing the Transaction Report node highlighting.

**Comment by n-stein** [comment]
Fixed in PR #5319

**Comment by tactilis** [comment]
Tested 1.6.1-Beta.1 64-bit commit: e85c7ba (2022-11-08)

Confirmed fixed.
