### ISSUE TITLE
Add transaction type to categories

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#530]
This is originally a [user request in Android app](https://github.com/moneymanagerex/android-money-manager-ex/issues/409) but it refers to the application in general.

>Can we add a column transaction type to table category? So that we can filter cat by transcode. Currently, when we create new transaction, we choose Withdrawal but can choose category Income, it's not make sense. Cheer

The request makes sense in terms of grouping. It should not, however, prevent entering a Withdrawal for an Income category as there would be no way to create "offset" transactions in that case.

**Comment by vomikan** [comment]
I don't remember for what exactly this request was.... May be for QIF
import... I've created function to detect if category withdrawal or deposit
by total summary of the category.
I think it useless request.

Regards,
Nikolay
16 июля 2015 г. 11:36 пользователь "Alen Siljak" <notifications@github.com>
написал:
