### ISSUE TITLE
Moneymanager ex schedule option

### ISSUE THREAD

**Issue by LeeS838** [moneymanagerex/moneymanagerex#5308]
Is it possible to create an option to schedule a deposit on the particular week/day of a month. ie problem arises for people receiving Social Security deposit on the 2nd and 4th Wednesday of every month. I don't see any option in the current date scheduling options that would cover this. Currently schedule monthly but then have to modify every month.
Thank You for this wonderful piece of software and all of the people that work on it.

**Comment by whalley** [comment]
Not currently possible. Option to have better schedule options has been asked for before, e.g. https://github.com/moneymanagerex/moneymanagerex/issues/2342 which also asks for Nth instance of day being a trigger.
Will consider this as part of that issue

**Comment by LeeS838** [comment]
I do appreciate the quick reply. This is an excellent app. It is easy
enough to work around.
Thank You

*Leighton (Lee) Stoddard*
***@***.****
*585-227-4452*
