### ISSUE TITLE
Bring back the Net Worth report

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#531]
A request from a user via Google Play:

>bring back the Nett Worth report in the windows version. I used to print this out with other reports at end of month.

**Comment by siena123** [comment]
I think the report that you are referring to is the Account Summary Report which was moved to General Reports (https://github.com/moneymanagerex/general-reports). It can be added back using the General Report Manager.

**Comment by guanlisheng** [comment]
@MisterY thought?

**Comment by MisterY** [comment]
I will try to find the user who requested this via comment on Play Store and contact them.

**Comment by MisterY** [comment]
Unfortunately, I can to get any contact data from a Play Store review. Here is the original review, though, and that is the only piece of information we have atm:
>Great simple all you need Money Manager Keep up the updates. Great to see a developer who responds. Would be great if the android version could load the encrypted .emb files also bring back the Nett Worth report in the windows version. I used to print this out with other reports at end of month. A great easy to use all you need app that syncs with windows version. With these modifications it will be a full 5 stars
