### ISSUE TITLE
Home Page Assets Widget

### ISSUE THREAD

**Issue by RTMWEST** [moneymanagerex/moneymanagerex#5310]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

A minor niggle, but would it be possible to store the Assets Widget's minimise / maximise setting just like the other widgets on the Home Page

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Open Home Page

Expected result:
When opening the Home Page the Assets Widget should display as previous setting, maximised or minimised.

Actual result:
Assets Widget is always maximised.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
This is a bug, the code is there but it is using the wrong label for the table.

**Comment by RTMWEST** [comment]
Thanks Mark – Glad it’s a simple fix.
