### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by anilmalleedi** [moneymanagerex/moneymanagerex#5315]
# Account Linking

Currently we are uploading the account statements by downloading in csv , ms money format . Instead of that If we are able to link the actual account and able to fetch the data for that account . So that when ever user refreshes the latest transaction data should be download from the respective bank account. 

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by tactilis** [comment]
Duplicate request.

Please see https://github.com/moneymanagerex/moneymanagerex/issues/3672
