### ISSUE TITLE
Notes disappear when clicking "Cancel" in Split Transactions window

### ISSUE THREAD

**Issue by Fabi54321** [moneymanagerex/moneymanagerex#5320]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Write something in transaction notes
2. open split transactions window
3. click "cancel"
4. text is gone

![2022-11-09_23-04-06 (1)](https://user-images.githubusercontent.com/13711459/200953890-79a9e106-0f4f-4370-8246-f6f2f7277d53.gif)

Expected result: Notes should not be deleted/modified when clicking "Cancel" in split window.

Actual result: Notes deleted after leaving split window.

# Additional information
Might be related to implementation of #910

**Comment by tactilis** [comment]
Bug confirmed.

It's still present in 1.6.1 Beta.

**Comment by tactilis** [comment]
> Might also be related to https://github.com/moneymanagerex/moneymanagerex/issues/5250 ...

No, that bug had a different cause and is now fixed ready for 1.6.1
