### ISSUE TITLE
MMEX Database Upgrade to version 15 failed!

### ISSUE THREAD

**Issue by f-i-l-z** [moneymanagerex/moneymanagerex#5326]
Upgraded from version 1.5.21 (win 64) to the latest version, 1.6.0 (Win 64) and on opening the existing database I get the following Error Message.

MMEX Database Upgrade to version 15 failed!
Please restore DB from autocreated pre-upgrade backup and retry or contact MMEX support
databse disk image is malformed[11]: database disk image is malformed.

![image](https://user-images.githubusercontent.com/77737688/201662053-7d843c27-98fe-4db3-8a8f-9b829674e304.png)

Never had a problem updating to new versions previously.  Going back to the previous version I then cannot load the database as it says:

MMEX database error!
MMEX database version 14 doesn't work with this MMEX version.  please upgrade to newer version.

I have restored by loading a backup copy of the database in the previous version but would like to update so please advise on what my next steps should be.

Some info from the about tab:

![image](https://user-images.githubusercontent.com/77737688/201663950-8a9896e4-dc9d-457f-8175-44c3631f82fd.png)

**Comment by whalley** [comment]
The error 11 (SQLITE_CORRUPT)  indicates that the database file has been corrupted in some way. The fact that it left the DB at v14 would indicate the original DB was accessible up to that point. What happens if you open the v14 DB format using v1.6.0 do you get the same error when it attempts the upgrade again?

What medium is the database on? HDD, SDD, USB, Network/Cloud. If USB or Network/Cloud could you try copying to HDD/SDD prior to doing the upgrade.

**Comment by f-i-l-z** [comment]
OK, I installed the portable version 1.6.0 alongside the 1.5.21 version and took a copy of the database file that works with 1.5.21.

When I try to open that file in 1.6.0 I get the error message above.  

![image](https://user-images.githubusercontent.com/77737688/201910252-b471cbbe-39bd-45c6-8c7b-605874c3b378.png)

If I then try and open that same file in the 1.5.21 version I get the following error message.

![image](https://user-images.githubusercontent.com/77737688/201907744-2391dc77-0d12-4bf8-a51f-8ba56c213695.png)

If I take that same file and try and open again in 1.6.0 I get this:

![image](https://user-images.githubusercontent.com/77737688/201910228-c9040a9a-5564-414d-bc0a-3ce60814f984.png)

If I then say no to the message saying do I have a debug file from MMEX I am then presented with the following Error Message:

![image](https://user-images.githubusercontent.com/77737688/201910492-f0125fb3-d6a7-427e-a5d2-cd4b176aaa96.png)

The applications and file is sitting on a standard HDD.


So am I reading this right, it tries to update the database to version 15 but fails for some reason but it has managed to update it to version 14 that then no longer works with 1.5.21?  1.6.0 is then unable to upgrade the version 14 database to 15?

Thanks

**Comment by whalley** [comment]
Best way to look at this is if you can send the DB to support@moneymanagerex.org. If you are uncomfortable with that then feel free to take a copy and remove any sensitive information - just make sure it still fails the upgrade when you do that.

**Comment by tactilis** [comment]
@f-i-l-z
> So am I reading this right, it tries to update the database to version 15 but fails for some reason but it has managed to update it to version 14 that then no longer works with 1.5.21?

Correct. 1.5.21 uses database version 7. The upgrade process creates a series of backup files from v7 through to v14.

Take a copy and rename the v7 backup (which is the same as your original .mmb file) if you need to revert to 1.5.21 temporarily while the problem is being resolved.

**Comment by f-i-l-z** [comment]
Thank you, I have a working copy for 1.5.21 so all is fine for the time being.  Would be nice to understand why the update is failing though so that I can upgrade in the future.

**Comment by tactilis** [comment]
> Would be nice to understand why the update is failing though so that I can upgrade in the future.

The only way to resolve this is to follow @whalley's advice here https://github.com/moneymanagerex/moneymanagerex/issues/5326#issuecomment-1315219297

**Comment by f-i-l-z** [comment]
> > Would be nice to understand why the update is failing though so that I can upgrade in the future.
> 
> The only way to resolve this is to follow @whalley's advice here [#5326 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/5326#issuecomment-1315219297) and send a copy of your 1.5.21 compatible .mmb so that he can debug the upgrade failure.

Thanks, I had missed that post - have just sent in a heavily sanitised version, but it still fails to load in 1.6.0.

**Comment by whalley** [comment]
I think the `order by TRANSDATE asc` is causing the error when the select query returns NULL.

I think we need to change the account INITIALDATE update logic from...

```
alter table ACCOUNTLIST_V1 add column INITIALDATE text;
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID )
            order by TRANSDATE asc limit 1 );
update ACCOUNTLIST_V1 SET INITIALDATE = (select PURCHASEDATE from STOCK_V1 where
            (ACCOUNTLIST_V1.ACCOUNTID = STOCK_V1.HELDAT)
            order by PURCHASEDATE asc limit 1 )  where INITIALDATE is null;
update ACCOUNTLIST_V1 set INITIALDATE = date() where INITIALDATE is null;
```

to...

```
alter table ACCOUNTLIST_V1 add column INITIALDATE text;
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID )
            order by TRANSDATE asc limit 1 )
    where exists (select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID ));
update ACCOUNTLIST_V1 SET INITIALDATE = (select PURCHASEDATE from STOCK_V1 where
            (ACCOUNTLIST_V1.ACCOUNTID = STOCK_V1.HELDAT)
            order by PURCHASEDATE asc limit 1 ) 
    where exists (select PURCHASEDATE from STOCK_V1 where
            (ACCOUNTLIST_V1.ACCOUNTID = STOCK_V1.HELDAT)) and INITIALDATE is null;
update ACCOUNTLIST_V1 set INITIALDATE = date() where INITIALDATE is null;
```

Can I ask that you add a **DUMMY** transaction record for any accounts that you currently have with no transactions, then try the upgrade. You can then delete the **DUMMY** transactions.

Must admit I'm a bit perplexed by this as I'm sure I had an account with no transactions in my DB prior to upgrade and it's odd it has not been reported before.

**Comment by tactilis** [comment]
@whalley, does your proposed change result in a null INITIALDATE for the account if contains no transactions at the time of DB upgrade? If so, does that matter?

Or is the logic that _if_ a transaction is later added to such an account, then the INITIALDATE will be set?

And if, subsequently, a transaction with an even earlier date is added, will INITIALDATE be updated to that earlier date?

And does this logic work for imported (CSV/XML/QIF) transactions too?

**Comment by whalley** [comment]
> does your proposed change result in a null INITIALDATE for the account if contains no transactions at the time of DB upgrade?

No... The original logic included this scenario, see the last line
`update ACCOUNTLIST_V1 set INITIALDATE = date() where INITIALDATE is null;`

> And does this logic work for imported (CSV/XML/QIF) transactions too?

For CSV and XML imports the account data needs to already exist in MMEX and it will not be possible to import transactions before the start date

For QIF it is possible to create the accounts from the QIF data if they don't exist. However as this does not hold the opening date the account it will be defaulted to TODAY. No prior dated transactions will then be imported. The user must therefore change the start date to the correct date and re-import - so it is a 2-stage process. I guess we could look at an enhancement to set the opening date based on earliest transaction but it gets complicated by the fact that users may have subsequent imports from banks....

**Comment by tactilis** [comment]
> No... The original logic included this scenario, see the last line
> `update ACCOUNTLIST_V1 set INITIALDATE = date() where INITIALDATE is null;`

Doh! I looked but somehow _(how??)_ I overlooked that. 

<br>

> For QIF... The user must therefore change the start date to the correct date and re-import - so it is a 2-stage process.

I think that's OK, provided there is a clear warning displayed that some transactions are dated earlier than the account start date so have not been imported. It's not going to happen very often.

Same issue will arise for OFX if we ever support it. A fair number of banks are providing OFX instead of QIF.

**Comment by whalley** [comment]
@n-stein My SQL is a bit rusty so maybe you can help.... I'm not sure why 
```
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID )
            order by TRANSDATE asc limit 1 );
```

would fail if no CHECKINGACCOUNT_V1 entries existed for ACCOUNTID. I had assumed it would return NULL, I tested it by deleting entries in my DB then running the SQL which seemed to work, but it does not work on the DB that @f-i-l-z has supplied. 

Instead

```
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID )
            order by TRANSDATE asc limit 1 )
    where exists (select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID ));
```

OR

```
update ACCOUNTLIST_V1 SET INITIALDATE = ( select TRANSDATE from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID )
            order by TRANSDATE IS NOT NULL ASC );
```

works! 

Any views?

**Comment by n-stein** [comment]
> For QIF it is possible to create the accounts from the QIF data if they don't exist. However as this does not hold the opening date the account it will be defaulted to TODAY. No prior dated transactions will then be imported

Oops, I didn't read this before I created #5334. I came across this issue when debugging QIF import for #1477.

> The user must therefore change the start date to the correct date and re-import - so it is a 2-stage process

They must also delete any transactions that did import, otherwise the second import will duplicate them.


> Any views?

I don't see anything wrong with that code, and I'm unable to reproduce a crash with an account that has no transactions either executing that SQL directly or allowing MMEX to migrate from v7 to v15. Must be something else in that DB which is causing the crash.

Surely the simplest thing is to just use the "min" function, no?

```
update ACCOUNTLIST_V1 SET INITIALDATE = ( select min(TRANSDATE) from CHECKINGACCOUNT_V1 where 
            (ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.ACCOUNTID OR
            ACCOUNTLIST_V1.ACCOUNTID = CHECKINGACCOUNT_V1.TOACCOUNTID ));
```

**Comment by whalley** [comment]
> I don't see anything wrong with that code, and I'm unable to reproduce a crash with an account that has no transactions either executing that SQL directly or allowing MMEX to migrate from v7 to v15. Must be something else in that DB which is causing the crash.

That's what I thought too, but can't see anything else in the DB that would cause the error (yes the SQL could be optimised!). If you send me your e-mail address to mark@ipx.co.uk I'll share the redacted DB.

**Comment by f-i-l-z** [comment]
>

**Comment by f-i-l-z** [comment]
> 
> Can I ask that you add a **DUMMY** transaction record for any accounts that you currently have with no transactions, then try the upgrade. You can then delete the **DUMMY** transactions.
> 

Wasn't sure if this comment was aimed at me but as far as I can tell there are no accounts with no transactions.  Been through the original database and every account has at least one entry.

**Comment by n-stein** [comment]
I've got you @f-i-l-z. Unzip & use this patch file when prompted:

[f-i-l-z_DB_v15_upgrade_fix.zip](https://github.com/moneymanagerex/moneymanagerex/files/10023306/f-i-l-z_DB_v15_upgrade_fix.zip)

**Comment by f-i-l-z** [comment]
> I've got you @f-i-l-z. Unzip & use this patch file when prompted:
> 
> [f-i-l-z_DB_v15_upgrade_fix.zip](https://github.com/moneymanagerex/moneymanagerex/files/10023306/f-i-l-z_DB_v15_upgrade_fix.zip)

Perfect, can report that it worked and I have copies now for both 1.5.21 and 1.6.0.  Thank you for your quick help.

**Comment by whalley** [comment]
> I've got you @f-i-l-z. Unzip & use this patch file when prompted:
> 
> [f-i-l-z_DB_v15_upgrade_fix.zip](https://github.com/moneymanagerex/moneymanagerex/files/10023306/f-i-l-z_DB_v15_upgrade_fix.zip)

So was it a corrupt index then? Good spot.

**Comment by n-stein** [comment]
Yup. Actual error was "wrong # of entries in index IDX_CHECKINGACCOUNT_TRANSDATE", so rebuilding the index was an easy fix.

**Comment by tactilis** [comment]
> Actual error was "wrong # of entries in index IDX_CHECKINGACCOUNT_TRANSDATE", so rebuilding the index was an easy fix.

Any thoughts on how this may have arisen?

**Comment by n-stein** [comment]
> Any thoughts on how this may have arisen?

Could be something like an app crash in the middle of a large insert/delete operation.

Perhaps we want to consider always calling REINDEX on any table we are about to touch in an upgrade script if we will be using an indexed column?
