### ISSUE TITLE
bad string (translations issue)

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5328]
D:\GitHub\moneymanagerex\src\reports\cashflow.cpp
```    const wxString& headingStr = wxString::Format("%s (%i %s)", getReportTitle(), getForwardMonths(), _("months"));```

https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#798138

[Óvári](https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#) (ovari)
Is this string used with a number before?

For example
4 months

In Hungarian, if there is a number before then months is always written in the singular, i.e.
4 month
not
4 months

Should this string be improved to include the variable? For example
%i months
?

That may make it easier to translate.

If it is a heading for the months of the year, then the Hungarian translation is the plural.

What do you think?

Thank you

**Comment by whalley** [comment]
I'm always a bit wary putting format specifiers in the strings to be translated as it can result in program crashes if they are omitted. I prefer the translation strings to be separate. In this case the use is for example: 4 months.

**Comment by ovari** [comment]
Thank you @whalley for sharing your thoughts.

> I'm always a bit wary putting format specifiers in the strings to be translated as it can result in program crashes if they are omitted.

Should a [linter](https://www.testim.io/blog/what-is-a-linter-heres-a-definition-and-quick-start-guide/) be used to should ensure that incorrect translations do not break the program? If at MMEX build time, a translation does not have the correct number (or type) of variables it should be flagged and the en source translation used.

> I prefer the translation strings to be separate.

Indeed – if the structure of all languages were homogeneous, then variables could be easily decoupled from the strings.

| English (en) | Hungarian (hu) | Comment |
| --- | --- | --- |
| `Page %1$s of %2$s` | `%1$s. oldal, összesen: %2$s` | Please note the dot after the page number in the translation. |
| `Step $s` | `$s. lépés` | Please note the dot after step number in the translation. How would `Page` be translated? |
| `$s string` | `A(z) $s végződő karakterlánc` | Sometimes the source string just has the variable at the beginning or end of a string and the translation has the variable enclosed by the translation. How would this be translated? |
| `%1$s string %2$s` | `%2$s karakterlánc %1$s` | Whenever there is more than one variable in a string, could the en source string please number the variables. This would allow different order of occurrence of the variables. Please see https://github.com/moneymanagerex/moneymanagerex/issues/5329. |

Does the current implementation in MMEX mean that `Page` (for `Page %s`) would be impossible to translate into Hungarian as `%s. oldal`? What would show to the MMEX users would be either:
1. `Oldal %s` with the number after the string and not at the beginning of the string and the full-stop `.` after the number missing; or
2. If the number was at the front in the source string, eg `page` (for `%s page`), then the translation would produce `%s . oldal` as the `%s` and ` ` is added later.

> Is it possible to configure crowdin to not allow the format specifiers to be removed?

[CardBook](https://gitlab.com/CardBook/CardBook/) uses `%n$s` whenever the number of variables in a string is greater than 1, i.e. `n>1`, eg. `%1$s`, `%2$s`, `%3$s`, …

Both `Money Manager Ex` and `CardBook` use the same translation platform [Crowdin](https://crowdin.com/):
* https://crowdin.com/project/cardbook
* https://crowdin.com/project/moneymanagerex

Are code pointers from the [CardBook add-on](https://addons.thunderbird.net/thunderbird/addon/cardbook/) for [Thunderbird](https://www.thunderbird.net/) helpful?

If the effort is to be made to ensure the scenarios mentioned above are implemented, should the paradigm of
> I prefer the translation strings to be separate.

be changed to

> The translation strings and variables in MMEX be combined.

What do you think?

Thank you

**Comment by ovari** [comment]
@vomikan this doesn't seem to be fixed.

https://crowdin.com/translate/moneymanagerex/470/en-hu#798138

Should the `fixed` label in this issue be removed?

Thank you

**Comment by ovari** [comment]
Thanks for merging @vomikan. Can this issue now please be closed? Thank you

**Comment by ovari** [comment]
Unfortunately, don't really know how to add singular and plural to the code.

**Comment by vomikan** [comment]
> Unfortunately, don't really know how to add singular `1 month` and plural `2 months` to the code.

    wxString text = wxString::Format(wxPLURAL("%d day remaining", "%d days remaining", daysRemaining), daysRemaining);

**Comment by ovari** [comment]
https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/cashflow.cpp#L257
```
    const wxString& headingStr = wxString::Format(_("%1$s (%2$i months)")
        , getReportTitle(), getForwardMonths());
```

Does this become:
```
    wxString text = wxString::Format(wxPLURAL("%1$s (%2$i month)", "%1$s (%2$i months)"
        getReportTitle(), getForwardMonths()), getReportTitle(), getForwardMonths());
```

Not sure to add a line or change the current line at https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/cashflow.cpp#L257

**Comment by vomikan** [comment]
The formula seems to be correct. But is there one month in this report?

**Comment by ovari** [comment]
> Is there one month in this report?

Yes.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/47910011-953c-4b80-bd76-a6a8e460443d)

**Comment by ovari** [comment]
Please close and this should be fixed now. Thank you
