### ISSUE TITLE
Distinguish source strings with multiple variables, eg. source: `%1$s blah %2$s` → translation: `%2$s absurdo %1$s`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5329]
Distinguish source strings with multiple variables, eg. source: `%1$s blah %2$s` → translation: `%2$s absurdo %1$s`.

Can the en source string please be changed from `$s` to `%1$s` when there are more than 1 indistinguishable variable in a translatable string?

It can help translators too who do not know `%1$s`.

What do you think?

Thank you

* https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#784898
* https://translatepress.com/translate-dynamic-strings-wordpress/

**Comment by n-stein** [comment]
I believe this could be achieved by enabling the preprocessor symbol wxUSE_PRINTF_POS_PARAMS then modifying all strings that have multiple variables to include the position indicators.
