### ISSUE TITLE
Slow refresh when add split rows

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5331]
> Here is the other issue I was trying to illustrate. 

Issue noted.

I've tested this on 1.6.1 Beta and there _is_ a problem when the number of splits entered results in the entire list not being visible (i.e. when the scroll bar is displayed) **_and_** the Add Split button is used instead of pressing Return in the Amount field.

The video shows:
1. Entry of some splits by pressing Return in the Amount field to finish the current entry and add a new row.
2. Entry of some splits using using the Add Split button to add a new row.
3. Removal of some splits using the Remove Split button.
 
https://user-images.githubusercontent.com/4060092/201884808-8d6d4479-5837-4bc8-80d1-045d90940793.mp4
 
1. Pressing the Return key results in the new row being added cleanly as expected.
2. Using the Add Spilt button results in a flickery scroll & refresh.
3. Using the Remove Spilt button results in a flickery scroll & refresh.

The refresh at step 2 is not as bad as is seen in @SJK55's video. Maybe I have a faster PC.

Note that the problem can easily be seen by just repeatedly clicking the Add or Remove Split buttons as shown below:
 
https://user-images.githubusercontent.com/4060092/201888684-78807b10-6566-41da-8179-cd1a5f22e933.mp4
 

@SJK55 Can I suggest that you update to 1.6.1 Beta which will deal with the bugs that are in 1.6.0 **_and_** that you press Return to enter the amount and add the next row.

There's no need to report anything more against 1.6.0.

_Originally posted by @tactilis in https://github.com/moneymanagerex/moneymanagerex/discussions/5132#discussioncomment-4144852_

**Comment by tactilis** [comment]
Tested 1.6.1-Beta.1 64-bit commit: e9c449d (2022-11-15)

Scroll refresh problem confirmed fixed.

**Comment by whalley** [comment]
Re-opening... 
https://github.com/moneymanagerex/moneymanagerex/discussions/5132#discussioncomment-4151829

**Comment by whalley** [comment]
The basic logic was there to detect if payee/categories had been added/deleted/renamed rather than just selected. It was just that we did not use it to determine if the comboboxes needed a refresh.
Hopefull this should improve things: [PR 5335](https://github.com/moneymanagerex/moneymanagerex/pull/5335)

**Comment by SJK55** [comment]
I just downloaded the latest beta from #5132 above from whalley and whatever you've done works a charm!
Smooth, responsive and what it should be doing. Thanks again for your patience. 
I'll drop a copy on that link as well!
