### ISSUE TITLE
QIF Import does not import transactions with date < today if the account doesn't already exist

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5334]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [x] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

QIF import automatically creates accounts if they do not exist in the database. However, the accounts are always created with INITIALDATE = today, so the transactions in the QIF file fail to import if TRANSDATE < today (since otherwise the transaction date is prior to account opening). 

In cases where accounts must be created, INITIALDATE should be set as the earliest transaction date.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Export a QIF file from a DB.
Create a new DB.
Import the QIF file.

Expected result:
Categories, payees, accounts, and all transactions are imported successfully.

Actual result:
Categories, Payees, and Accounts are created. Accounts all have an initial date of today. Only transactions with date >= today are imported.

**Comment by whalley** [comment]
Yep, as noted here it will need to be a two-step process at present. https://github.com/moneymanagerex/moneymanagerex/issues/5326#issuecomment-1315764051

**Comment by renato-mmex** [comment]
> QIF Import does not import transactions with date < today if the account doesn't already exist 

This problem still exists. 
I have testet with 1.6.2 Beta 1 from 6. Dez. 2022
You can work around it in the following way: 

- create all the accounts manually with the same name as in MS Money
- change all the creation date to a date prior to the first transaction date of all accounts

or

- import all transaction (all accounts are created)
- change all the creation date to a date prior to the first transaction date of all accounts
- delete all transaction
- import all transaction

See also: https://forum.moneymanagerex.org/viewtopic.php?t=10741

**Comment by vomikan** [comment]
Dear Renato, good afternoon. I fixed the problem, but in this case there is another one:

https://github.com/moneymanagerex/moneymanagerex/discussions/5404

The build with the latest changes for Windows is no longer available.

Best wishes,
Nikolay

**Comment by renato-mmex** [comment]
Hi Nikolay
Thank you for the information.
Question: What does it mean and what happens next ?
Greetings Renato          (wish happy holidays)

**Comment by whalley** [comment]
It should be building OK now.

**Comment by n-stein** [comment]
Question: Should a QIF import _always_ adjust the account INITIALDATE to the earliest transaction date, or only on new account creation where there is no preexisting INITIALDATE? 

Right now if I have an existing account and run a QIF import with transaction dates earlier than my account INITIALDATE it changes my existing INITIALDATE to the earliest transaction date.

**Comment by whalley** [comment]
> We should be guided by MMEX's behaviour when attempting to manually entering a transaction with a date is earlier than the existing INITIALDATE:

I'm not 100% in agreement with this. Whilst in general it is a good guidance to follow there can be exceptions, e.g. import will create an account if you add a transaction where none currently exists - adding a transaction via the GUI reports an error if the account does not exist.

Personally, I think the current behaviour is fine as it allows users to potentially import multiple QIF files and not have to worry about the date ordering.

**Comment by tactilis** [comment]
> I'm not 100% in agreement with this.

As I wrote it, I knew there would be alternative viewpoints 😃 

I actually don't feel that strongly either way - I  was just looking for a consistent application of "the rules".
  
 <br>
  
> it allows users to potentially import multiple QIF files and not have to worry about the date ordering.

Yes, I can see that practicality beats consistency in this case. 

So +1 for the current behaviour

**Comment by n-stein** [comment]
> I actually don't feel that strongly either way

Same, it was just something I noticed in testing and thought I'd mention in case others had strong opinions against it.

Thanks for the discussion guys. I'll go ahead and close the issue since it seems to be working as desired.
