### ISSUE TITLE
APP Android

### ISSUE THREAD

**Issue by Pinante69** [moneymanagerex/moneymanagerex#5351]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [x] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [ ] Linux 
 - [x]  APP Android

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
After upgrading from version 15 to 16 (windows version), when I copied the file to my mobile phone (android version) it never opened the file and before it always worked, I tried to downgrade with the file provided on the site (downgrade_db_13_7_v4) and it gives error. Which was very good because I could control the accounts on both the mobile and the laptop. So I would ask if it is possible to update the Android APP so that it is compatible with the Windows version. Thank you team

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![ERROR4](https://user-images.githubusercontent.com/118640233/202876625-d517b6e0-24ed-47ea-b587-f603e1b985b5.jpg)
![ERROR1](https://user-images.githubusercontent.com/118640233/202876626-2ccabd6a-1e01-4d44-b6dc-12f4313406a1.jpg)
![ERROR3](https://user-images.githubusercontent.com/118640233/202876628-47b99a29-b8dd-42b2-aafb-43c5f58fd199.jpg)
![ERROR2](https://user-images.githubusercontent.com/118640233/202876629-523e1bb4-d717-4513-bf84-c5425b6088ba.jpg)

**Comment by whalley** [comment]
See https://github.com/moneymanagerex/moneymanagerex/issues/5245
