### ISSUE TITLE
Crash on selecting Monthly or Yearly - Reports: Summary of Accounts

### ISSUE THREAD

**Issue by k13oharts** [moneymanagerex/moneymanagerex#5352]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
It seems that asset and stocks (together) have an issue during reporting their status
Viewing a fresh database with either asset or stock works but not both

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
- Created new/fresh database with one asset and one stock.
- Upon selecting Reports --> Summary of Accounts: Monthly or Yearly, mmex crashes

Expected result:
Accounts Balance graphical report

Actual result:
Crash

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
[MoneyManagerEx_dbgrpt-7480-20221120T205236.zip](https://github.com/moneymanagerex/moneymanagerex/files/10050252/MoneyManagerEx_dbgrpt-7480-20221120T205236.zip)
[newAssets.zip](https://github.com/moneymanagerex/moneymanagerex/files/10050255/newAssets.zip)

**Comment by n-stein** [comment]
Reproduced in 1.6.0. Still reproducible in 1.6.2 Alpha build.

**Comment by n-stein** [comment]
Fixed in PR #5358. During balance calculation the REFTYPE was not taken into account when pulling translink records, so it was trying to pull SHARENUMBER for asset transactions.
