### ISSUE TITLE
Filter including subcategory (nested category) fails

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#5355]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I tick "include subcategories" in the filter.
Sometimes no results.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:
I tick "include subcategories" in the filter.
I click OK.
No results.
I deselect the window to write this issue ticket.
The results appear.
I search again and they appear instant.

Expected result:
Results.

Actual result:
Sometimes no results.

# Additional information
I can't reproduce it anymore.
But somehow sometimes the filter results in no entries, I need to click "show all" and filter again.

**Comment by n-stein** [comment]
Categories are undergoing a major revision for 1.6.2 as we implement #1477. I tested this functionality with the new model and it works as expected, but its something we can watch for when we do more thorough testing.

**Comment by whalley** [comment]
@MartinX3 Does the issue still exist for you?

**Comment by MartinX3** [comment]
@whalley I think it got fixed. :)
