### ISSUE TITLE
 assertion failed (datetime) 

### ISSUE THREAD

**Issue by AgentB1** [moneymanagerex/moneymanagerex#536]
There have been several of these transient issues open and closed.  #256 was one example.

Today 31st July on starting mmex I received the same errors on startup

assert "IsValid()" failed in SetDay(): invalid wxDateTime

All previous issues have been logged on 31st day of the month, 

Restarting at midnight 1 August - the errors disappear.

This should help address the issue.

Ubuntu 14.04
MMEX 1.1.0
wxWidgets 3.0.1
SQLite3 3.8.5
wxSQLite3 3.1.1
Mongoose 5.4
Lua 5.2
GNU GCC/G++ 4.8.2

**Comment by dwrj87** [comment]
I've had these messages suddenly pop up today as well

**Comment by dwrj87** [comment]
31st again today and they've popped up

**Comment by dwrj87** [comment]
This happened again today on MMEX compiled from GIT

**Comment by guanlisheng** [comment]
Interesting but i have no idea here.

**Comment by b-trav** [comment]
I am also getting this error today (29th February 2016). It looks to me like there might be a bug when mmex opens on the last day of the month. I will try and open my files tomorrow ...

**Comment by AgentB1** [comment]
Again on 31 March
mmex v1.2.6 from "Ubuntu" repo 

ASSERT INFO:
../include/wx/datetime.h(1702): assert "tm.IsValid()" failed in Set(): invalid broken down date/time

BACKTRACE:
[1] wxDateTime::SetMonth(wxDateTime::Month)
[2] wxWizardPage::~wxWizardPage()
[3] wxWizardPage::~wxWizardPage()
[4] wxWizardPage::~wxWizardPage()
[5] wxSharedPtr<wxSQLite3Database>::get() const
[6] wxSharedPtr<wxSQLite3Database>::get() const
[7] wxDebugReportCompress::~wxDebugReportCompress()
[8] wxDebugReportCompress::~wxDebugReportCompress()
[9] wxDebugReportCompress::~wxDebugReportCompress()
[10] wxDebugReportCompress::~wxDebugReportCompress()
[11] wxString wxString::Format<wxString>(wxFormatString const&, wxString)
[12] wxString wxString::Format<wxString>(wxFormatString const&, wxString)
[13] wxEntry(int&, wchar_t**)
[14] __libc_start_main

hth

**Comment by vomikan** [comment]
@dwrj87 Could you check this issue using debugge?
https://github.com/moneymanagerex/moneymanagerex/wiki/Debuging-on-Linux-(Debian-Ubuntu)

**Comment by dwrj87** [comment]
I can, but probably not until Sunday

**Comment by dwrj87** [comment]
Hmm, I've compiled it with those flags, set my system date to the 29th Feb, and run the debugger. Nothing.....

The bug is there. I'll keep trying to get it to trigger, but if I can't, it will be triggered on the 30th April, so I shall get it done then

**Comment by dwrj87** [comment]
Hmmm, last day of the month today, and it hasn't triggered for for me..... I'll change clock to end of every month tomorrow and see what happens then
