### ISSUE TITLE
Hovering mouse pointer over an asset icon displays unwanted tootlip outline

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5360]
MMEX version:
 - [x] 1.6.1 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Hover the mouse pointer over an asset icon.  What looks like an empty tooltip outline is displayed.
 
https://user-images.githubusercontent.com/4060092/203168279-eae778f8-ac47-4668-9b5b-0df4a5a52282.mp4

Expected result:

The tooltip (or whatever it is) should not be displayed.

**Comment by tactilis** [comment]
It's possible that the small box that appears may be related to this https://github.com/moneymanagerex/moneymanagerex/issues/5057.

That issue is fixed but there may still be a remnant of the capability that was not removed.

**Comment by whalley** [comment]
Does not display text on MacOS, but this will likely fix it on Windows.

**Comment by tactilis** [comment]
Tested 1.6.2-Alpha.1 commit: 92766c0 (2022-11-22).

Confirmed fixed.
