### ISSUE TITLE
Personal Inventory

### ISSUE THREAD

**Issue by rungek** [moneymanagerex/moneymanagerex#5361]
Your program is for personal use, fair enough, but what about those of use that have personal inventories we want to keep track of. Think, wine. As inventory feature would be a great addition.

**Comment by tactilis** [comment]
@rungek Could you flesh out your idea a little please?

To me, an inventory is, at its simplest, just a list of item names, each with a set of associated attributes.

Obviously, people will have different requirements for the attributes depending on what sort of items the list contains. For example, the contents of a wine cellar requires different attributes to a collection of works of art, or a vinyl record collection.

What would you want MMEX to do with the list and the attributes?

How would using MMEX be better than, for example, using a spreadsheet to record the items?

**Comment by whalley** [comment]
Is this useful? https://github.com/moneymanagerex/moneymanagerex/issues/5129

**Comment by TomAff** [comment]
Do you mean something like this

[#3896](#3896)
