### ISSUE TITLE
Crash on changing account when adding new transaction on a stock

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#5363]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
**Wanted to add divident to a stock, seems not possible at the moment. Tried adding new transaction but looks like not the place to add divident.** 

Add screenshot or other files if needed.
# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
**Accidentally discovered this bug i.e. on New Transaction of a Stock, tried to change Account and it crashes.**

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@reddyshyam 

To help, please could you:

1. Upgrade to the latest release (1.6.1) and check whether the problem still exists.

If it does:

2. Provide a **precise, step by step**, set of instructions for reproducing the crash.

Your description does not allow us to reproduce **exactly** what you did:

_"Wanted to add dividend to a stock, seems not possible at the moment.
Tried adding new transaction but looks like not the place to add dividend.
Accidentally discovered this bug i.e. on New Transaction of a Stock, tried to change Account and it crashes."_

Thanks

**Comment by reddyshyam** [comment]
> @reddyshyam
> 
> To help, please could you:
> 
> 1. Upgrade to the latest release (1.6.1) and check whether the problem still exists.
> 
> If it does:
> 
> 2. Provide a **precise, step by step**, set of instructions for reproducing the crash.
> 
> Your description does not allow us to reproduce **exactly** what you did:
> 
> _"Wanted to add dividend to a stock, seems not possible at the moment. Tried adding new transaction but looks like not the place to add dividend. Accidentally discovered this bug i.e. on New Transaction of a Stock, tried to change Account and it crashes."_
> 
> Thanks

I did, giving again below.

Add New Transaction to a Stock, try to change Account and it crashes.

**Comment by tactilis** [comment]
@reddyshyam 

You reported this issue against 1.6.0.  Could you confirm that you are now testing on 1.6.1 and still get the crash?

I am unable to reproduce this on 1.6.1. Either it is fixed in that release or I am not following **exactly** the steps that you are because your description is open to different interpretations. Please look at this example where I have attempted to follow your instructions:
  
https://user-images.githubusercontent.com/4060092/203270147-f7033d61-d7e2-4a3b-9f36-6dd6a4c407f3.mp4
 
If I have misinterpreted _"Add New Transaction to a Stock/Shares, try to change Account and it crashes."_ and am not doing the same as you are, then please could you provide a precise, step by step, set of instructions for reproducing the crash. Screenshots would help. A screen recording would be ideal.

Thanks

**Comment by reddyshyam** [comment]
> @reddyshyam
> 
> You reported this issue against 1.6.0. Could you confirm that you are now testing on 1.6.1 and still get the crash?
> 
> I am unable to reproduce this on 1.6.1. Either it is fixed in that release or I am not following **exactly** the steps that you are because your description is open to different interpretations. Please look at this example where I have attempted to follow your instructions:
> 
>  mmex_bks2dHNnm5.mp4 
> If I have misinterpreted _"Add New Transaction to a Stock/Shares, try to change Account and it crashes."_ and am not doing the same as you are, then please could you provide a precise, step by step, set of instructions for reproducing the crash. Screenshots would help. A screen recording would be ideal.
> 
> Thanks

Hi, thanks again for looking and testing. My apologies for not being precise. I am on the latest build 1.6.1

My add transaction is on "Stock Portfolios". Please select ''My Investments" your end and then right click "add transaction" or use bottom bar. Once pop up appears, just change the account to something else and click on on popup. It should crash.

**Comment by tactilis** [comment]
@reddyshyam 
> My crash was on "Stock Portfolios".
> Please select ''My Investments" your end and then right click "add stock transaction" or use bottom bar.
> Once pop up appears, just change the account to something else and click OK on popup. It should crash

Thank you for the clarification.

I believe in the video below I am now following your revised instructions to _"change the account to something else and click OK"_. I make a couple of attempts at this with different accounts but still am unable to reproduce the crash that you are experiencing.
 
https://user-images.githubusercontent.com/4060092/203296862-6342d538-9c4d-4628-9ea2-a86ab4b93fd8.mp4
 
If I _am_ doing things correctly, then it's clear that there is something different in the accounts and transactions that you have compared to the ones I have.

To help investigate the problem, please could you paste screenshots here showing the exact sequence you are following, which accounts you select, etc. Or better still, add a video.

If you don't use anything else, then I recommend ShareX as a great tool for capturing screenshots and screen recordings.

If your screenshot or video would contain sensitive data, then please could you:
1. Create a new TEST_5363 database
2. Create the necessary number of accounts and transactions using sanitised names and values
3. Reproduce the crash
4. Upload the database here along with step by step instructions

Thanks

**Comment by reddyshyam** [comment]
Hi there,

You are too nice, patient and helpful. :) I would have given up long back. 😁 

I tried again and it happens only on specific accounts though all accounts are active. Not sure why and really do not want to go into creating sample database and testing. I know it is my problem but I am not as patient as you are. :)

Here is a video to explain what is happening. There is a crash log created too, will share once you confirm it doesnot contact my database or sentive information. Hope this is ok.

https://user-images.githubusercontent.com/12392746/203307759-f7c551fb-535e-47c2-b227-2004c9109a46.mp4

**Comment by reddyshyam** [comment]
Actually as explained earlier, this isn't an issue for me. I wanted to see how I can record dividend received for a share. Dividend gets transferred to my bank account automatically. Just wanted to see if I can record the same on MMEX. 

While attempting to do, encountered the above bug.

**Comment by tactilis** [comment]
@reddyshyam
> Actually as explained earlier, this isn't an issue for me  ...  While attempting to do, encountered the above bug.

Thank you for taking the time to report it.

> You are too nice, patient and helpful. :) I would have given up long back. 

Thanks. It would help a lot if reports of bugs could always include clear step by step instructions - and posting a video helps hugely.

I am still unable to reproduce a crash.  @whalley, @vomikan, @n-stein any thoughts?

The crash dump does not contain your database. It's a process memory dump, predominantly used to get a stack-trace in the hope of seeing the function call sequence that let to the crash.

**Comment by reddyshyam** [comment]
Oh ok @tactilis. Please find below the crash dump then. Hope it helps.

[MoneyManagerEx_dbgrpt-7844-20221122T171657.zip](https://github.com/moneymanagerex/moneymanagerex/files/10067663/MoneyManagerEx_dbgrpt-7844-20221122T171657.zip)

**Comment by whalley** [comment]
> Also on a general note, please update new bug reporting automated text as currently it is still showing 1.6.1 as beta

Done.

**Comment by n-stein** [comment]
My guess is one of two things:
1. The "Last Used" option is set for Default Payee but the PAYEEID on the last transaction is invalid.
2. The account "HDFC" doesn't have a valid CURRENCYID.

@reddyshyam First, check that account "HDFC" has a valid currency when you right click on the account and select "Edit". If it does, then try to add a new transaction in account "HDFC" to reset the last payee (it can be for $0, just need a record in the DB). Does MMEX still crash when trying to add a stock transaction afterwards?

**Comment by reddyshyam** [comment]
> My guess is one of two things:
> 
> 1. The "Last Used" option is set for Default Payee but the PAYEEID on the last transaction for account "HDFC" is invalid.
> 2. The account "HDFC" doesn't have a valid CURRENCYID.
> 
> @reddyshyam First, check that account "HDFC" has a valid currency when you right click on the account and select "Edit". If it does, then try to add a new transaction in account "HDFC" to reset the last payee (it can be for $0, just need a record in the DB). Does MMEX still crash when trying to add a stock transaction afterwards?

Hi @n-stein , thanks for looking into it. It is not just happening for HDFC account, it is happening on multiple accounts. Tested again and all of them have valid currency as it is very important as I deal with multiple currencies. 

Regarding payee id, I always use "unknown" as payee from dropdown. Is that a problem?

**Comment by n-stein** [comment]
> Regarding payee id, I always use "unknown" as payee from dropdown. Is that a problem?

Shouldn't be an issue. If it is available on the dropdown it is coming from the PAYEE_V1 table, so should be valid.

Debug report shows a memory access violation so perhaps you have a corrupt DLL.
`NULL_CLASS_PTR_READ_c0000005_wxbase32u_vc_mmex.dll!Unknown`

Can you download a fresh copy of 1.6.1 from GitHub and try to open?

**Comment by reddyshyam** [comment]
Hi @n-stein,

Good day! I always download from github, every release.

**Comment by whalley** [comment]
@reddyshyam Seems that reproducing this is not possible so I suggest the only option is for you to supply a demo database that exhibits the issue so we can investigate. However I note you have stated

> ..... really do not want to go into creating sample database and testing. 

If you don't want to do this then I suggest we/you close the issue.

**Comment by reddyshyam** [comment]
> @reddyshyam Seems that reproducing this is not possible so I suggest the only option is for you to supply a demo database that exhibits the issue so we can investigate. However I note you have stated
> 
> > ..... really do not want to go into creating sample database and testing.
> 
> If you don't want to do this then I suggest we/you close the issue.

Closing it is then. :)
