### ISSUE TITLE
Multi-transaction edit not allowing change to Amount, Payee, or Category

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5364]
MMEX version:
 - [ ] 1.5.21
 - [x] 1.6.0
 - [x] 1.6.1
 - [x] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Multiple transaction edit does not allow changing Amount, Payee, and Category even if no splits or transfers are selected.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Create a new DB
Create a new bank account
Enter a deposit/withdrawal transaction
Enter a second deposit/withdrawal transaction
Select both transactions, right click -> Edit Transactions...

Expected result:

Can edit the Amount and Category since no splits are selected. Can edit the Payee since no transfers are selected.

Actual result:

Amount, Payee, and Category are greyed out and cannot be edited.

**Comment by whalley** [comment]
I can't reproduce this.

**Comment by tactilis** [comment]
@n-stein

> Amount, Payee, and Category are greyed out and cannot be edited.

On 1.6.1, I don't see what you have found. Take a look...
  

https://user-images.githubusercontent.com/4060092/203403157-e6e64c49-b4c4-49da-b2a3-3ed54abd1748.mp4
 
You do have to tick Type to enable Payee (and that seems wrong).

But I don't observe the other problems.

**Comment by n-stein** [comment]
Strange. Here's what I see in 1.6.1. Just downloaded a fresh portable x64 copy and initialized a new DB:

https://user-images.githubusercontent.com/16599929/203404700-01bfc489-dfcf-471b-a3de-ded3219be52b.mp4

**Comment by n-stein** [comment]
Interestingly, the issue goes away if I explicitly initialize these booleans as false in the transactionsupdatedialog header

![image](https://user-images.githubusercontent.com/16599929/203405478-8322de17-f57c-4ce7-9532-c1db379ea99d.png)

**Comment by tactilis** [comment]
In @whalley's screenshot above, I note that he is able to tick Payee even though Type is not ticked, whereas I need to tick Type to enable Payee.  Very odd.

**Comment by n-stein** [comment]
@tactilis 

> You do have to tick Type to enable Payee (and that seems wrong).

You are seeing part of the issue in that the Payee box shouldn't be greyed out in the first place. However, the "Type" box enabling Payee edit is intentional. If the list of transactions you selected contains a transfer, you cannot edit the Payee (the dialog will initialize with Payee greyed out). However, if you tick the "Type" box and select either "Deposit" or "Withdrawal" you can also change the Payee because you will no longer have a transfer in your selected transactions. If you tick "Type" then select type "transfer" Payee goes back to being greyed out.

**Comment by n-stein** [comment]
I will push this small change, maybe it will fix your Payee issue too.

**Comment by n-stein** [comment]
PR #5366

**Comment by n-stein** [comment]
Tested AppVeyor build 5896 (x64 portable) of 1.6.2 Alpha. Working for me as expected now.

**Comment by n-stein** [comment]
@tactilis Did that fix your Payee issue?

**Comment by tactilis** [comment]
> Did that fix your Payee issue?

Yes, it does.

**Comment by n-stein** [comment]
Thanks, will close.
