### ISSUE TITLE
REINDEX tables prior to upgrade

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5367]
#5326 highlighted the fact that upgrade scripts could fail if SQL Index tables have become corrupt.

Perhaps we want to consider always calling REINDEX on any table we are about to touch in an upgrade script if we will be using an indexed column?

And/Or should we include an option to REINDEX all tables as a DBAdmin action, similar to DB Optimise.

![CleanShot 2022-11-22 at 20 23 29](https://user-images.githubusercontent.com/487345/203414080-1d50f49b-64d7-42fd-9ff1-d54b7492fd1f.png)

**Comment by n-stein** [comment]
Need to turn off flag SQLITE_CorruptRdOnly to do this for databases with corrupt indices. PR #5623 handles this for upgrade and debug, but we would need to do something similar for a menu option.

**Comment by n-stein** [comment]
Any concerns about performance if we just make the first line of every update script `REINDEX;`? I think it would be OK since database updates are fairly infrequent.

**Comment by n-stein** [comment]
This is not working as expected...

In mmframe.cpp I have these two lines which close the database and reopen with the SQLITE_CorruptRdOnly flag turned off
```
ShutdownDatabase();
m_db = mmDBWrapper::Open(fileName, password, true);
```

Right now they are placed here, and neither the upgrade nor a debug file can reindex a corrupt database.
![image](https://user-images.githubusercontent.com/16599929/222336178-434ca266-fa8d-4ae7-a05f-3e68580e7064.png)

If I move them down a few lines here, the upgrade still fails but the debug file can now reindex the database.
![image](https://user-images.githubusercontent.com/16599929/222336409-6108bc11-33cc-41dc-abe0-c63ec895a622.png)

So it seems the flag is being reenabled somewhere in the dbUpgrade::UpgradeDB method call.

**Comment by n-stein** [comment]
Disregard the above. It is working, I just didn't have the `REINDEX` call in the correct upgrade script for my test database. My test database was failing the v15 upgrade but `REINDEX` was only called in the v17 script. I will add the `REINDEX` call to all upgrade scripts v15-18.
