### ISSUE TITLE
Enhancement request for Transaction Filters

### ISSUE THREAD

**Issue by AgentB1** [moneymanagerex/moneymanagerex#537]
Date Range has drop down pre-selections to be 

This month
Last month
This Year
Last Year
This Financial Year
Last Financial Year

**Comment by vomikan** [comment]
Only 3 last items are missing

**Comment by guanlisheng** [comment]
i'm closing this as we will release it in 1.3.0

**Comment by AgentB1** [comment]
I have had a quick look at v1.3.0-alpha and i don't see the last 3, 
namely 

> Last Year
> This Financial Year
> Last Financial Year
>

**Comment by stef145g** [comment]
When referring to transaction filters now there is one in reports where these exist:
![report_trans_list](https://cloud.githubusercontent.com/assets/6927151/16191052/af2b2f3e-3725-11e6-872b-f783adfcd903.png)

And there is one in the Normal Transactions where they don't:
![trans_list](https://cloud.githubusercontent.com/assets/6927151/16191079/d6ac0f38-3725-11e6-8a2f-c9d5c93fc7e9.png)

@AgentB1, I take it that you are referring to the 2nd picture.

**Comment by stef145g** [comment]
This has been implemented in #835 
![trans_list_upd](https://cloud.githubusercontent.com/assets/6927151/16195283/312bf8fe-373c-11e6-9a96-730f14de1dc0.png)

**Comment by AgentB1** [comment]
Thanks Stefano i will test this later this week.

**Comment by guanlisheng** [comment]
Thanks. I had merged this pull request and you can test it on master now.

 
Thanks
Lisheng 

Sent from mobile
