### ISSUE TITLE
update of MMEX database to version 17 failed!

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5378]
MMEX version:
 - [x] 1.6.2 Alpha 1

Operating System:
 - [x] Windows 11

# Description of the bug

**After installation of: Merge pull request #5376 from whalley/master**

<img width="368" alt="image" src="https://user-images.githubusercontent.com/76920138/203656149-1c192350-fe4b-4f1a-871d-67b3a6492598.png">

**Back to:**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/76920138/203656461-bfad3141-4b1a-4c9c-95a6-54a016e32a72.png">
 **no Problem**

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
@renato-mmex Any chance of sharing a sanitised version of the DB that is failing the upgrade?

**Comment by whalley** [comment]
Looks like you (or some tool) has been manipulating your database as it contains two views that are causing this issue. You should delete these and then re-run the upgrade - if you want to re-instate the views then they will need updating due to the new category structure.

```
CREATE VIEW alldatax as 
    select CANS.TransID as ID, CANS.TransCode as TransactionType, CANS.TransDate as Date,
    coalesce(CAT.CategName, SCAT.CategName) as Category,
    coalesce(SUBCAT.SUBCategName, SSCAT.SUBCategName, '') as Subcategory,
    ROUND((case CANS.TRANSCODE when 'Withdrawal' then -1 else 1 end)*(case CANS.CATEGID when -1 then st.splittransamount else CANS.TRANSAMOUNT end),2) as Amount,
    cf.currency_symbol as currency,
    CANS.Status as Status, CANS.NOTES as Notes,
    cf.BaseConvRate as BaseConvRate,
    FROMACC.CurrencyID as CurrencyID,
    FROMACC.AccountName as AccountName,  FROMACC.AccountID as AccountID, TOACC.AccountName as ToAccountName, TOACC.ACCOUNTId as ToAccountID, CANS.ToTransAmount ToTransAmount, TOACC.CURRENCYID as ToCurrencyID,
    (case ifnull(CANS.CATEGID,-1) when -1 then 1 else 0 end) as Splitted,
    ifnull(CAT.CategId,st.CategId) as CategID,
    ifnull(SUBCAT.SubCategID,st.subCategId) as SubCategID,
    PAYEE.PayeeName as Payee, PAYEE.PayeeID as PayeeID,
    CANS.TRANSACTIONNUMBER as TransactionNumber,
    round(strftime('%Y', CANS.TransDate)) as Year,
    round(strftime('%m', CANS.TransDate)) as Month,
    round(strftime('%d', CANS.TransDate)) as Day
    from  CHECKINGACCOUNT_V1 CANS
    left join CATEGORY_V1 CAT on CAT.CATEGID = CANS.CATEGID
    left join SUBCATEGORY_V1 SUBCAT on SUBCAT.SUBCATEGID = CANS.SUBCATEGID and SUBCAT.CATEGID = CANS.CATEGID
    left join PAYEE_V1 PAYEE on PAYEE.PAYEEID = CANS.PAYEEID
    left join ACCOUNTLIST_V1 FROMACC on FROMACC.ACCOUNTID = CANS.ACCOUNTID
    left join ACCOUNTLIST_V1 TOACC on TOACC.ACCOUNTID = CANS.TOACCOUNTID
    left join splittransactions_v1 st on CANS.transid=st.transid
    left join CATEGORY_V1 SCAT on SCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid
    left join SUBCATEGORY_V1 SSCAT on SSCAT.SUBCATEGID = st.SUBCATEGID and SSCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid
    left join currencyformats_v1 cf on cf.currencyid=FROMACC .currencyid
    order by CANS.transid;
```

and

```
CREATE VIEW budget as
select * from BudgetYear_V1 BY, BudgetTable_V1 BT, Category_V1 C, SubCategory_V1 SC
where BY.BudgetYearID = BT.BudgetYearID and BT.CategID = C.CategID and BT.SubCategID = SC.SubCategID;
```

**Comment by renato-mmex** [comment]
Ran these two SQL statements on a copy of my original, still gives the same error message

**Comment by whalley** [comment]
Sorry, should have been clearer... You need to remove these views, then run the upgrade.

```
DROP VIEW alldatax;
DROP VIEW budget;
```

**Comment by renato-mmex** [comment]
I did this, of course, because I got a " duplicate " error message.

**Comment by whalley** [comment]
I ran that on your sample DB and then it upgrades and works correctly!

**Comment by renato-mmex** [comment]
Have tried everything, the error remains.
next try is with new .db3

**Comment by renato-mmex** [comment]
What a miracle, the update to V17 worked.
Thanks a lot
can be closed.

**Comment by tactilis** [comment]
@renato-mmex
> What a miracle, the update to V17 worked.

More importantly, is the question of how your database ended up with the _alldatax_ and _budget_ views being created?

**Comment by n-stein** [comment]
Someone recently asked something similar in #5375. Was this something left over from the 1.4.x version?

**Comment by whalley** [comment]
> Someone recently asked something similar in #5375. Was this something left over from the 1.4.x version?

No idea, before my time....

**Comment by TomAff** [comment]
An old Version of mmex included the View alldata.

**Comment by tactilis** [comment]
> An old Version of mmex (some years ago) included the View alldata.

Yes, I found old references to _alldata_ when searching github, but the view here was _alldatax_ and I could find no reference to that.

**Comment by TomAff** [comment]
Looks Like the Same or nearly the Same Script, that I had.
