### ISSUE TITLE
Reconciled Statement Date on Accounts

### ISSUE THREAD

**Issue by AgentB1** [moneymanagerex/moneymanagerex#538]
Most accounts are dynamic (changing) in the last month and older transactions never change.

Each month the bank statements need reconciling.

It would be helpful to have a "Latest Reconciled Statement Date" or "Statement Date" on each account.  

If enabled and a date set, no transactions can be removed, altered or added, up to to and including that date. 

If disabled, all transactions can be modified or deleted.

The default date if set is current date.

A Transaction Filter could then also be created "Since Statement Date" which would show the transactions you expect to see on next statement.

**Comment by vomikan** [comment]
I suggest to add warning message if some transaction older than last month added or edited.

**Comment by AgentB1** [comment]
Yes that would be helpful, or even "older than most recent reconciled transaction".

**Comment by stef145g** [comment]
This feature has now been completed using a 'json store'.

Extra account data is stored for each account in the table: INFOTABLE_V1 using json string variables.

Edit the account to set the initial values for that account.

**Comment by stef145g** [comment]
Completed. Extra account info added to account table without JSON data
