### ISSUE TITLE
Asset - Initial Value and Current Value

### ISSUE THREAD

**Issue by sirblime** [moneymanagerex/moneymanagerex#5381]
After upgrading to version 1.61. The Initial Value of Assets correctly reflects the converted base currency value however the Current Value reflects it incorrectly if the linked account is in a different currency 

<hr>Version: 1.6.1 64-bit<br>
 • Build: Nov 18 2022 10:39:40<br>
 • db 16 •  (aes128cbc)<br>
 • git 09cb031 (2022-11-18)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  English (South Africa) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment]
Can you please create and share a small example database replicating this issue so it is clear how you are using the assets and transactions.

**Comment by sirblime** [comment]
Hi,

Please see attached.

Regards

**Comment by tactilis** [comment]
@sirblime 
> Please see attached.

If you reply by email, attachments are stripped off.

Please go here https://github.com/moneymanagerex/moneymanagerex/issues/5381 and copy/paste your file into a reply.

Thanks

**Comment by sirblime** [comment]
> @sirblime
> 
> > Please see attached.
> 
> If you reply by email, attachments are stripped off.
> 
> Please go here #5381 and copy/paste your file into a reply.
> 
> Thanks

File attached. 
[MMEX Asset Bug.pdf](https://github.com/moneymanagerex/moneymanagerex/files/10111659/MMEX.Asset.Bug.pdf)

**Comment by n-stein** [comment]
Fixed in PR #5388
