### ISSUE TITLE
Mouse wheel scrolling rate is very slow in Split Transactions dialog

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5382]
MMEX version:
 - [x] 1.6.1
 - [x] 1.6.2 Alpha

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Using the mouse wheel to scroll the Split Transactions dialog is very slow compared to scrolling in all other parts of MMEX and in all other applications I use.

# Reproduction

Reproduction steps:

1. Add sufficient rows on the Split Transactions dialog to require scrolling to view them all.
2. Scroll up or down using the mouse wheel. Observe that the scrolling rate is unexpectedly and unreasonably slow.

For comparison, here are two screen recordings:

1. Scrolling in the Split Transaction dialog; firstly using the scroll bar and then using the mouse wheel, spinning it **as fast as possible**.
2. Scrolling in the Organize Categories dialog using the mouse wheel.
 

https://user-images.githubusercontent.com/4060092/204010199-266ea982-1f1a-42c9-8ef4-d9bc892315dd.mp4
 

https://user-images.githubusercontent.com/4060092/204010220-90e1dbf5-c0c4-4e82-bb57-c29f53272e3c.mp4

**Comment by whalley** [comment]
I can't reproduce that lag under MacOS or Win11. E.g on Win11
![CleanShot 2022-11-27 at 11 22 55](https://user-images.githubusercontent.com/487345/204132641-f7fcf199-bff5-4c57-9bb1-9b12d7cba47a.gif)

**Comment by tactilis** [comment]
@whalley
> I can't reproduce that lag under Win11

OK. Interesting.

What setting do you have for `Lines to scroll at a time` please?
 
![image](https://user-images.githubusercontent.com/4060092/204139424-73080697-3dda-4d1b-a4d0-8dee90f54b41.png)

As you can see, I have it set to 3, which is perfect for other apps and for other scrolling in MMEX - but not for Spilt Transactions. This video demonstrates the effect of turning the mouse wheel one 'notch' at a time. The scroll step on this particular dialog is tiny; it takes 12 wheel 'notches' to scroll one complete Split row.
 
https://user-images.githubusercontent.com/4060092/204139986-55312773-4b7d-485b-9e5f-6ab9892ce509.mp4
 
I observe the same 12 steps to scroll one Split row if I use may laptop's trackpad instead of the mouse or if I use a different brand of mouse.

If I increase `Lines to scroll at a time` to, say 40, then close and restart MMEX, the Spilt Transactions dialog scrolls at a more reasonable rate (but is a bit jerky due to the larger steps) - but everywhere else scrolls too fast.

**Comment by whalley** [comment]
> What setting do you have for Lines to scroll at a time please?

My settings are identical to yours.

> The scroll step on this particular dialog is tiny; it takes 12 wheel 'notches' to scroll one complete Split row.

Yes, same for me if I scroll notch-by-notch.

**Comment by whalley** [comment]
See if above change helps.

**Comment by tactilis** [comment]
```
SetScrollRate(6, 6);
```

Perfect. That makes scrolling comfortable.

Not that I ever have transactions with lots of splits - but we've seen that some people do, so this should help them.

**Comment by tactilis** [comment]
The MMEX Options dialog has the same slow scroll rate. Scrolling is often needed in that dialog if `View | Font size` is set to Large or Huge.

Could the same SetScrollRate fix be applied please?

**Comment by tactilis** [comment]
Thanks. All good now:
Split Transactions
Options
Custom Fields
