### ISSUE TITLE
Budget shows wrong month

### ISSUE THREAD

**Issue by MrCodeB2** [moneymanagerex/moneymanagerex#5390]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

Number YYYY-mm does not match with the month name. Actually used is the name for the budget. So if i set categories for a entry in an acount in november it will show up in 2022-05.

![mmex_nj9rdWoS3V](https://user-images.githubusercontent.com/56112299/204715839-28192502-23f1-42c3-8fd9-fbb6ff34ec2c.png)
![mmex_D01kjcMOsP](https://user-images.githubusercontent.com/56112299/204715842-964799ae-86e2-43c1-8e6b-0ff34b672ec2.png)

**Comment by whalley** [comment]
What are these settings set to: 
![CleanShot 2022-11-30 at 07 20 00](https://user-images.githubusercontent.com/487345/204732872-ff27bad4-f24d-4995-985e-cf208f09d685.png)
![CleanShot 2022-11-30 at 07 20 27](https://user-images.githubusercontent.com/487345/204732913-0e525f72-a873-425e-844a-1b02554116fb.png)


Month 01 is the start of the budgeting year (either calendar or finanancial). In your case, I suspect the settings are:

Use Financial Years
Start Month = July

**Comment by MrCodeB2** [comment]
ah.... RTFM...
Thank you whalley 👍
