### ISSUE TITLE
Use of | (pipe) in category name causes issues with transaction report

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5391]
Using MMEX v1.6.1 but same issue with v1.6.2.Beta.1

Raised via e-mail

If a split transaction is created as below:
![image002](https://user-images.githubusercontent.com/487345/205146894-8fbd38e5-7f1f-4d6f-94e7-e10e0d3001d5.png)

The transaction report will not report the transaction if filtered by the category. It works if the same category is used in a non-split transaction.

**Comment by rmelillo76** [comment]
I wonder if this bug has something to do with the regular expression handling in the transaction filter that allows category filters to be flexible. I also discovered a bug where an extra space is added within the text of the report filter causing the items to not be displayed unless you remove that space, but after saving the filter it is added back. I have a workaround but I will open an issue in case it is related and helps fix the defect,

**Comment by whalley** [comment]
Yes I think it is indeed an issue with the regex handling.

**Comment by n-stein** [comment]
This seems to specifically apply only to split transactions. Filter works fine on non-split transactions that have a | in the category.

**Comment by n-stein** [comment]
Fixed in PR #5398
