### ISSUE TITLE
for "all transactions" CRTL+c does not work

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5394]
MMEX version:
 - [x ] 1.6.2 Alpha
Operating System:
 - [x] Windows

# Description of the bug

**With "all transactions", the transactions can be marked with CTRL+a, but not copied with CRTL+c.**

# Reproduction
Is the bug reproducible? 
 - [x] Always

**Comment by tactilis** [comment]
> the transactions can be marked with CTRL+a, but not copied with CRTL+c.

It's not specifically that CTRL+C does not work.

The `All Transactions` view does not currently have the Copy operation enabled at all... and that is why CTRL+C does nothing.

![image](https://user-images.githubusercontent.com/4060092/205498157-1fcde4f6-644f-4f64-9d70-bdf7322e1b2e.png)
  
The question is whether there is any good reason that Copy should **not** be enabled in this view.

Now that MMEX has the ability to handle paste multiple transactions to a different account, I can't see why Copy from this view shouldn't be allowed. In any case, the main use would likely be to copy the transaction data to an external application, such as Excel.

**Comment by n-stein** [comment]
PR #5399 enables copy and paste in the "all transactions" view. 

Note that you still cannot copy/paste from an individual account into all transactions (or vice versa), but copy/paste works within all transactions itself.

**Comment by n-stein** [comment]
> copy/paste from an individual account into all transactions (or vice versa)

Is this part necessary?

**Comment by tactilis** [comment]
>>    copy/paste from an individual account into all transactions (or vice versa)

> Is this part necessary?

No, it isn't necessary.

IMO, it is enough (and is much safer for the user) to allow pasting _only_ within an account or from one account to another.

The only reason that copy from All Transactions was wanted was to copy the date to an another app (a spreadsheet, for example).

I'm not sure that pasting in the All Transactions view serves any useful purpose.

**Comment by n-stein** [comment]
> I'm not sure that pasting in the All Transactions view serves any useful purpose.

Agreed, I only enabled it because it was about the same amount of work as only enabling copying.

**Comment by tactilis** [comment]
> Agreed, I only enabled it because it was about the same amount of work as only enabling copying.

Unless anyone can think of a valid use case for pasting into the All Transactions view, then I would favour removing the capability.

It feels very confusing to be pasting into a composite multi-account view.

**Comment by n-stein** [comment]
Seeing no objections I've disabled paste in the All Transactions view to close out this issue.
