### ISSUE TITLE
Multi transaction update does not work consistenly

### ISSUE THREAD

**Issue by didikrm** [moneymanagerex/moneymanagerex#5395]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I select multiple entries to edit one of the fields, the option to change the payee is not always available. 

# Reproduction
- select multiple entries
![Capture1](https://user-images.githubusercontent.com/60562871/205506414-be5ed164-9c30-47fa-9897-2e6eab0754cd.JPG)
- right click and select 'edit transactions'
- there is no option to the edit payee field
![Capture2](https://user-images.githubusercontent.com/60562871/205506454-89746354-c6c7-4536-af2d-9b272f96864f.JPG)
- if you try multiple times, it will eventually work
![Capture3](https://user-images.githubusercontent.com/60562871/205506470-e7cd7ebb-1825-4987-896d-73be0213809b.JPG)
- if you do nothing and select 'edit transactions' again, the payee field may become unavailable again. 
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
As described above
Expected result:
- Have the payee editable all the time. This may be a buy affecting the other fields but I can't confirm that.
Actual result:
- Payee field is randomly greyed out
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Thanks for reporting.

This is a known problem, which is now fixed. See https://github.com/moneymanagerex/moneymanagerex/issues/5364

The fix will be in 1.6.2
