### ISSUE TITLE
Unable to add new share price

### ISSUE THREAD

**Issue by Markobros** [moneymanagerex/moneymanagerex#5396]
I'm trying to add new share price but it always shows me an error with invalid date: "The opening date for the account is later than the date od this transaction".

![mmx_invalid_date](https://user-images.githubusercontent.com/119841123/205578217-682bde95-5a7e-4c3c-b6fb-40462b8c9ff8.jpg)

<hr>Version: 1.6.1 64-bit<br>
 • Build: Lis 18 2022 10:39:40<br>
 • db 16 •  (aes128cbc)<br>
 • git 09cb031 (2022-11-18)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 •  Czech (Czechia) (windows-1250)<br>
 • 1920x1080 32bit 96x96ppi
![mmx_invalid_date](https://user-images.githubusercontent.com/119841123/205578093-772e4c30-ac84-403c-8300-18d4a39d1462.jpg)

**Comment by tactilis** [comment]
Right click on the account in the Navigation panel and `Edit Account`.

Is the account Opening Date _later_ than the date of your stock investment?  If so, you should alter the Opening Date to be the same date or earlier.

**Comment by Markobros** [comment]
The opening date is the same. I tried to set earlier too, but no change. Everything went well until this version (1.6.1).

![image](https://user-images.githubusercontent.com/119841123/205824422-bec22d2e-d037-49a9-b60b-2581dc448833.png)

I have another stock accounts and there everything is ok.

**Comment by n-stein** [comment]
Is this still an issue in 1.6.4 or the 1.7.0 beta?

**Comment by Markobros** [comment]
I'm sorry but I forgot to close the issue.
