### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5400]
MMEX version: 1.6.2-Beta.1 64-bit

Operating System: Linux Mint 21 Cinnamon

# Description of the bug
Can new and updated Hungarian translations from [Crowdin](https://crowdin.com/project/moneymanagerex) please be frequently imported into builds at https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex?

More work on the Hungarian translation is required and having builds with the latest translation can help with testing.

Thank you

**Comment by vomikan** [comment]
The latest translation is already there. This happens automatically. I don't understand the essence of this case.

**Comment by ovari** [comment]
> The latest translation is already there. This happens automatically. I don't understand the essence of this case.

### 1. Tools menu items are in English, not Hungarian

![Tools menu items](https://user-images.githubusercontent.com/17465872/206103129-cdda035b-da10-459f-9cbe-c10f44ec5757.png)

### 2. `Total Net Worth` is shown in English, not Hungarian

![Total Net Worth](https://user-images.githubusercontent.com/17465872/206103141-0b1d6b90-1825-49ac-abff-c3ef56cd02ab.png)

### 3. Strings have been updated

Does this help?

Thank you

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/206418184-6e50d804-d071-4438-8583-49c8dbc23fc5.png)

**Comment by vomikan** [comment]
Possible cause:
![image](https://user-images.githubusercontent.com/6836805/206421041-236bdd21-ee9c-41ef-9ded-d759b4d717a7.png)

Probably something has changed in the policy of this platform or an error has occurred. There should be no restrictions for open source projects.

**Comment by vomikan** [comment]
Synchronization has been restored, translations have been updated.

**Comment by ovari** [comment]
Verified fixed. Thank you
