### ISSUE TITLE
Import with custom columns

### ISSUE THREAD

**Issue by blueberry-bytes** [moneymanagerex/moneymanagerex#5401]
I've started using import feature for a few months. It's easier for me to write transactions to Excel from my bank account and import all of them at once. I use 2 custom columns, one text and one number. Unfortunately I don't see any possibility to import them with transactions, I have to do it manually after import.

![image](https://user-images.githubusercontent.com/5322956/206284326-21a6ec18-ec97-4ecf-a85b-a21eb670adc6.png)

**Comment by n-stein** [comment]
I must have missed this request. I already added this for 1.7.0 way back in July (#4270), so it's available in the beta. You can import to any custom fields, any type, as many as you have defined (not just limited to the 5 you chose to be displayed in the transaction panel). You'll find all of your custom fields in the bottom of the left panel on the import screen, just scroll all the way down.

**Comment by blueberry-bytes** [comment]
Thanks, I've tested it recently and it works perfectly.
