### ISSUE TITLE
"summary of accounts" - crash

### ISSUE THREAD

**Issue by akslow** [moneymanagerex/moneymanagerex#5411]
MMEX version:
 - [ ] 1.5.21
 - [x] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

From version 1.6.0 "summary of accounts" is crashing and debug report is generated.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
Same as this? https://github.com/moneymanagerex/moneymanagerex/issues/5352 ?

Can you confirm if latest beta fixes the issue. 
https://moneymanagerex.org/docs/downloads/development/

**Comment by akslow** [comment]
its fixed
