### ISSUE TITLE
MMEX Options: center labels under icons

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5415]
MMEX version: 1.6.2 Beta

Operating System: Linux Mint 21 Cinnamon

# Description of the bug

Please center labels under icons in `MMEX Options`.

# Reproduction

Is the bug reproducible? Always

Reproduction steps:
1. Menu Bar → Tools → Options…
2. In the left panel, the labels under the icons are not all centered
(a) `Home`
![Home](https://user-images.githubusercontent.com/17465872/206835847-5059f85d-6f62-4b50-ad3d-00dfb1624ced.png)
(b) `Others`
![Others](https://user-images.githubusercontent.com/17465872/206835849-5c0ae02b-bba5-462a-be13-112fc663973d.png)

Are you able to reproduce and please fix?

Thank you

**Comment by whalley** [comment]
Never noticed before, it's the same on MacOS.
![CleanShot 2022-12-10 at 18 43 57](https://user-images.githubusercontent.com/487345/206870579-3bf89aa5-14d9-49d2-bc52-c644d726839f.png)

**Comment by n-stein** [comment]
Looks fine on Windows
![image](https://user-images.githubusercontent.com/16599929/207112987-3eae057c-8a2a-415d-977c-7a59cd5c5f95.png)

**Comment by n-stein** [comment]
It's an issue in wxWidgets. Using their minimal sample you can see that without images the text is centered, but when you add images the text is no longer centered:

![image](https://user-images.githubusercontent.com/16599929/207645624-fdaf1b2d-36b8-47e0-9413-0f05a95919db.png)
![image](https://user-images.githubusercontent.com/16599929/207645834-33cdcb7c-dbaa-436b-95ae-b27d11dbf535.png)

**Comment by n-stein** [comment]
Switching to wxToolbook instead of wxListbook is somewhat better, but you lose the separate panel background color:
![image](https://user-images.githubusercontent.com/16599929/207651909-75d3c3fe-9c3e-4ac4-be0f-5f23f8f3eb2a.png)

**Comment by n-stein** [comment]
It only looks like it works in the sample because the text width is larger than the icon size. 

With standard sample icon size (32x32):
![image](https://user-images.githubusercontent.com/16599929/207663688-cbc7ca48-9ce2-422c-a6f7-c1e3252ec1e1.png)

Increasing icon size to 64x64:
![image](https://user-images.githubusercontent.com/16599929/207664420-898f1310-9e22-47e9-b1a1-7ebf9e9575a8.png)

**Comment by whalley** [comment]
Always thought those icons were a little large anyway 👍

**Comment by n-stein** [comment]
Opened PR #5423 to fix by reducing icon size from 48 to 32

Slightly smaller icons look like this:
![image](https://user-images.githubusercontent.com/16599929/207699532-b4ad3f31-8c85-4824-b692-7326963adb12.png)

**Comment by ovari** [comment]
Verified fixed with GNU/Linux. Thank you

https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/262/workflows/c64b4d55-5d3c-4747-bf8e-4208e0952e44/jobs/262/artifacts

![image](https://user-images.githubusercontent.com/17465872/207821453-88765306-0d91-4936-8329-79e59cd14b00.png)

**Comment by tactilis** [comment]
Not that it affects me, but I observe from the screenshots above that on Mac and Linux the text under the icons is poorly placed vertically. It is positioned roughly midway between the icons and therefore is not unambiguously associated with the icon above.

In fact, it appears that the text is actually slightly closer to the icon _below_ than the one above. As a consequence, it takes a few moments longer to grok the meaning of the left hand panel than it does on Windows.

Compare with Windows (on the right) below:
 
![image](https://user-images.githubusercontent.com/4060092/207849659-c9fd25be-f888-445d-a989-7e79d091cc91.png)
 
Can anything be done about this?

**Comment by ovari** [comment]
@tactilis if the icon could also be highlighted on GNU/Linux like Windows that would be helpful, i.e. highlighting both the icon and text as a group. Thank you
