### ISSUE TITLE
Savings Account missing.

### ISSUE THREAD

**Issue by N6REJ** [moneymanagerex/moneymanagerex#542]
There is no savings account category in 1.2.2

**Comment by stef145g** [comment]
The account types when setting up an account are now: Checking, Term, Credit Card, Investment.
While the types **Term** and **Credit Card** align up with the home page item separation, the others don't. 

A simple solution is to change the type **Checking** to its original label of **Checking/Savings** leaving everything else as is.

To rectify the home page alignment problem would require the changing of the current labels.That is: Checking becomes Bank, and Investment become Stocks. This would also raise confusion when a database is viewed directly via SQL Database browsers, because the current account type names are set in the database, and would be difficult to change.

The idea of having another group on the home page as Savings in my opinion is not warranted. This is because a savings account is a bank account, the same as a cheque account is a bank account.

**Comment by MisterY** [comment]
Perhaps it is technically warranted to have bank accounts together. From a user perspective, though, there is a significant difference. Savings accounts can usually transfer funds only to a checking account, they earn a higher rate of interest, etc. So there is a practical difference between the two.
The question we have is whether we want to accommodate people who are looking for more categorisation among accounts or not. This being a relatively simple implementation, I don't see why not.
The same goes for Cash account type. This one is even more different from a checking account in practice, while in the database there is no real difference. The whole purpose is just to have a visual separation between different account types, in my view.

**Comment by stef145g** [comment]
If you want to do this, then that is fine but the real questions become:
* How complicated do we want MMEX to be?
* What is the purpose for having and using MMEX?

What you say is completely true, but this belongs in the real world.

For me, I want MMEX to replicate real accounts that I maintain in a financial institution generally being a bank. These can be from the same or different banks. These are cash type accounts, and can be savings, check, daily credit or any other purposes I choose, which I can deposit and withdraw from, but at the end of the day, I want to know, how much cash money I have for my immediate usage. Makes it complicated when I have more than one account over several banks.

Also I have accounts where the money cannot be accessed at a moments notice. Here I want to know how much money I have tied up and would take time to access. I want this shown as a separate subtotal so I can arrange my finances to allow me a moderate cash flow, and maximise my investment returns.

Under the current scheme, it does this perfectly. If further classifications are added, these should be of a more general nature for better clarification. Example: The Credit Card subsection in my opinion should be generalised to Credit. Here all accounts owing money could be grouped together to reflect the total liability. Perhaps extending this to Credit and Loan Subsections to reflect short term credit and long term credit. It would then make sense to change the name of Bank to Savings or Cash.

I cannot see the benefit if having both Savings and Bank subsection. As an account type, see my previous comments above.

**Comment by MisterY** [comment]
That is correct and this requires more discussion on what scenarios do we want to support. My main point is the following: if we offer (hypothetically) 10 different account types then most people will be able to set up their accounts the way they want them. If we offer only two then the usage is much more limited.

Even if there are 30 different account types, your scenario would fit or one could still use only one type of account if they want them all under the same heading. 

It is also true that another level is required for grouping the similar account types. As you mention, Cash, Checking, Savings, perhaps even Term (what are these, BTW?) should be grouped under Banking, while Stocks (and maybe Term), as well as other investment types like certificates of deposit, belong under Investment. Assets belong under Property and Debt. Some users were also asking about accounts payable and receivable. As Stef says, it all depends on what scenarios we want to support and how useful to other people do we want MMEX to make.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/3ae11515ee1ed78e72fd4f70ae308d34499af607

https://github.com/moneymanagerex/moneymanagerex/commit/f2f6a66a09edbce84ef73b1f29550a476bf03f61

https://github.com/moneymanagerex/moneymanagerex/commit/9f1314b5c68b9e18c2b3f673374751cd801369a5

**Comment by MisterY** [comment]
Link to a related item - #455. I believe these additions refer to Cash type. 
Savings Accounts in MMEX are Bank Accounts and can also be Term Accounts.

**Comment by vomikan** [comment]
Now PC mmex supports any type of accounts like Bank Account (Checking).
