### ISSUE TITLE
Account View Balance Totals not updating after reconciled transaction deletion

### ISSUE THREAD

**Issue by brian-ebarb** [moneymanagerex/moneymanagerex#5425]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Account View Balance Totals not updating after transaction deletion.  By contrast the totals on the Home Page are updating properly. 

Please describe your issue with details.
Deleted a transaction that was a transfer from one account to another.  In Account View balances were off so attempted to recreate and delete the transaction again 2 more times doubling the original amount 28.19.  2nd transaction was 56.38. Total differnce shown is double that now, 112.76 in Account view, but Home page totals are correct:

Add screenshot or other files if needed.
![image](https://user-images.githubusercontent.com/116963850/207745375-2d7206fd-4d22-46d4-b6fb-2965e294cb64.png)

![image](https://user-images.githubusercontent.com/116963850/207745394-d97bb88f-a900-4a93-8681-b70daadba389.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Prereqs:
At least 2 checking accounts created.

Steps 1. Create single transfer from one account to another and reconcile it. 
2. Delete transaction
3. Notice totals update in Home page but not on Account view 
Expected result:
Totals update correctly to reflect deleted transaction 
Actual result:
Totals do not update the transaction deletion in Account view
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Already fixed for 1.6.2 in #5370. In the meantime, go to deleted transactions view and permanently delete them to fix the account view balances.

**Comment by brian-ebarb** [comment]
Much appreciated. You guys rock. I write code for a financial suite called Momentum as a day job. If I ever get a chance to help I will see what I can do.
