### ISSUE TITLE
`&Apply` button

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5427]
**MMEX**
* Verzió: 1.6.2-Beta.2 64-bit
* Készítési időpont dec. 15 2022 03:26:19
* Adatbázis verzió: 17
* (aes128cbc)

**Operating System**
Linux Mint 21 Cinnamon

# Description of the bug

1. Change language to Hungarian
2. Menu Bar → `&Eszközök` (`&Tools`) → `&Beallitások…` (`&Options…`) → `&Apply` button should show in Hungarian as `&Alkalmaz`.
https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=apply

![image](https://user-images.githubusercontent.com/17465872/208000031-ecb58788-d007-4a9c-bd5e-08511344c957.png)

# Reproduction

Is the bug reproducible? Always

Expected result:
`&Alkalmaz` (`&Apply`) button shown in Hungarian

Actual result:
`&Alkalmaz` (`&Apply`) button shown in English

Thank you

**Comment by whalley** [comment]
I can't reproduce this. (1.6.3 Beta.1)
![CleanShot 2022-12-22 at 15 51 47](https://user-images.githubusercontent.com/487345/209172039-d0700c3c-9675-4ef4-8a97-9edb4752439b.png)

**Comment by vomikan** [comment]
In order for the standard buttons to translate correctly, the following trick is used: a space is added to the name.
_("&OK ") 
_("&Cancel ")

**Comment by whalley** [comment]
Not sure how that relates to:

https://github.com/moneymanagerex/moneymanagerex/blob/732bf8ad716f1bdaf0c4efb8b0b80ae28d050ab6/src/optiondialog.cpp#L161

**Comment by ovari** [comment]
https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=0#q=&apply%20

**Comment by ovari** [comment]
Verified fixed.
```
Verzió: 1.6.3-Beta.1 64-bit
• Készítési időpont dec. 25 2022 03:26:31
• Adatbázis verzió: 17 (aes128cbc)
```

Thank you

![image](https://user-images.githubusercontent.com/17465872/209462295-f22801f9-4faf-4399-86e5-66ee7fc4345a.png)
