### ISSUE TITLE
Rename `Register/View Release &Notifications` to `News`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5429]
**MMEX**
* Version: 1.6.2-Beta.2 64-bit
* Build on Dec 15 2022 03:26:19
* Database version: 17
* (aes128cbc)

**Operating System**
Linux Mint 21 Cinnamon

# Description of the bug

1. Should the ampersand `&` be removed in `Register/View Release &Notifications` tool-tip/popup?
2. Can `Register/` be removed?
3. Should `Notifications` be changed to `Notes`?

Should the en source string be:
`View Release Notes`

![image](https://user-images.githubusercontent.com/17465872/208007692-1116add4-2dca-4893-917f-6b252abb9f83.png)

https://www.microsoft.com/en-us/language/Search?&searchTerm=View%20Release%20Notes&langID=382&Source=true&productid=undefined

https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=register/view

What do you think?

Thank you

**Comment by ovari** [comment]
Should the tooltip be `View Blog`?

**Comment by n-stein** [comment]
A link to the blog doesn't seem to be particularly useful, especially in the toolbar. It would be significantly better to link to the Forum (or perhaps to Github, wherever we want to steer users for "tier 1" assistance). There is already a blog link by going to Help > Community > Newsletter which I think is sufficient given the irregularity of the blog updates.

**Comment by tactilis** [comment]
> A link to the blog doesn't seem to be particularly useful, *especially in the toolbar*.

Agreed.

It's odd that the toolbar also contains `Show about dialog`.

The `About` dialog is accessible from its conventional location `Help | About`.

Having a toolbar icon for this just provides UI clutter (IMO).

**Comment by n-stein** [comment]
Even more useless is the "Show the Help file" dialog which just selects the "Help" section in the nav panel. Should be one place or the other -- if its in the toolbar we should remove "Help" from the nav panel or vice versa.

**Comment by tactilis** [comment]
> Personally I would prefer removing it from the nav panel as it seems a bit out of place there.

The argument for having Help in the Nav tree is that because MMEX _currently_ has only one main display panel (i.e. Help isn't shown in a separate window), then the Nav tree _must_ have a node that can be highlighted for each type of data (i.e. accounts, budgets, reports, and Help) that is being displayed.

**Comment by ovari** [comment]
Should the Toolbar could be Customizable, similar to Thunderbird?
https://support.mozilla.org/kb/how-customize-toolbars

Can better usage of screen real estate be achieved with putting items on a sidebar?
LibreOffice is doing this and it also helps when enabling LibreOffice to work on mobile form factors.
Desktop operating systems have displays with screen ratios changing from 4:3 to 16:9, meaning there is more space on the left and right than top and bottom.

**Comment by vomikan** [comment]
What hint will we make for this button?

https://moneymanagerex.org/blog/?utm_campaign=Application_Desktop&utm_source=News

![image](https://user-images.githubusercontent.com/6836805/209365795-bfa8027c-f50b-4582-82e7-4576adbc171b.png)

**Comment by ovari** [comment]
> What hint will we make for this button?

1. https://www.microsoft.com/en-us/language/Search?&searchTerm=blog&langID=382&Source=true&productid=undefined
(a) `Visit MMEX blog`
2. https://www.microsoft.com/en-us/language/Search?&searchTerm=news&langID=382&Source=true&productid=undefined
(a) `News`
(b) `Read news`
(c) `News posts`
(d) `Show News`
3. Something else?
