### ISSUE TITLE
Error SUBCATEGORY_V1: ## not found

### ISSUE THREAD

**Issue by tiker** [moneymanagerex/moneymanagerex#543]
I've found a way to create the following error with the latest version of MoneyMangerEX:
SUBCATEGORY_V1: ## not found

This error eventually prevents using MoneyManagerEX and requires terminating the application from the task manager.  It will re-occur under certain conditions when re-opening the database file.

To reproduce the error, do the following:
- Create a new test database, default settings don't matter
- Go to the new transaction entry form
- Fill the form as a withdrawal, entering a new payee
- Select an existing category for the transaction
- (without pressing "OK" to create the transaction) go back to the Category selection screen and delete the category you had previously selected
- Click cancel on the category selection window
- Press OK to create the transaction.
You will now have the error on the screen.

I was able to fix the problem by opening the SQLlite file with a SQLLite DB editor.  The table containing the list of Payees will show the default category for the new payee being the category that was selected and then deleted.  This causes the error when the software tries to reference the default category which no longer exists.

If I get time I'll see if I can figure out how to fix the problem in the code but I'm posting this problem here in case someone else who is more familiar with the code can fix it quicker.

I should probably add:
- Money Manager EX 1.2.2
- Portable version
- x64 version running on Windows 7 Enterprise

**Comment by guanlisheng** [comment]
@vomikan what do you think?

**Comment by vomikan** [comment]
Seems a bug. I'll check later how to fix.

2015-08-10 17:29 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by siena123** [comment]
I have an idea what is going on with this issue. Nikolay, I will try to post something soon.
- James
----- Original Message -----

**Comment by guanlisheng** [comment]
any update about this ticket @siena123 @vomikan

**Comment by siena123** [comment]
This fix has already been merged in to the main trunk.
        https://github.com/moneymanagerex/moneymanagerex/pull/546----- Original Message -----
