### ISSUE TITLE
Void Transaction are considered in cashflow report (both daily, montly, and transaction)

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/moneymanagerex#5437]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX  (not tested)
 - [X] Linux 

# Description of the bug
Recurring Transaction "VOID" expected to not be consider in cashflow.
example:
* homepage sample screen with cash account <img width="583" alt="1-homepage" src="https://user-images.githubusercontent.com/3205448/208293762-1b37c586-1b49-491e-823d-82666c5e4736.png">
* sample recurring transaction of type withdrawal "void" 
<img width="778" alt="2-recurring-void" src="https://user-images.githubusercontent.com/3205448/208293816-b84711ba-f958-451f-a215-d3c7fa94f57f.png">
* example of cashflow with evidence of "decrese" total 
<img width="380" alt="3-cashflow" src="https://user-images.githubusercontent.com/3205448/208293848-1deccbb0-ad2e-49e0-823c-781916de940a.png">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
as example here a file https://1drv.ms/u/s!AtPBR0zMvFhpjfxXOZmALjbz4HeE2w?e=QvTdJs
Step:
* Create Recurring void Transaction
* open Cashflow
* see that amount of recurring void transaction is consider

Expected result:
Void transaction does not alter the total for account

Actual result:
void transaction alter the total for account

# Additional information
Issue is present for any type of transaction (deposit, withdrawal and transfert). 
I suppose that this need to be done on "cashflow.cpp" in function mmReportCashFlow::trueAmount by checking if transaction isf of type VOID. Suppose (but not sure) after line 45 somethings like
`if (trx.STATUS == Model_Checking::VOID_) return 0.0`

**Comment by tactilis** [comment]
@wolfsolver What is your use case for voiding a recurring transaction please?

What is the purpose in keeping the RT if future instances are voided?

Just trying to understand.

**Comment by wolfsolver** [comment]
Main goal of void recurring transaction is to keep memory of payment that is NOT done using my account. For example my wife need to pay car insurance, but I don't handle wife bank account. So I track it as void transaction, so I can remember to my wife "Hey did you pay insurance?" :)

**Comment by tactilis** [comment]
> so I can remember to my wife "Hey did you pay insurance?" :)

Using Google Calendar (or any other calendar) with a recurring event as a reminder to you to ask your wife would seem an easier way to handle this rather than bodge this into MMEX as a void transaction for an account that you don't even handle in the application.

Or, even better, suggest that your wife sets up a recurring payment from her account, then nobody needs reminding.


> Another use case is that I user cash flow for some account only. I want to transfer "saving" to different account if balance of main account is positive. So I track transfer as void, and only when apply I decided if skip or apply removing void flag.

This feels (to me) as though you are trying to bend MMEX in a way that it was never intended to be used. Personally, I would again set a recurring calendar event to remind me to check for a positive balance every month (or whenever) and then just enter the transfer (and make it in the real world!) if the balance of main account is positive.

Maybe it is correct that voided future recurring transactions should not be included in the cashflow, but your use of MMEX feels like it is outside of the scenarios the app was designed for.

**Comment by wolfsolver** [comment]
I know that there are some different tools (like Google calendar) for remember thinks. Anyway I think that main goal of void transaction is to track something that not alter the Ballance. Same behaviour is what I expected from void RT.

By the way another use case that I have in my recurring transaction is this: I setup a RT for payment rate (for example 10 rate for dentist). This is normal transaction. Then I ask for reimbursement to my insurance, so I setup a deposit void RT (10 rate of deposit) , but I don't want that reimbursement impact on Balance since I'm not sure that reimbursement append due some limitation on my insurance (I prefer to have cashflow in worst case).

**Comment by n-stein** [comment]
PR #5446 will exclude VOID transactions from cashflow reporting.

**Comment by vomikan** [comment]
I suspect there is another problem. We mark deleted transactions with the deletion time, but do not set the Void flag. Therefore, deleted transactions are counted in reports.

I suggest that when deleting a transaction, put down the void status. When restoring, change to an empty status or followup.

**Comment by tactilis** [comment]
> I suggest that when deleting a transaction, put down the void status

I disagree.

Changing the status was similar to @n-stein's original implementation of Deleted Transactions, where restored transactions ended up with a status of Unreconciled.

It was discussed and for good reasons changed to the current implementation which allows a Delete/Restore round trip to return transactions to exactly the same state they had before deletion.

**Comment by vomikan** [comment]
> I disagree.

I probably didn't describe the problem well. There is a new DELETED TIME field for deleted transactions. But we haven't started using it. This is a mistake.

The transaction status can not be changed.

**Comment by n-stein** [comment]
You're right we are missing it here specifically (only for deleted _future_ transactions), so that was an oversight. I'll add the exclusion.

**Comment by n-stein** [comment]
PR #5447 will take care of the future deleted transactions being included in cashflow.

**Comment by rusty6285** [comment]
Same issue is occurring with any deleted transaction. Is there a way to view deleted transactions so I can try to re-balance the daily cash flow report by creating opposite transactions? or, is there access to a build with this fixed ? appreciate all the work you do
