### ISSUE TITLE
New View for recursive categories

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#5442]
Not sure if it's the right place to open the issue, but it involves MMEX, DB and GRM so I've opened it here for more visibility.

Considering the new recursive categories, what about define a view oto quickly get all category data in GRM?

Something like this query, just under a view that can be joined by other queries
https://github.com/moneymanagerex/general-reports/tree/master/packages/Category/OneCategoryList

**Comment by whalley** [comment]
We could do this, or the user could add the query to their GRM SQL. I personally prefer the latter.

**Comment by whalley** [comment]
Understood, but I saw this as a small inconvenience. If somebody wants to add it in the next release I have no strong objection. My view (pardon the pun) was that GRM users need to carefully track DB changes and carefully mange their SQL scripts so thought it a small issue.

**Comment by vomikan** [comment]
Related issue
https://github.com/moneymanagerex/moneymanagerex/issues/3617

**Comment by gabriele-v** [comment]
With this you get only the first parent, I think you need the recursive to get all the parents.
Not sure if the recursive could be added to a view BTW.

**Comment by n-stein** [comment]
Hmm. It seems to work for me:

![image](https://user-images.githubusercontent.com/16599929/208513422-8870506d-c0f8-4a04-8093-02f6deba83a4.png)

**Comment by gabriele-v** [comment]
Got it, it works because in the view you are querying the view itself, so it's already recursive

**Comment by n-stein** [comment]
Yeah, the RECURSIVE keyword isn't actually required unless you're using PostgreSQL. In SQLite its enough for the query to simply reference itself.
