### ISSUE TITLE
Update to 1.6.2 failed (Categories with same name but differing case)

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#5443]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I am unable to start 1.6.2. Loading my existing (v16) database fails with the following error:
`SQL logic error[1]: error in cumulative: no such table: main.allData`

![Capture](https://user-images.githubusercontent.com/1184162/208384826-4d5ba440-8f8e-47b0-be55-d1a46a323e46.JPG)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
Looks like you have a VIEW in your database that is not in the current schema. It may be legacy and is now causing issues with the recent schema change.

Please extract and try applying the following debug file.
[views_db_fix 2.zip](https://github.com/moneymanagerex/moneymanagerex/files/10258485/views_db_fix.2.zip)

**Comment by Dandy64** [comment]
> Looks like you have a VIEW in your database that is not in the current schema. It may be legacy and is now causing issues with the recent schema change.

Just FYI - I have been using the portable version of the Money Manager Ex and the DB was upgraded with no problem.

**Comment by cmbarbu** [comment]
Thank you, @whalley, the fix solved the issue and the DB can be opened again.

No clue why the view was still in the schema, but on the other hand my database file is _really_ old.

**Comment by renato-mmex** [comment]
There are other such problems (solved)
https://forum.moneymanagerex.org/viewtopic.php?p=23624#p23624
DROP VIEW IF EXISTS alldata2;
DROP VIEW IF EXISTS cumulative2;

**Comment by whalley** [comment]
Need to try and find out where all these views are coming from 😀

**Comment by renato-mmex** [comment]
sins of a bygone era 😒🤓

**Comment by aramacciotti** [comment]
Solution was not enough in my case. I still get the error:

![image](https://user-images.githubusercontent.com/6824322/208594353-1e971f5e-aeca-444a-b73a-7d16b7aefa82.png)

**Comment by renato-mmex** [comment]
@whalley @n-stein 
The database works with MMEX 1.6.1 without problems, no VIEWs exist.
Upgrading to 1.6.2 or 1.6.3 Beta1 gives the error message, can you help ??

**Comment by whalley** [comment]
Looks liks something odd in the existing categories. If we could get a dump of the  CATEGORY_V1 table and SUBCATEGORY_V1 table that might help in diagnosis.

**Comment by vomikan** [comment]
Could you please export all categories?
![image](https://user-images.githubusercontent.com/6836805/208722336-cef9b738-43c1-441c-8c07-2e96c7d6362b.png)

![image](https://user-images.githubusercontent.com/6836805/208722489-4cca7914-a50c-4a92-93b1-c6ba0328c5aa.png)

and upload the result here.

**Comment by aramacciotti** [comment]
Here it is

Cordiali saluti

Andrea Ramacciotti

Da: ***@***.***>
Inviato: martedì 20 dicembre 2022 17:56
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Update to 1.6.2 failed (Issue #5443)


Could you please export all categories?
[image]<https://user-images.githubusercontent.com/6836805/208722336-cef9b738-43c1-441c-8c07-2e96c7d6362b.png>

[image]<https://user-images.githubusercontent.com/6836805/208722489-4cca7914-a50c-4a92-93b1-c6ba0328c5aa.png>

and upload the result here.

**Comment by tactilis** [comment]
@aramacciotti 

If you reply by email, then attachments get stripped off and we can't see them.

Please could you reply directly in the github thread here https://github.com/moneymanagerex/moneymanagerex/issues/5443

Attach your file by zipping it first (because github won't allow .qif) and then dragging the .zip file into your reply.

Thanks

**Comment by renato-mmex** [comment]
[catecs.zip](https://github.com/moneymanagerex/moneymanagerex/files/10272093/catecs.zip)

**Comment by aramacciotti** [comment]
> [catecs.zip](https://github.com/moneymanagerex/moneymanagerex/files/10272093/catecs.zip)

Thx Renato

**Comment by n-stein** [comment]
You have two categories with identical names (case insensitive): "Tempo libero" and "Tempo Libero". Rename one of them and try the upgrade again.

**Comment by renato-mmex** [comment]
@n-stein  Congratulations, that was the solution.
But why that was possible, that in the past apparently distinguished upper/lower case and now no longer.

**Comment by aramacciotti** [comment]
Great. Thanks. It worked.

Cordiali saluti.

Andrea Ramacciotti

Da: ***@***.***>
Inviato: martedì 20 dicembre 2022 21:57
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Update to 1.6.2 failed (Issue #5443)


You have two categories with identical names (case insensitive): "Tempo libero" and "Tempo Libero". Rename one of them and try the upgrade again.
