### ISSUE TITLE
Hidden subcategory is shown at the drop-down window

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#5444]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ x] 1.6.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The hidden sub-category is shown in the drop-down window and can be chosen by the user, but can not be saved.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Reproduction steps:**
1. Opened Organize Categories.
2. Made Automobile's sub-categories hidden: Gas, Maintenace, and Registration
3. These subcategories have become pale.
4. Added a new transaction and has chosen Automobile/Gas (Gas, Maintenace, and Registration are pale).
5. Pressed OK button
 
**Expected result:**
The subcategories should be hidden and the user can not choose them.
**Actual result:**
The "hidden" subcategories are still visible and can be chosen. But on pressing the OK button appears the message "Invalid value", so the user can not understand what is going on.

**# Additional information**
* If the category (not subcategory) was hidden, the category is not shown and can not be chosen. 
![image](https://user-images.githubusercontent.com/83161661/208411185-f0a8bc10-c89b-4716-a3f8-bac7dc7a69ab.png)
![image](https://user-images.githubusercontent.com/83161661/208411294-c15a674a-49f3-46a3-b64f-d066a0ad234b.png)

**Comment by tactilis** [comment]
Hidden categories being shown in the combobox dropdown has been a problem since that UI change was made.

There was some discussion of it in this thread https://github.com/moneymanagerex/moneymanagerex/issues/4730

**Comment by n-stein** [comment]
Maybe I'm misunderstanding the issue, but I don't see anything wrong with the dropdown. When I hide the subcategories I only see the active categories/subcategories

![image](https://user-images.githubusercontent.com/16599929/208455428-c05c0c9f-ba4d-4ce3-bb21-cac53bb6e61f.png)

Are you pressing "Enter" in the dropdown then selecting the hidden category from the "Organize Categories" dialog that pops up? If so I think we just need to disable the "Select" button if an inactive category is chosen.

**Comment by n-stein** [comment]
PR #5445.

In addition to disallowing "Select" for inactive categories, I also changed it so that the "Cancel" button doesn't update the value of the combobox (previously the "Select" and "Cancel" buttons functioned identically).

**Comment by tactilis** [comment]
> Hidden categories being shown in the combobox dropdown has been a problem since that UI change was made.
> There was some discussion of it in this thread https://github.com/moneymanagerex/moneymanagerex/issues/4730

Oops. My bad.

It was a problem originally but you fixed it, @n-stein.

I didn't re-check a recent build.
