### ISSUE TITLE
Database failure in 1.6.2

### ISSUE THREAD

**Issue by petubl** [moneymanagerex/moneymanagerex#5448]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# I went to run mmex and i was prompted to upgrade to 1.6.2. When i did, the program throws up a warning screen that says the following:
MMEX database upgrade to version 15 failed. 
Please restore DB from autocreated pre-update backup.

SQL logic error[1]: no such table: CURRENCYFORMATS_V1

The file is unchanged, but i end up with two new files upgradev13.bak and upgradev14.bak

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Thank you for any help you can provide!

petubl

**Comment by whalley** [comment]
Am I correct in thinking that you currently have v1.4.x ? 
If so, you need to follow the instructions here: https://github.com/moneymanagerex/moneymanagerex/issues/2353 first before upgrading

**Comment by aramacciotti** [comment]
I have the 1.6.1 version and got the following error:

![image](https://user-images.githubusercontent.com/6824322/208633503-de97b239-fe15-4630-890e-1bdb029dddf0.png)

**Comment by petubl** [comment]
Hi whalley and thanks for responding. 

I am not sure what version i was one, to be honest. 

Should i follow your instructions, on the original file, or do i need to rename one of the two .bak files?

Thanks once again

petubl

**Comment by petubl** [comment]
> 

Hi i tried to do it using the debug file in the linked post but i get the same error...

**Comment by petubl** [comment]
I tired again with a backup copy of my database and it works great. Thanks for taking the time to look into this for me!
