### ISSUE TITLE
General Report Manager: Report Hidden when Changing Report Group

### ISSUE THREAD

**Issue by valsamis-d** [moneymanagerex/moneymanagerex#5449]
MMEX version:
 - [x] 1.6.2 x64 Windows Portable
(master branch).

Operating System:
 - [x] Windows

After upgrading to v1.6.2 I recreated some of my custom reports that were based on user-defined views. However, I cannot assign them to a new report group.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 
Reproduction steps:

1. Open General Reports Manager
2. Create a new report (even a blank one)
3. Assign it to one of the existing report groups
4. Right-click on the report and choose to assign it to another group
5. Type the name of a non-existing group, say "New Group"
6. The new group appears in the General Report Manager tree view, but the report does not, while it is shown in the list of the reports

![image](https://user-images.githubusercontent.com/17590539/208729319-53448d97-b5d4-48e7-bda5-a6d396d4a78a.png)

Expected result:

The report should be shown under the "General Report Manager > New Group" hierarchy

Actual result:

The "General Report Manager > New Group" is being showed as empty.

**Comment by vomikan** [comment]
I can't reprodce this.

**Comment by tactilis** [comment]
I cannot reproduce this either.

@valsamis-d Could you do a screen recording and upload it here please?

If you don't have screen recording software, then I recommend ShareX [https://getsharex.com/](https://getsharex.com/)

`Capture | Screen recording` and select the MMEX window.

**Comment by valsamis-d** [comment]
@tactilis see attached

https://user-images.githubusercontent.com/17590539/208860925-e588bc5e-ec05-4045-b8a0-d4121fe4b5aa.mp4

**Comment by whalley** [comment]
I can't seem to reproduce that on MacOS.

**Comment by vomikan** [comment]
Just because the theme is too dark, the icon is not visible >
If you click on it, a hidden item with a report will appear.

![image](https://user-images.githubusercontent.com/6836805/209230457-f93aa604-6e0c-452b-916c-a2072b51a138.png)

**Comment by valsamis-d** [comment]
> Just because the theme is too dark, the icon is not visible >
> 
> If you click on it, a hidden item with a report will appear.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6836805/209230457-f93aa604-6e0c-452b-916c-a2072b51a138.png)
> 
> 

Ouch! I feel like an idiot now :( Thanks @vomikan !

**Comment by tactilis** [comment]
> Ouch! I feel like an idiot now :( 

No need to feel that. The expand/collapse icons the Navigation tree are all but invisible in your screen video. Very dark icons on black background are not great for usability.
