### ISSUE TITLE
.qif import stores negative amount in ToTransAmount

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#545]
Hi, we have a report from a user who exported and imported the data via .qif file:

> In the attachment you find a new database 'test.mmb', the qif-export to this database and an other new database 'test2.mmb' in which I have imported the data from the qif-file. I used the latest desktop version 1.2.2 Win 64 portable. If I open 'test2.mmb' on my mobile, no entry is reconciled (it does not seem possible to import the status out of a qif-file) and the sign of the withdrawels are wrong (see the third entry of the scrennshot from the e-mail attachment - a minus is missing).

Qif file available here: http://pastebin.com/8vvB4R0x

Should you need the .mmb files, I can share/send. However, this should be obvious.

Transactions created via MMEX application use positive numbers in the ToTransAmount column. Transactions created via Qif import have negative amounts. Please synchronize so that the ToTransAmounts values are consistent.

**Comment by vomikan** [comment]
fix 
~~~~~
    trx->TRANSAMOUNT = fabs(amt);
    trx->TOTRANSAMOUNT = transfer ? amt : trx->TRANSAMOUNT;
~~~~~
