### ISSUE TITLE
Missing currency ZMW Zambian Kwacha

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5451]
MMEX version:
  - [x] 1.6.2 
  - [x] 1.6.3 Beta 1

Operating System:
 - [x] Windows

Today when I open a DB with 1.6.2 the currency ZMW Zambian Kwacha is missing.
Also when I open a new DB with version 1.5.0 this currency is missing.
by the way: my DB is from 2009 + updates and has much more (other) currencies
The attached files show the differences.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

[CURRENCYFORMATS_V1-163Beta.zip](https://github.com/moneymanagerex/moneymanagerex/files/10272039/CURRENCYFORMATS_V1-163Beta.zip)

**Comment by n-stein** [comment]
Probably related: the URL that the currency update script checks returns a 404.

https://github.com/moneymanagerex/database/blob/master/update_currencies_from_ISO.sh#L42

**Comment by tactilis** [comment]
There's going to be a lot of breakage!

A quick search shows that _many_ projects are dependant on the original list at https://www.currency-iso.org/dam/downloads/lists/list_one.xml

👎 to six-group for not maintaining the old URL and providing redirection.

**Comment by n-stein** [comment]
It does redirect properly, but somebody goofed and named the file `list-one.xml` instead of `list_one.xml`.

**Comment by n-stein** [comment]
I sent a message to them and asked them to rename the file.

**Comment by n-stein** [comment]
Response from SIX:

> The underscore in filenames is no longer supported on our systems.
>We would therefore like to ask you to retrieve the file only via the new URL:
>
>https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml
>
>The existing redirects for the previous domain currency-iso.org will no longer be adjusted,
as all content was already migrated to the SIX website several months ago.

So that's a polite "tough luck, deal with it".

**Comment by whalley** [comment]
That currency update script will need updating as it related to the previous (aborted) v1.4.x version.

**Comment by n-stein** [comment]
I fixed the currency update script, but what is the end goal here? Should the CURRENCYFORMATS_V1 database contain all current and historical currency codes? If so, the database increases from the current 153 to 427 entries. If we only add missing "active" codes then it increases to 312 entries.

**Comment by vomikan** [comment]
I don't see the point in collecting all currencies, much less historical ones.
Rarely, more than three to five currencies can be used in personal finance.

**Comment by n-stein** [comment]
I think we can get by without historical ones, but for the sake of localization we should add the 15 missing active currencies which include the third Belarusian Ruble (BYN), Cuban Peso (CUP), the new Leone (SLE), and both of the sovereign Bolivars (VED, VES).

**Comment by n-stein** [comment]
Might also look at updating the script to pull from the Unicode CLDR https://github.com/unicode-org/cldr-json.

**Comment by n-stein** [comment]
https://github.com/moneymanagerex/database/pull/46 adds missing ISO currency codes and updates names to conform to the Unicode CLDR.
