### ISSUE TITLE
About dialog info

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5459]
MMEX version: 1.6.3 Beta.1

Operating System: GNU/Linux

# Description of the bug

1. Should the list shown in the red box in the image below be separated into many dot `*` points?
2. Should the dot points in the green box in the image below be sorted alphabetically?

![image](https://user-images.githubusercontent.com/17465872/209429789-0dd12ead-8cf6-45e4-bd8a-2db538284b5d.png)

# Reproduction

Is the bug reproducible? Always

What do you think?

Thank you

**Comment by ovari** [comment]
3. Should `Build using` be past tense to become `Built using` as shown in the blue box in the image below?

![image](https://user-images.githubusercontent.com/17465872/209429855-13baf772-daea-4627-9c0a-736fc98d8c43.png)

Thank you

**Comment by ovari** [comment]
Please change `Build` to `Built` so that `Build on Dec 24 2022 03:27:11` becomes `Built on Dec 24 2022 03:27:11`.

Thank you

**Comment by ovari** [comment]
On GNU/Linux (please see image below):
1. `Git commit` does not show
2. `Git branch` does not show
3. there is no longer a blank line before the `Running on:` section

![image](https://user-images.githubusercontent.com/17465872/211146670-05076dc9-7e55-4339-9189-4f3071782427.png)

**Comment by ovari** [comment]
Should the heading `Has been built using:` be reworded to be more concise?

For example:
1. `Built using:`
https://www.microsoft.com/en-us/language/Search?&searchTerm=built%20using&langID=635&Source=true&productid=0
2. `Built with:`
https://www.microsoft.com/en-us/language/Search?&searchTerm=built%20with&langID=635&Source=true&productid=undefined

`Built width:` seems to be the better option.

Thank you

**Comment by vomikan** [comment]
Regarding the GIT:
```
#ifdef GIT_COMMIT_HASH
        << bull << wxString::Format(simple ? "git %s (%s)" : _("Git commit: %s (%s)"), GIT_COMMIT_HASH, GIT_COMMIT_DATE) << eol
#endif
#ifdef GIT_BRANCH
        << bull << wxString::Format(simple ? "%s" : _("Git branch: %s"), GIT_BRANCH) << eol
#endif
```
Seems this variables does not defided in your system.
