### ISSUE TITLE
Change subcategories string differentiation

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5463]
# Description of the feature
Hi, When there are subcategories, currently the string is "Category:Subcategory:Subsubcategory" which IMO is not very aesthetic. What do you think of replacing `:` with `>`?

![imagen](https://user-images.githubusercontent.com/11770760/209464034-5c2b030d-3b76-40f2-9ecf-bb12e7429bee.png)

IMO this is more aesthetic and more logical. For example Amazon uses this system too:
![imagen](https://user-images.githubusercontent.com/11770760/209464048-275083cb-c061-464e-8492-4d1e838b1c35.png)

# Use cases

It's just an aesthetic matter but I personally don't like the actual differentiation. Maybe it's just me though.

**Comment by tactilis** [comment]
You can do this already.

Just change the category delimiter by typing the desired character in the View Options:
 
![image](https://user-images.githubusercontent.com/4060092/209464900-609c6a52-45b4-406e-ad86-223dfcf08885.png)

**Comment by BanCrash** [comment]
> You can do this already.
> 
> Just change the category delimiter by typing the desired character in the View Options:
> 
> ![image](https://user-images.githubusercontent.com/4060092/209464900-609c6a52-45b4-406e-ad86-223dfcf08885.png)

Ooops, didn't know that. Thank you!
