### ISSUE TITLE
Improve budget perfomance report

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5464]
# Description of the feature
Hi again, 

After seeying Budget category summary report, I think that that report should be combined with the budget perfomance report, so it would end showing in a better way all the estimations and expenses on each category and subcategory, and giving more information than currently.

Currently:
![imagen](https://user-images.githubusercontent.com/11770760/209464427-9f35a7e9-30f2-45e6-abe2-0db63e22d756.png)

Idea: (sorry for using paint :/)
![imagen](https://user-images.githubusercontent.com/11770760/209464792-22d60e79-2699-4bb8-b98e-92791b17f93f.png)

So, as you can see, on one side we have a better looking report, since the subcategories are showed with indentation instead of repeating the previous categories, and for the other side we have more information since we have the totals for each category and each subcategoy. In my opinion this joins both reports, so it could be ended having only this one report. Other option would be to create this as a third new report, but that would be worst for mantaining I guess.
# Use cases

More information for the budgets in the report and also better aesthetic.

**Comment by n-stein** [comment]
Formatted to match the budget category report

![image](https://user-images.githubusercontent.com/16599929/217384145-0df7b0c5-5c9e-49d5-86b5-2682eb450e06.png)

**Comment by BanCrash** [comment]
> Formatted to match the budget category report
> 

Nice job, thanks!

**Comment by n-stein** [comment]
Fixed. @BanCrash Let me know if this is not what you are expecting.

**Comment by BanCrash** [comment]
> Fixed. @BanCrash Let me know if this is not what you are expecting.

Is there any build link available to test it?

**Comment by BanCrash** [comment]
I've just tested and now it's working as on 1.6.3. Thank you again @n-stein !
