### ISSUE TITLE
Show only subtransactions that match the filter

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5465]
# Description of the feature
Hi again, third and hopefully last feature request of the day.

When filtering for an specific category, amount or notes, it should show only the subtransactions that match the filter instead all the transaction. I mean, when you create a transaction divided in 3 subtransactions, if only 1 of them match the filter, should appear that as a result instead of showing all the original transaction IMO.

For example, if I have this transaction:
- Amount: 30 € Category: Presents Notes: Present for birthday
- Amount: 100 € Category: Bills Notes: Electricity bill
- Amount: 500 € Category: Bills Notes: Gas

When filtering:
- For amount: between 200 € and 600 €, it will show a transaction with amount 500 € instead of the entire transaction with 630 €, and the filtered balance will be 500 € instead 630 €.
- For category: Bills, it will show a transaction with amount 600 € and the category bills, instead the entire transaction of 630 €, and the filtered balance will be 600 € instead 630 €.
- For notes: Electricity, it will show a transaction with amount 100 € and notes Electricity bill, instead the entire transaction, and the filtered balance will be 100 € instead 630 €.

This new transaction could have a visual indicator (for example, with the text being in bold or italic) for knowing that it has a subtransaction instead the entire transaction, and when clicking on it for editing it will show the entire transaction, not the subpart. So these changes will only have visual effects.

# Use cases
When you filter normally you want to know the specific data for what you are filtering. If I want to know how I expended on presents yesterday for example, it's useless and counter-productive knowing that yesterday I have a transaction of 630 € since for presents I only expended 30 €. Also when there are a lot of transactions, filtered balance will only show the matched results which it's the expected IMO.

**Comment by n-stein** [comment]
New functionality: 

![image](https://user-images.githubusercontent.com/16599929/225052542-8a75e1e4-7dbe-4caa-8f39-fcaa0dc61230.png)
![image](https://user-images.githubusercontent.com/16599929/225052749-2c46c1fb-a69f-428d-b37e-9860c9deafbc.png)

If ALL splits match the filter, the record is shown as as single line.
e.g. set max amount to 70, the whole transaction matches the filter
![image](https://user-images.githubusercontent.com/16599929/225061778-80a8c932-819e-438d-9659-9afb19d96702.png)
![image](https://user-images.githubusercontent.com/16599929/225062021-b6b996bd-20ea-4c16-91cb-4232bedb1b61.png)

If a subset of the splits match, the record is expanded and only matching splits are shown each on a separate line with ID = TRANSID.SPLITTRANSID
e.g. Setting the amount filter to max of 50 now the whole transaction doesn't match, but the individual splits do:
![image](https://user-images.githubusercontent.com/16599929/225062970-560c1109-9794-4bc0-b968-1cb2b530b88a.png)
![image](https://user-images.githubusercontent.com/16599929/225068693-69a08b8a-ba6d-4be5-893e-a1c531e6d56e.png)

e.g. Only one split matches the selected category
![image](https://user-images.githubusercontent.com/16599929/225069061-0c3095d5-002c-405c-bae8-5448aaf6e6e1.png)
![image](https://user-images.githubusercontent.com/16599929/225069203-501a2604-5a53-4834-985e-49b11cb4ad34.png)

Double clicking on the record brings up the full transaction as normal.

Transaction report looks as it did previously (splits are always expanded) with the exception that they are now identified by the ID = TRANSID.SPLITTRANSID and all filters apply to split lines individually
![image](https://user-images.githubusercontent.com/16599929/225071068-54141745-2edd-415c-af37-f61cdf09e494.png)

Clicking on the ID in the transaction report opens the full transaction as normal.

**Comment by BanCrash** [comment]
> New functionality:
> 
> ![image](https://user-images.githubusercontent.com/16599929/225052542-8a75e1e4-7dbe-4caa-8f39-fcaa0dc61230.png) ![image](https://user-images.githubusercontent.com/16599929/225052749-2c46c1fb-a69f-428d-b37e-9860c9deafbc.png)
> 
> If ALL splits match the filter, the record is shown as as single line. e.g. set max amount to 70, the whole transaction matches the filter ![image](https://user-images.githubusercontent.com/16599929/225061778-80a8c932-819e-438d-9659-9afb19d96702.png) ![image](https://user-images.githubusercontent.com/16599929/225062021-b6b996bd-20ea-4c16-91cb-4232bedb1b61.png)
> 
> If a subset of the splits match, the record is expanded and only matching splits are shown each on a separate line with ID = TRANSID.<split index> e.g. Setting the amount filter to max of 50 now the whole transaction doesn't match, but the individual splits do: ![image](https://user-images.githubusercontent.com/16599929/225062970-560c1109-9794-4bc0-b968-1cb2b530b88a.png) ![image](https://user-images.githubusercontent.com/16599929/225068693-69a08b8a-ba6d-4be5-893e-a1c531e6d56e.png)
> 
> e.g. Only one split matches the selected category ![image](https://user-images.githubusercontent.com/16599929/225069061-0c3095d5-002c-405c-bae8-5448aaf6e6e1.png) ![image](https://user-images.githubusercontent.com/16599929/225069203-501a2604-5a53-4834-985e-49b11cb4ad34.png)
> 
> Double clicking on the record brings up the full transaction as normal.
> 
> Transaction report looks as it did previously (splits are always expanded) with the exception that they are now identified by the ID = TRANSID.<split index> and all filters apply to split lines individually ![image](https://user-images.githubusercontent.com/16599929/225071068-54141745-2edd-415c-af37-f61cdf09e494.png)
> 
> Clicking on the ID in the transaction report opens the full transaction as normal.

That's pretty cool, thank you!

**Comment by vomikan** [comment]
Now, if there is a split, the main notes are excluded from the search.

![image](https://user-images.githubusercontent.com/6836805/225265228-3e0bb389-79d5-49d1-8789-1308d5f9cf69.png)

**Comment by vomikan** [comment]
It would be necessary to do a search by notes and split, and combine the result using the OR method.

**Comment by n-stein** [comment]
Two small modifications needed: 

1. If splits are shown then selecting multiple rows from the same transaction duplicates the TRANSID in the m_selected_id vector. This causes copy/paste to create the same number of transactions as selected split rows instead of one single transaction. Need to only add unique TRANSID values to the vector.
2. If splits are shown and multiple rows are selected, the extra transaction data at the bottom of the checking panel is based on the full transaction amount, not the amount of the selected split.

Before:
![image](https://user-images.githubusercontent.com/16599929/226688012-c7b0e2c1-2563-4042-b390-96518ff32d22.png)

After:
![image](https://user-images.githubusercontent.com/16599929/226689445-ac3fc2ec-4332-4b17-b528-1dcf253583d6.png)

![image](https://user-images.githubusercontent.com/16599929/226689709-31df7580-6f90-4176-9f02-b59e7269f360.png)
