### ISSUE TITLE
Recurring transactions - attachments are disappear

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#5466]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

It was created a recurring transaction with an attached receipt. After executing all the transactions the receipt disappeared.
# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Reproduction steps:**
1. It created a new recurring transaction with 2 payments.
2. It added an attachment - a receipt as jpg.
3. Enter the next occurrence and pressed the OK button -> execute the transaction.
4. The transaction was executed.
_Comment: The executed transaction has no attachments, but the attachment is still present in the recurring transaction window._
5. Enter the next (the last) occurrence and pressed the OK button -> execute the transaction.
6.  The transaction was executed.
_Comment: The recurring transaction disappeared._ 
**Expected result:**
The receipt is attached to the first or the last executed transaction.
**Actual result:**
The attached file disappeared.
# Additional information 

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
PR #5493 moves attachments from the recurring transaction to the first executed transaction.
