### ISSUE TITLE
Deleted transactions should be excluded from Last Used date query

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5467]
MMEX version:
 - [x] 1.6.2 

See [https://forum.moneymanagerex.org/viewtopic.php?p=23647](https://forum.moneymanagerex.org/viewtopic.php?p=23647)

Deleted transactions are being included in the query to determine the 'Last Used' default date for new transactions.

**Expected result**

Only the transactions visible in the account should be used to determine the 'Last Used' default date for new transactions. Deleted transactions should be excluded.

**Comment by n-stein** [comment]
We ran into a similar issue before with the nulls. In the next DB update script perhaps we should set all the nulls to blanks and change tables.sql to specify the default for DELETEDTIME as blank. That way using DELETEDTIME(wxEmptyString) in a find_all will return all valid records.

**Comment by vomikan** [comment]
I wondered if this algorithm is correct?
It finds the maximum transaction date of the account, but less than or equal to today's date. It probably works well in most cases. But for those who start transactions not the future, it does not really help.
And the LASTUPDATEDTIME attribute also appeared. You can use it too.
