### ISSUE TITLE
1. Vertically center labels; 2. Homogenize having or not having colons `:` at the end of labels; 3. Homogenize strings for checkboxes to end with or without full stops `.`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5468]
MMEX version: 1.6.3-Beta.1 64-bit

Operating System: Linux Mint 21.1 Cinnamon

# Description of the bug

1. See blue box in the image below. Please **vertically** center labels. For example `Share Precision`.
2. See green box in the image below. Should the labels not end with a colon `:` to be consistent with the other labels? Or should other labels have a colon `:` added?
3. See red box in the image below. Should labels for checkboxes be consistent to always end with or never end with full stops `.`?

![image](https://user-images.githubusercontent.com/17465872/209535178-44ff00fa-2f68-45a6-be55-441b5ccc489c.png)

What do you think?

Thank you

**Comment by ovari** [comment]
Below are screenshots of Quicken 2004 which seems to follow [Microsoft Style Guide](https://www.microsoft.com/en-us/language/StyleGuides).

![QuickTabs](https://user-images.githubusercontent.com/17465872/209536100-f8a01137-f061-4b98-9c78-36d1b8a0b56f.png)

![General](https://user-images.githubusercontent.com/17465872/209536008-5f4eb47e-4ee1-4323-8d4e-e140368d17f3.png)

![Settings](https://user-images.githubusercontent.com/17465872/209536180-0746e513-f9f2-4a9d-ab3d-5d8448aff3a8.png)

![Startup](https://user-images.githubusercontent.com/17465872/209536220-f03f41b6-368d-4d36-8b49-e61980feb175.png)

**Comment by ovari** [comment]
Sorry for the misunderstanding. The green was correct, i.e. the colon `:` should be there. There should be a colon `:` in the blue.

Generally, every drop-down which **only** has a label before it should have a colon `:`.

In `General` tab
1. Change `User Name` to `User Name:`
2. Change `Base Currency` to `Base Currency:`
3. Change `Start Day` to `Start Day:`
4. Change `Start Month` to `Start Month:`

In `View Options` tab
1. Change `Accounts Visible` to `Accounts Visible:`
2. Change `Category Delimiter` to `Category Delimiter:`
3. Leave `Budget Offset (days):` unchanged
4. Leave `Start day of month for reporting:` unchanged
5. Change `Style Template` to `Style Template:`
6. Change `Theme Mode` to `Theme Mode:`
7. Change `HTML Scale Factor` to `HTML Scale Factor:`
8. Change `Font size` to `Font size:`
9. Change `Toolbar Icon Size` to `Toolbar Icon Size:`
10. Change `Navigation Icon Size` to `Navigation Icon Size:`
11. Change `Other Icon Size` to `Other Icon Size:`

In `Network` tab
1. Change `Url` to `URL:` (Should it be all capitalized?)
2. Change `GUID` to `GUID:`
3. Change `Proxy` to `Proxy:`
4. Should `Seconds` be changed to `Interval:`
5. Should `Seconds` be after the input box?
6. Should the `Stable`,`Unstable` dropdown be on the next line Change `` like LibreOffice does (as shown in the image below
![LibreOffice Options LibreOffice View](https://user-images.githubusercontent.com/17465872/210277481-eb1ce76f-e457-4911-8864-f639a9f0379b.png)
7. Should `from:` be added to the beginning of the `Stable`,`Unstable` dropdown

In `Others` tab
1. Change `Share precision` to `Share precision:`
13. Change `Max Files` to `Max Files:`
14. Change `Days to retain deleted transactions` to `Days to retain deleted transactions:`
15. Change `Delimiter` to `Delimiter:`
16. Change `` to 

![image](https://user-images.githubusercontent.com/17465872/210276409-4b3f01b0-3b41-4c8e-b207-f5a5eae39c03.png)

**Comment by vomikan** [comment]
I understand that it is necessary to strive for standardization. However, I don't like that adding a colon will require an additional load for translators and finding all the phrases where you need to add a colon.

Example. Do I need a colon here too?
![image](https://user-images.githubusercontent.com/6836805/210401115-d4e3c792-89c6-4464-9d3b-467c8956a86b.png)

**Comment by vomikan** [comment]
Related issue:
https://github.com/moneymanagerex/moneymanagerex/issues/4334

**Comment by tactilis** [comment]
@vomikan
> Example. Do I need a colon here too?  (Transaction Filter)

The answer is no you don't because based on what @ovari states:

"Generally, every drop-down [or entry field] which **_only_** has a label before it should have a colon"

The dropdowns on the Transaction Filter dialog do not _only_ have a label before them. 

However, I'm really not concerned about having colons after labels and neither are some other high profile apps, for example, Firefox

![image](https://user-images.githubusercontent.com/4060092/210834784-651f9ebf-31f8-4c3b-bc6e-556c42c3b654.png)


<br>
<br>

And I think our Transaction dialog, for example, is perfectly clear without colons

![image](https://user-images.githubusercontent.com/4060092/210834992-860fb8c5-5cb2-4380-bc61-ae67294e4306.png)
