### ISSUE TITLE
Enter button to save transation

### ISSUE THREAD

**Issue by alankeyes** [moneymanagerex/moneymanagerex#5471]
# Description of the feature

First time poster here--thank you so much to the devs, I love this software!

I would love to be able to hit the [Enter] key instead of having to click or tab over to OK when entering a new transaction, as that would speed up keyboard-only workflow considerably.  I am running 1.6.2 (and have used several earlier versions) on Linux Mint 21 (Ubuntu 22.04) with Cinnamon.

# Use cases

When entering a new transaction ([Ctrl]+N), use [Tab] to step through a few fields, entering data, then hit [Enter] in "Payee" or "Category" field; this has no effect.  Have to press [Tab] 9 more times from "Category" before "OK" is selected for action when hitting [Enter].

**Comment by vomikan** [comment]
Could you try Alt+O ?

**Comment by rmelillo76** [comment]
#5314

**Comment by alankeyes** [comment]
Oh excellent I hadn't thought of Alt+O, that works great!  Thanks so much!  And sorry for the duplicate--I hadn't noticed that when I looked through the existing list.
