### ISSUE TITLE
New transaction has empty date

### ISSUE THREAD

**Issue by alankeyes** [moneymanagerex/moneymanagerex#5472]
MMEX version:
 - [ ] 1.6.0
 - [x] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

When creating the first new transaction after opening the software, the date field is blank/empty (instead of pre-populated with today's date) unless another transaction is selected first.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Open a new instance of MMEX.
2. Select an account
3. Click New for a new transaction

Expected result:
New transaction dialog opens with date field selected and auto-/pre-populated with today's date.

Actual result:
New transaction dialog opens with the date field empty and not selected.

# Additional information
If the step "2b. Select a transaction" were added, this issue does not occur.

**Comment by vomikan** [comment]
Could you try to change this settins:
![image](https://user-images.githubusercontent.com/6836805/211639185-653cdcb5-abb1-413a-a197-c10f60d83c01.png)

After that, the date should be set to the same value as the last transaction.
Is it working?

**Comment by tactilis** [comment]
@vomikan
> After that, the date should be set to the same value as the last transaction.

That statement is true but, I think, not relevant to the problem that @alankeyes is reporting.

If the Default Date option is set to None then, on Windows at least, the Date field in a new transaction is populated with today's date; exactly as Alan expects to happen on Linux.

**Comment by vomikan** [comment]
I don't understand the problem and I don't have a Linux computer. So I'm leaving this problem.

**Comment by n-stein** [comment]
@vomikan you fixed this yesterday in #5523 as part of the fix for #5467

**Comment by alankeyes** [comment]
Sorry for my delayed response--changing the Default Date setting to Last Used unfortunately has no effect, but I'm glad to hear that it has been fixed as a side effect of another fix!  Looking forward to 1.6.3/4 so I can try it out.  Thanks so much for everyone's help!
