### ISSUE TITLE
Budget Performance report is doubling all estimated values

### ISSUE THREAD

**Issue by i-embree** [moneymanagerex/moneymanagerex#5473]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The Budget Performance report is doubling all of the estimated values.  (Actual values on the report appear to not be impacted by this bug.)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

- Set an non-zero estimate value for any category for a given budget year
- Open the 'Budget Performance' report and set the 'Budget' dropdown to the same year that contains the estimate value

Expected result:

Budget Performance report's 'Estimated' value matches budget page's 'Estimated' value

Actual result:

Budget Performance report's 'Estimated' value is double what the budget page has as its 'Estimated' value

# Additional Information

[Example screenshots]

Budget page:
<img width="381" alt="Screenshot 2022-12-29 012134" src="https://user-images.githubusercontent.com/115386454/209914362-2905c443-24f9-46d2-a394-8018925c9e59.png">
Budget Performance report:
<img width="729" alt="Screenshot 2022-12-29 012709" src="https://user-images.githubusercontent.com/115386454/209914364-ad0baf7f-a0b4-42f2-b507-e322fe2cb52d.png">

**Comment by n-stein** [comment]
I can't reproduce this, everything looks OK to me:
![image](https://user-images.githubusercontent.com/16599929/210418796-45e33b44-f579-4267-9228-15ebadd73454.png)
![image](https://user-images.githubusercontent.com/16599929/210418869-3b52de16-76e8-42b1-a079-e181d5140d6a.png)


Guessing you have both a yearly budget and a monthly budget. Does ticking this box help?
![image](https://user-images.githubusercontent.com/16599929/210418322-90fa7f6b-b639-48da-8439-48c8ae791b3d.png)

**Comment by i-embree** [comment]
Hi @n-stein

Yes, I do have both yearly and monthly budgets.  I usually create a yearly budget and then generate monthly budgets based on it.

I was not aware of what that checkbox meant, and I have not had it active with a checkmark before.  Now that I have it checked, the estimate doubling is no longer an issue.  User error... smh...

Thank you for your help!
