### ISSUE TITLE
QIF ability to import/export field "E" of split lines notes 

### ISSUE THREAD

**Issue by speedygh** [moneymanagerex/moneymanagerex#5474]
- It will be great if you could improve the QIF import procedure, in order to use QIF "E" field (split memo description) to fill in the split lines notes, when importing a QIF file.

- The same, when exporting an account to a QIF file, it would be great if you could export also the split lines notes using the "E" field.

D30/12'2022
**MEntire Entry Memo**
T-1000.00
PPayee 1
LCategoryX:SubCategory1
SCategoryX:SubCategory1
**ELine 1 Memo**
$-800.00
SCategoryX:SubCategory2
**ELine 2 Memo**
$-150.00
SCategoryX:SubCategory3
**ELine 3 Memo**
$-50.00
^

**Comment by vomikan** [comment]
Question: Can there be no notes for the first (or any but the last) field?

**Comment by speedygh** [comment]
You may have the entry’s header note using field “MEntire Entry Memo”, so, I suppose that all split lines notes can be omitted. As I have seen you have solved it, so it’s ok.

 

Thank you!
