### ISSUE TITLE
Prevent setting a Category on Transfers

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#548]
I am wondering what is the view on this issue.
Currently it is possible to assign a Category on Transfers. My suggestion is to disable category selection on these transaction but am wondering what are the benefits of having it as is currently.
Most other systems will simply use the destination account in the Category field so the question is do we need to have both? 
Selecting the Transfer transaction type will, by default, select Transfer as a category. I believe this should be mandatory and the user should not be allowed to modify it.
Are there any reports that display transfers that have a Category assigned? Any other relations?

**Comment by stef145g** [comment]
Personally, I think this proposal is a bad move.

There is a great benefit to enable the user to set a category for transfers. It gives greater scope to track income and expenses from different sources. From a savings account, we could transfer money to several other accounts for different reasons. The category provides a reason for the transfer. We can now filter the category to see how much we have transferred to any account for our particular reason. Just having a single category: Transfer is not enough information for further analysis.

Allowing categories on transfer type transactions is the advantage that MMEX has over other systems.

I use this feature extensively. I can transfer money to many accounts for different reasons and from my source account see exactly why I am transferring the money and to where.

**Comment by MisterY** [comment]
I see your point, Stefano. In principle, I also agree that more information is better, as opposite to less information. One thing that still somehow does not fit for me is the following. As Transfers are simply moving money between one's own accounts, and are neither Deposits nor Withdrawals so there is no in/out-flow of money from the total balance, I do not understand why they would need to be categorized.

For example, if we buy some groceries and spend $10, and then get some money from an ATM to cover for this purchase, would the transfer be categorized as Groceries? Would not this, then, show that Groceries expense was $20 instead of $10? I would expect that the inflows and outflows have categories so I know for which purpose the money flows in and out. But transferring from a bank account to cash is hardly worth categorizing. Since you are using this scenario actively, I would appreciate if you could give me an example. I still fail to be able to imagine a case where I would want to see categorized transfers in the reports.
Just for clarification, I believe that my notion of categories comes from years of using Microsoft Money and Quicken and this concept has been shaped by them. In that regard, you are correct that MMEX would have an edge by providing extra information. It is just that I do not see much benefit in it.

The reason for posting this issue is that, in Android app in the list of transactions, we show [Transfer] instead of a category name so that transfers would be clearly identifiable and distinguished from deposits and withdrawals. Hence we completely ignore the Category. It is also not used in the reports in case of transfers, anyway. To make things simpler, I've hidden the Category field if the type of transaction is switched to Transfer so that it does not create confusion. 
Some users are now asking about the change and I was wondering what is the view on the whole concept. Appreciate the clarifications.

**Comment by vomikan** [comment]
We can sutisfy this demand but in future will have others with revert this feature. I suggest to do nothing.

**Comment by vomikan** [comment]
I leave it as is.

**Comment by MisterY** [comment]
Just had a brief discussion (again) about categories and transfers. Reading the comments here, I can see that using categories on transfer transactions is basically trying to simulate budgeting. Categories are usually used to track income and expenses, money coming into or leaving our accounts. Therefore the cash flow can be monitored.
Trying to track the **intention** is something completely different. This is what budgeting is for. In a budget we can see how much money have we dedicated to a particular purpose and how much was really used (or received). Assigning categories to transfers dilutes the real financial situation.
In any case, it is OK some users want to use this functionality and create the systems that work for them. The important thing to keep in mind is to allow users a choice.

**Comment by vomikan** [comment]
I can add an option to skip category for transfers. But a lot of users on PC used outdated versoin of app. They lost a compability.
I recommend to use ' Transfer '  category  by default.

**Comment by slodki** [comment]
We should introduce an option blocking the use of categories for transfers because the current behavior is not intuitive for new users - see #1971
