### ISSUE TITLE
Report: Income vs Expenses Monthly - wrong column title

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#5480]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

This is a very minor GUI inaccuracy.
The first column of the report is called "Date" while actually, it is not the date, just Year and Month.

![image](https://user-images.githubusercontent.com/83161661/210165589-f3bc15ba-42c8-4a83-83ca-5d336404468d.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
[https://dictionary.cambridge.org/dictionary/english/date](https://dictionary.cambridge.org/dictionary/english/date)

**date** noun 

1. a numbered day in a month, often given with a combination of the name of the day, the month, and the year

2. a particular year

3. a month and a year

Using `Date` as the heading seems OK to me.
