### ISSUE TITLE
Shared category across databases

### ISSUE THREAD

**Issue by bwgjoseph** [moneymanagerex/moneymanagerex#5484]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I just created a new database, after creating various new accounts and so on. I noticed that my category show the list from the other database. 

Is there any way to not share the list if it is meant to?

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
Each database probably should display its own set of list

Actual result:
Each database category are shared

**Comment by tactilis** [comment]
Each database that you open _does_ display its own set of categories.

This is because the categories are stored in the .mmb database file along with your accounts, transactions, payees, etc.

The only way that you could have the same categories in your 'new' database is to have somehow created a copy of the old .mmb file and opened that as the 'new' database.

Did you perhaps do a File | Save Database As... ?

If you do File | New Database... then you will have a 'blank' database and the categories will simply be the default set that come with MMEX.

**Comment by bwgjoseph** [comment]
No, I created new database using `Create a new Database` option here

![image](https://user-images.githubusercontent.com/37484538/210222520-6214666e-f1f1-411a-983c-d861f078d128.png)

And both my database are encrypted version.

**Comment by tactilis** [comment]
I cannot find a sequence of actions that could lead to the situation you describe with user-added categories from your old database appearing in a new database.

Database files, whether unencrypted (.mmb) or encrypted (.emb) are completely separate. They do not share categories (or anything else).

Please could you 

1. Create a New Database.  Name the file AAA.mmb
2. Save Database As...  Name it AAA with Save as type set to .emb to encrypt it.
3. Add a new category or a subcategory.

4. Create a New Database.  Name the file BBB.mmb
5. Save Database As...  Name it BBB with Save as type set to .emb to encrypt it.
6. Confirm that the categories in BBB do not include those entered at step 3.

**Comment by bwgjoseph** [comment]
Sorry, I went to take a closer look, and realize that I was mistaken.

Those are the default ones created by the app, as the list was quite similar, I didn't notice the exact list, and I didn't realize that the app creates some defaults as well.

My bad!
