### ISSUE TITLE
Forecast Report bug due to multiple currencies

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#5489]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The Forecast Report shows the Deposit and Withdrawal time series in absolute values, and not in the main currency. Basically there is no difference is the currency in JPY, INR, USD or GBP, and only the values are plotted on the time series. 

For example, see below the unusually high peaks around 15 Dec and Jan, in expenses. This is happening because I have been spending in sub-currencies and not the main currency, while my income is coming-in in main currency.
![image](https://user-images.githubusercontent.com/83648377/210304886-60419cfe-6a3b-43a8-bb34-77e402ccc444.png)

**Comment by tactilis** [comment]
@h-vijayakumaran Are you saying that the transactions in JPY, INR, USD or GBP are not being converted to the equivalent values in your main currency before being plotted?

**Comment by n-stein** [comment]
This is indeed the case. I have fixed it in PR #5494.
