### ISSUE TITLE
impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC??

### ISSUE THREAD

**Issue by Cyternay** [moneymanagerex/moneymanagerex#5490]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Since this morning I can't open MMX anymore, the logo appear on my toolbar but no soft open.
I tried to upload a last version 1.6.2 but when I ask to open my database it doesn't work

I am french and if i translate the meesage:
Update MMEX database failed to the version 15
Retaure the BdD from the automatic saving creat before update and retry or contact MMEX support
SQL logic error[1]: no such table: REPORT_V1

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
How to solve this? all my account are their and can't open it suddenly

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@Cyternay What version of MMEX were you using prior to upgrading to 1.6.2?

**Comment by Cyternay** [comment]
Dear Martin, It was a version from August 2011, that was working till this last Week end a this Morning, not opening anymore.Shall I uninstall all and reinstall new version, as update seems not to work.Issue is to re use my database where all data are in regards Envoyé à partir de Courrier pour Windows De : MartinEnvoyé le :mardi 3 janvier 2023 09:51À : moneymanagerex/moneymanagerexCc : Cyternay; MentionObjet :Re: [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue ***@***.*** What version of MMEX were you using prior to upgrading to 1.6.2?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Cyternay** [comment]
I found that it was this verion Envoyé à partir de Courrier pour Windows De : Cyrille OrangeEnvoyé le :mardi 3 janvier 2023 12:28À : moneymanagerex/moneymanagerex; moneymanagerex/moneymanagerexCc : MentionObjet :RE : [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue #5490) Dear Martin, It was a version from August 2011, that was working till this last Week end a this Morning, not opening anymore.Shall I uninstall all and reinstall new version, as update seems not to work.Issue is to re use my database where all data are in regards Envoyé à partir de Courrier pour Windows De : MartinEnvoyé le :mardi 3 janvier 2023 09:51À : moneymanagerex/moneymanagerexCc : Cyternay; MentionObjet :Re: [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue ***@***.*** What version of MMEX were you using prior to upgrading to 1.6.2?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Cyternay** [comment]
I just found back the source file, uninstall all and reinstall this former version and all works again. Do you recommend to install the last version online or shall I stay on this one ? Envoyé à partir de Courrier pour Windows De : Cyrille OrangeEnvoyé le :mardi 3 janvier 2023 12:36À : moneymanagerex/moneymanagerex; moneymanagerex/moneymanagerexCc : MentionObjet :RE : [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue #5490) I found that it was this verion Envoyé à partir de Courrier pour Windows De : Cyrille OrangeEnvoyé le :mardi 3 janvier 2023 12:28À : moneymanagerex/moneymanagerex; moneymanagerex/moneymanagerexCc : MentionObjet :RE : [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue #5490) Dear Martin, It was a version from August 2011, that was working till this last Week end a this Morning, not opening anymore.Shall I uninstall all and reinstall new version, as update seems not to work.Issue is to re use my database where all data are in regards Envoyé à partir de Courrier pour Windows De : MartinEnvoyé le :mardi 3 janvier 2023 09:51À : moneymanagerex/moneymanagerexCc : Cyternay; MentionObjet :Re: [moneymanagerex/moneymanagerex] impossible to open MMEx since this morning?? 1.6.2 dowloaded again but not opening on PC?? (Issue ***@***.*** What version of MMEX were you using prior to upgrading to 1.6.2?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tactilis** [comment]
Please could you go here [https://github.com/moneymanagerex/moneymanagerex/issues/5490](https://github.com/moneymanagerex/moneymanagerex/issues/5490) and reply directly in github.

If you reply via email, the formatting can get messed up and any attachments (screenshots, etc) get stripped off.

**Comment by renato-mmex** [comment]
The solution was: https://forum.moneymanagerex.org/viewtopic.php?t=10776
can be closed
