### ISSUE TITLE
Change default encoding from `windows-1251` to `utf-8`?

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5501]
Under the `Running on:` section in the image below, the version says: `(windows-1251)`.

It is possible to changed the default `windows-1251` to `utf-8`?

Perhaps it is `ISO-8859-1`?
https://www.w3schools.com/charsets/ref_html_utf8.asp

Benefits:
1. People with Windows wouldn't need to activate the beta setting for UTF-8;
2. Future-proof MMEX.

![image](https://user-images.githubusercontent.com/17465872/211146094-1cbf3fc7-9d66-43b8-b14e-82e18c31991f.png)

What do you think?

Thank you

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/5462

![](https://user-images.githubusercontent.com/6836805/210228512-094e7316-44b0-433d-83f4-674739d43724.png)
