### ISSUE TITLE
Keep a history of past transaction report filters

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#5512]
# Description of the feature

If would be useful if the application remembered previous transaction report filters -- similar to how a browser history allows you to reopen a tab after you have closed it.

# Use cases

I sometimes need to run the same report filter multiple times. I click on a transaction in the report, edit it in some way (e.g., to split the transaction into multiple categories) and save it. Now I want to edit another transaction from the report, but there is no way (that I know of) to reopen the transaction report screen. So I have to reapply all filters, which is time consuming. I am aware I could save this filter, but it is something I only need _now_, not in the future.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/3752

**Comment by n-stein** [comment]
I don't really want to get into storing a long history of transaction filters, but there is a quick and easy way to store the last used filter. We could make it appear at the top of the settings list like this:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/01ad0bf6-f74d-4b78-a3ac-76e8adb5b344)

Thoughts?

**Comment by n-stein** [comment]
We could make it store the last used filter that isn't already saved as a preset (since those filter settings are already easily accessed via the named preset).

**Comment by n-stein** [comment]
I have added a "Last Used" preset to both the "Transaction Report" and the "All Transactions" panel. These store the last _unsaved_ settings used in their respective dialogs. Values are stored independently, i.e. the "Transaction Report" settings do not change the last used "All Transactions" settings and vice versa.
