### ISSUE TITLE
Link to transaction details of category and all its nested categories

### ISSUE THREAD

**Issue by nuvitong** [moneymanagerex/moneymanagerex#5514]
# Description of the feature

In custom reports I can link to _transaction details_ report with a given category using `<a href="viewtrans:<categId>" target="_blank">Category</a>`

![grafik](https://user-images.githubusercontent.com/7220672/211402440-2269a56c-db19-45fc-b517-79b155612bbc.png)

The linked _transaction details_ report contains all transactions, which the selected category is directly assigned to. 

I would like to link to a report which contains transactions not only assigned to the selected category but also to any of the nested categories of the selected category. 

Is this possible with the current version of MMEX (1.6.2)?

# Use cases

The custom BudgetMonitoring report (https://github.com/moneymanagerex/general-reports/tree/master/packages/Budget/BudgetMonitoring) groups the amounts by the highest level of each category. In this report I would like to link to the _transaction details_ report, which then contains all transactions of the given category and all of its categories (within the selected time range).

Thanks in advance.

**Comment by n-stein** [comment]
Use the :-2 modifier

<a href=\"viewtrans:13:-2\" target=\"_blank\">Income</a>

**Comment by nuvitong** [comment]
Thanks for the hint. I wasn't aware of that. Using the `:-2` modifier works so far, that subcategories are contained in the `transaction details` report as well.

Is there a chance that the selected date period (using `'&begin_date'` and `'&end_date'` in the sql) is also evaluated. This seems currently not to work.

![grafik](https://user-images.githubusercontent.com/7220672/211653190-7ddd3c7b-849e-45be-9f7f-4315cad68e34.png)

**Comment by nuvitong** [comment]
Hi,

the evaluation of `&begin_date` and `&end_date` in my custom report is working fine, indeed. But when I follow the link to the _transaction details_ report, this contains all transactions of the selected category independent of the selected date range.

I would assume, that the selected date range of my custom report is also evaluated within the linked _transaction details_ report.

**Comment by n-stein** [comment]
Ahh, I see what you mean now. I just opened PR #5548 which fixes this.

**Comment by n-stein** [comment]
I'm getting a debug assertion fail when jumping to a transaction report from a report with no date filter (such as the budget performance report). Will push a fix.

**Comment by nuvitong** [comment]
Thanks for the fix. I'm looking forward to checking it in the next version.

**Comment by nuvitong** [comment]
Hi. This issue is solved from my point of view and could be closed.
