### ISSUE TITLE
Layout of About dialog

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5516]
MMEX version: 1.6.3 Beta.2 Jan 9 2023 19:46:40

Operating System: GNU/Linux 

# Description of the bug

1. Should the 2 newline be only 1?
2. Should `Running on:` be before the dot point on a separate line?

![image](https://user-images.githubusercontent.com/17465872/211424229-e46b2445-e55e-43ed-826d-7fca5086ebb3.png)

Is the bug reproducible? Always 

Thank you

**Comment by ovari** [comment]
Should `Version: 1.6.3-Beta.2 64-bit` start with a dot `*`?

**Comment by ovari** [comment]
Can `64-bit` please be translatable?

In Hungarian, `64-bit` is translated as `64 bites`:
1. The hyphen `-` is replaced with a space ` ` (or a non-breaking space)
2. `es` is appended to `bit`

![image](https://user-images.githubusercontent.com/17465872/211424682-6ce92471-8d6a-467b-9b58-5a7364ee37ab.png)

https://hu.wikipedia.org/wiki/64_bites_architekt%C3%BAra

Thank you

**Comment by ovari** [comment]
Still seems to be two consecutive newlines.

![image](https://user-images.githubusercontent.com/17465872/212003504-c9879772-8ae2-4fd7-b0fa-94b886e86293.png)

Thank you

**Comment by ovari** [comment]
Sorry, don't know how to re-open this issue.

**Comment by ovari** [comment]
Should `* Linux Mint 21.1 "vera"` be on a newline?

![image](https://user-images.githubusercontent.com/17465872/212004658-d8e35a86-98a5-43bc-9765-83962d608355.png)

Thank you

**Comment by ovari** [comment]
Should the trailing newline be removed?

![image](https://user-images.githubusercontent.com/17465872/212004833-50c53a75-73f7-42a0-8417-7a693242d855.png)

Thank you

**Comment by renato-mmex** [comment]
when i open over it is always displayed too small, it was not like that before.
.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/76920138/212039526-0e81cd49-cc2b-4976-b04e-f5ba971c42ac.png">

**Comment by renato-mmex** [comment]
unfortunately no improvement with the latest version
.
<img width="201" alt="image" src="https://user-images.githubusercontent.com/76920138/212047969-a0d20edd-2238-484f-b19a-4922cb1cdbf2.png">

**Comment by vomikan** [comment]
> unfortunately no improvement with the latest version

Unfortunately, I can't reproduce it and have no idea what else can be done.
We can make changes to remember the size of the window after the resizing.

**Comment by renato-mmex** [comment]
Does the screen resolution affect ?
.
<img width="252" alt="image" src="https://user-images.githubusercontent.com/76920138/212055755-8ea655f2-fb7e-4289-9a3c-7ddfc08bd844.png">

**Comment by vomikan** [comment]
> Does the screen resolution affect ? . <img alt="image" width="252" src="https://user-images.githubusercontent.com/76920138/212055755-8ea655f2-fb7e-4289-9a3c-7ddfc08bd844.png">

Very possible. 
Easy to check. Set the virtual size in the monitor settings to 1980*1080 and restart the application.
This will help clarify the cause of the problem.

**Comment by renato-mmex** [comment]
yes,yes, it is so, I start MMEX on the other monitor with 1080x1920 then the About window is displayed larger.
But the resolution is also displayed here with 3840x2160, which is the size of the main monitor (1).
.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/76920138/212114368-2f60de9b-063b-4d0b-a4ba-24ec48c63584.png">
