### ISSUE TITLE
LASTUPDATEDTIME not used

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5521]
It's time to think about where to add the value of the current time, so that both when importing and when creating/changing transactions, it is recorded in the database.

Not enough:
void Model_Checking::putDataToTransaction(Data *r, const Data &data)
    LASTUPDATEDTIME  = wxDateTime::Now().FormatISOCombined();

**Comment by vomikan** [comment]
@n-stein Your experience could be useful in solving this problem.

**Comment by n-stein** [comment]
Initial thought is to simply overload Model_Checking::save the same way we do Model_Checking::remove

```
bool Model_Checking::save(Data* r)
{
  r->LASTUPDATEDTIME = wxDateTime::Now().ToUTC().FormatISOCombined();
  return this->save(r, db_);
}
```

Works well for both create and update.

**Comment by vomikan** [comment]
In my case, this function works. It was not redefined.
PS Windows 10
```
    /** Save the Data record memory instance to the database. */
    int save(typename DB_TABLE::Data* r)
    {
        r->save(this->db_);
        return r->id();
    }
```

**Comment by vomikan** [comment]
I also think that.Touch() is unnecessary in this case.

![image](https://user-images.githubusercontent.com/6836805/211923273-5e6cac5a-5772-45c5-89f9-804d197f0334.png)

![image](https://user-images.githubusercontent.com/6836805/211923228-821b8965-6962-4674-8541-fc59c3b94eae.png)

**Comment by vomikan** [comment]
It seems to be working. It was necessary to completely rebuild the project.

**Comment by n-stein** [comment]
I used ToUTC() to store in the same format as DELETEDTIME which is always stored in UTC regardless of the user's local timezone.

**Comment by vomikan** [comment]
I have redefined 3 functions. Now, when importing, the time of the transaction insertion is also indicated.
```
    int save(Data* r);
    int save(std::vector<Data>& rows);
    int save(std::vector<Data*>& rows);
```

**Comment by n-stein** [comment]
Currently simply opening the transaction dialog and pressing "Ok" updates the LASTUPDATEDTIME since save() is called.

What do you think of adding operator overloads of == and != in the DB_Table_*_V1.h headers which compare two data records field-wise? Then during save we only update LASTUPDATEDTIME if oldRecord != newRecord (meaning at least one field is different).

**Comment by tactilis** [comment]
> Currently simply opening the transaction dialog and pressing "Ok" updates the LASTUPDATEDTIME since save() is called.

Eek! Definitely need to do something about that.

Lots of people routinely click OK rather than Cancel as a means of closing the dialog when all they did was look at the transaction data.

**Comment by vomikan** [comment]
There are several ways to solve this problem.
In the dialog box itself, track whether there have been data changes.
You can close the OK button if the data has not changed.
In the saving procedure, make a comparison with the available data in the database.

I also found that the OK button is available for deleted transactions and clicking on it calls the save function with a change in the update time.

![image](https://user-images.githubusercontent.com/6836805/212036546-70dfca73-6be8-4a81-b8b4-ca9690b11e8f.png)

**Comment by vomikan** [comment]
In the future, it would be nice to display information such as the update time (and the deletion time) somewhere.

![lastupdatedtime](https://user-images.githubusercontent.com/6836805/212037352-9677e62d-3733-4fa0-b03e-cc8f6044daf0.png)

**Comment by vomikan** [comment]
> Currently simply opening the transaction dialog and pressing "Ok" updates the LASTUPDATEDTIME since save() is called.
> 
> What do you think of adding operator overloads of == and != in the DB_Table_*_V1.h headers which compare two data records field-wise? Then during save we only update LASTUPDATEDTIME if oldRecord != newRecord (meaning at least one field is different).

Do it in any convenient way, please.
I just voiced a few ideas for general information.

**Comment by vomikan** [comment]
Now the variable always takes a value equal to 1.
```    m_trx_data.TRANSID = Model_Checking::instance().save(r);```

**Comment by n-stein** [comment]
Ok. #5534 updates the LASTUPDATEDTIME only if at least one field on the record has changed. 

To do this I added an `equals(Data*r)` method to directly compare two database records for equality field-wise as well as a `read(int id)` method to read an existing record directly from the database (bypassing the cache).

**Comment by n-stein** [comment]
Thoughts on whether deletion/restoration should update the LASTUPDATEDTIME? Technically the database record is being updated, but I can see the argument against it since we have a separate DELETEDTIME and the overall goal of restoration is to put the record back in its original state.

**Comment by tactilis** [comment]
> the overall goal of restoration is to put the record back in its original state.

Exactly that. Delete/Restore should be a zero-change round-trip.

I agree that, based on our specific implementation, the transaction record _is_ updated in the database when deleting and restoring but you can imagine other implementations where the indication that a transaction has been deleted is meta-data that is not part of the transaction record. In this case there would be no question of changing the transaction LASTUPDATEDTIME.

**Comment by vomikan** [comment]
I am sure that if the transaction was deleted, then restored, then the update time should be changed. The original time in this case is not informative.

**Comment by vomikan** [comment]
There is one unaccounted moment. I'm changing a customized field and that's it. I'm saving it. The transaction modification time does not change.
It can be the same with the attached files.

![image](https://user-images.githubusercontent.com/6836805/212291637-3c084b56-cf9b-407e-92fb-dff016b656a0.png)

**Comment by vomikan** [comment]
> If you delete a file to the Recycle Bin in Windows and then Restore it, would you expect the Modified date (i.e equivalent to our LASTUPDATETIME) _of the file_ to change?

We checked it really is.
Even the great ones can be wrong))

In fact, I can remain neutral on this issue.

**Comment by n-stein** [comment]
Easy enough to keep the deletion/restoration from changing the time:

```
if (!oldData || (!oldData->equals(r) && oldData->DELETEDTIME.IsEmpty() && r->DELETEDTIME.IsEmpty()))
        r->LASTUPDATEDTIME = wxDateTime::Now().ToUTC().FormatISOCombined();
```

I notice changing the category on a splittransaction doesn't update it either. I suspect there will be similar issues with updating a stock transaction if the total amount doesn't change.

**Comment by tactilis** [comment]
> There is one unaccounted moment. I'm changing a customized field and that's it. I'm saving it. The transaction modification time does not change. It can be the same with the attached files.

Good spot @vomikan.


Can I check that the LASTUPDATETIME _is_ updated when the following actions are performed while displaying the transaction list:

1. Pressing CTRL+0..CTRL+7 to change the transaction colour.
2. Pressing the paperclip icon in the button bar at the bottom of the list to directly open the Organize Attachments dialog _and then_ making a change via that dialog.
3. Right-clicking a transaction and selecting `Mark as` and then changing the transaction status.
4. Pressing any of the shortcut keys U R V F D to change the status.

**Comment by n-stein** [comment]
That should take care of custom fields, shareinfo changes, and attachments.

**Comment by n-stein** [comment]
Do we want to add "Last Updated" to the checking panel as we do "Deleted On", or perhaps make it available but hidden by default?

**Comment by vomikan** [comment]
> Do we want to add "Last Updated" to the checking panel as we do "Deleted On", or perhaps make it available but hidden by default?

Do you mean another column at the end of the checking account view?

![image](https://user-images.githubusercontent.com/6836805/212431389-c448e7e6-fb0c-40c9-b2ae-25c07b4e2297.png)

**Comment by tactilis** [comment]
> Do you mean another column at the end of the checking account view?

Yes, that's what @n-stein means.

I'd say make it available but hidden by default.
I think it's going to be the most useful for people who import transactions (i.e. for a subset of MMEX users) as you can then see easily which transactions have just been imported.

**Comment by vomikan** [comment]
it is not necessary to hide this field. it's already at the end, its t is practically not visible. And later you will have to explain how to unhide it.

**Comment by tactilis** [comment]
> ...it is practically not visible.  And later you will have to explain how to unhide it.

OK. You've convinced me.

I was considering the people who have Custom fields displayed in the transaction list and how the sudden appearance of this new field would affect them. However, users with CFs are in the minority, so we can explain to them how to _hide_ the field if they don't like it.

**Comment by vomikan** [comment]
If we observe stability in this implementation, then we can close the case. Now is the right time for the release.

**Comment by n-stein** [comment]
Added to end of account view.
