### ISSUE TITLE
wxTimePickerCtrl for GRM

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5530]
Revision for timing in reports.

![image](https://user-images.githubusercontent.com/6836805/212128122-a30f83b3-627c-4375-a28e-482f29dab13b.png)

The following syntax can be used in SQL queries:
```
select * from CHECKINGACCOUNT_V1 c
where c.LASTUPDATEDTIME >='&single_date'||'T'||'&single_time'
```

**Comment by vomikan** [comment]
It should be noted here that the time stored in the UTC time zone is not very practical.

![image](https://user-images.githubusercontent.com/6836805/212131531-162a1dce-f272-4191-bcdb-8dfa18fb133a.png)

**Comment by n-stein** [comment]
Try this:

```
select * from CHECKINGACCOUNT_V1 c
where c.LASTUPDATEDTIME >= datetime('&single_date'||'T'||'&single_time', 'UTC');
```

**Comment by vomikan** [comment]
> You can just convert to UTC for the database read:

Thanks for pointing this out.

But it's about something else. Data is saved to the database without conversion to UTC.

**Comment by vomikan** [comment]
> You can just convert to UTC for the database read:
> 
> ```
> select * from CHECKINGACCOUNT_V1 c
> where c.LASTUPDATEDTIME >= datetime('&single_date'||'T'||'&single_time', 'UTC');
> ```

This leads me to wonder if it is necessary in this line ```.ToUTC()``` ?
```value = time->GetValue().ToUTC().FormatISOTime();```

**Comment by vomikan** [comment]
Transformations have to be done in 2 stages.

```
select c.* from CHECKINGACCOUNT_V1 c
where c.LASTUPDATEDTIME >= strftime('%Y-%m-%dT%H:%M:%S', datetime('&single_date'||'T'||'&single_time', 'UTC')) 
```

**Comment by vomikan** [comment]
```
select c.* from CHECKINGACCOUNT_V1 c
where c.LASTUPDATEDTIME >= strftime('%Y-%m-%dT%H:%M:%S', datetime('&single_date'||'T'||'&single_time', 'UTC')) 
```

**Comment by vomikan** [comment]
Invalid time value in the test mode of the editor.

![image](https://user-images.githubusercontent.com/6836805/212299231-99873866-0240-4e6f-b2e8-41ca03dafff1.png)
