### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5533]
https://github.com/moneymanagerex/moneymanagerex/issues/5530#issuecomment-1380725809

The time values in the CHECKINGACCOUNT_V1 table are stored in UTC.

And the customized values are saved 1:1

**Comment by n-stein** [comment]
I commented on the other issue, but SQLite can do the UTC conversion for you:

```
select * from CHECKINGACCOUNT_V1 c
where c.LASTUPDATEDTIME >= datetime('&single_date'||'T'||'&single_time', 'UTC');
```
