### ISSUE TITLE
Edit Account images

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5541]
Has this menu always looked like this?
It seems there was some text.

![image](https://user-images.githubusercontent.com/6836805/212386816-87f7740b-0545-49a8-8d1f-fc612019efcd.png)

**Comment by whalley** [comment]
For me...
![CleanShot 2023-01-13 at 19 17 00](https://user-images.githubusercontent.com/487345/212400759-9e4ad0e8-1d9d-43b2-81f4-d5f5e15303ce.png)

**Comment by vomikan** [comment]
Interestingly, the same color selection menu works in principle.

![image](https://user-images.githubusercontent.com/6836805/212415527-3ff29c0e-0e81-4f24-8caf-0a6f3c51d2a9.png)

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/212415867-678e4335-0e47-4509-a7c2-8b3ff711298a.png)
