### ISSUE TITLE
Additional menu for new transactions

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5544]
![image](https://user-images.githubusercontent.com/6836805/212411344-082ded90-c4ac-4455-9064-511b45d924be.png)

**Comment by rmelillo76** [comment]
Hi @vomikan,  I like this feature! Just one suggestion, can we change the accelerator ley to W, D and T. The initial code has &N for each.

```
menu. Append(Model_Checking::WITHDRAWAL, _("New &Withdrawal..."));
menu. Append(Model_Checking::DEPOSIT, _("New &Deposit..."));
menu. Append(Model_Checking::TRANSFER, _("New &Transfer..."));
```

**Comment by n-stein** [comment]
I think 'D' is already the accelerator for 'Duplicate', so we would have to use some other letter.

**Comment by tactilis** [comment]
> I think 'D' is already the accelerator for 'Duplicate', so we would have to use some other letter.

In fact Alt+'D' is the accelerator for Delete. ALT+U is for Duplicate.
 
![image](https://user-images.githubusercontent.com/4060092/212465175-fb9a197f-e405-4c68-86d8-e371b5b9ead5.png)
 
Note that there is currently a problem with accelerator letters that clash with the letters used for changing transaction status. Please see this issue  #5549
