### ISSUE TITLE
Error database disk image is malformated

### ISSUE THREAD

**Issue by Kal2935** [moneymanagerex/moneymanagerex#5550]
> Hello,
> When creating a new entry, the following error appeared : 
> ![image](https://user-images.githubusercontent.com/122673674/212468524-ef43907f-a1f2-4df0-be39-0a814bc71959.png)
>
> Since then, I can't do anything without this error appearing.
> In advance, thank you for your help!
>
> Cordially,
> Kal2935

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.6.2 64-bit<br>
 • Build: Déc 18 2022 18:51:43<br>
 • db 17 •  (aes128cbc)<br>
 • git 99da0db (2022-12-18)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 •  French (France) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by n-stein** [comment]
I think this is another case of a corrupt index. However, since we've updated to wxSQLite3 version 4.9.1 the previous debug files which we used to correct indices no longer work. This appears to be due to a code change in sqlite3 which no longer allows transactions to be executed if the SQLITE_CORRUPT error is thrown (previously it only checked for SQLITE_READONLY).

https://github.com/sqlite/sqlite/commit/46c425b4dd4e0e6371d8794b671135593d2ddf8c

We need a way to turn off the SQLITE_CorruptRdOnly flag during debug operations.

**Comment by n-stein** [comment]
Until we have a way to handle this via debug files, if you have an SQLite database browser try executing the command `REINDEX CHECKINGACCOUNT_V1;`

**Comment by Kal2935** [comment]
I try the command on DB Browser for SQLite. It doesn't work.
![image](https://user-images.githubusercontent.com/122673674/213105124-5d7076bc-cd0b-427f-bb4e-73d375a391bf.png)

I try Integrety_check, i don't know if that could help you
![image](https://user-images.githubusercontent.com/122673674/213105229-b3e2f9f6-3b42-4f66-b306-8cc070a51dc9.png)

**Comment by n-stein** [comment]
Looks like you have a bad index on Payee as well. Can you expand your screenshot a bit to show the full lines from the integrity check?

**Comment by Kal2935** [comment]
Here the "full" screenshot :
![image](https://user-images.githubusercontent.com/122673674/213262111-ba6be72d-1068-49c3-a54d-1341362a1eb9.png)

An another for description of the error *** in database main ***
![image](https://user-images.githubusercontent.com/122673674/213262379-f0f6f96e-5b92-47bb-ae3f-98968b5af1f0.png)

**Comment by n-stein** [comment]
You can try to just drop and recreate the index:

```
DROP INDEX IDX_PAYEE_INFONAME;
CREATE INDEX IDX_PAYEE_INFONAME ON PAYEE_V1(PAYEENAME);
```

If it still gives you trouble executing the SQL try just going to the "Database Structure" tab, right clicking the index and selecting "Delete Index", then recreating.

**Comment by Kal2935** [comment]
I can't open database after doing command.
This error continue : 
![image](https://user-images.githubusercontent.com/122673674/213278415-886c7dec-abc5-484d-8b28-abe7c3a560dd.png)

**Comment by renato-mmex** [comment]
Question: Is there a tutorial on how to rebuild all indexes.

**Comment by vomikan** [comment]
I think in this situation it is necessary to save the data. Indexes are used for acceleration. I would delete the indexes without restoring so that the database would open. After it opens, it must be backed up. Then solve the issue of restoring indexes.

**Comment by n-stein** [comment]
> Question: Is there a tutorial on how to rebuild all indexes.

To rebuild all indices you should just be able to execute the command `REINDEX;` without specifying any specific table or index.

**Comment by n-stein** [comment]
I think the suggestion of adding a menu option 'Reindex Database' as mentioned in #5367 is a good idea. However, we need to be able to circumvent the SQLITE_CorruptRdOnly limitation to do so.

**Comment by n-stein** [comment]
Are you still seeing errors in MMEX, or only in DB Browser?

**Comment by Kal2935** [comment]
I still saw error checkinaccount on MMEX.

19 janv. 2023 02:03:01 n-stein ***@***.***>:

**Comment by vomikan** [comment]
Have you considered restoring from a backup?

**Comment by Kal2935** [comment]
I try to restore with a bakcup file.
But, i don't know why, the last file is dated to october....

This backup file is working in MMEX after making database updated.
I stop MMEX and restore it many time with the backup file. No error.

**Comment by Kal2935** [comment]
Of course, i try to restore a backup file.
Only the backup from octover will work.

I close and re-open the file, MMEX work correctly.

**Comment by n-stein** [comment]
Made a small change to allow us to execute debug files on corrupt databases by turning off the SQLITE_CorruptRdOnly flag prior to calling SqlFileDebug.

**Comment by n-stein** [comment]
Shifted the code around a bit so that the flag is turned off during upgrade as well as debug to facilitate #5367.
