### ISSUE TITLE
Split Categories Transactions: Performance Issues

### ISSUE THREAD

**Issue by valsamis-d** [moneymanagerex/moneymanagerex#5559]
MMEX version:
 - [x] 1.6.2 Portable

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows

# Description of the bug & Reproduction Steps

I heavily use Split Transactions when it comes to playing my credit card, in which case I break the amount of payment into several categories (~25 each time/month). Since the new Split Transaction dialog (which btw is great) was introduced, there is a significant delay when a Split Transaction is edited and then save. It takes ~5 seconds for the application to be responsive. 

Recently, I created a Split Transaction "template" that consists of ~60 categories with 0 (zero) amounts. When it's time to pay my credit card, I copy/paste this "template" and then I edit it to enter correct amounts and remove not applicable categories. Each time I remove a split, it takes almost 10 seconds until the split is removed, and the dialog is responsive again. In other words, for approximately 10 seconds the mouse pointer turns into the hourglass and nothing can be performed on MM.

![image](https://user-images.githubusercontent.com/17590539/213433933-f6129400-659b-45cd-baaf-362498d8dfae.png)

In the above image, I included an excerpt of the "template" transaction. With red I have marked some suggestions:

1. Use a checkbox to the left of each split to mark it for deletion. This way one could remove multiple splits
2. Adjust the text of the "Remove Split" so that it indicates the number of selected splits

Is the bug reproducible? 
 - [x] Always 

Expected result:
Editing and Saving a split transaction shouldn't take more than 1 second. Same with removing a split in an existing Split Transaction.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4591

**Comment by valsamis-d** [comment]
> #4591

<3

**Comment by n-stein** [comment]
Not sure this one should be closed. #4591 doesn't address the lag experienced here. It appears to be caused by long execution time of methods mmSplitTransactionDialog::CreateControls() and mmSplitTransactionDialog::FillControls() when there is a large number of splits.

**Comment by vomikan** [comment]
> Not sure this one should be closed. #4591 doesn't address the lag experienced here. It appears to be caused by long execution time of methods mmSplitTransactionDialog::CreateControls() and mmSplitTransactionDialog::FillControls() when there is a large number of splits.

As I understand it, this is not about the speed of the program, but about the convenience of use.

**Comment by valsamis-d** [comment]
> 

@vomikan in addition to making deleting of categories easier (user experience/convenience of use), there's also a performance lag in that specific screen as @n-stein is mentioning. If #4591 doesn't address the performance of that form, then this should not be closed.

**Comment by n-stein** [comment]
For reference, I'm finding that with 60 splits CreateControls and FillControls each take about 8 seconds on my PC. So it takes roughly 16 seconds to open the split dialog (since it executes both CreateControls and FillControls), and about 8 seconds to delete a split (since only FillControls is executed).

**Comment by vomikan** [comment]
The solution to this problem is that you cannot use SetFocus(). It should be set only for the last element. This simple fix demonstrates that the performance has increased. But tuning is required.

![image](https://user-images.githubusercontent.com/6836805/214948956-c43968ad-0609-405a-9dff-6862258adf2a.png)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4625

**Comment by n-stein** [comment]
Ah, good catch. I think the first one is missing `if (row == focusRow)`.

**Comment by vomikan** [comment]
> Can we delay initialization until the combobox receives focus

This has already been implemented. But we need to monitor the use of SetFocus() programmatically.


> move init() out of the mmComboboxCategory constructor

Probably this can achieve additional acceleration, but it works well enough as it is.

The main problem is the slow AutoComplete() function. I showed it on the video https://user-images.githubusercontent.com/6836805/174457738-df29f688-ac8c-45eb-858f-f935d7b8a7fe.mp4 
And I did an experiment with background loading of the list. https://github.com/vomikan/moneymanagerex/commit/9338d8fac190de073b60492f4144187cd28ff8fe
But I don't have enough qualifications to finish it.

**Comment by n-stein** [comment]
Significant improvement for row deletion. I'm getting 1.5 seconds with 60 splits. 

Dialog creation still takes 14 seconds. Waiting until the last row to scroll the window to the bottom in addition to setting the focus cuts that down to 7 seconds:

![image](https://user-images.githubusercontent.com/16599929/215166671-02047e0d-1b37-4c39-8a76-cc4e6ef31259.png)

**Comment by vomikan** [comment]
I commented out init(); and this->AutoComplete(auto_complete);
42 entries open for 3 seconds.
That is, this is the actual GUI that turns out to be slow. Too many elements.

**Comment by vomikan** [comment]
@n-stein feel free to make any improvements. My ideas ran out.

**Comment by vomikan** [comment]
When deleting a line, we can simply re-create it, and not recreate the entire dialog.

![image](https://user-images.githubusercontent.com/6836805/215191953-929fd7f7-222d-4e3e-a204-de43e8a0d013.png)

**Comment by n-stein** [comment]
Not sure I like the disabled lines in the middle of the list. We can just refill the lines starting at the deleted row, that way all the other lines move up as they did previously. Improvement depends on which line you delete -- deleting the last line is a bit faster than deleting the first line.
![image](https://user-images.githubusercontent.com/16599929/215200569-62d60908-b9a7-4127-b479-8367804342fb.png)

**Comment by vomikan** [comment]
It got better. I'm checking on 45 lines.
In practice, I have not seen such split.

**Comment by vomikan** [comment]
I think that if you remove the graphic icons from the Notes buttons, it will also give a performance boost. You can use an empty (without text) button if there are no notes and use text when notes are present.

**Comment by n-stein** [comment]
I think as you said, the rest is just due to the GUI building the large number of elements. Performance is probably better for you than me -- my PC is from 2012, still has an AMD Phenom II 1090T in it.
