### ISSUE TITLE
Set transferred date

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#556]
Transfers are not immediate between two different banks, if I were to transfer money from an account on Friday the money will would not show up into my other account until Tuesday, which messes with the history if I made any transactions on the weekend.

**Comment by vomikan** [comment]
That is true. But in many cases we can ignore this fact to have simple UI.

**Comment by guanlisheng** [comment]
will close it soon if there is no additional discussion.
