### ISSUE TITLE
synchronization with all my devices.

### ISSUE THREAD

**Issue by kountryking** [moneymanagerex/moneymanagerex#5561]
When I enter a document on Microsoft Word, for example, on my primary laptop, I can open my secondary laptop or my Android phone and find the new entry there. I'd like to see MMEX have the same facility. If one laptop goes to the shop, I'd be up to date on the other or the cell phone (which I hate to use). Now, I have to make my MMEX entries on my primary laptop and copy them again on the other laptop.

**Comment by vomikan** [comment]
Historically, most users prefer to store their personal data in one place without using cloud storage.
1) You can write the program to a USB flash drive and run it from there. Carry a USB stick with you.
2) You can fumble mmb files through a service like Dropbox. But it caused a lot of issues and synchronization failures.

Thus, we are far from solving this query.

**Comment by kountryking** [comment]
Today, after adding new data to my MMEX. Then I downloaded the latest version, 1.6.3-win64. As usual, I was told that this download was not usual although I've been using it for eight years. I had to check "Keep" and "I trusted this app". After waiting a long time, I clicked the app to open it. I got a warning that began "Theme default not found, it may no longer be supported. Reverting to default theme. Then there was a list of pop-ups beginning with File 'master.ccs' missing or invalid in chosen theme 'default'. I had to click on their Xs to get this message to close. I can't open MMEX using 1.6.2 or any BAK or MMB File. I can't find the most recent data from earlier today. HELP!

**Comment by vomikan** [comment]
I checked this release here. It is enough to unpack to any folder and run bin\mmex.exe file. Everything works, all the themes are in place.

https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex-1.6.3-win64-portable.zip

**Comment by kountryking** [comment]
It worked perfectly. Thank you. My only problem was with Microsoft. They showed me how to resolve the download problem.
