### ISSUE TITLE
Balances

### ISSUE THREAD

**Issue by HmarB** [moneymanagerex/moneymanagerex#5563]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
I have a report called "Saldos" or "Balances" (please see the attached file "Saldos.grm". When I run this report as of, fox example, Dec, 31, 2022 shows a wrong balance of an account. If I compare this with the transacctions does not mathc. Please see the Word file attached with this images.
[Balance wrong.docx](https://github.com/moneymanagerex/moneymanagerex/files/10470613/Balance.wrong.docx)

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by HmarB** [comment]
[Saldos.zip](https://github.com/moneymanagerex/moneymanagerex/files/10470629/Saldos.zip)

**Comment by renato-mmex** [comment]
Saldos.grm does not contain any date restriction, all transactions are taken into account.
The transaction detail still contains transactions in 2023, these are also included.

**Comment by HmarB** [comment]
Thanks Renato for your quick replay. But I attached a Word file with the imagen, in which in Report I selected a date (31/12/2022) and when I see the highlighted account does not macht. Hope you can understant my point. Best!

**Comment by renato-mmex** [comment]
Probably you have deleted transactions (new features) and this is not taken into account in the SQL query.

Add **_DELETEDTIME = ""_** to the SQL query and check if the evaluation is correct.

with b as  (
    select ACCOUNTID, STATUS
        , (case when TRANSCODE = 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end) as TRANSAMOUNT
        , TRANSDATE
    from CHECKINGACCOUNT_V1    
    where STATUS <> 'V'
        and TRANSDATE <= '&single_date'
        **_and DELETEDTIME = ""_**
    union all
    select TOACCOUNTID, STATUS
        , TOTRANSAMOUNT ,TRANSDATE
    from CHECKINGACCOUNT_V1
    where TRANSCODE = 'Transfer'
        and STATUS <> 'V'
        and TRANSDATE <= '&single_date'
    )

**Comment by renato-mmex** [comment]
Sorry, apparently there are multiple values for this entry.
I have changed it so and with me it works, but whether I have interpreted correctly and have the right data to test ??

where STATUS <> 'V'
        and DELETEDTIME = "" or DELETEDTIME is null
        and TRANSDATE <= '&single_date'

**Comment by n-stein** [comment]
You can also use this to cover both the NULL and blank values:

`AND coalesce(DELETEDTIME, '') = ''`

**Comment by vomikan** [comment]
> AND coalesce(DELETEDTIME, '') = ''

https://www.sqlite.org/lang_corefunc.html#ifnull

```  ifnull(DELETEDTIME, '') = '' ```

I wanted to write this solution, but the DELETED TIME field never takes the null value. But perhaps there is an exception to this rule.

**Comment by vomikan** [comment]
```
with b as (
select ACCOUNTID, STATUS
, (case when TRANSCODE = 'Deposit' then TRANSAMOUNT else -TRANSAMOUNT end) as TRANSAMOUNT
, TRANSDATE
from CHECKINGACCOUNT_V1
where STATUS <> 'V'
and ifnull(DELETEDTIME, '') = ''
and TRANSDATE <= '&single_date'
union all
select TOACCOUNTID, STATUS
, TOTRANSAMOUNT ,TRANSDATE
from CHECKINGACCOUNT_V1
where TRANSCODE = 'Transfer'
and STATUS <> 'V'
and ifnull(DELETEDTIME, '') = ''
and TRANSDATE <= '&single_date'
)
, c as (select CURRENCYID, PFX_SYMBOL, SFX_SYMBOL, CURRENCY_SYMBOL, DECIMAL_POINT, GROUP_SEPARATOR, SCALE from CURRENCYFORMATS_V1)
, r as ( select cf.CURRENCYID, ifnull(ch.CURRVALUE, 1) CURRVALUE from CURRENCYFORMATS_V1 cf
left join CURRENCYHISTORY_V1 ch on cf.CURRENCYID = ch.CURRENCYID
and ch.CURRDATE = (SELECT MAX(CURRDATE) FROM CURRENCYHISTORY_V1 WHERE CURRENCYID = ch.CURRENCYID)
and ch.CURRDATE <= '&single_date')
select a.ACCOUNTNAME, a.ACCOUNTTYPE,
total(TRANSAMOUNT) + a.INITIALBAL as BALANCE,
c.PFX_SYMBOL, c.SFX_SYMBOL, c.CURRENCY_SYMBOL, r.CURRVALUE, c.SCALE
from ACCOUNTLIST_V1 a
left join b on a.ACCOUNTID=b.ACCOUNTID
left join c on a.CURRENCYID=c.CURRENCYID
left join r on r.CURRENCYID=c.CURRENCYID
where a.STATUS = 'Open' and a.ACCOUNTTYPE !='Investment'
group by a.ACCOUNTNAME
order by a.ACCOUNTTYPE, a.ACCOUNTNAME asc;
```

**Comment by renato-mmex** [comment]
@vomikan   Write: `I wanted to write this solution, but the DELETED TIME field never takes the null value. But perhaps there is an exception to this rule.`

Unfortunately, LASTUPDATEDTIME and DELETEDTIME have three different values, **NULL** or **""** or a date in the form of **2023-01-14T14:07:24.**

<img width="296" alt="image" src="https://user-images.githubusercontent.com/76920138/214162899-03db5f50-086e-4ae0-a10c-2f61eedff513.png">
<img width="221" alt="image" src="https://user-images.githubusercontent.com/76920138/214163464-c21716fc-de12-4625-8fa6-37f98d9cf595.png">

**Comment by HmarB** [comment]
Thanks a lot for all of you, for your helps!!

**Comment by n-stein** [comment]
> Unfortunately, LASTUPDATEDTIME and DELETEDTIME have three different values, **NULL** or **""** or a date in the form of **2023-01-14T14:07:24**

True, I believe the NULL only appear for records that exist in CHECKINGACCOUNT_V1 prior to the upgrade. Any records created after the initial upgrade are created with `''`. This is because we didn't specify a default value in the SQL script, so when the new column is added it generates full of NULLs.

The `coalesce` and `ifnull` functions (which are identical in this instance) return `''` if DELETEDTIME is either NULL or `''`.
