### ISSUE TITLE
Crash on stock price history deletion

### ISSUE THREAD

**Issue by Wehzie** [moneymanagerex/moneymanagerex#5564]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [x] Linux

# Description of the bug

Money Manager crashes when deleting all entries in the stock price history view.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Add new stock purchase
2. Enter symbol name
3. Add purchase date
4. Add purchase quantity
5. Add stock price at time of purchase
6. Click save; In the price view on the right-hand side, the date of purchase and price will show up
7. Select date and click delete
8. Money Manager crashes

![money_manager_crash](https://user-images.githubusercontent.com/39304339/213860674-280d69f7-9dac-4496-b54e-f6e48ddc9f25.png)

Expected result:

- Entry is deleted from stock's price history

Actual result:

- Money Manager crashes

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
WTF?

![image](https://user-images.githubusercontent.com/6836805/214141321-0d05b2b5-b3f0-4ec0-a0de-35558d176800.png)

**Comment by Wehzie** [comment]
Thanks for the quick fix!
