### ISSUE TITLE
Account Summary Report

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#5566]
Hi All!
Is there any report that would show the following accounts on a similar chart. Listed below is the total amount of assets, the amount of accounts and their percentage of total assets. Something like this.

Bank accounts
Cash accounts
Term Deposits
Securities
Current accounts
credit cards
loans
tools
investments
cryptocurrencies

You could even put one on the home page.
![report](https://user-images.githubusercontent.com/80578702/213911406-3da64945-4b53-423d-a7a8-cc8e25690cee.png)

**Comment by whalley** [comment]
You could start with the Account GRM reports as a basis for this:
https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances
https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountSummary

**Comment by Heny67** [comment]
@whalley 
Thank you!
