### ISSUE TITLE
Budget Performance Report

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#5573]
## Three interlinked features for the Budget Performance Report

**1. The total yearly budget should not be affected by the monthly budgets, when both coexist.** 

 
Imagine we have an yearly budget (say 2023) for a category Travel as €1500 (=€125 per month). Now, we can have a monthly budget (say January 2023) for the same category Travel as € 650 since we planed to spend a chunk of it in January. Defining a monthly budget should not affect my yearly budget, so it should stay as such, i.e. €1500, and not €125*11 + €650 = €2025.

![image](https://user-images.githubusercontent.com/83648377/214634912-c583dc32-2db4-4fed-85e8-6739bd585dbb.png)

**2.  If sum of all monthly budgets for a category is more than the yearly budget, a warning - say exclamation could be shown next to that category.**

Suppose I set a monthly budget  for 3 months (n_months = 3),  for category Travel which has yearly budget €1500:
January 2023 as €650,
March 2023 as €850,
June 2023 as €300,
a warning should be shown as the total budget of €1500 is exceeded by the sum of monthly budgets (sum over n_months: €650+€850+€300 =€1800). 

**3.  When monthly budgets are set up for selected months (n_months), the estimated budgets for other months (12 - n_months) should be adjusted to add up to the yearly budget** 

Suppose I set a monthly budget  for 3 months (n_months = 3),  for category Travel which has yearly budget €1500:
January 2023 as €650,
March 2023 as €150, 
June 2023 as €100,
The estimated budgets for the other (12 - n_months) should be:
<del>estimtated_monthly_budget = (€1500 - (€650+€150+€100))/12 =  €600/12 = €50 </del>
estimtated_monthly_budget = (€1500 - (€650+€150+€100))/(12-3) =  €600/9 = €66.67

**Comment by n-stein** [comment]
Its an interesting idea. I feel this would have to be a new option, something like "Deduct monthly budget from yearly budget".

I suppose that if you create a new budget month based on the year budget the amount would also need to be based on this "reduced" yearly budget, not simply year_amount/12 as it currently is.


> The estimated budgets for the other (12 - n_months) should be:
> estimtated_monthly_budget = (€1500 - (€650+€150+€100))/12 = €600/12 = €50

I think this is wrong. Your total would be 650+150+100+9*50 = 1350. You need to divide by (12-n), not 12.
estimtated_monthly_budget = (€1500 - (€650+€150+€100))/(12-3) = €600/9 = €66.67

**Comment by n-stein** [comment]
Adjusted the code a bit and got it working. Is this what you are expecting?

With 1500 yearly budgeting 650,150,100 in Jan-Mar it spreads 66.67 Apr-Dec
![image](https://user-images.githubusercontent.com/16599929/214708634-f5a0615a-2ebd-4e45-868b-18da8054afb5.png)

Adding a Sept budget 300 automatically changes Apr-Aug and Oct-Dec to 25
![image](https://user-images.githubusercontent.com/16599929/214709046-fb635a64-79da-4dd1-b9e5-7d7d165c010e.png)

Exceeding the yearly budget drops all non-budgeted months to 0
![image](https://user-images.githubusercontent.com/16599929/214709325-a995a9c5-9123-4430-ac55-762c8b216590.png)

I don't have any warnings or options added, just playing with report changes so far. Will continue to tinker on this.

Question: How should this interact with the "Override yearly budget with monthly budget" option? I feel like this "Deduction" option only makes sense when the "Override" is enabled.

I'll merge this with #5464, tackle both at the same time.

**Comment by n-stein** [comment]
> Question: How should this interact with the \"Override yearly budget with monthly budget\" option? I feel like this \"Deduction\" option only makes sense when the \"Override\" is enabled.

Thinking about this a bit more

```
If override
    If deduct
        monthAmt or (yearAmt - sum(monthAmt))/(12 - budgetedmonths)
    Else
        monthAmt or yearAmt/12
Else
    If deduct
        monthAmt + (yearAmt - sum(monthAmt))/12
    Else
        monthAmt + yearAmt/12
```

**Comment by h-vijayakumaran** [comment]
> I suppose that if you create a new budget month based on the year budget the amount would also need to be based on this "reduced" yearly budget, not simply year_amount/12 as it currently is.

Indeed! Sorry I overlooked it while writing, but that is what I meant :)

**Comment by n-stein** [comment]
New menu option:
![image](https://user-images.githubusercontent.com/16599929/217351547-e0e5bba9-4b95-40fc-9fad-dc32957806bc.png)


> If sum of all monthly budgets for a category is more than the yearly budget, a warning - say exclamation could be shown next to that category.

When the yearly budget has been exceeded the estimated amount text becomes red.
![image](https://user-images.githubusercontent.com/16599929/217097274-a55063fe-fd34-4843-a2f4-a6f4cb9f23f0.png)

If you have some time, please test the beta:
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/46169272

**Comment by h-vijayakumaran** [comment]
> If you have some time, please test the beta: https://ci.appveyor.com/project/whalley/moneymanagerex/builds/46169272

Is a beta available for Linux OS?

**Comment by n-stein** [comment]
> Is a beta available for Linux OS?

Sure is.

https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex?branch=master

**Comment by h-vijayakumaran** [comment]
The new functionality is working fine, however, selecting the "budget category summary" causes mmex to crash at the moment. I am not sure if this is due to the changes implemented or something else.
 ![image](https://user-images.githubusercontent.com/83648377/218518785-3b135bdb-4728-4607-a60d-9d9da1df40d2.png)

**Comment by n-stein** [comment]
Interesting, I don't get any crashes. However, the error message suggests where yours is failing so let me try to adjust the code a bit.

**Comment by n-stein** [comment]
@h-vijayakumaran You can check the next beta to confirm if that fixed it for you. Linux beta builds are performed nightly at 3:16 AM UTC.

**Comment by h-vijayakumaran** [comment]
Yes, it is working now :)
