### ISSUE TITLE
Add "All Time" period for Category reports

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#558]
A request via email from users to add "All Time" period to the desktop version.

**Comment by guanlisheng** [comment]
@vomikan will it be done for v1.3 release ?

**Comment by vomikan** [comment]
Yes. It should be quiet easy.

среда, 24 февраля 2016 г. пользователь Lisheng написал:

**Comment by vomikan** [comment]
Shoul dbe done in this case: https://github.com/moneymanagerex/moneymanagerex/issues/297
