### ISSUE TITLE
Testing database is not working

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5580]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I downloaded the testing database from https://github.com/moneymanagerex/database/tree/master/tests and I tried to open with last stable version of mmex, but it failed to update to version 15.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
- Download [mmex_0970.mmb](https://github.com/moneymanagerex/database/blob/master/tests/mmex_0970.mmb) database
- Try to open with MMex 1.6.2

Expected result:
Should open without any error in order to be able to use for tests.

Actual result:
Can't be upgrade.

# Additional information

![imagen](https://user-images.githubusercontent.com/11770760/214904554-fc6b3021-a61c-4a0c-ae99-80a9767fa81f.png)

If the testing database is placed somewhere else then I suggest to replace that old database or simply remove it, but I didn't found any other testing database.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/672

**Comment by vomikan** [comment]
Irecommend this one:
https://github.com/moneymanagerex/moneymanagerex/files/6056717/test_mmex_db_2021-02-28.zip

**Comment by vomikan** [comment]
I made a script that increases the last dates in the old demo database to today.

```
with d as (select round(julianday('now') - julianday(max(transdate))) diff from CHECKINGACCOUNT_V1)
update CHECKINGACCOUNT_V1
set TRANSDATE = date(TRANSDATE, '+'|| (select d.diff from d) || ' day')
--select date(TRANSDATE, '+'|| (select d.diff from d) || ' day') from CHECKINGACCOUNT_V1
```

[test_mmex_db_2021-02-28.zip](https://github.com/moneymanagerex/moneymanagerex/files/10513064/test_mmex_db_2021-02-28.zip)

**Comment by BanCrash** [comment]
> I made a script that increases the last dates in the old demo database to today.
> 
> ```
> with d as (select round(julianday('now') - julianday(max(transdate))) diff from CHECKINGACCOUNT_V1)
> update CHECKINGACCOUNT_V1
> set TRANSDATE = date(TRANSDATE, '+'|| (select d.diff from d) || ' day')
> --select date(TRANSDATE, '+'|| (select d.diff from d) || ' day') from CHECKINGACCOUNT_V1
> ```
> 
> [test_mmex_db_2023-01-26.zip](https://github.com/moneymanagerex/moneymanagerex/files/10513096/test_mmex_db_2023-01-26.zip)

Just tested and it works perfect, thanks!
