### ISSUE TITLE
Quicken QIF import issue in split transactions with balnk row

### ISSUE THREAD

**Issue by njwgh** [moneymanagerex/moneymanagerex#5583]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I'm importing from quicken 2008 using 1.6.3-Beta.3 64-bit
Some of my split transactions didn't import correctly. The total was correct but the splits weren't
I looked at the actual transaction in Quicken and I could see that there was a blank row between the splits.

![quicken-split-transaction](https://user-images.githubusercontent.com/6837919/215064479-c17c0986-13dd-4157-ba88-de1a73f1404d.png)

Because of this blank row, the QIF file exported from Quicken included the blank row as a line with a single 'S' and the next line as $0.00

![qif-blank-split-lines](https://user-images.githubusercontent.com/6837919/215064670-51d07821-2fe1-4122-91fe-27412a21ca77.png)

The import into mmex was not ignoring these two lines and incorrectly apportioning the splits, although the split total in the transaction was entered correctly the sum of the splits was not correct.

![mmex-transaction-entry](https://user-images.githubusercontent.com/6837919/215064757-6008b6b9-2422-487e-b522-3296cab95878.png)

![mmex-transaction](https://user-images.githubusercontent.com/6837919/215064788-a7a1701b-ec9a-446d-a1da-fd1b4540cd03.png)

![mmex-transaction-splits](https://user-images.githubusercontent.com/6837919/215064814-4f1bd601-dfbd-45cc-b49a-81246147c437.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information
This is potentially a quicken issue - it may be it is violating QIF file format as I'm not sure what the strict rules are.
A workaround is to do a regex search in your exported qif file for ^S\n\$0.00 and delete those lines before importing the qif file.

If you have a backtrace for a 

crash or a warning, paste it here.

**Comment by vomikan** [comment]
Could you provide QIF file fot this split transaction?

**Comment by njwgh** [comment]
Qif file attached
[quicken-split-transaction.zip](https://github.com/moneymanagerex/moneymanagerex/files/10518523/quicken-split-transaction.zip)

**Comment by vomikan** [comment]
After the fix, the following transaction is imported:
```
D24/4/19
U0.00
T0.00
PColes
LFood
SFood
$-30.00
S
$0.00
SGift card purchase
EPurchased gift card
$27.30
SBank charges
Ecitibank coles gift card
$2.70
```
Result:
![image](https://user-images.githubusercontent.com/6836805/215285378-d4e7da9c-f6f6-4219-8882-5e5282dc9a47.png)
