### ISSUE TITLE
GRM text box context menu is not translated

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5590]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
If I open the General Report Manager context menu, it will show the options unstranslated:

![imagen](https://user-images.githubusercontent.com/11770760/215317910-e5622db2-1b8d-4974-a34d-1baef7275b2f.png)

These strings appear to not be available on Crowdin:
![imagen](https://user-images.githubusercontent.com/11770760/215318047-4be67966-5a08-4dfc-bb54-11446027d625.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
- Open GRM.
- Create a new report or go to an already one existent.
- Go to SQL, Lua, Template or description (it happens on all of these).
- Right click on the text box will show the context menu untranslated.

Expected result:
Context menu should be translated into the selected language.

Actual result:
Context menu is shown in english.

# Additional information
![imagen](https://user-images.githubusercontent.com/11770760/215318009-31d8787c-979b-4474-97c6-a15642b1417d.png)

**Comment by vomikan** [comment]
Its OS language settings dependent menu.

**Comment by BanCrash** [comment]
> Its OS language settings dependent menu.

How can be that modified then if I have my Windows on spanish?

**Comment by tactilis** [comment]
@BanCrash
> Right click on the text box will show the context menu untranslated.
> Context menu is shown in english.

@vomikan
> Its OS language settings dependent menu.

The above statements are not 100% correct.

The menu item 'Delete' _is_ translated according to the MMEX application language.

'Borrar' in @BanCrash's screenshot.

And here with the MMEX language set to French:

![image](https://user-images.githubusercontent.com/4060092/215323362-551e7cc8-def7-4862-8e22-55d7078d0f72.png)

**Comment by BanCrash** [comment]
@tactilis Oh you're right, I din't see that there was one item translated, good catch.

**Comment by vomikan** [comment]
We can add the necessary phrases to the file const.cpp
```
//bug #5590
const wxString grm_menu_undo = _("Undo");
const wxString grm_menu_redo = _("Redo");
const wxString grm_menu_cut = _("Cut");
const wxString grm_menu_copy = _("Copy");
const wxString grm_menu_paste = _("Paste");
const wxString grm_menu_selall = _("Select All");
```
![image](https://user-images.githubusercontent.com/6836805/215326831-122e930c-63f6-4c12-b4a3-e470bf6aa099.png)

**Comment by vomikan** [comment]
However, in the Output tab, this trick did not work.

![image](https://user-images.githubusercontent.com/6836805/215327163-413bb3f3-8a42-4eca-bb5e-a4cea5577a69.png)

**Comment by BanCrash** [comment]
@vomikan that's fine for me since it's already on spanish on that context menu, except for "Export to Microsoft Excel" and "Send to OneNote" strings:

![imagen](https://user-images.githubusercontent.com/11770760/215331497-5506be21-414a-421e-a200-dbfc3e62405c.png)

**Comment by ovari** [comment]
Please add keyboard shortcuts to the context menu items.

Cf. https://github.com/moneymanagerex/moneymanagerex/issues/5636#issuecomment-1426371615
