### ISSUE TITLE
Release 1.6.3

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5598]
The release ends with an error

![image](https://user-images.githubusercontent.com/6836805/215612626-7385cf2d-769b-4feb-8237-6ba58baf9d2d.png)

**Comment by whalley** [comment]
Think this is related to the whne AppVeyor stopped working and I needed to re-create the associated. I have hopefully now added the  token needed for ...
`auth_token: '%GitHub_auth_token%'`
needed.

Let me know if that works.

**Comment by vomikan** [comment]
It's okey now!
https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-4e71ab7ce2e699d3df9a

Please fill in the binary files for nix

**Comment by whalley** [comment]
@vomikan MacOS and *nix builds uploaded.

Ready to go when you are ready.
