### ISSUE TITLE
Transaction Report / Categorie

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5599]
MMEX version:
  - [x] 1.6.2
 - [x] 1.6.3 Beta

Operating System:
 - [x] Windows

**Transaction Report / Categorie**
The selection including the subcategory does not always work.
In many cases, the field cannot be checked.
For example, if you use the category selection **Gifts|Bills**, the checked field is deleted and the evaluation is performed without subcategories.
By the way: in different keyboard layouts there is no | sign (vertical line), maybe you could place a | to the left of the field for inserting.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/76920138/215750847-76902432-c9fd-44fc-a641-2275f4e34f56.png">

**Comment by rmelillo76** [comment]
The Include all sub-categories checkbox is currently designed to only be active when the value entered into the Category text box is an actual, single category name. In this example, you have a regular expression that will evaluate to either "Bills" or "Gifts", not a singular category name. The checkbox will become enabled or disabled upon completion of the category field.  In my opinion, it may be very complex to try to identify the sub categories that are associated with each of the resulting category names after the regex is evaluated.

**Comment by renato-mmex** [comment]
@rmelillo76 
From my point of view there is no need for these tests for the checkbox, if I activate this checkbox for a category and it has no subcategories, then there are just no such results. The current state is unsatisfactory and confuses the normal user.

**Comment by vomikan** [comment]
As I remember, if you enter the name of the category in the field and it is present in the system, then the tick is active. As soon as a sequence of characters is entered, we consider it a search string and the check mark becomes unavailable.

**Comment by whalley** [comment]
> As I remember, if you enter the name of the category in the field and it is present in the system, then the tick is active. As soon as a sequence of characters is entered, we consider it a search string and the check mark becomes unavailable.

Think these is an issue, as I experience it on MacOS, in that as soon as a category is detected it will highlight the check box, but if the text is subsequently changed to be a non-category it is not de-selected.

**Comment by n-stein** [comment]
Give that a try

**Comment by rmelillo76** [comment]
> Give that a try.

Wow that is very slick @n-stein! I'm sorry I doubted and thought it would be overly complicated, but you nailed t!
@renato-mmex  obviously you'll test this too but wanted to pass along some early feedback that this fix seems to be exactly what you asked for. It handled a few different regex patterns I tried that would find any matching categories, and included the subcategories of each (if there were any)

**Comment by renato-mmex** [comment]
If you could still make an improvement there, then it would be perfect for me.
`By the way: in different keyboard layouts there is no | sign (vertical line), maybe you could place a | to the left of the field for inserting.`

**Comment by n-stein** [comment]
Just curious, which keyboard layout are you using?

**Comment by vomikan** [comment]
A similar situation with the Russian layout to write | I switch to the English layout.

**Comment by n-stein** [comment]
Check out https://github.com/samhocevar/wincompose to avoid switching layouts

**Comment by renato-mmex** [comment]
Have another CH keyboard connected that has the | with Alt Gr + 7

**Comment by n-stein** [comment]
Really I'm just trying to come up with reasons not to include a '|' button on the interface °͜°

**Comment by tactilis** [comment]
> Really I'm just trying to come up with reasons not to include a '|' button on the interface

It's not the job of the MMEX UI (or any other application's UI) to accommodate the idiosyncrasies of different national keyboards.

There is always a compose key sequence that you can type, and once you've learned it, it's quick to use.
Or, as you have indicated, WinCompose handles this with ease.

**Comment by renato-mmex** [comment]
I don't think that the "normal" MMEX user knows WinCompose. We should also keep the ease of use high for non-tech freaks. The selection of categories has now become very complex and users are challenged especially because we also do not provide a description.

**Comment by whalley** [comment]
Using RegEx is perhaps not for casual users.

**Comment by tactilis** [comment]
> The selection of categories has now become very complex

I don't agree.  You can filter on a category just as easily as you always could.

There are _additional_ facilities to cater for more complex filtering needs.

> we also do not provide a description

Agreed. That is an ongoing problem that we currently are unable to address other than by answering questions as they arise.
