### ISSUE TITLE
Auto linking of transfers

### ISSUE THREAD

**Issue by pjsoni** [moneymanagerex/moneymanagerex#560]
I'd like to have a feature for automatic linking of transactions for transfers.

For example, you have multiple transactions with transfer to/from accounts. currently, you need to manually edit transaction and MMEX creates duplicate transaction for the same. I'd suggest to have automatically link those transactions (transfers). Also it would be nice to have a context menu item for navigating the matching transfer of other account.

**Comment by gabriele-v** [comment]
It's an interesting idea that could be expanded to all transactions type.
When click "liked transactions" it will be opened a small window with related transactions and vice-versa.
Unfortunately currently I have no time to develop it, maybe someone could help.

**Comment by vomikan** [comment]
I don't understand the issue explanation.

**Comment by vomikan** [comment]
Reopen it if needed.

**Comment by chris3081** [comment]
I would be kind to see this I have hundreds of transfers that are marked in both accounts as either deposits or withdrawals. They could all be matched based on the receipt number in the notes.
