### ISSUE TITLE
Keyboard shortcuts missing

### ISSUE THREAD

**Issue by xyzyxx** [moneymanagerex/moneymanagerex#5604]
MMEX version:
1.6.3 (tested on 32 bit and 64 bit portable versions)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Keyboard shortcuts (Ctrl-R, Ctrl-U, etc.) no longer work to change the status of a selected transaction. Nothing appears to happen when these shortcuts are used. After switching back to 1.6.2 the shortcuts work again.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by xyzyxx** [comment]
Immediately after submitting, I noticed that pressing the shortcuts without the Ctrl key performs the desired actions. Was I mistaken that the Ctrl key was ever needed for these shortcuts?

I am guessing that this is intended behavior after all and this can be closed.

**Comment by tactilis** [comment]
> Was I mistaken that the Ctrl key was ever needed for these shortcuts?

Yes, you were.

U Unreconciled
R Reconciled
D Duplicate
F Follow-up
V Void
