### ISSUE TITLE
Search Feature issue introduced 1 - 2 updates ago not resolved

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/moneymanagerex#5606]
MMEX version:
 - [x ] 1.6.3

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11

# Search feature broken (has since 2 or so updates ago)

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
Start new transaction
Click into Category
When Organize categories comes up (Click in Search box)
PC or App doesn't respond as it used to, with matching text to categories as you typed.
It was brilliant before but broken now!

Expected result:
It works

Actual result:
Doesn't work at all.

# Additional information
Since updated version before end of 2022, it was fine but then whatever was done it no longer functions as it did.

If you have a backtrace for a crash or a warning, paste it here.

I've attached 2 MP4 files to illustrate this issue. (I'm surprised others haven't noticed it!)

https://user-images.githubusercontent.com/14268231/216217049-da08c35b-43e2-40b0-a4ac-2c381140245e.mp4

https://user-images.githubusercontent.com/14268231/216217072-0b306228-cdb3-478e-9e56-e4562144c284.mp4

**Comment by SJK55** [comment]
Sorry attached same file twice this was the follow up file I was trying to attach

https://user-images.githubusercontent.com/14268231/216217353-22244602-3f75-4cda-b6b6-8772ec5c2a46.mp4

**Comment by n-stein** [comment]
Definitely broken by #1477. Filtering currently works for top level categories, but not for nested.

**Comment by n-stein** [comment]
I've fixed the filtering. Please test the next beta build and check if it is working better for you.

Fair warning -- I tried rewriting and optimizing the code a bit, but performance still isn't going to be great with your 3800+ categories simply due to the volume. I was averaging about 5 seconds per refresh of the dialog using your category list from November on my ancient PC (10+ year old) , so it should be significantly better for you.

**Comment by SJK55** [comment]
n-stein thank-you for following up. To be fair the copy I did give you was an amalgamation of 2 older databases (dbase and MsMoney) that I'm trying to tame into one. (hence the extreme number of categories I guess) But even so the previous one mentioned before December still worked fine for me. But I'll try the Beta and get back to you. Again thanks for looking into this!

**Comment by SJK55** [comment]
Sorry to be a pain but can you please assist with the method to access the beta version. I did prior but can't find those instructions I followed before.

**Comment by n-stein** [comment]
Go to this link
https://ci.appveyor.com/project/whalley/moneymanagerex

Pick either the Win32 or x64 version.
Click the "Artifacts" tab.
Pick either the portable.zip or exe to download.

**Comment by SJK55** [comment]
Excellent! Totally works with not much delay considering my large category selection. Thank you very much! Well done!

**Comment by SJK55** [comment]
I used the 64 Bit version. (not portable)

**Comment by n-stein** [comment]
One thing I noticed is that my fix applies the filter by category name while previous versions applied it by "full name". The difference is applying it by "full name" means the filter will return a matching category plus all of its descendants rather than just the category.

Example consider this category hierarchy:

```
Income
  Investments
    Dividends
      Qualified
      Unqualified 
    Capital Gains
      Short Term
      Long Term
  Work
    Salary
    Bonus
```

In 1.6.1 searching for "Inv" would return
```
Income
  Investments
    Dividends
      Qualified
      Unqualified 
    Capital Gains
      Short Term
      Long Term
```

The current code will return
```
Income
  Investments 
```

Which will the average user expect?

**Comment by SJK55** [comment]
Not sure but from my point of view but the Beta I'm using now for me, suits well.
As an example looking up an Ant poison (under a Sub Category of Chemical.
When I type ant I get many hits displayed ie contained in words like Pantry, Warranty, Sealant
But if I place a space before ant and after I isolate the search to what I really was looking for being only 2 results.
This for me is how I want it to work as I have identified 2 places categories that exist using ant as the thing I'm trying to find.
So for me now I found 2 occurrences, I can  Relocate the Category of one to the other and reduce my 'category load' so to speak!
For me this helps finding where I last used a particular category and can't remember where or exactly what I called it.

**Comment by n-stein** [comment]
Refactored, significant performance improvement from 5 seconds to less than 1 second to filter 3800+ categories.

**Comment by BanCrash** [comment]
> One thing I noticed is that my fix applies the filter by category name while previous versions applied it by "full name". The difference is applying it by "full name" means the filter will return a matching category plus all of its descendants rather than just the category.
> 
> Example consider this category hierarchy:
> 
> ```
> Income
>   Investments
>     Dividends
>       Qualified
>       Unqualified 
>     Capital Gains
>       Short Term
>       Long Term
>   Work
>     Salary
>     Bonus
> ```
> 
> In 1.6.1 searching for "Inv" would return
> 
> ```
> Income
>   Investments
>     Dividends
>       Qualified
>       Unqualified 
>     Capital Gains
>       Short Term
>       Long Term
> ```
> 
> The current code will return
> 
> ```
> Income
>   Investments 
> ```
> 
> Which will the average user expect?

I don't know about others but I would expect the behaviour of 1.6.1. Sometimes I remember a middle category but not the exactly one. With the second behaviour filtering wouldn't make any difference.

**Comment by SJK55** [comment]
n-stein is there a Beta Plus you have created?
I tried to find but didn't using previous link.

**Comment by tactilis** [comment]
> Which will the average user expect?

The 1.6.1 behaviour, i.e returning the matching category plus its descendants.

Why?  Because if I'm looking to classify transaction that is a Bill, for example, I don't want to have to try to remember all the subcategories of Bills: that I have created. I want to see them all when I search for Bill to remind me what I have available.

**Comment by n-stein** [comment]
> n-stein is there a Beta Plus you have created?\nI tried to find but didn't using previous link.

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/46128886

Good points all on the name vs full name match, I will update this shortly.

**Comment by SJK55** [comment]
Wow, this is even better. Even from the New transaction clicking on Category it flies now! Gold Star!

**Comment by BanCrash** [comment]
@n-stein about the filtering of the full category instead only of the main category, could be added to the new transaction dialog too? Or that would need a lot of code refactoring?

![imagen](https://github.com/moneymanagerex/moneymanagerex/assets/11770760/dcfddebb-1f3b-4b40-ac16-b92394b9ad12)

![imagen](https://github.com/moneymanagerex/moneymanagerex/assets/11770760/af3c69be-cb75-4bdd-81f8-3b489be750bb)
