### ISSUE TITLE
IMPOSSIBLE DE METTRE A JOUR AVEC LES VERSIONS : MMEX 1.6.2 WIN64 et MMEX 1.6.3 WIN64

### ISSUE THREAD

**Issue by Claudan05** [moneymanagerex/moneymanagerex#5607]
> Message d'erreur : la mise à jour de la base de données MMEX version 17 a échoué
Restauré la BdD à partir le sauvegarde automatique automatique crée avant la mise à jour ou contacter le support MMEX
constraint Failed [2067] : UNIQUE  constraint Failed : CATEGORY_V1.CATEGNAME    CATEGORY_V1.PARENTED
Le support MMEX vous a t-il fourni un fichier de débogage ou un patch ? OUI ou NON 

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr>Version: 1.6.1 64-bit<br>
 • Build: Nov. 18 2022 10:39:40<br>
 • db 16 •  (aes128cbc)<br>
 • git 09cb031 (2022-11-18)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  French (France) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by renato-mmex** [comment]
https://forum.moneymanagerex.org/viewtopic.php?p=23696#p23696

**Comment by n-stein** [comment]
This is the duplicate category name issue:

See this comment https://github.com/moneymanagerex/moneymanagerex/issues/5443#issuecomment-1360228604

Or this forum post
https://forum.moneymanagerex.org/viewtopic.php?t=10777
