### ISSUE TITLE
latest version mmex for windows error

### ISSUE THREAD

**Issue by jam4657** [moneymanagerex/moneymanagerex#5608]
Impossible to use the latest version for windows with .mmb precedent version.

**Comment by n-stein** [comment]
Need a bit more information here. What error are you receiving? Can you provide a screen print?

**Comment by jam4657** [comment]
Here in attached piece hard copy screen. Sorry, the text is in french.
<img width="417" alt="Capture d’écran 2023-02-04 121030" src="https://user-images.githubusercontent.com/124278945/216764081-92602332-a399-4764-9897-97edb03fbfee.png">

**Comment by n-stein** [comment]
See here https://github.com/moneymanagerex/moneymanagerex/issues/5443#issuecomment-1360228604

Take a look at your category list. You have two categories with the same name (case is insensitive). Simply rename one of them or use the relocate feature to merge them, then try the upgrade again.
