### ISSUE TITLE
1.6.3 keyboard shortcuts do not work anymore

### ISSUE THREAD

**Issue by sharkyiwc** [moneymanagerex/moneymanagerex#5615]
MMEX version
 - [x] 1.6.3
Operating System:
 - [x] Windows

# Description of the bug
Hello,

I notice that in the new version 1.6.3 the keyboard shortcuts do not work anymore.

I use Shift+r and there is no reaction.
Is it a bug?
Can I just reconfigure them somewhere?

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

# Additional information
I tested with the portable version 1.6.2 and the shortcuts still work

Thanks

**Comment by tactilis** [comment]
It is a bug - the uppercase letters do not work.

Use the lower case letters:  r / u / d / f / v

**Comment by n-stein** [comment]
This is due to the addition of WXK_SHIFT on this line in the fix for #5549:

https://github.com/moneymanagerex/moneymanagerex/blob/bf359ba09e66388f8cec6ef9591e761c2b29b7be/src/mmchecking_list.cpp#L881

Previous check was for WXK_COMMAND, WXK_ALT, WXK_CONTROL.

**Comment by vomikan** [comment]
Here, perhaps, it is better to replace WXK_SHIFT  with WXK_COMMAND.
My mistake. Sorry.

**Comment by sharkyiwc** [comment]
Thanks for the quick feedback 
I take advantage of the subject to indicate that this information is missing somewhere.
There are options in the contextual menu but no information about the possible keyboard shortcut for this action.

**Comment by gabriele-v** [comment]
I was actively using CTRL+D as shortcut to duplicate transactions, is it possible to have it back?
Otherwise if it conflicts with something else, could you add a new shortcut?

Thanks

**Comment by n-stein** [comment]
@gabriele-v Try ALT+U to duplicate a transaction.

**Comment by gabriele-v** [comment]
Not sure which is the meaning of "U" but it's working

**Comment by n-stein** [comment]
ALT+D was already taken for Delete, so it uses U since it is the second letter of dUplicate.

**Comment by gabriele-v** [comment]
There is already "canc" button, which is a common shortcut for delete, I think ALT+D may be freed up for Duplicate, what do you think?

**Comment by vomikan** [comment]
Alt + U = D**u**plicate
![image](https://user-images.githubusercontent.com/6836805/216826543-c8504431-dd46-4e5d-904d-ea8f152d13a4.png)

**Comment by WebProd33** [comment]
What is the current solution pls to change the colour of a transaction from the transaction view? CTRL+NUMBER does not work for me.
