### ISSUE TITLE
reoccurring transaction error

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#562]
Hi,

in new reoccurring transaction screen, while selecting the account, an error message pops up :"CURRANCYFORMATS_V1:  47 not found".
see attached image
My regards
Avi
![capture](https://cloud.githubusercontent.com/assets/7680483/9954906/718c0cfc-5df5-11e5-80ad-a2a434713f37.PNG)

**Comment by gabriele-v** [comment]
Seems that currency of that account don't exist.. Try to re-set the currency for that account.

**Comment by avma** [comment]
I have checked of course that the account mentioned (as well as all my other accounts) is properly set and has a default currency assigned to it.This error happens with another account too "CURRANCYFORMATS_V1: 29 not found".
Some more information: I have checked of course that the account mentioned (as well as all my other accounts) is properly set and has a default currency assigned to it.This error happens with another account too "CURRANCYFORMATS_V1: 29 not found".

**Comment by gabriele-v** [comment]
Could you provide a sample DB with accounts only (renamed if you want) and cleaned from any transaction?

Send it to moneymanagerex@gmail.com 

Thanks

**Comment by avma** [comment]
sure can...on its way

**Comment by gabriele-v** [comment]
Fixed, will be ok in next version.
This fixes also #568 

https://github.com/moneymanagerex/moneymanagerex/pull/573

**Comment by avma** [comment]
great thanks
