### ISSUE TITLE
update to version 1.6.2

### ISSUE THREAD

**Issue by sirjoe65** [moneymanagerex/moneymanagerex#5624]
MMEX version:
 - [ ] 1.6.0
 - [X ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I'm still using Mmex version 1.6.1.
If I have version 1.6.2 the program tells me it can't update the database. I don't know how to upgrade my database which works with version 1.6.1. to a more recent version. Can someone help me?
Sergio Ferraiolo

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
always

Expected result:
upating database

Actual result:
g
# Additional information
g
If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@sirjoe65
> the program tells me it can't update the database

Please post a screenshot of, or the exact wording of, the error message you get when you try to update MMEX.

The problem can be fixed but we need to see which database upgrade error you are getting.

**Comment by sirjoe65** [comment]
when I try to update mmex 1.6.1 (working) to mmex 1.6.3 this error message appears and I cannot update the program 
![mmex bug](https://user-images.githubusercontent.com/61920723/217797540-7da5a357-afa6-46f6-92af-c97208969fc2.JPG)

**Comment by n-stein** [comment]
You seem to be having two issues:

The one in the screenshot above is an error in the _program_ update, and the message seems to indicate one of the libraries of the current install is still being used by the system. Are you trying to update MMEX to 1.6.3 while version 1.6.1 is still running on your PC? Please close any open instances of MMEX and try the update again.

The issue you mentioned initially seemed to be a database update issue (from DB v16 to v17 going from MMEX 1.6.1 to 1.6.2). Can you post a screenshot of the error you get during the database update?

**Comment by sirjoe65** [comment]
Thanks for the attention.
It is certainly not the first issue. I always close the previous version of mmex. The update asks me if I want to delete it. I answer yes.
As for the second issue, I don't know what to say. The program never asked me to update the database. How should I go about updating the database?

**Comment by n-stein** [comment]
Sorry, I must have misunderstood this line from your original post:

>If I have version 1.6.2 the program tells me it can't update the database. I don't know how to upgrade my database which works with version 1.6.1. to a more recent version

This lead me to believe you had attempted to open your existing database in 1.6.2 but encountered an update issue with the database itself rather than a program update issue.

For the software update issue please try to delete the Money Manager Ex program folder 'C:\Program Files\Money Manager EX' then try the update again.

**Comment by sirjoe65** [comment]
Sorry, I spelled it wrong. I am using version 1.6.1 of mmex . I can't upgrade that version to version 1.6.2 or version 1.6.3.
I always delete the Moneyex folder before installing a new version. It doesn't work the same.

**Comment by n-stein** [comment]
Not sure why it is complaining about a file in use if you have completely deleted the folder from 'C:\Program Files'.

The portable version should work in the meantime.
