### ISSUE TITLE
Please allow `Normal`, `Enlarged`, `Large`, `Huge` to be translatable

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5625]
Please allow list items in `Betűméret` to be translated (i.e. `Normal`, `Enlarged`, `Large` and `Huge`) into Hungarian.

![image](https://user-images.githubusercontent.com/17465872/217923298-5e4cc4e0-dbfd-4d7d-a161-3044327001f8.png)

Thank you

**Comment by vomikan** [comment]
https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=Huge

**Comment by ovari** [comment]
Verified fixed with
```
• Verzió: 1.6.4-Beta.1 64 bites
• Készítési időpont: feb. 16 2023, 03:26:30
• Adatbázis verziója: 17 (aes128cbc)
```

Thank you
