### ISSUE TITLE
Please allow `locale::facet::_S_create_C_locale name not valid` to be translatable

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5626]
Please allow `locale::facet::_S_create_C_locale name not valid` to be translatable. Perhaps something like `%s name not valid` where `%s` is `locale::facet::_S_create_C_locale`.

![image](https://user-images.githubusercontent.com/17465872/217924754-f399fbbd-7347-4af7-a26f-9d7906953230.png)

What do you think?

Thank you

**Comment by vomikan** [comment]
It's already there 
```
        doFormatDoubleValue(locale, result);
        m_sample_value_text->SetLabelText(wxGetTranslation(result));

    catch (std::exception & ex) {
        result = wxString(ex.what());
        result.Replace("std::locale::facet::_S_create_c_locale name not valid", wxTRANSLATE("bad locale name"));
        return false;
    }
```

**Comment by ovari** [comment]
Should `bad locale name` start with a capital letter, i.e.`B`, to become `Bad locale name`?

**Comment by vomikan** [comment]
I don't understand why you have system information displayed at all, and not its analogue.

**Comment by ovari** [comment]
Does this help:

```
Money Manager Ex
• Verzió: 1.6.4-Beta.1 64 bites
• Készítési időpont: feb. 7 2023, 03:26:45
• Adatbázis verziója: 17 (aes128cbc)
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Fut a következőn:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-28-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
I think it wasn't working because the search string had `std::` at the beginning.

**Comment by ovari** [comment]
Suggestion:

Replace `b` with a capital `B` to become:
`result.Replace("std::locale::facet::_S_create_c_locale name not valid", wxTRANSLATE("Bad locale name"));`

**Comment by ovari** [comment]
Verified fixed in
```
• Verzió: 1.6.4-Beta.1 64 bites
• Készítési időpont: feb. 19 2023, 03:26:26
• Adatbázis verziója: 17 (aes128cbc)
```

![image](https://user-images.githubusercontent.com/17465872/219943758-39ce4246-83a1-4ef9-a9d4-86bc2d43867a.png)

Thank you
