### ISSUE TITLE
Please allow title `Currency Manager` to be translatable

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5628]
Please allow title `Currency Manager` to be translatable.

![Currency Manager](https://user-images.githubusercontent.com/17465872/217968788-a373b686-b172-4f72-aa99-a5a093ea2ea8.png)

Steps to show `Currency Manager` window: https://github.com/moneymanagerex/moneymanagerex/issues/3925#issuecomment-1424975978

Thank you

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/5627/files

**Comment by ovari** [comment]
Can you please merge translations from [Crowdin](https://crowdin.com/project/moneymanagerex) before new builds are run at https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex to enable testing?

Thank you

**Comment by ovari** [comment]
Verified fix with
```
• Verzió: 1.6.4-Beta.2 64 bites
• Készítési időpont: feb. 20 2023, 03:27:10
• Adatbázis verziója: 17 (aes128cbc)
```
