### ISSUE TITLE
Transaction not deleted 

### ISSUE THREAD

**Issue by MartinGoike** [moneymanagerex/moneymanagerex#5630]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x] 1.6.3
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

If a Transaction was deleted there is still an entry left in "all transactions" with the  Transaction-Nummer but without data, only Error...
![PXL_20230210_065904573~2.jpg](https://user-images.githubusercontent.com/115636814/218024650-e9a6c660-6d6b-47c1-b82d-690b3e5c7c57.jpg)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Unable to reproduce.

@MartinGoike Could you please:

1. Look in the `Deleted Transactions` view please and show us what is there.

![image](https://user-images.githubusercontent.com/4060092/218034760-596b7b7c-b233-48ab-992f-41cd9adf53df.png)

If you don't see `Deleted Transactions` in the Navigation tree, then you need to turn on this View setting:

![image](https://user-images.githubusercontent.com/4060092/218035247-3895937e-d964-42a6-b454-9fd22f1df690.png)

2. Double click transaction 749 and show us what is displayed on the `Edit Transaction` dialog.

**Comment by MartinGoike** [comment]
https://user-images.githubusercontent.com/115636814/218037461-d7ab9739-8084-46f1-a8c1-0de935831535.mp4

**Comment by n-stein** [comment]
I can reproduce. Try these steps: 

Create a new database
Create an account
Add a transaction
Delete the transaction
Go to Deleted Transactions view
Permanently delete the transaction
Go to All Accounts view --> the transaction is still there with no date, account "Account Error", and payee "Payee Error".

**Comment by MartinGoike** [comment]
exactly 🤷‍♂️

**Comment by MartinGoike** [comment]
Does it make sense to access the database directly and delete the entry in this table shown, or will that cause new problems?

**Comment by n-stein** [comment]
Problem is that we first delete the checkingaccount record, then delete the attachments. But deleting the attachments updates the LASTUPDATEDTIME on the checkingaccount record. Since the checkingaccount record no longer exists, the Model_Checking.get() call returns a pointer to fake_. 

We are checking only whether we get a valid Data pointer (which we do, to fake_), but we are not checking that the Data pointer is to the record we are actually looking for.

**Comment by n-stein** [comment]
Should we move attachment and custom filed data deletion into the Model_Checking::remove() method itself?

**Comment by MartinGoike** [comment]
> Does it make sense to access the database directly and delete the entry in the table, or will that cause new problems?

Did ist with SQLiteSpy. 749 -> 0 = deleted.

**Comment by whalley** [comment]
> Should we move attachment and custom filed data deletion into the Model_Checking::remove() method itself? Right now we do Split Transaction and Translink deletion in there, we could add the others so that when the checking record is deleted, anything that references it is also deleted.

Yes, think that makes sense.

**Comment by n-stein** [comment]
I added this line in the upgrade script for database version 18, so installing 1.6.4 will automatically clean up these phantom records.

`DELETE FROM CHECKINGACCOUNT_V1 WHERE ACCOUNTID = '-1';`

**Comment by MAPA2023** [comment]
Hi Renato, many thanks. 
However I solved the problems by installing a database editor. In fact, this event occurs when, once the data has been deleted, it ends up in the deleted records section and if it is then definitively deleted from there, it leaves the record in the list WITHOUT ANY RELATIONSHIP. By installing the database editor (Db Browser SQL Lite) I solved the problem by deleting the row.

**Comment by MAPA2023** [comment]
I tracked the bug better. It's about this. When you delete an operation it goes to the "Trash". When deleting from the trash the program generates a new line with a new but empty ID. This can only be eliminated with a database editor but not directly from the program.

**Comment by tactilis** [comment]
@MAPA2023

> I tracked the bug better. It's about this. When you delete an operation it goes to the "Trash". When deleting from the trash the program generates a new line with a new but empty ID. This can only be eliminated with a database editor but not directly from the program.

Please note that this is a **Closed** issue. Please read all the comments above. The fix for the bug has already been made and will be included in the next release.
