### ISSUE TITLE
Change `system default` to `System default` and other minor improvements

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5636]
1. Should the [system default](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=0#q=system%20default) string start with a capital letter, i.e. `S`, to be [System default](https://www.microsoft.com/en-us/language/Search?&searchTerm=system%20default&langID=382&Source=true&productid=undefined)?

Thank you

**Comment by ovari** [comment]
Should the following have keyboard accelerators:
2. [Undo](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Undo)
3. [Copy](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Copy)
4. [Paste](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Paste)
5. [Select All](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Select%20All)
6. [Open](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Open)
7. [Home](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Home)
8. [Move Up](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Move%20Up)
9. [View Diagnostics](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=View%20Diagnostics)
10. [Show about dialog](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Show%20about%20dialog) Should `about` start with a capital letter, i.e. `A`, to become `About` (is it a Proper noun?)

What does the following refer to:
11. [N/A](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=N/A): Should `N/A` be changed to `Not applicable`, `Not available` or something else to enable better translations?

Should the space ` ` be removed and the `S` changed to a lowercase letter in:
12. [Web Site](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Web%20Site) to become `Website`? If required, should a keyboard accelerator also be added?

Should the following strings be changed to enable better translations:
13. [Home](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Home) be changed to [Home page](https://www.microsoft.com/en-us/language/Search?&searchTerm=Home%20page&langID=382&Source=true&productid=0)

Thank you

**Comment by ovari** [comment]
Should the following strings start with a capital letter:
14. [please fix attachments folder or delete attachments from WebApp](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=please%20fix%20attachments%20folder%20or%20delete%20attachments%20from%20WebApp)

Thank you

**Comment by ovari** [comment]
Should references to [Home](https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=home) be changed to [Dashboard](https://www.microsoft.com/en-us/language/Search?&searchTerm=dashboard&langID=382&Source=true&productid=0):
15. [Home](https://crowdin.com/translate/moneymanagerex/470/en-hu#783154) → `Dashboard`
16. [Home Page](https://crowdin.com/translate/moneymanagerex/470/en-hu#783974) → `Dashboard`
17. [Account &List (Home)](https://crowdin.com/translate/moneymanagerex/470/en-hu#784010) → `Account &List (Dashboard)`
18. [&Home Page](https://crowdin.com/translate/moneymanagerex/470/en-hu#797574) → `&Dashboard`
19. [Show Home Page](https://crowdin.com/translate/moneymanagerex/470/en-hu#797576) → `Open Dashboard`

Thank you

**Comment by ovari** [comment]
Additional strings from https://github.com/moneymanagerex/moneymanagerex/issues/5590#issuecomment-1407653650
15. `Cut` → `Cu&t`
16. `Redo` → `&Redo`

**Comment by vomikan** [comment]
These words must be one to one, otherwise it will not work.

![image](https://user-images.githubusercontent.com/6836805/218311731-bd36ef73-1032-4f4e-8d50-c78115c7cb58.png)

**Comment by vomikan** [comment]
https://github.com/vomikan/moneymanagerex/commit/f2a6be62c20b2c92d6e6c9902d90a0beb278b4a2

**Comment by ovari** [comment]
Can [system default](https://crowdin.com/translate/moneymanagerex/470/en-hu#784102) please be changed to `System default`?

**Comment by ovari** [comment]
Can the trailing newlines `\n\ please be removed from https://crowdin.com/translate/moneymanagerex/470/en-hu#783346 ?

**Comment by vomikan** [comment]
> Can [system default](https://crowdin.com/translate/moneymanagerex/470/en-hu#784102) please be changed to `System default`?

Already there

**Comment by ovari** [comment]
Can `Open the Money Manager EX website for latest news, updates etc` be changed to `Visit MMEX website`

**Comment by ovari** [comment]
>> Can [system default](https://crowdin.com/translate/moneymanagerex/470/en-hu#784102) please be changed to System default?

> Already there

Does it need updating in appstartdialog.cpp:201 ?

**Comment by ovari** [comment]
What does [Home](https://crowdin.com/translate/moneymanagerex/470/en-hu#783154) refer to? Is it `Dashboard` or something else? Thank you

**Comment by vomikan** [comment]
> What does [Home](https://crowdin.com/translate/moneymanagerex/470/en-hu#783154) refer to? Is it `Dashboard` or something else? Thank you

db/DB_Table_Category_V1.h:150 
it's categories

![image](https://user-images.githubusercontent.com/6836805/218333413-8c05fdc9-a0c9-4d3e-a398-d8264638cfe6.png)

**Comment by ovari** [comment]
Should a keyboard accelerator be added to [Move Up](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=Move%20Up)?

**Comment by ovari** [comment]
Should a keyboard accelerator be added to [View Diagnostics](https://crowdin.com/translate/moneymanagerex/all/en-hu?filter=basic&value=7#q=View%20Diagnostics)?
