### ISSUE TITLE
Negative zero balance

### ISSUE THREAD

**Issue by sempiternum** [moneymanagerex/moneymanagerex#564]
I noticed that recenlty i get a "negative" zero balance, instead of a normal 0.00[currency] balance.

Screenshot provided

![2015-09-25_11-38-37](https://cloud.githubusercontent.com/assets/5978745/10097586/42bc9ea2-637a-11e5-9467-fcec9a486cb3.png)

**Comment by vomikan** [comment]
we used wxNumberFormatter::ToString function. Seems the bug outside of mmex.
