### ISSUE TITLE
Imported transactions from webapp not working correctly

### ISSUE THREAD

**Issue by 5ky0ne** [moneymanagerex/moneymanagerex#5641]
Hi,
MMEX version:
 - [x] 1.6.2
 - [x] 1.6.3

Operating System:
 - [x] Windows

# Description of the bug

The transaction's import from WebApp doesn't work as expected: instead of downloading all the transaction, it downloads the first one (with import set at 0) a number of time equals to the transaction you have in WebApp. For example, if I have these 3 transaction in the WebApp:
10/02/2023 Withdraw MyCount SuperMarket 9,99
11/02/2023 Withdraw MyCount OtherMarket 14,35
11/02/2023 Withdraw MyCount GasStation 21,25

When I sync and I choose "Import all", in the Desktop version I have:
10/02/2023 Withdraw MyCount SuperMarket 0,00
10/02/2023 Withdraw MyCount SuperMarket 0,00
10/02/2023 Withdraw MyCount SuperMarket 0,00

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
Insert some transaction in WebApp and sync it with the Desktop version.

Expected result:
See before

Actual result:
See before

# Additional information
The first time I saw the problem, I already have transaction in the Desktop version, but I saw that there's not connection between the transactions you already have in Desktop and the ones you have in the WebApp.
In addition, the transactions in the WebApp are not deleted (so in the next syncs you'll have them again and again).

Regards.

**Comment by vomikan** [comment]
Test
![image](https://user-images.githubusercontent.com/6836805/218312948-f273fa50-b9f0-4c42-930d-103cca5bbed9.png)

![image](https://user-images.githubusercontent.com/6836805/218313027-8059259d-9125-4c17-9f19-5666b56c1800.png)

![image](https://user-images.githubusercontent.com/6836805/218313103-01de925a-5dce-42e7-bb2d-7d1b9f9bea06.png)

**Comment by 5ky0ne** [comment]
I tried again: 
![Immagine 2023-02-12 173411](https://user-images.githubusercontent.com/69081539/218324028-ade24e64-8788-4d3f-b14e-0c70c8193238.jpg)

![Immagine 2023-02-12 173430](https://user-images.githubusercontent.com/69081539/218324055-017c13ba-1964-412a-97fd-ae455821e2c6.jpg)

The web version is 1.0.4 (the last one at https://github.com/moneymanagerex/web-money-manager-ex/releases ) but I see that your is different: do I have to change something?

**Comment by vomikan** [comment]
I am using Docker and 
Version 1.2.1
API Version 1.0.1

**Comment by n-stein** [comment]
The last release is 1.0.4, but the codebase is up to 1.2.1. 

I suggest we release 1.2.1 officially in web-money-manager-ex to clear up the confusion.

**Comment by whalley** [comment]
Agreed. v1.2.2 released https://github.com/moneymanagerex/web-money-manager-ex/releases/tag/v1.2.2

**Comment by 5ky0ne** [comment]
After the upgrade, everything works well. Thank you so much!
