### ISSUE TITLE
Show count of selected/filtered/total records in the view

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#5656]
When I run a transaction filter, MMEX efficiently lists transactions
I want MMEX to display a count of 
1. Selected records
2. Filtered records (if any filter is applied)
3. Total records in the database (for the account or all as per the selection on left navigation)

# Use cases
It's handy when comparing the imported records with excel

**Comment by tactilis** [comment]
You can already display the information you are asking for.

> I want MMEX to display a count of
>  1. Selected records

This figure is already displayed at the bottom of the screen:

![image](https://user-images.githubusercontent.com/4060092/218522254-a3ded497-866f-4bfe-a5b0-df05bc26c626.png)
<br><br><br>
> 2. Filtered records (if any filter is applied)

If you press CTRL+A to select all, then the number of selected records displayed will be the number of filtered records:

![image](https://user-images.githubusercontent.com/4060092/218522453-1433f783-111a-4982-a98f-4979270203bd.png)
<br><br><br>
> 3.  Total records in the database (for the account or all as per the selection on left navigation)

If you `View All Transactions` and then CTRL+A you can see the total number of records:

![image](https://user-images.githubusercontent.com/4060092/218522901-6d4862a1-7383-4f0d-8e16-bdbeb64eb0f6.png)
<br><br><br>
Admittedly it's not as convenient as displaying all the information you have requested together - but it does avoid cluttering the display with extra information that maybe only a few people would need to see.

> It's handy when comparing the imported records with excel

I'm wondering what the need is to keep comparing MMEX records with Excel?
Presumably you are importing a CSV produced by Excel. You will know at the point of import whether the action was 100% successful or whether any rows were flagged as errors.

Just trying to understand your workflow.

**Comment by sarjanwebdev** [comment]
Thanks 
That's really helpful
