### ISSUE TITLE
Can't read database in Linux version

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#566]
Please see 
https://github.com/moneymanagerex/android-money-manager-ex/issues/536
and
https://github.com/moneymanagerex/android-money-manager-ex/issues/517

**Comment by vomikan** [comment]
May be it the same issue? https://github.com/moneymanagerex/moneymanagerex/issues/584

**Comment by MisterY** [comment]
No, these three cases are quite distinct and unique.
Only #517 remains a mystery. Some files are just not readable with certain SQLite versions. 
The other two cases are solved.

**Comment by guanlisheng** [comment]
would we close this issue now ?

**Comment by MisterY** [comment]
I have not heard from the affected users so I'd say yes. Next time I'd like them to file an issue directly on GitHub and follow up.

**Comment by guanlisheng** [comment]
thanks @MisterY , in this case, I will close this issue soon.
