### ISSUE TITLE
Do no show triangle (arrow) next to `Dashboard` as it does nothing

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5660]
Clicking on triangle (arrow) next to `Dashboard` does nothing.

![image](https://user-images.githubusercontent.com/17465872/218389089-b08215b9-d01a-4827-9d02-5d0bae07ed0a.png)

```
Money Manager Ex
• Version: 1.6.4-Beta.1 64-bit
• Built on: Feb 13 2023 03:26:28
• Database version: 17 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-28-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
#4483

**Comment by ovari** [comment]
Thank you for you link. Updated issue to: `Do no show triangle (arrow) next to Dashboard as it does nothing`

@vomikan can the duplicate tag be removed?

Thank you

Linux Mint 21.1 Cinnamon

**Comment by whalley** [comment]
> Thank you for you link. Updated issue to: Do no show triangle (arrow) next to Dashboard as it does nothing

As noted here: https://github.com/moneymanagerex/moneymanagerex/issues/4483#issuecomment-1140425305 removing it may not be possible. It's a very very minor UI artefact, my suggestion is we leave it and close this issue.
