### ISSUE TITLE
`User interface language: ` in `About` dialog

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5661]
Please add the `User interface language: ` to the About dialog, for example:

```
Money Manager Ex
• Version: 1.6.4-Beta.1 64-bit
• Built on: Feb 13 2023 03:26:28
• Database version: 17 (aes128cbc)
• User interface language: System default - English (Australia)
```

![image](https://user-images.githubusercontent.com/17465872/218389640-4431fedc-796a-481a-a2b1-a0a068dced3b.png)

What do you think?

Thank you

**Comment by whalley** [comment]
It's there...

![CleanShot 2024-02-14 at 16 56 42](https://github.com/moneymanagerex/moneymanagerex/assets/487345/2ff9de6e-380d-418c-9727-24569bb5bf31)
