### ISSUE TITLE
BUG when update to V15/16

### ISSUE THREAD

**Issue by gerardmmex** [moneymanagerex/moneymanagerex#5662]
MMEX version:
 - [ x] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
I was working on V0.9.8.0 on IMAC. I have now a mac book and i have downloaded the V16.0
When i open MMEX with the option "database already exist" i got on error : SQL LOGIC ERROR (1) no such table report_v1
Maj version 15 Failed

I have tried to downloas the V14 but it was not possible.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
Use the V16 with my database
Actual result:
The database conversion failed
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
Maybe this helps: https://forum.moneymanagerex.org/viewtopic.php?t=10776

**Comment by gerardmmex** [comment]
Hi,

I have done the database update but i still have the bug.

**Comment by renato-mmex** [comment]
a screenshot would help us

**Comment by gerardmmex** [comment]
database after deleting the view



Message when i lauch MMex V1.6

**Comment by n-stein** [comment]
In SQLITEBrowser what is the output of the command `PRAGMA user_version;` ?

**Comment by gerardmmex** [comment]
The result is.    14


Envoyé depuis Yahoo Mail pour iPad


Le lundi, février 13, 2023, 4:40 PM, n-stein ***@***.***> a écrit :




In SQLITEBrowser what is the output of the command PRAGMA user_version; ?

**Comment by n-stein** [comment]
After your upgrade fails, it will ask if MMEX has provided a debug/patch file. Select "Yes", then use this file (unzip it first).
[fix-5662.zip](https://github.com/moneymanagerex/moneymanagerex/files/10725956/fix-5662.zip)

That will recreate the REPORT_V1 table that the upgrade script is looking for. Then try the upgrade again and it should succeed.

**Comment by gerardmmex** [comment]
Hi,

It ’s OK now

Thanks
