### ISSUE TITLE
Allow Transaction Filter to filter for SPLIT transactions

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#5667]
Pretty much self explanatory.
Add a checkbox to dialog and filter accordingly if Split transaction is checked or not.

**Comment by tactilis** [comment]
The request is clear but please could you say under what circumstances you would use this additional filter?

i.e. Why is it important to be able to filter for display:

a) Transactions that have a split?
b) Transactions that do not have a split?
<br><br>
As an aside, there is already a fairly simple means by which you can group (and optionally highlight) split transactions...

1. Starting with transaction list, which could be a filtered list if you wish, ordered by Date.
Note that the split transaction category lists are preceded by \*

![image](https://user-images.githubusercontent.com/4060092/218691897-964732e4-77ed-4ef3-aeeb-1a8c0ba7b7d6.png)

2. Click on the Category header to sort by that column. Note that this groups all the split transactions together.

![image](https://user-images.githubusercontent.com/4060092/218693942-48f0e587-19a0-49c0-98ce-d0f51f077eab.png)

3. If you wish to highlight the split transactions, click/Shift+click to select them and apply a colour (CTRL+1 to CTRL+7).

![image](https://user-images.githubusercontent.com/4060092/218694012-95f1ebf1-f8a1-47e0-9f47-c916ffeeaedc.png)

4. If you wish to see them in their correct date order, click on the Date column header.

![image](https://user-images.githubusercontent.com/4060092/218694097-741fd70e-51fe-4a74-94b3-422ebc56ebde.png)
