### ISSUE TITLE
Move View Diagnostics Information to About Dialog

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5669]
There has been some work recently to improve the content and layout of the About Dialog. Would it make sense to remove the Help -> View Diagnostics dialog, and put its content into the About Dialog instead?  I've never seen anyone ask for the diagnostic info to troubleshoot an issue, but just an idea to centralize it with other information about the user's environment.

**Remove:**
![image](https://user-images.githubusercontent.com/95182117/218623801-e2a90cd8-c507-449c-97dc-891c2d8b4223.png)

**Add**
![image](https://user-images.githubusercontent.com/95182117/218624045-dc4432c7-b781-4168-b3ed-ef92d6402b1f.png)

**Comment by reddyshyam** [comment]
Diagnostics is a rare request and needed only to debug something while the rest is mostly used to check the version and other relevant information.

Why unneccessarily add more data to about dialogue when we are sure it will not be need 90% of time. Just my 2 cents. Will leave it for experts to comment.

**Comment by tactilis** [comment]
> I've never seen anyone ask for the diagnostic info to troubleshoot an issue

But others have.

The screen geometry diagnostic information was added to help resolve a difficult to solve bug.

The diagnostic information displayed may be changed in the future to help investigate other problems.

The diagnostic information may be altered on a specific test build targeted at certain users.

IMO it does not make sense to add it to the About tab.

**Comment by rmelillo76** [comment]
Hi @tactilis  and @reddyshyam thanks for your feedback and unless the developers feel there would be a benefit, we can close this item. Since Operating System and screen resolution is on the About Dialog it seemed to fit in but I understand your points. Thank you.
