### ISSUE TITLE
Minimum account balance

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#567]
A request from the users for implementation of the minimum account balance. The user is notified if the new transaction would bring the balance below the set minimum.
This would require a new field, so I'm adding a request here. Related issue for Android - https://github.com/moneymanagerex/android-money-manager-ex/issues/547.

>for second one is to set the "minimum balance for checking A/C".
it could be works as reserve for checking a/c's.
if a checking A/c having balance of INR 100000, and is set at minimum balance like "INR 10000". then this function will stop the transaction from this A/c, after spending INR90000.
It looks like reserve for A/c.

**Comment by gabriele-v** [comment]
I think that we have finally to decide a common and simple way to patch DB adding\removing\updating filelds.

@guanlisheng what do you think? We already spoken about it but without any decision

**Comment by MisterY** [comment]
I would contribute some thoughts from this issue - https://github.com/moneymanagerex/database/issues/4

As Android provides a convenient way to upgrade a database, by providing an onUpgrade method that gets executed when the database needs to be upgraded and provides both old and new version numbers, it is very easy to upgrade by calling only the migration scripts for the missing versions.

Each migration would be a separate script, for example "database_version_x.sql" and on upgrade we would loop `for version = oldVersion .. newVersion` and execute any "database_version_" + version + ".sql" scripts.
I find this by far the most convenient way and easy to implement on all platforms.

The thing to keep in mind would be to maintain the db version information at two location or to use the default PRAGMA UserVersion, provided by SQLite. Android SQLite libraries use this pragma to maintain the version information whereas in desktop version we use a value in the info table. Let me know how easy it is to read/write pragma values and perhaps this could be the most practical way.
Pragma values are available before any tables are created and should be more reliable than a value in a table, technically.
Just my $0.02.

**Comment by guanlisheng** [comment]
@gabriele-v  i'm fine if we could find a easy way to patch database.

**Comment by stef145g** [comment]
This feature has now been completed. Edit the account to set the initial values.

Extra account data is stored for each account in the table: INFOTABLE_V1 using json string variables.
The implementation contains: Credit Limit and Minimum value. The difference is that the Credit limit will be used as a negative value.

**Comment by stef145g** [comment]
Completed. The extra account information has been added to the accounts table, without JSON data.

**Comment by MisterY** [comment]
Great. I've updated the db schema to v7 in the mobile app.
