### ISSUE TITLE
Problems when changing language

### ISSUE THREAD

**Issue by viniciostorres** [moneymanagerex/moneymanagerex#5671]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [] 1.6.2
 - [ ] 1.6.3 Beta
 - [X ] Other (please specify) 1.6.3 64-bit

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [X ] Linux 

# Description of the bug
I have installed in a Ubuntu 20.04 machine with default language to Portuguese Brasil. When I changed to English American the home page doesn't appear and it shows the following dialog.

![image](https://user-images.githubusercontent.com/1395631/218904805-af6f8af1-dbc2-4a88-9f07-b02a9d905e13.png)

All Reports links has the same behavior.

**Comment by ovari** [comment]
Reproducible with Linux Mint 21.3 Cinnamon.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/c59587e5-4602-48ad-aa16-10f47d338ac1)

MMEX, Menu Bar, Help, About, `mmex Error` (see image below)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/5bd00e6f-9818-4967-b90c-bea691761780)

**Comment by ovari** [comment]
@viniciostorres is this still reproducible with 1.7.1-RC.1? Thank you

**Comment by ovari** [comment]
It seems that the file is located in a temporary `/tmp/` directory. Temporary directories delete files without user action.

**Comment by viniciostorres** [comment]
@ovari:
I did some tests (Version  1.7.0 64-bit, Ubuntu 20.04) changing languages and it works well. Even after the reboot of the computer the changes remain and the program shows no errors.

**Comment by ovari** [comment]
@viniciostorres can you please close this issue? Thank you
