### ISSUE TITLE
Calculation balance

### ISSUE THREAD

**Issue by sharkyiwc** [moneymanagerex/moneymanagerex#5673]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x ] 1.6.3
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Hello,

I discover the problem of calculation in the balance!

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Here are 2 examples with erroneous results, Excel comparison
Expected result:
See picture
![mmexBalance](https://user-images.githubusercontent.com/251279/219124063-0ab91756-ffe8-4c75-8541-6797ed55707c.png)
Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by sharkyiwc** [comment]
Hello,
I think I forgot some details.
Often it is clear for the one who writes, but not necessarily for the others. I'm sorry.
In my display, the chronology is from bottom to top.
Bottom right, a balance of 786.63 minus a debit of 304.2
mmex = 430.33 ??
by calculating 786.63-304.2=482.43
difference of the calculation 52.1

I tested
A balance of 786.63 plus a credit of 304.2
mmex = 1038.73 ?
calculating 786.63+304.2=1090.8
difference of the calculation 51.9

**Comment by tactilis** [comment]
You have most likely sorted the transaction list by a column other than Date. On which column header is the up/down arrow? And what does the Sort Order text say?

Click on the Date header to sort by Date.  Click again to toggle between ascending/descending.

![image](https://user-images.githubusercontent.com/4060092/219319606-8e1c08a2-dbc9-4e9e-8e18-403c82a0bcc1.png)
 
 
Balance OK now?

**Comment by sharkyiwc** [comment]
Hello,
Indeed, by clicking 2x on the sort by date it was updated.
But it was already in this sorting by date!!
Thanks for the solution

**Comment by tactilis** [comment]
> Indeed, by clicking 2x on the sort by date it was updated.
> But it was already in this sorting by date!!

@whalley I think we have seen this a few times before. After people update to a new version, it _appears_ that the Date+ID sorting is not always applied, even though people report that the sort arrow _is_ on the Date column. Re-sorting on Date fixes it. Any ideas?

@sharkyiwc Which version were you using prior to updating to 1.6.3 please?

**Comment by sharkyiwc** [comment]
Yes, 1.6.3

**Comment by tactilis** [comment]
@sharkyiwc
> 1.6.2 upgrade to 1.6.3

Do you know _for certain_ that the balance display was correct when you were using 1.6.2?  Or might it have been wrong there too?

**Comment by sharkyiwc** [comment]
I don't know if you are talking about before the update
or back to 1.6.2
The update, I did it a week ago and I noticed the problem yesterday.
When I went back to version 1.6.2, the error was still there.

**Comment by whalley** [comment]
Think this is resolved, so closing
