### ISSUE TITLE
Reoccurring transaction strange behavior

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#568]
Hi, 

Poking around 'Reoccurring Transaction' i noticed a strange behavior: While editing an existing Reoccurring Transaction (see attachment #1),  after selecting an account from the drop down box and pushing the OK button (see attachment #2), the transaction amount changes as well as the numbers format from #,###.00 to #.###,00 (see attachment #3).

My best regards
Avi
![recurr_1](https://cloud.githubusercontent.com/assets/7680483/10229246/d0ee6c28-687f-11e5-9046-ebd562017321.PNG)
![recurr_2](https://cloud.githubusercontent.com/assets/7680483/10229247/d0ef5584-687f-11e5-92ab-ed5e9536c09b.PNG)
![recurr_3](https://cloud.githubusercontent.com/assets/7680483/10229245/d0ebca36-687f-11e5-8ade-b781ff1bd1a3.PNG)

**Comment by gabriele-v** [comment]
Fixed PR #573
