### ISSUE TITLE
Budget view crash on double click category summary

### ISSUE THREAD

**Issue by Martin-H-42** [moneymanagerex/moneymanagerex#5686]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.3 64bit
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 10 build 19045 64bit
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In the category view, double click on a category summary line (the dark blue line) and mmex crashes.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

- Open category view
- Double click onto category summary (dark blue line) (example: user accidentally clicks on summary and not on individual category entry).
- mmex crashes, debug send report dialog opens.

Expected result:

- mmex doesn't crash, nothing happens because you cannot click these entries.

Actual result:

- mmex crashes

# Additional information

Will send a debug log linking with this github issue

**Comment by tactilis** [comment]
Crash confirmed when double clicking on any of the blue/grey lines:

![image](https://user-images.githubusercontent.com/4060092/219968654-96f64d0d-2522-4425-b4d8-10d7c9542f3d.png)

**Comment by vomikan** [comment]
Moreover, if there are no budgets, then the program crashes when creating the first one, but the budget is created.

![image](https://user-images.githubusercontent.com/6836805/219971476-a4107ddc-4dcb-4971-aabc-450a72d729c2.png)

![image](https://user-images.githubusercontent.com/6836805/219971538-fcd81286-4f45-4e33-9119-a967da33d1e8.png)
