### ISSUE TITLE
mmex 1.6.2 and 1.6.3 crash on Mac OS X 10.11

### ISSUE THREAD

**Issue by MacTerrassa** [moneymanagerex/moneymanagerex#5692]
MMEX version: 1.6.2 and 1.6.3 stable
 
System 10.11.6 on iMac Intel Core 2 Duo (2007) 2,4 GHz

I have had the program installed for some time, and apart from testing some function I have not used it so far. It has always opened correctly for me, and the initial page talks about system 10.9 as a basic requirement.

I have upgraded to version 1.6.2 and have not checked. When updating to 1.6.3 and trying to open the program it hangs, it generates two alert windows that invite me to create a report, but none of them allow me to do anything, nor do their buttons work.
If I go to the dock and select exit, it doesn't work. I can only exit by forcing exit from the keyboard.

I reset version 1.6.2 again and it opens without alert, but it doesn't show any window and it doesn't allow me to quit without forcing quit either. Deleting all user library folders, preferences and hidden files I can't start the program either. 

Finally, if I delete everything again and reinstall version 1.6.1 if it opens correctly again, it allows me to create a document for my data and the buttons work.

I am attaching two of the files created by the program when it started, and to which one of the alerts that the report created pointed to.

Is it possible that the program requirements have changed, and you need a new system to run? Is it some other problem that they can fix? Regards and thanks for the help.

[MoneyManagerEx2.txt](https://github.com/moneymanagerex/moneymanagerex/files/10784585/MoneyManagerEx2.txt)
[MoneyManagerEx.txt](https://github.com/moneymanagerex/moneymanagerex/files/10784586/MoneyManagerEx.txt)

**Comment by whalley** [comment]
Seems to be wxsqlite3 related and coincides with the module update in v1.6.2.  Will dig a bit deeper.

**Comment by whalley** [comment]
Seems an issue under 10.11 that was never successfully resolved.... https://github.com/utelle/wxsqlite3/issues/53

**Comment by MacTerrassa** [comment]
I'm waiting for the iMac to be renewed to change the hardware, but then the logical thing if the program has bugs with certain systems would be to report it, and perhaps recommend a previous version that can continue to be used. 

I understand that the requirements change over time, even if I don't particularly like it, but if a compatible and functional previous version is offered, even if it is without the news and improvements of the new versions, it is something to be appreciated.

For me, all software, paid or not, should allow the use of previous versions and maintain a minimum support for them. Hacking and banning that use, or not correctly reporting the requirements to use it correctly is the main form of planned obsolescence today. What's more, many no longer even bother to indicate the correct systems or conditions of use, simply "a current version" whatever that minute of the day you read the help. That is why more and more, I am abandoning paid software: if they don't even bother to tell me how to use it, I don't need to pay them anything.

And although free software is different, and I thought they offered a better product in many cases, I see that they have also caught the obsolescence virus. Any software needs a minimum to use it well, and the logical thing to do is to report those conditions. And offer solutions if possible in those cases where there are previous versions that may be of interest to many users.

In programs like yours, which also maintain access to download previous versions, all or most of them, I just don't understand that when those requirements change, it is easily indicated on the main page: current version needs system X.x, and for the following previous systems, the final versions to use will be these: version 2 for system 10.7, version 3 for systems 10.8 to 10.10... for example.

And obviously, when you can, you are interested in the changes and so on, everyone can update the hardware when necessary. But now that there is so much talk about ecology and such, it seems very important to me to be able to continue using the old hardware in tasks that can simply give a new use to an already old product, but fully functional on the other hand. That is the true green condition.

Thanks for the help, and the interest shown. All the best.

MacTerrassa

P.S. Message translated mechanically as I do not speak English, I apologize if I have not expressed myself correctly.

**Comment by tactilis** [comment]
@MacTerrassa
> And although free software is different, and I thought they offered a better product in many cases, I see that they have also caught the obsolescence virus. Any software needs a minimum to use it well, _**and the logical thing to do is to report those conditions. And offer solutions if possible**_ in those cases where there are previous versions that may be of interest to many users.

Agreed - but the problem has _only just_ been reported as occurring in MMEX 1.6.2, so your long comment above is a little unfair.

And it's not actually an MMEX issue.

As @whalley says:
> Seems to be wxsqlite3 related and coincides with the module update in v1.6.2. Will dig a bit deeper.
> ...
> Seems an issue under 10.11 that was never successfully resolved.... https://github.com/utelle/wxsqlite3/issues/53

(wxsqlite3 is a wrapper around the SQLite 3.x database and is specifically designed for use in programs, such as MMEX, based on the wxWidgets library)

**Comment by whalley** [comment]
@MacTerrassa Understand your frustration. I'll look to add a compatibility page and reference it from the website download page. Unfortunately we don't have the resources to test against such a large range of operating systems and rely on user feedback in many instances, so thanks for flagging this one up.

**Comment by MacTerrassa** [comment]
> And it's not actually an MMEX issue.

Hello, I think so. It's one thing if the problem isn't in the code directly written by you for MMEX, making it difficult to solve even if it were possible. And another, that if the external libraries used in the program have different requirements, they have to take that into account. I have tried with system 10.11, and its initial page specifically mentions 10.9, what happens with intermediate systems? Have you been affected by this bug, or were they no longer supported for more versions? That is my "anger". It seems that the initial page indicates the requirements of the initial version, but that it has not been rewritten as new versions are released.

I understand that support cannot be maintained over time, but then it is indicated. And if, as seems to be the case, they have versions that are compatible with previous systems, indicate it and that's it. All happy. And we continue to appreciate your work. Whoever uses more modern systems will install the current version, whoever is not the case will look for the appropriate version. Because also, I understand that the program does not depend on a server or any other external requirement, if there was a version compatible with 10.9, today it could be reinstalled and used correctly. Maybe not with the improvements and changes made later, but it can be useful to those who stay with that system, or those in between.

I also see this as one of the strengths of your free programs: offering solutions to old and obsolete systems is not bad for you. It is something that many will take into account. Myself, when I pay for a license I always prefer those programs that offer me the facility to continue using the old systems, and in the most current machines I use the new one... For example: when I replaced Aperture with Capture One, the main reason was that with the subscription they offered to use it in the old iMac with an earlier version and other more current ones in the second. What's more, I'm still using a fourth iMac with 10.4 only for a custom accounting program, and when it comes down to it, it's the one I use the most on a daily basis. 

No problem to this day, although it is true that I am considering changing it for a new one when they release the iMac M2 or M3 and finally updating the professional accounting program.

Regards

**Comment by MacTerrassa** [comment]
> Understand your frustration. I'll look to add a compatibility page and reference it from the website download page. Unfortunately we don't have the resources to test against such a large range of operating systems and rely on user feedback in many instances, so thanks for flagging this one up.

I appreciate you creating and facilitating a useful program for so many of us. I understand that they are voluntary and that support may not be the same as paid support in some cases. But I also think that they should be aware of the requirements of their new versions. It is logical that these requirements change over time, both due to the functions they use or add, as well as the external libraries used, as is the case.

And although I would like more if I could solve it :-), I understand that it is not always possible or that the necessary work implies more than what you can do, especially if we take into account that the problem comes from something external to the program itself. But if they indicate it on their website, if they also offer indications of which version is compatible with which systems, and they continue to be downloaded, I think it is something interesting for everyone. And that also reduces part of the work. If it is not indicated, I would think that many have been asking and have to bother to answer individual questions about something that could be indicated on a single occasion and useful for everyone instead.

Thank you both for your help. And of course, to all the collaborators of the program for making it available to everyone. All the best.

**Comment by tactilis** [comment]
@MacTerrassa You have made similar style comments on github over the last few years against a number of other projects that no longer work with your computer/OS version.

The sad fact is that your computer (released in 2006) is now very old and its operating system (OS X) is no longer maintained, having been superseded by 7 subsequent releases of MacOS.

> _**I would think that many have been asking**_

This is an incorrect assumption. It not an issue that has been raised much in relation to MMEX.

> and have to bother to answer individual questions about something that could be indicated on a single occasion and useful for everyone instead.

@whalley has already said he will look to add a compatibility page but for the reasons he stated it will be dependent on user feedback to report are any problems with old hardware/OS combinations.

**Comment by whalley** [comment]
https://moneymanagerex.org/docs/downloads/compatibility/

**Comment by tactilis** [comment]
> https://moneymanagerex.org/docs/downloads/compatibility/

That's great.

A couple of minor nits:

Double use of 'noted' and odd sentence break.

![image](https://user-images.githubusercontent.com/4060092/220859330-673dc7a6-02c7-46b7-a916-57b8c912a4b1.png)

**Comment by MacTerrassa** [comment]
> You have made similar style comments on github over the last few years against a number of other projects that no longer work with your computer/OS version.
> 
> The sad fact is that your computer (released in 2006) is now very old and its operating system (OS X) is no longer maintained, having been superseded by 7 subsequent releases of MacOS.

My complaints are not just that the latest version doesn't work on my system, to some extent I understand why it doesn't. But that the changes and the actual requirements of today are not indicated. And that they do not take the opportunity to indicate that previous versions can be used in previous systems. The linked page was precisely the answer I was looking for, thanks.

Perhaps in MMEX there weren't many queries, but many other programmers tell me that it is precisely these complaints that lead them to abandon support. In some cases, even answering that their program works on my system, but since they cannot provide a solution for all combinations of hardware and system, they choose to change their official requirements, even though they still really work.

Regards

**Comment by whalley** [comment]
> A couple of minor nits:

Fixed, thanks for proofreading.
