### ISSUE TITLE
Last Updated Display Format

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5698]
Should the 'Last Updated' field be displayed in the user's preferred Date Format? Currently it appears to always display as YYYY-MM-DD HH:NN:SS:

![image](https://user-images.githubusercontent.com/95182117/220632520-2e458074-4c95-4871-a661-5dd21142ce15.png)

![image](https://user-images.githubusercontent.com/95182117/220632674-4bcdcbe1-2c4b-489d-8fbc-e61e289b807a.png)

(while still using HH:NN:SS for the time portion)

I'm not sure if the current format was chosen for sorting purposes.

**Comment by n-stein** [comment]
Done for both Last Updated as well as Deleted Time.

![image](https://user-images.githubusercontent.com/16599929/220718457-cab8e830-36f5-4a13-8072-3f6e4d4cd623.png)
![image](https://user-images.githubusercontent.com/16599929/220718538-df977a3b-80f7-43f2-8108-c2fe452bd654.png)


![image](https://user-images.githubusercontent.com/16599929/220718834-431de988-8c5d-4402-8bb0-6a75972864d3.png)
![image](https://user-images.githubusercontent.com/16599929/220718892-8404ea71-70b2-49b0-a145-4fc1f46464c5.png)

**Comment by rmelillo76** [comment]
Looks good - thanks @n-stein !
