### ISSUE TITLE
[Feature Request] Ctrl + Enter to finish transaction entry and create next one.

### ISSUE THREAD

**Issue by Adelzu** [moneymanagerex/moneymanagerex#5716]
When entering a long list of entries into an account. It would be way easier to finalize a transaction in the New Transaction Dialog by pressing Ctrl + Enter (or Command + Enter on a MAC). This will should automatically click the "OK" button and if the app is configured to add another transaction next it will open the page again.

**Comment by tactilis** [comment]
This exists already.

Instead of just clicking OK to finish the transaction, hold down Shift while clicking OK and it will save the current transaction then pop up the dialog ready for the next.

If you want this behaviour to be the default (i.e. pop up a new dialog when you click OK), then on the Options | Others page turn on Bulk Transactions:

![image](https://user-images.githubusercontent.com/4060092/221622161-e471c9f5-6c0c-4403-8a95-1b7d0df92988.png)

You can then press Shift when clicking OK to signal that the transaction you just entered is the last in the sequence (or click Cancel to cancel the new dialog)

**Comment by Adelzu** [comment]
> This exists already.

No, you misunderstood the request.
In order to add the transaction, you have to either tab your way to the ok button then press enter, or use the mouse. Both are annoyingly slow.
Adding a quick "OK" shortcut by using CTRL + ENTER (or COMMAND + ENTER on MAC) makes the process easier.

**Comment by tactilis** [comment]
@Adelzu 

Press Alt+O

That is the standard shortcut key for the OK button.

See the underlined letter:

![image](https://user-images.githubusercontent.com/4060092/221643005-25545ccd-1509-4168-abcb-780376f7cf1e.png)

**Comment by tactilis** [comment]
@Adelzu 
> @whalley, i'm not sure this would be the right label.

`question` is the right label.

It's a question button shortcuts, which is an existing Windows & MMEX capability.

**Comment by rmelillo76** [comment]
@Adelzu you may also want to refer to https://github.com/moneymanagerex/moneymanagerex/issues/5314. That's an item I had created a while back with a similar request. I have since gotten used to ALT+O and it is pretty quick to save each new transaction.

**Comment by Adelzu** [comment]
> Press Alt+O

This! Thank you @tactilis & @rmelillo76. On Mac, the "O" is not underlined so i didn't think something existed.

**Comment by tactilis** [comment]
> On Mac, the "O" is not underlined so i didn't think something existed.

In Windows, when you press the Alt key, menu and dialog shortcut keys become underlined. I understand that there is no equivalent in MacOS.

Does this help at all with dialog shortcuts? Or does it just show menu shortcuts in MacOS?

https://www.mediaatelier.com/CheatSheet/

**Comment by njwgh** [comment]
A workaround that I use.
I use 'Autohotkey' to map 'Alt O' to the 'Enter' key when in popup dialogs in mmex

Then pressing 'Enter' will save the transaction.  A side-effect of this is that the 'Enter' key won't work in the 'Category' field to open the 'manage category' screen, but I seldom need this so Enter is way more useful to me as a 'save' command

The command for autohotkey is:

`#IfWinActive, ahk_class #32770 ahk_exe mmex.exe
$Enter::Send, !O
`

Autohotkey is here: https://www.autohotkey.com/

I am using version 1 so the command above is for version 1

**Comment by vomikan** [comment]
Shift + OK should work for renter current transaction and continue with new one.
