### ISSUE TITLE
The view "alldata" doesn't exist for version 1.6.3

### ISSUE THREAD

**Issue by jam4657** [moneymanagerex/moneymanagerex#5724]
MMEX version:

 - [ X] 1.6.3

Operating System:
 - [x] Windows

# Description of the bug

With version 1.6.2 I used view "alldata" with SQLlite project to etablish my accounting.
Now, this view doesn't existe and the shema has changed (subcategory table doesn't exist).
Could you give me the SQL code to create this view. Thanks
Here the old sql code :

CREATE VIEW alldata as 
select CANS.TransID as ID, CANS.TransCode as TransactionType, CANS.TransDate as Date, 
coalesce(CAT.CategName, SCAT.CategName) as Category, 
coalesce(SUBCAT.SUBCategName, SSCAT.SUBCategName) as Subcategory, 
ROUND((case CANS.TRANSCODE when 'Withdrawal' then -1 else 1 end)*
(case CANS.CATEGID when -1 then st.splittransamount 
else CANS.TRANSAMOUNT end),2) as Amount, 
cf.currency_symbol as currency, 
CANS.Status as Status, CANS.NOTES as Notes, 
cf.BaseConvRate as BaseConvRate, 
FROMACC.CurrencyID as CurrencyID, 
FROMACC.AccountName as AccountName, FROMACC.AccountID as AccountID, TOACC.AccountName as ToAccountName, 
TOACC.ACCOUNTId as ToAccountID, CANS.ToTransAmount ToTransAmount, TOACC.CURRENCYID as ToCurrencyID, 
(case ifnull(CANS.CATEGID,-1) when -1 then 1 else 0 end) as Splitted, 
ifnull(CAT.CategId,st.CategId) as CategID, 
ifnull(SUBCAT.SubCategID,st.subCategId) as SubCategID, 
PAYEE.PayeeName as Payee, PAYEE.PayeeID as PayeeID, 
CANS.TRANSACTIONNUMBER as TransactionNumber, 
round(strftime('%Y', CANS.TransDate)) as Year, 
round(strftime('%m', CANS.TransDate)) as Month, 
round(strftime('%d', CANS.TransDate)) as Day 
from  CHECKINGACCOUNT_V1 CANS 
left join CATEGORY_V1 CAT on CAT.CATEGID = CANS.CATEGID 
left join SUBCATEGORY_V1 SUBCAT on SUBCAT.SUBCATEGID = CANS.SUBCATEGID and SUBCAT.CATEGID = CANS.CATEGID 
left join PAYEE_V1 PAYEE on PAYEE.PAYEEID = CANS.PAYEEID 
left join ACCOUNTLIST_V1 FROMACC on FROMACC.ACCOUNTID = CANS.ACCOUNTID 
left join ACCOUNTLIST_V1 TOACC on TOACC.ACCOUNTID = CANS.TOACCOUNTID 
left join splittransactions_v1 st on CANS.transid=st.transid 
left join CATEGORY_V1 SCAT on SCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid 
left join SUBCATEGORY_V1 SSCAT on SSCAT.SUBCATEGID = st.SUBCATEGID and SSCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid 
left join currencyformats_v1 cf on cf.currencyid=FROMACC.currencyid 
order by CANS.transid

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@jam4657 Hopefully, someone will be along to discuss your request on how create an _alldata_ view.

However, please note that the existence of the _alldata_ view is **not a supported feature** of MMEX. It only existed in recent versions as a hangover from some development work done long ago that was subsequently abandoned. The presence of the out of date and unused _alldata_ view causes errors when installing updates to MMEX that also require an upgrade to the database.

Be aware that future versions of MMEX, such as the forthcoming 1.6.4 or 1.6.5, will also include changes to the database schema and thus may break any new _alldata_ view you create.

**Comment by n-stein** [comment]
It is enough to just remove the lines referencing SUBCATEGORY_V1.
```
CREATE VIEW alldata as
select CANS.TransID as ID, CANS.TransCode as TransactionType, CANS.TransDate as Date,
coalesce(CAT.CategName, SCAT.CategName) as Category,
ROUND((case CANS.TRANSCODE when 'Withdrawal' then -1 else 1 end)*
(case CANS.CATEGID when -1 then st.splittransamount
else CANS.TRANSAMOUNT end),2) as Amount,
cf.currency_symbol as currency,
CANS.Status as Status, CANS.NOTES as Notes,
cf.BaseConvRate as BaseConvRate,
FROMACC.CurrencyID as CurrencyID,
FROMACC.AccountName as AccountName, FROMACC.AccountID as AccountID, TOACC.AccountName as ToAccountName,
TOACC.ACCOUNTId as ToAccountID, CANS.ToTransAmount ToTransAmount, TOACC.CURRENCYID as ToCurrencyID,
(case ifnull(CANS.CATEGID,-1) when -1 then 1 else 0 end) as Splitted,
ifnull(CAT.CategId,st.CategId) as CategID,
PAYEE.PayeeName as Payee, PAYEE.PayeeID as PayeeID,
CANS.TRANSACTIONNUMBER as TransactionNumber,
round(strftime('%Y', CANS.TransDate)) as Year,
round(strftime('%m', CANS.TransDate)) as Month,
round(strftime('%d', CANS.TransDate)) as Day
from CHECKINGACCOUNT_V1 CANS
left join CATEGORY_V1 CAT on CAT.CATEGID = CANS.CATEGID
left join PAYEE_V1 PAYEE on PAYEE.PAYEEID = CANS.PAYEEID
left join ACCOUNTLIST_V1 FROMACC on FROMACC.ACCOUNTID = CANS.ACCOUNTID
left join ACCOUNTLIST_V1 TOACC on TOACC.ACCOUNTID = CANS.TOACCOUNTID
left join splittransactions_v1 st on CANS.transid=st.transid
left join CATEGORY_V1 SCAT on SCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid
left join currencyformats_v1 cf on cf.currencyid=FROMACC.currencyid
order by CANS.transid;
```

Do you want full category names, e.g. `Category:Subcategory:SubSubCategory` or just `SubSubCategory`? Then there is a bit of change needed to recursively append the names.

**Comment by jam4657** [comment]
Thank you very much n-stein.
I used also SubSubcategory. If you can?

**Comment by n-stein** [comment]
SubSubCategory is a category. There are no longer separate fields for category and subcategoryn in the database. My question was how do you want to view categories which are not at the top level (root) -- with all of their parents appended (full name) or with just the lowest level name displayed (the actual transaction category).

If you really need a separate field I can make one that has parent category and category as separate fields. That would mimic the old view if you only use two levels of categories.

**Comment by jam4657** [comment]
Yes I do. I used Parent category and category as separate fields.

**Comment by n-stein** [comment]
Try this:
```
CREATE VIEW alldata as
select CANS.TransID as ID, CANS.TransCode as TransactionType, CANS.TransDate as Date,
coalesce(CAT.parent, SCAT.parent, CAT.CategName, SCAT.CategName) as Category,
(case coalesce(CAT.parentid, SCAT.parentid) when -1 then "" else coalesce(CAT.CategName, SCAT.CategName) end) as Subcategory,
ROUND((case CANS.TRANSCODE when 'Withdrawal' then -1 else 1 end)*
(case CANS.CATEGID when -1 then st.splittransamount
else CANS.TRANSAMOUNT end),2) as Amount,
cf.currency_symbol as currency,
CANS.Status as Status, CANS.NOTES as Notes,
cf.BaseConvRate as BaseConvRate,
FROMACC.CurrencyID as CurrencyID,
FROMACC.AccountName as AccountName, FROMACC.AccountID as AccountID, TOACC.AccountName as ToAccountName,
TOACC.ACCOUNTId as ToAccountID, CANS.ToTransAmount ToTransAmount, TOACC.CURRENCYID as ToCurrencyID,
(case ifnull(CANS.CATEGID,-1) when -1 then 1 else 0 end) as Splitted,
ifnull(CAT.CategId,st.CategId) as CategID,
PAYEE.PayeeName as Payee, PAYEE.PayeeID as PayeeID,
CANS.TRANSACTIONNUMBER as TransactionNumber,
round(strftime('%Y', CANS.TransDate)) as Year,
round(strftime('%m', CANS.TransDate)) as Month,
round(strftime('%d', CANS.TransDate)) as Day
from CHECKINGACCOUNT_V1 CANS
left join 
    (
		select CAT.CATEGID as CATEGID, CAT.CATEGNAME as CATEGNAME, PCAT.CATEGNAME as PARENT, CAT.PARENTID as PARENTID 
		from CATEGORY_V1 CAT 
		left join CATEGORY_V1 PCAT 
		on PCAT.CATEGID = CAT.PARENTID
    ) as CAT on CAT.CATEGID = CANS.CATEGID
left join PAYEE_V1 PAYEE on PAYEE.PAYEEID = CANS.PAYEEID
left join ACCOUNTLIST_V1 FROMACC on FROMACC.ACCOUNTID = CANS.ACCOUNTID
left join ACCOUNTLIST_V1 TOACC on TOACC.ACCOUNTID = CANS.TOACCOUNTID
left join splittransactions_v1 st on CANS.transid=st.transid
left join 
	(
		select CAT.CATEGID as CATEGID, CAT.CATEGNAME as CATEGNAME, PCAT.CATEGNAME as PARENT, CAT.PARENTID as PARENTID 
		from CATEGORY_V1 CAT 
		left join CATEGORY_V1 PCAT 
		on PCAT.CATEGID = CAT.PARENTID
	) as SCAT on SCAT.CATEGID = st.CATEGID and CANS.TransId=st.transid
left join currencyformats_v1 cf on cf.currencyid=FROMACC.currencyid
order by CANS.transid;
```

**Comment by jam4657** [comment]
Thank's n-stein. It's perfect
