### ISSUE TITLE
DB image is malformed??

### ISSUE THREAD

**Issue by DavidE2910** [moneymanagerex/moneymanagerex#5725]
I have been happily using MMEX for years, but suddenly I have error message
CHECKINGACCOUNT_V1: Exception database disk image is malformed[11]: database disk image is malformed
Where do I go from here???

<hr> • Version: 1.6.3 64-bit<br>
 • Built: Jan 31 2023 12:09:35<br>
 • db 17 (aes128cbc)<br>
 • git 48d8562 (2023-01-31)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 •  English (United Kingdom) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Did you get this error while in the process of updating to 1.6.3? Or just when using MMEX _after_ 1.6.3 was installed?

See https://github.com/moneymanagerex/moneymanagerex/issues/5550 for a similar problem.

**Comment by n-stein** [comment]
I would be surprised if this occurred during the update as the DB version was not upgraded between 1.6.2 and 1.6.3. Likely some unexpected shutdown corrupted one of the indices.

This can likely be fixed by simply reindexing your database. Unfortunately due to a change in SQLite we can't provide a debug file to do this for you in versions 1.6.2 or 1.6.3. That limitation should be fixed in 1.6.4. Until then, you would have to manually execute `REINDEX;` using your choice of database browser as described in #5550.

**Comment by DavidE2910** [comment]
Many thanks for your prompt reply. I'll have a go on Monday .. busy weekend!
Cheers
David

**Comment by DavidE2910** [comment]
Hi,
Similar to #5550 I get

Execution finished with errors.

Result: database disk image is malformed

At line 1:

REINDEX;


but with integrity check I get


Execution finished without errors.

Result: 1 rows returned in 408ms

At line 1:

PRAGMA integrity_check;


So I went back to a backup from 6 Dec 2022 (which worked fine for nearly 2
months and I got


[image: 5ca39929-0bf6-43ff-9c5d-39a49be2ded8.png]

I then found a b/u from Jan 23. This seems OK. But in going through adding
and changing transactions to update it when changing a split transaction I
got this lot.....



[image: image.png]


14:16:42: CHECKINGACCOUNT_V1: Exception disk I/O error[3338]: disk I/O error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:42: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error
14:16:43: SPLITTRANSACTIONS_V1: Exception disk I/O error[3338]: disk I/O
error


However, I killed MMEX and restarted & it seems OK - it's just been a lot
of work to get back up to date.

Cheers

David

**Comment by tactilis** [comment]
@DavidE2910 When you reply via email, your images get stripped out, so we cannot see them.

Please could you post your comments directly via github here https://github.com/moneymanagerex/moneymanagerex/issues/5725 and paste the missing images.

Thanks

**Comment by DavidE2910** [comment]
Hi,
Sorry about that. Unfortunately I just cut & pasted the images so don't have a copy, but  basically the 6 Dec copy was giving the disk errors like before.
