### ISSUE TITLE
Buttons in Language are showing using the system language, instead of the language set in MMEX

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5727]
Money Manager Ex
• Version: 1.6.4-Beta.2 64-bit
• Built on: Mar 3 2023 19:53:26
• Database version: 17 (aes128cbc)

# Description of the bug
Buttons in `Language` are showing using the system language, instead of the language set in MMEX.

# Reproduction

1. The operating system language is set to Hungarian.
![image](https://user-images.githubusercontent.com/17465872/222853449-c74d1d27-e4f4-4151-b339-f1c0bbb1b6a5.png)
2. Open MMEX and set the language to English.
3. Restart MMEX and click `User Interface Language`
4. Should the buttons in the `Language` dialog show in English, i.e. `Cancel`, instead of Hungarian, i.e. `Mégse`?
![image](https://user-images.githubusercontent.com/17465872/222853630-d66ae621-d887-48e0-9c8f-a5b062354cbc.png)

Is the bug reproducible? Always

Thank you

**Comment by ovari** [comment]
Another test with:
* Operating system language = English, Australia
* MMEX language = Hungarian

Should the buttons in MMEX show in Hungarian the MMEX is set to Hungarian, instead of the operating system language?

![image](https://user-images.githubusercontent.com/17465872/222855255-a12288d6-bbf0-4fff-81c0-89ce3b828449.png)

Thank you

**Comment by ovari** [comment]
It seems that the `&OK` is not translated, as in Hungarian it should show as `&Rendben`

**Comment by vomikan** [comment]
This can be fixed. An example of the code is here:

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmSimpleDialogs.cpp#L848-L865

**Comment by ovari** [comment]
Thank you for the link.

Can https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmSimpleDialogs.cpp#L848-L865 be copied and pasted into the file at https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L185 using a web browser?

**Comment by n-stein** [comment]
> Can https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmSimpleDialogs.cpp#L848-L865 be copied and pasted into the file at https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L185 using a web browser?

You can try copying https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmSimpleDialogs.cpp#L860-L863 and paste it after https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L156

**Comment by ovari** [comment]
Can someone please merge https://github.com/moneymanagerex/moneymanagerex/pull/5728 (or advise what they want changed) so that a new fork can be made with this issue? Thank you

**Comment by n-stein** [comment]
You don't need that PR to be merged. Just create a new branch in your fork and make your changes there.

**Comment by n-stein** [comment]
@ovari I'm not seeing this issue. When I select Hungarian the buttons also appear in Hungarian.

![image](https://user-images.githubusercontent.com/16599929/223128850-70bb4cd4-b8b6-4290-8f79-da44f59be20e.png)

**Comment by ovari** [comment]
> You can try copying https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmSimpleDialogs.cpp#L860-L863 and paste it after https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L156

Done at https://github.com/moneymanagerex/moneymanagerex/pull/5735

Thank you

**Comment by n-stein** [comment]
This isn't related to the code in https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L156

The problem is the language list popup [here](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/appstartdialog.cpp#L212) is using a wxSingleChoiceDialog which by default uses the system language for the command buttons.

**Comment by vomikan** [comment]
https://github.com/vomikan/moneymanagerex/commit/83392ee9e2182b42abb688ec9db1e0b26c59f4c0

wxGetSingleChoiceIndex  occurs twice more in the code. I won't be able to fix it in the near future.

**Comment by vomikan** [comment]
> mmSingleChoiceDialog is just wrapping a call to wxSingleChoiceDialog, so won't it have the same issue?

This wrapper is made only for the translation of buttons and no more.

**Comment by ovari** [comment]
Not yet fixed when testing with
```
Money Manager Ex
• Version: 1.6.4-Beta.2 64-bit
• Built on: Mar 9 2023 03:27:31
• Database version: 17 (aes128cbc)
```

> wxGetSingleChoiceIndex occurs twice more in the code. I won't be able to fix it in the near future.

Does this need to be done for the fix to work?

Thank you

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/224001889-b3dfaf05-3b67-4f3a-9222-f5860d6b9e53.png)

**Comment by ovari** [comment]
> It should be noted that with the English locale of the operating system, the wxGetSingleChoice also shows buttons in Russian.

Doesn't show the buttons in Hungarian with the English locale of the operating system with Linux Mint Cinnamon.

![image](https://user-images.githubusercontent.com/17465872/224135087-77e6336f-fe26-4045-976a-60a93c63fc79.png)

**Comment by n-stein** [comment]
That should explicitly set the button label to the translated text after the dialog is created, maybe it will work for Linux.

**Comment by n-stein** [comment]
@ovari test the latest beta build, see if it works for you.

**Comment by ovari** [comment]
> @ovari test the latest beta build, see if it works for you.

Unfortunately MMEX Built on: Mar 10 2023 19:41:14 does not work.

![image](https://user-images.githubusercontent.com/17465872/224444728-4b88433e-086e-40aa-9445-7b482a88f46f.png)

**Comment by ovari** [comment]
Fixed with:

```
• Version: 1.6.4-Beta.3 64-bit
• Built on: Mar 14 2023 03:27:09
• Database version: 18 (aes128cbc)
```

Thank you
