### ISSUE TITLE
`Example.mmex` for updating `Screenshots` section

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5736]
Is there an `Example.mmex` database file that can be posted here to updated the [Screenshots](https://github.com/moneymanagerex/moneymanagerex#screenshots) section?

1. `Home Page` has changed to `Dashboard`
2. Showing nested categories in the `Transaction Filter and Organize Categories` screenshot
3. Showing nested categories in the `Budget Setup` screenshot
4. Text in window titlebar has been changed
5. Adding a screenshot with GNU/Linux
6. Adding a screenshot with macOS
7. Adding screenshots showing [International language support](https://crowdin.com/project/moneymanagerex).
Selection of languages:
(a) ones which developers use;
(b) translation which are, or close to, 100%;
(c) non-Latin characters (to show Unicode support).
Which language(s) below?
** Simplified Chinese
** Dutch
** French
** German
** Greek
** Hebrew
** Hungarian
** Italian
** Polish
** Portuguese, Brazilian
** Russian
** Spanish

Perhaps the screenshots could be taken with the same size of the current size of the screenshots, i.e. 1335x917.
* https://raw.githubusercontent.com/moneymanagerex/Art/master/PC/mmex1.png
* https://raw.githubusercontent.com/moneymanagerex/Art/master/PC/mmex2.png
* https://raw.githubusercontent.com/moneymanagerex/Art/master/PC/mmex3.png
* https://raw.githubusercontent.com/moneymanagerex/Art/master/PC/mmex4a.png

What do you think?

Thank you

**Comment by BanCrash** [comment]
@ovari I asked the same some time ago, in the comments you have a database:

https://github.com/moneymanagerex/moneymanagerex/issues/5580

**Comment by ovari** [comment]
How can the image be uploaded to GitHub?

https://www.youtube.com/watch?v=nvPOUdz5PL4

Is there a public folder to add the image files?

**Comment by ovari** [comment]
![1 MMEX Dashboard](https://user-images.githubusercontent.com/17465872/233927369-03eabcaa-0e29-4730-8be0-462c3e1c9a01.png)

![2 MMEX Payee Report](https://user-images.githubusercontent.com/17465872/233927379-268bd999-9093-4de9-ad72-02e0781b56ec.png)

![3 MMEX Budget](https://user-images.githubusercontent.com/17465872/233927385-0f5a551f-494b-43b6-92ef-8fa1ba91e3ed.png)

![4 MMEX User Interface Language magyar](https://user-images.githubusercontent.com/17465872/233927390-21a3bd99-06d7-4455-b96f-ae98b39a7358.png)

![5 MMEX Nested Categories](https://user-images.githubusercontent.com/17465872/233927396-7470f433-2756-4a68-b709-9a8834b6347d.png)

![6 MMEX Transaction Filter](https://user-images.githubusercontent.com/17465872/233927401-597ea9bc-a890-44df-b6eb-d26ce8369551.png)

**Comment by ovari** [comment]
Please post images with screenshots with macOS and Windows here. Please state which version of the operating system. Thank you

**Comment by ovari** [comment]
Please post an image of a portable screenshot if you have one available.

**Comment by ovari** [comment]
@tactilis okay so won't add `[portable mode]` screenshot. Can you please merge https://github.com/moneymanagerex/moneymanagerex/pull/5859 ?

Thank you

**Comment by ovari** [comment]
MMEX 1.7.1-RC.1 64-bit on Linux Mint 21.3 Cinnamon

![001 Dashboard](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/01cc2202-9d5a-4bba-a816-5868512196cb)

![002 Payee Report](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/9ba8d274-7af8-496c-9ab6-2c49235ec735)

![003 Budget](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ef2d2269-a973-4957-a10b-d13651390ad0)

![004 Magyar](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/4edfc0c8-7bfc-4052-bf2c-4b833b8b1547)

![005 Category Manager](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/be52a7f3-9dea-46dd-a04e-f198dd413b08)

![006 Transaction Report Filter](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b69b1eba-e476-4755-b64c-1eec2946f4a8)

![010 Currency Manager](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ebeb0cfb-ace1-4be8-b14b-ed41a741ec1c)
