### ISSUE TITLE
Can't build from sources on Windows 11 as per BUILD.md steps

### ISSUE THREAD

**Issue by giuseppepaoletti** [moneymanagerex/moneymanagerex#5739]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
I'm trying to compile MMEx from sources in Windows 11, x64 version, with Visual Studio 2022 following the steps in https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md. Commands work as expected until step 5, then at step 6 (apply patches from util directory to CMake modules) happen the first problem:
![image](https://user-images.githubusercontent.com/7680977/223670464-d1579960-e3fa-4020-935a-73ff40f98455.png)
CMake modules aren't in cmake-3.8 folder but in cmake-3.25; execute with this folder shows another error:
![image](https://user-images.githubusercontent.com/7680977/223671763-affdceb0-283b-49b9-9749-abbfe3162db2.png)

At step 7 (build curl library) there is another problem; first part of cmake command must be changed from
cmake -G "Visual Studio 17 2022 Win64" -DBUILD_CURL_EXE=OFF -DHTTP_ONLY=ON ^
to
cmake -G "Visual Studio 17 2022" -Ax64 -DBUILD_CURL_EXE=OFF -DHTTP_ONLY=ON ^
because architecture must be passed as optional parameter -A.

At step 8 (generate build environment using CMake), apart from the same error in step 7, there is another problem, CMakeLists.txt is not in build directory:
![image](https://user-images.githubusercontent.com/7680977/223673789-42ed619c-0362-425b-b5c8-f363f605fa1e.png)
Trying to execute cmake command from c:\projects\mmex (which contains CMakeLists.txt) or copy CMakeLists.txt file to build folder give the same error.

Can someone help me?
I was able to compile with no errors MMEx 1.5.3 with Visual Studio 2019 without error some time ago.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by vomikan** [comment]
I always skipped point 6.

I haven't changed this version yet.
• libcurl/7.61.1-DEV WinSSL

**Comment by giuseppepaoletti** [comment]
> > Trying to execute cmake command from c:\projects\mmex (which contains CMakeLists.txt) or copy CMakeLists.txt file to build folder give the same error.
> 
> Try removing the extra `"` after `-Ax64` ![image](https://user-images.githubusercontent.com/16599929/223795622-11a2c641-7b54-4dff-8238-1c56fa73c298.png)

Thanks! This was the problem, I forgot to delete the last `"` after modify cmake command.

Compilation start, but there are some unresolved external in LuaGlue class:
![image](https://user-images.githubusercontent.com/7680977/223967628-6e40a494-bf47-4c38-a193-6db4e046877d.png)

**Comment by n-stein** [comment]
> Compilation start, but there are some unresolved external in LuaGlue class:

Did you perhaps miss the `--recursive` option in the `git clone`?

What is in the folder `moneymanagerex/3rd/LuaGlue`? Should have these files:
![image](https://user-images.githubusercontent.com/16599929/224174019-f1f11e35-2130-44a5-b958-981d74fcfc89.png)

**Comment by n-stein** [comment]
After looking at your first screenshot again it looks like you cloned recursively, so that shouldn't be an issue.
