### ISSUE TITLE
Dirty category is shown in picklist and in some report after upgrade from non recursive category

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/moneymanagerex#5748]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [X] 1.6.3
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
After update to last version 
• Version: 1.6.3 64-bit
• compiled: Gen 31 2023 12:09:35
• Version Database: 17 (aes128cbc)
• Git commit: 48d8562 (2023-01-31)
with recurseve subcategory, some dirty category appears in category picklist and in some report. I suppose that this coming from historical management on my mmb, I suppose that I delete some top level category and now some subcaterory (orphan?) appears in list. 
Not understand I can reproduce starting from new and clean db.

View in category list:
<img width="292" alt="Immagine 2023-03-11 163428" src="https://user-images.githubusercontent.com/3205448/224495012-d66666d0-871b-4afd-9b63-27cb60617256.png">

View in category summary
<img width="349" alt="Immagine 2023-03-11 163516" src="https://user-images.githubusercontent.com/3205448/224495032-f4e0d46c-2346-430d-9e39-50fe52a5830c.png">

Wrong result in picklist
<img width="282" alt="Immagine 2023-03-11 164020" src="https://user-images.githubusercontent.com/3205448/224495042-d6a23ece-740a-4168-9594-e146dc8165a7.png">

wrng result in budget performance
<img width="477" alt="Immagine 2023-03-11 163847" src="https://user-images.githubusercontent.com/3205448/224495059-fa5aa72b-a665-4262-979c-997e474c2dc4.png">

**Comment by wolfsolver** [comment]
ps. taking a look to db I see that there are some record in category table that has reference to non existing root. 
This category record refer to parent 3, 5 and 6 that are not present in category table

34 | Movies | 1 | 3 
35 | Video Rental | 1 | 3 
36 | Magazines | 1 | 3 
41 | Books | 1 | 5 
42 | Tuition | 1 | 5 
43 | Others | 1 | 5 
44 | Clothing | 1 | 6 
45 | Furnishing | 1 | 6 
46 | Others | 1 | 6 

So I can try to remove record from db.

**Comment by n-stein** [comment]
Not sure how this occurred, must be at some point in the past MMEX didn't auto-delete associated subcategories when a category was deleted.

As you said, removing the bad records from your db should resolve the issue. Just make sure you don't have any transactions against those CATEGIDs before removing them.

**Comment by wolfsolver** [comment]
Thanks. I suppose so.

For me can be closed.

I left you to evaluate is a sanity check (missing parent category) need to be done after an upgrade, since even if not easy to reproduce, someone else can have this problem.
