### ISSUE TITLE
DEB package needed

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#575]
http://forum.moneymanagerex.org/viewtopic.php?f=25&t=6157

**Comment by dwrj87** [comment]
I think the best option would be to update the PPA, and then you can just copy that from there to the website. I can try and figure it out and make a script if you want

**Comment by vomikan** [comment]
I agree that PPA would be best option. But DEB pkg for v1.2.2 is OK becouse
it may be prepared quickly.

суббота, 10 октября 2015 г. пользователь David Jones написал:

**Comment by dwrj87** [comment]
Compiled a deb package on my computer and uploaded it here - http://s000.tinyupload.com/index.php?file_id=00321309975761478300

If it doesn't work, give me a shout and I'll try and do better

**Comment by nasko** [comment]
Thank you guys for bothering!

I just installed the DEB package without any problems. However, when I try to run the program, I get an error:

```bash
nasko@nasko-thinkpad:~$ mmex 
mmex: error while loading shared libraries: libwx_gtk2u_webview-3.0.so.0: cannot open shared object file: No such file or directory
```

If I can get you a more detailed debug data, please give me a hint on how to acquire it.

**Comment by nasko** [comment]
I installed `libwxgtk-webview3.0-0`, but now I get a different error:

```bash
nasko@nasko-thinkpad:~$ mmex 
mmex: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by mmex)
```

**Comment by dwrj87** [comment]
I think that the easiest way would be to get a PPA working, as that can take in to account different library versions on different versions of Ubuntu. I shall attempt it tomorrow

**Comment by dwrj87** [comment]
I'm afraid that I haven't been able to figure this out, and I don't think I'll have the time to do it sorry

**Comment by dwrj87** [comment]
https://launchpad.net/~dwrj87/+archive/ubuntu/mmex-test

**Comment by nasko** [comment]
I can confirm that I've successfully installed mmex using this ppa and it's running fine so far. 
Thanks indeed for your efforts, David!

**Comment by howff** [comment]
On 4 December 2015 at 21:46, Atanas Vasilev <notifications@github.com>
wrote:

> I can confirm that I've successfully installed mmex using this ppa and
> it's running fine so far.
> Thanks indeed for your efforts, David!
>

Indeed, thanks very much.  I've spent literally days of my life trying to
compile mmex for ubuntu.
Never suceeded. Not even in a fresh 14.04 VM. The latest compile errors
were:
 ../src/mmhomepagepanel.cpp: In member function ‘void
mmHomePagePanel::CreateControls()’:
../src/mmhomepagepanel.cpp:531:60: error: expected primary-expression
before ‘(’ token
     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new
wxWebViewFSHandler("memory")));
                                                            ^
../src/mmhomepagepanel.cpp:531:65: error: expected type-specifier before
‘wxWebViewFSHandler’
     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new
wxWebViewFSHandler("memory")));
                                                                 ^
make: *** [mmex_mmhomepagepanel.o] Error 1
If mmex could be built by all and sundry that would help me sleep easier ;-)
So thanks for providing the deb package.

**Comment by dwrj87** [comment]
To be honest, I'm not sure why you haven't been able to compile with the updated instructions. I tested them in virtual machines running fresh installs and wrote it down as I was doing it, and I've just tested them again now.

**Comment by vomikan** [comment]
https://launchpad.net/~dwrj87/+archive/ubuntu/mmex-test/
