### ISSUE TITLE
Automatically Download Stock Prices at Startup

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5759]
# Description of the feature

My suggestion would be to add a feature where MMEX will automatically download the current stock prices for shares that are held in Stock accounts at startup. Also add an option to control this via user preferences:

![image](https://user-images.githubusercontent.com/95182117/225479276-99ed78d7-3fc8-4312-b683-89d673918713.png)

**Comment by n-stein** [comment]
Does "current stock prices" mean the last close price?

**Comment by rmelillo76** [comment]
> Does "current stock prices" mean the last close price? I've finished adding this, just making sure it's fetching the right thing.

Hey @n-stein, that's a great question - I hadn't fully thought it out. I was initially thinking of fetching all of the available dates and their historical price since the last one already present in MMEX. But I can see that may be a little tricky since it looks the supported period to fetch from yahoo align with the selection dialog we present to the user when manually downloading ( "1d","5d","1mo","3mo","6mo","1y","2y","5y","10y","ytd","max"). This can be seen when looking at the JSON result when viewing 
https://query1.finance.yahoo.com/v8/finance/chart/<symbol>

Could we calculate how many days that need to be downloaded in order to bring current, then work off of that?
https://github.com/moneymanagerex/moneymanagerex/blob/8a7e546cb72d37f6c6805a0002bb4ffd46d82abe/src/stockdialog.cpp#L730

**Comment by rmelillo76** [comment]
Actually, @n-stein, I didn't mean to overcomplicate this 😊. Looking at the code, I now see there are a couple of different ways and URLs we are downloading rates. The function that is in stockspanel.cpp is capable of fetching rates for the last n days, months, 1 year, max. etc. But the idea of refresh I believe should simply re-use the function in util.cpp (get_yahoo_prices) that is invoked from the Tools | Download Rates menu, I think that simply retrieves the most current rate available and will keep it simple.  If a user wants to download historical rates, we can do that from the Stocks area of MMEX.

**Comment by n-stein** [comment]
![image](https://user-images.githubusercontent.com/16599929/226422493-677821f3-9020-4512-b29f-b0cf3a33b419.png)

> But the idea of refresh I believe should simply re-use the function in util.cpp (get_yahoo_prices) that is invoked from the Tools | Download Rates menu

Even simpler, when you open a DB it just triggers the event as if the user clicked on Tools > Download Rates.

**Comment by rmelillo76** [comment]
> Even simpler, when you open a DB it just triggers the event as if the user clicked on Tools > Download Rates.

I think that should do the trick!

**Comment by renato-mmex** [comment]
Have set the option, but when I start mmex the rates are not updated.

**Comment by rmelillo76** [comment]
> Have set the option, but when I start mmex the rates are not updated.

I am having the same results. Question for @n-stein: Should the "REFRESH_STOCK_QUOTES_ON_OPEN" setting be in the INFOTABLE_V1 table within the .mmb file, or SETTING_V1 table within the mmexin.db3 file? I see the code should be managing reading and writing the setting on dialog load and close, but I used  SQLLite DB Browser and am not seeing the setting in  either of those tables. Just wanted to mention that in case it helps.

**Comment by n-stein** [comment]
> Should the "REFRESH_STOCK_QUOTES_ON_OPEN" setting be in the INFOTABLE_V1 table within the .mmb file, or SETTING_V1 table within the mmexin.db3 file?

In general, the location of a setting depends on whether the setting is DB specific or not -- database specific settings go in INFOTABLE_V1 and non-specific settings go in SETTING_V1. Right now this setting is not DB specific and is in the SETTING_V1 table. Once this setting is enabled, any database you open will have the rates refreshed. 

Which mmexini.db3 table are you browsing with DB Browser? Make sure you're checking the correct file -- the portable version will use the one in the mmex-1.6.4-Beta.3-win64 folder, so check there. 

Here is what the mmexini.db3 file looks like on the portable beta after enabling this setting:

![image](https://user-images.githubusercontent.com/16599929/226695346-e2de8e04-b40b-48c6-9b35-106ac317af27.png)

If your rates don't refresh on open, try going to Tools > Download Rates. Do they refresh then? If not the symbol for which you are trying to fetch rates might not be valid.

**Comment by renato-mmex** [comment]
Tools > Download Rates  This works as before

**Comment by n-stein** [comment]
Are you testing the portable beta or the installable beta?

**Comment by renato-mmex** [comment]
I always test with:  installable beta

However, I use the following option because I have multiple databases (different languages/Options):
"C:\Program Files\Money Manager EX\bin\mmex.exe" -i C:\Users\bruec\AppData\Roaming\MoneyManagerEx\mmexini-d.db3

**Comment by rmelillo76** [comment]
I'm also using the installable beta, downloaded from AppVeyor

**Comment by rmelillo76** [comment]
Thanks @n-stein  - I was in fact looking at the wrong mmexini.db3. I located the correct one, which for me is in 
C:\Users\%username%\AppData\Roaming\MoneyManagerEx and I can see the setting is persisted there, and does toggle between TRUE and FALSE when saved in the Options dialog. Sorry about that!

![image](https://user-images.githubusercontent.com/95182117/226782953-ed13b4d5-d4a7-4a24-b99f-d00815a9312e.png)

However, it still doesn't appear that the rate update is occurring when MMEX starts up.

**Comment by n-stein** [comment]
Do you see a green pop-up that says "Downloading stock prices from Yahoo" when you open a DB?

**Comment by n-stein** [comment]
> by the way: MMEX has a conceptual flaw from my point of view, the options are the same for all databases, stored in .db3 instead of .mmb

I don't think this is a flaw in general. There are certain settings that must be stored in the mmb because they need to be maintained on a per-db basis. Things like username, webapp details, financial year details, user defined colors, or base currency are extremely database specific. But many options are stored in the ini file to provide consistency from database to database -- the web proxy, theme settings, icon sizes, font size, UI language, etc are things that don't need to change when you already have MMEX running and open a different database. So there is value in storing settings in both locations.

Now whether a specific setting is currently stored in the ideal location or not is a topic for discussion, and if there are any that should/need to be migrated one way or the other we can do that.

**Comment by rmelillo76** [comment]
> Do you see a green pop-up that says "Downloading stock prices from Yahoo" when you open a DB?

Nope, it doesn't seem like that event is being triggered for some reason. The code is pretty straightforward so I'm just as puzzled.

**Comment by n-stein** [comment]
Would you mind testing the portable beta?

**Comment by rmelillo76** [comment]
Works in Portable mode!  I was even able to grab a screenshot quick enough as the popup was briefly displayed:

![image](https://user-images.githubusercontent.com/95182117/226792000-bfd02b67-ae24-4d75-830b-315ba9737226.png)

**Comment by n-stein** [comment]
> Works in Portable mode

Interesting. And if you delete the mmexini.db3 file from the portable folder, does it still work when it falls back to the APPDATA ini file that the non-portable version updated?

**Comment by rmelillo76** [comment]
OK I discovered the pattern....

**Only** If the App Start Dialog is displayed, then the rates are downloaded, upon either clicking either of these options to open your DB....

![image](https://user-images.githubusercontent.com/95182117/226798307-9e4deb62-f639-4c0a-af5d-8870405d1a10.png)

Hopefully this provides a clue.. I normally  run MMEX with this command line in my shortcut:

"C:\Program Files\Money Manager EX\bin\mmex.exe" "C:\Users\richa\OneDrive\Documents\Money Manager Data\Filename.mmb"

**Comment by rmelillo76** [comment]
Working perfectly now, thanks @n-stein!!!

**Comment by renato-mmex** [comment]
Unfortunately it does not work for me yet when I start MMEX.

**Comment by rmelillo76** [comment]
> Unfortunately it does not work for me yet when I start MMEX.

I can reproduce that, when using the "-i <filename.db3> parameter. 

**Works:**
`"C:\Program Files\Money Manager EX\bin\mmex.exe" "C:\Users\richa\OneDrive\Documents\Money Manager Data\Rich and Karen.mmb"`

**Does not work:**
`"C:\Program Files\Money Manager EX\bin\mmex.exe" "C:\Users\richa\OneDrive\Documents\Money Manager Data\Rich and Karen.mmb"  -i "C:\Users\richa\OneDrive\Documents\Money Manager Data\mmexini.db3"`

**Comment by n-stein** [comment]
I'm not seeing any issue running from CMD with the `-i` parameter.

> **Works:** `"C:\Program Files\Money Manager EX\bin\mmex.exe" "C:\Users\richa\OneDrive\Documents\Money Manager Data\Rich and Karen.mmb"`
> 
> **Does not work:** `"C:\Program Files\Money Manager EX\bin\mmex.exe" "C:\Users\richa\OneDrive\Documents\Money Manager Data\Rich and Karen.mmb" -i "C:\Users\richa\OneDrive\Documents\Money Manager Data\mmexini.db3"`

These two commands are using different ini files. The first one is using mmexini.db3 located at `%APPDATA%\MoneyManagerEx` and the second the db3 file in your `Money Manager Data` folder. Did you copy the AppData ini file (where the option is already enabled), or start with a new mmexini.db3 and enable the option again?

Executing the second one with the `-i` parameter, if you go into options is the check box enabled? If not, enable it and restart with the `-i` option again.

**Comment by renato-mmex** [comment]
Tested with this call (checkbox is enabled), without success
"C:\Program Files\Money Manager EX\bin\mmex.exe" -i C:\Users\bruec\AppData\Roaming\MoneyManagerEx\mmexini.db3

**Comment by renato-mmex** [comment]
Tested again (check box is checked), it works, thanks a lot

**Comment by rmelillo76** [comment]
> Tested again (check box is checked), it works, thanks a lot

Same here, thanks!

**Comment by rmelillo76** [comment]
> I'm not seeing any issue running from CMD with the `-i` parameter.
> These two commands are using different ini files. The first one is using mmexini.db3 located at `%APPDATA%\MoneyManagerEx` and the second the db3 file in your `Money Manager Data` folder. Did you copy the AppData ini file (where the option is already enabled), or start with a new mmexini.db3 and enable the option again?
> 
> Executing the second one with the `-i` parameter, if you go into options is the check box enabled? If not, enable it and restart with the `-i` option again.

Yep, that was exactly my issue. Doh!!!
