### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by JJHarrison75** [moneymanagerex/moneymanagerex#5760]
Navigation was part of the "normal" view. 

Please put Navigation attached to the "normal" view - as it used to be.

# Use cases

If not obvious, explain the use cases or problems to solve.
![image](https://user-images.githubusercontent.com/6836805/225633468-255d4bf1-6131-458a-b9ca-a86cee2048d3.png)

It is currently a seperate window and needs to be sized and put next to the "Home" screen - it is more convenient to be all together as the standard view.

**Comment by tactilis** [comment]
> Navigation was part of the "normal" view.
> Please put Navigation attached to the "normal" view - as it used to be.

You have accidentally undocked the Navigation panel (you dragged the title bar) making it a floating window.

You just need to re-dock it as shown here:

https://user-images.githubusercontent.com/4060092/225596218-cfcf48fc-e39c-4f3f-9811-f1aec88f9d52.mp4

**Comment by rmelillo76** [comment]
@JJHarrison75 You may want to remove your screenshot, as it contains lots of what I would assume are private, sensitive information about your bank accounts and personal finances. Thanks!

**Comment by tactilis** [comment]
> Thanks very much for your help, I am an old pensioner and how do I "give you a coffee?"

Thanks but no need John!

I'm just pleased that it was easily fixable for you.
