### ISSUE TITLE
RESOCONTO OPERAZIONI - FILTRO NON VA QUANDO SALVATO

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5769]
> RESOCONTO OPERAZIONI - NON FUNZIONA IN ALCUNI CASI QUANDO SI SALVA IL MODELLO. ESEMPIO con "PERIODO" (EX. Anno in corso) ed una "CATEGORIA" (ex. Spese varie) e tutti gli altri parametri non selezionati NON VA SE SALVATO MA INVECE VA SE CREATO AL MOMENTO.
> Per favore non rimuovere le informazi
![Cattura](https://user-images.githubusercontent.com/128650264/227653583-42ac807f-6368-49ff-a8e8-fceb04f6f6c2.JPG)
oni allegate sotto questo testo.

<hr> • Version: 1.6.3 64-bit<br>
 • Built: Gen 31 2023 12:09:35<br>
 • db 17 (aes128cbc)<br>
 • git 48d8562 (2023-01-31)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19044), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Via Google Translate:

> Operations report - it does not work in some cases when saving the model. Example with "period" (ex. Year in progress) and a "category" (ex. Various expenses) and all the other not selected parameters does not go if saved but instead it goes if created at the moment.

**Comment by MAPA2023** [comment]
Now it's clearer to me. The problem is that when I save the report, if the category is above 2 levels it is not stored.

**Comment by n-stein** [comment]
> if the category is above 2 levels it is not stored

When you say "above two levels", do you mean if the category is L3 or L4 in the image below it is not being stored?

![image](https://user-images.githubusercontent.com/16599929/232892670-b19d16ec-9eb1-45f2-86bf-c19ece64ad3b.png)

**Comment by n-stein** [comment]
I am unable to reproduce this issue in either 1.6.3 or 1.6.4.

**Comment by MAPA2023** [comment]
Hi Stein, 

I work with version 1.6.3 ! Do you also have version 1.6.4.?

I am attaching the TEST DB containing the problem (I renamed the extension as JPG but in fact it is an MMB). The report is DIESEL and you will see that it doesn't work. However if you create it at the moment without saving it works correctly.


![Money Manager DATA2023 - Copia](https://user-images.githubusercontent.com/128650264/233313624-8ddd0d57-b6f4-44b5-8c96-7cae279a384e.jpg)

**Comment by MAPA2023** [comment]
DIESEL like GASOLIO

**Comment by n-stein** [comment]
Thanks this was helpful, I see the issue and will fix it shortly. In the meantime a workaround for version 1.6.3 is to switch your category delimiter from ' : ' to ':' under Options -> View Options. This will make your reports work as intended.

**Comment by n-stein** [comment]
Fixed. The issue was your chosen delimiter is ' : ' but settings are always stored with ':'. The system is supposed to replace the ':' with your chosen delimiter but it was only replacing the first occurrence. So instead of `L1 : L2 : L3` it was generating `L1 : L2:L3` which didn't match the full name of the L3 category.

**Comment by MAPA2023** [comment]
Excellent, I am very pleased to have contributed to optimizing the program. Do I have to do anything now? How soon will you put the new version?

**Comment by MAPA2023** [comment]
Well ! I had to empty the " " field and the system filled it correctly by putting ":" again. Now it works correctly.
