### ISSUE TITLE
RIGA REGISTRAZIONE CON ERRORE

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5770]
> RIGA CHE NON POSSO CANCELLARE IN QUANTO PRESENTA UN ERRORE. COME POSSO FARE?
![mm errore conto](https://user-images.githubusercontent.com/128650264/227745396-f75239b5-910c-4cc5-bba9-9af407279a64.JPG)
![mm errore conto](https://user-images.githubusercontent.com/128650264/227745413-4b046669-5037-49f9-9c21-88d638983f6f.JPG)
.
> Per favore non rimuovere le informazoni allegate sotto questo testo.

<hr> • Version: 1.6.3 64-bit<br>
 • Built: Gen 31 2023 12:09:35<br>
 • db 17 (aes128cbc)<br>
 • git 48d8562 (2023-01-31)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Wi
![mm errore conto](https://user-images.githubusercontent.com/128650264/227745431-8d84eb27-ee55-4fa8-9bac-40ef55e4c31d.JPG)
ndows 10 (build 19044), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by renato-mmex** [comment]
Presumably, this will help: https://github.com/moneymanagerex/moneymanagerex/issues/5630

**Comment by MAPA2023** [comment]
I tracked the bug better. It's about this. When you delete an operation it goes to the "Trash". When deleting from the trash the program generates a new line with a new but empty ID. This can only be eliminated with a database editor but not directly from the program.

**Comment by tactilis** [comment]
@MAPA2023
> I tracked the bug better. It's about this. When you delete an operation it goes to the "Trash". When deleting from the trash the program generates a new line with a new but empty ID. This can only be eliminated with a database editor but not directly from the program.

Please see the issue '#5630 referred to above. The bug is fixed.

This issue (#5770) is a duplicate. Please could you mark it as Closed.

Thanks

**Comment by MAPA2023** [comment]
TY

SORRY

Max.
________________________________
Da: Martin ***@***.***>
Inviato: lunedì 24 aprile 2023 20:46
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: MAPA2023 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] RIGA REGISTRAZIONE CON ERRORE (Issue #5770)


@MAPA2023<https://github.com/MAPA2023>

I tracked the bug better. It's about this. When you delete an operation it goes to the "Trash". When deleting from the trash the program generates a new line with a new but empty ID. This can only be eliminated with a database editor but not directly from the program.

Please see the issue '#5630<https://github.com/moneymanagerex/moneymanagerex/issues/5630> referred to above. The bug is fixed.

This issue (#5770<https://github.com/moneymanagerex/moneymanagerex/issues/5770>) is a duplicate. Please could you mark it as Closed.

Thanks
