### ISSUE TITLE
CSV Import - "Type" defined amount sign does not work

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5772]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x] 1.6.4 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When importing a CSV file, selecting the Type field and then using the Amount option "Positive if type has '...'" does not work.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Create a CSV file with a "Type" column with two transactions - Credit and Debit
Define Amount as "Positive if type has 'Credit'"
![image](https://user-images.githubusercontent.com/16599929/228024036-7417cd6d-5105-40de-b7ed-ff4da4b3ee6b.png)
Import

Expected result:
The "Credit" line is a deposit, the "Debit" line is a withdrawal.

Actual result:
Opposite: The "Debit" line is a deposit, the "Credit" line is a withdrawal.
![image](https://user-images.githubusercontent.com/16599929/228024960-4b8d85aa-e0c0-4538-89e4-31a71eb21f52.png)

# Additional information
Now try the reverse way: Set Amount to "Positive if type has 'Debit'"
![image](https://user-images.githubusercontent.com/16599929/228024415-2b422846-1ac9-4c7e-bb92-6551baaa3c6c.png)

The "Credit" line is still a deposit, the "Debit" line is still a withdrawal. So it's not that the logic is backwards -- its just simply not working.
![image](https://user-images.githubusercontent.com/16599929/228025056-2abf63f8-9223-4e1e-9b36-a48f04beca9e.png)

**Comment by n-stein** [comment]
Right, I think that is exactly the issue. The "Type" field should be checking for `depositType_` when `m_choiceAmountFieldSign->GetSelection() == DefindByType`, not for `{ "debit", "deposit", "+" }`

**Comment by n-stein** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/16599929/228039348-3de60321-6538-4049-8d47-52541125fa7d.png)

**Comment by n-stein** [comment]
> But if I switch to `Positive values are deposits` and _then_ back to `Positive if Type has 'Deposit'`, the `Enter a value` dialog appears asking me to specify the string in the CSV that indicates a _positive_ value (i.e for me it's Pay In)

You don't have to switch to one of the other options first, but you do need to reselect the third option. It should either be shown immediately when you add the "Type" field, or the "Amount" selection shouldn't automatically change to "Positive if type has ...'

> No, that is not correct. It is more flexible than that but the UI is _very_ confusing...

It's _supposed_ to be more flexible than that, but you'll notice that currently both your PayIn and PayOut will be withdrawals... hence this issue.

**Comment by n-stein** [comment]
I feel we should automatically prompt the user for the "Deposit" string, and also restrict the Amount choice to _only_ be "Positive if type has ..." as discussed in #5039.

**Comment by tactilis** [comment]
> You don't have to switch to one of the other options first, but you do need to reselect the third option.

I see (now).

Here's another bit of unexpected behaviour:

1. Add the Type field (the dropdown 3rd option says 'Deposit')
2. Reselect the 3rd option, which displays the prompt dialog.
3. Type 'Pay In', click OK. The 3rd option now says 'Pay In' as expected.
4. Reselect the 3rd option (by mistake). The prompt dialog is displayed showing 'Pay In' as expected.
5. Click Cancel to close the dialog with no changes... the 3rd option now says 'Deposit'!

**Comment by n-stein** [comment]
https://github.com/n-stein/moneymanagerex/commit/10995da0e545b7a0baed8b5d381d18b912de1722 addresses all the issues discussed

**Comment by n-stein** [comment]
Yeah, working as expected now.
