### ISSUE TITLE
Account selector is empty even when import file dialog is opened from context menu on an account

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#5785]
MMEX version:
Version: 1.6.3 64-bit
• Built on: Jan 31 2023 12:09:35
• Database version: 17 (aes128cbc)
• Git commit: 48d8562 (2023-01-31)

Operating System:
 - [x] Windows

# Description of the bug
Account selector is empty even when import file dialog is opened from context menu on an account

# Reproduction
Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
1. Right click on an account on list
2. Choose Import from > CSV File
3. A dialog with title 'Import from CSV File' is presented

Expected result:
The account selector should have a preselected value.

Actual result:
The account selector is empty.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

![image](https://user-images.githubusercontent.com/10950385/229332222-8b05dd15-8828-4189-b8b8-648340d220ef.png)

**Comment by tactilis** [comment]
> Expected result:
> The account selector should have a preselected value.

This behaviour will be present in 1.6.4 (coming soon).

If you want it now, then download Beta 4

**Comment by luisdev** [comment]
@sarjanwebdev, did you test this in the fixed version that was indicated in the above comment?

**Comment by luisdev** [comment]
@sarjanwebdev, did you test this in the fixed version that was indicated in the above comment?

**Comment by sarjanwebdev** [comment]
✅ Fixed
