### ISSUE TITLE
Associate an import/export Preset (template) name with an account

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5790]
As a result of recent work by @n-stein, the process of importing transactions from CSV files has become much slicker than it used to be.

One area where the UX is still sub-optimal is the selection and saving of templates that contain the import (or export) settings.

Open issues that are relevant are: #4899 (by Korb) and #3314 (by me).

_This_ issue requests that the above issues be addressed by doing away with the numbered radio buttons and providing proper handling of named templates (aka Presets) **_plus_** an additional enhancement that allows the user to associate a Preset name with the account when the settings are saved.

This would mean that the correct Preset for the account, with all its settings, would be automatically selected if the user:

- Right-clicks on an account in the Navigation tree and selects `Import From | CSV Files...'
or
- Drags a CSV file onto the account (once #3684 is released).
or
- Selects a different account name on the import dialog

![image](https://user-images.githubusercontent.com/4060092/229791448-09996fb8-cddc-427c-a69b-65324c204ce5.png)

<br>

Note that a Presets name can be associated with more than one account. Use case: I have multiple 'Nationwide' accounts, they all have the same CSV format, so can use the same a Preset.

Terminology

We need to decide on appropriate terminology:

- Template?
- Settings?
- Preset?

Looking at the Transaction Filter, we have a mixture of Settings, Preset, and Settings Name:

![image](https://user-images.githubusercontent.com/4060092/229793820-3ca51543-576b-4111-a0a6-f4c9bd8aab7a.png)

**Comment by n-stein** [comment]
Here's a first pass. Saving, loading, deleting/clearing, and setting/removing default presets works. I used the exact same strings as the Transaction Filter for now (since they are already translated), but once a decision is made on terminology we can update in both places.

![mmex_b5jRgzMRNN](https://user-images.githubusercontent.com/16599929/229880581-569a3d74-a748-4a82-abee-6bc681aff1cb.png)

![image](https://user-images.githubusercontent.com/16599929/229937090-695e6d03-f509-4a9e-9571-438dea5a82a3.png)

Existing presets in SETTINGS_V1 don't change and will load properly. There is also no limit on number of presets. 

The account defaults are stored in INFOTABLE_V1 by ACCOUNTID (to avoid issues when accounts are renamed).

![image](https://user-images.githubusercontent.com/16599929/229937499-cd24fb0d-994b-4e8f-b664-d62d741549bd.png)

**Comment by n-stein** [comment]
> * Selects a different account name on the import dialog

Oops, just realized I missed this piece. Will do that tomorrow. In the meantime the other functionality can be tested.

**Comment by tactilis** [comment]
A few minor things:

1. The Settings label needs a colon if it is to be consistent with the other labels on the dialog.
2. The layout looks better if the Settings dropdown and the buttons are aligned as shown:

![image](https://user-images.githubusercontent.com/4060092/230158152-bb276c3b-3b7e-4131-ab84-4c72a6133e49.png)

3. Need to consider consistent terminology (settings vs. template vs. preset) and more explanatory text in the tooltips. Comparing the Import dialog with the transaction Filter:

![image](https://user-images.githubusercontent.com/4060092/230159132-c619d6de-b19b-47e6-8b40-b7605d2ca2a0.png)

![image](https://user-images.githubusercontent.com/4060092/230159176-7c8d3d8b-35e0-44a8-a8bf-a8e7685d1e3a.png)

**Comment by n-stein** [comment]
> 1\. The Settings label needs a colon if it is to be consistent with the other labels on the dialog.
> 
> 2\. The layout looks better if the Settings dropdown and the buttons are aligned as shown:

Done and done.

> 3\. Need to consider consistent terminology (settings vs. template vs. preset) and more explanatory text in the tooltips. Comparing the Import dialog with the transaction Filter:

Ah, I forgot to also copy the tooltips from transaction filter. 

As for consistency, just changing "Settings" to "Presets" would make everything consistent. I feel that "Settings" is too vague and doesn't really describe what these values represent. I also personally prefer "Presets" vs "Templates", but I don't have a strong opinion on the matter.

**Comment by tactilis** [comment]
> As for consistency, just changing "Settings" to "Presets" would make everything consistent. I feel that "Settings" is too vague and doesn't really describe what these values represent.

Yes. Exactly.

**Comment by tactilis** [comment]
I've been thinking about the words I initially suggested for linking a Preset with an account name:

    "Associate Preset with account: %s"

We could make the purpose of the link more self explanatory if we change the words to:

    "Load this Preset when the account is: %s"

**Comment by tactilis** [comment]
Just checking:
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 5 2023 19:27:01
• Git commit: bb3c484 (2023-04-05)


I note that it's the _Preset_ that has an Account associated with it, rather than the _Account_ having an associated Preset.

This means that this:

> Note that a Presets name can be associated with more than one account. Use case: I have multiple 'Nationwide' accounts, they all have the same CSV format, so can use the same Preset.

cannot be achieved.

Ideally, I'd like my Nationwide accounts named:

- Nationwide Joint
- Nationwide Martin
- Nationwide Claudia

all to use the Preset named 'Nationwide Current ac'

My Nationwide Credit Card, which has a different CSV format, would use the Preset named 'Nationwide Credit'

etc.

Effectively this means that the Preset becomes an attribute of the account.

If implementing this is too problematic or could be confusing to the user, then I'll happily stick with what we have now and will save the same settings into multiple Presets with each named according to the account (Joint, Martin, Claudia...)

**Comment by n-stein** [comment]
> I note that it's the _Preset_ that has an Account associated with it, rather than the _Account_ having an associated Preset.
> 
> This means that this:
> 
> > Note that a Presets name can be associated with more than one account. Use case: I have multiple 'Nationwide' accounts, they all have the same CSV format, so can use the same Preset.
> 
> cannot be achieved.

Where are you seeing this? You can save the same preset to multiple accounts:

![image](https://user-images.githubusercontent.com/16599929/230195653-29bdb73d-329c-4ea7-beb4-dba3cd44215a.png)

In the above case, choosing either accountid '3' or '12' will load preset 0.

You just have to:
1. Save your preset 'Nationwide Current ac' as the default for account 'Nationwide Joint'.
2. Switch to 'Nationwide Martin'. Select the 'Nationwide Current ac' preset (if not already selected). Click Save and select the checkbox to 'Load this Preset when the account is: Nationwide Martin'.
3.  Switch to 'Nationwide Claudia'. Select the 'Nationwide Current ac' preset (if not already selected). Click Save and select the checkbox to 'Load this Preset when the account is: Nationwide Claudia'.

Now selecting any of the three 'Nationwide' accounts will load the 'Nationwide Current ac' preset.

Is this not working for you?

**Comment by n-stein** [comment]
Basically enabling/disabling the selected preset as the default for the selected account you have to go through the "Save" button. Maybe that's what's tripping you up. 

Perhaps putting the account default checkbox on the CSV dialog itself would be clearer?

**Comment by tactilis** [comment]
> Where are you seeing this? You can save the same preset to multiple accounts
> Is this not working for you?

> You just have to:
> 1...
> 2...
> 3...

Odd. The above is how I expected it to work when I proposed the checkbox on the Save dialog.
I tried it with a couple of accounts and convinced myself that it was not working; that there was a 1:1 relationship Preset to Account. Hence the comment above.

> Basically enabling/disabling the selected preset as the default for the selected account you have to go through the "Save" button. Maybe that's what's tripping you up.

No, it wasn't that. I was definitely saving.

> Perhaps putting the account default checkbox on the CSV dialog itself would be clearer?

Yes, possibly.

I'll do more testing tomorrow morning (UK) to try to see why I tripped up and to consider whether we can make it more obvious for users.

Thanks for all you are doing on this.

**Comment by n-stein** [comment]
Found a bug -- I need to adjust to handle an account having both a CSV preset and an XML preset. Right now you can only have one or the other. Will store XML presets in a different INFOTABLE_V1 entry.

**Comment by tactilis** [comment]
Testing:
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 6 2023 02:40:41
• Git commit: ec1d7f8 (2023-04-06)

1. The save tooltip shown below, copied from the Transaction Filter dialog is inappropriate here. The _active_ values that are being referred to in the Transaction Filter are its checkboxes that are ticked. And the bit about "current Preset" is inaccurate because the user can enter a different name to save as a new preset.

For the Import dialog, the wording might be better as: "Save current settings as a Preset" and change the title of the save dialog from 'Please Enter' to 'Save Preset'.

![image](https://user-images.githubusercontent.com/4060092/230352367-44f21524-7c83-4b75-b0c2-91379be15c02.png)

<br>

2. The delete tooltip and confirmation shown below, copied from the Transaction Filter dialog could be tidied up.

Tooltip: "Delete Preset"
Dialog title: 'Delete Preset'
Dialog text: "Preset %s will be deleted"  / "Do you wish to continue?"

![image](https://user-images.githubusercontent.com/4060092/230363340-2adaaa35-401e-4ea1-9fd4-c76d4844521a.png)

**Comment by tactilis** [comment]
If you manually select a Preset, the associated settings are loaded as expected.

If you manually change the Account, the associated Preset name _is_ loaded but the settings are not changed.

**Comment by tactilis** [comment]
1. The contents of the File Name field is currently loaded when you select a Preset.

I think it should **not** be part of the Preset's data. This is especially the case now that we have drag and drop on an account to select a file. Having it part of the Preset makes the operation of the dialog confusing.

2. I think the fields on the dialog should be reordered to place the Account field outside of the data format area. The File Name and the Account are the primary inputs to the import process. They should be displayed first as I've mocked up below.

Also the 'Presets:' label should be 'Preset:' (just as we use 'Account:' not 'Accounts:').

I've moved Date Format to where Account used to be.

![image](https://user-images.githubusercontent.com/4060092/230396348-2b9c0726-335f-42ed-96b6-67b701772e3e.png)

I think this looks more streamlined and has a better logical flow given the changes you have made.

**Comment by n-stein** [comment]
#5799 covers all of the requested changes.

**Comment by tactilis** [comment]
> https://github.com/moneymanagerex/moneymanagerex/pull/5799 covers all of the requested changes.

Fast work! Thank you.

Initial observation (more to follow):

1. Because of the account name at the end of the "Load this Preset when..." string, the dialog width changes as you switch accounts. It's not a big problem but it's visually a little distracting as shown because, not only does the dialog width change, but various of the fields do too to preserve the layout.

https://user-images.githubusercontent.com/4060092/230466365-9bada821-09e2-45af-8980-c045de74edb8.mp4

Maybe allow the dialog to grow wider if the length of the account name requires it but then do not shrink the width if the user switches to an account with a shorter name. If the user manually sets the dialog to be wider than required for the longest account name, it is never automatically reduced in width regardless of the account that is selected. 

Alternatively, we could leave your width changing code in place and put the account name on a separate line as shown below. I think it looks OK for short and long names and would prevent width changes for all but the very longest account names.

![image](https://user-images.githubusercontent.com/4060092/230472908-a02137e5-117e-4444-b206-1f33765785b1.png)

![image](https://user-images.githubusercontent.com/4060092/230472963-076a2b73-ac40-42de-a430-92854186817f.png)

**Comment by tactilis** [comment]
2. When you select an account using the dropdown on the Import dialog, you get a line in the log saying: 'Currency: UK Pound' (or whatever the account's currency is).

However, if the account name is pre-loaded by virtue of right clicking on an account in the Nav tree, then the 'Currency: xxxx' line is not displayed. Are we bypassing some processing that normally occurs when you use the dropdown?

**Comment by tactilis** [comment]
3. The widths of the columns in the data Preview panel are reset whenever the field specification is changed either by adding/removing a field name or by moving one up/down.

Here I have dragged out the Preview field widths so that I can see the data:

![image](https://user-images.githubusercontent.com/4060092/230483119-2eb4bbd0-0b0e-4a60-86eb-9571dfebb5a2.png)

But I then realise that I have Deposit and Withdrawal the wrong way around, so I click `Up`.
Rather frustratingly, the column widths are reset. It would be better if this could be avoided when all that has happened is to update the names of the column headers. Is this possible?

![image](https://user-images.githubusercontent.com/4060092/230483854-1a40e156-2466-4d4a-9807-1945fcb0abd1.png)

<br>

4. Is it possible to store the Data Preview column widths in the template so that the user doesn't have to keep resizing them each time an new Import is done? This is similar to storing the Transaction List column widths so that they are restored when restarting MMEX.

NB. This may be a problem on Mac & Linux because I believe @whalley has written that there is a wx limitation on those platforms (or maybe I'm confusing that with something else).

5. It is possible to change the order of the Data columns in the Preview panel. This should not be allowed.

https://user-images.githubusercontent.com/4060092/230486565-727093ea-b5c0-4821-885f-6c59234d020c.mp4

**Comment by tactilis** [comment]
6. The account highlighted in the Nav tree and the account displayed in the transaction panel can become mismatched when right clicking on an account to, for example, import from CSV.

In the video, observe that:
a) 'Barclays' is selected in the Nav tree and displayed in the transaction panel.
b) After right clicking 'Euro test account', that account is now displayed in the transaction panel but both 'Barclays' and 'Euro test account' are highlighted in the Nav tree.
c) After selecting Import from | CSV files and closing the Import dialog, note that 'Barclays' is highlighted in the Nav tree but 'Euro test account' is displayed in the transaction panel.

Is there a way to prevent this mismatch?

The video continues:
d) Single clicking on 'Barclays' does not correct the display in the transaction list (in the video I try this a few times).
e) Double clicking on 'Barclays' does correct the display in the transaction list (as shown at the end of the video).


https://user-images.githubusercontent.com/4060092/230500490-fb7f19a2-b2fd-424e-a74e-1649670353fa.mp4

**Comment by n-stein** [comment]
> 1. Because of the account name at the end of the "Load this Preset when..." string, the dialog width changes as you switch accounts.
>
> Alternatively, we could leave your width changing code in place and put the account name on a separate line

This is certainly the simpler approach, just requires changing the space to a '\n'.

> 2\. When you select an account using the dropdown on the Import dialog, you get a line in the log saying: 'Currency: UK Pound' (or whatever the account's currency is).

Not really bypassing anything, its that the 'Currency: xxxx' log entry is only written in the OnChoiceChanged function which isn't triggered on the initial load. I'll add that log entry separately on dialog creation.

> 3\. The widths of the columns in the data Preview panel are reset whenever the field specification is changed either by adding/removing a field name or by moving one up/down

I'll store the column widths and reapply them every time the preview is updated.

> 4\. Is it possible to store the Data Preview column widths in the template so that the user doesn't have to keep resizing them each time an new Import is done?

Sure. I've stored them in key "FIELD_WIDTHS" and will read & apply whenever a template is loaded.

> 5\. It is possible to change the order of the Data columns in the Preview panel. This should not be allowed.

A bit tricky in a wxListCtrl since column dragging is handled natively, but I'll work on it. If I can't come up with something we might have to switch to a wxDataViewListCtrl which gives us a bit more control.

> 6\. The account highlighted in the Nav tree and the account displayed in the transaction panel can become mismatched when right clicking on an account to, for example, import from CSV.

What is the desired outcome of the right click action itself? 
1. Right clicking switches the account view the same as left clicking, then shows the menu. In this case 'Euro test account' will end up displayed and selected.
2. Right clicking shows the menu, but doesn't switch the account view. In this case 'Barclays' will remain displayed and selected.

**Comment by tactilis** [comment]
> 1, 2, 3, 4

Great. Thank you.

<br>

>> 5. It is possible to change the order of the Data columns in the Preview panel. This should not be allowed.
>
>A bit tricky in a wxListCtrl since column dragging is handled natively, but I'll work on it. If I can't come up with something we might have to switch to a wxDataViewListCtrl which gives us a bit more control.

If it's a problem to solve with wxListCtrl, or if changing wxDataViewListCtrl is a lot of work or could introduce a performance penalty, then I'd just leave things as they are.

Although it makes no sense for a user to drag and reorder the columns, doing so is a purely cosmetic issue. It was just by accident, while resizing a column, that I found it could be dragged too.

<br>

>>  6. The account highlighted in the Nav tree and the account displayed in the transaction panel can become mismatched when right clicking on an account to, for example, import from CSV.
>
>What is the desired outcome of the right click action itself?
>
>1.  Right clicking switches the account view the same as left clicking, then shows the menu. In this case 'Euro test account' will end up displayed and selected.
>2.    Right clicking shows the menu, but doesn't switch the account view. In this case 'Barclays' will remain displayed and selected.

I think for MMEX, option 1 is the safest and most logical approach because the Nav tree and the main panel will then always be in sync. 

At present there is a mix of behaviours where, for some Nav tree nodes, right clicking switches the main panel content _and_ changes the highlight, but for others the highlight is not updated and you can end up with a mismatch.

**Comment by tactilis** [comment]
7. Trailing spaces should be trimmed from Preset names when saving to prevent this:

![image](https://user-images.githubusercontent.com/4060092/230641426-94021b32-e024-434d-960f-de603e8a6c57.png)

It wouldn't harm to trim leading spaces too.

**Comment by tactilis** [comment]
Testing:
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 7 2023 21:01:05
• Git commit: e86f1e5 (2023-04-07)

Observations 1 to 7 above are all fixed. 

The persistent column widths and the right click fix for the Nav tree are a huge improvement.

I'm just wondering whether you would be able to add a date format code to address #5792, so that it makes the 1.6.4 release please?

**Comment by tactilis** [comment]
Oops...

![image](https://user-images.githubusercontent.com/4060092/230684104-73ce3ad9-06a6-4892-9adc-dd15ca2a2aad.png)


The settings:

![image](https://user-images.githubusercontent.com/4060092/230684157-3cce81b3-15bd-4d08-bb0f-84b288f2215e.png)

I'll email you the .csv

**Comment by n-stein** [comment]
> Observations 1 to 7 above are all fixed.

#5 not fixed yet. 

Here is where I'm running into issues: the wxListCtrl doesn't fire an event on column reordering, and the native versions (which Windows uses) don't use a wxHeaderCtrl which does provide that event. So there is no good way to figure out when a user reordered a column other than polling the column order every so often and comparing it to the field selection list (which sounds like a terrible solution).

I am able to switch to a wxDataViewListCtrl fairly easily where I can forbid column dragging, but the problem I'm running into is that adjusting the colors of the rows (which we do for the skipped start/end rows) is tricky. I think it might be possible by creating a custom renderer to paint the rectangle in a different color, but I haven't gotten that far yet.

**Comment by n-stein** [comment]
> Oops...
> 
> ![image](https://user-images.githubusercontent.com/4060092/230684104-73ce3ad9-06a6-4892-9adc-dd15ca2a2aad.png)

Left over bug from #3148. Fixed.

Also fixed two other bugs:
* If the preview had more columns than the Selected Field list, resizing an "Unknown" column threw an error.
* If the default checkbox was disable due to a blank preset selection, saving a new preset didn't enable it automatically. You had to click the dropdown and reselect the new preset.

**Comment by tactilis** [comment]
Testing:
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 7 2023 22:59:24
• Git commit: cdcaf70 (2023-04-07)

Confirmed the duplicate payee 'Oops...' is fixed.

<br>



>>  Observations 1 to 7 above are all fixed.
>
>5 not fixed yet.
>Here is where I'm running into issues: the wxListCtrl doesn't fire an event on column reordering...

As mentioned previously, the fact that you can reorder the columns by dragging the header is not important because:
1. It's a pointless thing to do (I only did it my accident and it was obvious what I had done).
2. It's a cosmetic issue and does not affect the import of data.

If you can prevent it, that's great. But as it is proving harder than expected, I'd be inclined to just leave it as it is.

**Comment by tactilis** [comment]
8. Minor. Could the colour selector be moved closer to the label please like it is on the transaction dialog? At present, I keep visually associating the coloured square with the checkboxes to the right because it's closer to them than it is to its label.

![image](https://user-images.githubusercontent.com/4060092/230709423-dce4af6f-a2a7-426f-a722-ab800d7aaf61.png)


![image](https://user-images.githubusercontent.com/4060092/230709366-87585f91-20f9-4597-9a2f-06068037bddf.png)

**Comment by n-stein** [comment]
> 8\. Could the colour selector be moved closer to the label please like it is on the transaction dialog?

Done 

![image](https://user-images.githubusercontent.com/16599929/230980887-c743b903-90c9-4413-9742-cf80c8f582d7.png)

**Comment by tactilis** [comment]
> Done   (Colour selector)

Sometimes these little things make a significant difference. Thank you for all the ongoing work.
