### ISSUE TITLE
Colour settings are not saved with the template on import dialogs

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5791]
MMEX version:
 - [x] 1.6.4 Beta

# Description of the bug

On the Import from CSV/XML dialogs, the Colour settings are not being saved with the template.

They should be.

![image](https://user-images.githubusercontent.com/4060092/229801147-70fe03c8-025d-40a9-b362-75db760dc1a2.png)

**Comment by n-stein** [comment]
Fixed
