### ISSUE TITLE
New Tranaction widnow is growing after reopening and can't be shrinked down

### ISSUE THREAD

**Issue by FlameHorizon** [moneymanagerex/moneymanagerex#5808]
MMEX version:
 - [x] 1.6.4 Beta.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Linux 

# Description of the bug

New transaction window always can be enlarged but sometimes can't be shrieked down. Also transaction window sometimes grows overtime it's open again until width of monitor is reached.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [x] Randomly 
 - [ ] Happened only once

Reproduction steps:

For shrinking problem.
1. Open new transaction
2. Try to shrink it

For window growing problem.
1. Open new transaction window, observer it's width.
2. Close window.
3. Open it again and notice width.

Expected result:

New transaction window should be always shrinkable and never gets bigger every time it's reopen.

Actual result:

Window gets bigger without option to be resized.

# Additional information

![Peek 2023-04-08 16-21](https://user-images.githubusercontent.com/23423558/230726500-0503f98e-df2d-4ea3-bf95-fb9b6034f617.gif)

Edit: restarting MMEX sometimes helps, but not always.

**Comment by n-stein** [comment]
That fixes it on Debian Bullseye, hopefully same works for you.

**Comment by FlameHorizon** [comment]
Will confirm within this week.

**Comment by FlameHorizon** [comment]
I confirm, problem has been fixed with with built on: Apr 15 2023 03:26:52. I'm closing issue. Thanks!
