### ISSUE TITLE
Account, Payee and Category dropdown lists are not active

### ISSUE THREAD

**Issue by FlameHorizon** [moneymanagerex/moneymanagerex#5809]
MMEX version:
 - [x] 1.6.4 Beta.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Linux 

# Description of the bug
Account, Payee and Category dropdown lists are not active before clicking on adjacent text field

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

1. Open new transaction
2. Try clicking on any "Expand" dropdown list.

Expected result:

Expanding should be enabled from the get-go. I shouldn't be forced to click on adjacent text box.

Actual result:

Dropdown lists can't be expanded.

**Comment by tactilis** [comment]
There are no "adjacent text boxes" on the Transaction dialog:

![image](https://user-images.githubusercontent.com/4060092/230739143-5391f983-2e1a-4dc7-ba0c-2852af50dd2f.png)

Are you talking about the check boxes on the Transaction Filter dialog?

![image](https://user-images.githubusercontent.com/4060092/230739192-6425c9b1-5ebc-4508-83b7-26dbd089cdbd.png)

If so, this is working as intended.

**Comment by n-stein** [comment]
On Linux the dropdown button is disabled until the combobox text field receives focus as seen here:

https://user-images.githubusercontent.com/16599929/230956144-12a38a96-fb95-4160-a609-6478c4e28d29.mp4

**Comment by n-stein** [comment]
Fixed

https://user-images.githubusercontent.com/16599929/231607502-ad9961b5-876f-4b7e-b74b-b5f5b2259d44.mp4

**Comment by FlameHorizon** [comment]
Problem has been fixed with built on: Apr 15 2023 03:26:52. I'm closing the issue. Thanks!
