### ISSUE TITLE
Transaction report: option to group by ID

### ISSUE THREAD

**Issue by fabianrinker** [moneymanagerex/moneymanagerex#5812]
# Description of the feature
Since the changes #3940 #3937 (feature #3935) split transactions are always separate lines.

[In this comment](https://github.com/moneymanagerex/moneymanagerex/issues/3935#issuecomment-951145400) @whalley explains the change.
Unfortunately I missed the discussion back then because I miss the old report since then and would like to have this rather as an option. Other possibility would be to group all splits of one transactions and print a sum (adding "ID" to the "Group By" drop-down).

# Use cases
I often compare the transaction report of MMEX to e.g. the credit card report I received as pdf. Having only split values makes it more difficult to map the transactions.

**Comment by fabianrinker** [comment]
I also tried to implement this myself today and here is my current commit: [https://github.com/moneymanagerex/moneymanagerex/commit/e2304db565bc2508250aa9b94309ab203857bd5e](https://github.com/moneymanagerex/moneymanagerex/commit/e2304db565bc2508250aa9b94309ab203857bd5e)

I decided to add "ID" to the "Group By" drop-down. Downside of this approach is a rather high space consumption for all the headings that only contain the ID:
![image](https://user-images.githubusercontent.com/13711459/230741563-7982e6c6-86fa-44c1-8633-f6622b227998.png)

Since this is my first commit for MMEX ... what do you think? Should I create a pull request?

**Comment by n-stein** [comment]
Looks fine and it works, . I'm wondering if we should (also?) have a different presentation option to "Compress Splits" or "Summarize Splits" which shows a single table with only one summarized line per TRANSID rather than creating separate tables for each TRANSID as 'Group By' does. Would be a bit more complex to implement, but might be more usable. I guess one can always just use the Checking Panel for such comparisons though...

**Comment by tactilis** [comment]
Can't decide which of "Compress Splits" or "Combine Splits" best conveys what it does?

I'm leaning slightly towards Combine - but only just.

Thoughts?

**Comment by tactilis** [comment]
Or even "Group Splits"

**Comment by n-stein** [comment]
Not sure I like "Group Splits" immediately below "Group By". I prefer either "Compress" or "Combine".

**Comment by tactilis** [comment]
> Not sure I like "Group Splits" immediately below "Group By".

Agreed. I wrote Group as a consequence of looking at the issue title... but before I looked at the dialog!

**Comment by n-stein** [comment]
I went with "Combine Splits" with tooltip "Display split transactions as a single row".

@fabianrinker 
> Should I create a pull request?

If you feel the "Group By Transaction ID" option would still be useful given the above option to combine splits in the full report table them then by all means open a PR.

**Comment by tactilis** [comment]
> I went with "Combine Splits" with tooltip "Display split transactions as a single row".

Perfect.
