### ISSUE TITLE
Range options in transaction filter have no effect

### ISSUE THREAD

**Issue by fabianrinker** [moneymanagerex/moneymanagerex#5813]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3
 - [x] 1.6.4-Beta.4

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Selection of "Period Range" or "Date Range" in transaction report is not limiting transaction report to selected timeframe. Instead transactions of all time are shown.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open transaction filter dialog
2. Select a "Period Range" or a "Date Range"
3. press OK

Expected result:
Only selected range is shown.

Actual result:
All transactions are shown.

# Additional information
The issue is **not** present in current stable version 1.6.3.

**Comment by tactilis** [comment]
I am unable to reproduce this.

I've tested 1.6.4 Beta 4 with 4 transactions dated:

1. 01/01/2023  (note Jan)
2. 01/03/2023  (note Mar)
3. 02/03/2023
4. 03/03/2023

I've tried various Date Ranges (e.g 01/01/2023-01/03/2023, 02/03/2023-03/03/2023, etc) and Period Ranges (e.g Current Month, Current Year, etc) in all three views:

- All Transactions | View with Transaction Filter
- Account  | View with Transaction Filter
- Transaction Report | Transaction Filter

All produce the expected results.

@fabianrinker, if you still find the problem repeatable, could you post screenshots of your data, the Filter settings, and the results please.

**Comment by rmelillo76** [comment]
I can reproduce this using a recent beta version:

• Version: 1.6.4-Beta.4 64-bit
 • Built: Apr  6 2023 18:27:45
 • db 18 (aes128cbc)
 • git bbb39fb (2023-04-06)

Tools | Transaction Report Filter:

Using Period Range:

The first page has transactions from 2020, the last page shows the intended filter:
![image](https://user-images.githubusercontent.com/95182117/230788705-d7f6d37f-fca8-4b59-adf4-2725e1c47b34.png)

![image](https://user-images.githubusercontent.com/95182117/230788729-1df59ed6-0c05-4d48-a7c3-9cb986bbfb65.png)
_(Many other pages omitted)_
![image](https://user-images.githubusercontent.com/95182117/230788748-587f4ea8-fbdb-4f8f-9388-ea18f064d74d.png)

I can also reproduce this by selecting individual Date Range values, rather than choosing a Period Range:

![image](https://user-images.githubusercontent.com/95182117/230788957-928608b8-0fca-435f-bae0-0a49d289cd1a.png)

**Comment by fabianrinker** [comment]
@rmelillo76 Thank you for your reproduction, that's exactly the same as I saw it.

But I now additionally noticed that also only filtering for a specific account does not work:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/13711459/230794109-ad0dbf45-459c-4d1c-9468-5ec545fd01cf.png">
![image](https://user-images.githubusercontent.com/13711459/230794159-0b733b6c-3c33-498a-9741-020a6606373e.png)
![image](https://user-images.githubusercontent.com/13711459/230794206-13f94a74-e31e-4f2e-9be3-96a718cbdc5a.png)

**Comment by fabianrinker** [comment]
I tried now all filter settings:

| Filter | |
|--------|--------|
| Account | :x: |
| Period Range | :x: |
| Date Range | :x: |
| Payee | :x: |
| Category | :white_check_mark: | 
| Status | :x: | 
| Type | :x: | 
| Number | ❓* | 
| Color | :x: | 
| Custom Field | :x: | 

* Don't know how this is supposed to work. I entered number "1" and it showed this transaction at the top. But also many others that have no number specified.

**Comment by rmelillo76** [comment]
> I tried now all filter settings. Seems only categories filter works:

I'm not entirely positive, but the common theme so far seems to be that transactions with splits are the ones included in the results even when they fall outside of the date or other criteria.

@n-stein , @vomikan  @whalley  - I hope it's OK for me to reference a closed issue, but I suspect this may have to do with some of the fixes in https://github.com/moneymanagerex/moneymanagerex/issues/5465

**Comment by n-stein** [comment]
> the common theme so far seems to be that transactions with splits are the ones included in the results even when they fall outside of the date or other criteria.

Thanks for digging into this, definitely sounds like #5465. Will take a look in a few hours.

**Comment by n-stein** [comment]
Fixed. Splits were only being checked against fields contained in the SPLITTRANSACTIONS_V1 table, hence why Category, Notes, and Amount worked but everything else did not. They will now be checked against all filter fields.

**Comment by rmelillo76** [comment]
Looks good so far, thanks @n-stein!
