### ISSUE TITLE
Transaction Filter does not work correctly when changing an account

### ISSUE THREAD

**Issue by PaulBP14** [moneymanagerex/moneymanagerex#5817]
In v1.6.3 (and also 1.6.2) Windows 64 bit

Apply a transaction filter by date to an asset account, the filter works as expected.
Select a different asset account, all transactions are displayed.
Select view with transaction filter, the previously selected dates are still there and checked. Click OK - no transactions are displayed

The only way to get it to work is to select another account and then click back to the account you want which then resets the transaction filter.

**Comment by n-stein** [comment]
Issue was the Account ID was being stored in the transaction filter when executed in the checking panel. When you went from one account to another and resubmitted the same filter values, the old Account ID filter was applied as well.

**Comment by PaulBP14** [comment]
Thanks!
