### ISSUE TITLE
Transaction Filter / Nav Label Changes

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5824]
Just a couple of minor suggestions:

1. Change the Navigation panel "Transaction Report" label to "Transaction Reports" to be consistent with "Reports"

![image](https://user-images.githubusercontent.com/95182117/231460405-e16d46c8-9353-4d9f-b1c7-d08a20ed2f26.png)

2. Change the Transaction Filter dialog title from "Transaction Filter" to "Transaction Report Filter" to be consistent with the main menu title:

![image](https://user-images.githubusercontent.com/95182117/231460693-0775da92-8642-4059-b222-39237c2857a3.png)
![image](https://user-images.githubusercontent.com/95182117/231460955-bee89234-ab1a-4536-bc07-21e5c22e3491.png)
![image](https://user-images.githubusercontent.com/95182117/231461211-3da6fc65-65eb-4430-8bf8-888ef4cc764c.png)

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/6460/files
https://github.com/moneymanagerex/moneymanagerex/pull/6467
