### ISSUE TITLE
Transaction Details panel becomes unnecessarily wide when custom field contains data

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5832]
MMEX version:
 - [x] 1.6.4 Beta 4
 
 Tested:
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 14 2023 20:47:16
• Git commit: d21051b (2023-04-14)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The width of the left hand part of the transaction dialog (the Transaction Details panel) becomes unnecessarily wide and cannot be resized narrower when a custom field contains data.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create a transaction. Note that when you edit the transaction, the dialog width is normal. Close the dialog.
 
2. Use the Custom Fields Manager to create a custom field; I created a String field type called MyString.

3. Edit the transaction created at step 1. Note that the dialog width is still normal:
 
![image](https://user-images.githubusercontent.com/4060092/232159590-4df71b06-7e92-4fa1-948c-567fc7380b2f.png)
 
4. Click the arrow icon to show the Custom fields panel. Note that the Transaction Details panel is still normal width:
 
![image](https://user-images.githubusercontent.com/4060092/232160115-38ad2367-17de-4ef9-9824-db866ec57e29.png)
 
5. Enter a value in the custom field:
 
![image](https://user-images.githubusercontent.com/4060092/232160430-a9355d74-6298-4f0d-952a-8b313a153e8a.png)
  
6. Click OK to save the changes and close the dialog.

7. Edit the transaction. Note that the Transaction Details panel has become unnecessary wide:

![image](https://user-images.githubusercontent.com/4060092/232160969-2f3751f1-c960-43bd-8f62-145785cbb164.png)
  
8. With the Custom field panel still displayed, try to reduce the dialog width. It does becomes a little narrower but you cannot return the Transaction Details panel down to its normal width.

9. Click the arrow icon to hide the Custom fields panel. Try to reduce the dialog width. Note that you still cannot reduce the Transaction Details panel to its normal width:
 
![image](https://user-images.githubusercontent.com/4060092/232161828-dc31f7fc-51f3-4cd2-9363-0ec38b5b8471.png)

10. Click the arrow icon to open the Custom fields panel again.
Delete the data in the custom field.
OK the dialog to save and close it.
Edit the transaction again.
Note that although the dialog is initially displayed too wide, it _can_ now be resized down to the normal width (i.e the same as at step 3)

**Expected result:**

The Transaction Details panel should not change width just because a custom field contains data.

**Comment by n-stein** [comment]
fixed
