### ISSUE TITLE
Incorrect total net worth reported on Dashboard 

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#5834]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3 Beta
 - [x] 1.6.4 Beta
 
Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The Dashboard lists total net worth incorrectly as it doesn't account any funds transferred to the Shares Account(s). Note that this error is present only on the Dashboard. The Summary of Accounts report shows the net worth correctly.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by n-stein** [comment]
Fixed
