### ISSUE TITLE
App crashes when opening a database

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#584]
There is a case linked to opening the db on certain Android devices. Can anyone try to debug and let me know what causes the MMEX desktop (tested on Windows) crash when opening testdbPhone.mmb:
http://forum.moneymanagerex.org/viewtopic.php?f=20&t=6229&p=12865#p12865

I've compared the database files in binary mode and the testdbPhone has zz_ZZ vs en_GB somewhere in the file. It is possible that some systems return weird values for locale.

**Comment by MisterY** [comment]
OK, I got it. It's the base currency being set to -1. I guess the system returns a weird locale with no currency.

**Comment by MisterY** [comment]
In any case, this has been handled in the Android app to always use a defined currency in case the system does not provide a valid one.
You can, perhaps, just add some defensive checking in case a currency is not found, just in case.

**Comment by vomikan** [comment]
~~~~~
..\..\src\model\Model_Currency.cpp(106): assert "false" failed in
Model_Currency::GetBaseCurrency().
~~~~~

**Comment by vomikan** [comment]
Should we do somthing on PC version side?

**Comment by vomikan** [comment]
This issue is a distraction from the 1.3.0 release
