### ISSUE TITLE
Help is not displayed in MMEX 1.6.3 on macOS Monterey 12.6.5

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5847]
MMEX version:
 - [x] 1.6.3 Beta

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

As reported on the forum here https://forum.moneymanagerex.org/viewtopic.php?p=23917 by a user running macOS Monterey 12.6.5, MMEX Help is not displayed in 1.6.3 but is shown when they revert to 1.6.1.
 
![image](https://user-images.githubusercontent.com/4060092/233037708-6b471a27-359a-436c-a8fe-f7ec0d0d6d81.png)

 Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Install MMEX 1.6.1 - observe that Help can be displayed. 

Install MMEX 1.6.3 - observe that Help is not displayed.

**Comment by whalley** [comment]
I can't reproduce this on MacOS 10.15.7 or MacOS 13.2.1

**Comment by tactilis** [comment]
Closing this issue because the reported in the forum thread that installing 1.6.4 has resolved their problem.
