### ISSUE TITLE
Crash when creating new database & account

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5852]
MMEX version:
 - [x] 1.6.3 (and all earlier versions back to 1.5.14)

Operating System:
 - [x] Windows 10 and 11 (Norwegian)
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In forum post https://forum.moneymanagerex.org/viewtopic.php?p=23925 the user reports that MMEX closes (it's due to an ACCESS_VIOLATION exception) when creating a new database & account via the wizard.

In a video that the user recorded, the following actions are performed:

1. MMEX is started with no database open.
2. File | New Database...
3. Via the New Database wizard, create the database with base currency set to NOK.
4. Via the Add Account wizard, create a Checking account. Enter the account name and press Finish.
5. At this point MMEX crashes (before the Edit Account dialog has been displayed)

The MMEX window closes without displaying the crash handler dialog.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

As reported, install _any_ version of MMEX from 1.5.14 through to 1.6.3 and the crash occurs.

Install 1.5.13 and the crash does not occur.

Here's the crash dump that the user provided:

[MoneyManagerEx.xml.zip](https://github.com/moneymanagerex/moneymanagerex/files/11284871/MoneyManagerEx.xml.zip)

**Comment by phildivalerio2** [comment]
Exact same issue for me.  I tried using 1.5.13 and it works OK.

**Comment by tactilis** [comment]
@phildivalerio2
> Exact same issue for me. I tried using 1.5.13 and it works OK.

What version of Windows are you using?

What language is Windows set to?

What currency are you setting when you create the database?

**Comment by phildivalerio2** [comment]
Hi,
I use
Windows 11 Pro, 64 bit
Norwegian language.

MMEX will not work on versions above 1.5.13.

My other laptop is
Windows 10 Home, 64 bit
English language

MMEX works fine on the latest update.

Thanks for any help with this issue.

Phil

**Comment by phildivalerio2** [comment]
I'd be interested in knowing if anyone using Windows 11, Norwegian, is able to use MMEX.  Then I would know that it's something to do with my PC.

**Comment by tactilis** [comment]
So, a common factor between the original report (see link to the forum post above) and @phildivalerio2's report is having the language in Windows set to Norwegian.

It may just be coincidental and not the cause but needs investigation.

**Comment by birdnes** [comment]
Hello... I post the orginal report.

My pc run Windows 11 Home 64 bit
English language

mmex crash , only mmex 1.5.13 works

Have a surface with Windows 11 Pro 64bit
Norwegian language

same problem

**Comment by vomikan** [comment]
> mmex crash

Even if you create a new empty database?

**Comment by tactilis** [comment]
> Even if you create a new empty database?

The crash happens as I described in the initial post of this issue, i.e. when Finish is clicked on the New Account wizard. The actions listed in my post are transcribed from a video that @birdnes provided.

**Comment by phildivalerio2** [comment]
Yes.  After creating a new and empty database, MMEX crashes.  I go through
the process of selecting a currency (I have tried different currencies -
same condition) and bank account, and then MMEX crashes.

**Comment by vomikan** [comment]
1) Try portable version  https://ci.appveyor.com/api/buildjobs/9rrwq399can7klra/artifacts/mmex-1.6.4-Beta.4-win64-portable.zip
2) Could you find and delete all mmexini.db3 files?

**Comment by phildivalerio2** [comment]
Thanks, I'll check it out.

**Comment by phildivalerio2** [comment]
I'll try with the Beta.  I've previously worked exclusively with the
portable version though, which is the one that crashes.  The installed
version also crashes.  But I'll give it a try.

**Comment by n-stein** [comment]
If that doesn't work we could use GitHub's history to recompile the 1.5.14 Beta at some points between 1.5.13 and 1.5.14. This would allow us to isolate the commit that first caused this issue.

**Comment by birdnes** [comment]
Just tell me what to download and try

**Comment by n-stein** [comment]
1.5.13 released 2022-02-06
1.5.14 released 2022-04-14

I've rebuilt two portable betas from points between those dates. The date and commit are noted in the filenames. Can you please check if either works for you? Note both are x64 builds.

[mmex-20220221-3bedaf0.zip](https://github.com/moneymanagerex/moneymanagerex/files/11314971/mmex-20220221-3bedaf0.zip)

[mmex-20220312-0d1cc04.zip](https://github.com/moneymanagerex/moneymanagerex/files/11315128/mmex-20220312-0d1cc04.zip)

**Comment by n-stein** [comment]
#5689 is similar

**Comment by birdnes** [comment]
I have tried now and they are both crashing the same way .

**Comment by birdnes** [comment]
I have tried now and they are both working .. No close/crash.

Very Nice

**Comment by phildivalerio2** [comment]
Both crashed for me.

**Comment by n-stein** [comment]
Another. [mmex-20220211-a2242cc.zip](https://github.com/moneymanagerex/moneymanagerex/files/11326432/mmex-20220211-a2242cc.zip)

> Both crashed for me.

The first set or second?

**Comment by phildivalerio2** [comment]
I tried both, and they both crashed.
Windows 11 issue?  Have any others using Windows 11 managed a successful install?

**Comment by tactilis** [comment]
@phildivalerio2
> Have any others using Windows 11 managed a successful install?

Yes. Of course. Otherwise we'd have 100s of bug reports about it.

Your and @birdnes's crashes from 1.5.14 onwards do not occur for (most/all) other users of MMEX.

@birdnes reports that the crash using 1.5.14 onwards also happens for them on Windows 10.

**Comment by n-stein** [comment]
@phildivalerio2 

> I tried both, and they both crashed.

Interesting. I'm surprised the one from 2022-02-06 crashed, that is only a 2 PRs after the 1.5.13 release. Just to test, here is a build of the 1.5.13 release. If this fails for you then perhaps the issue is not MMEX source code but one of the libraries we are linking against.
[mmex-1.5.13-release.zip](https://github.com/moneymanagerex/moneymanagerex/files/11327042/mmex-1.5.13-release.zip)

**Comment by birdnes** [comment]
I have tried "mmex-20220211-a2242cc.zip" and its crashing the same way

**Comment by n-stein** [comment]
Thanks for testing, sorry to make you download and run so many versions.

So a2242cc doesn't work but d0a3f5c does.

That narrows down the list:
![image](https://user-images.githubusercontent.com/16599929/234594198-d24d777f-6d8b-4fc1-bcd6-d2ec93ba39ab.png)

Here's the build after 2af8562. If this works then the issue is contained in PR #4199.

[mmex-20220210-2af8562.zip](https://github.com/moneymanagerex/moneymanagerex/files/11333729/mmex-20220210-2af8562.zip)

**Comment by birdnes** [comment]
"mmex-20220210-2af8562.zip" is working normally with no crash

**Comment by n-stein** [comment]
That narrows it down to PR #4199 which changed the way string formatting works in Model_Currency.cpp

Just curious, can you test this version of 1.6.4 where I've updated the fmt submodule from 8.1.1 to 9.1.0? Perhaps some updates to the fmt library have fixed this issue.

[mmex-1.6.4-fmt_9.1.0.zip](https://github.com/moneymanagerex/moneymanagerex/files/11334414/mmex-1.6.4-fmt_9.1.0.zip)

**Comment by vomikan** [comment]
Can this information help?
https://github.com/fmtlib/fmt/issues/2748#issuecomment-1036749344

**Comment by n-stein** [comment]
> Can this information help?

It might be related. I looked through that thread earlier today when I was checking out #4191 (the issue that #4199 was addressing).

@birdnes what is your system locale? You can see this in "System Information"

**Comment by birdnes** [comment]
Norsk ( Norwegian ), but my main pc is English ( Windows 11 )

**Comment by n-stein** [comment]
Does it crash if you pick a base currency other than NOK when setting up the new DB, such as USD or GBP?

**Comment by birdnes** [comment]
> Does it crash if you pick a base currency other than NOK when setting up the new DB, such as USD or GBP?

Yes... Have tried different currency with same result

**Comment by phildivalerio2** [comment]
Me too.  Choosing another currency has ne effect.

**Comment by birdnes** [comment]
I have now tried to change regional settings on windows 11 to english us and mmex 1.6.3 works perfect.

I should have tried this before. So is in regional settings the problem is. If i change back to Norwegian again mmex close

**Comment by birdnes** [comment]
I have tried to change regional settings with pc running win 11 64 bit with norwegian language.

mmex close.

Conclusion :

Windows 11 64 bit Norwegian language it will not help to change regional settings to english us
the same will happend, mmex close after database make

**Comment by n-stein** [comment]
I was able to reproduce the crash by spinning up a Windows 10 VM in Norwegian language, building MMEX on it, and debugging. Crash was here: 
https://github.com/moneymanagerex/moneymanagerex/blob/158a936f2cf69121b835ecfbc3ebf08cd8e0faf9/src/model/Model_Currency.cpp#L259 and again on https://github.com/moneymanagerex/moneymanagerex/blob/158a936f2cf69121b835ecfbc3ebf08cd8e0faf9/src/model/Model_Currency.cpp#L271 

Removing the `.UTF-8` from the default en_US locale resolves the issue.

**Comment by phildivalerio2** [comment]
Great work.  Will this fox be implemented in the next update?

**Comment by n-stein** [comment]
> Will this fox be implemented in the next update?

Yes, also available now in the beta here: https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/92ef1c3klr94ajdc/artifacts
