### ISSUE TITLE
Transaction sound

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5853]
![image](https://user-images.githubusercontent.com/6836805/233332884-42ffc093-0e14-4eb6-ad36-ef04a5116777.png)

**Comment by tactilis** [comment]
👍

Since the `Use Transaction Sound` label is no longer for a use/don't use checkbox, ideally it should now say:

`Transaction Sound  [None / drop.wav / cash.wav]`

**Comment by vomikan** [comment]
> 👍
> 
> Since the `Use Transaction Sound` label is no longer for a use/don't use checkbox, ideally it should now say:
> 
> `Transaction Sound [None / drop.wav / cash.wav]`

This is true, but I don't want to violate the completeness of the translations. I'm planning an update in the next version.
