### ISSUE TITLE
Stock Portfolios: Click on update throwing Invalid Cookie error

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#5855]
MMEX version:
 - [x] 1.6.3 
 
Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Reproduction
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Clicking on update button as shown at the bottom, is throwing Invalid Cookie error which I have never seen before. May the yahoo link api is updated or an issue with yahoo finance site. Reporting so that it will be looked into.

Thanks in advance.

![image](https://user-images.githubusercontent.com/12392746/233338033-b40917f8-a2b3-4f0a-a12f-6af6c9d07064.png)

**Comment by PaulDarnell** [comment]
Same issue here

**Comment by rmelillo76** [comment]
It was failing for me this morning as well, but is now working again:

![image](https://user-images.githubusercontent.com/95182117/233447597-0960b07c-516b-4e49-b072-9a9e50b31c10.png)

I'm guessing there was something happening with Yahoo that is now resolved.

**Comment by reddyshyam** [comment]
Thanks @rmelillo76, it is working fine my end too. yes, could be the api glitch then. Will close the ticket.
