### ISSUE TITLE
Crash when using Organize Categories or Organize Payees if transaction report is open

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5857]
MMEX version:
 - [x] 1.6.3
 - [x] 1.6.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX crashes if the transaction report is open and you make a change in Organize Categories or Organize Payees.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Execute a transaction report
2. Open Organize Categories dialog
3. Add a new category or edit an existing category & close the dialog

Alternatively
1. Execute a transaction report
2. Open Organize Payees dialog
3. Add a new payee or edit an existing payee & close the dialog

Actual result:
MMEX crashes

**Comment by vomikan** [comment]
@n-stein I couldn't figure out the problem. 

The call initially comes from here:
```void mmGUIFrame::OnOrgPayees(wxCommandEvent& /*event*/)
{
    mmPayeeDialog dlg(this, false);
    dlg.ShowModal();
    if (dlg.getRefreshRequested())
    {
        refreshPanelData();
        RefreshNavigationTree();
    }
}```

The crash occurs on an uninitialized variable.
![image](https://user-images.githubusercontent.com/6836805/234875468-96b7ccc2-327f-4629-b3bf-d1a22e55289a.png)

```void mmPrintableBase::restoreReportSettings()
{
    Document j_doc;
    if (j_doc.Parse(m_settings.c_str()).HasParseError())
        return;
```

**Comment by n-stein** [comment]
I think in mmframe.cpp function createReportsPage the call to cleanupHomePanel is destroying the `rs` mmPrintableBase object which is supposed to pass the report settings to the mmReportsPanel constructor.


```
    wxSizer *sizer = cleanupHomePanel(); 
     panelCurrent_ = new mmReportsPanel(rs 
         , cleanup, homePanel_, this, mmID_REPORTS 
         , wxDefaultPosition, wxDefaultSize, wxNO_BORDER | wxTAB_TRAVERSAL);
```

**Comment by n-stein** [comment]
I've got a fix, but it can go one of two ways:
Should the default be to re-render the transaction report (with updated categories/payees), or to jump back to the home page?

**Comment by tactilis** [comment]
IMO, if you can re-render the transaction report, then that would be best.

The user has deliberately made a change that has the potential to affect the report, so it is to be expected that it will need updating.

Personally, I really dislike the fact that after making certain changes, MMEX jumps to back to the Home (now Dashboard) page, when it should be possible to redisplay the page (generally an Account) that you are currently on.

**Comment by n-stein** [comment]
Fixed.

> Personally, I really dislike the fact that after making certain changes, MMEX jumps to back to the Home (now Dashboard) page, when it should be possible to redisplay the page (generally an Account) that you are currently on.

I modified many of the calls to return you to the previously selected node. Things like editing accounts, viewing program options, opening the GRM editor and others that previously dumped the user back on the Dashboard now keep them on their previously selected panel. Let me know if you notice any that I missed that you feel shouldn't jump to Dashboard.

**Comment by tactilis** [comment]
@n-stein
> I modified many of the calls to return you to the previously selected node. Let me know if you notice any that I missed that you feel shouldn't jump to Dashboard.

Thank you. Will do.

This change may seem like a small thing but it will avoid the unpleasant UX of being jolted away from the task you are undertaking.

**Comment by tactilis** [comment]
Testing:
• Version: 1.6.4-Beta.6 64-bit
• Built on: May 31 2023 19:58:00
• Git commit: 2b33331 (2023-05-31)

1. If you delete an account then, as expected, the view changes to the Dashboard, however the Dashboard node of the Nav tree is not highlighted.

2. If you edit an account (for example change its name or its icon) and the account is also a Favourite account, then the Favourites branch is opened and the account is highlighted there:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/ee173ca1-ce68-4914-962e-694683646c78)

If this can't be fixed easily then don't worry. The behaviour is a big improvement on what would happen previously.

**Comment by n-stein** [comment]
> 1. If you delete an account then, as expected, the view changes to the Dashboard, however the Dashboard node of the Nav tree is not highlighted.

This one is easy.

> 2. If you edit an account (for example change its name or its icon) and the account is also a Favourite account, then the Favourites branch is opened and the account is highlighted there:

This one a bit trickier. Since the itemIDs may change every time the nav tree is recreated I use the item data to find an item with matching data. It selects the first item whose data matches, hence why it selects the one in "Favorites" before the one in the account sections.

**Comment by n-stein** [comment]
> It selects the first item whose data matches, hence why it selects the one in "Favorites" before the one in the account sections.

Will search first under the previous parent, then under root if not found.

**Comment by n-stein** [comment]
Done

**Comment by tactilis** [comment]
> Done.
It doesn't completely eliminate the issue if the item changes sections such as reallocating a bank account to a term account

Thank you. It's much better.
The remaining case is not a problem because the need to reallocate an account is such a rare event.
