### ISSUE TITLE
Category Report fails reporting 0 even if expenditures are present

### ISSUE THREAD

**Issue by stefanospizzica** [moneymanagerex/moneymanagerex#5860]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [] 1.6.2
 - [ ] 1.6.3 Beta
 - [x] 1.6.3
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I select Report->Category I have some category with 0 as total on some months. If I select the category then I can see the single expenditure for that months that have zero as sum. I have noted that transactions with Id < 10000 are not counted in the grandtotal.

Example: in the 1.jpg screenshot you can see that Appartamento:assicurazione category has 0 in January 2022 but if I click on the category you can see that payment are present in January itself (2.jpg).

Thanks
Stefano

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![1](https://user-images.githubusercontent.com/9107166/234325973-d5d44fbf-ca1f-43f9-abdc-5ab07abccf5f.jpg)
![2](https://user-images.githubusercontent.com/9107166/234326320-2c678b4a-26a4-4d3d-9a46-d32a18682f77.jpg)

**Comment by renato-mmex** [comment]
I would suggest installing the latest version of MMEX 1.6.3:
https://moneymanagerex.org/
or try with the latest beta version:
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/46898316/job/emgy47vophw3ydpb/artifacts

**Comment by stefanospizzica** [comment]
I have already the 1.6.3.
Now I have installed 1.6.4 Beta but the same problem occurs.
I have exported QIF files and imported them in a different financial software (free) and it works. correctly.
I think that if the problem still continue, I will move to a different application.

Thanks
Stefano

**Comment by stefanospizzica** [comment]
And I have noted right now the there is a new bug because the overall grandtotal is now wrong (it was correct in the 1.6.3).
I cannot revert to 1.6.3 because it says that database is not compatible.
What a disaster!!!!! Really a very very crappy piece of software....

**Comment by renato-mmex** [comment]
A thousand other users do not seem to have these problems and are satisfied with MMEX.
Those who have no patience and express themselves poorly, only harm themselves.

**Comment by stefanospizzica** [comment]
No need to comment

**Comment by n-stein** [comment]
Anybody have a method to reproduce this issue? I don't see anything wrong with the report in my databases.

**Comment by stefanospizzica** [comment]
Hi,

the only screenshots I have available to support the solution of the problem are the ones below which show the detail expenditure months by months but in the overall report some months are zero.
Please not the error seems to happen when the ID of the transaction has a value < 10000 (or is seems so).
![overall](https://user-images.githubusercontent.com/9107166/235485565-de0149fd-4452-4e78-bda9-3e2b9ef8c0fa.jpg)
![detail](https://user-images.githubusercontent.com/9107166/235485593-70e14a66-5b1b-4533-aa2e-9b762907a744.jpg)

As you can see the first three monts has ID less than 10000 and they are not summed in the grandtotal

**Comment by renato-mmex** [comment]
Question: how are these values set?
<img width="466" alt="image" src="https://user-images.githubusercontent.com/76920138/235508444-b0f4588c-7211-4469-a1d4-d27ebcbbd346.png">

**Comment by stefanospizzica** [comment]
![Immagine 2023-05-01 205000](https://user-images.githubusercontent.com/9107166/235510370-e37e8466-bb42-41ed-98b5-4dfbf9a9596a.jpg)
![Immagine 2023-05-01 205158](https://user-images.githubusercontent.com/9107166/235510397-66d3bbf5-40e2-4d8e-848f-6be7c9b5b12b.jpg)

**Comment by stefanospizzica** [comment]
But, as I said before, I see that transaction with an ID in the range of 1800 are not computed, while transaction with ID > 10000 are ok. How are the grandtotal in the category report sheet calculated?

**Comment by tactilis** [comment]
> But, as I said before, I see that transaction with an ID in the range of 1800 are not computed, while transaction with ID > 10000 are ok.

Are you sure It relates directly to the value of ID?

In general, but depending on the order in which transactions have been created, those with a lower ID are for earlier dates those with a higher ID are for later dates.

Could this simply be a date related issue?

Could you edit ID <1800 and one of the ID > 10000 transactions so that you swap the dates? Does that change which is included which is excluded from the report? (check the IDs)

**Comment by stefanospizzica** [comment]
Hello

I did the job to swap two transactions:

BEFORE SWAPPING:
August Grandtotal = 0, September Grandtotal = 18.29
Aug has 1 transaction, ID 1847, with value 19.90 which is not reported in the grandtotal (FAIL)
Sep has 1 transaction, ID 12364, with value 18.29 which is reported in the grandtotal (GOOD)

So I edited the 1847 and set date and value related to 12364 and then edited 12364 and set date and value related to 1847

AFTER SWAPPING:
Aug Grandtotal = 19.90, Sept Grandtotal = 18.29
Aug has 1 transaction, ID12364, with value 19.90 which is reported in the grandtotal (GOOD)
Sep has 1 transaction, ID1847, with value 18.29, which is reported in the grandtotal (GOOD)

Both are correct now, but I'm confused...

**Comment by tactilis** [comment]
> AFTER SWAPPING:
> ...

Now please swap them back, taking care to return them exactly to the state they were in originally.

Is the report now identical to the BEFORE SWAPPING case?  Or has something changed?

Are the re

**Comment by stefanospizzica** [comment]
Hello

I swapped again 1847 and 12364 to return to the original condition where ID1847 refers to August and 12364 refers to September.

The situation is still in the condition AFTER SWAPPING, so both August and September are now correct in the summary

**Comment by stefanospizzica** [comment]
But now I did another simple action: I edited a transaction with summary 0 and simply saved it without changing anything. After this move the report is now correct...

**Comment by n-stein** [comment]
There must be something about the way those transactions are stored in the database causing this -- some field filled with an erroneous value. If you have any still showing the 0 error, can you take a look at the raw data for that transaction using any SQL DB browser to open your MMB file?

**Comment by n-stein** [comment]
> simply saved it without changing anything. After this move the report is now correct

The fact that just opening & saving fixes it leads me to believe it is related to the LASTUPDATEDTIME going from blank to filled, as that would be the only field that has changed.

**Comment by stefanospizzica** [comment]
I think I have found something strange in the database, corrupted transactions seem those who have splitted items inside and categid is different from -1.

Example of a transaction which is not summed correctly:
![wrong](https://user-images.githubusercontent.com/9107166/235766031-06eb73ec-5391-434e-be25-9e9dbad8f2eb.jpg)

Example of a transaction which is summed correctly:
![ok](https://user-images.githubusercontent.com/9107166/235766110-743d4eab-0288-4f9b-9147-649cfc39c0c4.jpg)

Please note that categid=167 in the first wrong transaction has nothing to do with the transaction itself:
![cat167](https://user-images.githubusercontent.com/9107166/235766604-ece99bf5-1876-403a-9299-d07f8a955b4b.jpg)

Cat167 is named manutenzione and in the transaction 1233 there is no mention to this category...

**Comment by vomikan** [comment]
Once upon a time, I made a report that showed transactions with problems. It's time to update it using your case.

https://github.com/moneymanagerex/general-reports/tree/master/packages/Transaction/InvalidTransactions

**Comment by stefanospizzica** [comment]
> Once upon a time, I made a report that showed transactions with problems. It's time to update it using your case.
> 
> https://github.com/moneymanagerex/general-reports/tree/master/packages/Transaction/InvalidTransactions

Thanks, I run the query and I found many ERROR .... but how to correct them?

**Comment by vomikan** [comment]
> but how to correct them?

I do not recommend making corrections at the database level (unless you are a super expert). The easiest way is to create the correct transactions and delete the incorrect ones.

**Comment by stefanospizzica** [comment]
I see that actually your report cannot find errored multilevel transaction... now I have a problem because corrupted transactions are hundreds and manual correction one by one seems not the easiest way..

**Comment by stefanospizzica** [comment]
Basically, If I have correctly understood the db logic, the following query tells me which are the wrong transactions:

select * from CHECKINGACCOUNT_V1 c where categid <> -1 and c.TRANSID in (select Transid from SPLITTRANSACTIONS_V1)

Evey transaction which has splitted items, should have categid = -1, am I correct?

**Comment by vomikan** [comment]
> Evey transaction which has splitted items, should have categid = -1, am I correct?

Seems yes, you are correct.

**Comment by vomikan** [comment]
@n-stein , it seems we need to change the logic of the application. If there is a reference to a category in the SPLITTRANSACTIONS_V1 table, then assume that it is split.

At the moment, it looks like the ghost split is -1 in the category field of the CHECKINGACCOUNT_V1 table.

**Comment by stefanospizzica** [comment]
This query seems to solve the issue, now at a first sight, the sum in the report seem correct...

update CHECKINGACCOUNT_V1
set categid=-1
where categid <> -1 and CHECKINGACCOUNT_V1.TRANSID in (select Transid from SPLITTRANSACTIONS_V1);

**Comment by stefanospizzica** [comment]
and..thanks to vomikan for his support... ;-)
