### ISSUE TITLE
1. Implement `Theme Mode` = `Auto` to select `Light`/`Dark` theme from operating system setting; 2. Rename `Auto` to `System`.

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5861]
1. Set operating system to use dark theme.
2. Open MMEX.
3. Buttons in the top row could be better.
4. Dashboard shows in light theme. 

![image](https://user-images.githubusercontent.com/17465872/234415965-237ddad2-4bac-405c-b470-d97e74038176.png)

Thank you

**Comment by renato-mmex** [comment]
It would be helpful to know with which operating system and which MMEX version the error occurs.

**Comment by n-stein** [comment]
MMEX doesn't currently auto-detect when the OS is in dark mode. You have to manually switch to the dark theme using the theme manager (or view options) to get the white icons and the dark dashboard.

**Comment by ovari** [comment]
```
Money Manager Ex
• Version: 1.6.4-Beta.4 64-bit
• Built on: Apr 24 2023 03:26:30
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-41-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by ovari** [comment]
@n-stein does that mean that `Theme Mode = Auto`, shown in the image below, is not yet implemented?

![image](https://user-images.githubusercontent.com/17465872/234720418-f60cbb19-bc59-4f77-a0da-8daf009308c9.png)

@vomikan should the `question` label be removed?

Thank you

**Comment by n-stein** [comment]
> does that mean that `Theme Mode = Auto`, shown in the image below, is not yet implemented?

Correct, it is not yet implemented. Right now Auto == Light.

**Comment by n-stein** [comment]
> Correct, it is not yet implemented. Right now Auto == Light.

Sorry, this was not quite correct. It is implemented on macOS only. It is not implemented yet for Windows or Linux.

**Comment by ovari** [comment]
Should `Auto` be changed to `System`?

**Comment by ovari** [comment]
> The exact same code works for Windows, but perhaps we should hold off on the Windows change until dark mode is improved on that platform. Thoughts?

Something is better than nothing. Can the improvements please be applied?

**Comment by n-stein** [comment]
> Can the improvements please be applied?

They already were. They were merged after the nightly build, so check the beta tomorrow.

**Comment by ovari** [comment]
Is https://github.com/moneymanagerex/moneymanagerex/pull/5866 all that is needed to change `Auto` to `System`?

**Comment by n-stein** [comment]
> Is #5866 all that is needed to change Auto to System?

I believe so. Everything is based on the index of the choices rather than the text strings themselves. As long as "System" remains the first option (index 0) it should work.

**Comment by ovari** [comment]
> > Is #5866 all that is needed to change Auto to System?
> 
> I believe so. Everything is based on the index of the choices rather than the text strings themselves. As long as "System" remains the first option (index 0) it should work.

Can you please merge?

**Comment by ovari** [comment]
Can the theme please update if MMEX is opened and then the system theme is changed?

Firefox does this if there are pointers in the Firefox code.

Thank you
