### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by TonySLondon** [moneymanagerex/moneymanagerex#5869]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3 Beta
 - [x] Other (please specify)
1.6.3 64bit
Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
If I turn off the 'favourites' account by unticking the 'favourites' box in the edit account facility, the account disappears from favourites but also dissappears from Bank Accounts!
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
@TonySLondon Please check your Options | View settings.

I expect you have Accounts Visible set to Favourites, so when you unFavourite an account it is no longer visible.

![image](https://user-images.githubusercontent.com/4060092/235143506-f393e86b-812b-40ff-a438-5f2ef44515b2.png)
 
Change the setting to ALL or Open.

**Comment by ovari** [comment]
Is there any reason to shout in the drop-down? Should `ALL` be changed to `All`? Thank you

**Comment by whalley** [comment]
@TonySLondon Can this be closed? Did the response from @tactilis help resolve your 'issue'?

**Comment by whalley** [comment]
Closing...
