### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5870]
![image](https://user-images.githubusercontent.com/6836805/235141011-70f545e4-29f2-48cf-8eda-a685d0f264a8.png)

![image](https://user-images.githubusercontent.com/6836805/235140465-0f6f3349-9240-439b-b249-eadbb404c911.png)

**Comment by vomikan** [comment]
curl -XGET "https://api.github.com/repos/moneymanagerex/moneymanagerex/releases/latest"                                  curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

curl -XGET "https://api.github.com/repos/moneymanagerex/moneymanagerex/releases/latest" -k
working

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/discussions/5777#discussioncomment-5753598

**Comment by gabriele-v** [comment]
Sorry @vomikan but this is not a fix, you are introducing a security hole not checking for SSL.
With this change, potentially a malicious version of MMEX could be downloaded from client, I think we should revert it immediately.

**Comment by gabriele-v** [comment]
BTW I think it was a temporary GitHub issue because now is working for me

**Comment by vomikan** [comment]
> BTW I think it was a temporary GitHub issue because now is working for me

I keep getting the same error.
I don't think that the lack of certificate verification is a serious problem in our case. We download the JSON file to a specific address and extract the product version.

**Comment by gabriele-v** [comment]
> > BTW I think it was a temporary GitHub issue because now is working for me
> 
> I keep getting the same error.
> I don't think that the lack of certificate verification is a serious problem in our case. We download the JSON file from a specific address and extract the product version.
> 
> 
> 
> 

SSL is needed to guarantee that specific address is the real Github server. If client is pointed (IE with a DNS spoofing attack) to a fake server with some malicious code, SSL is the only way to detect and stop it.
