### ISSUE TITLE
Initialized when entering Unicode characters in the custom field Tooltip.

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#5875]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x] 1.6.3
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

Initialized when entering Unicode characters in the custom field Tooltip.
(custome field Tooltip 항목에 문자를 입력하면 입력 내용이 모두 초기화 됩니다)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
New/Edit Custom Field dialog
![스크린샷 2023-04-29 204750](https://user-images.githubusercontent.com/110871727/235301203-b1938c92-3fa8-4259-b9d6-6c9a94a70c6e.png)
Korean, Chinese, Special Char. typing any 2byte characters. just one char or nchar.
and click OK.

Expected result:

Actual result:

![스크린샷 2023-04-29 204806](https://user-images.githubusercontent.com/110871727/235301204-2b19b8ac-8b4a-4d4d-98be-32e5f5cbcdc1.png)

reOpen Edit Custom Field dialog
![스크린샷 2023-04-29 204814](https://user-images.githubusercontent.com/110871727/235301206-282e24cd-8dcf-4064-a233-518124c77064.png)

??? Initialized empty field...

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Affects all text fields other than name: Tooltip, RegEx, Default, and Choices

**Comment by n-stein** [comment]
Fixed

**Comment by rmelillo76** [comment]
Looks good - and just to have a little fun with it: 🤣

![image](https://user-images.githubusercontent.com/95182117/236348814-c176270b-c4f3-4337-836e-49578a8d7e76.png)

![image](https://user-images.githubusercontent.com/95182117/236348738-e46e63ca-b77b-474c-841a-33fc3593e402.png)
