### ISSUE TITLE
Debug report when trying to set category limit in "Budget Setup"

### ISSUE THREAD

**Issue by AverPower** [moneymanagerex/moneymanagerex#5879]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [x] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

When try to set budget limits to categories, window "debug report mmex" appears. So I can't specify limits at all/

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Create year in menu "Budget Setup". Then double click on category (any except first one)/ Then appears error windows and application carshes.

Expected result:
Window when I can specify limit for the category

Actual result:
Error
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by AverPower** [comment]
![Снимок экрана от 2023-04-30 16-25-13](https://user-images.githubusercontent.com/48547158/235355702-a43f6873-dfc5-47df-95fd-90468a4cfe23.png)

**Comment by n-stein** [comment]
I am unable to reproduce this. There have been many fixes since 1.6.2. Would you mind testing the latest 1.6.4 beta to check if your issue has been resolved?

Here is the link to the latest Linux beta:
https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/655/workflows/d8ea3fcd-a67f-4c79-872b-262a36db0efd/jobs/651/artifacts

**Comment by AverPower** [comment]
Sorry. I didn't mention that I've tried older versions and other OS.
I can add a link to my database - you would be able to reproduce it. Is that ok?


> I am unable to reproduce this. There have been many fixes since 1.6.2. Would you mind testing the latest 1.6.4 beta to check if your issue has been resolved?
> 
> Here is the link to the latest Linux beta: https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/655/workflows/d8ea3fcd-a67f-4c79-872b-262a36db0efd/jobs/651/artifacts

Sorry. I didn't mention that I've tried older versions and other OS.
I can add here a link to my database - you would be able to reproduce it. Is that ok?

**Comment by n-stein** [comment]
Does #5686 accurately describe your issue?

**Comment by AverPower** [comment]
@n-stein Yep... Thanks. Should I close this issue?

**Comment by AverPower** [comment]
@vomikan Could you explain - #5586 - is it solved? What should I do? Deal with it?)

**Comment by tactilis** [comment]
> Could you explain - https://github.com/moneymanagerex/moneymanagerex/pull/5586 - is it solved?

Yes it is solved and will be in 1.6.4.

You can either wait for that release (it won't be too long now).

Or you could use a beta version. For Windows see here https://ci.appveyor.com/project/whalley/moneymanagerex

**Note:** Installing 1.6.4 will update the database schema. You won't be able revert to 1.6.3 with an updated .mmb database

**Comment by AverPower** [comment]
@tactilis thanks a lot! Will be waiting with patience)
