### ISSUE TITLE
Remove `Dialog` and `Window` from source strings

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5881]
Please remove `Dialog` and `Window` from en source strings.

The words `Dialog` and `Window` are superfluous.

Please see comments in translation at https://crowdin.com/translate/moneymanagerex/470/en-pt?filter=basic&value=0#784842

What do you think?

Thank you

**Comment by tactilis** [comment]
> Please remove Dialog and Window from en source strings.

Yes please.

- Currency Dialog
- Relocate Category Dialog
- Relocate Payee Dialog

Are there any others?

**Comment by ovari** [comment]
Examples:

1. `Relocate Category Dialog` → `Relocate Category`
https://crowdin.com/translate/moneymanagerex/470/en-hu#784814
1. `Relocate Payee Dialog` → `Relocate Payee`
https://crowdin.com/translate/moneymanagerex/470/en-hu#784842
1. `Transactions Dialog` → `Transactions`
https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=dialog
1. `Tip: You can modify some runtime behavior of MMEX by changing the options in the Options Dialog. ` → `Tip: Change MMEX Options to modify some runtime behaviors. `
Change first-person to third-person.
https://crowdin.com/translate/moneymanagerex/470/en-hu#783808
1. `Organize Categories Dialog Tip: Pressing the h key will cycle through all categories starting with the letter h` → `Organize Categories Tip: Pressing the h key will cycle through all categories starting with the letter h`
https://crowdin.com/translate/moneymanagerex/470/en-hu#783814
1. `Organize Categories Dialog Tip: Pressing 2 key combination will cycle through all categories starting with that key combination. Example: Pressing ho will select Homeneeds, Home, House Tax, etc...` → `Organize Categories Tip: Pressing 2 key combination will cycle through all categories starting with that key combination. Example: Pressing ho will select Homeneeds, Home, House Tax, etc…`
Change 3-character ellipsis `...` to a 1-character ellipsis `…`
https://crowdin.com/translate/moneymanagerex/470/en-hu#783816
1. `Show the Options Dialog` → `Show Options`
https://www.microsoft.com/en-us/language/Search?&searchTerm=show%20options&langID=382&Source=true&productid=undefined
https://crowdin.com/translate/moneymanagerex/470/en-hu#784152
1. `&Show App Start Dialog` → `&Show Options menu at Startup`
https://crowdin.com/translate/moneymanagerex/470/en-hu#797194

What do you think?

Thank you

**Comment by ovari** [comment]
1. https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=dialog
1. https://crowdin.com/translate/moneymanagerex/470/en-hu?filter=basic&value=0#q=window

**Comment by tactilis** [comment]
Items from your examples above:

3 - Where is `Transactions Dialog` displayed please? I can't find that title on a dialog.

8 - `&Show App Start Dialog` → `&Show Options at Startup` should be `&Startup Options...` for the reasons:

   a. `Show *Options* at Startup` risks confusing Startup options with the with the main MMEX Options
   b.  `Show Options at *Startup*` displays the options straight away, not just at startup. Hence my use of  `&Startup Options...`

Also this string could be changed:

![image](https://user-images.githubusercontent.com/4060092/235850267-b2f2025c-b6d4-415d-b4d4-f1e48f55fb66.png)

**Comment by ovari** [comment]
8. Whatever works. Here are some more option:
a) &Do not show this dialog again
b) &Show this dialog box at startup
https://www.microsoft.com/en-us/language/Search?&searchTerm=show%20this%20dialog&langID=382&Source=true&productid=undefined

**Comment by tactilis** [comment]
> a) &Do not show this dialog again

Not this because:
1. The existing logic of the checkbox has to be reversed (i.e. needs a code change as well as a label change).
2. It sounds rather final, like "Do not show it again" ever!

<br>

> b) &Show this dialog box at startup
Yes, could just leave it as it is.

**Comment by nmsleal** [comment]
Yes, these "Dialog" words shouldn't exist for the users, as they are used mainly by developers. The main program's window is never mentioned as such - I vote for more coherency and less technical terms! Thanks!

**Comment by nmsleal** [comment]
Another example:
Specify the base (or default) currency to be used for the
database. **The base currency can later be changed by using
the options dialog**. New accounts, will use this currency by
default, and can be changed when editing account details.
