### ISSUE TITLE
`Transaction Filter` is bigger than the screen

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5885]
```
Money Manager Ex
• Version: 1.6.4-Beta.5 64-bit
• Built on: May 3 2023 03:26:09
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-41-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

# Description of the bug

`Transaction Filter` is bigger than the screen.

The default height of the `Transaction Filter` window should be at most the high of the available screen real estate and be resizable.

If required, should there be a vertical scrollbar in the Transaction Filter window?

![image](https://user-images.githubusercontent.com/17465872/236051996-fd132fa6-4c64-4020-93e7-b9dc0f9652f2.png)

### Reproduction

Is the bug reproducible? Always 

### Reproduction steps:

1. Computer with small screen.
2. Set screen to bigger resolution

### Expected result:

`Transaction Filter`:
1. fit in screen
2. be resizable
3. if required, have a vertical scrollbar

Thank you

**Comment by tactilis** [comment]
>  1. Computer with small screen.
>  2. Set screen to bigger resolution

What resolution are you running your screen at?  If I copy your screenshot, it appears to be approx 3070 x 1728

What Font Size do you have set in Options | View Options?

**Comment by ovari** [comment]
![Linux Mint Display](https://user-images.githubusercontent.com/17465872/236055038-df93e005-90ac-4a40-95f5-8d9654425cee.png)

![MMEX UI Appearance](https://user-images.githubusercontent.com/17465872/236055234-32b1abd7-d234-4f00-83ca-ed1eeca59db0.png)

**Comment by ovari** [comment]
@n-stein could you please have a look at this? Thank you

**Comment by n-stein** [comment]
I've put the field list is now inside a scroll window. Max dialog height is now the display height.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/ef2d91f7-456f-4cf7-bc97-ce31d3411e65)

Looks OK on Windows, but having some issues getting the scroll window to render the proper size on Linux...

**Comment by tactilis** [comment]
Should not be Closed yet since @n-stein wrote: _"but having some issues getting the scroll window to render the proper size on Linux..."_

**Comment by n-stein** [comment]
I've got it to work on Windows and Linux, but Linux required this odd line to render properly. I couldn't figure out why this was necessary:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/fb90f0e1-322c-4b2d-a16a-bbe0be331e5d)

Without it, the color button is so thin it is almost non-existent.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/a8c62e5c-60f3-4f84-bea6-56d009ac79c7)

With this line it renders properly:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/3fc593dd-1cc3-475c-b82a-9ecb7a76c7b1)

Windows behaves as expected -- without the line it renders properly, and with the line the box renders twice the height it should be.

@whalley can you check how the dialog looks on macOS?

**Comment by ovari** [comment]
Not fixed with settings as shown at https://github.com/moneymanagerex/moneymanagerex/issues/5885#issuecomment-1533785931

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/a5322a9d-0623-468e-93d7-bfa18cd695e0)

```
Money Manager Ex
• Version: 1.6.4-Beta.7 64-bit
• Built on: Jun 12 2023 03:28:32
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-43-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

Thank you

**Comment by tactilis** [comment]
> Not fixed...
Money Manager Ex
• Version: 1.6.4-Beta.7 64-bit
• Built on: Jun 12 2023 03:28:32
• Database version: 18 (aes128cbc)
MMEX is using the following support products:

Where is the Git commit line which normally follows the 'Database version' line?

> Built on: Jun 12 2023 03:28:32

It looks as though you _may_ be running a version that is earlier than the latest fixes that @n-stein made.

**Comment by ovari** [comment]
> Where is the Git commit line which normally follows the 'Database version' line?

Sorry, don't know.

**Comment by n-stein** [comment]
@ovari Commits aren't part of the beta builds until a pull request is opened. I just created the PR for this an hour ago, so it wouldn't be included in the nightly build you are testing. It is in the Windows build now and will be in the next nightly Linux build.

**Comment by ovari** [comment]
1. Thank you the `Transaction Filter` dialog is much better.
2. Is the height of the `Color` (`Colour`) field (shown with red arrow) correct?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/57ca20fd-5218-4a9b-8d44-27c519b99a30)

```
Money Manager Ex
• Version: 1.6.4-Beta.7 64-bit
• Built on: Jun 12 2023 23:03:41
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-43-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
> Is the height of the Color (Colour) field (shown with red arrow) correct?

Well, yes and no. No, that is not the intended size (the height is doubled), but yes it is correct because wxWidgets is working properly in that build while it seems to be working improperly on mine. I'll remove the line that is causing the double height.

**Comment by ovari** [comment]
Does a bug report need to be written at wxWidgets?

**Comment by n-stein** [comment]
> Does a bug report need to be written at wxWidgets?

Not yet, needs more investigation to determine the cause. Since it is working for you it is most likely an issue with my specific wxWidgets build. Let me rebuild 3.2.2.1 from scratch and see if it works. If not, I'll try 3.1.7 which is the version that yours was built with.

**Comment by tactilis** [comment]
@n-stein
> I introduce enough bugs as it is...

😆 I can't let that comment pass!

You are doing a fantastic job Nick; adding new capabilities (and fixing bugs), building on and extending the work that others have done before you.

Your effort is very much appreciated.

**Comment by ovari** [comment]
Fixed with https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/751/workflows/76459c3a-1309-422c-9a7f-5b01a1c9d324/jobs/747/artifacts

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/267b84c8-bdf2-4240-b9f2-20d5140d0563)

```
Money Manager Ex
• Version: 1.6.4-Beta.7 64-bit
• Built on: Jun 13 2023 08:42:44
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-43-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

Thank you
