### ISSUE TITLE
1. Remove `Sub Category:` from budget entry dialog; 2. Show entire category path in `Category:`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5892]
With the implementation of nested categories, category and subcategory should be merged into category. It is understood that `subcategory` no longer exists in the database file.

### Correct for first level category, as no `Sub Category` shown

![No Sub Category shown](https://user-images.githubusercontent.com/17465872/236574851-d480e21a-13dc-4e69-ad7c-cf9e6b77574c.png)

### Suggested improvements for image below
1. Remove `Sub Category:` line
2. In `Category:` change `Diesel` to `Automobile:Gas:Diesel:kj`

![image](https://user-images.githubusercontent.com/17465872/236575576-d589fa67-5b33-4f70-af94-53a6d208cb0d.png)

What do you think?

Thank you

MMEX version 1.6.4-Beta.5 64-bit
Operating System: GNU/Linux

**Comment by ovari** [comment]
@n-stein could you please have a look at this? Thank you

**Comment by n-stein** [comment]
Dialog gets a bit wider when the full name is used, especially when the category is deep. Does this look OK?

Before:

![image](https://user-images.githubusercontent.com/16599929/236724929-a4bd6cf7-67d9-427e-bf8c-331a694f0259.png)



After:

![image](https://user-images.githubusercontent.com/16599929/236725019-ce4f5d13-b957-4067-8b43-43971c87b5be.png)

**Comment by ovari** [comment]
> Dialog gets a bit wider when the full name is used, especially when the category is deep. Does this look OK?

Looks OK. What happens if it is wider than the screen, does a horizontal scrollbar get added?

Thank you

**Comment by n-stein** [comment]
The space after the `:` is there because my selected delimiter in options is `': '`.

The pane is not currently within a scrolled window, so will not get scroll bars automatically.

Is it necessary to show the full categname? What about this layout with just the parent?

![image](https://user-images.githubusercontent.com/16599929/236725513-465ac8e7-d1ae-4de3-8f81-898ea8e7fd93.png)

**Comment by ovari** [comment]
Would be better to show the entire category.

Please refer to the image below. A budget entry for `Water` would not indicate the property if only the direct parent was shown.

![image](https://user-images.githubusercontent.com/17465872/236726094-8d83352e-0acb-4ae5-8c6f-1e66c01ef3c6.png)

Thank you

**Comment by tactilis** [comment]
@n-stein 
> The pane is not currently within a scrolled window, so will not get scroll bars automatically.
> display full name and remove subcategory

Note that we have seen in past github issues and on the forum that some people use _very_ long `category:subcategory...` names   (even with just 2 levels), so for them the dialog would become unreasonably wide.

Could we perhaps have a fixed dialog width and, if that is insufficient to display the category, could the string be truncated with a trailing ellipsis? A hover-over tooltip could then display the full string, exactly as happens in the account transaction list when the Category column is too narrow.

There may be a few other places that this approach could be adopted to prevent dialogs from growing unreasonably wide.

**Comment by tactilis** [comment]
> Not sure where we draw the line of reasonableness.

I'd limit it to no more than 1.5 times the current dialog width. Any wider and the Estimated & Actual labels and their values become spaced too far apart.

**Comment by n-stein** [comment]
Would a set number of characters work? It would be simpler than trying to cut the string by the text extents.

Here's what a limit of 50 characters looks like:

Under limit:
![image](https://user-images.githubusercontent.com/16599929/236959936-e1310ae3-3a5a-4a76-b131-99e60d7f9ea2.png)


Over limit:
![image](https://user-images.githubusercontent.com/16599929/236959960-d897e829-58c0-48c4-84a0-9055011e105a.png)

Widest character is W, so max width would be:
![image](https://user-images.githubusercontent.com/16599929/236960309-f7ecca54-3007-4b8d-88d0-735cdc52e22a.png)

**Comment by ovari** [comment]
If the mouse hovers over a category which is has `...`, does it show a bubble with the category from the beginning?

**Comment by ovari** [comment]
Does this work with small form factors? For example, if MMEX was installed on a mobile screen form factor would this work?

[Librem 5](https://puri.sm/products/librem-5/) is a GNU/Linux desktop computer in a mobile device?

Thank you

**Comment by ovari** [comment]
Should the 3-character ellipsis `...` be replaced with a 1-character ellipsis `…`?

`(categname.size() > 50 ? "..." + categname.substr(categname.size() - 50) : categname));`
be
`(categname.size() > 50 ? "…" + categname.substr(categname.size() - 50) : categname));`

https://github.com/n-stein/moneymanagerex/commit/9fa7bd190936ab7b236f28d56f7d8e0d0d0224d6#diff-954691fd0c5c90040a49cb07faddac7c67a8892495e57c50d8d1c374f9c8ba27R112

Thank you

**Comment by vomikan** [comment]
Fixed?

**Comment by n-stein** [comment]
Yeah, fixed.
