### ISSUE TITLE
REPORTS - On all charts 

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5893]
# Graph - Point of Description intem

The request concerns the addition of "Values" such as "Percentage" and "absolute value" inherent in the graph. This is to allow, for example, to print only the graph without the data, leaving only the totals. The reason is to highlight the values when in the graph we have many "slices / sections" that hide the values.

This one if it's a simple thing it would be nice to have it in version 1.6.4

Add screenshots, design images or other files which would help for

If not obvious, explain the use cases or problems to solve.

![RPORT](https://user-images.githubusercontent.com/128650264/236645469-634f4d0b-2791-4f75-a208-cbc43a036471.JPG)

Other example

<img width="1920" alt="REPORT 2" src="https://user-images.githubusercontent.com/128650264/236645494-12bd0402-dc0f-4736-944d-3a400d78f644.png">

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5904#event-9255818786
