### ISSUE TITLE
Can not update stock prices. Get invalid cookie error.

### ISSUE THREAD

**Issue by dobber1** [moneymanagerex/moneymanagerex#5894]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5890

**Comment by vomikan** [comment]
I'm researching this case. The link to get quotes returns an incorrect result.
```
https://query1.finance.yahoo.com/v7/finance/quote?symbols=IBM&fields=regularMarketPrice,currency,shortName

{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
```

But V6 returns correct result
```
https://query1.finance.yahoo.com/v6/finance/quote?symbols=IBM&fields=regularMarketPrice,currency,shortName

{"quoteResponse":{"result":[{"language":"en-US","region":"US","quoteType":"EQUITY","typeDisp":"Equity","triggerable":true,"customPriceAlertConfidence":"HIGH","currency":"USD","marketState":"CLOSED","exchangeTimezoneShortName":"EDT","gmtOffSetMilliseconds":-14400000,"esgPopulated":false,"regularMarketPrice":173.57,"exchange":"NMS","shortName":"Apple Inc.","exchangeTimezoneName":"America/New_York","market":"us_market","regularMarketTime":1683316804,"fullExchangeName":"NasdaqGS","sourceInterval":15,"exchangeDataDelayedBy":0,"tradeable":false,"cryptoTradeable":false,"firstTradeDateMilliseconds":345479400000,"priceHint":2,"symbol":"AAPL"}],"error":null}}
```

**Comment by vomikan** [comment]
We don't have a file format check in our code, which is received in response in the function
bool mmStocksPanel::onlineQuoteRefresh

**Comment by n-stein** [comment]
Swapping to v6 in mmex::weblink::YahooQuotes seems to work OK. Currency rates and stock values all update properly as far as I can see. Can we just switch over to v6?

**Comment by n-stein** [comment]
Alternatively we can stick with V7 but first CURL finance yahoo.com to pull a session cookie as seen here https://github.com/pstadler/ticker.sh/blob/acquire-yahoo-finance-session/ticker.sh#L40-L49

**Comment by reddyshyam** [comment]
Hi both (@n-stein, @vomikan), not to add pressure but v1.6.4 is long over due. 😊 Just kidding.

Hope stock update fix makes into it and sometime soon.

**Comment by vomikan** [comment]
In the browser, I get the value, but not in the application.

![image](https://user-images.githubusercontent.com/6836805/236867966-6d49f912-dc4e-4091-8cc5-8e7095756dea.png)

**Comment by n-stein** [comment]
I think the cookie from the finance.yahoo.com call needs to be passed to CURL with the `-c` option in order to pick up the crumb.

**Comment by reddyshyam** [comment]
> I think the cookie from the first finance.yahoo.com GET needs to be passed to CURL with the `-c` option in order to pick up the crumb. The `http_get_data` call is not doing this.

Just thinking aloud, can we not switch to Google finance api which I think is more stable and long runner?

**Comment by n-stein** [comment]
@vomikan I think this needs to be reopened. The v6 API is no longer functioning.

**Comment by n-stein** [comment]
> Just thinking aloud, can we not switch to Google finance api which I think is more stable and long runner?

As far as I am aware Google Finance doesn't have a public API endpoint so the only option there is web scraping. Better to get the Yahoo v7 endpoint working again.

**Comment by thinkpad4** [comment]
@n-stein Is this the V7 API?  `https://query1.finance.yahoo.com/v7/finance/chart/RADICO.NS?&interval=1m`  which when I click on it seems to work

**Comment by n-stein** [comment]
Yup, seems they again removed the crumb verification check for V7. So good news is the panel button should work in 1.6.3, at least for now.

**Comment by thinkpad4** [comment]
Well damn, thought that was the solution

**Comment by thinkpad4** [comment]
@n-stein `https://rapidapi.com/blog/best-stock-api/`

**Comment by n-stein** [comment]
> Yahoo V6 and V7 are permanent shutdown it seems

Yahoo officially "shutdown" its API in 2017, but the endpoints are still functional (for now). They've just added a few hoops to jump through.

**Comment by thinkpad4** [comment]
@n-stein What about this:  `https://query1.finance.yahoo.com/v8/finance/chart/{ticker}` endpoint which seems to work. The response format is slightly different but seems to contain the same information.

E.g. to get the current price:

Old endpoint: quoteResponse.result[0].regularMarketPrice

New endpoint: chart.result[0].meta.regularMarketPrice

Found that here: `https://stackoverflow.com/questions/76059562/yahoo-finance-api-get-quotes-returns-invalid-cookie`

**Comment by n-stein** [comment]
> What about this: https://query1.finance.yahoo.com/v8/finance/chart/{ticker} endpoint which seems to work.

As far as I am aware the v8 endpoint doesn't provide a method to fetch all quotes at once, only one symbol at a time.

I've been working with v7. It seems like CURL is not an option because the cookies are set using javascript and not in the response headers. I am able to extract the crumb using wxWebView, but when I execute the v7 query I am prompted to download the resulting json to a file (which is the default behavior of IE). Need to find a way to set the mime type to plain text or else download the file automatically to memory.

**Comment by reddyshyam** [comment]
To extract share prices and historical data using cURL, you can make HTTP requests to the Yahoo Finance API endpoints. Here's an example of how you can retrieve the current share price and historical data for a specific stock using cURL:

Share Price:

`# Replace 'AAPL' with the stock symbol you want to retrieve the price for
curl -X GET "https://query1.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price" -H "accept: application/json" | jq '.quoteSummary.result[].price.regularMarketPrice.raw'
`
This command sends a GET request to the Yahoo Finance API endpoint for the specified stock symbol (in this case, 'AAPL' for Apple). It uses the jq command-line tool to parse the JSON response and extract the regular market price.

Historical Data:

`# Replace 'AAPL' with the stock symbol you want to retrieve historical data for
curl -X GET "https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1d&interval=1d" -H "accept: application/json" | jq '.chart.result[0].indicators.quote[0].close'
`
This command retrieves the historical closing prices for the specified stock symbol (in this case, 'AAPL') using the Yahoo Finance API. It requests one day of historical data with a daily interval. The response is parsed with jq to extract the closing prices.

**Comment by reddyshyam** [comment]
Sorry, the above might only work for v6. The above is chatgpt extract.

**Comment by reddyshyam** [comment]
Above is chatgpt answer, though it says its realtime info is cut off to 2021, surprised to see versions 10 and 8 mentioned in api calls.

**Comment by n-stein** [comment]
We currently use v8 for history. It seems v10 only works with single symbols, not all symbols at once. At least I couldn't find a way to generate a multi-symbol dataset. We could iterate through them, but that will generate many web requests to refresh all symbols (which likely won't make Yahoo very happy).

@vomikan
I can get the v7 API to work using this code:

```
wxString getYahooFinanceQuotes(const wxString& URL) {

    bool pageLoadFinished = false;
    wxFrame* frame = new wxFrame(nullptr, wxID_ANY, "");
    wxWebView* webView = wxWebView::New(frame, wxID_ANY);

    webView->Bind(wxEVT_WEBVIEW_LOADED, [&](wxWebViewEvent& event)
    {
        pageLoadFinished = true;
    });
    
    webView->LoadURL("https://finance.yahoo.com");
    
    while (!pageLoadFinished)
        wxYield();
    
    pageLoadFinished = false;
    webView->LoadURL("https://query1.finance.yahoo.com/v1/test/getcrumb");
    
    while (!pageLoadFinished)
        wxYield();
    
    wxString crumb = webView->GetPageText();

    pageLoadFinished = false;
    webView->LoadURL(URL + "&crumb=" + crumb);
    
    while (!pageLoadFinished)
        wxYield();

    wxString json_result = webView->GetPageText();

    webView->Destroy();
    frame->Close();

    return json_result;
}
```

calling it like this in util.cpp:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/8345e6c0-8674-449f-9e0a-e394619b4c17)


but we need to specifically set a registry entry so that Internet Explorer opens JSON data in-browser instead of downloading:

```
[HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/json]
"CLSID"="{25336920-03F9-11cf-8FD0-00AA00686F13}"
"Encoding"=hex:08,00,00,00
```

I tried a bit but couldn't get wxRegKey to set this programmatically, maybe due to it being in the HKCR hive?

Likely wouldn't be an issue if we used the Edge backend, but that isn't feasible without upgrading to the unreleased wxWidgets 3.3 (due to lack of VFS support in 3.2).

**Comment by reddyshyam** [comment]
Again from chatgpt, will the below work for multiple symbols?

**Replace** 'AAPL,MSFT,GOOGL' with the comma-separated list of stock symbols you want to retrieve prices for
`curl -X GET "https://query1.finance.yahoo.com/v10/finance/quoteSummary/{AAPL,MSFT,GOOGL}?modules=price" -H "accept: application/json" | jq '.quoteSummary.result[].price.regularMarketPrice.raw'
`

**Replace 'AAPL,MSFT,GOOGL' with the comma-separated list of stock symbols you want to retrieve historical data for**
`curl -X GET "https://query1.finance.yahoo.com/v8/finance/chart/{AAPL,MSFT,GOOGL}?range=1d&interval=1d" -H "accept: application/json" | jq '.chart.result[].indicators.quote[].close'
`

**Comment by n-stein** [comment]
I think ChatGPT is wrong on this. 

You can test by trying those URLs directly:
https://query1.finance.yahoo.com/v8/finance/chart/{AAPL,MSFT,GOOGL}?range=1d&interval=1d
https://query1.finance.yahoo.com/v10/finance/quoteSummary/%7BAAPL,MSFT,GOOGL%7D?modules=price

That is how it works for v7 (without the curly braces), but trying the same for v8 or v10 yields:

In v8:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/4f1e7118-deba-4883-83a3-07a5ee2ec5fa)

In v10:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/6a41bd10-ce55-4e64-8f93-8a532046a088)

**Comment by reddyshyam** [comment]
Sorry @n-stein, trying to help but adding to the woes.

**Comment by n-stein** [comment]
No worries, I appreciate the input. It's always helpful to have other suggestions, there may (likely) be something completely obvious I've missed.

**Comment by reddyshyam** [comment]
Thanks @n-stein 

The Yahoo Finance API does not support querying multiple stock symbols in a single request using the curly braces notation. Each symbol needs to be queried separately.

To retrieve historical data for multiple stock symbols in the browser using the Yahoo Finance API, you can use the following JavaScript code:

**Replace symbols with an array of stock symbols you want to retrieve historical data for**
`const symbols = ['AAPL', 'MSFT', 'GOOGL'];

symbols.forEach(symbol => {
  fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=1d&interval=1d`)
    .then(response => response.json())
    .then(data => {
      const quotes = data.chart.result[0].indicators.quote[0].close;
      console.log(`Historical data for ${symbol}:`, quotes);
    })
    .catch(error => console.error(error));
});
`
In this code, the symbols array contains the list of stock symbols for which you want to retrieve historical data. The forEach loop iterates over each symbol and makes a separate HTTP GET request to the Yahoo Finance API for that symbol. The response is parsed as JSON, and the closing prices are extracted and logged to the console.

**Comment by n-stein** [comment]
Fixed, please test.

**Comment by reddyshyam** [comment]
Hi @n-stein, 

Thanks for the fix, it works but does take time, may be because of symbol iteration. It takes couple of seconds. Also I noticed, history picks up current date i.e. 1st June in historical data while the trading didnot happen for the day yet! As it is 12:10am Indian Standard Time.

<img width="151" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/12392746/2e43e038-1f3a-4ead-860c-4b1bfa1849f7">

Also on the stock summary, should the price date be the last day the exchange run i.e. 31st May or the current date which is 1st Jun?

<img width="359" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/12392746/10bc4251-ddfb-4783-8091-7990105bf97f">

**Comment by n-stein** [comment]
> it works but does take time, may be because of symbol iteration

There is no symbol iteration since I am using the V7 API I am able to collect quotes for all symbols at once. The delay is due to the initial GET request to https://finance.yahoo.com which is _very_ bloated and takes a long time to load. 

I'll try to cache the cookie and crumb in the mmexini.db3 database and only refresh the cookie when it expires. That way the first pull will take a little longer to initialize but subsequent refreshes will be fast.

**Comment by n-stein** [comment]
Ok, done. The cookie & crumb are now stored in mmexini.db3. The quote refresh tries to use these values first, and only pulls new values if it fails.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/0a95a099-41a3-4244-bd0f-7eb70b43e2a7)

Refreshes are fast now. Give it a try.

**Comment by n-stein** [comment]
> Also on the stock summary, should the price date be the last day the exchange run i.e. 31st May or the current date which is 1st Jun?

It reflects the latest date in your Stock History. You have values for June 1st, hence you are seeing that date in the panel.

**Comment by n-stein** [comment]
> Also I noticed, history picks up current date i.e. 1st June in historical data while the trading didnot happen for the day yet! As it is 12:10am Indian Standard Time.

Which symbol? Mine don't display June 1st yet either through the History download or the quote refresh.

**Comment by thinkpad4** [comment]
@n-stein the latest dev build is working for me, I can get stock prices again

**Comment by reddyshyam** [comment]
> > Also I noticed, history picks up current date i.e. 1st June in historical data while the trading didnot happen for the day yet! As it is 12:10am Indian Standard Time.
> 
> Which symbol? Mine don't display June 1st yet either through the History download or the quote refresh.

HI @n-stein, that may be because you checked the same day the trading closed. I checked next day just past midnight.

**Comment by reddyshyam** [comment]
> > Also on the stock summary, should the price date be the last day the exchange run i.e. 31st May or the current date which is 1st Jun?
> 
> It reflects the latest date in your Stock History. You have values for June 1st, hence you are seeing that date in the panel.

Trading hasn't started for the day. Like I said it is midnight on 1st June here. Also it has same value as previous trading date which is 31st May. Please see the screenshots shared in the original post where I mentioned update delays.

**Comment by reddyshyam** [comment]
> Reference

All symbols. So generic issue I guess but if you want to check one then please use ITC.NS

**Comment by reddyshyam** [comment]
> Ok, done. The cookie & crumb are now stored in mmexini.db3. The quote refresh tries to use these values first, and only pulls new values if it fails.
> 
> ![image](https://user-images.githubusercontent.com/16599929/242419228-0a95a099-41a3-4244-bd0f-7eb70b43e2a7.png)
> 
> Refreshes are fast now. Give it a try.

Yes, it is. Thanks @n-stein. Back to good old days. 😎

**Comment by n-stein** [comment]
> Also I noticed, history picks up current date i.e. 1st June in historical data while the trading didnot happen for the day yet!

The historical download isn't the one that pulls current date. Historical download only pulls close prices. The June 1st entry you see is a result of clicking the panel button to fetch the prices after midnight. That button doesn't pull close prices, it pulls the current market price.

The quote refresh button on the panel always pulls the current market price from Yahoo and saves it with the current date. It doesn't care whether the market is open or not -- it's just the price that Yahoo reports at the moment you click the button. While the market is closed the market price is obviously the same as the last close price. When the market opens you can click refresh and it will update to the new market price. This is the way it has always worked.

**Comment by reddyshyam** [comment]
> > Also I noticed, history picks up current date i.e. 1st June in historical data while the trading didnot happen for the day yet!
> 
> The historical download isn't the one that pulls current date. Historical download only pulls close prices. The June 1st entry you see is a result of clicking the panel button to fetch the prices after midnight. That button doesn't pull close prices, it pulls the current market price.
> 
> The quote refresh button on the panel always pulls the current market price from Yahoo and saves it with the current date. It doesn't care whether the market is open or not -- it's just the price that Yahoo reports at the moment you click the button. While the market is closed the market price is obviously the same as the last close price. When the market opens you can click refresh and it will update to the new market price. This is the way it has always worked.

Seems like the case/logic. Works for me, just wanted to bring to your notice in case it was not observed. Thanks for the clarification, @n-stein. 'Good to go' from myside as well. 👍👏🎉

**Comment by renato-mmex** [comment]
Is this Beta version also available for MAC ?

Here   https://onedrive.live.com/?authkey=%21AEWtos0VyDKnlN4&id=A0FB83D788D2D744%21104142&cid=A0FB83D788D2D744 
there is none.

**Comment by n-stein** [comment]
Not yet, @whalley will need to build it

**Comment by whalley** [comment]
> Not yet, @whalley will need to build it

Should be there now..

**Comment by Heny67** [comment]
Hi All!
The date is fine for me, but the prices are not correct. I looked at several stocks and the same error.



![Névtelen](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/a7a50e99-3363-4754-8deb-e87cd51457b5)

**Comment by vomikan** [comment]
> the prices are not correct.

If the trading session is open, the price can vary greatly. Maybe this is the reason?

**Comment by n-stein** [comment]
No this doesn't make sense, IUSE.L hasn't had a trading low in the 80's since June 1st.

**Comment by vomikan** [comment]
The value 88.34 is strangely repeated at regular intervals.

**Comment by n-stein** [comment]
@vomikan you made quite a few changes in f57918fe5c4fd672ca6eae8aa219c0bd90ac482b when we briefly switched to the v6 API. Do we need to revert any since we moved back to v7?

**Comment by vomikan** [comment]
> @vomikan you made quite a few changes in [f57918f](https://github.com/moneymanagerex/moneymanagerex/commit/f57918fe5c4fd672ca6eae8aa219c0bd90ac482b) when we briefly switched to the v6 API. Do we need to revert any since we moved back to v7?

This changes have been made to check JSON Integrity.  It shouldn't affect. But the probability of error, as practice shows, is always there.

**Comment by n-stein** [comment]
I think the issue could be here:

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/stockdialog.cpp#L483

When the user clicks the save button whatever value is in the current price field gets applied to whatever date is in the history date text box. So if you click a line in the history panel and click save it will overwrite that line with the current price. This is why you see the same value repeated multiple times, it is overwriting on the save click. I don't think we should be doing this.

**Comment by n-stein** [comment]
@Heny67 If you simply download rates then view them (don't click the save or add buttons) is the price correct?

**Comment by reddyshyam** [comment]
> I think the issue could be here:
> 
> https://github.com/moneymanagerex/moneymanagerex/blob/master/src/stockdialog.cpp#L483
> 
> When the user clicks the save button whatever value is in the current price field gets applied to whatever date is in the history date text box. So if you click a line in the history panel and click save it will overwrite that line with the current price. This is why you see the same value repeated multiple times, it is overwriting on the save click. I don't think we should be doing this.

Sorry to butt in but this is still a bug, isn't it?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6030

This case closed!

**Comment by n-stein** [comment]
> this is still a bug, isn't it?

Yes, I think that line should be using Today instead of the date from the history text control, i.e. if the user changes the current price and clicks save it updates _today's_ price in the history data to whatever the user entered in the Current Price box, not some other historical date.

Looks like #6030 was opened to track this.

**Comment by n-stein** [comment]
> Edit securities investment menu, I clicked on the update rate button, the update share history window appeared, I pressed Ok and the data is not updated

As I mentioned up thread the history download function within the Edit Stock Investment dialog only pulls data through the _prior_ day. You won't receive data for 6/17 until your system date is 6/18. If you want data for the current date you have to use the Tools > Download Rates menu path or press the refresh button at the bottom of the investment panel.
