### ISSUE TITLE
Payess - TRANSACTION DETAILS

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5897]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3
 - [x] 1.6.4 Beta

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the OPTIMIZATIONS

In fact it is not a real bug but an interested optimization. It is about adding the balance of the Payess account as it happens on the Transaction reports based on the criteria selected.
Here I think it can be put since the balance concerns only one payees

Add screenshot or other files if needed.

![Payess](https://user-images.githubusercontent.com/128650264/236908525-2abc5b4d-ac0d-445f-8436-055ca68a9d79.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by rmelillo76** [comment]
Hi @MAPA2023 

>
> balance of the Payees account 
>

There is no actual Payee account in MMEX, MMEX is designed to act as a register of the activity in your **Bank** account, and  each record within the account contains the Payee that was used for that transaction. 

Have you looked at grouping the transaction report by Payee?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/91149c12-444f-4e56-ad0a-fe5abbb37c6b)

That will create individual groups sorted by payee, and the total amount for each one is shown at the bottom of the section like in the example below:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/bddd20fb-21c3-4a98-9827-b48acf624a79)

If you are requesting a "running balance", similar to what is displayed on the account views, that is not something the transaction report is designed to do, and in my opinion wouldn't make much sense anyway. The balance on the account view is representational of all the items in the account itself, not the payee.
