### ISSUE TITLE
Currency Dialog Representation

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5901]
MMEX version:
 - [x ] 1.6.4 Beta.5 64bit  May 9 2023

Operating System:
 - [x] Windows

Is the bug reproducible? 
 - [x] Always 

**Actual result:**

<img width="742" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/07cab5f6-6195-4ee9-b068-a839c607c0d3">

**Comment by tactilis** [comment]
You can drag the dialog size to be wider.
The new width is remembered across runs of MMEX.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/23061472-c221-4d0a-9802-cd2996373145)


The Currency dialog works OK with the different `Options | View | Font size` settings, except perhaps `Huge` (but that's a ridiculously large font).

**Comment by renato-mmex** [comment]
Presumably tactilis does not use the same version of MMEX.
My tests always run on the latest available MMEX version, currently 1.6.4 Beta.5 64bit May 9 2023 / Normal Font.
by the way: it should also work with other font sizes like "ridiculously large font", which are very useful on high resolution screens.

**Comment by tactilis** [comment]
> Presumably tactilis does not use the same version of MMEX.

Tested on:

• Version: 1.6.4-Beta.5 64-bit
• Built on: May 10 2023 07:05:22
• Database version: 18 (aes128cbc)
• Git commit: 0dda79c (2023-05-10)

<br>

> it should also work with other font sizes like "ridiculously large font", which are very useful on high resolution screens.

Good point.

**Comment by n-stein** [comment]
Columns now autosize and name column is resizable in the left side table.

**Comment by renato-mmex** [comment]
**Unfortunately, this version does not bring any improvement either.**
![image](https://github.com/moneymanagerex/moneymanagerex/assets/76920138/7de7e35d-adbc-4243-ac6b-bcd3c510e006)


![image](https://github.com/moneymanagerex/moneymanagerex/assets/76920138/ef03bc77-c39b-4585-a472-abdd5ed5425b)

**Comment by n-stein** [comment]
Fixed now.

**Comment by renato-mmex** [comment]
Congratulations, it works, best thanks
