### ISSUE TITLE
REPORTS - On all charts on V. 1.6.4

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5904]
# Graph - Point of Description intem

The request concerns the addition of "Values" such as "Percentage" and "absolute value" inherent in the graph. This is to allow, for example, to print only the graph without the data, leaving only the totals. The reason is to highlight the values when in the graph we have many "slices / sections" that hide the values.

This one if it's a simple thing it would be nice to have it in version 1.6.4

Add screenshots, design images or other files which would help for
<img width="1920" alt="REPORT 2" src="https://github.com/moneymanagerex/moneymanagerex/assets/128650264/51dd59a3-a30c-4e49-8232-02c6e4c88d8c">
and
![RPORT](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/9d24bdbf-e994-43c5-b0b2-322bf7ae2331)

If not obvious, explain the use cases or problems to solve.

Add screenshots, design images or other files which would help for

understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by n-stein** [comment]
In the first image, it is not possible to have the hover tooltip display a different string than the legend. So the tooltip displays the value twice 'percent value category value':

![mmex_iLGqyZPJSB](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/c4b53710-5e1f-4455-929e-dc00c227504c)

Personally I feel this looks a bit cluttered, it is hard to read the legend with the extra numbers there.

**Comment by MAPA2023** [comment]
Hi Stein,

thanks for your reply and how you exposed the data on the graph which in my personal opinion is perfect.

My consideration arises from the fact that you could only print the part of the graphs with the economic contents even if repeated.
This is especially true when the "graphic area of the percentage" is so small that it cannot report the data.

Having said that what you have exposed in your immage sent,  the graph is exactly my need and I find it very readable. I consider it a great added value on the data presented.

I really hope it is accepted it would be very useful for me.

Ciao.

Max.
________________________________
Da: n-stein ***@***.***>
Inviato: giovedì 11 maggio 2023 23:31
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: MAPA2023 ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] REPORTS - On all charts on V. 1.6.4 (Issue #5904)


In the first image, it is not possible to have the hover tooltip display a different string than the legend. So the tooltip displays the value twice 'percent value category value':

[mmex_iLGqyZPJSB]<https://user-images.githubusercontent.com/16599929/237816337-c4b53710-5e1f-4455-929e-dc00c227504c.png>

Personally I feel this looks a bit cluttered, it is hard to read the legend with the extra numbers there.

**Comment by MAPA2023** [comment]
I would add, as already mentioned, that having the data displayed is also important for printing the graphs on paper only.
You are very good at development and analysis, I know that you can find a solution that displays the data clearly by reiterating that for me, as you put them, they are perfect.

**Comment by n-stein** [comment]
I can adjust the tooltip text by editing the formatter in htmlbuilder.

![mmex_jUdGHEkksq](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/03290848-390a-42ea-9422-84e9fee8f257)

Also made the % and $ bold to try to make it more readable. It still looks cluttered to me, but interested to hear some other opinions.

**Comment by MAPA2023** [comment]
Gooo, thank you ... know that if you were a woman I would marry you :):).

I really like your idea. You can bold the symbol of the ex Currency. € or $ and the percentage. I think your observation is right and makes the values more readable even when printed on paper.
A suggestion, if I may, could be to align the percentage value as well as the absolute value to the right. I'm trying to give you an example but remember this is perfect.

Here is the example:
25% - €     -100.00 - Costs: Gas
15% - €   -1000.00 - Costs: Electricity
  8% - € -10000.00 - Costs: Various
Remember it's just a suggestion but already as you've done it's perfect. The Pop Up on the graph, on the other hand, is right.

It would be really valuable to me if you can implement it in the next version 1.6.4 or one of its Betas.

**Comment by MAPA2023** [comment]
Idea to PRINT ON PAPER

![Print idea](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/d3f3e944-b95c-43cf-b576-b1d20e89a6be)

**Comment by n-stein** [comment]
I've pushed a change that reformats the legend, but leaves the tooltip alone.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/48401127-c988-4f4b-b35f-8e6c373a753f)

You can test it out here:
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/47052470

**Comment by MAPA2023** [comment]
Hi Stein,

it might be correct. Another point to make to better show the data could be to put the standard of always 2 decimals. (formerly 120.00 or 45.00)

Ciao.

Max.


________________________________
Da: ovari ***@***.***>
Inviato: martedì 16 maggio 2023 10:29
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: MAPA2023 ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] REPORTS - On all charts on V. 1.6.4 (Issue #5904)


Should the label Unknown be Uncategorized?

That is, if there are transactions without a category, does the chart group them into the Uncategorized category?

Thank you

**Comment by n-stein** [comment]
> Should the label Unknown be Uncategorized? 
> That is, if there are transactions without a category, does the chart group them into the Uncategorized category?

In the current iteration of the program "Unknown" is the default text for category ID `-1`. In this case the "Unknown" is there because I imported a CSV file with no category column and no payee default categories, hence those transactions have category `-1`.  The chart is not doing any data modification, "Unknown" is literally the CATEGNAME in CATEGORY_V1.

Of course we can change the default category name, but since it's unrelated to this change it should be opened in a new issue for consideration.

**Comment by n-stein** [comment]
> Another point to make to better show the data could be to put the standard of always 2 decimals.

I'm not sure about this one, it might not make sense in all cases. Some currencies use 0 or 3 decimal places, and some reports in MMEX are not currency based (such as the Usage report).

**Comment by MAPA2023** [comment]
Thanks Stein, yes it seems correct to me not to put anything! I don't waste an idea it could be to use the record that has the most decimals and and complete the others by difference.

**Comment by ovari** [comment]
> Of course we can change the default category name, but since it's unrelated to this change it should be opened in a new issue for consideration.

Done at https://github.com/moneymanagerex/moneymanagerex/issues/5924

Thank you
