### ISSUE TITLE
Import from CSV with more than one positive income source/deposit

### ISSUE THREAD

**Issue by CasiN335** [moneymanagerex/moneymanagerex#5907]
# Description of the feature

Hello, I read the planned improvement for Import CSV and selecting Type and Amount. As it is now it is very confusing/counter intuitive but the update in Beta has fixed that. My request would be to allow the 2 other settings to work: "Positive values are deposits" and "Positive values are withdrawals". In the CSV file from my bank the "Type" is what kind of action it was, card payment, transfer, salary, benefit etc. I think this is useful data as then I can separate my income for salary, benefits or what my friends have sent me. As it is now I can choose for the type to be for example Salary but then the other sources of income show as withdrawals and it is a bit of a pain to manually edit them for a couple of years worth of data. 

I can also change the Type column to Category but then I have to choose between showing what type of transaction it is or what category it belongs to. Maybe this could be solved with subcategories? English is not my native language so maybe I have missed something or are misusing the types but I think allowing several types of "Type" should be useful.

As an example below if I change the Type to use the word Salary all others will be shown wrong and I have to manually edit them:

![example](https://github.com/moneymanagerex/moneymanagerex/assets/133350236/391d20cf-95fd-4d3e-ba04-88a10e7506bc)

# Use cases

Being able to separate different types of deposits by type if you are importing from CSV. ex. Salary, benefit, transfer from friend etc.

**Comment by n-stein** [comment]
The "Type" field in CSV import is used to distinguish between withdrawals and deposits and is expected to have only two values:  one for credits, the other for debits. This is useful for cases where a CSV file contains only an absolute value in the Amount column and relies on a different field to determine the amount sign. The values of that field are not stored anywhere in MMEX on import, so you can't use it to populate a field on the transaction.

> Being able to separate different types of deposits by type if you are importing from CSV. ex. Salary, benefit, transfer from friend etc.

This is normally the function of Categories. You mention that you have to choose between the "Type" of transaction and the category. Can you provide a bit of detail of how you would categorize these transactions, and how the category differs from the "Type"?

**Comment by CasiN335** [comment]
Ah I see, in my thinking Type was all the different types that I get in my .csv file. So in my .csv file I get Card Transaction, Salary, Benefit, Commercial Paper etc as a type of transaction, But if i make it the column Category it populates the Category with these types in addition to the English ones already existing. And this would be fine but if I change them to fit the English ones I lose the knowledge if it was a bank transfer, card payment, deduction etc. This might be just me thinking it needlessly complex and now that I think about it maybe those would fit in sub-category? As the picture shows that is how my .csv looks like and my thinking was that Type could be used as in the picture. My bank only has a few types and that is how I was imagining Type to work.

Am i thinking this wrong? Can sub-category be used to log the "type" as my bank puts it. I admit to not testing it thoroughly but my logic got stuck on on type not being type but this might more be a language issue.

**Comment by tactilis** [comment]
@CasiN335, you could import your bank's 'Type' column as 'Notes' in MMEX.

FYI, you can use 'Notes' for multiple columns in your CSV; the text in each column gets appended to the transaction's Notes.

So, based on your example data, you could assign the columns as:

Date
Payee
Notes   _(i.e Type in your data)_
Notes   _(i.e. Notes in your data)_
Amount

Does that help?

**Comment by n-stein** [comment]
#4270 would help. I'll try to look at that for 1.6.5.

**Comment by n-stein** [comment]
@CasiN335 Custom field import is included in 1.7.0. Just create a custom text field for your "Type" column and you can add it to the import structure (custom fields are all the way at the bottom in the left panel).

**Comment by CasiN335** [comment]
Great! I will set this one as closed then.
