### ISSUE TITLE
Remove space between too long category and ellipsis `…`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5911]
Follow-up from https://github.com/moneymanagerex/moneymanagerex/issues/5892

@n-stein can the space between the category and the ellipsis please be removed as shown in the image below?

![kép](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b47232a5-0ccd-4d93-bdf5-819096b8e2db)

Thank you

```
Money Manager Ex
• Version: 1.6.4-Beta.6 64-bit
• Built on: May 14 2023 03:26:42
• Database version: 18 (aes128cbc)

Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.19.0-41-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
What is your category name? The trailing ellipsis should only be present if the whole name doesn't fit in the column width.

**Comment by ovari** [comment]
The trailing ellipsis `…` is correct. It is a dummy category that is too long on purpose. Can the space between the `ww` and the `…` be removed? Thank you

**Comment by ovari** [comment]
> The space there is accurately representing the category name you have defined which contains either trailing white space or white space in the middle.

There are no white spaces as shown in the images below.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/71661c42-31d2-47cb-a2d4-5082661d41b4)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/9c283b78-d1d9-4a86-ba69-8b75a9328ddd)

Do the images help?

Thank you

**Comment by n-stein** [comment]
Interesting. This seems to be Linux-specific. There is no space on Windows, the string is extended all the way to the end of the cell before the ellipsis:
![mmex_fAORkPfvCd](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/e5d6f15f-6908-4c54-89b8-5c7271210d7e)

**Comment by ovari** [comment]
Please try one more level deep.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/81901a2e-cda2-4e78-ac14-a8e0dd9256ed)

Thank you

**Comment by ovari** [comment]
Can you try using a lowercase `w`s instead of capital `W`s?

**Comment by ovari** [comment]
Capital `W`s work correctly with GNU/Linux.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ba580882-91fa-43f4-9805-de35be0f7f4a)

Seems to be a bug if lowercase `w`s are used. Is this bug present on Windows when lowercase `w`s are used?

Thank you

**Comment by n-stein** [comment]
> Is this bug present on Windows when lowercase `w`s are used?

Nope, looks the same as uppercase.
