### ISSUE TITLE
use system version of wxsqlite

### ISSUE THREAD

**Issue by crayxt** [moneymanagerex/moneymanagerex#592]
Hi, it would be useful to be able to link mmex to system version of wxsqlite, instead of using own one.
Useful for packagers, I mean.

**Comment by vomikan** [comment]
I am sure that we does not use own one. Submodules are used.

**Comment by crayxt** [comment]
I meant, is there a way to specify in bakefile to use system-wide wxsqlite instead of one from submodule?

**Comment by guanlisheng** [comment]
@crayxt it's doable while we prefer to use the one from submodule since there are many customized features. i will close this ticket and feel free to reopen it.
