### ISSUE TITLE
Crowdin translation widget to add to readme.md

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5925]
Is there a Crowdin widget to show the languages and percentage translated like Weblate has?

For example:

## [Translations](https://github.com/flxzt/rnote/blob/main/README.md#translations)

```
<a href="https://hosted.weblate.org/engage/rnote/">
<img src="https://hosted.weblate.org/widgets/rnote/-/repo/multi-auto.svg" alt="Translation status" />
</a>
```

<a href="https://hosted.weblate.org/engage/rnote/">
<img src="https://hosted.weblate.org/widgets/rnote/-/repo/multi-auto.svg" alt="Translation status" />
</a>

Thank you

**Comment by renato-mmex** [comment]
https://crowdin.com/project/moneymanagerex

**Comment by ovari** [comment]
@renato-mmex does that provide an image like Weblate does for rnote?

**Comment by n-stein** [comment]
One option is @vomikan could install the BDS add-on to the project on Crowdin (https://store.crowdin.com/bds) to generate badges & shields. It will also generate charts such as the one you have shared.

**Comment by vomikan** [comment]
https://badges.awesome-crowdin.com/translation-12682419-342055.png

**Comment by vomikan** [comment]
https://crowdin.com/project/moneymanagerex/tools/app/bds%C2%A6bds
