### ISSUE TITLE
Button not visible in Relocation dialog.

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#5938]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.4 Beta 6
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Button not visible in Relocation dialog.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Korean Language
2. Font size: enlarge, other.
![스크린샷 2023-05-25 125229](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/87e478fb-8199-4dd6-985f-ee4873654cce)

Expected result:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/eedfbd53-03c4-4764-b04c-aff053c76b28)

Actual result:
Category Relocate
![스크린샷 2023-05-25 125156](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/92b95d89-c652-4404-b328-8e5a00e0e524)

Payee Relocate
![스크린샷 2023-05-25 125206](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/7f9de03c-b600-4510-a5f3-e455874b4cf6)

Huge
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/69a8365d-0777-4b2f-8f28-c66f14e61817)

# Additional information
Options dialog
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/1422fd5d-7367-47e9-bcb6-108f818dbff1)
Items on the left panel overlap.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Fixed
