### ISSUE TITLE
DB password change dialog Cancel button

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#5945]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.4 beta 6
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Exception handling problem

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Tool - Database - Change Encrypted Password...
2. click Cancel button
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/e8cedf81-2e6e-4cc4-8077-60218dd9059d)

Expected result:

3. The window should close immediately without further action

Actual result:

3. MessageBox: New password must not be empty.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/661f8f70-123e-4aad-957d-2107076af9d4)

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Confirmed.

Same behaviour when Cancel is clicked regardless of language.

**Comment by n-stein** [comment]
Fixed. Clicking cancel on the initial dialog just closes the dialog. Clicking cancel on the "Confirm password" dialog still displays the message "Confirm password failed". Should we also suppress the message on the second dialog?
