### ISSUE TITLE
Error when try to import a .csv file with a subcategory missing

### ISSUE THREAD

**Issue by kevyndev** [moneymanagerex/moneymanagerex#5947]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ ] 1.6.3
 - [X] Other (1.6.4 Beta 6)
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/c28413c7-5f96-452f-a69c-aebc10a7b202)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Error when try to import a .csv file with a subcategory missing if the same subcategory is following each other

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/6db1d27d-1d9c-4fad-9984-0dd6eed7005d)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Import a .csv file with the same subcategory subsequent each other

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/10a6c686-8d05-46c7-94bd-7c26732a2846)

if this subcategory is not yet created, after the import screen confirmation , this error should pop out

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/6db1d27d-1d9c-4fad-9984-0dd6eed7005d)

Expected result:

Both transactions should apper the subcategory

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/f392ba6f-a0e0-4e8b-bd7e-bdbce560e462)

Actual result:

Only the first transaction will show the subcategory

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/a7af9f1f-2156-48c8-a247-cec94932951d)

# Additional information

Also tested on the last stable version 1.6.3 and no issues at all

**Comment by ovari** [comment]
It is understood that the `subcategory` field no longer exists. Perhaps @n-stein can better explain.

**Comment by n-stein** [comment]
Subcategory _does_ exist in CSV import to preserve legacy (pre-1.6.2) presets that contain the field.

In this case the error is due to a change I made in #5790, so it is indeed a bug. I fixed it for the category field, but missed subcategory.

**Comment by ovari** [comment]
> Subcategory _does_ exist in CSV import to preserve legacy (pre-1.6.2) presets that contain the field.

Should an issue be created to remove subcategory field in CSV import when enough time has passed that legacy support can be removed to remove technical debt?

Thank you
