### ISSUE TITLE
Error opening encrypted DB

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#5948]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.64 beta 6
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

exception handling error
and critical error

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open Encrypted DB   Menu or Toolbar or StartUp Dialog
2. select emb file and Open
3. Please enter password for Database dialog
4. cancel click
5. show startup dialog
6. Open Existing Database click
7. select emb file and open
8. show MoneyManagerEx Error dialog
...
9. close error dialog and goto: 5.
repeat...

Expected result:

Error message should not be displayed as this is not an error situation.

Actual result:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/c3756c10-234e-479e-8eed-cdf5cd033365)
OK or X click
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/ce0e674c-bc24-4417-a6b3-763b75c93ad7)
OK click
terminated MMEX process.

# Additional information

Exception when entering wrong password
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/d9da6f95-395e-4eda-ab1c-24ff13ee27b9)
Folder does not exist at that location.

retry
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/05956c7a-fc7f-4a4c-9c83-af283d9e68e0)
blank dialog and can not exit. Need to force close in task manager.

**Comment by n-stein** [comment]
That fixes the "No Database Opened" error when you cancel opening the db. 

How do you trigger the debug report & blank app start dialog? When I type in a wrong password it just notifies me I typed a wrong password then shows me the (visible) app start dialog -- no exception/crash occurs.
