### ISSUE TITLE
bad locale name

### ISSUE THREAD

**Issue by aramacciotti** [moneymanagerex/moneymanagerex#5949]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [] 1.6.2
 - [ ] 1.6.3 Beta
 - [X] 1.6.3 32bit

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Considering I use a portable installation that I share between multiple PC on a OneDrive folder.
I got a new Windows 32bit laptop and when I open the application I get "bad locale name" whilst on any other PC I'm able to open it successfully.
I think it's a problem on the Windows configuration, but I don't know what I have to check

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Oepn the application and open whatever a database or even create a new one

Expected result:
Database is opened successfully

Actual result:
"bad locale name" messagebox is raised and the screen remains empty

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
https://www.youtube.com/watch?v=F8XJI7UmTu0&ab_channel=Techademics

**Comment by tactilis** [comment]
@aramacciotti, please let us know:

1. Which version of Windows are you running on your laptop?

2. What Windows Language and Region is set (see time 0:18 in the video linked above)?

3. What MMEX settings do you have here:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/61ce8a8c-9fc0-46c3-a683-0f2bc0ed4310)

**Comment by aramacciotti** [comment]
Thanks for the quick answer.

  1.  Which version of Windows are you running on your laptop? Windows 10 Home Edition
  2.  What Windows Language and Region is set (see time 0:18 in the video linked above)? Italiano (Italia)
  3.  What MMEX settings do you have here:
- Language: Italian (Italy)
- Currency: EURO
- Format derived from locale: (empty)
Cordiali saluti.

Andrea Ramacciotti

Da: ***@***.***>
Inviato: martedì 30 maggio 2023 12:52
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] bad locale name (Issue #5949)


@aramacciotti<https://github.com/aramacciotti>, please let us know:

  1.  Which version of Windows are you running on your laptop?
  2.  What Windows Language and Region is set (see time 0:18 in the video linked above)?
  3.  What MMEX settings do you have here:

[image]<https://user-images.githubusercontent.com/4060092/241944360-61ce8a8c-9fc0-46c3-a683-0f2bc0ed4310.png>

**Comment by aramacciotti** [comment]
No news? Anybody can say me which is the registry key or other place in which the "local name" is stored in order to check how that tablet is configured and, if the case, change it manually?

**Comment by aramacciotti** [comment]
> > to check how that tablet is configured...
> 
> By "tablet" do you mean the Windows 32bit laptop that you mentioned in your initial post?
> 
> If so, then you have said how that is configured:
> 
> * Windows 10 Home Edition
> * Windows Language and Region Italiano & Italia

Sure, but which is the "bad locale name" that MMX get and from where?

**Comment by n-stein** [comment]
Possibly related to the default locale MMEX tries to use. We had issues with a bad locale in Windows Norwegian language installations which was recently resolved, perhaps the same affects Italian.

Could you please give the latest beta a try?
https://ci.appveyor.com/project/whalley/moneymanagerex

**Comment by vomikan** [comment]
https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/o1gk5wc9svflf060/artifacts

**Comment by aramacciotti** [comment]
Thank you so much! It worked!

Cordiali saluti.

Andrea Ramacciotti

Da: ***@***.***>
Inviato: sabato 3 giugno 2023 15:24
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] bad locale name (Issue #5949)


Possibly related to the default locale MMEX tries to use. We had issues with a bad locale in Windows Norwegian language installations which was recently resolved, perhaps the same affects Italian.

Could you please give the latest beta a try?
https://ci.appveyor.com/project/whalley/moneymanagerex
