### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by josh-egan** [moneymanagerex/moneymanagerex#596]
Is there a list of keyboard shortcuts anywhere? I've looked through the help file, the website, and this repo and haven't found anything yet. I would love to see a single page that lists all of the keyboard shortcuts available in the various contexts.

**Comment by vomikan** [comment]
Ctrl + 1... 7 to change transaction color
R - Reconcile
U - Unreconcile
D - Duplicate
F - Fllowup

F9 - new transaction
F1 Help pages

Ctrl +N -newDB
Ctrl+O Open DB file

If Atl pressed some letters of buttons and main menu items became underscored. If underscored button pressed the appropriate button will pressed.
