### ISSUE TITLE
What does INFOID: 8 relate to please?

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#5962]
> Are there any other particularly egregious bugs that need to be squashed for 1.6.4?

I have just encountered this when upgrading a 1.6.3 (DB v17) .mmb to DB v18 using 1.6.4 Beta 6.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/cc297213-ffb6-4992-a92f-b09d2a4fc2f6)

It's weird because it only happens sometimes. I'm trying to pin down a repeatable set of steps so you can investigate it.

What does INFOID: 8 relate to please? Knowing that might give me a clue.

_Originally posted by @tactilis in https://github.com/moneymanagerex/moneymanagerex/discussions/5777#discussioncomment-6059645_

**Comment by tactilis** [comment]
@vomikan, I didn't see that you copied my and Nick's comments from the 1.6.4 discussion to this issue before I raised https://github.com/moneymanagerex/moneymanagerex/issues/5964

Could you close this issue please since #5964 describes in more detail what is occurring. Thanks

**Comment by ovari** [comment]
Is it possible to open one file using multiple instances of the program? Perhaps the database file could be stored on a network drive and multiple people could open the file on their computer? Thank you

**Comment by tactilis** [comment]
> Is it possible to open one file using multiple instances of the program? Perhaps the database file could be stored on a network drive and multiple people could open the file _**[simultaneously]**_ on their computer?

You can do it, if you choose to ignore this warning:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/f5d8ab58-f351-4107-8f84-b061ca3ebbb7)

You will at some point encounter data loss or apparent corruption of values entered/modified by the users.

MMEX is a _**personal**_ finance management application and, as such, it is intended to be used by one person - or a few people in a family, for example, who can coordinate their times of access to the database so that they don't conflict.

MMEX is not designed to handle concurrent database updates in multi-user environment. It would be a massive task to make it so.

Some background:
https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/transactions-and-concurrency
https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/optimistic-concurrency

(They are ADO.NET articles but the same principles apply)

**Comment by ovari** [comment]
Thank you @tactilis for your reply.

It was thought that it might be easier to do as technology has improved and there are other free accounting software like [Manager](https://www.manager.io/) that can do concurrent database access. Manager is feature-rich and cross-platform; however, Manager is not suitable as it is not single-entry (i.e. it is double-entry) accounting and not open-source (however it is free). It was thought that it might be a possibility with Money Manager Ex (MMEX) as Manger seems to be developed by one-person in Sydney Australia.

Maybe in the future the foundation will enable concurrent users - or the same user accessing the file on multiple devices (Windows, macOS and Android) to use MMEX.

Thank you once again for your reply.

**Comment by tactilis** [comment]
> as Manger seems to be developed by one-person in Sydney Australia.

Being based in Sydney Australia makes _all_ the difference 😉

**Comment by tactilis** [comment]
@ovari
> ...Manager is feature-rich and cross-platform; however, Manager is not suitable as it is not single-entry (i.e. it is double-entry) accounting

And, more relevant in any comparison with MMEX, Manager is heavily oriented towards business use. See https://www.manager.io/guides/. Its intended user base and design goals are different to MMEX's.

> ...there are other free accounting software like [Manager](https://www.manager.io/) that can do concurrent database access.

That's not a correct statement. The free desktop version of Manager with local data files (like MMEX) does not provide multi-user access. See https://www.manager.io/compare/

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/cdcb501b-0757-44c6-bf7b-e293bd9fdebd)

The cloud version _is_ multi-user. See https://www.manager.io/cloud/. But it is very much _not_ free. See https://www.manager.io/cloud/pricing

**Comment by vomikan** [comment]
Can this case be closed or does it need to be finalized?

**Comment by n-stein** [comment]
Close it, the issue was addressed in #5964
