### ISSUE TITLE
Online update in Currency Dialog doesn't work

### ISSUE THREAD

**Issue by Jerry23011** [moneymanagerex/moneymanagerex#5963]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [x] macOS 13
 - [ ] Linux 

# Description of the bug

When I click `online update` in the Currency Dialog, the popup says "Error Nothing to update"
I can update each currency individually by selecting them and clicking the update button on below the currency history view.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Open the Currency Dialog
2. Click `Online update`
Expected result:
The currency will update
Actual result:
The popup says there's an error
# Additional information
<img width="699" alt="截屏2023-06-01 21 13 27" src="https://github.com/moneymanagerex/moneymanagerex/assets/89069957/b1a8ddf8-8fc8-45d3-a7c2-09aec57cb00c">

**Comment by n-stein** [comment]
Same issue as #5894. Fetching rates for all currencies uses the Yahoo Finance v7 API which no longer functions in any released version of MMEX while history download uses the v8 API which still works.

This has already been fixed for 1.6.4.

**Comment by Jerry23011** [comment]
Thank you, @n-stein

**Comment by Jerry23011** [comment]
> This has already been fixed for 1.6.4.

Hi, I downloaded the release build of 1.6.4, yet it's still not working?

**Comment by n-stein** [comment]
For those outside the US there were additional fixes required which were corrected after the official 1.6.4 release. Try the 1.6.5 beta from June 26th here: https://link.ipx.co.uk/mmex-mac-betas

**Comment by n-stein** [comment]
I'm not able to reproduce this issue on Windows. @whalley any suggestions?

**Comment by Heny67** [comment]
> For those outside the US there were additional fixes required which were corrected after the official 1.6.4 release. Try the 1.6.5 beta from June 26th here: https://link.ipx.co.uk/mmex-mac-betas

Hi n-stein!

Is there such an improved beta for linux?  Because it doesn't throw an error on 1.6.4, but the exchange rate doesn't update, it doesn't download the real exchange rate.

**Comment by n-stein** [comment]
Linux build here:

https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/818/workflows/1d689e08-c125-46ff-86cc-10b014d1bb80/jobs/814/artifacts

Since it is a beta, as a precaution please take a backup copy of your database before testing it out.

**Comment by Heny67** [comment]
Hi n-stein!
Thank you!

**Comment by whalley** [comment]
> I'm not able to reproduce this issue on Windows. @whalley any suggestions?

I can't reproduce either on MacOS.

**Comment by Jerry23011** [comment]
It's working now, what I did is to manually update CAD and USD first, so that the dates of their currency history match each other. Then clicking on the online update will update their exchange rates.

Thanks @n-stein and @whalley
