### ISSUE TITLE
Constraint error on upgrade from DB 17 to DB 18 when another database is already open

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5964]
MMEX version:
 - [x] 1.6.4 Beta 6

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

This error is produced on upgrade of my _Master.mmb_ database from DB 17 to DB 18 when first opening it with 1.6.4 Beta 6 _if_ another DB 18 database is already open in MMEX.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/3e41b7fe-e417-4e5e-aad0-28732429a3ab)

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction:

Setup:
- Have a copy my DB 17 _Master.mmb_ available. Note that I am happy to send this .mmb via email but not to post it to github.
- Open  _Master.mmb_ with 1.6.3 then Exit MMEX to ensure that the DB is not marked as in-use.

- Using 1.6.4 create a new DB 18 database. Call it _New.mmb_. Exit MMEX to ensure that the DB is not marked as in-use.

Steps:
1. Via the Application Start dialog `Open Existing Database` _New.mmb_
2. Via `File | Open Database` open _Master.mmb_
3. The message 'MMEX database successfully upgraded to version 18' is displayed. Click OK
4. The above constraint error is then displayed.

Notes:
1. If the DB 17 _Master.mmb_ is opened in 1.6.4 via the Application Start dialog (i.e without _New.mmb_ being open), then _Master.mmb_ is updated to DB 18 and the constraint error does **not** occur. 
2. If the above steps 1 and 2 are repeated with _Master.mmb_ already upgraded to DB 18, then the constraint error does **not** occur.
3. If I try the above steps 1 and 2 using a DB 17 database different from my _Master.mmb_, then the  constraint error does **not** occur.

**Comment by n-stein** [comment]
I am unable to replicate using any of my v17 databases. Send me your mmb and I'll debug.

**Comment by n-stein** [comment]
Found it. The problem is when a database is closed the Model caches aren't cleared. During upgrade the system closes your Master.mmb in order to open it in debug mode, and during this time it attempts to set ISUSED = FALSE. Your Master.mmb has ISUSED with INFOID = 7 so it tries to set the record (7, ISUSED, FALSE), but the left over cache from New.mmb has ISUSED with INFOID = 8 so it thinks you are duplicating the ISUSED name.

We just need to clear the caches on database shutdown.

**Comment by tactilis** [comment]
> Found it. The problem is when a database is closed the Model caches aren't cleared.

Great. Thanks.

That's one fewer 1.6.4 upgrade error report from people who have multiple databases to upgrade.

**Comment by n-stein** [comment]
Fixed

**Comment by tactilis** [comment]
Tested. All good.
