### ISSUE TITLE
Crash when deleting or restoring transactions using context menu

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5966]
MMEX version:
 - [x] 1.6.4 Beta 6

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX crashes if you try to delete or restore one or more transactions using the right-click context menu.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

Setup:
1. Create a new database
2. Create a Checking account.
3. Create a transaction in the account.

Steps:
1. Select the transaction
2. Right-click | Delete | `Delete selected transaction`
3. Confirm the deletion. MMEX crashes

4. Restart MMEX. Note that the transaction was actually deleted and is now in Deleted Transactions
5. Select the deleted transaction
6. Right-click | `Restore selected transaction`
7. Confirm the restoration. MMEX crashes
8. Restart MMEX. Note that the transaction was actually restored

Notes:

MMEX crashes in the same manner if you use the context menus `Delete all transactions in current view` or `Restore all transactions in current view`

MMEX does not crash if you delete using the `Delete` button or press the Delete key.
MMEX does not crash if you restore using the `Restore` button.

**Comment by n-stein** [comment]
Fixed

**Comment by ovari** [comment]
https://github.com/n-stein/moneymanagerex/commit/606343381ff98a914136787f2ad6d6fdd6a312fb#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4R918

Should `home_page` be replaced with `dashboard` to reduce technical debt?

Thank you

**Comment by n-stein** [comment]
> Should home_page be replaced with dashboard to reduce technical debt?

Changing the text of the root nav tree node was purely a visual change. The term "home page" is used many times in variable names such as this throughout the code base. I'm not sure this would really reduce technical debt.

**Comment by tactilis** [comment]
> Good catch. Fixed.

Tested. All good.
