### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by howff** [moneymanagerex/moneymanagerex#597]
Hi
There have been no ubuntu packages for over a year now so I'm trying to build mmex on ubuntu-14.04-x64 but it fails here:

moneymanagerex/release/bk-deps g++ -c -o mmex_general_report_manager.o -I../lib/wxsqlite3/sqlite3/secure/src -I../lib/wxsqlite3/include -I../lib/lua/src -I../lib -I../3rd -I../3rd/LuaGlue/include -I../3rd/cgitemplate -I../3rd/csv-parser/include -I../src -DNOPCH -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -fPIC -DPIC  -g -O2 -std=c++11 -g0 -O2 ../src/general_report_manager.cpp

In file included from ../src/general_report_manager.cpp:20:0:
../src/general_report_manager.h:102:5: error: ‘wxWebView’ does not name a type

(following the instructions here:
https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.TXT
I got an error from configure with the suggested libwxgtk2.8-0 and libwxgtk2.8-dev (too old) but configure worked ok after installing libwxgtk3.0-0 and libwxgtk3.0-dev)

**Comment by vomikan** [comment]
Please discuss any Linux issues here
http://forum.moneymanagerex.org/viewforum.php?f=25

2015-11-18 18:45 GMT+06:00 howff <notifications@github.com>:

**Comment by vomikan** [comment]
I hope this help http://forum.moneymanagerex.org/viewtopic.php?f=25&t=6143

2015-11-19 14:42 GMT+06:00 Nikolay Akimov <nikolay.akimov@gmail.com>:

**Comment by dwrj87** [comment]
I shall take another look at the instructions and scripts for building on Linux

**Comment by howff** [comment]
Updating the build instructions is very much appreciated.
However they seem to be targeted at ubuntu 15.10 which has only been available for a few weeks so basically nobody is using it at the moment. It would be much appreciated by the wider linux user base if you could target your build instructions at the oldest version which is still on Long Term Support, i.e. 12.04. That way your efforts will be usable by a very much wider user base. And binaries created on older versions should run on newer versions (which is not true the other way around). Thank you.
(More specifically I can't even get past the requirement for libwxgtk-webview3.0-dev as it doesn't exist even in 14.04 (the most recent LTS release)).

**Comment by vomikan** [comment]
@howff  Are you sure that LTS is 14.04 not 15.04?

**Comment by howff** [comment]
Yes, see https://wiki.ubuntu.com/LTS

**Comment by dwrj87** [comment]
As it says, further versions to follow. The reason for it only being 15.10 at the moment is because that's the version I'm using

I've got to create a virtual machine with each version to be able to work it out, test it and write it down

**Comment by dwrj87** [comment]
Instructions for 14.04 & 15.04 added to the pull request

**Comment by dwrj87** [comment]
https://launchpad.net/~dwrj87/+archive/ubuntu/mmex-test

**Comment by vomikan** [comment]
Some user from http://forum.ubuntu.ru/index.php?topic=143753.270 reported this issues:
~~~~
An assertion failed!
../src/common/file.cpp(328): assert "(pBuf != __null) && IsOpened()" failed in Read().
~~~~

~~~~
mmex Error
can't open file '/usr/share/doc/mmex/contrib.txt' (error 2: No such file or directory)
~~~~

**Comment by dwrj87** [comment]
Hmmm, I've updated the PPA to put them in to the right place, but it's gzipping the files. Am doing some Googling and asking some questions to try and get it sorted

**Comment by dwrj87** [comment]
Fixed

**Comment by vomikan** [comment]
Thanks

**Comment by MartinX3** [comment]
I got this error, after updating from 1.2.4-trusty1 -> 1.2.5, too.

An assertion failed!
../src/common/file.cpp(328): assert "(pBuf != __null) && IsOpened()" failed in Read().

mmex Error
can't open file '/usr/share/doc/mmex/contrib.txt' (error 2: No such file or directory)

Using Linux Mint 17.3 x64 Mate-Edition.
I will unzip the .gz files in this directory, but that error should be fixed.
(And the PPA should be updated to 1.2.6)

**Comment by dwrj87** [comment]
Yes, I'm having a bit of trouble with the PPA. I will be fixing the bugs (again) and updating to 1.2.6 this week

**Comment by dwrj87** [comment]
PPA has been updated to 1.2.6 and the "can't open file '/usr/share/doc/mmex/contrib.txt' (error 2: No such file or directory)" error should be gone

**Comment by MartinX3** [comment]
Thank you, it worked! :)
