### ISSUE TITLE
Transfer arrow points the wrong way on Share Withdrawal transactions

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5975]
MMEX version:
 - [x] 1.6.3
 - [x] 1.6.4 Beta

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The transfer arrow on share transactions always points the same direction. It should follow the same format as normal account-to-account transactions where the arrow points towards the target.

On normal transaction the arrow points towards the target (`>` for withdrawals and `<` for deposits). On share transactions the arrow is always `<`. It should be reversed for withdrawals since the share account is the source on these transactions.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/72819bc5-340a-4f03-84e7-9b40bda3e7d5)

**Comment by n-stein** [comment]
Semi-related: I don't really understand why the status has a `<` as well. What is this signifying?

**Comment by ovari** [comment]
Should arrows be used (`→`, `←`)  be used instead of greater than and less than (`>`, `<`)? Thank you

**Comment by tactilis** [comment]
> Should arrows be used (→, ←) be used instead of greater than and less than (>, <)

Those arrow characters are really hard to distinguish compared to the existing symbols (see below).

IMO, the existing characters are visually simple and their meaning is unambiguous in the context in which they are used.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/69714afd-bcb9-47df-9520-6529b2e20c31)

**Comment by ovari** [comment]
Would solid pointers (`►`,`◄`) be easier to distinguish than the current characters? It also doesn't have confusion with inequalities (`>`,`<`).

**Comment by tactilis** [comment]
> Would solid pointers (►,◄) be easier to distinguish than the current characters? 

The solid pointer characters don't render well in MMEX and are not as easily distinguished as the existing characters:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/b91a889f-3a8f-4acb-832b-a46a4cc19502)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/efeb40f6-95d8-4bfb-a4b1-ced5f260e5e6)

> It also doesn't have confusion with inequalities (>,<).

I don't believe that there's a problem that needs solving here. I cannot imagine that anyone considers use of < > in the Payee field to mean less-than or greater-than.

**Comment by n-stein** [comment]
Just a small fix for the withdrawal arrow direction to indicate the transfer is outbound:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/81c39976-c3c1-4351-99d5-be7cf06a45a6)
