### ISSUE TITLE
Homepage account balances wrong for some currencies

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5988]
On MacOS I seem to have lost account balances for some currencies.

Was working here:
![CleanShot 2023-06-05 at 19 58 29](https://github.com/moneymanagerex/moneymanagerex/assets/487345/922a0e44-35c8-453c-b1a2-5649762875b5)
![CleanShot 2023-06-05 at 19 56 09](https://github.com/moneymanagerex/moneymanagerex/assets/487345/b8edad63-0996-46d4-a0f9-ff049593f80b)

Now broken:
![CleanShot 2023-06-05 at 19 59 03](https://github.com/moneymanagerex/moneymanagerex/assets/487345/c8434448-458d-4849-8f72-b2eaf62b8f25)
![CleanShot 2023-06-05 at 20 00 29](https://github.com/moneymanagerex/moneymanagerex/assets/487345/965f5293-f7e3-4339-b5bb-7124bae89f32)

**Comment by n-stein** [comment]
Interesting that the Total is the same in both cases. So in the first screenshot it is displayed, but not included in the total?

**Comment by whalley** [comment]
Yep, I'll have a look at the generated HTML to see if that gives any clues.

**Comment by n-stein** [comment]
Hmm. Both are built on your master branch, but these commits are sequential on that branch. The only difference is contrib.txt unless I'm missing something.

**Comment by whalley** [comment]
An odd one.... Reverted to re-building wxWidgets with the latest Xcode tools, then re-building MMEX, and signing... which solved the issue. 

Closing.

**Comment by whalley** [comment]
Issue has recurred..

**Comment by whalley** [comment]
Not sure what is happening here... but one other thing I've just noticed (which may not be related) is that when creating a new DB some currencies are missing, e.g, 2-EUR, 4-RUB, 5-UAH, 6-AFN, 8-DZD, 13-AWG, and others....

WHen running the application from the coammnd line it works fine, but when run from the desktop finder app then the issue occurs.

Seems fine on Windows. 

MAC USERS: Can you test the latest beta to see if you have the same issue?

**Comment by whalley** [comment]
A really odd one. I've rebuilt my tools and rebuilt wxWidgets and MMEX from scratch....

- It works fine on wx3.2.1
- I get the bug on wx3.2.2.1 

So reverting the MacOS builds back the wx3.2.1 for now until I can do a bit more investigating and checking with the wxWidgets team.

https://github.com/moneymanagerex/moneymanagerex/issues/5989

**Comment by whalley** [comment]
Think this may be the issue, but will need to check if this fixes it when I have a bit more time.
https://github.com/wxWidgets/wxWidgets/issues/23450

**Comment by n-stein** [comment]
I wonder if this fix for #5852 caused your issue to surface: 0eb31b93858fdc6204c9de2210f2c1ccc4fb7e15

**Comment by whalley** [comment]
> I wonder if this fix for #5852 caused your issue to surface: [0eb31b9](https://github.com/moneymanagerex/moneymanagerex/commit/0eb31b93858fdc6204c9de2210f2c1ccc4fb7e15)

Ooooo, maybe.

**Comment by n-stein** [comment]
> It works fine on wx3.2.1\nI get the bug on wx3.2.2.1

Is this still the case? Can we release 1.6.4 using 3.2.1, or do we need some other workaround?

**Comment by whalley** [comment]
> Is this still the case? Can we release 1.6.4 using 3.2.1, or do we need some other workaround?

Yes, all good with wx3.2.1 :-)

**Comment by vomikan** [comment]
Has this bug been fixed?

**Comment by n-stein** [comment]
Not fixed, but is not necessary to fix for 1.6.4. 

I think we should mark this one as on hold until wxWidgets 3.2.3 is released and we update the MMEX build to use it.
