### ISSUE TITLE
Build with wxWidgets 3.2.3

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5989]
# Description of the feature

Consider testing and adopting wxWidgets 3.2.3- https://www.wxwidgets.org/news/2023/10/wxwidgets-3.2.3-released/
~~Consider testing and adopting wxWidgets 3.2.2.1 - https://www.wxwidgets.org/news/2023/02/wxwidgets-3.2.2.1-released/~~

**Comment by n-stein** [comment]
Good idea. I've been using it on my dev builds for the past two months and haven't encountered any issues so far.

**Comment by joshua-stone** [comment]
Bumping wxWidgets to the latest stable version (3.2.2.1 as of today) seems like a good idea. The MMEX flatpak has been using that version and there haven't yet been any regressions reported:

https://github.com/flathub/org.moneymanagerex.MMEX/blob/729d93eb458732f9c8fa7ca40cb373fa49695554/org.moneymanagerex.MMEX.yml#L48

**Comment by whalley** [comment]
MacOS builds updated to v3.2.2.1 with no ill effect.

**Comment by n-stein** [comment]
We should keep all builds using 3.2.1 for the 1.6.4 release and target this for 1.6.5.

**Comment by whalley** [comment]
wxWidgest 3.2.3 released: Consider testing and adopting wxWidgets 3.2.2.1

**Comment by whalley** [comment]
wx3.2.3 looks good on MacOS and fixes, will include in MacOS betas so others can test.

- https://github.com/moneymanagerex/moneymanagerex/issues/5988
- https://github.com/moneymanagerex/moneymanagerex/issues/5330

**Comment by joshua-stone** [comment]
I can confirm that wxWidgets v3.2.x builds with MMEX. It also drastically reduces the build times ([1 hour to 15 minutes](https://buildbot.flathub.org/#/apps/org.moneymanagerex.MMEX)) as there are fewer modules to build:

https://github.com/flathub/org.moneymanagerex.MMEX/commit/968ab8d6746cbf9baae0945454d54b7463b105de

**Comment by whalley** [comment]
Are we happy have Flathub as the sole distribution mechanism for MMEX on Linux, and remove the other Linux builds we make via CircleCI. I'm concious that the CircleCI builds are still on wx3.1.7 and are falling behind Linux OS release versions with no active maintenance.

Views? My vote is to go with Flathub and drop the other builds.

**Comment by joshua-stone** [comment]
That's an interesting proposal.

I've done some digging to find the download counts of the last couple releases:

**v1.6.4:**

```
$ curl -s https://api.github.com/repos/moneymanagerex/moneymanagerex/releases | jq '.[0].assets[] | select(.browser_download_url | endswith(".deb") or endswith(".rpm")) | (.browser_download_url, .download_count)'
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.4/mmex-1.6.4-Fedora.36.ThirtySix.fc36.x86_64.rpm"
253
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.4/mmex-1.6.4-openSUSE.Tumbleweed.x86_64.rpm"
119
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.4/mmex_1.6.4-Ubuntu.18.04.bionic_amd64.deb"
206
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.4/mmex_1.6.4-Ubuntu.20.04.focal_amd64.deb"
382
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.4/mmex_1.6.4-Ubuntu.22.04.jammy_amd64.deb"
1211
$ curl -s https://api.github.com/repos/moneymanagerex/moneymanagerex/releases | jq '[.[0].assets[] | select(.browser_download_url | endswith(".deb") or endswith(".rpm")) | .download_count] | add'
2171
```

**v1.6.3:**

```
$ curl -s https://api.github.com/repos/moneymanagerex/moneymanagerex/releases | jq '.[1].assets[] | select(.browser_download_url | endswith(".deb") or endswith(".rpm")) | (.browser_download_url, .download_count)'
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex-1.6.3-Fedora.36.ThirtySix.fc36.x86_64.rpm"
350
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex-1.6.3-openSUSE.Tumbleweed.x86_64.rpm"
161
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex_1.6.3-Ubuntu.18.04.bionic_amd64.deb"
325
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex_1.6.3-Ubuntu.20.04.focal_amd64.deb"
609
"https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.6.3/mmex_1.6.3-Ubuntu.22.04.jammy_amd64.deb"
1760
$ curl -s https://api.github.com/repos/moneymanagerex/moneymanagerex/releases | jq -r '[.[1].assets[] | select(.browser_download_url | endswith(".deb") or endswith(".rpm")) | .download_count] | add'
3205
```

That's 5,376 downloads for MMEX's Linux builds from Github since Feb 1, compared to [4,472 downloads from Flathub](https://flathub.org/apps/org.moneymanagerex.MMEX)  since it was submitted to the store on [May 31](https://github.com/flathub/flathub/pull/4184).

It doesn't look like major distros like Ubuntu or Fedora package MMEX either, so most of the Linux downloads would have to be coming from either Github or from Flathub.

I'm in favor of streamlining the CI if it simplifies Linux support, however I recommend having a flatpak build target in place of the RPM/deb build targets to ensure regressions don't occur. The CI could produce flatpak build artifacts for testing:

https://github.com/MarvellousSoft/MarvInc/blob/27845edbfb421761112a01a697016c62a39f89dc/deploy.sh#L246

**Comment by whalley** [comment]
@joshua-stone FYI, I get the release stats from here: https://tooomm.github.io/github-release-stats/?username=moneymanagerex&repository=moneymanagerex which basically does the queries you did.

Do you want to submit a change to the CircleCI build script?
https://github.com/moneymanagerex/moneymanagerex/blob/master/.circleci/config.yml

**Comment by joshua-stone** [comment]
I have a draft PR, although I'm not sure how to test it:

https://github.com/moneymanagerex/moneymanagerex/pull/6239

**Comment by whalley** [comment]
See how this goes: https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/991/workflows/45c5a232-9864-4a41-8d4e-459176524184/jobs/988

**Comment by joshua-stone** [comment]
```
bwrap: Creating new namespace failed: Operation not permitted
Error: module wxWidgets: Child process exited with code 1
```

@whalley You might have to enable additional permissions/resources to make the CI complete:

https://github.com/obsproject/obs-studio/blob/3869cb83bc91ae96a93589139215e2f9e813d1e7/.github/workflows/build-project.yaml#L244

I'm not sure how to do this with CircleCI.

BTW, please don't merge drafts until they're deemed ready. We should make sure that whatever changes are being added doesn't introduce bugs and/or build failures.

**Comment by whalley** [comment]
> I'm not sure how to do this with CircleCI.

Neither am I, what permissions/resources are needed?

> BTW, please don't merge drafts until they're deemed ready. We should make sure that whatever changes are being added doesn't introduce bugs and/or build failures.

It seemed the easiest way to deal with your request "I have a draft PR, although I'm not sure how to test it"

**Comment by whalley** [comment]
Related to this? https://stackoverflow.com/questions/70520206/bwrap-creating-new-namespace-failed-operation-not-permitted-on-install-gimp-wi

**Comment by joshua-stone** [comment]
@whalley That might be it, which is what a "privileged" container is for. Not sure how CircleCI how does this, if it's even supported:

https://support.circleci.com/hc/en-us/articles/13352281909787-How-to-run-Container-Runner-in-Privileged-Mode

Usually in cases like this you either A) have the CI set up to test building the code to make sure it compiles and can generate a build artifact, or B) manually trigger a build job.


If CircleCI cannot fulfill these requirements, is it possible to try implementing build jobs with Github Actions instead?

**Comment by PMaff** [comment]
Which version of wxWidget shall I use for compiles? 3.2.3? 3.2.1?
Currently most of my compiles still use wxWidget 3.2.0 .

**Comment by whalley** [comment]
3.2.3 is now used in Win/MacOS/Linux-Flatpak builds.
