### ISSUE TITLE
Unable to capitalize category

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#599]
Attempting to change the capitalization of a category from 'tax' to 'Tax' is not possible as it says the category already exists.

**Comment by vomikan** [comment]
Try to change it to 'Tax+' then to 'Tax'.

2015-11-21 6:44 GMT+03:00 Dialga <notifications@github.com>:

**Comment by vomikan** [comment]
Minor bug, I don't want  fix.
