### ISSUE TITLE
MMEX flatpak is not listed on website

### ISSUE THREAD

**Issue by joshua-stone** [moneymanagerex/moneymanagerex#5997]
Since MMEX is now a [verified app on flathub](https://flathub.org/apps/org.moneymanagerex.MMEX), I think it would make sense to add it to the [MMEX downloads page](https://moneymanagerex.org/docs/downloads/latest/).

**Comment by whalley** [comment]
Done...

![CleanShot 2023-06-13 at 23 21 12](https://github.com/moneymanagerex/moneymanagerex/assets/487345/54092fc3-cbc9-45a8-837a-2eb24d32d300)

**Comment by joshua-stone** [comment]
Thank you!
