### ISSUE TITLE
Opt-in for sending usage statistics

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5998]
Currently, by default, usage statistics are sent to MMEX using Google Analytics.

Can this behavior please be changed so that usage statistics are **not** sent by default?

Users may not be aware this setting as it is easily overlooked:
1. as information in the `Privacy` tab (last tab)
![Privacy tab](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/02672a4a-f2a1-4154-b6e8-3939b8d27c41)
2. as the `Network` tab might be overlooked by users who think that relates to the non-Desktop, WebApp and MMEX for Android features
![Usage statistics](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ba1cf735-d719-44b3-ab79-ad56cb4dd8de)

MMEX is different from proprietary big-tech which centralizes the Internet. [Is Advanced AI A Reason To Decouple From The Centralized Internet?](https://puri.sm/posts/is-advanced-ai-a-reason-to-decouple-from-the-centralized-internet/). MMEX provides an offline solution that can help with [The Silicon Valley Matrix- How To Break Free From Internet Centralization!](https://puri.sm/posts/the-silicon-valley-matrix-how-to-break-free-from-internet-centralization/)

What do you think?

Thank you

**Comment by tactilis** [comment]
@ovari
> Currently, by default, usage statistics are sent to MMEX using Google Analytics.
> Can this behavior please be changed so that usage statistics are not sent by default?
> Users may not be aware this setting as it is easily overlooked: as information in the Privacy tab (last tab)

You are overlooking the fact that the **_very first_** dialog that is presented to the user when they first run MMEX (installer or portable version) is the Licence Agreement:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/94799653-6188-48d3-aafd-8d75d890a4fb)

The statement about what anonymous statistics are collected and how to later change the setting are very clear from the start.

To proceed, further, the user must click the OK button, above which is a very clear statement that the user can either accept or decline to allow the sending of anonymous statistics.

> What do you think?

T think we should leave it as it is.

MMEX's optional sending of anonymous statistics is a far cry from what is described in the 'shock' articles you link to, which IMO are clickbait adverts for Purism.
