### ISSUE TITLE
Error "invalid map<K, T> key" since v 1.2.3

### ISSUE THREAD

**Issue by bernique** [moneymanagerex/moneymanagerex#601]
Trying to import QIF files, I get the fatal error "invalid map<K, T> key" since I am on v 1.2.3. Going back to v 1.2.2 solves the problem.
Thanks for your support.
Loïc

**Comment by vomikan** [comment]
Hi,

It was minor changes since 1.2.2
https://github.com/moneymanagerex/moneymanagerex/commit/20ebb209db39cd850a99b283e4e621e480a3a99d

Could you provide QIF file for I can reproduce the problem?

**Comment by bernique** [comment]
Hi,
It is not that easy, because the files I have are full of my personal 
bank data. I can try to download other files with minor information, 
just 1-2 days, but I need to reinstall v 1.2.3 for testing. I don't 
really want on this computer, so I will try on another computer at home. 
I will keep you informed, I hope for tomorrow evening.
Thank you for your help.
Loïc

**Comment by bernique** [comment]
Finally, I have one qif file from an almost sleeping account. I got the 
same error with it, but I could import it with v 1.2.2. Dates are in 
French format dd/mm/yy.
Thanks again.
Lo{ic

Le 30/11/2015 08:13, Nikolay a écrit :
>
> Hi,
>
> It was minor changes since 1.2.2
> 20ebb20 
> <https://github.com/moneymanagerex/moneymanagerex/commit/20ebb209db39cd850a99b283e4e621e480a3a99d>
>
> Could you provide QIF file for I can reproduce the problem?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/moneymanagerex/moneymanagerex/issues/601#issuecomment-160542195>.
>


!Type:Bank
D11/10/15
T-19.61
NVirement
PPRLV SEPA EDF clients particul  
^
