### ISSUE TITLE
circleci

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6022]
Who is the owner of this farm? I don't have access there. Start building the project.

https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex?branch=master

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/ea8dec9e-a64c-4b20-af9f-3134fec9f82e)

**Comment by n-stein** [comment]
It will build automatically if @whalley merges #6021

**Comment by vomikan** [comment]
It seems frobiden personnaly for my account

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/d49c7158-9fa4-4ed0-84cb-a3257de7e753)

**Comment by whalley** [comment]
> It will build automatically if @whalley merges #6021. It won't build if you merge it due to [this](https://support.circleci.com/hc/en-us/articles/360043679453-CircleCI-Terms-of-Service-Violation-Sanctioned-Country) restriction CircleCI has put in place.

Yep, that's why I have it building nightly as well as on merge.

**Comment by ovari** [comment]
@whalley can you create a new build so testing of https://github.com/moneymanagerex/moneymanagerex/pull/6021#issuecomment-1595344424 can be done? Thank you
