### ISSUE TITLE
Crash in theme manager

### ISSUE THREAD

**Issue by kevyndev** [moneymanagerex/moneymanagerex#6036]
MMEX version:
 - [x] 1.6.3
 - [x] 1.6.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Crash after click on "Theme Manager" if a database is not open yet

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. After open MMEX, click on "New Database" or "Open Existing Database"
2. Click Cancel
3. Go to Tools > Theme Manager

Expected result:

Open the Theme Manager windows

Actual result:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/28196582/851d0fab-b9d4-4c7b-b059-0d9423b42edf)

# Additional information

Also happens with "Download Rates" and "Report a bug"

[MoneyManagerEx_dbgrpt-2964-20230621T100147.zip](https://github.com/moneymanagerex/moneymanagerex/files/11818658/MoneyManagerEx_dbgrpt-2964-20230621T100147.zip)

**Comment by tactilis** [comment]
Crash confirmed if you click `Tools | Theme Manager` when there is no database open.

Similarly, MMEX crashes if you click `Tools | Download Rates` or on the `Download Rates` icon in the toolbar when there is no database open.

As with most other MMEX functions, both of these should be inhibited when no database is open.

**Comment by n-stein** [comment]
fixed
