### ISSUE TITLE
Exchange rate update

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#6038]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [ x ] 1.6.4 
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

When you click the Update currency rates online button, the pop-up window says "invalid value" for the euro exchange rate.
And indeed the exchange rate is not good.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

Money Manager Ex
• Verzió: 1.6.4 64 bites
• Készítési időpont: jún. 20 2023, 19:34:35
• Adatbázis verziója: 18 (aes128cbc)
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Fut a következőn:
• Ubuntu.22.04.jammy
• Ubuntu 22.04.2 LTS "jammy"
• Linux 5.19.0-45-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi

If you have a backtrace for a crash or a warning, paste it here.
![Névtelen](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/b90b7de9-57ef-4fed-9013-5fda9f7efb91)

**Comment by n-stein** [comment]
Unable to reproduce

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/b70c8b0a-fc16-4bc3-97c9-364d6039c014)

**Comment by whalley** [comment]
The same happens to me:

![CleanShot 2023-06-22 at 23 05 01](https://github.com/moneymanagerex/moneymanagerex/assets/487345/5fb36c4a-01a1-4fe4-a750-c482174d5e87)

**Comment by n-stein** [comment]
I suspect this is caused by the same issue as #6040
