### ISSUE TITLE
Panel refresh after OnAutoRepeatTransactionsTimer

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#604]
refreshPanelData() should be done if wx_Cancel pressed on auto repeate dialog.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/39c8878e39a72d6b4805230063219ab542f6a5ed

**Comment by slodki** [comment]
@vomikan could you describe how to reproduce this bug?

**Comment by vomikan** [comment]
- set some auto recurring transaction with start today.
- start mmex and wait 1 min for auto trigger started.
- press Cancel button to avoid posting.
- look at Navigation panel.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2403

**Comment by gabriele-v** [comment]
Looks good
