### ISSUE TITLE
Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url"

### ISSUE THREAD

**Issue by therealstretch** [moneymanagerex/moneymanagerex#6040]
MMEX version:
 - [x] 1.6.4

Operating System:
 - [x] Windows 11

# Description of the bug

When I click "Refresh Stock Prices from Yahoo"  in Stock Portfolio view
I get the error "url using bad/illegal format or missing url"

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
click "Refresh Stock Prices from Yahoo" in Stock Portfolio view

Expected result:
Stock prices are updated

Actual result:
above Error, no stock price updated

![yahoo](https://github.com/moneymanagerex/moneymanagerex/assets/131329434/37d6216e-2ad1-48c5-9ac2-075d69f82a1a)

**Comment by Heny67** [comment]
> I am unable to reproduce this issue. Can you please share the stock symbols that you are trying to refresh?

Hi n-stein!

It works the same way for me.
Ubuntu mate 22.04 + https://github.com/moneymanagerex/moneymanagerex/issues/6038

![Névtelen1](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/57e881db-2886-457d-9523-4996770a01e0)

**Comment by n-stein** [comment]
@Heny67 need more information as everything is working for me.

Can you provide:
* What symbols you are refreshing
* The YAHOO_FINANCE_COOKIE & YAHOO_FINANCE_CRUMB values from your mmexini.db3 file

**Comment by Heny67** [comment]
2b76.de
d5bk.de
iuse.l
iwda.as
vuaa.mi
xdwh.de

**Comment by n-stein** [comment]
With an SQL browser you can view your mmexini.db3 settings database. There are two keys which store the Yahoo Finance Cookie & Crumb values:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/db81daed-c19d-4cf3-b1d7-49e1aa702dbb)

**Comment by Heny67** [comment]
![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/448e3f85-aa1d-4758-b43a-5255adc7fab5)

**Comment by Galdor83** [comment]
Same error here and in the mmexini.db3 file I've no entry for YAHOO settings (171 total rows)

**Comment by n-stein** [comment]
Don't know what I was thinking.. of course the YAHOO settings will be blank -- they are only stored if the fetch is successful (which clearly isn't the case here).

@vomikan @whalley are either of you experiencing this issue?

**Comment by vomikan** [comment]
I just run the program, open the first database I come across and update the courses.
It works.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/4a1c7d2d-d149-4324-9c65-38314d58f465)

**Comment by whalley** [comment]
> Don't know what I was thinking.. of course the YAHOO settings will be blank -- they are only stored if the fetch is successful (which clearly isn't the case here).
> 
> @vomikan @whalley are either of you experiencing this issue?

I don't use this feature. But have created a test database and get the same result

![CleanShot 2023-06-22 at 23 00 10](https://github.com/moneymanagerex/moneymanagerex/assets/487345/4f03cec3-fbc6-443e-ba2f-81b66675e9b6)

**Comment by n-stein** [comment]
> created a test database and get the same result\n\n

Thanks, please debug when you get a chance and let us know what you find.

**Comment by swjpanton** [comment]
When I try and update I get the same errors and it is for all my stocks. My yahoo link is http://finance.yahoo.com/echarts?s=%s
Is this correct as this was the default link in the program when I got it?

**Comment by vomikan** [comment]
the working portable mmex with DB
[mmex-1.6.4-win64.zip](https://github.com/moneymanagerex/moneymanagerex/files/11846726/mmex-1.6.4-win64.zip)

**Comment by therealstretch** [comment]
> the working portable mmex with DB (for Windows)
> [mmex-1.6.4-win64.zip](https://github.com/moneymanagerex/moneymanagerex/files/11846726/mmex-1.6.4-win64.zip)

I confirm this is working for me.

**Comment by swjpanton** [comment]
Is there a fix for Macos: ventura

From: Nikolay ***@***.***>
Date: Friday, 23 June 2023 at 10:10
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: swjpanton ***@***.***>, Comment ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" (Issue #6040)

the working portable mmex with DB
mmex-1.6.4-win64.zip<https://github.com/moneymanagerex/moneymanagerex/files/11846726/mmex-1.6.4-win64.zip>

**Comment by therealstretch** [comment]
> Who can make a broken assembly - send.

a broken assembly could be one with missing or empty YAHOO_FINANCE_COOKIE and YAHOO_FINANCE_CRUMB in table SETTING_V1 of mmexini.db3

**Comment by whalley** [comment]
Not had time to do much investigation yet.... But the crumb returned looks wrong...

![CleanShot 2023-06-23 at 12 48 44](https://github.com/moneymanagerex/moneymanagerex/assets/487345/038f91b2-0100-4d6e-9508-bee9fcf4a823)

`"<!doctype html public \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n<html>\n<head>\n    <title>Yahoo! - Error report</title>\n    <style>\n        /* nn4 hide */ /*/*/\n        body {\n        font: small/ 1.2em arial, helvetica, clean, sans-serif;\n        font: x-small;\n        text-align: center;\n        }\n\n        table {\n        font-size: inherit;\n        font: x-small;\n        }\n\n        html>body {\n        font: 83%/ 1.2em arial, helvetica, clean, sans-serif;\n        }\n\n        input {\n        font-size: 100%;\n        vertical-align: middle;\n        }\n\n        p,form {\n        margin: 0;\n        padding: 0;\n        }\n\n        p {\n        padding-bottom: 6px;\n        margin-bottom: 10px;\n        }\n\n        #doc {\n        width: 48.5em;\n        margin: 0 auto;\n        border: 1px solid #fff;\n        text-align: center;\n        }\n\n        #ygma {\n        text-align: right;\n        margin-bottom: 53px\n        }\n\n        #ygma img {\n        float: left;\n        }\n\n        #ygma div {\n      "...`

Accessing same from my web browser gives...
![CleanShot 2023-06-23 at 12 50 25](https://github.com/moneymanagerex/moneymanagerex/assets/487345/bfd2f78e-aca1-43aa-84aa-80240d275374)

**Comment by n-stein** [comment]
> And also my installed version is working after I added the YAHOO_FINANCE_COOKIE and YAHOO_FINANCE_CRUMB from yours to my mmexini.db3 manually.

Yes, this is the workaround. Manually entering valid cookie/crumb values under the appropriate keys in mmexini.db3 will work as long as the cookie doesn't expire.

**Comment by vomikan** [comment]
Does simply deleting all the data from the mmexini.db3 file help?

**Comment by therealstretch** [comment]
> Does simply deleting all the data from the mmexini.db3 file help?

Unfortunately, it doesn't work for me.

**Comment by Heny67** [comment]
Hi All!

My laptop is still running 1.6.3. It says the invalid cookie error, not the missing url error. When I updated to 1.6.4 on my PC, it asked me to optimize the database. After that, it already indicated the missing url error and not the invalid cookie error. Could this not be related to the error?

**Comment by n-stein** [comment]
I don't think the issue is with mmexini.db3. If the cookie/crumb is missing or invalid the system will just fetch a new one. 

Maybe a difference in the way CURL is functioning on different platforms? Im rebuilding my Linux VM, will see if I get the issue to help @whalley debug.

**Comment by whalley** [comment]
I'm not sure what is going on here.... I've used a network debugger...

What doe the requests look like on Windows???

Request to **finance.yahoo.com**
```
GET / HTTP/1.1
Host: finance.yahoo.com
User-Agent: Money Manager Ex/1.6.4
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
```

Response:
```
HTTP/1.1 307 Temporary Redirect
Date: Sun, 25 Jun 2023 15:42:45 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000
Server: ATS
Cache-Control: no-store
Content-Type: text/html; charset=utf-8
Content-Language: en
Expect-CT: max-age=31536000, report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-expect-ct-report-only"
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: https://guce.yahoo.com/consent?brandType=nonEu&gcrumb=Zoawgpg&done=https%3A%2F%2Ffinance.yahoo.com%2F
Set-Cookie: GUCS=AWaGsIKY; Max-Age=1800; Domain=.yahoo.com; Path=/; Secure 
Content-Length: 0
```

Request to get crumb....
```
GET /v1/test/getcrumb HTTP/1.1
Host: query1.finance.yahoo.com
User-Agent: Money Manager Ex/1.6.4
Cookie: GUCS=AWaGsIKY
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
```

Response fails:
```
HTTP/1.1 500 Internal Server Error
x-frame-options: SAMEORIGIN
content-type: text/html;charset=utf-8
content-length: 3160
x-envoy-upstream-service-time: 1
date: Sun, 25 Jun 2023 15:42:45 GMT
server: ATS
x-envoy-decorator-operation: finance-yql--mtls-default-production-ir2.finance-k8s.svc.yahoo.local:4080/*
Cache-Control: max-age=0, private
Expires: -1
Age: 1
Strict-Transport-Security: max-age=31536000
Referrer-Policy: no-referrer-when-downgrade
Connection: keep-alive
Expect-CT: max-age=31536000, report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-expect-ct-report-only"
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff

<!doctype html public "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Yahoo! - Error report</title>
    <style>
        /* nn4 hide */ /*/*/
        body {
        font: small/ 1.2em arial, helvetica, clean, sans-serif;
        font: x-small;
        text-align: center;
        }

        table {
        font-size: inherit;
        font: x-small;
        }

        html>body {
        font: 83%/ 1.2em arial, helvetica, clean, sans-serif;
        }

        input {
        font-size: 100%;
        vertical-align: middle;
        }

        p,form {
        margin: 0;
        padding: 0;
        }

        p {
        padding-bottom: 6px;
        margin-bottom: 10px;
        }

        #doc {
        width: 48.5em;
        margin: 0 auto;
        border: 1px solid #fff;
        text-align: center;
        }

        #ygma {
        text-align: right;
        margin-bottom: 53px
        }

        #ygma img {
        float: left;
        }

        #ygma div {
        border-bottom: 1px solid #ccc;
        padding-bottom: 8px;
        margin-left: 152px;
        }

        #bd {
        clear: both;
        text-align: left;
        width: 75%;
        margin: 0 auto 20px;
        }

        h1 {
        font-size: 135%;
        text-align: center;
        margin: 0 0 15px;
        }

        legend {
        display: none;
        }

        fieldset {
        border: 0 solid #fff;
        padding: .8em 0 .8em 4.5em;
        }

        form {
        position: relative;
        background: #eee;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-width: 1px 0;
        }

        #s1p {
        width: 15em;
        margin-right: .1em;
        }

        form span {
        position: absolute;
        left: 70%;
        top: .8em;
        }

        form a {
        font: 78%/ 1.2em arial;
        display: block;
        padding-left: .8em;
        white-space: nowrap;
        background: url(https://s.yimg.com/lq/a/i/s/bullet.gif)
        no-repeat left center;
        }

        form .sep {
        display: none;
        }

        .more {
        text-align: center;
        }

        #ft {
        padding-top: 10px;
        border-top: 1px solid #999;
        }

        #ft p {
        text-align: center;
        font: 78% arial;
        }
        /* end nn4 hide */
    </style>
</head>
<body>
<div id="doc">
    <div id="ygma">
        <a href="http://www.yahoo.com">
            <img src="https://s.yimg.com/lq/a/i/yahoo.gif" width="147"
                 height="31" border="0" alt="Yahoo!">
        </a>

        <div>
            <a href="http://www.yahoo.com">Yahoo!</a>
            - <a href="http://help.yahoo.com">Help</a>
        </div>
    </div>
    <div id="bd">
        <h1>HTTP Status 500 - Server Error</h1>

        <p>
            <b>type</b>
            Exception report
        </p>

        <p>
            <b>message</b>
            <u>Server Error</u>
        </p>

        <p>
            <b>description</b>
            <u>Server Error</u>
        </p>

        <p>
            
        </p>
    </div>
</div>
</body>
</html>
```

**Comment by whalley** [comment]
OK, update......

**The issue seems to be geo-related.** If I use a USA based VPN connection then it works. If I use UK based it fails. So seems a Yahoo Finance restriction.

**Comment by swjpanton** [comment]
Mark does this mean those of us in uk need to use another "provider"?SimonOn 26 Jun 2023, at 07:25, Mark Whalley ***@***.***> wrote:﻿
OK, update......
The issue seems to be geo-related. If I use a USA based VPN connection then it works. If I use UK based it fails. So seems a Yahoo Finance restriction.

**Comment by swjpanton** [comment]
Hello Mark, does this mean the link used on mmex/options/others (http://finance.yahoo.com/echarts?s=%s<http://finance.yahoo.com/echarts?s=%25s>) is not valid and those in the UK need to use another provider? If so do you know one/

Regards Simon Panton

From: Mark Whalley ***@***.***>
Date: Monday, 26 June 2023 at 07:25
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: swjpanton ***@***.***>, Comment ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" (Issue #6040)

OK, update......

The issue seems to be geo-related. If I use a USA based VPN connection then it works. If I use UK based it fails. So seems a Yahoo Finance restriction.

**Comment by n-stein** [comment]
> The issue seems to be geo-related. If I use a USA based VPN connection then it works. If I use UK based it fails. So seems a Yahoo Finance restriction.

Good catch. I get the issue using a German VPN. Sounds like it is GDPR related and we need to explicitly accept cookies. I think we can make it work, just need to modify a bit.

**Comment by whalley** [comment]
Have just tried MMEX on Windows on my machine and I get the same error when trying to update currencies... So does not seem platform related but geo related in some way. Any other UK customers that can confirm?

**Comment by swjpanton** [comment]
I use MMEX (ver1.6.4) on Apple Mac and get the same errors and am based in the UK
Regards Simon Panton

From: Mark Whalley ***@***.***>
Date: Monday, 26 June 2023 at 14:32
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: swjpanton ***@***.***>, Comment ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" (Issue #6040)

Have just tried MMEX on Windows on my machine and I get the same error when trying to update currencies... So does not seem platform related but geo related in some way. Any other UK customers that can confirm?

**Comment by whalley** [comment]
Does not work for me...

![CleanShot 2023-06-26 at 18 07 19](https://github.com/moneymanagerex/moneymanagerex/assets/487345/177acc64-ece3-4931-bd30-02d9f904a290)

The curlURL is empty.

![CleanShot 2023-06-26 at 18 07 38](https://github.com/moneymanagerex/moneymanagerex/assets/487345/a0a9d292-b3f8-4da7-baa7-8280eb314d61)

Also crashes
```
mmex(27781,0x1ffbcde00) malloc: Double free of object 0x102d7e2e0
mmex(27781,0x1ffbcde00) malloc: *** set a breakpoint in malloc_error_break to debug
```
Do we need the first `free(quote.memory)` ?

**Comment by n-stein** [comment]
> The curlURL is empty

This is interesting because sessionId is successfully parsed from curlURL per your screenshot. How is it being cleared after?

> Do we need the first free(quote.memory)

Don't think so, will remove it.

**Comment by n-stein** [comment]
Try that. Previously I parsed the sessionId from the URL, now I'm doing the opposite. The sessionId is passed in the response body, so instead of parsing the effective URL from CURL we can just pull the sessionId from the body and build the correct URL using it.

**Comment by whalley** [comment]
> This is interesting because sessionId is successfully parsed from curlURL per your screenshot. How is it being cleared after?

Good point.... 

`curl_easy_setopt(curl, CURLOPT_URL, curlURL);`

clears the curlURL, prior to the call it was:

`https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_d1352de0-f261-4998-88de-666c08f76ea4`

...something odd going on here. When making the call it returns CURLE_URL_MALFORMAT

**Comment by whalley** [comment]
> Try that. 

Bingo! That works, great stuff.

**Comment by n-stein** [comment]
> `curl_easy_setopt(curl, CURLOPT_URL, curlURL);`
> 
> clears the curlURL

Interesting. Must just be a difference in the CURL implementation on Windows and macOS.

**Comment by n-stein** [comment]
> > Do we need the first free(quote.memory)
> 
> Don't think so, will remove it.

Removing free(quote.memory) leads to a memory leak. Will fix.

**Comment by Astermast3r** [comment]
Hi, it's not clear to me if the fix is also valid for all non-US and non-UK users, however I ask if it is possible to specify what should be done to solve it, even for those who are not able to access/modify the files .db3 with a SQL Browser. Thank you.

**Comment by n-stein** [comment]
@Astermast3r You can try the beta available here https://ci.appveyor.com/project/whalley/moneymanagerex/builds/47442333/job/vnfamv8yl1dvksva/artifacts.

**Comment by Astermast3r** [comment]
> @Astermast3r You can try the beta available here https://ci.appveyor.com/project/whalley/moneymanagerex/builds/47442333/job/vnfamv8yl1dvksva/artifacts.
Thank you so much @n-stein !!! Now all works fine!!

**Comment by swjpanton** [comment]
Hi, sorry to trouble you but may I ask why this is closed as completed when its not been completed for MMEX on Mac. I still get the same errors and prices are not updating.

Regards Simon

From: Nikolay ***@***.***>
Date: Thursday, 13 July 2023 at 22:39
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: swjpanton ***@***.***>, Comment ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" (Issue #6040)

Closed #6040<https://github.com/moneymanagerex/moneymanagerex/issues/6040> as completed.

**Comment by whalley** [comment]
>  Hi, sorry to trouble you but may I ask why this is closed as completed when its not been completed for MMEX on Mac. I still get the same errors and prices are not updating.

Are you using the latest Beta that has the fix?
https://link.ipx.co.uk/mmex-mac-betas

**Comment by swjpanton** [comment]
Hello Mark, No I had’nt and checked for updates. Will download and please may I thank you

From: Mark Whalley ***@***.***>
Date: Friday, 14 July 2023 at 09:11
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: swjpanton ***@***.***>, Comment ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" (Issue #6040)

Hi, sorry to trouble you but may I ask why this is closed as completed when its not been completed for MMEX on Mac. I still get the same errors and prices are not updating.

Are you using the latest Beta that has the fix?
https://link.ipx.co.uk/mmex-mac-betas

**Comment by franci207** [comment]
con la Versione: 1.7.0-Beta.1 64-bit non funziona nuovamente, ancora errore url using bad/illegal format or missing..... funzionava perfettamente con la versione 1.6.5-beta.1. adesso non vengono aggiornati i prezzi

**Comment by tactilis** [comment]
> con la Versione: 1.7.0-Beta.1 64-bit non funziona nuovamente, ancora errore url using bad/illegal format or missing..... funzionava perfettamente con la versione 1.6.5-beta.1. adesso non vengono aggiornati i prezzi

**English (auto translated)**

With the version: 1.7.0-Beta.1 64-Bit does not work again, still error URL Using Bad/Illegal Format or Missing ..... it worked perfectly with version 1.6.5-Beta.1.now prices are not updated

**Comment by vomikan** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/7b757235-ccd4-4bdd-951e-3c2004f5d858)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/29667593-d578-447f-9d4a-3c791f8eeff1)

**Comment by vomikan** [comment]
https://api.coingate.com/v2/rates/merchant/usd/eur

[fixer.io](https://fixer.io/)

[currencylayer.com](https://currencylayer.com/)

**Comment by n-stein** [comment]
It appears that Yahoo was blocking the cURL user agent (every request returned a '429: Too Many Requests' error), so I've explicitly overridden the UA string in the request header and it seems to be working.

@vomikan does that fix your issue?

**Comment by n-stein** [comment]
@franci207 please try this beta:
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/48121060

**Comment by franci207** [comment]
it's ok, works perfectly, problem solved!!! :-)

**Comment by vomikan** [comment]
It seems OK now
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/337ca13c-675a-4090-9f33-c814ca74e3bd)
