### ISSUE TITLE
MMEX for arch linux is not listed on the download page anymore

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#6045]
# Description of the feature

We have two arch linux packages:
- [Points to the newest version](https://aur.archlinux.org/packages/moneymanagerex)
- [Points to the newest git commit](https://aur.archlinux.org/packages/moneymanagerex-git)

# Use cases

Users see that MMEX exists for arch linux.

**Comment by whalley** [comment]
Only flatpak now listed.
