### ISSUE TITLE
code tag v1.6.4 has version 1.6.4-Beta.8

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#6046]
MMEX version:
 - [x] 1.6.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I got version `1.6.4-Beta.8` after compiling.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Compile https://github.com/moneymanagerex/moneymanagerex/tree/v1.6.4

Expected result:

v1.6.4

Actual result:
v1.6.4-Beta.8

# Additional information

https://github.com/moneymanagerex/moneymanagerex/blob/dd67784392b6a3fefd5ca8abb0e4e4c8c3e4a54c/CMakeLists.txt#L22

```
• Version: 1.6.4-Beta.8 64-bit
• erstellt am: Juni 23 2023 09:33:52
• Datenbankversion: 18 (aes128cbc)
• Git-Eintrag: dd6778439 (2023-06-20)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.2.1 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.4.6
• libcurl/8.1.2 OpenSSL/3.1.1 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.54.0
• gettext 0.21.1
• apexcharts.js
erstellt mit:
• CMake 3.26.4
• GNU Make 4.4.1
• GCC 13.1.1 20230429
Läuft auf:
• EndeavourOS.rolling.rolling
• EndeavourOS Linux "rolling"
• Linux 6.3.9-zen1-1-zen x86_64
• German (Germany) (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by vomikan** [comment]
Maybe I made a mistake when I added the tag. It seems to be reproducible. However, binary releases (for Windows) contain the correct version. 
I'm a little confused, I apologize.

**Comment by MartinX3** [comment]
@vomikan Maybe the release binaries use the master branch instead of the tag. :D

**Comment by n-stein** [comment]
The Windows binaries are from AppVeyor build 767 they should be from build 768.

**Comment by n-stein** [comment]
Tag 1.6.4 is tagged to the wrong commit. It is tagged to dd67784392b6a3fefd5ca8abb0e4e4c8c3e4a54c but CMakeLists.txt wasn't updated until the next commit 6b4cc698fad728f9a4c2f4638b12a99aeaf37151.

**Comment by MartinX3** [comment]
At least we only miss a cosmetic commit.
No bugfix or feature. :)
