### ISSUE TITLE
Organize vs Organise

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6062]
How is it correct?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/102838ed-9179-4c6f-b01d-0a5a7b3ed723)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/e8051852-ecce-4df9-affa-3c9aee85b1dc)

**Comment by n-stein** [comment]
The rest of the application has US localization with translations in the en_GB.po file. I think "Organize" is correct in this case.
