### ISSUE TITLE
Strings ordering

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6063]
Value %s for %s custom field '%s' is not a valid selection.
Value %s does not match regex %s for custom field '%s'.
Please allow strings to be ordered. %1s, %2s, %3s.

Hungarian translation is better if the order can be %2s, %1s, %3s

Thank you

Please allow strings to be ordered. %1s, %2s, %3s.

Hungarian translation is better if the order can be %2s, %1s, %3s

Thank you

https://crowdin.com/translate/moneymanagerex/470/en-ru?filter=basic&value=0

**Comment by vomikan** [comment]
There is no need to change the original message. You can use the following syntax in translation:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/01a7ae6c-2256-4e2a-b98b-2b2e81a092e1)

**Comment by ovari** [comment]
@vomikan would it be an improvement if the original source string also had this explicitly written? For example `Value %1$s for %2$s custom field '%3$s' is not a valid selection.` Would this help translators who do not know about this feature too?

Thank you

**Comment by vomikan** [comment]
Yes, it will help. But we will have to redo a large volume of messages and all translators will have to translate it again.

**Comment by n-stein** [comment]
#5329

**Comment by ovari** [comment]
> Yes, it will help. But we will have to redo a large volume of messages and all translators will have to translate it again.

Can new strings that are added please have the numbers added to variables when multiple variables in a string?

**Comment by vomikan** [comment]
> Requires a new preprocessor symbol be compiled in wxWidgets, so we would no longer be able to use the pre-built binaries.

Is this a proven fact? I change the string and it works.

**Comment by n-stein** [comment]
> Is this a proven fact? I change the string and it works.

You're correct, I don't know why I didn't think it was enabled by default. Looking at wx_setup.props now I see the default is 1.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/af524ef3-01ed-477a-bb16-8c7a2c3c138c)
