### ISSUE TITLE
Presets for CSV import

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6065]
Presets does not remember the score and the path to the file. Is it right?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/587ff21c-8626-4f9b-be89-3c7fea54bdd9)

**Comment by n-stein** [comment]
Correct. The presumption is you don't want to load the same file over and over again, so storing the file name is useless. If you want to populate the name when the dialog opens use the drag & drop method of import.

**Comment by tactilis** [comment]
>> Presets does not remember the score and the path to the file. Is it right?

> Correct. The presumption is you don't want to load the same file over and over again, so storing the file name is useless. 

In addition, you can now automatically associate the same preset if you wish with more than one MMEX account (assuming the bank's various accounts use the same CSV field layouts). So this is even more reason that we no longer store the file path in the preset.
