### ISSUE TITLE
Broken import .csv configuration prevents importing transactions

### ISSUE THREAD

**Issue by Bubba9876** [moneymanagerex/moneymanagerex#6068]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Something is wrong with my .csv import profile. The problem now is that I get the following error and it prevents me from importing anymore files. Need a work around to delete the import profile.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/138267727/329ed15d-38aa-4cfa-95fc-ceac5f378862)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
File>Import>.csv file
Expected result:
File import configuration windows opens
Actual result:
Error shown in screenshot above
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by Bubba9876** [comment]
Found a work around - File > import> .csv file into another account, change the import configuration to the broken one and delete it. I then can initiate the import of a .csv file & create a good import configuration.

**Comment by tactilis** [comment]
@Bubba9876 
Your report says you are using MMEX 1.6.2. Is this correct?
If so, you have missed upgrading to 1.6.3 and now to 1.6.4, where there have been numerous updates to CSV Import.

Please update and raise a new report if you again experiencing a problem.
