### ISSUE TITLE
Please extend the `Search` field to the end of the window. Thank you

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6069]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b3f3e8fe-47ca-4a35-885c-6f5a0fc543d8)

```
Money Manager Ex
• Version: 1.6.5-Beta.1 64-bit
• Built on: Jul 1 2023 03:27:17
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.15.0-76-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
If you want it any wider than this we would have to reconfigure the panel layout as the space on the right is currently reserved for additional transaction info.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/35bf73bd-ef19-4a44-9562-382e0eaa14f2)

**Comment by ovari** [comment]
Thank you @n-stein for the improvement.

> If you want it any wider than this we would have to reconfigure the panel layout as the space on the right is currently reserved for additional transaction info.

Should the panel layout be reconfigure? MMEX could then be used so that is takes up the left half of the screen and the right half of the screen could be a program with a document that is being entered into MMEX. This would help with avoiding ALT+TABbing between 2 software programs.

Thank you once again.
