### ISSUE TITLE
Saving account - deposit 0, saved as withdrawal

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#6071]
MMEX version:
 - [x ] 1.6.4
 - [] 1.6.5 Beta
 - [ ] 1.6.6
 - [ ] 1.6.7
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Let's say I have a Checking Account used as my savings account.
I transferred to this account 100 Euro monthly using Recurring Transactions and it was saved as a deposit.
One day, I decided to skip one transaction, but since I want to keep it consistent I just put Amount = 0

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
The 0 Euro is written as a deposit.
Actual result:
The 0 Euro is written as a withdrawal.
# Additional information
I suppose that 0 amount can be noted as a deposit or withdrawal in depending on what the user chooses in the previous dropdown box. 
If you have a backtrace for a crash or a warning, paste it here.
![Example](https://github.com/moneymanagerex/moneymanagerex/assets/83161661/31929066-138c-48b0-ab76-2a2c7c58473f)

**Comment by tactilis** [comment]
Recently found this myself. It is a bug

> I suppose that 0 amount can be noted as a deposit or withdrawal in depending on what the user chooses in the previous dropdown box.

That's true. However, if the user explicitly creates a transaction as a particular type, in this case a Deposit, the list ought reflect that.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/b1d2b7df-ea4b-40bc-9650-805e897a42a5)
