### ISSUE TITLE
MMEX database Upgrade to version 18 Failed

### ISSUE THREAD

**Issue by CelticDragon1975** [moneymanagerex/moneymanagerex#6077]
Arggghhhhh - Never had a problem until now : Need some help
![Screenshot 2023-07-04 222950](https://github.com/moneymanagerex/moneymanagerex/assets/138625996/3722a446-c6bb-4bca-8876-2d27b9133bc5)

**Comment by n-stein** [comment]
Do you have an SQLite browser you can run a `pragma integrity_check`? This will give us more information about what precisely is "malformed" in your database.

**Comment by tactilis** [comment]
@n-stein
> Do you have an SQLite browser you can run a pragma integrity_check? This will give us more information about what precisely is "malformed" in your database.

As an aside, is there a way that `pragma integrity_check` could be provided in an .mmdbg file for running via `Tools | Database | Database Debug`, with the ability to display the output for copy/paste by the user?

If so, it would be preferable to asking users to investigate via an SQLite browser.

**Comment by CelticDragon1975** [comment]
Hi Screenshot as attached![image](https://github.com/moneymanagerex/moneymanagerex/assets/138625996/fc16c771-7885-4b50-a889-700065697d93)

**Comment by CelticDragon1975** [comment]
> Do you have an SQLite browser you can run a `pragma integrity_check`? This will give us more information about what precisely is "malformed" in your database.

As attached.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/138625996/a730fd1f-368d-44e8-a7ed-093ff8c32368)

**Comment by n-stein** [comment]
> is there a way that pragma integrity_check could be provided in an .mmdbg file for running via Tools | Database | Database Debug, with the ability to display the output for copy/paste by the user?
> If so, it would be preferable to asking users to investigate via an SQLite browser.

Had the same thought. I've entered #6079. We can add a message box with the result of the integrity check prior to prompting for the debug file.

**Comment by n-stein** [comment]
@CelticDragon1975 can you drag the field wider so the output isn't truncated with the '...'

**Comment by CelticDragon1975** [comment]
> @CelticDragon1975 can you drag the field wider so the output isn't truncated with the '...'

Hi Updated screenshot

Page5: btreeInitPage() returns error code 11

![image](https://github.com/moneymanagerex/moneymanagerex/assets/138625996/e9c806a5-2bdb-4e6b-a988-c0b4acb85054)

**Comment by CelticDragon1975** [comment]
Should also say that running 1.6.3 I have no issue.

**Comment by n-stein** [comment]
Page errors are tough. When was your last backup? You can run an integrity check on your backups to see if they have the same issue. If you have a backup with no integrity issues you can start from that point and re-enter any missing transactions.

Or, you can try to rebuild your `Live Accounts.mmb` database by doing the below. Note that there is no guarantee all data can be recovered, so at the end of this process you should check to make sure all of your transactions are there (check expected balances, record counts, etc):

1. In DB Browser go to File -> Export -> Database to SQL file.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/afa09732-d7e6-4386-866e-37bce5be7558)

    Select these options:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/82e11cb9-6b0c-4487-bd30-de688f8c6144)

    Name it something like `mmex-repair.sql`

2. In DB Browser import the file you just exported via File -> Import -> Database from SQL file. Select your `mmex-repair.sql` file.

    ![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/2fe0272a-383c-483a-94a5-f168b1c515c0)

    When asked to create a new DB select "Yes". Name your new database (select the file type 'All Files' and save with the .mmb extension), something like `mmex-fixed.mmb`

    ![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/6f08e7a0-1773-431d-9e41-bc25d3721fa6)

3. Click 'Write Changes' to save the data.

    ![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/aebc4189-f62e-4cd8-b88f-64e21a01c25c)

5. Optionally compare `mmex-fixed.mmb` to `Live Accounts.mmb` in DB Browser, check record counts for each table (to verify all records were recovered successfully).

6. Open your `mmex-fixed.mmb` in 1.6.4. It should update correctly.
7. Compare your `mmex-fixed.mmb` in 1.6.4 to your `Live Accounts.mmb` in 1.6.3, check for completeness.

**Comment by CelticDragon1975** [comment]
![Screenshot 2023-07-06 210201](https://github.com/moneymanagerex/moneymanagerex/assets/138625996/1c8b9572-1e72-4343-84fe-a05595a98d2e)

This did not work - Now have the following error !!

**Comment by CelticDragon1975** [comment]
Tried restoring from back ups from 2022 and similar errors. Had no problems upgrading until this more recent release.

**Comment by n-stein** [comment]
Sorry, I missed a step. In your repaired DB go to the "Edit Pragmas" tab, change "User Version" to 17, then click the "Save" button in the bottom right corner.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/18d42c2a-2e24-4c7d-a470-ee97a3a800b8)

**Comment by CelticDragon1975** [comment]
Thank you for that addiotional step. All working and data integrity looks good.

**Comment by n-stein** [comment]
@CelticDragon1975 If the issue has been resolved to your satisfaction please close.

**Comment by CelticDragon1975** [comment]
Sorry selected wrong emoji

**Comment by tactilis** [comment]
> Sorry selected wrong emoji

For info... you can just click an incorrectly applied emoji to remove it

**Comment by CelticDragon1975** [comment]
Perfect thanks. I used long press.
