### ISSUE TITLE
Add an "Integrity Check" to the Database Debug

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6079]
# Description of the feature

Many database issues require the user to run `PRAGMA integrity_check` to determine the root cause. I suggest we add this to the Database Debug... choice in the Tools > Database menu.

1. User clicks Tools > Database > Database Debug...
2. An integrity check is executed and the user is presented with the result.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/0b7c5ca6-bdde-425a-870a-4bb0f1aeb4b5)

3. The normal debug dialog is then displayed.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/349db778-a6c6-4355-a180-97dab87baf6a)

We could make it a separate menu option, but seems to fit OK here without adding more menu entries.

# Use cases

Assist in debugging database issues without relying on user's knowledge of SQLite or use of a database browser.

**Comment by tactilis** [comment]
> 1. User clicks Tools > Database > Database Debug...

It would be better to make that `Tools > Database > Database Check and Debug...`
That gives a clearer hint as to what is going to happen next.

<br>

> 2. An integrity check is executed and the user is presented with the result

Ideal.

It would be preferable though if the results, which I presume could be multi-line, are displayed in a read-only text field. That way the user can copy and paste the text into a github comment or a forum post. Not all users are adept at capturing and posting screenshots.

The dialog title should be changed from `DB Debug` to `Database Check` 

<br>

> The normal debug dialog is then displayed.

IMO the dialog title should be `Database Debug`

The text should say: "_Please use this function only if requested by MMEX support and you have been supplied with a .mmdbg debug file_"

Again, the purpose is to give the user a hint as to what comes next.

**Comment by n-stein** [comment]
> It would be better to make that Tools > Database > Database Check and Debug...

Done.

> It would be preferable though if the results, which I presume could be multi-line, are displayed in a read-only text field. That way the user can copy and paste the text into a github comment or a forum post. Not all users are adept at capturing and posting screenshots.

Changed to a multiline wxTextEntryDialog with disabled text entry.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/d8cfbef0-e83a-43d2-a23b-0d831b9067ad)

> IMO the dialog title should be Database Debug
>The text should say: "Please use this function only if requested by MMEX support and you have been supplied with a .mmdbg debug file"

Done.

**Comment by whalley** [comment]
MacOS build...

```
[ 61%] Building CXX object src/CMakeFiles/mmex.dir/mmpanelbase.cpp.o
/Users/mark/gitrepos/moneymanagerex/src/mmframe.cpp:2392:67: error: no member named 'GetWindowChild' in 'wxTextEntryDialog'
        wxTextCtrl* textCtrl = dynamic_cast<wxTextCtrl*>(checkDlg.GetWindowChild(3000));
                                                         ~~~~~~~~ ^
1 error generated.
```

**Comment by n-stein** [comment]
Try checkDlg.FindWindow(3000) instead

**Comment by whalley** [comment]
> Try checkDlg.FindWindow(3000) instead

Yep, that works.

**Comment by n-stein** [comment]
Small tweak, just added the MMEX icon to the check dialog header because it felt too plain.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/20462790-4306-4076-81a8-ae249b26ce6e)
