### ISSUE TITLE
Totale patrimonio netto : Saldo errato

### ISSUE THREAD

**Issue by FrancoVin** [moneymanagerex/moneymanagerex#6080]
> Nella home page di MME in alto nel riquadro centrale c'è una riga che riguarda il TOTALE PATRIMONIO NETTO, nella stessa riga a destra viene proposto il SALDO: ma attualmente la cifra indicata non è la somma delle varie voci (conti bancari+carte credito+conti deposito+titoli)
Posso chiedere se quella riga è in qualche modo parametrizzabile?
Grazie per l'attenzione 

<hr> • Version: 1.6.4 64-bit<br>
 • Built: Giu 20 2023 18:27:14<br>
 • db 18 (aes128cbc)<br>
 • git 6b4cc69 (2023-06-20)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 •  Italian (Italy) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
English translation:

**Total net assets: incorrect balance**

On the MMEX home page above in the central box there is a row concerning the total net assets, in the same line the balance is proposed: but currently the amount indicated is not the sum of the various items (bank accounts+credit cards+storage accounts+securities)

Can I ask if that line is somehow parameterizable?

Thanks for the attention

**Comment by FrancoVin** [comment]
Total Net Assets: Incorrect balance

On the MMEX home page above in the central box there is a line relating to the total net assets, in the same line the balance is proposed: but currently the amount indicated is not the sum of the various items (bank accounts + credit cards + accounts storage + securities)

May I ask if that line is somehow parameterizable?

Thanks for the attention

To date the problem has not been resolved 
Can you help me in someway

**Comment by whalley** [comment]
Can I ask that you share a screenshot of the figures displayed and an indication of which values are correct, e.g.

- Reconcilled: Correct/Incorrect
- Assets: Correct/Incorrect
- Stock: Correct/Incorrect
- Balance: Correct/Incorrect

**Comment by FrancoVin** [comment]
I can't show you the screenshot bat i can tell you this
RECONCILLED : probably correct (it's difficult to count)
ASSET : correct (zero because i don't use)
STOCK : correct
BALLANCE : INCORRECT  becaus the balance should be the sum of (bank accounts + credit card + savings account + securities) but it's not like that

Many tanks for you attention

**Comment by whalley** [comment]
Do any othese discussions help?
https://github.com/moneymanagerex/moneymanagerex/issues/6043
https://github.com/moneymanagerex/moneymanagerex/issues/5834

**Comment by FrancoVin** [comment]
Ho letto gli altri due posts suggeriti ma non ho trovato la soluzione. Io ho l'abitudine di salvare screenshot al 31.12 di ogni anno. Quello dell'anno 2022 era corretto. Da dopo l'ultimo aggiornamento software ho riscontrato questa anomalia, già segnalata a giugno (non solo da me) e non ancora presente non risolta. 

I read the other two suggested posts but didn't find the solution. I have the habit of saving screenshots on 12/31 of each year. The one for the year 2022 was correct. Since the last software update I have encountered this anomaly, already reported in June (not just by me) and not yet present and not resolved.

**Comment by FrancoVin** [comment]
Ho letto gli altri due posts suggeriti ma non ho trovato la soluzione. Io ho l'abitudine di salvare screenshot al 31.12 di ogni anno. Quello dell'anno 2022 era corretto. Da dopo l'ultimo aggiornamento software ho riscontrato questa anomalia, già segnalata a giugno (non solo da me) ed era già presente non risolta. 

I read the other two suggested posts but didn't find the solution. I have the habit of saving screenshots on 12/31 of each year. The one for the year 2022 was correct. Since the last software update I have encountered this anomaly, already reported in June (not just by me) and was juat present and not resolved.

**Comment by FrancoVin** [comment]
My same problem has already been described in two other threads, so I'm not the only one.
As you can certainly understand, it is not easy to share personal data in a forum.

**Comment by FrancoVin** [comment]
My same problem has already been described in two other threads, so I'm not the only one.

As you can certainly understand, it is not easy to share personal data in a forum.

It is possible to send directly email?

 

 

Da: Mark Whalley ***@***.***> 
Inviato: lunedì 4 dicembre 2023 18:54
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: FrancoVin ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Totale patrimonio netto : Saldo errato (Issue #6080)

 

I can't show you the screenshot bat i can tell you this

RECONCILLED : probably correct (it's difficult to count)

ASSET : correct (zero because i don't use)

STOCK : correct

BALLANCE : INCORRECT becaus the balance should be the sum of (bank accounts + credit card + savings account + securities) but it's not like that

Many tanks for you attention

I'm afraid without specific detail or a (redacted) database there is little to help me investigate further. Whilst I can look through all the coded logic for this without a specific pointer it will take too long.

If others have encountered the same issue then perhaps they can share detail.

**Comment by whalley** [comment]
> It is possible to send directly email?

Of course, you can send to me at support@moneymanagerex.org

After reviewing and (hopefully) identifying the issue I will of course delete the file.

Mark

**Comment by whalley** [comment]
After reviewing the test DB you supplied. I can see that the home page shows
![CleanShot 2023-12-08 at 00 15 35](https://github.com/moneymanagerex/moneymanagerex/assets/487345/eb0c612b-e3c7-4c5b-8018-b97c3d7ec66e)
Looking at the 'Summary of Accounts' report this is:
![CleanShot 2023-12-08 at 00 16 31](https://github.com/moneymanagerex/moneymanagerex/assets/487345/b617506f-b983-4f93-960d-3d47fadab16d)
Which seems to align.

The spend on stocks shows no gain to net effect on total assets is ZERO.

[prova9999.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/13607016/prova9999.mmb.zip)

**Comment by whalley** [comment]
Closed due to inactivity.
