### ISSUE TITLE
MMEX icon in ALT+TAB is blurry

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6096]
MMEX icon in ALT+TAB is blurry. Are vector images used in MMEX? If bitmap images are used, should they be replaced with vector images?

Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/bf340194-be57-46d4-b80b-e5069d5c5c0c)

```
Money Manager Ex
• Version: 1.6.5-Beta.1 64-bit
• Built on: Jul 1 2023 03:27:17
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.15.0-76-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
SVG is already used for Linux:

https://github.com/moneymanagerex/moneymanagerex/blob/88607384e5b129970a8454d20fcce85f835a4d99/CMakeLists.txt#L643-L647

**Comment by ovari** [comment]
Thank you @n-stein for your comment.

Sorry, don't know.

@joshua-stone can you please check?

Thank you

**Comment by joshua-stone** [comment]
The SVG should be used:

```
$ find /var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/files/share/icons -type f
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/files/share/icons/hicolor/scalable/apps/org.moneymanagerex.MMEX.svg
$ find /var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export -type f
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/share/applications/org.moneymanagerex.MMEX.desktop
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/share/icons/hicolor/scalable/apps/org.moneymanagerex.MMEX.svg
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/share/metainfo/org.moneymanagerex.MMEX.appdata.xml
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/share/mime/packages/org.moneymanagerex.MMEX.mime.xml
/var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/bin/org.moneymanagerex.MMEX
$ grep -i "^Icon" /var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/export/share/applications/org.moneymanagerex.MMEX.desktop
Icon=org.moneymanagerex.MMEX
```

The line `StartupWMClass=mmex` isn't present in the desktop file however:

https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/applications/org.moneymanagerex.MMEX.desktop

**Comment by joshua-stone** [comment]
Try to make a copy of the desktop file:

```
$ mkdir -p ~/.local/share/applications
$ cp /var/lib/flatpak/app/org.moneymanagerex.MMEX/current/active/files/share/applications/org.moneymanagerex.MMEX.desktop ~/.local/share/applications/org.moneymanagerex.MMEX.desktop
```

And see if setting `StartupWMClass=mmex` or `StartupWMClass=org.moneymanager.MMEX` does anything.

**Comment by ovari** [comment]
Have not changed any code.

As shown in the image below, opened both [developmental release](https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex) and [Flatpak](https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX).

[Developmental release](https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex) shows blurry image.
[Flatpak](https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX) shows clear image.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/9fe7f9b3-df4c-402a-b233-0b9200760d55)

**Comment by ovari** [comment]
> The SVG should be used.

Yes, seems to be the case. What needs to changed so that the non-flatpak version also uses SVG? Thank you

**Comment by ovari** [comment]
1. Open Files (aka Nemo)
2. Navigate to `/usr/share`
3. Right-click on `applications` and select `Open as root`
4. Enter password
5. Right-click on `MMEX Money Manager` and select `Open With Text Editor`
6. After `Type=Application`, on a new line add `StartupWMClass=mmex`
7. Save file
8. Close file
9. Works, thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/34ba1833-973d-4619-b404-ab2fd2fab5c3)
