### ISSUE TITLE
View Since Statement Date does not work unless account statement is Locked

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#6098]
MMEX version:
 - [x] 1.6.4
 
As reported here https://forum.moneymanagerex.org/viewtopic.php?p=24084 filtering a transaction list `Since Statement Date` does not work if Edit Account | Statement | Locked is not checked:

> "When setting a statement date for an account and then viewing the account as View Since statement Date all transactions are listed. I need to check the Locked checkbox to get the correct view. This locks all transactions prior to the statement date in every view and the Locked checkbox has to be unchecked again when viewing, for example, All transactions. Could Locked and Statement date have their interdependence removed please?"

<br>

If Locked is checked, it should (and does) raise a warning if you try to enter a transaction with a date <= to the statement (Reconciled) date.

However having Locked checked should not be necessary if all you want to do is filter the transactions based on the statement (Reconciled) date.

**Comment by n-stein** [comment]
fixed
