### ISSUE TITLE
Monthly Summary of Accounts

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#610]
The report
- slow
- does not show today stats
- does not use currency rates history?

has no sense in current realization.

**Comment by guanlisheng** [comment]
Let's remove this @moneymanagerex/desktop-mmex-team

**Comment by guanlisheng** [comment]
Done.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/b0f9a9e61f68cf7fb08b257f7d0d606324bb4609
