### ISSUE TITLE
Dashboard Transaction Statistics erroneously includes deleted transactions

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#6102]
MMEX version:
 - [x] 1.6.4
 
 The Dashboard includes a panel named Transaction Statistics which displays the number of transactions marked as `Follow Up` and the Total number of transactions.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/11b09ad3-a389-46b6-ae48-3f68b8528983)

**Actual Result**

Both of these numbers include a count of transactions that have been deleted and are in the Deleted Transactions view.

**Expected Result**

Deleted transactions should be excluded from the counts.

**Comment by n-stein** [comment]
fixed
