### ISSUE TITLE
Teach me how to use CSV import, please

### ISSUE THREAD

**Issue by mariusZZ51** [moneymanagerex/moneymanagerex#6103]
# CSV import must be way more simple 

I have few year and cannot finish my transition from one app to this just because importing in this app its a nightmare I downloaded CSV reports from my bank and I did try different ways and still could not do it  !! apparently different banks using differently information in csv reports so we ending with crap like this !!! Always getting some errors !!!
 I guess will be better to review and improve CSV file import because today its a disaster !!
below its an example of csv from my bank
![Capture](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/ec217cbf-82b8-4e05-868f-4d734c2dd476)

**Comment by n-stein** [comment]
That does not appear to be a well formatted CSV file -- you have different numbers of columns in every row. There is no way any software can import a CSV file such as this in a consistent manner.

It looks like the fields may be improperly escaped. Can you open the CSV file in a text editor instead of OpenOffice Calc and share a view of the raw data? This will let us tailor our response to your bank's particular output.

**Comment by mariusZZ51** [comment]
@n-stein > that's correct its not and Ive been trying many variations and nothing working, I have to chose the more closest one and then edit it manually !! which will take ages !
@tactilis > can you please slow down your horses in labeling people in something !! whatever you imagination is I did not offended anyone here or had any intentions like this ! the fact is you came with some accusation just because you believe something !! i believe is better to solve the problems instead to focus on some non existing issues !! 

this is how csv looks in txt ..

![Capture](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/84e1a41a-668a-49f6-901d-1ae9426100d5)

**Comment by n-stein** [comment]
Your bank has an interesting mix of single `'` and double `"` quotes in that export. At first glance it looks as though if you remove all the single quotes the format would be correct. Try a Find/Replace to remove all the single quotes `'` and see if that makes everything line up properly in OpenOffice.

**Comment by tactilis** [comment]
Picking as an example, the 2 Amazon transactions:

```
Date, Type, Description, Value, Balance, Account Name, Account Number
04/07/2016,POS,"'5672 01JUL16, AMAZON UK RETAIL, AMAZO, AMAZON.CO.UK LU",-13.46,209.50,"'AC NAME", "'AC NUMBER",
04/07/2016,POS,"'5672 03JUL16, AMAZON UK RETAIL, AMAZON.CO.UK LU",-20.07,189.43,"'AC NAME", "'AC NUMBER",
```

As expected, MMEX imports your bank's data without any problems (even with the extra single quotes, **which the bank adds to ensure that Excel interprets the Description and Account Name & Number fields as Text**):

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/1b584cae-2e60-4959-bbb1-232b26ff3981)

You can even get MMEX to Pattern Match the Payee and auto assign a Category to save you work:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/0899db9d-6a9e-4d16-be36-7b899f0e642e)


<br>


@mariusZZ51
> whatever you imagination is I did not offended anyone here 

The way you went about seeking help offended me, and other people here have indicted their agreement with this view.

<br>

@mariusZZ51
> CSV import its absolutley horible
> importing in this app its a nightmare
> so we ending with crap like this !!!
> I guess will be better to review and improve CSV file import because today its a disaster !!

None of what you wrote is true. It was not necessary for you to write in that inflammatory manner.

**Comment by renato-mmex** [comment]
I think many users forget that MMEX is freeware. MMEX is programmed and also maintained by volunteers. I would appreciate it very much if this circumstance is taken into account and the colloquial language is chosen accordingly.

**Comment by n-stein** [comment]
> the extra single quotes, which the bank adds to ensure that Excel interprets the Description and Account Name & Number fields as Text

Ah, of course. Thanks for pointing that out. Makes sense, they don't want Excel to strip leading zeros or reformat the number into scientific notation which it is  wont to do.

**Comment by tactilis** [comment]
Noted that you have updated the title @vomikan  👍

**Comment by mariusZZ51** [comment]
OK guys thanks for replaying, I'm a bit busy with other things at the moment !! I'll try what you recommended here and I will be back with the results as soon as possible !!

**Comment by mariusZZ51** [comment]
ok so what do we have here @tactilis ?!? very "easy" As expected, MMEX imports my bank's data without any problems !! Maybe you know better @vomikan because you change the title ! (I guess in you mind you were thinking of 'how to use CSV for stupid')
by the way @tactilis why to use Excel if @vomikan said I just don't know how to use CSV and just better to learn it !! Apparently only me left who doesn't know how to use CsV in this world ))) !!
![001](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/e96982b0-9007-49db-aa48-b1c5eb3ab07e)
![002](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/af9cbb7f-7e0f-488a-aa9c-d4846c861957)

**Comment by vomikan** [comment]
For this csv file could you please use:
Date
Notes
Notes
Amount
Don't care
Don't care
Don't care
Don't care

**Comment by n-stein** [comment]
@mariusZZ51 

In your first screenshot the log panel says the error is "The opening date of the account is later than the date of the transaction". Right click on the account "RBStest" in the nav panel, select "Edit" and change the account opening date to a date <= the first transaction in your CSV file.

**Comment by tactilis** [comment]
> For this csv file could you please use:
Date
Notes
Notes
Amount
Don't care
Don't care
Don't care
Don't care


I'd propose a small change to the above:
Date
Notes  (or **Don't care** if you are in not interested in recording the bank's transaction type code)
**Payee**    (because the bank's Description field is actually the description of the Payee)
Amount
Don't care
Don't care
Don't care
Don't care

<br> 

@mariusZZ51 you are using an out of date version of MMEX.

You need to update to the the latest version, which is 1.6.4. It has bug fixes and a new feature called Payee Matching. With this we can help you turn the bank's Description into sensible Payee names during Import.

**Comment by mariusZZ51** [comment]
@vomikan so as i understand 'i don't care' means to avoid certain columns in csv ?!! yea that was very obvious solution just put Don't care instead, why i dint figure out so long  !! but at lest it did work this way just i need some time to how to setup other unknown fields  and seems to be the solution !!!
![321](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/292063d6-e24a-41cc-a7f9-2186980cb63a)
![9876](https://github.com/moneymanagerex/moneymanagerex/assets/36503666/af873ef8-2153-49c6-90ca-aed2ebb2d21e)

**Comment by tactilis** [comment]
> i need some time to how to setup other unknown fields and seems to be the solution

As I indicated above, Payee can be handled like this:
    Date
    Notes   (or Don't care if you are in not interested in recording the bank's transaction type code)
    **_Payee_**   (because the bank's **_Description field is actually the description of the Payee_**)
    Amount
    Don't care
    Don't care
    Don't care
    Don't care

**Comment by mariusZZ51** [comment]
Apologies to everyone, I was in holiday for over a month so I'm back and I'll review and try all recommendations about my issues and will be back as soon as I'll have some results!

**Comment by mariusZZ51** [comment]
ok so finally @tactilis advise worked as I expected to be from the beginning , I wanna thank everyone for help !!
