### ISSUE TITLE
Tags field should not be displayed on New Transaction screen for split transactions

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/moneymanagerex#6123]
MMEX version:
 - [x] 1.7.0-Beta. 1 64-bit

Operating System:
 - [x] Windows 10 22H2

# Description of the bug
Following on from my comments in https://github.com/moneymanagerex/moneymanagerex/issues/5439:

The **Tags** field should not be displayed on the **New Transaction** screen when you create a split transaction. It should only be displayed on this New Transaction screen for non-split transactions, i.e. single line transactions.

For split transactions, capturing tags here doesn't seem to make sense because tags are associated with each item in the split transaction:

![Tags on New Transaction Screen](https://github.com/moneymanagerex/moneymanagerex/assets/1124791/b058c91c-f8d0-49ab-a3ec-4177c7b6729b)

The reason I say that is because when you create a split transaction you open the Split Transaction screen. That screen already has the Tags field on each row and that's where you capture your required tags for each row in the transaction:
![Tags_on_Split_Transaction](https://github.com/moneymanagerex/moneymanagerex/assets/1124791/1b1ca82c-43a6-4d56-93b8-b3f986017cab)

That's perfect because you can then assign different tags to each line in the split transaction. You wouldn't normally want to ALSO capture tags on the **New Transaction** screen - it seems pointless to add tags on the New Transaction screen AND on the Split Transaction screen.

**Comment by tactilis** [comment]
> The Tags field should not be displayed on the New Transaction screen when you create a split transaction. It should only be displayed on this New Transaction screen for non-split transactions, i.e. single line transactions.

Partially agreed.

The field should be still be displayed but be greyed out and inactive.

Toying with the idea that the field should say `See Split`, in grey like the `Split Transaction` text in the Category field, if there tags on _any_ rows of the Split Transaction dialog.

**Comment by luisdev** [comment]
Yes, I agree that the field should be still be displayed but be greyed out and inactive. That's perfect.

**Comment by luisdev** [comment]
I suppose it doesn't hurt to have them in both places, but why would you use them both? When and why would you apply a tag to the overall transaction when you've added tags to the individual lines in the split transaction?

Doesn't having them in both places just create a more confusing interface?

Either way, I'm not complaining too much. We finally have TAGS!! :-)

**Comment by tactilis** [comment]
@n-stein
> Right now tags are treated the same way we treat notes. You can have a note for the overall transaction and then individual notes on the splits. Tags is the same way, you can tag the overall transaction and assign different tags individually to the splits.

Ah, I didn't realise this.

So now I'm trying to weigh up:

a) the simplicity of presentation and the enhancement in user comprehension of having tags only on the rows of the split, which means that we have one simple rule that says every **categorized** expense (or receipt) can have one or more tags.

vs.

b) the ability to tag the categorized rows of the split as above _and_, separately, to tag the overall transaction, which groups together the splits, but which does not itself have a category.

I'm struggling to decide which is best.

However, the fact that @luisdev and I thought that a split transaction should not have a transaction level tag is perhaps an indication that having this capability would be confusing.

Is it the case that for reporting purposes, a transaction level tag is implicitly applied to _**all**_ of the rows of the split, even though it is not shown there? If this is so, then I would be in favour of requiring the user to be explicit about this and add the tag to each row of the split; i.e. option a) above.

It just seems less confusing to go to one place, the Split dialog, to see _all_ the tags, just as you go to the Split dialog to see _all_ the categories.

**Comment by n-stein** [comment]
> Is it the case that for reporting purposes, a transaction level tag is implicitly applied to _**all**_ of the rows of the split, even though it is not shown there? If this is so, then I would be in favour of requiring the user to be explicit about this and add the tag to each row of the split; i.e. option a) above.

Correct. Consider this transaction:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/94c5fbb6-7d6c-403a-a27d-35c672d8024f)

If I run a transaction report for `House` I get all line items:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/005d86f6-b882-4b27-b58e-1c9093e83330)

Without the ability to tag the base transaction, I have to apply the tag to each split individually to achieve the same result.

**Comment by tactilis** [comment]
> Without the ability to tag the base transaction, I have to apply the tag to each split individually to achieve the same result.

Yes, I get that. Having to tag each split is what I meant by being explicit rather than implicit.

However, based on your example, I do see see the advantage of tagging the base transaction. One thing to note though is that when viewing the Transaction dialog, you have no idea whether there are any tags on the splits unless you open the Split dialog to take a look. Is there merit in displaying something as a hint that there are tags hidden in the splits? I am undecided on this.

Looking at the transaction list, the user does see that there are multiple tags:
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/0345bccb-db4d-4589-8a22-bb3e55d348c8)
 
but can't tell whether any are applied to splits though. Except perhaps in this instance where Utilities is listed twice.

Should we display an * in front of the list of tags that belong to the splits? Or does none of this matter?

**Comment by tactilis** [comment]
Testing:

• Version: 1.7.0-Beta.1 64-bit
• Built on: Jul 18 2023 20:02:15
• Database version: 19 (aes128cbc)
• Git commit: 57c0c1a (2023-07-18)

If I type a new tag name in the Tag field on the Transaction dialog or on the Split dialog and tab out of the field, I am not asked whether I want to create a new tag and the name is erased from the field.

Expected Result: I am asked whether I want to create a new tag

**Comment by n-stein** [comment]
> but can't tell whether any are applied to splits though

In the checking panel tags for the same transaction/split are separated by the normal tag whitespace separator. The `,` is separating the split items: `House, Utilities, Utilities, Taxes,`.

**Comment by vomikan** [comment]
> The reason I say that is because when you create a split transaction you open the Split Transaction screen. That screen already has the Tags field on each row and that's where you capture your required tags for each row in the transaction:

In this case, the tags turn into something like categories.
For example, I want a transaction with many categories to be designated as #vacation. Why not?
In any case, this is debatable.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/8ec642cd-2d4f-40fe-8f0a-881c86340eff)

**Comment by tactilis** [comment]
@vomikan
> For example, I want a transaction with many categories to be tagged as #vacation. Why not?
In any case, this is debatable. But I'm in favor of leaving it as it is.

I agree (now).
@n-stein's example and the fact that you can see the full list of tags that have been applied on the base transaction and the split-categories on the transaction list convinced me.

**Comment by n-stein** [comment]
> In the checking panel tags for the same transaction/split are separated by the normal tag whitespace separator. The , is separating the split items

Any suggestions on a better way to display this? I took a cue from categories which uses the comma separator, though it also uses the leading asterisk. Should prepend the tags field with `*` as well? Or is there some other format change which would be clearer to end users?
