### ISSUE TITLE
Button clipped and unable to resize top and bottom of Merge dialogs

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6127]
Bottom buttons in Merge tags dialog are clipped (not showing). Can resize left and right dialog; however, unable to resize top and bottom of the dialog.

Similar for Merge payees and Merge categories dialogs.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/afb917a9-2a73-454f-9a35-39ce778a7806)

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Jul 19 2023 19:40:21
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-76-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by vomikan** [comment]
On Windows it liiks OK
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/b4c2779f-2c68-41bf-9121-051870aba8f0)

**Comment by n-stein** [comment]
@ovari is this still an issue? The 1.7.1 Beta looks OK on my Debian 12 system:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/d4978cdc-f7ee-4336-959b-6161b8057ce3)

**Comment by ovari** [comment]
Showing correctly with Version: 1.7.1-Beta.1 64-bit Built on: Feb 29 2024 03:16:21. Thank you
