### ISSUE TITLE
SSL connect error when attempting to Update share price & Check for MMEX updates

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#6132]
MMEX version:
 - [x] 1.6.4
 
Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In https://forum.moneymanagerex.org/viewtopic.php?t=10877 an MMEX user reports "SSL connect error" when attempting to refresh a share price.

Subsequent investigation reveals that the "SSL connect error" message also occurs when the user does `Help | Check For Updates`.

I can't find reference to this problem in previous issues, so could someone provide guidance on next steps please?

**Comment by n-stein** [comment]
Same as #5870

**Comment by tactilis** [comment]
> Same as https://github.com/moneymanagerex/moneymanagerex/issues/5870. Seems it is likely a transient error on the server side.

Ah yes, I'd forgotten about that. That explains the Check for Updates error but the OP on the forum said they were getting the same SSL connect error when updating share prices.
