### ISSUE TITLE
ALL FILTER OF REG. DOESENT WORK FINE.

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#6135]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
FILTER does not work.

# Reproduction
In fact, when I launch any search, it DUPLICATEs the operations (see registration ID ex. 210.1, etc.) which have a Category "Split" procedure inside them. If, on the other hand, the tables are not filtered, the numbers of the entries are correct. Note. Unfortunately I haven't backed up the data before and it won't let me go back to a previous stable version.
Please describe your issue with details.
Add screenshot or other files if needed.

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
-
![SENZA FILTRO](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/40884dbd-f89b-4723-a0c5-6367e8152821)
- in the example is the bank but is the same result with: category, payee ... all data.
![FILTRO](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/e631d21b-2f3f-40a4-a17f-52d21797ecd9)
-
![FILTERED WRONG](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/6a31c6d9-fcae-4b12-846e-f3c2895ccf20)

Expected result:

Actual result:

# Additional information
The problem of the filter is sure related to SPLIT CATEGORY, were we have on the database the filter doesn't work fine. 

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
This is due to a change I made for tag filtering, I accidentally removed the check for non-split fields. Will fix tomorrow.

**Comment by tactilis** [comment]
@MAPA2023
> Unfortunately I haven't backed up the data before and it won't let me go back to a previous stable version.

When you first ran the 1.7 Beta, the database schema will have been updated from v17 to v18.

However, MMEX makes a copy of your pre-upgrade .mmb database file and names it:

*<database_name.mmb>*\_upgrade\_v18\_*\<yyyy-mm-dd>*.bak

To go back to 1.6.4, just copy this file and name it *database_name.mmb*

**Comment by MAPA2023** [comment]
Many thanks Team. @n-stein, do you think that for this weekend I can have an updated 1.7 version? I use mmex in the Aero Club where I fly as a hobby. The club member to worm I have introduced it to found it very effective. This is one of the reasons why I asked to aggregate a Payee to a transaction that includes two asset accounts (Bank to Advance Account)

**Comment by tactilis** [comment]
@MAPA2023
> do you think that for this weekend I can have an updated 1.7 version?

I just want provide a reminder that MMEX 1.7 is in-development and has not been released yet.

Each interim Beta build of 1.7 (of which there are many) is potentially subject to breakage at any time.

If you/your club member accept this risk and can sort out problems yourself if you encounter any, then the Beta builds for Windows are available here: https://ci.appveyor.com/project/whalley/moneymanagerex

The general guidance for any software is that Beta builds are **not recommended for important databases** and that keeping backups and being able to revert to a previous version is essential.

**Comment by MAPA2023** [comment]
> @MAPA2023
> 
> > do you think that for this weekend I can have an updated 1.7 version?
> 
> I just want provide a reminder that MMEX 1.7 is in-development and has not been released yet.
> 
> Each interim Beta build of 1.7 (of which there are many) is potentially subject to breakage at any time.
> 
> If you/your club member accept this risk and can sort out problems yourself if you encounter any, then the Beta builds for Windows are available here: https://ci.appveyor.com/project/whalley/moneymanagerex
> 
> The general guidance for any software is that Beta builds are **not recommended for important databases** and that keeping backups and being able to revert to a previous version is essential.

@n-stein 
Hi Stein,
I know perfectly well that Betas can have errors. In this specific case I have only omitted to make a copy. But it's not important, I know it's an imperfection that, as you said, you're going to correct on this version as well. Just notify me, if you can, when the bug is fixed so I can download the new beta. Thanks for everything.

**Comment by MAPA2023** [comment]
@n-stein Hi Stein, is this done?

**Comment by tactilis** [comment]
> Hi Stein, is this done?

It will not be officially 'done' until MMEX 1.7 is released.

If you want to test the latest 1.7 Beta, then you can get it as explained in my response above https://github.com/moneymanagerex/moneymanagerex/issues/6135#issuecomment-1647631016

**Comment by MAPA2023** [comment]
I know 1.7 is not official. I was wondering when a new version 1.7 will be updated so as to be able to test it and in any case update the small defect of the indexes which, as you said, has already been resolved.

**Comment by n-stein** [comment]
@MAPA2023 

Please try https://ci.appveyor.com/project/whalley/moneymanagerex/builds/47745630/job/t9ydhfc0kohpmocf/artifacts and check if the filtering is working as expected.

**Comment by MAPA2023** [comment]
@n-stein many thanks Stein you are a great man ! TY
