### ISSUE TITLE
MMEX 1.7 Beta 1 - High CPU & GPU usage when Edit Transaction and Transaction Filter dialogs are displayed

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#6141]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0 Beta 1

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I noticed that my laptop's cooling fan started running at high speed after I'd left MMEX 1.7 Beta 1 open for a while.

Task Manager shows that higher than expected CPU usage is occurring when the Edit Transaction dialog is being displayed (but with no user interaction).

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/cda8ce53-4819-4608-a245-ecbc49d620de)

<br>

Viewing the same transaction in 1.6.4 shows 0% CPU usage.
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/0ffbb657-f520-4919-be22-8340a716c7ba)

<br>

In 1.7 Beta 1, the GPU 3D usage also steps up from 0% to 10% when the Edit Transaction dialog is opened.
This does not happen in 1.6.4.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/f17864aa-38c8-4809-a6a3-5fbfee9285ea)

<br>

CPU and GPU usage drop to zero again when the Edit Transaction dialog is closed.

**Comment by tactilis** [comment]
Note that the step up in CPU and GPU usage also occurs in 1.7 Beta 1 when the Transaction Filter dialog is displayed.

The common factor between the Edit Transaction & Transaction Filter dialogs in 1.7 Beta 1 is the presence of the Tags field, which of course, does not exist in 1.6.4.

**Comment by renato-mmex** [comment]
I can confirm that 1 CPU kernel is fully utilized, GPU utilization is negligible for me as the graphics card is sufficiently powerful.

**Comment by n-stein** [comment]
The issue is the Bind to wxEVT_UPDATE_UI. If I remove this event binding it drops to 0 again. Will look for a different event for Enable/Disable handling.

**Comment by tactilis** [comment]
I notice that the wxEVT_UPDATE_UI class docs say:

>If you find that the overhead of UI update processing is affecting your application, you can do one or both of the following:
>
> -   Call wxUpdateUIEvent::SetMode with a value of wxUPDATE_UI_PROCESS_SPECIFIED, and set the extra style wxWS_EX_PROCESS_UI_UPDATES for every window that should receive update events. No other windows will receive update events.
> -    Call wxUpdateUIEvent::SetUpdateInterval with a millisecond value to set the delay between updates. You may need to call wxWindow::UpdateWindowUI at critical points, for example when a dialog is about to be shown, in case the user sees a slight delay before windows are updated.

Does reducing the update rate help?

https://docs.wxwidgets.org/3.0/classwx_update_u_i_event.html

**Comment by n-stein** [comment]
> Does reducing the update rate help?

Probably would, but that event binding isn't even necessary. I can just override the Enable function inherited from wxPanel. Not really sure why I didn't do it that way before...

**Comment by n-stein** [comment]
@tactilis this was fixed a while ago, please confirm & close.

**Comment by tactilis** [comment]
Fixed. MMEX no longer uses excessive CPU.
