### ISSUE TITLE
Rename Full Transactions Report to Account View: All Transactions

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#6143]
I recommend we change the panel title to "Account View: All Transactions" for consistency with other account views.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/50d832d7-47f2-41fc-8ceb-e66d8dc85050)

**Comment by tactilis** [comment]
I agree.

The current inconsistent naming `All Transactions` => `Full Transactions Report` has always bugged me as well.

**Comment by vomikan** [comment]
There are two more strings:
_("All Transactions: Withdrawals, Deposits, and Transfers"));
_("All Transactions excluding Transfers"));

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/transactions.cpp#L413

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/reports/transactions.cpp#L395

**Comment by tactilis** [comment]
> There are two more strings:
_("All Transactions: Withdrawals, Deposits, and Transfers"));
_("All Transactions excluding Transfers"));

Are they in Reports somewhere? How do you get to see them? 

<br> 
Rich and I are talking about the All Transactions entry in the Navigation tree, which produces a (filterable) all transactions list.

**Comment by ovari** [comment]
`All Transactions: Withdrawals, Deposits, and Transfers`
https://crowdin.com/translate/moneymanagerex/470/en-hu#797570

`All Transactions excluding Transfers`
https://crowdin.com/translate/moneymanagerex/470/en-hu#797572

**Comment by rmelillo76** [comment]
> `All Transactions: Withdrawals, Deposits, and Transfers`
> 
> https://crowdin.com/translate/moneymanagerex/470/en-hu#797570
> 
> 
> 
> `All Transactions excluding Transfers`
> 
> https://crowdin.com/translate/moneymanagerex/470/en-hu#797572
> 
> 

We should also remove the word "Report"

The thought was to have the title be "All Transactions"

**Comment by ovari** [comment]
@rmelillo76 is https://github.com/moneymanagerex/moneymanagerex/pull/6153/files#diff-63b4bc6b9e6dffe709948324f1c8375f7979cc30862f66769fd67fb4e0410b1f what you had in mind? Thank you

**Comment by rmelillo76** [comment]
> @rmelillo76 is https://github.com/moneymanagerex/moneymanagerex/pull/6153/files#diff-63b4bc6b9e6dffe709948324f1c8375f7979cc30862f66769fd67fb4e0410b1f what you had in mind? Thank you

That's it, thank you!

**Comment by ovari** [comment]
@vomikan can you please close this issue? Thank you
