### ISSUE TITLE
MMEX Options, Attachments: Button very narrow; section expanded to the bottom of the window

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6155]
1. Should the button label be something like `Browse…` with the width to be increased?
2. Should the inside section be expanded to the bottom of the window?

Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/c1ff17a6-3427-4fe7-a51c-5569ee1f758a)

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Aug 2 2023 03:26:50
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.15
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-78-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by tactilis** [comment]
For reference, on Windows, both the [...] button and the Attachment Settings panel are displayed correctly.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/3e79a451-80ee-4a7f-bf33-ea27607184e5)

**Comment by PMaff** [comment]
I can confirm this for compiled version 1.6.3 for Ubuntu bionic.

**Comment by n-stein** [comment]
@ovari @PMaff I see point 1 but I don't see any issue with the panel not extending to the bottom. Is that still an issue in the current beta?

**Comment by ovari** [comment]
@n-stein

Point 1 still valid
Point 2 no long valid

![MMEX Options, Attachments](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/8689615b-b0b0-4a44-bbf3-ffb928b1cdf6)

Unfortunately `Copy all text to clipboard` in About dialog not working
Linux Mint 21.3 Cinnamon

Thank you

**Comment by n-stein** [comment]
That fixes the button width.

**Comment by ovari** [comment]
Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b15c9af9-a736-4dc7-bbb2-1668358f241c)

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 2 2024 13:48:04
• Database version: 19 (aes128cbc)
• Git commit: 138dc6b58 (2024-03-02)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.2
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-97-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```
