### ISSUE TITLE
Ubuntu/Linux: Download of stable 1.6.4  from github seems to result in 1.6.4-Beta.8

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#6157]
MMEX version:
 - [X] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
git clone --recursive https://github.com/moneymanagerex/moneymanagerex -b v1.6.4
seems to download 1.6.4-Beta.8 and not stable version 1.6.4 .

I am using the normal way to download the stable 1.6.4 sources, described here:
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux

moneymanagerex$ mkdir build
moneymanagerex$ cd build/
moneymanagerex/build$ cmake ..
results in:
...
-- MMEX configuration summary
-- ==========================
-- Version        : 1.6.4-Beta.8
-- Commit         : dd6778439 (2023-06-20)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
...

This compiles a 1.6.4-Beta.8 then (no compilation/link problems).

Version information in mmex 1.6.3 says:
"Version | Status | Datum | Zeit
v1.6.4 | Stabil | 2023-06-21

Version	Status	Datum	Zeit
[v1.6.4](https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.6.4)	Stabil	2023-06-21"

so the tag 1.6.4 seems to point to one earlier beta version.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: 
git clone --recursive https://github.com/moneymanagerex/moneymanagerex -b v1.6.4
cmake

Expected result:
Version 1.6.4 is configured.

Actual result:

-- MMEX configuration summary
-- ==========================
-- Version        : 1.6.4-Beta.8
-- Commit         : dd6778439 (2023-06-20)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON

# Additional information

**Comment by PMaff** [comment]
Package generation also says:
CPack: - package: .../moneymanagerex/mmex_1.6.4-Beta.8-Ubuntu.18.04.bionic_amd64.deb generated.

**Comment by PMaff** [comment]
I also tested the downloadable stable version here: 
https://github.com/moneymanagerex/moneymanagerex/releases/
and this shows the stable 1.6.4, so it looks like as if only the tag in github is wrong.

**Comment by PMaff** [comment]
I think I found the mistake.

The tagged 1.6.4 commit is dd6778439, which gives 1.6.4-Beta.8 and not 1.6.4 .
If you scroll down at https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex you will find
https://github.com/moneymanagerex/moneymanagerex/commit/dd67784392b6a3fefd5ca8abb0e4e4c8c3e4a54c
which was tagged as 1.6.4 but a bit above there is
moneymanagerex 788 with
https://github.com/moneymanagerex/moneymanagerex/commit/6b4cc698fad728f9a4c2f4638b12a99aeaf37151
and a tiny change shown here:
https://github.com/moneymanagerex/moneymanagerex/commit/6b4cc698fad728f9a4c2f4638b12a99aeaf37151
;-)
set(MMEX_VERSION 1.6.4)
SET(MMEX_VERSION_ALPHA -1)
-SET(MMEX_VERSION_BETA 8)
+SET(MMEX_VERSION_BETA -1)
SET(MMEX_VERSION_RC -1)
in CMakeLists.txt 

git clone  --recursive https://github.com/moneymanagerex/moneymanagerex
cd moneymanagerex/
git log :
...
```
commit 6b4cc698fad728f9a4c2f4638b12a99aeaf37151
Author: Nikolay <nikolay.akimov@gmail.com>
Date:   Tue Jun 20 21:20:07 2023 +0300

    Update CMakeLists.txt
```

`git checkout 6b4cc698fad728f9a4c2f4638b12a99aeaf37151`
then gives :
-- MMEX configuration summary
-- ==========================
-- Version        : 1.6.4
-- Commit         : 6b4cc698f (2023-06-20)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON

;-)

This compiles ok on Suse Tumbleweed newest version.
About dialog says:
```
Money Manager Ex
• Version: 1.6.4 64-bit
• erstellt am: Aug 7 2023 17:47:43
• Datenbankversion: 18 (aes128cbc)
• Git-Eintrag: 6b4cc698f (2023-06-20)
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.0 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.4.6
• libcurl/8.2.1 OpenSSL/3.1.2 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.5/openssl/zlib nghttp2/1.55.1 OpenLDAP/2.6.4
• gettext 0.21.1
• apexcharts.js
erstellt mit:
• CMake 3.27.1
• GNU Make 4.4.1
• GCC 13.1.1 20230720 [revision 9aac37ab8a7b919a89c6d64bc7107a8436996e93]
Läuft auf:
• openSUSE.20230806
• openSUSE Tumbleweed "n/a"
• Linux 6.4.8-1-default x86_64
• English (United Kingdom) (UTF-8)
• 0x0 0bit 96x96ppi

```
So in fact 1.6.4-Beta.8 is the stable 1.6.4 with a wrong CMakeLists.txt . :-)

@vomikan will you move the tag or do we keep it with this explanation here?

**Comment by n-stein** [comment]
See also #6046.
