### ISSUE TITLE
Entry Account Name Invalid When Correcting Title Case

### ISSUE THREAD

**Issue by Ocirasai** [moneymanagerex/moneymanagerex#6158]
MMEX version:
 - [X] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I created a new account and noticed that I had entered one of the words in the account title with a lowercase letter (I prefer Initial caps on words in an account name). So I went to Accounts > Edit Account and selected the account to edit. I changed the case on the word in the Account tile and went to save, but instead got an Invalid entry Dialog Box with the error "Entry Account Name is invalid"

# Reproduction

Is the bug reproducible? 
 - [X] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Create a new account (any type), such as: "HFCU - Car loan 1" (Notice that the "l" in loan is lowercase).
2. save the new account
3. From the Accounts menu, select Edit Account and then pick this account.
4. Attempt to change the case on the "l" in Loan from lowercase to uppercase and then click OK.

Expected result:

The account name should be saved as this is a rename option and "l" and "L" are different characters.

Actual result:

<img width="283" alt="Invalid Account Error" src="https://github.com/moneymanagerex/moneymanagerex/assets/140843655/e8b828c8-4834-449a-9ce9-2db475402588">

# Additional information

The workaround for this is that I needed to change the title to something else temporarily and then edit it again to rename it as I intended with the correct case.

**Comment by n-stein** [comment]
The account name ignores case to avoid ambiguity, the same as many other text fields (payee, category, tags, stock names, etc).

`ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE`

We can allow this in the special case where you are editing an existing account name and the old and new names differ only by case.

**Comment by n-stein** [comment]
That simple change allows you to adjust the case of the account name. 

Note case insensitivity still applies when creating new accounts or changing account names to anything other than the current name (so you can't rename account 'B' to account 'a' if account 'A' already exists).

Give it a try.
