### ISSUE TITLE
.QIF import: special characters not handled

### ISSUE THREAD

**Issue by Skeletorjus** [moneymanagerex/moneymanagerex#616]
If a payee contains special characters (like æøå), it breaks the string at that character.

**Comment by apintocr** [comment]
Hello @Skeletorjus 
Try to open the .qif file on Notepad++ (or other text editor of your choice) and convert the encoding to UTF-8 (with BOM), this fixed the issue for me.

I would suggest to verify the encoding before starting the import and prompt the user to attempt to convert to UTF-8.

**Comment by Skeletorjus** [comment]
@apintocr 
Thank you, that did the trick! This boils down to some sort of user error, but I agree that a check should be in place since the workaround isn't necessarily obvious.
