### ISSUE TITLE
.QIF import: wrong amount used

### ISSUE THREAD

**Issue by Skeletorjus** [moneymanagerex/moneymanagerex#618]
When importing a QIF-file, some of the transfers between accounts operate with the wrong amount.
This of course messes up the balance in the account.
If I edit the transaction, the leftmost cell will show the correct value, while the right one shows a totally unrelated one. If i deselect "Advanced" (which for some reason is already ticked), the correct value will be used and everything is OK again.
Needless to say, this is a manual fix which is way too cumbersome when we're talking about hundreds of transactions :)
This might in some way be related to issue #408

**Comment by vomikan** [comment]
Sample QIF file will helpful.

**Comment by vomikan** [comment]
I've commit changes that should fix this issue.
https://github.com/moneymanagerex/moneymanagerex/commit/7f151c3969ce1080d3d93eb0ccee7b1703df32d4
