### ISSUE TITLE
Allow mutiple Payees delete at once

### ISSUE THREAD

**Issue by cecco** [moneymanagerex/moneymanagerex#6181]
# Description of the feature

Sometimes after a qif import I have to tidy up Payees. After that, i get a lot of unused Payees, so I would like to select them and delete them at once. 

I have made a small change request I would like to contribute

**Comment by vomikan** [comment]
Try using automatic replacement when importing.

https://github.com/moneymanagerex/moneymanagerex/issues/3148

**Comment by vomikan** [comment]
Not bad for a start. Welcome aboard.
But there is still something to work on. For example, add wxPLURAL(

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/2492d61f-c5da-4245-a1f9-1a576ecaaa21)

**Comment by tactilis** [comment]
> Also 'Payee in use'

@cecco Any Payees used in transactions should not be included in the list for removal.

Only payees that have no transactions should be capable of being removed, so the above error message should not be triggered.

At present, if you select a single payee that is used in transactions, then the option to Remove it is greyed out.
Multi-payee deletion should respect that rule; maybe by informing the user when they click Remove that only the payees that are not in use will be removed.

**Comment by vomikan** [comment]
It seems to me that it would be better to add one menu item:
Join.

Then the question is how to name the category as a result of the union.

This will solve the problem if some categories are already in use.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/13255b3b-1867-4591-a880-4e39d210bc8d)

**Comment by tactilis** [comment]
> This will solve the problem if some categories are already in use.

This is a discussion about deleting payees. Whether a Default Category is associated with a payee or not is irrelevant.

`Remove Category` simply removes the **_default_** category from the payee. It doesn't matter whether the category is in use or not.

**Comment by vomikan** [comment]
> 

Sorry, I made a mistake in the last message. Mixed up the words.

**Comment by cecco** [comment]
> > Also 'Payee in use'
> 
> @cecco Any Payees used in transactions should not be included in the list for removal.
> 
> Only payees that have no transactions should be capable of being removed, so the above error message should not be triggered.
> 
> At present, if you select a single payee that is used in transactions, then the option to Remove it is greyed out. Multi-payee deletion should respect that rule; maybe by informing the user when they click Remove that only the payees that are not in use will be removed.

Hi @tactilis I think I could change this error:

![](https://user-images.githubusercontent.com/6836805/261854060-08bc6bd8-b253-4ef8-ad14-bb86fbc69422.png)

adding which (first) Payee is in use and can't be deleted.

Otherwise I have found out that if the Focused item (between the selected ones) is one used in transactions the option to Remove it is greyed out, else the option is enabled even if one of the selected item is used. I can change this behaviour by enabling the Remove item only if all of the selected items aren't used in transactions. 

Which one is preferable?

**Comment by tactilis** [comment]
Remove should be available if some (or all) of the payees are not used.

On clicking Remove, a warning should be given saying that some of the selected payees are in use so will not be removed. Then you remove the ones that are unused, leaving the in use ones untouched.

**Comment by cecco** [comment]
I made this pull request
https://github.com/moneymanagerex/moneymanagerex/pull/6188

**Comment by vomikan** [comment]
> I made this pull request

Jast put in a header of your PR
fix(#6188): change behaviour when multiple items deleted

**Comment by n-stein** [comment]
Reading over this I don't see any outstanding items. Closing.
