### ISSUE TITLE
Merge payees

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6182]
After merge the UI should be refreshed

For example/ I merger test1 payee with test.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/3511d721-cfaf-4534-bce3-806afea75367)

And the warning message should be appears immidiatly after merge not the dialog closed

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/72e66287-11cb-4894-80b4-7914c19ece9a)

**Comment by whalley** [comment]
The combobox does get refreshed if the 'Delete source payee after merge' is selected, there seems no need to update if the payee is still available.

**Comment by whalley** [comment]
@vomikan Can we close this, or is there still an issue?
