### ISSUE TITLE
Tags Filtering

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6183]
I've created the transaction with tag "test".
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/4a46e0f6-1643-4d5f-8616-7d5ce26a111b)

But I can find it using Transaction Fileter.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/5b97b478-20a3-4210-bc49-1cb63dd9c5bf)

https://github.com/moneymanagerex/moneymanagerex/issues/5439

[test5924 (2).zip](https://github.com/moneymanagerex/moneymanagerex/files/12388003/test5924.2.zip)

**Comment by rmelillo76** [comment]
Hi @vomikan, this works for me:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/f551587d-01be-4e62-86fe-ef526e3ca1fb)

Here's the version I'm using:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/5b767799-a566-4fd0-b6a5-66fbc2ffe8c4)

**Comment by vomikan** [comment]
After a short time (I practically did not change anything, except for the language settings) it began to work.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/0414da1c-381e-4f67-90dc-df9a0a260515)

But in Russian, the label looks strange.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/f90382bc-18a0-496a-b013-6c30a646e144)

**Comment by rmelillo76** [comment]
> 
> 
> But in Russian, the label looks strange.
> 
> ![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/5beac021-8988-4286-8233-6a52cef4d008)
> 
> 

I wonder if '1' is the TAGID from the database. Can you create another tag and see if it shows as '2' in Russian? (Or next assigned TAGID from TAGS_V1)

**Comment by vomikan** [comment]
> I wonder if '1' is the TAGID from the database.

Sure. Anaway it's a bug.
