### ISSUE TITLE
Increase Spacing Between Categories & Subcategories

### ISSUE THREAD

**Issue by Ocirasai** [moneymanagerex/moneymanagerex#6189]
I'm on a 4K monitor which is great for seeing lots of information all at once, but tough when the text is smaller.

While working with categories and subcategories in my registers, it is difficult to see the colon in-between to distinguish the two.

Here is an example of what I am requesting:

<img width="365" alt="Categories" src="https://github.com/moneymanagerex/moneymanagerex/assets/140843655/cc05cc99-6e35-46b1-bf5a-33c823597fd3">

In the graphic above, the first group of categories is the way the program displays them.

About halfway through is what I would like to see as this more easily distinguishes that there is a category and a subcategory.

The way I have been able to work around it is to add a space after my Category manually and then a space before my Subcategory in the Organize Categories area.

I'm concerned, though, that this might break the program at some point.

What would be preferable would be to have the spacing as shown above handled automatically so I can still enter the Categories and Subcategories the correct way (with no additional spacing), or better yet, a separate Subcategory field.

In some financial applications, I've seen this displayed as an option to display either Category and subcategory as two separate fields, or as a combined, single field.

Thank you.

**Comment by tactilis** [comment]
In Options | View change the Category delimiter.

The preset options in the dropdown are:

colon
colon space
space colon space

This just affects the display of the nested categories, this you can have:

category : subcategory : subcategory

It is also possible to type your own delimiter characters in that field but I would advise sticking with the presets. 

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/bf66250a-c4ee-47c9-87aa-3f35b082c72d)


Once you have set the above, you should undo your workaround.

**Comment by renato-mmex** [comment]
Note that the changes are applied only after restarting MMEX.  (Bug ??)

**Comment by tactilis** [comment]
> Note that the changes are applied only after restarting MMEX. (Bug ??)

No, not a bug. Just a feature of the current implementation.

I've got a long-standing task to try to work out which options need or don't need a restart: https://github.com/moneymanagerex/moneymanagerex/issues/3011#issuecomment-1325021044

It's low on the priority list though, and keeps getting pushed down by other things.

**Comment by Ocirasai** [comment]
Very nice - This did exactly what I needed - Thank you :)
