### ISSUE TITLE
Money Manager EX Crashes when trying to delete a transaction from a Credit Card Account

### ISSUE THREAD

**Issue by MyronAG** [moneymanagerex/moneymanagerex#6190]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by MyronAG** [comment]
![Screenshot 2023-08-23 181303](https://github.com/moneymanagerex/moneymanagerex/assets/134319513/9f8b173f-6e7b-4739-b42e-ed04f46905cf)

**Comment by renato-mmex** [comment]
for error clarification the .ZIP file is needed.

**Comment by whalley** [comment]
Closing as no further information supplied by originator
