### ISSUE TITLE
Budget Setup not working as expected

### ISSUE THREAD

**Issue by Dorusto** [moneymanagerex/moneymanagerex#6191]
MMEX version:
 - [x] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
<img width="899" alt="Screenshot 2023-08-24 120531" src="https://github.com/moneymanagerex/moneymanagerex/assets/19708912/ceb366f7-0e06-4370-af4c-fb11e7d38dce">

 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I add the month in budget editor for example 2023-02 it is synchronized with August transactions.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Create a transaction in august current year. Add month in budget month entry for example year 2023 and budget month 02. Now you will see the actual transaction made in august in here. If you create 2023 and month 8 the August transactions are not there. 

Expected result:

I expect the selected month 8 in the budget editor to be synchronized with transaction made in August.

Actual result:

The selected month 2 in the budget editor is synchronized with the transactions made in August.

# Additional information

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/discussions/6192

**Comment by Dorusto** [comment]
Apparently this portable mmex found on this [post](https://github.com/moneymanagerex/moneymanagerex/issues/6040#issuecomment-1603976222) fix my problem also! Thanks!
