### ISSUE TITLE
Program crash if I cancel the asset transaction requirement.

### ISSUE THREAD

**Issue by Dorusto** [moneymanagerex/moneymanagerex#6193]
MMEX version:
 - [x] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

When I create new asset I get the notification that the "asset account not found". After I'm creating new one and edit the account, new popup appears to add asset transaction. If I don't want to add new transaction and I press cancel the program crash.

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

**Comment by n-stein** [comment]
I think this is the same issue as #6089 which has already been fixed.

**Comment by Dorusto** [comment]
Oh, ok, then I will close this! Thank you!
