### ISSUE TITLE
Bug: Last used date not working

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#620]
If in Tools, Options, Others, Default date = last used, when we add another operation the date shown is the current date not the last used date.

**Comment by guanlisheng** [comment]
@stef145g would you mind to have a check here?

**Comment by stef145g** [comment]
It appears this only occurs when an account has a single entry. Investigating further...

**Comment by stef145g** [comment]
Last date of a transfer transaction in a B side account was not being recognised. A fix has been provided and pull requests generated.
