### ISSUE TITLE
New/Edit Scheduled Transaction: Set Focus on Amount should select its value

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#6200]
Currently, when clicking into, or pressing `TAB`or `SHIFT-TAB` to set focus into the Amount field, the cursor is placed at the end:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/94f96fdb-adb0-4dfd-95e2-a19a94f4da5c)

We should change the focus behavior of the control so that the entire field's contents are selected. It works that way with all other fields on the dialog (except Notes).

For reference, the Amount field on the New/Edit Transaction dialog already does this:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/c134730e-a75d-4a61-af26-fb43f7d56beb)

This makes it more convenient to change the amount without having to use additional keystroke or use the mouse to type over.

**Comment by tactilis** [comment]
Agreed. The Transaction Details panel of the Recurring Transaction dialog should operate identically to the normal New/Edit Transaction dialog.

There is an existing issue https://github.com/moneymanagerex/moneymanagerex/issues/4775 whose aim is to unify the implementation of the related transaction dialogs.

**Comment by whalley** [comment]
@rmelillo76 Is this OK now, can we close?

**Comment by rmelillo76** [comment]
> @rmelillo76 Is this OK now, can we close?

Yes looks good, thanks!
