### ISSUE TITLE
Autosort doesn't work on Payee's if search starts with a number

### ISSUE THREAD

**Issue by user8446** [moneymanagerex/moneymanagerex#6201]
MMEX version: v.1.5.21 (Stuck on this version due to the need for MMEX for Android but I looked through the changelogs for subsequent releases and did not see this issue)

Operating System:
 - [x] Windows

When adding a new transaction and clicking the down arrow in the Payee box to bring up the list of Payee's, you can sort the list by typing your desired payee. This works for letters but if you start with numbers the list does not sort as expected.

Is the bug reproducible? 
 - [x] Always 

Thank you

**Comment by tactilis** [comment]
> Is the bug reproducible?

It works correctly in MMEX 1.6.4

**Comment by vomikan** [comment]
I can't reproduce this issue 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/700e334a-525f-4ecf-a3f8-19e591cfd3b6)

**Comment by user8446** [comment]
Hi, 

To recreate  save a test Payee: "Bistro 212".

When searching for "212" either from the Payee search box or by clicking the down arrow in the Payee search box to bring up the whole list and then "212" the list does not filter.

**Comment by tactilis** [comment]
> To recreate save a test Payee: "Bistro 212".
> When searching for "212" from the Payee search box the list does not filter.

It does in MMEX 1.6.4

> or by clicking the down arrow in the Payee search box to bring up the whole list and then "212" the list does not filter.

Correct. The list filtering is anchored at the beginning of the payee name. So entering 'B' will give you Bistro 212 but '212' will not.

In MMEX 1.6.4 you can press Enter in the empty Payee field, which will bring up the Organize Payees dialog. Enter '212' there and select from the filtered list.

But obviously, if you need to stay with MMEX 1.5.21 then you won't be able to make use of any updates, of which there have been many.

**Comment by user8446** [comment]
So the expected behavior is to only sort from the beginning of the payee name regardless if there is more than one word in it?

**Comment by tactilis** [comment]
> So the expected behavior is to only sort from the beginning of the payee name regardless if there is more than one word in it?

Yes. Currently that is the expected behaviour. This is not a bug.
 
<br>
 
But note that it's _filtering_, not _sorting_. The payees are always _sorted_ alpha-numerically.

The filtering of the list in the Payee dropdown is anchored at the beginning of the string of characters. Spaces are just characters like any other, so there is no concept of "more than one word".

There is a discussion in another issue about sub-string filtering of categories. Depending on how that is resolved it may be applied to payees in due course but you'll need to upgrade to the latest release of MMEX.

**Comment by user8446** [comment]
Ok I'm closing it. Thank you very much for explaining how MMEX does it's filtering.

**Comment by whalley** [comment]
> There is a discussion in another issue about sub-string filtering of categories. Depending on how that is resolved it may be applied to payees in due course but you'll need to upgrade to the latest release of MMEX.

Or move to MacOS where it does do filtering in the way @user8446 wanted 😃

**Comment by user8446** [comment]
Ha no apple devices, I'm on Windows & Ubuntu 😃

I figured it's not even worth a feature request because it would be low priority anyway compared to bug fixes and other higher priority items.

**Comment by tactilis** [comment]
> I figured it's not even worth a feature request

It is already requested.

Platform differences in behaviour either need to be resolved by wxWidgets or have replacement OS-specific event handlers written for MMEX.

**Comment by user8446** [comment]
Understood, thank you!
