### ISSUE TITLE
Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" in version 1.7.0 beta.1

### ISSUE THREAD

**Issue by franci207** [moneymanagerex/moneymanagerex#6203]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I click "Refresh Stock Prices from Yahoo" in Stock Portfolio view
I get the error "url using bad/illegal format or missing url

# Reproduction
click "Refresh Stock Prices from Yahoo" in Stock Portfolio view
Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
Stock prices are updated
Actual result:

# Additional information
above Error, no stock price updated
![247915548-37d6216e-2ad1-48c5-9ac2-075d69f82a1a](https://github.com/moneymanagerex/moneymanagerex/assets/141711848/fb0ea0f0-62a5-42c5-92e2-720bcb4aa0f9)

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6203
https://github.com/moneymanagerex/moneymanagerex/issues/6049
