### ISSUE TITLE
Latest docker image?

### ISSUE THREAD

**Issue by adamchap1** [moneymanagerex/moneymanagerex#6205]
Been looking for a docker image of MMex to drop into Container Manager on my Synology NAS so that I can use MMex from any browser (including on my Android due to lack of native app anymore).

However, the last image on docker hub is from 6 years ago and can't be pulled. Anyone got plans to update this to latest, maintain it, or somewhere else I can find it? (And no, the web app is not the answer, I want full access, on the move).

Thanks!

**Comment by whalley** [comment]
These are used for the Linux builds...

https://hub.docker.com/repository/docker/whall3y/mmex/general
