### ISSUE TITLE
google Adsense

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6207]
Lishng wrote to me:
Just wanted to check whether you would help to make https://moneymanagerex.org/ads.txt abatable to return the content as attached (one line in total). Just to comply some google Adsense

[ads.txt](https://github.com/moneymanagerex/moneymanagerex/files/12659034/ads.txt)

@whalley Could you assist?

**Comment by whalley** [comment]
Done.
