### ISSUE TITLE
when closing MMEX file is mention as "DESKTOP-UB0NQQB_sep-25-070038-2023_Conflict.emb_update_2023-09-25

### ISSUE THREAD

**Issue by Osty01** [moneymanagerex/moneymanagerex#6208]
MMEX version:
 - [x] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
when closing the file is written as DESKTOP-UB0NQQB_sep-25-070038-2023_Conflict.emb_update_2023-09-25

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by Osty01** [comment]
I have this issue on several different computers and laptop

**Comment by vomikan** [comment]
Probably, you are running several applications in parallel on different computers and you have synced one mmb file via Dropbox or a similar application.
