### ISSUE TITLE
Transaction Report crashes if category starts with `+`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6212]
# Description of the bug

`Transaction Report` crashes if selecting a category which starts with `+`

# Reproduction

1. 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/05df4ea2-ee77-4efe-868c-7fd21c61e796)
2. 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b04c51db-752f-4319-b32d-7950252e88c0)
3.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/60d7e6f3-5116-44db-8089-3597d79e73ba)
4.
[mmex_dbgrpt-8257-20230929T065235.zip](https://github.com/moneymanagerex/moneymanagerex/files/12753863/mmex_dbgrpt-8257-20230929T065235.zip)

Is the bug reproducible? Always

Expected result:

Able to have Transaction Reports that have categories that start with `+1 Income` and `-1 Expense`

Actual result:

Invalid regular expression '+Automobile': quantifier does not follow a repeatable item

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Sep 28 2023 03:27:38
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-84-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by n-stein** [comment]
@ovari what steps are you using that result in a crash? 

I get the error popup but closing it just leaves me back on the Filter Transactions dialog. Clicking "OK" pops up the warning again. Clicking "Cancel" closes the dialog normally.

I made a small change which should fix the issue. Note you will still see this error message if you attempt to filter on `+Automobile` without first defining that category in `Organize Categories` as the system attempts to interpret it as regex when the entry is not a valid category name.

**Comment by ovari** [comment]
Thank you, verified fixed with:

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Oct 6 2023 03:27:03
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-86-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```
