### ISSUE TITLE
Save and allow multiple `Transaction Reports`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6213]
# Description of the feature

1. Enable multiple `Transaction Reports` be listed under the `Transaction Reports` (as they are saved)
2. Rename `Transaction Report` to `Transaction Reports` (singular to plural) as there can be multiple reports

# Use cases

This would enable clicking on a memorized transaction report to see the report based on a filter. It would enable toggling between transaction reports.

What do you think?

Thank you

**Comment by whalley** [comment]
> # Description of the feature
> 1. Enable multiple `Transaction Reports` be listed under the `Transaction Reports` (as they are saved)

Isn't this already there? Or are you asking for something else?

![CleanShot 2023-09-28 at 22 15 51@2x](https://github.com/moneymanagerex/moneymanagerex/assets/487345/7dff1b79-61e4-427e-a64c-d613b2617301)

**Comment by ovari** [comment]
> Isn't this already there? Or are you asking for something else?

Yes, that is what is being asked.  How did you do that?

**Comment by whalley** [comment]
Just save some reports and expand the Transaction Report on the tree view using the small arrow.

**Comment by ovari** [comment]
Where is the `Save` button/option?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/5b5ac0ec-80a0-44e1-b8c3-012f70814873)

**Comment by whalley** [comment]
![CleanShot 2023-09-28 at 23 39 12](https://github.com/moneymanagerex/moneymanagerex/assets/487345/8922a0a2-d22a-48d1-97fb-3fa7363fae40)

**Comment by ovari** [comment]
Thank you
