### ISSUE TITLE
Add `Transaction Report...` to contextual menu when clicking on transaction 

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6215]
1. Please add `Transaction Report…`/`Find` option to contextual menu (right mouse click) of a transaction
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/9ec30986-2545-4074-b762-0bb0ff913faa)
2. If the right-click is in the `Payee` field, the `Transaction Report…` automatically fills the Payee with the payee that was clicked on.
![ContextMenu](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/277902cf-bb54-4c6f-aeb8-6f7ce3c0c3b0)

Thank you

**Comment by rmelillo76** [comment]
I had requested something similar in [4232]()

**Comment by n-stein** [comment]
Perhaps a simple `Find` menu like this? 

![mmex_T6fI07qsX3](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/ad032bb6-0d03-4e0b-b198-0ac60dc7292e)

The `Payee` option would be hidden if the selected item is a transfer, `Tags` would be hidden if there are no tags, and both the `Category` and `Tags` options would be hidden if the item is a split transaction. The `Find` submenu would be shown only if a single transaction is selected.

**Comment by n-stein** [comment]
Wondering if this should be "Find" or "View" or something else?

**Comment by n-stein** [comment]
@ovari I made a change under #4232. You can right click anywhere in the panel and you will get an option to "Find all transactions with ..." whatever cell you clicked on. This jumps you to the "All Transactions" view with the corresponding filter applied.

Does that fulfill your request here, or are you looking for a way to launch a true "Transaction Report"?

**Comment by ovari** [comment]
Thank you @n-stein for your improvements.

1. Right-clicking on `Tags` where no tag is set, should there be a menu item such as `Find all transactions with no tags`?
2. Doing a Find and then doing another Find replaces the first find. Can there please be 2 (or more) finds shown in the Navigation side panel?
3. If there are multiple tags, say `tag1` and `tag2`, right-clicking on `tag2` shows menu `Find all transactions with Tags 'tag1 tag2'`. If possible, should **another** menu item be added such as `Find all transactions with Tags 'tag2'`?

Thank you

**Comment by ovari** [comment]
> Wondering if this should be "Find" or "View" or something else?

Terminology used in Quicken:
1. Right-clicking on Payee for a transaction with an outflow of funds `Payments made to PAYEE_NAME`
2. Right-clicking on Category for a transaction with an outflow of funds `Amount spent in CATEGORY_NAME`
3. Right-clicking on Payee for a transaction with an inflow of funds `Payments received from PAYEE_NAME`
4. Right-clicking on Category for a transaction with an inflow of funds `Amount received in CATEGORY_NAME`

Even thought Quicken says `Amount spent in …` and `Amount received in …`, the report finds all transactions whether they are inflows or outflows. 

> Does that fulfill your request here, or are you looking for a way to launch a true "Transaction Report"?

Looking for a quick way to create a `Transaction Report` (`Payee Report`, `Category Report`) that shows `Total inflows`, `Total outflows` and `Net total`.

Thank you

**Comment by rmelillo76** [comment]
> 1. Right-clicking on `Tags` where no tag is set, should there be a menu item such as `Find all transactions with no tags`?

Hi @ovari, this idea starts to introduce unnecessary scope from the original goal. It may not even be possible, because the Transaction Filter (which is being leveraged) does not allow one to try to filter on the Tags field yet leave it blank.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/585fc82e-e306-4288-b5b8-32797a992985)

**Comment by ovari** [comment]
Closing as fixed. Thank you
