### ISSUE TITLE
Error opening database

### ISSUE THREAD

**Issue by andreacarraro75** [moneymanagerex/moneymanagerex#6217]
MMEX version:
 - [x ] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I'm not able to open databse created with old version of sw (mmex-1.6.0-win32) with new version (mmex-1.6.5-win64). See attachment for error.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.
![Cattura](https://github.com/moneymanagerex/moneymanagerex/assets/146461015/0f6ffe50-bdf6-40af-95ac-39880f318ad6)

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/5568
