### ISSUE TITLE
Splits with tranfers

### ISSUE THREAD

**Issue by ricardoglezf87** [moneymanagerex/moneymanagerex#6218]
# Description of the feature

I think it is necessary to be able to make transfers when dividing movements. There are certain situations that are very difficult to control through categories.

# Use cases

The most typical use case is loan payment which is divided into principal and interest.
In particular, I have the case that with my payroll the doctor's insurance is paid and the per diem card is recharged in the same document.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/1396
