### ISSUE TITLE
New feature: copy (CTRL+C) + paste in Excel in Account view

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#622]
It would be nice to be able to select several operations in the account view, copy them easily with CTRL+C and paste them in Excel, with the header column being the title of the column.

**Comment by guanlisheng** [comment]
@siena123 help to take a look?
wxTheClipboard from the following link may help here
http://docs.wxwidgets.org/3.0/classwx_clipboard.html

**Comment by siena123** [comment]
That looks like it will work but also need to change the view to multi select instead of single select control / view. I will work on make some changes to support this.

**Comment by aquirin** [comment]
That's great thank you!

**Comment by siena123** [comment]
Pull Request submitted. The account panel showed since of being a multi-select control at one time.
