### ISSUE TITLE
Upgrade from 1.6.3 on Mac OS

### ISSUE THREAD

**Issue by OlivierG56** [moneymanagerex/moneymanagerex#6222]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [x] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by OlivierG56** [comment]
Upgrade to version 17 has failed. The same error keep on coming evens I tried to restart with previous version and DB.

<img width="305" alt="Capture d’écran 2023-10-03 à 11 16 18" src="https://github.com/moneymanagerex/moneymanagerex/assets/146826332/b37aa5f9-9abf-4380-8ab5-7447083b6162">

**Comment by OlivierG56** [comment]
Closed by mistake. Thanks.

**Comment by renato-mmex** [comment]
Maybe this will help: https://github.com/moneymanagerex/moneymanagerex/issues/5378

**Comment by OlivierG56** [comment]
Thanks Renato,

I am a basic user so could you help me a bit more. How do I run those scripts ?

Many thanks
Olivier

De : Renato ***@***.***>
Date : mardi, 3 octobre 2023 à 12:08
À : moneymanagerex/moneymanagerex ***@***.***>
Cc : OlivierG56 ***@***.***>, State change ***@***.***>
Objet : Re: [moneymanagerex/moneymanagerex] Upgrade from 1.6.3 on Mac OS (Issue #6222)

Maybe this will help: #5378<https://github.com/moneymanagerex/moneymanagerex/issues/5378>

**Comment by renato-mmex** [comment]
Hi @OlivierG56 
You can send the   .mmb   to mmex-reg@bluewin.ch and I will take care of it.
Of course I guarantee full confidentiality of the data.
Greetings Renato (Admin of the MMEX Forum)

**Comment by n-stein** [comment]
@OlivierG56 Your database has a view called `cumulative` that is unsupported in MMEX. Do you use this view for custom reports? If not it can be easily removed, otherwise it will need to be updated to align to the correct database structure.

**Comment by OlivierG56** [comment]
Many thanks.
I was using it but could probably do without if too complex to be updated.
Kind regards
Olivier


De : n-stein ***@***.***>
Date : mercredi, 4 octobre 2023 à 14:32
À : moneymanagerex/moneymanagerex ***@***.***>
Cc : OlivierG56 ***@***.***>, Mention ***@***.***>
Objet : Re: [moneymanagerex/moneymanagerex] Upgrade from 1.6.3 on Mac OS (Issue #6222)

@OlivierG56<https://github.com/OlivierG56> Your database has a view called cumulative that is unsupported in MMEX. Do you use this view for custom reports? If not it can be easily removed, otherwise it will need to be updated to align to the correct database structure.

**Comment by n-stein** [comment]
Check out https://github.com/moneymanagerex/moneymanagerex/issues/6056#issuecomment-1610361653. I posted instructions on how to recreate the allData table to fix the cumulative view. 

When you attempt to open your database and it asks if MMEX has provided a debug file, just select the recreate_allData.mmdbg file (from recreate_allData.zip in #6056), then retry the upgrade.

**Comment by OlivierG56** [comment]
Hi n-stein,
I had done this and just tried again but I got the same message “MMEX database upgrade to version 17 failed!”
Thanks for your help
Olivier

De : n-stein ***@***.***>
Date : mercredi, 4 octobre 2023 à 14:46
À : moneymanagerex/moneymanagerex ***@***.***>
Cc : OlivierG56 ***@***.***>, Mention ***@***.***>
Objet : Re: [moneymanagerex/moneymanagerex] Upgrade from 1.6.3 on Mac OS (Issue #6222)

Check out #6056 (comment)<https://github.com/moneymanagerex/moneymanagerex/issues/6056#issuecomment-1610361653>. I posted instructions on how to recreate the allData table to fix the cumulative view.

When you attempt to open your database and it asks if MMEX has provided a debug file, just select the recreate_allData.mmdbg file (from recreate_allData.zip in #6056<https://github.com/moneymanagerex/moneymanagerex/issues/6056>), then retry the upgrade.

**Comment by renato-mmex** [comment]
The two databases have the following views, probably you need to delete all of them for the upgrade to work.

<img width="143" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/2ef6fcc0-a6a9-4633-969e-7a752d1d2012">
<img width="113" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/d018e04f-876d-4945-9bfd-3c8fde82a7c6">

**Comment by renato-mmex** [comment]
I have deleted the views and successfully migrated both DB to 1.6.4. Send you back the corrected DBs.

**Comment by renato-mmex** [comment]
Unfortunately I can't help with the Excel problem because I don't have MAC.
Probably there are  ODBC problems with the MAC

For Windows: https://forum.moneymanagerex.org/viewtopic.php?f=10&t=9549&p=20427&hilit=odbc#p20427
