### ISSUE TITLE
Помилка при другому вході

### ISSUE THREAD

**Issue by Sergiy-88** [moneymanagerex/moneymanagerex#6228]
Після першого запуску програму зберіг файл. І знову ж хотів зайти для подальшої роботи в ньому, але видало таку помилку.

![Новий Точковий рисунок](https://github.com/moneymanagerex/moneymanagerex/assets/147140564/9b29f400-8870-4c22-822e-db150ba647e4)

**Comment by Sergiy-88** [comment]
Що робити щоб програма працювала?

**Comment by renato-mmex** [comment]
translated with www.deepl.com
After the first launch of the program, I saved the file. And again I wanted to open it to continue working in it, but the following error was displayed.
What should I do to make the program work?
.
.
probably there was an error message before this message, please make a screenshot of it
Вероятно, перед этим сообщением уже было сообщение об ошибке, сделайте, пожалуйста, его скриншот
