### ISSUE TITLE
Export Transaction Report as CSV File

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6231]
Right-clicking on an account in the Navigation sidebar shows an option to Export as CSV File.

Can an option please be added to the right-click (contextual) menu of a Transaction Report to enable exporting a report as a CSV file?

Thank you

**Comment by vomikan** [comment]
I recommend
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/3a84f4c1-fc9e-44ea-8808-a881dcd212c4)

then open the saved file in Excel

**Comment by rmelillo76** [comment]
To add to @vomikan's suggestion, you can also select the contents of the report, then open Excel and either Paste or Paste Special. Paste Special will eliminate the HTML and some formatting, you would then just need to delete any unwanted information and blank rows:

Select All) `(CTRL/CMD+A)`. then Copy (`CTRL/CMD+C`)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/a841348b-55af-4369-847b-88511fd7412d)

Then Paste:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/1df2fab5-c660-4e69-ad10-56ef8eebaea5)

Or "Paste Special"

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/6e02cc35-ca8e-478d-b965-bdd84b58d769)

**Comment by ovari** [comment]
Thank you for your workaround. The only spreadsheet program available here is [LibreOffice](https://www.libreoffice.org/) [Calc](https://www.libreoffice.org/discover/calc/) and the solutions provided work. Thank you both once again.

**Comment by vomikan** [comment]
There is one more solution like this:

https://forum.moneymanagerex.org/viewtopic.php?p=20427&hilit=odbc#p20427
