### ISSUE TITLE
Provide guidance on how to debug

### ISSUE THREAD

**Issue by otmarjr** [moneymanagerex/moneymanagerex#6237]
# Description of the feature

Hello. I'm new to OSS and C++ and I want to implement some new features in MMEX, specially some local mortgage rules. I've succesfully built it on my Ubuntu 22.04 and WSL2 environment, but I'm struggling to debug it.

I'm using VS Code and VCPKG. I've already tried CMAKE_BUILD_TYPE=Debug and also RelWithDebInfo and no luck trying to debug. When running from VS Code the breakpoints I've set are greyed out and display the message "Module containing this breakpoint has not yet loaded or the breakpoint adderess could not be obtained".

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110718/b2089718-7cc6-43ef-bdfc-01f0677890fd)

Trying to dig a little deeper, I tried to debug it using gdb directly by running gdb	~/projects/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.6.4-Beta.8-Linux/usr/bin/mmex after building it with  cmake --build .. --target package 

After that gdb starts by saying there's no symbols in the package:

Reading symbols from /home/otmar/projects/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.6.4-Beta.8-Linux/usr/bin/mmex...
(No debugging symbols found in /home/otmar/projects/moneymanagerex/_CPack_Packages/Linux/DEB/mmex-1.6.4-Beta.8-Linux/usr/bin/mmex)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110718/1481e63d-ad97-42d5-85c9-0a3d507c02d7)

I guess the fact gdb cannot find any symbols is related to the disabled breakpoints on VS Code GUI.

Any ideas on how to debug it? What am I missing?

Regards,
Otmar

**Comment by n-stein** [comment]
On my Linux box I develop and debug using Code::Blocks, but I will install VS Code and see if I can get it working.

Just curious since you mentioned WSL2, is there a reason you aren't developing directly on Windows?

**Comment by otmarjr** [comment]
> On my Linux box I develop and debug using Code::Blocks (which is super simple because CMake can automatically generate Code::Blocks projects), but I will install VS Code and see if I can get it working.
> 
> Just curious since you mentioned WSL2, is there a reason you aren't developing directly on Windows?

Well, I had faced some issues to build it, and because I had to skip the 6th step and adapt some parameters to be able to build it in Windows, I could not find any resources on how to overcome these 3 errors when I try to run it from Visual Studio 2022:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110718/e4bb8e0d-69fc-47d9-a3ff-f6683ba0d18a)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110718/b1209e2e-e28c-4cc5-b333-7e6024be6c9f)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110718/35056d20-13ec-4dda-984e-dad31cc63fc2)


These message are saying that those wx...dll files could be found, but I've previosly managed to successfuly build the mmex.sln generated by the cmake build instructions.

**Comment by n-stein** [comment]
> These message are saying that those wx...dll files could be found, but I've previosly managed to successfuly build the mmex.sln generated by the cmake build instructions.

The likely issue is that while Visual Studio knows where the wxWidgets dll files are to build the debug solution, but didn't actually copy them to the bin folder so when MMEX.exe runs it can't find them. 

Try this: Go to your wxWidgets lib folder,  find all of the debug dll files (the ones starting with `wxmsw317ud_` or `wxbase317ud_`), and copy them to the moneymanagerex/build/install/bin folder.

**Comment by n-stein** [comment]
Also, current builds use wxWidgets 3.2.1 and we are currently testing 3.2.3 as part of #5989, so please use the newer versions for development so you aren't chasing wxWidgets bugs from the old 3.1.7 release.

**Comment by otmarjr** [comment]
> > These message are saying that those wx...dll files could be found, but I've previosly managed to successfuly build the mmex.sln generated by the cmake build instructions.
> 
> The likely issue is that while Visual Studio knows where the wxWidgets dll files are to build the debug solution, it did not actually copy them to the bin folder so when MMEX.exe runs it can't find them.
> 
> Try this: Go to your wxWidgets lib folder, find all of the debug dll files (the ones starting with `wxmsw317ud_` or `wxbase317ud_`), and copy them to the moneymanagerex/build/install/bin folder.

Thank you very much, it finally worked. I may be doing something silly to only manage to build and debug running as administrator, but I may deal with it later.

Another question: do you have any strategy for regression testing ? I could not find any kind of automated tests in the source code, but maybe it's my ignorance.

**Comment by n-stein** [comment]
> I may be doing something silly to only manage to build and debug running as administrator

Sounds like a permission issue on your build folder. May be a silly question, but is your project stored/built in a privileged folder such as a subdirectory of `C:\Program Files`? 

> do you have any strategy for regression testing ? I could not find any kind of automated tests in the source code, but maybe it's my ignorance.

We have no automated tests, this is one area we are definitely lacking. Regression testing is a manual effort by the developer while implementing the changes, then by a wider team once the PR is opened and beta builds are created. If you have the skill and a desire to build some automated tests during your development, I'm sure the team would welcome the addition.

**Comment by otmarjr** [comment]
> Sounds like a permission issue on your build folder. May be a silly question, but is your project stored/built in a privileged folder such as a subdirectory of `C:\Program Files`?

Oh yeah, I just followed the instructions to for building in windows and it ended up there in program files. I'll take a look at this in the future

> We have no automated tests, this is one area we are definitely lacking. Regression testing is a manual effort by the developer while implementing the changes, then by a wider team once the PR is opened and beta builds are created. If you have the skill and a desire to build some automated tests during your development, I'm sure the team would welcome the addition.

Oh great, I'll study it and hopefully I'll be able to submit some additions for automated tests. Thank you very much!

**Comment by n-stein** [comment]
Welcome to the team!

**Comment by otmarjr** [comment]
After copying following [these instructions](https://github.com/moneymanagerex/moneymanagerex/issues/6237#issuecomment-1761820082) by @n-stein I was able to build and debug via Visual Studio 2022 building for Windows.

Note for future reference:
I've skipped the 6th step in the build instructions (patches from util directory to CMake modules) and needed to tweak the script to generate the build environment using CMake due to chances in architecture flag (-A)

cd c:\projects\mmex\build
cmake -DwxWidgets_ROOT_DIR:PATH=C:\wxWidgets-3.2.1 -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=c:\libcurl ..
