### ISSUE TITLE
New feature: using the filters before the reports

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#624]
The filters should be a general feature able to generate a new view of the data, view which can be later used to export the data, view them in the account view or generate the report. Now, when we use the filters and go to a report, all the data are used and when we go back to the account view, the filter has been reseted.

**Comment by vomikan** [comment]
This case seems similar to this:
https://github.com/moneymanagerex/moneymanagerex/pull/666

I close this one.
