### ISSUE TITLE
Request for updated documentation on creating categories.

### ISSUE THREAD

**Issue by Wehzie** [moneymanagerex/moneymanagerex#6240]
MMEX version:
 - [ x ] 1.6.4

Operating System:

 - [ x ] Linux 

#  Question

How do I create a new category?

# Reproduction

I've consulted the documentation at https://moneymanagerex.org/moneymanagerex/de_DE/index.html#section3
When typing in a new category, I'm not allowed to save a new or edited transaction.
This should be easy to do.

Furthermore I've browsed the MMEX Options menu, without success.

After some time I found Tools > Organize Categories. Maybe this is a good location, I'm new to MMEX, however updating the documentation might be sensible. It would be nice to hint at Tools > Ogranize Categories in Section 6 of the documentation. This is where users are likely to land when Googling something along the lines of "add category money manager ex".

An extract of the current documentation is included in the image below.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/39304339/dba9d29b-825d-488b-b530-344d1035b795)

**Comment by renato-mmex** [comment]
Yes, There is a problem with descriptions at the moment.
Everyone wants (demands) changes and no one is aware that you not only have to program changes, but also document them.
MMEX is freeware and lives from volunteers who program / document.
Unfortunately, the volunteers who document are missing.
That one must translate the documentation however also into the many languages is a further task. If one looks here https://crowdin.com/project/moneymanagerex at the state of the translations (3-100%), then there is also here for volunteers much to do.
Greetings from Renato (Admin of the forum MMEX)
