### ISSUE TITLE
Account Type: Mobile Cash/Digital Wallet

### ISSUE THREAD

**Issue by k13oharts** [moneymanagerex/moneymanagerex#6244]
# Description of the feature

Adding a new account type called "Mobile Cash/Digital Wallet" to MoneyManager EX.
This account type is specifically designed to cater to the increasing prevalence of digital wallets and mobile cash transactions in today's financial landscape. Currently, users (like myself) often face challenges in distinguishing between physical cash (of various currencies) and digital wallets from different countries. This new account type aims to bridge this gap by providing a dedicated category for digital wallet transactions.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/112816437/49baba4a-0042-4dcf-9f28-4ddd1fc16699)

Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

Use Case 1: Clear Transaction Tracking
Users frequently conduct transactions using digital wallets for various purposes, such as online shopping, mobile payments, or peer-to-peer transfers. With the Mobile Cash/Digital Wallet account type, users can clearly distinguish these transactions from physical cash transactions, providing a precise overview of their digital financial activities.

Use Case 2: International Users with Multiple Currencies
International users often have digital wallets in different currencies, leading to complexity in tracking expenses and managing budgets. The Mobile Cash/Digital Wallet account type allows users to input transactions in multiple currencies, ensuring accurate financial tracking irrespective of the user's location.

Use Case 3: Enhanced Budgeting and Financial Planning
By organizing digital wallet transactions separately, users can make informed decisions about their spending habits. They can set specific budgets for digital transactions, track expenditures, and plan their finances more effectively.

Use Case 4: Real-Time Balance Updates
Possible integration with digital wallet APIs (for advanced users) or manual input of transactions allows for real-time updates of the wallet balance within MoneyManager EX. Users can view their current digital wallet balances instantly, aiding in better financial decision-making.

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4806
https://github.com/moneymanagerex/moneymanagerex/issues/3894
