### ISSUE TITLE
GA4 integration 

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#6247]
https://support.google.com/analytics/answer/10759417 

> Google Analytics 4 has replaced Universal Analytics. Starting July 1, 2023, standard Universal Analytics properties stopped processing data.

we also see the data disappears in our google analytics, hence, we might need to take action asap to bring the metrics back.

![WX20231019-100149@2x](https://github.com/moneymanagerex/moneymanagerex/assets/721973/03b8dd75-86ff-4486-abfe-55f5f799c3d6)

**Comment by guanlisheng** [comment]
@vomikan , @whalley as  FYI.

**Comment by whalley** [comment]
@guanlisheng  Do we need to make any changes to the website for GA4?

**Comment by guanlisheng** [comment]
@whalley, great if we could enable it.

for webapp/php, I think we can follow gtag integration https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag

**Comment by guanlisheng** [comment]
sth like this

```<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-K8MBNK3HGN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-K8MBNK3HGN');
</script>```

**Comment by grumpy235** [comment]
@vomikan, @guanlisheng @whalley 
I am curious to know why this data is collected at all other than for an intellectual exercise in how to program the collection of this data and send it to Google.
It seems not to have been working for 3 months and the MMEX world did not stop turning.
What benefits does it give? 
We are not talking about a commercial product here just a very useful money management program supported by a few extremely dedicated volunteer developers.

Personally I have switched the collection of statistics off so I hope that means my usage data is not being given to Google (call me paranoid 😟 ) and as I do not download share prices I have also blocked the program in my Firewall.

Interested to hear your thoughts

**Comment by whalley** [comment]
@guanlisheng Have updated website https://moneymanagerex.org/ to use the new tracking code G-K8MBNK3HGN.

**Comment by guanlisheng** [comment]
hey @whalley , there is a dedicated one `G-YEFSZ5W46B` for our homesite. would you help to update it again.

**Comment by guanlisheng** [comment]
hi @grumpy235, the major goal is to track the usage, then we can monitor and measure which function/widget is widely used and which are not.

**Comment by grumpy235** [comment]
Hi @guanlisheng , that is what I guessed. I suppose what I was trying to get at is having collected this data does it help in MMEX developement?
In a commercial environment I can see how it can be used to direct where to concentrate one's development dollars to sell more product but for MMEX, in my opinion, it is simply an overhead, mind you I guess a relatively small one.
I have been using MMEX since version 0.9 days and I cannot remember any issue/enhancement being driven by the fact that function/widget X is being used a lot so perhaps it should be enhanced or for little used parts then perhaps they can be removed.

**Comment by guanlisheng** [comment]
sure, it helps with the iterations for a longer term. 
saying the versioning distribution, function distribution, and whether/why/how the active user increases or decreases. sure that we need to spend time analyzing data. we did deprecate some features which are seldom used. 

it is pretty common to collect such anonymous data, also provides the option to disable it by the end user as we did. 
in terms of Google Analytics, we just chose it and did not have much preference.

**Comment by renato-mmex** [comment]
I would understand the need for such analytical data, but only if you evaluate it and draw the necessary conclusions. 
Surely one would notice that certain program parts are not used so often or not at all, from this one could deduce whether there is a problem and one must improve or also that one invests a lot of development work in program parts that are not used at all.
I am not sure if the current developers have the necessary access to these statistics and have also looked at / analyzed them.

**Comment by guanlisheng** [comment]
though most of the developers have been granted access, feel free to ping me if you are not on the list. 

I was thinking of presenting such analytical data within MMEX as an advanced option, then we would have both `my usage` and `overall usage`.

**Comment by guanlisheng** [comment]
here you go an example from another open source project `homebrew`
https://formulae.brew.sh/analytics/

**Comment by guanlisheng** [comment]
this just inspired me.

@whalley, is it okay to have a similar page (e.g. https://moneymanagerex.org/analytics) to present the stats data, it might be an embedded page from google analytics report.

**Comment by whalley** [comment]
> hey @whalley , there is a dedicated one `G-YEFSZ5W46B` for our homesite. would you help to update it again.

Done.

> @whalley, is it okay to have a similar page (e.g. https://moneymanagerex.org/analytics) to present the stats data, it might be an embedded page from google analytics report.

Yes we could. Once you are ready and have details on the page we want to include let me know.

**Comment by guanlisheng** [comment]
thanks, @whalley 

finally, through Google Data Studio,  our GA4 report and data would be embedded via the following code. 
```
<iframe width="600" height="450" src="https://lookerstudio.google.com/embed/reporting/18963275-23ce-4a1e-a719-5edc95c40bfd/page/auZgD" frameborder="0" style="border:0" allowfullscreen></iframe>
```

hopefully, we can accumulate enough data shortly.

**Comment by whalley** [comment]
@guanlisheng https://moneymanagerex.org/docs/mmex/analytics/

Needs formatting abit...

**Comment by guanlisheng** [comment]
This looks great, and we would tune the width and height to make it fit the window.

in the meantime, we need more data and design the report.

**Comment by guanlisheng** [comment]
going to close this issue as basic functional is ready

**Comment by guanlisheng** [comment]
guys, I am on amplitude to better track and monitor the usage.  
feel free to ping me with your email to join the MMEX on amplitude to see the data.

**Comment by ovari** [comment]
Should **Google Analytics 4 (GA4)** be replaced with [Matomo](https://matomo.org/)?

**Comment by guanlisheng** [comment]
thanks @ovari, 
based on https://matomo.org/pricing/, seems it is a little bit costly. 

We are on Amplitude starter plan now (with up to 5k MTU and 50k monthly events).  would you share me you email then I can invite to the Amplitude MMEX team.

**Comment by ovari** [comment]
@guanlisheng perhaps "On-Premise" or "Eligible non-profit organizations" are possibilities.

@grumpy235 comments seems to imply that it would be best not to track at all. That is, remove GA4 and any other alternatives.

**Comment by guanlisheng** [comment]
I believe tracking is already a conclusion, otherwise, all contributors will be blind to the usage.

And individual end users can always disable this.  the discussion should be sufficient.

the invitation is assuming you want to understand more the usage. please ignore it if not the case.

**Comment by grumpy235** [comment]
@ovari just call me paranoid, I don't like revealing data about myself no matter how anonymous it is meant to be  but unfortunately in this modern world it is a fact of life ☹️  At least with MMEX the opportunity is there to turn it off assuming you realise it is on in the first place !

I suppose the point I was trying to make was that for a non-commercial piece of software - who cares how it is used and if it costs money to collect the data why not put that cash to better use.

There are a limited number of contributors who do a great job of reacting/fixing reported issues without I guess looking at usage stats before they start - why would they as it would not help them fix the problem. 

Will usage stats help to determine when version 1.7.0 goes GA? I doubt it much more likely to be driven by when somebody has the time to do the necessary work.

This piece of work  seems to me a distraction, I doubt if it will help you with your efforts to improve the useability of the product.

Just my opinion :smiley:

**Comment by guanlisheng** [comment]
it does help, in a way you cannot see or feel.  it is a basic engineering practice and every application would provide the option to disable if. 

can you guess what the portion of each version mmex, and what's the overall daily active users trend which motivates the continuous contributions? as we just almost lost the android mmex which is a relative high amount users.

For non-engineer, I would recommend writing up some best practices in both text and/or video.
