### ISSUE TITLE
Bug: exporting with UTF8 not working

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#625]
When we export data in CSV with URF8 (accentued characters, etc), these characters does not show properly in Excel.

**Comment by vomikan** [comment]
Did you try data import?

**Comment by aquirin** [comment]
The import is working fine and editing the file with another text editor is
showing properly the characters. I guess it is a problem with Excel then.
We can close this ;-)

2016-01-01 11:24 GMT+01:00 Nikolay <notifications@github.com>:
