### ISSUE TITLE
compile MMEX on mac osx

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#6255]
MMEX version:
 - [ ] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [x] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

always raise such errors and have no idea how to build mmex on Mac OSX. it is very similar with https://github.com/Tencent/rapidjson/issues/1187

> /Users/guanlisheng/workspace/moneymanagerex/src/maincurrencydialog.cpp:933:11: error: conversion from 'rapidjson::GenericValue<rapidjson::UTF8<>>::Array' (aka 'GenericArray<false, GenericValue<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>>>') to 'rapidjson::Value' (aka 'GenericValue<UTF8<>>') is ambiguous
    Value quotes_closed = quotes["adjclose"].GetArray();
          ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/guanlisheng/workspace/moneymanagerex/3rd/rapidjson/include/rapidjson/document.h:861:5: note: candidate constructor
    GenericValue(Array a) RAPIDJSON_NOEXCEPT : data_(a.value_.data_) {
    ^
/Users/guanlisheng/workspace/moneymanagerex/3rd/rapidjson/include/rapidjson/document.h:2916:5: note: candidate function
    operator ValueType&() const { return value_; }

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I have no issue building on MacOS? What is your build setup? And what is v1.7.2 ?

Simialr to this? https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#macos-with-homebrew

**Comment by guanlisheng** [comment]
yup, just followed the homebrew one and it is for master branch.


here we go my clang++ version
> $ clang++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by guanlisheng** [comment]
no such error on older version mac osx..

> $ clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by guanlisheng** [comment]
@whalley , may i have your osx version?

**Comment by whalley** [comment]
OSX 14.0 but it built fine on 13.x
$ clang++ -v
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
