### ISSUE TITLE
Reduce visible accounts

### ISSUE THREAD

**Issue by chrisairpic** [moneymanagerex/moneymanagerex#6259]
I want to hid closed accounts from the general view. In the menu "Accounts visible", I select "Open" and then only the open accounts are shown. So far, so gut. When I open Money Manager the next time, all accounts are shown. So the selection is **not** stored in the application. Please change.

<hr> • Version: 1.6.4 64-bit<br>
 • Built: Jun 20 2023 18:27:14<br>
 • db 18 (aes128cbc)<br>
 • git 6b4cc69 (2023-06-20)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 •  German (Switzerland) (windows-1252)<br>
 • 1920x1200 32bit 96x96ppi

**Comment by whalley** [comment]
You want to select this in the MMEX settings

![CleanShot 2023-10-23 at 19 52 15](https://github.com/moneymanagerex/moneymanagerex/assets/487345/56b4e4bb-94a7-48fd-8533-cc3c739fe803)

**Comment by chrisairpic** [comment]
Thank you very much this quick response.
