### ISSUE TITLE
Date problem in the booking input mask

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#6261]
MMEX version:
 - [x] 1.6.4
 - [x] 1.7.0 Beta 1

Operating System:
 - [x] Windows

# Description of the bug

**Whenever I change the date formatting, the change is respected in the list of transactions but is never respected when inserting a new transaction.**
https://forum.moneymanagerex.org/viewtopic.php?t=10918

Is the bug reproducible? 
 - [x] Always 

**Expected result:  The date format set in the options should also be applied in the booking input mask**

Actual result:

<img width="615" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/28f5c558-0f09-4476-be8a-e596787270a5">

<img width="405" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/09205cf9-5fcc-4ad8-967b-435aa483ef24">

**Comment by whalley** [comment]
As described here  https://github.com/moneymanagerex/moneymanagerex/issues/3619#issuecomment-860618722

The wxWidgets date picker uses the date format and first day of week that is set in your operating system's Regional Settings.

**Comment by renato-mmex** [comment]
Problem solved, there is no doubt that it was the settings in Windows 11. Thank you very much for your help.
