### ISSUE TITLE
Should `Slovenian (Slovenia)` be written as `sl-SI Slovenščina (Slovenija)`?

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6266]
In "User Interface Language", should `Slovenian (Slovenia)` be written as `sl-SI Slovenščina (Slovenija)` and sorted accordingly?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/4bf0ad94-6314-408a-aa4e-78d1d159c3fe)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/0439cc86-aa12-4d9c-8f0e-d3ef5f796eb9)

https://www.localeplanet.com/icu/sl-SI/index.html

Thank you

**Comment by n-stein** [comment]
![mmex_qps9YOOQVH](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/0da32ab9-76c3-458b-a476-ff3d18e52d24)
![zomaS3BiXt](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/d0bafe6f-8d25-4e94-aa1e-016c6059fc55)

**Comment by ovari** [comment]
Does a version tag need to be added to this issue?
