### ISSUE TITLE
New feature: default payee

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#627]
Currently in the option we can configure the payee as the last one used. It would be nice if we can directly set this default payee for new operations just after opening the DB

**Comment by guanlisheng** [comment]
@vomikan thought?

**Comment by vomikan** [comment]
I suggest to add "Unknown" payee on DB initialization.
Add the option like "Payee Mandatory".

**Comment by vomikan** [comment]
https://github.com/vomikan/moneymanagerex/commit/646ab4bb6970d9e70bb2252b53f1b78baf58b0d4
