### ISSUE TITLE
Transaction Report - Wrong Field(s) Become Hidden Due to Tags/Rate Column Indices

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#6270]
MMEX version:
 - [x] 1.7.0

# Description of the bug
The inception of Tags and/or Rates may cause the wrong field(s) to be hidden on existing Transaction Reports that have hidden columns. Note: This is easy to correct on a report-by-report basis upon opening the report, but may cause confusion and frustration for users.  If this can't be easily solved via logic or a SQL script, we may want to note this as a known issue when releasing 1.7.

# Reproduction
Open a Transaction Report that was created prior to the inception of Rate and/or Tags that contains hidden field(s). In my case, I had hidden the "Rate" field. but now "Amount" erroneously becomes hidden. This appears to be because the fields are identified via index, and the index has changed due to the new Tags field.

Report opened in 1.63. The Notes field is hidden so the last column displayed is Amount:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/8d2a0341-15f0-43bb-a836-2efa3b211897)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/65f38e89-01d7-4a0c-bf21-e0b0d8d51a81)

I then opened the same database in 1.7 (after being upgraded to DB version 19) and viewed the report. The Amount field is now hidden instead and the Rate and Notes fields are displayed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/78307146-1a58-4d4a-9fda-d84cfe00b303)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/2ca87bb3-c956-40e7-8a1e-534426304c68)

Thoughts?

**Comment by n-stein** [comment]
Good catch, Rich. I think I added Tags in the middle to make the order of fields in the "Hide Columns" pop-up match the filter dialog and didn't consider the implications of changing the item indices.

The easiest solution is to simply move Tags and Rate to the bottom of the list to preserve the index of all the pre-existing items, but that means those check boxes will now be at the end after the custom fields. Not ideal, but better than breaking saved reports.

**Comment by n-stein** [comment]
A consideration -- moving "Rate" to the bottom would fix the pre-1.6.4 reports with any hidden columns that have index ≥10, but will throw off any reports saved in 1.6.4 where Rate is now expected to be at index 10.

**Comment by rmelillo76** [comment]
> A consideration -- moving "Rate" to the bottom would fix the pre-1.6.4 reports with any hidden columns that have index ≥10, but will throw off any reports saved in 1.6.4 where Rate is now expected to be at index 10.

Thanks Nick. I think that's the way to handle this too. It's possible not too many users bother to hide columns, so the impact to existing reports since 1.6.4 may be low anyway.  And in a future change we consider a change to show the true name rather than the index (e..g. "10") like you mentioned.

**Comment by n-stein** [comment]
Fixed, also changed the report text to show column names instead of indices.

**Comment by rmelillo76** [comment]
> Fixed, also changed the report text to show column names instead of indices.

Thanks! Code looks good, but for some reason the build failed in Appveyor, looks like ther was a git issue. So, I'll test once we have a successful build: https://ci.appveyor.com/project/whalley/moneymanagerex/builds/48431811/job/3lr5il7uhsatvlf3

**Comment by n-stein** [comment]
> I'll test once we have a successful build

Should be able to test now using the latest build.

**Comment by rmelillo76** [comment]
Looks good, closing - thanks @n-stein !
