### ISSUE TITLE
New feature: insert new operations directly

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#628]
Be able to input new operations without closing the dialog, like in HomeBank

**Comment by guanlisheng** [comment]
@vomikan it should be a cool feature

**Comment by vomikan** [comment]
I like this idea.
But it's quite difficult to implement.
I can't realized how to refresh parent transaction list (+ play sound) on every new transaction.

**Comment by gabriele-v** [comment]
Maybe we could simply close and reopen existing transaction dialog? It will flash a bit but it's quite simple to realize.. 

Normal OK button will behave like now, closing dialog, new button "OK and new" will close dialog, play sound, refresh panel and open new transaction dialog.. 

Or maybe considering that transdialog is modal, we could consider to simply cleanup form and some variables without sound and panel refresh, that will be done after last transaction inserted closing form

PS: it will be nice to add an option where user can choose default focused button on new transaction (OK, OK and new, cancel)

**Comment by aquirin** [comment]
Thank you for your feedback,

I am not an expert in the code of this project, but the easiest way would
be to make this dialog non-modal and keep a pointer to the list item in the
panel to refresh it. It is is not possible or too complex, the second
solution of Gabriele to avoid flashing looks nice to me: keep the data
internally without noise or refresh, and send it at once when user press
"OK". The only drawback I see with this method is that the button "Cancel"
would mean delete all the operations inserted. A solution could be that
"Cancel" remove the last inserted item in the list, but still insert all
the previous ones.

The option proposed by Gabriele could be a simple checkbox, for instance,
like in this image:
http://wordsnsync.com/images/Ver62/Bookmark%20dialog%201A.jpg


2016-01-07 18:45 GMT+01:00 Gabriele-V <notifications@github.com>:

**Comment by vomikan** [comment]
I've tested this metod: on new transaction if OK button pressed the transaction saved then used as template for next transaction with the same date, type, status, account.
If dialogue will be closed the mentioned data will be lost. In that case the idea lost sence.

**Comment by gabriele-v** [comment]
Up to me it's fine in the way that you have implemented.

I only dubt if will be better to add a third button or at least an option to control if press ok will close or will leave open, I don't want that other users will ask to behave like in current version.. 

Surely we cannot change transaction to non-modal because there are too many variables and changes outside that could cause problems to transactions.

**Comment by vomikan** [comment]
I suggest to postpone this request...
