### ISSUE TITLE
Plural when multiple transactions selected

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6281]
When multiple transactions are selected and the mouse hovers above the `Edit` button, should the popup/tooltip show `Edit selected transactions`?

When multiple transactions are selected and the mouse hovers above the `Delete` button, should the popup/tooltip show `Delete selected transactions`?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/8e13e9f3-b58b-4f06-8ff1-b3c29cb615f2)

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Nov 3 2023 03:16:23
• Database version: 19 (aes128cbc)
• Git commit: 0898c7b42 (2023-11-02)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.3 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.4.0-DEV OpenSSL/3.1.4 zlib/1.3 nghttp2/1.56.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.27.7
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-88-generic x86_64
• X-Cinnamon
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1440x810 24-bit 96x96ppi
```

**Comment by whalley** [comment]
As the buttons and tooltips are there all the time I would suggest the best option is to just change to tooltip to:

"Edit all selected transactions" and "Delete all selected transactions". It is then correct whether none, one, or more are selected.

**Comment by ovari** [comment]
> As the buttons and tooltips are there all the time I would suggest the best option is to just change to tooltip to:
> 
> "Edit all selected transactions" and "Delete all selected transactions". It is then correct whether none, one, or more are selected.

Would that be consistent with `Mouse right-click`, `Delete >`, `Delete selected transaction...` (singular) and `Mouse right-click`, `Delete >`, `Delete selected transactions...` plural?
