### ISSUE TITLE
Add Kannada an Indian language `kn-IN ಕನ್ನಡ (ಭಾರತ)`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6288]
1. Add Kannada an Indian language KN-IN for translation at [Crowdin](https://crowdin.com/project/moneymanagerex/discussions/18)
2. Add `kn-IN ಕನ್ನಡ (ಭಾರತ)` to User Interface Language
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/3e38c90b-bb50-4f73-aa35-bc35e536b618)
3. International language support: [Crowdin](https://crowdin.com/project/moneymanagerex), [Desktop icon](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/applications/org.moneymanagerex.MMEX.desktop), [AppData](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml), [Filetype associations](https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/mime/packages/org.moneymanagerex.MMEX.mime.xml), [User interface language](https://github.com/moneymanagerex/moneymanagerex/blob/master/po/common.po)

Thank you

**Comment by vomikan** [comment]
https://crowdin.com/project/moneymanagerex/kn
