### ISSUE TITLE
Mac OS X: Transaction searches only check first word or string in a transaction field

### ISSUE THREAD

**Issue by gemellon** [moneymanagerex/moneymanagerex#6294]
MMEX version:
 - [x] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Search results only shows transaction if term is at the start of a transaction field.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

If Transaction looks like this:

```
Date             Payee                  Withdrawal        Deposit        Balance        Notes

2023-11-10       Tax Office: Local      100.00                           250.00         Paid at local office
```
1] Search for `Local` or `Office`.

Expected result:

Transaction with the date 2023-11-10 will be a result of the search

Actual result:

The transaction with the date 2023-11-10 is _not_ a result of the search.

# Additional information

A search for `Tax` or `Paid` will show this transaction as a result.

The issue is the Search only searches the first word or string in the transaction field. If the search term is not the first word or string there is no result produced for that transaction.

This issue is present for many versions of Money Manager Ex before 1.6.4 also.

**Comment by whalley** [comment]
Try searhcing for "*Local"

**Comment by renato-mmex** [comment]
is activated:
<img width="328" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/d00e5379-6d51-4bf8-adf1-65ec88152eb4">

the following is displayed when you point with the mouse to the search input field:

<img width="297" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/7ed2f19b-a2f9-4947-9da4-1a5c75835156">

**Comment by whalley** [comment]
> EDIT: Hi, I just checked the official documentation and section 7.1 Finding Transactions does not have the tooltip information.

The documentation is sadly no longer (or infrequently) maintained.
