### ISSUE TITLE
How to translate MMEX -Help?

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#6297]
[Post](https://forum.moneymanagerex.org/viewtopic.php?p=24357#p24357) by [frankieorabona](https://forum.moneymanagerex.org/memberlist.php?mode=viewprofile&u=42987) » 12 Nov 2023 09:02

Is there an option to translate the GUIDE/HELP?
Many phrases in Italian are incorrect and many words translated differently than how they are represented in MMEX

**Comment by Cavatilavedette** [comment]
Hi
you can use the online translator www.deepl.com

**Comment by frankieorabona** [comment]
Unnecessary answer... 
I am looking for the section to translate the whole help file. I don't want to do it via deepl (machine translator)!

**Comment by Cavatilavedette** [comment]
réponse inutile ? alors débrouillez vous seul

**Comment by whalley** [comment]
The docs are here: https://github.com/moneymanagerex/moneymanagerex/tree/master/docs feel free to update and submit changes.

**Comment by vomikan** [comment]
> I am looking for the section to translate the whole help file.

In what language?

**Comment by frankieorabona** [comment]
-Italian language. Tnx

**Comment by vomikan** [comment]
At the moment, there is a straightforward programming option. Fork the project and edit the file
https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/it_IT/index.html
