### ISSUE TITLE
New feature: re-assign labels in another category

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#630]
Right now, to change a label from/to another category we have to delete them and create them again which is painful if labels are used in many operations. It would be nice to change them directly in the Tools, Categories, Edit button.

**Comment by vomikan** [comment]
I disagree. It possible to change the label directly.

**Comment by aquirin** [comment]
The label yes but not its category.

**Comment by aquirin** [comment]
Sorry, i did not see the button "Reassign all categories..." in the Tools/Organize categories dialog. I am closing this issue.
