### ISSUE TITLE
Memory leak in 1.7.0-Beta.1

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6304]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

There is a memory leak in 1.7.0-Beta.1 built on commit 975a80c6d. The leak occurs after database open.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Run MMEX.
Open a database.
Close MMEX.

Expected result:
MMEX exits normally.

Actual result:
```
Detected memory leaks!
Dumping objects ->
{960951} normal block at 0x00000241A07DD5C0, 1544 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{960950} normal block at 0x00000241A3906120, 48 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 CD CD CD CD CD CD CD 
Object dump complete.
The program '[26408] mmex.exe' has exited with code 0 (0x0).
```

**Comment by ovari** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6281

**Comment by n-stein** [comment]
@ovari how does this relate to #6281?

**Comment by ovari** [comment]
> @ovari how does this relate to #6281?

The description refers to this, i.e.

> There is a memory leak in 1.7.0-Beta.1 built on commit https://github.com/moneymanagerex/moneymanagerex/commit/975a80c6d462db175a5dc57a4be55276e465b15f. The leak occurs after database open.

Maybe that commit is not the cause. Sorry for the noise.

**Comment by n-stein** [comment]
@vomikan Do you see this issue on your system? I compiled and ran 1.6.4 and 1.6.2 and I get the same "Detected memory leaks" message on both even though I hadn't seen this error in those releases.

**Comment by whalley** [comment]
Apologies, thought I had responded to this a week ago. I couldn't see a leak either.

**Comment by n-stein** [comment]
After further analysis this seems to be a false positive  being automatically reported by Visual Studio's built-in CRT debug heap functions. VLD reports no leaks, so will close this issue.
