### ISSUE TITLE
MoneyManagerEx 1.6.4 crash when I delete a transaction

### ISSUE THREAD

**Issue by jerome-duchene** [moneymanagerex/moneymanagerex#6307]
MMEX version:
 - [x] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Each time that I delete an operation, the app crash.
I try with the 32 and 64bit version and both on Windows 10 and 11

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Delete an operation

Expected result:

Delete the operation and still have the app running

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
I can't reproduce this, but it looks to be the same as #6139. In that issue the users noted that the delete button at the bottom of the panel works correctly. Is this the same case for you?

**Comment by jerome-duchene** [comment]
Same, with the button at the bottom, it's working
