### ISSUE TITLE
[Feature Request] Use Credit Card credit limit to format Credit Limit field automatically

### ISSUE THREAD

**Issue by gemellon** [moneymanagerex/moneymanagerex#6311]
# Description of the feature

The color, outline or text of the Credit Limit cell could be changed to show how close a user is to the account Credit Limit. User's could configure it by percentage, like 95% of Credit Limit, show cell, outline or text in Red, 80% show in Orange, or bold text, like that. Or there could be a default setting.

# Use cases

**Comment by whalley** [comment]
Unfortunately the wxWidgets library we use does not support the colouring of individual cells, only rows (and the row colouring is used for user highlighting). See discussion here https://github.com/moneymanagerex/moneymanagerex/issues/4268. We may need to think of other ways of representing the credit limit

**Comment by whalley** [comment]
I can add a "Credit Limit: xx%" to the panel at the top. Perhaps with a progress bar showing it graphically. Would that be OK?

Using colours gets trickier as it will be affected by themes and limitations on wxWidgets. It also adds the complexity of having user specified limits.

Example...
![CleanShot 2023-11-25 at 17 37 58](https://github.com/moneymanagerex/moneymanagerex/assets/487345/cb9983f2-f6a4-4103-aad6-3e54d271d1f4)

**Comment by whalley** [comment]
> I didn't understand what you wrote about using colors - can this progress bar change color with the user limits?

Not without quite a bit more work... So no plans to do that at present.
