### ISSUE TITLE
`Accounts Visible` has no value

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6319]
Unfortunately, the `Accounts Visible` has no value since https://github.com/moneymanagerex/moneymanagerex/pull/6317.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/d113a9ce-bf1f-4d05-ba5c-87c9005028d2)

Sorry, not sure how to fix.

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Nov 24 2023 03:16:48
• Database version: 19 (aes128cbc)
• Git commit: 9b5dacae3 (2023-11-23)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.3 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.4.0-DEV OpenSSL/3.1.4 zlib/1.3 nghttp2/1.56.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.27.7
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-89-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1440x810 24-bit 96x96ppi
```

**Comment by whalley** [comment]
If you select the dropdown does it give you options?

**Comment by whalley** [comment]
It can be resolved but would seem more work than need for a minor tidy-up. Because of the issues that this cause in terms of backwards compatibility I suggest leaving as-is. "ALL" of course can be translated via Crowdin.

**Comment by ovari** [comment]
> If you select the dropdown does it give you options?

Yes.

**Comment by ovari** [comment]
@n-stein is this something you would fix or should this issue be closed? Thank you

**Comment by renato-mmex** [comment]
I would welcome it if time were not wasted so much on unimportant little things that don't restrict functionality, which is then wasted on fixing real bugs. Sorry.
