### ISSUE TITLE
wxWidgets 3.2.4 released

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6322]
Should update to wx3.2.4 and test.

https://www.wxwidgets.org/news/2023/11/wxwidgets-3.2.4-released/

Yet another release in the stable 3.2 series is now [available on GitHub](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.4). You will find there archives with the library sources and documentation as well as binaries for the selected Windows compilers such as [Microsoft Visual C++](https://visualstudio.microsoft.com/), [MinGW-w64](https://mingw-w64.org/) and [TDM-GCC](https://jmeubank.github.io/tdm-gcc/). You can also read the [updated documentation](https://docs.wxwidgets.org/3.2.4/) for this version and, in particular, if you’re new to wxWidgets, you may find the [installation guide](https://docs.wxwidgets.org/3.2.4/overview_install.html) a good starting point.
Changes since 3.2.3

This release comes very soon after 3.2.3 because some of the changes in the last release resulted in regressions fixed by this release. Notably, 3.2.4 fixes a critical bug which made applications using wxGTK but not initializing the GUI to crash (see issue [#23981](https://github.com/wxWidgets/wxWidgets/issues/23981)).

Other bug fixes include:

    Fix regression in wxTranslations::AddCatalog() return value ([#24019](https://github.com/wxWidgets/wxWidgets/issues/24019)).
    Fix possible crash and too high CPU use when using EGL ([#24018](https://github.com/wxWidgets/wxWidgets/issues/24018)).
    Fix losing clipboard contents when clearing a different selection ([#23988](https://github.com/wxWidgets/wxWidgets/issues/23988)).
    Fix possible crash when dragging pages in wxAuiNotebook ([#24027](https://github.com/wxWidgets/wxWidgets/issues/24027)).
    Fix refreshing multiple selection items in generic wxListCtrl.
    Fix showing windows for background apps under macOS Sonoma ([#23893](https://github.com/wxWidgets/wxWidgets/issues/23893)).

The only new addition in this release is the possibility to create objects of wx legacy “dynamic arrays” class from std::initializer_list<> ([#23966](https://github.com/wxWidgets/wxWidgets/issues/23966)).

Please see the full [change log](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.2.4/docs/changes.txt) for more details.

This release is API and ABI-compatible with the previous 3.2.x releases, so the existing applications don’t even need to be rebuilt to profit from all the fixes above if they use shared/dynamic libraries. And if they do need to be recompiled, this can be done without any changes to the code.

**Comment by whalley** [comment]
@joshua-stone Can you please update the flatpak build to include wx-3.2.4

**Comment by joshua-stone** [comment]
@whalley Here it is:

https://github.com/moneymanagerex/moneymanagerex/pull/6328

**Comment by whalley** [comment]
Have tested on MacOS and looks fine.
