### ISSUE TITLE
Booking in foreign currency

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#6323]
Posting in foreign currency

I would like to be able to enter the exchange rate or the amount of the debit in the base currency in the entry screen.
This option is available for transfer Transaction, but not for normal Transaction.
See also: https://github.com/moneymanagerex/moneymanagerex/issues/4450

Reason: the valuation of the individual Transaction currently carried out according to an algorithm unknown to the user and results in differences in the accounting.

**Example:**
My base currency is CHF
My $ account has a balance of 1000 $
I entered the exchange rate on Nov. 1 $ = 0.91   
I pay with Paypal on 10. Nov 100$ at the rate of 0.90 = CHF 90.00 
I entered the exchange rate on Nov 15 $ = 0.89  
I pay on Nov 24th with Paypal 100$ at the rate of 0.88 = CHF 88.00

I have paid a total of CHF 178.00.  (sorry, my example could be better, then there would also be a difference here)

**Here is the evaluation from MMEX:**

It is calculated at "Gifts" with the rate of Nov 1, 0.91, as the sum of the "Expenses" (random correct) is calculated = ?

<img width="536" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/c02b7329-f954-4bb5-b534-800bae8db367">

I have now downloaded the current rate from Nov. 25th and the values are completely different.
The "Expenses" are shown correctly, but the "Gifts" are now valued at the last known rate and therefore now cost less.

<img width="534" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/90ad4321-f659-4e91-b967-430f2e8ac598">

<img width="159" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/4552c8e4-e153-427e-b18d-ab190c678740">

**I would like to point out that this type of treatment of foreign currencies does not make sense and hope that my proposed changes will be successful.**

**Comment by k13oharts** [comment]
I've been using MMEX for quite a while, and given my frequent travels, I often find myself dealing with transactions between accounts of different currencies (currently 9 in my case). I've noticed that exchange rate treatments can vary based on the country of domicile for different accounts, making direct conversion between currencies not as straightforward or universally applicable. Currency exchange rates are influenced by market conditions, financial regulations, and specific financial institution policies.

To address these nuances, I define PayPal as an independent account and carefully review the statements. For transactions between accounts of different currencies, I record them as "advanced transfers" from the originating account. To ensure the correct amount is reflected in the destination account, I use the "Advanced" option and manually calculate and deduct a Bank Charge or Conversion Fee, which is then recorded separately. These fees are usually detailed in the statements.

It's essential to consider that there are instances when the destination account may impose charges for receiving or processing the transfer.

Given this, I believe the only additional requirement might be to include a "Conversion" section in the Transaction screen, visible when selecting "Advanced." This would allow users to override the transfer with an alternative exchange rate, providing more control without depending solely on base currency rates, which I view as informational.

Regarding the Dashboard window, I suspect it utilizes the "last available" exchange rates to present non-base currency accounts in the Base currency.

**Comment by whalley** [comment]
I've hopefully corrected the wrong currecny calculations on the "Top Withdrawls", it was indeed using the FX rate for today rather than based on the transaction date.

I'm not sure about  over-complicating the transaction dialog with exchange rates. Appreciate it is a 2-step process, but if you need to be precise with conversion rates then they can, as you know, be manually added via the 'organise currencies' dialog.

**Comment by renato-mmex** [comment]
Unfortunately, the figures are still as described above.
Here is the example: 
[Fremdwährung.zip](https://github.com/moneymanagerex/moneymanagerex/files/13492341/Fremdwahrung.zip)

**Comment by whalley** [comment]
This is what I get...
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/48621621

![CleanShot 2023-11-28 at 19 57 15](https://github.com/moneymanagerex/moneymanagerex/assets/487345/aff265bc-44f4-462f-bcde-ea14f218a39f)

**Comment by renato-mmex** [comment]
![Daumen](https://github.com/moneymanagerex/moneymanagerex/assets/76920138/55079e68-febc-4446-a881-c0d16d9e57b9)
Thank you very much

**Comment by renato-mmex** [comment]
.
