### ISSUE TITLE
Bug: Categories reports show wrong incomes/expenses

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#633]
Is this a feature or a bug? I have the impression the "incomes" line show values when the total is positive and "expenses" line show values when the total is negative, in the categories report.

Steps:

(1) Create a new database

(2) Add an operation to withdraw 10€

![capt1](https://cloud.githubusercontent.com/assets/11461466/12071510/a43a4f5c-b0b0-11e5-9420-6f0a6cf3ca51.PNG)

(3) Categories report shows properly -10€ of expenses

![capt2](https://cloud.githubusercontent.com/assets/11461466/12071511/b8bcea8e-b0b0-11e5-851e-9bb33f3c4131.PNG)

(4) Add an operation to depose 20€

![capt3](https://cloud.githubusercontent.com/assets/11461466/12071513/c07e9aec-b0b0-11e5-8ce7-c34a2a5e0ffb.PNG)

(5) Categories report shows 10€ of income. Should not it indicates 20€, even if the total of 10€ is correct?

![capt4](https://cloud.githubusercontent.com/assets/11461466/12071518/e13a3250-b0b0-11e5-97bd-85460a18e727.PNG)

(6) Add another operation to withdraw 30€

![capt5](https://cloud.githubusercontent.com/assets/11461466/12071519/e8d564f8-b0b0-11e5-8883-ca38a8d49958.PNG)

(7) Now categories report shows expenses of -20€ and incomes of 0€. To my view, it should be 20€ in incomes and 40€ in expenses, which produces -20€ in total (this number is correctly reported).

![capt6](https://cloud.githubusercontent.com/assets/11461466/12071522/f2fd02ba-b0b0-11e5-8643-f126a43ba29f.PNG)

**Comment by aquirin** [comment]
I checked on the forums and I found this:
http://forum.moneymanagerex.org/viewtopic.php?f=10&t=6239

Is this related to this "bug"? So we cannot use the same categories for withdrawals and deposits?

**Comment by stef145g** [comment]
The forum comments explains it perfectly. It depends on how you wish to use MMEX.

This is not a bug or a feature, but a design dilemma. Using categories, how do we determine if a category is income or expense? Let the user decide. While the category reports give a general overview, the Transaction Report allows the user to be more specific, so if you use the same category for income and expenses, it becomes a user responsibility to determine why this transaction is an income or an expense based in this category. The perfect example is the Refund scenario. Alternatively, you can allow the category to determine if it is income or expense. The categories will then display the sum of income verses expense.

**Comment by aquirin** [comment]
Actually the table view of the category report is what I was looking for,
not the full list of transaction. About income/expense, it is easy to
determine: just sum all operations marked as "deposit" and as "withdrawal"
in two separated variables and report them in the "expenses" or the
"income" line. I have included a customized report based on the Category
Trend which achieve this (see attachment).



2016-01-02 2:52 GMT+01:00 Stefano <notifications@github.com>:

**Comment by stef145g** [comment]
@aquirin I don't appear to be able to download without having to sign up to the page. Suggest you create a pull request to the General Reports for MMEX: https://github.com/moneymanagerex/general-reports.git

Here you will also find a range or other reports created for MMEX. Also makes it easier to access.

**Comment by aquirin** [comment]
Ok I will create a pull request as far as I have access to a computer, (I
am with my phone now).

You can also download the file by clicking the small cloud after the name
of the file without registering.

**Comment by vomikan** [comment]
UP
This issue is still relevant?
