### ISSUE TITLE
Copy text on About window

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/moneymanagerex#6332]
When you click the About option on the Help menu MMX displays the About window with the About tab selected. All the MMX version details are displayed. You cannot copy any of the text that is displayed and I've often wanted to copy some of the data when writing a forum post or posting something here on github. You can SELECT text on this About tab, but you can't COPY it to the clipboard.

Can you add the right-click option to COPY text that you have selected on this About tab?

<hr> • Version: 1.7.0-Beta.1 64-bit<br>
 • Built: Nov 14 2023 00:27:34<br>
 • db 19 (aes128cbc)<br>
 • git 300316a (2023-11-14)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.3 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: en_GB.windows-1252<br>
 • 1920x1200 32-bit 96x96ppi

**Comment by renato-mmex** [comment]
you can select the text and copy it to the clipboard with ctrl+c.

**Comment by luisdev** [comment]
Ok, I tried that on my Windows 10 Pro 22H2 build 19045.3693 pc, but it's tricky! And maybe buggy?

Try this:

1. Click Help / About to open the About window.
2. Select the first line:
   • Version: 1.7.0-Beta.1 64-bit
3. Press ctrl+c.
3. Open Notepad,exe.
4. Right click in Notepad and select Paste or press ctrl+v.
5. You'll see the correct text pasted in notepad: 
   • Version: 1.7.0-Beta.1 64-bit
6.  Go back to the MMX About window.
7. Select the next line:
   • Built on: Nov 14 2023 00:27:34
8. Press ctrl+c.
9. Go back to Notepad,exe and press ctrl+v to paste the new text you selected and copied.
10.  It STILL pastes the origional text you selected
   • Version: 1.7.0-Beta.1 64-bit
   instead of the new text you selected:
   • Built on: Nov 14 2023 00:27:34
   It should have pasted the new selected line into Notepad:
   • Built on: Nov 14 2023 00:27:34

Now try this:
1.  Go back to the MMX About window.
2. Select the next line:
   • Database version: 19 (aes128cbc)
3. Press ctrl+c MORE THAN ONCE in quick succession.
4. Go back to Notepad and press ctrl+v:
5. Now it pastes the correct text that you selected:
   • Database version: 19 (aes128cbc)
6. Repeat the above (select text, then press ctrl+c more than once)
7. Press ctrl+v in Notepad.
8. The correct text that you selected is pasted into Notepad.

So, it seems like you have to press the ctrl+c keys multiple times in quick succession for the copy from the About window to work.

Can you reproduce this?

**Comment by renato-mmex** [comment]
Place the cursor on the first character, hold down the left mouse button and drag the cursor down to the last desired character, so that the desired text is highlighted in blue, then copy it to the clipboard with ctrl+c.

Sorry, these are basic Windows, Editor .... functions : https://edu.gcfglobal.org/en/windowsbasics/keyboard-shortcuts-in-windows/1/

**Comment by luisdev** [comment]
Thanks Renato. I am quite familiar with how the Windows copy and paste functionality works. And it's working on all applications on my computer, except on this About screen in MMX, as per my description.

**Comment by whalley** [comment]
Seems fine for me on MacOS and Win11.

**Comment by whalley** [comment]
> I was very surprised, but I can reproduce this as well. I'm not sure why the Ctrl+C sequence is not consistently copying the selected text. Are we using a web browser control or a rich text editor to display the formatted contents ?

It's a wxHtmlWindow.

**Comment by rmelillo76** [comment]
Thanks @whalley 

I did some basic testing and found on Windows 10 that the screens using wxHtmlWindow that consistently copy to the clipboard using `CTRL+C `are the ones that also have the right click context menu enabled:

1. Help -> Report a Bug
2. GRM Main Help Page (Click on General Reports Manager)
3. GRM Output Tab
4. All GRM Reports

On the contrary, screens that do not have the right click context menu as was reported here do not seem to register CTRL+C consistently, or at all, EXCEPT the Dashboard/Home Page. For whatever reason that works 100% of the time for me:

1. Help > Help (F1)
2. Help > About  (All tabs)
3. Help > View Diagnostics
4. Theme Manager

Not sure how important this is but thought I'd let you folks know my findings.

**Comment by whalley** [comment]
Apologies I was just using CTRL+C to cut the detail, never even looked at right-click! Agreed a right-click menu does not exist. 

Not sure this really something we should expend energy on adding, the ability to copy is there.

**Comment by rmelillo76** [comment]
> @rmelillo76 The pages that you mention that have right click menus are based on wxWebView controls and not wxHtmlWindow and are used for more expansive, web-browser like, pages.

Thanks, that helps clarify. I guess there are some quirks (and possibly only on Windows) with how CTRL+C is handled in the wxWebView control. And quite possibly outside of our control.

**Comment by renato-mmex** [comment]
There are many windows in MS Windows that cannot be selected and copied (e.g. error messages). Microsoft has simply not brought its old windows and functions up to date over the years.

**Comment by rmelillo76** [comment]
@renato-mmex 
> There are many windows in MS Windows that cannot be selected and copied (e.g. error messages). Microsoft has simply not brought its old windows and functions up to date over the years.

While this is true, many Windows users don't know that you can copy info from dialogs using CTRL+C. I know I was surprised when I found this somewhat obscure feature many years ago:

https://winaero.com/copy-text-message-box-windows-10/

A couple examples:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/864d4d40-710d-4739-b8cb-c4707f83f3dd)

Pressing CTRL+C places the following into the clipboard:

```
[Window Title]
MMEX Options

[Content]
General page has been saved.

[OK]
```

And:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/a92dc1a9-f3d6-4888-98bd-67239f22df78)


```
[Window Title]
Confirm Transaction Deletion

[Main Instruction]
Do you really want to delete the selected transaction?

[Content]
Deleted transactions will be temporarily stored and can be restored from the Deleted Transactions view.

[Yes] [No]
```

**Comment by ovari** [comment]
> Can you add the right-click option to COPY text that you have selected on this About tab?

Should a right-click option to `Select All` also be added?

**Comment by ovari** [comment]
> This should resolve the 'issue'

Can there please be a keyboard shortcut? For example, before the `C` in `Copy`?

`&Copy all text to clipboard` or `_Copy all text to clipboard`

What do you think?

Thank you

**Comment by ovari** [comment]
> While this is true, many Windows users don't know that you can copy info from dialogs using CTRL+C. I know I was surprised when I found this somewhat obscure feature many years ago:

Unfortunately, this does not seem to be the case with GNU/Linux.

**Comment by ovari** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/909810e1-5011-4e8e-b997-9bb254121ed0)

The icon seems to be an `Open` icon. Would it be better to change the icon to a `Copy` icon?

The keyboard shortcut `Ctrl+O` does not work. Should the keyboard shortcut be changed to `Ctrl+C`?

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Dec 1 2023 03:16:22
• Database version: 19 (aes128cbc)
• Git commit: df1680403 (2023-11-30)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.4.0-DEV OpenSSL/3.1.4 zlib/1.3 nghttp2/1.56.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.27.7
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-89-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1440x810 24-bit 96x96ppi
```

**Comment by whalley** [comment]
> The icon seems to be an Open icon. Would it be better to change the icon to a Copy icon?
> The keyboard shortcut Ctrl+O does not work. Should the keyboard shortcut be changed to Ctrl+C?

Think this is due to poor selection of the menu ID. Hopefully fixed now.

Not planning to have a keyboard accelerator for this. It was added to cover the case mentioned above when users are not familiar with keybaord shortcuts - so a simple right-click menu was added. 

Think we have done enough to address the original concern.

**Comment by luisdev** [comment]
> Think we have done enough to address the original concern.

It's perfect! I will test.
Thank uou.
