### ISSUE TITLE
Recent Files list doesn't always show the full path to the recent MMX .mmb files

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/moneymanagerex#6333]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Using MMX:
• Version: 1.7.0-Beta.1 64-bit
• Built on: Nov 28 2023 20:29:44
• Database version: 19 (aes128cbc)
• Git commit: 6356895 (2023-11-28)

On a Windows 10 Pro 22H2 PC.

The Recent Files option on the MMX File menu does not always show the FULL PATH to the different .mmb files that you have previously opened. For some .mmb files it shows the FULL windows path to the .mmb file and for other files it shows just the .mmb file name.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
To test this you should have multiple MMX .mmb database files, preferably in different locations and/or folders.
1. Open MMX 1.7.
2. Click the _File_ menu.
3. Click Open Database.
4. Navigate to a folder that contains a .mmb file and select it.
5. Open the database.
6. Click the _File_ menu.
7. Move down to _Recent Files_.
8. The _Recent Files_ sub-menu expands with a list of all the recent MMX databases that you have used.  Notice how the file names are listed.
9. Click Open Database.
10. Navigate to a folder that contains another .mmb file and open it.
11. Repeat the apove to open a third and fourth database.
12. Move your mouse to _Recent Files_ on the _File_ menu.. You should see all the files that you opened above.
13. Repeat the above process to reopen the different .mmb files again. Each time pay attention to how the databases are displayed on the Recent Files menu.

See attached screenshot 

Expected result:
The recent .mmb files that you have opened should ALWAYS be displayed with their FULL path names on the MMX _File / Recent Files_ menu.

Actual result:
You will see that some of the files are displayed on the MMX _File / Recent Files_ menu with their FULL paths while other files are displayed with just the .mmb file name - without the full path. See the screenshots below taken as I tested this:

![Recent Files](https://github.com/moneymanagerex/moneymanagerex/assets/1124791/df2ac357-a8d1-4952-b925-5826b1705737)

# Additional information
My computer is only running MMX 1.7.0 Beta at the moment, so I can't test this in MMX 1.6.

**Comment by luisdev** [comment]
But users don't know that. Shouldn't it ALWAYS show the full path? Then there will never be any confusion?

**Comment by n-stein** [comment]
Easy fix.

**Comment by luisdev** [comment]
This seems to be fixed now in:
• Version: 1.7.0-Beta.1 64-bit
• Built on: Dec 14 2023 07:00:58
• Database version: 19 (aes128cbc)

Now the **File \ Recent Files** menu always shows me the full paths to the MMX databases. :-)
I'll test some more...

Thanks.

**Comment by whalley** [comment]
Yes, looks good from my testing on MacOS....

**Comment by luisdev** [comment]
Thanks for fixing this.
