### ISSUE TITLE
Erreur de solde (Balance Error)

### ISSUE THREAD

**Issue by Cavatilavedette** [moneymanagerex/moneymanagerex#6361]
Bonjour
le solde de mon compte courant n'a plus rien à voir avec les opérations pointées ce week en : il y a une différence de + de 1300 € 
Idem sur la gestion de mon lep : il y a une différence de plus de 1250 € en négatif.
Je n'ai pas mis à jour le logiciel.
Comment faire pour récupérer la bonne version de mes comptes ?
Merci de votre aide

**Comment by whalley** [comment]
Good morning
the balance of my current account no longer has anything to do with the transactions noted this week in: there is a difference of more than €1,300
Ditto for the management of my lep: there is a difference of more than €1250 in negative.
I haven't updated the software.
How do I get the correct version of my accounts?
Thank you for your help

**Comment by whalley** [comment]
Is it this 'issue' that you have? https://github.com/moneymanagerex/moneymanagerex/issues/5673#issuecomment-1432759278

**Comment by Cavatilavedette** [comment]
non, ce n'est pas ce type de souci, c'est comme s'il des opérations avaient des disparues mais le pointage que je réalise est correct alors que le solde n'est pas bon
j'ai pointé mes comptes le 10 décembre et tout était ok, et lorsque j'ai réalisé un nouveau pointage le 11 décembre : le solde présentait une différence. je n'arrive pas à trouver l'erreur. le solde d'ouverture est toujours bon.

**Comment by whalley** [comment]
> no, it's not this type of problem, it's as if transactions had disappeared but the score I make is correct even though the balance is not good
I checked my accounts on December 10 and everything was ok, and when I did a new check on December 11: the balance showed a difference. I can't find the error. the opening balance is always good.

So you are saying that you manually count the transactions and the balance is correct, but MMEX is counting it wrong? If that is the case, then please check if you have accidentally set any transactions to VOID (status = V) transactions

Failing that, could you include a screen snapshot showing the issue? Feel free to hide any sensitive data.

**Comment by Cavatilavedette** [comment]
That's very kind of you, but unfortunately all the transactions are in "close" or "R" status.
It would be pointless to take a screenshot as the balance comparison for the 11th no longer matches the balance for the 12th, even though it looks like I haven't touched anything.
This doesn't seem to be fixable and I'm going to create a new file to resume managing my accounts.

**Comment by whalley** [comment]
OK if you don't want to investigate more then are you OK with closing this issue?
