### ISSUE TITLE
Theme manager and font colours

### ISSUE THREAD

**Issue by tycariadus** [moneymanagerex/moneymanagerex#6366]
Can the available themes be increased?

The default theme with light blue font for account names against white is not great for older eyes, and the extreme version of white on black is great if you are a teenager!  Can we just have Plain black or a dark blue on white?

Many thanks!

Simon

**Comment by whalley** [comment]
[default-nobluelink.zip](https://github.com/moneymanagerex/moneymanagerex/files/13664929/default-nobluelink.zip)
Unzip this and import to your list of Themes. The light blue should now be black and a bit more readable for our elderly eyes :-)
