### ISSUE TITLE
Vector error

### ISSUE THREAD

**Issue by Ian53OBE** [moneymanagerex/moneymanagerex#6373]
MMEX version:
 - [ x] 1.6.4
 - [
![Screenshot 2023-12-16 at 10 49 07](https://github.com/moneymanagerex/moneymanagerex/assets/139635837/870c9b4e-b7d9-470f-847a-5cbc8a710bc4)
] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [x ] Mac OSX
 - [ ] Linux 

# Description of the bug
When I try to import a CSV file I get an error report stated as Vector. Screenshot attached. I cant proceed beyond this point. If I choose import from XML I can proceed although I dont have XML files so that doesnt help. 
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Related? https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-1857095219 Though possibly not.

@Ian53OBE Is it possible to share the CSV file and perhaps a cutdown database.

**Comment by Ian53OBE** [comment]
Hi Mark,

Thanks for the response.
 I could attach a CSV file in the format I import but I don't think thats the problem. I don't get as far as seeking to access a a file, the error message appears as soon as I click import a  a CSV file so the programme never gets as far as seeking to open any particular file. 

Not sure what you meant by a cut down database but I created a new database which I attach. If you click on import from and select a CSV file you will see the problem. If you select to import from an XML file the usual data specification page opens up.

Ian

**Comment by Ian53OBE** [comment]
😳

**Comment by Ian53OBE** [comment]
Hi Mark, THIS HAS THE CORRECT TEST FILE

Thanks for the response.
 I could attach a CSV file in the format I import but I don't think thats the problem. I don't get as far as seeking to access a a file, the error message appears as soon as I click import a  a CSV file so the programme never gets as far as seeking to open any particular file. 

Not sure what you meant by a cut down database but I created a new database which I attach. If you click on import from and select a CSV file you will see the problem. If you select to import from an XML file the usual data specification page opens up.

Ian

**Comment by whalley** [comment]
Do you still have an issue with the latest Beta release?
https://link.ipx.co.uk/mmex-mac-betas

Import from CSV just pops the Import dialog up for me with no error.

BTW, you will need to attached the test file via Github, not via e-mail response.

**Comment by n-stein** [comment]
The issue could be in mmexini.db3, possibly related to the storage/retrieval of the column widths which was a recent change.

@Ian53OBE does the same issue occur if you right click on "Import from CSV" in a different account? What if you create a new account and right click and "Import from CSV" (so that it doesn't use an existing preset)?

**Comment by n-stein** [comment]
You could also try changing the name of mmexini.db3 so that MMEX can't see it and creates a fresh one. If it works after that than the issue is somewhere in the settings database.

**Comment by wolfgang-ch** [comment]
> Do you still have an issue with the latest Beta release? https://link.ipx.co.uk/mmex-mac-betas

Is there also a beta for Windows?

**Comment by renato-mmex** [comment]
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/48821892

**Comment by n-stein** [comment]
@wolfgang-ch Does the 1.7.0 release solve this? If not, can you send the record for the import settings from mmexini.db3, or just send the whole settings database?

**Comment by Ian53OBE** [comment]
I wasnt showing an update was available but didnt have this 1.7.0 release.
I have now installed it and it seems to have sorted the problem.
Many thanks

**Comment by Ian53OBE** [comment]
I tried that but it didn't work

**Comment by Ian53OBE** [comment]
This release seems to have solved the problem.
Many thanks

**Comment by wolfgang-ch** [comment]
> @wolfgang-ch Does the 1.7.0 release solve this? If not, can you send the record for the import settings from mmexini.db3, or just send the whole settings database?

1.7.0 fixed this problem and the app is working 😄 many thanks for the very quick response 👍
