### ISSUE TITLE
Add asset causes crash

### ISSUE THREAD

**Issue by howff** [moneymanagerex/moneymanagerex#6377]
MMEX version:
 - [x] 1.6.4

Operating System:
 - [x] Windows

# Description of the bug

I added an asset and it asked me "do you want to create an asset account?"
I had no idea what it was asking me (the asset is an item I own, it doesn't have its own bank account), so I answered No.
Then mmex crashed and left the database locked.
If there's a stack trace somewhere I'd add it but nothing was presented to me.

**Comment by renato-mmex** [comment]
This will probably be solved with the next version 1.7.0: 
https://github.com/moneymanagerex/moneymanagerex/issues/6089

**Comment by howff** [comment]
Thanks, I searched open issues but not closed issues ;-)
