### ISSUE TITLE
Cosmetic: Resizing columns in 'All transactions' or 'Bank Accounts' is leaving a trail of vertical black lines. Not checked anywhere else.

### ISSUE THREAD

**Issue by reddyshyam** [moneymanagerex/moneymanagerex#6384]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I can't reproduce. Can you please attach a screenshot.

**Comment by reddyshyam** [comment]
> I can't reproduce. Can you please attach a screenshot.

Hi @whalley, good day! Thanks for getting back. Please see below.

![Animation](https://github.com/moneymanagerex/moneymanagerex/assets/12392746/f0d747b9-145a-42dd-a9ff-eff8a763ce4a)

**Comment by whalley** [comment]
Very odd, I don't get that issue on either Windows or MacOS?

Let's see if others can reproduce.

**Comment by reddyshyam** [comment]
> Very odd, I don't get that issue on either Windows or MacOS?
> 
> Let's see if others can reproduce.

Could it be theming issue? I am using yellow blue.

**Comment by whalley** [comment]
> Could it be theming issue? I am using yellow blue.

Again, I have no issue when using that theme.
