### ISSUE TITLE
Ensure that the generated file from NEWS.md can pass Flathub validation.

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6386]
We may have to add a call to `appstreamcli validate --strict org.moneymanagerex.MMEX.metainfo.xml` to CMakeLists.txt to ensure that the generated file can pass Flathub validation.

_Originally posted by @joshua-stone in https://github.com/moneymanagerex/moneymanagerex/discussions/6369#discussioncomment-7951251_

**Comment by whalley** [comment]
@joshua-stone Is it the CMakeLists or CircleCI file that needs updating for this. Can you make the changes you feel are neccessary.

**Comment by joshua-stone** [comment]
@whalley Here are the changes:

https://github.com/moneymanagerex/moneymanagerex/pull/6415
