### ISSUE TITLE
Version 1.7.0 The software closes when you create a new recurring operation

### ISSUE THREAD

**Issue by lafuye** [moneymanagerex/moneymanagerex#6390]
Dès la validation de la nouvelle opération, le programme se ferme et l'opération n'est pas créée ! 
Quand on relance le programme, la BDD n'a pas été correctement fermée !

**Comment by Dandy64** [comment]
Google translate:
As soon as the new operation is validated, the program closes and the operation is not created!
When we restart the program, the database has not been correctly closed!

**Comment by whalley** [comment]
What version of MMEX are you running and on what platform?
What is the operation you are performing?

**Comment by lafuye** [comment]
1.7.0 
Windows 10 - 64 bit

⁣Télécharger BlueMail pour Android ​

Le 27 déc. 2023, 20:24, à 20:24, Mark Whalley ***@***.***> a écrit:

**Comment by whalley** [comment]
If you create a new database and add a recurring transaction does it still crash?

Doe sit only crash if you use certain Accounts, Payees, Categories?

Can you share the detail in the transaction you have entered that fails?

**Comment by TulioLazarini** [comment]
I have tested the creation of a new scheduled transaction after upgrading from 1.6.4 to 1.7.0 on MacOS, and the test was successful. I've created a new scheduled transaction and deleted it, everything went fine, no crashes. To be noted I've made a database optimisation after upgrade, as suggested by MMEX once the new version was opened.
<img width="807" alt="Screenshot 2023-12-27 at 17 02 47" src="https://github.com/moneymanagerex/moneymanagerex/assets/12682580/88c65b77-bcf4-470e-a978-6a8575c910d0">

**Comment by Dandy64** [comment]
I can't confirm the issue for the portable version 1.7.0, Windows 10 and 11.

**Comment by lafuye** [comment]
With a new database, no crash. 
Crash only with my old database with several accounts, payees or categories !

⁣Télécharger BlueMail pour Android ​

Le 27 déc. 2023, 20:57, à 20:57, Mark Whalley ***@***.***> a écrit:

**Comment by whalley** [comment]
Can you please perform a "Database Optimise" and a "Database Check & Debug" both of which should be found under the Tools menu.

**Comment by lafuye** [comment]
I have already performed a "Database Optimise" without positive result ! For "Database Check" the result is "ok" but i cannot execute the "Debug" option without debug file .mmdbg. I have installed MMEX on an other computer and i get the same bug with my BDD.

**Comment by whalley** [comment]
Is it possible for you to share a copy of your database. If you take a copy and delete all transactions, leaving the scheduled transactions does it still fail? If so, could you share the database so we can look for errors. Feel free to share to support@moneymanagerex.org if you dont feel comfortable posting here.

**Comment by lafuye** [comment]
J'ai fait le test demandé et j'ai toujours un échec.
[lafuye.zip](https://github.com/moneymanagerex/moneymanagerex/files/13802152/lafuye.zip)

**Comment by whalley** [comment]
Thank you that has helped isolate the issue. There does seem to be an issue when reporting that the scheduled transaction will exceed the credit limit on the acount. 

As an interim, until this is fixed, you can set the credit limit on the account for which the scheduled transaction relates to ZERO in the account settings

**Comment by whalley** [comment]
@lafuye There is a 1.7.1 Beta version that you can try here: https://ci.appveyor.com/project/whalley/moneymanagerex/builds/48859392/job/754twhgnh6274gux/artifacts let me know if this fixes your issue.

**Comment by lafuye** [comment]
Nouvelle version testée et OK !
Merci et bonne année à vous !
