### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by pdelamotar** [moneymanagerex/moneymanagerex#6391]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

No matter what language you set, the new date ranges don't come out translated

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

![Captura de pantalla 2023-12-27 144710](https://github.com/moneymanagerex/moneymanagerex/assets/133933827/5e48477f-2c66-4f85-9dd4-6c47bb6443a3)

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
The translations are done by volunteers / users.
Many program changes require new texts which then have to be translated. 
You can view the status of the translations here https://crowdin.com/project/moneymanagerex and also help to translate the texts.

**Comment by pdelamotar** [comment]
> The translations are done by volunteers / users. Many program changes require new texts which then have to be translated. You can view the status of the translations here https://crowdin.com/project/moneymanagerex and also help to translate the texts.

Check the translations and they are done, only for some reason, at least in Spanish, it doesn't apply

![Captura de pantalla 2023-12-27 172351](https://github.com/moneymanagerex/moneymanagerex/assets/133933827/00b5e4a5-dbe5-4f24-910b-ef73c6dc0df8)

Is it necessary to create a translation for each number of days? or there is some code to represent each number of days no matter the quantity

example 

Last 14 days

Last 21 days

etc..

Sorry, I'm not familiar with translations

**Comment by n-stein** [comment]
I think the issue is here:

https://github.com/moneymanagerex/moneymanagerex/blob/master/src%2Freports%2FmmDateRange.cpp#L284

The `"Last %i Days"` needs to be wrapped in `_( )`

**Comment by pdelamotar** [comment]
> I think the issue is here:
> 
> https://github.com/moneymanagerex/moneymanagerex/blob/master/src%2Freports%2FmmDateRange.cpp#L284
> 
> The `"Last %i Days"` needs to be wrapped in `_( )`

Perfect, it would just be searching for that term and translating it, for the moment I'll close

**Comment by whalley** [comment]
Lets's keep open as the code needs fixing.

**Comment by n-stein** [comment]
Fixed.
