### ISSUE TITLE
patch file download

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#6392]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [x] Linux ubuntu 22.04.3 LTS

# Description of the bug

The program requests a repair file. I found it on this link but it doesn't work with it.
[https://github.com/moneymanagerex/moneymanagerex/issues/2353](url)
Where can I download the patch file?

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
What version of MMEX were you previously running?
Is this reported as part of the database upgrade process?
Can you please share the exact message that is reported.

**Comment by Heny67** [comment]
mmex 1.6.4 version

"mmex database error!
the mmex 19 version database does not work with this mmex version. Update mmex to a newer version"

![image](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/d0255200-1f3d-4108-8d9a-dca22f7ee1ec)

After that, the program asks if I have received this repair file.

**Comment by whalley** [comment]
Are you sure you are opening the database with v1.7.0 and not trying to open again with v1.6.4?

**Comment by Heny67** [comment]
I just installed it with flatpac. I downloaded and installed from this link:
[https://flathub.org/apps/org.moneymanagerex.MMEX](url)
But if I see correctly, this is 1.6.4 and not 1.7.0
![image](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/acfba878-78d4-4972-ac8e-690a856a5c2e)

**Comment by whalley** [comment]
That is indeed the issue. @joshua-stone When will the flathub build be updated?

**Comment by joshua-stone** [comment]
@whalley It should be updated now.

@Heny67 Please try updating MMEX with the following:

```
$ flatpak update org.moneymanagerex.MMEX --assumeyes
```

**Comment by whalley** [comment]
This guy age still indicates 1.6.4 https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX

**Comment by whalley** [comment]
> This page still indicates 1.6.4 https://flathub.org/en-GB/apps/org.moneymanagerex.MMEX

Looks good now.

**Comment by Heny67** [comment]
It's good now, thanks.
But when launched the control panel is blank.
By the way, the data is there, but for some reason the control panel does not display it.
What's more, the reports monthly view, summary view, stock report, income expenditure monthly view, etc... are all empty like the dashboard.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/cda487cc-9323-43ae-8225-d26439e4fcb2)

**Comment by whalley** [comment]
Moved to seperate issue.
