### ISSUE TITLE
Account View Right-click For Menu Crash

### ISSUE THREAD

**Issue by Vayben** [moneymanagerex/moneymanagerex#6400]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [X] Linux 

# Description of the bug

When you right-click the empty area in the Account view to bring up a menu for adding records it crashes.  It used to work fine in 1.6.4

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Right-click any empty area in the Account view
![mmex right-click bug](https://github.com/moneymanagerex/moneymanagerex/assets/155168309/4d50c20a-2492-4135-b6e0-df2d5beed162)

Expected result:
Crashes.

Actual result:

**Comment by rmelillo76** [comment]
Hi @Vayben, does it work as expected when the grid is not empty? I am wondering if it has to do with the enhancements made here: https://github.com/moneymanagerex/moneymanagerex/issues/4232#issuecomment-1746195823

**Comment by whalley** [comment]
I can't reproduce this in MacOS or Windows.

**Comment by Vayben** [comment]
> Hi @Vayben, does it work as expected when the grid is not empty? I am wondering if it has to do with the enhancements made here: [#4232 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/4232#issuecomment-1746195823)

Yes, it crashes even if there are items in the grid, But you have to right click below the last entry in the dark area.  Right-clicking a normal grid entry does work fine.

**Comment by n-stein** [comment]
That should fix it.

**Comment by Vayben** [comment]
Thank you guys... i'll wait for the next release.
