### ISSUE TITLE
Installation on Windows issues

### ISSUE THREAD

**Issue by TonySLondon** [moneymanagerex/moneymanagerex#6401]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
I have trouble when upgrading to the latest version. First, Windows 11 doesn't like MMEX and blocks it, I deal with that. Then I launch the new installation and there I lose the will to live. Windows forces me to select from a list of options, none of which make sense. To install an update of your program is about as desirable as fighting on the Ukraine/Russia front.  I have lots of software, and when updates come in they are smooth and simple.  MMEX operates in the wilderness. I admit to not being a Geek, so I will suffer as MMEX is more for Geeks than for people wishing to run their home accounts. Such a shame. It is a very usable programam under normal circumstances. Big criticism is the program's inability to do a year-end rollover, as professional  accounting programs do. However, MMEX is more a playground for Geeks, than home accountants.
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
Not sure where you think 'MMEX is more a playground for Geeks' as there are many non-geek users of the software who use it for home accoounts and some for small business accounts.

It would be helpful if you take screenshots of the messages windows prompts you with and share. I appreciate that the Windows version is not code-signed which may be causing these extra steps as part of the installation.

**Comment by rmelillo76** [comment]
@TonySLondon this was unnecessary. You took all that time to post a bitter diatribe full of sarcasm yet could not even be specific about the actual prompts/options you were presented with. The folks that work on this software do it in their spare time and do the best they can. Please do better.

**Comment by TonySLondon** [comment]
It was totally necessary. Error messages and screen shots have already 
been sent. I am still having problems loading this latest version but 
will live with it. This happens every time an update turns up. Don't you 
dare tell me to do better. It's the Geeks like you that need to do 
better. Thousands of pieces of software get written, not all charged, 
yet they can do updates seamlessly; so why can't MMEX. The program is 
good but it falls short. It needs more competent coders.



------ Original Message ------
From "Rich" ***@***.***>
To "moneymanagerex/moneymanagerex" ***@***.***>
Cc "Tony Speigal" ***@***.***>; "Mention" 
***@***.***>
Date 30/12/2023 13:20:08
Subject Re: [moneymanagerex/moneymanagerex] Installtion (Issue #6401)

**Comment by Speigy** [comment]
Now this crazy program has added over £3,000 to my account just by me 
opening and closing the program and reopening it!!!!!!!!!!!!!! What a 
farce. Never again.


------ Original Message ------
From "Tony Speigal" ***@***.***>
To "moneymanagerex/moneymanagerex" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 31/12/2023 12:15:48
Subject Re: [moneymanagerex/moneymanagerex] Installtion (Issue #6401)

**Comment by whalley** [comment]
> Now this crazy program has added over £3,000 to my account just by me opening and closing the program and reopening it!!!!!!!!!!!!!! What a farce. Never again.

Wow, wish it would add £3,000 to my account. What are you going to spend the money on? Have you thought about a donation to this project.

**Comment by whalley** [comment]
> Error messages and screen shots have already been sent. 

I don't remember seeing these, so apologies, could you please upload these here and describe the steps you need to go through to install - this may help others and raise visibility of the install issues.

> It needs more competent coders.

Point noted, we will all look to do better in the future :-)

**Comment by Speigy** [comment]
In your dreams. Researching another program, there are many. Don't mind 
paying will get people who know what they are doing.


------ Original Message ------
From "Mark Whalley" ***@***.***>
To "moneymanagerex/moneymanagerex" ***@***.***>
Cc "Speigy" ***@***.***>; "Comment" ***@***.***>
Date 31/12/2023 12:34:37
Subject Re: [moneymanagerex/moneymanagerex] Installtion (Issue #6401)

**Comment by whalley** [comment]
> Researching another program, there are many.

@Speigy AKA @TonySLondon Good luck in your research. Could I ask that once this is complete that you let us know the pros/cons of each program and your reason for choosing a new program (if you indeed do). This will help others when makinbg a decsion and perhaps help us with the future feature prioritisation.

**Comment by TonySLondon** [comment]
Will do.

------ Original Message ------
From "Mark Whalley" ***@***.***>
To "moneymanagerex/moneymanagerex" ***@***.***>
Cc "Tony Speigal" ***@***.***>; "Mention" 
***@***.***>
Date 31/12/2023 12:52:07
Subject Re: [moneymanagerex/moneymanagerex] Installation on Windows 
issues (Issue #6401)

**Comment by whalley** [comment]
FYI. We have recieved a few emails from people struggling to install on Windows, I have directed them to the GitHub support pages.
