### ISSUE TITLE
Error in Total of "Reconciled Balance" in the top bar "Total Net Value"

### ISSUE THREAD

**Issue by Pucela200** [moneymanagerex/moneymanagerex#6402]
> Los saldos de las cuentas están bien, pero en el resumen de saldos de la barra de arriba, el saldo conciliado, no coincide con la suma de todos los saldos conciliados de todas las cuentas.
Tengo todas las cuentas con los saldos conciliados y me coincide el importe de la columna "conciliado" con el importe de la columna "Saldo"
Ya me ocurría con la versión anterior, he esperado para ver si con la nueva se corregía, pero no es así, sigue calculando mal, por lo que el saldo TOTAL también está mal.
Un saludo.
> Por favor, no elimine la información adjunta debajo de este texto.

<hr> • Version: 1.7.0 64-bit<br>
 • Built: Dic 26 2023 19:10:28<br>
 • db 19 (aes128cbc)<br>
 • git b380493 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22631), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: es_ES.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by renato-mmex** [comment]
traducido con www.deepl.com:
translated with www.deepl.com:
The balances of the accounts are OK, but in the balance summary in the bar above, the reconciled balance does not match the sum of all the reconciled balances of all the accounts.
I have all the accounts with the reconciled balances and the amount in the "reconciled" column matches the amount in the "Balance" column.
It already happened to me with the previous version, I have waited to see if with the new one it would be corrected, but it is not, it still calculates wrong, so the TOTAL balance is also wrong.
Best regards.

**Comment by whalley** [comment]
Do you have any share accounts?

**Comment by Pucela200** [comment]
Si

**Comment by Pucela200** [comment]
El saldo de las acciones me da bien.

**Comment by whalley** [comment]
The 'Shares' accounts are considered when considering the Reconcilled balance. These are not, rightly or wrongly' not listed in the Dashboard accounts. The dashbaord only shows the 'Stocks'. Does this account for your issue?

I'm not overly familar with the Stocks/Shares fucntionality in MMEX but perhaps 'Shares' accounts should be shown.

**Comment by Pucela200** [comment]
He conciliado todas las anotaciones de las acciones y ahora tengo el saldo conciliado bien pero el total NO suma el importe de acciones.

**Comment by whalley** [comment]
@Pucela200 Not sure I now understand what you are saying. It would be useful to understand what the specific numbers are. i.e. total account (bank, cash, card, shares) balances and reconcilled transactions. Assets, Stocks, and the Toal balance you are seeing.

**Comment by Pucela200** [comment]
Lo que digo es que la suma del total conciliado mas las acciones, no suman el TOTAL de Saldo.
El saldo conciliado sale bien, las acciones salen bien, pero el Saldo Total no sale biern.

**Comment by Pucela200** [comment]
Los saldos son: 
Conciliado: 184.523,52 
Activos: 0,00
Acciones: 1.483,07
SALDO: 184.444,33
Como puedes comprobar el SALDO no está bien.

**Comment by whalley** [comment]
This would seem to point to the fact that there are a number of unreconcilled transactions totalling -1562.26 (perhaps a credit card account?)

**Comment by Pucela200** [comment]
No, no es eso.
Si sumo el importe conciliado de cada cuenta (Todo tipo de cuentas menos acciones) me da el importe total conciliado del resumen. Este importe sumado a las acciones, debería ser el importe total del SALDO y esto es lo que no coincide.

**Comment by Pucela200** [comment]
En las columnas de las cuentas, la columna de conciliado y la columna de saldo coinciden, es en el resumen de arriba donde da el error.

**Comment by whalley** [comment]
I'm currently at a loss as to how to best analyse this without a sample DB showing the discrepancy you are seeing - this can be a cutdown DB if teh issue still exists with that.  If you feel more comfortable sharing via e-mail then please send to support@moneymanagerex.org. I can assure you this will only be used for analysing the issue and will be deleted once done.

**Comment by Pucela200** [comment]
Te remito base de datos por correo.

**Comment by whalley** [comment]
Thank you for sharing. As I noted here: https://github.com/moneymanagerex/moneymanagerex/issues/6402#issuecomment-1872590673 it seems to be the Share Accounts.

If you expand the 'Share Accounts' in the navigation panel you will see there are two accounts, one at -375.44 and one at -1186.82. These account for the difference.

**Comment by Pucela200** [comment]
No encuentro la opción de "Cuentas compartidas" en el menú de navegación.

**Comment by whalley** [comment]
![CleanShot 2024-01-05 at 10 17 18@2x](https://github.com/moneymanagerex/moneymanagerex/assets/487345/e8ea6a72-2bd2-48b5-a000-eef808790c4e)

**Comment by Pucela200** [comment]
El problema es que en las cuentas de acciones, sale la cantidad como "No Conciliado" y no se puede cambiar a conciliado. Lo cambio y al volver a entrar en el movimiento, me pone "No conciliado"

**Comment by Pucela200** [comment]
Creo que en el resumen de arriba, lo correcto seria: Valor neto: Conciliado + Activos + Acciones = SALDO

**Comment by whalley** [comment]
> ENG> The problem is that in the stock accounts, the amount appears as "Not Reconciled" and cannot be changed to reconciled. I change it and when I re-enter the movement, it says "Not reconciled"

I changed all the SHARE transactions to "Reconcilled" in the DB you supplied. I had no issues in changing to reconcilled.

> ENG> I think that in the summary above, the correct thing would be: Net worth: Reconciled + Assets + Shares = BALANCE

The BALANCE figure includes reconcilled and Unreconcilled transactions. This is as displayed in the dashboard and the 'Summary of Accounts' report.

**Comment by Pucela200** [comment]
Bueno creo que el problema está aclarado, por lo tanto destruya la base de datos y podemos cerrar el roblema.

**Comment by whalley** [comment]
Thank you. I have deleted the DB you sent. You may also noted that due to you raising your issue we are now looking to add the Share accounts to the dashboard for better clarity https://github.com/moneymanagerex/moneymanagerex/issues/6437 so thank you for raising the original issue.
