### ISSUE TITLE
Korean language name in "View -> User Interface Language" should be written in the Korean alphabet

### ISSUE THREAD

**Issue by tomasz1986** [moneymanagerex/moneymanagerex#6404]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The native language name used next to "ko-KR" is written in simplified Chinese characters. This is incorrect, because a) it should be written in the Korean alphabet as `한국어(한국)` (or more correctly as `한국어(대한민국)`), and b) even when using Chinese characters, Korean only uses the traditional version of them, not the simplified one as is the case here.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/5626656/aae88fa5-a837-4800-825e-3f3a870faba0)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by tasukus** [comment]
The selection menu for the user interface language in mmGUIFrame is also present in OptionSettingsGeneral.
I noticed that the display string in OptionSettingsGeneral does not match.
I believe it would be better to align the display strings between mmGUIFrame and OptionSettingsGeneral.
Do you happen to know why there was a need for different display strings?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6128426/3045e5da-e6e6-424d-be96-944173d4de1d)

**Comment by n-stein** [comment]
> Do you happen to know why there was a need for different display strings?

I think the reason is because we forgot there is a third language list. We translated the list in the App Start Dialog and the View menu but missed the list in the options menu.

**Comment by n-stein** [comment]
Both issues fixed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/fb2e8dac-1002-4d9f-b03f-247dbdd902ee)
