### ISSUE TITLE
Link Tags to Category

### ISSUE THREAD

**Issue by pdelamotar** [moneymanagerex/moneymanagerex#6406]
# Description of the feature

Any way to link categories to tags? Just how do you do it with the payees - category? Or am I missing something?

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

When you put payees automatically you put the last used category which is usually always the same, and then this category puts the last used tag, it would make life easier

Sorry, I'm using a translator I don't know if my plan is being clear

**Comment by whalley** [comment]
Not sure about linkage from Tag to Category or Payee. Think holding a 'Last used tags for category' may get things wrong more often that not. People use Tags for many things.

**Comment by pdelamotar** [comment]
I mean it would be helpful if I have several categories that indicate my salary from different jobs, that given one a tag is linked automatically, the same for taxes for example that single tag could be linked to many categories

**Comment by n-stein** [comment]
So in Options under the defaults section you want a setting for Tags with the choices "None, Last used for Category, Last used for Payee"?

**Comment by pdelamotar** [comment]
> Entonces, en Opciones, en la sección predeterminada, desea una configuración para Etiquetas con las opciones "Ninguna, Última vez utilizada para la categoría, Última utilizada para el beneficiario"? ¿O más bien la "Categoría predeterminada" que puede asignar a un beneficiario?

It would be great, so you don't have to put the same tag in the same category every new transaction

**Comment by whalley** [comment]
As noted above I think the use of Tags is different for many users and creating the linkage of tags to categories/payees is just one such use case. 

See: https://help.quicken.com/display/MAC/Learning+about+categories+and+tags  for an example used in the Quicken manual where the association to payees/categories in non-existant.

My view is that we don't implement this feature, however if somebody were to implement it should be disabled by default.

**Comment by luisdev** [comment]
@pdel, perhaps you could set up a recurring transaction to do what you want? Add the tags that you want, and they should be loaded to new transactions each time that recurring transaction is recorded.

**Comment by luisdev** [comment]
> My view is that we don't implement this feature, however if somebody were to implement it should be disabled by default.

I agree.

If I want to attach a tag to a recurring transaction, then I just create a Recurring Transaction in MMX. Then, each time the Recurring Transaction is recorded, the tag is also recorded, without manual intervention from me.
