### ISSUE TITLE
Transaction Report - Rate column

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6408]
The PR that updated the 'Rate' column on the Transactions report needs more work. If we are to change "Rate" to "Currency Exchange Rate" then the list for "Hide Columns" should be changed also.

![CleanShot 2023-12-30 at 19 21 05](https://user-images.githubusercontent.com/487345/293477044-0eb257cb-9d50-4053-a676-cb98b33b839d.png)

However, my view, is that the use of "Rate" was suitable. The column heading seems now too long....

![CleanShot 2023-12-30 at 19 24 49](https://github.com/moneymanagerex/moneymanagerex/assets/487345/7e63b95d-6966-435c-b8c1-80da2a643205)

_Originally posted by @whalley in https://github.com/moneymanagerex/moneymanagerex/issues/6374#issuecomment-1859000017_

**Comment by whalley** [comment]
I'm happy with "FX Rate".

**Comment by whalley** [comment]
@ovari Is "FX Rate" acceptable to you?

**Comment by ovari** [comment]
> @ovari Is "FX Rate" acceptable to you?

Sounds fine.  Thank you
