### ISSUE TITLE
Foreign currency conversion issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#641]
I have GBP as the base rate but need to setup a bank account with VND - the exchange rate is 0.000030 but it would appear the system can only handle a maximum of 4 decimal places.

Is there anyway I can change this?

http://forum.moneymanagerex.org/viewtopic.php?f=10&t=6312

**Comment by callmenemo491** [comment]
https://en.wikipedia.org/wiki/Exchange_rate
The fourth decimal place is usually referred to as a "pip"). An exception to this was exchange rates with a value of less than 1.000 which were usually quoted to five or six decimal places

so we should have the rule.
if x-rate is above 1.000  then we display the x-rate to 4 decimal places, e.g.  1.0264  or 153.1234

if x-rate is below 1.0000,  then we go to 6 decimal,  like:  0.000030
