### ISSUE TITLE
MMEX 2019 database does not update

### ISSUE THREAD

**Issue by SJCourtney** [moneymanagerex/moneymanagerex#6410]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
We need more information. 

What error message is given?
What is MMEX 2019 database?

**Comment by SJCourtney** [comment]
I have recently installed an update of MMEX which has automatically 
updated all my previous years databases, with one exception.
My database for 2019 generates an error message that it cannot update 
ver15. All the other databases update correctly to ver 17.
I hope this helps.

**Comment by whalley** [comment]
The latest DB used by MMEX v1.7.0 is v19, I'm therefore curious to understand why you mention v17?

**Comment by SJCourtney** [comment]
When I was updating my old databases. the successful ones showed a list 
of updates - v13,v14,v15,v16 and v17. The rogue database however will 
update v13 and v14 but fails to load beyond v15.

**Comment by renato-mmex** [comment]
**You would make our investigations much easier if you could show us the error message in the form of a screenshot here.**
Not by e-mail, otherwise the screenshot will not be displayed.

**Comment by SJCourtney** [comment]
Screenshot attached. The program then asks if there is a debugb patch 
Yes/No. I have no debug patch

**Comment by renato-mmex** [comment]
@SJCourtney    I have written: **Not by e-mail, otherwise the screenshot will not be displayed.**

**Comment by SJCourtney** [comment]
So how do I send you the screenshot

**Comment by renato-mmex** [comment]
Login to Github and paste into the post (ctrl+v)

**Comment by SJCourtney** [comment]
![Screenshot 2024-01-02 124729](https://github.com/moneymanagerex/moneymanagerex/assets/155319516/b209364c-30aa-4405-8314-83f706e39848)

**Comment by SJCourtney** [comment]
Screenshot added to Github

**Comment by renato-mmex** [comment]
With which MMEX version was this database last opened without problems?   1.4.0 ????
can you copy us a list of the files from this database.
Sample:
<img width="236" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/5bc25c05-ff75-46bd-9b5e-660354953c78">


May I ask you to comment on whalley's question
_The latest DB used by MMEX v1.7.0 is v19, I'm therefore curious to understand why you mention v17?_
If you are using MMEX 1.7.0, the other databases of the DB should be v19. So the upgrade v18 should be available.

By the way: the better information you provide us with, the more we can help you.

**Comment by SJCourtney** [comment]
The last two times I have tried unsuccessfully to open 2019.mmb, the 
program logs the following - 2019.mmb_upgrade_v14_2023-12-28.bak and 
mmb/2019.mmb_upgrade_v14_2023-12-31.bak. The 2019 database would have 
been created using the latest update available in late 2018. I'm sorry 
but I have no record of which MMEX version that was. Hope this helps.

**Comment by whalley** [comment]
Sounds like this may be a DB from the aborted v1.4.x product line.

Please take a backup of your database and follow the instructions here: https://github.com/moneymanagerex/moneymanagerex/issues/2353

Then open the database with v1.7.0.

**Comment by SJCourtney** [comment]
Success. 2019 now opens OK. Many thanks
