### ISSUE TITLE
Tags are not being copied during copy/paste transactions

### ISSUE THREAD

**Issue by TulioLazarini** [moneymanagerex/moneymanagerex#6424]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

When one copies a transaction between accounts, and the original transaction has a tag associated to it, the tag is not present  in the pasted transaction - one has to edit the newly pasted transaction and manually add the tag. Probably the tag attribute is not being originally copied, or the feature that pastes the data is ignoring the tag attribute originally copied.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
- Create a new transaction and associate a tag to it
- Right click the transaction and copy it ("Copy Transaction")
- Go to the account you want to paste the transaction
- Right click inside the account view and paste the transaction (using "Paste Transaction")
- One will see the tag originally associated to the copied transaction won't be there.

Expected result:
- Having all transaction details, including tags, in the pasted transaction

Actual result:
- Tags are not being pasted

**Comment by whalley** [comment]
Confirmed, thank you for reporting.

**Comment by whalley** [comment]
Same issue applies when copying transactions with splits that have tags

**Comment by n-stein** [comment]
Fixed
