### ISSUE TITLE
Monye Manager bug when delete a ligne

### ISSUE THREAD

**Issue by Alouette44** [moneymanagerex/moneymanagerex#6448]
> Remplacez ce texte (marqué par >) avec une description détaillée de votre problème.

Hello,
The program has had a bug for some time when you delete an accounting line (delete then delete the selection).
The attached error message appears and you have to quit the application and start again.
This has been going on for several versions now, for about 3 months.
I was hoping this would be corrected but the error keeps recurring.
It's not systematic but very frequent (95% of the time).
Thank you for your help.
Best regards and happy new year 2024

![Capture](https://github.com/moneymanagerex/moneymanagerex/assets/155957418/8fe14336-38e2-420b-b8e6-aa3ec3306cf8)

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr> • Version: 1.7.0 64 bits<br>
 • Built: Déc 26 2023 19:10:28<br>
 • db 19 (aes128cbc)<br>
 • git b380493 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: fr_FR.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by n-stein** [comment]
Does #6139 accurately describe your issue?

**Comment by Alouette44** [comment]
Yes #6139 describe my issue

**Comment by whalley** [comment]
Closing as duplicate.
