### ISSUE TITLE
Problème sur le rapport de "Performance budgétaire"

### ISSUE THREAD

**Issue by lafuye** [moneymanagerex/moneymanagerex#6450]
> Rapports - Budgets - Performance budgétaire
Si on a défini des budgets mensuels, les estimations cumulent la valeur mensuelle retenue
 dans le budget annuel avec la valeur contenue dans le budget mensuel ce qui provoque un doublement erroné de l'estimation budgétaire !
J'ai renseigné les bugets mensuels de janvier et février et on observe bien le bug dans le tableau suivant.

ENG> Reports - Budgets - Budget performance
If monthly budgets have been defined, the estimates accumulate the monthly value retained
in the annual budget with the value contained in the monthly budget which causes an erroneous doubling of the budget estimate!
I entered the monthly budgets for January and February and we can clearly see the bug in the following table.

![Perf Budg](https://github.com/moneymanagerex/moneymanagerex/assets/155011886/f19ca30f-4371-44f1-a178-2a17ecadaf32)

<hr> • Version: 1.7.1-Beta.1 64 bits<br>
 • Built: Janv.  1 2024 13:15:44<br>
 • db 19 (aes128cbc)<br>
 • git 8947791 (2024-01-01)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: fr_FR.windows-1252<br>
 • 1366x768 32-bit 96x96ppi

**Comment by n-stein** [comment]
Not a bug.

Go to Tools -> Options... -> View Options and enable "Override yearly budget with monthly budget"

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/25140489-b80c-462d-b607-6579dbc00810)

**Comment by lafuye** [comment]
Fine ! 
Thanks !

**Comment by lafuye** [comment]
Fine !
Thanks !

**Comment by lafuye** [comment]
Fine !
Thanks !
