### ISSUE TITLE
Make Transaction column value copyable 

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#6457]
# Make Transaction details copyable

Make Transaction Notes at the bottom of the transaction list copyable. Double click to select line, Triple click to select everything and click and drag to select part.

Only thing better is to be able to click on any cell on the transactions table and have a context menu to "Copy" the cell value as is.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/10950385/cd32a4ef-a2e5-49ab-8d20-b48d21e52c26)

# Use cases

I have to double click and wait for the edit transaction dialog to open to copy.
Being able to copy FULL or PART of the notes at the preview panel at the bottom is handy little feature I need.
Quite like you do on a web page with input[type=text] or textarea elements.

**Comment by whalley** [comment]
Right click on transactions table should allow you to now copy text to the clipboard.

**Comment by sarjanwebdev** [comment]
Yes it does, but the whole transaction gets copied, and there is a whole lot of editing to be done.
When doing quarterly accounting, I copy-paste from notes a lot to search elsewhere.
Being able to partial copy the field I want is perfect for my use case.

Change that label to a read-only enabled text area. That's it, I guess.

> Right click on transactions table should allow you to now copy text to the clipboard.

**Comment by whalley** [comment]
> Yes it does, but the whole transaction gets copied, and there is a whole lot of editing to be done.
> 
> When doing quarterly accounting, I copy-paste from notes a lot to search elsewhere.
> 
> Being able to partial copy the field I want is perfect for my use case.
> 
> 
> 
> Change that label to a read-only enabled text area. That's it, I guess.
> 
> 
> 
> > Right click on transactions table should allow you to now copy text to the clipboard.
> 
> 
> 
> 

Using the latest beta, if you hold the mouse over a specific cell and right click it should now allow you to copy that cell.

**Comment by whalley** [comment]
@sarjanwebdev Does this change address you needs? Beta build - https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/oo7cigtt0cf49xrj/artifacts

**Comment by njwgh** [comment]
Note that this only seems to work on the 'main' notes, not any notes in split transactions. It confused me for a while until I worked out why some notes had the 'copy' option and other didn't
