### ISSUE TITLE
Error ../include/wx/datetime.h(1727): assert "IsValid()" failed in GetTicks(): invalid wxDateTime

### ISSUE THREAD

**Issue by camposFabio** [moneymanagerex/moneymanagerex#6458]
MMEX version:
 - [x] 1.7.0

Operating System:
 - [X] Linux 
Debian 12
```

MMEX configuration summary
==========================
Version        : 1.7.0
Commit         : b38049357 (2023-12-26)
Host system    : Linux x86_64
Target system  : Linux x86_64
Build types    : 
Generator      : Unix Makefiles
Install prefix : /usr/local
DB encryption  : ON

Versions
-========-
Linux 6.1.0-17-amd64
Debian.12.bookworm
Debian.GNU/Linux.12.(bookworm)
CMake 3.25.1
GNU Make 4.3
ccache
GNU 12.2.0
wxWidgets 3.2.4
wxSQLite3 4.9.1
Lua 5.3.5
curl 7.88.1
gettext 0.21
------------------ 8< -----------------

--- Locale ---
LANG=pt_BR.UTF-8
LANGUAGE=
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

```
------------

# Description of the bug

Every time I want to change the status of an transaction (via keyboard or right-button "Mark as")  the error "../include/wx/datetime.h(1727): assert "IsValid()" failed in GetTicks(): invalid wxDateTime" occurs 3 times. 
The transaction has its status changed after the last message.

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:

- Select any transaction and press R  (or right-button "Mark as") to check it as reconcilied

Expected result:
- Transaction marked as R

Actual result:
- Erro message then transaction changed
 
# Additional information
Language configuration
![image](https://github.com/moneymanagerex/moneymanagerex/assets/40764894/3661b2f5-4799-4be4-bdb9-c27a38b1d290)

If you have a backtrace for a crash or a warning, paste it here.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/40764894/1af60327-d4fe-4b4d-a9e3-ced1af734cfa)

# Backtrace:

```

ASSERT INFO:
../include/wx/datetime.h(1727): assert "IsValid()" failed in GetTicks(): invalid wxDateTime

BACKTRACE:

[1] wxDateTime::GetTm(wxDateTime::TimeZone const&) const
[2] wxDateTime::Format(wxString const&, wxDateTime::TimeZone const&) const
[3] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[4] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[5] wxEvtHandler::TryHereOnly(wxEvent&)
[6] wxEvtHandler::ProcessEventLocally(wxEvent&)
[7] wxEvtHandler::ProcessEvent(wxEvent&)
[8] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[9] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[10] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[11] wxEvtHandler::TryHereOnly(wxEvent&)
[12] wxEvtHandler::ProcessEventLocally(wxEvent&)
[13] wxEvtHandler::ProcessEvent(wxEvent&)
[14] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[15] g_closure_invoke
[16] g_signal_emit_valist
[17] g_signal_emit
[18] gtk_window_propagate_key_event
[19] g_closure_invoke
[20] g_signal_emit_valist
[21] g_signal_emit
[22] gtk_main_do_event
[23] g_main_context_dispatch
[24] g_main_loop_run
[25] gtk_main
[26] wxGUIEventLoop::DoRun()
[27] wxEventLoopBase::Run()
[28] wxAppConsoleBase::MainLoop()
[29] wxEntry(int&, wchar_t**)
[30] __libc_start_main

```

-------------
# WxWidgets 3.2.4 build from source followig this steps:

```

wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2
bzip2 -d wxWidgets-3.1.0.tar.bz2
tar xvf wxWidgets-3.1.5.tar.bz2

To avoid wxWebViewEvent erro on compilling mmex:
sudo apt-get install libwebkit2gtk-4.1-dev

cd wxWidgets-3.1.5
mkdir -p build-release
cd build-release
../configure --disable-debug_flag --with-gtk=3 --enable-stl
make -j$(nproc) 

sudo make install
sudo ldconfig  

```

# MMEX compilled with this steps:

```

To avoid error with libcurl:
sudo apt-get install libcurl4-openssl-dev

git clone --recursive https://github.com/moneymanagerex/moneymanagerex  --branch v1.7.0

mkdir moneymanagerex/build
cd moneymanagerex/build
export MAKEFLAGS=-j4

cmake . (only sometimes needed)
cd build/

cmake -DCMAKE_CXX_FLAGS="-w" -DCMAKE_BUILD_TYPE=Release ..
cmake --build .. --target package


```

**Comment by whalley** [comment]
Does the published flatpak version work OK on your system?

**Comment by camposFabio** [comment]
I don´t know. Its an new debian instalation and I don´t have flatpak

**Comment by n-stein** [comment]
I would try wxWidgets 3.2.4. The BUILD.md which says to use 3.1.5 is outdated.

**Comment by whalley** [comment]
> I don´t know. Its an new debian instalation and I don´t have flatpak

Could you please try the flatpak version so we can see if it a general issue with your OS or a build issue.

**Comment by n-stein** [comment]
The presence of wxWidgets debug assertions indicates you are using wxWidgets debug libraries. Compile release instead and the errors will go away. 

> `../configure --disable-debug_flag --with-gtk=3 --enable-stl`

Instead of `--disable-debug_flag` try `BUILD=release`



That doesn't mean we don't need to check our code, we may be doing something wxWidgets doesn't like and is handling the error silently in the background.

**Comment by camposFabio** [comment]
> I would try wxWidgets 3.2.4. The BUILD.md which says to use 3.1.5 is outdated.

I'm using the 3.2.4 version. 

> The presence of wxWidgets debug assertions indicates you are using wxWidgets debug libraries. Compile release instead and the errors will go away.
> 
> > `../configure --disable-debug_flag --with-gtk=3 --enable-stl`
> 
> Instead of `--disable-debug_flag` try `BUILD=release`
> 
> That doesn't mean we don't need to check our code, we may be doing something wxWidgets doesn't like and is handling the error silently in the background.

I will try and report the results.

**Comment by camposFabio** [comment]
> The presence of wxWidgets debug assertions indicates you are using wxWidgets debug libraries. Compile release instead and the errors will go away.
> 
> > `../configure --disable-debug_flag --with-gtk=3 --enable-stl`
> 
> Instead of `--disable-debug_flag` try `BUILD=release`
> 
> That doesn't mean we don't need to check our code, we may be doing something wxWidgets doesn't like and is handling the error silently in the background.

Compiling wxwidgets without debug `../configure BUILD=release --with-gtk=3  --enable-stl --disable-debug`
info solved the problem. Thanks!

**Comment by camposFabio** [comment]
> The presence of wxWidgets debug assertions indicates you are using wxWidgets debug libraries. Compile release instead and the errors will go away.
> 
> > `../configure --disable-debug_flag --with-gtk=3 --enable-stl`
> 
> Instead of `--disable-debug_flag` try `BUILD=release`
> 
> That doesn't mean we don't need to check our code, we may be doing something wxWidgets doesn't like and is handling the error silently in the background.

Compiling wxwidgets without debug `../configure BUILD=release --with-gtk=3  --enable-stl --disable-debug`
info solved the problem. Thanks!
