### ISSUE TITLE
Some actions make the accounts in the Navigation pane disappear

### ISSUE THREAD

**Issue by gemellon** [moneymanagerex/moneymanagerex#6464]
MMEX version:
 - [x] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Some steps I take in Money Manager Ex make the list of accounts in the Navigation pane to disappear. Sometimes only one or two accounts, sometimes all of them except one. This is only a display bug, the accounts are not lost.

# Reproduction

First way:

Delete a transaction. For me this always makes the list of accounts disappear except for the account that I am viewing. In the image below I deleted a transaction from one account (I removed the name) and this is what the Navigation Pane looked like after:

![3](https://github.com/moneymanagerex/moneymanagerex/assets/145873120/ebf8ab06-a53c-40a6-87ad-55b5dc75d167)

Second way:

1. Select an account in the Navigation pane.
2. Use the arrow keys and move up and down the list of accounts

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Expected result:

The accounts should not disappear from the list.

Actual result:

In the first way, all the accounts except one disappear from the pane.

In the second way, one or two accounts (even the account type, like 'Cash Account' or 'Credit Card Account') will disappear from the pane but will come back if I select them again with the arrow keys, but then when they appear another one will disappear. If I click on the disappearing account with the mouse it comes back without another account disappearing.

# Additional information

I couldn't reproduce the 'first way' bug in a new database but it was very quick test with only one account and some transactions. I didn't test for the 'second way' bug because I would have to create many accounts.

**Comment by whalley** [comment]
I cannot reproduce... What version of MacOS are you using?

**Comment by rmelillo76** [comment]
Could this be related to #6438 ?

**Comment by whalley** [comment]
Unfortunatley I don't have a machine with 10.13 (oldest I have is 10.15) to test this on.

I wonder if other users with 10.13 have simialr issues?
