### ISSUE TITLE
1.7.0 has compile error when compiling from source

### ISSUE THREAD

**Issue by PMaff** [moneymanagerex/moneymanagerex#6465]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [x] 1.7.1-Beta.1

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Sources via :
`git clone --recursive https://github.com/moneymanagerex/moneymanagerex -b v1.7.0`

Compilation as described in https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux

Error:
```
...
/home/pmaff/Technical/MMEX/1_7_0stable/moneymanagerex/po/ar_SA.po:8579: duplicate message definition...
/home/pmaff/Technical/MMEX/1_7_0stable/moneymanagerex/po/ar_SA.po:8468: ...this is the location of the first definition
/usr/bin/msgfmt: found 37 fatal errors
gmake[2]: *** [po/CMakeFiles/Translations.dir/build.make:109: po/ar_SA.mo] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:314: po/CMakeFiles/Translations.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 29%] Linking CXX static library libHTML-template.a
[ 29%] Built target HTML-template
[ 30%] Linking C static library libSQLite3.a
[ 30%] Built target SQLite3
```

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Simple compile from sources.

```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.7.0
-- Commit         : b38049357 (2023-12-26)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 6.6.11-1-default
-- openSUSE.20240112
-- openSUSE.Tumbleweed
-- CMake 3.28.1
-- GNU Make 4.4.1
-- ccache
-- GNU 13.2.1
-- wxWidgets 3.2.4
-- wxSQLite3 4.9.1
-- Lua 5.4.6
-- curl 8.5.0
-- gettext 0.21.1
-- ------------------ 8< -----------------
-- Configuring done (0.7s)
-- Generating done (0.0s)
```

Expected result:
Compilation creates rpm package on Suse Tumbleweed.

Actual result:
Compilation fails.

Bug also exists for 
```
-- Version        : 1.7.1-Beta.1
-- Commit         : b0f9a671e (2024-01-14)
```

**Comment by whalley** [comment]
I'm not aware of any major build changes..

**Comment by PMaff** [comment]
> I'm not aware of any major build changes..

It is currently not a big issue since I still can use the 1.6.4 stable rpm with wxWidgets 3.2.4 but the question is, what causes this
moneymanagerex/po/ar_SA.po:8579: duplicate message definition...
...
/usr/bin/msgfmt: found 37 fatal errors

**Comment by n-stein** [comment]
> Edit: There seem to be double definitions: e.g.:
> msgid "Vietnamese (Vietnam)"
> msgstr "vi-VN Tiếng Việt (Việt Nam)"
> at line 8579 and 8468 in moneymanagerex/po/ar_SA.po

Confirmed, I encounter this when I attempt to build using the command line as described in BUILD.md. However, I don't normally do this -- I use cmake to generate a CodeLite workspace, and building within CodeLite occurs without errors. This is why I haven't encountered this since we added the common translations in #5410.

The error you noted above means that for some reason the common.po file is being appended multiple times to the po file, which should not occur. The relevant code is here:

https://github.com/moneymanagerex/moneymanagerex/blob/1edc0dfe293837aa8a916222e4ae17dacdbf52c7/po/CMakeLists.txt#L26-L56

Specifically, lines 32-34 append the contents of common.po to the end of each file in the moneymanagerex/po directory prior to gettext compiling the mo file. It seems that when building from the command line it is appending common.po multiple times, hence the "duplicate message definition" error. Not sure why this is occurring from the command line but not through CodeLite.

Maybe some bug in the section I noted above that would cause this?

**Comment by PMaff** [comment]
I am not a po-File expert, but should 
```
     if(CurrentFile MATCHES "common") 
         continue() 
     endif() 
```
end something, if "common" is not matched?

**Comment by n-stein** [comment]
I think I've got it. The key is _don't_ execute `cmake .` in the `moneymanagerex` directory, only execute `cmake ..` in the `moneymanagerex/build` directory.

From BUILD.md:

```
cd moneymanagerex/
mkdir build
cmake . (only sometimes needed) <------ SKIP THIS LINE!
cd build/
cmake ..
```

The root cause is if you run `cmake .` in `moneymanagerex` then `CMAKE_SOURCE_DIR == CMAKE_BINARY_DIR == moneymanagerex` but the code relies on these two directories being different.

**Comment by n-stein** [comment]
If that fixes your issue we should modify BUILD.md to remove the offending line.

**Comment by PMaff** [comment]
Yep I just came to this in the same moment.
Doing only one cmake is the point.
Previously sometime the cmake .. in the build-directory threw errors, which were not coming up, when doing an
additional cmake . in moneymanagerex .
I tried with only cmake . in moneymanagerex and not cmake .. in build-Dir and that works.
mmex-1.7.0-openSUSE.Tumbleweed.x86_64.rpm
is generated.

**Comment by n-stein** [comment]
Ah, good catch. I didn't realize it works either way and that the key is you can't do both.

Do you want to amend BUILD.md with your preferred approach?

**Comment by n-stein** [comment]
If you use `cmake .` instead of `cmake ..` then the build occurs in `moneymanagerex` instead of `moneymanagerex/build` which is a bit messy.

Might be better to:

```
mkdir build
cd build
cmake ..
xport MAKEFLAGS=-j4  (to speed up the build)
cmake --build . --target package
```

Note the last line differs from BUILD.md which says to use `cmake --build ..`. Maybe this is the reason you needed the `cmake .` before?

I can update BUILD.md. Please give it a run through and make sure it works as intended.

**Comment by PMaff** [comment]
When installing from command line I get
```
rpm -ivh ./mmex-1.7.0-openSUSE.Tumbleweed.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	file /usr/share/mime from install of mmex-1.7.0-openSUSE.Tumbleweed.x86_64 conflicts with file from package filesystem-84.87-15.1.x86_64
	file /usr/share/mime/packages from install of mmex-1.7.0-openSUSE.Tumbleweed.x86_64 conflicts with file from package filesystem-84.87-15.1.x86_64
```
on my Suse Tumbleweed.

I tried yast2 where this does not happen. The message about missing signature is ignored by me.
I will try a complete build once more from scratch.

**Comment by n-stein** [comment]
> file /usr/share/mime from install of mmex-1.7.0-openSUSE.Tumbleweed.x86_64 conflicts with file from package filesystem-84.87-15.1.x86_64
> file /usr/share/mime/packages from install of mmex-1.7.0-openSUSE.Tumbleweed.x86_64 conflicts with file from package filesystem-84.87-15.1.x86_64

Possibly related to the changes made for Flatpak builds?

**Comment by PMaff** [comment]
At least yast2 does not complain.

**Comment by PMaff** [comment]
```
CMake Error at
[...]MMEX/1_7_0stable/moneymanagerex/build/cmake_install.cmake:144 (file):
  file INSTALL cannot find
  "[...]MMEX/1_7_0stable/moneymanagerex/org.moneymanagerex.MMEX.metainfo.xml":
  No such file or directory.


CPack Error: Error when generating package: mmex
gmake: *** [Makefile:71: package] Error 1

```

**Comment by n-stein** [comment]
> build/org.moneymanagerex.MMEX.metainfo.xml is obviously not found. ;-)

Odd though because it doesn't say it's looking in build. It says it is looking in moneymanagerex.

> "[...]MMEX/1_7_0stable/moneymanagerex/org.moneymanagerex.MMEX.metainfo.xml":
>   No such file or directory.

**Comment by PMaff** [comment]
cmake .. and cmake --build . --target package ?

**Comment by PMaff** [comment]
org.moneymanagerex.MMEX.metainfo.xml is in build when doing a cmake .. in build
and
build/cmake_install.cmake has:

```
if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/metainfo" TYPE FILE FILES ...
moneymanagerex/org.moneymanagerex.MMEX.metainfo.xml...
```
;-)

**Comment by n-stein** [comment]
Just need to change CMakeLists.txt here:

https://github.com/moneymanagerex/moneymanagerex/blob/1edc0dfe293837aa8a916222e4ae17dacdbf52c7/CMakeLists.txt#L683-L685

to 

```
    install(FILES
        ${CMAKE_BINARY_DIR}/org.moneymanagerex.MMEX.metainfo.xml
        DESTINATION share/metainfo)
```

**Comment by PMaff** [comment]
${CMAKE_BINARY_DIR}/org.moneymanagerex.MMEX.metainfo.xml
works.

**Comment by n-stein** [comment]
I've put these changes into PR #6466. Let's see if the Flatpak CI build plays nice with the tweak. I think it should be OK.

**Comment by PMaff** [comment]
checking with another build for xubuntu 22.04...

**Comment by n-stein** [comment]
It worked for me on Debian 12 for another point of reference.

**Comment by PMaff** [comment]
This also works:
```
Money Manager Ex
• Version: 1.7.0 64-bit
• Built on: Jan 17 2024 01:16:30
• Database version: 19 (aes128cbc)
• Git commit: b38049357 (2023-12-26)
MMEX is using the following support products:
• wxWidgets 3.2.0 RC1 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.4.0
Running on:
• Ubuntu.22.04.jammy
• Ubuntu 22.04.3 LTS "jammy"
• Linux 5.15.0-91-generic x86_64
• XFCE (X11)
...
```

I will update that virtual machine to wxWidget 3.2.4 later on.
I think we can close that ticket.
Thx for your help @n-stein .

**Comment by PMaff** [comment]
mmex-1.7.0-openSUSE.Tumbleweed.x86_64.rpm
and
mmex_1.7.0-Ubuntu.22.04.jammy_amd64.deb
are available if there is the need.

**Comment by n-stein** [comment]
Thanks, will close once we confirm the CI Flatpak build is OK.

**Comment by PMaff** [comment]
libwebkitgtk6_0-4 is version 2.42.4 (boo#1218032) on Suse Tumbleweed if that helps for 
https://github.com/moneymanagerex/moneymanagerex/issues/6214

**Comment by PMaff** [comment]
I have to reopen this issue.
On Ubuntu 18.04 LTS I get

```
...
-- Performing Test Wlogical-op
-- Performing Test Wlogical-op - Success
-- Performing Test Wuseless-cast
-- Performing Test Wuseless-cast - Success
Unknown command 'news-to-metainfo'.
CMake Error at CMakeLists.txt:679 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

when doing 
1_7_0stable/moneymanagerex/build$ cmake ..

**Comment by n-stein** [comment]
> I have to reopen this issue.

I was just about to do this. I found that compilation fails if AppStream version is < 0.15 due to this line failing:

https://github.com/moneymanagerex/moneymanagerex/blob/4d406afa33a6233908cfc55fc0547d239c532c3a/CMakeLists.txt#L679

Error message:

```
Failed to detect section `Miscellaneous:
* #6032 GUI - minor text improvement in Russian
* #5997 MMEX flatpak is not listed on website
* #5962 What does INFOID: 8 relate to please?
* #5686 Budget view crash on double click category summary
* #5656 Show count of selected/filtered/total records in the view'
```

Failure occurs with AppStream 0.14.5 but succeeds with 0.15.2. This means currently building on Ubuntu Bionic (AppStream 0.12.0) or earlier does not work.

**Comment by PMaff** [comment]
I just updated wxWidget 3.2.4 on that machine.

Do you need me to try something on a 1.7.1beta?

**Comment by n-stein** [comment]
No, the issue is AppStream didn't add support for the 'Miscellaneous:' section of a NEWS file until v0.14.6 (specifically this commit https://github.com/ximion/appstream/commit/e815634ffa9b4c0fba90c9b0ae55ccc070e0e9c4).

We need to add a check for appstreamcli --version and skip executing news-to-metainfo if the version is < 0.14.6.

**Comment by n-stein** [comment]
> cmake ..
> Then
> touch /home/.../1_7_0stable/moneymanagerex/build/org.moneymanagerex.MMEX.metainfo.xml
> afterwards compilation was ok.

You can also do:

```
cmake ..
sed -i -e ':a;N;$!ba;s/\n\nMiscellaneous://g' ../NEWS
```

Which just merges the Miscellaneous section into the Bugfixes section in the metainfo.

**Comment by n-stein** [comment]
> You can also do:
> 
> ```
> cmake ..
> sed -i -e ':a;N;$!ba;s/\n\nMiscellaneous://g' ../NEWS
> ```

This works in Ubuntu 20.04 LTS but not in 18.04 LTS. The `news-to-metainfo` command was added in AppStream 0.12.9 and the Bionic repository maxes out at version 0.12.0. I will just copy the metainfo.xml file into ${CMAKE_BINARY_DIR} without merging news if the AppStream version is < 0.14.6.

**Comment by n-stein** [comment]
Also the 1.7.1 beta won't compile with Ubuntu < 23.04 because the `appstreamcli validate --strict` flag wasn't added until AppStream 0.15.4.

**Comment by n-stein** [comment]
Had to bypass metainfo validation when appstreamcli < 0.12.3 since it doesn't support an empty content_rating tag. 

Current beta now builds with all Ubuntu releases >= 18.04.

**Comment by PMaff** [comment]
I can confirm that build works for 
```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Erstellt am: Jan 25 2024 21:27:20
• Datenbankversion: 19 (aes128cbc)
• Git-Eintrag: 714352aa0 (2024-01-24)
• Git Zweig: master
MMEX verwendet folgene Unterstützungsprodukte:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.4.6
• libcurl/8.5.0 OpenSSL/3.1.4 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.5/openssl/zlib nghttp2/1.58.0 OpenLDAP/2.6.6
• gettext 0.21.1
• apexcharts.js
erstellt mit:
• CMake 3.28.1
• GNU Make 4.4.1
• GCC 13.2.1 20240109 [revision 36ddb5230f56a30317630a928dd73ed46eda03f1]
Läuft auf:
• openSUSE.20240124
• openSUSE Tumbleweed ""
• Linux 6.7.1-1-default x86_64
• XFCE (X11)
• Systemsprache: en_GB.utf8
• Sprache der Benutzeroberfläche: de_DE.UTF-8
• 0x0 0-bit 96x96ppi
```

and

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Jan 25 2024 21:35:32
• Database version: 19 (aes128cbc)
• Git commit: 714352aa0 (2024-01-24)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.0 RC1 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.4.0
Running on:
• Ubuntu.22.04.jammy
• Ubuntu 22.04.3 LTS "jammy"
• Linux 5.15.0-92-generic x86_64
• XFCE (X11)
• System Locale: LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_AT.UTF-8;LC_TIME=de_AT.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_AT.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_AT.UTF-8;LC_NAME=de_AT.UTF-8;LC_ADDRESS=de_AT.UTF-8;LC_TELEPHONE=de_AT.UTF-8;LC_MEASUREMENT=de_AT.UTF-8;LC_IDENTIFICATION=de_AT.UTF-8
• User Interface Language: en_US.UTF-8
• 0x0 0-bit 96x96ppi
```

as well as:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.7.1-Beta.1
-- Commit         : 714352aa0 (2024-01-24)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.4.0-170-generic
-- Ubuntu.18.04.bionic
-- Ubuntu.18.04.6.LTS
-- CMake 3.27.4
-- GNU Make 4.1
-- ccache 3.4.1
-- GNU 7.5.0
-- wxWidgets 3.2.4
-- wxSQLite3 4.9.1
-- Lua 5.3.3
-- curl 7.58.0
-- gettext 0.19.8.1
-- ------------------ 8< -----------------
-- Configuring done (1.6s)
-- Generating done (0.0s)
```
