### ISSUE TITLE
Stock performance chart shows tickers of previously held stocks

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#6471]
MMEX version:
 - [x] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I had a stock portfolio, let us call it Portfolio-A, in which I had 3 stocks PPP, QQQ, RRR. I have another portfolio, lets us call it Portfolio-B which held stocks XXX, YYY, ZZZ. If I look at the landing page of "Stocks Report" It would show nice graphs of Stocks Performance Charts (for period of choice) which would show price history of PPP, QQQ, RRR, XXX, YYY and ZZZ.

Lets say that now I sold all my stocks in Portfolio-A and I deactivated the portfolio as well. Now when I launch the Stocks Performance Chart, it still shows the history of all six stocks. For me it makes sense to only have the stocks that are listed in the active portfolio, i.e. Portfolio B, meaning just the histories for stock prices for the tickers XXX, YYY, ZZZ.

Alternatively, if the application could let  the user select which stock price histories to display, that could also solve the issue.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by whalley** [comment]
OK, proposal is to exclude all stocks from the 'Stocks Report' if the 'Investment' Account is CLOSED. Does that work? Note, this would be irrespective of the status of the stocks or any share account?

![CleanShot 2024-01-19 at 17 33 45](https://github.com/moneymanagerex/moneymanagerex/assets/487345/bb91b238-78a1-4c87-b8cf-132a473bd8a1)

**Comment by h-vijayakumaran** [comment]
Yes this should work

**Comment by whalley** [comment]
The Stocks Report Summary did indeed already skip closed Investment accounts. The performance charts should now do the same.
