### ISSUE TITLE
comma not always accepted with different settings

### ISSUE THREAD

**Issue by Flexmaen** [moneymanagerex/moneymanagerex#6474]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

If comma is , (comma) and thousand separator is . (point)  like in the settings de_DE then you cannot overwrite a comma since the thousand seperator (=point) seems to be mistaken for a comma.
I hope this description or title is clear enough. But you can easily reproduce this issue with the following steps:

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. In the Settings (Extra/Options/General) set "de_DE" as currency format, which will be 1.234.567,89
2. create a new bank account with 1500,50 which will turn into 1.500,50
3. right click bank account and select "edit account"
4. for example, value there is "1.500,50" you want to change it to "1.580,90"
5. delete last 4 digits, start typing. You cannot type a comma anymore (,) since the point (.) is mistaken for a comma.

Expected result:

You should be able to type a , even if a . is alredy seperating the value.

Additional Information:

Select/overwrite 4 digits:
![mmex_step1](https://github.com/moneymanagerex/moneymanagerex/assets/6330276/c2af1425-bc54-4838-8921-cea7a74e8801)

No comma (,) accepted:
![mmex_step2](https://github.com/moneymanagerex/moneymanagerex/assets/6330276/293f977d-a9dd-4350-8ee4-bc6bfb076cb6)

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6441

**Comment by Flexmaen** [comment]
I did read #6441 but this is a different issue.
I the case here you can neither ad a , or a . since the . which seperates the thousands in this settings is mistaken for being a decimal seperator.

**Comment by n-stein** [comment]
The amount fields are designed to allow only one decimal to be entered. However, they always check using the currency decimal separator, not the locale decimal separator even though they display using the locale separator, if it is defined in settings.

I have changed the amount fields to use the locale decimal separator when a locale is defined in settings, otherwise it will use the currency decimal separator. This should resolve your issue.
