### ISSUE TITLE
How can I stop the pop up "Specify any text notes you want to add to this transaction" when my mouse is in notes field?

### ISSUE THREAD

**Issue by tccadam** [moneymanagerex/moneymanagerex#6478]
When I click in the notes field, that pop up window appears "Specify any text notes you want to add to this transaction" and doesn't go away.  It's always blocking the text behind it and I have to click and play with the mouse until it disappears. Drives me crazy. Any way to disable that pop up hover thing?

**Comment by whalley** [comment]
You can turn tootips off in the settings...
![CleanShot 2024-01-23 at 19 07 00](https://github.com/moneymanagerex/moneymanagerex/assets/487345/9475a185-1c41-4edd-aac0-5e592ac357fb)
