### ISSUE TITLE
Transaction Report Filter Saved Settings - Category is cleared on focus if it contains a regular expression or a Category not in the list

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#6480]
MMEX version:
 - [x] 1.7.0

Operating System:
 - [x] Windows

On the Transaction Filter dialog, the Category drop down value is cleared out as soon as it receives focus, but only when it contains a regex or a Category not in the list (may have existed before, but is now deleted). This occurs when editing a saved setting and does not happen when initially adding the filter setting. And it never happens with a category that is in the auto complete list.

For example, use the following regular expression and save it:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/ff11a3f5-96d8-4c42-a4b3-08de81c35156)

Next, edit the filter and tab into or click the drop down. The value is removed:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/d21b9792-a744-4d46-aefa-1713f4cd5487)

Interestingly, if you type it back in and tab out and back into the field it is not removed, so it seems to happen only upon first focus. 

# Reproduction

Is the bug reproducible? 
 - [x] Only when the setting is being edited, and only initially receiving focus. 

Expected result:
The value should remain. 

Actual result:
The value is cleared out.

**Comment by n-stein** [comment]
Fixed

**Comment by rmelillo76** [comment]
Confirmed, thanks! I also updated the title and description after looking at the code, since it had to do with the value not in the auto complete list, not specifically a regex pattern. (I added another filter using a real category, then deleted that category and was able to reproduce it, and confirmed the new build handles it fine).
