### ISSUE TITLE
Bad desktop file

### ISSUE THREAD

**Issue by rezso** [moneymanagerex/moneymanagerex#6489]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [ ] Mac OSX
 - [x ] Linux 

# Description of the bug
desktop-file-validate fails on the desktop file:
sr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[cs]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[de]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[en]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[en_AU]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[en_GB]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[es]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[fi]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[fr]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[hu]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[is]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[it]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[kn]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[ko]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[lv]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[nl]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[no_NY]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[pt]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[pt_BR]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[ro]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[ru]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[sk]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[sl]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[tr]" in group "Desktop Entry", but "Categories" is not defined as a locale string
usr/share/applications/org.moneymanagerex.MMEX.desktop: error: file contains key "Categories[uk]" in group "Desktop Entry", but "Categories" is not defined as a locale string

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by n-stein** [comment]
Per the desktop file [spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) `Categories` values cannot be localized (type is `string` instead of `localestring` or `iconstring`.

**Comment by n-stein** [comment]
@ovari maybe you want to handle this one?

**Comment by ovari** [comment]
Is the solution to delete all the Categories localization lines, i.e. https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/applications/org.moneymanagerex.MMEX.desktop#L140-L163 ?

Don't understand how to do `localestring`.

Thank you

**Comment by n-stein** [comment]
> Is the solution to delete all the Categories localization lines

I think that may be the only solution.
