### ISSUE TITLE
Window "Currency rate updated" to big, no scroll (Mac)

### ISSUE THREAD

**Issue by alex-gee** [moneymanagerex/moneymanagerex#649]
If I update the currency rates the resulting window is to big and has no scroll.

![mmex_report](https://cloud.githubusercontent.com/assets/1726021/12305372/bd60a6ce-ba34-11e5-9b22-12f22db7cf96.png)

**Comment by vomikan** [comment]
Thanks for report this issue. It seems minor bug in case if this window may be close by Esc button.
As workaround here I reccommend to update currencies after DB initialization and only for really used currencies.

**Comment by omalleypat** [comment]
There is a similar issue for stock prices update.

**Comment by vomikan** [comment]
This code should help
~~~~~
        wxMessageDialog msgDlg(this, _("Currency rate updated"), _("Currency rates"), 5L|wxHELP);
        msgDlg.SetHelpLabel(_("Log"));
        if (!hide)
        {
            if (msgDlg.ShowModal() == wxID_HELP)
            {
                wxMessageDialog msgDlg2(this, msg, _("Currency rate updated"));
                msgDlg2.ShowModal();
            }
        }
~~~~~

**Comment by vomikan** [comment]
![screenshot 85](https://cloud.githubusercontent.com/assets/6836805/18353931/7f2304d2-75ec-11e6-9ab5-67a8ffa4b228.jpg)
