### ISSUE TITLE
ERROR SCROLL DOWN ON ALL REG

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#6491]
MMEX version:
 - [ ] 1.6.4
 - [] 1.7.0
 - [x ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details. The problem is related to **scrolling down all registrations**. At around 70/80 a DEBUG message appears.

Add screenshot or other files if needed. YES Attached the screen of the error and the database.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: Select All Transaction and scroll dow. NOTE the transaction uclude te TAGS. The same versione withot the TAGS work fine.
![error](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/cd6f0493-48ff-483f-ad3a-6dcecdff58b1)
[DATI - ACSondrio - 2024.zip](https://github.com/moneymanagerex/moneymanagerex/files/14076964/DATI.-.ACSondrio.-.2024.zip)

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by MAPA2023** [comment]
![ERROR ALL](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/5567e6af-16d7-46c9-af58-811af64c75da)

**Comment by whalley** [comment]
Looks as if there are two TAGLINK entries pointing at TAGID = -1 resulting in the crash.

@n-stein Any idea what could have caused these? 
Should we protect against the crash in Model_Taglink::get() ?

**Comment by whalley** [comment]
@MAPA2023 Do you tend to take early Beta versions? Did you take the early v1.7.0 Beta releases that included the Tags feature? I'm just wondering for some issues arose then.

**Comment by n-stein** [comment]
> Did you take the early v1.7.0 Beta releases that included the Tags feature?

I was going to ask the same. I had this happen in one of my test databases. My theory was at some point the code was written such that a new tag had been created in the cache and then immediately linked to the transaction prior to being saved in the db, so at that point it didn't have a valid TAGID.

**Comment by whalley** [comment]
@MAPA2023  - To fix you database....

Unzip the attached file and save it.

After backing up your database open it up, and before doing anything else, select the following from the menus:

TOOLS -> DATABASE -> DATABASE CHECK AND DEBUG...

The integrity check should report "ok", then press OK. The select "YES" to the "Do you want to proceed?" option and select the .mmdg file you have extracted from the zip. Open it and you should get a success message.

Now close MMEX and open again with your database.

[taglink_fix.zip](https://github.com/moneymanagerex/moneymanagerex/files/14088979/taglink_fix.zip)

**Comment by MAPA2023** [comment]
I also tried on version 1.7.0 and it's the same thing. What do you recommend to redo all the Tags?

**Comment by whalley** [comment]
@MAPA2023 Apply the fix I noted above.

**Comment by MAPA2023** [comment]
@whalley Thanks, I reread it carefully and everything is clear. When saving I saved to the copy of the zip file you provided and everything works. Thank you.
