### ISSUE TITLE
MMEX Instance Check Closes after 3 seconds

### ISSUE THREAD

**Issue by PKCMVA** [moneymanagerex/moneymanagerex#6499]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
I tried to open the MMEX today but get the "MMEX Instance Check" window popup.  It then closes down after 3 or 4 seconds.  Tried re-installing, rebooting and shutting down but nothing helps. 

Add screenshot or other files if needed.
![Money Manager Ex Crashing](https://github.com/moneymanagerex/moneymanagerex/assets/87059822/c81bdbb2-7e29-4389-8f7c-0b4edd8f57c5)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
What happens if you press "Yes" ? Your description implies it closes down once the dialog is presented.

When it closes down does it report any messages?

**Comment by PKCMVA** [comment]
Hi, When I press the "Yes" my current saved database opens but closes after about 3 seconds.  Scanning the window before it closes, all looked normal except Income & Expenses windows has zero balance for both which is wrong.  I had it set for 21 days and is now showing month to date.

**Comment by whalley** [comment]
Can send the database to support@moneymanagerex.org so I can look at this. I assure you that the database will only be used to diagnose this issue and will be deleted once this is complete.

**Comment by whalley** [comment]
Could you also try the latest 1.7.1 Beta https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/4e40ui84y0vvcbaf/artifacts

**Comment by PKCMVA** [comment]
I installed the v1.7.1 beta and it seems to have fixed the issue.  Only things I had to change back was the Income & Expenses window to 21 days and the theme from green to colour.  Closed and opened a few times just to make sure it stayed the same and did.  If you still need the database to check things let me know.

**Comment by whalley** [comment]
Great. There were a few crashes fixed soon after v1.7.0 was released. Good that they solved your issue.

**Comment by PKCMVA** [comment]
Thanks for your time and help, much appreciated.
