### ISSUE TITLE
Notes Field display doesn't auto wrap text lineas too long

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/moneymanagerex#650]
Desktop Ver.1.2.4
1.- Enter this dummy character line in notes field:
1111111111111111111111111111111111111111111222222222222222222222222222333333333333333333333333333333334444444444444444444444444444444555555555555555555555555555555555555555556666666666666666677777777777.
2.- Save the transaction.
3.- The bottom view of the account view window trunk the line. I don't auto wrap the excess into new line.

**Comment by vomikan** [comment]
Practically it can't be so length a text string.
