### ISSUE TITLE
Move transactions

### ISSUE THREAD

**Issue by xdodo49** [moneymanagerex/moneymanagerex#6503]
# Description of the feature

Move same-dated transactions up or down to maintain chronological order

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by n-stein** [comment]
Seems like a reasonable request. I know we have had some complaints about the Date+ID sort order lock, so this could help.

Have you thought about the mechanics of how it would work? Maybe Ctrl + Up/Down arrow to move the transaction? Do we allow a transaction to be moved any time, or only when sorted by date?

**Comment by whalley** [comment]
Would this not be better acheived by implementing this:  https://github.com/moneymanagerex/moneymanagerex/issues/2729. the use can then better order chronologically.

**Comment by n-stein** [comment]
> Would this not be better acheived by implementing this: #2729. the use can then better order chronologically.

Good point. Two birds, one stone. Let me work on #2729.

**Comment by DevelopmentAnything** [comment]
#5873 제가 원하던 기능입니다.
MMEX v2에서는 거래 날짜 필드 속성을 datetime로 만들면 좋겠습니다.
😍😍😍

**Comment by n-stein** [comment]
> 제가 원하던 기능입니다. 
> MMEX v2에서는 거래 날짜 필드 속성을 datetime로 만들면 좋겠습니다.

> Translation:
> This is a feature I've been wanting.
> In MMEX v2, it would be nice to make the transaction date field attribute a datetime.

This is completed for 1.7.1. Just go into Tools -> Options -> View Options and enable `Use 'Time' in transaction recording/reporting`

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/dbe1b72c-28fc-4bd9-abba-a57e76eafd4d)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/78e3db6e-399f-4ba0-9555-3631e1ee08d4)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f63a4d7b-a978-4b6b-b30d-ec087433c0b8)


@xdodo49 This allows you to reorder the same-dated transactions by changing the times.

**Comment by DevelopmentAnything** [comment]
> ![image](https://private-user-images.githubusercontent.com/16599929/309962240-f63a4d7b-a978-4b6b-b30d-ec087433c0b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTk5NTcsIm5iZiI6MTcwOTYxOTY1NywicGF0aCI6Ii8xNjU5OTkyOS8zMDk5NjIyNDAtZjYzYTRkN2ItYTk3OC00YjZiLWIzMGQtZWMwODc0MzNjMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA2MjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjA1ZmU3MTY2ODIyMjM0M2NjMzNkYjQyZjdkYThlYTc1Y2MzNmI1MDg2MTdlMzA4NDdhNjI2ZTAwYmQ1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33nuguLojxo3AwWc8kJNkwwzriSm08Xr4pF7ttlEQ2c)

No matter how hard I try, the transaction list only shows 00:00:00. I have to open the dialog to see the time I set.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/b62aa60a-bdb5-459c-8e51-605c3636b2c5)

Is this issue reported? Do I have to write a bug report?
or....is bug only on Windows 11 again? 😢

**Comment by vomikan** [comment]
I can confirm the bug.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/ad58dff5-6cb9-498e-9c24-14bbbe1d8e0b)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/d8897233-787a-4b56-a5a0-4fab2f70eb65)

**Comment by n-stein** [comment]
> is bug only on Windows 11 again?

No, it must be something else. You can see from the screenshots the time displays correctly on my Windows 11 system.

**Comment by DevelopmentAnything** [comment]
> No, it must be something else. You can see from the screenshots the time displays correctly on my Windows 11 system.

I just found out the cause.
My DB migrated from 1.7.0, and the time is always shown as 00:00:00.
However, if create a new DB and create a transaction, the transaction time will be displayed normally. 12:34:56.
There seems to be a problem with the code migrating the DB.

If someone doesn't solve this problem, I think I'll have to give up again. 😢

**Comment by DevelopmentAnything** [comment]
> No, it must be something else. You can see from the screenshots the time displays correctly on my Windows 11 system.

I just found out the cause.
My DB migrated from 1.7.0, and the time is always shown as 00:00:00.
However, if create a new DB and create a transaction, the transaction time will be displayed normally. 12:34:56.

**Comment by n-stein** [comment]
> My DB migrated from 1.7.0, and the time is always shown as 00:00:00.\nHowever, if create a new DB and create a transaction, the transaction time will be displayed normally. 12:34:56.

Strange, there was no database change between 1.7.0 and 1.7.1 so functionally there should be no difference in an old vs new database. Not sure what's going on here...

**Comment by vomikan** [comment]
I think time widgets are useless here.
It is better to remove them altogether or make the time a separate line, as well as the date.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/1356f32c-2566-44aa-b5fd-63cb5c77ba00)

**Comment by vomikan** [comment]
Let's say I bought something at 1:00 p.m. during the last week.
I will not be able to find the transaction by specifying the time in the current implementation.

**Comment by whalley** [comment]
> Let's say I bought something at 1:00 p.m. during the last week. I will not be able to find the transaction by specifying the time in the current implementation.

OK, understand what you are saying, but thats another search criteria. Having a time range independent of the Period Range / Date Range may indeed be useful. Suggest we create another issue for this enhancement.

**Comment by DevelopmentAnything** [comment]
> or make the time a separate line, as well as the date.

(Korean)

이 말에 전적으로 동의합니다.

@whalley 말대로 한다면 문제점이 하나 있습니다.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/a8f85c90-2dbe-4034-a82e-a74e3b823170)

넓은 범위의 날짜를 검색할 때 중간에 있는 날짜는 항상 24h간으로 시간 필터링이 적용되지 않습니다. 즉, 시작과 끝 날짜에만 시간 필터가 적용됩니다. 또한, 시작과 끝 날짜는 순차 정렬을 통해 쉽게 알아볼 수 있습니다. 비효율적입니다.

@vomikan 말대로 시간 필터를 다음 줄에 별도로 만든다면 장점이 있습니다.

넓은 범위의 날짜에서 특정 시간대의 거래를 검색할 수 있습니다.

예) 수천~수만 개의 거래 내역에서, AM 10:00 ~ PM 12:00 사이에 거래한 기록을 찾고 싶다면? (첨부 그림 참고)
 @whalley 처럼 적용한다면 찾을 수가 없습니다. 하지만 @vomikan 처럼 적용한다면 쉽게 찾을 수 있습니다.

SQL 처리 방법도 간단해집니다. 옛 DB에서는 초단위의 unix timstamp 를 사용했지만, 현재 DB는 ISO YMDTHms 형식이므로 쉽게  substring이 가능하고 group by가 쉽습니다.

**Comment by DevelopmentAnything** [comment]
> Strange, there was no database change between 1.7.0 and 1.7.1 so functionally there should be no difference in an old vs new database. Not sure what's going on here...

I found out one more thing.
The time value is not saved in the existing DB. When MMEX is restarted, the time value of the transaction data changes to 00:00:00 again. the new DB is noproblem.
Both DBs are in the same folder and have the same access rights.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/5d9bf5ef-1229-4156-8f8f-eab9221de9c9)
using my DB. migrated from 1.6.x to 1.7.1

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/997cec57-5173-419a-9ebf-b1a0675e8e08)
create new DB 1.7.1

TRANSDATE column does not change to T format.

**Comment by n-stein** [comment]
> @whalley 처럼 적용한다면 찾는데 시간이 걸리며 필터가 제 역할을 하지 못합니다. 하지만 @vomikan 처럼 적용한다면 쉽게 찾을 수 있습니다. 시간대별 통계 및 보고서 작성에도 사용할 수 있습니다.

I think @whalley was agreeing with @vomikan that a time filter is necessary for filtering exclusively by time across multiple dates, he just suggested it be raised as a separate enhancement request as this issue relates to display order of transactions which is not directly related.

> SQL 처리 방법도 간단해집니다. 옛 DB에서는 초 형식의 unix timestamp 를 사용해서 어렵고 속도가 느렸지만, 현재 DB는 ISO YMDTHms 형식이므로 쉽게 substring이 가능하고 group by가 쉽고 빠릅니다.

The date was not previously stored as a unix timestamp in the database, it has always been an ISO formatted date string Y-M-D.

**Comment by vomikan** [comment]
@DevelopmentAnything could you test the following build?
https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49335095/job/wotbb3n555ls9cf5/artifacts

The changes are: https://github.com/moneymanagerex/moneymanagerex/pull/6555/files

**Comment by vomikan** [comment]
Preferred design
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/93f1629c-a043-46b0-a57c-94a882ac362b)

https://github.com/moneymanagerex/moneymanagerex/discussions/6558

**Comment by n-stein** [comment]
#6581
