### ISSUE TITLE
Cannot build 1.7.0 from source

### ISSUE THREAD

**Issue by h-vijayakumaran** [moneymanagerex/moneymanagerex#6506]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I am unable to build mmex from source. Below is the output from my terminal. Not sure what exactly is the issue here. Any help would be much appreciated :)

```
moneymanagerex/src/general_report_manager.h:102:22: error: ‘wxWebViewEvent’ has not been declared
  102 |     void OnNewWindow(wxWebViewEvent& evt);
      |                      ^~~~~~~~~~~~~~
moneymanagerex/src/general_report_manager.h:107:5: error: ‘wxWebView’ does not name a type
  107 |     wxWebView* browser_ = nullptr;
      |     ^~~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::createOutputTab(wxNotebook*, int)’:
moneymanagerex/src/general_report_manager.cpp:413:5: error: ‘browser_’ was not declared in this scope
  413 |     browser_ = wxWebView::New();
      |     ^~~~~~~~
moneymanagerex/src/general_report_manager.cpp:413:16: error: ‘wxWebView’ has not been declared
  413 |     browser_ = wxWebView::New();
      |                ^~~~~~~~~
moneymanagerex/src/general_report_manager.cpp:420:43: error: ‘wxWebViewHandler’ was not declared in this scope; did you mean ‘wxEvtHandler’?
  420 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                           ^~~~~~~~~~~~~~~~
      |                                           wxEvtHandler
moneymanagerex/src/general_report_manager.cpp:420:59: error: template argument 1 is invalid
  420 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                                           ^
moneymanagerex/src/general_report_manager.cpp:420:65: error: expected type-specifier before ‘wxWebViewFSHandler’
  420 |     browser_->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
      |                                                                 ^~~~~~~~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp:422:10: error: ‘wxEVT_WEBVIEW_NEWWINDOW’ was not declared in this scope; did you mean ‘wxEVT_LEAVE_WINDOW’?
  422 |     Bind(wxEVT_WEBVIEW_NEWWINDOW, &mmGeneralReportManager::OnNewWindow, this, mmID_BROWSER);
      |          ^~~~~~~~~~~~~~~~~~~~~~~
      |          wxEVT_LEAVE_WINDOW
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnUpdateReport(wxCommandEvent&)’:
moneymanagerex/src/general_report_manager.cpp:690:9: error: ‘browser_’ was not declared in this scope
  690 |         browser_->SetPage(report->DESCRIPTION, "");
      |         ^~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnRun(wxCommandEvent&)’:
moneymanagerex/src/general_report_manager.cpp:706:9: error: ‘browser_’ was not declared in this scope
  706 |         browser_->ClearBackground();
      |         ^~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::OnSelChanged(wxTreeEvent&)’:
moneymanagerex/src/general_report_manager.cpp:825:9: error: ‘browser_’ was not declared in this scope
  825 |         browser_->SetPage(description, "");
      |         ^~~~~~~~
moneymanagerex/src/general_report_manager.cpp: In member function ‘void mmGeneralReportManager::showHelp()’:
moneymanagerex/src/general_report_manager.cpp:1085:5: error: ‘browser_’ was not declared in this scope
 1085 |     browser_->LoadURL(url);
      |     ^~~~~~~~
moneymanagerex/src/general_report_manager.cpp: At global scope:
moneymanagerex/src/general_report_manager.cpp:1261:6: error: variable or field ‘OnNewWindow’ declared void
 1261 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |      ^~~~~~~~~~~~~~~~~~~~~~
moneymanagerex/src/general_report_manager.cpp:1261:42: error: ‘wxWebViewEvent’ was not declared in this scope; did you mean ‘wxDataViewEvent’?
 1261 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |                                          ^~~~~~~~~~~~~~
      |                                          wxDataViewEvent
moneymanagerex/src/general_report_manager.cpp:1261:58: error: ‘evt’ was not declared in this scope; did you mean ‘ecvt’?
 1261 | void mmGeneralReportManager::OnNewWindow(wxWebViewEvent& evt)
      |                                                          ^~~
      |                                                          ecvt
gmake[2]: *** [src/CMakeFiles/mmex.dir/build.make:398: src/CMakeFiles/mmex.dir/general_report_manager.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:343: src/CMakeFiles/mmex.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

```

**Comment by n-stein** [comment]
How did you build wxWidgets? Maybe you forgot `--enable-webview`?

`../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl`

**Comment by h-vijayakumaran** [comment]
Tried this, still getting the same errors, unfortunately

**Comment by PMaff** [comment]
I configured wxWidget 3.2.4 a bit different than @n-stein with
`...wxWidgets/buildgtk$ ../configure --disable-shared --enable-stl --enable-utf8only --enable-intl  --enable-xlocale  --enable-webviewwebkit --with-gtk=3`
( @n-stein do you see any problems with this config?)

```
Configured wxWidgets 3.2.4 for `x86_64-pc-linux-gnu'

  Which GUI toolkit should wxWidgets use?                 GTK+ 3 with support for GTK+ printing libnotify
  Should wxWidgets be compiled into single library?       no
  Should wxWidgets be linked as a shared library?         no
  Should wxWidgets support Unicode?                       yes (using wchar_t)
  What level of wxWidgets compatibility should be enabled?
                                       wxWidgets 2.8      no
                                       wxWidgets 3.0      yes
  Which libraries should wxWidgets use?
                                       STL                yes
                                       jpeg               sys
                                       png                sys
                                       regex              sys
                                       tiff               sys
                                       lzma               no
                                       zlib               sys
                                       expat              sys
                                       libmspack          no
                                       sdl                no
```


I also compiled the samples, @h-vijayakumaran ,  so maybe you can check, if compiling the wxWidget samples also results in such error messages.

so:
`make `
and
`make samples`
Samples are then in buildgtk/samples in my case.

If the samples are working (  ./samples/webview/webview , ./samples/minimal/minimal , ./samples/wizard/wizard )
then try to build mmex 1.7.0 .

@n-stein or @whalley can you label this ticket as "Linux"?

**Comment by n-stein** [comment]
@h-vijayakumaran what distro are you using?

**Comment by h-vijayakumaran** [comment]
> @h-vijayakumaran what distro are you using?

Ubuntu 22.04 LTS

**Comment by h-vijayakumaran** [comment]
> I also compiled the samples, @h-vijayakumaran , so maybe you can check, if compiling the wxWidget samples also results in such error messages.
> 
> so: `make ` and `make samples` Samples are then in buildgtk/samples in my case.
> 
> If the samples are working ( ./samples/webview/webview , ./samples/minimal/minimal , ./samples/wizard/wizard ) then try to build mmex 1.7.0 .

When I do this, the `minimal` and `wizard` are working. There is no directory `webview` though

**Comment by n-stein** [comment]
> There is no directory webview though

This is odd because it is there in the github source. Seems like your wxWidgets might be incomplete.

For reference, here's how I build on 22.04 LTS from a completely clean install:

Install dependencies:

```
sudo apt install -y --no-install-recommends \
      cmake build-essential libssl-dev gettext git pkg-config lsb-release file ccache \
      libgtk-3-dev liblua5.3-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev wget appstream
```
Build wxWidgets:

```
mkdir dev
cd dev

wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxWidgets-3.2.4.tar.bz2

tar -xjf wxWidgets-3.2.4.tar.bz2

cd wxWidgets-3.2.4
mkdir build-linux
cd build-linux

../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl

make -j$(nproc)

sudo make install

sudo ldconfig
```

Build MMEX:

```
cd ../..

git clone --recursive https://github.com/moneymanagerex/moneymanagerex -b v1.7.0

cd moneymanagerex
touch org.moneymanagerex.MMEX.metainfo.xml

mkdir build
cd build

cmake ..

export MAKEFLAGS=-j$(nproc)

cmake --build . --target package
```

**Comment by h-vijayakumaran** [comment]
I am able to build now, but when I install, I get the following error:
```
The following packages have unmet dependencies:
 mmex : Depends: libpng15 (= 1.5.30) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I don't get this error when I install the deb package shared by @n-stein in https://github.com/moneymanagerex/moneymanagerex/issues/6396#issuecomment-1896286439

**Comment by PMaff** [comment]
> I am able to build now, but when I install, I get the following error:
> 
> ```
> The following packages have unmet dependencies:
>  mmex : Depends: libpng15 (= 1.5.30) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> I don't get this error when I install the deb package shared by @n-stein in [#6396 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/6396#issuecomment-1896286439)

Strange, that you have 1.5.30 on Ubuntu 22.04.
I have libpng-dev 1.6.34-1ubuntu0.18.04.2 on Ubuntu 18.04 .

```
dpkg -l | grep libpng
...
ii  libpng-dev:amd64                                                 1.6.34-1ubuntu0.18.04.2                              amd64        PNG library - development (version 1.6)
ii  libpng-tools                                                     1.6.34-1ubuntu0.18.04.2                              amd64        PNG library - tools (version 1.6)
ii  libpng16-16:amd64                                                1.6.34-1ubuntu0.18.04.2                              amd64        PNG library - runtime (version 1.6)

```

**Comment by PMaff** [comment]
@h-vijayakumaran what happens if you do
```
mkdir <somedirectorywhereyoucanbuild>/wxWidget3_2_4
cd <somedirectorywhereyoucanbuild>/wxWidget3_2_4

git clone https://github.com/wxWidgets/wxWidgets -b v3.2.4

cd wxWidgets

git submodule init

git submodule update

mkdir buildgtk
cd buildgtk/

../configure --disable-shared --enable-stl --enable-utf8only --enable-intl  --enable-xlocale  --enable-webviewwebkit --with-gtk=3
```

you should then have at the end:
```
...
Configured wxWidgets 3.2.4 for `x86_64-pc-linux-gnu'

  Which GUI toolkit should wxWidgets use?                 GTK+ 3 with support for GTK+ printing libnotify
  Should wxWidgets be compiled into single library?       no
  Should wxWidgets be linked as a shared library?         no
  Should wxWidgets support Unicode?                       yes (using wchar_t)
  What level of wxWidgets compatibility should be enabled?
                                       wxWidgets 2.8      no
                                       wxWidgets 3.0      yes
  Which libraries should wxWidgets use?
                                       STL                yes
                                       jpeg               sys
                                       png                sys
                                       regex              sys
                                       tiff               sys
                                       lzma               no
                                       zlib               sys
                                       expat              sys
                                       libmspack          no
                                       sdl                no

```

then (if you have 8 cores):
```
make -j 8

make -j8 samples
```
That will take some time.
Afterwards you should have 
```
buildgtk> ./samples/webview/webview
buildgtk> ./samples/minimal/minimal
buildgtk> ./samples/wizard/wizard
```
and all the other samples in the samples directory.

`sudo make install`

will install this wxWidget 3.2.4 on your machine.
Check with
`wx-config --version`

After that erase the moneymanagerex directory from above and start mmex build from
scratch in some 
`mkdir <somedirectorywhereyoucanbuild>/MMEX`
just like @n-stein  described above.

If mmex was ready, what happens if you do not install mmex but
make a backup of your .mmb database and
 test mmex with
`[...]/MMEX/moneymanagerex/build$ ./_CPack_Packages/Linux/DEB/mmex-1.7.0-Linux/usr/bin/mmex`

Does this work?

**Comment by PMaff** [comment]
Tiny remark beside 1.7.0 :
@n-stein on the latest mmex:
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.7.1-Beta.1
-- Commit         : 138dc6b58 (2024-03-02)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.15.0-97-generic
-- Ubuntu.22.04.jammy
-- Ubuntu.22.04.4.LTS
-- CMake 3.22.1
-- GNU Make 4.3
-- ccache 4.5.1
-- GNU 11.4.0
-- wxWidgets 3.2.4
-- wxSQLite3 4.9.1
-- RapidJSON 1.1.0
-- Lua 5.3.6
-- curl 7.81.0
-- gettext 0.21
```


I get an error when compiling on 18.04 and 22.04  :

```
[ 46%] Building CXX object src/CMakeFiles/mmex.dir/general_report_manager.cpp.o
.../moneymanagerex/src/filtertrans.cpp: In member function ‘void mmFilterTransactions::setDateRange(wxDateTime, wxDateTime)’:
.../moneymanagerex/src/filtertrans.cpp:42:35: error: could not convert ‘wxDateTime::FormatISOTime() const().wxString::operator=(((const char*)"00:00:00"))’ from ‘wxString’ to ‘bool’
   42 |     if (startDate.FormatISOTime() = "00:00:00")
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
      |                                   |
      |                                   wxString
```

I guess you know this already.

**Comment by n-stein** [comment]
> I guess you know this already.

I did not. Honestly I'm really surprised it built written like that... Have fixed it in #6543.

**Comment by n-stein** [comment]
> I am able to build now, but when I install, I get the following error:
> 
> ```
> The following packages have unmet dependencies:
>  mmex : Depends: libpng15 (= 1.5.30) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> I don't get this error when I install the deb package shared by @n-stein in [#6396 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/6396#issuecomment-1896286439)

Hmm. That build was on Ubuntu 22.04 LTS minimal server, I'm assuming you're building on desktop version? Are all your packages up to date?

**Comment by h-vijayakumaran** [comment]
> Does this work?

Yes it does! Thank you very much for helping me through this. It would be great if these steps could be included in the build documentation :)
I am also able to build the latest beta version

**Comment by n-stein** [comment]
Strange, there should be no difference between pulling the 3.2.4 source from GitHub and downloading the 3.2.4 tar.bz2 bundled source which already contains the required submodules.

**Comment by PMaff** [comment]
> Strange, there should be no difference between pulling the 3.2.4 source from GitHub and downloading the 3.2.4 tar.bz2 bundled source which already contains the required submodules.
> 
> I would guess it has more to do with the configuration options.

I always used the version from github.
Shall/can we compare the existing files in the tar version with the github version?
I can make a list of md5sums .

**Comment by PMaff** [comment]
> > I am able to build now, but when I install, I get the following error:
> > ```
> > The following packages have unmet dependencies:
> >  mmex : Depends: libpng15 (= 1.5.30) but it is not installable
> > E: Unable to correct problems, you have held broken packages.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't get this error when I install the deb package shared by @n-stein in [#6396 (comment)](https://github.com/moneymanagerex/moneymanagerex/issues/6396#issuecomment-1896286439)
> 
> Hmm. That build was on Ubuntu 22.04 LTS minimal server, I'm assuming you're building on desktop version? Are all your packages up to date?

Most of the people will build/run on a desktop Ubuntu (so do I).
I wonder where version 1.5.30 for libpng comes from on the build server.
See my versions above for Ubuntu 18.04 and 22.04, they are all newer than 1.5.30 .

**Comment by n-stein** [comment]
> I wonder where version 1.5.30 for libpng comes from on the build server.

Based on what @h-vijayakumaran noted above, the version I built on Ubuntu server installed fine and did not require libpng 1.5.30. It was the version he attempted to build on desktop 22.04 (using the same exact process) that wouldn't install due to the libpng dependency.

In fact, my Ubuntu server has:
```
apt list libpng-dev
Listing... Done
libpng-dev/jammy,now 1.6.37-3build5 amd64 [installed,automatic]
```

**Comment by PMaff** [comment]
> > I wonder where version 1.5.30 for libpng comes from on the build server.
> 
> Based on what @h-vijayakumaran noted above, the version I built on Ubuntu server installed fine and did not require libpng 1.5.30. It was the version he attempted to build on desktop 22.04 (using the same exact process) that wouldn't install due to the libpng dependency.
> 
> In fact, my Ubuntu server has:
> 
> ```
> apt list libpng-dev
> Listing... Done
> libpng-dev/jammy,now 1.6.37-3build5 amd64 [installed,automatic]
> ```

Ok, it was may false idea the the build server (not your Ubuntu server) has some wrong libpng version.
That was nonsense from me.
Sorry.

**Comment by PMaff** [comment]
> > I guess you know this already.
> 
> I did not, the CI builds are all passing. Honestly I'm really surprised it built written like that... Have fixed it in #6543.

-- MMEX configuration summary
-- ==========================
-- Version        : 1.7.1-Beta.1
-- Commit         : 141f73915 (2024-03-04)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.15.0-97-generic
-- Ubuntu.22.04.jammy
-- Ubuntu.22.04.4.LTS
-- CMake 3.22.1
-- GNU Make 4.3
-- ccache 4.5.1
-- GNU 11.4.0
-- wxWidgets 3.2.4
-- wxSQLite3 4.9.1
-- RapidJSON 1.1.0
-- Lua 5.3.6
-- curl 7.81.0
-- gettext 0.21
-- ------------------ 8< -----------------
-- Configuring done
-- Generating done

builds ok for me also and runs ok.
I tested with
.../MMEX/latest/moneymanagerex/build$ ./_CPack_Packages/Linux/DEB/mmex-1.7.1-Beta.1-Linux/usr/bin/mmex 
Installation on virtual 22.04 is also fine.



The latest version on Ubuntu 18.04 is also ok and runs ok

**Comment by PMaff** [comment]
> > I guess you know this already.
> 
> I did not, the CI builds are all passing. Honestly I'm really surprised it built written like that... Have fixed it in #6543.

It is strange, that the CI builds are passing with that.
Are there some different compile options?

**Comment by PMaff** [comment]
> This will generate the `mmex_1.7.0-Ubuntu.22.04.jammy_amd64.deb` package in the moneymanagerex/build directory.

@n-stein I tried your build method also with the tar.bz2 of wxWidget 3.2.4,
compiled mmex 1.7.0 from scratch again, but I did not get the libpng15 error when installiing the .deb file.

**Comment by PMaff** [comment]
@h-vijayakumaran and/or @n-stein : do you think we can close this ticket?
