### ISSUE TITLE
I don't found a Argentine pesos to use it

### ISSUE THREAD

**Issue by GatoPardoPy** [moneymanagerex/moneymanagerex#6512]
In the list of differents currencies I didnt found the Argentine Pesos and I dont found the way to add it.
Please help, thanks
Nicolas

<hr> • Version: 1.7.0 64-bit<br>
 • Built: Dic 26 2023 19:10:28<br>
 • db 19 (aes128cbc)<br>
 • git b380493 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: es_ES.windows-1252<br>
 • 2880x1920 32-bit 96x96ppi

**Comment by renato-mmex** [comment]
<img width="410" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/e4dd95d7-804a-46aa-8705-7ef7f7d9737d">
<img width="420" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/bdb24417-34d3-4344-a633-addb61e4b7dc">

**Comment by GatoPardoPy** [comment]
Thank you!!!!

_________________
Nicolás Arzamendia

________________________________
De: Renato ***@***.***>
Enviado: lunes, 5 de febrero de 2024 16:20
Para: moneymanagerex/moneymanagerex ***@***.***>
Cc: Nicolás Arzamendia ***@***.***>; Author ***@***.***>
Asunto: Re: [moneymanagerex/moneymanagerex] I don't found a Argentine pesos to use it (Issue #6512)

image.png (view on web)<https://github.com/moneymanagerex/moneymanagerex/assets/76920138/e4dd95d7-804a-46aa-8705-7ef7f7d9737d> image.png (view on web)<https://github.com/moneymanagerex/moneymanagerex/assets/76920138/bdb24417-34d3-4344-a633-addb61e4b7dc>
