### ISSUE TITLE
An addition anomaly?????

### ISSUE THREAD

**Issue by huntersmoon100** [moneymanagerex/moneymanagerex#6517]
MMEX version:
 - [ ] 1.6.4
 _**- [x] 1.7.0 - [x] 1.7.0**_
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows  64 bit
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
An anomaly in addition.  I've been using money manager for years and never had this problem.  see attachment.  I've deleted and reintroduced it to no avail.  I've saved it come back in nothing.  Am I doing something wrong????

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
> Am I doing something wrong????

Yes, you are not describing what this issue is with any clarity.

Can't see an attachment? Without it I have no idea what issue you are describing.

**Comment by renato-mmex** [comment]
See: https://github.com/huntersmoon100

**Comment by whalley** [comment]
The balance is calculated based on date. It looks like your account view is currently sorted by transaction ID. Please sort by date.

**Comment by whalley** [comment]
@huntersmoon100 Is this now resolved?

**Comment by huntersmoon100** [comment]
Yes thank you. I apologise I should have let you know. I appreciate your
help.

Kind regards

Jacqueline Hunter
