### ISSUE TITLE
does not perform backup on close

### ISSUE THREAD

**Issue by Allotmentman** [moneymanagerex/moneymanagerex#6520]
> MMEX does not perform backup on close down since upgrading to version 1.7.0

> Please do not remove information attached below this text.

<hr> • Version: 1.7.0 64-bit<br>
 • Built: Dec 30 2023 12:38:47<br>
 • db 19 (aes128cbc)<br>
 • git b38049357 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMac 13.6)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0<br>
 • gettext 0.22.3<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.27.8<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 15.0.0 (clang-1500.0.40.1)<br>
<br>
OS:<br>
 • macOS Ventura Version 13.6.3 (Build 22G436)<br>
 • System Locale: <br>
 • User Interface Language: en_GB.Western (Mac OS Roman)<br>
 • 1440x900 32-bit 144x144ppi

**Comment by whalley** [comment]
Seems fine on MacOS. Back up created as expected.

**Comment by Allotmentman** [comment]
Hi Mark

My mistake, all is well here too

Sorry for the confusion - another senior moment

Cheers

Dave
