### ISSUE TITLE
Comprobación de instacia MMEX

### ISSUE THREAD

**Issue by ronaldromejo** [moneymanagerex/moneymanagerex#6528]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Comprobación de instacia MMEX

La base de datos que está intentando abrir está marcada como abierta por otra instancia de MMEX.
Para evitar pérdidas de datos o conflictos, se recomienda encarecidamente que cierre todas las demás aplicaciones que puedan estar utilizando la base de datos.

Si no se está ejecutando nada más, es posible que la base de datos se haya quedado marcada como abierta como resultado de un bloqueo durante el uso anterior de MMEX.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/157624579/0044cf0f-09de-41ee-8288-bc4184f85bce)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

# Additional information

Hola,
Estoy presentado el error (La base de datos que está intentando abrir está marcada como abierta por otra instancia de MMEX) con la v1.7.0 (2023.12.26). Si le indico continuar muestra los datos por un lazo de 5 segundos antes de cerrar la aplicación.

Intente abrir la base de datos con la v1.6.4 (2023.06.20) y me indica que la base de datos fue actualizada y no abre.

**Comment by renato-mmex** [comment]
```
MMEX Instance Check

The database you are trying to open is marked as being opened by another instance of MMEX.
To avoid data loss or conflicts, it is strongly recommended that you close all other applications that may be using the database.

If nothing else is running, the database may have been marked as open as a result of a crash during previous use of MMEX.

```
Hello,
I am getting the error (The database you are trying to open is marked as open by another instance of MMEX) with v1.7.0 (2023.12.26). If I prompt it to continue it displays the data for a 5 second loop before closing the application.

I tried to open the database with v1.6.4 (2023.06.20) and it tells me that the database was updated and does not open.

**Comment by ronaldromejo** [comment]
Excellent, the v1.7.1 Beta build allows me to open the database without it closing.
