### ISSUE TITLE
MMEX Database error

### ISSUE THREAD

**Issue by Petefen** [moneymanagerex/moneymanagerex#6536]
Hi, Sorry this is probably a simple known issue but I couldn't find any documentation. When I log into the system I get this error message:-
![Screenshot 2024-02-28 081020](https://github.com/moneymanagerex/moneymanagerex/assets/161574000/5318ad45-4ebb-43a0-a6ab-b82b414e0b17)

Then this screen
![image](https://github.com/moneymanagerex/moneymanagerex/assets/161574000/b50215f3-3e92-450c-af74-3a0c21776bb2)

Please can you tell me how to fix this?

MMEX version:
 - [x] 1.6.4
 - [] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
Have you used this database with the latest Android version ?
Have you tried a v1.7.1 Beta build. 
Try this: https://ci.appveyor.com/api/buildjobs/pxumq6wd4e2ls6pg/artifacts/mmex-1.7.1-Beta.1-win64.exe

**Comment by whalley** [comment]
With your database you need to be using v1.7.0 or above.. https://moneymanagerex.org/docs/downloads/latest/

**Comment by Petefen** [comment]
Thanks so much, that's done the trick
