### ISSUE TITLE
Upgrade database encryption to AES256

### ISSUE THREAD

**Issue by howff** [moneymanagerex/moneymanagerex#6538]
Are there any plans to upgrade the database encryption to AES256?
A bit overkill for my needs, but it would make it compatible with the Android version of moneymanagerex
https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.02.26.1020

**Comment by guanlisheng** [comment]
linked to https://github.com/moneymanagerex/moneymanagerex/pull/6532

if we don't consider the historical data, we can replace this cipher with SQLCiper 
refer to https://github.com/guanlisheng/wxsqliteplus/blob/master/src/sqliteplusframe.cpp#L308-L310

**Comment by guanlisheng** [comment]
hi @howff , the latest code has supported AES256/SQLCipher.
