### ISSUE TITLE
Recurring operations section no longer works With Money Manager

### ISSUE THREAD

**Issue by melseille** [moneymanagerex/moneymanagerex#6539]
>I updated today the Money Manager Ex program to versionMoney Manager Ex /  Version: 1.7.0 64-bit
I have a glitch when I want to work, modify or add a recurring operation, the application closes and it crashes, not wanting to open again. When I close everything and restart, the application no longer wants to load the database and it displays this frame.

![Capture d'écran 2024-03-01 162731](https://github.com/moneymanagerex/moneymanagerex/assets/161859152/66d36202-bede-424b-a8c5-e2c00d852b83)
until now I had never had any problems with the application that I have been using for years
THank you for your help!

> Veuillez ne pas effacer les informations jointes sous ce texte.

<hr> • Version: 1.7.0 64 bits<br>
 • Built: Déc 26 2023 19:10:28<br>
 • db 19 (aes128cbc)<br>
 • git b380493 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22631), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: fr_FR.windows-1252<br>
 • 3000x2000 32-bit 96x96ppi

**Comment by n-stein** [comment]
Possibly due to #6390 which has been resolved.

Please try the 1.7.1 beta here https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/9wndlu785u3h29ud/artifacts

**Comment by melseille** [comment]
THank you I try after

**Comment by melseille** [comment]
My computer wouldn't install the portable version, it told me there were suspicious data actions and isolated the folder immediately. The 64 bit version in application. exe to work and the problem is resolved everything works perfectly in recurring operations! Thank you so much. I think I won't be updating for a long time!!!! Thanks again !!!!

**Comment by n-stein** [comment]
Thanks for confirming.

> I think I won't be updating for a long time

You may want to at least upgrade to the official 1.7.1 release which should be available within the next few weeks.
