### ISSUE TITLE
Income category CANNOT be displayed properly

### ISSUE THREAD

**Issue by 1196262437** [moneymanagerex/moneymanagerex#6541]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
![Uploading image.png…]()
![Weixin Screenshot_20240302221621](https://github.com/moneymanagerex/moneymanagerex/assets/161951089/28445241-9014-42b2-9d55-cf9dee30978e)
As the picture shown above, income category cannot be displayed as Income: Salary etc. Instead, the interface only shows +other expenses and cannot be changed even if after being edited and saved.
 
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by rmelillo76** [comment]
Hi @1196262437, Are there any Splits on this transaction? The "+" would indicate so, and that 'Other Expenses' is the category on the Split. Would you mind posting screenshots of the transaction in Edit mode, as well as the split item(s). Thanks

**Comment by 1196262437** [comment]
> Hi @1196262437, Are there any Splits on this transaction? The "+" would indicate so, and that 'Other Expenses' is the category on the Split. Would you mind posting screenshots of the transaction in Edit mode, as well as the split item(s). Thanks

Hello, @rmelillo76, thank you for your close attention. Problem solved and it turns out it's my mistake. I edit category on  the SPILT mode. Thanks a lot!
![1-1](https://github.com/moneymanagerex/moneymanagerex/assets/161951089/f689dfb2-06b1-4b44-bc34-1c279b22574b)
![2](https://github.com/moneymanagerex/moneymanagerex/assets/161951089/67ed6bf4-577e-468a-a8db-22a1fa885df6)
![3](https://github.com/moneymanagerex/moneymanagerex/assets/161951089/f85c2bd5-272b-465a-a374-76c9b9c87173)

**Comment by rmelillo76** [comment]
@1196262437 you're welcome! happy to help and I'm glad that solved it for you!
