### ISSUE TITLE
Import translations from Crowdin

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6545]
Please import translations from Crowdin to enable more time for checking translations and keyboard shortcuts as it seems that the next version is soon to be released (cf. https://github.com/moneymanagerex/moneymanagerex/pull/6532#issuecomment-1963024517). Thank you

**Comment by ovari** [comment]
@whalley do you have an update on when v1.7.1 is expected? Thank you

**Comment by whalley** [comment]
Was planning to release next weekend.

**Comment by ovari** [comment]
> Was planning to release next weekend.

Can you please merge translated strings from Crowdin so that the beta edition can be tested? Thank you

**Comment by whalley** [comment]
I see @vomikan has merged latest. No need to raise a issue for these, they will get merged periodically.
