### ISSUE TITLE
Unchecked in custom field, date format

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6561]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [x] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/2c54744f-82a7-4715-9000-f35dca1e8287)

if check the checkbox without changing the date in a CF item(date format), the selection status is not saved.
must change it to another date, change it back to the previous date, and save it to take effect.

without changing = not change date value

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

custom field
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/1c235272-1f43-47cf-bc83-8dd601f84b37)

New/Edit Transaction
CF - Date field - Check box Check
click OK button, Save

open Edit Transaction

?!?!? unchecked Date field's checkbox

Expected result:

save checkbox value without changing the date in a CF

Actual result:

checkbox value not saved

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Confirmed. This seems to only impact the 'Date' type fields.
