### ISSUE TITLE
Pie chart in Reports - Number format is inconsistent with decimal digits count & comma separation 

### ISSUE THREAD

**Issue by Aravinth-Earth** [moneymanagerex/moneymanagerex#6566]
location : reports -> pie charts 
note: attached image shows 'where the money goes' screen, but in all the places where pie charts comes in, the same issue occurs

two part observation with the numerical value display,
1. the decimal values -> can this be prefixed to be a 'two digit display' for all entries ?
2. the number formatting system -> even though in the main transaction view & in the reports table, it's formatted properly (as per my locale configuration), just next to the pie chart it is not working properly.

setting:
![image](https://github.com/moneymanagerex/general-reports/assets/55803552/41676def-7e80-4619-81f0-14204b12e54c)

issues screenshot:
![Sample screen with issues & expected fix highlighted](https://github.com/moneymanagerex/general-reports/assets/55803552/3b382143-4061-40bb-9735-c99456af3b35)

**Comment by n-stein** [comment]
I have localized the pie chart legends. Numbers are displayed according to the MMEX locale with the decimals set by the base currency.

For example:

en_US locale with USD base currency (2 decimals):

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f10c70db-d359-469b-88e5-7f448aa98076)

de_DE locale with Bitcoin base currency (9 decimals):

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/eb2f1550-1bcb-4b44-b093-d5ccb89d2f8b)

be_BY locale with BYR base currency (0 decimals):

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/4fca4b45-735e-4778-a21f-eff9df5533e7)

**Comment by renato-mmex** [comment]
@n-stein ................great, thank you
