### ISSUE TITLE
Scheduled Transaction Dialog - Payments Left

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6570]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [x] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/29d0aee7-6e90-40a3-a5ef-fb2eebcf20c8)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/dbec8436-fe71-408b-a235-a344611706fc)

Payments Left: 
Enter a number here, delete it again, and move the focus to another location then can see value of -2147483648.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. New/Edit Scheduled Transaction, Open Dialog
2. Click  Payments Left Input box
3. typing any number ex) 0
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/318958e2-959a-45bb-ba53-167b7dc89981)

4. delete number value (you can see empty box)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/24a21efb-e95f-4773-a167-121c288aac78)

5. Click another component (date, text input, any buttons, OK&Save button also...)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/978978c2-f2be-447c-b1da-28255d304a62)

6. You can see -2147483648 value in Payments Left. 🎉

Expected result:
'∞'

Actual result:
'-2147483648'

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Fixed the "Payments Left" bug. The value will remain blank when cleared.
I also fixed the bug where entering a date too far in the future causes the payment to become overdue.

**Comment by DevelopmentAnything** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/4029defe-cc7b-4b10-9c03-0c46e38d2587)

There are still issues with the display.
don't see some of the numbers.
Theoretically, we can enter numbers up to 2147483647
width of the component must be set long.
