### ISSUE TITLE
`Edit Account` dialog

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6572]
For hu-HU locale:
1. Should the large space in the tab labels (red) be removed?
2. Should the right side (blue) align with dialog boundary?

![Edit Account - English locale](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/94e7e271-79a4-4d48-9b32-e9f24d8761aa)

![Edit Account - Hungarian locale](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/13ea1c35-1010-4a0e-8955-c95577085f70)

Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/56d13180-df64-4edd-8329-b4fcd51f1ba1)

**Comment by vomikan** [comment]
Windows 10
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/ec668117-6b67-41cb-8a39-fa4ec91c7c9b)

**Comment by ovari** [comment]
Verified fixed. Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/41349883-c57e-4741-a27f-03389891d015)

```
Money Manager Ex
• Verzió: 1.7.1-Beta.1 64 bites
• Készítési időpont: márc. 12 2024, 03:16:33
• Adatbázis verziója: 19 (aes128cbc)
• Git-végrehajtás: 0e99b4c2e (2024-03-11)
• Git-ág: master
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Fut a következőn:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• Rendszer területi beállítása: en_AU.UTF-8
• Felhasználói felület nyelve: hu_HU.UTF-8
• 1368x768 24-bit 96x96ppi
```
