### ISSUE TITLE
German Keyboard comma 

### ISSUE THREAD

**Issue by Mikel1950** [moneymanagerex/moneymanagerex#6579]
> Ersetzen Sie diesen Text (mit > markiert) mit einer detaillierter Beschreibung Ihres Problems.
> Bitte entfernen Sie die unter diesem Text enthaltenen Informationen nicht.

<hr> • Version: 1.7.0 64-bit<br>
 • Built: Dez 26 2023 19:10:28<br>
 • db 19 (aes128cbc)<br>
 • git b380493 (2023-12-26)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 11 (build 22631), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: de_DE.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by Mikel1950** [comment]
Hallo ,
I use a logitech Keyboard K360. When i put in an amount with the number-block let say 56,34€ it change that amount into 5634€.
I can put in the first two digits with tne number-block, then the comma from the mainblock (netx to M . -) and than the last digits. this amount will be accepted correctly. What can i do to input the amount with the nimber-block complete?

By the way: i used a Version of Money Manager EX which allows me to repeate the last booking date until i put a new one. I cannot find that setting in my version.

hopefully awaiting your answer
Mike1950

**Comment by whalley** [comment]
> By the way: i used a Version of Money Manager EX which allows me to repeate the last booking date until i put a new one. I cannot find that setting in my version.

![CleanShot 2024-03-11 at 20 49 29@2x](https://github.com/moneymanagerex/moneymanagerex/assets/487345/2b3f9708-ede3-4ae6-977e-1838e541cf28)

**Comment by Mikel1950** [comment]
Thank you. Your advise solved my Problem. I found Out this setting.ThanksMike 1950Sent from Android deviceAm 11.03.2024 21:50 schrieb Mark Whalley ***@***.***>:

By the way: i used a Version of Money Manager EX which allows me to repeate the last booking date until i put a new one. I cannot find that setting in my version.

***@***.*** (view on web)
