### ISSUE TITLE
Remove shortcut hints shown in the "frequently used notes" menu on Linux

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6583]
1. `New Transaction` dialog
2. Click the Notes ellipsis `…` and the option shows `Nyitva` in Hungarian (should be shown in English)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/b940348e-c8a4-4e68-b1f7-d0dfabd4b5fb)

Thank you

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 12 2024 03:16:33
• Database version: 19 (aes128cbc)
• Git commit: 0e99b4c2e (2024-03-11)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by vomikan** [comment]
And what does it say in the notebooks? How can I reproduce this?
The fact is that the notes appear in this list as is, without translation.

**Comment by n-stein** [comment]
> 2\. Click the Notes ellipsis `…` and the option shows `Nyitva` in Hungarian (should be shown in English)

This is the "Frequently Used Notes" list. It shows the 20 most frequently used notes for transactions in the account. None of these are translated, you must have entered the word "Nyitva" as a note on at least one of your transactions in that account.

Side note, I'm not sure why Linux adds the "Ctrl+O". It adds others when you have more in the list:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f210b730-1e3f-48b7-b6f3-61fdd26fa9e1)

As far as I can tell, pressing that key combination does absolutely nothing, so...?

**Comment by vomikan** [comment]
It seems happens becouse the ids of menu items  match the service codes.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/e452e9c1-d534-40cd-8b12-2e7606c7c5d5)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/25b3f4f3-f445-4d12-9879-4a8b0d30580a)

**Comment by n-stein** [comment]
Perhaps we should be using wxID_HIGHEST here

https://github.com/moneymanagerex/moneymanagerex/blob/master/src%2Ftransdialog.cpp#L1136

https://github.com/moneymanagerex/moneymanagerex/blob/master/src%2Ftransdialog.cpp#L1149

**Comment by n-stein** [comment]
Looks better now:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/d8913ac9-7668-48f3-9135-90d4c294c186)

**Comment by ovari** [comment]
Verified fixed. Thank you

The icon has also been removed. Thank you once again.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/c0acceb6-f8e0-46c4-8531-f1f192e7c85c)

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 15 2024 20:30:16
• Database version: 19 (aes128cbc)
• Git commit: d082daa60 (2024-03-15)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by n-stein** [comment]
Not quite closed. I have applied the same fix to the Scheduled Transactions dialog. Please confirm the issue is fixed there as well.

**Comment by ovari** [comment]
> Not quite closed. I have applied the same fix to the Scheduled Transactions dialog. Please confirm the issue is fixed there as well.

Once https://github.com/moneymanagerex/moneymanagerex/pull/6597 is merged can check if issue is fixed. Below is screenshot of unfixed version.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/4ee2acad-6453-4876-a6a4-0b429118d1a9)

```
Money Manager Ex
• Version: 1.7.1-RC.1 64-bit
• Built on: Mar 17 2024 13:23:38
• Database version: 19 (aes128cbc)
• Git commit: d8f831b3e (2024-03-17)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.6.0-DEV OpenSSL/3.1.5 zlib/1.3.1 libidn2/2.3.4 libpsl/0.21.2 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-101-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by ovari** [comment]
> Not quite closed. I have applied the same fix to the Scheduled Transactions dialog. Please confirm the issue is fixed there as well.

Fixed

```
Money Manager Ex
• Verzió: 1.7.1-RC.1 64 bites
• Készítési időpont: márc. 21 2024, 03:16:21
• Adatbázis verziója: 19 (aes128cbc)
• Git-végrehajtás: d478cd2e3 (2024-03-20)
• Git-ág: master
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.6.0-DEV OpenSSL/3.1.5 zlib/1.3.1 libidn2/2.3.4 libpsl/0.21.2 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Fut a következőn:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-101-generic x86_64
• X-Cinnamon (X11)
• Rendszer területi beállítása: en_AU.UTF-8
• Felhasználói felület nyelve: hu_HU.UTF-8
• 1368x768 24-bit 96x96ppi
```
