### ISSUE TITLE
`New Transaction` dialog `-` and `+` buttons

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6584]
In the `New Transaction` dialog:
1. Should the height of the `-` and `+` buttons be increased to be the same height as the date drop-down?
2. Is the `-` button missing the top, bottom and right borders (left border is showing) which are shown for the `+` button?
3. The left border for the `-` button is square and the right border for the `+` button is rounded. Should these be consistent?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/637875a6-91d3-4055-bb52-530cea69fcb3)

Thank you

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 12 2024 03:16:33
• Database version: 19 (aes128cbc)
• Git commit: 0e99b4c2e (2024-03-11)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by n-stein** [comment]
Done.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/815faf3e-0415-45a4-95d3-13df180ca748)

**Comment by ovari** [comment]
Thank you @n-stein for fixing the height of the buttons.

Are you able to fix the border, i.e.
3. The left border for the `-` button is square and the right border for the `+` button is rounded on Linux Mint 21.3 Cinnamon. Should these be consistent?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/0783c7ae-5a87-46cb-936f-fc7f3cdf5edf)

Thank you

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/deee1cb3-6478-4fdf-b403-182634f23c19)

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 15 2024 20:30:16
• Database version: 19 (aes128cbc)
• Git commit: d082daa60 (2024-03-15)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by n-stein** [comment]
> Are you able to fix the border, i.e.
> 3. The left border for the `-` button is square and the right border for the `+` button is rounded on Linux Mint 21.3 Cinnamon. Should these be consistent?

Hm. Not sure why you are seeing this. It looks normal for me as you can see in my Debian 12 screenshot above.

**Comment by ovari** [comment]
> > Are you able to fix the border, i.e.
> > 3. The left border for the `-` button is square and the right border for the `+` button is rounded on Linux Mint 21.3 Cinnamon. Should these be consistent?
> 
> Hm. Not sure why you are seeing this. It looks normal for me as you can see in my Debian 12 screenshot above.

@mtwebster is the screen border a bug due to Linux Mint? Thank you

**Comment by ovari** [comment]
Also shows incorrectly in Scheduled Transactions.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/df108a86-394c-4b9a-b7c5-e420c669f311)

**Comment by n-stein** [comment]
Does it look ok in the AppImage?
 https://github.com/moneymanagerex/moneymanagerex/actions/runs/8381763846

**Comment by ovari** [comment]
> Does it look ok in the AppImage? https://github.com/moneymanagerex/moneymanagerex/actions/runs/8381763846

Thank you for the link.

1. Downloaded AppImage
2. Made AppImage executable
3. Open AppImage and MMEX did **not** open

**Comment by n-stein** [comment]
Probably a missing dependency. Do you have `fuse` installed? Try executing the AppImage from the terminal, it will tell you why it won't start.

**Comment by ovari** [comment]
> Probably a missing dependency.

```
$ ./MMEX\ Money\ Manager-1.7.1-RC.1-x86_64.AppImage 
/tmp/.mount_MMEX MX8seWV/usr/local/bin/mmex: error while loading shared libraries: liblua5.3.so.0: cannot open shared object file: No such file or directory
```

> Do you have `fuse` installed?

No.
