### ISSUE TITLE
Transaction Report not filtering categories if period range specified

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6589]
MMEX version:
 - [X] 1.7.1

If I create a transaction report and select a category to filter on then the reporting works fine, however if I select a period range, e.g. Last 12months the reported categories now include categories I have not selected.

@vomikan Just checked and prior to https://github.com/moneymanagerex/moneymanagerex/pull/6555 it worked fine.

**Comment by n-stein** [comment]
> @vomikan Just checked an prior to https://github.com/moneymanagerex/moneymanagerex/pull/6555 it worked fine.

I was about to say I couldn't reproduce, but I haven't merged this PR in my master branch yet!

**Comment by n-stein** [comment]
Fixed it

**Comment by whalley** [comment]
Yep, that fixes it.
