### ISSUE TITLE
Migrate Options Settings

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6594]
1.7.1. RC1

# Description of the feature

Every time update a program
Some of the option settings are not migrated.

It's quite annoying to resetting when every update

List of applicable

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/5dc0d740-6772-4c5c-91de-ad10628dcef1)
Transaction copy options

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/bec5f452-fddd-424a-b603-e532a7e8afb0)
use Time option
style theme and Home page text size, etc

The remaining items are unknown because they are used by default.

**Comment by renato-mmex** [comment]
how and which new MMEX version you install. 
(portable ?, delete old version first ?)
The settings are in the "mmexini.db3", each portable version has its own .db3

**Comment by DevelopmentAnything** [comment]
@renato-mmex
So why are the settings divided?
Some of the settings are in .mmb INFOTABLE, and some are in mmexini.db3.

**Comment by DevelopmentAnything** [comment]
The settings in .mmb will still apply when I update them. Why on earth do I save the rest of the settings separately?

**Comment by renato-mmex** [comment]
The concept is just like that, I would also like .db3 to be integrated into .mmb.
That would solve many problems.
Here is another hint on how to work around the problem.
https://forum.moneymanagerex.org/viewtopic.php?p=23851&hilit=mmexini#p23851

**Comment by n-stein** [comment]
> So why are the settings divided?
> Some of the settings are in .mmb INFOTABLE, and some are in mmexini.db3.

Some settings are applicable across databases, and these are held in SETTINGS_V1 within mmexini.db3. Settings which are specific to a particular database are held in INFOTABLE_V1. If you switch databases these settings will be set by the incoming database.

> It's quite annoying to resetting when every update

Copy your mmexini.db3 file to %APPDATA%\MoneyManagerEx. Then when you download a new portable version just delete the mmexini.db3 file that comes with it and it will use the version in APPDATA.

**Comment by DevelopmentAnything** [comment]
nice~!
%APPDATA%\MoneyManagerEx
It works very well.

Actually, it's in English in the help, but since some time, the page has disappeared from crowdin. It's not translable.

**Comment by vomikan** [comment]
> the page has disappeared from crowdin

What are you talking about?
https://crowdin.com/project/moneymanagerex/ko

**Comment by DevelopmentAnything** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/1a35a69c-84ee-4080-a309-31a409670476)

@vomikan Help document.

**Comment by vomikan** [comment]
At one time, help pages were available on crowdin. But, since this is a very large volume, they were practically not translated. We decided to remove them.
