### ISSUE TITLE
When set the color, note is inserted

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6595]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [x] 1.7.1 RC1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/6fefed44-0cbf-4a7b-81f1-89a925e6befd)

Why are notes entered automatically?

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. open New/Edit Transaction Dialog
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/d1b214d6-2aec-4f23-96c1-ba2145e03f21)

2. Click Color button and click Color item
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/859d5702-98f2-4c65-995f-5edf7a6682d2)

3.  you can see notes in note area

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/0ff8dda5-56d7-421e-828a-1722d02e2ffe)

red color = note Item 1;
orange color = note Item 2;
yellow color = note Item 3;
...
🤣

Expected result:

Change Color Only

Actual result:

with insert Note item

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Ah, a consequence of changes for #6583 -- the color button menu range overlaps with the note button menu range, which normally wouldn't be an issue but the event table sends all of these to the same event handler...

I have fixed it now.

**Comment by ovari** [comment]
@DevelopmentAnything can you verify this issue is fixed in the latest build? If so, can you please close this issue? Thank you

**Comment by DevelopmentAnything** [comment]
It is necessary to ensure that the color of the button does not change in the mouse over event
