### ISSUE TITLE
Translated Help (index) pages link to English sub-pages (grm, budget, stocks_and_shares) even when translations are available

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6596]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [x] 1.7.1 RC1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/80a6eaac-b5c8-4d90-bc68-74547223bf17)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. click any language (no English)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/c9ba5e49-1e7b-4b9c-92d3-e66bd494f3ed)

2. go to 14. Stocks and Shares section
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/674aa412-f45f-4222-b10c-41ae26152c3b)

3. click Further details refer to Stocks, Shares and Share Dividend Management in MMEX 

You can only see the English page

Expected result:

load ..language directory/stocks_and_shares.html

Actual result:

only loaded english page.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Same applies to any of the subpages -- Budgeting, Reports, etc.

All the link tags look like `<a href="../budget.html?lang=ru">` but they should have the full locale `<a href="../budget.html?lang=ru_RU">`

**Comment by DevelopmentAnything** [comment]
@n-stein 

The content you explained has already been applied.
Because if don't modify it, it won't even appear on the language list.

What I'm asking is sub page. It's not just Korean but all languages are the same. Only the English page appears.

**Comment by DevelopmentAnything** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/0868bdc1-a808-4aa8-9f60-fde2937cdb78)

?lang=ko
has already been applied.
Code does not do parameter parsing.

**Comment by n-stein** [comment]
> The content you explained has already been applied.

> ?lang=ko
> has already been applied.

No, that's not what I mean. You _can't_ use `?lang=ko` you need to use `?lang=ko_KR` in all of the `<a>` tags. Change your html to `<a href="../stocks_and_shares.html?lang=ko_KR">` and it will work.

**Comment by DevelopmentAnything** [comment]
OK.

So should I wait for the translator to correct the incorrectly applied code to the html file in each language? Can the MMEX coder modify it?
( Belarusian  Chinese  German  French  Hungarian  Hebrew  Croatian  Italian  Dutch  Polish  Russian  Spanish )

**Comment by n-stein** [comment]
> So should I wait for the translator to correct the incorrectly applied code to the html file in each language? Can the MMEX coder modify it?

I've fixed all the incorrect links I could find.
