### ISSUE TITLE
Accounts headers on the Home Page

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#660]
Please one style!
![acc](https://cloud.githubusercontent.com/assets/6836805/12533162/5990b66e-c238-11e5-8639-cb7aaf19b9b4.png)

**Comment by stef145g** [comment]
Noting that the navigation panel has the plural version of Account, will make the home page plurals as well. ie **Accounts**

**Comment by stef145g** [comment]
This issue was fixed in the cancelled pull request https://github.com/moneymanagerex/moneymanagerex/pull/661

**Comment by stef145g** [comment]
This is now fixed in pull request: https://github.com/moneymanagerex/moneymanagerex/pull/664
