### ISSUE TITLE
Asset "Initial Value" on dashboard does not display the initial value, VALUE field includes void transactions

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6610]
Two issues as noted by forum user Simon1D here: https://forum.moneymanagerex.org/viewtopic.php?p=24976#p24976

1. An asset's "Initial Value" reported on the dashboard is incorrect. It should be the value of the asset on the asset STARTDATE
2. An asset's VALUE includes asset transactions which have been marked "Void"

**Comment by n-stein** [comment]
The "Void" issue also applies to stock value

**Comment by renato-mmex** [comment]
I have downloaded the corrected version and cannot see any change.
Neither the asset account, nor the initial value, nor a transfer to an asset account is displayed on the homepage.

When opening an asset account, the following message is displayed, the meaning of which I do not understand.
<img width="327" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/9d9c5bb2-28e1-4328-b9d1-fd98d1a321e4">

**Comment by n-stein** [comment]
This fix is related to assets, not asset accounts. The change is the info displayed in the "Assets" section of the dashboard:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/20d64443-fe66-464f-bfb9-96952222ba71)

You won't see any difference if you don't have any manually adjusted asset values.
