### ISSUE TITLE
Translations are not shown for strings which include the char →

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6614]
### Discussed in https://github.com/moneymanagerex/moneymanagerex/discussions/6600

<div type='discussions-op-text'>

<sup>Originally posted by **DevelopmentAnything** March 21, 2024</sup>
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/b55119b9-10a8-4bbb-82fa-518d35bc579f)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/9ad7e96e-cae6-4fb2-b851-82bab800b110)

When I register share account, a message box appears, and the contents are empty.
I have completed all related translations.

why empty ? ? ?</div>

**Comment by n-stein** [comment]
wxString::FromUTF8() needs to be wrapped in wxGetTranslation()

**Comment by n-stein** [comment]
@DevelopmentAnything I can now see the message box translated:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f57afded-4f54-45e2-adff-4f51d18a2395)

can you check the beta build to see if your "blank" issue is resolved?

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/49489119/job/r2sx0rmq5qu1kfdt/artifacts

**Comment by DevelopmentAnything** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/9d15d14b-c26d-407e-81ac-54bef2dedd47)

GOOD.
