### ISSUE TITLE
Kontrol Paneli Font Boyutu

### ISSUE THREAD

**Issue by secalp54** [moneymanagerex/moneymanagerex#6620]
Kontrol Panelindeki yazı boyutunun ayarlanabilmesi.

Kontrol paneldeki yazı büyüklüğü küçük kalıyor ve görmekte zorlanıyorum,
yazı büyüklüğünün ayarını da seçeneklerde bulamadım,

Aşağıdaki resimde kontrol paneldeki yazılar (sağ tarafta kalan) küçük ama sol taraftaki kısımda bulunan yazılar büyük ve daha okunaklı, lüften **"Toplam Net Değer"** yazısının altında bulunan listedeki yazılarında büyültülebilmesini sağlayabilir misiniz?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/101110375/0beaf8fe-032d-407e-b3e2-3970a2e6b3b8)

Teşekkür ederim. İyi çalışmalar dilerim.

**Comment by n-stein** [comment]
Translated:

Adjusting the font size in the Dashboard.

The text size in the dashboard is small and I have difficulty seeing it,
I couldn't find the font size setting in the options,

In the picture below, the writings in the control panel (on the right side) are small, but the writings on the left side are large and more legible, can you please make the writings in the list under the "Total Net Value" text larger?
