### ISSUE TITLE
BUG - Update BdD MMEx

### ISSUE THREAD

**Issue by Johar24** [moneymanagerex/moneymanagerex#6629]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [x] Other (please specify) 15

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX (10.15.7)
 - [ ] Linux 

# Hello,
When upgrading my mac system (bought in 2012), I also had to update MMEX which was no longer working on the "new" mac version (10.15.7). I tried to download the latest update, but it won't launch.  Here's the message that appears when I launch it : 

MMEX database update to version 15 has failed.
Restore the DB from the automatic backup created before the update and try again, or contact MMEX support.
SQL Logic error[1]: no such table: REPORT_V1

Thank you for your help !

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

<img width="1440" alt="Capture d’écran 2024-04-01 à 17 01 23" src="https://github.com/moneymanagerex/moneymanagerex/assets/163874971/f5094170-4048-44c7-9c59-db657a72737f">

**Comment by renato-mmex** [comment]
Maybe that will help: https://github.com/moneymanagerex/moneymanagerex/issues/5662hilft

**Comment by Johar24** [comment]
Thanks a lot ! Delighted to be able to continue using this software.
