### ISSUE TITLE
My database make crash MMEX

### ISSUE THREAD

**Issue by AdrielLesch** [moneymanagerex/moneymanagerex#6630]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

I tried to open my database today and the software crashed. Since, when I open the database, I've a popup message which say : "the database has been marked already open" and if I say "yes" to open, after 10/15 seconds the software closes alone. I've tried to open the backups, but they didn't run, and they have the same problem.

I thought it was a software problem, but if I create a new base it seems to run perfectly. So I think it's a problem with the database and not with the software. 

Before, I've already some problems, in particular with recurrent operations. They make crash the software, and after I had the popup message will say "the database has been marked has open". I don't know if there is a link between the two.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [x] Randomly 
 - [ ] Happened only once

# Additional information

![image](https://github.com/moneymanagerex/moneymanagerex/assets/165686274/0e68e0e7-ea9d-43e0-95b2-8d54ce2a6f02)

**Comment by n-stein** [comment]
Maybe caused by #6390 where the application crashes if a recurring transaction will exceed the account credit limit?

Please try the latest 1.7.1 RC1 build from https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49517368/job/ky1q8meejvp8m7ks/artifacts
