### ISSUE TITLE
Design or bug - specifying ALL accounts on Transaction Filter

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#6632]
![Screenshot 2024-04-03 091134](https://github.com/moneymanagerex/moneymanagerex/assets/24897056/df13d392-31d5-47a7-ba72-976746b3740e)

This pops up when I hit OK - any reason why this is not allowed?
I want to extract records with the specified category from ALL accounts over the past Tax Year.
I am currently using GRM and my own SQL but using the Transaction Filter looks so much easier.

Running 1.7.0 on Windows 11

**Comment by ovari** [comment]
Workaround: unselect the tickbox before the `Account` label. Does that work? Thank you

**Comment by ovari** [comment]
Is a workaround only required if there is a **bug**? If so, then should your issue be re-opened as it is valid bug? Thank you

**Comment by ovari** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/f8ed3c4a-f452-4bb9-bbf3-bbd44a2e2e37)

Reproduced with
```
Money Manager Ex
• Version: 1.7.1-RC.1 64-bit
• Built on: Apr 2 2024 03:16:22
• Database version: 19 (aes128cbc)
• Git commit: f49592915 (2024-04-01)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.6.0-DEV OpenSSL/3.1.5 zlib/1.3.1 libidn2/2.3.4 libpsl/0.21.2 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-101-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by grumpy235** [comment]
I guess the logic goes..
1. One ticks the box 
2. The program then expects you to select a specific account and ALL is not the name of a valid account

One could then argue that the program should treat the word ALL as wanting all accounts no matter what the setting of the tickbox but what about if someone has an account called ALL !

I think it is best to leave things as they are, of course if anybody had the time and skills to write some documentation then that would make things easier.

**Comment by ovari** [comment]
@vomikan does your actions mean that this issue should be re-opened? Thank you
