### ISSUE TITLE
Payee and Category Match not working as intended

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6637]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The payee definition is setup with matching critiera. While importing the Memo column has the criteria.  In the preview pane under payee I find the match is successful. But, when the import happens, the payee column is defaulted as "Unknown".
![mmex-payee-setup](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/219b72e6-9a8c-4f1f-9c13-b2fa1e7239a3)
![mmex-import-dialog](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/f8ea6b37-e826-4130-932e-ef85400bd1d5)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
The data is imported with matched payee and default category in the payee setup.
Actual result:
The data is imported with payee as "Unknown", so is the category.
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
I am unable to reproduce this issue. Can you please test using the 1.7.1 RC and see if you can reproduce? 

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49536430/job/cdd90pk0s6ngud7d/artifacts

**Comment by n-stein** [comment]
Anyone able to reproduce this?

**Comment by spillaip** [comment]
Yes Luis, this is happening for import transactions.  The import dialog
shows the payee information correctly, but import as UNKNOWN

**Comment by n-stein** [comment]
@spillaip can you please verify that the issue exists in version 1.7.1 RC found here https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49536430/job/cdd90pk0s6ngud7d/artifacts

**Comment by spillaip** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/a8cc39c1-6d55-4adb-9cb1-9784c91595b9)

I am able to reproduce in this version

**Comment by n-stein** [comment]
@spillaip  can you provide a sample CSV and match pattern which exhibits this behavior? I've tried multiple times but cannot reproduce this issue with any CSV file I have created.

**Comment by spillaip** [comment]
I have tried again by populating the matching criteria to the "Payee" column.  The functionality is working as expected.  Thank you for your patience.
