### ISSUE TITLE
Font size of the dashboard and Reports

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6638]
# Description of the feature

The dashboard font size is not controlled in the settings.  Please provide ability increase the fontsize.  Also, 

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by rmelillo76** [comment]
Hi @spillaip, you can increase the HTML Scale Factor size here. Mine is set to 150% which for me is more comfortable than the default:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/316bced8-99ac-4956-9152-4089db75d1e2)

**Comment by spillaip** [comment]
Works beautifully, thank you for this.
