### ISSUE TITLE
Summary Report does not ignore deleted transactions

### ISSUE THREAD

**Issue by boombuler** [moneymanagerex/moneymanagerex#6639]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The summary report had shown some weird values for me. After some digging through the database i've found that deleted transactions are treated as if they were not deleted.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1) Buy a share from the portfolio
2) Delete that transaction in the stock account

Expected result:

The summary report does ignore the deleted transaction.

Actual result:

The summary report displays the values as if the transaction was not deleted.

# Additional information

If i delete the deleted transaction from the "deleted transactions" view, the values are back to normal.

**Comment by n-stein** [comment]
Can you give a bit more info which "summary report" you are referring to? Maybe a screenshot if possible? When I look at the built in Stocks Summary and Account Summary reports, the deleted stock transactions are excluded.

**Comment by boombuler** [comment]
It is the account summay 
See this [example database](https://github.com/moneymanagerex/moneymanagerex/files/14912791/example-db.zip)

As you can see:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/275687/ebb28985-396d-46db-886c-581fb8b9cfca)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/275687/055b3b06-fc1f-4e6b-a742-de697d045632)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/275687/394399e7-eb9c-47be-bc04-e9e4bc6a730f)


If you need any more information let me know

**Comment by n-stein** [comment]
Perfect. Thanks, that helped. I've pushed a fix.

**Comment by boombuler** [comment]
Thank you very much!
