### ISSUE TITLE
Incorrect balance being exported to CSV

### ISSUE THREAD

**Issue by JAKW62** [moneymanagerex/moneymanagerex#6642]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When exporting an account to CSV, the Balance column appears completely random.  The attached screenshot shows the export on the left and MMEX on the right, with numbered transactions in the same order but wildly different balances (final column) after each transaction.
![2024-04-06](https://github.com/moneymanagerex/moneymanagerex/assets/166283893/95a83970-41d8-4d57-9c29-fb14c7b1bf7a)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
the left list is sorted by date and the right list by booking number ???

**Comment by JAKW62** [comment]
Thanks for the response, Renato.  I'm not sure if that's a statement or a
question.  The spreadsheet on the left and the MMEX screenshot on the right
show the same transactions in the same (date) order.  Not only does
each transaction have different balances associated with it in each place,
but also none of the exported "balance" figures appears anywhere in
the MMEX file.

**Comment by renato-mmex** [comment]
I have created various .CSVs in the latest MMEX version 1.7.1 and have not experienced any problems.

**Comment by n-stein** [comment]
I can reproduce this. 

My account has a starting balance of $167.

Viewing all transactions, sorted by date/ID ascending. The very first line has the correct balance $-33 in the checking panel (167 - 200 = -33)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/dc44543c-2129-420f-9c25-eb5e76a87bcc)

The same exact line of the CSV export has $100057

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/1f4fb52a-4b7f-4951-9edf-bea25f9d38bd)

**Comment by n-stein** [comment]
Looks good now.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/35dd4bb1-1f95-47f0-a561-7580573b8fb1)
