### ISSUE TITLE
Single instance 

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#665]
http://docs.wxwidgets.org/trunk/classwx_single_instance_checker.html

Shoul we use this?

**Comment by stef145g** [comment]
IMHO... NO.

**Comment by siena123** [comment]
I don't see a need to use it and would recommend not using it. Doing this would go against the precedent of the portable copy that we post with every release as it is intended to be run as multiple instances without affecting each other. Also I quite often have multiple instances open, either an installed version with a portable version or multiple portable versions.
