### ISSUE TITLE
Tag not entered when scheduled transaction is auto-registered

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6672]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [x] 1.7.1 RC1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

 scheduled transaction
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/9ba20d64-5d47-4515-9f8d-d818d5b5b351)
tag is registered.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Only tags have been added to the existing scheduled transaction

Expected result:
Tag must be entered

Actual result:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/8d4ca62b-31a4-4403-9f86-c5f24bd21d5b)
empty

scheduled transaction was marked in purple.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Confirmed, thanks for pointing this out. I've fixed it.
