### ISSUE TITLE
Bank accounts not displayed on the dashboard

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6691]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ x] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
Beyond certain number of bank accounts, the dashboard is no longer displaying the accounts and its balances.  Only final total is displayed

Please describe your issue with details.
Beyond certain number of bank accounts, the dashboard is no longer displaying the accounts and its balances.  Only final total is displayed.  I have seen for few accounts the bank accounts are displayed.

Add screenshot or other files if needed.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/2d01662a-d18b-494a-beab-4419fc2541cf)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/34810a30-9457-4ad7-9000-6f1ab679b4ef)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
I have created 19 checking accounts.

Expected result:
All the bank accounts are displayed
Actual result:
None are displayed
# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Did you by chance collapse the table with the `[-]` in the top right?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/5c7be61d-c355-4956-9167-ce2c8be07475)

**Comment by spillaip** [comment]
@n-stein You are amazing and correct. Now it displays fine.
