### ISSUE TITLE
Provide a calculator attached to Amount column

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6703]
# Description of the feature
Provide a calculator attached to Amount column

Please describe your feature with details.
Please provide a calculator attached to amount column, very similar to calendar attached to Date.

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by n-stein** [comment]
In the amount field you can key in the calculation directly such as `(13.52*7+6.79)` and it will be replaced by the result `101.43`

**Comment by spillaip** [comment]
Excellent, this is a fantastic.  I think, for better user experience, providing calculator interface is added advantage.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4607

**Comment by n-stein** [comment]
I've added a simple calculator popup. The amount (if any) is transferred to the calculator when you press the button. You click the buttons to calculate a new value, then click out of the calculator to automatically close the calculator and transfer the value to the amount field.

In the case of "Advanced" transfers it defaults to using the "Amount" but you can target the "To Amount" by first clicking in the "To Amount" field then clicking the calculator button.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/36a36421-9346-4227-a6d8-2d642a050887)

**Comment by spillaip** [comment]
@n-stein Looks cool! Thank you for your effort, appreciate it.

**Comment by renato-mmex** [comment]
I have the following error messages when starting this version:

<img width="407" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/5847a724-22d8-4bdc-bba9-0402f2862536">
<img width="411" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/cd37fd93-ce7f-4a11-8db7-e0a2bb67b49e">

By the way: on high-resolution screens, the calculator is very small and therefore difficult to use.

**Comment by n-stein** [comment]
> I have the following error messages when starting this version:

There is a new icon added to the theme. Uses who run a custom theme need to manually add a CALCULATOR.svg icon to the `controls` folder of their theme to continue using it.

**Comment by n-stein** [comment]
> By the way: on high-resolution screens, the calculator is very small and therefore difficult to use.

I've changed to make it follow the Options -> Font Size setting:

Normal:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/a34c753a-ec98-4429-a700-c5e974d32df2)

Huge:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/466b8e78-acdd-431c-b7ae-8ffa32085cff)

**Comment by spillaip** [comment]
@n-stein Hope you are retaining inline addition/subtraction feature.

**Comment by n-stein** [comment]
> Hope you are retaining inline addition/subtraction feature.

Yes, no change there. You can still type calculations directly in the amount text boxes, this just adds a secondary "visual" form of entering calculations.

**Comment by spillaip** [comment]
Truly appreciate your effort

**Comment by renato-mmex** [comment]
@n-stein Apparently you have added CALCULATOR.svg to all themes, but have not yet adopted it.

**Comment by vomikan** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/f2bd7607-ec60-4c2e-915d-62d03c640199)

**Comment by whalley** [comment]
MacOS.... 
![CleanShot 2024-05-04 at 16 26 24](https://github.com/moneymanagerex/moneymanagerex/assets/487345/4d1b27db-4a65-476d-ba48-966a40082eae)

**Comment by n-stein** [comment]
> MacOS....


Interesting, the buttons aren't square on macOS... No idea why that is the case. Is functionality ok?

**Comment by whalley** [comment]
> > MacOS....
> 
> 
> Interesting, the buttons aren't square on macOS... No idea why that is the case. Is functionality ok?

Yep, functionality seems is fine.

**Comment by n-stein** [comment]
In the release notes we should mention the new icon for those running custom themes

**Comment by whalley** [comment]
> In the release notes we should mention the new icon for those running custom themes

Added to draft release notes...

**Comment by ovari** [comment]
1. If there is not enough space to the right, should the calculator be shown to the left?
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/0809fb2f-3cbf-42c3-b113-245243a2201c)
2. Is the position of the calculator correct for RTL scripts?
3. Can a calculator please be shown next to the `Amount` fields in the `Split Transaction` window?
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/80c12ff9-25be-4235-8b11-0378969d7630)
4. Should `/` be changed to `÷`?
5. Should `*` be changed to `×`?
6. Should `C` be changed to `Clear` and be translatable?
7. Is `Del` translatable?

Thank you

**Comment by spillaip** [comment]
Here is the standard calculator layout on Microsoft Windows 11

![image](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/34cba997-3471-4dfa-9e94-185a6040c5d9)

**Comment by n-stein** [comment]
> If there is not enough space to the right, should the calculator be shown to the left?

Yes, we should always render it on screen.

> Can a calculator please be shown next to the Amount fields in the Split Transaction window

Thought about this, but I think it clutters the dialog too much if we include the button on every line. Perhaps one button at the bottom of the dialog instead?

> Should / be changed to ÷?
> Should * be changed to ×?
> Should - be changed to −?

I used these originally, but switched because the standard calculation functions only accept `/`,  `*`, and `-`. It can be changed, just requires explicitly checking for those button presses and replacing the string rather than just passing the button label to the text field which is what is currently done with all buttons other than Clear and Delete.

> Should C be changed to Clear and be translatable?

I think `C` is pretty ubiquitous, Microsoft uses `C` on the standard Windows calculator. I don't see a need to change it. Plus making the text longer would necessitate bigger buttons.

> Is Del translatable?

No, but I think it makes more sense to change to `⌫` rather than a translatable string.

**Comment by ovari** [comment]
>> If there is not enough space to the right, should the calculator be shown to the left?

> Yes, we should always render it on screen.

For LTR scripts, if it was always under the button with the right of the button and the right of the calculator in line, would it always work?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/2af50109-1caf-45d7-a5b3-156cbe42857a)

>> Can a calculator please be shown next to the Amount fields in the Split Transaction window

> Thought about this, but I think it clutters the dialog too much if we include the button on every line. Perhaps one button at the bottom of the dialog instead?

It would seem better to have the calculator next the to field it relates to.

![First row calculator in split](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/6c3ea1bb-c449-421c-a1d6-7cf013716b08)

![Second row calculator in split](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/bbc601cc-9618-4173-9261-fe232bb115ce)

>> Should C be changed to Clear and be translatable?

> I think C is pretty ubiquitous, Microsoft uses C on the standard Windows calculator. I don't see a need to change it. Plus making the text longer would necessitate bigger buttons.

Change `C` to `⌫`?

Linux Calculator

![Linux Calculator](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/26dc866f-4bf3-455c-acc4-34588d0f8d49)

Qalculate!
https://qalculate.github.io/

![Qalculate!](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ea2e56e1-4769-49c4-8c84-c0d3ad94e2d7)

>> Is Del translatable?

> No, but I think it makes more sense to change to ⌫ rather than a translatable string.

Yes, indeed.

Thank you

**Comment by ovari** [comment]
> > In the release notes we should mention the new icon for those running custom themes
> 
> Added to draft release notes...

Should the next MMEX release be a major version?

Should `Version: 1.8.1-Beta.1` be changed to `2.0.0-Beta.1`?

Thank you

**Comment by ovari** [comment]
Inspiration from Linux calculator: should `⌫` and a translatable `Undo` be incorporated instead of `C` and `Del`?

**Comment by spillaip** [comment]
My vote is for ⌫

**Comment by whalley** [comment]
> > > In the release notes we should mention the new icon for those running custom themes
> 
> > 
> 
> > Added to draft release notes...
> 
> 
> 
> Should the next MMEX release be a major version?
> 
> 
> 
> Should `Version: 1.8.1-Beta.1` be changed to `2.0.0-Beta.1`?
> 
> 
> 
> Thank you

Can't see anything justifying this.

**Comment by n-stein** [comment]
> Change C to ⌫?
> should ⌫ and a translatable `Undo` be incorporated instead of `C` and `Del`, respectively?

I don't know what the function of this button is on Linux, but it doesn't make sense for a "Clear All" button. The codepoint label for ⌫ is literally "Erase to the left" -- exactly what the `Del` button does. 

As for the `Del` button, the label `Undo` implies it reverses/removes the last thing the user entered which is not what this button does. If you enter a number, click to the left of it and hit `Del` it removes the character to the left not the number you just entered.


> Can't see anything justifying this.

Agreed, this is a very minor UI element. I'm working on a stocks/shares revamp (based on @vomikan's work a few years ago) that would justify a 2.0 label within the next few releases.

**Comment by ovari** [comment]
1. It seems that the convention is to have the `0` on the left and the decimal point `.` to the right.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/df8e1309-4c9c-43e2-b236-ac0d66876496)
Should the decimal point `.` and `0` be interchanged?
2. Should the decimal point `.` be translatable? In Hungarian, the decimal separator is a comma, i.e. `,`.
3. Pressing `.` on the keyboard only allows one `.`; however, using the mouse and clicking on the decimal point `.` allows multiple decimal points. Should this be fixed?
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/52846cce-0376-4d86-a146-6bdec8711352)

Thank you

**Comment by ovari** [comment]
> > Can't see anything justifying this.
> 
> Agreed, this is a very minor UI element. I'm working on a stocks/shares revamp (based on @vomikan's work a few years ago) that would justify a 2.0 label within the next few releases.

Should the version be changed from `1.8.1` to `1.9.0`?

**Comment by n-stein** [comment]
> Should the decimal point . be translatable? 

No, the decimal point is set based on the amount field decimal. This is defined by either the MMEX locale (if one is set in options) or the account currency if locale is blank.
