### ISSUE TITLE
Adjust the "Times Repeated" title in Recurring Transactions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#673]
The label "Times Repeated" might be confusing as the meaning of this wording would be to indicate the number of times the transaction has occurred in the past.
The actual meaning of the field, though, is the number of times the transaction should occur in the future. 
The label's title should be adjusted to better convey the meaning of the field.
Perhaps something like "# Left", "Occurs", "Repeats", etc.

**Comment by stef145g** [comment]
This label has been renamed: **Payments Left**
ref: https://github.com/moneymanagerex/moneymanagerex/issues/561
