### ISSUE TITLE
asking for a bug fix

### ISSUE THREAD

**Issue by 610e6613** [moneymanagerex/moneymanagerex#6732]
![Screenshot 2024-05-07 10 00 18](https://github.com/moneymanagerex/moneymanagerex/assets/169141486/868ed681-7514-49a9-b829-b7bf4c08ff88)
![Screenshot 2024-05-07 10 00 01](https://github.com/moneymanagerex/moneymanagerex/assets/169141486/db62b4c9-2045-4442-8284-359c5a58d95f)
![Screenshot 2024-05-07 09 59 49](https://github.com/moneymanagerex/moneymanagerex/assets/169141486/d76dc977-d284-44f4-915b-51d9121c8b54)
![Screenshot 2024-05-07 09 08 40](https://github.com/moneymanagerex/moneymanagerex/assets/169141486/7695a435-cb53-4368-a345-18b34bad9d3a)

**Comment by renato-mmex** [comment]
See: https://github.com/moneymanagerex/moneymanagerex/issues/5568

**Comment by whalley** [comment]
@610e6613 Did you resolve this?
