### ISSUE TITLE
Custom reports broke down after upgrading to 1.8.0

### ISSUE THREAD

**Issue by feimosi** [moneymanagerex/moneymanagerex#6736]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

I've just noticed that after upgrading to v1.8.0, my reports broke down because 
1) the charting library is no longer accessible, I was always importing it like this:
> `<script src = "ChartNew.js"></script>`

Now I can see this error:

<img width="1106" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/5721520/8f25e455-f2da-49cf-a380-7296fcea0bbe">

2) the default styling disappeared, which I assume is because the styles file changed too:
> `<link href="master.css" rel="stylesheet">`

Can you please guide me what are the current paths to use? The https://github.com/moneymanagerex/general-reports repo has outdated content too.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by lonemadmax** [comment]
I was using those paths prefixed by `memory:` in 1.6.4 and my reports still work after upgrading to current 1.8.1. In fact, I have all the resources prefixed with that. Probably copied them from: https://github.com/moneymanagerex/moneymanagerex/blob/8723054b5a4a66cfb0ecd59ec8d3f6ee59ff67a6/src/general_report_manager.cpp#L130-L147

**Comment by feimosi** [comment]
Thank you, that did the trick!
