### ISSUE TITLE
Unable to edit Stock Transaction

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6737]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
I have ability to view the transactions, but I am unable to find ability to edit the transaction

Add screenshot or other files if needed.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/13807297/39c3a4bb-85cf-4c43-a628-edda570ea830)

# Reproduction
Navigation: Stock Portfolios -> Stock -> Select a Stock

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:
A Button to Edit the transaction or provide ability to edit in the View Option.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
Stock transactions are one-way transactions. You edit them in the source account (for buys/withdrawals) or the destination account (for sells/deposits). They are not currently editable from the stock list.

**Comment by spillaip** [comment]
Got it, thank you for your response. It would be nice to edit in a same place.

**Comment by n-stein** [comment]
Now in the "View Stock Transactions" popup, double clicking on a row will open the share transaction:

![mmex_MExwkNpG44](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/74ad8a53-1fc4-4ab0-87c0-461bb616bfae)

**Comment by spillaip** [comment]
@n-stein Simply awesome, sincere appreciation to you.  This enhances the user experience of managing stock transactions.
