### ISSUE TITLE
Rest api

### ISSUE THREAD

**Issue by gamebeaker** [moneymanagerex/moneymanagerex#6740]
# Description of the feature
Implement rest api to allow using a other database than the local sqlite.
This would allow to separate the database from moneymanagerex and enable other uses.

Reasons:
The reason i got this idea is that i have a nextcloud server and searched for a money manager app on nextcloud and found nothing [Budget App - any interest?](https://help.nextcloud.com/t/budget-app-any-interest/57788).
If moneymanagerex-"server" is an app on the nextcloud store it would reach new people.
If rest api is supported it doesn't matter which database is in the backend (Postgres, Mariadb, MySQL etc.).

I am aware of [web-money-manager-ex](https://github.com/moneymanagerex/web-money-manager-ex) and that you can sync via your own cloud (dropbox etc.) if you use [android-money-manager-ex](https://github.com/moneymanagerex/android-money-manager-ex).

**Comment by whalley** [comment]
You may get better support fromm this project https://www.firefly-iii.org/ as given the architecture and lack of a large developer community for MMEX this is just not going to happen.

**Comment by gamebeaker** [comment]
@whalley thanks for the response.
