### ISSUE TITLE
Mohtly budget overview no longer availabe

### ISSUE THREAD

**Issue by aleskubac** [moneymanagerex/moneymanagerex#6743]
I just updated to version 1.8 (from version 1.5 or so). I found out that I no longer have the option to see monthly budgets in the budget category overview under budgets. There is a drop down menu in the top upper left corner which used to show list of budgeted years and months. Now it shows only years so I cannot see budget category overview for individual months.

Otherwise, all data concerning budgets remained in the application. So the application can work with mohtly budgets, but there is no longer an option to show monthly budget in budget category overview.

MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
This changed in v1.5.21 (commit 29fb60b38188a034fd6ff77fc9bbbc8be0ade147). It seems this was a conscious decision made to resolve #4214.

> there is no longer an option to show monthly budget in budget category overview.

The monthly budget is always shown in the budget reports -- it is either added to the yearly budget (by default) or overrides the yearly budget (if selected in options).

**Comment by aleskubac** [comment]
The change just limited usability of the app. I had a system of monthy budgets and annual budgets which is now more difficult to use. You can do whatever changes in options which people can use if they like, but why to limit funcitonality of the app?

We may have another tick box, which would enable monthly budget overview for those, who want it. Others could keep the box unticked.

For me the monthly budget overview was a good overview of budget of each month. Without option to select overview of moths the monthly budget overview became essentially redundant. I just do not need to review annual budget so often.

Again - why to limit this functionality?

Btw. I was keeping old version of the app and refused to update just to have the mohtly buget overview in place. I was waiting for the option to come back in some future version.

**Comment by n-stein** [comment]
It is simple to enable them in the dropdown, but I can see that in the report the monthly views don't respect the "view budgets by financial year" setting. For example, If I set my financial year starting July 1st and budget for 2024-05 then the budgeting panel correctly identifies 2024-05 as November but the budget category summary report for 2024-05 is based on May.

Actually, 1.5.20 has the exact same issue in the report, but also has this issue in the budgeting panel itself....

I can re-enable the monthly views for the category report, they don't make sense in the performance report. Will fix the financial month issue as well.

**Comment by n-stein** [comment]
Please test the beta once build finishes: https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49831677

**Comment by aleskubac** [comment]
Thank you!
