### ISSUE TITLE
Cashflow transactions doubling income payments

### ISSUE THREAD

**Issue by swjpanton** [moneymanagerex/moneymanagerex#6745]
> I have scheduled income transactions see attached screenshot
[screenshot 1.pdf](https://github.com/moneymanagerex/moneymanagerex/files/15320759/screenshot.1.pdf)
 1.pdf

today is 15 May
It is reconciled in my account: screenshot 2
[screenshot 2.pdf](https://github.com/moneymanagerex/moneymanagerex/files/15320780/screenshot.2.pdf)

In reports/Cashflow/transactions it is also showing. see screenshot 3.pdf
[screenshot 3.pdf](https://github.com/moneymanagerex/moneymanagerex/files/15320838/screenshot.3.pdf)

This means it is effectively doubling the balance in that account for today. therefore the projected cashflow is wrong.

To help if i changed the reconciled date to yesterday the balance is corrected the cashlow/transactions has removed the two credits seen in screenshot 3. see screenshot 4 and the cashflow is corrected.
[screenshot 4.pdf](https://github.com/moneymanagerex/moneymanagerex/files/15320888/screenshot.4.pdf)

hope this has provided enough info. Many thanks
simon Panton

> Please do not remove information attached below this text.

<hr> • Version: 1.8.0 64-bit<br>
 • Built: Apr 29 2024 08:12:03<br>
 • db 19 (aes128cbc)<br>
 • git 3325705b3 (2024-04-29)<br>
 • master<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMac 14.4)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0<br>
 • gettext 0.22.5<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.28.3<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 15.0.0 (clang-1500.3.9.4)<br>
<br>
OS:<br>
 • macOS Sonoma Version 14.4.1 (Build 23E224)<br>
 • System Locale: <br>
 • User Interface Language: en_GB.Western (Mac OS Roman)<br>
 • 1344x840 32-bit 144x144ppi

**Comment by pfbreton-perso** [comment]
I found this problem as well today.   Income today counted twice in the cashflow report

**Comment by swjpanton** [comment]
The above bug also applies to debits reconciled on the day too.

**Comment by n-stein** [comment]
This was an artifact of the addition of transaction time. The report pulled the current balance based on the end of today, then pulled the future transactions based on the start of today, so items for "today" were incorrectly included in both.

I have adjusted the report as well as some bugs I found on the home screen and checking panel related to the display of "future" transactions.

Now same-dated transactions in the future are marked as such if time is enabled and the time portion of the transaction is in the future:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/5b4feae7-145c-4602-b88a-79d06e4ed59f)

or if time is disabled:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/7421d7bb-2102-42e7-a052-783521e9cf38)

This also adjusts the balance calculations in the account view and home screen if "Ignore future transactions" is enabled. If you enable transaction time but ignore future transactions, the dashboard shows you the account values as of "now". So if you log a transaction for today but set the time in the future it is excluded from account views/balances until that time, the same as if the date portion was set in the future.

**Comment by n-stein** [comment]
@swjpanton if you have some time please give the beta a try once the AppVeyor build is complete and confirm it is behaving as expected:

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49830886

**Comment by swjpanton** [comment]
I have clicked on the link and have no idea had to review as I have never done this before. I cannot see a beta version as not sure what that looks like is it a mmex file?

From: n-stein ***@***.***>
Reply to: moneymanagerex/moneymanagerex ***@***.***>
Date: Thursday 16 May 2024 at 22:29
To: moneymanagerex/moneymanagerex ***@***.***>
Cc: Simon Panton ***@***.***>, Mention ***@***.***>
Subject: Re: [moneymanagerex/moneymanagerex] Cashflow transactions doubling income payments (Issue #6745)


@swjpanton<https://github.com/swjpanton> if you have some time please give the beta a try once the AppVeyor build is complete and confirm it is behaving as expected:

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49830886
