### ISSUE TITLE
not translated - delete menu

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6748]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1b1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/f4f1f140-4af6-4d97-b02c-b7c01a81a8c0)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/c8d4dc7c-b1c5-4570-a2f8-e57cfd0e33f2)

Translation has not been applied

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

transaction grid - context menu - delete - ...

Expected result:
translated

Actual result:
english;;;

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
On this homepage, users can make the translations themselves.
https://crowdin.com/project/moneymanagerex

**Comment by DevelopmentAnything** [comment]
> On this homepage, users can make the translations themselves. https://crowdin.com/project/moneymanagerex

I know.
I wrote the wrong title.🤣
and this is a bug issue. bcz I translated it into Korean.😉

**Comment by ovari** [comment]
The English source strings has been updated with keyboard accelerators. Crowdin strings first need to be updated from GitHub. @vomikan may be able to advise when this may happen.

**Comment by n-stein** [comment]
Looks ok now

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/4fce8830-ff41-466e-9894-9d487aff4e7c)
