### ISSUE TITLE
Thousands separator is missing, again

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#6763]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The thousands separation still does not work for transaction reports.

![240521](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/1ef8e91a-b9b4-4985-a9d0-ef9e9d7640cb)

And not on the dashboard and in the reports.

![Névtelen2](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/c3778d78-d4ba-42ca-a923-f721e6a0bdc3)

![Névtelen3](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/9aed056a-6a2f-4245-884a-0d9a003eb8c8)

![Névtelen4](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/3b538073-2629-46b1-bc19-c4fd3505e2fa)

  
![Névtelen](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/714fc806-a2bd-4459-b7ee-5df28fbfd911)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
What settings do you have in the options:
.
<img width="487" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/d74a4190-0ea0-42ba-842e-354160526f46">

**Comment by Heny67** [comment]
![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/0bed1078-4827-4e3e-b4c0-d63eba83337c)

**Comment by renato-mmex** [comment]
and if you set this option:
<img width="632" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/9fea2573-2a0d-493a-bbe1-914c092fc763">

**Comment by Heny67** [comment]
As I press the apply button:

![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/ab94047e-ff42-4cf0-972e-d9297b31d409)

**Comment by n-stein** [comment]
What does your system return if you run the command `locale` in terminal?

> As I press the apply button

Try free-keying in `hu_HU.UTF-8` in that locale field (i.e. add the `.UTF-8` suffix yourself), then you won't get this error.

**Comment by Heny67** [comment]
locale output:
LANG=hu_HU.UTF-8
LANGUAGE=hu
LC_CTYPE="hu_HU.UTF-8"
LC_NUMERIC=hu_HU.UTF-8
LC_TIME=hu_HU.UTF-8
LC_COLLATE="hu_HU.UTF-8"
LC_MONETARY=hu_HU.UTF-8
LC_MESSAGES="hu_HU.UTF-8"
LC_PAPER=hu_HU.UTF-8
LC_NAME=hu_HU.UTF-8
LC_ADDRESS=hu_HU.UTF-8
LC_TELEPHONE=hu_HU.UTF-8
LC_MEASUREMENT=hu_HU.UTF-8
LC_IDENTIFICATION=hu_HU.UTF-8
LC_ALL=


Well, I typed it in manually (hu_HU.UTF-8), it didn't give an error, but after restarting the problem was not solved.

![kép](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/ff171a6a-578a-4329-8a89-819c15880325)

**Comment by n-stein** [comment]
I forgot to ask are you running the Flatpak or your own build?

**Comment by Heny67** [comment]
own build

**Comment by n-stein** [comment]
Does the Flatpak have the same issue? Or the deb package and AppImage built here https://github.com/moneymanagerex/moneymanagerex/actions/runs/9326417719?

**Comment by Heny67** [comment]
Appimage: ./MMEX\ Money\ Manager-1.8.1-Beta.1-x86_64.AppImage 
/tmp/.mount_MMEX MSTa2AC/usr/local/bin/mmex: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

Flatpak:sudo apt install flatpak
Reading parcel lists... Finished
Building a tree of dependence... Finished
Read status information... Ready
E: This package cannot be found: flatpak
ppa added

**Comment by n-stein** [comment]
Try 

`flatpak run --env=WEBKIT_DISABLE_COMPOSITING_MODE=1 org.moneymanagerex.MMEX`

**Comment by n-stein** [comment]
Try 

`flatpak run --env=WEBKIT_DISABLE_COMPOSITING_MODE=1 org.moneymanagerex.MMEX`

**Comment by Heny67** [comment]
It works, thank you.

**Comment by n-stein** [comment]
Any change in the thousands separator?

**Comment by Heny67** [comment]
Yes, it's OK now.

**Comment by n-stein** [comment]
> The thousand separator in the reports is still not good.
> 
> Some report graphs are not even displayed. E.g.:Categories-Assistance,Where the money goes,Where the money comes from,Income/expenditure-beneficiaries

This is due to #6781 which has been resolved. Try the 1.8.1 beta on Flatpak (latest beta here https://output.circle-artifacts.com/output/job/df994362-71b3-4a75-a7cb-3b3c94864778/artifacts/0/tmp/artifacts/mmex.flatpak)

**Comment by n-stein** [comment]
> The thousand separator in the reports is still not good.

Actually, the report data labels and tooltips were still an issue. I have localized them now.

**Comment by Heny67** [comment]
No change.

![Képernyőkép 2024-06-06 06-33-23](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/5b62edfd-f935-4a15-9f25-653019fd8735)

**Comment by n-stein** [comment]
Linux beta will be updated after #6791 is merged

**Comment by n-stein** [comment]
This beta has the new labels https://output.circle-artifacts.com/output/job/cd2148b9-10b0-417a-8c34-cc3b36ca54e4/artifacts/0/tmp/artifacts/mmex.flatpak

**Comment by Heny67** [comment]
Separation by thousands:Ok.
Graphs: are visible,numbers are displayed correctly.
Thank you.
