### ISSUE TITLE
most recent notes issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#677]
it is not the twenty most recent notes, or even the twenty most common notes. On my PC, I have notes that in that field that have only been used once, but the supermarket that I go to every week does not appear and has to be typed out by hand every time. If I understand the notes correctly, they are supposed to be the most commonly used entries. That is certainly not the case with me. 

http://forum.moneymanagerex.org/viewtopic.php?f=10&t=6247

**Comment by guanlisheng** [comment]
has this been fixed? @vomikan

**Comment by vomikan** [comment]
may be only performance issue.

**Comment by guanlisheng** [comment]
what is the performance issue, is there any data to reproduce the issue?

**Comment by vomikan** [comment]
Just needed any account with about 10k transactions with notes.

**Comment by guanlisheng** [comment]
ok. let's use priority queue to process counterMap
http://www.cplusplus.com/reference/queue/priority_queue/

**Comment by guanlisheng** [comment]
@vomikan here you go


    const auto notes = instance().find(NOTES("", NOT_EQUAL)
        , accountID > 0 ? ACCOUNTID(accountID) : ACCOUNTID(-1, NOT_EQUAL));

    std::map <wxString, size_t> counterMap;
    for (const auto& entry : notes)
        counterMap[entry.NOTES]++;

    std::priority_queue<std::pair<size_t, wxString> > q;
    for (const auto & kv: counterMap)
    {   
        q.push(std::make_pair(kv.second, kv.first));
    }   

    while(!q.empty() && frequentNotes.size() < 20) 
    {   
        const auto & kv = q.top();
        frequentNotes.push_back(kv.second);
        q.pop();
    }

**Comment by vomikan** [comment]
Here is Trim() needed
~~~~~
for (const auto& entry : notes)
    counterMap[wxString(entry.NOTES).Trim()]++;
~~~~~
