### ISSUE TITLE
`Customize Transaction Report ` screenshot

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6773]
Customise Transaction Report (MMEX 1.8.1-Beta.1 64-bit, User Interface Language: en_GB.UTF-8, on Linux Mint 21.3 Cinnamon)

![Customise Transaction Report (MMEX 1.8.1-Beta.1 64-bit, User Interface Language: en_GB.UTF-8, on Linux Mint 21.3 Cinnamon)](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/ef82b81b-7d91-4f6c-8583-55a8707c16a4)

Attempt 2

**Comment by ovari** [comment]
Unfortunately, the image at https://github.com/moneymanagerex/moneymanagerex/issues/6773#issue-2316220731 doesn't show at https://github.com/moneymanagerex/moneymanagerex?tab=readme-ov-file#screenshots

@n-stein @whalley do you know how to fix?

Thank you

**Comment by n-stein** [comment]
You are attempting to use an image stored in your private user images which requires an authentication token to view. 

Instead, take your screenshot and drag/drop or copy/paste it into the comment box (or any comment box on any issue). GitHub will automatically upload it and generate a link like 

`![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/dcf430b4-0ed4-414f-8d20-3c73760ae235)`

Then just take the URL portion and use that in the src tag for the image in README.md.

**Comment by ovari** [comment]
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/d9dcdcd8-abda-4ae5-b6e4-4d137ef99613)

**Comment by ovari** [comment]
@n-stein thank you for the help. Should be done now. Do you want to use your image instead? If so, please advise the operating system and MMEX version. Thank you once again

**Comment by n-stein** [comment]
Looks like it worked. The Linux Mint image is fine.

**Comment by ovari** [comment]
Thank you @n-stein for your help.

**Comment by n-stein** [comment]
I should have noted that you don't need to drag & drop the image into a comment. You can drag & drop the image directly into the README.md if it is in edit mode and GitHub will generate the link there too. Might be easier next time.

**Comment by ovari** [comment]
Thank you
