### ISSUE TITLE
Import currency history from CSV/TXT

### ISSUE THREAD

**Issue by Squaredude** [moneymanagerex/moneymanagerex#6779]
# Description of the feature

In the Currency Manager there could be a way to import CSV/TXT data of the daily value of a currency. At the moment, it can only be done manually by picking a date for each value.

# Use cases

In my country we have a real mess with currency (it increases daily and there are several unofficial exchange rates to track), so I keep track of it manually using a spreadsheet. As I'm moving full-time to MMEX, I'd like to use its existing features, as I could generate reports based on currency (for example, to compare amounts).

However, there doesn't seem to be any way to import historical currency in the Currency Manager window. I can only input them one by one for every day. Since I have several sheets with years of data, this is not ideal.

**Comment by georgeef** [comment]
Maybe the program in https://forum.moneymanagerex.org/viewtopic.php?t=11141 can help you, after some editing of your sheets.

**Comment by Squaredude** [comment]
Thanks a lot! I completely forgot about this issue I opened.

I have "solved" this via a workaround, kind of like you did.

I opened the MMEX database with DBeaver and dumped my data via SQL, as I'm far more comfortable with that.

I'll close the issue so it doesn't waste more people's time.
