### ISSUE TITLE
Localized Pie-Charts are broken

### ISSUE THREAD

**Issue by moritzhoewer** [moneymanagerex/moneymanagerex#6781]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [x] Current master

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
When trying to view a report with a pie chart, no chart is showing.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/1266361/5baacc7e-fd75-43ed-856d-66b7f55d8f7b)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Try to view a report with a pie chart (e.g. "Where the money goes")

Expected result:
Chart is shown

Actual result:
Blank page is shown

# Additional information
This looks to be caused by #6567.  Investigation with a web-browser shows a JavaScript error in the apexcharts library, related to the locale that is passed
![image](https://github.com/moneymanagerex/moneymanagerex/assets/1266361/7fcab0bb-91a8-4d39-a5d0-dd633562b3a4)

Removing the ".UTF-8" suffix from the locale removes the error and restores the chart. I am working on a fix to `htmlbuilder.cpp` and will open a PR asap.

**Comment by n-stein** [comment]
Thanks for the fix!
