### ISSUE TITLE
Dashboard / report pages / Help sections do not work or are missing. The entire program becomes slow.

### ISSUE THREAD

**Issue by Squaredude** [moneymanagerex/moneymanagerex#6787]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

The sections where reports and dashboard should appear are completely blank.

The Help section has the same problem, as does the "General Report Manager" section.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Open any database MMEX version 1.8

Expected result:

The file is opened normally and all sections are visible.

Actual result:

The file is opened but the sections Dashboard / General Report Manager / Reports / Help do not appear at all.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/14142391/fba3d128-c1e4-43c1-a407-827a4c129ed6)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/14142391/a2f0a3ae-1142-454c-a68e-dd7d219cd9b6)

# Additional information

I'm on a relatively clean install of Pop_OS! 22.04 LTS, I've migrated from Windows 11 64-bit this week.

The only available install from the official MMEX website is a flatpak.

I downloaded the .deb of version 1.6.4 (2023.06.20) of MMEX, and it works correctly with no lag. The only issue is that my database was opened with version 1.8 and therefore is not compatible with the older version.

I tried running the Windows portable version with WINE, but I get the same problem as with flatpak 1.8 version, the Dashboard, etc. are not visible.

The program does work, in the general sense. I can add transactions and such. I can view the accounts and their transactions. I can go to the Scheduled Transactions section.

**Comment by n-stein** [comment]
Another user had a similar issue on Pop!_OS 22.04, try the solution outlined here https://github.com/moneymanagerex/moneymanagerex/issues/4269#issuecomment-1240175720

**Comment by n-stein** [comment]
> For posterity, setting WEBKIT_DISABLE_COMPOSITING_MODE=1 fixes it.\n\nFor flatpak (my case): flatpak run --env=WEBKIT_DISABLE_COMPOSITING_MODE=1 org.moneymanagerex.MMEX\n\nEdit: ref the issue #6396

This was going to be my next suggestion! Glad you worked it out.
