### ISSUE TITLE
Possible faulty german translation - msgid "Duplicate"

### ISSUE THREAD

**Issue by trm217** [moneymanagerex/moneymanagerex#6790]
As this is not a bug in the traditional sense, I removed the issue template.

I believe there is a [faulty translation](https://github.com/moneymanagerex/moneymanagerex/blob/590324f8e75572eebe9fcbcd2727db3b20fd4e41/po/de_DE.po#L2586) in the german translations.

The words in the translation is "Duplizieren". However, "Duplizieren" isn't really a status, but rather a action. The noun for that action would be "Duplikat".
Unless that status leads to any automated process, "Duplizieren" probably would be correct, but I don't think that's what the status is for.

I guess the issue comes from the derivation of the english translation where duplicate is both the noun and the verb at the same time.

**Comment by renato-mmex** [comment]
You can correct such "translation errors" yourself:
https://crowdin.com/project/moneymanagerex/de#/master/po
