### ISSUE TITLE
Scheduled Transaction did not activate automatically

### ISSUE THREAD

**Issue by gemellon** [moneymanagerex/moneymanagerex#6798]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

The Scheduled Transaction for one my accounts didn't get entered automatically at the last scheduled date. This is the first time this happened. "Grant Automatic Execute" was enabled. Usually this works.

# Reproduction

Is the bug reproducible? 
 - [ ] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:

1. Make a new Scheduled Transaction for future date
2. Grant "Automatic Execute"

Expected result:

Transaction is automatically entered on the chosen account without user action.

Actual result:

Transaction was not automatically entered. Scheduled Transaction showed that the date had passed and there was a red message but I forget now what it said, something like "this transaction is late". When I choose "Enter" on Scheduled Transaction window the transaction was entered correctly and the next one is scheduled.

# Additional information

I don't know why this happened. I didn't update the application recently and earlier Scheduled Transactions were working OK. I made a change 1 month ago or more ago to increase the value of the transaction, maybe this is the cause? I made a search in Issues and nothing there the same. Possibly was just one off.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
I can't reproduce.
