### ISSUE TITLE
Align with wxWidgets 3.2.5 release

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6799]
https://www.wxwidgets.org/news/2024/05/wxwidgets-3.2.5-released/

The latest release in stable 3.2 series is now [available on GitHub](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.5) and you can download archives with the library sources and documentation as well as binaries for the selected Windows compilers such as [Microsoft Visual C++](https://visualstudio.microsoft.com/), [MinGW-w64](https://mingw-w64.org/) and [TDM-GCC](https://jmeubank.github.io/tdm-gcc/) from there. You can also read the [updated documentation](https://docs.wxwidgets.org/3.2.5/) for this version online and, in particular, if you’re new to wxWidgets, you may find the [installation guide](https://docs.wxwidgets.org/3.2.5/overview_install.html) a good starting point.
Changes since 3.2.4

This release contains more than a hundred fixes and improvements for all platforms. Some of the most important ones are:

    Support macOS 14 Sonoma ([#23916](https://github.com/wxWidgets/wxWidgets/issues/23916), [#24054](https://github.com/wxWidgets/wxWidgets/issues/24054), [#24067](https://github.com/wxWidgets/wxWidgets/issues/24067), [#24073](https://github.com/wxWidgets/wxWidgets/issues/24073), [#24515](https://github.com/wxWidgets/wxWidgets/issues/24515)) and fix installation on some Apple Silicon Macs ([#23143](https://github.com/wxWidgets/wxWidgets/issues/23143)).
    Wayland-related fixes in wxGTK: clipboard ([#24391](https://github.com/wxWidgets/wxWidgets/issues/24391)), OpenGL ([#24076](https://github.com/wxWidgets/wxWidgets/issues/24076), [#24395](https://github.com/wxWidgets/wxWidgets/issues/24395)) and other ([#24021](https://github.com/wxWidgets/wxWidgets/issues/24021), [#24050](https://github.com/wxWidgets/wxWidgets/issues/24050), [#24051](https://github.com/wxWidgets/wxWidgets/issues/24051)).
    Fix crash when using wxApp in console wxGTK programs ([#24081](https://github.com/wxWidgets/wxWidgets/issues/24081)).
    Support for dates after 2038 in wxDateTime ([#24464](https://github.com/wxWidgets/wxWidgets/issues/24464)).

Other changes include:

    Fix support for using Chinese (zh-Hans-CN) locale under macOS ([#24396](https://github.com/wxWidgets/wxWidgets/issues/24396)).
    Fix alpha channel in bitmaps loaded from SVG in wxGTK ([#24064](https://github.com/wxWidgets/wxWidgets/issues/24064)).
    wxGenericListCtrl improvements ([#24292](https://github.com/wxWidgets/wxWidgets/issues/24292), [#24293](https://github.com/wxWidgets/wxWidgets/issues/24293), [#24311](https://github.com/wxWidgets/wxWidgets/issues/24311), [#24312](https://github.com/wxWidgets/wxWidgets/issues/24312), [#24332](https://github.com/wxWidgets/wxWidgets/issues/24332)).
    wxGrid improvements ([#24247](https://github.com/wxWidgets/wxWidgets/issues/24247), [#24286](https://github.com/wxWidgets/wxWidgets/issues/24286)).
    More high DPI fixes in wxMSW ([#24283](https://github.com/wxWidgets/wxWidgets/issues/24283), [#24196](https://github.com/wxWidgets/wxWidgets/issues/24196), [#24456](https://github.com/wxWidgets/wxWidgets/issues/24456)).
    Avoid new gcc 14 warnings in the headers ([#24502](https://github.com/wxWidgets/wxWidgets/issues/24502)).

**Comment by georgeef** [comment]
BUILD.md is not updated. See #6825
