### ISSUE TITLE
sync?

### ISSUE THREAD

**Issue by ghost** [moneymanagerex/moneymanagerex#6803]

**Comment by guanlisheng** [comment]
hi @stokebreakup, can you share more about your idea?

so far, MMEX data would be shared among your different devices via [BYOC](https://moneymanagerex.org/docs/features/usecloud/)

**Comment by guanlisheng** [comment]
still not sure what is your asking and what's your goal, 

Syncthing is working well with mmex and it is decentralized.

**Comment by guanlisheng** [comment]
ok, I c. this would be a little bit difference as the current design is to rely on some storage (instead of protocol).

btw, can you contribute too?

**Comment by guanlisheng** [comment]
thanks @stokebreakup ,
maybe you can help to desc what it looks like firstly. to be honest, i am still not sure what's it yet.

**Comment by guanlisheng** [comment]
Yes, WebMmex would be a good starter as it is b/s arch. Also, can you write something about integrating `nostr` here?
