### ISSUE TITLE
Payee autocomplete doesn't work anymore

### ISSUE THREAD

**Issue by sommella** [moneymanagerex/moneymanagerex#6814]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Previously, few chars were enough to have the Payee field auto-completed from the list of payees, now I need to click on the arrow to expand the dropdown menu in order to select it.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Insert a new expense, in the Payee field type some chars of a entry you know exists in your list.

Expected result:

Autocomplete to start immediately

Actual result:

Autocomplete works only when the entire word is written

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by jensb** [comment]
Cannot reproduce on current Git (1.8.1-beta) on Linux, and also on 1.8.0 release.
As soon as I start typing, the menu opens and matching Payee choices are shown. When I continue typing the list is reduced further.

**Comment by sommella** [comment]
Hi,

I tested on Ubuntu Desktop (in a Virtual Machine) and it works like expected.
For Windows, I executed it also on a different pc (both Windows 11) and the problem is the same.

Is there something more I can do?

Cheers

**Comment by n-stein** [comment]
I am unable to reproduce this issue in Windows 11.

Can you provide the details from the "About" dialog so we can see the details of the build?

**Comment by sommella** [comment]
Hi,

I had an empty item under my Payee list, that was causing the issue, removing it the autocomplete returned working.

Anyway here the About info you asked:


```
Money Manager Ex
• Versione: 1.8.0 64-bit
• Compilato il: Apr 29 2024 08:08:39
• Versione del Database: 19 (aes128cbc)
• Git commit: 3325705 (2024-04-29)
MMEX utilizza i prodotti di supporto seguenti:
• wxWidgets 3.2.4 (wxMSW 10.0)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV Schannel
• gettext 0.21
• apexcharts.js
Realizzato con:
• CMake 3.29.1
• MSBuild 17.9.8.16306
• Microsoft Visual Studio 17.0
• Microsoft Visual C++ 19.39.33523.0
• Windows SDK 10.0.22621.0
In esecuzione su:
• Windows 11 (build 22631), 64-bit edition
• Lingua del Sistema: 
• Lingua dell'Interfaccia Utente: it_IT.windows-1
```252
• 1920x941 32-bit 96x96ppi
