### ISSUE TITLE
Date picker don´t respect global date configuration/locale

### ISSUE THREAD

**Issue by adamitj** [moneymanagerex/moneymanagerex#6818]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

I'm using Flatpak version 1.8.0 and every date picker is using English US date format MM/DD/YYYY even though I have manually set it in the global configurations to DD/MM/YYYY. All record lists are using the formact correctly.

# Reproduction

![mmex-date-locale](https://github.com/user-attachments/assets/b8c75660-0fb3-453d-acc9-cdd8a14ecf5d)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Set in Tools --> Options --> Date format: DD/MM/YYYY.
2. Click in OK button.
3. Close and reopen Money Manager Ex.
4. Go to any account and create or edit a transaction.
5. Check the date picker with wrong format: MM/DD/YYYY.

Expected result:

Date picker might respect the configured date format DD/MM/YYYY

Actual result:

Date picker is using MM/DD/YYYY format no matter which format I use in global options.

# Additional information

Optionally you can set the application language to Brazillian Portuguese, but it has no effect too. 

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
What settings have you made here?
<img width="488" alt="image" src="https://github.com/user-attachments/assets/2c05d65a-5b51-4c43-951e-bfb398c51a42">

**Comment by adamitj** [comment]
Hello @renato-mmex 

This is my current configuration

![image](https://github.com/user-attachments/assets/d33add68-2901-4bec-8c2e-bc64668742e6)

**Comment by renato-mmex** [comment]
Sorry, I can't understand this on my computer.
What language settings/region does your computer have?
By the way: Running intl.cpl shows the settings.

**Comment by adamitj** [comment]
The picture I uploaded shows the date format **DD/MM/YYYY** using locale **pt_BR**, and language **Brazillian Portuguese**.

However, I'm using Linux (PopOS! 22.04) in English **en_US.UTF8**. Money Manager Ex is packaged in Flatpak.

This is my main computer and I use it with software and database development tools that are better seen in English than my native language.

I guess there's something related to the Date Picker widget/component only, because everything else is working fine with date format.

**Comment by renato-mmex** [comment]
Sorry, I overlooked the fact that it concerns Linux, I can't help you with that.
Maybe one of the developers can take a look at it.
@n-stein @whalley

**Comment by Lanna253** [comment]
man I wish it's me spending it 😭 TRACK THE NODE  it's ridiculous you have
no idea how these ppl smart lol I found it tracking software Im still shock

**Comment by n-stein** [comment]
Add pt language to Flatpak

```
flatpak config  --system --set languages 'en;pt'
flatpak config  --user --set languages 'en;pt'
```

Update config to download the new language

`flatpak update`

Override the Flatpak app locale

`flatpak override --user --env=LC_MESSAGES=pt_BR.UTF-8 --env=LANG=pt_BR.UTF-8 org.moneymanagerex.MMEX
`

**Comment by adamitj** [comment]
Hi @n-stein !

Thank you so much. I was not aware of `flatpak config`. Your instructions worked like a charm. 

![image](https://github.com/user-attachments/assets/854c16d7-3661-42a7-ad3e-b12596bc731e)

It also fixed something annoying I did not mention: the application was lagging using high CPU before setting the correct locales. After fixing it in Flatpak, everything is going smooth.
