### ISSUE TITLE
(trivial) incorrect / misleading German translation in transactions header

### ISSUE THREAD

**Issue by jensb** [moneymanagerex/moneymanagerex#6819]
MMEX version:
 - [X] 1.8.0
 - [X] current Git code

Operating System:
 - [x] Windows
 - [x ] Mac OSX
 - [x] Linux 

# Description of the bug
In de_DE.po, both "ID" and "Number" translate to "Nummer", which is confusing when they both appear in a table header as in transactions view. I suggest to just not translate "ID", and leave it to be "ID". If you must use a translation, use "Lfd." (laufend = running number, counter, ...) or "#" (universal sign for a number or counter).

# Reproduction
See [moneymanagerex](https://github.com/moneymanagerex/moneymanagerex/tree/master)/[po](https://github.com/moneymanagerex/moneymanagerex/tree/master/po) /de_DE.po.

Is the bug reproducible? 
 - [x] Always 

![image](https://github.com/user-attachments/assets/620dffa6-be72-4dfa-b912-5150ec5bc05a)

Note: This may also apply to other translations.

**Comment by renato-mmex** [comment]
If you wish, you can customise the text here.
https://crowdin.com/project/moneymanagerex/de#/master/po

**Comment by jensb** [comment]
Thanks! I browsed through some awkward sounding translations and edited them on crowdin.
Will these be merged automatically?

**Comment by renato-mmex** [comment]
> Will these be merged automatically?

Yes, but I don't know when.

**Comment by jensb** [comment]
OK. If this is handled automatically we can close the bug.
