### ISSUE TITLE
The model of scheduled transactions (billsdeposits) is confusing

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/moneymanagerex#6827]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [X] 5a67e5d (2024-08-04)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description

In the following
- `entry` means a scheduled transaction (a record in table `BILLSDEPOSITS_V1`)
- `panel` means the `Scheduled Transactions` panel,
- `edit form` means the `Edit Scheduled Transaction` dialog,
- `REPEAT_NONE entry` means an entry with `REPEAT_TYPE` equal to `REPEAT_NONE`,
- `REPEAT_IN entry` means `REPEAT_TYPE` is `REPEAT_IN_X_*`,
- `REPEAT_EVERY entry` means `REPEAT_TYPE` is `REPEAT_EVERY_X_*`,
- `REPEAT_countdown entry` means any other entry,
- `N` is abbreviation for `NUMOCCURRENCES`. 

A `REPEAT_NONE` entry is executed once (it is equivalent to a `REPEAT_countdown` entry with `N=1`).
The label `None` in the interface and the enum name `REPEAT_NONE` are confusing; they should better be `Once` and `REPEAT_ONCE`, resp.
The panel column `Repetitions` shows `∞` (infinity); it should show `1` (as for `REPEAT_countdown` entries with `N=1`).
The edit form accepts a positive number in `Payments Left`, and this number (`N>0`) also appears in the panel column `Repetitions`,  which doesn't make sense to the user; the field `Payments Left` should be reset to empty (i.e., `N` should be reset to `-1`).

`REPEAT_EVERY` entries with `N>0` are executed infinite times (until canceled), e.g., `REPEAT_EVERY_X_DAYS` with `N=1` is equivalent to `REPEAT_DAILY` with `N=-1`.
The panel column `Repetitions` shows the value of `N`; it should show `∞` (infinity).
The value of `N` in `Repetitions` is redundant anyway; it appears also in column `Frequency`.

`REPEAT_EVERY` entries with empty `Period` (`N=-1`) are more confusing.
The panel column `Frequency` shows `Every -1 Days/Months`, which (strictly speaking) doesn't make sense. After the entry is executed manually (by pressing the `Enter` button), its paid/due dates move backwards by 1 day/month, which is consistent with the text in column `Frequency`, however most probably this is not what the user wants. Even if this feature was useful (it is not), any negative `N` should be allowed by the interface; allowing backward movement by one unit only is mostly an unwanted side-effect of the special case of empty `Period` (which happens to be encoded with `N=-1`).
The panel column `Payment` shows `Inactive` for these entries, if their paid date is in the past. Although this feature effectively supports dummy (placeholder) entries which awkward date update, it is more of a confusion than a convenience. The user has other ways to keep dummy or "inactive" entries in the table, e.g., by setting the paid/due date in the far future. The model would be cleaner if all entries are active (executable), and can move only forward in time when they are executed. 
~~**Proposal:** `REPEAT_EVERY` entries with empty `Period` (`N=-1`) should either: (preferable) not be allowed, or (less preferable) be transformed to `REPEAT_NONE` (execute once and remove).~~
**Proposal:** If the edit form of a `REPEAT_EVERY` entry has empty `Period`, then set `N` to `1`, i.e., empty (or default from user's perspective) `Period` means `1`.

`REPEAT_IN` entries with `N>0` are meant to be executed twice (once at the defined paid/due date, and a second time after `N>0` days/months), e.g., `REPEAT_IN_X_DAYS` with `N=1` is equivalent to `REPEAT_DAILY` with `N=2`. 
The panel column `Repetitions` shows the value of `N`; it should show `2`.
Entries with `N>0` become entries with `N=-1` after their first execution.

`REPEAT_IN` entries with empty `Period` (`N=-1`) are the most confusing.
The panel column `Frequency` shows `In -1 Days/Months`.  
Their behavior is similar to `REPEAT_EVERY` entries with `N=-1`.
The panel column `Repetitions` shows `∞` (infinity), but the entries derived from `N>0` after one execution are meant to be executed once more.
Newly created entries with empty `Period` (`N=-1`) behave like derived entries, so they are meant to be executed only once. The last feature is a confusing alternative to `REPEAT_NONE`, while moving backwards in time after manual execution is as confusing as for `REPEAT_EVERY` entries with `N=-1`.
**Proposal:** Do not allow `REPEAT_IN` entries with empty `Period` (`N=-1`). In general do not allow "inactive" entries in the table (perhaps a better term for them is "zombie" entries).
After the first execution of a `REPEAT_IN` entry with `N>0`, update its paid/due dates and convert it to a `REPEAT_NONE` entry. In this way `REPEAT_IN` entries are executed twice (as intended) and then disappear, like `REPEAT_countdown` entries with `N=2` do.

Most of the confusion described above comes from the use of `NUMOCCURRENCES` for multiple purposes (its name describes its purpose only in `REPEAT_countdown` entries).
Another confusion in the source code comes from the use of `enum REPEAT_TYPE` for two purposes (encoding of `REPEAT` types and encoding of special values of `NUMOCCURRENCES`).
These two encodings have nothing to do with each other, and should be better separated, such that one does not restrict the other.

The multiplexing of `REPEAT` type and the auto execution modes into the `REPEATS` field in table `BILLSDEPOSITS_V1`, is less confusing, however in the long run it may create more problems than it solves. The database design is quite clean in general, and multiplexing is avoided in other places, since the application is not memory-limited. 
**Proposal for a future revision of the database:** Split the field `REPEATS` into `REPEATAUTO` and `REPEATFREQ`, and rename `NUMOCCURRENCES` to `REPEATPARAM`.

# Code review

All references to 5a67e5d (2024-08-04).

* `src/model/Model_Billsdeposits.cpp:281`

  If the transaction type is `WITHDRAWAL`, the account balance is reduced (instead of increased) by `TRANSAMOUNT`. The same should happen for a `TRANSFER` transaction.

* `src/model/Model_Billsdeposits.cpp:288,293`

  A `DEPOSIT` transaction can only increase (improve) the account balance. It should be allowed, even if the new balance is below the account limits (two or more such transactions could bring the balance above limits).

* `src/model/Model_Billsdeposits.cpp:333`

  The update of `bal[]` is not consistent with `Model_Account::balance()`.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: Normal execution of the application, without any special settings, shows the problems described above.

Expected result:

Actual result:

# Additional information

This issue is not actually a bug report, it is a description of unwanted (to the user) behavior.

# Task list

- [X] #6829
- [X] #6836
- [X] #6839
- [X] #6841
- [X] #6843
- [X] #6845
- [X] #6846

**Comment by whalley** [comment]
@georgeef Is your work on this now complete, subject to any bug reports?

**Comment by guanlisheng** [comment]
thank you, @georgeef  

@wolfsolver, can you take a look at this and consider the compatibility of them

**Comment by wolfsolver** [comment]
Yes. I open an issue on AMMEX refering this and do some check.
