### ISSUE TITLE
Drop-down list

### ISSUE THREAD

**Issue by Ilja-789** [moneymanagerex/moneymanagerex#6830]
> I have created a custom field. Which contains information about whether the DS is returned to the budget or not. However, when creating a report based on criteria, the report is created empty. In this case, the text is just a set of broken characters. (I created a field with a drop-down list). I sent the screenshot. (Example; RћrµµcЂ°C†resЏ Рr¶Rґr°Rµc' Rѕr·RЂr°C'R"RY.). Despite the fact that when trying to run the report, the program crashed, but there was no information about the error.  You can contact me by e-mail: ilja.strikoff@yandex.ru .
![Снимок экрана 2024-08-07 135314](https://github.com/user-attachments/assets/0173c8ea-69e6-47f7-bd76-dc0e3bd935e2)
> Пожалуйста, не удаляйте информацию, указанную ниже этого текста.

<hr> • Version: 1.8.0 <br>
 • Built: Апр 29 2024 08:28:06<br>
 • db 19 (aes128cbc)<br>
 • git 3325705 (2024-04-29)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.5.0-DEV Schannel<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.29.1<br>
 • MSBuild 17.9.8.16306<br>
 • MSVS17.0<br>
 • MSVSC  19.39.33523.0<br>
 • Windows SDK 10.0.22621.0<br>
<br>
OS:<br>
 • Windows 11 (build 22621), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: ru_RU.windows-1251<br>
 • 1600x900 32-bit 96x96ppi

**Comment by n-stein** [comment]
Does it crash only when running the 'Transaction Report', or also in the account view?

Do you see the broken characters in the transaction dialog and account view or only in the transaction report?

Can you share some examples of the text that you entered as the choices in your custom field?

**Comment by Ilja-789** [comment]
In this video, I sent the process of creating a custom field through a special manager. 

The failure occurs when you request a report based on criteria. This will be visible in my video. 

Everything is fine in the transaction itself. Such symbols appear only when requesting a report based on criteria. 

If you have any more questions, I will be happy to help.

Uploading bandicam 2024-08-10 15-49-32-218.mp4…
