### ISSUE TITLE
Export selected transactions to clipboard as CSV or rich text formatted table

### ISSUE THREAD

**Issue by jensb** [moneymanagerex/moneymanagerex#6844]
Every now and then I need selected (or tagged or ...) transactions in another application, maybe a spreadsheet, or a mail.
I'd like to be able to copy & paste these transactions from MMEX in a formatted way into the clipboard, maybe even choosing which columns to actually export, so that apps like Libreoffice Calc, Excel, but also all rich text content accepting applications can receive the data.

I'd put this into the context menu as an "Export selected ..." option which then opens a dialog with a column selection menu.

Does this exist or work in some non-obvious way?

If it doesn't, but would be interesting to have, I can draft something.

**Comment by renato-mmex** [comment]
I select the desired transactions, right-click on the ‘Copy transactions’ function and paste the data into Excel.

**Comment by jensb** [comment]
Hm.
This was the first thing I checked, but I cannot replicate this with LibreOffice Calc.
I cannot even get stuff into the clipboard on Linux.

**Comment by jensb** [comment]
Hm.
This was the first thing I checked, but I cannot replicate this with LibreOffice Calc.
I cannot even get stuff into the clipboard on Linux. Is this a WxWidgets bug or a mmex bug?

**Comment by renato-mmex** [comment]
You did not mention that you work under Linux, otherwise I would not have answered you, because I am Windows orientated.

**Comment by jensb** [comment]
True. However, since MMEX uses WxWidgets which claims to be portable, this is still a useful comparison, because it means there may be a portability issue.

**Comment by jensb** [comment]
I double checked.
"Copy transaction" actually works perfectly also on Linux and Libreoffice.
I was using "Copy text to clipboard", which only copies a single cell.
Sorry, and thanks for testing this on Windows!

**Comment by renato-mmex** [comment]
You're welcome. Next time, please mention which operating system and which MMEX version you are using. This will make clarification much easier for us. Greetings from Switzerland / Renato
