### ISSUE TITLE
Suppression de catégorie

### ISSUE THREAD

**Issue by Freland38** [moneymanagerex/moneymanagerex#6856]
J'ai créé une catégorie. J'ai imputé 1 débit sur cette catégorie. Je me sui ravisé pour créer une sous-catégorie d'une autre catégorie et j'ai déplacé le débit sur cette nouvelle sous-catégorie.
J'ai vérifié qu'il n'y avait plus aucune opération imputée sur la 1ere catégorie pour pouvoir la supprimer : La commande "supprimer" est grisée et donc non disponible à la suppression.

![Capture d'écran 2024-09-05 084817](https://github.com/user-attachments/assets/d362b5c9-8b11-46eb-a09a-97e125af5ae5)

MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by Freland38** [comment]
"Je me suis ravi" est une erreur. Je voulais dire j'ai changé d'avis

**Comment by renato-mmex** [comment]
<img width="640" alt="image" src="https://github.com/user-attachments/assets/b054a89c-111f-4ddc-b636-249387803a78">

**Comment by Freland38** [comment]
Encore une fois, merci beaucoup Renato.
