### ISSUE TITLE
Disallow blank payee name in edit dialog

### ISSUE THREAD

**Issue by SG24User** [moneymanagerex/moneymanagerex#6863]
Some time ago (within the past year I believe), my automatic dropdown selection list for Payee stopped working.  I used to be able to start typing and the dropdown list would automatically pop up and I could hit enter for the selected payee, or use the cursor keys to select the correct one.

This functionality still works for category.

I can work around it by pressing alt/down cursor to bring up the list, but this takes my hands further from the keys I'm using for input.
This is especially annoying if a Payee is unique after only a few characters and I either have to fully type it out, or force the list and select from it before it will auto-fill the Category for me.

Example when typing in Category field (this is working fine still):

![image](https://github.com/user-attachments/assets/1fb96e6f-6401-4ef8-88d7-966294f4f451)

Thank you any assistance you can provide.

<hr> • Version: 1.8.0 64-bit<br>
 • Built: Apr 29 2024 08:08:39<br>
 • db 19 (aes128cbc)<br>
 • git 3325705 (2024-04-29)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.5.0-DEV Schannel<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.29.1<br>
 • MSBuild 17.9.8.16306<br>
 • MSVS17.0<br>
 • MSVSC  19.39.33523.0<br>
 • Windows SDK 10.0.22621.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: en_US.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by whalley** [comment]
Seems to work fine on MacOS and Win 11/ARM running in Parallels VM.

**Comment by SG24User** [comment]
I am in the process of moving to a new Windows 11 Pro PC (from Windows 10 Pro PC).  I will try it again once I move over and if I can reproduce it, I will create a new dataset to rule out some corruption with my own.  Thanks.

**Comment by SG24User** [comment]
I have moved to my new PC and the problem follows my database.  I created a new database to test the functionality and that works fine, so this is pointing to either database corruption, or hitting a limit on number of payees affecting usability.  I have at least 400 payees.  Optimizing the database did not help.  The Database Check and Debug function first shows OK, then indicates not to proceed without MMEX support and a debug file.  Looking for help here.  Thanks.

**Comment by whalley** [comment]
@SG24User Can you share an example database that replicates the problem, perhaps with all transactions deleted and just the payees. If you want to mail it rather that upload here then please send to support@moneymanagerex.org

**Comment by SG24User** [comment]
Thanks Mark,

I will do this on my old PC before I wipe the drives.  Might take a day or
two though.

Regards,
Stewart

**Comment by n-stein** [comment]
The issue occurs when you have a payee with blank text. Look in your payee manager and look for a blank line at the top. Right click and remove it.

![image](https://github.com/user-attachments/assets/a7d49c23-3a41-4ce9-a627-f3ec9d83bc0a)

**Comment by SG24User** [comment]
Yes, the source of my problem was the blank payee.  I was able to fix the issue removing the blank payee, and recreate the issue by editing an existing payee and blanking out all the fields.  It may be worth fixing this bug, or adding some script into the Optimize Database function to correct blank entries.  In testing, I can blank out the fields when editing a payee and save the payee.  I can not do the same for Categories or Tags, so this is an inconsistency.  Not urgent, but worth fixing.  Thanks everyone for helping trace this down.

**Comment by nickallington** [comment]
I also had this problem, and found a blank at the top of the payee list. However, I am pretty sure I DID create that, by accident, when trying to make adjustments to certain payees, in spite of what has been said above. So I think there is a bug here, though probably not a very important one since there is an easy solution to the problem.

**Comment by n-stein** [comment]
> In testing, I can blank out the fields when editing a payee and save the payee. I can not do the same for Categories or Tags, so this is an inconsistency.

Indeed, this shouldn't be allowed. 

> However, I am pretty sure I DID create that, by accident, when trying to make adjustments to certain payees, in spite of what has been said above. So I think there is a bug here, though probably not a very important one since there is an easy solution to the problem.

Probably due to the bug described above where the "Edit Payees" allows blanking out the name.

I've fixed this.
