### ISSUE TITLE
Database encryption change to AES256

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#6871]
MMEX version:
 - [ ] 1.7.0
 - [] 1.8.0
 - [X ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Just downloaded 1.8.1-RC.1 from Appveyor and confused by the following..
![Screenshot 2024-09-12 150802](https://github.com/user-attachments/assets/0a0b265c-4752-469b-a549-07cbf8670575)
This shows aes128cbc, MMEX has been changed to use AES256cbc by "#6538 Upgrade database encryption to AES256". 

Looking at the code in util.cpp, this displays the default...

wxSQLite3Cipher::GetCipherName(wxSQLite3Cipher::GetGlobalCipherDefault()) 

which has not changed.

The AES256 implementation has been made by specifying AES256 in the MMEX source where ever it is required.

Personally I would vote to remove aes128cbc from the Database line on the "About panel" as to my mind it only serves to confuse and is rather meaningless now.
Alternatively perhaps hardcode AES256 ?

Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
> Personally I would vote to remove aes128cbc from the Database line on the "About panel" as to my mind it only serves to confuse and is rather meaningless now.

I would agree that the ABOUT box is probably not the right place for this information as everything else is the box displays information about the application build and environment and not database specific information.

**Comment by whalley** [comment]
> > I would agree that the ABOUT box is probably not the right place for this information as everything else is the box displays information about the application build and environment and not database specific information.
> 
> This isn't really database-specific information though, it is telling the user the default encryption algorithm for the version of MMEX they are running.
> 
> The global cipher default for wxSQLite3 is still AES-128, so we can't use `wxSQLite3Cipher::GetGlobalCipherDefault()`. We now encrypt using SQLCipher Version 4 which is AES-256-CBC with the SHA512 hash algorithm for HMAC calculation, so if we were to hard code we would write something like `aes256cbc-hmac-sha512`, or maybe more succinctly `SQLCipher 4`.

OK, my misunderstanding. Let's code it to `aes256cbc-hmac-sha512` then.

**Comment by n-stein** [comment]
I incorporated this minor change in #6984.
