### ISSUE TITLE
Menu "Find all transactions with Amount" does not switch to filter view

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/moneymanagerex#6874]
MMEX versions:
 - [X] 1.8.0
 - [X] 1.8.1 RC 1

Operating System:
 - [X] Mac OSX

## Reproduction
 - [x] Always

## Description of the bug

In the transactions panel of a single account, right-click on an amount (in the Withdrawal or Deposit columns) opens a menu which has a choice "Find all transactions with Amount ..." (at the bottom).

With MMEX 1.8.0, this choice switches to the "All Transactions" panel, where it shows the search results. The transactions filter is set automatically to "View with Transaction Filter".

With MMEX 1.8.1 RC 1, this choice switches to the "All Transactions" panel, but does not show the search results. The transactions filter is set automatically to "View All Transactions". The filter is properly configured (as can be seen if "View with Transaction Filter" is selected manually), but the "All Transactions" panel does not switch to it.

**Comment by n-stein** [comment]
Fixed #6935
