### ISSUE TITLE
Copying transactions: Take over original date

### ISSUE THREAD

**Issue by mraht** [moneymanagerex/moneymanagerex#6883]
# Description of the feature
If one copies transactions via the context menu of transaction entries the date of today is being used to create the copied transactions. I'd like to choose wether to use the original date the transaction occured for the new copied entry or today.

# Use cases
I create offsetting accounting entries and therefore need the original date.

**Comment by vomikan** [comment]
it should be option in the application settings.

**Comment by georgeef** [comment]
In MMEX 1.8.0 for macOS it is in:
- Options... -> General -> Use Original Date when Duplicating Transactions [at the bottom]

**Comment by mraht** [comment]
Thanks @georgeef, found it :)
