### ISSUE TITLE
Please allow `Cash Flow - Daily` to be translatable

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6897]
MMEX version: 1.8.1

Operating System: GNU/Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Please allow `Cash Flow - Daily` to be translatable.

Is the bug reproducible? Always

Reproduction steps:

Show `Cash Flow - Daily` window title in Hungarian.

Expected result:

Show in Hungarian.

Actual result:

Incorrectly showing in English, not Hungarian.

![image](https://github.com/user-attachments/assets/fb7329f8-37a9-4d92-85f8-f18fa6815a20)

Right-click in About dialog box to copy all the data does not work. A screenshot of the About dialog workaround shown below:
![image](https://github.com/user-attachments/assets/644f8e07-a727-4aae-808c-2e007dfeeef4)

**Comment by n-stein** [comment]
It is already translated, just needed to use the translated string in the dialog title.

**Comment by ovari** [comment]
Thank you for your https://github.com/moneymanagerex/moneymanagerex/pull/6911 patch. Will this be merged before [v1.8.1](https://github.com/moneymanagerex/moneymanagerex/milestone/44) release? Thank you
