### ISSUE TITLE
Fraction part may get lost after opening transaction for edit

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#690]
http://forum.moneymanagerex.org/viewtopic.php?f=10&t=6165

https://sourceforge.net/p/moneymanagerex/bugs/808/

Windows 7 x64, system locale settings are set to "Russian Federation", MMEx default currency is set to RUB. One of my accounts uses USD as a default currency. For USD the default is to use dot (".") as a decimal separator. In case I create a new USD transaction having a non-zero fractional part (123.45 for example) and save it - MMEx stores correct value into the database and displays proper value in the account view. But as soon as I try to open this transaction for edit the amount displayed in the dialog box have fractional part lost (i.e. 123.45 changes into 123.00). If a user wouldn't pay attention and would click on "Ok" button the transaction would be silently changed to contain a new (and wrong) value.
Changing USD definition to use colon instead of dot as a decimal separator workarounds the issue.
I think that this is a bug and it is a nasty one as data may get lost silently. IMHO as long as MMEx intend to support different decimal separators for different currencies it should be able to handle any configured decimal separator properly in transaction edit dialog box without loosing frational parts of values.

**Comment by guanlisheng** [comment]
would we close this? @vomikan
