### ISSUE TITLE
Blocco della visualizzazione dati di un solo conto

### ISSUE THREAD

**Issue by Berio35Elisir8** [moneymanagerex/moneymanagerex#6910]
[money manager ex.docx](https://github.com/user-attachments/files/17188754/money.manager.ex.docx)

Questo file contiene le indicazioni per il debug che si è verificato.

Resto in attesa delle Vostre indicazioni

Grazie

Giovanni Falciani
gfalciani@gmail.com

> Sostituisci questo testo (evidenziato con >) con una dettagliata descrizione del tuo problema.
> Per favore non rimuovere le informazoni allegate sotto questo testo.

<hr> • Version: 1.8.0 64-bit<br>
 • Built: Apr 29 2024 08:08:39<br>
 • db 19 (aes128cbc)<br>
 • git 3325705 (2024-04-29)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.5.0-DEV Schannel<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.29.1<br>
 • MSBuild 17.9.8.16306<br>
 • MSVS17.0<br>
 • MSVSC  19.39.33523.0<br>
 • Windows SDK 10.0.22621.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: it_IT.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by renato-mmex** [comment]
As this is an English forum, I have translated her request:

> This file contains the directions for the debugging that occurred.
> 
> I look forward to your directions
> 
> Thank you
> 
> John Falciani
> gfalciani@gmail.com

It would certainly be an advantage if you could also tell us in detail what led to this error.
An alternative would be for you to send your .mmb to mmex-reg@bluewin.ch and we will take a look at it.
Of course, we will treat your data very confidentially.

By the way: use www.deepl.com to translate between Italian/English

Sarebbe sicuramente un vantaggio se potesse anche dirci in dettaglio cosa ha portato a questo errore.
In alternativa, potete inviare il vostro .mmb a mmex-reg@bluewin.ch e noi lo esamineremo.
Naturalmente tratteremo i vostri dati con la massima riservatezza.

A proposito: utilizzate www.deepl.com per tradurre tra italiano e inglese.

**Comment by Berio35Elisir8** [comment]
Grazie per la cortese a pronta replica alla mia mail.

Allego copia del file .mmb interessato

Rimango in attesa delle Vostre indicazioni per risolvere il problema.

Ancora grazie

giovanni falciani
________________________________
Da: Renato ***@***.***>
Inviato: lunedì 30 settembre 2024 18:27
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: Berio35Elisir8 ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Blocco della visualizzazione dati di un solo conto (Issue #6910)


As this is an English forum, I have translated her request:

This file contains the directions for the debugging that occurred.

I look forward to your directions

Thank you

John Falciani
***@***.******@***.***>

It would certainly be an advantage if you could also tell us in detail what led to this error.
An alternative would be for you to send your .mmb to ***@***.******@***.***> and we will take a look at it.
Of course, we will treat your data very confidentially.

By the way: use www.deepl.com<http://www.deepl.com> to translate between Italian/English

Sarebbe sicuramente un vantaggio se potesse anche dirci in dettaglio cosa ha portato a questo errore.
In alternativa, potete inviare il vostro .mmb a ***@***.******@***.***> e noi lo esamineremo.
Naturalmente tratteremo i vostri dati con la massima riservatezza.

A proposito: utilizzate www.deepl.com<http://www.deepl.com> per tradurre tra italiano e inglese.

**Comment by renato-mmex** [comment]
Done, can be closed
