### ISSUE TITLE
Lost Data

### ISSUE THREAD

**Issue by jimbrancato** [moneymanagerex/moneymanagerex#6920]
I had 3 months worth of entries, I went to delete 1 transaction and I accidently erased all 3 months of transactions. Is there any way to retrieve everything I deleted?
Also is there any way to backup my worksheet to be able to retrieve it at a later date if needed?

**Comment by renato-mmex** [comment]
In your menu there is ‘Deleted Transactions’, here you can restore the bookings.

**Comment by jimbrancato** [comment]
Where in the menu.I can’t find anything on how to restore deleted items.Sent from my iPhoneOn Oct 4, 2024, at 1:43 AM, Renato ***@***.***> wrote:﻿
In your menu there is ‘Deleted Transactions’, here you can restore the bookings.

**Comment by whalley** [comment]
> I had 3 months worth of entries, I went to delete 1 transaction and I accidently erased all 3 months of transactions. Is there any way to retrieve everything I deleted? Also is there any way to backup my worksheet to be able to retrieve it at a later date if needed?

What version of MMEX are you using?

**Comment by jimbrancato** [comment]
Money Manager Ex 1.8.0 64-bitSent from my iPhoneOn Oct 4, 2024, at 11:32 AM, Mark Whalley ***@***.***> wrote:﻿

I had 3 months worth of entries, I went to delete 1 transaction and I accidently erased all 3 months of transactions. Is there any way to retrieve everything I deleted? Also is there any way to backup my worksheet to be able to retrieve it at a later date if needed?

What version of MMEX are you using?

**Comment by jimbrancato** [comment]
Can you call me to help me do this ?Sent from my iPhoneOn Oct 4, 2024, at 11:48 AM, Jim Brancato ***@***.***> wrote:﻿Money Manager Ex 1.8.0 64-bitSent from my iPhoneOn Oct 4, 2024, at 11:32 AM, Mark Whalley ***@***.***> wrote:﻿

I had 3 months worth of entries, I went to delete 1 transaction and I accidently erased all 3 months of transactions. Is there any way to retrieve everything I deleted? Also is there any way to backup my worksheet to be able to retrieve it at a later date if needed?

What version of MMEX are you using?

**Comment by renato-mmex** [comment]
<img width="251" alt="image" src="https://github.com/user-attachments/assets/e264ed3d-1ecb-43d0-aec4-4329d4d86aa0">

**Comment by jimbrancato** [comment]
This is all that shows

Sent from my iPhone

**Comment by renato-mmex** [comment]
Github does not receive attachments by e-mail

**Comment by jimbrancato** [comment]
So how do I get help from to retrieve my deleted data now

**Comment by renato-mmex** [comment]
There are .bak files that you can rename to file.mmb and call up with MMEX. Unless you have switched off the backup function in the settings.

**Comment by renato-mmex** [comment]
@jimbrancato Apparently the problem has been solved.

**Comment by jimbrancato** [comment]
Went to the Geek Squad and got the files recovered.

**Comment by renato-mmex** [comment]
can be closed
