### ISSUE TITLE
No chart in Cash Flow Report

### ISSUE THREAD

**Issue by craveiroh** [moneymanagerex/moneymanagerex#6927]
On the Daily or Monthly Cash Flow Report I can't see the chart, I can only see the table with the flow for each day.

**Device Information:**
• Version: 1.8.0 64-bit
• Built on: Apr 29 2024 08:08:39
• Database version: 19 (aes128cbc)
• Git commit: 3325705 (2024-04-29)
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxMSW 10.0)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV Schannel
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.29.1
• MSBuild 17.9.8.16306
• Microsoft Visual Studio 17.0
• Microsoft Visual C++ 19.39.33523.0
• Windows SDK 10.0.22621.0
Running on:
• Windows 11 (build 22631), 64-bit edition
• System Locale: 
• User Interface Language: en_GB.windows-1252
• 1920x1200 32-bit 96x96ppi

**Comment by vomikan** [comment]
#6925
