### ISSUE TITLE
"Find all transactions" not working from checking account panels

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6935]
MMEX version:
 - [X] 1.8.1

In any account panel other than the "All Transactions" view, right clicking and selecting "Find all transactions with ..." jumps to the "All Transactions" page, but doesn't automatically apply the filter. The filer is saved correctly, the panel is just defaulting to "View All Transactions" instead of "View Transaction Report..."

**Comment by n-stein** [comment]
Seems it was broken by e88c3e58df3584ab19ab09c30a3100f3d2aa7eab

**Comment by n-stein** [comment]
Fixed by using the defined constant instead of hard coding.

**Comment by ovari** [comment]
Thank you for fixing what we broke. Is it correct to assume it is fixed for user interfaces set to different locales too? Thank you

**Comment by georgeef** [comment]
Is #6874 related to this?

**Comment by n-stein** [comment]
> Is #6874 related to this?

Yup, same issue. Sorry I didn't see yours was already logged. Should be fixed now.
