### ISSUE TITLE
`User Interface Language` list incorrectly showing in English when System locale is selected (System locale = English, Australia)

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6938]
1. Linux Mint 22 Cinnamon operating system locale is `English, Australia`
2. MMEX Menu Bar, View, User Interface Language, System Default
3. Bug: Languages not translated into native languages
![image](https://github.com/user-attachments/assets/70045570-fb27-4693-93d1-d83eeb3defa0)
4. MMEX Menu Bar, View, User Interface Language, hu-HU magyar (Magyarország)
5. Languages are translated into native languages
![image](https://github.com/user-attachments/assets/0aea4b6c-8963-424e-ae52-655d1b7f551a)

Is the bug reproducible? Always

Seems to be a regression as this was previously working correctly.

```
Money Manager Ex
• Version: 1.8.1-RC.1 64-bit
• Built on: Oct 25 2024 13:38:43
• Database version: 19 (aes128cbc)
• Git commit: 468681c00 (2024-10-25)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.6 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 libidn2/2.3.7 libpsl/0.21.5 nghttp2/1.63.0
• gettext 0.22.5
• apexcharts.js
Built with:
• CMake 3.30.4
• GNU Make 4.4.1
• GCC 14.2.0
Running on:
• GNOME.47 (Flatpak runtime)
• GNOME 47 (Flatpak runtime) ""
• Linux 6.8.0-47-generic x86_64
• X-CINNAMON (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en.UTF-8
• 1280x720 24-bit 96x96ppi
```

Thank you

**Comment by n-stein** [comment]
That should fix it. 

Previously I was merging the common UI Language translations into the individual language catalogs, but that doesn't work if there is no catalog for the locale (e.g. en_AU). I've switched to sending the common catalog to only the `en_US` directory and loading it explicitly from there first before switching to the UI Language directory to load the mmex catalog. This should work regardless of the system locale.
