### ISSUE TITLE
UI Elements overlap in Transaction Report Editor

### ISSUE THREAD

**Issue by Jerry23011** [moneymanagerex/moneymanagerex#6943]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Some UI elements from "Specify" section seem to overlap with the bottom section in transaction report editor. Please see screenshots below.
<img width="529" alt="1" src="https://github.com/user-attachments/assets/aea670ba-786b-41c5-9a24-efe58da94b25">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Click Transaction Report
2. Observe the UI in the editor

Expected result:
UI to not overlap each other.

Actual result:
UI overlaps in the editor

**Comment by whalley** [comment]
Will be fixed in 1.8.1. https://github.com/moneymanagerex/moneymanagerex/issues/6393

**Comment by Jerry23011** [comment]
> Will be fixed in 1.8.1. #6393

Thank you
