### ISSUE TITLE
subtract monthly budget from yearly budget in reporting - strange behaviour

### ISSUE THREAD

**Issue by giongy** [moneymanagerex/moneymanagerex#6957]
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Hi, I encountered an error in the budget report and would like to submit it to you to see if it is reproducible and maybe fixable. by flagging the “subtract monthly budget from yearly...” option, I see that in the budget performance the various “est.” columns randomly turn red. It seems to change behavior if I change the income category name by making them alphabetically first, like “1-incomes”.

wrong red color, with income category named "Entrate":
![image](https://github.com/user-attachments/assets/d3c16db5-e3f6-4481-934e-dd453778eb00)

all seems fine if I rename "Entrate" in "1-Entrate" make the income category first:
![image](https://github.com/user-attachments/assets/af59e0a4-0c4c-44d4-8f62-44bcd082ed0a)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

**Comment by giongy** [comment]
could be that  ` estimateTotal[12]` must be reset at the end of "for" ? 

![image](https://github.com/user-attachments/assets/38bc0801-8f23-4506-9279-04843ecf5d90)

as it is, estimateTotal[12] increase every cell , every months and this calculation could be wrong:

` hb.startSpan(estimateVal, wxString::Format(" style='text-align:right;%s' nowrap"
                            , (budgetDeductMonthly && estimate != 0 && round(estimateTotal[12]/budgetStats[catID][12] * 100)/100 > 1) ? "color:red;" : ""));`

Maybe I'm totally wrong, I just want to help in the solution.
by the way, your software is GREAT! I'm just starting to use it and it's quite perfect; I love the possibility to make my own report. great work guys.

**Comment by n-stein** [comment]
> it works adding a estimateTotal[12] = 0; in reports\budgetingperf.cpp at line 296

I agree with your analysis and solution (assuming you meant line 293 and not 296). The `estimateTotal[12]` field holds the value of the cumulative YTD budget for the category in order to detect the point when the sum of the monthly budgets has exceeded the yearly budget. This number should be reset for each new category.

Feel free to submit a PR with the fix.

**Comment by giongy** [comment]
thanks for the analysis. unfortunately i am afraid i am not able to act with github (pull request, commit, push ...) i am too afraid to mess up. I am a mainframe systems engineer and enjoy sometimes programming small things . could you help me in understanding the various steps to “submit a PR with the fix” please?

**Comment by n-stein** [comment]
> could you help me in understanding the various steps to “submit a PR with the fix” please?

@giongy Since you are on Windows, I wrote a short intro to the Visual Studio GitHub integration detailing my workflow which might help. See discussion #6962.

**Comment by giongy** [comment]
Thank you very much @n-stein , your guide to github is definitely very helpful, especially for a beginner like me
