### ISSUE TITLE
Error in "About panel" on 1.8.1

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#6972]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Minor irritation but could cause some confusion.
Upgraded to 1.8.1 and displayed the "About panel"

![Screenshot 2024-11-30 101921](https://github.com/user-attachments/assets/b21ca731-5c59-4987-8c58-97886bdd0601)

Still thinks I have AES128 on my encrypted database rather than AES256.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Click on Help/About

Expected result:
Database version: 19 (aes256cbc)

Actual result:
Database version: 19 (aes128cbc)

**Comment by guanlisheng** [comment]
related #6871
