### ISSUE TITLE
I can not open encrypted database afer upgrade MMEX from v. 1.8.0 to 1.8.1

### ISSUE THREAD

**Issue by Testymoniusz** [moneymanagerex/moneymanagerex#6973]
MMEX version:
 - [ ] 1.7.0
 - [] 1.8.0
 - [x ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
I can not open encrypted database after upgrade MMEX from v. 1.8.0 to 1.8.1 After write down my proper password I've got information about wrong password or chosen file was not been database.
After roll back to MMEX v. 1.8.0 the database has been opened ad once.
# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result: Opening already exist encrypted database should be fixed.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by guanlisheng** [comment]
related #6971

**Comment by guanlisheng** [comment]
closing the issue, please refer and chat in #6971
