### ISSUE TITLE
Unable to open and encrypted file

### ISSUE THREAD

**Issue by sb12857** [moneymanagerex/moneymanagerex#6974]
MMEX version:
 - [ ] 1.7.0
 - [] 1.8.0
 - [x ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Just downloaded and installed v 1.8.1. But could not open an encrypted file as it stated I entered an incorrect password.  Tried several times and ensured I used the correct password. I've reinstalled 1.8.0 and everything is ok.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Several attempts to open the file

Expected result:
File should open

Actual result:
Unable to open file

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by guanlisheng** [comment]
hi @sb12857, can you follow the approach mentioned in the release note to migrate your database from AES128 to AES256.

**Comment by guanlisheng** [comment]
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.8.1

**Comment by sb12857** [comment]
Thank you.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guanlisheng** [comment]
closing the issue, please refer and chat in #6971
