### ISSUE TITLE
password errata su versione 1.8.1, mentre su 1.8.0 funziona

### ISSUE THREAD

**Issue by babyteam1970** [moneymanagerex/moneymanagerex#6979]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by babyteam1970** [comment]
nella versione 1.8.1 la password non lo accetta, dice che è errata. Ho messo la 1.8.0 e l'accetta.

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6971
