### ISSUE TITLE
Create a corrected version 1.8.1 (or 1.8.2)

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#6986]
There were some user unwanted issues to solve in the recently released version 1.8.1. 
I would like to see these fixes incorporated into version 1.8.1 (or a version 1.8.2 released) so that all users can benefit from these fixes.

**Comment by whalley** [comment]
Yes, I think this would be wise.

Currently I think we need to....

1. Create new v1.8.2 branch from tags/v1.8.1
2. Merge into this the following PRs
- https://github.com/moneymanagerex/moneymanagerex/pull/6984 (prompt to auto rekey encrypted db with new cipher algorithm)
- https://github.com/moneymanagerex/moneymanagerex/pull/6982 (save/restore column order by account type)
- https://github.com/moneymanagerex/moneymanagerex/pull/6976 (Update org.moneymanagerex.MMEX.metainfo.xml.in)
3. Change version to v1.8.2

What else needs fixing?

**Comment by guanlisheng** [comment]
the three are great for v1.8.2

**Comment by n-stein** [comment]
Those were definitely the glaring issues with 1.8.1.

@renato-mmex Anything else major you've noticed from the forum?

**Comment by whalley** [comment]
Ideally we should await some translations for this also: https://github.com/moneymanagerex/moneymanagerex/pull/6984/files#diff-44bef8fa93d168379ef331d9e11d333be06ce98a8f37ec65f8a987846b90a151 

@vomikan I think you have permissions to upload the new mmex.po for translation.

**Comment by whalley** [comment]
v1.8.2 Release candidate available:
Windows 64 - https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51110007/job/vutahskpjbuliror/artifacts
Windows 32 - https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51110007/job/988sy0yfpe4pqlsn/artifacts
MacOS - https://onedrive.live.com/?authkey=%21AEWtos0VyDKnlN4&id=A0FB83D788D2D744%21104142&cid=A0FB83D788D2D744

**Comment by whalley** [comment]
@n-stein @guanlisheng @renato-mmex @vomikan Do we think this is good to release? It should be cause less problems that v1.8.1 at least. Language is English only for the Cipher warning however...

**Comment by guanlisheng** [comment]
I'm fine here. So, over 50% of guys have been upgraded to v1.8.1 in the past week.

**Comment by guanlisheng** [comment]
After a second, do you guys think we can have INT64 and SUID included? if not, what's the plan

INT64
- https://github.com/moneymanagerex/moneymanagerex/pull/6965
- https://github.com/moneymanagerex/moneymanagerex/pull/6994
- https://github.com/moneymanagerex/moneymanagerex/pull/7007
- https://github.com/moneymanagerex/moneymanagerex/pull/7010

SUID
- https://github.com/moneymanagerex/moneymanagerex/pull/6964

**Comment by whalley** [comment]
So are you thinking we hold off the v1.8.2 and just go with the v1.9.0 release? Would have thought we would want to wait at least another month to test and iron out any issues found by beta testers.

**Comment by guanlisheng** [comment]
I just wanted to release INT64 earlier as we can see the issue happening like https://github.com/moneymanagerex/moneymanagerex/issues/6992

it would be ideal if we postpone v1.8.2 couple of weeks to include the two key changes, and v1.9.0 would take longer.

thoughts?

**Comment by whalley** [comment]
OK, but think we might as well wait a few weeks and push out v1.9.0 with https://github.com/moneymanagerex/moneymanagerex/issues/6860 included also.

**Comment by guanlisheng** [comment]
i c. a few weeks should be fine. looking forward to v1.9.0

**Comment by whalley** [comment]
Plan is now to release v1.9.0 at end of year.
