### ISSUE TITLE
String missing from Crowdin

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#6990]
MMEX version:
 - [X] 1.8.1

From forum post https://forum.moneymanagerex.org/viewtopic.php?t=11166

The below string is not available on Crowdin:

https://github.com/moneymanagerex/moneymanagerex/blob/ef7f1787ed641afbe82fbd1b63a42d5e00201708/src/mmframe.cpp#L1396

**Comment by n-stein** [comment]
Fixed

**Comment by n-stein** [comment]
Looks like the last refresh of the translatable strings in Crowdin was Nov 28th? Not sure if I'm reading that correctly...

@whalley @vomikan -- Perhaps we could utilize Crowdin's Github action https://github.com/crowdin/github-action to automate the upload of the source strings to Crowdin and download of translated strings from Crowdin on a regular basis? It might help lighten the admin workload a bit, and it would lend an easy answer to the question "when will my new translation be merged" that we see from time to time.

**Comment by whalley** [comment]
> Looks like the last refresh of the translatable strings in Crowdin was Nov 28th? Not sure if I'm reading that correctly...
> 
> @whalley @vomikan -- Perhaps we could utilize Crowdin's Github action https://github.com/crowdin/github-action to automate the upload of the source strings to Crowdin and download of translated strings from Crowdin on a regular basis? It might help lighten the admin workload a bit, and it would lend an easy answer to the question "when will my new translation be merged" that we see from time to time.

This would be ideal. I understand that at present the repo is linked the @vomikan fork and requires manual action. It would be good to automate this.

**Comment by n-stein** [comment]
Three GitHub actions:

1. An "Update PO Template" action. On every pull request merged to master the `po/mmex.pot` file is regenerated. If there are changes, a new PR is opened with the updated `po/mmex.pot`.

2. A "Crowdin Upload" action. Whenever a pull request that contains `po/mmex.pot` is merged to master, it uploads the new `po/mmex.pot` source to Crowdin.

3. A "Crowdin Download" action. When the action is triggered, it downloads the translations from Crowdin to the `po` directory. It is manually triggered for now, but can be automated as desired (maybe a weekly cron job?). 

@whalley can you add me as a manager on Crowdin so I can test the upload/download actions?

**Comment by whalley** [comment]
> @whalley can you add me as a manager on Crowdin so I can test the upload/download actions?

Hopefully done.

**Comment by whalley** [comment]
> 3\. A "Crowdin Download" action. When the action is triggered, it downloads the translations from Crowdin to the `po` directory. It is manually triggered for now, but can be automated as desired (maybe a weekly cron job?).

Yes, a weekly download would be good, but having ability to run it manually helps as we get ready to push out a release and look for latest translations.

Am I correct in understanding that this will generate a PR also, as there are instances where there have been failures and we have had to fix the crowdin translations.

**Comment by n-stein** [comment]
> Am I correct in understanding that this will generate a PR also, as there are instances where there have been failures and we have had to fix the crowdin translations.

Correct. The download action downloads the translations to the `l10n` branch then opens a PR against `master`. If anything fails with the build we can fix it in Crowdin, then manually run the download action to pull it into GitHub.

**Comment by n-stein** [comment]
> Hopefully done.

Perfect, that was exactly what I needed. Found my config was a bit off and corrected.

I opened a PR with the changes. We will need to add a Crowdin API token as `CROWDIN_PERSONAL_TOKEN` to GitHub Action Secrets as well as one for `CROWDIN_PROJECT_ID=342055`. 

![image](https://github.com/user-attachments/assets/6365ec87-f6e7-48b0-833e-6bdeaff11303)

I don't have access to the project settings so I can't set this up myself.

**Comment by n-stein** [comment]
Success. 

I merged the PR. Automatic action run https://github.com/moneymanagerex/moneymanagerex/actions/runs/12322721341 generated #7021.

I merged that PR, then automatic action run https://github.com/moneymanagerex/moneymanagerex/actions/runs/12322765695 pushed the source to Crowdin which added 12 new strings to translate.

![image](https://github.com/user-attachments/assets/f8ae46cc-8e00-4294-8bd2-668b420e1172)

Finally, I manually executed action run https://github.com/moneymanagerex/moneymanagerex/actions/runs/12322821984 which generated #7022 with new translations.

**Comment by n-stein** [comment]
> Yes, a weekly download would be good, but having ability to run it manually helps as we get ready to push out a release and look for latest translations.

I set to automatically download Fridays at 00:00, but also allowed to trigger the workflow manually:

![image](https://github.com/user-attachments/assets/0b57a8a8-3fe3-49af-bf47-b5803f613e1b)

**Comment by n-stein** [comment]
Also, this resolved the initial issue of the missing string.

![image](https://github.com/user-attachments/assets/aaa41770-1b04-430d-b535-fdb33c1dcf0b)
