### ISSUE TITLE
can not save PAYEE_V1

### ISSUE THREAD

**Issue by Markoise** [moneymanagerex/moneymanagerex#6992]
MMEX version:
 - [ ] 1.7.0
 - [x] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When I create a payment and create a new payee, this is first saved and displayed in the payment.
The next time, the payee is no longer entered in the payment posting. The field is suddenly empty.
If I select the payee again from the pull-down menu, the error message “can not save PAYEE_V1” appears.

![grafik](https://github.com/user-attachments/assets/d83561e8-5b15-4b48-8330-9d4d722017db)

I also use Moneymanager for Android in the latest version of F-Droid.
The synchronization of the file works flawlessly.

Incidentally, I can select the payee here and save it again in the payment without an error occurring. The payee is only removed again when I start Moneymanager EX on the PC.

# Reproduction

Is the bug reproducible? 
 - [x] Always
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

When I create a payment and create a new payee, this is first saved and displayed in the payment.
The next time, the payee is no longer entered in the payment posting. The field is suddenly empty.
If I select the payee again from the pull-down menu, the error message “can not save PAYEE_V1” appears.

**Comment by guanlisheng** [comment]
hi @Markoise 

I presume it is related to the fact that the current desktop does support large IDs well and was refined by #6965 
A similar issue was reported in our forum as well: [Payee error](https://forum.moneymanagerex.org/viewtopic.php?t=11218)

can you help verify it with [the latest beta desktop mmex](https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51105199/job/e4es15hekea3qma7/artifacts)? 

we have paused MMEX4Android to generate large IDs since v2024.11.30. it is available in Google Play while F-Droid needs some time.

**Comment by Markoise** [comment]
> hi @Markoise
> 
> I presume it is related to the fact that the current desktop does support large IDs well and was refined by #6965 A similar issue was reported in our forum as well: [Payee error](https://forum.moneymanagerex.org/viewtopic.php?t=11218)
> 
> can you help verify it with [the latest beta desktop mmex](https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51105199/job/e4es15hekea3qma7/artifacts)?
> 
> we have paused MMEX4Android to generate large IDs since v2024.11.30. it is available in Google Play while F-Droid needs some time.

I can't find MMEX4Android on Google Play, so I installed it via F-Droid.

It seems to work better with beta version 1.9.0.
When I create a new payee under Android, I now see “Incorrect payee” in the field on Windows. I can choose the correct one again and it works. 

Thank you

**Comment by guanlisheng** [comment]
https://play.google.com/store/apps/details?id=com.money.manager.ex.android can you see the app in google play now?

**Comment by Markoise** [comment]
> https://play.google.com/store/apps/details?id=com.money.manager.ex.android can you see the app in google play now?

Yes, thank you very much. That's how it works now.

**Comment by NeoXTof** [comment]
I hadd the issue with also trying to play with the android app and 1.8.1. I created a payee in the app, and it was the root cause of the bug: The ID in the DB for the PAYEE created in the APP was the MAX value of the ID and it was crashing the desktop app 1.8.1. 

The workaround I found was to edit the DB and delete the PAYEE created in the app.

**Comment by guanlisheng** [comment]
thanks @NeoXTof 

Another simple workaround is to delete the payee in the app (v2024.11.30).

**Comment by Tracachang** [comment]
> hi @Markoise
> 
> I presume it is related to the fact that the current desktop does support large IDs well and was refined by #6965 A similar issue was reported in our forum as well: [Payee error](https://forum.moneymanagerex.org/viewtopic.php?t=11218)
> 
> can you help verify it with [the latest beta desktop mmex](https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51105199/job/e4es15hekea3qma7/artifacts)?
> 
> we have paused MMEX4Android to generate large IDs since v2024.11.30. it is available in Google Play while F-Droid needs some time.

I had the same issue (flatpak linux version) and I have tested the latest beta and I confirm it is fixed. However, I do not know if this is related but with the desktop app I am unable to delete a payee while with the android version it works.

Thank you

**Comment by BoubouleThai** [comment]
I confirm that the problem is solved with 1.9.0 beta. Good!
