### ISSUE TITLE
Unable to edit a"payee created with android"

### ISSUE THREAD

**Issue by Tracachang** [moneymanagerex/moneymanagerex#7003]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [x] 1.9.0
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug
With the last android app version 2024.11.30 (1050). I create a new payee called "test" and sync the db with syncthing to my desktop pc.

On desktop version I go to "Payee manager", double click to the newly created payee.

![image](https://github.com/user-attachments/assets/4c3d3b68-2792-424b-a081-1fb0ab75a00d)
![image](https://github.com/user-attachments/assets/f31193a3-e30c-48a7-80ff-46338599db2e)

All the other payees have the name appear and can be edited, but in this case it is blank. When I type test, the message pops up:"A payee with this name already exists".

If I enter a different name, such as "tests":

![image](https://github.com/user-attachments/assets/b3e6b463-9f06-4bed-ba17-2a6648374f5b)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by Tracachang** [comment]
I ended up restoring an older backup and updating all the data. So I have no more problems. Since I do daily backups, I can always restore a "broken" backup and test it if needed. 

All of these problems occurred on desktop (flatpak) and Android (f-droid version 2024.11.25). 1.9.0 beta and the latest apk helped by showing all the payees, but did not really fix the problems.

**Comment by guanlisheng** [comment]
similar to #6992
