### ISSUE TITLE
MMEX 1.8.1 quit while digit a search with letter " q "

### ISSUE THREAD

**Issue by GuidoC57** [moneymanagerex/moneymanagerex#7005]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] 1.9.0
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

MMEX 1.8.1 crash while digit a search with letter " q "

# Reproduction

- select for example a current account;
- in the research field when you digit the letter  " q ";   the MMEX program  quit.
- Note: the letter  " q "  can be digit alone or in a word or also using an asterisk as wildcard
- Note: the Database is on external SSD;

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/6949        ?????

**Comment by GuidoC57** [comment]
You are right.
I'm sorry. I didn't find the poblem sooner


________________________________
Da: Renato ***@***.***>
Inviato: sabato 7 dicembre 2024 14:46
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: GuidoC57 ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] MMEX 1.8.1 quit while digit a search with letter " q " (Issue #7005)


#6949<https://github.com/moneymanagerex/moneymanagerex/issues/6949> ?????
