### ISSUE TITLE
Slow loading and response of program

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#7015]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] 1.9.0
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
The program opens quickly but every entry or clicking on account isvery slow. This especially bad with a new transction or amendment to a transaction.
Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
You already reported this 3 days ago and received an answer, but did not take a stand.
See:  https://github.com/moneymanagerex/moneymanagerex/issues/7011
