### ISSUE TITLE
Transaction Report - Account handling broken

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#7018]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [x] 1.9.0
 - [ ] Other (please specify)

Was working in v1.8.1, not sure if it is related to ID (int64) changes as not had chance to invesigate yet. When selecting a subset of accounts for the report in some cases ALL accounts seem to be selected or in other reports selected accounts are being omitted.

**Comment by n-stein** [comment]
Looks like cc9bd22bb903a45c295e867abde85240b143a248 accidentally switched a `==` to a `!=`

**Comment by whalley** [comment]
Good spot, I'll test that later. Thanks for saving me looking at this. 👍

**Comment by whalley** [comment]
Fixed.

**Comment by whalley** [comment]
...another change that accidentally switched a `==` to a `!=`
