### ISSUE TITLE
Can't download mmb database

### ISSUE THREAD

**Issue by gmerckx** [moneymanagerex/moneymanagerex#7024]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1
 - [ ] 1.8.2
 - [ ] 1.9.0
 - [ X] Other (please specify) (not sure what version I have. Last used 10/2023 when computer crashed. 

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug - Had to have the database recovered in a clean room from my computer when it crashed. Trying to download the recovered version and getting this error: "MMEX database upgrade to version 15 failed! Please restore DB from autocreated pre-upgrade backup and retry or contact MMEX support . SQL logic error (1): no such table: REPORT_V1"
<img width="432" alt="Screenshot MMEX error" src="https://github.com/user-attachments/assets/e345adaa-5f44-44f7-af9c-75c310a2d411" />

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result: would like my history included from this database

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment]
The fix is outlined here: https://github.com/moneymanagerex/moneymanagerex/issues/5662#issuecomment-1428618635
