### ISSUE TITLE
Release 1.8.1

### ISSUE THREAD

**Issue by beppeolivero** [moneymanagerex/moneymanagerex#7041]
### Discussed in https://github.com/moneymanagerex/moneymanagerex/discussions/6866

<div type='discussions-op-text'>

<sup>Originally posted by **whalley** September 11, 2024</sup>
@guanlisheng  @n-stein @vomikan Have pushed all open issues planned for 1.8.1 out to 1.9.0 as nothing looked too major. 

Will issue an RC build for final testing. We can look to release by end of the month.  Suggest **not** merging any non-essential changes until 1.8.1 is released.</div>

**Comment by whalley** [comment]
Not sure what the issue is here. v1.8.1 has been released. Plan to issue v1.9.0RC in next week or so.
