### ISSUE TITLE
incorrect language display 1.9.0 Beta

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#7070]
Version 1.8.1 displays German correctly, but since 1.9.0 Beta many German texts in the menus are in English with additional special characters.
The English version also has these special characters.

![image](https://github.com/user-attachments/assets/95d45d78-5076-43ad-9cf5-76fc7c41ea46)  

![image](https://github.com/user-attachments/assets/f7262432-dfcc-4764-8f28-c82fd1d98ee1)

**Comment by whalley** [comment]
@n-stein https://github.com/moneymanagerex/moneymanagerex/pull/7057

**Comment by renato-mmex** [comment]
With the version:

Money Manager Ex
• Version: 1.9.0-Beta.1 64-bit
• Erstellt am: Dez 31 2024 11:55:32
• Datenbankversion: 19 (aes256cbc-hmac-sha512)
• Git-Eintrag: 607148b (2024-12-31)

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51246161/job/34y65y7vnypu4jxk/artifacts

it is displayed correctly again.  Thank you
