### ISSUE TITLE
SPLITTRANSACTIONS: add ACCOUNTID and NOTES columns

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#709]
existing SPLITTRANSACTIONS_V1 has some performance issues to fetch all split transactions under a given account

> CREATE TABLE SPLITTRANSACTIONS_V1(
> SPLITTRANSID integer primary key 
> , TRANSID integer NOT NULL
> , CATEGID integer
> , SUBCATEGID integer
> , SPLITTRANSAMOUNT numeric
> );

The basic goal is to add account id for v2.

**Comment by gabriele-v** [comment]
Why not simple add new column ACCOUNTID? In that way we won't make any problem to existing reports..

It could be the opportunity to start add in desktop version SQL Updates as suggested by @MisterY 

With a .sql file (that we could simply run in Android version too) we will brillant solve the problem:
`ALTER TABLE SPLITTRANSACTIONS_V1 ADD COLUMN ACCOUNTID;`
`CREATE INDEX IDX_SPLITTRANSACTIONS_V1_ACCOUNTID ON SPLITTRANSACTIONS_V1(ACCOUNTID);`
`UPDATE SPLITTRANSACTIONS_V1 SET ACCOUNTID = (SELECT ACCOUNTID FROM CHECKINGACCOUNT_V1 WHERE CHECKINGACCOUNT_V1.TRANSID = SPLITTRANSACTIONS_V1.TRANSID);`

**Comment by MisterY** [comment]
Agree. And we could add Notes field at the same time.

**Comment by gabriele-v** [comment]
@guanlisheng if agree I can take care of add upgrade support to MMEX Desktop, I've already done it for WebApp so I can easily reproduce it..

**Comment by guanlisheng** [comment]
@gabriele-v there are two reasons to keep an explicit v2 table to replace v1 and thanks for the taking.
* Easy to track the versioning for a given table
* ALTER TABLE has some limitation here which would only appends new columns to the end of the list of existing columns

@MisterY agreed to add notes as well.


Some notes here. this is a try on how to do the table/data migration for future schema changes since i have observed more and more requests to modify existing schemas.

@moneymanagerex/desktop-mmex-team @moneymanagerex/android-mmex-team as fyi.

**Comment by gabriele-v** [comment]
Personally I don't think that add columns to to the end it's a problem. Maybe stylish won't be optimal, but it's a DB so if you want column with specific order you can choose it during select. 
Anyway it's still possible to add a column in the middle, simply create a temp table, populate with data, drop the original, recreate, reinsert and then drop temp table.

Regarding versioning, change a table name will cause more problems than benefits obtained from versioning IMHO..

**Comment by vomikan** [comment]
Related issue: https://github.com/moneymanagerex/moneymanagerex/issues/488

**Comment by guanlisheng** [comment]
schema for v2
> CREATE TABLE SPLITTRANSACTIONS_V2(
> SPLITTRANSID integer primary key 
> , ACCOUNTID integer NOT NULL
> , TRANSID integer NOT NULL
> , CATEGID integer
> , SUBCATEGID integer
> , SPLITTRANSAMOUNT numeric
> , NOTES TEXT
> );

**Comment by guanlisheng** [comment]
@gabriele-v example on how to upgrade the schema from v1 to v2
https://github.com/moneymanagerex/moneymanagerex/compare/master...guanlisheng:master

**Comment by gabriele-v** [comment]
@moneymanagerex/desktop-mmex-team see pull #715 

@guanlisheng it will be really nice if you could create a script sqliteupgrade2cpp.py similar to sqlite2cpp.py in order to automatically generate dbupgrade_query.h searching for existing files like database_version_4.sql, database_version_5.sql etc. in database folder.
I'm not a Python expert but should be quite simple considering work that you have made for sqlite2cpp.py

**Comment by MisterY** [comment]
Great work, @gabriele-v. :+1: Thanks!

**Comment by gabriele-v** [comment]
@moneymanagerex/desktop-mmex-team @moneymanagerex/android-mmex-team
Do you think that we need to upgrade BUDGETSPLITTRANSACTIONS_V1 as well?

**Comment by MisterY** [comment]
I believe so. They are copied 1-to-1 into the split categories of the actual transaction, right?

**Comment by gabriele-v** [comment]
BUDGETSPLITTRANSACTIONS_V1 updated.

@stef145g could you update code to correctly manage new split fields in recurring transaction? I don't know that code well.. Thanks

**Comment by stef145g** [comment]
Changed Milestone to V2.0
Other proposed changes may impact in the implementation of this namely Split Transfers #461

**Comment by slodki** [comment]
@moneymanagerex/desktop-mmex-team Do we have any plans to use SPLITTRANSACTIONS_V2 in place of SPLITTRANSACTIONS_V1?

**Comment by vomikan** [comment]
Seems we are following a way to upgrade (alter) tables.
If DB upgrade script would be provided then we increase the app performance.

**Comment by gabriele-v** [comment]
I agree that DB upgrade procedure works quite well, we still need to decide if we want to keep the vXX suffix or not. Up to me, we could remove all of them because versioning it's handled with pragma. Also, removing all suffixes, we need to update MMEX code just one time, and also patch on GRM table (search for _V1 replace with empty) have to be done once.

**Comment by vomikan** [comment]
#910

**Comment by vomikan** [comment]
CLOSE: fixed

REASON: Notes have now been added to Split Transactions.
