### ISSUE TITLE
wxNewId()

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#710]
I spied it here:
https://sourceforge.net/p/lenmus/code/HEAD/tree/trunk/src/app/lenmus_welcome_window.cpp#l42

~~~~~
namespace lenmus
{

//IDs for controls
const int lmLINK_NewInLenmus = wxNewId();
const int lmLINK_NewScore = wxNewId();
const int lmLINK_QuickGuide = wxNewId();
const int lmLINK_OpenEBooks = wxNewId();
const int lmLINK_Instructions = wxNewId();
const int lmLINK_Recent1 = wxNewId();
~~~~~
Should we use subj.?

**Comment by gabriele-v** [comment]
wxNewId() is deprecated and suggested use of wxID_ANY:
http://docs.wxwidgets.org/trunk/group__group__funcmacro__misc.html#gaa2d93c1680369b4227f7de9de58e5fcb
