### ISSUE TITLE
qif import not respecting selected date format

### ISSUE THREAD

**Issue by bob3000** [moneymanagerex/moneymanagerex#721]
mmex version: 1.2.5
os version: Max OSX 10.11.3

I tried to import some qif files with the date format like `DD/MM/YYYY`. Even though I selected the correct format mmex would in some cases (I couldn't figure out on what it depends) interpret the format as `YY/MM/DD`.
It even showed up correctly in the preview window but finally when I close the import window in my account I'll have entries e.g. from 1931-12-14 for a payment form 2014-12-31.

make sure these boxed are checked before submitting your issue - thank you!
- [x] check your os version (windows, linux, osx)
- [x] check your mmex version

**Comment by vomikan** [comment]
It looks like already fixed symptom. Try to select date format before import even if already ok.

**Comment by vomikan** [comment]
Could you provide sample QIF file to reproduce this issue.

**Comment by vomikan** [comment]
I can't reproduce this issue with mmex 1.3.0
~~~~~~
!type:Bank
D2014-12-31
T-299.91
MCHEQUE                  N° 4702696
^
~~~~~

**Comment by bob3000** [comment]
I need to correct my bug report. The import itself works. What happens is the following. I set the date to the correct format `DD/MM/YYYY`, then I open the file and when the open-file-dialog closes the date format jumps to `YY/MM/DD`. I didn't noticed that in the first place
So the bug is actually not that problematic but is's still very confusing. My apologies for the wrong former description of the problem.

**Comment by vomikan** [comment]
OK 
It wokrs the next way.
When file opening all 'Date' tags analized. If date parsed successfully with some date mask - this mask is valid, if not parsed - the mask is invalid.
I recommend to choose date mask after file opening.
