### ISSUE TITLE
Views to wrap physical tables

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#723]
Now we have following tables and as @vomikan mentioned, better to create a fix view name to point the table. for instance view **ACCOUNTLIST** to **ACCOUNTLIST_V1**

CREATE TABLE ACCOUNTLIST_V1
CREATE TABLE ASSETS_V1
CREATE TABLE BILLSDEPOSITS_V1
CREATE TABLE BUDGETSPLITTRANSACTIONS_V1
CREATE TABLE BUDGETTABLE_V1
CREATE TABLE BUDGETYEAR_V1
CREATE TABLE CATEGORY_V1
CREATE TABLE CHECKINGACCOUNT_V1
CREATE TABLE CURRENCYHISTORY_V1
CREATE TABLE CURRENCYFORMATS_V1
CREATE TABLE INFOTABLE_V1
CREATE TABLE PAYEE_V1
CREATE TABLE SPLITTRANSACTIONS_V1
CREATE TABLE STOCK_V1
CREATE TABLE STOCKHISTORY_V1
CREATE TABLE SUBCATEGORY_V1
CREATE TABLE ATTACHMENT_V1 
CREATE TABLE USAGE_V1 
CREATE TABLE ASSETCLASS_V1 
CREATE TABLE ASSETCLASS_STOCK_V1 
CREATE TABLE CUSTOMFIELD_V1 
CREATE TABLE CUSTOMFIELDDATA_V1

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team any volunteer to follow this?

**Comment by guanlisheng** [comment]
[Create View in SQLite](https://www.sqlite.org/lang_createview.html)

**Comment by gabriele-v** [comment]
I think it will be better to directly rename tables instead of create views.. 

Also, both creating views and rename table, could be done only after 2.0.0 using new upgrade process

**Comment by slodki** [comment]
See #709

**Comment by slodki** [comment]
Different solution in #1636
