### ISSUE TITLE
"Cancel" button in new DB wizard doesn't work

### ISSUE THREAD

**Issue by gitys** [moneymanagerex/moneymanagerex#736]
make sure these boxed are checked before submitting your issue - thank you!
- [x] windows, debug 32
- [x] 1.3.0-alpha side branch

This is a debug build on my side branch with no significant changes. 

There seems to be no way out of the wizard besides the finish button because the X button doesn't work and neither does the cancel button.

**Comment by vomikan** [comment]
I think it happens after this changes
https://github.com/moneymanagerex/moneymanagerex/commit/1a3b8009c0a6f1d8232905c16d4f499522ca3287

**Comment by siena123** [comment]
It has nothing to do with those changes. 

The problem is that we are specifically telling it to ignore the cancel event in line 94 of the wizard_newdb.cpp file. Was this done to insure that the base currency got set? 

void mmNewDatabaseWizard::OnWizardCancel(wxWizardEvent& event) 
{ 
event.Veto(); 
} 

- James

**Comment by slodki** [comment]
Does it still exist in 1.4.0?

**Comment by slodki** [comment]
New database wizard cannot be canceled after selecting filename in current master.

1. File->New Database or Ctrl-N or Create New Database from startup dialog
2. While in filename selection dialog there is Cancel button **working**
3. After filename selection the New database wizard pop-up is opened with Cancel button and close window icon **not working**. The Next button is the only one working here...
4. Next window - with base currency and user name selection - has
  a) Back button **not working** - raising "base currency not set" error (why?!)
  b) Cancel button **not working**
  c) close window icon **not working**
