### ISSUE TITLE
It takes "New DB wizard" 35 seconds to open

### ISSUE THREAD

**Issue by gitys** [moneymanagerex/moneymanagerex#737]
After selecting the file name for the new DB, I took 35 seconds for the wizard window to open.
This time can probably be shortened.
If not, there should be a "Please wait..." message open, with a progress bar if possible.

- [x] windows
- [x] 1.3.0-alpha

**Comment by vomikan** [comment]
Only 5 sec in debug mod for me

**Comment by vomikan** [comment]
http://docs.wxwidgets.org/3.1.0/classwx_activity_indicator.html

**Comment by vomikan** [comment]
~~~~~
void db_table_unicode_data::ensure_data(wxSQLite3Database* db)
{
    db->Begin();
    db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS_V1 VALUES (1, '%s', '%s', '%s', '%s', '%s', '%s', '%s', 100, 1, '%s')", wxTRANSLATE("United States dollar"), wxTRANSLATE("$"), wxTRANSLATE(""), wxTRANSLATE("."), wxTRANSLATE(" "), wxTRANSLATE(""), wxTRANSLATE(""), wxTRANSLATE("USD")));
.....
 db->Commit ();
    ~~~~~
 It should help
