### ISSUE TITLE
Transactions are empty on 29.02.2016 (Leap Year Bug)

### ISSUE THREAD

**Issue by enasalitis** [moneymanagerex/moneymanagerex#741]
BUG seems to affect all mmex versions in Windows

You can find a detailed desciption of the problem to the following Support Forum Threads:
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6394
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6398
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6392
http://forum.moneymanagerex.org/viewtopic.php?f=23&t=6399

Copying from the first forum:
"Mon Feb 29, 2016 12:45 am
As on this morning, when I opened MMEX, I do not see any of my transactions. However, the Account Balance, Reconciled Balance and Diff were showing some values. 

So I clicked on Transaction filter and checked the Account name and selected the account I was looking for. All the transactions are now visible. 
I have not updated MMEX. Version 1.1.1 is my version that I am using. 

Closed and opened MMEX to see if that helped and still same issue. 

What seems to be the problem? Please help. "

Thank you

**Comment by vomikan** [comment]
Leap Year Bug

If you used MMEX today (Feb 29 - leap year) you've probably noticed all your transactions are not displaying properly. All the data in the database is safe, it is only an issue with displaying items on the screen. Everything will return to normal tomorrow. You can also reset the date on your computer to yesterday and everything should reappear. Sorry for the inconvenience and thanks for using MMEX!

**Comment by mj1856** [comment]
According to [issue 837 on SourceForge](https://sourceforge.net/p/moneymanagerex/bugs/837/) there are still issues.

(Why two bug trackers anyway?  :confused: )

**Comment by vomikan** [comment]
![screenshot 37](https://cloud.githubusercontent.com/assets/6836805/13555119/f8bbe77a-e3c8-11e5-9b5b-f68290e2b91b.jpg)
I can't reproduce this issue
