### ISSUE TITLE
"Budget Performance Summary" - Enhancement Needed

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#742]
Hello MMEX Team,

Regarding this Feature, it is a very good idea for summarizing the whole year's comparison (Actual Vs Estimated) for the year . But I realize that, the way this report is presented is not user friendly to read the report / values. 

Please have a look onto my attached proposal for enhancing this feature, which could make the report to be more easily readable.

I believe that, my proposal shall be taken into consideration for upcoming update of this software. 

With Thanks & Appreciations.

http://forum.moneymanagerex.org/viewtopic.php?f=8&t=6404

![bdgt_perfm_rpt](https://cloud.githubusercontent.com/assets/6836805/13460054/2280e74c-e089-11e5-9852-85bf2c826fbe.jpg)

**Comment by guanlisheng** [comment]
@stef145g what's your opinion ?

**Comment by stef145g** [comment]
Looks good, and should be achievable.

**Comment by vomikan** [comment]
It should be c++ JSON html template IS solution.

**Comment by stef145g** [comment]
I agree

**Comment by siena123** [comment]
I also agree that the proposal looks better. I think the view selection could be implemented similar to the way date range is done on the reports panel and could also be provided to the other budget report as well.
