### ISSUE TITLE
Rethink import/export settings templates

### ISSUE THREAD

**Issue by gitys** [moneymanagerex/moneymanagerex#745]
There are several points here I was thinking can be improved and in this issue I'd like to share them with the team and start a discussion about them.

**Primary improvements** 
1. Templates should have a name. It will make it easier to find, rather than hopping through numbers 1-9.
2. It is not possible to modify an existing template and save it in a different slot. You need to go to the new slot and change the settings there.

**Additional improvements**
1. File name should not be part of template. I see the template as a format that can import each time from a different file. It should be possible to "save as".
2. When importing, it is likely that for a given account the same template will mostly be used. For example for a credit card account, the template for that particular credit card will be used. There are two features that come to mind here:
1) Have an import option when right clicking on an account and have the name of the last template used for this account appear it the popup menu.
2) It is possible to skip the step of selecting the file format (SCV, XML, QIF). Choosing a template can imply the format to use.

Please let me know if you have any comments about the above or if you have any other ideas related to the above.
Thanks.

**Comment by CloudAloud** [comment]
I like the idea of export/import by right clicking on account. 
I regularly import data from one MMEX database to another. Are there any way to do it without import/export directly from source to destination database? It might be very useful from my point of view.

**Comment by gitys** [comment]
Hi @CloudAloud 
There is a "duplicate transaction" feature but it only works for a single transaction. It sounds like you are interested in a batch duplication, possibly using multi selection.
Since this issue specifically discusses templates, I recommend you open a separate feature request for batch duplicate.

**Comment by gitys** [comment]
I've finally been able to make some progress on this. I will give a preview in order to get comments from the team.
The main change is that the 0-9 radio button selection is replaced with a new custom control. The control (squared below in red) contains the list of templates on the left and action buttons to the right. Templates are now identified by name not number (internally the number is still used).

![new template control- marked](https://cloud.githubusercontent.com/assets/14854328/14770520/79927b64-0a7c-11e6-9c30-44f4111db738.png)

The drop down list allows to select the current template. The list is still limited to 10 templates.
![template list](https://cloud.githubusercontent.com/assets/14854328/14770567/55ed7230-0a7d-11e6-861b-8c35d6105fcc.png)
 
The actions begin with the "Save" button that was already supported. 
Next is the Copy button that copies setting from the current template to another template. Pressing the button opens the following selection dialog. 
![2016-04-25 3](https://cloud.githubusercontent.com/assets/14854328/14770591/dc7ce1dc-0a7d-11e6-9e10-14183b4b21f2.png)
 
The third button is Rename. This renames the currently selected template. Pressing the button opens the following rename dialog:
![rename](https://cloud.githubusercontent.com/assets/14854328/14770624/4188d43c-0a7e-11e6-9a8e-30f1e030ef2c.png)

The last action is delete. This will delete all store settings of the currently selected template. All settings are returned to default.

The implementation of the template control is completely unrelated to the import dialog, therefor it easily be used in other places in the program. Currently I am changing only CSV import/export.

Please comment. If the concept is more or less okay I should be able to have this ready shortly.

**Comment by vomikan** [comment]
Actually users are using 1-3 templates. I suggest to move all this staff

[image: Встроенное изображение 1]
to separate dialog.

And leave only pull down menu with non empty templates and [Edit
(templates)] button.

Regards,
Nikolay

2016-04-25 0:49 GMT+03:00 yshatsky <notifications@github.com>:

**Comment by gitys** [comment]
Hi @vomikan 
So I think there are two points here
1) Display only used templates in drop down.
2) Move command s to another dialog.  

I think the first point should be quite simple, I would need to add a "New template" button and have the code use an internally stored ID instead of the index of the selected item. 
The second point I am not very clear about. I can see something along the line of a "template management" dialog but even then I think that the "Save" button, for example, should remain outside since it pertains to the fields on the original dialog. It also seems it might be a over kill for just a few button and will lead to over complication. **Do you think it would be reasonable to start with a first PR that does not contain the sub-dialog, see how it is, and then decide where to take it from there?** 

I am also very curious how users get away with 1-3 templates. I would have guessed 3-5. Is this not the primary methods of importing data from bank accounts and credit cards?

BTW, it looks like you posted an image but only the markup is displayed for me, not the image.
Thanks,

**Comment by vomikan** [comment]
I mead this frame should be moved out the dialog to child one
![screenshot 59](https://cloud.githubusercontent.com/assets/6836805/14883954/57772464-0d4a-11e6-9a41-c8b3d0807e45.jpg)

**Comment by vomikan** [comment]
Related case is: https://github.com/moneymanagerex/moneymanagerex/issues/1002

**Comment by erflungued** [comment]
Would the help info for MoneyManagerEX document that CSV's need to have the oldest transaction on the first line please.
My bank exports data with the newest transaction first and it took me quite some time to work out why my transaction balances were not correct.

**Comment by sarjanwebdev** [comment]
Can we allow to right click and account, choose export/import, and select the account on dialog by default?

**Comment by sarjanwebdev** [comment]
> Would the help info for MoneyManagerEX document that CSV's need to have the oldest transaction on the first line please.
> My bank exports data with the newest transaction first and it took me quite some time to work out why my transaction balances were not correct.

I include (concatenate) my bank's balance at the end of description before importing
When in MMEX, if MMEX balance matches ANY of the lines of the same day, that day is reconciled. I mark it green with Ctrl+4.
