### ISSUE TITLE
Deprecate class mmOptions & mmIniOptions

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#750]
As part of code cleanup & system simplification, i believe this class would be deprecated and removed in near future and we can retrieve the data directly from database.

**Comment by gabriele-v** [comment]
They are also used to improve performance storing in memory some common and widely used variables. We could have some performance issues fetching them every time from db

**Comment by guanlisheng** [comment]
I don't see any performance here and it should be handled in model level.

**Comment by stef145g** [comment]
I would have thought that the preferred method would be to keep the class/objects for options and even combining the two classes into one class.

This means that the only call we make is to the class method and the class/object does the rest. This way the class can determine if the option requires memory buffering for performance purposes or not, and if the data needs to be stored in the database or not. It also serves the purpose of keeping the options and associated data in one central location.

**Comment by guanlisheng** [comment]
more details please and i don't quite understand your point here.

**Comment by stef145g** [comment]
I will create an example and post it in a branch

**Comment by stef145g** [comment]
New branch posted:[class_mmoptions_update](https://github.com/stef145g/moneymanagerex/tree/class_mmoptions_update)

**Comment by vomikan** [comment]
@guanlisheng please look at this

**Comment by guanlisheng** [comment]
is there a pull request to see the code difference?

**Comment by guanlisheng** [comment]
i had a quick glance via https://github.com/moneymanagerex/moneymanagerex/compare/master...stef145g:class_mmoptions_update?expand=1

i am wondering why we still need this wrapper for model_infotable and model_setting?

**Comment by stef145g** [comment]
@guanlisheng The pull request is #775 

1. The wrapper simplifies calls to the appropriate table ("Model") unless the same calls are provided in the Model_xx class
2. It keeps all options together and ensures these are buffered. Improves performance
3. Improves code readability.

The class mmIniOptions should be merged into mmOptions class as these are options regardless of where they reside. The option class will determine where these actually reside.
This merge has not been implemented yet as only the first stage is done.

Final stage is to rename the mmOptions class to Option and the file name renamed to options.

What is your view?

**Comment by stef145g** [comment]
Continue with pull request #783
