### ISSUE TITLE
db files structure

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#755]
@guanlisheng 
Could you refactor (split)
DB_Table_Currencyformats_V1.h to h and cpp files
DB_Table_Currencyformats_V1.cpp (may be rename it to db_table_currencyformats_v1.cpp)

```
void DB_Table_CURRENCYFORMATS_V1::ensure_data(wxSQLite3Database* db)
{
     .... 
}

```

DB_Table_Currencyformats_V1.h

```
void ensure_data(wxSQLite3Database* db);
```

**Comment by guanlisheng** [comment]
i wanted to understand why we need this change ?

**Comment by vomikan** [comment]
If any changes has done in header file it takes a lot of time to compile a project.
No any other reasons.
You can close the issue if the alteration takes a lot of time.

**Comment by stef145g** [comment]
I totally agree with @vomikan 

@guanlisheng  to answer your question:
> i wanted to understand why we need this change ?

1. When a .cpp file is compiled, all .h files referenced are also compiled. This means that if a .h file is referenced by 20 files, the same .h file is compiled 20 times. The bigger it is, the longer it takes.

2. When the code is contained in a .cpp file, the .h file is still referenced but the actual code is only compiled once. This reduces the actual overall compile time.

3. All .h files should be used as an interface to the actual code. Any change to the actual code, become localised, and keeps the code "private".

4. In MSVC at least, I can compile a single .cpp file to check for syntax and code errors. I cannot do this when the code is placed in a .h file.

I believe that the general rule is: **Keep .h files small and place all code in .cpp files**.

**Comment by guanlisheng** [comment]
i think it's not the time yet.

**Comment by guanlisheng** [comment]
will close it soon if there is no objection ...

**Comment by slodki** [comment]
http://www.hwaci.com/sw/mkhdr/makeheaders.html
