### ISSUE TITLE
Convert comma to decimal point while inserting value

### ISSUE THREAD

**Issue by dmgawel** [moneymanagerex/moneymanagerex#756]
Many European countries use the comma (,) as a decimal point. In case such a keyboard layout is used also decimal point on numpad is treated as comma. It makes inserting values into MMEX uncomfortable (it ignores commas). Maybe it would be a good idea to automatically change commas to decimal points while inserting values?

**Comment by vomikan** [comment]
It's already there.

**Comment by dmgawel** [comment]
Unfortunately it's not working.

My setup:
* MMEX v1.2.6
* Windows 8.1 (64bit)
* Keyboard layout: polish (programmers)

**Comment by dmgawel** [comment]
I've achived it by changing decimal point in PLN to ",". Works fine. Maybe should be default for PLN?
