### ISSUE TITLE
Add Tags on transactions

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#770]
Ref: https://github.com/moneymanagerex/android-money-manager-ex/issues/735

For a start, we can add a Tags table with Id, TxId, and Name.
Users should be able to utilize tags in custom reports for now.

**Comment by vomikan** [comment]
Gabriele already has done somthing like this:
https://github.com/moneymanagerex/moneymanagerex/commit/392000f4d1a8adf3317e3e7f83ed21c99b3e509b

**Comment by MisterY** [comment]
Ah, great! That seems to be about the same concept. That way we can say we have even better feature than Projects. 
When is this expected to be released? I don't see the table in my databases at the moment.

**Comment by gabriele-v** [comment]
You are right, I haven't added tables in DB Upgrade..
On desktop it works because all tables are created if not exist.  I'll add them in v5 and 1.3.0

**Comment by slodki** [comment]
#1474
