### ISSUE TITLE
Help files in different languages differ from the original

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#776]
Help files in different languages differ from the original.
I suggest to have one file and translate it to oter languages by JS.

Prototype:
https://github.com/vomikan/mmex_help

**Comment by vomikan** [comment]
http://desktop.moneymanagerex.org/
https://github.com/moneymanagerex/moneymanagerex/tree/gh-pages

**Comment by slodki** [comment]
The bug still exist...

**Comment by vomikan** [comment]
I've made [partial] translation from English to Russian using js
Other languages present by outdated files.
To complete this job there are more human resources needed.

**Comment by slodki** [comment]
I see no benefits from storing all translated strings (for all languages) into separate .js file.
It's hard to validate it completness or match correlated strings. Translator has no context for .js items.

This approach is similar to store all translation in one .html file and hide them with jquery based on lang attribute. In this approach the layout and context could be preserved.

But this still has no benefits over separate .html files per language. This approach allows to display files side-by-side and compare or quickly identify differences.

I tried to update polish translation your way but it didn't make sense for me.
I think your work could be preserved by rendering help page in werbbrowser and catching rendered DOM model as html from browser... to convert it to plain html again.

**Comment by vomikan** [comment]
![screenshot_20190113-115413](https://user-images.githubusercontent.com/6836805/51083369-48441f00-172a-11e9-9828-4034b3a142a6.png)
With crowdin we can translate original html file. I think it's best solution.
https://crowdin.com/project/moneymanagerex/pl#
