### ISSUE TITLE
Base Currency change

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#793]
It appears that could be a bug when changing base currency.
Reproduce as follows:
1. Options – Base currency
2. Select currency line
3. Press Add Button
4. Close currency dialog
..... result: system crash
~~~~~
<frame level="1" function="mmCurrencyDialog::OnTextChanged" offset="000000bb" file="c:\users\stef\documents\tortoisegit\moneymanagerex.master\src\currencydialog.cpp" line="241">
~~~~~
This occurs in Master branch only.

**Comment by stef145g** [comment]
Problem found. I will fix this later.

**Comment by stef145g** [comment]
Pull request #796 created.

**Comment by vomikan** [comment]
[This](https://github.com/vomikan/moneymanagerex/commit/9e466c9deb087375dfad0590dd9c37ce77d076c4) changes did not fix the problem.

How to reproduce a crash:
1. Options – Base currency
2. Select currency line
3. Press Add Button
4. Cancel
5. Enter the currency name: "test"
6. OK

**Comment by stef145g** [comment]
You are correct. Previous fix delayed this crash, but fixed other issues as well.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/8ac7cecb03e30b84d517a8542fc095edcf7d3aa0
