### ISSUE TITLE
Bitcoin - Decimal places & Transfers Fiat > Bitcoin

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#798]
1) Currencies are at present only calculated up to the 6th decimal. Bitcoin works with **8** decimals. The rounding of the last two decimals is not a major problem but will lead to inaccurate balances.

2) When making a transfer from a fiat account to a bitcoin account the bitcoin amount is rounded to the 2nd decimal instead of all the way to the 8th. I made a transfer from my bank account to a bitcoin account today and the amount of bitcoin should have been 0.31058987 but only showed as 0.31. That's a difference of $0.26, not major but with larger transactions balances will be completely skewed.

Tried adjusting the bitcoin balance in the transaction (in the second amount window) by entering the full 8 decimal value but it again gets rounded back down to 2 decimal places.

**[EDIT]** Just checked, when transferring from a Bitcoin account to fiat account one is allowed more decimal places but again only 6 places and not 8.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

**Comment by stef145g** [comment]
@RustyNomad Please check if this has been fixed with issue #839

**Comment by RustyNomad** [comment]
@stef145g Yes this has been resolved.
