### ISSUE TITLE
Bugs with file attachments on recurring transactions that do not repeat

### ISSUE THREAD

**Issue by tiker** [moneymanagerex/moneymanagerex#806]
I may not be using the recurring transactions as expected but I found an issue that probably shouldn't be an issue.  When creating an entry under recurring transactions that does not repeat with an attachment, that attachment carries over to the next recurring transaction entry.

Here's how to recreate the problem I'm trying to explain:
* Create a new .mmb database, account, currency, etc. doesn't matter.
* Setup the option to specify the directory for file attachments from the options.
* Now, create a new recurring transaction that does not repeat and attach a file.
* Next, right-click that transaction and select "Enter next Occurence" which should move the transaction to the account.
* At this point, the first problem is that the transaction that was created for the account does not contain the file attachment from the recurring transaction entry.
* Now, create another recurring transaction.  Do not attach a file to this new entry.
* After it has been created, you'll see this new recurring transaction contains an attachment even though one was not specified.

This attachment here is the attachment from the first recurring transaction.  This is where the second problem exists.  The second recurring transaction might be something that does repeat, has nothing to do with the first entry but is linked to the file attachment from the previous entry.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows  (Win7 64-bit)
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x   (1.2.7)
  - [ ] 1.1 or older

**Comment by gabriele-v** [comment]
Regarding attachments copy on new transaction it's in this way by design, because there could be an attachment on recurring transaction that hasn't to be copied on normal transaction, also you will have lots of normal transaction with the same attachment.

Regarding attachments moved to newly created recurring transaction after execution, I know the problem and I'll fix it.

**Comment by tiker** [comment]
For the first item (moving the attachment over with the transaction part) I'm OK with that.  That's part of the unusual way I'm using this feature.  Perhaps an option to move the attachment with the final transaction if a limited number of recurrences were defined but that'll be for a different thread.

For now, the main issue was the attachment appearing in a new recurring entry which you've recognized so that's good.

Thanks.
