### ISSUE TITLE
Processor #3 at 100% 

### ISSUE THREAD

**Issue by dmbr0** [moneymanagerex/moneymanagerex#808]
MMEX uses 100% of 3rd processor. 

Linux version 3.19.0-32-generic (buildd@lgw01-43) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015

I get this error at startup: 

ASSERT INFO:
../src/generic/imaglist.cpp(66): assert "(bitmap.GetWidth() >= m_width && bitmap.GetHeight() == m_height) || (m_width == 0 && m_height == 0)" failed in Add(): invalid bitmap size in wxImageList: this might work on this platform but definitely won't under Windows.

BACKTRACE:
[1] wxGenericImageList::Add(wxBitmap const&)
[2] navtree_images_list()
[3] mmGUIFrame::createControls()
[4] mmGUIFrame::mmGUIFrame(mmGUIApp_, wxString const&, wxPoint const&, wxSize const&)
[5] OnInitImpl(mmGUIApp_)
[6] mmGUIApp::OnInit()
[7] wxEntry(int&, wchar_t**)
[8] main
[9] __libc_start_main
[10] _start

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

![screenshot at 2016-04-28 16 02 38](https://cloud.githubusercontent.com/assets/2502253/14899628/ed3ff614-0d5a-11e6-9aea-a3057d37d1bb.png)

**Comment by guanlisheng** [comment]
is it always on 100% ?

**Comment by dmbr0** [comment]
Yes. Right at startup and the whole time it is running.

**Comment by guanlisheng** [comment]
@vomikan would you mind to take a look for linux platform?

**Comment by vomikan** [comment]
I have no linuxed available anymore.

**Comment by BentleyJOakes** [comment]
On my machine (Arch Linux), mmex uses a normal amount of CPU process on startup and while viewing transactions.
Perhaps this high CPU usage was related to the crash dump process on the user's machine?
