### ISSUE TITLE
MMEX Windows keeps sending zombie network requests

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#811]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

Running MMEx on a network with a proxy/firewall results in startup taking ~15 seconds. For this reason, I've blocked MMEx at a Windows Firewall level. Unfortunately, now MMEx.exe keeps issuing network requests by the hundreds per second, clogging the firewall logs. What's worse, after closing the application, the process remains running, taking some ~20% processor time.
Something seems wrong with the part where it is using the network. 
The application should be fine with running without network access and should handle any issues there more gracefully.

**Comment by guanlisheng** [comment]
It would be fixed via v1.3.0 release after we switched to Google Analytics.
