### ISSUE TITLE
Assets Module - Version 1.3.0-Alpha (DB v.6)

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#824]
**OS:** Windows 10
**MMEX Version:** Version 1.3.0-Alpha (DB v.6)

I know the above release is the latest build and was not sure whether bugs must be posted here or not. The following were found while working with the Assets module:

1) When creating a new Asset from the top menu only the screen to setup the Asset account comes up, there is no option to set the appreciation/depreciation etc.. like when setting it up as per point (2),

2) In order to create a new Asset a user needs to click on the Asset field in the 'account tree' on the left and then click on 'New' in the Assets window on the right. When following these steps the New Asset window where you can set the initial value, depreciation and or appreciation etc.. appears as well as the screen to setup the account for the specific asset. This process is confusing, especially so for new users who will try to setup a new asset through the top menu's.
 
3) My logic tells me that when a new asset is created that it should have a zero balance i.e. create the asset first, then deposit/transfer the funds to the asset account which is then the same as actually buying the asset.
 
This works fine but when doing it this way the appreciation/depreciation does not work. If you create a new asset and backdate it with a couple of months, then go to the bank account and transfer funds to the assets, also with a back dated transaction, then the balance being reflected in the asset is exactly what was transferred/deposited. There is no appreciation and or depreciation.
 
If one however set an initial balance when the asset is created then the appreciation/dep. works.
 
4) The current balance of the asset window where all the assets are listed does not update when a deposit/withdrawal is made on an asset. If you click on the specific asset you can see the transactions that were made with the correct balances but this does not reflect on the assets main window under the current balance column. The balance is also not correctly updated on the Home Page.

As said, not sure whether I should post bugs of the latest build here or not. If not is there another site where this information could be shared with the developers?

**Comment by guanlisheng** [comment]
@stef145g would you mind to take a look here since you are on this area recently. thanks

**Comment by stef145g** [comment]
@RustyNomad Asset management has been expanded from the previous version. The creation of Asset accounts is an extension to Assets. **An Asset account maintains Asset Transactions**. The only way to create an Asset transaction is via the asset itself. The reason for this is that the accounts structure revolves around normal style accounts of whatever type they are.

**Old style Asset Management:**

- Selected Assets via the Navigation tree  or
- Selected Assets via the Tools menu.
- Create an asset in Asset Management window.

**Problems**: Cannot transfer money to normal accounts.

**New Style Asset Management:**

**Same as the old style with the following extensions**:
- Creation of transactions tied to the Asset which can be associated with any account.
- Creation of an Asset Account (Optional, but highly recommended)

**By the creation of an Asset account:**
- Asset transactions are kept together.
- Asset interaction with normal accounts is achieved by accessing the Asset Account and creating a normal transaction to any other account type.
- Navigation to the asset account is achieved by using Right-Click on the required Asset and selecting: "Open Asset Account''

**Benefits:**
- Allows an asset to hold many transactions
- Allows interaction to normal accounts such as transfers
- Asset Transactions can be treated as Income/expense or as transfers depending on the state of the "Transfer" check box.

**Comment by RustyNomad** [comment]
@stef145g Did quite a number of tests on the Asset module today and it works very well. I guess this issue can be closed.

**Comment by stef145g** [comment]
@RustyNomad Thanks for testing this feature, and now closing this issue.
