### ISSUE TITLE
"Today's Date" in reports does not respect user's date format

### ISSUE THREAD

**Issue by Twintop** [moneymanagerex/moneymanagerex#832]
For reports, "Today's Date" in the upper left is always formatted DD/MM/YYYY and does not respect a user's selected date format.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [X] 1.2.x
  - [ ] 1.1 or older

**Comment by guanlisheng** [comment]
Thank you for the feedback!

@vomikan would you mind to take a look

**Comment by vomikan** [comment]
It (htmlbuilder.cpp:116) should be 
~~~~~
    today_.todays_date = wxString::Format(_("Today's Date: %s"), mmGetDateForDisplay(today_.date));
~~~~~

**Comment by vomikan** [comment]
I'll fix it at next Monday.
