### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by mailagentrus** [moneymanagerex/moneymanagerex#834]
- Check OS
  - [x] Windows
  - [x] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Can we add CMake support to build Money Manager EX for Win, Mac, Linux. In this case:
- "build" folder can be dropped;
- User can manualy specify "wxwidgets" folder without using WXWIN Environment variables for windows (for example);
- Developers can add various compiler specific defines in one file;
- Developers can prepare MMEX backedend for migrating to Qt (for example).

**Comment by vomikan** [comment]
@dwrj87 is working on it
https://github.com/dwrj87/moneymanagerex/tree/cmake
