### ISSUE TITLE
web server

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#836]
The latest build (1.3.0 alpha) on Windows 10 x64 stop its execution due to an invalid certificate. Then I force to execute it, but the process stucks and does not start (it remains pending into the process list).
- Check OS
  - [X] Windows 10
-  Check MMEX version
  - [X] 1.3.x

Seems the problem if ip port 8080 (by default) is already used.

**Comment by vomikan** [comment]
Original bug here: https://sourceforge.net/p/moneymanagerex/bugs/886/

**Comment by DareDevil73** [comment]
Thank you, I'll wait for a solution.
Antonio

**Comment by DareDevil73** [comment]
Hi, I downloaded and installed the mmex_1.3.0-alpha_x64_portable_build240.zip, but it is not yet working. 

Same issue, it stucks!

I'll add the dump to SF ticket.

**Comment by DareDevil73** [comment]
Hi, the build 242 does not start as the previous releases.

Is it possibile to sign the executable with a development certificate in order to avoid the block by Windows 10?
