### ISSUE TITLE
[BUG/IMPROVEMENT] Decimal places in Stock Portfolio Module

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#839]
Just tested the Stock Portfolio in the latest build. Works perfectly for all my Bitcoin accounts but have one problem namely the number of decimal places allowed for the number of shares.

When entering the the number of shares (coins) purchased it rounds the value off to the 4th decimal. Bitcoins works up to the 8th decimal and this rounding leads to several inaccuracies in the balances especially after several smaller transactions. 

The 4th decimal in Bitcoin is at present worth US$0.06 so the stock value is essentially rounded to the nearest 6 cents each time.

If possible could this please be looked at in future versions. At present it works fine with me just entering a slight adjustment every month.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x ] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x ] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by stef145g** [comment]
@RustyNomad , @Zorg2409 helped me to test this implementation and suggested it would be good if the precision was made user definable. I originally set it to 6 digits, and found the display to be confusing, so the precision was reverted back to 4 digits.

I will investigate the possibility of add this feature, keeping the precision in reports as 4 digit, while the storage and calculations have a user definable precision.

**Comment by RustyNomad** [comment]
@stef145g Your solution should work just fine as it will resolve possible longer term rounding errors while still keeping reports nice and tidy.

**Comment by stef145g** [comment]
@RustyNomad, @zorg2409, I have now set the Shares Precision as an option with a default value of 4, but can be set between 2 and 10. This option is set in the database, so the option will need to be set for each database. You can download an updated version for Windows from [Appveyor](https://ci.appveyor.com/project/stef145g/moneymanagerex)

**Comment by stef145g** [comment]
Closing this issue as this should be fixed. Can be reopened if other issues are found.
