### ISSUE TITLE
{BUG] Stock Portfolio/Share Account/Bank Account - Multi currency problems

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#840]
There is a bug in the Stock Portfolio/Share Account section in regards to the conversion between different currencies.

To recreate:

1) Create a new database with say ZAR (South African Rand) as the base currency,
2) Create a new bank account (Bank1) with ZAR currency,
3) Create new Investment account (Gold1) with US$ as currency,
4) Select the Gold1 account and select 'New' to add new share,
5) Enter company name Test1, stock symbol GCM16.CMX, 20 shares at 1200, click 'Save'
6) Create the Share account (Test1) with currency set to US$, no initial balance,
7) In the 'Add Share Transaction' window select any Payee and category and click 'OK'
8) When done go to the Test1 share account under 'Share Accounts' - The transaction shows up in the account but **the amount is reflected in the base currency (ZAR) and not in US$ as selected when the account was created as in step 6,**
9) Share account has a negative balance which is correct as there was no initial balance,
10) Make a note of the balance amount, go to the bank account and make a transfer for that amount to the share account,
11) When you are busy doing the transfer you will see that it picks up that the Share Account is set to US$ and it shows the exchange rate etc.. which is correct as the Share Account was setup with US$ as the currency,
12) Go back to the Share Account, the transfer from the bank account shows but the amount is shown in US$, which is correct as the share account was setup in US$. So you now have two amounts on the same accounts, one expressed as US$ and the other as ZAR and MMEX is calculating the balance of the account based on the values as shown without any form of conversion resulting in an incorrect balance.

**Tried Solution:**
1) Repeated all steps but selected ZAR as the currency for each account,
2) On the screen where you enter the stock, the price seems to default to US$. If you enter the share price it shows the value lower down in the base currency.
3) When the share account is created, the base currency (ZAR) is selected,
4) In the transaction screen the value for the transaction is reflected in US$ and not in the base currency for the transaction as it should,
5) When you accept the transaction like this the balance reflected in the Share Account is the dollar value of the transaction instead of the converted ZAR base currency value as it should be.

So it seems like there are some currency conversion issue around the Share accounts.

Windows 10
MMEX 1.3.0-Alpha (DB v.6)

**Comment by stef145g** [comment]
Thanks for the detailed description as I have now replicated the problem.
I will report back when I have a solution for you to test.

**Comment by stef145g** [comment]
@RustyNomad, Thanks for the detailed description as I have now replicated the problem.
 I will report back when I have a solution for you to test.

**Comment by stef145g** [comment]
@RustyNomad, You can download an updated version for Windows from [AppVeyor](https://ci.appveyor.com/project/stef145g/moneymanagerex)
Please check it in case I have missed something.

**Comment by RustyNomad** [comment]
@stef145g Just did a quick test and seems to be working fine now. Will later this afternoon do a proper test with multi accounts/shares/currencies and post feedback.

**Comment by RustyNomad** [comment]
@stef145g Did some more testing and all seems to be fine now. Everything I tried seems to be working as it should. Did multiple stock purchases/sales including the relevant transfers from bank accounts (in various currencies) to and from the share account etc.. and all seems fine.

One problem I did notice though were in the reports. On the stock summary report the totals are not converted to the base currency. In my case all share accounts are in USD and base currency is in ZAR. The total on the report is just a total of the USD amounts but shown as being in ZAR. Other than that all seems to perfect.

While speaking about reports, is there any way to get hold of the standard reports i.e. the sql, template etc? I would like to use some of them as a basis from which to design other reports.

**Comment by stef145g** [comment]
@RustyNomad , I have readjusted the report in pr #851 
Now the report will display the currency of the portfolio. This means that the portfolio and subsequent share accounts should be in the same currency as is set up by default.

The the internal reports, use the standard database access methods, and sometimes goes beyond the scope of the SQL access used by the General Reports Manager. You may find this report in the [General Reports](https://github.com/moneymanagerex/general-reports) useful.

**Comment by RustyNomad** [comment]
@stef145g Thanks for the fix and the reports.
