### ISSUE TITLE
User agent refine 

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#842]
Since we are switching to GA officially soon while the user agent support is pretty limited
`User-Agent: Mac OS X (Darwin 15.5.0 x86_64)`

we may consider how to pass more proper information via this
http://www.useragentstring.com/

**Comment by slodki** [comment]
It's [implemented](https://github.com/moneymanagerex/moneymanagerex/pull/1432/files#diff-b7702a084eb00fb47f9800fd68271951R140) in `site_content()` function in #1432.

Now we should check all other places and switch to this function if needed.

**Comment by slodki** [comment]
Should be fixed with #1755
