### ISSUE TITLE
Expanded Assets section on Home screen, similar to Stocks

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#847]
Currently the Assets section on the home screen only shows the word 'Assets' as a link together with the balance in the base currency. It would be nice if it could be expanded similar to the Stocks section so that a person could see a list of the assets in the assets section.

In the Stocks section you have 2 columns namely 'Gains/Loss' and 'Total', in the Assets section it could be made to be 'Initial Balance' and 'Current Value'.

**EDIT:** Thought about this after my post. Initial balance might be of little use, Gains/Loss would be more appropriate in order to see how an asset appreciated and or depreciated. So the same headings could be used.

**Comment by stef145g** [comment]
While there are some similarities between Stocks and Assets, the home page should not display Stocks the same as Assets for the following reason.
1. The Assets heading is similar to a single Stock Portfolio in the Stocks section.
2. The Stocks section displays many Stock Portfolio's.

As a user may have a many assets, the Assets view is the place to list the actual asset accounts if an asset account is desired. Some assets may not need an account.

While the Assets view can have another column added to show a percentage gain loss, it may be more appropriate to display the "Change in Value" condition as Appreciates, Depreciates or None.
 **Current value is the calculated value based on the Condition and Rate**.
