### ISSUE TITLE
Belarus to have denomination, but the currency has old values

### ISSUE THREAD

**Issue by valsaven** [moneymanagerex/moneymanagerex#850]
Greetings! "Organize currency" update it to new values (BYR/USD for example), but in the program BYR still in thousands.

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.7
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
New Belarusian Ruble is BYN
Just add new currency BYN then check if currency exchange rates working.

**Comment by valsaven** [comment]
I see, thank you.
