### ISSUE TITLE
Currency update - Invalid value issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#853]
Bug.

![screenshot 108](https://cloud.githubusercontent.com/assets/6836805/16554727/469ba4bc-41d9-11e6-945e-d1a740a6cefe.jpg)

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
FYI
http://kx.cloudingenium.com/content-providers/how-to-obtain-stock-quotes-from-yahoo-finance-you-can-query-them-via-excel-too/

**Comment by guanlisheng** [comment]
fixed? @vomikan

**Comment by vomikan** [comment]
Yes
