### ISSUE TITLE
Download Stock Price history - mismatch to currency format

### ISSUE THREAD

**Issue by lakeuk** [moneymanagerex/moneymanagerex#856]
Add a UK stock (ie LLOY.L) as a price GBP £0.70, when you come to 'Download Stock Price history' from yahoo all the UK stock prices are provide in pence so our stock will show as 70p (pence price need converting to pounds)

Enhancement to have a setting to allow an multiple/divide adjustment to downloaded prices so they can align the currency. 
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by gabriele-v** [comment]
Unfortunately it's a Yahoo problem with specific stocks:
https://sourceforge.net/p/moneymanagerex/bugs/448/
https://sourceforge.net/p/moneymanagerex/bugs/729/

**Comment by lakeuk** [comment]
I wouldn't say it's a yahoo problem just as it's not a MMEx problem as such, GBp is a standard that all UK publications follow for reporting london stock exchange shares, it's often referred to in the UK as GBX (exchange quoted price) and yahoo follows this standard.  Are there any london stock exchange (.L) shares that yahoo reports in GBP as opposed GBp - I've not found any yet.

I see that the main stock panel has a workaround is in place to get the price correct on MMEx in moving the decimals based on the daily csv showing the GBp currency, while the history csv doesn't state the currency in the feed could a workaround also be applied to the 'Download Stock Price History' process, suggested conditions could be - If the stock ticker ends in '.L' it does a lookup to the daily csv and if it contains GBp then it applies the adjust to the history csv data feed in the same way as the current hack.

stockspanel.cpp -

        /* HACK FOR GBP
        http://sourceforge.net/p/moneymanagerex/bugs/414/
        http://sourceforge.net/p/moneymanagerex/bugs/360/
        1. If the share has GBp as currency, its downloaded value in pence
        2. If the share has another currency, we don't need to modify the price
        */

        if (updated && dPrice > 0)
        {
            if (stock_quote_currency == "GBp")
                dPrice = dPrice / 100;
            stocks_data[stock_symbol_with_suffix].first = dPrice;
            stocks_data[stock_symbol_with_suffix].second = sName;
            sError << wxString::Format(_("%s\t -> %s\n")
                , stock_symbol_with_suffix, wxString::Format("%0.4f", dPrice));
            count++;
        }

**Comment by gabriele-v** [comment]
Sorry, I thought it was related to actual value, not history.

I'll try find a workaround for it, maybe I could download a sample actual value just to check currency..

**Comment by slodki** [comment]
@vomikan please verify this while working on #1367

**Comment by vomikan** [comment]
It seems OK after this changes: https://github.com/moneymanagerex/moneymanagerex/pull/1435
https://finance.yahoo.com/chart/BP.L

![default](https://user-images.githubusercontent.com/6836805/36383165-6291e954-159c-11e8-9ca8-881858c433e7.JPG)

**Comment by vomikan** [comment]
OK lets investigate this issue more closed
```
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "quoteType": "EQUITY",
        "quoteSourceName": "Delayed Quote",
        "exchangeDataDelayedBy": 20,
        "exchange": "LSE",
        "market": "gb_market",
        "marketState": "REGULAR",
        "regularMarketPrice": 471.55,
        "regularMarketTime": 1519211521,
        "sourceInterval": 15,
        "exchangeTimezoneName": "Europe/London",
        "exchangeTimezoneShortName": "GMT",
        "gmtOffSetMilliseconds": 0,
        "esgPopulated": false,
        "tradeable": false,
        "fullExchangeName": "LSE",
        "symbol": "BP.L"
      }
    ],
    "error": null
  }
}

```

**Comment by vomikan** [comment]
```
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "quoteType": "EQUITY",
        "quoteSourceName": "Free Realtime Quote",
        "exchange": "MCX",
        "fullExchangeName": "MCX",
        "sourceInterval": 15,
        "exchangeTimezoneName": "Europe/Moscow",
        "exchangeTimezoneShortName": "MSK",
        "gmtOffSetMilliseconds": 10800000,
        "exchangeDataDelayedBy": 0,
        "regularMarketPrice": 272.84,
        "regularMarketTime": 1519212617,
        "market": "ru_market",
        "esgPopulated": false,
        "tradeable": false,
        "marketState": "REGULAR",
        "symbol": "SBER.ME"
      }
    ],
    "error": null
  }
}
```

**Comment by vomikan** [comment]
Got it.
https://query1.finance.yahoo.com/v7/finance/quote?symbols=BP.L&fields=regularMarketPrice;fields=ebitda,shortRatio,priceToSales,currency

```
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "quoteType": "EQUITY",
        "quoteSourceName": "Delayed Quote",
        "currency": "GBp",
        "fullExchangeName": "LSE",
        "sharesOutstanding": 19911200768,
        "marketState": "REGULAR",
        "market": "gb_market",
        "marketCap": 94050557952,
        "sourceInterval": 15,
        "exchangeTimezoneName": "Europe/London",
        "exchangeTimezoneShortName": "GMT",
        "gmtOffSetMilliseconds": 0,
        "exchangeDataDelayedBy": 20,
        "regularMarketTime": 1519212444,
        "esgPopulated": false,
        "tradeable": false,
        "revenue": 238432993000,
        "priceToSales": 0.39445278,
        "regularMarketPrice": 472.35,
        "exchange": "LSE",
        "symbol": "BP.L"
      }
    ],
    "error": null
  }
}
```

**Comment by vomikan** [comment]
https://query1.finance.yahoo.com/v8/finance/chart/BP.L?range=1mo&interval=1d&fields=currency

**Comment by slodki** [comment]
We should use official currencies is data structures inside MMEX only IMHO. Conversion to values user preferred values should be done by presentation layer.
