### ISSUE TITLE
Bakefile not handling platfdep.cpp correctly

### ISSUE THREAD

**Issue by omalleypat** [moneymanagerex/moneymanagerex#857]
The section of common.bkl where the platfdep.cpp is chosen is not working correctly.

```
<set var="PLATF_DIR">
            <if cond="TOOLSET=='win32'">win</if>
            <if cond="TOOLSET=='unix'">unix</if>
            <if cond="1">/mac</if>
        </set>

        <headers>$(fileList( [ 'src/*.h', 'src/reports/*.h', 'src/db/*.h', 'src/import_export/*.h', 'src/model/*.h' ] ))</headers>
<sources>$(fileList( [ 'src/*.cpp', 'src/reports/*.cpp', 'src/db/*.cpp', 'src/' + PLATF_DIR + '/*.cpp', 'src/import_export/*.cpp', 'src/model/*.cpp' ] ))</sources>

```

This evaluates to `unix` on mac.

mmex v1.3.0

**Comment by omalleypat** [comment]
```
        <set var="PLATF_DIR">
           <if cond="PLATFORM_MACOSX=='1'">mac</if>
        </set>
```
Results in no platfdef.cpp file in Makefile.

```
        <set var="PLATF_DIR">
           mac
        </set>
```
works fine

**Comment by omalleypat** [comment]
Workaround: after generating Makefile, run:
`sed -i '' 's|/src/unix|/src/mac|' Makefile`

**Comment by siena123** [comment]
Are we still using bakefile or have we moved to CMake? We were working on the change to CMake as I remember.

**Comment by omalleypat** [comment]
I think we're still on bakefile - the volunteer working on CMake made a
huge amount of progress on CMake but was unable to finish and I haven't had
the time to look at it myself.

>

**Comment by guanlisheng** [comment]
Yep that we are still on backfile

**Comment by siena123** [comment]
I will take a look at it and see if I can find something for you. I can come up with a way to do some initial testing but will need you to do some testing later.

**Comment by guanlisheng** [comment]
The Dockerfile under the root of github repo should be clear enough to build it from scratch

**Comment by siena123** [comment]
I only thing that I have been able to think of is to modify the bootstrap.sh to set an environment variable and then set the PLATF_DIR based on the environment variable but I don't have a way to test this for you as what I was trying to setup to do testing is not working for me at them moment.

`
dist=$(uname -s 2> /dev/null)
`
`
        <set var="PLATF_DIR">
            <if cond="TOOLSET=='win32'">win</if>
            <if cond="$(envvar('dist'))=='Darwin'">/mac</if>
            <if cond="TOOLSET=='unix'">unix</if>
        </set>
`
