### ISSUE TITLE
[BUG] Issue with transactions on bitcoin based account

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#866]
Unable to enter an initial balance (lower than 0) and or new transactions on an account set with bitcoin as the currency. To recreate:

a) Create new account (I selected current) and set currency to Bitcoin.
b) Enter a new deposit transaction, enter amount as say 0.0035555
c) Press tab after entering value and the value returns to 0.00

If you edit the account and set the initial value to 0.0035555 it does not change when you click OK but when you go to the account the balance shows as 0.00.

When entering an amount of 0.11 all works fine. However 0.011 gets rounded to 0.01 so there seems to be a problem on the rounding as bitcoin is set to 6 decimals in the settings (should be 8 for bitcoin but MMEx only allow for 6 decimal places).

Windows 10
MMEX 1.3.0-Beta

**Comment by stef145g** [comment]
@RustyNomad I assume that this has not worked for Bitcoin at all. You state that you set currency to Bitcoin. I also assume you have created this currency as an addition to the preloaded currencies.

Does Bitcoins belong only to Shares or do they belong to ordinary transactions as well?
Wondering if this is a bug or a new feature.

**Comment by RustyNomad** [comment]
@stef145g I guess the way in which Bitcoin is setup will depend on the user. Some buy into bitcoin as an investment and for that the shares work perfectly. Others might use Bitcoin just like any other currency so might setup a 'current' account with bitcoin as the currency and then use it just like any other bank account. In my case I use both as I have some bitcoin holdings for the longer term but I also have a normal account which I use like a bank account.

**Comment by stef145g** [comment]
@RustyNomad I was trying to determine which currency it was by the name and or currency symbol.
I ended up creating a currency called BitCoin (BIT) and setting the scale to 8 for this purpose.

I have modified the transaction dialog to accept my created bitcoin currency to allow precision settings up to 9 max. You can get the built files from here for testing: https://ci.appveyor.com/project/stef145g/moneymanagerex

This involves modifying the currency and set the scale to 8 (now max = 9), then using this currency in an account. The resulting transactions for that account will result with a precision of 8.
Please test before I submit it as a pull request in case there are any problems I have yet to encounter.

**Comment by RustyNomad** [comment]
@stef145g Tested and all seems to be working 100%.

The currency I used was Bitcoin BTC which is one of the preloaded currencies.

**Comment by stef145g** [comment]
@RustyNomad Could you test the latest code as I have updated the code.

I have also discovered that the discrepancy about the Bitcoin currency.
The currency BitCoin (BTC) is preloaded in 1.2.x but not in 1.3.x 
This will be fixed as a separate issue.

**Comment by RustyNomad** [comment]
@stef145g Just tested everything again on the latest build (281) and all seems to be perfect now. Thanks for the updates.

**Comment by stef145g** [comment]
Thanks for testing out this feature.
