### ISSUE TITLE
[BUG] Duplicate transaction not working anymore

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#867]
I used to be able to right click on any old transaction and select the 'Duplicate Transaction' from the menu, enter a new date and or value and then accept the transaction. This would create a new transaction with the new details without affecting the old transaction.

In the latest version no new transaction is created, the old transaction is edited with the new details. So instead of duplicating it, it only changes the exiting selected transaction. The Duplicate Transaction now does the same as Edit Transaction.

Windows 10
MMEX 1.3.0-Beta

**Comment by stef145g** [comment]
Thanks for reporting this as a fix has now been found. Fixed file available in Appveyor

**Comment by guanlisheng** [comment]
Will release another beta release to fix this issue
