### ISSUE TITLE
Add support to HiDPI (High Dots Per Inch) displays

### ISSUE THREAD

**Issue by rgaiacs** [moneymanagerex/moneymanagerex#878]

**Comment by guanlisheng** [comment]
what's the platform you are referring?

**Comment by rgaiacs** [comment]
> what's the platform you are referring?

GNU/Linux

**Comment by guanlisheng** [comment]
thanks. we are lack of Linux developer now and it will take more time

**Comment by guanlisheng** [comment]
based on https://www.wxwidgets.org/news/2016/02/wxwidgets-3.1.0-released/
i think wx3.1.0 should have resolved the HiDPI issue.

**Comment by vomikan** [comment]
related issue:
https://github.com/moneymanagerex/moneymanagerex/issues/478
