### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#883]
mmErrorDialogs::MessageError(m_choice_account_, _("Default account \"" + accountName + "\" for this template does not exist.\nPlease select a new account."),

**Comment by vomikan** [comment]
customReportMenu->Append(ID_GROUP, _("Rename Group"));

    mmDialogComboBoxAutocomplete dlg(this, _("Enter or choose name for the new group"),
        _("Rename group"), GroupName, Model_Report::instance().allGroupNames());

**Comment by guanlisheng** [comment]
pull request, please!

**Comment by vomikan** [comment]
a bit later I will

**Comment by vomikan** [comment]
{Model_Attachment::BANKACCOUNT, wxString(wxTRANSLATE("BankAccount"))},
    {Model_Attachment::BILLSDEPOSIT, wxString(wxTRANSLATE("RecurringTransaction"))},

**Comment by vomikan** [comment]
if (workbookElement->GetName() != _("Workbook") || workbookElement->GetAttribute("xmlns") != _("urn:schemas-microsoft-com:office:spreadsheet"))

**Comment by vomikan** [comment]
wxMessageBox(wxString::Format(_("%i occurrencies founded and replaced!"), (int)data.size())

**Comment by vomikan** [comment]
_("You have modified choiches: ones removed will be cleaned!") + "\n"
