### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#884]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows

-  Check MMEX version
  - [X] 1.3.x

In case if any account has >5k transactions the account view became slow.
I suggest this changes to avoid a sorting data every time before the account view.

~~~~~
--- a/src/db/DB_Table.h
+++ b/src/db/DB_Table.h
@@ -47,8 +47,10 @@ struct DB_Table
     DB_Table(): hit_(0), miss_(0), skip_(0) {};
     virtual ~DB_Table() {};
     wxString query_;
+    wxString order_by_ = "";
     size_t hit_, miss_, skip_;
     virtual wxString query() const { return this->query_; }
+    virtual wxString order_by() const { return this->order_by_; }
     virtual size_t num_columns() const = 0;
     virtual wxString name() const = 0;
 
@@ -116,8 +118,10 @@ const typename TABLE::Data_Set find_by(TABLE* table, wxSQLite3Database* db, bool
     typename TABLE::Data_Set result;
     try
     {
-        wxString query = table->query() + " WHERE ";
-        condition(query, op_and, args...);
+        wxString where = " WHERE ";
+        condition(where, op_and, args...);
+        const wxString query = table->query() + where + table->order_by();
+
         wxSQLite3Statement stmt = db->PrepareStatement(query);
         bind(stmt, 1, args...);
 
diff --git a/src/db/DB_Table_Checkingaccount_V1.h b/src/db/DB_Table_Checkingaccount_V1.h
index e620890..927780f 100644
--- a/src/db/DB_Table_Checkingaccount_V1.h
+++ b/src/db/DB_Table_Checkingaccount_V1.h
@@ -500,6 +500,7 @@ struct DB_Table_CHECKINGACCOUNT_V1 : public DB_Table
     DB_Table_CHECKINGACCOUNT_V1() : fake_(new Data())
     {
         query_ = "SELECT TRANSID, ACCOUNTID, TOACCOUNTID, PAYEEID, TRANSCODE, TRANSAMOUNT, STATUS, TRANSACTIONNUMBER, NOTES, CATEGID, SUBCATEGID, TRANSDATE, FOLLOWUPID, TOTRANSAMOUNT FROM CHECKINGACCOUNT_V1 ";
+        order_by_ = " ORDER BY TRANSDATE";
     }
 
     /** Create a new Data record and add to memory table (cache)*/
diff --git a/src/model/Model_Account.cpp b/src/model/Model_Account.cpp
index b680e7d..f585f64 100644
--- a/src/model/Model_Account.cpp
+++ b/src/model/Model_Account.cpp
@@ -174,8 +174,8 @@ const Model_Checking::Data_Set Model_Account::transaction(const Data*r)
 {
     auto trans = Model_Checking::instance().find_or(Model_Checking::ACCOUNTID(r->ACCOUNTID)
         , Model_Checking::TOACCOUNTID(r->ACCOUNTID));
-    std::sort(trans.begin(), trans.end());
-    std::stable_sort(trans.begin(), trans.end(), SorterByTRANSDATE());
 
     return trans;
 }

~~~~~

**Comment by guanlisheng** [comment]
Any proof that this is a bottleneck?

 
Thanks
Lisheng 

Sent from mobile

**Comment by vomikan** [comment]
timing in debug mode

**Comment by vomikan** [comment]
In any case.
When switching between accounts firstly started (Model_Account.cpp:177):
    std::sort(trans.begin(), trans.end());
    std::stable_sort(trans.begin(), trans.end(), SorterByTRANSDATE());
then secondly (mmcheckingpanel.cpp):
(147)    std::sort(this->m_trans.begin(), this->m_trans.end());
(178)        std::stable_sort(this->m_trans.begin(), this->m_trans.end(), SorterByTRANSDATE());

**Comment by vomikan** [comment]
Also if 
order_by_ = " ORDER BY TRANSDATE, TRANSID"
std::sort may be avoided

**Comment by vomikan** [comment]
![screenshot 88](https://cloud.githubusercontent.com/assets/6836805/18391526/e29c5c1e-76b6-11e6-9bb2-db0f7c081a37.jpg)
![screenshot 89](https://cloud.githubusercontent.com/assets/6836805/18391523/e28eeca0-76b6-11e6-8974-1013bf3fde35.jpg)
![screenshot 90](https://cloud.githubusercontent.com/assets/6836805/18391522/e28f1fb8-76b6-11e6-9adb-f6eeaf1eebec.jpg)
![screenshot 91](https://cloud.githubusercontent.com/assets/6836805/18391525/e2932fa4-76b6-11e6-8bdc-e5dde587235c.jpg)
![screenshot 92](https://cloud.githubusercontent.com/assets/6836805/18391524/e2915652-76b6-11e6-86ac-ebaf2b1fe878.jpg)

**Comment by guanlisheng** [comment]
The key is whether such sorter is bottleneck. Based on existing profiling result, it's NOT.

I'm closing this issue and feel free to reopen it with more proofs.
