### ISSUE TITLE
[FEATURE REQUEST] - Projects

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#896]
Add an option to mark transactions as belonging to the same project

For example: I buy from different sellers, different parts of a computer

On the left I can see in the "Projects" section all that I spent/earned by simply selecting that particular project

It should be Project:Subproject like it is for Category:Subcategory

**Comment by vomikan** [comment]
This feature is already there (v. 1.3.0)
![screenshot 30](https://cloud.githubusercontent.com/assets/6836805/18783967/9cfa0c2e-8197-11e6-80d7-1f5305aaa8e8.jpg)

**Comment by J316** [comment]
@vomikan That feature is not good because you can't customize view if you want to look transactions for a particular project and/or subproject. Please, add it in the main fields, searchable and able to customize reports for, not as a custom entry

**Comment by vomikan** [comment]
#1664

**Comment by slodki** [comment]
#1664 will not offer two-level hierarchy

**Comment by vomikan** [comment]
As the same way as categories no. But it msy be two string field used.

**Comment by slodki** [comment]
All hierarchy is about relations. To separate fields will require manual synchronization and selection of two values instead of one.

**Comment by luisdev** [comment]
How is the "Projects" concept that you refer to in this feature request different to the "Tags" concept (as used in Quicken)?

**Comment by vomikan** [comment]
There can be many tags, but only one project.
