### ISSUE TITLE
Choiches

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#903]
There are typos in the code
~~~~~
   const json::Array& jsonChoiches = jsonProperties[L"Choiches"];
    for (json::Array::const_iterator it = jsonChoiches.Begin(); it != jsonChoiches.End(); ++it)
    {
        const json::Object& obj = *it;
        Choiches.Add(wxString(json::String(obj[L"Choiche"])));
    }
~~~~~
Should we fix it before release or leave it as is?

**Comment by stef145g** [comment]
Best to fix it.

**Comment by vomikan** [comment]
I have no rights to restart appveyor task
https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/1.0.342-tsftbnku/job/m71vh6tj9mqt7u86

I wish to include that changes befor fix this issue

![screenshot 28](https://cloud.githubusercontent.com/assets/6836805/18742136/4c92d770-80bb-11e6-8dbf-640150c1ec66.jpg)
