### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#904]
I suggest to include mpress.219 files into cache

~~~~~
cache:
  - '%APPVEYOR_BUILD_FOLDER%\setup\win\mpress.219'
..........
- cmd: if not exist %APPVEYOR_BUILD_FOLDER%\setup\win\mpress.219\mpress.exe appveyor DownloadFile https://web.archive.org/web/20150506065200/http://www.matcode.com/mpress.219.zip && 7z x mpress.219.zip -o%APPVEYOR_BUILD_FOLDER%\setup\win\mpress.219
~~~~~

https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/1.0.342-crfucwrp/job/v1vlbvrfurjmijhk
![screenshot 30](https://cloud.githubusercontent.com/assets/6836805/18744752/eaebddde-80c7-11e6-99ab-740b456b308d.jpg)

**Comment by guanlisheng** [comment]
i think we can just have another try if there is networking issue.
