### ISSUE TITLE
Change a value for multiple transactions at the same time

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#909]
For example add the same note or the same number to multiple transactions at the same time

**Comment by Spoker** [comment]
I would also love this feature.
For me, the most important is to bulk select transactions and change the payee or category for all of them at once.

**Comment by Spoker** [comment]
Now that multiselect is possible in 1.3.0, are there any plans to implement this feature?
It would be great if it were possible to change payee, categorie, note, number, ... for a multi-selection.

**Comment by vomikan** [comment]
Yes

**Comment by vomikan** [comment]
What about this implementation?
![screenshot 351](https://cloud.githubusercontent.com/assets/6836805/21743185/21d11568-d50e-11e6-80ae-6491e3b8818c.jpg)

**Comment by Spoker** [comment]
This looks great!

**Comment by Spoker** [comment]
It would also be good if it is possible to change multiple transactions into a transfer. It would be usefull to manually adjust imports where transfers were registered as withdrawals.

**Comment by vomikan** [comment]
Just UI:
![screenshot 35](https://cloud.githubusercontent.com/assets/6836805/22473102/ab380bc6-e7e8-11e6-99d1-121ccd91a4e7.jpg)

**Comment by gjroelofs** [comment]
Given that 1.4 seems to be abandoned - will this be backported to 1.3?

**Comment by vomikan** [comment]
It will be backported.
