### ISSUE TITLE
Notes in split categories

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#910]
It would be very useful to add notes for each entry in split categories entries

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/feature-requests/340/

**Comment by guanlisheng** [comment]
hi @J316  we might consider this in v2.0.

**Comment by J316** [comment]
Would be awesome. Thanks

**Comment by anandasudarshan** [comment]
+1 very useful to have this

**Comment by whalley** [comment]
We can now add this feature due to the recent DB change.

Any proposals on how to add the notes to this?

Some suggestions:

- Another field under the Category/Amount?
- A button on the right that the user can press to add/edit notes, and can view when hovered over?
- any others?

<img width="502" alt="CleanShot 2022-09-30 at 13 34 54@2x" src="https://user-images.githubusercontent.com/487345/193270808-c2cd5153-899c-477d-b424-19e83c2391cd.png">

**Comment by tactilis** [comment]
> Any proposals on how to add the notes to this?

Thinking about it. Will produce a mock-up for dicussion.
 
 
 

Do you intend including this capability too?

![image](https://user-images.githubusercontent.com/4060092/193356495-fba96509-23cf-48be-a9dd-acc8908c43a1.png)

**Comment by whalley** [comment]
> Do you intend including this capability too?

I guess we could.

**Comment by tactilis** [comment]
First attempt, for discussion:

![image](https://user-images.githubusercontent.com/4060092/193450947-d5c27a8b-cd92-4b65-aa39-118c0eedbadf.png)

1. The Notes field is always shown next to the Amount field but greyed out for not active rows.

2. The initial (default) width of the dialog is such that you can see ~25 characters, probably enough for most short notes.

3. The width of the Notes field increases when the user increases the width of the dialog.

4. Clicking in a Notes field enables the note to be edited.

5. If the entered note is too long for the field, the text will scroll left/right as the enters/deletes characters or moves the text caret.

6. When the text caret is in a Notes field, the **[...]** button is displayed next to that row.

7. Clicking the  **[...]** button allows one of the frequently used notes to be selected and entered (similar to the functionality on the Edit Transaction dialog).

8. If a multi-line note is entered using the  **[...]** button (or by typing; see below) then all the lines of the note are displayed on one line as is done in the Notes column of the Transaction list. A one, two, and a three line note is shown on the dialog above.

Hovering the mouse cursor over a Note field displays a tooltip showing the entire note properly formatted. For example, the tooltip for the 3rd row above would be:
```
First line
Second
Third and final line
```

**Unresolved issue for discussion:**

How should the a user type a multi-line note?

Options (depending on what is possible in wx):

1. Allow Return to be typed (and stored) but _display_ it as a space.

2. Treat the Notes field as a one line high window into a multi-line field. Allow Return to be typed, which scrolls the line above out of view. Using the Up and Down arrow keys to move from one line to another.

3. When Return is typed, pop-up a small multi-line text dialog to enter the note. When OK is pressed, close the dialog and display the note as a single line as previously described.

-- 

Or we could prohibit multi-line notes for split transactions. Not sure this is desirable though.

**Comment by whalley** [comment]
> 3. The width of the Notes field increases when the user increases the width of the dialog.

We already have the category field increasing in size, not sure the controller we use can grow two columns? If we could, what would be the growth relationship between the two?

> 8. If a multi-line note is entered using the  **[...]** button (or by typing; see below) then all the lines of the note are displayed on one line as is done in the Notes column of the Transaction list. A one, two, and a three line note is shown on the dialog above.

It would then have to be saved as a single line note if edited as we have lost the original intent.

I was originally thinking about adding a button to bring up a simple notes dialog where the user can enter a frequently used note or edit note text. We can change the tooltip for the button to show any existing note or prompt the user to enter a note otherwise. Keeps the split transaction dialog simple albeit with an extra dialog to enter text if the user requires this, **we could extend this additional dialog if we support custom fields (a requested feature) for the splits in the future.**

![CleanShot 2022-10-03 at 00 30 03](https://user-images.githubusercontent.com/487345/193481136-b5af26a5-f16f-44f6-aeef-74e1830c70e3.png)

**Comment by luisdev** [comment]
> We can now add this feature due to the recent DB change.
> 
Does that mean that the CATEGORY TAGS feature can now also be implemented? 
(https://forum.moneymanagerex.org/viewtopic.php?t=10538)

**Comment by whalley** [comment]
> > We can now add this feature due to the recent DB change.
> 
> Does that mean that the CATEGORY TAGS feature can now also be implemented? (https://forum.moneymanagerex.org/viewtopic.php?t=10538)

Not yet, that will require more DB changes :-)

**Comment by whalley** [comment]
> @whalley If I did it, I would do it this way. 

Yes, I see it as the equivalent of the transaction dialog for a split - if that makes sense. The user can enter the basic info in the 'Split Transaction' view as we currently have, but for more information on each split (if they need it) they need to bring up another dialog to define the specifics - initially just notes.

**Comment by tactilis** [comment]
> for more information on each split (if they need it) they need to bring up another dialog to define the specifics - initially just notes

The downside of this is that you have to hover over each button in turn to see a tooltip just to know whether there are any notes. You can't just look at the dialog and see the notes.

This is why here https://github.com/moneymanagerex/moneymanagerex/issues/910#issuecomment-1264696906 I proposed something like this:

![image](https://user-images.githubusercontent.com/4060092/193684212-035f958a-8e4b-48dc-86c6-44efe0b0e828.png)

**Comment by tactilis** [comment]
>> 3. The width of the Notes field increases when the user increases the width of the dialog.

> We already have the category field increasing in size, not sure the controller we use can grow two columns? 

I'd set Category to a fixed width, so that at least all of the MMEX default category text can be seen, and have the Notes field expand.

> If we could, what would be the growth relationship between the two?

33% to the Category field and 67% to the Notes.

**Comment by whalley** [comment]
@tactilis You seem to be concentrating on the Notes field (which admittedly is the current problem), I want something that accommodates this and other attributes, we can't keep widening the dialog to accommodate all these. There have been calls to add other attributes the split, similar to a 'real' transaction - custom fields, colour, attachments, tags (future) to name a few. 

We can change the icon if there are any attributes behind it. E.g. initially start with ![image](https://user-images.githubusercontent.com/487345/193701538-71acb84b-49df-4e12-9ae5-03fd77572d08.png) to signify that the user can edit more attributes. Then perhaps change to ![image](https://user-images.githubusercontent.com/487345/193701696-5cbc9e3d-7acd-4d36-82ab-b5a953a6862b.png) if additional data is held.

We can summarise in the tooltip the additional information (currently notes).

**Comment by tactilis** [comment]
@whalley
> You seem to be concentrating on the Notes field

Indeed. That seemed to be the scope of what was being asked: _"Any proposals on how to add the notes to this?"_ and the scope of this issue.

Your suggestion: _"We can change the icon if there are any attributes behind it"_ looks good and would serve the wider aims.

**Comment by whalley** [comment]
> Indeed. That seemed to be the scope of what was being asked: _"Any proposals on how to add the notes to this?"_ and the scope of this issue.

I like to change the requirement on the fly and keep you on-your-toes :-)

**Comment by tactilis** [comment]
> I like to change the scope on the fly and keep you on-your-toes :-)

👍 

Keep iterating.
Keep polishing.
MMEX is getting better and better.
