### ISSUE TITLE
ERROR "An assertion failed" after compilation

### ISSUE THREAD

**Issue by Beast141** [moneymanagerex/moneymanagerex#917]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

After compilation and building on Ubuntu 14.04. Followed this guide: https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.Ubuntu.md

Then when i ran mmex, it throws an error just as in this image i uploaded:
https://postimg.org/image/sodp2awrp/

**Comment by Beast141** [comment]
Also, What is the procedure to update mmex?

**Comment by guanlisheng** [comment]
hi @Beast141 actually we are lacking of Linux developer though we are trying to provide our best here for linux platform.

**Comment by vomikan** [comment]
I think a problen in web_money.xpm and hourglass.xpm dimention.
It should be 48*48

**Comment by Beast141** [comment]
Sorry, i meant to tick version 1.2. The stable version is the one with this problem. not version 1.3

**Comment by vomikan** [comment]
To clone the stable version use the following command:
~~~~~
git clone --branch v1.2.7 github.com/moneymanagerex/moneymanagerex --recursive
~~~~~

**Comment by vomikan** [comment]
$ git clone will give you the whole repository.

After the clone, you can list the tags with $ git tag -l and then checkout a specific tag:

$ git checkout tags/<tag_name>

Even better, checkout and create a branch (otherwise you will be on a branch named after the revision number of tag):

$ git checkout tags/<tag_name> -b <branch_name>

**Comment by Beast141** [comment]
Thank you!! finally compiled and installed stable version on ubuntu 16.04!
If you can put this line in the documentation for compiling stable version for Ubuntu 16.04:
git clone --branch v1.2.7 https://github.com/moneymanagerex/moneymanagerex --recursive

then i followed by typing:
git submodule update --init
mkdir compile
./bootstrap.sh
cd compile
../configure && make
sudo make install

This is what i needed!.

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/wiki/Building%20mmex%20Debian%20%28Ubuntu%29%20Linux/

**Comment by vomikan** [comment]
Finaly it should be:
~~~~~
git clone --branch v1.2.7 https://github.com/moneymanagerex/moneymanagerex --recursive
cd moneymanagerex
./bootstrap.sh
mkdir build && cd build
../configure && make
sudo make install
~~~~~
