### ISSUE TITLE
Caracter display issues in 1.30RC1

### ISSUE THREAD

**Issue by rcocchiararo** [moneymanagerex/moneymanagerex#918]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

![127](https://cloud.githubusercontent.com/assets/437389/19021272/304d8714-8894-11e6-8202-e68c602e6a9d.JPG)
![130](https://cloud.githubusercontent.com/assets/437389/19021271/30511fdc-8894-11e6-9adb-9ecc646089d8.JPG)

I am new to MMEX, i decided to see how it looked, and in windows 10 pr x64 (fully updated) with the spanish language pack installed, i see the issues presented in the "130" screenshot.
It is not present in the 127 one (screenshot names related to MMEX version).

**Comment by guanlisheng** [comment]
thanks  @rcocchiararo for the info 
@vomikan would you mind to take a look at the help document encoding issues.

**Comment by vomikan** [comment]
![screenshot 50](https://cloud.githubusercontent.com/assets/6836805/19342656/5de2ae84-913b-11e6-90eb-5204f068bbef.jpg)
