### ISSUE TITLE
Today's Date field on Transaction Report does not follow date format setting

### ISSUE THREAD

**Issue by apillard** [moneymanagerex/moneymanagerex#920]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [X] 1.2.x
  - [ ] 1.1 or older

I'm running MMEX 1.2.7 on Windows 10.

When running the Transaction Report at the top of the report there is a field for Today's date. This field is formatted as DD/MM/YYYY even though my date format in the settings menu is set to MM/DD/YYYY. The dates for the actual transactions in the report appear as expected, it's just the Today's date that is backwards. Please see attached screenshot

![capture](https://cloud.githubusercontent.com/assets/6886875/19060786/9cb2c104-89b0-11e6-8e29-bcd51e08a6d2.PNG)
.

**Comment by vomikan** [comment]
It's OK for v 1.3.0
![screenshot 37](https://cloud.githubusercontent.com/assets/6836805/19078131/d12fddd4-8a57-11e6-8146-2e289a3cb427.jpg)
