### ISSUE TITLE
Investment fund error

### ISSUE THREAD

**Issue by rcocchiararo** [moneymanagerex/moneymanagerex#921]
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hi

I am still new and testen MMEX.
I noticed that the Actions/investment funds sections in 1.27 was kind of disconnected from the other accounts (i could not transfer/pay/receive from them). That is, as far as i could see, i am new to those things in real life too.

Then in 1.30RC1 i saw a new option to add purchaces of actions/something in the actions/investment funds section.

When you do, an account is then connected, but the ammounts in the the actual account are with 2 extra "ceroes".

Example:

Currency: ARS
Amount purchased: 3.560,4698
Price: 4,4938

That you take $16000 from the bank.
It is shown correctly in the investment account section, but then in the bank, it says you sent/spent "1600000".

**Comment by rcocchiararo** [comment]
After poking arround some more, i saw that the accounts that are created for the stock/investment/share stuff appear under "bank" in 1.27 and under the investment one in 1.30.

In both cases, i see a correct display outside, and a wrong one inside.

I leave some pics as an example.
![1](https://cloud.githubusercontent.com/assets/437389/19195759/37b602bc-8c89-11e6-9764-757801b3ddaf.png)

As you can see, it should "16000,04" under "cargo", but it shows "1.600.004,04".

My initial report was missing a 0.

**Comment by stef145g** [comment]
It appears that the translation from separator/decimal place[ (comma/dot) to (dot/comma) appears to be throwing errors. Needs further investigation....

**Comment by rcocchiararo** [comment]
Not trying to ask for ETAs or anything.

Is there any workarround for this while it is investigated ? i am comparing MMEX, and a few payed products, and that comparison is on hold while this is broken XD

**Comment by stef145g** [comment]
Edit the currency being used with separator/decimal place[ (comma/dot) and change it to (dot/comma).
This should fix it until we have time to fully investigate and find a solution to this problem.

**Comment by stef145g** [comment]
Fix found. See Pull Request #947
