### ISSUE TITLE
Performance killers 2

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#923]
For every  Reccuring Transaction at startup the app calculates an account balance.

```
bool Model_Billsdeposits::AllowTransaction(const Data& r)
{
    Model_Account::Data* account = Model_Account::instance().get(r.ACCOUNTID);
    double current_account_balance = Model_Account::balance(account); //speedup needed
```

**Comment by vomikan** [comment]
https://sourceforge.net/p/moneymanagerex/bugs/946/

**Comment by siena123** [comment]
Do to a new feature (account credit limit) being checked this is needs to be here unless we remove the notification / prompt about exceeding the account limit. The only other way to speed this up would be to handle the limit check and / or account balance in a different manor than is currently being done.

**Comment by vomikan** [comment]
Agree regarding different manor.
I suggesions to add global map <acc_id, balance>
In case if any translation added or deleted  the balance of the account will changed but not calculated from scratch.

**Comment by siena123** [comment]
I agree that have some global map of the account balance would speed up performance for the app in more that just this one place but that will be a major change and we should not hold up the release of 1.3 for it. If this is a problem for some we can do one item here that will help by doing the same thing on a smaller local scale.

**Comment by vomikan** [comment]
On the other hand now we have new option for account - reconcilation date.
It,s more import to lock old balance instead check current balance dynamically.
It may have negative feedback in case if used will enter real translation but the account balance became incorrect becouse previous transactions are incorrect.
