### ISSUE TITLE
Ubuntu 16.04 support ??

### ISSUE THREAD

**Issue by Beast141** [moneymanagerex/moneymanagerex#924]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

The ppa for Ubuntu 16.04 Xenial does not work.
The source code for the stable version of 1.2.7 which is i assume: moneymanagerex-1.2.7.tar.gz
i try and compile and build it but it throws error:
make: **\* No rule to make target '../lib/wxsqlite3/src/wxsqlite3.cpp', needed by 'wxsqlite_wxsqlite3.o'.  Stop.

I have already installed: libwxbase3.0-dev libwxgtk3.0-dev libwxgtk-webview3.0-dev and still gives that error.

Can someone update the documentation for how to build on Ubuntu 16.04  successfully?
https://github.com/moneymanagerex/moneymanagerex/blob/master/INSTALL.Ubuntu.md
is not working for me.
and there are no instructions on how to build from the tar.gz file.

Should we build from tar.gz file or from the zip file?   what are the differences?

**Comment by dwrj87** [comment]
Try going through the instructions again. The last time few times I remember people say they don't work, I created virtual machines, installed the operating systems and then went through the instructions and installed the PPAs. They all worked fine.

Quite simple, you're doing something wrong

**Comment by Beast141** [comment]
After adding the ppa to UBUNTU 16.04, and then do sudo apt-get update, there are no releases for xenial and it ends with errors.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/917
