### ISSUE TITLE
Migrate build system

### ISSUE THREAD

**Issue by dgmvecuador** [moneymanagerex/moneymanagerex#932]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [x] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Migrate from **Bakefile** to other build system, like **cmake** for example. this make easier to compile and maintenance.

Is there a reason for use **Bakefile**??

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/679
