### ISSUE TITLE
How to make portable version for Ubuntu 16.04?

### ISSUE THREAD

**Issue by Beast141** [moneymanagerex/moneymanagerex#933]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

I was wondering if its possible to convert existing compilation of version 1.2.7 to portable version?
Do we have to move the .db3 file which is under /home/USER/.mmex to another dir eg. in a USB?

And is it needed to backup the .db3 file or only the .mmb file?
Does the .db3 file contain config settings in mmex?

**Comment by vomikan** [comment]
On Unix (assume /media/disk is mounted USB flash drive)<br>
                Compile mmex from sources as usually,<br>
                and make install prefix=/media/disk<br>
                cp ~/.mmex/mmexini.db3 /media/disk/mmex/share/mmex<br>
                <br>
                or if you want to copy mmex which has already installed in
                /usr<br>
                cp /usr/bin/mmex /media/disk/mmex/bin<br>
                cp /usr/share/mmex /media/disk/mmex/share<br>
                cp /usr/share/doc/mmex /media/disk/mmex/share/doc<br>
                cp ~/.mmex/mmexini.db3 /media/disk/mmex/share/mmex<br>
