### ISSUE TITLE
lost of decimal number after update transaction

### ISSUE THREAD

**Issue by Gaet81** [moneymanagerex/moneymanagerex#937]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Hi,

I'm using the nightbuild of MMEX 1.3.0-RC.2 (DB v7)

I've imported a csv file, all has been perfectly imported into MMEX but when I'm changing the transaction it reset the decimal number to 00.

Note that number in my csv file have the format: 3.394,86
So to import it correctly I've temporarly change the windows number format to this:
![format number](https://cloud.githubusercontent.com/assets/22379937/19894203/0ecee82c-a044-11e6-833c-8d8884777ef0.png)

 relaunch MMEX then import.

If I'm not changing the transaction then the decimal stay
![keep decimal if untouch](https://cloud.githubusercontent.com/assets/22379937/19894573/64533950-a045-11e6-95c1-c338b33b970b.png)

I'v attached an exemple file.
Here is the import config:
![import config](https://cloud.githubusercontent.com/assets/22379937/19895277/07d2481c-a048-11e6-9501-21943bfec3a9.png)

 Import it and change for example the category, you will see the decimal number are restet to 0
[Test bug.zip](https://github.com/moneymanagerex/moneymanagerex/files/564365/Test.bug.zip)

.

However, if after the import I'm resseting back the number format (decimal and digit grouping) close MMEX and ropen it, the bug disapear...
The issue is that I need to change the number format because otherwise it will not import number with grouping separator.

Regards,

Gaet81

**Comment by vomikan** [comment]
You should set not OS currency parameters but an account currency that import into.
