### ISSUE TITLE
lib/lua submodule missing - Lua 5.2.4 not exist anymore

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#954]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

> Cloning into 'moneymanagerex'...
> remote: Counting objects: 33517, done.
> remote: Compressing objects: 100% (12/12), done.
> remote: Total 33517 (delta 0), reused 0 (delta 0), pack-reused 33504
> Receiving objects: 100% (33517/33517), 33.53 MiB | 2.04 MiB/s, done.
> Resolving deltas: 100% (27086/27086), done.
> Checking connectivity... done.
> Submodule '3rd/ChartNew.js' (https://github.com/FVANCOP/ChartNew.js) registered for path '3rd/ChartNew.js'
> Submodule '3rd/LuaGlue' (https://github.com/moneymanagerex/LuaGlue.git) registered for path '3rd/LuaGlue'
> Submodule '3rd/cajun' (https://github.com/moneymanagerex/cajun.git) registered for path '3rd/cajun'
> Submodule '3rd/cgitemplate' (https://github.com/moneymanagerex/html-template.git) registered for path '3rd/cgitemplate'
> Submodule '3rd/csv-parser' (https://github.com/moneymanagerex/csv-parser.git) registered for path '3rd/csv-parser'
> Submodule '3rd/ctpp' (https://github.com/moneymanagerex/ctpp.git) registered for path '3rd/ctpp'
> Submodule '3rd/mongoose' (https://github.com/cesanta/mongoose.git) registered for path '3rd/mongoose'
> Submodule '3rd/sorttable.js' (https://github.com/diepes/sorttable.js.git) registered for path '3rd/sorttable.js'
> Submodule '3rd/sqlcipher' (https://github.com/sqlcipher/sqlcipher.git) registered for path '3rd/sqlcipher'
> Submodule 'database' (https://github.com/moneymanagerex/database) registered for path 'database'
> Submodule 'lib/cppunit' (https://github.com/moneymanagerex/cppunit.git) registered for path 'lib/cppunit'
> Submodule 'lib/lua' (https://github.com/lua/lua) registered for path 'lib/lua'
> Submodule 'lib/wxsqlite3' (https://github.com/utelle/wxsqlite3.git) registered for path 'lib/wxsqlite3'
> Cloning into '/tmp/moneymanagerex/3rd/ChartNew.js'...
> Cloning into '/tmp/moneymanagerex/3rd/LuaGlue'...
> Cloning into '/tmp/moneymanagerex/3rd/cajun'...
> Cloning into '/tmp/moneymanagerex/3rd/cgitemplate'...
> Cloning into '/tmp/moneymanagerex/3rd/csv-parser'...
> Cloning into '/tmp/moneymanagerex/3rd/ctpp'...
> Cloning into '/tmp/moneymanagerex/3rd/mongoose'...
> Cloning into '/tmp/moneymanagerex/3rd/sorttable.js'...
> Cloning into '/tmp/moneymanagerex/3rd/sqlcipher'...
> Cloning into '/tmp/moneymanagerex/database'...
> Cloning into '/tmp/moneymanagerex/lib/cppunit'...
> Cloning into '/tmp/moneymanagerex/lib/lua'...
> Cloning into '/tmp/moneymanagerex/lib/wxsqlite3'...
> Submodule path '3rd/ChartNew.js': checked out 'b9e576fffa368873caed5c5dcdeb1de99637da5f'
> Submodule path '3rd/LuaGlue': checked out 'c51d11a247ee4d1e9817dfa2a8da8d9e2f97ae3b'
> Submodule path '3rd/cajun': checked out '36849008a90811fccb5356c11c757d50518cffbe'
> Submodule path '3rd/cgitemplate': checked out 'e43bec4c0e648a5311aaae4211834cdc085178a4'
> Submodule path '3rd/csv-parser': checked out 'ca3f0d7891238a5c3df7bdcd8be72846392114a4'
> Submodule path '3rd/ctpp': checked out '9f4dd0d742fea9e9bb0d346eabfe9a1981e486f9'
> Submodule path '3rd/mongoose': checked out '36a1927915f966f20486a80070f0428f2606a53a'
> Submodule path '3rd/sorttable.js': checked out '3c63cb04c8bf086ea0d85076fe5250a1fca595f3'
> Submodule path '3rd/sqlcipher': checked out '910fd70a3fdeeaa937e0d26940f924dbefe7ba77'
> Submodule path 'database': checked out 'eb805fe77342da8d7faf4828bbe4e58f66158821'
> Submodule path 'lib/cppunit': checked out 'fe55c81c8042d728fe726e49a7c821db199ee669'
> **error: no such remote ref 4fd8751bd02b0618b975504491e2221ced98c8d4
> Fetched in submodule path 'lib/lua', but it did not contain 4fd8751bd02b0618b975504491e2221ced98c8d4. Direct fetching of that commit failed.**

Lua release 5.2.4 (4fd8751 linked in #645) was removed from repo, so it's not accesible by git clone anymore.

**Comment by vomikan** [comment]
Please try 
git submoduled submodule update --init
Again

**Comment by Uskok** [comment]
Url path is wrong in .gitmodules. Correct is https://github.com/lua/lua.git
Second problem the structures is changes, there is no src folder anymore. This source could be new Lua 5.3. The file lua.hpp is missing. New Lua 5.3 has problem with LuaGlue.
I was manual unpack Lua 5.2.4 from www.lua.org and I am able to build mmex under Centos 7 with wx3.1. Congratulation of invested afford in project. It is very impressive.

**Comment by andjscott** [comment]
Will a new release be made as v1.3.0 is not able to be built from source?

**Comment by stef145g** [comment]
If you are using the GitHub repo, update to latest and the rebuild should be successful.
Prebuilt files are available from [AppVeyor build 390](https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/1.0.390) for Windows under PlatformXX - -> Artifacts

**Comment by andjscott** [comment]
I was updating mmex's [nixpkg](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/mmex/default.nix) which prefers a git tag as a revision. Using `rev = "d661518f5e04a54bfcb39201c44529d6413c6276";` can work in the meantime.

**Comment by stef145g** [comment]
@andjscott the git tag for v1.3.0 has been moved and can now be built from source.
Refer to [AppVeyor build 392](https://ci.appveyor.com/project/guanlisheng/moneymanagerex/build/1.0.392)
