### ISSUE TITLE
Automatic Database Backup

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#956]
Just trying the new 1.3.0 GA Portable and it appears that backups are not being made. My settings of take backup at start and keep 4 iterations appears to be ignored. Drop back to 1.2.7 and it works fine. Not done much research yet but what I have spotted is that mmframe.cpp in1.2.7 uses "BackupDatabase" whereas 1.3.0 uses "dbUpgrade:BackupDB" so I guess some re-writing/changes in this area.

Problem appears to be non-initialised variable "m_filename" passed to "dbUpgrade::BackupDB" at line 1737 in mmframe.cpp. Database not yet open so "m_filename" is not valid, I guess should use "fileName" which works for me.

https://sourceforge.net/p/moneymanagerex/bugs/968/

-  Check MMEX version
  - [x] 1.3.x

**Comment by stef145g** [comment]
Fixed with PR #960: automatic database backup on start-up
