### ISSUE TITLE
Invalid bitmap size in wxImageList assert fired

### ISSUE THREAD

**Issue by BentleyJOakes** [moneymanagerex/moneymanagerex#971]
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [X] Linux 
-  Check MMEX version
  - [X] 1.3.x

This assertion is seen in Issue #917 and #957 for Arch Linux systems.
I believe this is caused by the pie_chart_png.h file only having 12 pixels for the height, instead of 16 pixels as requested by the icon size.

**PROBLEM:**
Assertion is fired from wxWidgets 
`ASSERT INFO: ./src/generic/imaglist.cpp(66): assert "(bitmap.GetWidth() >= m_width && bitmap.GetHeight() == m_height) || (m_width == 0 && m_height == 0)" failed in Add(): invalid bitmap size in wxImageList: this might work on this platform but definitely won't under Windows.
[1] wxGenericImageList::Add(wxBitmap const&)

**INVESTIGATION:**
In moneymanagerex/src/images_list.cpp, add printf("Height: %d Width:%d\n", img.second.GetHeight(), img.second.GetWidth()); to line 170. The height for the pie chart entry in navtree_images() will be 12

**TEMPORARY FIX:**
Change line 113 in moneymanagerex/src/images_list.cpp to have png::BUDGET at the end.

**SUGGESTION:**
Have a check at line 170 to check that the icon height and width matches the required icon size. Otherwise, an empty or debug icon should be displayed.

**Comment by vomikan** [comment]
~~~~~
wxImageList* navtree_images_list()
{
    int x = Option::instance().IconSize();
    int y = 0;
    wxImageList* imageList = new wxImageList(x, x);
    for (const auto& img : navtree_images()) {
        imageList->Add(img.second);
        wxLogDebug("%i | Height: %d Width:%d\n",img.first, img.second.GetHeight(), img.second.GetWidth());
    }
    for (const auto& img : acc_images()) {
        imageList->Add(img.second);
        wxLogDebug("%i | Height: %d Width:%d\n", img.first, img.second.GetHeight(), img.second.GetWidth());
    }

    return imageList;
}
~~~~~
Output:
3 | Height: 12 Width:16
It's mean that png::PIE_CHART has incorrect size

**Comment by vomikan** [comment]
https://openclipart.org/detail/125071/pie-graph
