### ISSUE TITLE
Attempting to create an RPM package: need runtime dependencies and build dependencies

### ISSUE THREAD

**Issue by fusion809** [moneymanagerex/moneymanagerex#974]
Hi,

I am interested in creating an RPM package for Money Manager Ex for Fedora, and if possible (as I am not using these other operating systems myself) CentOS, Mageia, openSUSE, PCLinuxOS, _etc._ and to do this I am going to need a list of runtime dependencies and build dependencies for this package on Linux. Guessing based on your README that the following Fedora packages will need to be listed as runtime dependencies:

* [`mongoose`](https://apps.fedoraproject.org/packages/mongoose)
* [`wxsqlite3`](https://apps.fedoraproject.org/packages/wxsqlite3)
* [`wxGTK3`](https://apps.fedoraproject.org/packages/wxGTK3)

will I also have to create a `html-template` package for Fedora to satisfy this package's dependency? Plus will I need the C/C++ development headers for the aforementioned packages in order for this package to build properly? 

Thanks for your time,
Brenton

**Comment by stef145g** [comment]
@fusion809, The branch [cmake](https://github.com/moneymanagerex/moneymanagerex/tree/cmake) may have information that may assist you. This branch contains *cmake* build information but this work was not completed by the author.

**Comment by efDidymos** [comment]
Hi @fusion809 see https://github.com/moneymanagerex/moneymanagerex/issues/950#issuecomment-284143691

**Comment by tomasfrtala** [comment]
Currently done. You can find for [fedora](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.Fedora.md) [openSUSE](https://github.com/moneymanagerex/moneymanagerex/blob/master/doc/INSTALL.openSUSE.md) and lot of [others](https://github.com/moneymanagerex/moneymanagerex/tree/master/doc).
