### ISSUE TITLE
Slow displaying transactions in an Account

### ISSUE THREAD

**Issue by grumpy235** [moneymanagerex/moneymanagerex#980]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  
Noticable slow down when displaying transactions (6000+) in a Checking Account compared to 1.2.7
Compiling latest source on Win10 and VS2015 and running debug shows the following Hotpath
TransactionListCtrl::OnGetItemAttr 60%
wxDateTime::ResetTime 30%
wxDateTime::FormatISODate 30%

The following line in mmcheckingpanel.cpp appears to be the problem
1341 bool in_the_future = tran.TRANSDATE > wxDateTime::Today().FormatISODate();

Looks like a similar sort of problem to the one I reported in [http://forum.moneymanagerex.org/viewtopic.php?f=23&p=14569&sid=6fbc165bfa645ab2aa5c53aed48e0741#p14569] which was recently fixed.

Changing line 1341 to simply
     bool in_the_future = false;
and the problem goes away.

I guess more problems with evaluating wxDateTime::Today().FormatISODate() under latest Win10 - I assume it is evaluated everytime the line is executed ?

Whilst messing with this I set a breakpoint on 1341 and then stepped through the program, was somewhat surprised to see that the line was hit around 10 times for no apparent change in the data certainly the tran record was the same each time until we eventually moved on to another account record.

**Comment by grumpy235** [comment]
Nikolay,
Many thanks - instant display now.
This problem got me looking at User Colors in "View Options", is there any documentation on to use them? I could not find much in the Help file.

**Comment by vomikan** [comment]
In an account panel if Ctrl+1....Ctrl+7 have pressed the selected transaction will marked by specified color. Ctrl+0 is for reset.

**Comment by vomikan** [comment]
In an account panel if Ctrl+1....Ctrl+7 have pressed the selected transaction will marked by specified color. Ctrl+0 is for reset.
