### ISSUE TITLE
Bug at depreciation of assets

### ISSUE THREAD

**Issue by thainanfrota** [moneymanagerex/moneymanagerex#988]
Hello!

I think I have a problem with a depreciation of assets, and if this is not the place to post this question, I apologize.

I created a asset with value 100,000.00, with depreciation rate of 10% per year and start data on 2017/01/03 (and today is 2017/01/04).

1) If I define the appreciation / depreciation method as APPRECIATION, MMEX behaves correctly, ie:

((10/100 + 1) ^ (1/365)) * 100000 = 100,026.12

2) But if I change to depreciation, it displays 99,971.14 instead of 99,973.88

My question is: how do I get the calculation that MMEX uses in depreciation?

(Sorry for my bad english, i'm brazillian)

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
One year contains 365 days. But 4 year contains 364*4+1.

**Comment by thainanfrota** [comment]
But the difference is 1 day.

**Comment by thainanfrota** [comment]
Guys, 

I was wrong. I have already found how MMEX calculates depreciation.

((10/100 - 1) ^ (1/365)) * 100000 = -99971,14 (Exactly what MMEX is displaying)

I will close this thread.

Sorry for any inconvenience.
