### ISSUE TITLE
mmex Error

### ISSUE THREAD

**Issue by Dialga** [moneymanagerex/moneymanagerex#996]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ ] Windows
  - [ ] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older
![mmex-screenshot_2017-01-08_10-33-57](https://cloud.githubusercontent.com/assets/5157928/21745327/0aba879e-d58e-11e6-860d-80665294d51a.png)

I just upgraded to moneymanagerex-1.3.1 and my database fails to open due to this error:

REPORT_V1: Exception SQL logic error or missing database[1]: no such column: TEMPLATECONTENT

**Comment by vomikan** [comment]
Could you please provide more details.
- OS
- from what version you have upgraded

**Comment by Dialga** [comment]
On Arch Linux, from version 1.2.7

**Comment by vomikan** [comment]
It's a bit strange. The table REPORT_V1 already contains the field TEMPLATECONTENT in v.1.2.7

**Comment by Dialga** [comment]
I just opened my database in sqlite3 and the report_v1 table is as follows:
`CREATE TABLE REPORT_V1(REPORTID integer not null primary key, REPORTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE, STATUS TEXT COLLATE NOCASE NOT NULL, GROUPNAME TEXT COLLATE NOCASE, SQLCONTENT TEXT, LUACONTENT TEXT, TEMPLATEPATH TEXT);`

**Comment by Dialga** [comment]
I just tried exactly that and my database still fails to open, so I've reverted.
